### ISSUE TITLE
Event forwarding through Shadow DOM polyfill does not unwrap event.target

### ISSUE THREAD

**Issue by Caffeinix** [Polymer/polymer#1001]
If you attach this event handler in a browser where Shadow DOM is polyfilled:

~~~javascript
window.addEventListener('resize', function(evt) {
  console.log(evt.target === window);
});
~~~
you will discover that the output is `false`.  The reason is that `evt.target` is actually `Object { __impl4cf1e782hg__: window }` or similar.  

This seems like a very specific problem, except that this code is almost precisely what exists in emscripten's library_html5.js, and is called when attaching resize events to the window from within C++ code.  This issue therefore renders Polymer inherently incompatible with the event handling code in emscripten.

This could be fixed by unwrapping the event target before forwarding the event, though that could conceivably break existing code.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
