### ISSUE TITLE
Compatibility with mod_pagespeed

### ISSUE THREAD

**Issue by shield-9** [Polymer/polymer#1002]
It seems polymer is NOT compatible with mod_pagespeed (or its specific configurations).

e.g. https://github.com/Polymer/polymer-tutorial/blob/master/step-1/index.html is displayed like:
![unquote](https://cloud.githubusercontent.com/assets/3660715/5329996/12529a44-7e12-11e4-9c64-dc66f02aa394.png)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
