### ISSUE TITLE
core-animated-pages' and paper-tabs' selected attribute collide

### ISSUE THREAD

**Issue by AndreasGalster** [Polymer/polymer#1009]
When you have paper-tabs in a core-animated pages and you set the core-animated-pages to selected="0", paper-tabs with selected="0" doesn't work properly. It doesn't recognize that the tab is selected. Adding no selected="0" to paper-tabs and writing it in the DOM after launch selects the tab as expected. 

Unfortunately however you can't set the property "selected" either with jquery or navtive methods. I've read a discussion stating this is desired apparently. Anyway, the issue above is a bug, isn't it? Any suggestions or workarounds?

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
