### ISSUE TITLE
Dropdown menu not working

### ISSUE THREAD

**Issue by fredpedro** [Polymer/polymer#1010]
I tried following the instructions posted in the polymer website on how to create a dropdown menu. But when i tried to run the page, the drop down is not showing. I even downloaded the code of the demo, but doesn't work. Note, that I have installed all the components that is necessary for that feature. When I use Developer tools to see where it is located, I see that it is located at the upper left corner and the size is the 0x0.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
