### ISSUE TITLE
Consistency between element classes, attributes and variables.

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#1011]
This drives me nuts haha :p Who do I need to convince here that the mix between attributes and classes could be made a bit more consistent. Someone should sit down, make a list of all attributes and classes and make sure everybody is doing it the same way. Will this break everything? Yes but call it 0.6 i don't care, it should be ironed out. Restrict it to one way only, don't care which way just make it one way :)

https://www.polymer-project.org/docs/elements/core-elements.html#core-header-panel

```html
<core-header-panel>
  <div class="core-header">standard</div>
  <div class="content" fit>content fits 100% below the header</div>
</core-header-panel>
```
https://www.polymer-project.org/docs/elements/core-elements.html#core-toolbar

```html
<core-toolbar class="tall">
  <div id="progressBar" class="bottom fit"></div>
</core-toolbar>
```
https://www.polymer-project.org/docs/elements/core-elements.html#core-scroll-header-panel

```html
<core-scroll-header-panel>
  <core-toolbar>Header</core-toolbar>
  <div>Content goes here...</div>
</core-scroll-header-panel>
```
https://www.polymer-project.org/docs/elements/core-elements.html#core-drawer-panel

```html
<core-drawer-panel rightDrawer>
  <div drawer> Drawer panel... </div>
  <div main> Main panel... </div>
</core-drawer-panel>
```

Many more examples, just want to make a point.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
