### ISSUE TITLE
Arguments to changed handlers are reversed from observe.js

### ISSUE THREAD

**Issue by chiefcll** [Polymer/polymer#1016]
When using the changed handlers for Polymer we do:

betterChanged: function(oldValue, newValue) {
        ...
},

using observe.js directly its

var obj = { foo: { bar: 'baz' } };
var observer = new PathObserver(obj, 'foo.bar');
observer.open(function(newValue, oldValue) {
  // respond to obj.foo.bar having changed value.
});

Can we make these consistent?

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
