### ISSUE TITLE
Ability to observe objects in a array.

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#1018]
https://www.polymer-project.org/docs/polymer/polymer.html

Can you observe a array too please?

```html
Polymer('x-element', {
  observe: {
    'a[ ].c': 'validateSubPath'
  },
  ready: function() {
    this.a = [{c: 'exists'}];
  },
  validateSubPath: function(oldValue, newValue) {
    var value = Path.get('a[ ].c').getValueFrom(this);
  }
});
```

(http://stackoverflow.com/questions/27408560/how-to-bind-items-sum-outside-a-template-repeat)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
