### ISSUE TITLE
polymer elment encoding with gbk 

### ISSUE THREAD

**Issue by superstarwulin** [Polymer/polymer#1019]
a.htm  import ==>b.htm,all encoding with gbk because of the runtime context.

the page a.htm come out messy code in the custom element area ，as follows：

![image](https://cloud.githubusercontent.com/assets/4719920/5391017/e3661f6c-814f-11e4-947e-0c410c883068.png)

how to sovle it ?

do polymer has some config of encoding?

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
