### ISSUE TITLE
Polymer throws Error on load in Chrome 39.0.2171.71 (64-bit)

### ISSUE THREAD

**Issue by tinco** [Polymer/polymer#1020]
Hi, I'm using Chrome on Linux (Ubuntu)

Polymer throws an error while booting, it's that the property 'flags' is missing on the CustomElements object. I've investigated a little bit and it seems CustomElement is getting defined in /src/system/compat.js, I tried adding the property there, but then Polymer crashed somewhere else, so I think there's a bigger problem going on.

Are other people on Chrome experiencing this? I think this would be a too big issue to have such a blatant problem, am I doing something wrong?

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
