### ISSUE TITLE
webcomponents.js errors on Safari 5.1.7 Cannot declare a parameter textContent in strict mode.

### ISSUE THREAD

**Issue by Will-in-BC** [Polymer/polymer#1024]
OK please ignore my issue. This was completely my ignorance as I had not realized Apple had discontinued support for Safari on Windows. It has been years since I used Safari and I just wanted to test my app and thought I had the latest release (well I did for Windows).  

Hi,

I have a Polymer app (uses 0.5.1 of Polymer) that works fine in Chrome. When I attempt to test the application in Safari (5.1.7) I receive the above error. I believe this occurs before Polymer ready is fired. Here is a screen shot of the error. You can access the application at the url in the screen shot. 

ps the error is not received in IE11.

![image](https://cloud.githubusercontent.com/assets/9541036/5426149/5d8df346-82f4-11e4-831d-968008128981.png)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
