### ISSUE TITLE
polymer-ready not working

### ISSUE THREAD

**Issue by Cloudswalker** [Polymer/polymer#1025]
Greatings. This editor "eats" code examples - so I deleted all "<" symbols in start of each line.

!DOCTYPE html>
html lang="en">
	head>
		meta charset="utf-8">
		meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		meta name="viewport" content="width=device-width, initial-scale=1.0">
		meta name="mobile-web-app-capable" content="yes">
		meta name="apple-mobile-web-app-capable" content="yes">
		script src="bower_components/webcomponentsjs/webcomponents.js">/script>	
		link rel="import" href="bower_components/polymer/polymer.html">
	/head>
body fullbleed layout vertical>
p id="ma">Html /p>
	script>	
		document.addEventListener('polymer-ready', function() 
		{
				document.getElementById('ma').innerHTML = "JavaScript";
		};
	/script>	
/body>
/html>

If I change 
"document.addEventListener('polymer-ready', function()"
to
"window.onload = function()"

All is working.

my email is tutkay@gmail.com .Please send me feedback.

Reagrds, Bohdan K.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
