### ISSUE TITLE
Core-selector didn't display selected item properly after some operations on "selected" array.

### ISSUE THREAD

**Issue by lisfe** [Polymer/polymer#1026]
I set "valueattr" to some attribute and there are six elements (a, b, c, d, e, f) in the core-selector.
At beginning, selected is [ 'e', 'c' ] and core-selector displayed properly. 
But after following operations, c element is not selected.
1 remove e,c
2 add a, b, c, d, e, f

I traced the code and found polymer will generate two splices for core-selector:
1 [ index:0, addedCount:4 ]
2 [ index:5 addedCount:1,  removed: ['c'] ]

and core-selector will set c from true to true and to false.

Maybe we need to check whether there are any repeated elements in the splices before directly set element to true or false.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
