### ISSUE TITLE
paper attribute like a layout attribute

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#1029]
When I first look at this

https://www.polymer-project.org/docs/elements/core-elements.html#core-menu-button

```html
<core-menu-button>
    <core-icon-button icon="menu"></core-icon-button>
    <core-dropdown class="dropdown" layered>
        <core-menu>
            <core-item>Share</core-item>
            <core-item>Settings</core-item>
            <core-item>Help</core-item>
        </core-menu>
    </core-dropdown>
</core-menu-button>
```

And then look at this

https://www.polymer-project.org/docs/elements/paper-elements.html#paper-menu-button

```html
<paper-menu-button>
    <paper-icon-button icon="menu" noink></paper-icon-button>
    <paper-dropdown class="dropdown">
        <core-menu class="menu">
            <paper-item>Share</paper-item>
            <paper-item>Settings</paper-item>
            <paper-item>Help</paper-item>
        </core-menu>
    </paper-dropdown>
</paper-menu-button>
```

I have this `deja vu` feeling :)

I think having two sets of elements like this especially when you have core things inside a paper element it should be made in just one element.

What about a paper attribute that would look like this

```html
<core-menu-button paper>
    <core-icon-button icon="menu" noink></core-icon-button>
    <core-dropdown class="dropdown" layered>
        <core-menu paper class="menu">
            <core-item>Share</core-item>
            <core-item>Settings</core-item>
            <core-item>Help</core-item>
        </core-menu>
    </core-dropdown>
</core-menu-button>
```

Think of it this way, building a puzzle is fun until you have too many pieces :) If core and paper elements look so similar it should be one element instead of 2.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
