### ISSUE TITLE
Value binding on <input type="date"> becomes invalid on day rollover

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#103]
Test: http://jsfiddle.net/fC3H9/4/

Using Chrome, increment the day until it rolls over. Something in the data binding
layer causes the input to be invalid when the day rolls over.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) release of Polymer - please feel free to re-open if this is incorrect.
