### ISSUE TITLE
remove components/polymer/polymer.html on the main page.

### ISSUE THREAD

**Issue by Pomax** [Polymer/polymer#1031]
From the view-source on the polymer-platform.org main page:
```
<!-- TODO: remove when https://github.com/Polymer/polymer/issues/391 is fixed -->
<link rel="import" href="/components/polymer/polymer.html">
```
That issue is marked as closed now =)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
