### ISSUE TITLE
A type with that name is already registered

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#1032]
My idea is to offer some set of Polymer-based web components on page, but if some web-components were already declared somewhere - redefine previous declaration after (and be able to extend previous version). This will allow to make general HTML markup with web-components and redefine necessary components to make customizations.
Here is demo: http://jsfiddle.net/hoxrjzgk/
I'm getting
> Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'test-element'. A type with that name is already registered.

Even though I didn't execute `Polymer(...)` on that component, and component do not have `noscript` attribute.
What is even worse - I can't catch that exception to suppress and/or process somehow.

Perfect way for me would be:
```html
<polymer-element name="test-element">
    <template>
        Some long text
    </template>
    <script>Polymer('test-element');</script>
</polymer-element>
<polymer-element name="test-element" extends="test-element" replace>
    <template>
        Some long text
    </template>
    <script>Polymer('test-element');</script>
</polymer-element>
```
`replace` would stand for replacing previous declaration, when not present - declaration ignored if there was one with the same name already.

Seems to be related to #357

**Comment by nazar-pc** [comment]
Patch commit against master: https://github.com/nazar-pc/polymer/commit/cc2595f6247661146901dd4354a1a9870aa61494
Not sure how to make patch against 0.8-preview, it seems that main work is happening there, because it differs too much and I don't see support for `<polymer-element>` (will there be any in future?).

**Comment by Nevraeka** [comment]
@nazar-pc As per @ebidel - you are referring to browser behavior. An element cannot extend to overwrite itself or otherwise (as per the spec). This is not a Polymer issue but more a disagreement with the official spec used to implement custom elements in the browsers. 

The reason we should not do hacks like `replace` is to avoid overwriting native elements and browsers the security & trust that these elements are what we say they are. By that point, granting them first class citizenship in the browser.

**Comment by nazar-pc** [comment]
@Nevraeka, Polymer already includes a bunch of usefull features, that in fact extends default behavior of custom elements.
Since we declare Polymer element, not raw custom element, we can tweak it to extent that I propose.

If you look at patch I wrote, example how to use it and my intension - you'll understand how usefull it can be in real life. It does nothing with Web Components specs, under the hood it works by general rules.

This is not a bug report, this is a feature request with reference implementation. It is very difficult to maintain patched version, so I'm proposing ideas that I think might be useful for lots of others to upstream.

**Comment by Nevraeka** [comment]
@nazar-pc I see what you are trying to get from a feature like this but I'm not sure if it is 'good' idea to add this IMO. While I think there is merit & usefulness to the idea of 'replace' I feel creating temporary extends values is probably not the answer. 

Rather than having the concept of 'replace', why not use a compositional technique with more lightweight HTML. I would want Polymer to create temporary attributes and conditional checks for each element in this case. I would much rather see an error if this occurs so I can figure out where I have registered my element again. I think of `document.registerElement` as an secure initializer as the page is loading. If I can hack that up my trust with it lessens. Just my thoughts on it. Not saying its not a valid case, I just think it's not in line with the Polymer philosophies.

**Comment by nazar-pc** [comment]
> Rather than having the concept of 'replace', why not use a compositional technique with more lightweight HTML.

@Nevraeka, what do you mean under this phrase? I didn't found any good alternatives. The point is that someone already made polymer component and you need to customize it in some simple way while not touching its usage. Probably, someone will need to modify yours modified version too.

Initially I wanted to implement this as plugin for Polymer, but it is not currently possible.

**Comment by Nevraeka** [comment]
What I mean by that is that we, as a community, tend to have large monolithic UI components. By creating smaller components that we can easily nest into other components via template content we get a versatile and easily composed design structure. I know when dealing with others code this can be difficult, if not impossible, but smaller components eliminate the need for something like 'replace'. As for `extends`, I have found is rarely good for anything UI focused except form elements. It is good however for elements like `core-xhr`, etc. 

If an element has the same name - don't use it or write a new component with modified (and attributed credits) of the authors component code as your starting point (most elements I have seen are not proprietary if they are publicly available). Polymer should be a lightweight library of "syntactic sugar", not the next Angular IMO. @ebidel - what are your thoughts?

**Comment by nazar-pc** [comment]
I do have small nested components in my CMF, these small components are used to build whole pages. There pages are separate stand-alone modules (plugins in WP terminology). And I as developer want to create module, that works as it is out of the box from one point of view, from another I want to offer an ability to customize appearance to any extent possible in current web. Usually view customization is done via templates, but I want to completely eliminate templates usage in traditional meaning, using polymer elements customization instead.

For example, content of page built with such approach looks like:
```html
<section data-id="1" data-in_stock="25" data-price="20" data-soon="0" is="cs-shop-item">
	<div id="images">
		<img alt="" src="http://cscms.org/storage/public/Plupload/2015-01-03/18/2_031854a812c6b264b.jpg">
		<img alt="" src="http://cscms.org/storage/public/Plupload/2015-01-03/18/2_035654a812ec26d24.jpg">
		<img alt="" src="http://cscms.org/storage/public/Plupload/2015-01-03/18/2_035654a812ec1c834.jpg">
	</div>
	<div id="videos">
		<a href="https://www.youtube.com/watch?v=bmtbg5b7_Aw">&nbsp;</a>
		<a href="https://www.youtube.com/watch?v=rHBxJCq99jA">&nbsp;</a>
		<a href="http://dailymotion.com/embed/video/xxgmlg?autoplay=1">
			<img alt="" src="http://cscms.org/storage/public/Plupload/2015-01-03/18/2_114354a814bf1b101.jpg">
		</a>
	</div>
	<h1>Minions</h1>
	<div id="description">
		<p>And here are some images with nice minions</p>
		<p>And here are some images with nice minions</p>
		<p>And here are some images with nice minions</p>
		<p>And here are some images with nice minions</p>
		<p>And here are some images with nice minions</p>
		<p>And here are some images with nice minions</p>
		<p>And here are some images with nice minions</p>
		<p>And here are some images with nice minions</p>
		<p>And here are some images with nice minions</p>
		<p>And here are some images with nice minions</p>
		<p>And here are some images with nice minions</p>
	</div>
	<div id="attributes">
		<table>
			<tr>
				<td>Size</td>
				<td>2</td>
			</tr>
		</table>
	</div>
</section>
```
This is pretty abstract, but well structured, simple and semantic HTML that will be easily crawled by any search engine, even such that knows nothing about custom elements and all the stuff.
This HTML will be transformed to nice page with slide-show including both videos of different types and images, there will be button to add this item to shopping cart and so on.
From another side with my patch this gives you, as web-site developer flexibility to transform this page to literally anything in your particular project and even add functionality that was not present initially (also, everything have public API, so it is possible to load necessary data if it was not present in original HTML).

**Comment by pertrai1** [comment]
@Nevraeka @ebidel @nazar-pc - I believe that the UI components should be held behind a facade where the components are small and are an extension of Polymer. The use of an element that shares a name should be no different than only one id semantically. When the syntax is tokenized I have the feeling that it would be non intuitive as to what the parser should do with components that have the same name and/or `extend` from another component. If this is already being done then I am showing off my ignorance. I feel that explaining it from my point of view is easier in conversation if my point is not well understood.

I do see pros and cons about this and would want to see more use cases before I could see the benefit from doing this. This is my opinion.

**Comment by nazar-pc** [comment]
Since 1.0 was released I want to ask what can be done regarding this question now, this is not really version-specific issue.

A brief repeat of what I want to achieve and how it works now:
* there is CMF where most of things are done as Polymer elements (currently using 0.5)
* if we take for instance Blogs module - it contains elements for post (`cs-blogs-post`), posts list and so on
* user can install Blogs module with standard UI
* user can create/install module with customized `cs-blogs-post` to change appearance and/or functionality entirely without any need to edit Blogs module itself at all

Currently this is achieved with patched Polymer 0.5.
I wanted to migrate to 1.0 and possibly create similar patch, but there is no possibility to extend custom elements yet.
There is a statement that most of inheritance-like features can be done in 1.0 with behaviors and composition, but I do not really see any good solution with styles resolution regarding this case, extending elements using the same name was simple and reliable solution that works fine, it doesn't confuse or overcomplicates anything once you know what is that.

**Comment by Nevraeka** [comment]
@nazar-pc You should do a PR for 1.0 referencing this issue so the team can review the changes.  I still feel the same on the subject due to standards compliance reasons but it's better to submit a PR and see what the team has to say on the code and strategies

**Comment by nazar-pc** [comment]
@Nevraeka, I'm not sure whether this is currently possible, since Polymer 1.0 does not support extending custom elements, and this is the feature my patch was based on.

I'm looking for, probably, different approach with 1.0, but still can't find a way for this. Also I do not see any roadmap for supporting extension of custom elements.

Since 1.0 is composed of a relatively independent components my hope is that it would be possible to create extension without need to modify Polymer's core.

**Comment by Nevraeka** [comment]
@nazar-pc extending elements is a touchy subject ATM on the [WebApps w3c mailing list](https://lists.w3.org/Archives/Public/public-webapps/2015AprJun/0899.html)

**Comment by nazar-pc** [comment]
If anyone will be interested - I've implemented something similar in Polymer 1.x using conversion of prototype to behavior and some hacks around `Polymer.DomModule` in order to allow optionally override element's module (by default only latest declaration is used).
Implementation is completely backward compatible with all existing elements unaware of these improvements.
Code can be found here: https://github.com/nazar-pc/CleverStyle-CMS/commit/7403ead9aedab67f235b287b1e68137574886460, file `aa.Polymer-extend-override` (LiveScript original and JavaScript compiled version).
