### ISSUE TITLE
paper and core dropdown menu when scrolling closes without selecting

### ISSUE THREAD

**Issue by TimWillis** [Polymer/polymer#1035]
When I  try to scroll using the mouse on the dropdown menus it closes the "dialog". Also would be nice to type to select option. You can see it right here: https://www.polymer-project.org/components/paper-dropdown-menu/demo.html

**Comment by franklinrussell** [comment]
Is there an ETA for when this will be fixed?

**Comment by franklinrussell** [comment]
Others are running into this as well.

https://github.com/Polymer/paper-dropdown-menu/issues/55

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
