### ISSUE TITLE
Polymer elements do not parse JSON attributes containing &#39; / singlequote characters.

### ISSUE THREAD

**Issue by jerub** [Polymer/polymer#1037]
Here is a working example:
 
    <polymer-element name="test-element" attributes="attr">
    <template>
      Attr: {{ attr }}<br>
      Length: {{ attr.length }}<br>
    </template>
    <script>
    Polymer({
        attr: [],
    });
    </script>
    </polymer-element>
    <test-element id="good" attr="[&quot;foo&quot;]"></test-element>
    <hr>
    <test-element id="bad" attr="[&quot;&#39;&quot;]"></test-element>
    </body></html>

And the resulting webpage looks like:

    Attr: foo
    Length: 1

    Attr: ["'"]
    Length: 5

According to the documentation, valid JSON should always be parsed, especially when there's a hint in the polymer element.

**Comment by jerub** [comment]
Any progress with this? I had to work around this by doing JSON.parse manually.

**Comment by arthurevans** [comment]
Update: This issue no longer occurs in the 0.8-preview branch.

http://jsbin.com/cotoyo/1/edit?html,output

Given that 0.5 is pretty stable and people may rely on the existing (albeit odd) behavior, I suspect this won't get changed in the 0.5 branch.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
