### ISSUE TITLE
FR: Lower default paper-dropdown-transition duration from 500ms

### ISSUE THREAD

**Issue by ninabikes** [Polymer/polymer#1038]
If unspecified, paper-dropdown-transition uses a default duration of 500ms. This makes the dropdown feel incredibly sluggish and unpolished.

Please consider lowering the default to 100ms or 200ms.

Known workaround: I can set the duration manually, but the defaults should be better. :)

**Comment by diegohaz** [comment]
How do you set it manually?

**Comment by ninabikes** [comment]
It's an attribute: https://www.polymer-project.org/docs/elements/paper-elements.html#paper-dropdown-transition

You can set it on the paper-dropdown directly.
<paper-dropdown duration="200"></paper-dropdown>

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
