### ISSUE TITLE
<template repeat> fails to iterate over custom arrays

### ISSUE THREAD

**Issue by Mitranim** [Polymer/polymer#1040]
Example.
```javascript
// Custom array class
function Collection() {
  this.push.apply(this, arguments)
}
Collection.prototype = Object.create(Array.prototype)
Collection.prototype.constructor = Collection

var myCollection = new Collection(1, 2, 3)  // → [1, 2, 3]

myCollection instanceof Array               // → true
```

When used in Polymer:
```html
<template repeat="{{num in myCollection}}">
  {{num}}
</template>
```

Produces nothing:
```html
▼ <template repeat="{{num in myCollection}}">
     #document-fragment
  </template>
```

Custom arrays are pretty common in model libraries, or at least in [this one](https://github.com/Mitranim/record). Polymer should be able to iterate over them.

**Comment by jmesserly** [comment]
fwiw, ES6 supports subclassing builtins: https://github.com/lukehoban/es6features#subclassable-built-ins
... so it seems like there should be some way to do this in ES6? Maybe Array.isArray will return true for those objects?

**Comment by pflannery** [comment]
if IsArray is the only problem then it is possible to extend an Array class where Array.isArray() === true. 

Example:

```js
function MyArray(args) {
	var collection = Object.create(Array.prototype);
	collection = Array.apply(collection, args);
	return collection;
}

var x = new MyArray();
Array.isArray(x) // => true;
x instanceof Array // => true
```

**Comment by Mitranim** [comment]
@pflannery Unfortunately that's not a new class, it's a generator of objects that inherit only from Array. Wouldn't be as useful as an actual subclass with its own Array-derived prototype.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
