### ISSUE TITLE
[Shadow DOM] Make Shadow DOM optional 

### ISSUE THREAD

**Issue by Nevraeka** [Polymer/polymer#1042]
It has been argued that HTML Imports, Templates, & Shadow DOM are add ons for Custom Elements. The Polymer library will always use Shadow DOM (polyfilled or native). It would be a great advantage to have Shadow DOM as a configuration flag globally in the flags object OR even at the element level with a property like `shadow : false`. 

Any thoughts on this?

**Comment by ssorallen** [comment]
Disabling shadow DOM completely would affect the common practice of using `id` attributes for element references and for styling. If an element is used more than once on a page, wouldn't the page have multiple elements with the same ID?

**Comment by Nevraeka** [comment]
Yes It would. I would do this only per element

**Comment by justinfagnani** [comment]
This is configurable now. See https://github.com/Polymer/polymer/blob/0.8-preview/PRIMER.md#global-polymer-settings
