### ISSUE TITLE
[Browser Detection] Replace IE User Agent detection

### ISSUE THREAD

**Issue by Nevraeka** [Polymer/polymer#1043]
Currently `navigator.userAgent` is used for detecting IE. Would using feature detection be a better solution? I have a PR ready with the code below if you think this is a better way. Thanks. cc/ @robdodson 

```javascript
// from https://github.com/Polymer/polymer/blob/master/src/system/HTMLImports/base.js#L67

var isIE  = new Function("return/*@cc_on!@*/!1")();
```

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
