### ISSUE TITLE
paper button double padding

### ISSUE THREAD

**Issue by mattkrick** [Polymer/polymer#1047]
For paper-button, links get double padding, as can be seen on the demo page (https://www.polymer-project.org/components/paper-elements/demo.html#paper-button). Was this intended? As is, any linked buttons in a navigation toolbar are probably going to exceed the default height.

This can be traced to paper-button.html, starting on line 111:
```
      .button-content {
        padding: 0.7em 0.57em
      }
      polyfill-next-selector { content: '.button-content > a'; }
      ::content > a {
        height: 100%;
        padding: 0.7em 0.57em;
```

**Comment by morethanreal** [comment]
Sounds like a bug. Can you file in the issues for Polymer/paper-button?

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
