### ISSUE TITLE
Your home page does not work in Safari on Yosemite

### ISSUE THREAD

**Issue by bobfischer** [Polymer/polymer#1048]
The polymer home page does not work on Safari.  The second and third panels don't display any content.  I am using Safari Version 8.0.2 (10600.2.5) on Yosemite (Version 10.1.1).

![polymer screen capture](https://cloud.githubusercontent.com/assets/1811785/5538080/eff83178-8a7a-11e4-9e3b-33c6a66f1e07.png)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
