### ISSUE TITLE
Firebase example (on polymer.github.io) link is broken—404 error

### ISSUE THREAD

**Issue by richieb** [Polymer/polymer#1049]
For the two Firebase examples on the page below, only the first one (firebase-element ) loads:
http://polymer.github.io/firebase-element/components/firebase-element/demo.html

The "firebase-login" example does not load:
http://polymer.github.io/firebase-element/components/firebase-element/demos/login.html

**Comment by Nevraeka** [comment]
@richieb - :+1: Interesting catch - `https://github.com/Polymer/firebase-element/blob/master/demos/login.html` exists so I am guessing it was not updated on the polymer.github.io pages. It is definitely not there though.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
