### ISSUE TITLE
Class medium-tall in firefox

### ISSUE THREAD

**Issue by ramonsenadev** [Polymer/polymer#1050]
Broken height in firefox, if used medium-tall class in core-toolbar and scroll mode in core-header-panel. If not use scroll mode in core-header-panel, it works.

Example code:
  ```<core-header-panel flex mode="scroll">
    <core-toolbar class="medium-tall">
      <paper-icon-button icon="menu" title="menu" role="button" aria-label="menu"></paper-icon-button>
      <div>Hello World</div>
    </core-toolbar>
  </core-header-panel>```

Ps. Sorry for my english.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
