### ISSUE TITLE
Difficult to create reusable styles (style guide)

### ISSUE THREAD

**Issue by zinkkrysty** [Polymer/polymer#1052]
Polymer is great for encapsulating styles and functionality so it doesn't leek into the main document.

However, when building a larger web application using Polymer, sharing styles is very important to the maintainability of the project. Also, with increasing popularity of SASS in web design, there are numerous libraries that make designer's life easier and stylesheets more maintainable.

Currently in Polymer, there are limited ways of sharing styles, all with serious issues that make building a web application in Polymer resembling a bit the entangled mess of a spaghetti bowl for web designers. These ways are the following, however the issues are obvious and hard to find workarounds to, without affecting the maintainability of the project codebase:

1. Using /deep/ to target all shadow DOMs
    - Every selector needs to have `body /deep/` in order to propagate the shared styling. Adds a lot of overhead to the stylesheet, also making things like selector + selector behave unexpectedly.
2. Importing the same stylesheet for many elements
    - Seems more like a hack, which is bad for performance
3. The `<core-style>` to reuse CSS declarations directly.
    - This method is very promising, however because of writing styles directly in the `<core-style>` tag, we can't use the power of pre-processors or including external stylesheets

CSS can indeed be hard to maintain and this is confirmed by the very numerous and strict ways of achieving this job (read BEM, style guides, specificity managing, etc.).

I believe having a great living style guide is one of the important keys to solving the CSS maintainability problem, however it is very hard to find a way to do this properly with Polymer and web components.

This issue is connected to the fact that when building a Polymer app, it tends to go into the direction where your app is a Polymer element itself and made out of other Polymer elements, making it hard to have a common stylesheet that applies to elements in your app.

More specifically, how would we style basic elements like `h1` and `h2`, making them share the style for a consistent look across the app, no matter where they are situated in the Shadow DOM tree?

**Comment by ebidel** [comment]
It's a common practice to include everything inside the components import that is depends on. This should include all of its dependencies and markup. As such, it makes sense to include/import any css the component needs. Importing compass files are harmless. They're only mixins and won't bloat the output .css file. For things like fonts, we usually use an HTML Import to bring it in as a dependency at the top of the element's import:
https://github.com/Polymer/font-roboto/blob/master/roboto.html

**Comment by ssorallen** [comment]
I interpreted the "overhead" of "Using /deep/ to target all shadow DOMs" to be a comment on the work required to use existing libraries with custom elements that use shadow DOM and not a comment on performance. If you wanted to use a pre-built CSS framework like Bootstrap, putting a single `<link>` in the head would likely not work as expected if your pages use any shadow DOM: you'd have to modify the library and prepend `body /deep/` to many of its selectors or forego the shadow DOM like @zinkkrysty mentioned (#222).

@ebidel Is the current suggestion to add a `<link>` to the library in each custom element and let the browser de-dupe the multiple references to the stylesheet?

**Comment by Nevraeka** [comment]
@ssorallen version 0.8 is being tested now with optional Shadow DOM so theming could also be achieved a bit more like we would expect it to be based on current best practices. `/deep/` is a hammer and should be used in moderation as necessary. Shared styles can be achieved in a few ways.
- Using a CSS precompiler as your core styling distribution at build time that concat to the appropriate component files (as @ebidel points out) & vulcanize
- Using `<core-style>` (as described in @PascalPrecht 's [article] (https://pascalprecht.github.io/2014/08/01/sharing-styles-across-web-components-with-polymer-and-core-style/));
- use `::content` and shallow Shadow Roots (probably hard to achieve when using other peoples components with yours but the idea is sound)
- "Hulk Smash" style by using global `body /deep/` selectors (similar to `!important`)
- wait until Shadow DOM is optional

A combination of these might be a good way to go to see what works for you. You can `git checkout -b 0.8-preview` to use the 0.8 version if you like but keep in mind that it is a preview and not a release yet so it's buggy.

**Comment by ebidel** [comment]
> Is the current suggestion to add a `<link>` to the library in each custom element and let the browser de-dupe the multiple references to the stylesheet?

I wouldn't recommend including huge libraries like boostrap.css like this.

**Comment by ssorallen** [comment]
Thanks for the round up, @Nevraeka.

**Comment by Nevraeka** [comment]
:+1: @ssorallen

**Comment by zinkkrysty** [comment]
Oh that's very neat, @Nevraeka ! Optional Shadow DOM seems like a good solution, until we can have a more versatile `<core-style>` element. 

Using the project's own styleguide is similar to using an external library such as Bootstrap, which is now a pain with Shadow DOM and the way styles aren't inherited by custom elements.

I wonder if it would be a good idea that you can turn Shadow DOM on/off for any element that you use, even if it's a core element or a paper element. That way, you can have a custom CSS style guide that would impact those elements as well. 

I am not sure where the fine line is between Shadow DOM being very useful or just a pain to work with in big projects. Any tips from someone with experience here?

**Comment by esprehn** [comment]
Using lots of <style> elements will be the most performant option in
Chrome. You don't want to "bake" your common styles into a single sheet in
all your components, instead you want to do something like:

<polymer-element name="this-widget">
  <template>
    <link rel="stylesheet" href="common.css">
    <link rel="stylesheet" href="this-widget.css">
  </template>
  ...
</polymer-element>

We then share the common.css sheet internally between all widgets that used
it, and the this-widget.css sheet will be shared between all of this
<this-widget> elements that use it.

**Comment by Meligy** [comment]
@esprehn is `<style>` more performant than `<core style ref=".." >` in that case?

**Comment by esprehn** [comment]
I assume core-style just inserts a <style> so it should perform about the
same.

**Comment by clintwood** [comment]
Doesn't this issue simply highlight a limitation or shortcoming with related WebComponent specifications.

To me it feels like we trying to hack out a solution specifically around theming existing components and none seem natural and/or intuitive... Am I missing this completely?

**Comment by cmawhorter** [comment]
@clintwood That was my take away after building an internal app with polymer last year.  I just found a [chat transcript](http://www.w3.org/2015/04/24-webapps-irc) from last month talking about this stuff, so it seems like it's at the forefront.

I just hope it gets resolved in a way that doesn't just trade bootstrap for polymer-ui.  I'd really like to be able to use a la carte components without a huge styling headache.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

**Comment by cmawhorter** [comment]
Even 1.0 doesn't feel like a good solution to the theming problem: https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-css-mixins

CSS4 will go a long way to alleviating the generic website theming problem but polymer/WebComponents feel clunky to me.  Which is why I don't bother changing default polymer styles... who wants that headache.

A brief somewhat off-topic Web Component rant:  

It seems to me that shadow dom and a chunk of the other web component spec serves to recreate what is essentially and iframe in a terrible way.

My $0.02 -- Extending iframe would've solved what web components aimed to in a backwards compatible way.

And an even more off-topic rant... entire SPA frameworks have been built to recreate <frame>.  The new web is insane.

**Comment by jaichandra** [comment]
@ebidel What's the best practice for including a shared library in an element. I understand that the import is de-duplicated, but what's the performance impact on including a large shared style module. Will it get copied in the DOM for each element and parsed separately?
