### ISSUE TITLE
Changed callback behavior when default value is set to `null`

### ISSUE THREAD

**Issue by kgryte** [Polymer/polymer#1053]
If I set the default attribute value to `null`, setting the attribute to `undefined` does __not__ cause the `attrChanged` callback to fire.

The issue does not appear to be due loose equality checking ( `==` versus `===`), as setting the attribute to `false` does trigger the `attrChanged` callback.

If I set the default attribute value to `5`, setting the attribute to `undefined` does result in the `attrChanged` callback to fire.

The issue seems to be limited to the case where the default value is `null`.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
