### ISSUE TITLE
is there paper-table which use materials design?

### ISSUE THREAD

**Issue by Colstuwjx** [Polymer/polymer#1056]
I didn't find the paper-table element, and want to use paper-table instead of the origin \<table\>.

Did Polymer support this?

**Comment by MetalMatze** [comment]
Since there's now a spec for data tables. Has anyone done some work on this? Maybe something with `core-list`? Otherwise I would start to create my own, since I would need something like that.

**Comment by chuckh** [comment]
This might work for you, Vaadin Components a data grid for showing large amounts of data on the web. It is based on Polymer.

https://vaadin.com/labs-components/

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
