### ISSUE TITLE
Aliasing tag names on import to resolve name clashing

### ISSUE THREAD

**Issue by phestermcs** [Polymer/polymer#1060]
It seems right now all element names fundamentally live in a global namespace. It hasn't happened yet, but I'm sure sooner rather than later, element names from different parties will clash when both are used in the same application.

It would be ideal if, when importing an element, there was a way to alias it within the application. Conceptually, if I were to import say `core-label`, I could optionally override it's in-app namespace by replacing `core` with my own alias. For example (a bit contrived, and using a 'new' Polymer defined custom element `import-alias`):

``` html
<import-alias prefix="v1">
  <link rel="import" href="vendor-abc/chart-pie.html"/>
</import-alias>

<import-alias prefix="v2">
  <link rel="import" href="vendor-xyz/chart-pie.html"/>
</import-alias>

<import-alias prefix="x">
  <link rel="import" href="core-label/core-label.html"/>
  <link rel="import" href="paper-progress/paper-progress.html"/>
</import-alias>
...
<v1-pie></v1-pie>

<v2-pie>/<v1-pie>

<x-label>
  Progress
  <x-progress value="10"></x-progress>
</x-label>
```

**Comment by davidmaxwaterman** [comment]
What an interesting idea....

**Comment by kieran** [comment]
This seems conceptually similar to xml namespaces, for which there's already native support in rendering engines.

in theory, we could do something like:

````xhtml
<link rel="import" href="vendor-abc/chart-pie.html" xmlns:abc="http://abc.co/chart-pie">
<link rel="import" href="vendor-xyz/chart-pie.html" xmlns:xyz="http://xyz.io/chart-pie">
...
<abc:pie></abc:pie>
<xyz:pie></xyz:pie>
````

**Comment by zoechi** [comment]
That's what I thought when I saw the report but
XML namespaces aren't part of HTML5 proper (http://stackoverflow.com/questions/7851190/how-to-include-multiple-xml-namespaces-in-html5).

**Comment by Nevraeka** [comment]
Interesting idea. From my understanding, custom elements need to exposed to the global namespace to be considered 'first class citizens' in the browser. Not sure if this is exactly what you want, but when building native elements you can use JavaScript namespaces by creating a globally exposed namespace imperatively on the window object

```javascript
...

window[namespace] = window[namespace] || {};
window[namespace].AwesomeElement = document.registerElement('awesome-element', { prototype: AwesomeElementProto });

...
```

**Comment by phestermcs** [comment]
Something like:
```html
<link ... xmlns:ns="[namespace uri]">
```
merely defines an alias named `ns` for `[namespace uri]`, and would not necessarily 'place' the ```<link>``` element, or any of its children, or its imported content 'into' any particular namespace. The alias itself is only scoped to ```<link>``` and its children, so using it later wouldn't work from just defining the alias in the ```<link>``` element. That's just the semantics of XML namespaces, and it probably wouldn't be a good idea to override that.

If it were possible to use XML namespaces, the element author would need to specify the namespace URI upon element declaration/registration. And then an element consumer could create an alias for that namespace in the `<html>` or `<body>` tags. Something like (simplified):
```html
<html>
  <head>
    <polymer-element name="some-element" targetNamespace="http://author.com"/>
  </head>

  <body xmlns:f="http://author.com">
    <f:some-element/>
  </body>
</html>
```

But reading the current draft for [Custom Elements](http://w3c.github.io/webcomponents/spec/custom/index.html#dfn-definition-construction-algorithm), it's not clear this is possible. While it says in Section 4 that an element definition includes a namespace, there's no way to explicitly set it. Further section 7 seems to effectively indicate that custom elements are in the `HTML Namespace` or `SVG Namespace`. Using XML namespaces (and XHTML) might be the ultimate way to disambiguate custom elements, but it should probably be part of the Custom Element spec.


It is preferred to use elements declaratively in HTML, and not imperatively in Javascript. HTML element namespaces are completely separate from and different than javascript namespaces, and being able to alias a custom element name on import is dealing with namespacing in HTML.

**Comment by phestermcs** [comment]
So, I spent about the last 2.5 weeks putting something together to solve this. If there's anyone out there reading this, I would appreciate any feedback. Please check out [PolyComp](https://github.com/phestermcs/polycomp)

**Comment by azakus** [comment]
This is more of a spec problem that should be handled in the Custom Elements spec: https://github.com/w3c/webcomponents/issues/344
