### ISSUE TITLE
DataBinding not full work in IE (polymer-0.5.2)

### ISSUE THREAD

**Issue by nim** [Polymer/polymer#1063]
See 
http://plnkr.co/edit/eyFdiL?p=preview
http://prntscr.com/5n6zxg

The word 'red' must be color red. Works fine in FireFox and Chrome, but no work in IE11.

**Comment by IntranetFactory** [comment]
That's a documented restriction of IE (see https://www.polymer-project.org/docs/polymer/databinding-compat.html). You should bind _style and it will work in all browsers (see http://plnkr.co/edit/EP3yQetpXar7o8Xs58UN?p=preview)

**Comment by nim** [comment]
Thanks,
but i use demo from https://www.polymer-project.org/docs/start/creatingelements.html#publishing
This is a strange approach. What and where I still have to know that I did not have to trouble?
