### ISSUE TITLE
How to replace tag name depend on attribute?

### ISSUE THREAD

**Issue by f0rmat1k** [Polymer/polymer#1064]
I tried
```
<template>
  <{{tagName}}></{{tagName}}>
</template>
```
but it isn't working.

And
``` 
<template>
  <template if={{someConditions}}>
     <some-another-tag>
  </template>
</template>
```
is not working to.

Also http://stackoverflow.com/questions/27732408/polymer-how-to-replace-tag-name-depend-on-attribute

**Comment by ebidel** [comment]
See http://stackoverflow.com/questions/27732408/polymer-how-to-replace-tag-name-depend-on-attribute/27768080#27768080

**Comment by f0rmat1k** [comment]
Thank you.
