### ISSUE TITLE
Can core-xhr and core-ajax not merged into one?

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#1065]
```html
<core-ajax id="xhr"></core-ajax>
<core-xhr id="xhr"></core-xhr>
this.$.xhr.request({url: url, params: params, callback: callback});
```

I can't see a reason why we need two ajax elements?

**Comment by Nevraeka** [comment]
I am not sure but I am guess to make it easier to create different types of requests (similar to JQuery creating $.load, $.getJSON, $.getScript, etc which call $.ajax underneath the covers)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
