### ISSUE TITLE
Data Binding Outside Template

### ISSUE THREAD

**Issue by mahdaen** [Polymer/polymer#1068]
Hi all,

I just wondering, how to bind data outside `<template>`?
Maybe something like this:

```js
window.project = {
    title: "Something",
    version: "1.0.0"
}
```
```html
<x-label value="{{ project.title }}">
    <x-span>{{ project.version }}</x-span>
</x-label>
```

Thanks

**Comment by pflannery** [comment]
this explains binding outside:
https://www.polymer-project.org/docs/polymer/databinding-advanced.html#bindingoutside

**Comment by davidmaxwaterman** [comment]
Some interesting information there, but I don't quite see how to use those techniques to solve the problem - not without some additional script anyway.

**Comment by pflannery** [comment]
Here is an example of the above working with outside binding: http://jsfiddle.net/13du4ohg/

@davidmaxwaterman yeah its additional script, I don't believe we have a choice about that right now. 
Maybe a newer feature like below to make it script less when auto-binding is present.
```html 
<template is="auto-binding" bind="{{window.project as project}}">
    <label>{{project.title}}</label>
    <span>{{project.version}}</span>
    <br />
    <br />
    <input value="{{project.version}}" />
</template>
```

**Comment by ebidel** [comment]
There's no way to do data-binding without script atm. It's not a native feature in the web platform :\

The template needs to be activated and told which data model to associate with it. In Polymer, we've created the auto-binding template to make things easier for folks and to use Polymer's features outside of custom elements. The TemplateBinding library that polymer uses adds basic binding features to the `<template>` element. 

```
<template bind="{{project}}">
  <label>{{title}}</label>
  <label>{{version}}</label>
  ...
</template>

var t = document.querySelector('template');
t.model.project = {title: "Something", version: "1.0.0"};
```

I recommend using the auto-binding template because it's easier to use and supports more features.

**Comment by mahdaen** [comment]
Thanks guys, so I can't bind data outside `<template>` right?
Does polymer has a plan to add that feature? I think binding data without wrapping them to `<template>` is more beautiful.

I want to create app with polymer that automatically synchronize the data to server with this tag: `<data-provider src="..." name="project" auto />`. Maybe I must create my own data binding to makes me able bind data outside template, but will be better if polymer have that feature. ;)

**Comment by ebidel** [comment]
AFAIK, no plans. The model is that you create custom elements that fire events, have attributes, properties and methods. Data-binding is just a convenient feature on top of that that reduces the amount of wiring you have to do. 

Bringing data-binding features outside of custom elements is something traditional frameworks do.  They control the entire page. On the other hand, `<template is="auto-binding">` is a custom element that extends the native `<template>` with Polymer's data-binding capabilities. So it still follows the model of custom elements doing all the work.

**Comment by mahdaen** [comment]
Okay, now I understand. :)
Btw, how to listen event when `<template>` element is inserted into document using ajax or `.appendChild()`?

My plan is something like this:

```html
<template dref="project, authors, repos" is="auto-binding">
   <h2 class="title">{{ project.title }}</h2>
   <p>Total: {{ authors.length }} authors</p>
   <p>Total: {{ repos.length }} repositories</p>
</template>
```
Then when that template is inserted by ajax, it's firing an event. So I can find does each object inside data-ref is available on DataStore before binding. If available, then I bind the data to that template.

Thanks for helps ;)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
