### ISSUE TITLE
Chaning the color of Core-toolbar

### ISSUE THREAD

**Issue by SneakyKoala** [Polymer/polymer#1070]
Using core-scaffold and core-toolbar to create a navigation menu. Codepen (example): http://codepen.io/anon/pen/MYbrmO

But  I can't menage to edit the background-color of the toolbar next to the navigation, it stays blue.
With CSS to style it by giving it a class and even in the element itself doesn't change anything.

Am I doing something wrong?

**Comment by ebidel** [comment]
The core-toolbar in the scaffold is part of the element's shadow dom. You can use `::shadow` to select and style it:

    core-scaffold::shadow core-toolbar {
      background-color:grey;
   }

Alternatively, you can style all toolbars anywhere in shadow dom using:

    html /deep/ core-toolbar {...}

**Comment by SneakyKoala** [comment]
Wow, thanks alot for the fast response!
Fixed.

**Comment by NitroBAY** [comment]
That doesn't work on firefox :-1:

**Comment by arthurevans** [comment]
@NitroBAY if you're using the shadow DOM selectors (/deep/, ::shadow, ::content) in a document-level stylesheet, you need to add `shim-shadowdom` to the `<style>` tag:

    <style shim-shadowdom>

See:

https://www.polymer-project.org/0.5/docs/polymer/styling.html#sdcss

**Comment by NitroBAY** [comment]
Thanks
