### ISSUE TITLE
Paper-Tabs Core-Pages -- on-core-select fired early

### ISSUE THREAD

**Issue by Will-in-BC** [Polymer/polymer#1071]
HI,

I am trying to use paper-tabs and core-pages together. Upon polymer ready I set the value of selected for paper-tabs. This causes on-core-select to be fired but core-pages are not completely ready. I am using 0.5.2 of polymer 

Here is the code that illustrates the issue:

```
<!doctype html>
<html>
<head>

  <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1, user-scalable=yes">

  <title>Paper Tabs Core Pages Issue demo</title>

  <script src="../webcomponentsjs/webcomponents.js"></script>

  <link rel="import" href="../font-roboto/roboto.html">
  <link rel="import" href="../core-pages/core-pages.html">
  <link rel="import" href="../paper-tabs/paper-tabs.html">



<style shim-shadowdom>

body {
  font-family: RobotoDraft, 'Helvetica Neue', Helvetica, Arial;
  margin: 0;
  padding: 24px;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  -webkit-tap-highlight-color: rgba(0,0,0,0);
  -webkit-touch-callout: none;
}
</style>

</head>
<body unresolved>
  <template is='auto-binding' id='myTemplate'>
    <paper-tabs id='myTabs' on-core-select="{{tabSelected}}" selected="{{pageSelected}}">
      <paper-tab>Tab 1</paper-tab>
      <paper-tab>Tab 2</paper-tab>
    </paper-tabs>
    <core-pages id='myPages'>
      <div>Tab 1</div>     
      <div>Tab 2</div>     
    </core-pages>
  </template>

  <script>
    document.addEventListener('polymer-ready', function() {
      var templateHandle = document.querySelector('#myTemplate');
      templateHandle.pageSelected = 1; // this will cause tabSelected (on-core-select) to be fired
      templateHandle.tabSelected = function() {
        //
        // this is a bit of a hack -- it looks as if tabSelected can be fired before $ hash is 
        // set up. Check to make sure the $ hash is available before using.
        // Should be further investigated. 
        //
        if (typeof (templateHandle.$) !== 'undefined') {
          pages = templateHandle.$.myPages;
          pages.selected = templateHandle.pageSelected;
        } else {
          console.log('event triggered but $ hash not established') 
        }

      } // end tabSelected

    }); // end polymer ready
  </script>
</body>
```

Note I have tried to put the `templateHandle.pagesSelected = 1` into `templateHandle.ready` but same issue.

**Comment by morethanreal** [comment]
Have you tried binding the `paper-tabs` and `core-pages`'s `selected` property together?

```
<paper-tabs selected="{{pageSelected}}"></paper-tabs>
<core-pages selected="{{pageSelected}}"></core-pages>
```

**Comment by Will-in-BC** [comment]
Yvonne,

Thanks that will work but I am still unclear as to why the $ hash (and I
assume the shadow dom as I cannot use querySelector either) is not
established at the time polymer ready is triggered. When should the $ hash
be available?

I was following a pattern posted by one of the Polymer team (
http://jsbin.com/denedudokike/1/edit?html,output) which doesn't include
wrapping the code in a template and explicitly handles the on-core-select
event.

Happy New Year

Will


On Mon, Jan 5, 2015 at 2:42 PM, Yvonne Yip <notifications@github.com> wrote:

> Have you tried binding the paper-tabs and core-pages's selected property
> together?
>
> <paper-tabs selected="{{pageSelected}}"></paper-tabs>
> <core-pages selected="{{pageSelected}}"></core-pages>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Polymer/polymer/issues/1071#issuecomment-68795564>.
>



-- 
Will Hopkins
604.437.0337 (H)
778.773.0320 (M)
williamr.hopkins@gmail.com

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
