### ISSUE TITLE
Failed to assign list scroller to scroller of headerPanel

### ISSUE THREAD

**Issue by nick-lehmann** [Polymer/polymer#1072]
To get in touch with polymer I watched a [talk](https://www.youtube.com/watch?v=kV0hgdMpH28) by Rob Dodson. Because it is always better to write some code I started my own app and tried to follow his steps. It's app is a contact app is available on [Github](https://github.com/robdodson/contacts-app).

The main part of the app is a `core-list` where all contacts are displayed. Then he gives a hint that you should assign the scroller of the `core-list` to the scroller of the `core-header-panel`. Unfortunately, I failed to accomplish this even when I looked at his repo and compared the code. I asked a [question on StackOverflow](http://stackoverflow.com/questions/27678417/polymer-scroller-target-not-working-properly) where I included more information and some images.

Hopefully anybody out there has a clue on how to fix this.

**Comment by nick-lehmann** [comment]
Ok, I suppose I found my error. The import of `core-header-panel` was missing and therefore the scroller was undefined.

**Comment by frankiefu** [comment]
sounds like is resolved, closing.
