### ISSUE TITLE
Urgent: None of the /deep/ or ::shadow styling works on Chrome

### ISSUE THREAD

**Issue by richieb** [Polymer/polymer#1073]
I am almost finished building my Polymer app, but this one issue has costed me about 3 hours:

None of the styling shown on the link below works on Chrome (I have version 39.xxx), the code does works on Safari and Firefox (latest version of each browser):
https://www.polymer-project.org/articles/styling-elements.html

Specifically, I am using sass and I cannot get any of this to work in Chrome:

/deep/ paper-shadow h1 mark-down * {
margin:4px;
}

 /shadow-deep/ paper-shadow h1 mark-down * {
margin:2px;
}

my-component::shadow paper-shadow::shadow h1 mark-down::shadow * {
  margin:1px;
  }

As I noted above, all of it works on Safari and Firefox.

**Comment by ebidel** [comment]
Chrome has native SD support, which is why there is a difference. 

- `/deep/` needs a selector in front of it. So `body /deep/ paper-shadow h1 mark-down *` should work
- you need `shim-shadowdom` on the stylesheet if it's outside of polymer-element: https://www.polymer-project.org/docs/polymer/styling.html#sdcss
- `/shadow-deep/` is no longer a thing. use `/deep/`.

Please ask these types of questions on Stackoverflow in the future :)

**Comment by richieb** [comment]
First, thanks for the quick reply. 

Second, I did as you have suggested and it is still not working Chrome.

**Comment by ebidel** [comment]
Ok, can you post a jsbin so we can take a look?

**Comment by Nevraeka** [comment]
@richieb - here is an [example on codepen](http://codepen.io/robdodson/pen/wraDn/) by @robdodson

Also check out this article:

http://robdodson.me/shadow-dom-css-cheat-sheet/

**Comment by richieb** [comment]
Ok, so it looks like I have narrowed down the problem to the mark-down component. See the jsbin below, and note that the mark-down component is now loading (I need the proper link). If it does load and execute, then it breaks the code:

http://jsbin.com/zogepocuxi/1/

**Comment by richieb** [comment]
Thanks a lot for the demo and link @Nevraeka. I noticed @robdodson created the mark-down component, which is the issue in this case.

**Comment by richieb** [comment]
By the way, I purposefully added the div with id="markdown" [<div id="markdown">] because mark-down does that. I was trying to replicate the same HTML structure that shows up in my rendered page.

**Comment by richieb** [comment]
I am either going nuts or there is a Chrome bug relating to this issue. I will test a few more examples later today and report back with my findings. I am convinced there is an issue somewhere with Chrome and the shadow dom, and it doesn't appear to be related to the mark-down component.

**Comment by miztroh** [comment]
You should try running your jsbin with dev tools open.  You will notice in your example that github.io is not allowing the @robdodson element to load for cross-origin reasons.  Also, you have a bad path to webcomponents.js.

I've created a new example for you.  You'll see that ```test-element /deep/ p``` works just fine to style the shadow DOM of your custom element.  It would work the same assuming you could get mark-down to load.

http://jsbin.com/mugunifimi/2/edit?html,output

**Comment by richieb** [comment]
Thanks, @miztroh, but the jsbin is the least of my troubles. The jsbin that I posted yesterday has been edited many times since, for testing, so it is likely much different now. The original issue (buggy shadow down under a specific condition) is still present in Chrome, however. I will follow up later today.

**Comment by richieb** [comment]
Here are my findings, all of which should be documented somewhere with the points I note below:

A. This doesn't work: `body /deep/ paper-shadow h1 mark-down *`
This works (in native shadow DOM browsers like Chrome): `body /deep/ mark-down /deep/ *`
(**Notes:** We need the second `/deep/` after `mark-down`)

Here is another example:
This doesn't work: `body /deep/ element-name ol`
While this works: `body /deep/ element-name /deep/ ol`

B. You must add `shim-shadowdom` on not just the individual custom element's link tag, for linked stylesheets, as shown below, but also on the link style tag on the homepage, where you likely have a main style.css file (if the page hasn't been vulcanized). 

For example, in mark-down.html, we know we should have `shim-shadowdom` like this:
<link rel="stylesheet" href="mark-down.css" shim-shadowdom>

But in the index.html, we **need** the `shim-shadowdom` as well:
<link rel="stylesheet" href="stylesheets/style.css" shim-shadowdom>

C. You have to be diligent when using SASS with Polymer, particularly because, while Polymer conveniently takes your shadow-DOM-supported-browser styles (with the /deep/ selector, for example) and polyfills accordingly for non-native-shadow-DOM browsers, it doesn't do the same in reverse. That is, it doesn't (and perhaps couldn't) take your nested SASS classes that are missing shadow DOM selectors like `/deep/` and figures out that those nested classes won't work by themselves on Shadow-DOM-supported browsers. This last bit is tricky, and its subtlety can prove elusive for newcomers to Polymer and web components. (Most of us are newcomers to *Polymer*, *web components*, and *shadow DOM*, right?).

To demonstrate that last point, observe the two examples below:

// This is how we are accustomed to writing our standard SASS styles using nesting
// (But it won't work on **native shadow DOM browsers**, though it does work on all other browsers)
```
.contentWrapper {
  .innerDiv mark-down p {
    color: red;  
  }
}
```

// When using Polymer with SASS, this is how we have to write the same style for it to work on both native shadow DOM and non-native shadow DOM browsers:
```
.contentWrapper {
  .innerDiv /deep/ mark-down /deep/ p {
    color: red;
  }
}
```
I should note that I am not sure if the necessity of the last `/deep/` after the final custom tag (the `mark-down` tag in my example) is a bug in Chrome or part of the spec.

D. As we develop Polymer web apps, we have to continually test on all the evergreen browsers during developing, not just at the end of the development cycle. As exhibit A, consider that even the exemplary Topeka app wasn't working on Safari 8.

E. Since SASS's `include` doesn't work like HTML's `import`, which loads each file just once, we need a new pattern or specification for including SASS files. Consider that four different web components (Polymer elements) may need to include the variables.scss and mixin.scss SASS files. We will end up with duplicated CSS classes in the final CSS file(s). Does anyone have a good pattern for working with SASS files and Polymer elements to resolve this issue? I understand that tools such as http://devilo.us can remove duplicated CSS classes and tidy up your CSS, no doubt a hacky way to resolve this issue now.
