### ISSUE TITLE
paper-toggle-button and paper-checkbox events incorrectly documented

### ISSUE THREAD

**Issue by m4b** [Polymer/polymer#1074]
In the Polymer documentation for [&lt;paper-toggle-button&gt;](https://www.polymer-project.org/docs/elements/paper-elements.html#paper-toggle-button), the events section lists the two callbacks as `change` and `core-change`, but the actual callbacks seem to be `on-change` and `on-core-change`.

Similarly for [&lt;paper-checkbox&gt;](https://www.polymer-project.org/docs/elements/paper-elements.html#paper-checkbox).

**Comment by IntranetFactory** [comment]
Why do you report this here and not in repos of each component? I did a quick check and https://github.com/Polymer/paper-toggle-button/blob/master/paper-toggle-button.html#L139 shows that 'change' and 'core-change' are fired.

**Comment by m4b** [comment]
Ah, yea I actually misunderstood the documentation. `change` and `core-change` are definitely fired, since I mentioned their respective `on` callbacks, but I thought event callbacks were documented with their respective `on-x` methods, and not the event `x`.  Seems I was mistaken.

As for reporting, I just used the documentation's "file a bug" button, which didn't notice sent me to the base polymer repo, or [here](https://github.com/Polymer/polymer/issues/new).

I'll close the issue.
