### ISSUE TITLE
0.8-preview: "ready" fires before "created"?

### ISSUE THREAD

**Issue by morethanreal** [Polymer/polymer#1079]
http://jsbin.com/vorute/1/edit

Seems wacky to get "ready" before "created".

**Comment by sjmiles** [comment]
Agreed I believe this is not on purpose, even though it looks like the code is working as written.

Steve owns the `ready` feature, he'll look at it when he's back on his feet.

**Comment by sorvell** [comment]
Yeah, that's a problem. We have separately discussed eliminating the `created` method. I'd like to decide on that before fixing this issue.

**Comment by sorvell** [comment]
Was fixed awhile ago. Closing.

**Comment by Nevraeka** [comment]
thank you @sorvell
