### ISSUE TITLE
0.8-preview: handle case-sensitivity problems around attributes

### ISSUE THREAD

**Issue by sjmiles** [Polymer/polymer#1080]
Where event names need to map to case-sensitive strings, e.g. `on-EventName` and `myProperty="foo"`, we need to do white-list mapping.

Note in particular that binding to mixed-case properties won't work in the meantime.

**Comment by justinfagnani** [comment]
Mixed case bindings work now, but I hit a pothole in that I tried to use the camelCase name on the left hand side of the binding. It'd be really nice if an error were thrown when the property doesn't exist to help catch this error.

**Comment by kevinpschaaf** [comment]
Fixed in https://github.com/Polymer/polymer/pull/1191
