### ISSUE TITLE
Accessibility in core-focusable

### ISSUE THREAD

**Issue by hcarmona** [Polymer/polymer#1081]
In https://github.com/Polymer/core-focusable/blob/master/core-focusable.js
`this.setAttribute('aria-disabled', '');`
should be changed to
`this.setAttribute('aria-disabled', 'true');`

This is because aria-disabled must have a value of true or false. Empty string is invalid and the default value is false. http://www.w3.org/TR/wai-aria/states_and_properties#aria-disabled

**Comment by Nevraeka** [comment]
Adding  [Polymer/core-focusable issue #7](https://github.com/Polymer/core-focusable/issues/7) Let's close this

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
