### ISSUE TITLE
filter not updating when argument is array

### ISSUE THREAD

**Issue by pkuvegeta** [Polymer/polymer#1082]
{{ someArray | myFilter(arrayArgument) }}

When arrayArgument is updated, we do see the arrayArgumentChanged handler getting called. However this filter isn't updating.

http://jsbin.com/vuvikare/4/edit?html,output

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
