### ISSUE TITLE
Anonymous function error on core-ajax/demo-progress.html

### ISSUE THREAD

**Issue by kmraen** [Polymer/polymer#1083]
Hi Polymer team, my name is Donghun and I want to report below issue.

While I have been studied, always below error occurred.

There is an exception error on core-ajax/demo-progress.html file.
this.$.ajax.abort(); << this.$.ajax.abort() is not a function. I don't know why this error has been occurred.

Because of this issue, reset button didn't work. I hope this issue will be troubleshooted as soon as possible.

Thank you.

Regards,
Donghun.

**Comment by davidmaxwaterman** [comment]
This should probably be better asked here :

<https://github.com/Polymer/core-ajax>

Max.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
