### ISSUE TITLE
Paper-dialog not positioned correctly for dynamically populated content

### ISSUE THREAD

**Issue by richieb** [Polymer/polymer#1090]
If you have a paper-dialog element set to display dynamic content, as illustrated in the code below, it does not display correctly on the screen, not centered. It is off to the side and below somewhere. Sure, it does display correctly if it is NOT dynamically populated.

Now, although it shows up not centered on launch, if you resize the browser window, then the dialog readjusts and positions itself to the correct **centered** position. I am much too busy right now to re-create a jsbin for this, but this description and the code below should suffice.
```
  <paper-dialog heading="{content.title}}" class="scrolling" transition="core-transition-center">   
     <template repeat="{{ item in content.items }}">
        // code removed for brevity
    </template>
</paper-dialog> 
```

**Comment by davidmaxwaterman** [comment]
probably not relevant but looks like you're missing a '{' - might want to edit that (then I'll delete this comment), so it's not distracting the reader.
also, shouldn't this be file on paper-dialog? It's not related to polymer itself, is it? <https://github.com/Polymer/paper-dialog/issues>

**Comment by KrisSiegel** [comment]
I'm having a similar issue and I think it's related to https://github.com/Polymer/paper-dialog/issues/44.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

**Comment by KrisSiegel** [comment]
Does anyone know if this was addressed? I haven't used Polymer in some time now but I'd like to know if it was.

**Comment by rvraaphorst** [comment]
Seems like this issue is still there in 1.0

**Comment by nbehary** [comment]
Yes, it is still seems to be present in 1.0.  I've spent today fighting with it not thinking to look for an issue.

**Comment by tjsavage** [comment]
This issue was moved to PolymerElements/paper-dialog#68
