### ISSUE TITLE
on-tap="{{activePage=1}}"

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#1091]
It would save me allot of extra polymer code if you could assign values directly into a binding.

**Comment by davidmaxwaterman** [comment]
I'm a bit surprised you can't put a function in there, eg on-tap="{{ function() { activePage=1; } }}", like you can for callback functions, eg setTimeout( function() { bla; }, 1000 ); instead of setTimeout( myMethod, 1000 );

**Comment by diegohaz** [comment]
It would be very useful.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
