### ISSUE TITLE
fire() during ready() causes 'dispatchMethod' of undefined

### ISSUE THREAD

**Issue by pflannery** [Polymer/polymer#1094]
The error occurs [here](https://github.com/Polymer/polymer/blob/87b3815812aaa9f956f044e74d43460b1babee5f/src/declaration/events.js#L65-L75) when trying

```js
Polymer({
  ready: function() {
    this.fire("yo",{});
  }
})
```

I find that I can get it to work if there was a fall back to this statement ```controller = target.templateInstance.model``` , is this feasible?

**Comment by arthurevans** [comment]
I'm not seeing this:

http://jsbin.com/watoyo/1/edit?html,console,output

Can you provide a few more details?

**Comment by pflannery** [comment]
I have written a plnkr [here](http://plnkr.co/edit/J95l5gMZpNY0ZjdrJg9s?p=preview)
