### ISSUE TITLE
flex-basis: 0.000000001px;

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#1097]
http://jsbin.com/livije/1/edit

Why can I not remove `auto-vertical`

**Comment by ebidel** [comment]
I don't see any code in that bin that removes it. Attributes don't remove themselves :) 

You can use bindings (`auto-vertical?="{{showMe}}"`) as one way to toggle it when `showMe` changes.

**Comment by gertcuykens** [comment]
Sorry I was not clear enough when you remove the `auto-vertical` attribute and use only `flex` everything get squashed see http://jsbin.com/livije/2/edit

**Comment by ebidel** [comment]
`flex` sets `flex-basis: 0.000000001px;` to help IE10's buggy implementation of flex-basis. If you're using vertical layout, don't use `flex` or use `flex one` should work. https://www.polymer-project.org/docs/polymer/layout-attrs.html#auto-vertical

**Comment by gertcuykens** [comment]
`flex one` works :) Not sure if `flex-basis: 0.000000001px;` wil fix more things then it will confuse people. +1 to set it back to auto and move things like this into a seperate webcomponent css `<link rel="stylesheet" type="text/css" href=""https://www.polymer-project.org/components/webcomponentscss/webcomponents.css">` So you can get rid of it as soon as possible :)

**Comment by bendavis78** [comment]
I also got caught by the `flex-basis: 0` hack. The standard default is `auto`, not `0`. IMHO, I don't think IE compatibility should come at the cost of things not working how one would expect in regular browsers.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
