### ISSUE TITLE
core-icons:work bug

### ISSUE THREAD

**Issue by salah-saleh** [Polymer/polymer#1100]
on chrome
![screen shot 2015-01-17 at 17 09 21](https://cloud.githubusercontent.com/assets/1296191/5789459/a798f21e-9e6b-11e4-8719-af8e1c109886.png)
on firefox
![screen shot 2015-01-17 at 17 10 40](https://cloud.githubusercontent.com/assets/1296191/5789465/d1a83ef2-9e6b-11e4-9d92-d9ae74339218.png)

**Comment by gertcuykens** [comment]
does this work ?
https://www.polymer-project.org/components/core-icons/demo.html

**Comment by salah-saleh** [comment]
It works just fine now. I have no clue why! I will post again if I figured it out.
