### ISSUE TITLE
Cannot find function or filter

### ISSUE THREAD

**Issue by rajasharan** [Polymer/polymer#1102]
Below is a sample my-element which uses use custom filters. The custom filter functionality works but console shows weird errors only on page load.

Till now can't find any faults in the functionality or the GUI behavior,

```html
<!-- Import Polymer -->
<link rel="import" href="../bower_components/polymer/polymer.html">
<link rel="import" href="../bower_components/paper-radio-group/paper-radio-group.html">
<link rel="import" href="../bower_components/paper-radio-button/paper-radio-button.html">
<link rel="import" href="../bower_components/paper-slider/paper-slider.html">

<!-- Define your custom element -->
<polymer-element name="my-element">
    <template>
        <!--
           -<style><style>
           -->
        <paper-radio-group selected="{{type}}">
            <paper-radio-button name="daily" label="Daily"></paper-radio-button>
            <paper-radio-button name="weekly" label="Weekly"></paper-radio-button>
        </paper-radio-group>

        <br />
        <paper-slider min="{{type | getMin}}"
                      max="{{type | getMax}}"
                      step="{{type | getStep}}"
                      pin="true">
        </paper-slider>
    </template>

    <script>
        PolymerExpressions.prototype.getMin = function(input) {
            if (input === 'daily') return 1;
            else if (input === 'weekly') return 10;
        };
        PolymerExpressions.prototype.getMax = function(input) {
            if (input === 'daily') return 1000;
            else if (input === 'weekly') return 5000;
        };
        PolymerExpressions.prototype.getStep = function(input) {
            if (input === 'daily') return 5;
            else if (input === 'weekly') return 50;
        };

        Polymer('my-element', {
            ready: function() {
                this.type = 'daily';
            }
        });
    </script>

</polymer-element>

```

![image](https://cloud.githubusercontent.com/assets/299522/5790396/fe66c876-9e63-11e4-972b-462313103d1f.png)

**Comment by gertcuykens** [comment]
What happens if you put this in the `ready` function?

PS consider making a `jsbin.com` to show case the problem, its easier for amatures like me to answer the question :)

```html
PolymerExpressions.prototype.getMin = function(input) {
            if (input === 'daily') return 1;
            else if (input === 'weekly') return 10;
        };
        PolymerExpressions.prototype.getMax = function(input) {
            if (input === 'daily') return 1000;
            else if (input === 'weekly') return 5000;
        };
        PolymerExpressions.prototype.getStep = function(input) {
            if (input === 'daily') return 5;
            else if (input === 'weekly') return 50;
        };
```

**Comment by rajasharan** [comment]
if I add all those expressions inside ready each error repeats twice on page load.
(sorry still trying to figure out to make polymer work in jsbin)

**Comment by pflannery** [comment]
I not seeing a problem

[jsbin example](http://jsbin.com/renosezubo/1/edit)

[plunker example](http://plnkr.co/edit/gvroIkkFFIkLnbQlIYVv?p=preview)

**Comment by rajasharan** [comment]
thanks for the jsbin - I did slight modification (used direct components from polymer website instead of ../bower_components)

live preview link: http://jsbin.com/nonetirovu

If i open the chrome console I see the same errors, do you see in your browser?

**Comment by gertcuykens** [comment]
lol it even crashed my browser if I click on weekly

**Comment by gertcuykens** [comment]
@robdodson why is this breaking the internet :P

```html        
<paper-slider min="{{type | getMin}}"
                      max="{{type | getMax}}"
                      step="{{type | getStep}}"
                      pin="true">
        </paper-slider>
```

**Comment by gertcuykens** [comment]
Note that without paper-slider it works

http://jsbin.com/heqidu/1/edit?html,output

**Comment by pflannery** [comment]
I've realised now that your filters don't return a value when the type is not set or unknown so the filters are being cached as undefined.

 I think you have two choices here to fix this:

1. ensure the type is set
```
       Polymer('my-element', {
            type: 'daily', // ensures the type is set
            ready: function() {
                this.type = 'daily';
            }
        });
```

or 2. handle unknown\undefined types

```
        PolymerExpressions.prototype.getMin = function(input) {
            if (input === 'daily') return 1;
            else if (input === 'weekly') return 10;
            else return 0;
        };
        PolymerExpressions.prototype.getMax = function(input) {
            if (input === 'daily') return 1000;
            else if (input === 'weekly') return 5000;
            else return 0;
        };
        PolymerExpressions.prototype.getStep = function(input) {
            if (input === 'daily') return 5;
            else if (input === 'weekly') return 50;
            else return 0;
        };
```

**Comment by gertcuykens** [comment]
Suggesting to build in `undefined` fail system in polymer because does bugs are very hard to find!

**Comment by rajasharan** [comment]
@pflannery  - initializing `type: 'daily'` did the trick. I also see your point about handling undefined case as well - will do.

@gertcuykens - I did notice the "freeze" issue. But now if I use `value="{{value}}"` attr for paper-slider it no longer freezes - I guess it needed some variable to bind the value.

I think I'll close the issue. Thanks guys.

**Comment by itsNikolay** [comment]
it fails when we use filter in `paper-elements`
it looks like external components do not see internal filters
