### ISSUE TITLE
the question with expression {{}} in html a tag href attribute

### ISSUE THREAD

**Issue by Byronlee** [Polymer/polymer#1104]
js data collections
```
[{"id":1,
"url":"http://xxxxx.com/posts/collections/1",
"name":"product collecitons",
"notes_count":35,
"description":"some thing ",
"feature_image": "some thing",
"description": "some thing"
},
{
.....
}]
```
in my template html
```
        <template repeat="{{item in collections}}">
          <div class="col-sm-3" style="min-height: 230px;">
            <a href="{{ item.url }}" target="_blank">
              <img src="{{item.feature_image}}" class="img-responsive" alt='' />
            </a>
            <h3 class="mg-md">
             <a href="" >{{ item.name }}</a>
           </h3>
           <p>
            {{ item.description }}
          </p>
        </div>
      </template>
```
but every thing is ok except expression{{ item.url }}， it render 
```
<a href="/%5B%5Bitem.url%5D%5D" target="_blank">
```
bug i want it render that 
```
<a href="http://xxxxx.com/posts/collections/1" target="_blank">
```
After several debugging, I found that when the attribute names is "href" that can not be rendered successful if other attribute names, rendering success.

So I change the href attribute to ref, then  can normally rendered as:
```
<a ref="http://xxxxx.com/posts/collections/1" target="_blank">
```
if i use href ,It can not render any expression

This is why, ask for help, thank you

**Comment by davidmaxwaterman** [comment]
I notice you have a double 'double quote' in your data :

"description":""some thing"

-----------------------^^

...otherwise, it seems to work as expected for me :

<http://jsbin.com/guqegoxodo/1/edit?html,console,output>

Am I doing something differently?

Max.

**Comment by Byronlee** [comment]
Oh... I'm sorry, when I wrote the issue of negligence, the data is no problem,

the development environment is
```
Rails  
# and use  
polymer-rails

```

**Comment by davidmaxwaterman** [comment]
Yes, I guessed it was a simple copy/paste problem, or something similar.

I know little-to-nothing about rails - best come up with a jsbin, imo...but since it works with a simple Polymer example, I'd guess this is a rails problem, or at least some unexpected interaction between the two.

**Comment by zoechi** [comment]
This will not solve your problem but you might consider prefixing some attributes with `_` (see https://www.polymer-project.org/docs/polymer/databinding-compat.html#binding-to-attributes)

**Comment by mschwartz** [comment]
I'm using 1.0.

The following does not work, but I think it should :)

```html
<a href="/view/{{item.id}}">text</a>
```

The URL generated looks like /view/{{item.id}} instead of /view/actual_id

**Comment by arthurevans** [comment]
@Byronlee For `href`, we recommend using the attribute binding syntax:

https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#property-binding

@mschwartz String concatenation is currently not supported for data binding in 1.0. This is a well-documented limitation:

https://www.polymer-project.org/1.0/docs/migration.html#data-binding

The good news is, we think it should work, too :D ... this is on the roadmap for a future release.

**Comment by mschwartz** [comment]
Not hard to work around, by having the server add a url member:

```html
<a href="{{item.url}}">text</a>
```

that works, and isn't awful.

;)

**Comment by mschwartz** [comment]
It's also an issue for iron-ajax...

Consider pagination.

```html
<iron-ajax
    params="{ start: {{start}}, limit: {{limit}} }"
    ...
>
```

**Comment by arthurevans** [comment]
You can also use a computed binding, like:

    href$="{{urlForID(item.id)}}"

    ...

    itemForID: function(id) {
      return '/view/' + id;
    }

For the params case, you can also just pass in a params object.

    params="{{myParams}}"

**Comment by mschwartz** [comment]
Can you give a more detailed example of how to use href$?

For someone who never used 0.5, the 1.0 docs aren't that rich with examples of how to wire up things.  The HTML and Web Components are documented pretty good.

**Comment by arthurevans** [comment]
Just replace `href=` in your example with `href$=`.

`<a href$="{{foo}}">`  says, bind the anchor's `href` _attribute_ to the value of `foo`.

`<a href="{{foo}}">`  says, bind the anchor's `href` _property_ to the value of `foo`.

In _most cases_, you want to bind to an element's properties. But there are a few special cases where:

1) A native element (like `<a>`),
2) has a property (like `href`),
2) which is also exposed as an attribute.

And in these cases, sometimes binding to the property makes the browser throw a hissy fit. That's a technical term defined in the W3C specification, "Browsers and the weird stuff they make developers do."

Anyway, the attribute binding syntax works around that issue. There are a couple of other use cases for it, but as I said, most of the time you want a property binding. More info on attribute bindings here:

https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#attribute-binding
https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#native-binding

**Comment by mschwartz** [comment]
Awesome, that's exactly what I was looking for.
