### ISSUE TITLE
paper-autogrow-textarea inserting scrollbar on long text without breaks

### ISSUE THREAD

**Issue by arielkroszynski** [Polymer/polymer#1106]
when creating an autogrow text box, it grows nicely as long as no word is longer than the box width.
In case there is a long word, an undesired scrollbar appears.

see image below where the first word is longer than the text box width.
![image](https://cloud.githubusercontent.com/assets/10140055/5803218/1e8801ea-a005-11e4-856c-ec5d1eccc267.png)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
