### ISSUE TITLE
Conditional attributes with value (HTML5 forms)

### ISSUE THREAD

**Issue by jirihybek** [Polymer/polymer#1107]
When dynamically creating HTML5 form elements Iam missing possibility to remove attribute when binded value is undefined or null and set attribute value when non-empty.

For example:
```json
{
     "type": "text",
     "name": "first_name",
     "pattern": null
}
```

```html
<input type="{{field.type}}" name="{{field.name}}" pattern="{{field.pattern}}" />
```

Will result in:
```html
<input type="text" name="first_name" pattern />
```

When form is validated in Chrome field value is invalid because did not match the pattern.

There should be a solution where previous example will result in:

```html
<input type="text" name="first_name" />
```

**Comment by jirihybek** [comment]
I've solved it by modifying following function in NodeBind.js but I think that it will be great to add it to official version.

```javascript
  function updateAttribute(el, name, conditional, value) {
    if (conditional) {
      if (value)
        el.setAttribute(name, ( value === true ? '' : value )); //<--- HERE
      else
        el.removeAttribute(name);
      return;
    }

    el.setAttribute(name, sanitizeValue(value));
  }
```

**Comment by gertcuykens** [comment]
What happens when you do this `pattern?="{{field.pattern}}"`

**Comment by jirihybek** [comment]
When {{field.pattern}} is empty then attribute is not set, but when field.pattern is not empty, attribute is set without its value, so for example:

```json
{
     "type": "text",
     "name": "first_name",
     "pattern": "^[0-9a-z]+$"
}
```

```html
<input type="{{field.type}}" name="{{field.name}}" pattern?="{{field.pattern}}" />
```

Results in:
```html
<input type="text" name="first_name" pattern />
```

Instead of:
```html
<input type="text" name="first_name" pattern="^[0-9a-z]+$" />
```

It is because of original line of code, where attribute value is always se to empty string if conditional:

```javascript
  function updateAttribute(el, name, conditional, value) {
    if (conditional) {
      if (value)
        el.setAttribute(name, ''); //<--- HERE
      else
        el.removeAttribute(name);
      return;
    }

    el.setAttribute(name, sanitizeValue(value));
  }
```

**Comment by pflannery** [comment]
Alternatively you could set pattern to match any single character (minus line breaks) when the pattern variable is not set

```pattern="{{pattern ? pattern : '.*'}}"```

[example](http://plnkr.co/edit/Nrry8QXDL8oU4psypjx3?p=preview)

**Comment by wjmazza** [comment]
I personally preferred  putting it in my "ready" callback as such

```
ready: function(){
    var $input = this.$.input;
     if ( this.pattern ) {
        $input.setAttribute("pattern",this.pattern);
    }
},
```

**Comment by jirihybek** [comment]
@pflannery It is not only about pattern attribute, but about all others, such as ***min***, ***max***, ***maxlength***, etc...

@wjmazza Iam creating polymer-element which completly builds up an HTML5 form based on JSON schema from server-side, so checking every attribute in repeated template its really hacky and ugly solution, same as creating new polymer-element for every form field which will be wrapping attributes behaviour... and importat fact is that ***input*** element must be in same document root as ***form*** element or is ignored when submitting and validating...

As i metioned before in comment, modifing function in NodeBind.js is working and clean solution which can has wide usage...

**Comment by pflannery** [comment]
@jirihybek I agree with needing a solution and yours is on the money. 

One more alternative is to capture the changed event
```js
        patternChanged: function() {
          var el = this.$.input;
          
          if (this.pattern)
            el.setAttribute('pattern', this.pattern);
          else
            el.removeAttribute('pattern');

          this.notifyValidateChange();
        }
```

**Comment by jirihybek** [comment]
@pflannery It looks like good solution for few input fields, my case is little bit more complicated...

Simplified example of my case:
```html
<form on-submit="{{handleSubmit}}">
	<template repeat="{{group in groups}}">

		<h2>{{group.label}}</h2>
		
		<template repeat="{{field in group.fields}}">
			
			<p>
				<label for="field-{{field.name}}" required?="{{field.required}}">{{field.label}}</label>

				<!-- text-based fields -->
				<template if="{{field.baseType == 'text'}}">
					<input
						type="{{field.type}}"
						name="{{field.name}}"
						id="field-{{field.name}}"
						value="{{data[field.name]}}"
						placeholder?="{{field.default}}"
						pattern?="{{field.pattern}}"
						minlength?="{{field.minLength}}"
						maxlength?="{{field.maxLength}}"
						min?="{{field.min}}"
						max?="{{field.max}}"
						required?="{{field.required}}" />
				</template>

				<!-- checkbox -->
				<template if="{{field.baseType == 'checkbox'}}">
						<input
							type="checkbox"
							name="{{field.name}}"
							id="field-{{field.name}}"
							checked="{{data[field.name]}}"
							required?="{{field.required}}"
							on-change="{{save}}" />
				</template>

			</p>

		</template>
	</template>
</form>
```
So your solution will be complicated in this example...

My question is if its possible to consult / add my modification to official Polymer's library, should I wrote someone or post a pull request to NodeBind repo?

Thanks for advices...

**Comment by pflannery** [comment]
I see another problem with the original updateAttribute function:

```js
  function updateAttribute(el, name, conditional, value) {
    if (conditional) {
      if (value) //<--- HERE
        el.setAttribute(name, '');
      else
        el.removeAttribute(name);
      return;
    }

    el.setAttribute(name, sanitizeValue(value));
  }
```

if the value is ```0``` for ```min``` then the attribute is removed. I'm also wondering if any changes to the updateAttribute function could be a breaking change. 

So i've created a new solution which is to create a special conditional ```??``` just for the InputElement attributes (pattern, min, max etc....)

```js
    function updateSpecialConditionalAttr(el, name, value) {
      if (value !== undefined && value !== null && value !== '')
        el.setAttribute(name, value);
      else
        el.removeAttribute(name);
    }

    function specialConditionalAttrBinding(el, name) {
      return function(value) {
        updateSpecialConditionalAttr(el, name, value);
      };
    }

     // adds special conditionals ?? for use with attributes like pattern, min, max etc...
     // i.e. <input value="abc" pattern??="[a-z]"> or <input value="abc"> when pattern?? is not defined
    var inputElementBind = HTMLInputElement.prototype.bind;
    HTMLInputElement.prototype.bind = function(name, observable, oneTime) {

      var specialConditional = name.substring(name.length - 2) === '??';
      if (specialConditional) {
        this.removeAttribute(name);
        name = name.slice(0, -2);
        return updateSpecialConditionalAttr(
          this,
          name,
          observable.open(specialConditionalAttrBinding(this, name))
        );
      }
      // not a special conditional
      return inputElementBind.apply(this, arguments);
    }
```

[Working example](http://plnkr.co/edit/3rIMOqalp4nc0u1kLYXE?p=preview)

**Comment by jirihybek** [comment]
It looks good and can be implemented via script import, I will try it in my project... thanks...

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

**Comment by phasmal** [comment]
I found this while searching to do the same thing (add an attribute to an inner element conditionally based on an element's properties) - what feature of Polymer 1 implements this?

I'm using Polymer 1.6.1
