### ISSUE TITLE
Issue with webcomponents.js

### ISSUE THREAD

**Issue by hcho112** [Polymer/polymer#1108]
I'm having frequent problems when using Google Polymer with non-Chrome browsers (Firefox/IE). Using Polymer on its own (such as viewing Polymer Element demo pages) does not seem to cause any issues. However, issues arise when using webcomponents.js is included on an existing web-application with many included GUI and utility packages (jQueryUI, 

The issue seems to be related to webcomponents.js specifically. If no HTML imports are used and *only* webcomponents.js is imported, it throws the same error in both Firefox and IE:

    webcomponents.js:2114 - SyntaxError: An invalid or illegal string was specified
    webcomponents.js:113 - Error: Assertion failed

The specific line of webcomponents.js simply reads:

    list = originalDocumentQuerySelectorAll.call(target, selector);

\- which seems to have no immediately obvious syntax error.

Due to this error, other GUI elements on the page now exhibit erroneous behavior. There is no other useful console output provided when this happens, and no exceptions thrown by other JS packages. None of this behavior is shown when using Chrome.

**Comment by jannakha** [comment]
webcomponents.js is broken in Safari as well: a simple demo of paper drop down menu doesn't render. Error doesn't say much
```
[Error] TypeError: Attempting to configurable attribute of unconfigurable property.
	defineProperty (webcomponents.min.js, line 11)
	j (webcomponents.min.js, line 11)
	H (webcomponents.min.js, line 11)
	(anonymous function) (webcomponents.min.js, line 12)
	global code (webcomponents.min.js, line 12)
```

**Comment by arthurevans** [comment]
@hcho112 You might want to check out this SO answer:

http://stackoverflow.com/questions/24942308/platform-js-polymer-jquery-2-x-x-and-bootstrap-error

(And be sure you're including webcomponentsjs before other scripts that touch DOM.)

@jannakha What you're seeing sounds like a separate issue. If you're seeing this consistently, can you open a new bug on [webcomponents repo](https://github.com/webcomponents/webcomponentsjs/issues):

- URL where this occurs, or a minimal reproducible test case.
- Browser & OS version

For what it's worth, I'm not seeing this error on:

https://www.polymer-project.org/components/paper-dropdown-menu/demo.html

Tested on Safari 7.1.2 Mac and Safari iOS (8.1.1), both render correctly.

**Comment by jannakha** [comment]
@arthurevans polymer-project.org uses @version 0.5.1-1 version of webcomponents, so it works in Safari, would be great if polymer-project.org could upgrade to 0.5.3.

I'll submit a bug to webcomponentsjs team.
Cheers.

**Comment by ChenRoth** [comment]
having the same error (webcomponents.js:112) on IE (10+) /firefox

I'm developing an app in Meteor, using the meteor-polymer package (just a wrapper package to include webcomponents.js 0.5.4 and polymer.js)

**Comment by robdodson** [comment]
Worth a shot: Try upgrading to webcomponents.js 0.5.5 to see if it fixes the issue. Just ran into this issue on another project and the upgrade fixed it. YMMV

**Comment by ebidel** [comment]
Closing stale issues. Please reopen if you have a reproducible test on the latest polyfill.
