### ISSUE TITLE
Repeated template doesn't show in IE

### ISSUE THREAD

**Issue by tpluscode** [Polymer/polymer#1111]
Hi

I've been playing with polymer recently and I created a sample app, which is accessible [here](http://polymer-flux.t-code.pl/dist/). It works fine in latest Chrome and Firefox but somehow the nested components don't appear in IE10. It seems to work fine on the inside though as I see the requests and I can debug all internal code. There is no error, nothing. 

Could you please help me determine what the problem is?

Thanks,
Tom

**Comment by cdata** [comment]
Hi @tpluscode. I poked through your example in IE10 a little bit and noticed that at one point it is navigating to a bogus URL (`http://polymer-flux.t-code.pl/dist/undefined/dist/?uri=http://data.test.wikibus.org/` - note the `undefined` in the path).

I believe this is because in IE10, window.location.origin is `undefined`. Does fixing this bug result in the example working better?

**Comment by tpluscode** [comment]
Oh, sorry I was wrong about my browser. I use IE11 after all. I've fixed the `location.origin` but still both IE11 and emulated IE10 don't work. All the events fire but the UI doesn't appear.

**Comment by tpluscode** [comment]
I think there is a problem with `<template repeat="..." />. Notice how [this page](http://polymer-flux.t-code.pl/dist/?uri=http://test.wikibus.org/book/1936) shows an image but not the preceding content. The component is `[ld-resource](https://github.com/tpluscode/polymer-flux/blob/gh-pages/src/components/ld-resource.html#L6)`. The nested `sw-object` does not show at all but it is all [a repeating template](https://github.com/tpluscode/polymer-flux/blob/gh-pages/src/components/sw-object.html#L15). I tried adding some more content beside the repeater and it works.

Also it's not the `getValues()` call. I tried replacing that with a property with no difference in behaviour.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
