### ISSUE TITLE
Inspection.  Please run an inspection tool like WebStorm's inspect code.

### ISSUE THREAD

**Issue by electricessence** [Polymer/polymer#1114]
There are way too many consistencies and minor code no-nos that shouldn't be in here.
I thought about going through each one and logging an issue but there is over 200+.

![screen shot 2015-01-20 at 5 14 08 pm](https://cloud.githubusercontent.com/assets/5899455/5829488/c6e6d362-a0c7-11e4-8a55-1b833a250802.png)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
