### ISSUE TITLE
custom-element-file::shadow { custom css } does not work on Firefox and Explorer

### ISSUE THREAD

**Issue by LacikIgor** [Polymer/polymer#1115]
Hello,

Example - more details:
<ul>
  <li>
   I specified a <strong> hello-world.html </strong> document with a custom hello-world element
  </li>
  <li>
    Here I styled <code> h1 { color: #CCC; } </code> for this element
  </li>
  <li>
    In the main <strong> index.html </strong> document I use this custom element
  </li>
  <li>
    In <strong> index.html </strong> I styled <code> hello-world::shadow h1 { color: #F00; } </code>
  </li>
</ul>

In chrome, the h1 content of the custom element is red. 
In latest firefox and latest explorer 11 it remains CCC.

Hopefully this helps

**Comment by zoechi** [comment]
This might apply https://www.polymer-project.org/docs/polymer/styling.html#sdcss

**Comment by tcipierre** [comment]
Hi,

zoechl is right, I had it work on Firefox. However be careful with this one, it doesn't accept this :

```html
<link rel="stylesheet"  href="main.css" shim-shadowdom>
```

It only understands `shim-shadowdom` on a `<style>` element. You can find an easy workaround here :  https://github.com/noflo/noflo-ui/commit/3c6f8a5b8cfeed2b17530e28e7d9d2ef7b3ecda1

All the best.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
