### ISSUE TITLE
Dropdown Menu

### ISSUE THREAD

**Issue by andrewiharrison** [Polymer/polymer#1118]
When you first select the drop down menu, the transition is really smooth and nice.
However, the second time you click on it, it breaks and the transition goes out before it comes in again...

Not really sure how to stop that my end so hoping you guys can release a quick fix :)

Loving Polymer,
Andy

**Comment by namiheike** [comment]
Already mentioned and solved here: https://github.com/Polymer/paper-dropdown/issues/6

**Comment by andrewiharrison** [comment]
Ah okay, still not fixed then :/

**Comment by robdodson** [comment]
Closing this in favor of the linked issue.
