### ISSUE TITLE
TypeError: Attempting to configurable attribute of unconfigurable property.

### ISSUE THREAD

**Issue by Bor1s** [Polymer/polymer#1119]
Hello guys!

I'm using polymer 0.5.3 and core/paper components 0.5.3.
I've got an error in Safari (8.0.2), Mobile Chrome (IPad), Mobile Safari (IPad) that causes something on
webcomponents.js:317 - defineProperty.
```javascript
function defineGetter(constructor, name, getter) {
      getterDescriptor.get = getter;
      defineProperty(constructor.prototype, name, getterDescriptor);
    }
```
After debug, I found out that it fails with:
constructor.prototype -> GeneratedWrapper
name -> ownerSVGElement
getterDescription -> Object({configurable: true
enumerable: true})

**Comment by miztroh** [comment]
I get the same issue in Safari 7.1.2 on Mavericks (10.9.5).

**Comment by arthurevans** [comment]
0.5.4 is now out. It's the same as 0.5.3 except it reverts the problematic change.

Please update.
