### ISSUE TITLE
core-elements zip archive is empty.

### ISSUE THREAD

**Issue by spikewilliams** [Polymer/polymer#1120]
Go to https://www.polymer-project.org/docs/elements/core-elements.html , then click on Get Core Elements, then click on the button to download a zip archive. It will send an empty archive.

**Comment by LM450N** [comment]
I tried and I got properly the archive filled. If you have some browser add-ons, try disable blockers just for download the ZIP and/or use another browser.

If you want to build a project with Polymer, I recommend you to use [Bower][1] for manage the dependencies.


[1]:http://bower.io/

**Comment by spikewilliams** [comment]
That's interesting. I just tried in in two different browsers on a different machine on a different network - no blockers - and got an empty archive. I've been able to get full zip archives of other links on the site - just not that one.

I've yet to get Bower to work on Windows. For a dependency manager, it seems to have too many dependencies - meaning a whole lot of potential points of failure.  I did get it to work under an older version of Linux, but had to jump through quite a few hoops for that to work.

**Comment by spikewilliams** [comment]
I tried the downloading the archive again today, and it had the data in it. 

Could this problem perhaps be related to the time of day the download takes place? Or perhaps there are multiple servers that provide the archive, and some of them have the valid zip file, and some of them don't?

**Comment by LM450N** [comment]
I don't know. But when I downloaded the archive, it was pretty slow to start downloading. I think the archive was created on the fly to have the latest release available. Maybe sometimes the script fails to find data and sends an empty archive.

**Comment by ebidel** [comment]
The .zipper service has been known to fake out from time to time. That's amplified depending on where in the world you are :) At the moment if looks fairly stable.

**Comment by spikewilliams** [comment]
I'm in Trinidad.It wouldn't surprise me if there are some latency issues connecting from here. Ping times to bowerarchiver.appspot.com are on the order of 200-500 ms.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
