### ISSUE TITLE
A bunch of core-icons are gone. (0.5.4)

### ISSUE THREAD

**Issue by Kylo3** [Polymer/polymer#1121]
A lot of core-icons (especially in "social:" are now gone.  Is this intentional?  If so, why?  Even polymer-project.org looks strange because most of the icons can't load.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

**Comment by tjsavage** [comment]
Hm we had to remove a number of the old social: icons, but social:notifications should work. Could you post a simple repro?

**Comment by zoechi** [comment]
Here it's shown https://elements.polymer-project.org/elements/iron-icons?view=demo:demo/index.html&active=iron-icons. The demo just lists all available icons. 
Maybe you're missing some import.

**Comment by nicobrinkkemper** [comment]
I'm sorry. To anyone that comes across this: make sure to import the sets you need as stated in the docs:
```
<!-- icon sets -->
<link rel="import" href="/bower_components/iron-icons/iron-icons.html">
<link rel="import" href="/bower_components/iron-icons/social-icons.html">
<link rel="import" href="/bower_components/iron-icons/maps-icons.html">
```
