### ISSUE TITLE
webcomponents.min.js broken (0.5.4)

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#1122]
0.5.4 broke my page? webcomponents.min.js:11 Uncaught TypeError: undefined is not a function
where do I need to start looking?

**Comment by gertcuykens** [comment]
Dammit I imported the wrong file, jezus sometimes polymer is a jungle if you get errors like this, found it by pure luck.

**Comment by jdub108** [comment]
What was the correct file or what was the error? I'm having the same problem.

**Comment by gertcuykens** [comment]
Just take a look at all your import statements, one of them will be wrong.
