### ISSUE TITLE
core-drawer-panel cannot handle z-index correctly

### ISSUE THREAD

**Issue by cn123h** [Polymer/polymer#1123]
If there are some elements with positive z-index defined in "main" part. The "drawer" part popup will be covered by these element.

I fixed this by adding a z-index for "core-selector > #drawer" in core-drawer-panel.css.

polymer version: 0.51
for all browsers

**Comment by bv-vd** [comment]
Same issue. Needed to set z-index and position to the element (I only have one) in "main" part to workaround

**Comment by jilt** [comment]
thanks :)

**Comment by jilt** [comment]
you may also change the #scrim z-index on same file, assuming you're using backdrop

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
