### ISSUE TITLE
IE 10+11 + data binding in inline style not working in Polymer v0.5.4

### ISSUE THREAD

**Issue by eeid26** [Polymer/polymer#1124]
Works under chrome and ff but not ie
http://jsbin.com/xoremiwite/2/edit

**Comment by sjmiles** [comment]
IE doesn't allow `{{ }}` in the value of the `style` attribute, use `_style` instead.

See information here https://www.polymer-project.org/docs/polymer/databinding-compat.html#binding-to-attributes

**Comment by eeid26** [comment]
Thank you. it works now. I don't know how I missed that compatibility note.

**Comment by sjmiles** [comment]
This information should be more prominent, this is a common problem.
