### ISSUE TITLE
FireFox : After Dialog Toogle and Ajax Reload, Elements are broken

### ISSUE THREAD

**Issue by DSigmund** [Polymer/polymer#1125]
Dear Devs,

I Am experiencing the following Issue:

- I am having an index.html with all Imports, etc.
- In there, Content is loaded via an Ajax Call
- The Content contains polymer buttons and a dialog.
- I toogle the dialog twice (eg open / cancel)
- i am getting the same content via ajax again
- >>> Now the polymer items dont exist anymore (eg cant toggle the dialog ("has no such method")

The Problem only occurs in Firefox, where i am using webcomponents.js

Any Ideas?

Many Thanks in Advance,
Dominik

**Comment by DSigmund** [comment]
I did a workaround:

If i take the dialogs into my index.html, the problem will not persist.

But i'd really like to keep them seperated ...

**Comment by ebidel** [comment]
Hi @DSigmund, it's hard to say whether this is a Polymer issue or one with your setup. Please post working code when filing issues.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
