### ISSUE TITLE
body[unresolved] not getting resolved because of something related to a custom element's script tag

### ISSUE THREAD

**Issue by ekantola** [Polymer/polymer#1130]
Something related to &lt;script> elements inside custom element templates is causing the [unresolved] attribute to not getting removed from &lt;body> element with Polymer version 0.5.4. Similar situations may cause hard-to-debug problems since no errors are thrown. Test case below.

Main HTML file, test.html:

    <!DOCTYPE html>
    <html>
    <head>
        <script src="bower_components/webcomponentsjs/webcomponents.js"></script>
        <link rel="import" href="foo-elem.html">
    </head>
    <body unresolved>
        <div>Bar</div>
    </body>
    </html>

Custom test element, foo-elem.html:

    <link rel="import" href="bower_components/polymer/polymer.html">
    <polymer-element name="foo-elem">
        <script> </script>
    </polymer-element>

Polymer installed with Bower.

Note the single space inside the &lt;script> element. With affected browsers, opening test.html does not show anything. But either one of the following things makes the text "Bar" appear on the page:

- Remove the space from between &lt;script> start and end tags.
- Add a "noscript" attribute to the polymer-element.

Affected browsers:

- Chrome 40.0.2214.93 (64-bit) on OSX 10.10.1
- Chrome 42.0.2289.0 canary (64-bit) on OSX 10.10.1
- Chrome 38.0.2125.111 m (32-bit) on Windows 7 v6.1.7601
- Internet Explorer 11.0.9600.17358 on Windows 7 v6.1.7601 (also with IE10 emulation mode)
- Firefox 35.0.1 (32-bit) on Windows 7 v6.1.7601
- Opera 27.0.1689.54 (64-bit) on OSX 10.10.1

Not affected:

- Firefox 35.0.1 (64-bit) on OSX 10.10.1

**Comment by ikeagold** [comment]
Can anyone test it on current polymer builds and browsers?

I meet almost same issue with my project in Chrome Canary (46.0.2468.0 canary (64-bit) /win) with Polymer 1.0.8, but... its working fine in Chrome Stable (44.0.2403.125 m /win).

**Comment by azakus** [comment]
Closing due to age.
