### ISSUE TITLE
[0.8-preview] Boolean attribute change handlers are called before `localDom` or `lightDom` are available.

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer#1131]
Considering the following contrived element built on 0.8-preview branch:

```html
<script>
Polymer({
  is: 'simple-element',
  published: {
    awesome: Boolean
  },
  bind: {
    awesome: 'awesomeChanged'
  },
  ready: function () {
    console.log('I am ready.');
  },
  awesomeChanged: function () {
    if (this.lightDom && this.localDom) {
      console.log('I has a DOM');
    } else {
      console.log('I do not has DOM');
    }
  }
});
</script>
```

The first time `awesomeChanged` is called will happen before `this.lightDom` and `this.localDom` have been initialized on the element. It will also be called before the `ready` lifecycle handler has been called, which may or may not be intentional, but seems undesirable on the surface.

**Comment by cdata** [comment]
@sorvell Related to your `configure` implementation: the above described behavior is a little awkward because `*Changed` handlers will get called as defaults are assigned from the set of values yielded by `configure`. In order to work around this, one would have to measure the initialization state of other self-properties before taking action in a `*Changed` handler that references those properties (particularly if those properties are `Object` or `Array` types).

**Comment by arthurevans** [comment]
Could we just suppress change notifications that occur before ready? I know
on 0.5 people get confused by multiple change events, or values that get
bound before they're assigned (not sure if that's one issue or two).

**Comment by addyosmani** [comment]
> The first time awesomeChanged is called will happen before this.lightDom and this.localDom have been initialized on the element. It will also be called before the ready lifecycle handler has been called, which may or may not be intentional, but seems undesirable on the surface.

Would a scheduler that queued up change notifications fired prior to the lightDOM, localDOM and ready methods be desirable here? I'd personally find notification suppression a little hard to debug.

**Comment by cdata** [comment]
Since `configure` is intended to specify defaults (to my understanding), setting properties with the "configured" default should never trigger a `*Changed` handler. To me, "changed" implies that there has been a change from the initialized state. If that is the intended meaning, it may be the case that these handlers are bound too early in the lifecycle.

**Comment by sorvell** [comment]
lightDom and localDom have been removed via https://github.com/Polymer/polymer/commit/7c7e426c8fdd5a326525bb1953b8ee59ad83e448.

**Comment by sorvell** [comment]
Configure is functioning according to the current design. Let's open a separate issue to discuss that if necessary. Closing this one.
