### ISSUE TITLE
typo in paper-elements docs

### ISSUE THREAD

**Issue by sixsided** [Polymer/polymer#1135]
On this page:

https://www.polymer-project.org/docs/elements/paper-elements.html#paper-input-decorator

This sample code:

    paper-input-decorator[focused] /deep/ .floating-label .label-text {
        /* floating label color when the input is focused */
        color: orange;
    }

should read:

    paper-input-decorator[focused] /deep/ .floated-label .label-text {
        /*                                ^^^^^^^^^^^^^^               */
        color: orange;
    }

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
