### ISSUE TITLE
core-icons post-* gone

### ISSUE THREAD

**Issue by kevohagan** [Polymer/polymer#1136]
I am using these icons for this package https://github.com/meteor-useraccounts/polymer and with 0.5.4 the post-* icons are depreceated. What would be the alternative? 

Thanks so much for all the work guys!!

**Comment by Kylo3** [comment]
What I ended up doing is downloading core icons version 0.5.2 (as a zip from GitHub), putting it in my bower_components folder, and imported that core-icons-0.5.2 instead.

**Comment by zoechi** [comment]
Seems there were originally icons include which were not intended to be. see https://github.com/Polymer/blog/pull/25/files 
Sounds like they might come back eventually.

**Comment by kevohagan** [comment]
so i guess just wait and see

On 29 January 2015 at 09:53, Günter Zöchbauer <notifications@github.com>
wrote:

> Seems there were originally icons include which were not intended to be.
> see https://github.com/Polymer/blog/pull/25/files
> Sounds like they might come back eventually.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Polymer/polymer/issues/1136#issuecomment-71989908>.
>



-- 
Kevin O'Hagan
@kevohagan
+0034685245319
Palma de Mallorca,
Spain

**Comment by ebidel** [comment]
Closing stale issues. Please reopen on the appropriate element repo if you'd like to see something added.
