### ISSUE TITLE
Error improvement misspelled import

### ISSUE THREAD

**Issue by amannn** [Polymer/polymer#1137]
Currently when I misspell an HTML import I get the following error on webcomponents.js:30:
```
Uncaught TypeError: undefined is not a function
```
This is resolved when the HTML import works. It would help a lot if the error would help pointing out what the actual problem is and which import failed.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
