### ISSUE TITLE
[0.8-preview] detached not getting called when the element being removed is in the localDom of another element.

### ISSUE THREAD

**Issue by frankiefu** [Polymer/polymer#1145]
Under CustomElements polyfill (e.g. Safari, Firefox), detached is not getting called when trying to remove an element (x-foo) which is in the localDom of another element (x-app).
```
<script>
  Polymer({
    is: 'x-foo',
    detached: function() {
      console.log('x-foo.detached');
    }
  });
</script>

<dom-module id="x-app">
  <template>
    <x-foo id="foo"></x-foo>
  </template>
</dom-module>

<script>
  Polymer({
    is: 'x-app',
    removeFoo: function() {
      this.$.foo.remove();
    }
  });
</script>
```

In the above, calling removeFoo() will not trigger x-foo's detached callback.

This is because in [ready.html](https://github.com/Polymer/polymer/blob/0.8-preview/src/features/mini/ready.html#L56), `host` is being added to the element but in [CustomElements/observe.js](https://github.com/webcomponents/webcomponentsjs/blob/master/src/CustomElements/observe.js#L166) we also use `host` to determine if the element is inDocument.

**Comment by sorvell** [comment]
Fixed via https://github.com/webcomponents/webcomponentsjs/commit/a8ec8d6a4d54d0b4d24795ad49d3ea37dbbede97
