### ISSUE TITLE
Ripple does not work on re-attached component

### ISSUE THREAD

**Issue by dstefanox** [Polymer/polymer#1148]
Appearence:
paper-button is added to page, it works as expected (ripple works). Then, button is removed from the DOM tree (button object still exists). Removed object is then added back to the page. Ripple does not work anymore.

How to reproduce (code snippet to add to page):

<div id="holder">
    <paper-button id="to_remove">Click me</paper-button>
    <paper-button id="remover" onClick="removeit();">I remove!</paper-button>
</div>

  <script type="text/javascript">
    var removed = false;
    var toRem = document.querySelector('#to_remove');
	function removeit() {
		if (!removed) {
			toRem.parentElement.removeChild(toRem);
			removed = true;
		} else {
			var toHold = document.querySelector('#holder');
			toHold.appendChild(toRem);
			toRem.pressed = false;
			removed = false;
		}	
	}
  </script>

**Comment by alxhub** [comment]
+1, seeing this as well.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
