### ISSUE TITLE
[0.8-preview] Cannot bind `this` in template using `{{}}` or `[[]]`

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer#1150]
In 0.5.x, it is possible to bind to `this` in a template by using an empty `{{}}`. For example:

``` html
<template>
  <x-foo target="{{}}"></x-foo>
</template>
```

The above would previously bind to the model `this`. In 0.8-preview, it generates a syntax error along the lines of:

``` javascript
(function(old
/**/) {
this._nodes[0].value = this._data.;
})
```

**Comment by justinfagnani** [comment]
I hit this recently myself :)

**Comment by pflannery** [comment]
+1

**Comment by jogibear9988** [comment]
I've tried, does also not work in Polymer 2.0

I've changed the RegEx in "property-effects.html" line 820 to match also the empty brackets, but there's still some work to do when the bindings are run. I've not yet looked where this is done!

**Comment by TimvdLippe** [comment]
You can implement this in Polymer 2: http://jsbin.com/pogezub/3/edit?html,console,output Since there is an API to write these custom extensions, we are inclined to not incorporate this into Polymer core. Therefore I am closing this issue.
