### ISSUE TITLE
Conflict between Polymer (webcomponents.js) and Highchart (highcharts.js) 

### ISSUE THREAD

**Issue by hcho112** [Polymer/polymer#1154]
In IE, if I use Polymer and Highcharts together, it does not display things properly. Detailed descriptions are already posted on stackoverflow: 

http://stackoverflow.com/questions/28205698/conflict-between-google-polymer-and-highcharts-library

The live demo is available on jsfildde:

http://jsfiddle.net/epavak4y/2/

The example codes used on jsfiddle is copy of highchart demo. (Noticed that Issue only occurs on IE. Tested with IE11)

**Comment by hcho112** [comment]
Here are the response from Highcharts Support team:
-------------------------------------------------------------------------
For some reason IE is not able to calculate the bounding box of text elements in this case. The problem arises on this line: https://github.com/highslide-software/highcharts.com/blob/master/js/parts/SvgRenderer.js#L616 .

An error is thrown on element.getBBox(), and the message is "Invalid calling object". You can debug this by adding a console.log(e.message) inside the catch statement.

Why this happens is another case. The element is an SVG text element, and other browsers have no problem with it. You could take this back to the Polymer developers so they can take it further.

For the records, I have tried rendering Highcharts to hidden or disconnected nodes, but that too works well, so it is not the reason why the elements don't have a bounding box: http://jsfiddle.net/highcharts/721to3sj/
----------------------------------------------------------------------------------------------------------------------------

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
