### ISSUE TITLE
Polymer.mixin2 undefined

### ISSUE THREAD

**Issue by wintersandroid** [Polymer/polymer#1155]
Trying to verify our applications under firefox, 35.1 we get a console error 
TypeError: Polymer.mixin2 is not a function on the paper-dropdown-menu (the first one it hits).

The app appears to stop, we see nothing.. Chrome works good and there is no console output like the above.

Unfortunately, I have someone breathing down my back wanting to make sure our apps work on at least Firefox.

I am unable to get anything other than the basic tutorial to work under current firefox.

Using polymer .54

**Comment by ericeslinger** [comment]
I'm getting the same error - the application loads okay in safari and chrome, but in ff 37.0.1 the unresolved stuff never falls off my body tag, and I get TypeError: Polymer.mixin2 is not a function in core-tooltip line 211.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
