### ISSUE TITLE
Paper Elements > Dropdown > Function deprecated soon

### ISSUE THREAD

**Issue by MasamuneCode** [Polymer/polymer#1157]
On dropdown page, 1st scrolling and margin, open and close it.
Got this message in console (firebug & IE debug)

Web Animations: AnimationTiming.playbackRate is deprecated and will stop working on Sat Feb 28 2015. Use AnimationPlayer.playbackRate instead.

Cheers

**Comment by CoreMaker** [comment]
The message belongs to [web-animations-js](https://github.com/web-animations/web-animations-js) which indicates that the animation standard will be changed on that date.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
