### ISSUE TITLE
Custom event on detached lifecycle method fails

### ISSUE THREAD

**Issue by omerts** [Polymer/polymer#1159]
I would like to fire a custom event when an element is detached, but it results in a js error.
My code is:
```
detached: function() {
  this.fire("detached");
}
```
The error is:
Uncaught TypeError: Cannot read property 'dispatchMethod' of undefined

**Comment by miztroh** [comment]
As a workaround, you can just set up a mutation observer on the parent element and listen for changes to its children.

https://www.polymer-project.org/docs/polymer/polymer.html#onMutation

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
