### ISSUE TITLE
<link> doesn't work with XD resources

### ISSUE THREAD

**Issue by mattiasmak** [Polymer/polymer#116]
This is perhaps a known issue, but I'll report it anyway.

Inside a component, the link-tag for referencing css is not working at all for me. To get around the problem I use @import inside the style tag.

<style>
@import url(http://url.com/mystyle.css);
</style>

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) release of Polymer - please feel free to re-open if this is incorrect.
