### ISSUE TITLE
Inconsistent behaviour with attributes and linked/inline stylesheets

### ISSUE THREAD

**Issue by pedro2555** [Polymer/polymer#1160]
# The problem

In inline styles is possible to pass to CSS properties the a value of an element attribute, however, that is not possible with linked stylesheets.

# Reproduce it

Assume the element declaration a)

	[some-element-name.html]
	<polymer-element name="some-element-name" attributes="width">
		<template>
			<style>
				:host {
					width: {{width}}px;
				}
			</style>
		</template>
	</polymer-element>

And b)

	[some-element-name.html]
	<polymer-element name="some-element-name" attributes="width">
		<template>
			<link rel="stylesheet" href="some-element-name.css">
		</template>
	</polymer-element>

	[some-element-name.css]
	:host {
		width: {{width}}px;
	}

And the instantiation:

	<some-element-name width="100">

For case a) the element style is assigned as follows:

	width: 100px;

and for case b)

	width: px;

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
