### ISSUE TITLE
property changed event fired before dom updated.

### ISSUE THREAD

**Issue by TimWillis** [Polymer/polymer#1164]
I have a list where I want to highlight the first item in the list. This list is dynamically populated with an ajax call. I use the listChanged event to listen for the list to be updated, at which time I re-highlight the first item in the list. Can't use css as I need the first item to not always be highlighted as the user mouses over different parts of the list. 
The problem is when I try to change the css property of the first item, the first item has not been created in the dom yet, so my css change does not take effect and the first item shows up un-highlighted. I have to put a timeout to get this to work as follows:
    listChanged: function (oldValue, newValue) {
        setTimeout(() => {
            this.hoverChange(false);//highlight first item
        }, 20);
    }
Is there a better way to do this, another event to listen for, or will this be fixed in another release. The fix I have in now is way to hacky.

Thanks and great work on Polymer

**Comment by miztroh** [comment]
You should add a mutation observer to the parent element that will let you know when its children change.

https://www.polymer-project.org/docs/polymer/polymer.html#onMutation

**Comment by TimWillis** [comment]
Thanks, I was looking into doing something like that after I sent the
email. I just wasn't sure if Polymer had plans to change this behavior or
not.

thanks
Tim

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
