### ISSUE TITLE
horizontal layout wrap doesn't work on safari

### ISSUE THREAD

**Issue by emmanuelbuah** [Polymer/polymer#1166]
I have tried this a couple of times but children of a parent div with horizontal layout wrap don't wrap in safari. It works in Chrome (using v41) and firefox (using v.35.0.1). Using Polymer v0.5.4

**Comment by frankiefu** [comment]
It seems to work for me on Safari 8: http://jsbin.com/sosimetude/1/edit

**Comment by emmanuelbuah** [comment]
@frankiefu  Thanks for the jsbin. I modified your sample code to conform to my use case to reproduce the issue here: http://jsbin.com/gixixevujo/2/edit. When you adjust the width of the window, you can tell its doesn't wrap in safari but it does in chrome and firefox. This seems to occur when the children element have percentage width, with a min-width.

**Comment by emmanuelbuah** [comment]
@frankiefu Want to check if this bug is planned for a release. I have an app out which relies on this layout. I'm hoping to tell my users till will be fixed soon.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
