### ISSUE TITLE
Event not propagated to firing element if bubbling disabled

### ISSUE THREAD

**Issue by fedy2** [Polymer/polymer#1167]
I'm firing an event Y from an element X and listening for the same event Y in X.
When the event's flag canBubble is set to false the event is not propagated to the listener in X, otherwise with the flag set to true it works fine.

Here a test: http://jsfiddle.net/Fedy2/hg4kn9Lf/4/

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
