### ISSUE TITLE
`injectBoundHTML` :: event handlers binding fails

### ISSUE THREAD

**Issue by mudasobwa** [Polymer/polymer#1170]
Let’s consider we inject a shadow DOM nodes in existing web component:

```js
      myHandler: function() {},
      myCaption: '¡Hola!',
      domReady: function() {
        // this.eventController = this;
        var nodes = this.$.content.getDistributedNodes();

        for(var node in nodes) {
          var elem = ...;
          this.injectBoundHTML(
            '<paper-button on-tap="{{myHandler}}">{{myCaption}}</paper-button>', 
            elem
          );
        }
      }
```

Everything works fine save for binding event handlers (`myHandler`.) It fails to bind (well, it binds, but no one of it’s parents has `eventController` attribute defined and (due to `findController` is unable to find a controller) dispatching events fails with 

> Uncaught TypeError: Cannot read property 'dispatchMethod' of undefined

One might fix a problem by uncommenting line `this.eventController = this;` in the very beginning of custom `domReady` handler, but it does not seem to be evident hack. 

Quick fix might be to move `this.eventController = this` from `polymer.js:lightFromTemplate` to `polymer.js:attachedCallback` (did I miss smth?)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
