### ISSUE TITLE
Polymer is failing silently without any console error

### ISSUE THREAD

**Issue by harshavidao** [Polymer/polymer#1171]
I have bower_components loaded in a different place and created a softlink at the index.html page.So it looks like everything is loading without any problem but not displaying anything in the page.I tried to break the link then it gives the console error.So i assume that everything is loading up but not displaying...Please any suggestions

**Comment by winhowes** [comment]
Do you have a link to what you're working on?

**Comment by jariz** [comment]
I've seen this before on my own project, happens for me when I have a <polymer-element>  without a script tag in it.
Either use 'noscript' attribute or add a script tag to your <polymer-element>.

**Comment by harshavidao** [comment]
Here is the solution it got solved by doing this.I provided polymer element names for every element inside the script tag for example Polymer("element-name"{}). If you are having multiple elements in single page we need to name the polymer-element inside the script tag. This solution seems to be meaningless but i got it solved by using this.
