### ISSUE TITLE
Paper-button does not trigger submit/reset in form

### ISSUE THREAD

**Issue by winhowes** [Polymer/polymer#1173]
I'm not sure whether or not this was intended, but as I'm using paper-buttons to replace normal buttons, I expected them to trigger submit (or reset) events when placed in a form. Unfortunately, they do not do so, but it'd be great if they would!

**Comment by morgs32** [comment]
I agree

**Comment by zoechi** [comment]
http://stackoverflow.com/questions/24867107

**Comment by winhowes** [comment]
Right, there are absolutely work arounds to submit a form with `<paper-button>`'s, it'd just be nice to have that by default or at least as an attribute

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
