### ISSUE TITLE
"action" attribute on custom elements is converted into a url

### ISSUE THREAD

**Issue by filaraujo** [Polymer/polymer#1175]
Any custom element that has an "action" attribute has that attribute automatically converted into a url.

This can be fixed by only targeting form action attribute

https://github.com/Polymer/polymer/blob/c7169640c567fb9bc709207ecbd9f747f8df48d5/src/lib/url.js#L78

**Comment by silentHoo** [comment]
+1

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
