### ISSUE TITLE
DOM element not available in *dynamic* template with "if"

### ISSUE THREAD

**Issue by richieb** [Polymer/polymer#1176]
If we update a bound property (*showVote*, in this case) to show a template sometime after the DOM initially updates, we can't select elements (neither with *querySelector* nor Polymer's automatic node selection):
```
 <template if="{{showVote}}">
   <div id="voteBtn"> Vote </div>
   <button on-tap="{{enableVoteText}}">enable vote text</button>
 </template>
```

```javascript
<script>
Polymer( {
showVote:false,
enableVoteText:function () {
  this.showVote = true;
// None of these works
var voteBtn = this.shadowRoot.querySelector ("#voteBtn");
var voteBtnTryAgain = document.querySelector ("body /deep/ #voteBtn");
var voteBtnUsing$ = this.$.voteBtn;
}
});
</script>
```

**Comment by miztroh** [comment]
Stamping out dynamic template content takes time.  Try wrapping your code in an async call

```
enableVoteButton: function () {
	this.showVoteButton = true;

	this.async(
		function () {
			console.log(this.shadowRoot.querySelector('#voteBtn'));
		},
		null,
		100
	);
}
```

**Comment by richieb** [comment]
Thanks for your reply, @miztroh. That appears to work. 

Since you are here, note that the following, both from the Polymer documentation:

```
// this doesn't work (get an error)
<div style="color: {{color}}">{{color}}</div>

this works:
<div style="{{styles | styleObject}}">...</div>

```

**Comment by miztroh** [comment]
Per https://www.polymer-project.org/docs/polymer/databinding-compat.html, try `_style` instead of `style`.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
