### ISSUE TITLE
Ternary operator with filter function throws syntax error

### ISSUE THREAD

**Issue by richieb** [Polymer/polymer#1178]
Using the ternary operator plus a filter function throws a syntax error.

This throws an error:
```
<div>{{ data.name === 'Tom' ? {accountData: data.accounts.tom, name: data.name} | modifyTomAccount : data.name }}</div>
```

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
