### ISSUE TITLE
[0.8-preview] Using reserved name for computed property fails silently in 0.8

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#1179]
Creating a computed property that uses a built-in element property fails silently. Consider:

```
computed: {
  style: 'computeStyle(color)'
},
```

If I bind to `{{style}}`, I can see the `computeStyle` method being called, but there's no output at all.

In 0.5, the same code logs a warning. And the binding value appears as "[object CSSStyleDeclaration]" which is also kind of a big hint. These mistakes are really easy to make, we should warn if at all possible.

**Comment by TimvdLippe** [comment]
This seems to be fixed in Polymer 2: http://jsbin.com/yepuqixaxu/edit?html,console,output
