### ISSUE TITLE
core-selector not correct for core-menu

### ISSUE THREAD

**Issue by Baze985** [Polymer/polymer#1183]
I played around with core-menu holding at least one core-submenu. 
If on this menu(core-selector) we add a core core-select eventHandler, then the both, fired value and the value in menuEl.selected are not correct. If a submenu itemEl is clicked then fired value is always the one from the submenu...exp

menu
++ item 0
++ item 1
++ submenu 
       ++ item 2
       ++ item 3

in this structure if item3 is clicked, then menu.selected holds '3' as a selected position. This is like this I guess because the 'core-selected' class is set on the both. I guess needs to be set just on the item3 and sub-manu need to hold some other class for making it highlighted .

Olso one other question, Is there a chance that we can disable the automatic closing of the previus opened submanu when we jump to a diferent navigation position which is not the same as the actual submanu? Making it act as a normal tree structure...

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
