### ISSUE TITLE
core-color component

### ISSUE THREAD

**Issue by AaronLayton** [Polymer/polymer#1185]
An idea for a new utility element (if something like this doesn't already exist). 

Set an inputColor and have the core-color figure out what the closet pallet color is based on the Material Design pallet
http://www.google.co.uk/design/spec/style/color.html#color-color-palette

```html
<core-color inputColor="#ff0000" mainColor="{{ backgroundColour }}" textColor="{{ textColor }}" format="#hex"></core-color>
<!-- backgroundColour == #b71c1c -->
<!-- textColor == #fff -->
```

Let the input color be anything
* Web Safe
* HEX
* #HEX
* RGB
* RGBA
* HSL
* HSLA
* CMYK

Let the user specify the format they want to retrieve the color as

**Comment by AaronLayton** [comment]
I would change this to `iron-color-picker` ?

**Comment by addyosmani** [comment]
Going off an idea from your other ticket, I've been building out elements that pick the dominant colors from a supplied image and generate a palette of colors (vibrant, muted etc) that can be used to theme other pieces of UI:

![screen shot 2015-09-01 at 13 47 34](https://cloud.githubusercontent.com/assets/110953/9604506/0726d830-50b0-11e5-8681-656ec6256fdc.png)

Some of this might make it into one of my talks at the Polymer Summit, but I'll look at refactoring them into something more generic if the team thinks that would be useful.

**Comment by AaronLayton** [comment]
That's great @addyosmani you preview looks good, anything we can look at now or wait until after the Summit?

**Comment by addyosmani** [comment]
It hasn't been code reviewed by the team yet I'm afraid. It'll probably be after the summit before they have a chance to look it over :)

**Comment by azakus** [comment]
This issue was moved to PolymerElements/paper-elements#67
