### ISSUE TITLE
How Polymer handle elements' model communication?

### ISSUE THREAD

**Issue by Colstuwjx** [Polymer/polymer#1187]
HI, I am new to polymer, and I just wonder how to handle the model communication between two elements. It just like:

```
    <!-- this is the parent element which contain session model -->
    <polymer-element name="gaea-router" attributes="routers">
        <template>
            this is user {{  session.username }}
            <gaea-scaffold>...</gaea-scaffold>
        </template>
    </polymer-element>

    ...
    <!-- this is the child element -->
    <polymer-element name="gaea-scaffold">
        <template>
            <!--  How to get session model??? -->
            <!-- BTW, How to get the parent element attributes??? -->
        </template>
    </gaea-scaffold>
```

Wishes your reply, many thanks!!!

**Comment by cedric-marcone** [comment]
Hello, @ebidel got you covered and wrote an article (Communication & Message Passing) on the polymer website. Every possible ways are described : binding, watchers, events & signals and using an element’s API.
https://www.polymer-project.org/articles/communication.html

**Comment by Colstuwjx** [comment]
Thanks a lot to your reply!!!!

**Comment by dongyang03** [comment]
@cedric-marcone  404 the  url https://www.polymer-project.org/articles/communication.html

**Comment by donmccurdy** [comment]
Both articles above are a 404 for me now, latest I can find is here:

https://docs-05-dot-polymer-project.appspot.com/0.5/articles/communication.html

^Although this refers to Polymer 0.5.

**Comment by arthurevans** [comment]
Two videos that might be helpful for general design principles:

Thinking in Polymer:
https://www.youtube.com/watch?v=ZDjiUmx51y8

Data Flow in Polymer Elements and Apps:
https://www.youtube.com/watch?v=pAW4YDLtPVs

**Comment by jfrazzano** [comment]
Is there a work around to get the hoist a new on a generator  used to grab.  

It allowed an app wide value handler to maintain state across elements and local moderators. 

It kicks against the straight line down flow of the more recent data binding model

But it provided a shortcut in 2.0 to replicate some of the 1.5 data flow. 

If not thanks for the work Arthur.
