### ISSUE TITLE
How to use external css file in polymer element?

### ISSUE THREAD

**Issue by Colstuwjx** [Polymer/polymer#1189]
I just want to reuse external opensource file, just like semantic-ui, but I'm confused that how to combine it with polymer element:

```
<polymer-element name="gaea-tplts">
    <template><!-- how to use semantic-ui here??? --></template>
</polymer-element>
```

Thanks.

**Comment by IntranetFactory** [comment]
I think it's not possible to use an existing CSS to style elements in the shadow dom. 

For Semantic-UI I yesterday started a fork where I wrap all definitions into html /deep/ (see https://github.com/TangereJs/Semantic-UI/blob/Carbon/dist/components/button.css for a sample). 

You can now embed the semantic.css from https://github.com/TangereJs/Semantic-UI/blob/Carbon/dist/components/button.css in your page and then use their classes in your custom elements.

**Comment by Colstuwjx** [comment]
Thanks for your distribution. You just mean that I can never use another jquery libraries until it has offered a Polymer version(add html /deep/ to it)?

**Comment by zoechi** [comment]
As far as I saw Polymer 0.8 should make it easier to create Polymer elements without shadow DOM. Then it should be easy to use other CSS/JS libs with Polymer. Currently it's like http://stackoverflow.com/questions/26702025 (couldn't find a pure JS example but I'm sure there is one on SO).

**Comment by pflannery** [comment]
if you want to just wrap css with a specific selector like ```html /deep/``` then this should do the trick - https://github.com/everything-polymer/polymer-scope-css

then just place something like this in your index.html page - 
```html
<link rel="stylesheet" href="url/to/semantic-ui.css" scope="html /deep/ ">
```

It can also let you do something like this
```html
<!-- in your index.html -->
<link rel="stylesheet" href="url/to/bootstrap.css" scope="html /deep/ .bootstrap ">

<!-- in your custom polymer element -->
<polymer-element name="custom-element" noscript>
  <template>
    <div>
      <strong>Element Scope</strong>
      <div class="btn btn-default">No style applied</div>
    </div>
    <br />
    <div class="bootstrap">
      <!-- everything here will use the boostrap styles -->
      <strong>Bootstrap scope</strong>
      <div class="btn btn-default">Default Button</div>
      <div class="btn btn-primary">Primary Button</div>
    </div>
  </template>
</polymer-element>
```

It basically just applies ```html /deep/ ``` to each css selelctor (including inside media queries).

**But** if you also want javascript from other libraries to play nice then **as** @zoechi has pointed using elements without the shadow dom is the way to go.
```js
// a no shadow dom element
Polymer({
    // overrides existing parseDeclaration implementation
    parseDeclaration: function(elementElement) {
      var template = this.fetchTemplate(elementElement);
      if (template) {
        var root = this.lightFromTemplate(template);
      }
    }
});
```

**Comment by Colstuwjx** [comment]
Hi, @pflannery, are you just meanning that I must use lightDOM if I want to combine with Polymer & full semantic-ui?

**Comment by pflannery** [comment]
If your using an external library not made for the Shadow DOM then **yes** because any selectors it may rely on wont pierce the Shadow DOM boundary. But by putting all your HTML elements in to the Light DOM then your external library selectors can select them as it usually would (both css and javascript). When putting your elements in to the Light DOM make sure you also put their parent element (if any) in to the Light DOM, this will prevent any Shadow Boundaries getting in the way.

However if your not using javascript and you want to use the Shadow DOM then you have a choice:

- In your element put a @import to the external css library the css style
- use [everything-polymer/polymer-scope-css](/everything-polymer/polymer-scope-css) which you can use to prepend a scope selector to all css selectors in the library. Using ```scope="html /deep/ "``` will mean your external CSS library will pierce the shadow boundary. You can also contain your external libraries with something like ```scope="html /deep/ .myLibContainer "``` which lets you keep library css separated

**Comment by Colstuwjx** [comment]
OK, Thanks.

**Comment by Colstuwjx** [comment]
Sorry, @pflannery , but I still feel confused to use it...

In my program, I use app-router to router the app pages, and it use import to load custom elements.
Just like:

```
        <app-router>
            <app-route path="/" import="/static/Gaea/elements/gaea-tplts.html" element="gaea-tplts" on-before-data-binding="{{bindSession}}" bindRouter>
            </app-route>
        </app-router>
```

If I just want to use semantic.js in custom element `gaea-tplts.html`, what should I do?
Now, it's

```
<polymer-element name="gaea-tplts">
    <template>
        <link type="text/css" rel="stylesheet" href="/static/sui/semantic.min.css">
        <link type="text/javascript" href="/static/js/jquery-1.11.0.min.js">
        <link type="text/javascript" href="/static/sui/semantic.min.js">
        <form class="ui form">
        ...
        </form>
    </template>
    <script>
        Polymer('gaea-tplts', {
            parseDeclaration: function(elementElement) {
                var template = this.fetchTemplate(elementElement);
                if (template) {
                    var root = this.lightFromTemplate(template);
                }
            }
        });
    </script>
</polymer-element>
```

But it didn't work...
What should I do??

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
