### ISSUE TITLE
how to capture image of polymer elements layout?

### ISSUE THREAD

**Issue by bhaveshvavdiya** [Polymer/polymer#1190]
I have created tabel layout.
Now i want to save as image, but I dont know how to capture image of layout.
Please help me.

Thank you all.

**Comment by IntranetFactory** [comment]
[This](http://meta.stackexchange.com/questions/18584/how-to-ask-a-smart-question) seems to be a good starting point to solve your problem

**Comment by AaronLayton** [comment]
@bhaveshvavdiya your question seems to have nothing to do with Polymer and instead seems to be something you are trying to solve. This issue should be closed off if that is the case.

Try this though, it may help http://html2canvas.hertzen.com/

**Comment by positlabs** [comment]
I use PhantomJS for this. http://phantomjs.org/

But yeah... not really a Polymer issue.

**Comment by bhaveshvavdiya** [comment]
Thanks for your answer.

As you know I am using Polymer and when I tried to capture image using html2canvas it give me nothing. Because html2canvas library is not recognize to get polymer DOM.
Please let me know if any other solution which I can recognize polymer DOM.

Thanks.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

**Comment by diegocerdan** [comment]
There is an issue open in html2canvas github: https://github.com/niklasvh/html2canvas/issues/430
