### ISSUE TITLE
Mobile Safari Infinite Loop: Polymer app in Mobile Safari runs non-stop. The Data Wheel is spinning non-stop for hours even without any user input...

### ISSUE THREAD

**Issue by cherukumilli** [Polymer/polymer#1193]
Any polymer app in Mobile Safari is running in an infinite loop. The same problem does NOT happen in Mobile Chrome browser on an IPhone.

You can recreate the problem by doing the following:
1. Start your app server (node or python webserver)
2. Start your iOS simulator
3. Open the Mobile Safari browser in the iOS simulator
4. Navigate to the  "pathTo/core-input/demo.html"  file in the mobile safari browser. You can observe that in the Mobile Safari Browser, the DATA WHEEL continues to spin forever. please see attached screen shot for the data wheel spinning and demo.html output in the mobile safari browser.
5. Start the Safari Browser on your desktop where you are running the iOS simulator
6. Open the Safari Web Inspector by going to the menu develop->iOS Simulator->xxx.xxx.xxx/demo.html
7. In the web inspector, go to Timelines
8. Click on the Network Requests
9. Click on the Record red button. You will see a stream of events in the "JavaScript & Events" section
10. Click on the "JavaScript & Events" in the left pane. You will see the attached Web Inspector screen.
11. You will see the events are trigger from polymer.js line# 8170 approximately every 13 seconds
12. Click on the event shows me the Attached screen with "function flush(){" as the function that is being called infinitely

![screen shot 2015-02-14 at 9 40 01 pm](https://cloud.githubusercontent.com/assets/5217007/6202235/9649cbcc-b492-11e4-8c83-2e6d9601e4bd.png)

![screen shot 2015-02-14 at 9 40 25 pm](https://cloud.githubusercontent.com/assets/5217007/6202241/b948bb56-b492-11e4-994c-3bf02edf6a7c.png)

![screen shot 2015-02-14 at 9 43 08 pm](https://cloud.githubusercontent.com/assets/5217007/6202243/bd592d66-b492-11e4-89bc-082d02fefae0.png)

**Comment by joao-parana** [comment]
This error doesn't occurs for me on iOS Simulator 8.1, Xcode 6.1.1 and Safari 8.0.3. All run fine. I'm have tested in Swift with UIWebView and run fine too.


    import UIKit

    class ViewController: UIViewController {

        @IBOutlet weak var webView: UIWebView!
        
        override func viewDidLoad() {
            super.viewDidLoad()
            let url = NSURL(string: "http://mymac.my-domain.com.br:8000/core-input/demo.html")
            let request = NSURLRequest(URL: url!)
            webView.loadRequest(request)
        }

        override func didReceiveMemoryWarning() {
            super.didReceiveMemoryWarning()
            // Dispose of any resources that can be recreated.
        }

     }

**Comment by Nevraeka** [comment]
@joao-parana should we close this one? cc/@tjsavage

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
