### ISSUE TITLE
core-header-panel shadow attribute: Should be reflected?

### ISSUE THREAD

**Issue by adjl** [Polymer/polymer#1195]
**Background**
- I have a custom element (app) with a top-level core-drawer-panel, with main and drawer core-header-panels and nested core-toolbars.
- Content in the main panel is long enough that it becomes scrollable, whereas content in the drawer is not.
- Both panels are set to waterfall mode.
- Only the main header-panel has a shadow when scrolling (expected behaviour).

--
The effect I wanted to achieve is to also show a shadow under the drawer header-panel when scrolling the main panel, as if this panel is its content.

The first thing I tried was to set the drawer's shadow attribute dynamically, like so:
```
...
<core-header-panel drawer shadow="{{shadow}}" ... >
...
onScroll: function(e) {
  var scroller = e.detail.target;
  this.shadow = scroller.scrollTop > 0;
}
...
```
But this did not work.

I only achieved it by setting the mode instead:
```
...
<core-header-panel drawer mode="{{mode}}" ... >
...
onScroll: function(e) {
  var scroller = e.detail.target;
  this.mode = scroller.scrollTop ? 'standard' : 'seamed';
}
...
```
--
Looking at core-header-panel's source, it appears the shadow property is not reflected. I wonder if it would be better if it is. In my case, toggling shadow makes semantic sense compared to setting the mode, which feels hacky.

Thanks

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
