### ISSUE TITLE
Bug in docs/start/creatingelements.html of the polymer-project official website

### ISSUE THREAD

**Issue by MacTheZazou** [Polymer/polymer#1196]
The horizontal Scrollbar of the code example with tabs for each example file just don't work...

I'm on Google Chrome 40.0.2214.111 .

If I select the text with my mouse, I can scroll, but it's not really handy...

Direct link: https://www.polymer-project.org/docs/start/creatingelements.html

![sans titre](https://cloud.githubusercontent.com/assets/1732909/6213272/35f29242-b5ee-11e4-9b95-a493f3532a0c.png)

**Comment by addyosmani** [comment]
cc @robdodson

**Comment by ebidel** [comment]
We're a bit confined on the amount of stuff that needs to be shown in the limited page width we have.  The tradeoff is to increase the column width of the main section, but we shortened it a while back so the site was easier to read. The majority of the site is text (and not these live examples) so legibly for copy is more important than demo-tabs not having scroll bars.

**Comment by MacTheZazou** [comment]
@ebidel The problem isn't that there are scroll bars... The problem is that the scroll bars doesn't work!

**Comment by ebidel** [comment]
Oh weird. They're working for me. What platform are you on?

**Comment by MacTheZazou** [comment]
Google Chrome 40.0.2214.111  Win 7 64x
I mad a video of the bug: https://www.youtube.com/watch?v=g5y4YSVKu3A

**Comment by robdodson** [comment]
Hm.. that feels like it may be a Chrome bug especially since you can highlight to get it to scroll over.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
