### ISSUE TITLE
Template's script doesn't execute when imported from another document (polyfill)

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#1197]
Test: http://jsbin.com/qegitukowe/1/edit?html,output

[The import](http://jsbin.com/kofevojipi/1/edit?html,output) used in the demo contains a `<template>` with a `<script>` in it.

**Expected**: In Chrome, when you click that page it updates the `<template ref>`
with "content2" and alerts 10.
**Actual**: In FF (polyfill), the template content is updated but the alert never happens (e.g. the script doesn't execute). 

This may have something to do with template being in another document and the polyfill using `.innerHTML`.

**Comment by garlicnation** [comment]
dup: webcomponents/webcomponentsjs#151
