### ISSUE TITLE
[0.8] x-template should provide bound values to elements' configure

### ISSUE THREAD

**Issue by nevir** [Polymer/polymer#1200]
Currently, `<x-template>` and friends stamp out elements and _then_ update their properties to match the bindings. I.e. bound values are **not** available to those elements until _after_ `ready`.

Ideally, we'd have values available to stamped out elements prior to that point. Maybe expose their bound values via `configure`?

**Comment by kevinpschaaf** [comment]
Fixed in https://github.com/Polymer/polymer/commit/d31279c5eb1ba543eb60c823ba23b0433ee6400c
