### ISSUE TITLE
[0.8] Attribute deserialization possibly busted?

### ISSUE THREAD

**Issue by robdodson** [Polymer/polymer#1208]
I feel like this has to be user error, but thought I'd file it anyway...

Given this element:

```js
Polymer({

  is: 'x-custom',

  published: {
    user: String,
    manager: {
      type: Boolean,
      notify: true
    }
  },

  created: function() {
    this.textContent = 'Hi I am ' + (this.user || 'nobody');
  }

});
```

Used as:

```html
<x-custom user="Rob"></x-custom>
```

What render is `Hi I am nobody`. I was expecting `Hi I am Rob`.

**Comment by dhubler** [comment]
"created" is before attributes, "attached" is after and should work in this
case.

**Comment by robdodson** [comment]
If that's the case we should update the PRIMER.md https://github.com/Polymer/polymer/blob/0.8-preview/PRIMER.md#attribute-deserialization

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/polymer/commit/0270e49bdd96cad4a2b34e3a29b557547abc8f52
