### ISSUE TITLE
styleObject doesn't work on IE10. Workaround?

### ISSUE THREAD

**Issue by richieb** [Polymer/polymer#1210]
The following, from the official documentation, doesn't work on IE10:
```<div style="{{styles | styleObject}}">...</div>```

**Comment by Jeff17Robbins** [comment]
Don't you need _style="..." on IE?

**Comment by richieb** [comment]
Yep, that did it. The documentation should make note of this.

**Comment by Jeff17Robbins** [comment]
It is documented, but I'm not sure how visibly.

https://www.polymer-project.org/docs/polymer/databinding-compat.html#binding-to-attributes

**Comment by Nevraeka** [comment]
Should this issue be closed? Has it been resolved?

**Comment by richieb** [comment]
Yes, close it. It has been resolved.
