### ISSUE TITLE
Imperatively declared element's custom fired event does not bubble up.

### ISSUE THREAD

**Issue by Werner-Swart-83** [Polymer/polymer#1212]
I have JSBin example (http://jsbin.com/wahapu/3/edit?html,console,output) where there are 3 custom elements. When they are declared declaratively I can catch the event as expected from the parent elements, but when I declare an element imperatively and force the event to fire the parent elements do not pick it up.

Although this example is useless it self, I found this problem with one of my projects where I had a "sign-out" event fired from an custom ajax element when the token expired. I like to use the ajax element imperatively rather then declaratively since nothing is rendered on the screen and I can read those elements that render easier in the template section.

**Comment by phestermcs** [comment]
You need to add the created element to the DOM for its events to bubble. Just calling `new elementThree()` doesn't automatically append the element to the DOM. In you jsbin sample, add the line `document.body.appendChild(target);` right after the line `var target = new elementThree();`

**Comment by Werner-Swart-83** [comment]
Ah, thank you, that worked.

**Comment by phestermcs** [comment]
No problem :). You might want to close this issue.
