### ISSUE TITLE
BUG: web-component-tester, sauce-connect-launcher dependency

### ISSUE THREAD

**Issue by phestermcs** [Polymer/polymer#1214]
After cloning Polymer/polymer, and running `npm install`, the following error occurs:
```
npm ERR! sauce-connect-launcher@0.9.0 postinstall: `node scripts/install.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the sauce-connect-launcher@0.9.0 postinstall script.
npm ERR! This is most likely a problem with the sauce-connect-launcher package,
npm ERR! not with npm itself.
```

Then running just `npm install sauce-connect-launcher@0.9.0` reports the following error:
```
> sauce-connect-launcher@0.9.0 postinstall D:\src\polymer\polymer\node_modules\sauce-connect-launcher
> node scripts/install.js

Downloading https://saucelabs.com/downloads/sc-4.3.5-win32.zip (3.18MB)
Unzipping D:\src\polymer\polymer\node_modules\sauce-connect-launcher\sc\sc-4.3.5-win32.zip

Invalid or unsupported zip format. No END header found

npm ERR! sauce-connect-launcher@0.9.0 postinstall: `node scripts/install.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the sauce-connect-launcher@0.9.0 postinstall script.
npm ERR! This is most likely a problem with the sauce-connect-launcher package,
npm ERR! not with npm itself.
```

This wasn't happening at least a couple of weeks ago, implying that a new `sc-4.x.x-win32.zip` was recently created, that's missing a zip END header. `sc-4.3.5-win32.zip` can be opened just fine when downloaded manually. It appears `sauce-connect-launcher` depends on `adm-zip` which is what's actually throwing the error; I'm guessing it's not as tolerant of "non-essential" zip file-format compliance.

Interestingly, running `npm install sauce-connect-launcher` installs `v0.9.3` (as of time of writing), which does not report errors (nor does it seem to attempt downloading and unzipping anything).

Lastly, `web-component-tester` appears to be at `v2.2.3` while Polymer/polymer is depending on the latest `v1`. The unit tests appear to all pass when running with latest `web-component-tester`, which reports no errors when installed manually.

We're developing PolyComp, an "add-on" for Polymer that enables consumer controlled, element renaming and namespacing within the consumer's app.  PolyComp patches Polymer's lifecycles, and we therefore need to ensure all the Polymer unit tests pass when PolyComp is active. This obviously requires that `web-component-tester` is working.

**Comment by robdodson** [comment]
@nevir

**Comment by nevir** [comment]
`sauce-connect-launcher` is still using `adm-zip` - was this error repeatable for you? It was my understanding that it's a transient error (https://github.com/bermi/sauce-connect-launcher/issues/45), but haven't had time to track down the cause. Definitely a lot less frequent w/ newer versions of `web-component-tester` (and `sauce-connect-launcher`)

I've switched the WCT dependency to `*` for this project to avoid the staleness. Sorry!
