### ISSUE TITLE
Clarification on Tutorial

### ISSUE THREAD

**Issue by Najii** [Polymer/polymer#1217]
The tutorial (in Step 2 section) says, "Add a <post-card> element to index.html directly after the 
<core-toolbar> element:" but it is a bit unclear that the intention is to paste the code below the CLOSING </core-toolbar> tag, and not after the opening <core-toolbar> tag. Pasting the code "directly below the <core-toolbar>" element breaks the page.

**Comment by davidmaxwaterman** [comment]
I think the formatting in your post is broken. Is it the following part that you mean?

<https://www.polymer-project.org/docs/start/tutorial/step-2.html#edit-indexhtml>

`Add a <post-card> element to index.html directly after the 
<core-toolbar> element:`

Note that you can edit the page using the `edit on github` link at the top (legal agreement might be an issue though).

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
