### ISSUE TITLE
The core-list demo page is rendering completely unstyled

### ISSUE THREAD

**Issue by kenmoore** [Polymer/polymer#1219]
Not sure what's causing that, but it looks bad.

**Comment by robdodson** [comment]
This page? https://www.polymer-project.org/components/core-list/demo.html

If so, that's how it has always looked

**Comment by arthurevans** [comment]
Something is wrong there -- the controls on the bottom of each item are cut off. 

There's a slightly different version in the core-list guide that doesn't cut them off:

https://github.com/Polymer/docs/blob/master/samples/core-list/multiple-elements/index.html

(It's not a thing of beauty or anything, but it does show the entire item.)

**Comment by kenmoore** [comment]
Oh, I get it now.  I was looking for a table example for guidance on sortable column headers, so when I saw this page it looked so out of sync with the rest of the site that I thought some CSS was failing to load.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
