### ISSUE TITLE
core-animated-pages : Selected variables return the wrong data

### ISSUE THREAD

**Issue by yonathan9669** [Polymer/polymer#1220]
When using the core-animated-pages as core-selector with a core-menu, the bind variable "selected" works great, but the selectedModel and selectedIndex both have an issue. They both return the data of the last selected object instead of the current.

I took some captures, hope can help.

Declaration
![core-definition](https://cloud.githubusercontent.com/assets/897389/6366723/661ff2fc-bc9c-11e4-8a38-d218ed17a934.png) 
Output-code
![output code](https://cloud.githubusercontent.com/assets/897389/6366724/66250a1c-bc9c-11e4-95b5-06c12708cd88.png)
Output-result
![output generated](https://cloud.githubusercontent.com/assets/897389/6366722/66012232-bc9c-11e4-9814-975a2c375f37.png)
can be notice that the INDEX is 0 and the OBJECT.uid too, they both point to the last state instead as the current, and the ITEM.page-uid with the Selected are both at the right state.

**Comment by LM450N** [comment]
You can directly link both elements together.

    <core-menu id="menu" selectedoption="{{selectedPage}}"></core-menu>
    <core-pages selected="{{selectedPage}}">
        <div>  </div>
        <div>  </div>
    </core-pages>

It works in a similar way with a `core-animated-pages`. Maybe [this video][1] could be helpful.

And if you want catch the change try to add an observer into your Polymer object.

    selectedPageChanged: function (oldValue, newValue) {
        console.log("\n### selectedPageChanged ###");
        console.log(oldValue);
        console.log(newValue);
        console.log("\n");
    }

[1]: https://www.youtube.com/watch?v=6x2A9UgLqEw&list=PLOU2XLYxmsII5c3Mgw6fNYCzaWrsM3sMN&index=2

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
