### ISSUE TITLE
content does not get wrapped on mobile devices

### ISSUE THREAD

**Issue by siritsch** [Polymer/polymer#1221]
I created the following html structure:

<body fullbleed layout vertical>
    
    <core-drawer-panel id="drawerPanel">
         <core-header-panel mode="waterfall-tall" tallClass="medium-tall" drawer>
             <core-toolbar><img  height="131" src="Bilder/lotus.jpg" /></core-toolbar>
             <core-menu>
                 <core-item label="One"></core-item>
                 <core-item label="Two"></core-item>
             </core-menu>
        </core-header-panel>
       
        <core-header-panel mode="waterfall-tall" tallClass="medium-tall" main>
            <core-toolbar>
                <core-icon-button id="navicon" icon="menu">
                </core-icon-button>
                <h1>Studio Daria</h1>
                <p>...die reiche Welt der Kosmetik</p>
            </core-toolbar>
            <div class="content">
           </div>
       </core-header-panel>
   </core-drawer-panel>
</body>

If I put content inside the div element  with class="content" then this content does not get wrapped on mobile devices and there is also no horizontal scrollbar available. So the content gets cut!
An example of this problem can be found under http://www.studiodaria.de/newsite/index.html .

I'm using Polymer 0.5.1

**Comment by siritsch** [comment]
The body tag has the attributes  "fullbleed layout vertical"

**Comment by siritsch** [comment]
I now added
div[class=content] {
    overflow-x: auto;
}
to the app.css file. On dektop computers and laptops it works, but on mobile devices the performance is quite poor and the scrolling behaviour is quite strange. If I want to scroll right I first have to scroll down to the bottom and then I can sroll right. To scroll back to the left I again first have to scroll down and then I can scroll left.

**Comment by davidmaxwaterman** [comment]
Seems odd to do `div[class=content]` - does `div.content` not work?

**Comment by siritsch** [comment]
I also tried this. Has the same effect. Meanwhile I solved the problem with
changing the viewport parameters and I also added left and right margins
for paragraphs.  The performance on mobile devices with Chrome is ok
although the initial loading takes a while.  With Firefox the performance
on the same mobile device is poor.  I did not try iOS devices yet.
Am 27.02.2015 18:11 schrieb "Max Waterman" <notifications@github.com>:

**Comment by davidmaxwaterman** [comment]
Glad to know it worked - it just looked weird and I wondered if there was any subtle difference I didn't know about. Anyway, I doubt it makes any difference in this case, but I *think* using a class selector is quite a bit faster that using an attribute selector....but I'm no expert.

Glad you fixed the problem whatever the cause :)
