### ISSUE TITLE
Safari platform.js error

### ISSUE THREAD

**Issue by KupuJIJI** [Polymer/polymer#1225]
I have error at start my polymer app in Safari 8

[Error] TypeError: Attempted to assign to readonly property.
	(anonymous function) (platform.js, line 16)

**Comment by Nevraeka** [comment]
@KupuJIJI `platform.js` has been deprecated as of version 0.5x. I believe you are using an earlier version of Polymer in this case. If it is possible, I recommend you upgrade your application to the latest. The latest iOS 8 builds are not guaranteed to handle `platform.js`. Ping me on Hangouts if I can help. :)

**Comment by Nevraeka** [comment]
@KupuJIJI how did this go ?

**Comment by KupuJIJI** [comment]
@Nevraeka  Update Polymer, have "undefinded is not a function" in this row

Polymer(Polymer.mixin({

**Comment by robdodson** [comment]
hm @kevinpschaaf have you seen this before?

**Comment by kevinpschaaf** [comment]
No, I'm confused what the configuration causing the error is.  Has @KupuJIJI updated to webcomponents.js?

**Comment by KupuJIJI** [comment]
I remove all components and install again with bower and with this header:

<head><style>body {transition: opacity ease-in 0.2s; } 
body[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } 
</style>
    <link rel="import" href="/assets/polymer/layout.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/polymer/polymer.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/core-selection/core-selection.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/core-selector/core-selector.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/core-style/core-style.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/core-meta/core-meta.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/core-transition/core-transition.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/core-animated-pages/transitions/core-transition-pages.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/core-animated-pages/transitions/hero-transition.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/core-animated-pages/transitions/cross-fade.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/core-animated-pages/core-animated-pages.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/core-animated-pages/transitions/slide-from-right.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/paper-ripple/paper-ripple.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/paper-radio-button/paper-radio-button.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/paper-checkbox/paper-checkbox.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/core-input/core-input.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/paper-input/paper-input.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/core-iconset/core-iconset.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/core-icon/core-icon.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/core-iconset-svg/core-iconset-svg.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/core-icons/core-icons.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/paper-focusable/paper-focusable.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/paper-button/paper-button.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/paper-radio-group/paper-radio-group.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/core-range/core-range.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/paper-progress/paper-progress.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/core-transition/core-transition-css.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/paper-dialog/paper-dialog-transition.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/core-overlay/core-key-helper.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/core-overlay/core-overlay-layer.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/core-overlay/core-overlay.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/paper-shadow/paper-shadow.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/paper-dialog/paper-dialog.html?body=1" data-turbolinks-track="true">
    <link rel="import" href="/assets/application.html?body=1" data-turbolinks-track="true"><link rel="stylesheet" media="all" href="/assets/active_admin.css?body=1" data-turbolinks-track="true">
    <link rel="stylesheet" media="all" href="/assets/icons.css?body=1" data-turbolinks-track="true">
    <link rel="stylesheet" media="all" href="/assets/website.css?body=1" data-turbolinks-track="true">
    <link rel="stylesheet" media="all" href="/assets/application.css?body=1" data-turbolinks-track="true"><script src="/assets/webcomponentsjs/webcomponents.js?body=1" data-turbolinks-track="true"></script><style type="text/css"></style><style>[touch-action="none"]{ -ms-touch-action: none; touch-action: none;}
html /deep/ [touch-action="none"]{ -ms-touch-action: none; touch-action: none;}
[touch-action="auto"]{ -ms-touch-action: auto; touch-action: auto;}
html /deep/ [touch-action="auto"]{ -ms-touch-action: auto; touch-action: auto;}
[touch-action="pan-x"]{ -ms-touch-action: pan-x; touch-action: pan-x;}
html /deep/ [touch-action="pan-x"]{ -ms-touch-action: pan-x; touch-action: pan-x;}
[touch-action="pan-y"]{ -ms-touch-action: pan-y; touch-action: pan-y;}
html /deep/ [touch-action="pan-y"]{ -ms-touch-action: pan-y; touch-action: pan-y;}
[touch-action="pan-x pan-y"],[touch-action="pan-y pan-x"]{ -ms-touch-action: pan-x pan-y; touch-action: pan-x pan-y;}
html /deep/ [touch-action="pan-x pan-y"],html /deep/ [touch-action="pan-y pan-x"]{ -ms-touch-action: pan-x pan-y; touch-action: pan-x pan-y;}
[touch-action="manipulation"]{ -ms-touch-action: manipulation; touch-action: manipulation;}
html /deep/ [touch-action="manipulation"]{ -ms-touch-action: manipulation; touch-action: manipulation;}
</style>
    <script src="/assets/jquery.js?body=1" data-turbolinks-track="true"></script>
    <script src="/assets/jquery_ujs.js?body=1" data-turbolinks-track="true"></script>
    <script src="/assets/turbolinks.js?body=1" data-turbolinks-track="true"></script>
    <script src="/assets/website.js?body=1" data-turbolinks-track="true"></script>
    <script src="/assets/application.js?body=1" data-turbolinks-track="true"></script><meta name="csrf-param" content="authenticity_token">
    
  </head>


I got this errors:

polymer.html?body=1:24 Uncaught ReferenceError: Platform is not defined
polymer.html?body=1:24 Uncaught Element name could not be inferred.
polymer.html?body=1:24 Uncaught Element name could not be inferred.
polymer.html?body=1:24 Uncaught Element name could not be inferred.
polymer.html?body=1:24 Uncaught Element name could not be inferred.
localhost/:60 GET http://localhost:3000/assets/polymer/polymer.js.map 404 (Not Found)

**Comment by robdodson** [comment]
The script for webcomponents.js needs to come before any HTML import link tags or any other scripts in your page.

**Comment by pflannery** [comment]
On top of that you will also need to remove the ```?body=1``` from the href referencing polymer.html, that will fix the ```undefined is not a function```
example: ```<link rel="import" href="http://www.polymer-project.org/components/polymer/polymer.html">```

You also don't need layout.html because currently polymer.html imports this for you.

**Comment by pflannery** [comment]
if anyone wants to recreate the ```object is not a function``` an [example is here](http://plnkr.co/edit/AXbkQ8EsCx0MWr68WNNA?p=preview)

**Comment by KupuJIJI** [comment]
I cat remove many requriments and with this code:

````html

    <script data-turbolinks-track="true" src="/assets/webcomponentsjs/webcomponents.js"></script>
    <link href="/assets/polymer/polymer.html" rel="import" />
    <link rel="import" href="/assets/application.html?body=1" /><link rel="stylesheet" media="all" href="/assets/active_admin.css?body=1" data-turbolinks-track="true" />
    <link rel="stylesheet" media="all" href="/assets/icons.css?body=1" data-turbolinks-track="true" />
    <link rel="stylesheet" media="all" href="/assets/website.css?body=1" data-turbolinks-track="true" />
    <link rel="stylesheet" media="all" href="/assets/application.css?body=1" data-turbolinks-track="true" /><script src="/assets/jquery.js?body=1" data-turbolinks-track="true"></script>
    <script src="/assets/jquery_ujs.js?body=1" data-turbolinks-track="true"></script>
    <script src="/assets/turbolinks.js?body=1" data-turbolinks-track="true"></script>
    <script src="/assets/website.js?body=1" data-turbolinks-track="true"></script>
    <script src="/assets/application.js?body=1" data-turbolinks-track="true"></script><meta name="csrf-param" content="authenticity_token" />

I had same:

Uncaught TypeError: undefined is not a function polymer.html:213 (anonymous function)polymer.html:213 (anonymous function)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
