### ISSUE TITLE
Observing property from another component causes major slowdowns in IE and Firefox

### ISSUE THREAD

**Issue by kevin-wise-infusionsoft** [Polymer/polymer#1227]
I have a situation where one component is wired to another component and the second component observes changes on the first component's property.  Under Chrome it works fine.  Under IE and Firefox the performance is so bad that the browser is unusable.  I was able to find a workaround by copying the property during domReady.  This works in my situation because I don't care about changes to the property after domReady. I have a couple of examples that demonstrate the problem and the workaround which I can attach to this issue.

The high level is a component referencing another component:

```html
<tag-a id="componentA"></tag-a>
<tag-b target="{{ $.componentA }}"></tag-b>
```

Then inside the second component, reference a property from the first component:
```html
<template repeat="{{ item, itemIndex in target.items }}">
```

When loaded, the page performs exceptionally slow, sometimes hanging to the point that it appears to have crashed.  The workaround:

```javascript
domReady: function() {
    this.targetItems = this.target.items;
}
```
```html
<template repeat="{{ item, itemIndex in targetItems }}">
```

Sample code: https://drive.google.com/file/d/0ByV_9KExHuPRWEg5Rk5rNFBZSlU/view?usp=sharing

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
