### ISSUE TITLE
Attribute Value of "selected" in the tutorial

### ISSUE THREAD

**Issue by abhiShandy** [Polymer/polymer#1228]
Should be "0" instead of "all"
https://www.polymer-project.org/docs/start/tutorial/step-1.html

**Comment by Nevraeka** [comment]
I think the attribute `valueattr` was meant to be used here instead of a selected index. 

```html
<paper-tabs id="tabs" valueattr="name" selected="all" self-end>
    <paper-tab name="all">All</paper-tab>
    <paper-tab name="favorites">Favorites</paper-tab>
  </paper-tabs>
```

**Comment by Nevraeka** [comment]
https://github.com/Polymer/docs/pull/917

This should allow this issue to be closed once this PR is accepted.
cc/ @tjsavage

**Comment by robdodson** [comment]
ping @arthurevans

**Comment by Nevraeka** [comment]
the code is correct as per the docs. We are going to add descriptive text to make the code clearer as @robdodson suggested in the docs PR

**Comment by ebidel** [comment]
Cleared up https://github.com/Polymer/docs/commit/78a0acb6d3a3ec173db880b175ea19e8b8674bd7
