### ISSUE TITLE
When debugging custom elements, all type names show as "Polymer"

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer#1231]

**Comment by TimvdLippe** [comment]
This issue is so ancient, I don't know what it actually is about :stuck_out_tongue: Given that I never experienced it, I think it is resolved?

**Comment by justinfagnani** [comment]
THis is only a problem with legacy style elements that use the `Polymer()` function. Class-based elements get a proper name in debugging, stack-traces, etc.

**Comment by TimvdLippe** [comment]
I am probably misunderstanding the problem. Could you add a screenshot of dev-tools to show the issue, hopefully I understand the situation better?
