### ISSUE TITLE
What about the difference between element's attributes & template model?

### ISSUE THREAD

**Issue by Colstuwjx** [Polymer/polymer#1232]
As I known, Polymer element has attributes & template model, such as:
```
    <polymer-element name="gaea-lib-suicheckbox" attributes="checked inner-tips">
        <template repeat="{{ f in features }}">
    ...
```

Both this.features & this.inner-tips can be accessed by `this`, but what's the meaning of attributes & template model?

I just think that attributes are the element's exposed properties which  may access or share to other elements, and template model is just used by the element, eg. gaea-lib-suicheckbox itself??

Wishes your reply, many thanks!!

**Comment by LM450N** [comment]
About the attributes you have right. But the template tag is little bit more complicated than what you said. It provides many features. [HTML5 Template Tag][1]

[1]: http://www.html5rocks.com/en/tutorials/webcomponents/template/

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
