### ISSUE TITLE
polymer.js:8186 Uncaught ReferenceError: Observer is not defined

### ISSUE THREAD

**Issue by reggi** [Polymer/polymer#1236]
I've been trying to compile polymer with every build system on the planet and I keep getting this error. 

```
polymer.js:8186 Uncaught ReferenceError: Observer is not defined
```

**Comment by davidmaxwaterman** [comment]
This has me puzzled. Is it possible you've completely misunderstood how to use Polymer? It doesn't require any 'compile' step - you just use it directly. There are plenty of examples, and the best place to start is, of course, <https://www.polymer-project.org/>.

As a summary, you only need to 'include' polymer if you're writing your own elements. If you simply want to use one of the elements written using polymer, then you just need to import that element's html file (it will then import polymer.html, or something else that does) in your html file. If you're targeting a browser that doesn't implement some features required for polymer (anything except chrome?), then you also need to include the web components library that 'polyfills' those features in javascript.
To get the polymer library (or any of the core or paper elements that use it), you can use a command called 'bower'. You can also reference it on some cdn, I expect, though (iinm) there is no 'official' one.

**Comment by reggi** [comment]
Thanks @davidmaxwaterman, commented here https://github.com/Polymer/polymer/issues/1238#issuecomment-76739195

**Comment by stefanr** [comment]
One reason why this fails is that there are a few functions that are called with `this` which is not really a reliable value when loaded with module loaders.

Example: https://github.com/Polymer/polymer/blob/0.5.5/polymer.js#L3192

It's supposed to be `window` but mostly it is not.

Another problem is the following (`observe-js`):
https://github.com/Polymer/polymer/blob/0.5.5/polymer.js#L5845-L5856

It's checking for Node.js but this condition is met by module loaders as well, it should actually check for browsers first.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
