### ISSUE TITLE
Links in SPA tutorial are broken

### ISSUE THREAD

**Issue by jakemac53** [Polymer/polymer#1239]
The links to the final files are broken on this page https://www.polymer-project.org/articles/spa.html.

They need an extra `0.5` folder added into them. For example: https://github.com/Polymer/docs/blob/master/articles/demos/spa/final.html should be https://github.com/Polymer/docs/blob/master/0.5/articles/demos/spa/final.html

**Comment by ebidel** [comment]
Thanks! Will fix.

**Comment by ebidel** [comment]
This issue was moved to Polymer/docs#918
