### ISSUE TITLE
[0.8] Multiple computed properties call same method

### ISSUE THREAD

**Issue by ssorallen** [Polymer/polymer#1242]
When pointing multiple computed properties to the same method but with different arguments, the output is unexpected.

https://gist.github.com/ssorallen/07337da2bbfb4929333a

```html
<link rel="import" href="../polymer/polymer.html">

<dom-module id="multi-compute">

  <template>
    <div class-name="[[first]]"></div>
    <div class-name="[[second]]"></div>
  </template>

</dom-module>

<script>
  Polymer({
    is: 'multi-compute',

    computed: {
      first: 'computeClassName(foo)',
      second: 'computeClassName(bar)'
    },

    configure: function() {
      return {
        bar: 'hola',
        foo: 'bonjour'
      };
    },

    computeClassName: function(c) {
      return c;
    }
  })
</script>
```

Expected output when using the `multi-compute` element:

```html
<multi-compute>
  <div class"bonjour"></div>
  <div class="hola"></div>
</multi-compute>
```

Actual output:

```html
<multi-compute>
  <div class"bonjour"></div>
  <div></div>
</multi-compute>
```

**Comment by ssorallen** [comment]
The method strings constructed by the computed property code pass the same value to `debounce`. In the example they end up containing:

```js
this.debounce('_computeClassName', function() { ... })
```

Since they pass the same value as the task name, `debounce` does its job and calls the function only once because the calls happen within a short period of time.

Computed properties need to ensure the task names they pass to debounce are unique among all computed properties of a model.

**Comment by sorvell** [comment]
Closed via https://github.com/Polymer/polymer/pull/1243
