### ISSUE TITLE
Installing with Bower not working

### ISSUE THREAD

**Issue by xtinacosta** [Polymer/polymer#1246]
Please can you check what is wrong with bower installation, `Polymer/polymer` package cannot be found
I tried `polymer-polymer`, it was found but when installing dependencies bower couldn't find  `core-component-page#^0.5`
Maybe the packages names changed so you need to update the dependencies ....

**Comment by davidmaxwaterman** [comment]
wfm (see below). Do you have a `bower.json` file you can share? `.bowerrc` have anything in it? Perhaps do a `bower cache clean` and try again (I did that before doing below, to make sure I am getting the latest)?
Am I missing something? Perhaps you can post the output of your attempts to help people see what's going wrong?

```
(cli-extra)davidmaxwaterman@localhost:~/tmp$ bower install Polymer/core-component-page#^0.5
bower not-cached    git://github.com/Polymer/core-component-page.git#^0.5
bower resolve       git://github.com/Polymer/core-component-page.git#^0.5
bower download      https://github.com/Polymer/core-component-page/archive/0.5.5.tar.gz
bower extract       core-component-page#^0.5 archive.tar.gz
bower invalid-meta  core-component-page is missing "main" entry in bower.json
bower invalid-meta  core-component-page is missing "ignore" entry in bower.json
bower resolved      git://github.com/Polymer/core-component-page.git#0.5.5
bower not-cached    git://github.com/Polymer/webcomponentsjs.git#^0.5
bower resolve       git://github.com/Polymer/webcomponentsjs.git#^0.5
bower not-cached    git://github.com/Polymer/polymer.git#^0.5
bower resolve       git://github.com/Polymer/polymer.git#^0.5
bower download      https://github.com/Polymer/webcomponentsjs/archive/0.5.5.tar.gz
bower download      https://github.com/Polymer/polymer/archive/0.5.5.tar.gz
bower extract       polymer#^0.5 archive.tar.gz
bower invalid-meta  polymer is missing "main" entry in bower.json
bower invalid-meta  polymer is missing "ignore" entry in bower.json
bower resolved      git://github.com/Polymer/polymer.git#0.5.5
bower extract       webcomponentsjs#^0.5 archive.tar.gz
bower resolved      git://github.com/Polymer/webcomponentsjs.git#0.5.5
bower install       core-component-page#0.5.5
bower install       polymer#0.5.5
bower install       webcomponentsjs#0.5.5

core-component-page#0.5.5 bower_components/core-component-page
├── polymer#0.5.5
└── webcomponentsjs#0.5.5

polymer#0.5.5 bower_components/polymer
├── core-component-page#0.5.5
└── webcomponentsjs#0.5.5

webcomponentsjs#0.5.5 bower_components/webcomponentsjs
(cli-extra)davidmaxwaterman@localhost:~/tmp$  bower list
bower check-new     Checking for new versions of the project dependencies..
tmp /home/davidmaxwaterman/tmp
└─┬ core-component-page#0.5.5 extraneous
  ├─┬ polymer#0.5.5
  │ └── webcomponentsjs#0.5.5
  └── webcomponentsjs#0.5.5
(cli-extra)davidmaxwaterman@localhost:~/tmp$ 
```

**Comment by xtinacosta** [comment]
my `.bowerrc` looks like this:
>{
>  "directory" : "public/bower_components",
>  "json"      : "bower.json",
>  "searchpath"  : "",
>  "shorthand_resolver" : ""
>}
I did a `bower cache clean` then
> xtina:project xtinacosta$ bower install Polymer/polymer
> bower                        ENOTFOUND Package  not found
> xtina:project xtinacosta$ 

and when I try `polymer-polymer`

> xtina:project xtinacosta$ bower install polymer-polymer
> bower polymer-polymer#*     not-cached git://github.com/Polymer/polymer.git#*
> bower polymer-polymer#*        resolve git://github.com/Polymer/polymer.git#*
> bower polymer-polymer#*       download https://github.com/Polymer/polymer/archive/0.5.5.tar.gz
> bower polymer-polymer#*        extract archive.tar.gz
> bower polymer-polymer#*   invalid-meta polymer is missing "main" entry in bower.json
> bower polymer-polymer#*   invalid-meta polymer is missing "ignore" entry in bower.json
> bower polymer-polymer#*       resolved git://github.com/Polymer/polymer.git#0.5.5
> bower core-component-page#^0.5        ENOTFOUND Package  not found
> xtina:project xtinacosta$

**Comment by davidmaxwaterman** [comment]
Does it work in an empty tmp/ directory, like I tried? That might help remove some variables to the problem...

I don't think polymer-polymer is correct - should be Polymer/polymer (unless things have changed or I'm "just wrong"(tm)). Unless, that is, you have such a line in your bower.json file to match it...can you share that too (though I'd try a blank directory first, as a diagnostic step)?

**Comment by xtinacosta** [comment]
Turned out it was an error in my `.bowerrc` file :s 
I removed the searchpath & shorthand_resolver and it worked perfectly
Sorry for bothering you and thanks a lot for your help :)
