### ISSUE TITLE
[0.8] Polymer.import missing

### ISSUE THREAD

**Issue by IntranetFactory** [Polymer/polymer#1248]
It seems that Polymer.import is missing in 0.8. Polymer.import is also not mentioned in the Migration Notes of the primer.

Are there any plans to bring it back? Is there any new way to load components on demand?

**Comment by IntranetFactory** [comment]
I've copied the code from 0.5 to https://github.com/TangereJs/Polymer-import/tree/0.8-preview and it seems to work after a minor change.

Is this the right approach? It works for my current use case, but it seems to easy ...

**Comment by IntranetFactory** [comment]
**Does anybody have any information about the future of Polymer.import()?** Unfortunately that feature is quite essential for us.

The version we made at https://github.com/TangereJs/Polymer-import/tree/0.8-preview has an issue when used with FF/IE: in the freshly imported elements the dom-module is sometimes empty. It seems that the dom-module is upgraded after the Polymer() was already executed.

As a workaround it works if the Polymer() code is included in the dom-module, so if the code is like 
```
<dom-module>
  <template>
  ....
  </template>

  <script>
  Polymer(
  ...
  </script>
</dom-module>
```
Polymer.import seems to work in IE/FF as well.

**Comment by arthurevans** [comment]
@sorvell Can you comment? I believe there is an importHref _instance_ method, but I'm not sure whether it's a replacement for Polymer.import.

**Comment by IntranetFactory** [comment]
I've tested *importHref* it only imports one element and not an array of elements. We can probably work around that limit in our own code.

But *importHref* has the same problem I faced with our port of Polymer.import: nested dom-modules fail to load correctly in IE/FF. *importHref* works in IE/FF when I move the `<script>Polymer(...` into the `<dom-module>`.

Should *importHref* work IE/FF ? Is this a known problem/bug?

**Comment by IntranetFactory** [comment]
I've created a new issue to show the importHref issue in FF/IE11 https://github.com/Polymer/polymer/issues/1343

**Comment by IntranetFactory** [comment]
Any help with  polymer component imports? Are we doing something wrong or is it really not possible in 0.8 to import components in FF and IE11 ?

**Comment by sorvell** [comment]
We're investigating a fix for this issue. It stems from limitations of the HTMLImports and CustomElements polyfills.

**Comment by IntranetFactory** [comment]
Thank you for the feedback, good to know that a fix is coming.

**Comment by ghmlee** [comment]
@sorvell Thanks I also want to know the fix.

**Comment by sorvell** [comment]
Closing this since #1343 has been fixed. The `importHref` method is intended to replace `Polymer.import`. We'll consider expanding the api to support an array as `Polymer.import` did based on user feedback.
