### ISSUE TITLE
<paper-input-decorator label=“birthday”>

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#1251]
Is it possible to show the label `birthday` like the other decorators when the input field is empty?

```html
    <paper-input-decorator label="birthday">
           <core-localstorage name="birthday" value="{{birthday}}"></core-localstorage>
           <input name="birthday" value="{{birthday}}" is="core-input" type="date" required>
    </paper-input-decorator>
```

In safari you see a empty field
In chrome a pre defined dd/mm/yyyy
But there is no indication of the label birthday

http://stackoverflow.com/questions/28840931/polymer-paper-input-decorator-label-birthday

**Comment by ssorallen** [comment]
`type="date"` has a browser-defined placeholder that represents the format of the date. You should use a real `<label>`:

```html
<paper-input-decorator>
  <core-localstorage name="birthday" value="{{birthday}}"></core-localstorage>
  <label>
    Birthday
    <input name="birthday" value="{{birthday}}" is="core-input" type="date" required>
  </label>
</paper-input-decorator>
```

**Comment by gertcuykens** [comment]
Not really consistent with `type="text"` but good enough thanks :)

**Comment by ssorallen** [comment]
To be clear, the part that seems inconsistent to you is the way Chrome implements `type="date"`. This is unrelated to Polymer. This JSFiddle shows the difference: http://jsfiddle.net/ssorallen/0w73nxhn/

Worth noting however is that neither Firefox nor Safari implements a date picker for `type="date"` yet. They likely behave the way you are expecting. Try opening that JSFiddle in each browser.

**Comment by gertcuykens** [comment]
True I much rather see chrome displaying the label first and only show the empty place holder 'dd/mm/yyyy' only when the field gets selected. If you know a chrome developer tell him to look at your example :P

**Comment by ssorallen** [comment]
That's not how the [`placeholder`](http://www.w3.org/TR/2011/WD-html5-20110525/common-input-element-attributes.html#the-placeholder-attribute) attribute is designed to work though. Also according to the spec, "The placeholder attribute should not be used as an alternative to a label."

You should use real `<label>` elements when the value is truly a label.

**Comment by gertcuykens** [comment]
Ok fair enough
