### ISSUE TITLE
core drawer / core header panel - hides scroll bar

### ISSUE THREAD

**Issue by TimWillis** [Polymer/polymer#1252]
I am using a combination of core drawer and  core header panel. When I am in a desktop browser with the page long enough the scroll bar is partially or totally hidden behind the header. This is fine for mobile as there are no scroll bars, but for a desktop browser people still use the scroll bar. I think this should be handled by the component based on the height of the content and the height of the window(if the scroll is shown, put a right-margin on the header.) Example of the bug at http://xmenu.menu - just resize window until scroll is needed.

Thanks
Tim

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
