### ISSUE TITLE
[0.8] camel-case attributes do not deserialize to properties correctly.

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#1257]
<x-thing camel-case="foo">

should result in 

    xThing.camelCase === 'foo'

**Comment by sorvell** [comment]
Related to https://github.com/Polymer/polymer/issues/1226

**Comment by ssorallen** [comment]
Except for `data-` attributes probably, otherwise they are not set on the element's `dataset`. Or would you have to suffix those with a `$`?

**Comment by kevinpschaaf** [comment]
This issue _only_ relates to the [attribute deserialization](https://github.com/Polymer/polymer/blob/0.8-preview/PRIMER.md#attribute-deserialization) feature of Polymer, which only operates on attributes matching property names defined in `properties` with a `type` field set.

Per current rules, `data-foo` would only be deserialized by Polymer if there was a `dataFoo` property defined.  The fact that `data-foo` also deserializes to `dataset.foo` is a feature of the DOM, not Polymer, and that will happen regardless.

**Comment by kevinpschaaf** [comment]
Fixed in https://github.com/Polymer/polymer/commit/618756bb746f51fe3912e031f89f8c5e7fb5aca1.

**Comment by ssorallen** [comment]
:+1: It looks like this addresses #1226 as well since `className` (which converts from `"class-name"`) is a property of HTMLElement.
