### ISSUE TITLE
One-way data binding in 0.5.5 issue

### ISSUE THREAD

**Issue by dbismut** [Polymer/polymer#1259]
Hey,

I'm using the code below to simulate one-way data-binding only when the exhibition object is ready (loaded via ajax query).

```html
<template if="{{!!exhibition}}">
      <img-crop url="[[exhibition.attributes.smallPreview._url]]"></img-crop>
</template>
```

When the DOM renders, the url value becomes:

```
url="elements/exhibition-form/http://files.parsetfss.com/xxxxxxxxxxxxxxxx"
```

Where `elements/exhibition-form` is the custom polymer element where my code is... Using double brackets `{{}}` works fine (but then I get the two-way data-binding which I'm trying to avoid).

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
