### ISSUE TITLE
core-icons (social) in a footer are dissapeared

### ISSUE THREAD

**Issue by AKHXtern** [Polymer/polymer#1260]
http://polymer-project.org
Social icons in a footer area are dessapeared, looks like some problem with fonts

**Comment by AKHXtern** [comment]
and in a top, in a next of "GET POLYMER" button VIEW ON GITHUB icons is broken too

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
