### ISSUE TITLE
paper-input-decorator's page needs updated link to github repo

### ISSUE THREAD

**Issue by prateekjadhwani** [Polymer/polymer#1263]
It seems that `paper-input-decorator` cannot be obtained via github or via bower. The repo page on github shows `404` error code

**Comment by miztroh** [comment]
It's part of the paper-input repo.

https://github.com/Polymer/paper-input

**Comment by prateekjadhwani** [comment]
That makes sense. Thank You
I guess the documentation wasnt updated in polymer-project website

**Comment by miztroh** [comment]
Consider changing the the issue title?

That makes sense. Thank You
I guess the documentation wasnt updated in polymer-project website

—
Reply to this email directly or view it on GitHub
<https://github.com/Polymer/polymer/issues/1263#issuecomment-77556218>.

**Comment by prateekjadhwani** [comment]
done @miztroh 
Thanks for pointing that out

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
