### ISSUE TITLE
[0.8] accidental shared state in configure value?

### ISSUE THREAD

**Issue by IntranetFactory** [Polymer/polymer#1269]
I have an element with a property of type Object with a default value like
```
    properties: {
      user: {
        type: Object,
        notify: true,
        value: {
          name: {
            first: 'James',
            last: 'Cook',           
          },
          counter: 1
        }        
      }
```

When using that element all instances share the same "user" object.

I think the reason for this is
https://github.com/Polymer/polymer/blob/0.8-preview/src/features/standard/configure.html#L75

After I changed that line to 

```
            // deep copy config value
            config[i] = (JSON.parse(JSON.stringify(c.value)));  
```

the shared state didn't happen any longer.

**Comment by ssorallen** [comment]
If the initial value is a primitive like a Number, a Boolean, or a String, it is okay to set it as the value. If the initial value is an Object you need to [provide a function](https://github.com/Polymer/polymer/blob/0.8-preview/PRIMER.md#configure-values) that returns the initial:

```js
value: function() {
  return {
    name: {
      first: 'James',
      last: 'Cook',           
    },
    counter: 1
  };
}
```

**Comment by IntranetFactory** [comment]
Wouldn't it make more sense to automatically also copy non primitive types if no function is provided? It would still be possible to write a function when a copy is not sufficient. Just creating an avoidable shared state seems to be not really convenient.

**Comment by ssorallen** [comment]
A shallow copy works in the case you gave, but consider more complex data structures that are not just simple JavaScript objects. This is a case better left to the developer because he or she has more knowledge about the data structure than the framework can possibly infer.

**Comment by IntranetFactory** [comment]
I understand the idea - but I didn't want to remove the function. I just think it's quite surprising that when no function is provided a shared state is created. If using a default value for an object really requires to write a function then without such a function, I think no default should be copied.

**Comment by sorvell** [comment]
This can be a little confusing, but it's also fundamental language functionality. We can't know what's appropriate since there are cases when it's desirable for the object to actually be shared on the prototype. For these reasons, we've elected to allow the user to give Polymer explicit information by providing a function that can generate the default property value.

**Comment by IntranetFactory** [comment]
Wouldn't it be less surprising if both works? So if the value is a function then call the function, but if it's an object copy that object?

So in the cases when I want to share the state or when a deep copy is not appropriate I can provide a function, but in the cases where a simple copy of the value is ok I don't have a write a function over and over to just copy the values.
