### ISSUE TITLE
paper-dropdown-menu layered attribute has no effect when in core-overlay

### ISSUE THREAD

**Issue by dough10** [Polymer/polymer#1270]
![layered](https://cloud.githubusercontent.com/assets/7014926/6548126/ce781388-c5bc-11e4-9f0c-32be0ebac6c3.png)

can be seen here. https://www.polymer-project.org/components/paper-dropdown-menu/demo.html
click toggle core-overlay button
open menu
witness the sadness

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
