### ISSUE TITLE
[0.8] body unresolved broken

### ISSUE THREAD

**Issue by IntranetFactory** [Polymer/polymer#1271]
To prevent FOUC we used, as suggested, `<body unresolved>`.  webcomponents.js always define the style for unresolved - so the body still gets hidden.

But it seems that in 0.8 the `unresolved` is never removed from body.

If I don't use unresolved I see the page but again get FOUC in FF & IE.

**Comment by IntranetFactory** [comment]
In https://github.com/webcomponents/webcomponentsjs/issues/230 I've proposed a workaround which solved that issue for me.

**Comment by ebidel** [comment]
Running into this too

**Comment by addyosmani** [comment]
Confirmed that I've been bitten by this too, but I agree with @garlicnation's resolution on that bug. It's fine for the framework or user to remove the unresolved attribute at a time they consider the page ready.

**Comment by IntranetFactory** [comment]
I've a page with several components. I've no problem to remove unresolved myself - but how do I know that **all** components are ready and won't cause any FOUC?

**Comment by ebidel** [comment]
@addyosmani, `unresolved` was something users had to manage themselves if they were just using the wc.js polyfill. If you were authoring 0.5 Polymer elements, it's a feature Polymer managed.

**Comment by kdex** [comment]
I ran into this, too.
If it helps, the following will **never** fire in `0.8`:
```js
window.addEventListener("polymer-ready", function() {
    console.log("Event broken?");
}, false);
```

**Comment by sorvell** [comment]
Id would be best if the `webcomponents.js` polyfills would take care of this issue, but doing so would break support for Polymer 0.5. That said, it seems reasonable and simple for Polymer to auto-remove this attribute at the appropriate time.
