### ISSUE TITLE
[0.8-preview] Shadey styles have incorrect order of precedence

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer#1277]
Styles targeting :host should have lower precedence than styles targeting the same element in `<head>`. However, when switching to shadey mode, generated stylesheets are appended (as opposed to inserted before existing stylesheets), and this throws the precedence off.

**Comment by sorvell** [comment]
Instead of always putting shimmed styles at the top, we should put them in order of element registration. This should help address https://github.com/Polymer/polymer/issues/1279
