### ISSUE TITLE
Calender bug

### ISSUE THREAD

**Issue by redchief** [Polymer/polymer#1278]
hey there polymer team there is a calender / datepicker bug we cannot change or goto a desired date.

**Comment by Nevraeka** [comment]
@redchief - can you be more specific? Is this a native browser datepicker? Please add a code example if you can on codepen.io or ele.io.Thanks

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
