### ISSUE TITLE
icon demo page 404s

### ISSUE THREAD

**Issue by kenrothmuller** [Polymer/polymer#1280]
no longer can see a visual list of all the icons on the Polymer site

**Comment by ebidel** [comment]
Our URLs are versioned now:
https://www.polymer-project.org/0.5/components/core-icons/demo.html

I've also just fixed the link in the core-icon.html docuemenation: https://github.com/Polymer/core-icon/commit/4bbe26ad6f622aac1cec0b58cfcf54b1ff5b6ac0

**Comment by kenrothmuller** [comment]
Got it and thanks for the quick fix - I can stop scanning the HTML for icons - yay - Ken
