### ISSUE TITLE
Polymer layout collision with another frameworks like Angular Material

### ISSUE THREAD

**Issue by lucasmartinez** [Polymer/polymer#1289]
Hi. Sorry for my bad english.

I'm designing a web application with Angular Material as front end using some components from Polymer ( in special core-menu, core-submenu ).
I'm using layout from Angular Material ( like layout="column" and flex="20" ).
When I include Polymer library into my website, your layout collision with Angular Layout. I see all my imputs, div, etc, in just One line. My original layout is not respected.

Is this an issue ?

**Comment by robdodson** [comment]
Hm I wonder if it's being caused by [layout.html](https://github.com/Polymer/polymer/blob/master/layout.html#L62)

A lot of Polymer elements rely on `layout.html` so if that's the case, I don't think it will be as simple as not including that file or renaming the attribute....

**Comment by lucasmartinez** [comment]
I think you should use layout internally for your components in the shadow dom and give us the option to use or not your layout for main project. In the meantime, I can't use polymer elements because of that.
Regards.

**Comment by robdodson** [comment]
In Polymer 0.8 the layout attributes have been moved to classes, we'll see if that improves things
