### ISSUE TITLE
Map hyphenated-element-IDs to camelCase in this.$ node reference marshalling

### ISSUE THREAD

**Issue by michaelpg** [Polymer/polymer#1290]
The widespread convention is to use "hyphenated-element-IDs" in HTML. In Polymer this makes the $ syntactic sugar less sweet:

    var a = this.$['some-id'];
    var b = this.$.someId;

    <div>{{$['some-id'].label}}</div>
    <div>{{$.someId.label}}</div>

Since Polymer converts attribute names between HTML and JS, why not IDs as well?

**Comment by ssorallen** [comment]
Why is that desired? There's no auto-downcasing of attribute values in HTML like there is for attribute names.

**Comment by michaelpg** [comment]
I was asked to file this by a Polymer team member. I've expanded my comment with rationale. Thanks for considering.

**Comment by ssorallen** [comment]
You could use `someId` as the ID directly in the HTML since it's an attribute value. Values are not case-insensitive like names are:

```html
<div id="someId"></div>
...
this.$.someId;
```

**Comment by michaelpg** [comment]
The idea would be to let us use hyphenated ID names, which as I said I believe is pretty much the convention on the Web (and within Google), without having to wrap them in brackets and quotes.

    <div id="some-id"></div>
    ...
    this.$.someId;

Polymer would augment each element's `$` node mapping as follows:

    for (id in this.$) {
      var camelCaseId = toCamelCase(id);
      if (!(camelCaseId in this.$))
        this.$[camelCaseId] = this.$[id];
    }

I was told this would be pretty simple since the map is only generated once. If it's relatively simple to add I'd like to request it as a feature.

**Comment by ssorallen** [comment]
Yup yup, it would be easy to do. However, the dash-to-camel-case conversion of attribute names is done because HTML attribute names are case-insensitive. Attribute values are intentionally left alone because they have no such restriction.

Doing this would also make clashes possible, for example:

```html
<div id="fooBar"></div>
<div id="foo-bar"></div>
```

In HTML those are two unique IDs, but camel casing the dashes would make them the same.

This seems like sugar that's best left to the developer if that's the ID naming style they prefer.

**Comment by justinfagnani** [comment]
I have to agree with Ross. The aliasing of ids that would occur could lead to strange, though admittedly very rare, bugs. Camel-casing attributes names is by necessity, I'm not sure symmetry beats the simplicity of doing nothing here.

**Comment by thedeeno** [comment]
I agree, this sugar seems like developer rather than framework choice. The `$['..']` syntax, while arguably ugly, is definitely not surprising.

**Comment by sorvell** [comment]
We've elected not to provide extra sugar for this right now. We'll consider it based on additional user feedback
