### ISSUE TITLE
on-tap not fired on button when text content is tapped, on-click does

### ISSUE THREAD

**Issue by marcoms** [Polymer/polymer#1292]
<!doctype html>
	<html>
		<head>
			<meta charset="utf-8">
			<title>test</title>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/polymer/0.5.5/polymer.min.js"></script>
			<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

			<polymer-element name="x-btn">
				<template>
					<button style="padding: 24px;" on-tap="{{log}}"><content></content></button>
				</template>

				<script>
					Polymer({
						n: 0,

						log: function() {
							console.log(this.n++);
						}
					})
				</script>
			</polymer-element>
		</head>

		<body>
			<x-btn>tap on the text, then the padded area</x-btn>
		</body>
	</html>

Demo [here](http://zoo-keeper-henry-75638.bitballoon.com/)

Tapping on the text area of the button will not run the callback, but the padded area will. This only works on mobile or device emulation mode in Chrome. :/

Big issue if you want to listen to a tap on a button, but it doesn't get recognised 50% of the time

**Comment by kuc** [comment]
Bug still exists in 1.0

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
