### ISSUE TITLE
[0.8] Unexpected token ]

### ISSUE THREAD

**Issue by robdodson** [Polymer/polymer#1298]
Not sure why I'm getting this error, maybe it's PEBCAK, but nothing is jumping out at me as wrong in my element definition.

**Element definition**:

```html
<link rel="import" href="../../bower_components/polymer/polymer.html">

<dom-module id="dnews-story-comments">
  <style>
    :host {
      display: inline-block;
    }
  </style>
  <template>
    <span>[[votes]] points and</span>
  </template>
</dom-module>

<script>

  Polymer({

    is: 'dnews-story-comments',

    properties: {
      votes: Number
    }

  });

</script>
```

**Usage**:

```html
<dnews-story-comments votes="2"></dnews-story-comments>
```

**Error**:

```js
(function(old
/**/) {
	this._nodes[0].textContent = this._data.points]] points a;
})
```

**Comment by IntranetFactory** [comment]
Afaik the binding annotation must currently span the entire content of the tag (https://github.com/Polymer/polymer/blob/0.8-preview/PRIMER.md#basic-property-binding)

So  `<span>[[votes]]</span> points and` might work

**Comment by robdodson** [comment]
@IntranetFactory ah thanks! I totally overlooked that. Well hopefully this ticket can serve as a signpost for anyone else who makes the same mistake :)
