### ISSUE TITLE
Support for on demand databinding

### ISSUE THREAD

**Issue by paulgingrich** [Polymer/polymer#1303]
I have a use case that is not covered by polymer today.  I have a database that I want to expose as a non visual polymer component.  Widgets can bind to the data in the database using mustache notation or through the polymer editor.  For example,
<input value={{$.db.entry}}> where db is the id of the database polymer component.  Because the database is large in relation to the number of entries that the application will bind to, rather than declaratively publish all entries in the database, I would like to only publish the ones that are used by other widgets on the fly on demand.  Currently, the only way to do this is to duplicate the information and have the user inform the database which entries it is interested in in a declarative fashion.  I would prefer something like a pre-binding event where I can validate that the entry is valid for my database, and create the onEntry() handler to responde to changes after the binding has been created.

Here is a link to further discussions on this topic:
http://stackoverflow.com/questions/28639863/how-to-dynamically-create-properties-in-polymer-as-needed/29106288

**Comment by TimvdLippe** [comment]
@paulgingrich This is quite an old request, but Polymer 2 allows you to customize the bindings parser with [overriding `_parseBindings`](https://www.polymer-project.org/2.0/docs/api/elements/Polymer.Element#method-_parseBindings) Could you confirm/deny that you can implement your usecase with that?

**Comment by TimvdLippe** [comment]
Closing for now as I assume this is possible. Feel free to reopen if you are unable to make it work with Polymer 2!
