### ISSUE TITLE
Slow performance of template-repeat custom element

### ISSUE THREAD

**Issue by arodic** [Polymer/polymer#1304]
My team has been working on an app that pushes Polymer's performance to its limits and it turned out template-repeat can be a huge performance bottleneck.

I recently build a simple benchmark that creates massive recursive objects and arrays in order to measure how template-repeat performs in various conditions such as object creation and mutation.

[Live Benchmark](http://akirodic.com/polymer-performance-test/index.html) - [(Source)](https://github.com/arodic/polymer-performance-test)

With initial settings, the benchmark creates branching structures of arrays/object with 1000 leaf nodes. On my macbook pro, it takes about 1 second for polymer to do its work each time a new recursive array/object is created.

An interesting observation is that array mutation (changing the leaf values) takes about the same time as creating a whole new array structure.

Another observation is that this [hack](https://github.com/arodic/polymer-performance-test/blob/master/value-object.html#L18) I created to enable template-repeat [iteration on objects](https://github.com/Polymer/polymer-expressions/issues/11), actually improves performance of both object and array mutations by 10x!

I also tried running the benchmark against [recent PR](https://github.com/Polymer/TemplateBinding/pull/211) that enables object iteration in Polymer and in that case object creation and mutation performance increased 5x (mutations still 2x slower than my hack) while array tests run equally slow.

I hope this benchmark will help you improve performance of template-repeat element.

Let me know if you need any additional details.

**Comment by devinivy** [comment]
We have run into this issue as well.  @arodic how exactly do you use the hack that you created?

**Comment by arodic** [comment]
Hry @devinivy I use [this filter](https://github.com/arodic/io-value/blob/master/io-object-to-array.html) to convert observed objet to array. It returns an array where each element is an object with key and value property that maps to observed object. To use it in an element, I find it the easiest to use computed property [like I did here](https://github.com/arodic/io-value/blob/master/io-object.html#L103).

**Comment by arodic** [comment]
@devinivy you can also pass it an array since arrays are also objects.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
