### ISSUE TITLE
this.$.container in documentation

### ISSUE THREAD

**Issue by KrisSiegel** [Polymer/polymer#1308]
Perhaps this is my misunderstanding but in multiple places this.$.container is referenced and shown when attempting to use querySelector within your component's shadow dom. However, I've never been able to access the container property as it's always undefined for me. Instead I can either access elements by id using this.$.<id> or I can use this.shadowRoot.

I've tried the different polymer events (ready, attached, domReady) but I've never seen this.$.container not be undefined.

**Comment by batista** [comment]
@KrisSiegel are you refering to something like in the second scenario in [automatic-node-finding](https://www.polymer-project.org/0.5/docs/polymer/polymer.html#automatic-node-finding) documentation?

>To locate other nodes inside the element’s shadow DOM, you can create a container element with a known ID and use querySelector to retrieve descendants. For example, if your element’s template looks like this:

>```html
<template>
  <div id="container">
    <template if="{{some_condition}}">
      <div id="inner">
       This content is created by data binding.
      </div>
    </template>
  </div>
</template>
```
>You can locate the inner container using:

>```javascript
this.$.container.querySelector('#inner');
```

if that is the case, note the ```<div id="container">``` declaration.

**Comment by davidmaxwaterman** [comment]
Yeah, your question is a little confusing - could you show us some code?

I suspect you're just misunderstanding, but it could be that you've not defined your ```#container``` div correctly.

**Comment by KrisSiegel** [comment]
@batista you hit it; I've never seen a div with an id of "container" in the documentation (I suspect it's omitted in some places and I probably overlooked it in others) so I assumed it was something provided by polymer versus something manually defined by the developer.

Thanks! When I get a chance later today I'll double check some of the documentation I found and perhaps I can make an issue (or PR, not sure if all of it is in GitHub) to add clarification if the container div is truly missing.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
