### ISSUE TITLE
Spaces in binding causes SyntaxError: Unexpected identifier.

### ISSUE THREAD

**Issue by dj2** [Polymer/polymer#1311]
I put <span>{{ name }}</span> in my dom-module and when I refreshed I got a 'SyntaxError: Unexpected identifier' in the console.  The bad method can be seen below:

```
(function(value
/**/) {
var old = this._setData(' name ', value);
if (value !== old) {
  this._ name Effector(old);
}
})
```

This is coming from bind/bind.html and it looks like it isn't stripping space before/after the property name inside the {{}}. Changing to {{name}} fixes the issue.

This is with 0.8-preview @ ce0a765b77

**Comment by thedeeno** [comment]
We're seeing this on our team as well.
