### ISSUE TITLE
x-repeat sort error: TypeError: this.sortFn is not a function

### ISSUE THREAD

**Issue by dj2** [Polymer/polymer#1315]
In x-repeat.html when the sort function is used (~ line 235), the code has return this.sortFn(c.getItem(a), c.getItem(b));

This doesn't work. The method on this is called _sortFn, but it's also pulled out earlier as var sortFn (~ line 201). So, changing to:

return sortFn(c.getItem(a), c.getItem(b)); 

fixes the issue.

This is with 0.8-preview.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
