### ISSUE TITLE
Polymer function not accessible in firefox/safari

### ISSUE THREAD

**Issue by prateekbh** [Polymer/polymer#1316]
So I made a polymer element.
and in the script part i wrote this

<script>
        Polymer({
            renderEvents:function(e,shipment_id){
                this.events=e.events;
                this.shipment_id=shipment_id;
            }
        });
    </script>

And in my JS controller i wrote:

var timelineEl=document.querySelector(".timeline-shipment");
console.log(timelineEl);
timelineEl.renderEvents(data,$scope.shipment_id);

This works fine in chrome but not in firefox/safari...
I had to do this:
timelineEl.__proto__.renderEvents(data,$scope.shipment_id);

**Comment by bruunofco** [comment]
Any example in Plunker?

**Comment by prateekbh** [comment]
unable to get a polymer example running in plunkr... can help?

**Comment by prateekbh** [comment]
Sample code:
<polymer-element name="eventtimeline">
    <template  attributes="events">
        <div class="timeline">
            <template repeat="{{events}}">
                <div>Hi</div>
            </template>
        </div>
    </template>
    <script>
        Polymer({
            renderEvents:function(e){
                this.events=e.events;
            }
        });
    </script>
</polymer-element>

**Comment by prateekbh** [comment]
So i was using a SPA
and the other view which loaded via ajax was bringing in new polymer tags
so it was not getting initialised before i accessed them..
any way of knowing such initialisation event?
