### ISSUE TITLE
node.bind() incorrectly verifies that the property exists

### ISSUE THREAD

**Issue by paulgingrich** [Polymer/polymer#1317]
The implementation in Polymer.js for node.bind() checks for the existence of a property before calling this.bindProperty() method.  However, if the property is specified in mixed case, it does not find the property and does not call bindProperty().  Therefore, to work properly, I must convert my property name to lower case before calling node.bind().  I believe that this is a bug.  I should not have to do this.  I believe this makes the API incompatible with the web component definition of bind(). 

The implementation uses the method propertyForAttribute which correctly returns the property name given the lower case attribute name, but node.bind() should assume the name is an attribute.  It should support properties as well.  

A simple fix would be to add a name.toLowerCase() on the call to propertyForAttribute()

for example

this.propertyForAttribute(name.toLowerCase());  would work better than just

this.propertyForAttribute(name);

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
