### ISSUE TITLE
paper-input focus method doesn't work

### ISSUE THREAD

**Issue by bashvlas** [Polymer/polymer#1318]
paper-input focus method doesn't work.

**Comment by emreturkay** [comment]
Probably related:

An `<input>` tag with `autofocus` attribute within a `<paper-input-decorator>` doesn't "auto focus" in safari & firefox (works in chrome). Tested with Polymer 0.5.4.

The HTML:
```html
<paper-input-decorator>      
      <input id="text" is="core-input" autofocus>   <!-- This doesn't autofocus -->
</paper-input-decorator>
```
The JavaScript:
```javascript
document.getElementById("text").focus();   // This doesn't focus either.
```

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
