### ISSUE TITLE
bug with IE in polymer.js

### ISSUE THREAD

**Issue by TimWillis** [Polymer/polymer#1319]
Hey, I found a bug thrown in ie. the bug is variable not defined in strict mode. The offending code is:
case 'scheme data':
          if ('?' == c) {
            query = '?';
            state = 'query';
          } else if ('#' == c) {
            this._fragment = '#';
            state = 'fragment';
          } else {
            // XXX error handling
            if (EOF != c && '\t' != c && '\n' != c && '\r' != c) {
              this._schemeData += percentEscape(c);
            }
          }
          break;

found around 7651

This breaks IE code execution completely.

I fixed by just adding var in front of query, state, but may need to declare this variables further up the page.

thanks
Tim

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
