### ISSUE TITLE
What polymer bring to us?

### ISSUE THREAD

**Issue by Colstuwjx** [Polymer/polymer#1325]
Thanks to polymer bring a web component world.
However, Opensource World has a lot of JQuery libs & tools,  such as DataTable\Select2 etc.
They are so cool, and make front-end development more faster!

If I turn to use Polymer, I just cannot re-use it anymore? any idea about this?

**Comment by gertcuykens** [comment]
Normally Polymer does not mess up jquery, just make your own components. In short Polymer is just an abstraction to make custom html tags and some fancy binding stuff thats it. The paper elements are only pre made building blocks.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
