### ISSUE TITLE
Tool-tip issues on paper-fab on toolbar

### ISSUE THREAD

**Issue by tamas-brisbane** [Polymer/polymer#1326]
I tried to add a core tool-tip to a core toolbar element and then adding a paper-fab to the tool-tip.
It does work but the paper-fab is not located on the toolbar but a bit below that and the tool-tip shows up on the toolbar.

I understand this is a cross-compatibility issue between the core and paper elements I still think it is worth to be mentioned, if it hasn't been done before.

Thanks

Tamas

PS: Screen-dump of the issue. I used the Chrome Dev Editor with the built-in Polymer start-up project.

![image](https://cloud.githubusercontent.com/assets/11612956/6780087/e16c75b8-d1ad-11e4-9dff-b8e23130b810.png)

**Comment by ebidel** [comment]
Can you provide a code snippet of your setup?

**Comment by tamas-brisbane** [comment]
Setup as in...?

The source code how I call these objects as follows:

```$( "#coretoolbar" ).append("<core-tooltip label=\"New\" position=\"bottom\"><paper-fab icon=\"add\"></paper-fab></core-tooltip label>");```


As you can see the core-toolbar element (id="coretoolbar") is appended by the html code of the tooltip and the fab button added to the tooltip - same as in documentations.

If I use the other type of button (paper-icon-button) instead of paper-fab with tooltip it works fine, no issues whatsoever.

The core-tooltip component is not added to the Chrome Dev Editor project - so I downloaded from the site and added to the project folder, then imported in the html source and refactored for CSP.

My guess here is as follows: It seems that the paper-fab button is aligned to the tooltip objects and when the tooltip object is aligned to the core-toolbar then the paper-fab button gets mis-positioned...purely because it is aligned to the tooltip...in short it seems like a CSS issue, but again, this is the result of my guesswork...

The Dev Editor set-up is out-of-box...0.20.3503

Hope this helps...

btw - this is the tooltip with fab - you can see the fab is not on the edge of the bar...
![clipboard01](https://cloud.githubusercontent.com/assets/11612956/6793761/19bbcd12-d215-11e4-8449-8384bf1cab67.jpg)

this is when the tooltip is used with paper-icon-button...as you can see it's all good...
![clipboard02](https://cloud.githubusercontent.com/assets/11612956/6793762/1a21908e-d215-11e4-88b9-9178cc9c24ac.jpg)

**Comment by bruunofco** [comment]
Hello,

Can simulate this error using Plunker or similar?
It is likely that there is some error in the structure of your HTML or CSS style.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
