### ISSUE TITLE
Recommendation: "/components/..." should point to the latest version of the library

### ISSUE THREAD

**Issue by ksgy** [Polymer/polymer#1329]
Hi,

I'm including polymer components on some pages. Previously (from a demo page) I've used this URL the get paper-ripple:
http://www.polymer-project.org/components/paper-ripple/paper-ripple.html

Figured out, this has been changed to 
http://www.polymer-project.org/0.5/components/paper-ripple/paper-ripple.html (added the version)

Don't know if it's easy to achieve, but the link without the version should point to the latest version to (at least) to not to get 404 error messages when loading the page.

Thanks

**Comment by justinfagnani** [comment]
You have a point, but we're also not intending polymer-project.org to be a CDN in this way. Even if we pointed to the latest elements, without version management there's no guarantee that the latest version wouldn't break someone. I highly recommend serving up your own elements for now, and resolving versions via bower.

**Comment by ebidel** [comment]
What @justinfagnani said. We're really trying to get people off of hot linking to URLs that were never intended to be stable.

**Comment by ksgy** [comment]
Makes sense, thanks!
