### ISSUE TITLE
Polymer not rendering HTML Escaped Characters

### ISSUE THREAD

**Issue by tamsler** [Polymer/polymer#1331]
Polymer doesn't render HTML escaped characters.

Characters like \&#8220; etc.

If any of these characters is bound to a template, these characters are not interpreted.

e.g.
var message = "Hello \&#8220;world\&#8221;";
\<div>{{message}}\</div>

displays: Hello \&#8220;world\&#8221;

... instead of: Hello &#8220;world&#8221;

**Comment by bruunofco** [comment]
Hello,

For security the Polymer escapes any HTML element. This avoids many problems.

There is a specific function for inserting HTML elements. injectBoundHTML.

Below is an example.

```html
<polymer-element name="my-element">
  <template>
    <div id="message_area"></div>
  </template>
  <script>
    Polymer({
      message: 'hi there',
      ready: function() {
        this.injectBoundHTML('<b>{{message}}</b>', this.$.message_area);
      }
    });
  </script>
</polymer-element>
```

Hope this helps.

**Comment by tamsler** [comment]
@bruunofco Thank you for your reply. The issue is that if "message" contains HTML and or HTML escaped characters, it won't render them.
e.g.

```html
<polymer-element name="my-element">
  <template>
    <div id="message_area"></div>
  </template>
  <script>
    Polymer({
      message: 'hi &#8220;there',
      ready: function() {
        this.injectBoundHTML('<b>{{message}}</b>', this.$.message_area);
      }
    });
  </script>
</polymer-element>
```

**Comment by tamsler** [comment]
Never mind. I made a mistake. The injectBoundHTML() method works perfectly.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
