### ISSUE TITLE
tiny bug 0.5.5 updateBindings variable name error

### ISSUE THREAD

**Issue by KPblCEHblLLl** [Polymer/polymer#1332]
polymer.js:
```
function updateBindings(node, name, binding) {
    ...
    if (bindings[name])
      binding[name].close();
```
should be `bindingS[name].close()` or it crushes

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
