### ISSUE TITLE
Safari 8.0.5 rendering problems

### ISSUE THREAD

**Issue by DzinVision** [Polymer/polymer#1334]
In Safari 8.0.5 (10600.5.15) (available on Mac OS X 10.10.3 beta) polymer does not render properly.
![screen shot 2015-03-25 at 4 09 38 pm](https://cloud.githubusercontent.com/assets/5161200/6827704/5d0b5b9c-d309-11e4-8c83-e665af440aa7.png)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
