### ISSUE TITLE
[0.8] Feature request: computed properties in x-repeat

### ISSUE THREAD

**Issue by morethanreal** [Polymer/polymer#1337]
I would like to use computed properties based on array data used in an `x-repeat`. For example, given data like this:

```js
items: [
      {
        "type": "phone"
      },
      {
        "type": "email"
      }
]
```

I want to be able to do:

```html
<template is="x-repeat" item="{{items}}">
    <core-icon icon="[[computeIconFromType(item.type)]]"></core-icon>
</template>
```

**Comment by chuckh** [comment]
+!

**Comment by Lorenzbi** [comment]
+1 Is there a workaround yet?

ps: Issue #1337 :)

**Comment by mdwragg** [comment]
:+1:   Needed here too +1 @robdodson - do you know a workaround?

**Comment by robdodson** [comment]
@kevinpschaaf and @sorvell are the Polymer core wizards who might know secret black magic workarounds :sparkles:

**Comment by kevinpschaaf** [comment]
There are no good workarounds right now.  This will definitely be done before 1.0, hopefully in 0.9 timeframe.

**Comment by dhubler** [comment]
why can't you use filter?

 <core-icon icon="[[item.type | computeIconFromType]]"


[[computeIconFromType(item.type)]]

**Comment by mdwragg** [comment]
Does this not work either?

```<span hidden$="[[!enabled]]">{{item.label}}</span>```

in an ```x-repeat``` block? Where enabled is a property.

**Comment by mbleigh** [comment]
As an alternative (or in addition), what about a `map` that lets you modify the items as you run through them:

```html
<template is="x-repeat" map="prepareRepeat" items="[[users]]">
  <a href="[[item.profileLink]]">[[item.name]]</a>
</template>
<script>
  Polymer({
    prepareRepeat: function(user) {
      return {
        name: user.name,
        profileLink: "/users/" + user.id
      }
    }
  })
</script>
```

**Comment by kevinpschaaf** [comment]
Closing, as inline computed binding support landed in https://github.com/Polymer/polymer/pull/1422 and https://github.com/Polymer/polymer/pull/1398.
