### ISSUE TITLE
Is there a plan for wrapping IndexedDB?

### ISSUE THREAD

**Issue by nanowang** [Polymer/polymer#1340]
As the title says

**Comment by ebidel** [comment]
I don't think there's any plan atm. @addyosmani threw https://github.com/addyosmani/polymer-localforage a while back.

**Comment by nanowang** [comment]
@ebidel 

Hi,

The repo `polymer-localforage` hasn't been update since a looong time ago.

In addition, I believe `localforage` itself has some performance drawback for its pretty good compatibility.

So I'm creating a custom element to wrap indexeddb, since
1. I don't care about the out-dated deprecated WebSQL, 
2. there's no official plan for this kind of element.

What I'm asking is, do polymer team accept core-element from the community?
