### ISSUE TITLE
I volunteer to help organise, and maintain, this issue list

### ISSUE THREAD

**Issue by mercmobily** [Polymer/polymer#1345]
Hi there,

I think Polymer has immense potential, and deserves a lot of attention. I am planning on adding Polymer support to my own [Hotplate](https://github.com/mercmobily/hotplate) this year.

However! I find this issue list a little more polluted than it could be. I offer myself to:

* Close issues that should most likely be closed. E. g. https://github.com/Polymer/polymer/issues/1331 and https://github.com/Polymer/polymer/issues/1325
* Tag issues as  enhancement, bug, duplicate, invalid, question, wontfix (the default ones offered by GutHub)
* Attempt to answer basic questions whenever possible

Please let me know if you want me to get on with it. I am willing to start right away.
Thanks!

**Comment by mercmobily** [comment]
Err... maybe I should just get started, and if anybody objects they can just let me know?

**Comment by mercmobily** [comment]
I just noticed some labels popping up, 0.8 and bug. Please let me know if you don't want my help, no hard feelings either way!

**Comment by azakus** [comment]
Thanks for the offer, please let us know if you are still interested!

**Comment by mercmobily** [comment]
Absolutely interested. I am helping out with the documentation already (I might have seen those tickets). Generally speaking, I love issue pruning and generally helping out with the Polymer project. So, given that I am still interested, where do we go from here? my email is tonymobily@gmail.com if you'd like to talk privately (although I am happy to talk here!)

**Comment by tjsavage** [comment]
Will send you an email!
