### ISSUE TITLE
Site down: Is this a known bug? "ReferenceError: Can't find variable: query" on Safari

### ISSUE THREAD

**Issue by richieb** [Polymer/polymer#1347]
I am getting this error in Safari only and I wondering if it is related to Polymer.js:
```ReferenceError: Can't find variable: query```

I would appreciate a quick reply because our site is down due to this possible bug. We will continue to dig around to see if it is related to our code. The line that is throwing the error is here (in the parse function):
```case 'scheme data':
          if ('?' == c) {
            query = '?'; <-- Error -------
            state = 'query';
          } else if ('#' == c) {
            this._fragment = '#';
            state = 'fragment';
          } else {
```

**Comment by richieb** [comment]
We found the bug, and it is indeed a Polymer bug. 
If you have a question mark character "?" inside your template (in our case the question mark was part of a simple href link for an email mailto), it messes with the Polymer parse function. See my original message.

This bug should be fixed pronto because it can kill an entire Polymer app and cause frustration. It kills Polymer apps only on Safari.

**Comment by arthurevans** [comment]
Specifically, this looks like a bug in webcomponents.js:

https://github.com/webcomponents/webcomponentsjs/blob/master/src/URL/URL.js#L148

Looks like `query` should be `this._query` on that line? Can you add an example URL that causes this problem for testing purposes?

**Comment by richieb** [comment]
Thanks for following up on this, Arthur, and I apologize for this late response. Here is an example of the code that caused the problem:
```
<template>
The question mark in the href link below throws an error on Safari and kills the entire Polymer app (nothing loads):
<a href='mailto:me@gmail.com?Subject=Website%20Comment%201' target='_top'>me@gmail.com</a>
</template>
```

On an entirely separate note, what is the recommended Polymer way to find an element's parent node, especially if the child is in a shadow root? *Element.parentNode* works when there is no shadow root, and of course we can run a while loop penetrating the parentNodes' shadow root, **but what is the best syntax (that works with Polymer's polypill) to penetrate an element's parent shadow dom from element.parentNode** ? Sure, looking downwards with /deep/ works charmingly, like the way you have answered my questions. But  looking upwards seems to be more elusive. We definitely don't want to do document.querySelector(). Walking up using parentnode is what we are after, as in jQuery's *element.parents ("parentElementClassOrIDName");*

**Comment by richieb** [comment]
Regarding my little question in my last post, to put the question another way, what is Polymer's polyfill syntax for *element.parentNode.host*?

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
