### ISSUE TITLE
Scaffold blinking

### ISSUE THREAD

**Issue by victoriaSh** [Polymer/polymer#1352]
Main screen blinking grey and black while drawer is opening. 
In browser it's ok but on Nexus5 it always reproduces.

I found the problem - you should delete "opacity: 0; " and transition too for #scrim from core-drawer-panel.css

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
