### ISSUE TITLE
Webcomponentsjs error

### ISSUE THREAD

**Issue by teckays** [Polymer/polymer#1353]
I'm getting a `Uncaught TypeError: undefined is not a function` error on this [line] 
(https://github.com/Polymer/webcomponentsjs-dev/blob/master/webcomponents.js#L34). `console.log()` of `flags.log` outputs `Object {}`. It popped-up I didn't even realise it, the app works OK (at least it seems like). I don't exclude the fact that I messed up something in my code which I would love to find and fix it but unfortunately I cannot track this error down, any ideas what could be the cause or how to debug it? 

PS. Chrome debugger didn't help in this particular case.

**Comment by bruunofco** [comment]
Hello, could simulate this same error using Plunker?

**Comment by teckays** [comment]
@bruunofco will try this out, will be difficult because I have a quite complex app and have no idea where this error come from. Will post it here if I have something.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
