### ISSUE TITLE
Why polymer create non-ui element?

### ISSUE THREAD

**Issue by acthtml** [Polymer/polymer#1354]
why polymer create non-ui element ?

why not inject the function into the javascript obejct?

like &lt;core-ajax&gt; => $.ajax();

poor english, sorry

**Comment by justinfagnani** [comment]
Elements have some nice properties that we take advantage of when possible:

 * They live in the DOM tree and can be referenced various ways: `this.$`, `querySelector`, `childNodes`, etc.
 * They have the custom element lifecycle of created, attached, detached, etc.
 * They have a natural serialized form in HTML.
 * They can fire DOM events, which in turn have useful features like bubbling, behaviors at shadow boundaries.
 * They can directly participate in our data-binding system.
 * Sometimes it's interesting to be able to render and style what would normally be non-UI

In general we like the idea of building an app out of generally the same "stuff", and for us that is elements. It's not a hard and fast rule that everything be built this way, but we certainly try to embrace this style where we can.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
