### ISSUE TITLE
Component becomes unusable if you remove and add it back

### ISSUE THREAD

**Issue by cwayfinder** [Polymer/polymer#1355]
Issue happens when you remove `paper-checkbox` from DOM and then add it again. Look at [live demo](http://screencast.com/t/8fmy4Amjr).
Remark: the `checkedChanged` watcher doesn't work but the `attributeChanged` works. Something related to the properties observer goes wrong.

```html
<!doctype html>
<html>
<head>
  <script src="../webcomponentsjs/webcomponents.js"></script>
  <link rel="import" href="paper-checkbox.html">
</head>

<body unresolved>
  <div>
    <button id="show">show</button>
    <button id="hide">hide</button>
  </div>
  
  <script>
    var element = document.createElement('paper-checkbox');
  
    document.getElementById('show').addEventListener('click', function () {
      document.body.appendChild(element);
    });
  
    document.getElementById('hide').addEventListener('click', function () {
      document.body.removeChild(element);
    });
  </script>
</body>
</html>
```

This critical issue occurs for other polymer elements as well.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
