### ISSUE TITLE
Valid css class name characters (hyphen) throws Unexpected Token ILLEGAL

### ISSUE THREAD

**Issue by w-p** [Polymer/polymer#1357]
Using a CSS class name containing a hyphen '-' in a tokenList filter on the class attribute of an element throws an Unexpected Token ILLEGAL error.  I assume this is because the class name is being pass to a javascript object.  I've tried encapsulating the name in a variety of quote combinations to no avail. I'm left with the options of underscore or dollar sign as a separator.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
