### ISSUE TITLE
Ripple effect on certain paper elements doesn't reset on right button click.

### ISSUE THREAD

**Issue by biwin** [Polymer/polymer#1358]
Playing around the Polymer official demos, found that the ripple effect on certain elements doesn't reset if right button is pressed while holding the left button clicked on some element with ripple effect.

Screencast for this.
https://youtu.be/xgAtdJoll-g

Not sure if a bug or feature.
The buttons on https://www.polymer-project.org/0.5/components/paper-button/demo.html are free from this.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
