### ISSUE TITLE
[0.5.5] Chrome doesn't allow inner components to be styled and stops the propagation of events outside the custom element

### ISSUE THREAD

**Issue by elegos** [Polymer/polymer#1361]
Hello!

I'm attempting creating a paper-button able to trigger a form's submit event. My first attempt was to create a custom element extending "button", but that disabled the ripple somehow on Firefox.

I then came up with the idea of placing the `paper-button` and a hidden standard `button` (with `type="submit"`), so that on the `click` event of the `paper-button` procs the button's click and thus the outer form's submission.

Also I've created a style which applies to all the paper-button with class 'blue' (see the code below).

All these things work as expected on Firefox, but **on Chrome** the `button`'s click event is ignored by the outer form and the `paper-button.blue` style is ignored.

Style, referenced in a standard CSS file inside the HTML page:

    paper-button.blue {
      color: #FFFFFF;
      background-color: #2196F3; }

`paper-submit` polymer element:

    <link href="../polymer/polymer.html" rel="import">
    <link href="../paper-button/paper-button.html" rel="import">

    <link href="../polymer/polymer.html" rel="import">
    <link href="../paper-button/paper-button.html" rel="import">

    <polymer-element name="paper-submit" attributes="bClass raised recenteringTouch fill" role="button">
        <template>
            <style>
                #submit-button {
                    display: none;
                }
            </style>
            <paper-button id="button" on-click="{{click_submit}}" class="{{bClass}}" raised="{{raised}}" recenteringTouch="{{recenteringTouch}}" role="button">
                <content></content>
            </paper-button>

            <button type="submit" id="submit-button"></button>
        </template>
        <script>
            Polymer({
                publish: {
                    bClass: '',
                    raised: false,
                    recenteringTouch: false,
                    fill: true
                },

                click_submit: function () {
                    var submit = this.$['submit-button'];
                    submit.click();
                }
            });
        </script>
    </polymer-element>

**How to reproduce**: create a simple `form` with some required fields, then click on the `paper-submit` DOM element, defined as follows:

    <paper-submit bClass="blue" role="button" tabindex="0">Click me</paper-submit>

Note: the color works if you create a `paper-button` element directly in the body:

    <paper-button class="blue" role="button">I work</paper-button>

Thanks :)

**Comment by elegos** [comment]
As for the style problem, I was unaware of the `/deep/` selector. Using it, Chrome styles the button correctly.

Now, because of this behavior I suspect it's the web components Chrome's management to isolate the component and its events from the outside. I tried using the following code, but it will then bypass the HTML5's validation:

        function getParentForm(el) {
            var parent = el.parentNode,
                tag = parent.tagName.toLowerCase();
            if (tag === 'form') {
                return parent;
            }
            if (tag === 'body') {
                return null;
            }

            return getParentForm(parent);
        }
        Polymer({
            publish: {
                bClass: '',
                raised: false,
                recenteringTouch: false,
                fill: true
            },

            click_submit: function () {
                var form = getParentForm(this);

                if (form) {
                    form.submit();
                }
            }
        });

**Comment by elegos** [comment]
Ok, I came with a workaround, hoping this will be fixed (?) as soon as possible. The main concept is to find the closest form, inject a submit button, click on it and eventually remove it from the DOM. This allows HTML5 validation to trigger and everything seems to be OK.

        function getParentForm(el) {
            var parent = el.parentNode,
                tag = parent.tagName.toLowerCase();
            if (tag === 'form') {
                return parent;
            }
            if (tag === 'body') {
                return null;
            }

            return getParentForm(parent);
        }
        Polymer({
            publish: {
                bClass: '',
                raised: false,
                recenteringTouch: false,
                fill: true
            },

            click_submit: function () {
                var form = getParentForm(this);
                if (form) {
                    var button = document.createElement("button");
                    button.setAttribute("type", "submit");
                    form.appendChild(button);
                    button.click();
                    form.removeChild(button);
                }
            }
        });

**Comment by elegos** [comment]
FYI, I've created a paper-submit webcomponent, you can install it via bower (paper-submit). This is the link on GitHub: https://github.com/elegos/paper-submit

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
