### ISSUE TITLE
[0.8] - default property values are not set by the time observers are called

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#1364]
In this example, I'm seeing `this.published === undefined` in `keyChanged`. I'd expect all of the element's properties to have their default values by the time `keyChanged` is called:

    Polymer({
        is: 'google-sheets',
        properties: {
          key: {
            type: String,
            value: '',
            observer: 'keyChanged'
          },
          published: {
            type: Boolean,
            value: false
          }
        },

        keyChanged: function(newValue, oldValue) {
          //this.published === undefined when the element loads
        }
    });

**Comment by sorvell** [comment]
You cannot depend on the value of one property in the observer of another. Instead consider this:

    observers: {
      'key published': 'doStuff'
    }

**Comment by ebidel** [comment]
Thanks @sorvell. So is [this](https://github.com/Polymer/core-ajax/blob/0.8-preview/core-ajax.html#L308-L311) the recommended pattern now? I also want to react to individual properties changing later on.

--
@arthurevans I think we can be more precise in the [section on `observers`](https://www.polymer-project.org/0.8/docs/devguide/properties.html#observing-changes-to-multiple-properties). What's not clear:

1. When does the callback get called? end of micro task?
2. If any of the properties change, the callback gets called. People could think they all have to change.

**Comment by sorvell** [comment]
>
> So is this
> <https://github.com/Polymer/core-ajax/blob/0.8-preview/core-ajax.html#L308-L311> the
> recommended pattern now?


Yes, but this is an area we're still refining so it may change slightly in
the 0.9 timeframe.


> When does the callback get called? end of micro task?
>

Yes


> If any of the properties change, the callback gets called. People could
> think they all have to change.
>

Yes
