### ISSUE TITLE
[ShadyDOM] Exception when removing non-distributed nodes

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer#1366]
This code throws:
```
let child = Polymer.dom(this).querySelector('#not-distributed');
console.assert(Polymer.dom(child).parentNode == this);
Polymer.dom(this).removeChild(child);
```
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**Comment by sorvell** [comment]
Good catch, we'll need to check if the element is distributed here.

**Comment by sorvell** [comment]
Cannot repro. Please re-open if this issues comes back.
