### ISSUE TITLE
[x-repeat] can't bind to childNodes under Shadow DOM

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer#1367]
With a template like this:
```
<template>
  <template is="x-repeat" items="{{fooNodes}}">{{item.nodeName}}</template>
</template>
```

And code like this:
```
this.fooNodes = Polymer.dom(foo).childNodes;
```

An exception is thrown under Shadow DOM, but not Shady DOM:

Uncaught TypeError: this.collection.observe is not a function

**Comment by justinfagnani** [comment]
I presume this is because Polymer.dom().childNodes is an Array under Shady DOM, but a NodeList under Shadow DOM.

If possible, x-repeat should be made to handle NodeLists, if not Polymer.dom() should tag its arrays somehow so that they also cause an exception in x-repeat.

**Comment by sorvell** [comment]
Currently `x-repeat` requires an array. We should probably make Polymer.dom().childNodes an actual array for consistency, but it does cover up a potentially confusing issue wrt `x-repeat`.

**Comment by justinfagnani** [comment]
Making childNodes an Array would be nice for consistency...
