### ISSUE TITLE
[0.8] `Polymer.Base.chainObject` tosses out existing prototype chains

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer#1368]
`Polymer.Base.chainObject` will toss out a prototype chain that already exists on the `object` being chained to `inherited`. Since the `Polymer` helper function uses `Polymer.Base.chainObject` to chain a provided prototype with `Polymer.Base`, it is very difficult to apply traditional prototypal inheritance strategies to Polymer elements.

**Comment by TimvdLippe** [comment]
Closing as this API is on the legacy element.
