### ISSUE TITLE
Polymer in 10 Minutes - Reusing other elements

### ISSUE THREAD

**Issue by Gregory-Phillips** [Polymer/polymer#1370]
I'm walking through the Tutorial and I am at the beginning of this walk through. When I get to the Reusing other elements and it asks to install the core-ajax:
`bower install Polymer/core-ajax`
should we not be using:
`bower install Polymer/core-ajax --save`
so it will update our `bower.json` file?

**Comment by ebidel** [comment]
This issue was moved to Polymer/docs#990
