### ISSUE TITLE
Polymer in 10 Minutes - 3. Create an app

### ISSUE THREAD

**Issue by Gregory-Phillips** [Polymer/polymer#1371]
I'm working through the https://www.polymer-project.org/0.5/docs/start/creatingelements.html
Under the section 3.Create an app it states:
website: 
Your final directory structure should look something like this:
````
yourapp/
  bower_components/
    webcomponentsjs/
    polymer/
    core-ajax/
  elements/
    my-element.html
  index.html
````
The working directory is actually scaffold out like this when following the recommended install and bower installs:
````
yourapp/
  bower_components/
    core-ajax/
    core-component-page/
    polymer/
    webcomponentsjs/
  elements/
    my-element.html
  bower.json
  index.html
```` 

Hope this feedback helps

**Comment by ebidel** [comment]
This issue was moved to Polymer/docs#989
