### ISSUE TITLE
How do you cancel job1 completely before its timeout value occur?

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#1374]
_From @gertcuykens on December 27, 2014 3:17_

https://www.polymer-project.org/docs/polymer/polymer.html#job

```html
this.responseChanged = function() {
  this.job('job1', function() { // first arg is the name of the "job"
    this.fire('done');
  }, 500);
}
```

_Copied from original issue: Polymer/docs#847_

**Comment by arthurevans** [comment]
_From @ebidel on December 27, 2014 17:29_

`job()` is for debouncing. Presumably you want whatever you're wrapping to be called at least once. If you want a cancelable call, try `async()` which can be canceled using `cancelAsync()`:

https://github.com/Polymer/polymer/blob/87b3815812aaa9f956f044e74d43460b1babee5f/src/instance/utils.js#L53

We need to document this method: https://github.com/Polymer/docs/issues/848

**Comment by arthurevans** [comment]
_From @gertcuykens on December 27, 2014 18:26_

Let say you have a hover in and hover out where the hover toaster get a delay before it disappears after a hover out. But when you hover back in quick enough you need to cancel that job of disappearing.

The thing about `async()` is that it doesn't cancel itself when you hover in out in multiple times before the timeout like `job()` does?

**Comment by arthurevans** [comment]
_From @gertcuykens on December 27, 2014 21:12_

Currently I do it like this
```js
            in: function (e){
                this.cancel=true
                document.querySelector('my-hover').fire('my-hover-in', {'title': title})
            },

            out: function (e){
                this.cancel=false
                this.job('myJob', function() {
                    if (this.cancel) return 0
                    document.querySelector('my-hover').fire('my-hover-out')
                }, 500);
            },
```
But this would be nicer

```js
            in: function (e){
                this.jobCancel('myJob')
                document.querySelector('my-hover').fire('my-hover-in', {'title': title})
            },

            out: function (e){
                this.job('myJob', function() {
                    document.querySelector('my-hover').fire('my-hover-out')
                }, 500);
            },
```

**Comment by arthurevans** [comment]
A little code poking reveals an alternate way of invoking job, using a job handle instead of a string. You can use the handle to stop the job, like this:

  this.myjob = this.job(this.myjob, function);
  this.myjob.stop();

**Big caveat** -- this syntax may be deprecated:

https://github.com/Polymer/polymer/blob/87b3815812aaa9f956f044e74d43460b1babee5f/src/instance/base.js#L52
https://github.com/Polymer/polymer/blob/master/src/lib/job.js#L41

It would be pretty trivial to add a cancelJob method. What say you, @sjmiles ?

**Comment by arthurevans** [comment]
_From @gertcuykens on December 30, 2014 22:56_

Great thanks, I would never tought of that

PS Actually I would deprecate this part haha :)
```
var n = '___' + job;
this[n] = Polymer.job.call(this, this[n], callback, wait);
```
not the following part because it is nicer and does not mess with polymer internals.
```js
return Polymer.job.call(this, job, callback, wait);
```

**Comment by arthurevans** [comment]
_From @ebidel on April 6, 2015 16:50_

This issue has gone stale. Marking as obsolete.

**Comment by arthurevans** [comment]
_From @gertcuykens on April 6, 2015 19:15_

I am happy the github issues are getting cleaned up. I know you all have things to do and I also know allot of them are invalid, but still every open issue is a frustrated user and every polymer team member should know that even it is not there fault.

**Comment by arthurevans** [comment]
Talked to core folks. I'm going to re-open and move this to Polymer/polymer as an 0.8 feature request.

**Comment by sorvell** [comment]
`this.cancelDebouncer('name')`
