### ISSUE TITLE
CSS counter not incrementing

### ISSUE THREAD

**Issue by joekode** [Polymer/polymer#1375]
Hey there,

Using the following code, css counters are not incrementing. I am guessing that this is web component related. The result is that the pseudo element just displays 1

:host-context(.block) {
	counter-reset: list-counter;
}

:host-context(.block) .question-item {
	  margin: 0;
	  padding: 20px 30px 20px 55px;
}

:host-context(.block) .question-item :before {
                content: counter(list-counter);
                counter-increment: list-counter;
    		display: block;
    		padding: 35px 0;
    		position: absolute;
    		left: 25px;
    		top: 0;
    		bottom: 0;
}

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
