### ISSUE TITLE
Polymer safari 8.0.4 issue fails making request on ready

### ISSUE THREAD

**Issue by harshakakumanu1** [Polymer/polymer#1376]
My app runs perfectly in chrome,opera and firefox but fails in Safari. I am making a get request in ready function to check whether the user have session or not. I am getting the following error when loading the page in safari. Is it something related to multiple request at single time... but other browsers seems to work fine.
![screen shot 2015-04-07 at 9 35 14 am](https://cloud.githubusercontent.com/assets/8547351/7030595/96ee8a44-dd1a-11e4-9001-18dfe2fcedf6.png)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
