### ISSUE TITLE
extends doesn't work?

### ISSUE THREAD

**Issue by pjump** [Polymer/polymer#1377]
Below is the count-button snippet from https://www.polymer-project.org/0.5/platform/custom-elements.html#extending-existing-elements slightly modified (changed template, removed the "extends" attribute) embedded in some bare-bone html assuming the same context as starter/index.html has in the tutorial.

It works fine as long as the extends attribute on <polymer-element> is removed. Adding `extends="button"` as in the example at https://www.polymer-project.org/0.5/platform/custom-elements.html#extending-existing-elements causes it to fail at creating the custom element.

I'm on `Version 41.0.2272.76 Built on Ubuntu 14.04, running on LinuxMint 17 (64-bit)`

```html
<!doctype html>
<html>

  <head>

    <title></title>

    <script src="../components/webcomponentsjs/webcomponents.js">
    </script>
    <link rel="import" href="../components/polymer/polymer.html">
    
    <polymer-element name="count-button" on-click="increment" extends="button" >
      <template>
        <style></style>
        {{counter}}++
      </template>
      <script>
        Polymer({
          counter: 0,
          increment: function(e, detail, sender) { this.counter++; }
        })
      </script>
    </polymer-element>

  </head>

  <body>
        <count-button>Button</count-button>
  </body>

</html>

```

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
