### ISSUE TITLE
[0.8] No more polymer-ready event?

### ISSUE THREAD

**Issue by JanMiksovsky** [Polymer/polymer#1381]
I'm not seeing a polymer-ready event fire anymore. I don't see it documented anywhere in the migration guide, so assume this is still a service that Polymer is going to provide. Is this event not yet implemented in 0.8?

**Comment by richardcwc** [comment]
Try this.

domReady: function() {

}

**Comment by arthurevans** [comment]
Hi Jan,

That was an oversight when putting together the guide. 

@sorvell @sjmiles is this a gap, or is the event no longer required now that things are more synchronous?

**Comment by sorvell** [comment]
In Polymer 0.8, all elements are upgraded by the time of the CE polyfill's
`WebComponentsReady` event. Therefore, there is no longer a need for a
polymer specific `polymer-ready` event.

**Comment by ebidel** [comment]
@sorvell Since there's a lot of codez out there that waits for `polymer-ready`, could we consider still firing that event in 0.8, but at `WebComponentsReady` time?

**Comment by silentHoo** [comment]
+1 for @ebidel s comment

**Comment by chuckh** [comment]
+1 for @ebidel s comment

**Comment by JanMiksovsky** [comment]
For my vote, I don't actually need polymer-ready, and am happy to use WebComponentsReady instead if that's the best practice. If a revived polymer-ready wouldn't add any value beyond WebComponentsReady, in fact, I'd prefer to see that event dropped. We've already had to extensively touch every single component we have to migrate to 0.8, an extra change won't make a difference. And in the long term, I don't think it helps the world to have two synonyms for the same event.

All we would have wanted was for for this to be mentioned in the migration guide, rather than having to puzzle over why we were no longer getting the event.

**Comment by arthurevans** [comment]
@sorvell What if you're running with native CE? Does the polyfill still fire the event? Or does the app need to know that it's running native and not wait for the event?

**Comment by sorvell** [comment]
We're inclined not to provide a `polymer-ready` out of the box mainly for the reasons Jan's mentioned.

Users that have made use of `polymer-ready` and cannot update that code can fire `polymer-ready`  manually  at `WebComponentsReady` time.

@arthurevans When the WebComponents polyfill is loaded on a page, the `WebComponentsReady` event will always fire.

**Comment by clintwood** [comment]
@sorvell, @arthurevans, I bumped up agains this...

Is `WebComponentsReady` part of the spec?

I was under impression that WebComponents was following the standards very strictly (unless unable to for technical reasons) so removing the polyfill breaks things.  Is this desired and more importantly what is the workaround/alternate for this event when the polyfill is removed?

The reason I ask is that I'm building apps deployed with [nw.js](https://github.com/nwjs/nw.js) so would like to eliminate polyfill unless really needed.

**Comment by ebidel** [comment]
> @arthurevans When the WebComponents polyfill is loaded on a page,
the WebComponentsReady event will always fire.

Doesn't this force users to always include the polyfill?

It's still unclear if Polymer will fire this event if native CEs are at
play. If the browser is running the native stuff, I would expect wc.js to
not run code.

**Comment by sorvell** [comment]
`WebComponentsReady` is not a spec thing. It's a necessary polyfill
conceit. For compatibility, it always fires when `webcomponents.js` is
included in the page, regardless of native support. It is true, of course,
that if the polyfill is removed, the event will not fire.

It's also true that a `polymer-ready` event could *always* fire,
independent of polyfill inclusion. I'd prefer polymer not do this since the
state in question is not polymer specific. It's web components specific.

The vast majority of `WebComponentsReady` event usage should be at the
application level where the user is deciding to include the polyfill or
not. If the polyfill is not included, simply putting a script at the end of
the document should suffice. In this case, the user can manually fire the
`WebComponentsReady` event in the rare case that some 3rd party code uses
it.

**Comment by ebidel** [comment]
So if someone doesn't use the polyfill, all elements will be ready by the time you get to the bottom of the page (e.g. poke at properties and methods)? All of the polymer registration asynchronicity is gone in 0.8?

**Comment by sorvell** [comment]
Yeah, that's right.

**Comment by IntranetFactory** [comment]
Is the opposite also true? So if someone uses the polyfill e.g. on IE11, all elements will be ready by the time you get to the bottom of the page? Or do I still need to wait for WebComponentsReady in that case?

**Comment by sorvell** [comment]
No, this is exactly why the event exists. When the polyfill is needed, you
must wait for `WebComponentsReady`.

**Comment by arthurevans** [comment]
No, on a brower that doesn't support the standard natively, you need to use
the polyfill AND you need to wait for the event. That's because the element
upgrade process can't be totally synchronous on a browser that doesn't
implement the standards natively. In particular, HTML Imports are
polyfilled using XMLHttpRequest, which is async. The main page loads its
elements using HTML imports, and Polymer elements need to load their
dependencies (imported elements, stylesheets, etc.) before they're ready to
go.

Likewise, if custom elements aren't built into the browser, the custom
elements polyfill needs to wait until DOMContentLoaded has fired & any
pending HTML imports have finished before going through the tree and
"upgrading" elements -- setting up their prototype chains, creating their
local DOM, and so on.

**Comment by IntranetFactory** [comment]
I therefore would prefer if Polymer continues to tell me when everything is ready. This would ensure that developers just wanting to use Polymer components don't need to be aware of these details and more importantly that they can't do it wrong.

**Comment by clintwood** [comment]
@sorvell, @arthurevans, @ebidel, @IntranetFactory, +1 to have this event functionality in Polymer!

Having an event fired by Polymer would guarantee that a Polymer app relying on such an event would NOT need to know whether it is running with or without WC.js polyfills.  This means Polymer would need to detect whether it is running in a polyfill context and forward the `WebComponentsReady` WC.js event.

As a Polymer dev I can then deploy my app to different contexts and not be concerned about whether WC.js polyfills are being used or not.

**Comment by sorvell** [comment]
Native web components do not provide an explicit readiness signal. Instead, a `<script>` element can be used to force the browser to ensure everything above the script is upgraded. This is not something Polymer can simulate. Polymer could wait for window.load, but this would be sub-optimal.

It's the user's decision to load or not `webcomponents-lite.js` and this means the user must also adjust code such that it waits for `WebComponentsReady` or includes a `<script>` at the proper spot.

**Comment by devAtPolydeals** [comment]
@sorvell , so what is the final resolution? I want to route user to specific page as soon as they goto index, i use WebComponentsReady for this, which is fine; however i dont load polyfill on chrome since it natively supports it. In that case that event doesnt get fired. What event should i use?

**Comment by davidmaxwaterman** [comment]
This seems like a backward step from 0.5 where the used could just have a polymer-ready handler for all use-cases, irrespective of 'inclusion' of platform.js/webcomponents.js, or of native support.
Ideally, we want code that is the same irrespective of the browser, but it seems like we now have to make lots of decisions, potentially also detecting native support or not.
If there is a way for things to be as easy as they were in 0.5, it's (imo) not clear from the above discussion, and there is perhaps need for some clear documentation (or link to same, if there is some already).

**Comment by ktiedt** [comment]
+1 for a clear solution, just ran into this myself today... Seems silly to have to either create 2 code paths, or TEST for the absence of polyfils just to then simulate the polyfil event we were told to rely on in place of polymer-ready

**Comment by jaykay** [comment]
+1 for a clear solution. Is there any by today? The Polymer Performance Guides say not to include webcomponents-polyfill when not neccessary, but even the PSK relies heavily on the WebComponentsReady-Event. For me it's very confusing which way to go. The 'performance'-way or the 'easy but dirty'-way... Any clues?

**Comment by ebidel** [comment]
Performance can sometimes come at the cost of developer ergonomics. That's one reason we haven't moved everything over to lazy loading, async imports, and conditionally loading the polyfill. Making those decisions comes with caveats. 

If you're in a browser that natively supports HTML imports, you can use its `load` event to know when everything is ready. Any script in the import that registers elements will have run by this time.

`<link rel=import onload=...>` or imperatively https://gist.github.com/ebidel/1ba71473d687d0567bd3#file-app-js-L40

**Comment by ktiedt** [comment]
This still requires maintaining 2 code paths when there is a clear single point that could (and had previously) provided added value... I can't think of a single library that I've used in the past that forced their users to use custom written user code to detect when it was safe to move forward with their code... Much less one that had one then removed it...

**Comment by ebidel** [comment]
You're conflating the webcomponents.js polyfill and Polymer into one thing. In the 0.5 days, the two were tightly coupled (but wrongfully so). Now that the polyfills are a separate entity, it's up to user code to do feature detection. I don't see this as two code paths, but a feature detection issue. @sorvell's comment in https://github.com/Polymer/polymer/issues/1381#issuecomment-104472036 is spot on.

I believe https://gist.github.com/ebidel/1d5ede1e35b6f426a2a7 does what you're after.
jsbin: http://jsbin.com/dihasa/edit?html,output
