### ISSUE TITLE
if I would like to use extends on paper-elements what would be the best way to do it in 0.8 

### ISSUE THREAD

**Issue by rjankie** [Polymer/polymer#1383]
Extends is dropped from 0.8. But will be back in the future. So if I would like to create my-button which "extends" functionality from paper-button, what would be the way to go?

**Comment by LM450N** [comment]
Maybe you could use the [composition][1] way. I mean, create a custom element who contains / uses a template paper-button.

I think about something like that (not yet tested) :
```html
<link rel="import" href="./paper-button.html">

<dom-module id="my-button">
  <link rel="import" type="css" href="./my-button.css">
  <template>
    <template is="paper-button"></template>
    <!-- Insert your features here... -->
  </template>
<dom-module>

<script>
  Polymer({
    is: 'my-button'
    // Insert your features here...
  });
</script>
```

[1]: https://polymer-project.appspot.com/0.8/docs/migration.html#inheritance

**Comment by Sherlock92** [comment]
Is there a recommended workaround that we can use in the interim until support comes back ?

**Comment by TimvdLippe** [comment]
In Polymer 2 you can extend custom elements using native ES6 inheritance: https://www.polymer-project.org/2.0/docs/devguide/custom-elements#extending-other-elements For templates, you can retrieve the parent template with `super.template` and insert into the dom on the place you want.
