### ISSUE TITLE
[0.8] x-repeat should support iterating object-valued `items`

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#1385]
Currently only arrays are supported.  Object (and possibly Map) values should also be made iterable.

This was requested in the Polymer 0.5 codebase per https://github.com/Polymer/polymer-expressions/issues/11.

**Comment by arodic** [comment]
Yes, please, please please.

**Comment by lgersman** [comment]
:+1:

**Comment by chuckh** [comment]
+1

**Comment by RB14** [comment]
I'll add to that and suggest adding support for any iterable object (including generators and other user-defined iterables). I think I requested it in 0.5 few months ago.

**Comment by ganadev** [comment]
+1

**Comment by chuckh** [comment]
+1

On Mon, Apr 20, 2015 at 5:05 AM, ganadev <notifications@github.com> wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Polymer/polymer/issues/1385#issuecomment-94434652>.
>



-- 
Chuck Horton
actionplanr.com
www.hware.com
chuck@hware.com
www.twitter.com/chuckhorton
530.268.5840

Let us create a world that works for all.

**Comment by ternite** [comment]
+1

**Comment by mcarey1590** [comment]
+1

**Comment by knowlecules** [comment]
+1

**Comment by alecbenzer** [comment]
+1

**Comment by harsimranmaan** [comment]
+1

**Comment by Jamtis** [comment]
+1

**Comment by jialic** [comment]
+1

**Comment by shingo-kumagai** [comment]
+1

**Comment by kingflurkel** [comment]
+1

**Comment by laurajmaddox** [comment]
+1

**Comment by b0c1** [comment]
+1

**Comment by zmoshansky** [comment]
Please use the "Subscribe" feature under notifications in the right pane instead of +1'ing this into oblivion; Then everyone avoids getting spammed with useless notification emails.

**Comment by Jamtis** [comment]
In order to iterate over objects or iterables the 'items' property of the 'dom-repeat' template must different from `Array`.
Can be found [here](https://github.com/Polymer/polymer/blob/master/src/lib/template/dom-repeat.html#l126).

After thinking about this a little bit I guess the best thing is to set the type to `Object` to support all [Iterable](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Iteration_protocols) objects.

**Comment by Jamtis** [comment]
When iterating over key-value iterable should index represent the key or should there be a separate key property?

**Comment by jarede** [comment]
+1

**Comment by Jamtis** [comment]
A possible solution could be to internally convert all Iterable (Object, Array, Set, Map, Generator) to a `Map`.

I don't know how performant this solution is...

Does someone have a better way to do it?

Additionally:

If we want to support Set/Map (generally) Polymer needs a way to listen to changes made to them.
Polymer can't even listen to Array changes natively, `element.push` is required.
So Polymer has to implement Set/Map method also... as I stated in #2074.

**Comment by jmcgdz** [comment]
+1

**Comment by mercmobily** [comment]
+1 I would love this.

**Comment by LuisTJap** [comment]
+1

**Comment by jgautheron** [comment]
+1

**Comment by MeTaNoV** [comment]
status?

**Comment by Jamtis** [comment]
Is anyone from the polymer team actively working on this?
Otherwise I'll take a deeper look into this.

**Comment by chunkzer** [comment]
BIGGEST +1

**Comment by Jamtis** [comment]
[This line](https://github.com/Polymer/polymer/blob/master/src/lib/template/dom-repeat.html#L127) states that the `items`property of `dom-repeat` is an array.
Therefore we need a more general type to cover all iterable objects.

@kevinpschaaf What do you think about an "Iterable" type?

Furthermore `Polymer.Collection` handles the given array interally @ [line 348](https://github.com/Polymer/polymer/blob/master/src/lib/template/dom-repeat.html#L348).
Thus `Collection` must support all Iterables.
Critical parts are [here](https://github.com/Polymer/polymer/blob/master/src/lib/collection.html#L32-L39), this loop must also cover other iterables.

**Comment by alodavide** [comment]
+1

**Comment by schrotie** [comment]
I needed a solution for this so I wrote something. Since I don't know Polymer internals and did not want to work with a modified version anyway, I had to make do with what's there. I transform the Object into an array once and then propagate only the changes up and down. It does not handle key additions/removals and array splices but otherwise it's fully transparent. Maybe some of it is of some use here. Usage:
```
<my-objarray object="{{object}}" array="{{array}}"><my-objarray>
<template is="dom-repeat" items="{{array}}">[[item.key]]: [[item.value]]</template>
```
The code is on [stackoverflow](http://stackoverflow.com/questions/30781500/how-to-use-dom-repeat-with-objects-instead-of-arrays-in-polymer-1-0/37015188#37015188).

**Comment by fernandojsg** [comment]
Any updates on this? :\ one of the biggest downside I've found on polymer right now

**Comment by bvhme** [comment]
The new Firebase element does no longer support an array like collection AFAIK, this makes an iterable template for objects a lot more relevant again I hope.

**Comment by klarkc** [comment]
A big blocking here, of course, because of Firebase element changes.

**Comment by cleaverpj** [comment]
+1

**Comment by Arual90** [comment]
+1

**Comment by monkybrain** [comment]
+1

**Comment by krozycki** [comment]
+1

**Comment by sreekrishna** [comment]
+1

**Comment by derhuebiii** [comment]
+1

**Comment by diegocerdan** [comment]
Does Polymer 2.0 help with this issue? Every time I start side-projects using Polymer I step into this problem.

**Comment by Pablo-Aldana** [comment]
+1

**Comment by dwelby101** [comment]
+1 This would be a really neat feature to have

**Comment by NicolasRannou** [comment]
+1

**Comment by baocang** [comment]
+1

**Comment by derhuebiii** [comment]
Polymer 2.0 doesn't seem to have this functionality either? At least I cannot find it in the specs?
Are there any plans to implement this? Was hoping so much for Polymer 2.0 ...
[https://www.polymer-project.org/2.0/docs/devguide/templates](https://www.polymer-project.org/2.0/docs/devguide/templates)

**Comment by togonow** [comment]
+1

**Comment by Geoffrey-Pliez** [comment]
+1

**Comment by jogibear9988** [comment]
same as #800 maybe close one

**Comment by LarsDenBakker** [comment]
+1 seems like such a basic functionality

**Comment by derhuebiii** [comment]
Are there any plans for this to come?

**Comment by SoufianAkh** [comment]
When will there be a fix for this nonsense?
