### ISSUE TITLE
Shady DOM doesn't honor host selector specificity.

### ISSUE THREAD

**Issue by philipwalton** [Polymer/polymer#1387]
Consider the following element:

``` html
<dom-module id="my-element">
  <style>
    :host(.some-class) {
      --color: green;
      border: 5px solid green;
      display: block;
    }
    :host {
      --color: red;
      border: 5px solid red;
      display: block;
    }
    p {
      color: var(--color);
    }
  </style>
  <template>
    <p>Some paragraph text...</p>
  </template>
</dom-module>

<script>
  Polymer({
    is: "my-element",

    // The custom properties shim is currently an opt-in feature
    enableCustomStyleProperties: true
  });
</script>

<my-element class="some-class"></my-element>
```

Chrome correctly identifies that the border color should be green, but Polymer's shady DOM sets the text to red, even though the `:host(.some-class)` selector is more specific than `:host`.

![screen shot 2015-04-08 at 11 11 43 pm](https://cloud.githubusercontent.com/assets/326742/7061293/a43880da-de44-11e4-8107-d923494f7027.png)

**Comment by sorvell** [comment]
Defining property values for an element scope inside of a qualified `:host` selector like `:host(.some-class)` is not currently supported. We do plan to add support for this in the future.

**Comment by noahlaux** [comment]
We started out using ShadowDOM and this feature is SUPER awesome, we hope for support soon!

**Comment by madshensel** [comment]
Not having this feature seems to works against encapsulation. In our current workaround we use a class that applies styles to the element from the light DOM.

**Comment by TimvdLippe** [comment]
This seems to be fixed with Polymer 2 and shadyCSS: http://jsbin.com/podejuyowa/edit?html,console,output (tested in Chrome with native shadow dom and Firefox with Shady dom)
