### ISSUE TITLE
Polymer-micro.html broken?

### ISSUE THREAD

**Issue by IntranetFactory** [Polymer/polymer#1390]
I'm not sure if it's just me facing this issue. https://github.com/Polymer/polymer/blob/0.8-preview/polymer-micro.html#L10 tries to import src/polymer.html 

But src/polymer.html doesn't exist in https://github.com/Polymer/polymer/tree/0.8-preview/src any longer. Seems to be now called polymer-lib.html

**Comment by beaudesigns** [comment]
Ran into this as well.

**Comment by arthurevans** [comment]
Sounds correct. If you don't want to be living on master (with its inherent churn), I recommend installing the released version:

    bower install --save Polymer/polymer#^0.8.0-rc.2
