### ISSUE TITLE
[0.8] Nested property binding not working on Firefox/IE

### ISSUE THREAD

**Issue by Sleeckx** [Polymer/polymer#1391]
Consider the following code:

```html
<html>
<head>
    <script src="Bower/webcomponentsjs/webcomponents-lite.js"></script>
    <link rel="import" href="Polymer/polymer.html" />
    <link rel="import" href="index-test-elements.html" />
</head>

<body touch-action="auto">
    <host-element first="First name" last="Last name"></host-element>
</body>
</html>

```

```html
<dom-module id="host-element">
    <template>
        <span>{{first}}</span>
        <child-element name="{{last}}"></child-element>
    </template>
</dom-module>

<dom-module id="child-element">
    <template>
        <span>{{name}}</span>
    </template>
</dom-module>

<script>
    Polymer({
        is: "host-element",
        properties: {
            first: String,
            last: String
        },
    });

    Polymer({
        is: "child-element",
        properties: {
            name: String
        }
    });
</script>
```

In Chrome, this results in: **First name Last name** being displayed.
In Firefox/IE, this results in **First name** only.

**Comment by Sleeckx** [comment]
Created a demo case for this: **http://jsbin.com/mawexu/2/edit?html,output**

At the moment this is preventing every more complex web components application to run in anything but Chrome (did not test on Safari, but I would assume it will react the same way as IE/FF).

**Comment by robdodson** [comment]
This was brought up in Slack as well. Just curious if @kevinpschaaf or @sorvell see's anything wrong with the above example.

**Comment by IntranetFactory** [comment]
Not sure if that's related, but while analyzing nested, preserve-content templates which fail only in IE and Safari I found that the  `importNode` (https://github.com/Polymer/polymer/blob/0.8-preview/src/mini/template.html#L50) might cause the problem. In my case the template.content contains other template nodes. These nodes have a .content DocumentFragment. After the importNode the nested nodes in `dom` have either an empty .content property or it's missing in IE/Safari. In Chrome and FF these dom nodes retain the original .content

**Comment by IntranetFactory** [comment]
In Safari probably this bug might be the reason https://bugs.webkit.org/show_bug.cgi?id=137619 Just checked the error still exists in Safari 8.0.5

**Comment by Sleeckx** [comment]
Closing this issue as it was resolved in one of the recent commits.

http://jsbin.com/sinuzi/1/edit?html,output

Output on IE11:
![image](https://cloud.githubusercontent.com/assets/2143495/7493770/e104aad2-f403-11e4-9ccd-b145f4e163d1.png)

Output on FF (37.0.2):
![image](https://cloud.githubusercontent.com/assets/2143495/7493795/068308f8-f404-11e4-8536-4756326290ff.png)
