### ISSUE TITLE
[0.8] `readOnly` properties do not receive the initial value specified by `value`

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer#1393]
Considering the following contrived element:

```javascript
var XContrived = Polymer({
  is: 'x-contrived',
  properties: {
    foo: {
      type: Boolean,
      readOnly: true,
      value: false
    }
  }
});
```

And the following usage:

```javascript
var el = new XContrived();

console.log(el.foo);
```

The following will be logged to the console:

```javascript
undefined
```

This has impactful consequences when using `readOnly` properties as dependencies of computed properties. If the `readOnly` property remains `undefined`, the computed property will never be computed.

**Comment by kevinpschaaf** [comment]
Fixed in https://github.com/Polymer/polymer/commit/3428904744254db20f83c1c81e7fbc2257a69d3f.
