### ISSUE TITLE
[0.8] Properties deserialized from native inputs lose their type

### ISSUE THREAD

**Issue by garlicnation** [Polymer/polymer#1396]
Bind a number-valued property to native input, change the input, the property is now a string.

Demo:
http://garlicnation.github.io/polymer/demo/
https://github.com/garlicnation/polymer/tree/nativeInputTypes/demo

A workaround would be to add some indirection when setting the property w/ a change handler function, but I don't see anything in our documentation capturing this behavior.

**Comment by zhaoz** [comment]
I was told that I could set type="number" for the <input>, however I tried that in a similar demo to the one garlicnation posted and was not able to get it to work.

**Comment by sorvell** [comment]
Polymer does not deserialize or type check property assignments. In this case, the `<input>` element always produces `value` as a string (e.g. http://jsbin.com/dicosi/1/edit?html,console,output).

Users can, of course, implement this type of type validation/conversion, if desired.
