### ISSUE TITLE
paper-radio-group impacted by div 

### ISSUE THREAD

**Issue by vikjung** [Polymer/polymer#1403]
Following checks off one radio button if the other is clicked and works fine -

paper-radio-group>
 paper-radio-button name="W" >/paper-radio-button>
  paper-radio-button name="X" >/paper-radio-button>
  /paper-radio-group> 

But following allows multiple select which is not wanted-

 paper-radio-group>
 div>
    paper-radio-button name="W" >/paper-radio-button>
  paper-radio-button name="X" >/paper-radio-button> 
/div>
  /paper-radio-group>  

At times there might be other stuff next to the radio button e.g. when asking for input of multiple choice answers to a question.  So single selection should not be impacted irrespective of where buttons are in the group.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
