### ISSUE TITLE
[0.8] Global settings overwritten by webcomponents

### ISSUE THREAD

**Issue by clintwood** [Polymer/polymer#1404]
Just in case someone else bumps up against this...

[The documentation states](https://www.polymer-project.org/0.8/docs/devguide/settings.html) that  global settings should be the first script in the main document.  So one would tend to do the following:

```html
  <head>
    <title>Polymer Sample</title>
    <script>Polymer = {dom: 'shadow'};</script>
    <script src="./bower_components/webcomponentsjs/webcomponents.js"></script>
    <!-- <script>Polymer = {dom: 'shadow'};</script> -->
    <link rel="import" href="./bower_components/polymer/polymer.html">
  </head>
```
However, [webcomponents.js overwrites](https://github.com/webcomponents/webcomponentsjs/blob/4c5f21610c6cea02c74beaa3a25cd8075807ce31/src/WebComponents/dom.js#L60-L87) the global `Polymer` variable.

This is not the case when following the 0.8-preview recommendation to use `webcomponents-lite.js`.

Alternatively you can move the script tag that declares the `Polymer` variable to just above the import `link ` tag (as show in the commented `script` tag above).

**Comment by arthurevans** [comment]
Good catch -- thanks. Will fix.

**Comment by arthurevans** [comment]
This issue was moved to Polymer/docs#1017
