### ISSUE TITLE
[0.8] 'Polymer' undefined in Polymer.Base assignment

### ISSUE THREAD

**Issue by Rich17** [Polymer/polymer#1408]
File: polymer/src/lib/base.html
Issue: in the createdCallback method on Polymer.Base, Polymer (and Polymer.telemetry) is not defined.
Error thrown: Uncaught TypeError: Cannot read property 'instanceCount' of undefined
Note: The Polymer object is defined outside of Polymer.Base, but is not defined within

**Comment by sorvell** [comment]
It's hard to understand how this could happen. Can you provide a reproduction if this is still an issue? Thanks.

**Comment by Rich17** [comment]
This is no longer an issue after updated to Polymer 0.9. Thanks.
