### ISSUE TITLE
Polymer 0.8 cant bind to array item.

### ISSUE THREAD

**Issue by wintersandroid** [Polymer/polymer#1409]
This we could do in 5.x

Using an array property/attribute which is populated with an 'associative' array of values, There is an error on the bind..

Eg.

Setup and element with a property (we are using this for translating the page)
```
  translations:{
          value: [],
          type: Array,
          notify: true,
          readOnly: true
        },
```

populate translations with an array of Objects. eg.
```
var trans = [];
trans['id-one'] = 'one';
trans['id-two'] = 'two';
this._setTranslations(trans);
```

Then

use the element.
```
    <translator-json translations="{{translations}}" ></translator-json>
    <paper-button raised="true">[[translations['id-one']]]</paper-button>
    <paper-button raised="true">[[translations['id-two']]]</paper-button>
```

Results in an error in bind.html
unexpectedIdentifier

it creates a setter
```
"var old = this._setData('translations['id-one']', value);
if (value !== old) {
  this._translations['id-one']Effector(old);
}"
```

**Comment by kevinpschaaf** [comment]
We do not plan to support `[...]` bracket dereferencing in 0.8+, as we are avoiding use of a full JS expression parser for performance and simplicity.

However, this syntax will work: `[[translations.id-one]]`.
