### ISSUE TITLE
[0.8] x-repeat objectizes arrays of strings

### ISSUE THREAD

**Issue by mbleigh** [Polymer/polymer#1411]
```html
<template is="x-repeat" items="[[package.tags]]">
  <span name$="[[item]]">[[item]]</span>
</template>
<script>
  var package = {
    tags: ['first', 'second']
  }
</script>
```

This will cause the `name` attribute to appear as `name=""first""` and `typeof $0.name` would be `object` because it's a String object.

**Comment by Nevraeka** [comment]
:+1:

**Comment by lucasfanning** [comment]
(y)

**Comment by lucasfanning** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by kevinpschaaf** [comment]
This is fixed on master; primitives are no longer upgraded to their object counterparts in place.
