### ISSUE TITLE
[0.8] IE11 displays and then hides Custom Elements

### ISSUE THREAD

**Issue by jodekirk** [Polymer/polymer#1412]
Chrome displays the text correctly: 'Hello World, I am a Custom Element!', 
but IE11 displays 'This is local DOM' very briefly and then removes it and displays nothing. Is this a bug?

    <html>
    <head>
        <script src="webcomponentsjs/webcomponents.js"></script>
        <link rel="import" href="polymer/polymer.html" />
    </head>
    <body unresolved>
        <x-custom></x-custom>
        <dom-module id="x-custom">
            <template>
                <div>This is local DOM</div>
            </template>
        </dom-module>
        <script>
            Polymer({
                is: 'x-custom',
                properties: {
                    user: String,
                    isHappy: Boolean,
                    count: {
                        type: Number,
                        readOnly: true,
                        notify: true
                    }
                },
                ready: function () {
                    this.innerHTML = 'Hello World, I am a <b>Custom Element!</b>';
                }
            });
            document.body.removeAttribute('unresolved');
        </script>
    </body>
    </html>

**Comment by sorvell** [comment]
When defining an element in the main document on a browser that doesn't support HTMLImports natively, you need to wait for the `HTMLImportsLoaded` event to call `Polymer`. For example,

```
<script>
addEventListener('HTMLImportsLoaded', function() {
  Polymer({
    // stuff
  });
});
// ...
```

This should make the above work. Also, you'll want to use `webcomponents-lite.js` instead of `webcomponents.js`.
