### ISSUE TITLE
Paper dropdown automatically closes on mouse up after scroll (ANIMATED GIF)

### ISSUE THREAD

**Issue by richieb** [Polymer/polymer#1414]
This issues is best described with a video (or animated gif), so here we go:

Note that the menu closes after scrolling; the user cannot select an item after he uses his mouse to scroll. 
<a href="https://imgflip.com/gif/k681o"><img src="https://i.imgflip.com/k681o.gif" title="made at imgflip.com"/></a>

**Comment by windlessuser** [comment]
I also have this issue. In more detail. I develop using a laptop and I alterante between my mouse and the trackpad. With a trackpad, I have to scroll using the scrollbar. As soon as I leave the scroll bar it closes. However, if I use the mouse wheel, It doesnt close and I can select my item.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
