### ISSUE TITLE
[0.8] Support :root in x-style

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#1415]
Adding support for `:root` in x-style will provide an alternative to using `*` for matching everything. I will also create an analog to `:host` to allow for production of property values in the root scope.

**Comment by sorvell** [comment]
Fixed in https://github.com/Polymer/polymer/commit/1976ad0077a7c13df783c30108d9ac480973f0c2.

**Comment by nevir** [comment]
Woot!

**Comment by morethanreal** [comment]
PSA when that goes into a release?

**Comment by sorvell** [comment]
Yeah, it'll be in the 0.9 rc.
