### ISSUE TITLE
Issue with Sample Code in Documentation

### ISSUE THREAD

**Issue by mrodtek** [Polymer/polymer#1416]
https://www.polymer-project.org/0.5/docs/start/creatingelements.html#creatapp
Section: Using Polymer’s features
Sub-section: Add properties and methods

The sample code in the index.html "tab" has:
`<link rel="import" href="proto-element.html">`

Should be:
`<link rel="import" href="elements/proto-element.html">`

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
