### ISSUE TITLE
With <template if=> missing how can I have several different styles applied?

### ISSUE THREAD

**Issue by josator** [Polymer/polymer#1419]
How can I have different css styles inside a polymer element now that the \<template if=\> is gone?
¿What about adding a \<style if=\> tag?

**Comment by Punk-UnDeaD** [comment]
try different class or calculated style attribute
``` <div class=spacer style="{{spacerStyle(status)}}"></div>```

**Comment by josator** [comment]
I opened this months ago and the answer solved my question. You can close it.
