### ISSUE TITLE
Auto-generate camel case constructor name from element name

### ISSUE THREAD

**Issue by JanMiksovsky** [Polymer/polymer#142]
From a [discussion group thread](https://groups.google.com/forum/?fromgroups#!topic/polymer-dev/GWvR4TUMn7s):

The need to specify both an element name and a constructor name seems pretty tedious, anti-DRY, and against the Polymer "no boilerplate" principle. Already, the convention seems to be to give an element called my-element a constructor called MyElement. Why not codify that convention?

Let's assume a constructor can't be assumed (because one doesn't want to pollute the global namespace, say). How about at least letting the name of the constructor be inferred? This could be done with a value-less attribute:

```
<element name="my-element" constructor>
```

or some magic constructor value (e.g,. the empty string "", or something like "*") to indicate that a constructor is desired, and that it should be given the conventional camel-cased name generated from the element name.

Polymer could try this and, if people like it, the case could be made to push it into the <element> spec.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) release of Polymer - please feel free to re-open if this is incorrect.
