### ISSUE TITLE
Polymer Paper Input: Next/Go on mobile keyboard is not working

### ISSUE THREAD

**Issue by theGreatHeisenberg** [Polymer/polymer#1420]
I have included polymer's paper-input in my web page. Whenever (in mobile browser) I click on an input, type something and click on Go/Next button on keyboard/keypad, the keypad doesn't disappear. Is this a known issue with polymer's paper-input.?

Try opening a following Demo page and try reproducing the issue. 

[Polymer Paper Input](http://stackoverflow.com/questions/29700402/polymer-paper-input-next-go-on-mobile-keyboard-is-not-working)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
