### ISSUE TITLE
A invalid link on core-icons page

### ISSUE THREAD

**Issue by renfeng** [Polymer/polymer#1424]
This link is invalid.
http://www.polymer-project.org/components/core-icons/demo.html

It should be
https://www.polymer-project.org/0.5/components/core-icon/demo.html

**Comment by renfeng** [comment]
Note
core-icon (correct)
core-icons (wrong)

**Comment by arthurevans** [comment]
Which page is the link on? There is a core-icons demo as well: https://www.polymer-project.org/0.5/components/core-icons/demo.html
We've made a fix on the core-icon reference page, which hasn't yet been deployed. But I'm not sure if that's the same link you're reporting here.

**Comment by renfeng** [comment]
On this page, https://www.polymer-project.org/0.5/docs/elements/core-icon.html

You can find the link by searching in page, "See core-icons for the default set of icons."

I think the last link you showed should be the most correct! :D

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
