### ISSUE TITLE
Designer Bug - Can't save code.

### ISSUE THREAD

**Issue by MrWeb** [Polymer/polymer#1427]
Hi,
when editing the code in polymer designer (https://polymer-designer.appspot.com)
the code I write disappears and I get a blank code even if I save...

This is the video: https://dl.dropboxusercontent.com/u/2276958/Polymer.mov

Using: OSX 10.8.5 - Chrome 42.0.2311.90 (64-bit)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
