### ISSUE TITLE
Error in 0.8 RC6 - not present in RC4

### ISSUE THREAD

**Issue by mdwragg** [Polymer/polymer#1428]
Hi,

@tjsavage asked me to raise a bug here - I was on polymer.slack.com highlighting a bug between 0.8RC4 and RC6.

We get the error below (in Chrome):

![image](https://cloud.githubusercontent.com/assets/3594714/7243624/60bc7a84-e784-11e4-9832-02ea8b5648d8.png)

Our template looks a little like this:

```html
        <template is="x-repeat" items="{{navItems}}">
          <li>
            <a class$="{{item.class}}" href$="{{item.href}}" on-click="navClickHandler"><i class$="{{item.icon}}"></i><span data-l10n-id$="{{item.l10nId}}">{{item.label}}</span></a>
            <ul class="list-bare visuallyhidden">
              <template is="x-repeat" items="{{item.subitems}}">
                <li>
                  <a href$="{{item.href}}" on-click="subnavClickHandler"><span class="visuallyhidden" data-l10n-id$="{{item.l10nId}}">{{item.label}}</span></a>
                </li>
              </template>
            </ul>

          </li>
        </template>
```

Again, this is fine in RC4 and errors in RC6.

Thanks!

**Comment by sorvell** [comment]
Thanks for reporting this problem. I can confirm the problem. It'll be fixed in the next rc.

**Comment by Diwatt** [comment]
Hi,
An other issue if i use the "observers" property.

![screenshot from 2015-04-21 11 15 16](https://cloud.githubusercontent.com/assets/739484/7249084/0edb7a28-e818-11e4-8b1e-33f6afeb7309.png)


```
<dom-module id="ugo-test">
    <template>
        <content></content>
    </template>
</dom-module>
<script>
    Polymer({
        is: 'ugo-test',
        properties: {
            attr1: String,
            attr2: String
        },

        observers: {
            'attr1 attr2': 'onPropChange'
        },
        onPropChange: function () {}
    });
</script>
```

It works well in RC4.

Bye

**Comment by IntranetFactory** [comment]
There was a breaking change in the observers syntax. See https://github.com/Polymer/polymer/blob/0.8-preview/PRIMER.md#multipe-property-observation for current syntax. So in your sample it should now be 

```
        observers: [
            'onPropChange(attr1, attr2)'
       ],
```

**Comment by Diwatt** [comment]
Thanks !

**Comment by mdwragg** [comment]
Excellent - thanks @sorvell

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/polymer/commit/4a5ad41968b1fbb728639cb682acd86ad152033b

**Comment by mdwragg** [comment]
Thanks for fixing so quickly @sorvell :+1:
