### ISSUE TITLE
[0.8] Polymer.dom() should expose innerHTML and textContent

### ISSUE THREAD

**Issue by JanMiksovsky** [Polymer/polymer#1429]
Now that we have to use the Polymer.dom() to cover both Shadow and Shady DOM, we're finding it hard to programmatically get and set element content. We'd like to be able to get and set both `Polymer.dom(element).innerHTML` and `Polymer.dom(element).textContent`. From what I can tell, neither of those are defined by the result of Polymer.dom().

While we can try to roll our own Shadow/Shady implementations of innerHTML and textContent by looking at Polymer.dom()'s `.children` or `.childNodes` properties, it seems much better to share reliable, platform-supported helpers for that.

**Comment by IntranetFactory** [comment]
+1  

`innerHTML` and `textContent` are really missing. We made some custom code which should lead to the same result - but we're not sure if it's the best/fastest approach. So we would appreciate an official solution as well.

**Comment by justinfagnani** [comment]
I believe these are on the way. @sorvell knows more.

**Comment by sorvell** [comment]
Yup, these should be coming soon.

**Comment by kevinpschaaf** [comment]
This was completed in https://github.com/Polymer/polymer/pull/1462.

**Comment by JanMiksovsky** [comment]
Fantastic, thanks!
