### ISSUE TITLE
[0.8] `<content select=".class">` and `hostAttributes` don't work together

### ISSUE THREAD

**Issue by morethanreal** [Polymer/polymer#1431]
https://gist.github.com/morethanreal/da583f571d9931d03f99

This example should distribute nodes with `.foo` first.

In the first example, the class is set on the distributed node with `hostAttributes`. In the second example it's set with an inline `class` attribute. Only the second example distributes properly.

**Comment by sorvell** [comment]
Distribution based on element mutations is not automatic under ShadyDOM. Distribution is synchronous to element upgrade. In the example `my-element` upgrades and distributes and then `other-element` upgrades. In the example, `distribute` must be called on `my-element`.

We've investigating ways to improve this. Distribution could be made asynchronous to upgrade, but the dynamic case still requires kicking. A mutation observer could be used to monitor `my-element`, but there are performance concerns with this approach.

**Comment by sorvell** [comment]
We think we've found a reasonable way to address this and a fix should be coming soon.

**Comment by sorvell** [comment]
In the example provided, if you import `other-element` before `my-element`, you can avoid the issue. It's not always feasible to import children before parents, however, so we'll still fix the issue.
