### ISSUE TITLE
How can I know the time x-repeat finish DOM parsing after dataset changed asynchronously

### ISSUE THREAD

**Issue by brannpark** [Polymer/polymer#1441]
I want to fire click event on the element which is made by x-repeat template.
But I couldn't find any callback API for this. so now I'm trying to find the element with querySelector and setTimeout recursively.
Is there any another solutions for this?

**Comment by kevinpschaaf** [comment]
You can call `render()` imperatively on the x-repeat to force synchronous rendering.
