### ISSUE TITLE
Read-Me File Dead Link

### ISSUE THREAD

**Issue by PushkaCom** [Polymer/polymer#1442]
https://github.com/Polymer/polymer/

The 1st link and image are broken:

![image](https://cloud.githubusercontent.com/assets/985223/7291067/b44d4750-e9cd-11e4-9c59-8cc5e6ed08c3.png)

![image](https://cloud.githubusercontent.com/assets/985223/7291072/c06ba608-e9cd-11e4-9b25-791039bac13c.png)

http://build.chromium.org/p/client.polymer/waterfall

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
