### ISSUE TITLE
StyleTags lack sourceURL

### ISSUE THREAD

**Issue by aslushnikov** [Polymer/polymer#1447]
### Repro steps:
- Check out Polymer tutorial: http://www.polymer-project.org/docs/start/tutorial/step-1.html.
- Download it and open the 'finished/index.html'
- Open devtools, try to edit styles for the small "heart" icon.

Styles sidebar panel is missing urls / lines against the CSS rules.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
