### ISSUE TITLE
[0.8] getDistributedNodes() does not update when distributed content changes

### ISSUE THREAD

**Issue by atotic** [Polymer/polymer#1449]
_distributedNodes array does not get updated when underlying nodes are added/removed.

If you start off with:
```html
    <dom-module id="bug-distributor">
      <template>
        <content id="pcontent" select="p"></content>
      </template>
    </dom-module>

    <bug-distributor>
      <p>Paragraph 1</p>
      <p>Paragraph 2</p>
      <p>Paragraph 3</p>
    </bug-distributor>
```
`bug-distributor.getDistributedNodes().length` is 3.

Then you remove all the distributed nodes:

    document.querySelectorAll('p').forEach( p.remove())

`bug-distributor.getDistributedNodes().length` is 3, should be 0.

Is there a workaround, call one can make to update the list of distributedNodes?

**Comment by arthurevans** [comment]
I think you should be using Polymer.dom to remove the nodes.

**Comment by atotic** [comment]
I've tried using Polymer.dom, same result. 

```javascript
    var allPs = document.querySelectorAll('p');
    Array.prototype.forEach.call( allPs, function(p) {
      Polymer.dom((Polymer.dom(p).parentNode)).removeChild(p);
    });
```

**Comment by arthurevans** [comment]
Ah, sorry. I see what's wrong. These operations may be async, so you need to call flush() after removing the children.

Call `Polymer.dom.flush()` before calling getDistributedNodes the second time:

http://jsbin.com/rusoro/4/edit?html,console,output

I think this was just shorthand in your description, but I believe that getDistributedNodes needs to be called on the content node, not the host element.

**Comment by atotic** [comment]
Thanks for helping out with this. Still not quite up to speed with Polymer dom.
