### ISSUE TITLE
Found another attribute inconsistency

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#1450]
https://www.polymer-project.org/0.5/docs/elements/core-list.html

- selection

https://www.polymer-project.org/0.5/docs/elements/core-selector.html

- selectedItem

Any hope there will be a better naming convention in 0.8 ?

I know Arthurevans was already working on a list but I did not see a blog post on it yet. Would be nice before you start implementing you would blog a RFC or something. 

Can you make a Polymer/RFC repository containing 1 RFC for each component so we can complain about design before it gets implemented? I feel like 50% of you wants to know what we think, the other 50% feel like a Madonna webcomponent :p

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
