### ISSUE TITLE
[0.8] Document (and/or further hide) reserved properties

### ISSUE THREAD

**Issue by nevir** [Polymer/polymer#1451]
There are a few currently off-limits properties that authors need to be careful about:

```
el = new (Polymer({is: 'very-blank'}));
Object.keys(el).filter(function(k) { return k[0] === '_'; }).sort();
=> ["_clients", "_clientsReadied", "_config", "_data", "_debouncers", "_handlers", "_readied"]
```

`_config` and `_data` are especially generic and likely to trip people up

(switching to double leading underscores, and documenting that as off-limits is probably best?)

**Comment by sorvell** [comment]
`_data` was changed to `__data__`

**Comment by bpinney** [comment]
`_notes` is another one that tripped us up today.  Would a PR in which all private polymer methods and properties are standardized such that methods are prefixed with a double underscore `__someMethod(foo, bar)` and properties are prefixed and suffixed `__someProperty__` be considered by your team?

**Comment by TimvdLippe** [comment]
All properties are now either double-underscored to denote private or public: http://jsbin.com/xuvejaqefa/edit?html,console,output
