### ISSUE TITLE
[0.8] Self-closing p tag breaks template

### ISSUE THREAD

**Issue by ngduc** [Polymer/polymer#1455]
Hi,
I got a strange issue. When I use a self-closing p tag &lt;/p&gt; , it breaks my element. (doesn't let me use another element). Please check the example below:
http://howjs.com/Odsv/2#html

After I changed it to &lt;p&gt;&lt;/p&gt; then it works.
http://howjs.com/tbLU/2#html

**Comment by sjmiles** [comment]
The only `void tags` supported by HTML are `area, base, br, col, command, embed, hr, img, input,
keygen, link, meta, param, source, track, wbr`.

See some discussion here: http://stackoverflow.com/questions/3558119/are-self-closing-tags-valid-in-html5

**Comment by ngduc** [comment]
Thanks @sjmiles for the info.

Just curious why an invalid tag can break Polymer like that? how about some arbitrary tags ?
Can this be fixed ? Thanks.

**Comment by dhubler** [comment]
especially not arbitrary tags.  A lot of people learn this the hard way and
speaking for myself, once i know, I rarely make the mistake again.

**Comment by kevinpschaaf** [comment]
This can't be fixed, using an invalid closing tag breaks the HTML parser in the browser.
