### ISSUE TITLE
TODO in polymer.js references fixed bug

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/polymer#1457]
(polymer 0.5.5 in chrome Version 43.0.2357.37 beta (64-bit))
It seems like the 'blocked' comment no longer applies.

<https://github.com/Polymer/polymer/blob/e4f64ff770b8c0673c65102a882e6cb37c38b1e8/src/declaration/polymer-element.js#L42>

    // TODO(sorvell): we currently queue in the order the prototypes are 
    // registered, but we should queue in the order that polymer-elements
    // are registered. We are currently blocked from doing this based on 
    // crbug.com/395686.

(moved discussion on requirejs to #1463)

**Comment by sorvell** [comment]
This version of Polymer is only getting maintenance fixes so this will not be addressed.
