### ISSUE TITLE
[0.8] `hostAttributes` should respect user-provided defaults

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer#1458]
First, I would like to clarify that this is a proposal for API change and not a bug report. AFAIK the existing API is working as advertised.

Currently, attribute values specified in `hostAttributes` will automatically override user-specified values for those attributes. I propose that this should be changed, so that attributes specified in `hostAttributes` will respect and defer to user-specified values.

One of the more tempting uses of `hostAttributes` is to set default ARIA attributes like `role`, and / or related ARIA states and properties. However, `hostAttributes` is a bad choice for this _because_ you generally want to respect user-provided values for those same attributes.

For anecdotal evidence that the proposed behavior is preferable to the current behavior, please refer to the discussion here: https://github.com/PolymerElements/paper-toggle-button/pull/1#discussion_r29089004

**Comment by sorvell** [comment]
This sounds reasonable. Will make it so.

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/polymer/commit/85cc721be91ba789e8d360592ab91a7f85cb416b
