### ISSUE TITLE
.8 domReady never being called

### ISSUE THREAD

**Issue by BLamy** [Polymer/polymer#1460]
Using Polymer .8 I have the following element
```
<link rel="import" href="../../bower_components/polymer/polymer.html">

<dom-module id="app-logo">
  <template>
    <link rel="import" href="../../bower_components/font-roboto/roboto.html">
    <link rel="stylesheet" href="../../bower_components/components-font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="app-logo.css">
    <i class="fa fa-sun-o"></i> playground
  </template>
</dom-module>

<script>
  Polymer({
    is: 'app-logo',

    //this is never called
    domReady:function(){
      console.log("logo domReady");
    },

    //however this is.
    ready:function(){
      console.log("logo Ready");
    }

  });
</script>
```

ready is called fine but domReady is never called? 

Is this a regression or intentional. I didn't read anything about it in the migration guide?

**Comment by sorvell** [comment]
This is by current design: `domReady` is not available in 0.8.

The 0.5 approach for this problem was brittle and prone to failure. We're investigating the use cases around 0.5's `domReady` method in an attempt to provide something better for 0.8.
