### ISSUE TITLE
[0.8] properties from attributes are not set on ready and attached lifecycle function on Chrome.

### ISSUE THREAD

**Issue by brannpark** [Polymer/polymer#1461]
In Safari, the sequece of invoking related functions is
ready > propertyChanged > attached

But, in Chrome..
ready > attached > propertyChanged

I want to use property set from attribute in ready or attached function.
Is it a bug?

**Comment by sorvell** [comment]
Can you provide more information about what you're doing to see this behavior?

I tried to setup what you described and can't reproduce any difference between Chrome and Safari:

http://jsbin.com/nidenakube/1/edit?html,console,output

**Comment by kevinpschaaf** [comment]
@brannpark Are you still having an issue here, or can we close this?

**Comment by brannpark** [comment]
I can't reproduce my issue now because I changed the code logic. And I can't remember previous codes bother me. Anyway, I close this issue. Thank you for your attention.
