### ISSUE TITLE
[0.8] IE9 styles broken

### ISSUE THREAD

**Issue by webdesserts** [Polymer/polymer#1464]
Hello!

In IE9 Polymer 0.8 breaks with the following error when you attempt to include a style tag in your element:

```
SCRIPT5007: Unable to get value of the property 'removeChild': object is null or undefined
```

This specific error is referring to the [_unapplyStyles function](https://github.com/Polymer/polymer/blob/v0.8.0-rc.7/src/standard/styling.html#L104) under the standard/styling.html feature. When debugging the function it shows `parentNode` returning `null`.

This can be reproduced by trying to include the following element into your page:

```html
<dom-module id="my-element">
  <style></style> <!-- remove this line and everything works -->
  <template>Hello, World</template>
</dom-module>

<script>Polymer({ is: 'my-element' })</script>
```

I realize 0.8 is still in an alpha state and you're probably a bit more worried about the api than IE9 bugs right now, but the company I work for is very interested in using 0.8-1.0 as it stabilizes and IE9 is one of our target browsers. I thought I would start including errors as I run into them. On that note, will IE9 still be partially supported for the 1.0 release?

Thanks

**Comment by webdesserts** [comment]
I included the following logs into the `_unapplyStyles` function:
```js
      _unapplyStyles: function(styles) {
        for (var i=0, l=styles.length, s; (i<l) && (s = styles[i]); i++) {
          console.log('original', s)
          console.log('orignal parent', s.parentNode)
          console.log('applied', s.__appliedElement)
          console.log('applied parent', s.__appliedElement.parentNode)
          s = s.__appliedElement || s;
          console.log(s.parentNode)
          s.parentNode.removeChild(s);
        }
      },
```
I checked the result in both firefox and IE9 and I see these differences.

![polymer-styles-error](https://cloud.githubusercontent.com/assets/916253/7398900/96b9a77a-ee77-11e4-8f24-8114c07e7eb6.PNG)

It looks like the `__appliedElement.parentNode` returns the `<head>` element normally, but in IE9 it returns null. Not sure how the `__appliedElement.parentNode` is returning `<head>` in the first place as the `<style>` tag doesn't seem to be attached to the document? Not sure.

**Comment by sorvell** [comment]
Polymer relies on the [WebComponents polyfills](https://github.com/webcomponents/webcomponentsjs) and supports the same browsers and versions that these polyfills do. The oldest supported version of IE is IE10.
