### ISSUE TITLE
support data binding with ES6 module?

### ISSUE THREAD

**Issue by pianoboysai** [Polymer/polymer#1465]
I really like polymer.  but I like ES6 module too.
I don't know many about polymer, could it support  ES6 module as  data binding source?

with systemjs project, I have created many ES6 modules like this:
```js
import $ from "jquery"
export class DocEditor {
    constructor(){
         this.name="sai"
    }
    render() {}
}
```
I hope Polymer could reuse ES6 module in "component" so that I needn't write code like this
```html
<script>
  Polymer({
    is: "DocEditor",
    properties: {
      greeting: {
        type: String,
        name: "sai"
      }
    }
  });
</script>
```
I think porting ES6 module to this syntax is meaningless, and I trusted the ES6 module will be web standard in future, why should I study a new module syntax?

btw: another framework "aurelia" had finished data binding with ES6 module

Thanks.

**Comment by kevinpschaaf** [comment]
We are excited about ES6 modules and want to support that development pattern once they are widely available in browsers without transpiling.  Once ES6 classes are widely available, we will likely add a syntax for creating Polymer element prototypes using an ES6 class syntax.  In the short-term, we are avoiding requiring users of Polymer to buy in to transpilation steps.
