### ISSUE TITLE
[0.8] Ready callback and element initialization

### ISSUE THREAD

**Issue by jeffposnick** [Polymer/polymer#1467]
The [current docs for 0.8](https://www.polymer-project.org/0.8/docs/devguide/registering-elements.html#ready-method) say the following about the `ready` callback:

> The ready method is part of an element’s lifecycle and is automatically called ‘bottom-up’ after the element’s template has been stamped and all elements inside the element’s local DOM have been configured (with values bound from parents, deserialized attributes, or else default values) and had their ready method called. Implement ready when it’s necessary to manipulate an element’s local DOM when the element is constructed.

However, I'm not seeing that "bottom-up" behavior when using parent Polymer elements containing children Polymer elements. You can see this in the JS console output of http://jsbin.com/lisave/33/edit?html,console,output

You'll see that each of the `x-parent`'s callbacks (`created`, `ready`, `attached`) is invoked before the `x-child` elements' callbacks. It seems like what's actually happening is "top-down" rather than "bottom-up".

@arthurevans, this might be a docs issue, or the docs might be correct about the intended behavior and there's a bug in Polymer.

**Comment by sorvell** [comment]
This is by design. The `ready` ordering mentioned in the documentation refers only to the fact that an element's 'local DOM' should be all call `ready` before the element itself calls `ready`. There is no ordering guarantee of `ready` between elements in the same dom tree, but generally it will be called in document order.

**Comment by arthurevans** [comment]
This issue was moved to Polymer/docs#1163
