### ISSUE TITLE
Unable to connect to github.com...

### ISSUE THREAD

**Issue by ronaldpabilonia** [Polymer/polymer#1468]
Hi, trying to use `bower install --save Polymer/polymer#^0.5` but I get

`Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=No such file or directory`

I was just following the instruction on `www.polymer-project.org` and I also have a `bower.json` file already. Am I doing something wrong? Please help. Thanks.

**Comment by arthurevans** [comment]
Just tried running the command locally and it worked for me. The error you report sounds like some kind of connectivity problem with github. If you're behind a proxy, you may get better results by configuring git to use https:// URLs instead of git:// URLs, by running the following command:

git config --global url."https://".insteadOf git://

(Found in this bug thread over here:
https://github.com/DefinitelyTyped/tsd/issues/84)

You don't mention what OS you're on, but there are also some issues reported on Debian Linux and on Windows that came up when I searched for that error (unable to connect to github.com No such file).

**Comment by ronaldpabilonia** [comment]
Yeah I am on windows. And yeah I'll try first the `git config --global url`

**Comment by ronaldpabilonia** [comment]
Oh wow the config worked. Thanks so much! :)

**Comment by jandiralceu** [comment]
Thanks @arthurevans, it's worked!

**Comment by yasirrose** [comment]
@arthurevans  I am using mac and tried you connection but it is not working.
This is what I am getting.when i run vagrant provision

"failed": true, "msg": "fatal: unable to connect to github.com:\ngithub.com[0: 192.30.253.112]: errno=Connection refused\ngithub.com[1: 192.30.253.113]: errno=Connection refused\n\nfatal: unable to connect to github.com:\ngithub.com[0: 192.30.253.113]: errno=Connection refused\ngithub.com[1: 192.30.253.112]: errno=Connection refused\n\nfatal: unable to connect to github.com:\ngithub.com[0: 192.30.253.112]: errno=Connection refused\ngithub.com[1: 192.30.253.113]: errno=Connection refused\n\nfatal: unable to connect to github.com:\ngithub.com[0: 192.30.253.113]: errno=Connection refused\ngithub.com[1: 192.30.253.112]: errno=Connection refused", "rc": 11, "stderr": "fatal: unable to connect to github.com:\ngithub.com[0: 192.30.253.112]: errno=Connection refused\ngithub.com[1: 192.30.253.113]: errno=Connection refused\n\nfatal: unable to connect to github.com:\ngithub.com[0: 192.30.253.113]: errno=Connection refused\ngithub.com[1: 192.30.253.112]: errno=Connection refused\n\nfatal: unable to connect to github.com:\ngithub.com[0: 192.30.253.112]: errno=Connection refused\ngithub.com[1: 192.30.253.113]: errno=Connection refused\n\nfatal: unable to connect to github.com:\ngithub.com[0: 192.30.253.113]: errno=Connection refused\ngithub.com[1: 192.30.253.112]: errno=Connection refused\n\n", "stderr_lines": ["fatal: unable to connect to github.com:", "github.com[0: 192.30.253.112]:

**Comment by heeramani** [comment]
Finally it works. Because i am behind proxy. So used https: instead of git:

**Comment by Siddhant9868** [comment]
@arthurevans thanks, It worked

**Comment by topdeveloper2210** [comment]
Thanks, that's very helpful!
Thanks again.

**Comment by GuddyV** [comment]
Thanks so much, it worked flawlessly

**Comment by maalejahmed55** [comment]
> Just tried running the command locally and it worked for me. The error you report sounds like some kind of connectivity problem with github. If you're behind a proxy, you may get better results by configuring git to use https:// URLs instead of git:// URLs, by running the following command:
> 
> git config --global url."https://".insteadOf git://
> 
> (Found in this bug thread over here: [DefinitelyTyped/tsd#84](https://github.com/DefinitelyTyped/tsd/issues/84))
> 
> You don't mention what OS you're on, but there are also some issues reported on Debian Linux and on Windows that came up when I searched for that error (unable to connect to github.com No such file).

thanks bro it worked for me
i had a problem : cant connecte to github while i was trying to install floodlight

**Comment by code-rain002** [comment]
You can fix this issue just by deleting some configuration on .gitconfig file.
It is normally located at C:/Users/[Username]/.gitconfig
Remote this and try.
[url "git@github.com"]
insteadOf = https://github.com/:
[url "git://"]
insteadOf = https://
[url "https://"]
insteadOf = git://
