### ISSUE TITLE
Image URLs whcih contains the word 'asset' are transformed into local file paths

### ISSUE THREAD

**Issue by hahnrobert** [Polymer/polymer#1479]
When using an URL which contains the word **'assets'**, polymer transformers the URL into a local file path.

`<img src="http://cdn.aaaaa.bb/api/modules/assets/media/ic_speaker_off.svg" />`

is transformed to

`<img src="packages/media/ic_speaker_off.svg" />`

**Comment by kevinpschaaf** [comment]
We need some more information to understand your issue.

Can you note the version of Polymer, any tools you used, and ideally a test case?

**Comment by kevinpschaaf** [comment]
@hahnrobert Are you still having an issue here, or can we close this?

**Comment by azakus** [comment]
Closing due to age, please reopen if this is still an issue.
