### ISSUE TITLE
Using Polymer with NW.js

### ISSUE THREAD

**Issue by Bryan-Turek** [Polymer/polymer#1481]
I'm looking at creating a Node-webkit application using Polymer, however I want to jump on board with the latest 0.8 branch. Is there any support for core-elements in 0.8? I'd like to start scaffolding out sidebar elements and toolbar elements. I see that paper-elements support 0.8 though. where is the best place to begin?

**Comment by kevinpschaaf** [comment]
0.8+ compatible elements are all now located under the https://github.com/PolymerElements org.  Thanks.
