### ISSUE TITLE
[0.5.5] Function calling is not working in custom element

### ISSUE THREAD

**Issue by AsBer** [Polymer/polymer#1484]
Hi,
my problem is this, I have made a custom element, a really simple one:

```
<link rel="import" href="../bower_components/polymer/polymer.html">
<link rel="import" href="../bower_components/core-collapse/core-collapse.html">
<link rel="import" href="../bower_components/paper-button/paper-button.html">

<!--COURSES PAGE -->
<polymer-element name="page-five">
	<template>
		<paper-button on-tap"{{toggleContent}}">Toggle >: /</paper-button>
  		<core-collapse id="collapse1">
    		<div class="content">
      			Lorem ipsum
      		</div>
  		</core-collapse>
	</template>
	<script>
		Polymer({
			toggleContent : function() {
			this.$.collapse1.toggle();
			}
		});
	</script>
</polymer-element>
```
Once inserted in my index, I click on the button but it never toggles and I cannot even guess why because I have done a couple of similar ones and they work perfectly.
Other uses of data binding work well such as inputs... I have no clue of what is going on
Can be maybe a missing import? Or maybe I should update polymer files?
Thank you for the help! :)

**Comment by miztroh** [comment]
Looks like you're not importing Polymer.  You need something like this at the top.

```
<link rel="import" href="/bower_components/polymer/polymer.html">
```

**Comment by AsBer** [comment]
It is imported in the index and afterwards I tried to import it in the custom element because I suspected it was an import issue but it did not work either.

**Comment by miztroh** [comment]
Your index page should be importing webcomponentjs:

```
<script src="/bower_components/webcomponentsjs/webcomponents.min.js"></script>
```

If that doesn't fix the issue for you, perhaps you can create a full test case on codepen or something like that.

**Comment by arthurevans** [comment]
You're missing the `=` when assigning the on-tap handler:

        <paper-button on-tap"{{toggleContent}}">Toggle >: /</paper-button>

Should be:

        <paper-button on-tap="{{toggleContent}}">Toggle >: /</paper-button>

http://jsbin.com/nunera/1/edit?html,output

**Comment by miztroh** [comment]
@arthurevans Good catch.

**Comment by AsBer** [comment]
I don't know if I should laugh or cry... I've been looking for this error about 8 hours. Thank you so much for the help! :smile:

**Comment by arthurevans** [comment]
No problem! Glad you got it sorted.
