### ISSUE TITLE
Internet Explorer 11 "Failed to open data:text/javascript;charset=utf-8,"

### ISSUE THREAD

**Issue by zardoz** [Polymer/polymer#1485]
Hi all, 

we have a component in our Polymer project that is returning URL encoding, in the debugger it shows as:

```
Failed to open data:text/javascript;charset=utf-8,
	    var SAGEITEMID%3B
	    var JJFunction %3D new Object()%3B
	    JJFunction.AJAX %3D new Object()%3B    
	    JJFunction.BASKET %3D new Object()%3B
	    JJFunction.BASKET.ITEM      %3D new Object()%3B
	    JJFunction.BASKET.SUMMARY   %3D new Object()%3B
	    JJFunction.BASKET.MASTER    %3D new Object()%3B
	    JJFunction.SHOP             %3D new Object()%3B
	    JJFunction.UI               %3D new Object()%3B
	    JJFunction.GODADDY          %3D new Object()%3B
....
```

We are importing this file through a 

```
<link import /> 
```

This files registers a polymer element name in the file itself:

```
<polymer-element name="proto-JJFUNCTION" >
	<template>
		<style>
          
		</style>


	</template>
	<script>
	    var SAGEITEMID;
	    var JJFunction = new Object();

	    JJFunction.AJAX = new Object();
	    
	    JJFunction.BASKET = new Object();
	    JJFunction.BASKET.ITEM      = new Object();
	    JJFunction.BASKET.SUMMARY   = new Object();
	    JJFunction.BASKET.MASTER    = new Object();
	    JJFunction.SHOP             = new Object();
	    JJFunction.UI               = new Object();
```

And includes this as a component as . 

```
<proto-JJFUNCTION></proto-JJFUNCTION>
```

This works really well for all browsers apart from IE which seems to barf the encoding of the file....

I'm using master branch, some of the components are to version 0.6.1

Any suggestions?

**Comment by zardoz** [comment]
This was not what I thought it was, simple project structure.

**Comment by ldtung** [comment]
I also have the same issue.
Could you please share how to deal with this?

**Comment by nicholaswmin** [comment]
:+1: Same here

**Comment by zardoz** [comment]
OK, Yikes, this was a while ago. The first thing I would do is make sure that your template structures are not to complex (caveat we are running on Polymer 0.5, we are upgrading soon ), We found that on 0.5 deeply nested templates can cause issues, in-line as much as possible on those. We also provided id params on any custom elements, so the element:

```<proto-JJFUNCTION id="a"></proto-JJFUNCTION>

So I'd start by looking at your templates. Make sure you are using the webcomponent tester and associated testing tools, found on the Polymer blog.

I'm very sorry I can't be more specific, as it was a while ago. I will reply back if I remember anymore

**Comment by rnyberg** [comment]
Also started experiencing this on IE11

**Comment by rnyberg** [comment]
Heh, I bumped into this again and to my surprise, I found myself in this issue.

Long story short: `var obj = {some, thing};` makes something in Polymer html encode the contents of the object on IE11.

Workaround: stay away from https://ariya.io/2013/02/es6-and-object-literal-property-value-shorthand even if you are running a shiv for IE11.

**Comment by rozzamozza** [comment]
Got the same issue on Polymer
"in-line as much as possible" kind of defeats the purpose of web components...

will checkout the web component tester...

**Comment by rozzamozza** [comment]
Found the related Polymer loading issue (for my issue at least).
The following works in Chrome..
      _recalculate(){
But IN IE It needs to be stricter. I.e. this
      _recalculate: function(){

It still renders poorly as UTF8 in IE though for other errors...
