### ISSUE TITLE
Cross domain HTML import

### ISSUE THREAD

**Issue by shailesh17mar** [Polymer/polymer#1489]
I am not able to import my component from a different domain. It is not able import the internal imports present in my component. Is this problem due to relative import paths or something else?
Is there any way to work it out?

**Comment by Nevraeka** [comment]
Check your console for CORS related errors. What are they?

**Comment by Nevraeka** [comment]
@shailesh17mar - did you find out what happened?

**Comment by shailesh17mar** [comment]
I am getting this error in console then 
Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': Nodes of type 'HTML' may not be inserted inside nodes of type '#document'.

and then 79 other errors : Uncaught TypeError: Polymer is not a function

**Comment by shailesh17mar** [comment]
Found out the issue. It was importing polymerjs multiple times for each component imported. Therefore, as a workaround I created a seperate elements.html file and vulcanized it and finally imported that instead of importing elements separately.
