### ISSUE TITLE
[0.8] SVG elements fail on IE11 due to missing classList

### ISSUE THREAD

**Issue by Sleeckx** [Polymer/polymer#1490]
Opening the following test case on IE11 will throw an error in the ***```transformElement```*** function in the ***style-transformer.html*** file because the element doesn't have a classList. Chrome shows the SVG element without a problem.

http://jsbin.com/vududa/1/edit?html,output

Could we maybe add a check for this in the starting condition, like ```if(useAttr || !element.classList)```?

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/polymer/commit/0f5bfa5b56582bde3928fcc7d2ef62ccd42984bf
