### ISSUE TITLE
Upgrade from polymer 0.5 to 0.8

### ISSUE THREAD

**Issue by bilalqayyum7861** [Polymer/polymer#1492]
Hello I am trying to upgrade **polymerJs** from ```0.5 to 0.8``` using bower. 
As we know that running ```$ bower update``` will update all of the necessary packages.

But unfortunately it is updating to ```0.5.5 not to 0.8.0``` Can someone please let me know what exactly the problem is or how can i achieve the upgrade ? Much appreciated. Thanks

http://stackoverflow.com/q/30079420/4870985

**Comment by dhubler** [comment]
0.8 is in preview so if you want to live on the edge, you have to edit
bower.json to point to the git branch explicitly.

**Comment by Nevraeka** [comment]
Pin it in your 'bower.json` to `bower install polymer#0.9.0-rc.1` or whichever rc for 0.8 you want

**Comment by Nevraeka** [comment]
@dhubler did you get it working ?

**Comment by dhubler** [comment]
@bilalqayyum7861 had the issue.  I'm all set w/0.8 sans my paper-based
elements
