### ISSUE TITLE
[0.9] when I move a dom-repeat element from one parent to another, the items will gone

### ISSUE THREAD

**Issue by jwu** [Polymer/polymer#1498]
```html
<dom-module id="custom-element">
  <template>
    <template is="dom-repeat">{{users}}</div>
  </template>
</dom-module>
```

In the <body>

```html
<div id="first"><custom-element id="my-list"></custom-element></div>
<div id="second"></div>
```

When I use `Polymer.dom(element("#second")).appendChild( element("#my-list") )`, the whole list inside it will be removed.

**Comment by jwu** [comment]
Well, I check the Polymer latest code and found this issue relative with the code here: https://github.com/Polymer/polymer/blob/0.8-preview/src/lib/template/dom-repeat.html#L199

In the `dom-repeater` there is a `detached` callback that will clear all the list when the dom detached. I think it should add an `attached` callback to recover this, otherwise the dom list will gone, but the Polymer element still have that data keep on it. 

Q: When will people detached a list and attach it some where again?
A: I have a panel system that can freely dock itself from one parent to another. If there is a dom-repeat list in it, when the panel move, the items in the dom-repeat will be `detached` based on the code I found above, but never recover again when the panel dock to other element.

**Comment by kevinpschaaf** [comment]
Yes, `dom-repeat` needs balanced re-attachment logic to re-insert stamped nodes back into the DOM after having been detached.  This will be the fix.
