### ISSUE TITLE
hyphenated attribute names should map to camelCase property names (was: Change watchers do not work for hyphenated attribute names)

### ISSUE THREAD

**Issue by jonrimmer** [Polymer/polymer#150]
If element attribute name contains a hyphen, e.g. ```paragraph-size```, a corresponding change watcher named ```paragraph-sizeChanged``` is not called, even if it is placed on the element prototype.

**Comment by ImanMh** [comment]
Yea, many HTML attributes contain dashes in their names so it's very luckily you end up with a code that contains dozens of ```[``` and ```]``` which is really ugly.

**Comment by robdodson** [comment]
@stevenroose @ImanMh Polymer 0.8 will support dashes for custom attributes. https://github.com/webcomponents/customelements.io/issues/210#issuecomment-76392605

> In order to bind to camel-case properties of elements, dash-case should be used in the attribute name

Polymer.Dart is a separate project maintained by a different team, I'm not sure why they've decided to drop dashes. @justinfagnani may know more.

**Comment by justinfagnani** [comment]
No idea. @sigmundch ?

**Comment by jmesserly** [comment]
polymer.dart is matching 0.5.x behavior here. I'm happy to hear it will be changing in 0.8 :)

**Comment by adko-pl** [comment]
Why a web framework built atop on the latest web standards does not support the HTML naming convention (i.d. attribute names with hyphens)? Please, please, please, get it fixed.

**Comment by robdodson** [comment]
@adko-pl it is fixed in 0.8, please be patient

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) release of Polymer - please feel free to re-open if this is incorrect.
