### ISSUE TITLE
Paper-action-dialog with backdrop disables window

### ISSUE THREAD

**Issue by vikjung** [Polymer/polymer#1509]
Refreshed  with bower update today.  Now  dialog with backdrop locks page.  It works when bacdrop not included.

                        <paper-action-dialog backdrop autoCloseDisabled layered="false" id="infolink" class="dialogsize">
                <helpdialog id="dataselect" link="one"></helpdialog>
                            <paper-button dismissive>
                                Close
                            </paper-button>
                        </paper-action-dialog >

**Comment by dominik0711** [comment]
I had the same issue. You have to remove `layered="false"`. Then everything should be fine again.

**Comment by vikjung** [comment]
great thanks closing issue
