### ISSUE TITLE
paper-autogrow-textarea doesn't work as explained in documentation

### ISSUE THREAD

**Issue by yaraju** [Polymer/polymer#1511]
https://polymer-designer.appspot.com/#ec215931065ef58062d7

Problems:
1) Uncaught TypeError: this.$.paper_autogrow_textarea.update is not a function
According to the documentation, we should call "a1.update()" where a1 is the id of the paper-autogrow-textarea element.
2) maxRows doesn't behave as advertised. Whether it "scrolls" or not is dependent on the size of the "textarea", not on the maxRows value.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
