### ISSUE TITLE
[0.9.0-rc.1] Method expression without arguments is not invoked

### ISSUE THREAD

**Issue by GabiAxel** [Polymer/polymer#1516]
For methods defined like this:
```javascript
Polymer(
   is: 'something-something',
   method: function() {
      return "something";
   }
);
```

The following works:
```html
[[method(someObject)]]
```

But this does not work - the method is not invoked at all:
```html
[[method()]]
```

**Comment by thesupremecommander** [comment]
Can confirm. It seems like this is also failing if more than one argument is passed in, as can be seen in PolymerElements/paper-drawer-panel.
