### ISSUE TITLE
[0.9] Touch scroll gesture, setScrollDirection doesn't work any longer

### ISSUE THREAD

**Issue by IntranetFactory** [Polymer/polymer#1520]
After applying https://github.com/Polymer/polymer/commit/617093ca224ed1f2289e531c72150fc6c2698932 from @azakus touch track works, but it seems that now touch scroll doesn't work any longer. In the previous version node.setScrollDirection('y'); enabled vertical scroll, which seems to not work any longer.

Should setScrollDirection work as before or did anything change?

**Comment by IntranetFactory** [comment]
When I remove the `if (!HAS_NATIVE_TA) ` from line 140 (https://github.com/Polymer/polymer/blob/0.8-preview/src/standard/gestures.html#L140) scroll and track works on the iPhone as expected.

**Comment by IntranetFactory** [comment]
It seems to work for me when I switch pan-x and pan-y checks

```
        } else if (ta === 'pan-y') {
          prevent = dx >= dy;
        } else if (ta === 'pan-x') {
          prevent = dy > dx;
        }
```

**Comment by azakus** [comment]
Whoops, thanks for the insight.

**Comment by bendavis78** [comment]
This still seems to be broken, at least in my use case. See the following jsbin: http://output.jsbin.com/nisoru. (you'll need to view it on a touch-capable display or using the chrome mobile emulator).

If you remove `on-track` from the div, you can then scroll the list up and down by dragging.

**Comment by bendavis78** [comment]
Scratch that last comment. I figured out I had to add setScrollDirection before the touch event, as well as pass the 2nd parameter for the target. I've updated the jsbin in case anyone else ends up here :)
