### ISSUE TITLE
[0.5.6] Hang in loading polymer

### ISSUE THREAD

**Issue by ericeslinger** [Polymer/polymer#1524]
Core-menu-button.html, line 80 in the 0.5.6 tagged release has a debugger call in it, which hangs until the user presses resume.

I can't quite figure out how to force bower into loading 0.5.5 either, so this is definitely an issue.

**Comment by arthurevans** [comment]
Sorry about that. core-menu-button has been re-tagged for 0.5.6. I think if you install this version with --force it should update.

**Comment by arthurevans** [comment]
Retag appears to have fixed this one. Please reopen if you're still seeing it.
