### ISSUE TITLE
Could I disable the two-way binding?

### ISSUE THREAD

**Issue by wannadream** [Polymer/polymer#1529]
Our user is asking us to create a data table with around 15,000 rows. I realized that it does not work with Polymer. I think the the component is trying to digesting the whole data which leads to a death of the browser. Is there a way to make the choice by our own decision on two-way binding?

**Comment by arthurevans** [comment]
You don't say what version you're using. Two-way binding is optional in 0.8+, but I don't think that's going to get you to where you want to be. If you're trying to put 15,000 rows in the DOM at one time, that's basically going to be a bad user experience no matter what. 

You probably want some kind of virtualized list view, like [core-list](https://www.polymer-project.org/0.5/docs/elements/core-list-guide.html). That element hasn't been ported to 0.9 yet, though.

**Comment by wannadream** [comment]
Thanks, Arthur.
I think I downloaded 0.5. I will try the new one.

**Comment by rgthree** [comment]
> If you're trying to put 15,000 rows in the DOM at one time, that's basically going to be a bad user experience no matter what.

Just to be clear, the vanilla DOM is very efficient at putting 15,000 rows in at one time. Takes an avg of 150ms on my Chrome desktop and scrolls and behaves just fine. http://fiddle.jshell.net/rgthree/pv4d449n/

**Comment by arthurevans** [comment]
@rgthree It will definitely work, my point was that it wasn't a good user experience. On Chrome desktop, it scrolls OK, but I wouldn't call it a good user experience.

If I just scroll from one end to the other with the trackpad, it takes me 30 seconds or more to get to the end. If I try to scroll using the scroller thumb, the smallest jump I get is about 50 items on a window 30 items high. The only way I would be likely to use a table like this would be Ctrl+F/Cmd+F.

**Comment by kevinpschaaf** [comment]
To opt-out of two-way binding, use `[[...]]` square-bracket binding annotations.
