### ISSUE TITLE
[0.9] this.resolvePath() missing in 0.8/0.9

### ISSUE THREAD

**Issue by yo3jones** [Polymer/polymer#1530]
https://www.polymer-project.org/0.5/docs/polymer/polymer.html#resolvepath

**Comment by arthurevans** [comment]
@sorvell @sjmiles Is this or something like this destined to return?

There appears to be a resolveUrl in 0.9, but it doesn't appear to do the same thing.

**Comment by sorvell** [comment]
The intent is that `resolveUrl(url)` is the replacement for 0.5's `resolvePath`. 

@arthurevans Why do you say it does something different?

**Comment by arthurevans** [comment]
I reproduced the example described in the docs:

https://www.polymer-project.org/0.5/docs/polymer/polymer.html#resolvepath

index.html
bower_components/
    my-thing/
      my-thing.html
      foo.png

index.html contains:
```
<doctype html>
<html>
  <head>
    <link rel="import" href="bower_components/my-thing/my-thing.html">
  </head>
  <body>
    <my-thing>
    </my-thing>
    <script>
      var thing = document.querySelector("my-thing");
      alert(thing.resolveUrl("foo.png"));
    </script>
  </body>
</html>
```

Alert says: "foo.png".

Expected alert to say: "bower_components/my-thing/foo.png".

**Comment by arthurevans** [comment]
Grr. GH won't let me edit my comment properly. Tree should look like this:

```
index.html
bower_components/
  my-thing/
    my-thing.html
    foo.png
```

**Comment by sorvell** [comment]
Does `my-thing` have a `dom-module`? That's now a requirement.

**Comment by arthurevans** [comment]
Gah. It had a dom module ... with a typo.

Fixed typo, now get correct information.

Le sigh. Now just need to document this little hiccup.

**Comment by arthurevans** [comment]
This issue was moved to Polymer/docs#1162
