### ISSUE TITLE
Imported resource from origin 'file://' has been blocked from loading by Cross-Origin Resource Sharing policy: Received an invalid response. Origin 'null' is therefore not allowed access.

### ISSUE THREAD

**Issue by lukaandjelkovic** [Polymer/polymer#1535]
I did the same site as the Making app for 10 minutes , and Chrome
display and white image , the Inspect element was a bug as its title .

Also, bower_components \ polymer \ docs \ index.html was a few files that did not exist . These are:
* Bower_components / polymer / perf - lib / perf.js
* Bower_components / polymer / x- elements / x -doc -viewer / x- doc- viewer.html
* Bower_components / polymer / assets / icons.html

It is a version of the Polymer 0.5 .
Please look at this , I was two or three weeks looked for this.

**Comment by miztroh** [comment]
Due to the way HTML imports work, Polymer requires a web server.  You could try developing using Chrome Dev Editor, which has a built-in web server.

https://chrome.google.com/webstore/detail/chrome-dev-editor-develop/pnoffddplpippgcfjdhbmhkofpnaalpg

**Comment by sorvell** [comment]
By design `HTMLImports` can only load resources that support CORS.

**Comment by kevinpschaaf** [comment]
Those docs are old and vestigial, thanks for pointing out.  We'll remove.  The [PRIMER.md] and (https://github.com/Polymer/polymer/blob/master/PRIMER.md) polymer-project.org website should be used for docs.

**Comment by jdmagic21** [comment]
You could alwasy just set up your own node server and then you can present these locally instead of pushing them to your own testing server.

**Comment by kolarski** [comment]
How about using polymer inside cordova ?

**Comment by xiaoxuanwang** [comment]
We could easily start a web server by using python:
python -m SimpleHTTPServer 8000

**Comment by josephmokenela** [comment]
You can consider using polymer starter kit as well and install the local development server.
The instructions are on the following link. 
https://developers.google.com/web/tools/polymer-starter-kit/

**Comment by stevenroose** [comment]
Wait what?? With the "new web" we will no longer be able to open HTML files from local files?? What the hell?? Can someone perhaps point me to some documentation of this?

**Comment by miztroh** [comment]
@stevenroose Opening an HTML file directly will work just fine via a file protocol URL.  However, ``HTMLImports`` cannot load data via that protocol.

**Comment by stevenroose** [comment]
> Opening an HTML file directly will work just fine

Only when that file doesn't import other files. What if I want to create an offline-capable browser dashboard that does use htmlimports?

**Comment by miztroh** [comment]
Operating offline isn't the issue.  The protocol is the issue.  file:// requests will not work, but you can run a local web server (polymer serve, express, etc.) to use HTTP requests instead.  You could even use the following Chrome extension to run a local web server.

https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en

**Comment by DieAntonie** [comment]
@stevenroose , this isn't an issue in Edge
