### ISSUE TITLE
Improve error message if observer is missing

### ISSUE THREAD

**Issue by robdodson** [Polymer/polymer#1538]
If I define an observer on my properties object but don't actually implement the method, I get a strange error in effects.html: `Uncaught TypeError: this[effect.method] is not a function`. It's really not clear that the issue is a missing observer, I had to track down @cdata who could point me in the right direction. Any chance to handle and send out a helpful error message in this scenario?

**Comment by lrbridge** [comment]
+1

**Comment by kevinpschaaf** [comment]
Yes, we'll be doing a "useful warning" sweep and adding warnings for some obvious things.  For user errors that don't make the cut for having warnings included in Polymer proper, the work-in-progress `polylint` tool will be much more exhaustive.

**Comment by jmcgdz** [comment]
+1
