### ISSUE TITLE
Polymer.dom(parent).querySelector polyfill is broken in 0.8

### ISSUE THREAD

**Issue by zhaoz** [Polymer/polymer#1540]
Trying to use the polyfill and I'm currently unable to querySelector/querySelectorAll with webcomponents-lite

I get an error:
Polymer.dom(parent).querySelectorAll('*')
TypeError: undefined is not an object (evaluating 'Array.prototype.slice.call(b)')

**Comment by zhaoz** [comment]
Note that this was in firefox.

It seems like queryselector just doesn't work at all,

Polymer.dom(this.root).querySelector('blah /deep/ blah') also produces errors.

SyntaxError: An invalid or illegal string was specified

**Comment by arthurevans** [comment]
querySelector is working fine for me.

The first error sounds like the node you're working on (`parent`) is undefined.

The second error is because Firefox doesn't support native shadow DOM, so it doesn't recognize /deep/ as a valid selector.

**Comment by zhaoz** [comment]
What would be correct way to do /deep/ selectors in firefox then? Do you detect if the browser has shadow dom support and remove the deep selector? 
I guess my assumption was that Polymer.dom returns a shim object able to support deep selectors. Maybe that assumption was incorrect.

As for parent is undefined, when can that occur? window.parent points to itself by default. I also tried it again, parent is not undefined.

**Comment by sorvell** [comment]
The argument to `Polymer.dom` must be a node. Therefore, in the original post, an error is expected unless `parent` is a node.

As far as `/deep/`, Polymer.dom's querySelector specifically does not support this. The `/deep/` css selector is being removed from the ShadowDOM spec so it's not good to rely on. In cases where crawling the entire document is absolutely necessary, it can be done manually.
