### ISSUE TITLE
0.9 zip file nearly empty

### ISSUE THREAD

**Issue by hochhaus** [Polymer/polymer#1541]
The 0.9 *.zip file only contains a few files.

https://github.com/Polymer/polymer/archive/v0.9.0.zip

$ unzip polymer-0.9.0.zip
Archive:  polymer-0.9.0.zip
creating: polymer-0.9.0/
inflating: polymer-0.9.0/LICENSE.txt
inflating: polymer-0.9.0/bower.json
inflating: polymer-0.9.0/build.log
inflating: polymer-0.9.0/polymer-micro.html
inflating: polymer-0.9.0/polymer-mini.html
inflating: polymer-0.9.0/polymer.html

Is it possible to regenerating with the entire project?

**Comment by kevinpschaaf** [comment]
Released version tags contain only the built distribution files, none of the source files.

You can look in the [`build.log`](https://github.com/Polymer/polymer/blob/v0.9.0/build.log) for the exact hash of the development source files the tag was created on (https://github.com/Polymer/polymer/tree/37c324d075efd242a777c78c45fa70cfaa639381 for `v0.9.0`), and get the entire source there.

**Comment by hochhaus** [comment]
Thanks @kevinpschaaf.

Either I'm confused or the documentation is inconsistent with your description.

https://www.polymer-project.org/1.0/docs/start/getting-the-code.html#using-zip

    When you download Polymer as a ZIP file, you get all of the dependencies
    bundled into a single archive. It’s a great way to get started because you
    don’t need to install any additional tools.

What am I missing?

**Comment by kevinpschaaf** [comment]
That archive contains the Polymer core library and its (single) dependency, webcomponents.js (web components polyfills for other browsers).  This is the core library, and enough to get started _creating your own elements_.

If you'd just like to _use_ pre-build polymer elements, head to the Polymer elements catalog at https://elements.polymer-project.org, where you can select elements to "add to your cart", and download a ZIP containing those elements and all their dependencies (including Polymer & webcomponents.js).

Last, you can try out Polymer Starter Kit (https://developers.google.com/web/tools/polymer-starter-kit/), which contains elements and an app scaffold to get started even more quickly.

**Comment by hochhaus** [comment]
Thanks @kevinpschaaf.
