### ISSUE TITLE
webcomponents loading order

### ISSUE THREAD

**Issue by triune** [Polymer/polymer#1544]
I have noticed that the order of loading webcomponents, with respect to other js libraries can cause issues. Specifically, loading jQuery before webcomponents will break a very popular jQuery search autocomplete library. 

I have not come across anything in the Polymer documentation that mentions or spells out the recommend loading order for libraries. Could someone explain what is going on here and point to some Polymer documentation to explain this phenomenon?

**Comment by sorvell** [comment]
See the note about this here: https://www.polymer-project.org/0.5/docs/start/platform.html
