### ISSUE TITLE
[0.9] documentation issue - horizontal scrolling broken on code views

### ISSUE THREAD

**Issue by yusufm** [Polymer/polymer#1545]
On https://www.polymer-project.org/0.9/docs/start/quick-tour.html

some of the boxes with code do not scroll horizontally, when trying to use the scrollbars. If you select the long text in the code, you can get it to scroll.

This box doesn't work: https://www.polymer-project.org/0.9/docs/start/quick-tour.html#declared-properties

Browser info: 
Chrome (stable)
Version 42.0.2311.152 (64-bit)

**Comment by arthurevans** [comment]
Thanks for the report, @yusufm. Are you on Windows? We had another report of an issue with these scrollers on Chrome Windows.

**Comment by yusufm** [comment]
Its on ubuntu:

DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04 LTS (upgraded from: Ubuntu 12.04.3 LTS)"
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04

**Comment by tjsavage** [comment]
auto-moving this issue to Polymer/docs#1071 and closing this one
