### ISSUE TITLE
seems that case sensitive properties doesn't work

### ISSUE THREAD

**Issue by votingsystem** [Polymer/polymer#1547]
In this example 'lowerprop' works as expected and 'caseSensitiveProp' doesn't get its value
   
     <dom-module id="user-view">
            <template>
                First: <span>{{caseSensitiveProp}}</span><br/>
                Last: <span>{{lowerprop}}</span>
            </template>
        </dom-module>
        <script>
            Polymer({
                is: 'user-view',
                properties: {
                    caseSensitiveProp: String,
                    lowerprop: String
                }
            });
        </script>

        <user-view caseSensitiveProp="sValue" lowerprop="lValue"></user-view>

**Comment by arthurevans** [comment]
Try:

    <user-view case-sensitive-prop="sValue" lowerprop="lValue"></user-view>

For an explanation, see:

https://www.polymer-project.org/0.9/docs/devguide/properties.html#property-name-mapping
