### ISSUE TITLE
Layout functionality in 0.9

### ISSUE THREAD

**Issue by nojaf** [Polymer/polymer#1551]
Do all [layout features](https://www.polymer-project.org/0.5/docs/polymer/layout-attrs.html) still exist in 0.9? If not what's the alternative?

**Comment by gertcuykens** [comment]
This I guess https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Flexible_boxes
But I hope they make a layout 0.5 migration example for us because my code is full of layout attributes and going to take  a long time to figure out how to do it in CSS if there is no 0.5 layout migration guide.

**Comment by rbjarnason** [comment]
Maybe this will help? https://www.polymer-project.org/0.9/docs/migration.html#layout-attributes

**Comment by gertcuykens** [comment]
Haha sorry I missed that part :D Thanks

**Comment by nojaf** [comment]
@rbjarnason thx, that will do the trick.
