### ISSUE TITLE
[0.9] How to dynamically import elements?

### ISSUE THREAD

**Issue by zerodevx** [Polymer/polymer#1554]
In 0.5.5, I used to dynamically import elements by calling Polymer.import, then inserting that element into the local DOM. 

May I ask how can I do that in 0.9?

Thanks so much.

**Comment by IntranetFactory** [comment]
There is a new utility function importHref(href, onload, onerror) to dynamically import one component. See https://www.polymer-project.org/0.9/docs/devguide/utility-functions.html

**Comment by zerodevx** [comment]
Yes thank you, I must have missed this. I will test this out. Thanks again.

On 17 May 2015 18:50:54 GMT+08:00, Martin Amm <notifications@github.com> wrote:
>There is a new utility function importHref(href, onload, onerror) to
>dynamically import one component. See
>https://www.polymer-project.org/0.9/docs/devguide/utility-functions.html
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Polymer/polymer/issues/1554#issuecomment-102782934

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
