### ISSUE TITLE
Offsetting core drawer panel

### ISSUE THREAD

**Issue by VigneshVaidyanathan** [Polymer/polymer#1557]
I would like to know if we can offset the core drawer panel when the toggle button is clicked so that the drawer scrolls after the toggle button but still the toggle button should be active to be clicked on again to hide the drawer panel.
Also is it possible to make the core drawer panel scroll from bottom, say an options bar that when toggled will scroll up from bottom.

Thanks

**Comment by tjsavage** [comment]
auto-moving this issue to PolymerElements/paper-drawer-panel#25 and closing this one
