### ISSUE TITLE
core-tooltip/demo.html was not found on this server.

### ISSUE THREAD

**Issue by hano** [Polymer/polymer#1558]
The requested URL /0.5/components/core-tooltip/demo.html was not found on this server.

https://www.polymer-project.org/0.5/components/core-elements/demo.html#core-tooltip

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
