### ISSUE TITLE
Logical Operators doesn't work anymore in 0.9

### ISSUE THREAD

**Issue by drxcheng** [Polymer/polymer#1568]
! || &&

Or is there an alternative way?

**Comment by arthurevans** [comment]
0.9 doesn't support any expressions, except for simple negation (!).

https://www.polymer-project.org/0.9/docs/migration.html#data-binding

In most cases, what you want is a computed binding:

    <span>{{userType(user.type, defaultType)}}</span>

Where `userType` is a function like:

    userType: function(type, default) {
     return type || default;
    }

Note that in 0.9, computed bindings don't accept literal arguments at this point (that is, I can't use `{{userType(user.type, "End User")}}`. However I believe that's already checked in to master and should be in 1.0.
