### ISSUE TITLE
Array helpers don't notify length change

### ISSUE THREAD

**Issue by mbleigh** [Polymer/polymer#1573]
If I use the built-in array mutation helpers, I would expect that they would properly notify not just on the array itself but also on its length. Right now I have an app with a counter and I have to manually `notifyPath` for the length each time I mutate the array.

**Comment by kevinpschaaf** [comment]
You can observe `array.splices` or `array.*`, which will get notified for any array mutations that affect the length of the array.  Is that sufficient?

**Comment by mbleigh** [comment]
It works in terms of giving me a workaround without manual notification but
will then require me to memoize the length in a separate value instead of
being able to bind to it directly. Not the end of the world, but "counter
for an array property" is likely a common use case and I wouldn't be
surprised if other people run into the same issue.

**Comment by kevinpschaaf** [comment]
I see, you'd like to bind the actual length `length` into the template, got it.

Sort-term, you could also do this, to avoid needed to make a property:

`{{arrayLength(array.*)}}`

```
arrayLength: function(change) {
   return change.base.length;
}
```

**Comment by mbleigh** [comment]
Nice!
