### ISSUE TITLE
[0.9] Extends delays/breaks polymer element setup

### ISSUE THREAD

**Issue by Xaratas** [Polymer/polymer#1575]
Tested in FF 38, stipped down version of my actual code.

Error Message:
TypeError: dialogueLink.fromXML is not a function
	dialogueLink.fromXML();

Without the extends in this testcase it works.

In my actual code (https://github.com/Xaratas/PillarsOfEternity-Quest-Editor) i have build drag and drop, which creates DialogueLink elements via the constructor. These are created fully, and have all expected polymer properties and my functions. 

I spotted the difference between my working Links from drag and drop and the links from my xml setup. In the drag and drop case i add the element to the dom.
I have a line for this below, but it still prints the error.
Other, non extends elements i create does not have to be added to the dom to call my functions, thats why i think this is a bug.

```html
<!DOCTYPE html>
<html>
  <head>
    <script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
    <link rel="import" href="bower_components/polymer/polymer.html">
  </head>

  <body>
<script>

</script>

    <script>
		 document.addEventListener('WebComponentsReady', function() {
	    DialogueLink = Polymer({
			is: "dialogueLink-element",
			extends: "canvas", // comment out and it works

			properties: {
				randomWeight: Number,
        	    playQuestionNodeVO: Boolean,
            	questionNodeTextDisplay: String,
	            startElement: Object,
    	        endElement: Object
			},
		
    	    // ist vor dem Behavior dran
			factoryImpl: function(startElement, endElement) {
				this.startElement = startElement;
				this.endElement = endElement;
			},
       
			created: function() {
		    	console.log("created and prototype ready");
			},

			fromXML: function(xml) {
        	    console.log("fromXML");
	        }
		});

        	var dialogueLink = new DialogueLink(); // parameter doesnt really matter for this test
               // uncomment, and it will setup the canvas as polymer element, but in this function fromXML() would still "not exist"
               // document.getElementsByTagName("body")[0].appendChild(dialogueLink);
            dialogueLink.fromXML();
        });
	</script>
    
</body>
</html>
```

**Comment by sorvell** [comment]
The issue here is a CustomElements polyfill limitation. The createElement call fails if the extended element is created with an uppercase character in the name.

```
is: "dialogueLink-element", // make the `L` here lowercase and it'll work
```

Closed in favor of https://github.com/webcomponents/webcomponentsjs/issues/313.
