### ISSUE TITLE
Iron-Input hint not turning into label on ChromeBook apps

### ISSUE THREAD

**Issue by akhr** [Polymer/polymer#1581]
Hi,

I tried using the iron-input element and works fine when packaged as an app .crx on Chrome browser on mac or pc. When the same .crx ported to chromebook the app just loads fine but has following issues
1.The input element's hint turning into label wont just work.
2.If this input element is a part of form, then form submission wont read the values from these elements. 

Attached screenshots from desktop chrome (just works fine) and chromebook (where it wont).

Thanks
Akhash
<br>
<b>On Desktop :</b><br>
![chrome](https://cloud.githubusercontent.com/assets/695965/7739874/bc13c7ce-ff1d-11e4-8674-84e63ba83ec4.png)

<br>
<b>On ChromeBook:</b><br>
![cb_1](https://cloud.githubusercontent.com/assets/695965/7739895/ee2726ac-ff1d-11e4-9a55-0ac41cce7a62.png)
![cb_2](https://cloud.githubusercontent.com/assets/695965/7739896/f25eddf0-ff1d-11e4-8d79-7120611a838d.png)
![cb_3](https://cloud.githubusercontent.com/assets/695965/7739898/f46734f8-ff1d-11e4-9cf1-f00aad89c809.png)

**Comment by tjsavage** [comment]
auto-moving this issue to PolymerElements/iron-input#22 and closing this one
