### ISSUE TITLE
Content tag does not work inside dom-if template

### ISSUE THREAD

**Issue by shailesh17mar** [Polymer/polymer#1584]
Content is not working inside the conditional template tag. It used to work in Polymer 0.5. 

 <template is="dom-if" if="{{!isIconOnly}}">
          <paper-button raised="{{raised}}" disabled="{{disabled}}" toggles="{{toggles}}" >
               <content ></content>
              <iron-icon icon="{{icon}}" hidden$="{{rightIcon}}"></iron-icon>
          </paper-button>
      </template>

**Comment by kevinpschaaf** [comment]
Related to https://github.com/Polymer/polymer/issues/1565 (investigate at same time).
