### ISSUE TITLE
Tap event not firing the first time after tracking another element

### ISSUE THREAD

**Issue by Sleeckx** [Polymer/polymer#1590]
Created a test case here: http://jsbin.com/cowarujeje/2/edit?html,output

When I first move the red square by dragging it, then click the Tap Me element, the tap event isn't fired. Only after clicking it a second time it fires as normal again.

**Comment by azakus** [comment]
Yep, there's a bad state reset for tap. Easy fix.

**Comment by Sleeckx** [comment]
Unfortunately, this is broken again with the current code :cry:
The same test case still applies: http://jsbin.com/cowarujeje/2/edit?html,output
First drag the red square, then tap the **Tap Me** button.
