### ISSUE TITLE
Allow for assigning multiple handlers for the same event on the same element, declaratively in HTML

### ISSUE THREAD

**Issue by miztroh** [Polymer/polymer#1593]
Perhaps `<div on-click="handler1 handler2"></div>`?

**Comment by TimvdLippe** [comment]
In Polymer 2 you can implement this sugar by overriding [`_parseTemplateNodeAttribute`](https://www.polymer-project.org/2.0/docs/api/elements/Polymer.Element#method-_parseTemplateNodeAttribute) and extracting the events. The corresponding library code can be found [here](https://github.com/Polymer/polymer/blob/1a32f4dd423116c5d1ee13e452922839d4eebd60/lib/mixins/template-stamp.html#L358-L366)
