### ISSUE TITLE
[0.9.1] Regression in styling with custom css mixins

### ISSUE THREAD

**Issue by cedric-marcone** [Polymer/polymer#1601]
Hi,
I don't know if it's on purpose because I can't keep up with the flow of recent commits but, in 0.9.0, passing multiple mixins to `@apply` used to work like a charm : 

```css
.class {
  @apply(--layout-horizontal --layout-center);
}
```

In 0.9.1, styles are not applied until you split the declaration with multiple `@apply` :

```css
.class {
  @apply(--layout-horizontal);
  @apply(--layout-center);
}
```

**Comment by sorvell** [comment]
Yup, this was done on purpose. Sorry for the churn. 

We decided to leave room inside the parens (...) for future more interesting enhancements to the syntax. 

As you discovered, you'll need to use multiple `@apply` properties.

**Comment by cedric-marcone** [comment]
Thanks for the feedback.
Exciting times ahead !
I can't wait for the Google IO ;)
