### ISSUE TITLE
Blog down https://blog.polymer-project.org/ 

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#1603]
Somebody pushed the wrong button :P

https://blog.polymer-project.org

**Comment by arthurevans** [comment]
Thanks Gert. Yep, we have a DNS problem affecting the blog. Please stand by, may be offline for a couple of days.

**Comment by Nevraeka** [comment]
thanks @arthurevans

**Comment by ebidel** [comment]
Dupe of https://github.com/Polymer/docs/issues/1081#issuecomment-105442831
