### ISSUE TITLE
[0.9] Documentation issue (dom-repeat)

### ISSUE THREAD

**Issue by cedric-marcone** [Polymer/polymer#1608]
I can't find the right way of accessing the DOM generated by a `dom-repeat`.

Looking up the code it seems I can use the `rows` property in a `dom-change` event handler but I'm not sure it's really a public API...

Any hints ?

**Comment by kevinpschaaf** [comment]
Can you help us understand what you mean by "accessing the DOM?", i.e. what are you trying to accomplish?

Once `dom-change` is fired, you can querySelect for the elements that it stamped.

`rows` are not the DOM, they are the "template instances", aka binding scope for the elements stamped.

In general, for DOM stamped using a data-based system like `dom-repeat`, you are generally better off interacting with the dom via the data rather than selecting and modifying DOM managed by the `dom-repeat` directly.

**Comment by cedric-marcone** [comment]
My bad :)

First of all, I'm in the process of porting a component I wrote using 0.5.
This component is not "classic" because it layouts elements : it takes a collections of variable heights "cards" and shuffle them in dynamically generated columns :

Here is a gist of the 0.5 component :
https://gist.github.com/cedric-marcone/bee589a81bcc9e7ee93b#file-card-layout-html

It was invoked this way : 

```html
<card-layout data="{{myCollection}}">
  <template>
    <my-element item="{{}}"></my-element>
  </template>
</card-layout>
```

As you can see in the gist, `card-layout` used to configure the provided template in order to generate the content for the collection bound to the data attribute and stamp it in the light DOM.

```js
this.template = this.querySelector('template');
this.template.setAttribute('repeat', '');
this.template.model = this.data;
```

While trying to port my code, I discovered two things : 

1) "Upgrading" a raw template by adding `is="dom-repeat"` at runtime doesn't work
-> Whats's the recommended way to dynamically force a native element to extend a type-extension custom element ?

2) I understood that `dom-change` is fired once the DOM was updated and I could reproduce this behavior in simple test cases, but, trying to do it while porting this element I stumbled on something strange : my domChanged event handler was called but the was nothing to see until I added an async call with a 100ms delay.
-> There must be an edge case where the `dom-change` is fired before modifications are propagated to the DOM.
-> I'll try to extract a piece of code to reproduce this behavior today

**Comment by cedric-marcone** [comment]
@kevinpschaaf : You can close the bug.
The problem I was facing was related to my "unreasonable" use of dynamically stamped elements.

@ebidel said at IO that migration to 1.0 was an "implementation detail", but sometimes it's not ;)
- you really have to make up your mind on the right way to do things
- it's really for the best because everything is MUCH cleaner now

**Comment by kevinpschaaf** [comment]
Ok, glad you got unblocked.  Thanks for the follow-up.

**Comment by zerodevx** [comment]
@cedric-marcone 
Hi, I understand this issue is closed. However, regarding (1),
> 1) "Upgrading" a raw template by adding is="dom-repeat" at runtime doesn't work
> -> Whats's the recommended way to dynamically force a native element to extend a type-extension 
> custom element ?

I am wondering if you found out how to imperatively invoke `dom-repeat`? I too am wondering what's the best practice for this.

Thanks,
J
