### ISSUE TITLE
[0.9] Array mutation API documentation

### ISSUE THREAD

**Issue by amannn** [Polymer/polymer#1609]
In the [documentation regarding declared properties](https://www.polymer-project.org/0.9/docs/devguide/properties.html#array-observation) it is mentioned that there is a specific API for mutating arrays, so that observers take notice. It appears to me that the link is dead. The section doesn't seem to be availble (#array-mutation).

I guess that part of the documentation should be fixed. Would you mind telling me in the meantime what these APIs are?

**Comment by arthurevans** [comment]
Thanks for letting us know. I'll take a look at this when I get to the office. In the meantime, see the 0.9 release notes, here:

https://www.polymer-project.org/0.9/docs/release-notes.html#span-classbreakingbreaking-changespan-array-mutation-methods

**Comment by amannn** [comment]
Thanks for the quick response!

**Comment by arthurevans** [comment]
This issue was moved to Polymer/docs#1160
