### ISSUE TITLE
polymer variable not initializing

### ISSUE THREAD

**Issue by zishanj** [Polymer/polymer#1610]
I am using polymer 0.5.5 and I am trying to create animated pages with `core-animated-pages`. I am using it like this inside the `body` tag:

    <core-animated-pages selected="{{page}}" transitions="hero-transition slide-up slide-down cross-fade list-cascade" on-core-animated-pages-transition-end="{{complete}}">

      <section layout vertical>

        <div class="tall-toolbar categories" slide-down>
          <span>Your name here</span>
        </div>

        <div class="tiles-container">
          <div class="tile" style="background-color:#ccc;" layout vertical>
            <div class="tile-top" flex></div>
            <div class="tile-bottom" style="background-color:#aaa;">
              Leaderboard
            </div>
          </div>
          <div class="tile" hero-id="category-image" hero style="background-color:#ffff8d;" layout vertical on-tap="{{transition}}">
            <div class="tile-top" flex></div>
            <div class="tile-bottom" hero-id="footer" hero style="background-color:#ffeb3b;">
              General Knowledge
            </div>
          </div>
          <div class="tile" style="background-color:#b9f6ca;" layout vertical>
            <div class="tile-top" flex></div>
            <div class="tile-bottom" style="background-color:#0f9d58;">
              Category 2
            </div>
          </div>
          <div class="tile" style="background-color:#ff8a80;" layout vertical>
            <div class="tile-top" flex></div>
            <div class="tile-bottom" style="background-color:#db4437;">
              Category 3
            </div>
          </div>
          <div class="tile" style="background-color:#82b1ff;" layout vertical>
            <div class="tile-top" flex></div>
            <div class="tile-bottom" style="background-color:#4285f4;">
              Category 4
            </div>
          </div>
          <div class="tile" style="background-color:#b388ff;" layout vertical>
            <div class="tile-top" flex></div>
            <div class="tile-bottom" style="background-color:#7e57c2;">
              Category 5
            </div>
          </div>
        </div>

      </section>

      <section layout vertical>

        <div class="top" hero-id="category-image" hero flex layout horizontal center center-justified>
          <div class="top-image" cross-fade></div>
        </div>
        <div class="bottom" hero-id="footer" hero cross-fade>
          <span cross-fade>General Knowledge</span>
        </div>
        <div class="fab fab-0" hero-id="fab" hero>
          <paper-fab icon="av:play-arrow" on-tap="{{transition}}" hero></paper-fab>
        </div>
      </section>
    </core-animated-pages>

I am then trying to initialize `page` property in polymer like this:

    Polymer({
      page: 0,
      transition: function(e) {
        if (this.page === 1) {
          this.page = 0;
        } else {
          this.page += 1;
        }
      }
    });

This throws an error because I am not using any `element` name inside polymer constructor. If I try to create custom polymer element and then use above constructor inside it then it works fine and pages also get animated. 

Is there any workaround to this, so I can use it inside the `body` tag without creating any custom element?

**Comment by arthurevans** [comment]
What you want is called an auto-binding template:

https://www.polymer-project.org/0.5/docs/polymer/databinding-advanced.html#autobinding

**Comment by zishanj** [comment]
Thanks for the reply. It has worked though with auto-binding, but I am facing one issue now. Initial transition doesn't work and it just jumps to second page, but on second page the transition works fine and it returns to first page very smoothly. Here are my updated codes:

    <template id="test-card" is="auto-binding">
      <core-animated-pages selected="{{page}}" transitions="hero-transition slide-up slide-down cross-fade list-cascade" on-core-animated-pages-transition-end="{{complete}}">
        <section>
          <div horizontal around-justified layout wrap>
            <paper-shadow z="2" class="card" vertical layout hero-id="open-card" hero>
              <div flex auto vertical layout>
                <div flex auto horizontal center center-justified layout relative class="card-image">
                  test
                </div>
                <div class="card-footer" horizontal center layout>
                  <paper-icon-button icon="arrow-back" alt="read" on-tap="{{transition}}"></paper-icon-button>
                  <div flex class="align-right">
                    <paper-icon-button icon="info" alt="info"></paper-icon-button>
                  </div>
                </div>
              </div>
            </paper-shadow>
          </div>
        </section>
        <section layout="" vertical="">
          <div hero-id="open-card" hero>
            <div class="top" flex="" layout="" horizontal="" center="" center-justified="">
              <div class="top-image" cross-fade=""></div>
            </div>
            <div class="bottom" cross-fade="">
              <span cross-fade="">General Knowledge</span>
            </div>
            <div class="fab fab-0">
              <paper-fab icon="av:play-arrow" on-tap="{{transition}}"></paper-fab>
            </div>
          </div>
        </section>
      </core-animated-pages>
    </template>
Here is my js code:

    var t = document.querySelector('#open-card');
    t.page = 0;
    t.transition = function(e) {
      if (t.page === 1) {
        t.page = 0;
      } else {
      t.page += 1;
     }
    };

I have tested it with custom polymer element but the transition works fine there. Any idea what's going wrong here?

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
