### ISSUE TITLE
paper-slider input box overflow.

### ISSUE THREAD

**Issue by cmcneil** [Polymer/polymer#1611]
Hello,
When I use the `<paper-slider editable></paper-slider>`
element, everything works as in the demo, until I type more than 3 characters into the input, at which point text gets cut off(The fourth character gets chopped in half and more characters don't appear at all). I think this is supposed to be controlled from within paper-slider element, not styled from the outside. Is this incorrect?

**Comment by tjsavage** [comment]
auto-moving this issue to polymerelements/paper-slider#11 and closing this one
