### ISSUE TITLE
[0.9.2] dom-repeat issues in 0.9.2

### ISSUE THREAD

**Issue by jeffposnick** [Polymer/polymer#1615]
Somewhere between 0.9.0 and 0.9.2, it seems like a bug's been introduced in `<dom-repeat>`. Here are two JSBins illustrating the problem, nested inside of a `<dom-bind>` parent:

Working 0.9.0: http://jsbin.com/topize/3/edit
Broken 0.9.2: http://jsbin.com/fuxode/2/edit

In 0.9.2, the <template>'d content isn't being stamped out to the DOM. By the time the `WebComponentsReady` is fired, the property on the parent `<dom-bind>` that is being repeated is set to undefined.

**Comment by kevinpschaaf** [comment]
@jeffposnick We should be able to get https://github.com/Polymer/polymer/pull/1618 in a release tomorrow.
