### ISSUE TITLE
chrome embed/object re-render when switching core-animated-pages

### ISSUE THREAD

**Issue by ShockiTV** [Polymer/polymer#1616]
Hello,

When I switch tab of core-animated-pages in chrome back to embeded object, it re-renders it.
In IE/firefox it was not showing that behaviour - it was keeping it untouched so it does not load every time I switch tabs.

My little polymer wrapper:
``` html
<polymer-element name="special-wrap" noscript>
  <template>
      <paper-tabs noink nobar selected="1" selectedindex="0" id="paper_tabs" horizontal center layout>
        <paper-tab id="paper_tab" inline flex center-center horizontal layout>Chat</paper-tab>
        <paper-tab id="paper_tab1" inline flex center-center horizontal layout active>Search</paper-tab>
        <paper-tab id="paper_tab2" inline flex center-center horizontal layout>Social</paper-tab>
      </paper-tabs>
        <core-animated-pages transitions="slide-up slide-down cross-fade" selected="{{ $.paper_tabs.selected }}" lastselected="0" selectedindex="1" notap id="core_animated_pages">
          <content></content>
        </core-animated-pages>
  </template>
</polymer-element>
```
Website I am expiriencing this is http://shockitv.meteor.com, when switching from other tabs to Chat. By clicking on stream in Search tab it start embedding video player and given chat to Chat tab. So to reproduce first pick 1 from Search and switch to Chat tab. And then switch however u want.

Regards
Robert ShockiTV Simon

**Comment by ebidel** [comment]
Closing stale issues. Please reopen on the 1.0 element's repo if you have a reproducible test.
