### ISSUE TITLE
Trouble accessing light dom element properties in Polymer 0.9

### ISSUE THREAD

**Issue by shailesh17mar** [Polymer/polymer#1617]
So, I have a table and I need to access the light dom 't-column' elements in 'domReady'. Since, domready has been removed from Polymer 0.9, is there any other way to access elements because the even the 'attached' event of t-table is called before the 'ready' lifecycle event of 't-column'.
<t-table id="rtable"  edittable="true" searchable="true" search-on="fruit" >
                                <t-column hide-on="tablet" data-value="fruit" display-value="Name" action="test"></t-column>
                                <t-column hide-on="phone"  data-value="alice" display-value="Role"></t-column>
                                <t-column ignore-sort="true" data-value="bill" display-value="Last" ></t-column >
                                <t-column data-value="casey" display-value="Status" ></t-column>
                                <template id="test" name="edit">
                                    <iron-icon src="http://www.unixstickers.com/image/cache/data/stickers/golang/golang.sh-600x600.png" style="width: 24px; height: 24px;"> </iron-icon>
                                    <span>{{}}</span>
                                </template> 

```
                            <t-body>
                                [
                                    { "fruit":"apple",  "alice": 4, "bill": 10, "casey": 2 },
                                    { "fruit":"banana", "alice": 0, "bill": 4,  "casey": 0 },
                                    { "fruit":"grape",  "alice": 2, "bill": 3,  "casey": 5 },
                                    { "fruit":"pear",   "alice": 4, "bill": 2,  "casey": 8 },
                                    { "fruit":"apple",  "alice": 4, "bill": 10, "casey": 2 },
                                    { "fruit":"banana", "alice": 0, "bill": 4,  "casey": 0 },
                                    { "fruit":"grape",  "alice": 2, "bill": 3,  "casey": 5 },
                                    { "fruit":"apple",  "alice": 4, "bill": 10, "casey": 2 },
                                    { "fruit":"banana", "alice": 0, "bill": 4,  "casey": 0 },
                                    { "fruit":"grape",  "alice": 2, "bill": 3,  "casey": 5 },
                                    { "fruit":"pear",   "alice": 4, "bill": 2,  "casey": 8 },
                                    { "fruit":"apple",  "alice": 4, "bill": 10, "casey": 2 },
                                    { "fruit":"banana", "alice": 0, "bill": 4,  "casey": 0 },
                                    { "fruit":"grape",  "alice": 2, "bill": 3,  "casey": 5 }
                                ]
                            <t-body>
                    </t-table>  
```

**Comment by TimvdLippe** [comment]
In Polymer 2 you can use the `connectedCallback` and use `slot.assignedNodes()` to retrieve the light-dom content: http://jsbin.com/dibicehece/edit?html,console,output
