### ISSUE TITLE
animating to single page from multiple elements

### ISSUE THREAD

**Issue by zishanj** [Polymer/polymer#1619]
I ran into a situation where I am using transition to change to next page using `core-animated-pages`. On initial page I have created elements dynamically using `repeat` in template like this:

      <core-animated-pages selected="{{page}}" transitions="hero-transition slide-up slide-down cross-fade list-cascade" on-core-animated-pages-transition-end="{{complete}}">
        <section>
          <div horizontal around-justified layout wrap>
          <template repeat="n in [1,2,3]">
            <paper-shadow z="2" class="card" vertical layout hero-id="open-card{{n}}" hero>
              <div flex auto vertical layout>
                <div flex auto horizontal center center-justified layout relative class="card-image">
                  test
                </div>
                <div class="card-footer" horizontal center layout>
                  <paper-icon-button icon="arrow-back" alt="read" on-tap="{{transition}}"></paper-icon-button>
                  <div flex class="align-right">
                    <paper-icon-button icon="info" alt="info"></paper-icon-button>
                  </div>
                </div>
              </div>
            </paper-shadow>
           </template>
          </div>
        </section>
        <section layout="" vertical="">
          <div hero-id="open-card" hero>
            <div class="top" flex layout horizontal center center-justified>
              <div class="top-image"></div>
            </div>
            <div class="bottom">
              <span>General Knowledge</span>
            </div>
            <div class="fab fab-0">
              <paper-fab icon="av:play-arrow" on-tap="{{transition}}"></paper-fab>
            </div>
          </div>
        </section>
      </core-animated-pages>

The actual problem is my second page is same irrespective of the dynamic elements that create transition and instead of creating multiple same pages, I want to use single page only. The above code doesn't works well because the `hero-id` requires to be a unique id.

Is there any workaround to this?

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
