### ISSUE TITLE
Issue with scrolling using the flot library

### ISSUE THREAD

**Issue by anniesullie** [Polymer/polymer#162]
I made a page that uses flot to plot some charts inside custom elements. When I scroll down the page, the flot library plothover event sends events with incorrect data. It works correctly if I use plain HTML instead of a custom element.

Here is a test case I made:
https://github.com/anniesullie/polymer-flot-bug

The file flot-scroll.html demonstrates the bug, and the file flot-scroll-no-polymer.html demonstrates that there is no bug when I use plain html without polymer.

**Comment by czellweg** [comment]
@anniesullie I'm facing almost the same problem. Would you mind sharing your solution, i.e. how you patched document.contains? Your help would be greatly appreciated.

**Comment by anniesullie** [comment]
@czellweg - The code that called into document.contains was actually jQuery, so we ended up patching the jQuery implementation of document.contains. Here's the code, which is quite hacky--you could do something more general case for the 'MY ELEMENT HERE' part, of course.

    // Workaround for document.contains returning false for elements in the
    // shadow DOM. jQuery mouse events need it to return true for scrolling
    // to be properly accounted for. For background, see
    // https://github.com/Polymer/polymer/issues/162 and
    // https://www.w3.org/Bugs/Public/show_bug.cgi?id=22141
    jQuery.contains = function(doc, elem) {
      shadowElems = document.getElementsByTagName('ELEMENT NAME HERE');
      for (var i = 0; i < shadowElems.length; i++) {
        if (shadowElems[i].shadowRoot.contains(elem)) {
          return true;
        }
      }
      return doc.contains(elem);
    }

@azakus @dglazkov - Did the spec and implementation ever get updated to deal with this better?

**Comment by czellweg** [comment]
@anniesullie Awesome, thanks for your quick reply. Will try it out.
