### ISSUE TITLE
Gestures Events don't have pointerId attribute

### ISSUE THREAD

**Issue by ystreibel** [Polymer/polymer#1620]
Hi,

When I use gestures event, they haven't pointerId properties. 
How could you manage multi-touch event with gestures event ?

More other, after an handleUp, they are a handleTrack !

**Comment by azakus** [comment]
Are you using Polymer 0.5 or 0.9?

**Comment by ystreibel** [comment]
I'm using Polymer 0.9.

**Comment by azakus** [comment]
Polymer 0.9 only has support for one input (mouse or touch) at a time. Two finger gestures will come later, and be narrowly scoped.

**Comment by ystreibel** [comment]
Ok, I'm agree with that but What about the handleTrack after an handleUp ?

**Comment by azakus** [comment]
Yes, track has a state property that says "end", so you know that a track has ended.

**Comment by ystreibel** [comment]
I understand that have an end state for handleTrack but I don't understand why when I have an handleUp, I have an handleTrack.

For me, handleUp is the laste event fire !
