### ISSUE TITLE
Strange events behavior.

### ISSUE THREAD

**Issue by s-chizhik** [Polymer/polymer#1621]
Hi. I wrote my own wrapper(not extend) for `core-ajax` — `my-ajax`, where I handling all needed things and dispatching custom events. Also I didn't make any proxying things for events from `core-ajax`. Recently I made mistake and tried to handle `core-response` event on `my-ajax`. And... It works!
```html
<my-ajax
    id="ajax_save"
    method="PUT"
    url="http://localhost/something"
    body="param={{$.param.selected}}"
    on-core-response="{{onResponse}}"
>
</my-ajax>
```
As srcElement i got `my-ajax`.

I dont think, that it's expected behavior, isn't it?

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
