### ISSUE TITLE
[0.9] Lifecycle event ordering is different between browsers

### ISSUE THREAD

**Issue by ripla** [Polymer/polymer#1622]
This is related to #1467. I have two simple test elements `x-parent` and `x-child`, with lifecycle functions that do a console print. In my DOM I have the `x-child`as a child node of `x-parent`. When running in Chrome I get this console output:
1. parent is created.
2. parent is ready.
3. parent is attached.
4. child is created.
5. child is ready.
6. child is attached.

And with the newest Safari & Firefox I get:
1. parent is created.
2. child is created.
3. child is ready.
4. child is attached.
5. parent is ready.
6. parent is attached.

First of all, is this a bug? Second, as a workaround, how could I reliably know in either the parent _or_ the child component that the other one is now ready and can be accessed?

**Comment by TimvdLippe** [comment]
http://jsbin.com/cexavijere/edit?html,console,output In the parent, given that the child is defined, you can rely that the child is created and connected and you can thus use the child inside the parent immediately.
