### ISSUE TITLE
bower_components default directory

### ISSUE THREAD

**Issue by saan1984** [Polymer/polymer#1630]
Hi,
In this article(https://www.polymer-project.org/0.5/docs/start/reusableelements.html) it is mentioned to run bower install command which will create a bower_components directory and put polymer library as a child sub directory.The screenshot shows the Polymer directory as a sibling of custom element definition file(test-element.html).

To get this project structure we have to add a .bowerc file to configure bower's default directory of installation.

Can you please recheck it and do the changes in the article?

**Comment by kevinpschaaf** [comment]
Right, the default `.bowerrc` was removed from `seed-element` in https://github.com/PolymerElements/seed-element/commit/55e5e2c569f712a3b158fe37c6a768a6144d0096, as it was proving to be too much of a footgun for users unaware that dependencies would be installed outside of the folder (which is technically the correct place per the relative paths that components use to reference their dependencies, but potentially dangerous nonetheless).

In the meantime, the [polyserve](https://github.com/PolymerLabs/polyserve) tool has emerged as one way to deal with the disconnect between where bower puts dependencies when running `bower install` from _within a component_ vs. running `bower install` of a project `bower.json` that _contains components_.  It effectively allows you to put a components dependencies _inside_ of it, but serve them as if they were peers to it.

I'll assign this to our docs editor to make sure our 1.0 docs reflect the change to `seed-element` and current best practices.

**Comment by azakus** [comment]
Closing, docs have been updated for seed-element.
