### ISSUE TITLE
[0.9.4] Dom-if template doesn't stamp when its content contains a wrapped insertion point

### ISSUE THREAD

**Issue by Sleeckx** [Polymer/polymer#1631]
The following case demonstrates the issue:
http://jsbin.com/lolareyeca/1/edit?html,output

Clicking *Go* should cause the dom-if template to stamp, but it doesn't.
When removing the **div** element around the insertion point, it works as intended.

Probably related to #1565, #1584?

**Comment by kevinpschaaf** [comment]
Will be fixed by https://github.com/Polymer/polymer/pull/1816

Confirmed fix in repro case here:
http://jsbin.com/tenata/2/edit
