### ISSUE TITLE
[0.9.4] Nested dom-if templates show invalid content

### ISSUE THREAD

**Issue by Sleeckx** [Polymer/polymer#1632]
Consider the following case: http://jsbin.com/biquxakiqi/1/edit?html,output

After clicking the steps one by one, you will see that *WORLD* is shown even though the value of the *world* property, used in the inner dom-if template, is still false.

Result (tested on Chrome):
![image](https://cloud.githubusercontent.com/assets/2143495/7837253/4d64367e-0486-11e5-947d-530f2bfb613b.png)

Adding **restamp** to the inner dom-if template fixes the issue, as seen in this sample: http://jsbin.com/ducakepone/1/edit?html,output

![image](https://cloud.githubusercontent.com/assets/2143495/7837340/a8f4e196-0486-11e5-9b51-c0f681e48bd8.png)

**Comment by kevinpschaaf** [comment]
Will be resolved in PR https://github.com/Polymer/polymer/issues/1635.
