### ISSUE TITLE
[0.9.4] Data binding works only for "id" attribute?

### ISSUE THREAD

**Issue by miriti** [Polymer/polymer#1633]
I'm trying to bind a computed property to different attributes on different elements. But it works only for "id" attributes. Is it the way it should be? I couldn't find anything about it in the documentation. Or I'm doing something wrong? Here is a reduced case:
http://miriti.github.io/polymer-case/
If you'll "Inspect" those elements you will that only "id" attributes are set as expected. Also other attributes that was bound disappeared!

Code:

```html
<dom-module id="test-element">
    <template>
    <div class="{{computedID('value')}}">DIV</div>
    <p data-id="{{computedID('value')}}">P</p>
    <button id="{{computedID('value')}}">BUTTON</button>
    <a id="{{computedID('value')}}">A</a>
    </template>
</dom-module>

<test-element></test-element>

<script>
Polymer({
    is: 'test-element',
    seed: 293472,
    computedID: function(someval) {
        return this.seed + '_' + someval;
    }
});
</script>
```
http://miriti.github.io/polymer-case/

**Comment by Sleeckx** [comment]
You will have to use $= instead of =
https://www.polymer-project.org/0.9/docs/devguide/data-binding.html#attribute-binding

**Comment by miriti** [comment]
Oh! I'm really sorry for my inattentiveness!
But why it works for "id" attributes?

**Comment by sorvell** [comment]
`id` is also a property so binding to it as a property works.

You will need to use `$=` to bind to `class` or `data-*`.
