### ISSUE TITLE
using javascript core functions

### ISSUE THREAD

**Issue by zishanj** [Polymer/polymer#1641]
Why I can't use javascript core functions like `String.fromCharCode` directly inside double-mustache?

**Comment by kevinpschaaf** [comment]
Polymer currently only supports using inline functions defined on the element prototype, for simplicity.

Marking this as an enhancement request for now.  In the meantime, you can do

```html
{{fromCharCode(foo)}}
```
and
```js
fromCharCode: function(val) {
   return String.fromCharCode(val);
}
```
If you'd like to use that in a lot of elements, you can define `fromCharCode` in a [behavior](https://github.com/Polymer/polymer/blob/master/PRIMER.md#behaviors) that is shared among multiple elements.

**Comment by zishanj** [comment]
Thanks... It would be great if this enhancement is implemented in future release.
