### ISSUE TITLE
Gestures event issue - No offsets management

### ISSUE THREAD

**Issue by ystreibel** [Polymer/polymer#1646]
Hi,

When we try to use the x, y coordinates given by gestures event, we have noticed that the values do not take offsets in account.

You can find a sample code at https://github.com/ystreibel/my-canvas and the working demo http://ystreibel.github.io/my-canvas/components/my-canvas/demo/

This issue seems quite important, Could you please fix it up as soon as possible ?

Thanks.

**Comment by azakus** [comment]
I don't understand what you mean by "offsets". Can you explain a bit more?

**Comment by ystreibel** [comment]
Yes, try to draw on the yellow my-canvas components at http://ystreibel.github.io/my-canvas/components/my-canvas/demo/
Click down and move to the top. You can see a difference between your pointer position and the drawing point.
This difference is due to the first my-canvas conponents heigth (=offsets).

**Comment by azakus** [comment]
Ah I see. What I would recommend you do is use `downEvent.sourceEvent.offsetX` and `offsetY` to find your starting point and use `offsetX + trackEvent.detail.dx` and `offsetY + trackEvent.detail.dy` to draw your line.

**Comment by ystreibel** [comment]
I don't understant why the x,y coordinates are not computed by the topleft corner of the component.
More other, why they are not the sourceEvent on the trackEvent ?

**Comment by azakus** [comment]
sourceEvent was missing on the track events, I added them here: https://github.com/Polymer/polymer/commit/5fb2ef3a312d6d4151ad6b9b8a3f443495492a0a

Making x/y the topleft of a node requires using `getBoundingClientRect`, which will can cause a synchronous layout and be very expensive and slow.

**Comment by ystreibel** [comment]
Cool for sourceEvent on trackEvent, thanks !
Ok, I understand for **getBoundingClientRect**.

**Comment by kevinpschaaf** [comment]
Closing, with @azakus's `sourceEvent` fix there is enough information to calculate the screen position.
