### ISSUE TITLE
Site is not looking good in Mac Chrome Versión 43.0.2357.81 (64-bit) 

### ISSUE THREAD

**Issue by miguelusque** [Polymer/polymer#1650]
Hi! 

    I am trying to watch the examples in your site, and the left side bar is looking ugly (in the left side top, the 'Demo' link is overlapped by other elements)

    Attached an image of what I am watching.

    My laptop is a Macbook Pro with  OS Yosemite 10.10.4 and my Chrome version is 43.0.2357.81 (64-bit) 
![captura de pantalla 2015-05-28 a las 21 45 45](https://cloud.githubusercontent.com/assets/3194737/7869441/11903cbc-0583-11e5-88b5-e2fbeb4511a4.png)

**Comment by DavidSouther** [comment]
Just came here to say the same. 

![screen shot 2015-05-28 at 4 06 31 pm](https://cloud.githubusercontent.com/assets/498712/7869913/a70dce1a-0553-11e5-8c13-4f00740db9f8.png)

**Comment by sorvell** [comment]
Sorry about that, should be fixed in the most recent catalog push.
