### ISSUE TITLE
Color Extraction

### ISSUE THREAD

**Issue by danielhickman** [Polymer/polymer#1654]
Android Lollipop+ has a color extraction API that I've longed to use in my web projects. I've seen other similar projects like Color Thief (http://lokeshdhakar.com/projects/color-thief/), but nothing looks as good as the native Android one. Is there any plans on creating such a API-ish thing to Polymer?

**Comment by clintwood** [comment]
[Just seen this](https://github.com/jariz/vibrant.js), may be relevant.

**Comment by danielhickman** [comment]
Oh my, thank you so much! I still would like a polymer version, but this makes me more than happy!

**Comment by visualfanatic** [comment]
https://github.com/marijnvdwerf/material-palette

**Comment by tjsavage** [comment]
auto-moving this issue to polymerelements/paper-elements#12 and closing this one
