### ISSUE TITLE
dom-repeat data binding issue

### ISSUE THREAD

**Issue by shailesh17mar** [Polymer/polymer#1658]
Following push operation does not re-renders the template.
this.push('property',value);
but if I set the property in inline fashion this.push('property',{value:'value'}). Then it works

**Comment by arthurevans** [comment]
It's hard to know what you're seeing without more code. Is `value` in 

    this.push('property',value);

An object? Can you give us a small complete test case, like a jsbin?

**Comment by shailesh17mar** [comment]
```javascript
var header = {
  						key: data.key,
  						value: data.value,
  						hideOn: data.hideOn,
  						ignoreSort: data.ignoreSort,
  						isChildRow: data.isChildRow,
  						columnTemplate : data.columnTemplate,
  						action: data.action,
  						isSorted :data.isSorted,
  						hideColumn: table._hideColumn(data.hideOn, data.isChildRow)
  					};

//this doesn't work
table.push('columnHeaders',header);

//this.works ( If I do push by assigning value inline)
table.push('columnHeaders',{
  						key: data.key,
  						value: data.value,
  						hideOn: data.hideOn,
  						ignoreSort: data.ignoreSort,
  						isChildRow: data.isChildRow,
  						columnTemplate : data.columnTemplate,
  						action: data.action,
  						isSorted :data.isSorted,
  						hideColumn: table._hideColumn(data.hideOn, data.isChildRow)
  					});
```

**Comment by kevinpschaaf** [comment]
The works & doesn't work cases you showed are equivalent from a JS language point of view, so it's likely there's something going on in your scenario.

Can you try creating a reproduction case starting from http://jsbin.com/?html,output?  Thanks.

**Comment by shailesh17mar** [comment]
So, the problem is there with the event loop. If I do put a set timeout in there then, it starts working as expected. 
```javascript
paginatedRecords.forEach(function(record){
  						setTimeout(function(){
  							table.push('paginatedRecords',record);
  						},0);
  					});
```

**Comment by kevinpschaaf** [comment]
Would you like us to keep this issue open?  There's not enough information here yet for us to reproduce the issue you are seeing, and assess why your `setTimeout` workaround was required.

Please provide a reproduction case if you would like us to investigate something.  Thanks.

**Comment by kevinpschaaf** [comment]
@shailesh17mar Are you still having an issue here, or can we close this issue?
