### ISSUE TITLE
[1.0] extends native element and "is" attribute

### ISSUE THREAD

**Issue by edoardocavazza** [Polymer/polymer#1659]
Hi,

I am migrating my Polymer app from 0.5 to 1.0 and I have some problems with custom elements that extend native elements. I have not found in the migration guide a syntax change about this, so I have tried to use `<native-element is="custom-element">`, but it is not working:
- no custom prototype instance
- no `:host` style

Did I miss something?

Thanks

**Comment by kevinpschaaf** [comment]
Native element type extension is supported using the `extends` property on the prototype definition, and `is` on the instance, similar to 0.5.  Covered in the docs here: https://www.polymer-project.org/1.0/docs/devguide/registering-elements.html#type-extension

Could you please try and set up a repro case that exhibits the problems you're seeing starting with this: http://jsbin.com/?html,output

Thanks!

**Comment by edoardocavazza** [comment]
Hi @kevinpschaaf ,

thanks for your support! As I said, I had missed something! :)

Now all works as aspected!
I am sorry for the inconvenience.

**Comment by kevinpschaaf** [comment]
Great, will close the issue.  Thanks!

**Comment by schnie** [comment]
@edoardocavazza @keanulee Asking you guys because I'm out of ideas hah.. I'm trying to use an iron form with an `<form is="iron-form">` tag, but for some reason the form is just a regular form with none of the iron-form properties or methods.  Other elements (paper-input, paper-button) seem to work fine.  Using chrome.  Any ideas?

**Comment by arthurevans** [comment]
@schnie Make sure you're importing `iron-form` properly. You can double-check by creating one imperatively:

    var form = document.createElement('form');
    var ironForm = document.createElement('form', 'iron-form');
    console.log('Form is a generic form: ' + (form.__proto__ == HTMLFormElement.prototype));
    console.log('IronForm is a generic form: ' + (ironForm.__proto__ == HTMLFormElement.prototype));

**Comment by schnie** [comment]
@arthurevans, I was just going through that haha.  My dom is being dynamically rendered, so prior to the time of rendering, I am doing this exact same test and it shows that `iron-form` exists.  Then it renders my template (containing the iron-form, along with some paper elements) and when I attempt to select the form, from an event handler, it shows it is a generic form, but the other paper elements have definately been upgraded perfectly.  It only happens in chrome, which is even weirder... This is driving me crazy!

**Comment by arthurevans** [comment]
That is really strange. I'm not sure what else you're using (i.e., for the rendering) -- those other elements aren't type-extension elements, so maybe that's the hangup. If the rendering code is trying to treat `is` like any other attribute, that would explain the issue. I think this is probably worth putting on stackoverflow with as much of a reduced test case as you can come up with. 

If your repro case makes it look like a Polymer bug, please open a new issue here.

**Comment by schnie** [comment]
I ruled out type extension issue by importing an `iron-input` element right inside the form and it was able to upgrade that element perfectly!  Its really weird..  Posted an SO question here: http://stackoverflow.com/questions/30807881/polymer-iron-form-not-working
