### ISSUE TITLE
[1.0.2] Global leak found in _marshalArgs

### ISSUE THREAD

**Issue by jwu** [Polymer/polymer#1660]
Hi, 

I was doing mocha test with global leaking check, it raise an error in Polymer library, and I found the _marshalArgs have a leak:
 
https://github.com/Polymer/polymer/blob/6dd6aa9755e2911018a199990875974e4e61f410/src/lib/bind/effects.html#L113

**Comment by kevinpschaaf** [comment]
Thanks.  Fixed in https://github.com/Polymer/polymer/commit/cd4acffab214fb407aec5c10092c8b3b62015bdb.
