### ISSUE TITLE
missing "

### ISSUE THREAD

**Issue by RudolfHladik** [Polymer/polymer#1662]
Hello polymer team,
I have noticed that there is missing "  in your how to install polymer with bower section right in the tip block  ( https://www.polymer-project.org/1.0/docs/start/getting-the-code.html#using-bower )

Tip: --save adds the item as a dependency in your app’s bower.json: 
{
  "name": "my-project",
  "version": "0.0.0",
  "dependencies": {
    "polymer": "Polymer/polymer#^1.0.0             <-------- there is missing " on the end of the line
  }
}

not a big deal, but can cause problems, especially for people who starts with Polymer

**Comment by nanowang** [comment]
Already create a PR for that: https://github.com/Polymer/docs/pull/1092 :)

**Comment by arthurevans** [comment]
Fixed by prior commit.
