### ISSUE TITLE
Wrapping non interpolated strings with span in 1.0

### ISSUE THREAD

**Issue by nathanjohnson320** [Polymer/polymer#1664]
Is there a particular reason why you have to wrap strings that aren't in {{ }} in a span or some other element?

In 0.5 I could do something like
```
<div>per {{ product.UnitType }}</div>
```

But it 1.0 I have to do
```
<div><span>per </span>{{ product.UnitType }}</div>
```

**Comment by kevinpschaaf** [comment]
We didn't quite land that feature in 1.0, but it's on the near-term roadmap.
https://www.polymer-project.org/1.0/docs/#binding-features

**Comment by TimWillis** [comment]
@kevinpschaaf - Is there a place to see the progress of this "near-term roadmap"? This feature for strings in the html and attributes is keeping me from migrating from .5.x to 1.x - it's just way to much of a rewrite especially for attributes as I would have to make tons of computed's like for anchors and href attributes...  thanks

**Comment by kevinpschaaf** [comment]
It should be on the order of weeks, not months.

**Comment by TimWillis** [comment]
Awesome, thank you!
