### ISSUE TITLE
Array mutation without using helper methods

### ISSUE THREAD

**Issue by benjyblack** [Polymer/polymer#1666]
What's the recommended way to signal a change on an array when we're not using the helper methods? For instance, if I want to sort an array, what's the best way to let Polymer know something has changed? At the moment I'm using `this.set('myArray', myArray.slice(0));` but is there a better way?

**Comment by kevinpschaaf** [comment]
Note that `dom-repeat` supports filtering and sorting the _view_, such that for many use cases you don't need to mutate (sort/filter) the actual underlying array: https://www.polymer-project.org/1.0/docs/devguide/templates.html#filtering-and-sorting-lists

Right now, Polymer's array observation doesn't support observing in-place array sorts, so the workaround you are using is probably the best option at the moment if you absolutely need to sort the actual array for some app-specific reason.
