### ISSUE TITLE
[1.0] ::before / ::after psudo selectors in a custom-style

### ISSUE THREAD

**Issue by blasten** [Polymer/polymer#1668]
I came across with this issue while using `::before`
```html
<style is="custom-style">
   span::before {
     content: "->";
     color: red;
   }
</style>
```
The shim will create the selector `span::before:not([style-scope]):not(.style-scope)`, but the browser is expecting `span:not([style-scope]):not(.style-scope)::before`

**Comment by pkaske** [comment]
I wrote a quick and dirty work-a-round-hack to fix this till it's implemented properly.
See 8f26767834d97cf5b679d20745c497ecb059d6c3
