### ISSUE TITLE
PolymerElement enhancement

### ISSUE THREAD

**Issue by zishanj** [Polymer/polymer#1672]
I have tried to use `paper-input` today with external library AngularJS to use bidirectional data-binding with it. But after experimenting and viewing source of `paper-input`, I came to know that it's using `paper-input-container` as it's base element which also accept HTML native `input` element. I have then successfully used AngularJS with `paper-input-container` to use bidirectional data-binding.

After this I thought that the element structure would be same across all other paper elements, but unfortunately it was not like that. I was to use `paper-checkbox` but it was developed differently and doesn't contain any base container which I can use like `paper-input-container` to bind with native HTML `input` element.

I think it will be very beneficial if you follow the same element structure like `paper-input` as a standard and use a base container with native HTML `input` element, that we can use easily to bind with any external library like AngularJS. The reason is, these libraries bind on native HTML `input` element.

**Comment by TimvdLippe** [comment]
I am not really sure what the exact issue is, but `paper-input` does not use the native `input` directly, neither does `paper-checkbox`. Since this issue is quite ancient, I am closing it. Feel free to reopen if you feel your issues were not addressed.
