### ISSUE TITLE
Binding not working for open text

### ISSUE THREAD

**Issue by pawelstep** [Polymer/polymer#1677]
<dom-module id="el-item"> <template> <div>MyCaption = {{caption}}</div> </template></dom-module>
This above does not work. Currently binding works only for entire attribute or for entire tag content
<span>{{caption}}</span>.

Ideallly, binding should work for any piece of text within DOM, like it was in 0.5
<template><div>The company {{company}} CEO is {{ceo}}</div></template>

More, this should work also for CSS customizations (text insertions), and class selectors and inline-style   (I know there are other ways to do it, but that was really great in 0.55):
<template><style>
div {
     background-color:{{bkgcolor}}
}
.caption {
     color:{{fontcolor}}
}
.caption .level1 {
     font-size:10pt;
}
.caption .level2 {
    font-size:8pt;
}
.caption .level3 {
    font-size:8pt;
}
</style>
<div class='caption level{{level}}' style='clear:both; {{addstyle}}'>My Text</div>
</template>

**Comment by IntranetFactory** [comment]
That's by design

> The binding annotation must currently span the entire content of the tag:

See https://www.polymer-project.org/1.0/docs/devguide/data-binding.html

**Comment by pawelstep** [comment]
Let me correct the layout : 
\<template> \<div> MyCaption={{caption}}\</div>\</template>

This above does not work. Currently binding works only for entire attribute or for entire tag content e.g.
\<span>{{caption}}\</span>

<b>I've seen already your comment 'that's by design'. It's a pity. 
So please consider the below ones too:</b>

More, this should work also for:(I know there are other ways to do it, but that was really great in 0.55):
* CSS customizations (text insertions), 
* class selectors
* inline-style.

\<template>\<style>
div { background-color:{{bkgcolor}} }
.caption { color:{{fontcolor}} }
.caption .level1 { font-size:10pt; }
.caption .level2 { font-size:8pt; }
.caption .level3 { font-size:7pt; }
\</style>
\<div class='caption level{{level}}' style='clear:both; {{addstyle}}'>MyText\</div>
\</template>

**Comment by kevinpschaaf** [comment]
The feature wasn't forgotten, we just didn't quite land that for 1.0, but it's documented on the near-term roadmap.
https://www.polymer-project.org/1.0/docs/#binding-features
