### ISSUE TITLE
Where's paper-dropdown-menu 1.0?

### ISSUE THREAD

**Issue by lifeelement** [Polymer/polymer#1684]
I literally just started learning polymer and luckily I didn't get too far before the 1.0 release. My app uses the paper-dropdown-menu, but I don't see it in 1.0.  Will it be added later?

**Comment by hourliert** [comment]
It seems the paper-dropdown-menu is in progress. https://github.com/PolymerElements/paper-elements/blob/master/README.md

**Comment by juampi92** [comment]
Is there any news about the element's progress?

**Comment by eziante** [comment]
Any rough estimates of when the paper-dropdown-menu will be done?

**Comment by antono** [comment]
Looks like iron-dropdown is already implemented: https://elements.polymer-project.org/elements/iron-dropdown

**Comment by lifeelement** [comment]
Did you try the demo? It doesn't behave the same way as the
paper-dropdown-menu from 0.5. Also seems buggy. When selecting a list item,
the visible instead of showing the selected option.

On Sat, Jul 25, 2015 at 4:25 PM, Antono Vasiljev <notifications@github.com>
wrote:

> Looks like iron-dropdown is already implemented:
> https://elements.polymer-project.org/elements/iron-dropdown
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Polymer/polymer/issues/1684#issuecomment-124885751>.
>



-- 
*Roy Oliver, PMP*

**Comment by azumbrunnen** [comment]
Any progress here?

**Comment by DavidPedraza** [comment]
Do you have any estimated date of release??

**Comment by zenorocha** [comment]
FYI this element has been released couple hours ago: https://github.com/PolymerElements/paper-dropdown-menu/releases :pray:
