### ISSUE TITLE
core-animated-pages any plans?

### ISSUE THREAD

**Issue by tdesc** [Polymer/polymer#1689]
Hello, 
My app on polymer 0.5.5 uses core-animated-pages/"hero-transition"
Will it be ported to 1.0?

**Comment by Deseteral** [comment]
You should take a look at Neon Elements

[neon-animation](https://elements.polymer-project.org/elements/neon-animation?active=hero-animation)

**Comment by ebidel** [comment]
Yep, it's now https://github.com/PolymerElements/neon-animation.
