### ISSUE TITLE
Custom Elements polyfill is myopic about SVG

### ISSUE THREAD

**Issue by coonsta** [Polymer/polymer#169]
If I write this in Chrome:

    <!DOCTYPE html>
    <svg>
      <circle is="foo-bar" cx="50" cy="50" r="50" fill="red"></circle>
    </svg>
 
and inspect the red circle, its prototype is SVGCircleElement.prototype. Likewise if I follow through with registering a definition, it stays "instanceof SVGCircleElement".

However if I write this:

    <!DOCTYPE html>
    <script src="polymer/polymer.js"></script>

    <element name="foo-bar" extends="circle">
    <script>
    if (this !== window) {
      this.register({prototype: Object.create(SVGCircleElement.prototype, {})});
    }
    </script>
    </element>
    <svg> 
      <circle is="foo-bar" cx="50" cy="50" r="50" fill="red"></circle>
    </svg>

then the circle becomes a HTMLUnknownElement.

In general it seems the polyfill assumes "extends" refers to HTML elements, and it also doesn't match up tag names of custom elements with what is on the prototype chain (for example if I make that extends="button", then my circle ends up with a prototype chain that leads to HTMLButtonElement.

**Comment by adamthebig** [comment]
+1 for SVG support.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) release of Polymer - please feel free to re-open if this is incorrect.
