### ISSUE TITLE
Computed property doesn't work in dom-repeat

### ISSUE THREAD

**Issue by phanect** [Polymer/polymer#1691]
When I specify computed value in `dom-repeat`, it doesn't work.
In the console, following warning is shown: `Polymer::Attributes: couldn't decode Array as JSON`, but actually this message is wrong.
When I add `throw x;` in [`deserialize` function](https://github.com/Polymer/polymer/blob/master/src/micro/attributes.html#L195), correct error message is shown: `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`.
This occurs because string `csvFieldNames(_relations)` is given to `JSON.parse` as an argument, although JSON string should be given.

Following is the example to reproduce this bug:

```
<link rel="import" href="/bower_components/polymer/polymer.html">

<dom-module id="import-table">
    <template is="dom-repeat" items="csvFieldNames(_relations)">
        <span>{{item}}</span>
    </template>
</dom-module>

<script>
    Polymer({ // jshint ignore:line
        is: "import-table",
        properties: {
            _relations: {
                type: Object,
                notify: true,
                value: {
                    "foo": "bar",
                    "boo": "far"
                }
            }
        },
        csvFieldNames: function(_relations) {
            return Object.keys(_relations);
        }
    });
</script>
```

**Comment by arthurevans** [comment]
You're missing the mustaches around you computed binding, should be:

    "{{csvFieldNames(_relations)}}"

Without the mustaches, Polymer is trying to interpret this as a JSON array literal.
