### ISSUE TITLE
Mobile links off homepage dont work

### ISSUE THREAD

**Issue by fyndor** [Polymer/polymer#1692]
You can easily test this in Chrome by going in to Developer Tools and selecting one of the phone Devices and reloading the https://www.polymer-project.org site.  Because you have a small screen you are forced to having the menu in the dropdown.  I think the menu items off the dropdown in the home page appear to take you to the wrong urls and you get a 404.  If you instead load the page full screen etc on a desktop and go to the https://www.polymer-project.org/1.0/docs/devguide/feature-overview.html page for instance, then change the Device in Developer tools in Chrome back to a phone device the page loads fine.  The problem is if you are coming to the Polymer site from an actual mobile device you will never find that page because the home page gives you the wrong link ;(

**Comment by arthurevans** [comment]
Sorry about that! We're aware of the problem, but still trying to figure out why the wrong layout is being loaded for the 1.0 landing page. This is already reported as Polymer/docs#1108, so closing this as duplicate.

**Comment by rajuGT** [comment]
Closed!! Facing the same issue now :(  automatically redirecting to home page.

**Comment by arthurevans** [comment]
@rajuGT What device & browser are you seeing this on, and can you provide exact repro steps?

This particular bug has been fixed for months. I just tested on iOS Safari and Chrome for Android, as well the Chrome desktop with device emulation, and these links appear to be working.

I did see one issue on iOS Safari where the version picker dropdown doesn't appear to work correctly if the other dropdown menu is open. I'll file that separately.

**Comment by arthurevans** [comment]
Version picker issue: https://github.com/Polymer/docs/issues/1367

**Comment by rajuGT** [comment]
I'm checking in iPad 2, chrome browser version 45. Steps: click get started  button in home page , slowly loads the get started page and redirects back to home page.https://www.polymer-project.org/1.0/

**Comment by arthurevans** [comment]
Thanks for the details. Opened a new issue for this (Polymer/docs#1369). It appears to be confined to Chrome for iOS, oddly enough. I didn't see this issue on Safari or Chrome for Android.
