### ISSUE TITLE
can't use flex inside neon-animated-pages

### ISSUE THREAD

**Issue by zishanj** [Polymer/polymer#1694]
I am using `neon-animated-pages` to animate the page. I have set it's height to 100%. I am using `div` inside it with `background-image`. But the height of div doesn't cover the entire browser height and is limited to it's content only. I have tried using `flex` with div but that also doesn't work. If I use this div outside of `neon-animated-pages` then it flexes well and cover the entire browser height.

What's going wrong inside `neon-animated-pages`?

**Comment by tjsavage** [comment]
auto-moving this issue to PolymerElements/neon-animation#18 and closing this one
