### ISSUE TITLE
Parsing --my-css-variable:; results in an unhandled error

### ISSUE THREAD

**Issue by vsimonian** [Polymer/polymer#1696]
Parsing `--my-css-variable:;` results in an error originating in these lines from `/src/lib/style-properties.html`:

``` js
          while (m = rx.exec(cssText)) {
            // note: group 2 is var, 3 is mixin
            properties[m[1]] = (m[2] || m[3]).trim();
            any = true;
          }
```

In particular, `m[2]` evaluates to `""` and `m[3]` evaluates to `undefined`. This results in `(m[2] || m[3])` evaluating to `undefined`, and `undefined.trim()` naturally throws an error.

It seems to me that such a mistake in CSS is fairly possible (`:;` is not a particularly out-of-the-ordinary mistake to make), but I don't think that the app should come crashing down over a CSS error. It seems, after discussing this with @arthurevans, that a good way of handling this would be to check if `(m[2] || m[3])` is falsy, and if it is, output an error to the console with `console.error` or `console.warn` instead of a `throw` or leaving the error unhandled. I'm not sure if the rule should then have its value blanked or if the malformed definition should be skipped entirely.

I am told @sorvell is the mad scientist who might have a good answer or two. :smile:

**Comment by arthurevans** [comment]
I wasn't sure if it was desirable to have a way to blank out a property, like:

    --my-custom-prop: "";

In which case, we should handle this; otherwise, we should put out a reasonable error. Tagging @frankiefu for an opinion on the above question.

**Comment by TimvdLippe** [comment]
Seems to be fixed: http://jsbin.com/koninutozu/edit?html,console,output
