### ISSUE TITLE
Elements in Polymer

### ISSUE THREAD

**Issue by railsocial** [Polymer/polymer#1697]
Iron and Paper Polymer elements don't load in Polymer v 1.0.
Thank in adavance

**Comment by sorvell** [comment]
You'll need to provide more information about the issue you're having.

Please refer to the documentation at the [Polymer web site](https://www.polymer-project.org) to get started.

**Comment by railsocial** [comment]
I think that the issue is in Polyserve. It says cannot GET /

**Comment by arthurvr** [comment]
> I think the server is not the problem. Every file is loading fine but the paper elements do not show in the browser (Chrome).

@railsocial Some code for us to look at might be beneficial. Also, are you seeing any errors in the console?

**Comment by kevinpschaaf** [comment]
@railsocial Are you still having an issue here, or can we close this issue?

**Comment by sorvell** [comment]
Closing due to age.
