### ISSUE TITLE
Might as well move <script /> to outside of <dom-module /> in README.md

### ISSUE THREAD

**Issue by yutori** [Polymer/polymer#1700]
In [Migration guide](https://www.polymer-project.org/1.0/docs/migration.html), I found `<script />` are defined outside of `<dom-module />`. We might as well move `<script />` to outside of `<dom-module />` in README.md.

**Comment by kevinpschaaf** [comment]
We are encouraging putting `<script>` inside the `<dom-module>` now for readability.  Either way works, and there may be a mix of examples using both syntax, so we'll try and clean that up.

@arthurevans could you do a sweep and make sure the docs are consistent in this respect?  Thanks.

**Comment by IntranetFactory** [comment]
When script is now again inside dom-module would it then be possible to get rid of the is: property where the dom-module name needs to be repeated. It seems that I frequently forget to change one of them when I copy and rename a component. But maybe it's just me.

**Comment by arthurevans** [comment]
This issue was moved to Polymer/docs#1124

**Comment by yutori** [comment]
Thank you for discussed and moved the issue.
