### ISSUE TITLE
Issue running Polymer Started Kit 1.0.0

### ISSUE THREAD

**Issue by cyberabis** [Polymer/polymer#1703]
I downloaded polymer-starter-kit-dependencies-checked-in-1.0.0.zip and tried gulp serve. I got an "Unhandled rejection Error". I bypassed this by adding an error handler for the "images" gulp task and printed the error to console. The error I see is below:

Error in plugin 'gulp-cache'
Message:
    spawn ENOENT
Details:
    code: ENOENT
    errno: ENOENT
    syscall: spawn
    fileName: /Users/abishek/work/dev/onroad/onroad-polymer/app/images/touch/apple-touch-icon.png

Though the server started up after handling the error, wondering what needs to be done here to fix this nicely.

**Comment by kevinpschaaf** [comment]
This issue should be moved to the polymer-starter-kit repo.

**Comment by tjsavage** [comment]
auto-moving this issue to PolymerElements/polymer-starter-kit#110 and closing this one
