### ISSUE TITLE
[1.0] shady dom inserts '<content>' more than once

### ISSUE THREAD

**Issue by Imskull** [Polymer/polymer#1704]
My element:

```
<dom-module my-elem >
  <template>
    <div class="abc">
      <content></content>
   </div>
  </template>
  ...
</dom-module>
```
Scripts:

```
var html = "<my-elem>hello world</my-elem>";
var el1 = document.createElement("div");
el1.innerHTML = html;
var el2 = document.createElement("div");
el2.innerHTML = el1.innerHTML;
```

After, el2:

```
<my-elem>
  <div class="abc">
    <div class="abc">
    hello world
    </div>
  </div>
</my-elem>
```

Shady DOM should check if el2 is _post-processed_ when trying to insert client content at insert point.

**Comment by Imskull** [comment]
You may interesting why I convert HTML and element back and forth, basically, it is because localization and extracting templates from bulk of HTML, it's another story.

**Comment by sorvell** [comment]
You'll running up against one of the limitations of the Shady DOM shim here. For reasons of practicality and performance, Shady DOM does not attempt to modify dom accessors to behave like Shadow DOM. 

Instead the `Polymer.dom` api is provided to produce normalized output. In this case, `e1.innerHTML` is giving you the fully composed dom and you likely want scoped/local dom. Instead you should use `Polymer.dom(e1).innerHTML`. Here's a jsbin sample:

http://jsbin.com/gareni/3/edit?html,output
