### ISSUE TITLE
New version, get stylesheets of the webcomponent

### ISSUE THREAD

**Issue by itamayo** [Polymer/polymer#1705]
HI,

I am working in a platform based on polymer 0.5. We used to work with a webcomponents stylesheets property, but in the new version (1.0)  I could not find a way to get this property. Perhaps is because you have pre-process all css ? Is there any possibility to get this attribute ?

**Comment by sorvell** [comment]
I not sure to what you're referring. Could you provide a small snippet of code that you used to write relevant to this? Thanks.

**Comment by itamayo** [comment]
The platform need to execute media queries of each components when the size of the component changes, not only when window is resized. So to  achieve this functionality, we parse each media queries of each component through component.shadowRoot.stylesheets and we run the media queries rules when the size of the component changes.e.

Is there anyway to have access to each style of each component ?
Best regards.

**Comment by itamayo** [comment]
Is there anyway to have access to each style of each component ?
I checked that there is a  the function component._scopeStyle but it returns a plain text, so is there  some way to get it computed as rules as polymer 0.5 does ?

Thanks

**Comment by zoechi** [comment]
closed, so what is the solution?

**Comment by itamayo** [comment]
For now my solution doesn't resolve the problem but there is a way to access to webcomponent's stylesheet. Document object knows about all stylesheets on the webpage. It is saved with ownerNode reference, so the only thing you have to do is  navigate on the loop on each stylesheet and find matches with your webcomponent's nodeName.

```javascript
            var localName= cmp.localName;
            var appStyles = document.styleSheets;
            var ownStyleSheet=null;

            for (var x in appStyles){
              if (appStyles[x].ownerNode)
                if (appStyles[x].ownerNode.textContent.indexOf(localName)>-1)
                  ownStyleSheet=appStyles[x];
                }
                cssRules=ownStyleSheet.cssRules;
              }
```

On standard of the shadowDom it describes that each of the shadowRoot must have stylesheets attribute that returns StyleSheetList object. I don't know why polymer based webcomponents does not have this attribute, neither I know why shadowRoot is null on polymer webcomponents.

**Comment by zoechi** [comment]
Maybe you need to opt in to use shadow DOM. Default is shady DOM. https://www.polymer-project.org/1.0/docs/devguide/settings.html

**Comment by itamayo** [comment]
Thanks, I will try it tomorrow =)

**Comment by itamayo** [comment]
Better way to do it:

```javascript
Polymer.StyleUtil.parser.parse(Polymer.StyleUtil.cssFromModule('x-media',true))
```
