### ISSUE TITLE
Paper-Button references <core-icon>

### ISSUE THREAD

**Issue by chrisgriffith** [Polymer/polymer#1709]
Since <core-icon> deprecated, this sample should be updated
<paper-button>
  <core-icon icon="favorite"></core-icon>
  custom button content
</paper-button>

to 

<paper-button>
  <iron-icon  src="favorite.png"></iron-icon>
  custom button content
</paper-button>
<iron-icon

**Comment by tjsavage** [comment]
should be fixed as of https://github.com/PolymerElements/paper-button/commit/e27704da98be3c10908814cf0211da399c1004ab
