### ISSUE TITLE
"TypeError: Cannot read property '$' of undefined" during `document.createElement`

### ISSUE THREAD

**Issue by jyasskin** [Polymer/polymer#1711]
[`prepareInstance`](https://github.com/Polymer/polymer/blob/master/src/lib/bind/accessors.html#L214-216) initializes `inst.__data__`. Its call chain is [`_marshalInstanceEffects`](https://github.com/Polymer/polymer/blob/master/src/standard/effectBuilder.html#L241-244), `_initFeatures`.

[`_propertySet`](https://github.com/Polymer/polymer/blob/master/src/lib/bind/accessors.html#L50) calls `this.__data__[property]`, but `this.__data__` is undefined. Its call chain is [`setter`](https://github.com/Polymer/polymer/blob/master/src/lib/bind/accessors.html#L151-153), [`_marshalIdNodes`](https://github.com/Polymer/polymer/blob/master/src/standard/annotations.html#L227-234), [`_marshalAnnotationReferences`](https://github.com/Polymer/polymer/blob/master/src/standard/annotations.html#L200-206), `_initFeatures`.

[`_initFeatures`](https://github.com/Polymer/polymer/blob/master/polymer.html#L61-88) is:

``` javascript
    _initFeatures: function() {
      // ...
      // concretize template references
      this._marshalAnnotationReferences();
      // ...
      // concretize effects on instance
      this._marshalInstanceEffects();
      // ...
    },
```

Which does the two in the wrong order.  I'm doubting my diagnosis though, because this should cause an error on every element creation, not just my `document.createElement` call.

**Comment by jyasskin** [comment]
It looks like this comes from using `{{$.whatever}}` inside the template (due to upgrading from 0.5). It'd be nice if Polymer would give an error pointing at that bad binding instead of failing deep inside its guts.

**Comment by MetaMemoryT** [comment]
:+1:

**Comment by TimvdLippe** [comment]
Polymer 2 silently processed it without errors now, which I think is the expected behavior: http://jsbin.com/gifebiveso/edit?html,console,output Therefore I am closing this issue.
