### ISSUE TITLE
Uncaught TypeError When splicing an array into emptiness

### ISSUE THREAD

**Issue by andrepl** [Polymer/polymer#1714]
This appears to happen when the last element of an array is spliced out using the array manipulation helper 'splice'.

    Uncaught TypeError: Cannot read property '0' of null
        Polymer._detachRow @ polymer.html:3425
        (anonymous function) @ polymer.html:3409
        Polymer._applySplicesArraySort @ polymer.html:3407
        Polymer._render @ polymer.html:3278
        Polymer.Templatizer._flushTemplates @ polymer.html:2900
        Polymer.Debounce.Debouncer.complete @ polymer.html:847
        atEndOfMicrotask @ polymer.html:808

**Comment by kevinpschaaf** [comment]
I'm having trouble reproducing.  Could you try modifying this jsBin to cause the problem you're seeing?  Thanks!

http://jsbin.com/yeqapupuza/2/edit

**Comment by andrepl** [comment]
Turns out it's related to nested repeats and removing the parent item when its list of children is empty, so it's a bit more complicated to reproduce, but this appears to do it.

http://jsbin.com/hukoponuna/2/edit?html,console,output

**Comment by kevinpschaaf** [comment]
Perfect, thanks for the repro.

I confirmed this issue will be solved by the fix in https://github.com/Polymer/polymer/pull/1629, which should be merged shortly.

Here is your jsbin using that branch, for confirmation:
http://jsbin.com/tikayu/2/edit
