### ISSUE TITLE
core-list 0.5 demo, selection does not work on chrome 43

### ISSUE THREAD

**Issue by lem38** [Polymer/polymer#1718]
Have an issue with item selection in core-list in my application on chrome 43 (work in chrome 42).
Check core-list demo, same issue.

**Comment by levy5674** [comment]
This affects my application as well.  Any news?

**Comment by lem38** [comment]
No news. Work on opera.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
