### ISSUE TITLE
[1.0.2] '$' is undefined when 'created' is being called 

### ISSUE THREAD

**Issue by dzhioev** [Polymer/polymer#1728]
See http://dzhioev.net:8080/dollar_in_created.html, which is slightly modified example from [primer](https://github.com/Polymer/polymer/blob/master/PRIMER.md#node-marshaling).
On Chrome 42.0.2311.153 (Official Build) (64-bit) I get
> Uncaught TypeError: Cannot read property 'name' of undefined

in dollar_in_created.html:25.

**Comment by kevinpschaaf** [comment]
The callback here should be `ready`.  As noted, at `created` time the nodes are not yet marshaled.
