### ISSUE TITLE
draggable=true problem

### ISSUE THREAD

**Issue by daiying-zhang** [Polymer/polymer#1729]
element with attribute `darggable=“true”`, but everytime i want to drag it , i must click or double click it first. If i don’t click(or double click) it , it can’t drag it. it works fine with OSX 10.10 Safari

**Comment by chalkyjoe** [comment]
Having the same issue, although it seems to be much more temperamental than the case described here. Only around 1 out of 3-4 attempts to drag items works. This applies to any Polymer element I try to use it on.

**Comment by daiying-zhang** [comment]
Maybe is something about the `focus`.
