### ISSUE TITLE
Paper-tabs in Flexbox

### ISSUE THREAD

**Issue by Dyljyn** [Polymer/polymer#1730]
When using paper-tabs (Polymer 1.0) inside a flexbox without a specific width, they disappear in IE (10 as well as 11).

```html
<div class="horizontal layout center">

  <div class="flex">This is flex</div>

  <paper-tabs>
    <paper-tab>Paper</paper-tab>
    <paper-tab>Tabs</paper-tab>
  </paper-tabs>

</div>
```

Any solution as I guess I should be able to use it this way (I'm very new to Polymer).

**Comment by 19Gerhard85** [comment]
@Dyljyn 
Did you tried the universal CSS fix for IE?
```css
zoom: 1;
```

**Comment by tjsavage** [comment]
auto-moving this issue to PolymerElements/paper-tabs#29 and closing this one
