### ISSUE TITLE
Polymer.Base.splice and dom-repeat

### ISSUE THREAD

**Issue by cphillips** [Polymer/polymer#1733]
See wf-list line 46 for the non-working code and work around for this possible bug

http://plnkr.co/edit/JbKfgS74X7JvtZeA4wCv?p=preview

**Comment by kevinpschaaf** [comment]
Should be fixed in: https://github.com/Polymer/polymer/pull/1739

Verified in your use case here:
http://plnkr.co/edit/oz9rIB7sos0VToAjqr3A?p=preview
