### ISSUE TITLE
Gesture event bubbles are overwriting properties on elements

### ISSUE THREAD

**Issue by birkir** [Polymer/polymer#1736]
Consider this.

``` html
<template is="dom-bind" id="app">
  <iron-pages selected="{{route}}" attr-for-selected="data-route">
    <section data-route="foo">
      <div on-tap="changeRouteToBar">Goto bar</div>
    </section>
    <section data-route="bar">bar</section>
  </iron-pages>
</template>
```

``` javascript
var app = document.querySelector('#app');
app.route = 'foo';
app.changeRouteToBar = function (e) {
  app.route = 'bar';
}
```

Tapping the button will fire two events, one that changes the `app.route` to `bar` then another Gesture event that changes it back to `foo`.

My workaround for this was wrapping it with setTimeout, which need's to be fixed. IDK what's causing this, but it seems to be Gesture that's firing on-click event from the `iron-pages` element.

``` javascript
var app = document.querySelector('#app');
app.route = 'foo';
app.changeRouteToBar = function (e) {
  setTimeout(function () {
    app.route = 'bar';
  }, 1);
}
```

**Comment by TimvdLippe** [comment]
This appears to be fixed in Polymer 2: http://jsbin.com/tukofug/edit?html,console,output
