### ISSUE TITLE
`attached` handler executed in wrong order in chrome browser.

### ISSUE THREAD

**Issue by markovuksanovic** [Polymer/polymer#1743]

**Comment by markovuksanovic** [comment]
Check out this commit (https://github.com/markovuksanovic/polymer/commit/86f026e9945d18f11497eb7ae53790ce1b81fdba) for unit test to reproduce

**Comment by JamesMilnerUK** [comment]
Is this related this this issue? https://github.com/Polymer/polymer/issues/1699

**Comment by markovuksanovic** [comment]
Yes, I believe it is. Thanks for the pointer!

**Comment by JamesMilnerUK** [comment]
you can emulate domReady from 0.5 using this.asyc . A bit of a hack but it works!

**Comment by kevinpschaaf** [comment]
Closing, per the comments above.  Tracking issue for the "distributed children changed" feature here: https://github.com/Polymer/polymer/issues/1773, which will be the proper solution for users to rely on.
