### ISSUE TITLE
paper-toolbar [title] conflicts with HTML [title]

### ISSUE THREAD

**Issue by Imskull** [Polymer/polymer#1745]
```
<paper-toolbar>
  <paper-icon-button title="whatever"></paper-icon-button>
</paper-toolbar>
```
the HTML title conflicts with the style in `paper-toolbar` : 
```
    .toolbar-tools > ::content [title] ...
```
it causes `paper-icon-button` has unwanted style, like `flex: 1`.

**Comment by andreleblanc-wf** [comment]
+1 the 'title' attribute appears to be the only way to get a tooltip on a button inside a toolbar, but it also causes a bunch of unwanted styles to be added.  IMO the toolbar should look for a different attribute, 'title' is already taken.

**Comment by kevinpschaaf** [comment]
This is the Polymer core library issue tracker.  Element issues should be filed under the repo for the specific element in question.

**Comment by andrepl** [comment]
This has been fixed: https://github.com/PolymerElements/paper-toolbar/commit/cca6996a203585ac8653548d8cf89444372bbb7b
