### ISSUE TITLE
[1.0.3]Cannot start up after upgrade

### ISSUE THREAD

**Issue by Imskull** [Polymer/polymer#1754]
After I updated Polymer from 1.0.0 to 1.0.3 via `bower update` , my project and polymer demo(eg. paper-fab/demo/index.html) all get an error:
```
Uncaught TypeError: Cannot read property '_addFeature' of undefined | polymer-mini.html:1054
```

**Comment by Imskull** [comment]
When I rolled back to 1.0.2, everything is right
```
  "dependencies": {
    "polymer": "Polymer/polymer#1.0.2",
    "iron-elements": "polymerelements/iron-elements#^1.0.0",
    "paper-elements": "polymerelements/paper-elements#^1.0.0"
  }
```

**Comment by zishanj** [comment]
Instead of using `polymer-mini.html` try using full version `polymer.html` and see if it works.

**Comment by Imskull** [comment]
@zishanj `polymer-mini.html` is imported by `polymer.html` not by me.

Just re-tried a moment ago, still got same error. does anybody succeed upgrade to 1.0.3?

**Comment by azakus** [comment]
I can't repro this. Can you run `bower cache clean`, remove the directory, and reinstall your components?

**Comment by Imskull** [comment]
Thanks @azakus , `bower cache clean` works amazing.
