### ISSUE TITLE
PolymerElement enhancement

### ISSUE THREAD

**Issue by zishanj** [Polymer/polymer#1755]
I have seen that PolymerElements doesn't fully support `direction: rtl`. For example, `paper-radio-button`, `paper-toggle-button` does right aligned but the ripple effect doesn't place over the item correctly.

**Comment by ronlobo** [comment]
Thank you for reporting, full rtl support would be great!

**Comment by kevinpschaaf** [comment]
Thanks for the suggestion.  This issue tracker is for the Polymer core library, not elements built with it.  We'll get this moved to an appropriate spot.

**Comment by tjsavage** [comment]
We're looking at improving RTL support on an element-by-element basis. If you're running into RTL issues the best thing to do will be to file an issue directly on the element that you're having problems with. Thanks!
