### ISSUE TITLE
Element properties set before the component is initialised should work

### ISSUE THREAD

**Issue by manolo** [Polymer/polymer#1756]
If we create an element and set some properties previously to being initialized, those properties should be applied after the component is initialised. This is useful for frameworks loading the component dynamically when they are used (for instance in vaadin gwt-polymer).

In this example the 'menu' icon is never shown because the import takes some milliseconds.

```
    var link = document.createElement('link');
    link.setAttribute('rel', 'import');
    link.setAttribute('href', 'bower_components/iron-icons/iron-icons.html');

    var icon = document.createElement('iron-icon');
    icon.icon = 'menu';

    document.head.appendChild(link);
    document.body.appendChild(icon);
```

Note, that if you set the 'menu' icon as an attribute, it is considered when the component is initialised, hence with properties should be the same.

**Comment by IntranetFactory** [comment]
We use a lot of dynamically loaded components. We load them via `importHref(href, onload, onerror)` (https://www.polymer-project.org/1.0/docs/devguide/utility-functions.html) and initialize them in the onload callback. Works for far well in all browsers.

**Comment by sjmiles** [comment]
This is not supported at the moment for properties, only for attributes. I've marked it for consideration as an enhancement.

**Comment by cwayfinder** [comment]
@sjmiles , what do you mean about attributes?

The following example doesn't work:
```
    var link = document.createElement('link');
    link.setAttribute('rel', 'import');
    link.setAttribute('href', 'bower_components/iron-icons/iron-icons.html');

    var icon = document.createElement('iron-icon');
    icon.setAttribute('icon', 'menu');

    document.head.appendChild(link);
    document.body.appendChild(icon);
```

**Comment by sjmiles** [comment]
@cwayfinder: unfortunately, your problem is due to a flaw in `iron-icons` that creates a race-condition. I created an issue ticket here: https://github.com/PolymerElements/iron-icons/issues/18

In general however, attributes *do* persist across upgrades. For example, the following works:

```js
   var link = document.createElement('link');
   link.setAttribute('rel', 'import');
   link.setAttribute('href', 'paper-button/paper-button.html');

   var button = document.createElement('paper-button');
   button.textContent = 'Button';
   button.setAttribute('raised', '');

   document.head.appendChild(link);
   document.body.appendChild(button);      
```

**Comment by Artur-** [comment]
If you happen to do 
```
var link = document.createElement('link');
link.setAttribute('rel', 'import');
link.setAttribute('href', 'bower_components/polymer/polymer.html');
document.head.appendChild(link);

link = document.createElement('link');
link.setAttribute('rel', 'import');
link.setAttribute('href', 'bower_components/paper-slider/paper-slider.html');

var slider = document.createElement('paper-slider');
slider.step=2;

document.head.appendChild(link);
document.body.appendChild(slider);
```

You will end up with a slider with broken drag functionality because the ```step``` property will not exist in the slider at all (```_applyConfig``` only initializes properties for which ```this[n] === undefined```, which is not the case for ```n='step'``` here). The lack of the step property, combined with Polymer not firing events to observers if one parameter value is undefined, causes ```_updateKnob``` never to be called in paper-slider. 

The visible end result is that slider works ok, except that after dragging the handle, it will be returned to its previous position.

**Comment by manolo** [comment]
Hi @blasten This is the issue I told about in the polymerday.

**Comment by manolo** [comment]
This issue seems not happening any more. I guess it was fixed in https://github.com/Polymer/polymer/commit/ecd9b0902d6753d9f1aff2d02ff408796d37ab3c

**Comment by TimvdLippe** [comment]
Yes it has been fixed :tada: http://jsbin.com/fizanuvuwe/edit?html,console,output
