### ISSUE TITLE
Feature Request - Change log

### ISSUE THREAD

**Issue by zmoshansky** [Polymer/polymer#1762]
Maybe I missed it, but I can't seem to find a change log anywhere. This would be super helpful as so many bugs are getting worked out in the first few minor releases.

**Comment by ronlobo** [comment]
:+1:

**Comment by vsimonian** [comment]
Release notes are available at https://www.polymer-project.org/1.0/docs/release-notes.html

**Comment by zmoshansky** [comment]
@vsimonian Thanks for linking that, I have found the release-notes super helpful. Is there an equivalent for minor releases v1.0.x?

**Comment by vsimonian** [comment]
@zmoshansky For minor releases, there's not much. However, the [release details on GitHub](https://github.com/Polymer/polymer/releases) *may* mention why the minor version was incremented.

However, admittedly this is fairly fragmented and inconsistent, [especially](https://github.com/PolymerElements/iron-ajax/releases) [when](https://github.com/PolymerElements/paper-item/releases) [you](https://github.com/PolymerElements/paper-drawer-panel/releases) [begin](https://github.com/PolymerElements/paper-styles/releases) [to](https://github.com/PolymerElements/iron-flex-layout/releases) [include](https://github.com/PolymerElements/iron-component-page/releases) [the](https://github.com/PolymerElements/paper-toolbar/releases) [element](https://github.com/PolymerElements/iron-selector/releases) [repositories](https://github.com/PolymerElements/iron-menu-behavior/releases).

I agree that it would be nice to have:

- Standardized changelogs
- A central point at which these could all be reviewed

The latter could be implemented by anyone using a script that pulls information off of GitHub, but the first is up to the authors and them alone.

It'd be nice to hear what the official stance on this is, or if this information already exists in some page I might have not found yet.

**Comment by arthurevans** [comment]
We should probably be delivering this, and we'll figure out how. 

Meanwhile, I've added 1.0.1 - 1.0.3 to the release notes:

https://www.polymer-project.org/1.0/docs/release-notes.html

**Comment by batista** [comment]
> We should probably be delivering this, and we'll figure out how.

@arthurevans, perhaps these guys might have provide some nice input:
* @olivierlacan from [olivierlacan/keep-a-changelog](https://github.com/olivierlacan/keep-a-changelog)
* @skywinder from [skywinder/github-changelog-generator](https://github.com/skywinder/github-changelog-generator)

**Comment by skywinder** [comment]
Yep, I will create a PR with change log, so you can review it :) Check #1829

BDW, since you are use custom labels in your repo - the change log will looks better after this issues will be resolved: https://github.com/skywinder/github-changelog-generator/issues/240 and https://github.com/skywinder/github-changelog-generator/issues/54

**Comment by skywinder** [comment]
Ok! Everything is fixed in `1.6.0` that I released minutes ago. You can check, how it works now in #1829 :wink:

**Comment by kevinpschaaf** [comment]
@azakus Can you see about integrating this into our release process?

**Comment by zmoshansky** [comment]
Thanks team! This is great!
