### ISSUE TITLE
1.0 Starterkit (modest changed) works better in FF than in Chrome (menu missing) (W7)

### ISSUE THREAD

**Issue by EckhardSchoenknecht** [Polymer/polymer#1763]
Hello World,
... from germany, new to github, sorry for all mistakes.

See screenshot below or try demo hier: sbiz.schoenknecht.biz
Changing some colors and menu points (routing) and the drawer on the right: Everthing works well under Ubuntu (Chrome & FF) but under W7 (64B) with latest Chrome the Hamburger menu on the right is missing. Really nice (in my case):

If you take the mouse and fumble on the right side of screen, you can acess the menu and pull it on screen. Sometimes you have to try more than once.

OK, same demo, second problem (or feature). This works well in Chrome, but in FF it`s strange:

Klicking once to a menu Point doesnt work. You have to cklick double (like Windows 3.11:-) to see some content matching the menu Point. That`s nice, but i fear not all customers will appreciate this feature.

Best regards
Eckhard
![sbizwithpolymer](https://cloud.githubusercontent.com/assets/12674973/8018161/4f1adf0c-0c0d-11e5-99d5-9f740c7b0191.jpg)

**Comment by kevinpschaaf** [comment]
Thanks for the issue!  This issue tracker is for the Polymer core library, not the starter kit or elements built with it. We'll get this moved to an appropriate spot.

**Comment by tjsavage** [comment]
This issue was moved to PolymerElements/polymer-starter-kit#192
