### ISSUE TITLE
How to create a polymer element from iron-ajax element response

### ISSUE THREAD

**Issue by ronlobo** [Polymer/polymer#1764]
Hey there,

I'm trying to create a new polymer element from an iron-ajax element response.

Is there any advise on this?

Thanks in advance!

**Comment by ronlobo** [comment]
edited title

**Comment by kevinpschaaf** [comment]
Rather than using AJAX, we'd recommend using `importHref` either from an element context (`this.importHref`) or on `Polymer.Base.importHref`; you can find the documentation here: http://polymer.github.io/polymer/
