### ISSUE TITLE
Request fullscreen polymer element

### ISSUE THREAD

**Issue by ronlobo** [Polymer/polymer#1765]
Hi,

Just want to file a feature request for a 'request fullscreen' polymer element.

Might make sense if a polymer web app makes use of platinum-sw element.

Thoughts?

**Comment by kevinpschaaf** [comment]
This issue tracker is for the Polymer core library itself.  We'll get this moved to a more appropriate tracker, like `PolymerElements/iron-elements`.

**Comment by tjsavage** [comment]
This issue was moved to PolymerElements/iron-elements#14
