### ISSUE TITLE
Shopping card polymer element

### ISSUE THREAD

**Issue by ronlobo** [Polymer/polymer#1766]
Hey there,

Any plans on implementing the shopping card element which can be found at https://elements.polymer-project.org/ for polymer?

**Comment by kevinpschaaf** [comment]
The Polymer element catalog is built in Polymer 1.0 and is open source, located here: https://github.com/Polymer/polymer-element-catalog

All of the custom elements created specific to the app can be found here, which you might be able to port to your app: https://github.com/Polymer/polymer-element-catalog/tree/master/app/elements
