### ISSUE TITLE
official element-table bower package

### ISSUE THREAD

**Issue by MetaMemoryT** [Polymer/polymer#1767]
It would be nice to have an element that implements this spec:

http://www.google.com/design/spec/components/data-tables.html

Some new work appears here:
https://github.com/Polymer/polymer-element-catalog/tree/master/app/elements/element-table

Another option is:

vaadin-components https://github.com/vaadin/components/blob/master/vaadin-components-package/bower.json  (which is updated to 1.0). demo: http://vaadin.github.io/components-examples/v-grid/datasources.html

not yet updated to 1.0:

https://github.com/stevenrskelton/sortable-table
https://github.com/liuwenchao/aha-table
https://github.com/handsontable/hot-table

It would be nice to have a polymer project maintained element.

related:

https://github.com/Polymer/polymer/issues/1056

**Comment by horochovec** [comment]
I agree, and would like to invite those interested in participating in a development to share with the community.

**Comment by SmokyBob** [comment]
:+1: for a paper-data-table element, but I think the issue should be filed in the [paper-elements repo] (https://github.com/PolymerElements/paper-elements/issues)

**Comment by vsimonian** [comment]
+1 @SmokyBob 

To the `paper-elements` repo!

*batcave music*

**Comment by tjsavage** [comment]
Added a `paper-data-table` to the README roadmap. This is a pretty complex element so will be pretty far down the roadmap, but it's certainly under consideration.

**Comment by supermuka** [comment]
There is a time limit for an official data table? 3 months, 6 months or when people have time only?

**Comment by tjsavage** [comment]
Given the quality of components out there already like [v-grid](https://github.com/vaadin/vaadin-grid) and [paper-datatable](https://github.com/David-Mulder/paper-datatable), we don't have a timeline to release an 'official datatable'.

**Comment by bturk** [comment]
I would note that paper-datatable is not really a solution here as it only works on one browser and has restrictive licensing.

**Comment by ruckc** [comment]
also paper-datatable doesn't work in current polymer versions... at least that I can figure out.

**Comment by NeilujD** [comment]
[This one](https://customelements.io/jay8t6/paper-datatable/) does. But still it has restrictive licensing.

**Comment by Gnesan** [comment]
I use vaadin-components with Polymer. I try add custom buttons in one of columns. The buttons render correctly, but they don't capture on-click event. I didn't something wrong or it is a bug?

**Comment by hzmnet** [comment]
need it even it is very simple by official.
