### ISSUE TITLE
Minor typo: Items attribute value omitted within the template demonstrating how to use dom-repeat's  observer and filter properties in HTML (Data Binding Helper Elements Section of Docs)

### ISSUE THREAD

**Issue by lozandier** [Polymer/polymer#1769]
There seems to be a minor error in the docs regarding using `dom-repeat`'s `observe` & `filter` attributes together to ensure nodes repeated are correctly being up-to-date to be correctly filtered using the type extension custom element.

```html
<template is="dom-repeat" items=""
    filter="isEngineer" observe="type manager.type">
```

`items` seemingly should have `{{employees}}` within it:

```html
<template is="dom-repeat" items="{{employees}}"
    filter="isEngineer" observe="type manager.type">
```
![img_1521](https://cloud.githubusercontent.com/assets/1223224/8022322/fbb81c0a-0c96-11e5-9ab1-41a759ef001c.PNG)

**Comment by arthurevans** [comment]
Fixed in previous docs push:

https://www.polymer-project.org/1.0/docs/devguide/templates.html#filtering-and-sorting-lists
