### ISSUE TITLE
Feature: Add distributed children changed callback/event

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#1773]
Due to timing differences resulting from the inability to polyfill the exact timing of parent/child lifecycle callbacks for native custom elements, Chrome and polyfilled browsers behave differently in attached timing between parent/children, leading users to search for a solution to know when parents can interact with their children.

In 0.5, we had a fig-leaf solution called domReady, which was called async after the element became attached, which avoided seeing the timing difference between parent/child attachment. We have avoided adding this back in 1.0 because it was incomplete: if an element needs to inspect its children, it shouldn't only do that once at startup, but any time its children change, since this could happen when the user appendChild's to the element directly (or via distribution).

The proper solution will be to provide a normalized callback when any light/distributed children change that users will be able to use in either case.

**Comment by sorvell** [comment]
Work on this issue is being done in: https://github.com/Polymer/polymer/tree/effective-children

**Comment by jab** [comment]
Hi Team Polymer,
Interested in following progress on this (and contributing if I can) but the https://github.com/Polymer/polymer/tree/effective-children branch linked to above is giving 404.
Also, is PolymerElements/iron-form#61 (which this is blocking) important enough to promote this from p1 to p0? On the grounds that the disable-submit-button-until-form-is-valid pattern is so common.
Thanks!

**Comment by sorvell** [comment]
Merged this awhile so closing. See https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#observe-nodes for documentation.
