### ISSUE TITLE
Minor typo: Docs do not explicitly state the naming conventions they need to use for their Web Components to not be an HTMLUnkownElement

### ISSUE THREAD

**Issue by lozandier** [Polymer/polymer#1774]
The relevant sections of the docs that describe registering an element ( [a particular quick tour section](https://www.polymer-project.org/1.0/docs/devguide/registering-elements.html#register-element) & [ a particular section in the developer docs](https://www.polymer-project.org/1.0/docs/start/quick-tour.html#register)) do not explicitly explain to newcomers unfamilar with the nuances of the Custom Element spec for whatever reason that the name of their components must have a dash in between one or more characters before & after the dash.

**Comment by arthurevans** [comment]
This issue was moved to Polymer/docs#1158
