### ISSUE TITLE
Nuances involving async operations & the use of Polymer.dom.flush() seemingly benefits having a code snippet provided (DOM API Docs) 

### ISSUE THREAD

**Issue by lozandier** [Polymer/polymer#1775]
Given the unconventional (non-standard) way that insert, append, & remove operations are transacted lazily, it seems in the best interest of developers reading up on Polymer to have a code snippet demonstrating the correct usage of `Polymer.dom.flush()` w/ such operations.

This is particularly true in the contexts of having to use `Polymer.dom.flush()` & `window.getComputedStyle`, assuming the latter was in fact the method referred by the `getComputedStyle` reference in the [documentation](https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#dom-api).

**Comment by kevinpschaaf** [comment]
Maybe in the "async operations" box we could add a little code snippit?

**Comment by arthurevans** [comment]
This issue was moved to Polymer/docs#1159
