### ISSUE TITLE
property initialization/declaration order arbitrarily throws errors in computed value definitions using `this`

### ISSUE THREAD

**Issue by m4b** [Polymer/polymer#1776]
## Issue

I've noticed that the order of declaration for polymer properties seems to matter in an arbitrary manner when a **computed property** uses another property (like an array) using `this` in the function definition, instead of passed as a parameter.

This is perhaps bad practice (I don't see it explicitly proscribed anywhere in the docs (yet)), etc., but it's a nasty gotcha; it might be a good idea to just throw an error, if possible, whenever a property is used not via a parameter.

For example:
````javascript
    <dom-module id="init-good">
        <template>
          <style>
          </style>
        </template>
        <script>
          Polymer({
            is: "init-good",
            properties: {
              _title: {
                type: String,
                computed: '_getTitle(_selected)'
              },
              _array: {
                type: Array,
                value: function(){
                  return ["one", "two", "three"];
                }
              },
              _selected: {
                type: Number,
                value: 0,
              }
            },
            _getTitle: function(selected){
              return this._array[selected];
            },
            ready: function(){
              console.log("ready: ", this._array, this._selected, this._title);
            }
          });
        </script>
    </dom-module>
````

`<init-good>` runs fine.  However, if the declaration positions of `_array` and `_selected` are switched, then we get "Uncaught TypeError: Cannot read property '0' of undefinedPolymer._getTitle", i.e.:

````javascript
            properties: {
              _title: {
                type: String,
                computed: '_getTitle(_selected)'
              },
              _selected: {
                type: Number,
                value: 0,
              }
             },
              _array: {
                type: Array,
                value: function(){
                  return ["one", "two", "three"];
                }
              }
````
The "good" order of `_array` and `_selected`, compared to the error-producing order seems arbitrary, no matter which way you look at it (whether the properties are initialized from top to bottom, or bottom to top).

Clearly `_title` needs `_selected` and `_array`, but neither `_selected` or `_array` needs anything.

Hence if initialization occurs from the top, then switching `_selected` with `_array` should have no effect, and in *both* cases it should throw an error.  But if initialization occurs from the bottom, then switching `_selected` and `_array` should both *not* throw an error, since `_getTitle` hasn't been initialized yet.

Due to the arbitrariness, if the user accidentally writes or amends a computed definition using `this` instead of passing another property as a parameter, it will sometimes work, and sometimes not work.  Hence the suggestion to throw an error always.  If it's bad practice, and has strange declaration order problems, then it should probably be discouraged as much as possible by refusing to run at all.

## Steps to Reproduce

I can reproduce this on Linux (firefox and chrome), and OSX (on firefox, chrome and safari).

1. Put the above `<init-good>` dom module into a project, import it, and create the element.
2. Note no error occurs.
3. Switch the declaration order of `_array` and `_selected`, and note the undefined error coming from `_getTitle`
4. Various permutations show that most orders throw an error, except when `_array` is at the "top" (the first declared property) of the 3 property declarations.

**Comment by kevinpschaaf** [comment]
Computed properties should declare _all_ their dependencies to avoid being called with `undefined`.  Note that `_getTitle` references both `_selected` and `_array`, so it should declare both as dependencies, i.e. 

```js
            properties: {
              ...
              _title: {
                type: String,
                computed: '_getTitle(_array, _selected)'
              },
              ...
            },

            ...

            _getTitle: function(array, selected){
              return array[selected];
            },

```

This behavior of not calling computed functions until all dependences are defined is discussed [here](https://www.polymer-project.org/1.0/docs/devguide/properties.html#computed-properties):

>The computing function is not invoked until once all dependent properties are defined (!== undefined). So each dependent properties should have a default value defined in properties (or otherwise be initialized to a non-undefined value) to ensure the property is computed.

I will keep this issue open and assigned to our docs lead @arthurevans to make sure the nuance about needing to declare _all_ dependent properties is clear.

Also (pro-tip), in order for `_getTitle` to be re-computed when the array is mutated (e.g. `splice`, etc.), observe `_array.*` using a [deep path observer](https://www.polymer-project.org/1.0/docs/devguide/properties.html#deep-observation):

```js
            properties: {
              ...
              _title: {
                type: String,
                computed: '_getTitle(_array.*, _selected)'
              },
              ...
            },

            ...

            _getTitle: function(change, selected){
              return change.base[selected];
            },

```

**Comment by m4b** [comment]
@kevinpschaaf thanks for the response.  I'm aware the dependencies need to be declared, I was more worried about the declaration order arbitrarily throwing errors if a property is referenced with `this`.  Yes, it shouldn't be done, but it's a nasty shock for the reasons I outlined above.  Adding a note in the documentation should be a fair warning, at the very least.

So, while not a computed property per-say, a similar issue occurs with an observer (which I don't believe declare their dependencies?).

Correct me if I'm wrong, but observer properties are allowed to perform arbitrary work in the function definition using `this`, correct?

For example, the following module runs fine, but if the declaration order of `_array` and `_selected` are switched, it will throw errors.

````html
<dom-module id="init-observer">
  <template>
    <style>
    </style>
    <paper-button on-tap="_change">tap me</paper-button>
    <iron-pages selected="[[_selected]]">
      <template is="dom-repeat" items="[[_array]]">
        <h1>[[item]]</h1>
      </template>
    </iron-pages>
  </template>
  <script>
    Polymer({
      is: "init-observer",
      properties: {
        _array: {
          type: Array,
          value: function() {
            return ["one", "two", "three"];
          }
        },
        _selected: {
          type: Number,
          value: 0,
          observer: '_selectedChanged'
        },
        _title: {
          type: String,
          computed: '_getTitle(_selected, _array)'
        },
      },
      _selectedChanged: function(selected){
        console.log("_selectedChanged selected: ", selected);
        console.log("_selectedChanged array: ", this._array[selected]);
      },
      _change: function(e) {
        this._selected = (this._selected + 1) % 3;
      },
      _getTitle: function(selected, array) {
        return array[selected];
      },
      ready: function() {
        console.log("ready: ", this._array, this._selected, this._title);
      }
    });
  </script>
</dom-module>
````

What I take away from this is that declaration order *is* important, at least for observers, and a note should be made somewhere to avoid surprises like the above.

**Comment by arthurevans** [comment]
This issue was moved to Polymer/docs#1156

**Comment by kevinpschaaf** [comment]
Rather than "saying order is important" (which would be bad, since you don't have control over the order the user _sets_ properties on your element), I would just say that "declaring dependencies is important," since that's how you get a guarantee from the system not to call the observer/computed function until all dependencies have been defined (or have received their default `value`).

Note that the `observer` field in `properties` is short-hand for defining an observer with only one dependency.  There are also [multiple-property observers](https://www.polymer-project.org/1.0/docs/devguide/properties.html#multi-property-observers) which you should use if your observer depends on other members of `this`.

**Comment by m4b** [comment]
My apologies, I didn't realize the observer function was sugar for multiple property observers (didn't even realize there were multiple property observers).

Maybe to prevent impatient people from making similar mistakes, have a big bold "Do Not Use This" in the sections on property observers and computed functions?
