### ISSUE TITLE
Youtube-Upload documentation says one minute.

### ISSUE THREAD

**Issue by GanadiniAkshay** [Polymer/polymer#1777]
The google-youtube-upload component's documentation on the polymer-project website says "one minute".

**Comment by ebidel** [comment]
Page?

**Comment by GanadiniAkshay** [comment]
https://elements.polymer-project.org/elements/google-youtube-upload

**Comment by kevinpschaaf** [comment]
This issue tracker is for the Polymer core library, not elements built with it. We'll get this moved to an appropriate spot.

**Comment by GanadiniAkshay** [comment]
Sorry didn't notice.

**Comment by tjsavage** [comment]
This is interesting - I think this might be an issue with hydrolysis. Moving to that repo.

**Comment by tjsavage** [comment]
This issue was moved to Polymer/hydrolysis#132
