### ISSUE TITLE
Is there a list of Polymer 1.0 elements in the documentations? as it used to be 0.5!

### ISSUE THREAD

**Issue by mehany** [Polymer/polymer#1782]
I have been looking for a list of all the existing elements for Polymer 1.0 but I can't find it. Docs for 0.5 is different than Docs for 1.0. I may be about to write an element that already exists! Can someone post a link that lists all existing Polymer 1.0 elements?

**Comment by vsimonian** [comment]
I think what you're looking for is https://elements.polymer-project.org/

**Comment by ebidel** [comment]
Yep, the catalog is linked to from the Polymer site. We're missing docs on some elements but that's where you'll find 1.0 stuff now.
