### ISSUE TITLE
webcomponents.js trying to call polymer.html and getting a 404 error

### ISSUE THREAD

**Issue by MrPhilbert** [Polymer/polymer#1783]
Trying out polymer 1.0.3 via bower.
When I link to "bower_components/webcomponentsjs/webcomponents.js", I get a 404 error for polymer.html.
This is the path it's looking for: /bower_components/webcomponentsjs/'%20+%20'components/polymer/polymer.html. 
This appears to be coming from line 7089 and an install polymer warning function and this link:
<link rel="import" href="' + 'components/polymer/polymer.html">

I changed it to "<link rel="import" href="../polymer/polymer.html">", the 404 goes away and polymer is loaded correctly.

I don't think this is Bower specific as I believe the directories are separate regardless.
FYI, I am on windows 7 

Thanks

**Comment by azakus** [comment]
No, that is just an error message telling you to put `webcomponents.js` before an import for polymer.

**Comment by MrPhilbert** [comment]
Weird how a function designed to output an error message would generate a link instead.
The 404 message was in Chrome/source and showed the link as above.

**Comment by MrPhilbert** [comment]
Oh, I didn't paste the change I made to the link in the installPolymerWarning function:
<link rel="import" href="../polymer/polymer.html">
Sorry

**Comment by MrPhilbert** [comment]
"<link rel="import" href="../polymer/polymer.html">"

**Comment by MrPhilbert** [comment]
'<link rel="import" href="../polymer/polymer.html">'

**Comment by MrPhilbert** [comment]
`<link rel="import" href="../polymer/polymer.html">`

**Comment by TimvdLippe** [comment]
I am unable to reproduce this issue. Please reopen this issue if you can supply a JSBin which shows what is going wrong.
