### ISSUE TITLE
Computed binding can't handle comma in literal string

### ISSUE THREAD

**Issue by jyasskin** [Polymer/polymer#1784]
See http://plnkr.co/edit/G8hEnW0qwlB88ljO5V4S?p=preview, whose `dom-element.html` is below. If you add a comma in one of the arguments to `concat`, the rendering breaks.

```html
<link rel="import"
      href="http://www.polymer-project.org/1.0/samples/components/polymer/polymer.html">

<dom-module id="dom-element">
  <template>
    <p>{{concat('I am a DOM element and this is my ', field, ' DOM!')}}</p>
  </template>
</dom-module>

<script>
  Polymer({
    is: "dom-element",
    
    properties: {
      field: {
        type: String,
        value: 'local',
      },
    },
    
    concat: function() {
      return Array.prototype.join.call(arguments, '');
    },
  });
</script>
```

Amusingly, if you use `{{concat('I am a DOM element, ' and this is my ', field, ' DOM!')}}` as in http://plnkr.co/edit/TCFCC98q8utBvz7hg7oo?p=preview, it removes the character before the `,`, and recovers from there.

**Comment by arthurevans** [comment]
You can escape the comma with a backslash.

**Comment by kevinpschaaf** [comment]
@arthurevans Should make this issue into a docs issue to make sure the literal property support in computed functions is documented?

**Comment by jyasskin** [comment]
Could y'all double-check that this argument parsing is actually the user-facing interface you want? Making `function('some'text'in\,cluding'apostrophes x , 3)` pass the 2 arguments `["some'text'in,cluding'apostrophes ", 3]` is pretty surprising.

**Comment by MaKleSoft** [comment]
+1 for fixing this in the parser. Even if you document this prominently there will still be a lot of people stumbling across this. I know I did... In any case, it is certainly not the behaviour you would expect.

**Comment by bearfriend** [comment]
How about literal arrays? Is it possible to pass them in a computed binding?

**Comment by TimvdLippe** [comment]
This is fixed with #3017 as shown by http://jsbin.com/rihewoheno/edit?html,console,output

**Comment by sorvell** [comment]
Fixed, closing.

**Comment by tdesc** [comment]
[[translate("Tokyo\, New York\, London\, Moscow")]]

**Comment by yairopro** [comment]
Well it doesn't work when the literal string is placed in a computed property's function definition as [shown here](http://jsbin.com/bisugonodo/edit?html,console,output).
