### ISSUE TITLE
Feature request: Ability to NOT include HTML comments inside a template when stamping it

### ISSUE THREAD

**Issue by punzki** [Polymer/polymer#1785]
I sometimes need to write HTML comments (e.g., `<!-- foo -->`) inside my template as a form of documentation. But I don't want these to be stamped in the DOM, which bulks up the page, especially when repeated many times.

**Comment by zmoshansky** [comment]
@punzki, perhaps a tool like [Vulcanize](https://github.com/Polymer/vulcanize) with `--strip-comments` would be a good solution. I just tested using a polymer component and it removed the comments inside a template when stamped out.

**Comment by punzki** [comment]
@zmoshansky - That's a good idea. I guess you could classify removing comments as one of the typical steps before making code production ready, like minifying.

Still, I think it would be nice for comments to not be included at all when stamping occurs.

**Comment by TimvdLippe** [comment]
Given that minification is primarily an optimization step which is outside of the scope for Polymer. If you would like to minify these comments away, please use tools such as https://github.com/kangax/html-minifier
