### ISSUE TITLE
Too many property change notifications fired for a property if the property is defined by multiple behaviors

### ISSUE THREAD

**Issue by morethanreal** [Polymer/polymer#1791]
If an element implements `BehaviorA` and `BehaviorB` and both behaviors declare a `foo` property that is `notify:true`, the element will get two `foo-changed` events when the `foo` property is changed.

**Comment by gaurav21r** [comment]
@kevinpschaaf @sjmiles Any updates on this issue? Can the priority be bumped up? Its affecting a lot of elements. Especially the `value` property. Too many events are firing which leads to performance losses!

**Comment by mercmobily** [comment]
+1 on this with bonus jsbin! 

https://jsbin.com/vojexe/edit?html,console,output

And random people working around it:

https://github.com/vaadin/vaadin-combo-box/blob/29ec860e8dafc22848bf1d328f5f7ecac14c9a9e/vaadin-combo-box-behavior.html#L44

**Comment by jlramosr** [comment]
News about this??

I temporarily solve this problem creating a propery called _myStopPropagation_ and modifying it of this way:

`
<paper-input on-value-changed = "_optionChanged"</paper-input>

<script>
...
  properties: { 
    ... 
    myStopPropagation: { type: Boolean, value: false},
    ...
  } 
...
    _optionChanged(event, newValue) {
        // Pass twice here (due to Paper and Input Behaviour)
        if (!this.stopPropagation) {
          this.stopPropagation = true;
          return;
        }
        this.stopPropagation = false;
        // Over here only pass one time
        ...
    }
</script>



<
`

**Comment by jlramosr** [comment]
News about this??

I temporarily solve this problem creating a propery called myStopPropagation and modifying it of this way:

```
<paper-input on-value-changed = "_optionChanged"></paper-input>
```
```
properties: { 

  myStopPropagation: { 
    type: Boolean, 
    value: false
  }

}

_optionChanged(event, newValue) { 
  // Pass twice here (due to Paper and Input Behaviour) 
  if (!this.stopPropagation) { this.stopPropagation = true; return; } 
  this.myStopPropagation = false; 
  // Over here only pass one time ... 
} 

```

**Comment by TimvdLippe** [comment]
This has been fixed in Polymer 2: http://jsbin.com/nuxetoxozi/edit?html,console,output

**Comment by mercmobily** [comment]
It's a Polymer 2 world I guess! :D
