### ISSUE TITLE
boolean property is undefined if HTML attribute corresponding to property is not set

### ISSUE THREAD

**Issue by punzki** [Polymer/polymer#1794]
See: http://jsbin.com/xoruqa/1/edit?html,console,output

According to the documentation at https://www.polymer-project.org/1.0/docs/devguide/properties.html#attribute-deserialization:

> Boolean properties set based on the existence of the attribute: if the attribute exists at all, its value is true, regardless of its string-value (and the value is only false if the attribute does not exist).

Yet from the above jsbin, it is clearly being set us `undefined`. A workaround is to set a default value of `false` for the property, but this should not be required.

**Comment by kevinpschaaf** [comment]
We'll get the docs updated to reflect the current behavior, as it changed slightly prior to our 1.0 release.

Two points to clarify:

* The lack of an attribute will not result in deserialization, so a `Boolean` property will only get `false` if a default `value: false` was defined in `properties`.  Hence, this statement in the docs is technically no longer accurate:

   > and the value is only false if the attribute does not exist

   You can define `boolProp` like this to see the correct `console.log`:

   ```js
        boolProp: {
          type: Boolean, 
          value: false
        },
   ```

* There are no guarantees for ordering of when no-dependency inline functions like `{{compute()}}` are called, so you shouldn't expect values to have their configured values when it runs, unless you declare the actual dependencies you want to access, as in `{{computeMe(boolProp}}`.

@arthurevans Can you make sure the docs reflect this?  Thanks.

**Comment by punzki** [comment]
Thanks for the clarification. But I do think that in general, deserialization of Boolean properties can be quite confusing. As you say, "the lack of an attribute will not result in deserialization," but how else are developers supposed to declare that a property of the custom element should be `false`?

The only thing that will make the custom element behave logically is to always set a default value of `false` for a property. I'd try to see if there's a way to make this more clear in the docs.

**Comment by TimvdLippe** [comment]
@arthurevans I think we should move this to the docs, if it hasn't been addressed already?

**Comment by TimvdLippe** [comment]
This issue was moved to Polymer/docs#2405
