### ISSUE TITLE
Data binding with JavaScript no longer available in 1.0

### ISSUE THREAD

**Issue by arodic** [Polymer/polymer#1796]
In 0.5 there was a handy built-in function `this.bindProperty()` as well as `this.bind()` It appears that equivalent functions no longer exist in 1.0. Perhaps this functionality is provided in undocumented `Polymer.Bind` but without documentation it is hard to tell.

**Comment by zerodevx** [comment]
I think imperative data-binding is not supported in 1.0 per #1778

**Comment by arodic** [comment]
> we don't currently support this

According to @kevinpschaaf this is "currently" not supported. Perhaps it will be supported in the future?

**Comment by zerodevx** [comment]
Not sure... But given that data is bounded on registration, I'm experimenting with a (bit hackish) way to data bind imperatively by defining the prototype chain before registration on the fly. Will post results.

On 9 June 2015 15:53:42 GMT+08:00, AKI RODIC <notifications@github.com> wrote:
>> we don't currently support this
>
>According to @kevinpschaaf this is "currently" not supported. Perhaps
>it will be supported in the future?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Polymer/polymer/issues/1796#issuecomment-110265029

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JasonFitz** [comment]
Has there been any work on this? Our app hinges on the ability to bind properties to elements created dynamically.

**Comment by polpo** [comment]
We also use this heavily and would like to know if any work or decisions have been made on this.

**Comment by bedeoverend** [comment]
Would also love to see this implemented +1

**Comment by capira12** [comment]
Would also love to see this implemented +1

**Comment by saurshaz** [comment]
+1 
repeating @polpo  "We also use this heavily and would like to know if any work or decisions have been made on this."

**Comment by zerodevx** [comment]
I believe this feature is in the Polymer owners' radar and inside the dev timeline. For certain instances, a (somewhat hackish) workaround that I used to employ was this: https://github.com/Polymer/polymer/issues/2131#issuecomment-125119968. 

Later, I just made some workflow (and mindset) changes that for most times replaced the need for late binding completely. I'll suggest that, or waiting for an official (and true) late-binding API to be released.

**Comment by warpech** [comment]
+1

**Comment by warpech** [comment]
I also have a problem with this: I have two Polymer elements which ignore that they are bound to the same object: https://jsfiddle.net/warpech/g4xoqaff/2/

I know that this can be worked around by wrapping them in a single Polymer element, but can't have that workaround. I would like to use a JS API to bind them together.

**Comment by devinivy** [comment]
@warpech this is possible with a little extra glue– you need to keep track of which components share that object then `notifyPath()` on each of them when one of them changes it.  See the approach in [`yarn-state-behavior`](https://github.com/yarn-co/yarn-state-behavior).  And perhaps a better/simpler option in this case is to create a third element to house the shared object.  This third element could be included in all elements that need to bind to the object.

Also related to this discussion are the existing `linkPaths()` and `unlinkPaths()` methods: https://github.com/Polymer/polymer/blob/acdfc1e097dbe9c984aad72c4aba94463341e599/src/standard/notify-path.html#L333-L365

**Comment by kaste** [comment]
Can you take a look at #3456 (and its related PR #3460) and perhaps comment if that would fix your issue.

**Comment by TimvdLippe** [comment]
Closing per https://github.com/Polymer/polymer/pull/3460#issuecomment-320333064 This API shipped in Polymer 2.

**Comment by dman777** [comment]
👎   A little upset since 1.* is still being supported and this was skipped.

**Comment by dman777** [comment]
👎 What about Polymer 1.*? It is still being supported.
