### ISSUE TITLE
<template is=dom-if> fails to add rows to a table if they contain <content>

### ISSUE THREAD

**Issue by jyasskin** [Polymer/polymer#1800]
Demo at http://plnkr.co/edit/adwhKJcfSxiM3tjxU6JS?p=preview. 

```html
    <table>
      <template is="dom-if" if="{{hasSpan}}">
        <tr>
          <th>Header</th><td><content select="span"></content></td>
        </tr>
      </template>
    ...
```
never shows the row, but replacing the `<content>` with anything else makes it work.

**Comment by kevinpschaaf** [comment]
May be related to https://github.com/Polymer/polymer/issues/1631, will test after that fix.

**Comment by kevinpschaaf** [comment]
Will be fixed by https://github.com/Polymer/polymer/pull/1816

Confirmed fix in repro case here:
http://jsbin.com/nunavo/2/edit
