### ISSUE TITLE
Call render on the dom-repeat to refresh the sort/filter.

### ISSUE THREAD

**Issue by euclid1990** [Polymer/polymer#1801]
How to call `render()` manually from followings code:

```
<template id="resultList" is="dom-repeat" items="{{ schedules }}" filter="filterRoom" as="schedule" index-as="scheduleId">
...
</template>
```
I have a `filterRoom` function based outside model value !

Could anyone give the sample code to call render() function of template repeat !

I try `this.$.resultList.render()` but it not work :(

Thank you !

**Comment by kevinpschaaf** [comment]
Here's an example: http://jsbin.com/ziqiwe/1/edit

Maybe you can edit this to more closely match where you're having trouble?

**Comment by euclid1990** [comment]
@kevinpschaaf Thank you for supporting !
But I have another question, while google only have 3 members (I saw) for this Project, I only see about 3 engineers of google in this git !

**Comment by kevinpschaaf** [comment]
Your app looks great!  Thanks for sharing!

Our documentation is always improving.  If you can post any specific issues you had, we'll work on addressing them.

**Comment by clearmirror** [comment]
I did a bit change of the example code (http://jsbin.com/hewapofavo/1/edit?html,output) but it does not work as expected. Basically I removed the filter and whenever input text changes I push a new item into schedules. The render method extends the list but names of new items are missing.

**Comment by kyooriouskoala** [comment]
@clearmirror 
Long due answer. Anyhoo ... 
change: `this.schedules.push({name: 'Item A'});` 
to `this.push('schedules', {name: 'Item A'});` 
Doc: [Polymer array mutation](https://www.polymer-project.org/1.0/docs/devguide/model-data#array-mutation)
