### ISSUE TITLE
Attribute name starts with "on" is not allowed

### ISSUE THREAD

**Issue by pienikrz** [Polymer/polymer#1803]
I have dom module with attribute "on-tab-change". When I use it on my page it's work fine but when I use it in another dom-module the attribute disappear. Ex.

	<dom-module name="my-tabs">
		...
	</dom-module>
	<script>
		Polymer({
			is: 'my-tabs', 
			
			properties: {
			  onTabChange: String  
			}
		});
	</script>
	
	<dom-module name="my-module">
		<my-tabs on-tab-change="...."></my-tabs>
	</dom-module>
	<script>
		Polymer({
			is: 'my-module'
		});
	</script>

**Comment by kevinpschaaf** [comment]
In Polymer templates, attributes starting with `on-*` are reserved and interpreted as [annotated event listeners](https://www.polymer-project.org/1.0/docs/devguide/events.html#annotated-listeners).  The attributes are removed from elements in the template before stamping, and after stamping, event listeners are set up on the instances corresponding to the attribute name that call the function named in the attribute value.

So, for the _property API_ of your element, you'll need to choose property names that don't start with `on`.

**Comment by pienikrz** [comment]
Ok, thx for response. I couldn't find information about that in dev guide.
