### ISSUE TITLE
Unwrapped dom-if causes DOMException

### ISSUE THREAD

**Issue by Sleeckx** [Polymer/polymer#1804]
The following case throws a **DOMException: NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.**

http://jsbin.com/gujenocexo/2/edit?html,output

Wrapping the dom-if template in a ```div``` fixes the error.

Could this be related to #1631?

**Comment by sorvell** [comment]
There's a bug here, but the test case should define `x-inner` before `x-outer`. Doing so avoids the issue:

http://jsbin.com/gibewu/2/edit

**Comment by sorvell** [comment]
Fixed in branch, see: http://jsbin.com/haseju/2/edit
