### ISSUE TITLE
Does version 1.0 support recursion?

### ISSUE THREAD

**Issue by masaoliou** [Polymer/polymer#1806]
Version 0.5 allows us to recursively generate elements using **ref** syntax. Can this be done in version 1.0, and how?

**Comment by dhubler** [comment]
Same way as in 0.5

**Comment by vsimonian** [comment]
`ref` in repeating templates isn't currently supported. I'm not sure whether or not it's on the roadmap, though - that's a question worth asking, I think.

A theoretical code sample for anyone peeking into this issue:

```html
<template id="recursiveTemplate" is="dom-repeat" items="[[menuItems]]">
  <template is="dom-if" if="[[item.items]]">
    <div class="submenu">
      <header>[[item.name]]</header>
      <template is="dom-repeat" ref="recursiveTemplate"></template>
    </div>
  </template>
  <template is="dom-if" if="[[!item.items]]">
    <paper-item>[[item.name]]</paper-item>
  </template>
</template>
```

**Comment by kirilledelman** [comment]
This doesn't seem to work:

            <template is="dom-repeat" items="{{items}}" id="mindmap-row">

                <div id="{{item.id}}" on-click="rowClicked"></div>

                <template is="dom-if" if="{{item.children}}">

                    <iron-collapse>
                        <template is="dom-repeat" items="{{item.children}}" ref="mindmap-row"></template>
                    </iron-collapse>

                </template>

            </template>

My collapse section is always empty - template isn't referenced.

**Comment by vsimonian** [comment]
@kirilledelman If you're on 1.0, you're not doing anything wrong. There's currently no support for `ref` in templates.

**Comment by kirilledelman** [comment]
Oh I see. That's too bad, as it's a very useful feature. I'll have to rewrite using recursive elements instead.

**Comment by zikes** [comment]
You can include a component inside of itself: http://stackoverflow.com/questions/30468581/polymer-recursive-template-binding/30469213#30469213

**Comment by masaoliou** [comment]
Including a component inside of itself as zikes pointed out works for myself.

**Comment by vsimonian** [comment]
@zikes, now that's a creative solution! Never even occurred to me. :+1:

**Comment by robrez** [comment]
Did anyone get word if "ref" is going to be implemented?  Recursion-aside, it's nice to be able to "stamp" stuff out in a named template.

Maybe a custom element for any such case is going to be the recommend approach.

**Comment by robrez** [comment]
It looks like "ref" is officially on the radar...
See here: #1852
