### ISSUE TITLE
Polymer-micro throwing `Uncaught TypeError: prototype.registerCallback is not a function`

### ISSUE THREAD

**Issue by tigerhawkvok** [Polymer/polymer#1814]
On line 63:

`
polymer-micro.html:63 Uncaught TypeError: prototype.registerCallback is not a function
`

On Chrome Version 45.0.2421.0 dev-m (64-bit) / Windows

In the document `<head>`:

```html
    <script type="text/javascript" src="bower_components/webcomponentsjs/webcomponents.js"></script>
    <link rel="import" href="bower_components/polymer/polymer.html"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script type="text/javascript" src="js/purl.min.js"></script>
    <script type="text/javascript" src="js/xmlToJSON.min.js"></script>
    <script type="text/javascript" src="bower_components/js-base64/base64.min.js"></script>
    <script type="text/javascript" src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="bower_components/js-base64/base64.min.js"></script>
    <script type="text/javascript" src="bower_components/picturefill/dist/picturefill.min.js"></script>
    <script src="bower_components/imagelightbox/dist/imagelightbox.min.js"></script>
    <script src="bower_components/markdown/lib/markdown.js"></script>
    <script src="js/jquery.cookie.min.js"></script>
    <script type="text/javascript" src="js/c.min.js"></script>
    <!-- As of Polymer 1.0, all the stuff you want has to be imported
         individually -->

    <link rel="import" href="bower_components/paper-fab/paper-fab.html"/>
    <link rel="import" href="bower_components/paper-item/paper-item.html"/>
    <link rel="import" href="bower_components/paper-scroll-header-panel/paper-scroll-header-panel.html"/>
    <link rel="import" href="bower_components/paper-header-panel/paper-header-panel.html"/>
    <link rel="import" href="bower_components/paper-toolbar/paper-toolbar.html"/>
    <link rel="import" href="bower_components/paper-toggle-button/paper-toggle-button.html"/>
    <link rel="import" href="bower_components/paper-toast/paper-toast.html"/>
    <link rel="import" href="bower_components/paper-input/paper-input.html"/>
    <link rel="import" href="bower_components/paper-radio-group/paper-radio-group.html"/>
    <link rel="import" href="bower_components/paper-radio-button/paper-radio-button.html"/>
    <link rel="import" href="bower_components/paper-spinner/paper-spinner.html"/>
    <link rel="import" href="bower_components/paper-styles/paper-styles.html"/>
    <link rel="import" href="bower_components/paper-dialog/paper-dialog.html"/>
    <link rel="import" href="bower_components/paper-dialog-scrollable/paper-dialog-scrollable.html"/>
    <link rel="import" href="bower_components/paper-button/paper-button.html"/>
    <link rel="import" href="bower_components/paper-icon-button/paper-icon-button.html"/>
    <link rel="import" href="bower_components/iron-icons/iron-icons.html"/>
    <link rel="import" href="bower_components/iron-form/iron-form.html"/>
    <link rel="import" href="bower_components/iron-autogrow-textarea/iron-autogrow-textarea.html"/>
    <link rel="import" href="bower_components/iron-icons/image-icons.html"/>
    <link rel="import" href="bower_components/iron-icons/social-icons.html"/>
    <link rel="import" href="bower_components/iron-icons/communication-icons.html"/>
    <link rel="import" href="bower_components/gold-email-input/gold-email-input.html"/>
    <link rel="import" href="bower_components/gold-phone-input/gold-phone-input.html"/>
    <link rel="import" href="bower_components/gold-zip-input/gold-zip-input.html"/>
```

With Polymer reporting in `bower.json` it's version `1.0.3`.

**Comment by relicmelex** [comment]
Same problem... came along when I updated my polymer deps... super annoying:
```
    "webcomponentsjs": "~0.7.3",
    "es6-module-loader": "~0.17.0",
    "system.js": "~0.17.1",
    "polymer": "~1.0.3"
```

**Comment by kevinpschaaf** [comment]
This seems to work fine: http://jsbin.com/mawepa/edit?html,output

@azakus Can you investigate?

**Comment by azakus** [comment]
Can't repro this with @relicmelex's steps

Maybe try a `bower cache clean` and reinstall?

**Comment by relicmelex** [comment]
Ah, so didn't realize my dependancies were so far out of date when I did this update... was an ID-10-T error over here. I'm pretty sure I had polymer 0.5 elements and the 1.0 library at this point... sure this was my issue. Maybe there should be a 'throw' surrounding legacy formats?

**Comment by azakus** [comment]
That might be a reasonable request. Vulcanize will through on finding
`polymer-element`.

**Comment by ksteigerwald** [comment]
I am having this problem as well. I tried clearing my bower cache as @azakus recommend, no dice. I was following this tutorial to get started with polymer components:
http://code.tutsplus.com/tutorials/using-polymer-to-create-web-components--cms-20475

**Comment by sujkh85** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sujkh@naver.com 님께 보내신 메일 <Re: [polymer] Polymer-micro throwing `Uncaught TypeError: prototype.registerCallback is not a function` (#1814)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by MarkDurbin104** [comment]
the instructions in that article are a little out of date, you should use:
__bower init
bower install --save Polymer/polymer
bower install --save PolymerElements/iron-elements
bower install --save PolymerElements/paper-elements__

**Comment by HeathNaylor** [comment]
I am having this issue, installing the elements was not a fix.

**Comment by nailaandleeb** [comment]
having same issue n couldn't resolve by bower updating.

**Comment by forresto** [comment]
For what's it's worth, I had the same issue when I forgot to update one element from 0.5 → 1.0.

**Comment by azakus** [comment]
@forresto That's a good point. @HeathNaylor @nailaandleeb @relicmelex @tigerhawkvok , can you run vulcanize 1.10.3 on your project and see if it complains.

The error message should look something like this

    [Error: This version of vulcanize is not compatible with Polymer < 0.8. Please use vulcanize 0.7.x. File:

**Comment by jain6968** [comment]
Same issue for running a simple program.Uncaught TypeError: prototype.registerCallback is not a function.

Nothing is displayed on screen.

**Comment by jain6968** [comment]
I have simple code as below shown on polymer site but after loading in browser nothing is displayed. Also all the files are loaded in browser in resource section.

<!DOCTYPE html>
<html>
  <head>
    
    <script src="bower_components/webcomponentsjs/webcomponents.min.js"></script>
    
    <link rel="import" href="elements/my-element.html">
  </head>
  <body>
    
    <my-element></my-element>
  </body>
</html>

**Comment by sfanjoy** [comment]
For what its worth I encounter the same issue and can reproduce.
npm install -g bower
npm install -g vulcanize@0.7.10
(make new project with Chrome Dev Editor)
cd  newproject
bower init
bower install --save Polymer/polymer
create a simple element
vulcanize -o build.html index.html --csp

**Comment by jain6968** [comment]
Thanks! But I simply tried other examples. its working fine. Didn't had to use the vulcanize installation.
I had replaced the platform folder with new one.

**Comment by sfanjoy** [comment]
Not trying to beat a dead horse. Trying some other routes but wanted to get this out. Also if there is a different forum for this let me know. I am really interested in developing Chrome apps using Polymer.

New VM running Windows 7 (ran windows update)
Grew a beard
Installed latest Chrome
Installed Chrome Dev Editor
Installed Git 2.5.3 (allowed Git to be used from Windows shell)
Installed node 4.1.0 using msi from nodejs.org
Installed Bower using : npm install -g bower
Created Directory c:\OpenSource
Started Chrome Dev Editor
Create new project (choose c:\OpenSource directory)
Project Name: Polymerization
Project type: Chrome App using Polymer Paper objects
Got Dialog explainingCSP requirements
Right Clicked bower_components->Refactor for CSP
 Got another dialog with the following:
  Not Found Error: A requested file or directory could not be found
   at the time an operation was processed.
 (on 478 of 821)
Right click update bower_components (success)
 Right Clicked bower_components->Refactor for CSP
 Got dialog again with the above error.

**Comment by sethwklein** [comment]
I just solved this by...

1. looking in `bower_components` and noticing a bunch of `core-*` stuff,
1. searching the `bower.json` files of all the other things in `bower_components` until I found something that depended on a `core-*` thing,
1. basically manually following the dependency tree back up until I found something I'd installed directly,
1. deleting `bower_components` and running `bower cache clean`,
1. fixing it by `bower install username/element-name` rather than `bower install element-name`.

**Comment by akutamruta** [comment]
I don't see any core-* components in my bower_components. Tried cleaning up the dist and doing a full rebuild but still didn't work.

**Comment by jain6968** [comment]
There is this new release of Chrome Polymer editor where all the installation haziness is not required.
While creating the project also we just need to select the type and it automatically installs all the components.

**Comment by akutamruta** [comment]
I used Polymer Starter Kit to get the basic wiring and scripts ready and I refactored the code a bit the way I found it convenient and got the error while refactoring..

**Comment by sethwklein** [comment]
It looks like it might be worth noting that dependencies with names starting with `core-*` aren't the only things that can require Polymer < 1.0.

**Comment by azakus** [comment]
Closed due to age, please reopen if this is still a problem.

**Comment by raffaeu** [comment]
I just started with Polymer 1.2.0 from ground 0 and I get the same problem.

Uncaught TypeError: prototype.registerCallback is not a function
