### ISSUE TITLE
Clicking Demo button results in error

### ISSUE THREAD

**Issue by phub4r** [Polymer/polymer#1815]
**Problem**
Demo button does not work

**Reproduction scenario**
1. Goto page: https://www.polymer-project.org/0.5/docs/elements/core-tooltip.html
2.Click Demo button

**Result**
Error: Not Found
The requested URL /0.5/components/core-tooltip/demo.html was not found on this server.

**Comment by arthurevans** [comment]
Old issue, long fixed.
