### ISSUE TITLE
Dom-bind not working if parent is already attached

### ISSUE THREAD

**Issue by Sleeckx** [Polymer/polymer#1818]
Hello,

please consider the following test case. Clicking "**Add dom-bind directly**" for the first time, it will append the dom-bind template but not its bound children. Upon clicking it again, it adds the bound content as intended.

http://jsbin.com/weyobaqewo/6/edit?html,output

**Comment by kevinpschaaf** [comment]
Root caused to distribution reentrancy during attached.  Short-term solution is for `dom-bind` to address this specifically; @sorvell to open general issue to cover the reentrancy problem.
