### ISSUE TITLE
Computed bindings are not updated when using polymer's this.push to add elements

### ISSUE THREAD

**Issue by makrolabs** [Polymer/polymer#1822]
http://jsfiddle.net/3e3d8kzz/4/

In the example, the computed binding only updates when resetting the array using line 10-12 in the example.

**Comment by arthurevans** [comment]
This computed binding `selected$="{{computeInArray(selected, item)}}"` only recomputes when the property itself changes. To observe array changes, you can use `selected.*` or `selected.splices`:

http://jsfiddle.net/3e3d8kzz/1/

**Comment by makrolabs** [comment]
Can you please post an example? I think your jsfiddle url links to my example.

**Comment by arthurevans** [comment]
Sorry, not used to jsfiddle. Here it is:

http://jsfiddle.net/b4gdksu4/2/

I'm sure this could be more efficient, but it works. More information on observing this kind of change:

https://www.polymer-project.org/1.0/docs/devguide/properties.html#deep-observation

**Comment by makrolabs** [comment]
Thanks it works great!
