### ISSUE TITLE
Shim child selectors (>) for main document styles

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#1825]
The help users, it would be nice to have the shimmer convert `>` selectors to something that works well with shady dom.

The selector `#mainheader > paper-icon-button` no longer matches the light dom of the toolbar. This is because shady dom gives the composed tree:

```
<paper-toolbar id="mainheader">
     <paper-icon-button>
     <paper-icon-button>
   ...
```

This didn't work in the 0.5 polyfill either, but is a new gotcha/difference between shady and shadow.

**Comment by sorvell** [comment]
Yes, this is a limitation of the shady styling shim, which as you mentioned was also a limitation of 0.5 Shadow DOM polyfill styling shim.

We'll work on improving this but as a workaround you can use a descendant selector instead:

`#mainheader paper-icon-button`

The descendant selector is automatically scoped such that it will only match elements that are in the same scope. (Note, that is an improvement over Polymer 0.5's style shimming.)
