### ISSUE TITLE
The demo page of the iron-doc-viewer is blank & the doc page for iron-component-page is missing

### ISSUE THREAD

**Issue by lozandier** [Polymer/polymer#1826]
The demos demonstrating `iron-doc-viewer` is currently blank. Verified by @arthurevans being indeed the case for the element's demo page it seems fit to file this as a bug since no bug has been already filed for this problem. 

It seems warrantable for this to be fixed, as well as a demo page for `iron-component-page`.

**Comment by sorvell** [comment]
This is the issue tracker for the Polymer core library. We'll get this moved to an appropriate location.

**Comment by tjsavage** [comment]
This issue was moved to PolymerElements/iron-doc-viewer#50

**Comment by lozandier** [comment]
@tjsavage Understood
