### ISSUE TITLE
polymer 1.0 how to use dom-if ?

### ISSUE THREAD

**Issue by sujkh85** [Polymer/polymer#1828]
Please understand I do not speak English.
```javascript
  <template is="dom-if" if="{{ img_Path ==='./images/text-received.svg' }}" restamep="true">
```
How to use conditional yo Didn't?
only if = boolean?

thank you

**Comment by arthurevans** [comment]
You can't use an 0.5-style expression inside the `if=` -- you need to replace your expression with a computed binding, like:

    if="{{showImage(img_Path)}}"

See, for example: http://stackoverflow.com/questions/30607379/polymer-1-0-binding-css-classes/30607783#30607783

    

https://www.polymer-project.org/1.0/docs/migration.html#data-binding
