### ISSUE TITLE
Polymer 1.0.x and Meteor Blaze

### ISSUE THREAD

**Issue by tdesc** [Polymer/polymer#1830]
Hello,
Previous version of Polymer 0.5.5 works with Meteor Blaze render just fine.
Now, with version 1.0.x it works only on single-page-application.
If it has few routes ( I use iron:router ) to switch between pages, Polymer breaks.
Demo application with 2 pages. 
Page 1 renders fine once.
http://monosnap.com/image/Y5ImNd7AFpYYppaLOLs2Wtnv0EuNxV
Switching to Page 2 breaks DOM
http://monosnap.com/image/PKgprIQACqv6jgeGfVV8WFC8jppFl2
From log we can see, polymer element gets ready faster than Blaze renders template. 
paper-drawer-panel ready
paper-drawer-panel attached
Template.page2.rendered
Demo project here: https://github.com/tdesc/PolymerTest.git

**Comment by tdesc** [comment]
First time page rendered, it calls logged as
Template.name.rendered 
paper-drawer-panel created
paper-drawer-panel ready
paper-drawer-panel attached

Using Route.go() to switch page, we got wrong order:
paper-drawer-panel created
paper-drawer-panel ready
paper-drawer-panel attached
Template.name.rendered

Polymer calls create/ready/attached in process of Blaze._materializeDOM and Template is not yet rendered, so <content> not found. And after paper-drawer-panel attached to DOM, Template content added on same level of DOM.

Blaze.Polymer.created (paper-drawer-panel.html:374)
Polymer.Base.addFeature.invokeBehavior (polymer-micro.html:283)
Polymer.Base.addFeature.doBehavior (polymer-micro.html:278)
Polymer.Base.createdCallback (polymer-micro.html:108)
materializeTag (materializer.js:99)
materializeDOMInner (materializer.js:54)
Blaze._materializeDOM (materializer.js:33)
doMaterialize (view.js:343)
Tracker.nonreactive (tracker.js:560)
doRender (view.js:341)
(anonymous function) (view.js:191)
Template._withTemplateInstanceFunc (template.js:437)
(anonymous function) (view.js:190)
Blaze._withCurrentView (view.js:523)
DynamicTemplate:materialize (view.js:189)
Tracker.Computation._compute (tracker.js:294)
Tracker.Computation._recompute (tracker.js:313)
Tracker._runFlush (tracker.js:452)
onGlobalMessage (setimmediate.js:102)

**Comment by rcaferati** [comment]
As the 1.0 version isn't using the shadow-dom, once the element is processed it changes completely its DOM nodes. Therefore making it virtually impossible to use the components in a reactive template where you will generate/change the element content dynamically on the client.

Am I missing something here?

**Comment by dobrysmak** [comment]
Using Polymer 1.0.8 with Meteor 1.1.0.2.
Same problem here. The content of custom element seams to render itself in the root of the <template> tag, not inside HTML tag. 

Example
```
<custom-button>
  <span>Sample text 1</span>
  <span>Sample text 2</span>
</custom-button>

// custom-button.html
...
<template>
  <div class="content-wrapper">
     <content></content>
  </div>
</template>
...
```

Output
```
<custom-button>
  <div class="content-wrapper"></div>
  <span>Sample text 1</span>
  <span>Sample text 2</span>
</custom-button>
```

Any suggestions?

**Comment by dobrysmak** [comment]
I think i solved the issue. 
@tdesc and all with this problem, try to force Polymer to use ShadowDOM insted of ShadyDOM (it's default)

```
<script src="webcomponentsjs/webcomponents.js" charset="utf-8"></script>
<script>
   window.Polymer = window.Polymer || {};
   window.Polymer.dom = 'shadow';
</script>
<link rel="import" href="polymer/polymer.html">
```

Works for me
Cheers!

**Comment by HedCET** [comment]
same issue, after template switching neon-animated-page failed to sed iron-selected class
@dobrysmak i tried the above code that cause style issues with paper-elements

**Comment by iSuslov** [comment]
What is the current status of this issue? Google says Polymer is a **library** on top of framework, but in fact we can not use it with framework Blaze (I don't know about React and Angular). 
Are you guys going to say something about it?

**Comment by ebidel** [comment]
If you're only in Chrome have you tried enabling native shadow dom? That should be most of the issues related to DOM interop in frameworks.

The patch-dom.html import should help if you want to keep using shady dom and support other browsers:
https://github.com/Polymer/polymer/issues/1405#issuecomment-134771127

Another option is to opt-into shadow dom (with the setting in the previous comment) and use the full shadow dom polyfill (webcomponents.min.js not -lite.js). I haven't tested this recently to verify it 100% works. But in theory, it should get closer to native shadow dom than shady.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with Polymer 2 for us to be able to debug and potentially fix. Polymer 2 fixes a large amount of issues, probably including this one as well.

Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with Polymer 2.  Thank you!
