### ISSUE TITLE
viewBox svg attribute

### ISSUE THREAD

**Issue by josator** [Polymer/polymer#1831]
When using the data binding with $ attributes are converted to lower case.
Browsers expect svg viewBox attribute to be camel case "viewBox" but it is converted to lower case "viewbox". The data binding does not work.

The only solution for this is to use the dom api to change this attribute dynamically with setAttribute("viewBox", "0 0 100 100") ie in the "ready:" function.

Selecting the element by id seems not a good thing. If several elements have the same id in the same dom.

There should be a cleaner way to solve this.

**Comment by sorvell** [comment]
Thanks for pointing this out. This is a fairly lower level problem that we'll have to consider carefully.

Polymer uses `$=` to indicate a binding to an attribute, but making a binding to `viewBox$="{{...}}"` actually parses as an attribute called `viewbox$` so the case information is lost.

We'll need to either avoid using `$` for bindings to svg elements or whitelist attribute names that need case information. The former sounds a lot better than the latter and perhaps we might force all bindings to svg elements to be attribute bindings.

**Comment by josator** [comment]
I am also experiencing some issues with attributes like "xlink:href".

**Comment by webhipster** [comment]
values attribute doesn't seem to work either.

**Comment by davidmaxwaterman** [comment]
I'm seeing this issue too...

**Comment by lucamoller** [comment]
+1, just had the same issue.

**Comment by KeithHenry** [comment]
This is just one symptom of a more severe issue - Polymer can't support case-sensitive attributes at all, which affects a much wider range of components than just `svg viewBox`.
