### ISSUE TITLE
this.$ does not contain nodes with ids which are children of other elements with ids.

### ISSUE THREAD

**Issue by aravind901** [Polymer/polymer#1833]
For example, in a structure like this -

    <div id="parent">
        <div id="child1"></div>
        <div id ="child2"></div>
    </div>

In this case, this.$ only contains the parent node but not the child nodes.

**Comment by Sleeckx** [comment]
It seems to work on the current version: http://jsbin.com/zitetomoze/1/edit?html,output
Could it be that your children are hosted in a dom-if template?

**Comment by aravind901** [comment]
Yes. Children are present in a dom-if template. Is this intended so that multiple templates with same children nodes(with same ids) can be stamped out conditionally? But, I assumed that Polymer would be able to identify the nodes once the template is stamped. Can Polymer only do this before the attached callback?

**Comment by arthurevans** [comment]
Yes. The `this.$` hash is only populated once (before `ready` is called). Dynamically-added nodes are not included. See:

https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#node-finding
