### ISSUE TITLE
Support for expressions and filters

### ISSUE THREAD

**Issue by tam4s** [Polymer/polymer#1847]
These things below should work, because adding a full element with script tag in order to make simple things work prevents adoption of Polymer.

    <template>
      1 + 1: <span>{{ 1+1 }}</span>
      Hello <span>{{ "world".toUpperCase() }}</span>
      ...or...
      Hello <span>{{ "world"|toUpperCase }}</span>
    </template>

**Comment by peduxe** [comment]
That is still not possible, what you can do is alter the binding with computed bindings: https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#annotated-computed

**Comment by robdodson** [comment]
@tam4s you can do `<template is="dom-bind">` to automatically stamp out a template, however Polymer 1.0 does not currently have support for binding expressions.

> adding a full element with script tag in order to make simple things work prevents adoption of Polymer.

Polymer is designed for building Web Components, it's not primarily focused on being a general purpose templating library.

**Comment by sorvell** [comment]
Rob's comment covers Polymer's current behavior. We consider new features based on user feedback. Thanks for your comments.

**Comment by popbee** [comment]
What's wrong with binding expressions?

> We consider new features based on user feedback. 

Where to express the feedback? I'll post here.

> Polymer is designed for building Web Components, it's not primarily focused on being a general purpose templating library.

...Then tell us how to use a "general purpose templating library" when writing Polymer components. I have yet to see a solution.

Do you agree that not having expressions inside HTML feels backwards nowadays?

I mean, do you deny Binding/Templating Expression's popularity? To me, it is very easy to understand and attractive. We cannot say the same for computed bindings / filters!  They are hard to read (unless you are really good with your naming conventions), not easy to code (have to not only create a piece of code completely elsewhere but one has to give it a name even for simple things like "{{index%2==0}}".

Half-baked solution:
In Polymer 1.0 you left the "bang" (!) operator. I didn't read anywhere the reason why bang operator was still available. Please explain this. Guess what: I'll use your explanation in favor to full blown expressions! Frankly, what is the difference between something like "{{!shown}}" and "{{index + 1}}"?

From a high level:
One beauty of javascript is inline (&anonymous!) functions. Code is next to where it is used. Well, binding expressions is very similar! Code exactly where it's needed (and for simple things, without the hassle of naming it and maintaining an "external" piece of code).

**Comment by Tomucha** [comment]
@popbee I would like this too, please express your feedback also here:
https://plus.google.com/u/1/+TomasZverina/posts/W43sPHaFysE

**Comment by popbee** [comment]
Sure did. I will support any effort to have better "extrapolations" (or whatever they like to call it) with Polymer. Either within the core (better as everybody would align) or at least a solution supported by Polymer docs / people (or anything going in that direction).

AFAIK I have yet to see a [good] demonstration of why this would be "wrong" or would slow down anything. I am opened to hear it.

I must confess that this very feature [or lack thereof] is what "killed" Polymer for me. As of now, I did not upgrade existing projects to 1.0 and went the ReactJS [& related] route for new ones.

**Comment by larsgk** [comment]
Why stop at expressions and filters? - attributes in general also slow down processing - maybe they should be removed alltogether so we only have the tag? /s ;)
