### ISSUE TITLE
'this' points to Window rather than custom element when called through setTimeOut()

### ISSUE THREAD

**Issue by aravind901** [Polymer/polymer#1853]
After calling a function through setTimeOut inside a Polymer element, 'this' no longer points to the custom element but to the window. Demo below.

http://jsbin.com/hehafo/2/edit?html,console,output

**Comment by pvmart** [comment]
use 
``` js
setTimeout(this.delayed.bind(this),100);
```
instead

**Comment by peduxe** [comment]
Third method:
```javascript
setTimeout(function() {
    this.delayed();
}.bind(this),100);
```

**Comment by ebidel** [comment]
Yep, this is what `async()` is for. If you want to use `setTimeout`, you'll need to bind `this`. Just scoping ftw!
