### ISSUE TITLE
can I two way binding a properties type of 'Number' to attribute?

### ISSUE THREAD

**Issue by w88975** [Polymer/polymer#1856]
I define a properties, type of 'Number':

``` javascript

properties: {
            inputValue: {
            type: Number,
            notify: true,
            value: 0,
            observer: '_inputValueChanged',
        },
}

```

I set the element Attribute with this properties:

```html

<input type="number" value="inputValue::input">

```

I input some number in this element,I got this `inputValue`, output a 'string' type value?

how can I get a 'number' type value, and how can I set the tow way binding value type of 'number'?

thanks!

**Comment by peduxe** [comment]
You need to compute the value and convert it to Number.

With a computed binding, here is a working example: http://jsbin.com/xapegu/1/edit?html,console,output

**Comment by w88975** [comment]
@peduxe 

I made a mistake on this issue, but my code are right 😓.

thanks for you .

this `computed` are pretty good.
