### ISSUE TITLE
documentation bug; search elements

### ISSUE THREAD

**Issue by dsaronin** [Polymer/polymer#1858]
Typing in "paper-drawer-toggle" in the search bar of the Polymer Elements page (screenshot) in order to view all element docs referencing the search phrase fails to turn up anything, yielding the following: 
```
'paper-drawer-toggle' Elements 0
```

It would be nice to actually be able to search through all the polymer documents for a particular result or reference. I hear that a young company out of Mountain View has a search engine with exceptional capability; "Google" I think is their name.

![screenshot from 2015-06-12 17 18 51](https://cloud.githubusercontent.com/assets/410380/8142108/babc9524-1127-11e5-9d4e-3b85940fc1a1.png)

**Comment by sorvell** [comment]
Should be posted in https://github.com/Polymer/polymer-element-catalog/issues.

**Comment by arthurevans** [comment]
This issue was moved to Polymer/polymer-element-catalog#129
