### ISSUE TITLE
Polymer Catalog -- link-related usability issue

### ISSUE THREAD

**Issue by pjump** [Polymer/polymer#1860]
The demo buttons look like links but they don't behave like links. Clicking on a link while holding CTRL would normally opens up a new tab. It doesn't for the demo buttons (the ones with the eye icon).
Also back buttons after clicking on a link will normally get you back to the same place you departed from (same page, same spot on the page). It doesn't work with the demos.

Can't the demo buttons just be normal links?

**Comment by sorvell** [comment]
Should be posted in https://github.com/Polymer/polymer-element-catalog/issues.

**Comment by pjump** [comment]
Apologies. Will cut & paste.
