### ISSUE TITLE
[1.0] Inserted content not toggled when inside dom-if

### ISSUE THREAD

**Issue by yyx990803** [Polymer/polymer#1862]
With the following template:

``` html
<template is="dom-if" if="{{ok}}">
    <p>normal content</p>
    <content></content>
</template>
```

When the `ok` property changes, `<p>normal content</p>` is toggled as expected; However the inserted content will always remain in the DOM.

**Comment by peduxe** [comment]
https://github.com/Polymer/polymer/pull/1816

If you're in the master branch the problem has been fixed.

**Comment by yyx990803** [comment]
Cool, thanks!
