### ISSUE TITLE
Loop in iron-overlay-manager

### ISSUE THREAD

**Issue by dsportes** [Polymer/polymer#1864]
I have a modal paper dialog opening a second modal paper-dialog.
This causes a loop (Maximum call stack exceed) in two different locations :
iron-overlay-manager.html line 63
paper-dialog-manager.htm line 210
I didn't find any workaround.
Regards

**Comment by dsportes** [comment]
I patched iron-overlay-manager.html at line 74 with: 
        setTimeout(function() {current._applyFocus();}, 100);
and paper-dialog-behavior.html at line 210 with:
        	  if (!document.hasFocus()) {
		            if (this._lastFocusedElement) {
		              this._lastFocusedElement.focus();
		            } else {
		              this._focusNode.focus();
		            }
        	  }
Issues "seem" to be solved but I'm not really confident why :-)
Regards

**Comment by sorvell** [comment]
This issue tracker is for the Polymer core library. We'll make sure this is moved to an appropriate location.

**Comment by tjsavage** [comment]
This issue was moved to PolymerElements/iron-overlay-behavior#18
