### ISSUE TITLE
templatizer behavior docs don't appear

### ISSUE THREAD

**Issue by tjsavage** [Polymer/polymer#1867]
Repro:
- Go to http://polymer.github.io/polymer/
- Select "dom-template" from the dropdown
- Try to click on the "Templatizer" behavior

Result: It doesn't take you anywhere

@garlicnation this might be iron-doc-viewer, hydrolysis, or just that [templatizer behavior](https://github.com/Polymer/polymer/blob/master/src/lib/template/templatizer.html) needs more docs.

**Comment by garlicnation** [comment]
Templatizer needs `@polymerBehavior`
