### ISSUE TITLE
Paper Elements don't appear on site

### ISSUE THREAD

**Issue by illuminationdesign** [Polymer/polymer#1868]
Hello everyone,

I am using the Polymer Paper Elements in a test web app. The link is [http://illuminationdesignstudio.com/testing/](http://illuminationdesignstudio.com/testing/). At least for me, on Google Chrome, the site works fine and all of the elements appear. On mobile - specifically iPhone, the text appears, but it is not stylized as Paper Elements. I used both Safari and Chrome on iOS 8.1.2 and I get the same problem on both. I have tried using the "unresolved" attribute in the body tag, but that just leaves me with a blank screen. Could somebody help please? I can upload screenshots if needed. Thanks.

**Comment by VandeurenGlenn** [comment]
Hi @illuminationdesign 

The ShadowDOM polyfill isn't included in the webcomponents-lite.js, so just replacing it with webcomponents.js should work.

**Comment by illuminationdesign** [comment]
Thanks @VandeurenGlenn, worked like a charm. I appreciate the help. :+1:
