### ISSUE TITLE
Paper-Input validation does not work on iOS

### ISSUE THREAD

**Issue by devAtPolydeals** [Polymer/polymer#1870]
I have the following paper-input:
``` <paper-input pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" value="{{email}}" name="email" id="email" label="Email Address" required  error-message="Invalid Email Address!"></paper-input>```

It works perfect on Chrome on Windows/Android but not in iOS, after user enters the value and hits the Submit button, even with a valid email the validation fails.

I am using webcomponents.min.js polyfill.

**Comment by kevinpschaaf** [comment]
You opened this in the Polymer core library issue tracker.  We'll get this issue moved to the appropriate element repo's tracker (`paper-input`).

**Comment by devAtPolydeals** [comment]
btw I ended up using gold-email-input...
