### ISSUE TITLE
Polymer object is undefined on IE11 due to use of behaviors

### ISSUE THREAD

**Issue by dimshik100** [Polymer/polymer#1871]
while checking the iron-range-behavior from your catalog on ie11, I've got the following exception: 'Polymer' is undefined.

sample link: https://elements.polymer-project.org/elements/iron-range-behavior?active=Polymer.IronRangeBehavior&view=demo:demo/index.html

Also tried iron-range-behavior uni-test from polymer-starter-kit, they all fail on IE11.
http://<polymer-starter-kit host>/bower_components/iron-range-behavior/test/index.html
  
It looks like IE11 have some issues with polymer behaviors.

**Comment by kevinpschaaf** [comment]
The call to `Polymer` needs to be wrapped in `HTMLImports.whenReady`.

**Comment by tsachyg** [comment]
Thanks kevinpschaaf,
It solved the problem :-)

**Comment by tjsavage** [comment]
This issue was moved to PolymerElements/iron-range-behavior#7
