### ISSUE TITLE
Polymer Elements Do Not Show Up On Chrome version 39.0.*

### ISSUE THREAD

**Issue by dman777** [Polymer/polymer#1872]
When using my browser, `Google Chrome 39.0.2171.95`, the demos for the polymer 1.0 paper elements do not render. 

[paper-header-panel demo](https://elements.polymer-project.org/elements/paper-header-panel?view=demo:demo/index.html&active=paper-header-panel)
![pic2](https://cloud.githubusercontent.com/assets/887815/8162154/20489af8-1341-11e5-89b7-3f25fa57acf2.jpg)

Note: this is not a issue with version `0.5.5`....only with `1.0`

**Comment by kevinpschaaf** [comment]
We can't reproduce this on Chrome Stable (42 or 43).  Can you try upgrading and reproducing this on a current version?

**Comment by kevinpschaaf** [comment]
@dman777 Are you still having an issue here, or can we close this issue?

**Comment by dman777** [comment]
@kevinpschaaf I am going to work on this Sunday, I will definitely let you know. Thank you for asking.

**Comment by dman777** [comment]
Closing  this issue...I just upgraded my browser to fix this(alot of work on Gentoo).
