### ISSUE TITLE
Overwriting mixin properties 

### ISSUE THREAD

**Issue by Pupix** [Polymer/polymer#1873]
Hello! I am trying to overwrite a property coming from a CSS mixing, but the way Polymer handles the variables makes it impossible to do so (without using "!important").

```html
<style>
    .foo {
        @apply(--paper-font-caption)
        white-space: normal;
    }
</style>
```

The expected result would be to have "white-space: normal" applied on top of the one provided by paper-styles, however that's not the case.

Do I have to rewrite the entire mixing just to change one property or is there an alternative way?

Cheers.

**Comment by sorvell** [comment]
This is due to the way that Polymer separates static styles from styles which contain custom properties. This use case is reasonable and our approach needs to be modified slightly to support this better.

We will probably not separate custom properties css from static css within rules that contain properties.

**Comment by Pupix** [comment]
Thanks for the response. Will wait for an update then.

**Comment by sorvell** [comment]
This issue also leads to specificity issues when combining static and custom property rules.

**Comment by robrez** [comment]
:+1:

**Comment by jmcgdz** [comment]
:+1:

**Comment by nazar-pc** [comment]
@Pupix, can you provide complete test case? I guess this might be either already fixed by #2642 or I can try to extend PR to cover this case as well and add corresponding test case.

**Comment by robrez** [comment]
@nazar-pc Here's a jsbin that, i think, demonstrates the issue:

https://jsbin.com/kefuzi/edit?html,output

**Comment by nazar-pc** [comment]
OK, here is easier to understand example: https://jsbin.com/xupufudivu/1/edit

**Comment by nazar-pc** [comment]
Seems to be different area than covered in #2642, but I'll take a look on this as well.

**Comment by nazar-pc** [comment]
#2642 now fixes this issue as well.
