### ISSUE TITLE
CSS Custom Properties with semicolon

### ISSUE THREAD

**Issue by benjyblack** [Polymer/polymer#1875]
The Custom Property shim isn't able to deal with values that contain semicolons, as can be seen in this [jsbin](http://jsbin.com/suwopoteye/1/edit?html,output). If you inspect the text in the inspector you'll see that the value is cut off to `background-image: url(data:image/gif; };`. The [spec](http://dev.w3.org/csswg/css-variables/#syntax) seems to indicate that semi-colons can be used as long as they're not at the top level. I'm not sure what constitutes top-level but it seems as though this use case should be supported.

**Comment by sorvell** [comment]
Thanks for finding this issue. This should be valid syntax and will need to be supported.

**Comment by TimvdLippe** [comment]
http://jsbin.com/bikawijuqu/edit?html,console,output seems to be working now with Polymer 2, so I assume the issue has been fixed in the mean time.
