### ISSUE TITLE
Add a way to share styles between elements and the global scope

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#1876]
Given that a user has made a `custom-style` for something like layout, for example, it's convenient to be able to use this inside an element as well. Currently, this requires code duplication.

If we supported a new syntax like this: `<link rel="import" is="custom-stylesheet">` then the style could be defined once and used globally (via `cusotm-style` functionality) or locally inside an element via the link's location inside an element `<dom-module>` (`custom-style` uses this technique now). If we do this, we should deprecate the current syntax for loading remote stylesheets in element (`<link rel="import" type="css">`)

**Comment by eximius313** [comment]
+1

**Comment by vsimonian** [comment]
+1

**Comment by agektmr** [comment]
+1

**Comment by sorvell** [comment]
Changes that will be merged for this issue are here: https://github.com/Polymer/polymer/pull/2198.

**Comment by sorvell** [comment]
@arthurevans can you please close this when you feel this has been adequately documentated? Thanks.

**Comment by arthurevans** [comment]
Documented, as described in #2229.
