### ISSUE TITLE
Binding undefined object sub-properties may result in multi-prop observers not running

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#1877]
Binding structured data with `undefined` sub-properties into an element results in `undefined` being set to the property in question; typically we only expect `undefined` values transiently at startup, since they should either become valued by attributes in markup, bindings from above, or default values, and Polymer avoids calling multi-property observers until all dependencies become valued.

However, in the case of bindings to structured data, if a new object is set with undefined properties, this results in the element receiving `undefined` at runtime and may not properly react to this change in state.

See http://jsbin.com/cejusi/edit?html,output for repro, where `dom-if` receives `undefined` but since its observer is multi-prop, it waits until it becomes defined.

One idea is to explicitly trap the case that `undefined` is being set to a Polymer element property and convert that to the element's default value for the property, if it exists.

**Comment by robrez** [comment]
I reported some problems w/ a multi-property attribute binding earlier, #1874, it sounds like what kevin's describing:

> Polymer avoids calling multi-property observers until all dependencies become valued

**Comment by kevinpschaaf** [comment]
Issue for proposed fix here: https://github.com/Polymer/polymer/issues/1946 with PR in https://github.com/Polymer/polymer/pull/1941

**Comment by sorvell** [comment]
Alternatively object sub-properties could be treated as `null`. This would indicate a value has been set causing observers to fire without requiring a default value to be set.
