### ISSUE TITLE
How binding a JSON in Polymer 1.0

### ISSUE THREAD

**Issue by ypicoleal** [Polymer/polymer#1878]
I have a Json like this:
<pre>[{
  "id":4,
  "fecha":"2015-05-13 22:34:01.560404+00",
  "latitude":"10.41413",
  "longitude":"-75.530156",
  "imagenes":[
      "media/6_img_0001.jpg",
      "media/7_img_0004.jpg"
  ]
},
{
  "id":5,
  "fecha":"2015-05-20 15:28:12.079346+00",
  "latitude":"10.402313",
  "longitude":"-75.505112",
  "imagenes":[
      "media/8_ctev.jpg",
      "media/9_2560x1600.jpg"
  ]
}]</pre>

I'm trying to bind the JSON in a template repeat, like this one:
<pre><code>
&lt;dom-module id="bas-app"&gt;
&lt;style&gt;&lt/style&gt;
&lt;template&gt;
&lt;iron-ajax auto url="reportes.json" handle-as="json" on-response="handleResponse"&gt;&lt/iron-ajax&gt;
&lt;paper-menu&gt;
   &lt;template is="dom-repeat" items="{{reportes}}"&gt;
      &lt;paper-item&gt;{{item.id}}&lt/paper-item&gt;    
   &lt;/template&gt;  
&lt;/paper-menu&gt;
&lt;/template&gt;
&lt;/dom-module&gt;
&lt;script&gt;
        Polymer({
            is: 'bas-app',
            reportes: [],
            handleResponse: function(event){
                this.reportes = event.detail.response;
            }
        });
&lt;/script&gt;
</code></pre>
but I got an error like this
<pre>
Polymer::Attributes: couldn`t decode Array as JSON
</pre>

**Comment by thanhnhan2tn** [comment]
Hello, 
I have same issues, please give me a solution for this.
Thanks.

**Comment by zoechi** [comment]
[StackOverflow](http://stackoverflow.com/questions/new/polymer) might be a better place to ask questions
