### ISSUE TITLE
The requested URL /0.5/components/core-tooltip/demo.html was not found on this server.

### ISSUE THREAD

**Issue by VikramTiwari** [Polymer/polymer#1880]
https://www.dropbox.com/s/rcj7yxn4uehe9ag/Screenshot%202015-06-15%2019.09.50.png?dl=0

**Comment by VikramTiwari** [comment]
Page URL

https://www.polymer-project.org/0.5/components/core-elements/demo.html#core-tooltip

**Comment by ebidel** [comment]
This issue was moved to Polymer/docs#1197
