### ISSUE TITLE
Open the website country restrictions

### ISSUE THREAD

**Issue by AliMD** [Polymer/polymer#1885]
Could you please open the website country restrictions for iranian users?

![screenshot from 2015-06-16 17 11 36](https://cloud.githubusercontent.com/assets/697913/8183111/f2eff28a-144a-11e5-8d7c-ccbb6745d952.png)

There is no issue to view elements.polymer-project.org !
I think its for app-engine policy and it can be switched.

**Comment by sorvell** [comment]
This issue tracker is for the Polymer core library. We'll make sure this is moved to an appropriate location.

**Comment by ebidel** [comment]
This issue was moved to Polymer/docs#1196
