### ISSUE TITLE
Expected behavior for importNode,cloneNode

### ISSUE THREAD

**Issue by timeu** [Polymer/polymer#1888]
I am not sure if this is by design and/or if it is a `Polymer` or rather a general `Web-Components` spec issue. 

When I use `importNode` or `cloneNode` with `deep=true` of a custom-element that contains another custom element (via Light DOM) and then insert it into the document, the resulting DOM structure is not the same as if I would create it manually. 

See the jsbin: http://jsbin.com/haxeni/edit?html,console

**Comment by sorvell** [comment]
Thanks for posting this. This is a known limitation that comes with using Shady DOM. We need to add support for `importNode` and `cloneNode` to the `Polymer.dom` api to address this. At that point, you'll use `Polymer.dom(element).cloneNode` and `Polymer.dom(element).importNode`.

**Comment by sorvell** [comment]
Marking this high priority since we plan to add these api's very soon.

**Comment by timeu** [comment]
Great thanks for the feedback.

**Comment by nomego** [comment]
Also appending a `<template is="dom-bind">` element with `Polymer.dom(element).appendChild(template)` breaks the stamping. The same code, replacing `Polymer.dom(element)` with `document.body` works.

Let me know if this is a separate issue.
