### ISSUE TITLE
[1.0] Uncaught TypeError: Cannot read property '$' of undefinedPolymer...

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#1892]
Goodluck finding it :)

```log
Uncaught TypeError: Cannot read property '$' of undefinedPolymer.Bind._modelApi._propertySet @ 
polymer.html:1015setter @ polymer.html:1092Polymer.Base._addFeature._marshalIdNodes @ 
polymer.html:300Polymer.Base._addFeature._marshalAnnotationReferences @ 
polymer.html:284Polymer.Base._addFeature._initFeatures @ 
polymer.html:2776Polymer.Base.createdCallback @ 
polymer-micro.html:106
```

Or maybe it is something else :P I'm completely in the dark here.

**Comment by timeu** [comment]
Are you trying to access `$` in the `created` callback ? 
If so then this won't work because the local DOM is not initialized at that point. You should use the `ready` callback. See the [docs](https://www.polymer-project.org/1.0/docs/devguide/registering-elements.html#ready-method) for more infos.

**Comment by gertcuykens** [comment]
Aaa that could be it, thanks :)

**Comment by gertcuykens** [comment]
O wait I was using ready but in the docs I see

ready: function() {
  // access a local DOM element by ID using this.$
  this.$.header.textContent = 'Hello!';
}

Can't remember where I read that I needed to replace all this.$... with Polymer.dom(this.$....)

Hmm let me look it up..

**Comment by gertcuykens** [comment]
https://www.polymer-project.org/1.0/docs/migration.html#dom-apis

Damit! Now I understand I think. Conclusions I messed up allot of lines

**Comment by gertcuykens** [comment]
And I am back too `Uncaught TypeError: Cannot read property '$' of undefinedPolymer`
No way I am the only one struggling with this error going from 0.5 to 1.0?

**Comment by gertcuykens** [comment]
Finally found out why. PS at polymer team don't let your 0.5 migrating users suffer like this...

```html
       <paper-input-decorator label="Titel" error="Verplicht veld." isInvalid="{{!$.i1.validity.valid}}"> <==============
            <input id="i1" name="title" value="{{title}}" is="iron-input" required>
        </paper-input-decorator>
```
