### ISSUE TITLE
[google-youtube] fluid not working

### ISSUE THREAD

**Issue by 19Gerhard85** [Polymer/polymer#1896]
Hey guys,

I tried to include a YouTube video into my site, unfortunately the fluid parameter isn't working.

```html
<paper-material elevation="1">
    <google-youtube
        video-id="qyJ9xctOMCI"
        fluid="true"
        rel="0"
        start="0"
        autoplay="0">
    </google-youtube>
</paper-material>
```

The width of the embedded player is 100% but the height is only 150px small instead of a 16:9 ratio.

**Comment by sorvell** [comment]
This issue tracker is for the Polymer core library. We'll make sure this gets moved to the appropriate repo.

**Comment by tjsavage** [comment]
Looks like this was added as https://github.com/GoogleWebComponents/google-youtube/issues/40 Thanks!
