### ISSUE TITLE
Will properties support merge some day?

### ISSUE THREAD

**Issue by melonHuang** [Polymer/polymer#1897]
Sometimes when we have many properties, we'd like to devide them into groups like:

``` javascript
Polymer({
    is: 'plugin-share',
    properties: {
        shareData: {
            type: Object,
            value: {
                title: document.title,
                desc: '',
                link: location.href,
                img: '';
            }
        },
        otherProps: Object
    }
    ready: function() {
        // ...
    }
})
```

However, when we define an element, the properties we pass will override the default value。
As a result, in the following case, when I want to define share description, and use the default title, link, the default value is overrided and lost the default title, link, etc.

``` html
<plugin-share share-data="{desc: /"share description/"}"></plugin-share>

<script>
document.querySelector('plugin-share').shareData; 
// { desc: "share description" }
</script>
```

Will Polymer support another key like this (merge):

``` javascript
Polymer({
    is: "plugin-share",
    properties: {
        shareData: {
            type: Object,
            merge: true,
            value: {}
        }
    }
})
```

Is there an elegent way that I can solve this reuse issue.

Thx!

**Comment by kevinpschaaf** [comment]
Unlikely that we'll support this soon, since JSON-encoded attributes for static configuration in markup is not a typically used idiom in HTML.  But we'll keep it open for now for future consideration.

**Comment by TimvdLippe** [comment]
Closing this in favor of #2069
