### ISSUE TITLE
clientHeight / clientWidth of local elements

### ISSUE THREAD

**Issue by prushforth** [Polymer/polymer#1898]
I have found that Polymer 1.0 does not support Leaflet map in the way that Polymer 0.3.5 did, and I would appreciate some advice as to how to proceed. It is obviously desirable to be able to use Polymer 1.0 and not develop in an obsolete version. Here is the code which worked at 0.3.5
(well I'm not sure exactly which version mix the fellow used - it was about 0.3.5 though. Here's the link to his work, which I installed and used ( http://prtksxna.github.io/leaflet-map-component/ ):

If you want the tl;dr version, scroll to the bottom, the issue I believe is red-circled.

Thank you

index.html:

```
<!DOCTYPE html>
<html>
  <head>
    <script src="./bower_components/platform/platform.js"></script>
    <link rel="import" href="polymer-map.html">
    <style>
      my-map {
        height: 300px;
        width: 640px;
      }
    </style>
  </head>
  <body>
    <my-map zoom="15" lat="45.398043" lon="-75.70683"></my-map>
  </body>
</html>
```
and the imported polymer-map.html

```
<link rel="import" href="./bower_components/polymer/polymer.html">

<script src="./bower_components/leaflet/dist/leaflet.js"></script>

<polymer-element name="my-map" attributes="lat lon zoom">

<template>
  <style>
   :host {
     display: block;
     position: relative;
   }

   #map {
     position: absolute;
     top: 0;
     right: 0;
     bottom: 0;
     left: 0;
   }
  </style>
  <link rel="stylesheet" href="./bower_components/leaflet/dist/leaflet.css">
  <div id="map"></div>
  <content></content>
</template>
<script>
Polymer({
    is: "my-map",
    publish: {
      lat: {
        value: 0, 
        reflect: true 
      },
      lon: {
        value: 0,
        reflect: true 
      },
      zoom: {
        value: 10, 
        reflect: true
      }
    },
    attached: function() {
      console.log(this.localName + '#' + this.id + ' was attached');

      this.map = L.map(this.$.map, {
        center: new L.LatLng(this.lat, this.lon),
        zoom: this.zoom,
        layers: [L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png')]
      });
      console.log(this.localName + "this.$.map.clientWidth/Height: "
              +this.$.map.clientWidth+ "/ "+this.$.map.clientHeight);
      console.log("map center: "+this.map.getCenter());
      var west = this.map.getBounds().getWest(),
          south = this.map.getBounds().getSouth(),
          east = this.map.getBounds().getEast(),
          north = this.map.getBounds().getNorth();
      
      if (west === east || south === north) {
        console.log('ERROR: BAD EXTENT');
      }
      console.log("map bounds bbox=" + this.map.getBounds().toBBoxString());
    }
});
</script>
</polymer-element>
```

When I run it, I get a nice map.  If I reveal the console, the logged result is as follows:

![image](https://cloud.githubusercontent.com/assets/2437285/8207610/a3f2327a-14d0-11e5-91af-58f9b16edcd1.png)

Here is the equivalent code for Polymer 1.0, with output below:

index.html:
```
<!DOCTYPE html>
<html>
  <head>
    <script src="./bower_components/webcomponentsjs/webcomponents.min.js"></script>
    <link rel="import" href="polymer-map.html">
    <style>
      my-map {
        height: 300px;
        width: 640px;
      }
    </style>
  </head>
  <body>
      <my-map zoom="15" lat="45.398043" lon="-75.70683"></my-map>
  </body>
</html>
```

and polymer-map.html:
```
<link rel="import" href="./bower_components/polymer/polymer.html">

<script src="./bower_components/leaflet/dist/leaflet.js"></script>

<dom-module id="my-map">
<style>
  :host {
      position: relative;
      display: block;
    }
  #map {
      position: absolute;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
  }
</style>
<link rel="import" type="css" href="leaflet/leaflet.css">

<template>
  <div id="map">
  </div>
  <content></content>
</template>
<script>
Polymer({
    is: "my-map",
    properties: {
      lat: {
        type: Number,
        value: 0, 
        reflectToAttribute: true 
      },
      lon: {
        type: Number,
        value: 0,
        reflectToAttribute: true 
      },
      zoom: {
        type: Number,
        value: 10, 
        reflectToAttribute: true
      }
    },
    attached: function() {
      console.log(this.localName + '#' + this.id + ' was attached');
      this.map = L.map(this.$.map, {
        center: new L.LatLng(this.lat, this.lon),
        zoom: this.getAttribute('zoom'),
        layers: [ L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png')]
      });
      console.log(this.localName + "this.$.map.clientWidth/Height: "
        +this.$.map.clientWidth+ "/ "+this.$.map.clientHeight);

      console.log("map center: "+this.map.getCenter());
      var west = this.map.getBounds().getWest(),
          south = this.map.getBounds().getSouth(),
          east = this.map.getBounds().getEast(),
          north = this.map.getBounds().getNorth();
      
      if (west === east || south === north) {
        console.log('ERROR: BAD EXTENT');
      }
      console.log("map bounds bbox=" + this.map.getBounds().toBBoxString());
    }
});
</script>
</dom-module>
```

Here's what the logged output and map look like:

![image](https://cloud.githubusercontent.com/assets/2437285/8207780/bf53395a-14d1-11e5-99e7-be0399cfd417.png)

**Comment by robrez** [comment]
I think that attached might be too early for obtaining size metrics.

Have you tried moving your code to another function and running that, via async, from the attached function...

```
attached: function() {
    this.async(this._domReady)
}

_domReady: function() {
    //do stuff
}
```

I've had some trouble w/ offsetHeight/Width and client height/Width even in polymer 0.5. I think that you have timing issues such that distribution has not yet filled in `<content>` tags.

/sub

**Comment by prushforth** [comment]
Hi,

Thanks for the suggestion.  It looked promising, but that particular async has the same result.  The weird thing is that
when I put a breakpoint on the code and then let it run , the clientHeight returns non-zero value.

The map is still messed up, but probably for other reasons related to dom, but at the least it doesn’t start out with
a bad extent.

Thanks
Peter

**Comment by robrez** [comment]
Yeah that sounds like the timing trouble I've had in the past. I think I did something silly like waiting for a few RAFs or using setTimeout before trying to obtain height/Width.

Good luck. I'm following the issue to see if anyone has good suggestions.. Keep me posted if you figure anything out

**Comment by prushforth** [comment]
I notice that even if I set the timeout value for the async call to 10000, it executes immediately.  This I think is
reflected in the documentation:


  *   async(method, [wait]). Calls method asynchronously. If no wait time is specified, runs tasks with microtask timing (after the current method finishes, but before the next event from the event queue is processed). Returns a handle that can be used to cancel the task.

which implies that whatever event would correctly set the clientHeight to non-zero value has not yet fired.  So
I guess I need a way to wait until that event is fired.

**Comment by sjmiles** [comment]
Polymer 0.5 had a lot more built-in asynchrony. 

Fwiw, I tried this with `this.async(..., 1);` and successfully retrieved the metrics. 

http://plnkr.co/edit/zTQcG94OLFRa94mdvkYq?p=preview

Fwiw, `async` of 0 is _inside_ the animation frame by design, and therefore too soon.

**Comment by prushforth** [comment]
Hey Scott,

Thanks for your reply.  I did not realize the [wait] parameter was seconds(?).  Maybe it did not like the 10000 value I was giving it!

That does seem to solve the first problem, indeed.  Now I just have to figure out the other layout issues, but that will seem like a breath of fresh air after the frustration of the first request problem.

Thanks also to Rob Resendez also, who only didn’t solve the problem by virtue of my ignorance.
Thanks again.  Case closed.
Peter

**Comment by sjmiles** [comment]
Wait argument is in milliseconds (ms).
