### ISSUE TITLE
Cannot expression-bind special utf8 characters in HTML

### ISSUE THREAD

**Issue by arodic** [Polymer/polymer#1899]
if `this.apple == ''` I would expect that:

`<span>{{apple}}</span>`

should render:

`<span></span>`

Instead I get:

`<span>ï£¿C</span>`

**Comment by moderndeveloperllc** [comment]
I can use this fine on the polymer-start-kit. I'm thinking that perhaps your file is not saved with a UTF-8 encoding?
```
properties: {
        greeting: {
          type: String,
          value: '',
          notify: true
        }
      }
```

**Comment by arodic** [comment]
@moderndeveloperllc you are correct. My mistake. Closing.
