### ISSUE TITLE
With Shady DOM, <content> doesn't get passed to another element inside dom-if

### ISSUE THREAD

**Issue by trevordixon** [Polymer/polymer#1902]
See http://plnkr.co/edit/k159u1diDGJ1PNgfwAvB?p=preview. Using v1.0.3, there are JS errors. Using master, there aren't JS errors, but it still doesn't work.

It does work, in v1.0.3 and master, with native shadow DOM. See http://run.plnkr.co/plunks/k159u1diDGJ1PNgfwAvB/?dom=shadow.

@kevinpschaaf Probably related to #1816?

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/polymer/pull/1917.
