### ISSUE TITLE
Cannot read property 'instanceCount' of undefined Polymer.Base.createdCallback 

### ISSUE THREAD

**Issue by cchristensen-cxp** [Polymer/polymer#1905]
Uncaught TypeError: Cannot read property 'instanceCount' of undefinedPolymer.Base.createdCallback 
@ polymer-micro.html:103

Upgraded from .5 to 1.0 and now I get this error.

**Comment by timeu** [comment]
how does your `created()` callback look like ?

**Comment by addyosmani** [comment]
Would it be possible to share the source to your element (or a minimal test case) that we can use to dig into this further?

**Comment by cchristensen-cxp** [comment]
Found the issue while making the test case.  I was importing file that didn't exist.

**Comment by JGSolutions** [comment]
@cchristensen-cxp 
Did you only get this error message appearing in firebase hosting? 

When I do firebase serve and everything is fine but when I deploy to firebase hosting this is when I get the error.

**Comment by Shah-Parth** [comment]
@JGSolutions have you been able to fix this issue? I keep getting this when I try to deploy it or serve it through firebase.

**Comment by JGSolutions** [comment]
In the sw-precache-config.js add this line: 

navigateFallbackWhitelist: [ /^\/[^\_]+\// ]

**Comment by rafagarcia** [comment]
@JGSolutions when i add this line i get this message in the polymer build process:

info:    Preparing build...
info:    Building application...
warn:    /Users/********/Desktop/*******/sw-precache-config.js file was found but could not be loaded
{ loadError: {} }
info:    Generating build/unbundled...
info:    Generating build/bundled...
info:    Build complete!
