### ISSUE TITLE
dom-repeat doesn't recognize when its DOM is modified by something other than itself

### ISSUE THREAD

**Issue by zbury** [Polymer/polymer#1906]
I was directed here after posting [this question on SO](http://stackoverflow.com/questions/30878200/inform-polymer-dom-repeat-of-changes-to-local-dom).

Basically, my issue is that after manipulating a `dom-repeat` template with jQuery UI Sortable, I update its `items` array  to reflect the change, which results in the change being carried out a second time.

The only hack I came up with involves clearing its `items` array before setting it to reflect the updated order. Is there any way to work around this?

**Comment by bruunofco** [comment]
Can you give us an example working? maybe Plunker?

**Comment by TimvdLippe** [comment]
Closing per above comment. We can reopen this issue if a JSBin is supplied.
