### ISSUE TITLE
Add equivalent of Angular's 'track-by' to dom-repeat to control association of dom nodes to data

### ISSUE THREAD

**Issue by sshumaker** [Polymer/polymer#1908]
Currently, dom-repeat uses === equality to determine how to re-use dom nodes when the underlying array is mutated.

However, it's pretty common to want to use some other identifier, because you've fetched new data from the server but most of the data is really equivalent (maybe with a newer item in front), even if the top level object has changed. For example, your objects may have a unique id that you would rather use.

Perhaps something of the form:

``` HTML
<template is="dom-repeat" track-by="{{item.foo.id}}" items="{{data}}">
```

or

``` HTML
<template is="dom-repeat" track-by="{{getId(item)}}" items="{{data}}">
```

**Comment by TimvdLippe** [comment]
Because of the trade-off between implementation time, maintenance burden and eventual new features, we will not be spending work on this specific feature. Therefore, I am closing this issue.
