### ISSUE TITLE
Attributes are null if default attributes are used

### ISSUE THREAD

**Issue by torcellite** [Polymer/polymer#1909]
If default attribute values are set in `properties`, then the attributes continue to be `null` even when `ready()` is called.

Shouldn't the attributes be initialized with the default values?

**Comment by zerodevx** [comment]
Attributes that are set up in `properties` should be initialized by the time the `ready()` callback is called. Could you post a repro code snippet?

**Comment by torcellite** [comment]
Well, they are displayed when the custom element is used in an HTML file. However, when I try to test the default attributes, I get a `null` unless they're explicitly set.

custom-element: http://pastebin.com/YcwFHABs
test suite: http://pastebin.com/LiaBikgJ

**Comment by zerodevx** [comment]
Your custom element seems correct except I don't think you have to define `attributes` within the `dom-module` tag in Polymer 1.0 - published properties are defined inside `properties`. The element's default values are definitely working; you can add
```js
console.log(this._url, this._label, this._active);
```
inside the `ready()` callback and you will see the defined defaults when no attributes are passed in.

I can only assume it's a problem with the unit test..... which I'm unfamiliar with so I can't help you there.

**Comment by torcellite** [comment]
Hmm. Have you tried using the `getAttribute()` function within the `ready()` function of the custom element? That yielded a `null` too.

**Comment by zerodevx** [comment]
You mean `this.getAttribute()`? That should be expected behaviour. If you call your custom element without passing anything in,

index.html
```html
<navbar-button></navbar-button>
```

navbar-button.html
```js
...
properties: {
  _label: { type: String, value: "Google" }, // default value if nothing is passed in
  ...
},
ready: function () {
  console.log(this._label); // ............................(1)
  console.log(this.getAttribute("_label")); // ............(2)
},
...
```
naturally (1) shows `"Google"` and (2) shows `null` (because you didn't actually pass in any data)

If your index.html is
```html
<navbar-button _label="Foobar"></navbar-button>
```
(1) shows `"Foobar"` and (2) shows `"Foobar"`.

If your index.html is
```html
<navbar-button _label="Google"></navbar-button>
```
(1) shows `"Google"` and (2) shows `"Google"`.

**Comment by torcellite** [comment]
My bad, wasn't aware that it was expected behavior. Sorry about that.

You mean this.getAttribute()? That should be expected behaviour. If you
call your custom element without passing anything in,

index.html

<navbar-button></navbar-button>

navbar-button.html

...
properties: {
  _label: { type: String, value: "Google" }, // default value if
nothing is passed in
  ...
},ready: function () {
  console.log(this._label); // ............................(1)
  console.log(this.getAttribute("_label")); // ............(2)
},
...

naturally (1) shows "Google" and (2) shows null (because you didn't
actually pass in any data)

If your index.html is

<navbar-button _label="Foobar"></navbar-button>

(1) shows "Foobar" and (2) shows "Foobar".

If your index.html is

<navbar-button _label="Google"></navbar-button>

(1) shows "Google" and (2) shows "Google".

—
Reply to this email directly or view it on GitHub
<https://github.com/Polymer/polymer/issues/1909#issuecomment-113084223>.

**Comment by tjsavage** [comment]
@torcellite Properties set in the `properties` object are not by default reflected as attributes on the custom element itself. If you'd like to reflect the property value as an attribute you can set `reflectToAttribute: true` on the property settings:

```
properties: {
  label: {type: String, value: "Google", reflectToAttribute: true}
}
```

See this jsbin for more info: http://jsbin.com/yanuto/edit?html,console,output

One thing to be aware of is that camel-cased property keys are automatically set to hyphenated attribute keys - e.g. `myProperty` becomes `<x-element my-property>` as attributes are case-insensitive.

Thanks @zerodevx!

**Comment by torcellite** [comment]
Just a tiny bump. If the data type is `Boolean`, `getAttribute()` returns `null` if `false` and an empty string (i.e. not a `null`) if `true`.
