### ISSUE TITLE
Shady DOM and local style selector renaming

### ISSUE THREAD

**Issue by atoy40** [Polymer/polymer#1918]
Hello,
I created an element which is a simple wrapper on an other javascript library.
this element (call it "my-element") contains a simple :

```html
<div id="mywrapper" class="foo"></div>
```

Then this div is filled with other elements after a call to a function. For example, it append a div childwith axis class :
```html
<div id="mywrapper" class="foo">
  <div class="axis"></div>
</div>
```

The problem is shady dom rewrite my rules selector so :
```.foo .axis```
becomes
```.foo.my-element .axis.my-element```

But in the browser, the .axis div (created programically) isn't modified by shady and looks like :

```html
<div id="mywrapper" class="foo style-scope my-element">
  <div class="axis"></div>
</div>
```
so the rewrited rules doesn't match.
It works perfect if i use shadow DOM.

Anthony.

**Comment by atoy40** [comment]
I found that replacing the selector from ```.foo .axis``` to ```.foo /deep/ .axis``` works with shady and shadow the same way. But is it really a good solution or a side effect ?

**Comment by kevinpschaaf** [comment]
There is an API called `scopeSubtree` provided on Polymer element prototypes to help in this scenario.

After you call into the 3rd-party lib to fill DOM into `mywrapper`, you can call `this.scopeSubtree(this.$. mywrapper)` to have all descendants of the container scoped per shady-dom rules.  Passing `true` as the second argument will set up a mutation observer to ensure any nodes subsequently added (e.g. by the 3rd-party lib) will also be scoped.

You can read the API docs here: http://polymer.github.io/polymer/ (search for `scopeSubtree`).

Give that a try, and feel free to re-open if this didn't solve your problem.  Thanks!

p.s. Note that `/deep/` has been [officially deprecated](https://www.chromestatus.com/features/6750456638341120) by W3C spec and Chrome, so you should not rely on it going forward.

**Comment by atoy40** [comment]
argh, I missed it !
thanks.

**Comment by ybian** [comment]
@kevinpschaaf Seems `scopeSubtree` is removed in 2.0. What am I supposed to do in 2.0 to solve the same issue?
