### ISSUE TITLE
[0.5] Repeat template and one-time binding of index

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#1922]
```html
<template repeat="{{module, index in modules}}">
    <span data-id="[[index]]">{{module}}</span>
</template>
```

I always had bugs with one-time bindings, this is one of them.
`[[index]]` evaluated to empty string, looks like Polymer doesn't understand that it depends on `template[repeat]`.
Relevant to 0.5, not sure how it is implemented in 1.0 since I'm not using it yet.

**Comment by arthurevans** [comment]
Polymer 1.0 doesn't include the concept of one-time bindings, so there's no direct equivalent. 

I suspect the recommended workaround would be to use a standard binding here.

**Comment by nazar-pc** [comment]
I already do so, any chance to be fixed?

**Comment by arthurevans** [comment]
Pretty much all development work is focused on the 1.0 release now. @tjsavage for our exact policy, but I expect fixes to be limited to critical bugs.
