### ISSUE TITLE
Demos not shown in element catalog

### ISSUE THREAD

**Issue by oathcomrade** [Polymer/polymer#1923]
If I select any element in the element catalog and click on _Demo_, nothing is shown. Refreshing the page doesn't help.
The console shows this warning:
[page-element::_annotatedComputationEffect]: compute method `baseURI` not defined

**Comment by kevinpschaaf** [comment]
This issue tracker is for the core Polymer library.  We'll get this moved to the https://github.com/Polymer/polymer-element-catalog/issues tracker.

**Comment by tjsavage** [comment]
This issue was moved to Polymer/polymer-element-catalog#140
