### ISSUE TITLE
Eclipse thinks ".delete" and ".instanceof" are bugs

### ISSUE THREAD

**Issue by salamanders** [Polymer/polymer#1924]
Either polymer shouldn't be using reserved words as object property keys (like instanceof and delete) or Eclipse's javascript is over aggressive for spotting bugs.

Description | Resource | Path | Location | Type
------------|----------|------|----------|------
Syntax error on token ".", , expected | ShadowDOM.js | /myproject/www/bower_components/webcomponentsjs | line 982 | JavaScript Problem
Syntax error on token ".", , expected | ShadowDOM.js | /myproject/www/bower_components/webcomponentsjs | line 983 | JavaScript Problem
Syntax error on token ".", , expected | webcomponents.js | /myproject/www/bower_components/webcomponentsjs | line 1022 | JavaScript Problem
Syntax error on token ".", , expected | webcomponents.js | /myproject/www/bower_components/webcomponentsjs | line 1023 | JavaScript Problem
Syntax error on token "instanceof", Identifier expected | webcomponents-lite.js | /myproject/www/bower_components/webcomponentsjs | line 2194 | JavaScript Problem
Syntax error on token "instanceof", Identifier expected | webcomponents-lite.js | /myproject/www/bower_components/webcomponentsjs | line 2212 | JavaScript Problem
Syntax error on token "instanceof", Identifier expected | webcomponents.js | /myproject/www/bower_components/webcomponentsjs | line 6963 | JavaScript Problem
Syntax error on token "instanceof", Identifier expected | webcomponents.js | /myproject/www/bower_components/webcomponentsjs | line 6981 | JavaScript Problem

**Comment by miztroh** [comment]
Yeah, I'd say Eclipse is being too aggressive.

**Comment by salamanders** [comment]
For reserved words, they could be easily written as .['delete'] and .['instanceof'] - but yea.  Don't know what JS standard is for making syntax checkers and linters happy.

**Comment by kevinpschaaf** [comment]
JavaScript reserved words are only reserved when used as "identifiers" (e.g. `var delete;` is invalid), not "identifier names" such as object keys (e.g. `var obj = { delete: true };` is valid).  

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Reserved_word_usage

As such, this is a problem with Eclipse's linter, not Polymer.  Either way, most linters should allow specifying exclude paths/libs, as most would want to exclude 3rd-party libs and only lint user-written code, so I would recommend excluding these files from your linting setup.
