### ISSUE TITLE
Setting readOnly AND computed on properties

### ISSUE THREAD

**Issue by positlabs** [Polymer/polymer#1925]
Obviously, we can't set a value on a computed property, but setting `readOnly: true` causes the computed property handler to never be called. Maybe there should be some warning, or even an error if a property is configured like this. Or possibly just ignore the `readOnly` flag if `computed` is defined.

```javascript
				_optionLabels: {
					type: Array,
					value: [],
					readOnly: true,
					computed: '_computedOptionLabels(options)'
				},
```

**Comment by kevinpschaaf** [comment]
This is a bug.

The expected behavior is that making a property `computed` should implicitly make it `readOnly`.  Currently it is both not `readOnly` by default, and attempting to make it `readOnly` manually fails as noted.

**Comment by positlabs** [comment]
Nice. Thanks for fixing!
