### ISSUE TITLE
Error with nesting dom-bind templates

### ISSUE THREAD

**Issue by eximius313** [Polymer/polymer#1928]
When I have a template like this:
```
<template id="test-template" is="dom-bind">
	<input type="text" value="{{bug}}" />
</template>
```
and doesn't have the ```bug``` property defined (because its value is unknown yet) then everything is fine.
But when you use this small template inside some other template (I must use composition of templates):
```
<template id="outer-template" is="dom-bind">
	<!-- many other functionalities here -->
	<template id="test-template" is="dom-bind">
		<input type="text" value="{{bug}}" />
	</template>
</template>
```
I get 
```Uncaught TypeError: Cannot set property '_parent_bug' of undefined```
error and whole template is not beeing loaded

**Comment by kevinpschaaf** [comment]
The intended use case for `dom-bind` is to create a context in the main-document inside of which Polymer bindings can be used.  Once you are inside one `dom-bind`, there is no reason to create another.

Is there a reason you are nesting `dom-bind` (this isn't a use case we intended to support)?

**Comment by eximius313** [comment]
First of all (correct me if I'm wrong), I believe that dom-bind is rather expensive element (it has to look and evaluate all expression in its DOM tree), so it is not intended to wrap whole application - it should be rather used on smallest pieces of code that need this functionality?
If yes, then you could easily fall into situation, where you have reusable part of code (e.g. google-map component connected with google-map-search component) and it's wrapped in dom-bind element so you could use it as standalone HTML fragment.
Then it happens, that you must use this component inside another dom-bind element (iron-collapse for example) which - in order to work properly with toggle button - has to be wrapped in another dom-bind element. And this is the case.

**Comment by kevinpschaaf** [comment]
Our focus on Polymer is providing useful features for building new Custom Elements, rather than being a general-purpose templating library.  In web components, Custom Elements, not templates alone, are the first-class unit of reuse, and so we focus heavily on those use cases. 

Currently `dom-bind` does not support nesting other `dom-bind` templates inside of it since that was not its intended purpsoe.  We'll consider that enhancement, but it's likely to be of lower priority.

**Comment by tomalec** [comment]
@eximius313 If you need nested `dom-bind`s because you load the content dynamically, or loaded from external file, you can try
[`imported-template`](https://github.com/juicy/imported-template) custom element, which makes your code works:
http://jsbin.com/dozilu/edit?html,output
```html
<template id="outer-template" is="dom-bind">
  <h1>Outter template</h1>
    <!-- many other functionalities here -->
  <input type="text" value="{{bug::input}}" />
  <template is="imported-template" content='<template id="test-template" is="dom-bind">
        <h1>Inner template</h1>
        <input type="text" value="{{model::input}}" />
    </template>' model="{{bug}}"></template>
    
</template>
```

**Comment by eximius313** [comment]
Thanks!
I'll look at it.

**Comment by eximius313** [comment]
It seems that with newest version of Polymer, nested ```dom-bind``` templates are working ;)
