### ISSUE TITLE
iron-ajax not posting data

### ISSUE THREAD

**Issue by ahumblenerd** [Polymer/polymer#1929]
<dom-module id="my-new-app">
    <style>
    </style>
    <template>
    
      <iron-ajax
          id="ajax"
          handle-as="json"
          content-type="application/json"
          method="POST"
          body={"user":2,"dob":"2015-06-10","jobs":1,"skills":[],"about":"cool"}
          on-response="hresponse"
          debounce-duration="3000">
      </iron-ajax>
      <button on-click="setajax">Click me</button>
    </template>
    <script>
    Polymer({
      is: "my-new-app",
      setajax: function () {
    
          this.$.ajax.url="http://127.0.0.1:8000/users/";
        this.$.ajax.generateRequest();
      },
      hresponse: function(request) {
        console.log(request.detail.response);
        console.log(this.$.ajax.lastResponse);
        console.log(this.$.ajax.params);
      }
    });
    </script>
    </dom-module>

This does not post data correctly to the server. Also when i put in a console.log inside the iron-ajax.html file i found out that contentType was still set as `application/x-www-form-urlencoded` . The documentation says we can specifiy contentype by specifiying `contentType = {String}`.

**Comment by vsimonian** [comment]
The `body` attribute should be wrapped in quotes:

```html
<iron-ajax
  body='{"user":2,"dob":"2015-06-10","jobs":1,"skills":[],"about":"cool"}'
  ...
```

Other than that, I can't seem to replicate the behaviour you're seeing:

![screen shot 2015-06-20 at 1 14 13 pm](https://cloud.githubusercontent.com/assets/9868643/8269086/bac36930-174e-11e5-983a-e687bbf7619a.png)

Mind providing more details?

**Comment by ahumblenerd** [comment]
It works fine when i try to post it to a normal service . But when i try my own backend based on Django Rest Framework it throws out errors . And when i looked into it , Django was receiving application/x-www-form-urlencoded instead of application/json.So I went inside iron-ajax/iron-ajax.html and typed in a console.log() to print all parameters and it was showing that the url encoding was not changing even when i was explicitly specifying .

**Comment by kevinpschaaf** [comment]
This issue tracker is for the core Polymer library, not elements created with Polymer.  We'll get this moved to the right tracker for `iron-ajax`.

**Comment by tjsavage** [comment]
This issue was moved to PolymerElements/iron-ajax#66
