### ISSUE TITLE
Locating dynamic-created Node. $$ vs $.container.querySelector.

### ISSUE THREAD

**Issue by hourliert** [Polymer/polymer#1930]
Hi,

I am using d3 to create a hexagon. When it is inserted in my polymer element, I add an id on it so I could find it later. Here is my complete code :

```
  attached: function() {
      var width = (Math.sqrt(3) / 2) * this.width,
          radius = (this.width + this.height) / 4;

      d3.select(this.$.tile).select('svg').remove();

      var svg = d3.select(this.$.tile).insert('svg', ':first-child')
          .attr('width', width)
          .attr('height', this.height)
          .attr('class', 'fit')
        .append('g')
          .attr('transform', 'translate(' + width / 2 + ',' + this.height / 2 + ')');

      var hexbin = d3.hexbin()
        .radius(radius);

      svg.selectAll('#hexagon')
          .data(hexbin([[0,0]]))
        .enter().append('path')
          .attr('id', 'hexagon')
          .attr('d', hexbin.hexagon(radius - this.margin))
          .style('fill', this.color);
    },

```

On tap on my component, I try to recover the `#hexagon` element to modify its color.

Following the [doc](https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#node-finding), I have tried to do `this.$$('#hexagon')`but I always get undefined.

Whereas if I do `this.$.tile.querySelector('#hexagon')` (`#tile` is the svg container) , it works.

Did I miss something ?
Thanks in advance.

Thomas

**Comment by arthurevans** [comment]
I think what you're seeing here is that d3 is adding children to a node in your element's shady DOM, but it isn't using the `Polymer.dom` methods to do so, which means the d3 nodes exist in a sort of limbo between shady  DOM and light DOM.

There are two challenges here:

-  `Polymer.dom(node).querySelector` (used internally by `$$`) won't find the nodes. Using standard `querySelector` from a node inside the shady DOM (as you did) should work fine here, with (rather small) caveat that standard `querySelector` won't respect the shady DOM boundaries, so _if_ `this.$.tile` contains other Polymer elements, you could possibly get the wrong node. Other than that issue, though, I believe this strategy should work correctly under both shady DOM and native shadow DOM.

-  Shady DOM styles won't get applied to these nodes. You can fix this issue by using `scopeSubtree` (currently only described in the API docs):

http://polymer.github.io/polymer/

This would look something like:

    this.scopeSubtree(this.$.tile, true);

Hope this helps.

**Comment by hourliert** [comment]
Thank you very much. Your answer is very useful. I suspected something like that. Moreover I missed that in the doc : `Note: All DOM manipulation must use this API, as opposed to DOM API directly on nodes.`

So I have created a 'virtual' node with d3 and then inserted it with the Polymer.dom API. It works great !

Here is my modified `attached` method:

```javascript
  attached: function() {
      var width = (Math.sqrt(3) / 2) * this.width,
          radius = (this.width + this.height) / 4;

      var svg = d3.select('body').append('svg')
          .remove()
          .attr('width', width)
          .attr('height', this.height)
          .attr('class', 'fit');

      var g = svg.append('g')
          .attr('transform', 'translate(' + width / 2 + ',' + this.height / 2 + ')');

      var hexbin = d3.hexbin()
        .radius(radius);

      g.selectAll('#hexagon')
          .data(hexbin([[0,0]]))
        .enter().append('path')
          .attr('id', 'hexagon')
          .attr('d', hexbin.hexagon(radius - this.margin))
          .style('fill', this.color);

      Polymer.dom(this.$.tile).insertBefore(svg.node(), this.$.anchor);
    },
```

Thank again. I am closing this issue.
