### ISSUE TITLE
Bindings don't update when paths include notified properties of other elements

### ISSUE THREAD

**Issue by jyasskin** [Polymer/polymer#1931]
http://plnkr.co/edit/RJ4STXnp78qktLOkczkw?p=preview demonstrates the problem. I have an element that fills in its `notify`ed field asynchronously and another element that refers to the first and tries to use the field.

The real system is trying not to make its users understand Polymer, so I'm trying to avoid making them write `<template is="dom-bind">` or use the `{{}}` syntax.

**Comment by peduxe** [comment]
What's the expected value of:
```javascript
fieldElem.field:
```
?

**Comment by jyasskin** [comment]
@peduxe `undefined` for 1s, then `'Field'`.

**Comment by kevinpschaaf** [comment]
The binding system does not currently support binding to sub-properties of elements passed as properties.

Currently, you would need to manually listen for Polymer's conventional `property-changed` events on elements passed into properties, and forward those changes using the `notifyPath` API.  Example:
http://plnkr.co/edit/nxik3xxKHqpDid4SSOTs?p=preview

We will keep this issue open to consider making this more ergonomic, either by providing helper functions to accomplish this, or else detect when a property is set to a `Polymer.Base` subclass and perform the observation automatically.

**Comment by filaraujo** [comment]
+1

**Comment by zacharytamas** [comment]
:+1: This eating my lunch today.

**Comment by sujkh85** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sujkh@naver.com 님께 보내신 메일 <Re: [polymer] Bindings don't update when paths include notified properties of other elements (#1931)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by TimvdLippe** [comment]
This is working now in Polymer 2: http://jsbin.com/savufenuwe/edit?html,console,output

**Comment by TimvdLippe** [comment]
During lunch I realized that my above JSBin is wrong. It should modify the property of the existing element instead of replacing the element. This is the correct JSBin which does show the problem still exists: http://jsbin.com/xitinisexu/edit?html,console,output

**Comment by TimvdLippe** [comment]
Closing this as a documented limitation. For a specific list of how to deal with these changes, check out https://www.polymer-project.org/2.0/docs/devguide/data-system#observable-changes
