### ISSUE TITLE
How to register an element imperatively in 1.0 ?

### ISSUE THREAD

**Issue by nippur72** [Polymer/polymer#1932]
Is it still possible to register elements imperatively ? In 0.5 [there was this possibility](https://www.polymer-project.org/0.5/docs/polymer/polymer.html#imperativeregister) but I haven't found it mentioned it in the new 1.0 docs.

**Comment by timeu** [comment]
https://github.com/Polymer/polymer/blob/master/PRIMER.md#register-element

**Comment by vsimonian** [comment]
Here's a bit of a more comprehensive example which demonstrates how to wire up bindings and set custom styles solely in script: http://jsbin.com/gocirecaze/edit?html,output

That being said, I'm not sure why this would be necessary. It would be best to do this declaratively.

**Comment by nippur72** [comment]
Ok thanks, that's just what I was looking for.

Strangely it doesn't work on IE11, I had to switch to `webcomponents.js` instead of `webcomponents-lite.js`. Is there any particular reason?

Chrome and FF are ok anyway.

**Comment by peduxe** [comment]
@nippur72 fwiw, document.registerElement is not supported in IE

**Comment by peduxe** [comment]
probably the polyfill isn't included in webcomponents-lite

**Comment by nippur72** [comment]
Ok thanks!

**Comment by nippur72** [comment]
@vsimonian: imperative creation is useful in TypeScript ([nippur72/PolymerTS](https://github.com/nippur72/PolymerTS)) because you can have template + code in the same .ts file.
