### ISSUE TITLE
Polymer.Base.async "infinite loop" condition

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer#1933]
Please consider the following contrived usage of `Polymer.Base.async`:

```html
<link rel="import" href="../polymer/polymer.html">
<script>
  function AsyncAlpha() {
    // Queue a task:
    Polymer.Base.async(function() {
      console.log('alpha');

      // Cause a second task to be queued:
      AsyncBeta();

      // Throw an exception before the first task returns:
      throw new Error('ANY ERROR');
    });
  }

  function AsyncBeta() {
    Polymer.Base.async(function() {
      console.log('beta');
    });
  }

  AsyncAlpha();
</script>
```

The above example will cause the first task ("alpha") to be re-called in what is effectively an infinite loop. In order to reproduce this condition, a second task ("beta") _must_ be queued before the first task returns, and an exception _must_ be thrown after the second task is queued but before the first task returns.

**Comment by timeu** [comment]
Yes I had the same issue, when I ported a rather complicated element from 0.5 to 1.0. 
A JS error caused an infinite loop when it was thrown in an async callback.

**Comment by arthurevans** [comment]
Is this a dup of #1759?

**Comment by cdata** [comment]
@arthurevans yes, it's a dupe (sorry!). I looked for potential reports of this bug, but didn't notice #1759 for some reason. Thanks for noticing this :beers:

**Comment by cdata** [comment]
On the other hand, the description of the conditions to produce the error in #1759 is incomplete according to my experience with the bug.
