### ISSUE TITLE
Bower install -> ECONFLICT Unable to find suitable version for polymer

### ISSUE THREAD

**Issue by Frankrafael** [Polymer/polymer#1934]
Hello!

I am trying to add Polymer/paper-elements to my project using bower, but after downloading everything it fails saying:

> ECONFLICT Unable to find suitable version for polymer

My bower.json looks like:

{
    "name": "2StepAuth-web",
    "description": "2StepAuth-web",
    "version": "0.0.0",
    "private": true,
    "dependencies": {
        "polymer": "Polymer/polymer#^1.0.0",
        "jquery": "*",
        "bootstrap": "*",
        "socket.io-client": "*"
    }
}

Now if I run:
<code> bower install --save Polymer/paper-elements </code>
or
<code> bower install --save Polymer/core-icons </code>

like described in <link>https://www.polymer-project.org/0.5/docs/start/usingelements.html</link>

I have this:
![image](https://cloud.githubusercontent.com/assets/5017439/8273330/215d203a-1869-11e5-8b04-15423d2fed59.png)

What I tried so far:
1) Update bower (1.4.1)
2) Clear bower cache (bower cache clean)
3) Delete everything from /bower_components and reinstall

Please let me know if I missed something or if there is anyway I can help!

And sorry in advance if I posted this issue on the wrong section.

Thank you!
Frank

**Comment by MarkDurbin104** [comment]
__In a clean directory, try:__
bower init  __<< just press enter for each question__
bower install --save Polymer/polymer 
bower install --save PolymerElements/iron-elements 
bower install --save PolymerElements/paper-elements 
__and you'll be ready to go.__

**Comment by Frankrafael** [comment]
Hi Mark!

Thank you! You just pointed out the problem!

Acutally I was trying:
<code>bower install --save Polymer/paper-elements</code>
where the correct is 'PolymerElements'
<code>bower install --save <strong>PolymerElements</strong>/paper-elements</code>

Everything works fine now.

Cheers!

Frank

**Comment by MarkDurbin104** [comment]
Hi Frank,

The Google team appear to have moved all of the __Elements__ to the __PolymerElements__ git hub
The way to check is to look in the GitHub repository : 
https://github.com/PolymerElements

Cheers,
Mark.

**Comment by Frankrafael** [comment]
Hi Mark,

Oh, I see, this is also helpful!

Thank you again!

Cheers,
Frank
