### ISSUE TITLE
Polymer 1.0 :Nested dom-repeat templates cannot show the content of a child object

### ISSUE THREAD

**Issue by HamzaouiMounir** [Polymer/polymer#1937]
I want to display an object content(comments) in a post data (using firebase-collection) : Here is the structure of a post in firebase :

"Publication" : {
       "date":"22-06-2015",
 "content" : "post example",
 "comments": {
  //a post has too many comments on it
  }
}
My goal is to add another dom-repeat to show comments but i cannot see anything. Here is the code example(the first template work correctly as i mentioned)

<template is="dom-repeat" items="{{posts}}" as="post">
       
          <template is="dom-repeat" items="{{post.comments}}" as="commentaire">
               <span>{{commentaire.date}}</span>
           </template>
</tempalte>
I followed the Polymer Migration documentation but no results , i would be thankful if there is any solution .

**Comment by kevinpschaaf** [comment]
This is the issue tracker for the Polymer core library, not elements created with it.  We'll move this to a more appropriate location (probably https://github.com/GoogleWebComponents/firebase-element).

**Comment by tjsavage** [comment]
This issue was moved to GoogleWebComponents/firebase-element#33
