### ISSUE TITLE
Observer responds only once?

### ISSUE THREAD

**Issue by masaoliou** [Polymer/polymer#1942]
I am trying to call a method of child custom element. To achieve this, I set the child element's property which is observed by that child element. Hopefully the method of the child element will unconditionally be invoked by its observer.

As shown in the following example, the observer however seems to react only once and ignore the rest of property changes. Am I missing something?

Please repeatedly click on the button.

index.html:

    <!DOCTYPE html>
    <html>
      <head>
        <script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
        <link rel="import" href="my-element.html">
      </head>
      <body>
        <my-element></my-element>
    	<button onclick="SetAge();">Set Age</button> 
    	<script>
    		function SetAge(){
    			document.querySelector("my-element").SetAge();
    		};
    	</script>
      </body>
    </html>

my-element.html:

    <link rel="import" href="bower_components/polymer/polymer.html">
    <link rel="import" href="observe.html">
    <dom-module id="my-element">
    	<template>
    		<observe-age age="[[MyAge]]"></observe-age>
    	</template>
    </dom-module>
    <script>
    	Polymer({
    		is:"my-element"
    		,SetAge:function(){
    			this.MyAge=2;
    		}
    	});
    </script>

observe.html:

    <link rel="import" href="bower_components/polymer/polymer.html">
    <dom-module id="observe-age"></dom-module>
    <script>
    	Polymer({
    		is:"observe-age"
    		,properties:{
    			age:{
    				type:Number
    				,observer:"AgeChanged"
    			}
    		}
    		,AgeChanged:function(n,o){
    			if(typeof n !== "undefined"){
    				alert("I am forced to do some (perhaps the same) work: old="+o+", new="+n);
    				this.age=undefined; //Reset value in order to respond to all succeeding requests.
    			}
    		}
    	});
    </script>

**Comment by timeu** [comment]
I would assume that the observer is only called if the dependent value also changes. 
In your example you are setting a constant value (MyAge=2) so AgeChanged is only invoked once.

**Comment by masaoliou** [comment]
@timeu Exactly! Revising `my-element.html` to:

    <observe-age age="{{MyAge}}"></observe-age>

and `observe.html` to:

            age:{
                type:Number
                ,observer:"AgeChanged"
                ,notify:true
            }

appears to be able to wake up the observer without exception.
