### ISSUE TITLE
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

### ISSUE THREAD

**Issue by schipplock** [Polymer/polymer#1944]
Hi,
I have a problem with polymer 1.0.0:

I tried one of your basic examples but get a warning in firefox 38.0.5:

> mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

I use "webcomponents-lite.min.js" as suggested by the website. In firefox I have a noticeable render lag when I have more than one "component". I tested the same in IE11 and latest Chrome where I don't have a lag at all. But most people use firefox right now.

In my bower.json I have the following dependency:

```
"dependencies": {
    "polymer": "Polymer/polymer#1.0.0"
  }
```

Is there a workaround? I can live with a warning but not with a slow ui. I just played around and haven't built anything serious with it. The lag is approx. 500ms long. The user sees a blank page for approx. 500ms after the site has been fetched from the server. I am the user and I have a fast core i7.

Any help would be great.

Thanks in advance.
Andreas.

**Comment by Pupix** [comment]
AFAIK there's no workaround. 

The problem is caused by webcomponentsjs and not Polymer.

**Comment by aemonge** [comment]
So..... any work-arrounds ?

**Comment by nickbae91** [comment]
+1

**Comment by zoechi** [comment]
Hopefully this will fixed by Firefox by implementing the custom elements features so polyfills aren't necessary anymore.

**Comment by leninmehedy** [comment]
Firefox 38.5.2 is complaining for the below line:
```javascript
object.__proto__ = inherited;
```
in 

```javascript
Polymer.Base.chainObject = function (object, inherited) {
if (object && inherited && object !== inherited) {
if (!Object.__proto__) {
object = Polymer.Base.extend(Object.create(inherited), object);
}
object.__proto__ = inherited;
}
return object;
};
```

**Comment by azakus** [comment]
This will be fixed by Firefox's native implementation of Custom Elements, but it is not something we have control over, and is not a real problem, just a warning Firefox developers put into the browser.
