### ISSUE TITLE
iron-jsonp should not do initialization in ready

### ISSUE THREAD

**Issue by sshumaker** [Polymer/polymer#1950]
the iron-jsonp behavior immediate calls this._loadLibrary() in ready(), which immediately checks libraryUrl. However, ready is called synchronously with creation, so if you want to do this:

  var api = document.createElement('iron-jsonp-library');
  api.libraryUrl = 'https://apis.google.com/js/client.js?onload=%%callback%%';
  api.notifyEvent = 'api-load';

You get an exception thrown.

Suggestion: Wrap the loadLibrary in a this.async call (so it's equivalent to 0.5 domReady), or be even smarter and observe libraryUrl changes.

**Comment by kevinpschaaf** [comment]
Agreed.

This issue tracker is for the Polymer core library, not elements built with it.  We'll get it moved to the right tracker.

**Comment by tjsavage** [comment]
This issue was moved to PolymerElements/iron-jsonp-library#6

**Comment by sujkh85** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sujkh@naver.com 님께 보내신 메일 <Re: [polymer] iron-jsonp should not do initialization in ready (#1950)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
