### ISSUE TITLE
:host([attribute~="value"]) attribute selector do not work

### ISSUE THREAD

**Issue by david-saslawsky** [Polymer/polymer#1952]
Style transformation fails with `:host` attribute selectors like `:host([lang~="en"])` 
It works however with `:host([lang^="en"])` or `:host([lang|="en"])`

Tested on polymer 1.0.4 and Chrome

**Comment by azakus** [comment]
Should be fixed with #3587

**Comment by TimvdLippe** [comment]
Yes this is working properly in Polymer 2: http://jsbin.com/kivucubixo/edit?html,console,output
