### ISSUE TITLE
iron-form and POST method problem

### ISSUE THREAD

**Issue by Krazitchek** [Polymer/polymer#1955]
Hello, i use Polymer starter kit 1.0.2 and i'm trying to use iron-form based on (little) documentation i found.

My method form is "post" and contain only one input.

My form "action" is a PHP script (add.php) showing content of $_GET and $_POST:

```
echo '<pre>';
print_r($_POST);
print_r($_GET);
echo '</pre>';
```

My form component (form_eclp.html) is:

```
<dom-module id="my-form">
    <template>
        <div class="horizontal center-center layout">
            <div>
                <div class="horizontal-section">
                    <form is="iron-form" id="formGet" method="post" action="add.php">
                        <paper-input name="name" label="Name" required></paper-input>
                        <br><br><br>
                        <paper-button raised onclick="clickHandler(event)">Submit</paper-button>
                    </form>
                </div>
            </div>
        </div>
    </template>
    <script>

        function clickHandler(event) {
            Polymer.dom(event).localTarget.parentElement.submit();
        }

        Polymer({
            is: 'my-form',
            listeners: {
                'iron-form-response': 'formResponse'
            },
            formResponse: function(e) {
            	// ?????????
            }
        });
    </script>
</dom-module>
```
I call if from:
```
<link rel="import" href="form_eclp.html">
<my-form></my-form>
```
When i click the submit button after entering the text 'test' in name input, i can see in the network tab of the browser developper tools that it's a POST request, ok, but the url is add.php?name=test, and in the response tab i have:
```
<pre>Array
(
)
Array
(
    [name] => test
)
</pre>
```
According to my form action (add.php script), first array is for $_POST and the second $_GET.

I can see, despite form method="post", it's a "get" request because only $_GET is populated, there is nothing in $_POST.

Have i missed something ?... i don't understand.
![polymer](https://cloud.githubusercontent.com/assets/11500208/8335721/b0caa8d6-1a9f-11e5-96c3-42a0e411b97f.png)

**Comment by kevinpschaaf** [comment]
This issue tracker is for the Polymer core library, not elements created with it.  We'll get this moved to the right issue tracker.  Thanks.

**Comment by tjsavage** [comment]
This issue was moved to PolymerElements/iron-form#18

**Comment by sujkh85** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sujkh@naver.com 님께 보내신 메일 <Re: [polymer] iron-form and POST method problem (#1955)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
