### ISSUE TITLE
Single { and } are sometimes url escaped in attributes

### ISSUE THREAD

**Issue by nhnb** [Polymer/polymer#1960]
If an element is defined inside a binding template or dom-module, single { and } are escape in some cases. As far as I can tell, this is an undocumented behaviour. I cannot find information on how to prevent this. This behaviour breaks custom timesets in &lt;leaflet-map&gt;: leaflet-extras/leaflet-map#22

It feels a lot like PHP's infamous magic quotes. There is no way to tell from inside an element, whether %7B and %7D were intended by the user or automatically escaped by polymer.

More general, this behaviour seems to be triggered based on the name of the attribute. This might have security implication because developers might not understand whether a certain value is escaped or not.

**Testcase:**
~~~~
<template is="dom-bind">

   <a
      href="https://stendhalgame.org/map/3/{z}-{x}-{y}.png" 
      title="https://stendhalgame.org/map/3/{z}-{x}-{y}.png"
      src="https://stendhalgame.org/map/3/{z}-{x}-{y}.png"
      url="https://stendhalgame.org/map/3/{z}-{x}-{y}.png"
      name="https://stendhalgame.org/map/3/{z}-{x}-{y}.png">link</a>

</template>
~~~~

**Expected behaviour:** { and } are unchanged for all attributes

**Actual behaviour:** { and } are url escaped, if the attribute is named href, src or url. It remains unchanges for attributes named name or title.
![escape](https://cloud.githubusercontent.com/assets/364184/8339485/1bb88b64-1ab8-11e5-9401-c4073faf4319.png)

**Comment by JustinCase1089** [comment]
I know it may not be the prettiest solution in the world, but how about allowing the user of the property to use []'s which are then replaced with {}'s inside the element. Then at least the url can be set

**Comment by sujkh85** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sujkh@naver.com 님께 보내신 메일 <Re: [polymer] Single { and } are sometimes url escaped in attributes (#1960)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by kevinpschaaf** [comment]
Per http://tools.ietf.org/html/rfc3986#section-2.3 and https://perishablepress.com/stop-using-unsafe-characters-in-urls/ `{` and `}` are unsafe characters in a URL and must be escaped.

See the following jsBin: http://jsbin.com/rinadu/edit?html,console (no polymer involved).  The parser in Chrome at least appears to automatically escape unsafe characters when parsing attributes known to be URL's.  This is the native parser behavior.

You should use `decodeURI` if you need to read the unescaped value of the URL.
