### ISSUE TITLE
Example text is not selectable.

### ISSUE THREAD

**Issue by scheib** [Polymer/polymer#1961]
Example: https://elements.polymer-project.org/elements/paper-item has text

```
<paper-item>
  <paper-item-body two-line>
    <div>Show your status</div>
    <div secondary>Your status is visible to everyone</div>
  </paper-item-body>
  <iron-icon icon="warning"></iron-icon>
</paper-item>
```

which is not selectable on the page. This breaks copy-paste of example code.

**Comment by arthurevans** [comment]
We should fix this.

**Comment by miztroh** [comment]
@scheib Which browser are you using?  I don't know if I'm misunderstanding the issue, but I can't reproduce this in Chrome, IE, or Firefox.  All three allow me to select, copy, and paste that block of text.

**Comment by scheib** [comment]
Whoops, this is subtle:

Text selectable here:
https://elements.polymer-project.org/elements/paper-item

Text not selectable here:
https://elements.polymer-project.org/elements/paper-item?active=paper-icon-item

Google Chrome	43.0.2357.125 (Official Build) (64-bit)
OS	Linux

**Comment by scheib** [comment]
Latter achieved by clicking "Docs" link on left multiple times.

**Comment by miztroh** [comment]
I still can't duplicate this in Chrome 43.0.2357.130.

**Comment by scheib** [comment]
Repro'd again from Windows 43.0.2357.130 (Official Build) m (32-bit)

Click:
https://elements.polymer-project.org/elements/paper-item?active=paper-icon-item
Mouse left drag over syntax highlighted HTML snippet, or any text on page.

No selected text. 

Double click and a word will be selected.

**Comment by kevinpschaaf** [comment]
We should move this issue to either the [catalog](https://github.com/Polymer/polymer-element-catalog) or [iron-component-page](https://github.com/PolymerElements/iron-component-page) tracker.

**Comment by tjsavage** [comment]
This issue was moved to PolymerElements/iron-component-page#42
