### ISSUE TITLE
Middle clicking 'Docs' and 'Demo' on Catalog pages fails to open content in new tab.

### ISSUE THREAD

**Issue by scheib** [Polymer/polymer#1962]
Middle click should always open content in a new tab. However on pages such as  https://elements.polymer-project.org/elements/paper-item?view=demo:demo/index.html middle clicking the 'Docs' and 'Demo' links in the left navigation panel fails to open a new tab.

**Comment by miztroh** [comment]
This seems like a browser-specific issue.  For example: In Chrome, Ctrl + Left Click opens "Docs" and "Demo" links in new tabs.

**Comment by scheib** [comment]
Chrome:
https://elements.polymer-project.org/elements/paper-item
Middle mouse click "Catalog" at top of the page, new tab opened with
Catalog top page.
Middle mouse click "Docs" on left of page, nothing.
Ctrl-click "Docs", new tab.

**Comment by tjsavage** [comment]
This issue was moved to Polymer/polymer-element-catalog#143
