### ISSUE TITLE
Error message after I updated the polymer library : Failed to execute 'write' on 'Document':It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.

### ISSUE THREAD

**Issue by SophiaBelkin** [Polymer/polymer#1963]
I submitted a ticket last week and it was fixed today. 
https://github.com/Polymer/polymer/issues/1911#event-339478577

I updated my polymer library with the latest version. But I am still having trouble loading the components. 

Here is the new error message: 

custom-style.html:61
Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.

dom-bind.html:46 
Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.

polymer-bootstrap.html:42 
Uncaught TypeError: prototype.registerCallback is not a function

Please let me know if there is anything else I should update. 

Thanks,
Sophia

**Comment by sorvell** [comment]
I can confirm that the issue in #1911, at least, is fixed.

Sorry for the continued trouble. We'll need more information to be helpful. A code snippet or jsbin.com would be ideal. Specifically how are you loading `webcomponents-lite.js` and the components? What browser/version are you using?

Unfortunately, the errors about `document.write` are not helpful. Nothing in the polymer core library calls that method.

**Comment by kevinpschaaf** [comment]
@SophiaBelkin Are you still having an issue here, or can we close it?

**Comment by SophiaBelkin** [comment]
Hi @kevinpschaaf , 

Thanks. You can close this ticket. I will try it again and create amore specific ticket.

Sophia
