### ISSUE TITLE
Multiple content tags in a module

### ISSUE THREAD

**Issue by mdschramm** [Polymer/polymer#1964]
This is a test module that I made:
```html
<link rel="import" href="bower_components/polymer/polymer.html">
 <link rel="import" href="components/test-4.html">

<test-4 testbool="">
  <span>inside content</span>
</test-4>
```

...

```html
<dom-module id="test-4">
  
  <template>
    
    <template is="dom-if" if="{{testbool}}">
      <p>content 1</p>
      <content></content>
    
    </template>
    
    <template is="dom-if" if="{{!testbool}}">
      <p>content 2</p>
      <content></content>
    
    </template>
  </template>
</dom-module>
<script>
  Polymer({
    is: 'test-4',
    
    properties: {
      testbool: {
        type: Boolean,
        value: true
      }
    }
    
  });
</script>
```
when rendering it outputs:
```
content 1

inside content
```
I was expecting to get:
```
content 2

inside content
```
Polymer seems to be ignoring the dom-if templates here. In absence of the dom-if templates, only content 1 shows up.

**Comment by sujkh85** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sujkh@naver.com 님께 보내신 메일 <[polymer] Multiple content tags in a module (#1964)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by MarkDurbin104** [comment]
use:
`<test-4 testbool>
  <span>inside content</span>
</test-4>`
or 
`<test-4 >
  <span>inside content</span>
</test-4>`
__not:__
`<test-4 testbool="">
  <span>inside content</span>
</test-4>`

**Comment by sujkh85** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sujkh@naver.com 님께 보내신 메일 <Re: [polymer] Multiple content tags in a module (#1964)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by sorvell** [comment]
When the `testbool` property is given `type: Boolean` this is an indication to Polymer that the corresponding attribute should be treated as a [boolean attribute](http://www.w3.org/TR/html4/intro/sgmltut.html#h-3.3.4.2). Boolean attributes are considered true if the attribute is present and false if it is not. Therefore `testbool=""` results in the property `testbool` being `true`. This can be a bit confusing, but we're following the web platform convention here.

I believe this explains the behavior you're seeing. I'll leave the issue open for confirmation, but it seems that the `dom-if` usage is not relevant. Here's a jsbin of the example in case you'd like to modify it:

http://jsbin.com/rusiwo/edit?html,output

**Comment by kevinpschaaf** [comment]
@mdschramm Can you confirm whether you're still having an issue, or if we can close this?  Thanks!

**Comment by azakus** [comment]
Closed due to age, please reopen if this is still a problem.
