### ISSUE TITLE
hidden="{{!value}}" not binding properly

### ISSUE THREAD

**Issue by thepeoplesbourgeois** [Polymer/polymer#1965]
The docs specifically call this out as a valid usage :cry: 
With `required: Boolean` defined inside of properties (also tried renaming the property to `necessary`)

```
<!-- Polymer declaration -->
  <template>
    <label>
      <div id="message">
        <span hidden="{{!required}}">*</span>
        <span id="name">{{name}}</span><span hidden$="{{valid}}">:</span>
  ...

<!-- usage in demo.html -->
  <text-field name="username" required></text-field>
  <text-field name="phone number"></text-field>
  <text-field name="zip" required></text-field>
  ...

<!-- result -->
* username
* phone number
* zip
```

**workaround**

```
<!-- Polymer declaration -->
<template>
  <label>
    <div id="message">
      <span hidden="{{unrequired}}">*</span>
      <span id="name">{{name}}</span><span hidden$="{{valid}}">:</span>
...

... <script>
attached: function(){
  this.unrequired = !this.required;
}
...

<!-- result -->
* username
  phone number
* zip
```

**Comment by sujkh85** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sujkh@naver.com 님께 보내신 메일 <[polymer] hidden="{{!value}}" not binding properly (#1965)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by MarkDurbin104** [comment]
try setting your boolean required value:false in the properties.
`properties: {
   required:{type:Boolean,value:false}
}`

**Comment by thepeoplesbourgeois** [comment]
Delightful!  Thanks for the tip.

**Comment by sujkh85** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sujkh@naver.com 님께 보내신 메일 <Re: [polymer] hidden="{{!value}}" not binding properly (#1965)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by robrez** [comment]
just wanted to point out that you didn't use `hidden$` here:

`<span hidden="{{!required}}">*</span>`

I think that could cause some problems for you

**Comment by thepeoplesbourgeois** [comment]
It's my understanding that you use `$=` over `=` in cases where you expect the bound value to change out from underneath you.  With `required` being an attribute set on the top-level element, the asterisk reliably hides and shows as `<custom-element required>` is set and unset.

**Comment by arthurevans** [comment]
@thepeoplesbourgeois to be clear, `foo$="{{hostProperty}}"` sets the target element's `foo` **attribute** to the serialized value of _hostProperty_. So if _hostProperty_ is true, this would show up as:

    <custom-element foo>

The standard binding format `foo="{{hostProperty}}"` sets the target element's `foo` **property** to  _hostProperty_.

Both of them work dynamically (i.e., changing _hostProperty_ updates the binding). However, updating a property is less expensive, and to be preferred unless you really need to set an attribute (for example, for styling or `querySelector`).

**Comment by thepeoplesbourgeois** [comment]
@arthurevans Interesting... Can you clarify how this behavior works with regard to `hidden`?  I just experimented with flipping on a `custom-element[required]` within Web Inspector to see if it would affect the value of `document.querySelector('span[hidden]').length`.  The count incremented for me because a `<span hidden={{!required}}>` was affected.

**Comment by thepeoplesbourgeois** [comment]
@arthurevans Just experimented with setting `span[arbitrary-attribute]` with `$=` and `=`, and I confirmed that the behavior you described on `custom-element` is also true for `decidedly-standard-element`.

It looks as if `hidden="{{foo}}"` is one special case that will set the HTML attribute regardless of whether `$=` or `=` is used.
