### ISSUE TITLE
`notifyPath` doesn't return as its documentation says

### ISSUE THREAD

**Issue by zacharytamas** [Polymer/polymer#1966]
I've been running into lots of problems lately and have been trying to use `notifyPath` to test things and have found that it actually doesn't behave like its documentation says. 

[The documentation says that it returns `true` if the notification actually happens](https://github.com/Polymer/polymer/blob/master/src/standard/notify-path.html#L73) but if you look at the source code, it never actually returns anything and is always undefined.

This isn't very helpful from a debugging standpoint and is also inconsistent with what the [API Reference](http://polymer.github.io/polymer/) says (because this is auto-generated from the source code comment which is incorrect).

It would be nice if we could get a `return true` as the documentation states. In my case, my calls to `notifyPath` where not actually causing events but it was hard to determine that.

**Comment by sujkh85** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sujkh@naver.com 님께 보내신 메일 <[polymer] `notifyPath` doesn't return as its documentation says (#1966)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by kevinpschaaf** [comment]
PR: #1991

**Comment by zacharytamas** [comment]
Thanks @kevinpschaaf
