### ISSUE TITLE
Path change notifications on shared objects not propagating completely

### ISSUE THREAD

**Issue by zacharytamas** [Polymer/polymer#1967]
[The documentation on data binding](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html) states this about when to elements are bound to the same path on an object:

> When two elements are bound to the same path of a shared object and the value at that path changes, the new value is immediately visible to both elements, because both elements are accessing the same object.

> In this case, the element that changed the path must notify the system so that other elements that have registered interest in the same path may take side effects. Path bindings notify the system automatically. Imperative code must call set.

I've noticed that in this case these 2+ elements are sharing a reference to the same JavaScript object. Thus when when you make a change to that object it is visible to all of them whether they are aware of the change or not. Because of this, you have to manually notify the system by calling `set` or by using a path binding, which handles the notification for you.

The problem I'm running into though, is I have an object bound inside a `dom-repeat`. When the change arrives, the `dom-repeat` calls `notifyPath` which [checks the old value against the new value](https://github.com/Polymer/polymer/blob/master/src/standard/notify-path.html#L82). Because they share an object reference, the "old" value is _already_ the "new" value (because JavaScript), and so the propagation stops because Polymer figures that this element already knows. But in this case, the element does not know: the value of a key of its object changed but it is oblivious.

I've stepped through this in the debugger and have observed that `old` is `new` in the `notifyPath` call. If I pause between them and change the value of the `old` variable to anything, the change propagates completely. 

I'm not sure what a good resolution is as I understand this is a complex situation and the current code is in place for efficiency for communicating the change throughout the graph. It's more performant to not notify a node in the graph that seems to already know, similar to a graph search algorithm. It's just in this case my element does not actually know about changes to objects it holds a reference to. :frowning:

**Comment by sujkh85** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sujkh@naver.com 님께 보내신 메일 <[polymer] Path change notifications on shared objects not propagating completely (#1967)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by sorvell** [comment]
I'm not quite sure I follow the use case. Specifically is the notification not propagating to some usage outside the dom-repeat or another item inside the dom-repeat? Is the shared object a sub-path of the repeated array or are the items themselves duplicated (e.g. [objectA, objectA] or [{a: objectA}, {b: objectA}])?

It'd be great to get a [jsbin](http://jsbin.com/refawe/1/edit?html,output) of the basic issue. Thanks.

**Comment by sjmiles** [comment]
I believe this question was resolved here: http://stackoverflow.com/questions/31079535/bindings-when-elements-are-bound-to-same-object-in-memory/
