### ISSUE TITLE
Polymer Paper Element not displaying correctly in Safari

### ISSUE THREAD

**Issue by kenliao94** [Polymer/polymer#1971]
Hi,

I acknowledged that Paper Elements are depreciated in Polymer 0.9 +. However, when I used Paper element in Safari v8.0.6 with Polymer 0.5.6. The paper-tabs not displayed correctly on Safari. On Safari, the paper tabs are not flex but rather clustered in 2/3 of the width of scree. When you clicked the third tab, it will shrink. On Chrome, it displays perfectly. If you would want to check the source code, feel free to look it up on https://github.com/kenliao94/picalory.git. That is a Node.js app using Handlebars as template engine. The page uses the tabs is under /views/layout/main.handlebars. Please see the pictures attached below. I think Paper Elements looks really cool and hopefully I can use it on Safari.for the future. 
![chrome](https://cloud.githubusercontent.com/assets/6269022/8390237/64601994-1c58-11e5-8460-06cfec91e8fb.png)
![safari](https://cloud.githubusercontent.com/assets/6269022/8390239/700ac078-1c58-11e5-8047-4b8203978e08.png)

**Comment by tjsavage** [comment]
Hi @kenliao94 - as you noted, it's highly recommended that you try upgrading to the latest 1.0 versions of the library and the elements.

The new 1.0-compatible elements are in https://github.com/polymerelements - you can browse the available elements at https://elements.polymer-project.org

**Comment by kenliao94** [comment]
Hi @tjsavage . Thanks for replying. I really like what Google is doing !
