### ISSUE TITLE
DOM API innerHTML adds only first element

### ISSUE THREAD

**Issue by SmokyBob** [Polymer/polymer#1972]
[JSbin + workaround](http://jsbin.com/rufuge/edit?html,output)

When trying to set a inner HTML only the first element is added to the node. 
`Polymer.dom(node).innerHTML = "<div>added</div><div>missing</div>"`

A work around is to wrap the new html inside a div (see JS bin)

I think the culprit is [this](https://github.com/Polymer/polymer/blob/master/src/lib/dom-api.html#L617) that uses `e.nextSibling`.

I think the for should loop over `d.children` or I miss something (ex. performance reason, etc...)?

**Comment by Imskull** [comment]
I had similar problem, I solved it by adding `Polymer.dom.flush()` in the loop, may that works for you as well.

**Comment by kevinpschaaf** [comment]
```js
              for (var e=d.firstChild; e; e=e.nextSibling) {
                this.appendChild(e);
              }
```

@sorvell In the case that the container does not require distribution, composition is fast-pathed and `e` is inserted into the composed DOM, rendering `e.nextSibling` null.  Should probably capture an array copy of `children` and iterate that as @SmokyBob suggested.
