### ISSUE TITLE
with Polymer#1.05-update, style-sheets and custom-style-elements are not parsed in my project anymore

### ISSUE THREAD

**Issue by fooloomanzii** [Polymer/polymer#1974]
I think, I kept following rules for mixins and css-variables but console says "Uncaught TypeError: Cannot read property 'trim' of undefined"
Everything is fine with my style-sheets with Polymer#1.04, and I don't see anything wrong in my code
https://github.com/Fairyon/webvisual/tree/develop/src/public/css

**Comment by sorvell** [comment]
Thanks for finding this issue. We'll correct it in the next release. In the meantime, here is a workaround, remove all the new lines following `:` in this rule: https://github.com/Fairyon/webvisual/blob/develop/src/public/css/app-theme.html#L320.

**Comment by fooloomanzii** [comment]
Thank you so much, without this certain mixin, it's working

**Comment by robertavram** [comment]
Is this problem back? After I run `gulp serve:dist` I'm getting ```Cannot read property 'trim' of undefined```
![screen shot 2015-12-04 at 5 54 23 pm](https://cloud.githubusercontent.com/assets/5633041/11603502/1c2a1036-9ab0-11e5-9a50-6b14f92e69e3.png)

This is with Polymer Starter Kit 1.2.3

Thanks,
