### ISSUE TITLE
Mention the requirement to install iron-input using bower

### ISSUE THREAD

**Issue by VikramTiwari** [Polymer/polymer#1977]
The documentation skips this part and hence if someone is following the documentation to the point they are unable to get the final step.

Screenshot: 
![screen shot 2015-06-27 at 21 51 43](https://cloud.githubusercontent.com/assets/1330677/8395193/ed64424c-1d16-11e5-9b0b-d127d484c39b.png)

**Comment by tjsavage** [comment]
This issue was moved to Polymer/docs#1237
