### ISSUE TITLE
Append and Remove Child Element Error

### ISSUE THREAD

**Issue by section14** [Polymer/polymer#1979]
I'm writing a "content loader" element that imports html documents depending on the current page. Depending on the `filePath` that is provided to the element, it's goal is to remove any existing children, and add a new child anytime that `filePath` changes.

The element is functioning correctly until I repeat an import. For instance, I can visit pages in this order and it's fine:

Home -> About Us -> Contact

However, as soon as I go back to Home or About Us from contact, I get this error: 

`Uncaught TypeError: Cannot read property '_lightParent' of null
Polymer.DomApi.DomApi._removeNodeFromHost @ polymer-mini.html:587
Polymer.DomApi.DomApi.appendChild @ polymer-mini.html:460(anonymous function) @ content-loader.html:60`

The order is irrelevant, btw. I can import pages in any order, and the error triggers as soon as I repeat an import.

Here's the element code:

```javascript
<dom-module id="content-loader">

    <template>
        <div id="pageContent"></div>
    </template>

    <script>

    Polymer({

        is: "content-loader",

        properties: {
            filePath: {
                type: String,
                observer: "loadFile"
            },

            currentContent: {
                type: String
            }
        },

        loadFile: function() {
            var baseUrl;

            if (!window.location.origin)
            {
                baseUrl = window.location.origin = window.location.protocol + "//" + window.location.hostname + (window.location.port ? ':' + window.location.port: '');
            }
            else
            {
                baseUrl = window.location.origin;
            }

            //import html document and append page content
            if(this.filePath)
            {
                //unload any content already loaded
                if (this.currentContent)
                {
                    //attempt #1
                    var firstChild = Polymer.dom(this.$.pageContent).firstChild;
                    Polymer.dom(this.$.pageContent).removeChild(firstChild);

                    //attempt #2
                    Polymer.dom(this.$.pageContent).removeChild(this.currentContent);
                    //Polymer.dom.flush(); //tried this, no change
                }

                this.importHref(baseUrl + this.filePath, function(link) {
                    this.currentContent = link.target.import.body;
                    Polymer.dom(this.$.pageContent).appendChild(this.currentContent); //line 60
                    //Polymer.dom.flush(); //tried this, no change
                },
                function(error){
                    console.log(error);
                });

            }
        }

    });

    </script>

</dom-module>
```

Both attempts to remove children (not ran at the same time, of course) return the same result.

My questions are: Is this approach correct for dynamically loading in HTML pages with Polymer? If it is, how do I properly reference a created child node, and remove it before adding a new node in it's place?

**Comment by bruunofco** [comment]
Hello, can provide a simple example in Plunker?

**Comment by section14** [comment]
I've fixed this issue by using `iron-ajax` to load the page instead. Scratching my head as to why I didn't go this route to begin with. Perhaps the documentation can be updated with a footnote that suggests using `iron-ajax` for loading page content, where `importHref` lends itself more towards dynamically adding `<link rel="import" href="polymer-element.html">` to a page.

Here's the working element:

```javascript
<dom-module id="content-loader">

    <template>

        <iron-ajax
            id = "contentReq"
            on-response = "loadContent"
            on-error = "loadError"
        ></iron-ajax>

        <div id="pageContent"></div>

    </template>

    <script>

    Polymer({

        is: "content-loader",

        properties: {
            filePath: {
                type: String,
                observer: "loadFile"
            },

            currentContent: {
                type: String
            }
        },

        loadFile: function() {
            var baseUrl;

            if (!window.location.origin)
            {
                baseUrl = window.location.origin = window.location.protocol + "//" + window.location.hostname + (window.location.port ? ':' + window.location.port: '');
            }
            else
            {
                baseUrl = window.location.origin;
            }

            //request html document
            if(this.filePath)
            {
                this.$.contentReq.url = baseUrl + this.filePath;
                this.$.contentReq.method = "GET";
                this.$.contentReq.handleAs = "document";
                this.$.contentReq.debounceDuration = "500";
                this.$.contentReq.generateRequest();
            }
        },

        loadContent: function() {
            if(this.currentContent)
            {
                //remove existing content
                Polymer.dom(this.$.pageContent).removeChild(this.currentContent);

                //load new content
                this.currentContent = this.$.contentReq.lastResponse.body;
                Polymer.dom(this.$.pageContent).appendChild(this.currentContent);
            }
            else
            {
                //load new content
                this.currentContent = this.$.contentReq.lastResponse.body;
                Polymer.dom(this.$.pageContent).appendChild(this.currentContent);
            }
        },

        loadError: function() {
            console.log("error loading file");
        }

    });

    </script>

</dom-module>
```

**Comment by kevinpschaaf** [comment]
The problem in your original code was with these lines:
```js
this.currentContent = link.target.import.body;
Polymer.dom(this.$.pageContent).appendChild(this.currentContent);
```
Nodes can only ever be children of _one_ tree at a time  Hence, the `<body>` that came from your import was originally part of the import document, but the moment you call `appendChild` into another tree (your element's `pageContent`), it is removed from the import document.  Thus, the second time you import the same document, the import document is reused (a feature of HTMLImports) and no longer has a body, so `link.target.import.body` returns null.

You could have worked around the issue by placing the import content in a `<template>`, and using `document.importNode(template.content, true)` so that the import document remains inert and non-upgraded, and each time you clone a copy of the content that immediately upgrades.

Using ajax is probably fine as well, although note that it relies on the network cache from incurring multiple network fetches and may result in re-parsing of the content (depending on how smart the browser implementation is), whereas using imports ensures only one fetch is made and the document is only parsed once.

**Comment by section14** [comment]
Thanks for the detailed description. I may have spoke too soon declaring the AJAX method as the solution. While it imported the html file just fine, Polymer elements (custom, or part of the elements library) would not work this way. Not sure if this is a local / light DOM related issue, but when importing it via `iron-ajax` any Polymer based elements in the imported document would not render to the screen. Not sure if this should be opened as an issue of it's own, or if that's by design.

I was able to get a version of your suggested method to work:

```javascript
this.importHref(baseUrl + this.filePath, function(link) {
    var importedDocument = link.target.import.body;
    this.currentContent = document.importNode(importedDocument, true);

    Polymer.dom(this.$.pageContent).appendChild(this.currentContent);
 },
    function(error){
        console.log(error);
});
```

It imports the document, all the elements on imported pages work, and there aren't any extra network calls as a result of changing pages. Win!

There are instances where I'd like to delay rendering data, and the template tag seems to fit that need perfectly. However, I couldn't figure out the syntax to achieve this. Specifically, when I wrapped the html file I wanted to import in a `<template>` tag. I couldn't get the data from it. I tried all of these using the same syntax as above:

```javascript
 var importedDocument = link.content;
 var importedDocument = link.target.content;
 var importedDocument = link.target.import.content;
 var importedDocument = link.head.content; //chrome showed the template in the head when viewing the tree
```

Generally, it wouldn't render, was `undefined` or I got the error:
`Uncaught TypeError: Failed to execute 'importNode' on 'Document': parameter 1 is not of type 'Node'.`

**Comment by kevinpschaaf** [comment]
You should do something like:

```js
this.importHref(baseUrl + this.filePath, function(event) {
  var link = event.target;
  var template = link.import.querySelector('template');
  this.currentContent = document.importNode(template.content, true);
  ...
}
```

Explanation:

The argument to the `importHref` callback is the `load` event from a generated HTML Import  (`<link rel="import">` element), so `event.target` is that link.  `link.import` is the document in the imported file.  You can then run `querySelector` on that document to find the template (customize the selector as needed if you need multiple templates, for example).  `template.content` is the DocumentFragment of the template containing the inert DOM of the template.  Finally, you need to call `document.importNode(template.content, true)` to "import" and upgrade the inert nodes from the template into the main document so that they can be inserted into the main document.

**Comment by kevinpschaaf** [comment]
I'll go ahead and close this, but feel free to re-open if you have further questions.
