### ISSUE TITLE
Allow bindings to non-Polymer element properties.

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer#198]
Polymer can create bindings to published properties of Polymer elements, but it can't create bindings to element properties in general. There should be support in the binding syntax for denoting that an attribute name used in a binding really represents a property, not an attribute, similar to how attribute names starting with "on-" indicated a binding of an event handler.

See this lengthly discussion on polymer-dev@: https://groups.google.com/d/msg/polymer-dev/eAA0SeVu-8E/OO59I6ZyNwEJ

A possible encoding would be a "this.", ".", ":", or "prop-" prefix:

``` html
<template>
  <x-not-a-polymer-element this.myproperty="{{ foo }}">
</template>
```

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) release of Polymer - please feel free to re-open if this is incorrect.
