### ISSUE TITLE
Older code in documentations

### ISSUE THREAD

**Issue by VikramTiwari** [Polymer/polymer#1980]
![screen shot 2015-06-28 at 20 12 45](https://cloud.githubusercontent.com/assets/1330677/8400381/4f22175a-1dd2-11e5-97c4-6dda2a1e6cf5.png)

Remove core-icon

**Comment by ebidel** [comment]
What page is this on?

**Comment by arthurevans** [comment]
Looks like the paper-button API docs.

This appears to be fixed in master, so should get fixed with the next catalog update.

**Comment by VikramTiwari** [comment]
@ebidel https://elements.polymer-project.org/elements/paper-button

**Comment by tjsavage** [comment]
Catalog has been updated with the latest element releases
