### ISSUE TITLE
Child's attached is never called when parent doesnt have an insertion point

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#1984]
Given a element definition without an insertion point:

```
<dom-module id="my-parent">
  <template>
    <span>parent</span>
  </template>
</dom-module>
```

`my-a`'s `attached` callback never gets called:

```
<my-parent>  
  <my-a></my-a>
</my-parent>
```

Repo: http://jsbin.com/benorosage/edit?html,console,output

Notes:
- `my-a.attached` is called under native shadow dom 
-  `my-a.attached` is called under shady dom, but changing `my-parent` to have an insertion point (e.g. `<content>parent</content>`)

Somewhat related to #1622.

**Comment by TimvdLippe** [comment]
Fixed in Polymer 2: http://jsbin.com/zehuvufezu/edit?html,console,output
