### ISSUE TITLE
Take advantage of Backbone Event Notation

### ISSUE THREAD

**Issue by azumbrunnen** [Polymer/polymer#1985]
Really love the way we can write components. However, I think it could be useful to have more fine grained control over the events setup.

```html
<my-element>
  <ul>
     <template is="dom-repeat" items="{{items}}">
         <li>one</li>
         <li>two</li>
     </template>
</ul>
</my-element>
```
How about adding events like this:

```js
listeners: {
    'click li', 'handleClick'
}
```

Let me know what you think.

**Comment by kevinpschaaf** [comment]
I understand what you're asking for is slightly different, but just want to make sure you're aware of [annotated event listeners](https://www.polymer-project.org/1.0/docs/devguide/events.html#annotated-listeners) (as opposed to [host listeners](https://www.polymer-project.org/1.0/docs/devguide/events.html#event-listeners)) you can place in the template, like so:
```html
     <template is="dom-repeat" items="{{items}}">
         <li on-tap="{{handleTap}}">{{item.text}}</li>
     </template>
```

**Comment by azumbrunnen** [comment]
Yes thank you. I was aware of this notation I just thought the other notation could potentially help to keep the templates a little simpler with less functionality in it.
