### ISSUE TITLE
Need 0.5 -> 1.0 help please

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#1990]
How do I get rid of the remaining dom-module into a polymer mixin class or something?

```html
<dom-module id="forward-button" icon="arrow-forward" on-tap="toggle" extends="paper-icon-button">
</dom-module>

<script>
    Polymer({
        is: 'forward-button',
        properties: {      
            items: Array,        
            activePage: Number            
        },
        toggle: function() {
            var p=parseInt(this.activePage)
            p = (p+1) % this.items.length
            location.hash = '#!/1/'+p
        }
    });
</script>
```

**Comment by kevinpschaaf** [comment]
Polymer 1.0 [does not yet support inheritance of other custom elements](https://www.polymer-project.org/1.0/docs/migration.html#inheritance), only native elements.

As such, there are other techniques you can use instead: 

For example, you could use composition rather than inheritance (e.g. _has a_ vs. _is a_); i.e. make `forward-button` contain an `iron-icon-button`, and facade any `iron-icon-button` API on `forward-button` as necessary.

```html
<dom-module id="forward-button">
  <template>
    <iron-icon-button icon="arrow-forward" on-tap="{{toggle}}"></iron-icon-button>
  </template>
</dom-module>

<script>
    Polymer({
        is: 'forward-button',
        properties: {

            items: {
                type: Array,
                notify: true
            },

            activePage: {
                type: Number,
                notify: true
            },

        },
        toggle: function() {
            var p=parseInt(this.activePage)
            p = (p+1) % this.items.length
            location.hash = '#!/1/'+p
        }
    });
</script>
```

Alternatively, you can use a decorator pattern where `forward-wrapper` catches the `tap` event from an `iron-icon-button` that the user places inside of `forward-wrapper`, to avoid having to facade all of `iron-icon-button`'s API through.

```html
<script>
    Polymer({
        is: 'forward-wrapper',

        listeners: {
          tap: 'toggle'
        },

        properties: {

            items: {
                type: Array,
                notify: true
            },

            activePage: {
                type: Number,
                notify: true
            },

        },
        toggle: function() {
            var p=parseInt(this.activePage)
            p = (p+1) % this.items.length
            location.hash = '#!/1/'+p
        }
    });
</script>
```
```html
<forward-wrapper>
  <iron-icon-button icon="arrow-forward"></iron-icon-button>
</forward-wrapper>
```

Hope that helps.

**Comment by gertcuykens** [comment]
Thanks :D ps what about something like this?

<paper-icon-button icon="arrow-forward" behaviors="{{forward-behavior}}"></paper-icon-button>

**Comment by kevinpschaaf** [comment]
Unfortunately that won't work.  Behaviors are only mixed in at registration time, not instance time, for performance reasons.

**Comment by gertcuykens** [comment]
Ok got it, thank you :)

**Comment by mercmobily** [comment]
@arthurevans You are going to hate me... but... wouldn't this make a _great_ little chapter for the official documentation? Would you like me to give it a go, and use this code as template for a nice explanation of "using the decorator pattern rather than inheritance"?

**Comment by arthurevans** [comment]
Inheritance is actually supposed to arrive in the not-too-distant future, so this might not be the best place to focus efforts.

These are all still useful strategies, but we don't have a great place to discuss them at present.
