### ISSUE TITLE
Ready Event not firing with dom-repeat directive

### ISSUE THREAD

**Issue by azumbrunnen** [Polymer/polymer#1994]
```js
  <template>
    <ul class="user-list">
      <template is="dom-repeat" items="{{items}}">
        <li on-click="openBackground">
          <paper-ripple style="pointer-events: none; color: #4285f4;"></paper-ripple>
          <a href="[[item]]">{{item}}</a>
        </li>
      </template>
    </ul>
  </template>
```

The following markup with dom-repeat directive will not fire a ready event once all its elements are rendered. Therefore I can't run cascading animations on every LI since they are not available in this moment yet.

**Comment by kevinpschaaf** [comment]
`dom-repeat` renders lazily, but fires a `dom-change` event after the initial render (and any subsequent modifications to the rendered DOM).  You can catch this with an `on-dom-change="doAnimation"` annotated event listener and perform work on the rendered DOM  in `doAnimation`.

Alternatively, you can call `render()` on `dom-repeat` to force it to render, e.g. from the `ready` callback of the element that owns the template.

Can you try one of these and report back?  Thanks.

**Comment by azumbrunnen** [comment]
Thanks! Yes the problem ocurred when I was trying to setup neon elements with cascaded animations. The API seems to be a little tricky to understand and the animated nodes didn't exist yet when animationConfig was parsed. I guess I just have to figure out another way. on-dom-change="setAnimationConfig" or something.

Thanks anyways for the reply!
