### ISSUE TITLE
@apply() Custom CSS Mixin fails LESS Parse

### ISSUE THREAD

**Issue by mflorence99** [Polymer/polymer#1999]
Apologies if this is the wrong place to ask:

I tried to use the @apply() syntax as documented [here](https://www.polymer-project.org/1.0/docs/devguide/styling.html).

I am building stylesheets in LESS v3.

The @apply() causes the LESS preprocessor to choke.

Does anyone have a work around for this? Many thanks!

**Comment by herkulano** [comment]
Sass supports custom at-rules. 
Although you have to compile with ruby, libsass doesn't support them yet.  
https://github.com/sass/libsass/issues/1263

**Comment by mflorence99** [comment]
Many thanks for that suggestion! Let me close this issue and express in another what I found.
