### ISSUE TITLE
Array registration

### ISSUE THREAD

**Issue by fooloomanzii** [Polymer/polymer#2005]
My Element can't find the Array, what was initialized like here.
![image](https://cloud.githubusercontent.com/assets/9318952/8461337/34dd68f2-202c-11e5-9eb1-d4d0dc57dd49.png)
![image](https://cloud.githubusercontent.com/assets/9318952/8461325/1ecaed00-202c-11e5-9e7a-090fe9d7d72d.png)
![image](https://cloud.githubusercontent.com/assets/9318952/8461407/8ea5c028-202c-11e5-8f8d-d4c86d0a65d3.png)
Tried to work arround by using the attached key and the async function.
I'm trying to watch change on inner values of that Array, but it's a pity, that it doesn't work.

**Comment by fooloomanzii** [comment]
When I initialize it through 
![image](https://cloud.githubusercontent.com/assets/9318952/8461703/d83010de-202e-11e5-961b-fcdfb04a9006.png)
Then the array gets filled, but I still cannot watch if an array, what is in the upper array was modified or not, allthough I also fill it, like above, with the atandard array methods https://www.polymer-project.org/1.0/docs/devguide/properties.html#array-mutation

**Comment by kevinpschaaf** [comment]
@fooloomanzii  I wasn't able to reproduce the issue here (using `setInterval` and dummy data to mimic socket.io in your example: http://jsbin.com/motida/edit?html,output

Maybe you can try to modify that jsBin to more closely match your problem and try to reproduce the issue?

**Comment by fooloomanzii** [comment]
Yes, I'm sorry for putting up this request. It seems, that the problem was in the rest of my code, that another element did request the first array-element, before it excisted by two-way-binding. I modified your example, for structured data, and it still works: http://jsbin.com/xofuya/edit?html,console,output
Sorry for that and thank you for your time
