### ISSUE TITLE
Template stamping doesn't work in custom element light DOM

### ISSUE THREAD

**Issue by nomego** [Polymer/polymer#2010]
Considering the following code:

```js
var appendTo = this.$.myCustomElement,
  t = document.createElement('template', 'dom-bind'),
  span = document.createElement('span');
span.innerHTML = '{{hello}}';
t.content.appendChild(span);
t.hello = 'hey';
```

Appending this to the light DOM won't work:

```js
Polymer.dom(appendTo).appendChild(t);
```

This will only render the template tag with the content within and data-binding placeholders emptied.
The `dom-change` event will actually fire and informs me that the `attached()` callback stuff of the `dom-bind` element actually have been run.
But stamping fails and moving the content outside the template never happens.
Tries with `dom-template` and manual `stamp()` also failed.

It actually needs to be in the local DOM:

```js
Polymer.dom(appendTo.root).appendChild(t);
```

Is this a bug or by design?
Could not find any documentation on this.

**Comment by sorvell** [comment]
I can confirm this issue. Here's a simple test and a workaround:

http://jsbin.com/vagugufowi/1/edit?html,output (see the `//workaround` comment)

We'll try to get this fixed by the next release.

**Comment by sorvell** [comment]
Related to https://github.com/Polymer/polymer/issues/1818.

**Comment by nomego** [comment]
Thank you, and thanks for the workaround.
It would be semantically more accurate to append to the light DOM with consideration of the content.
Also, it's good if this process works the same way for native and custom elements.
