### ISSUE TITLE
Observing of "notify" arrays are not updating consuming templates (dom-repeat)

### ISSUE THREAD

**Issue by faGH** [Polymer/polymer#2012]
When defining an array property on a component and setting its "notify" to be true, if this property is being used in some dom-repeat template, the template would not get updated when a new element has been pushed to the array.

For the time being, a work around was to extend the current array using $.extend and .set the property to the new extended array, after pushing the new element to the extended array.

**Comment by timeu** [comment]
Are you using the [Array mutation methods](https://www.polymer-project.org/1.0/docs/devguide/properties.html#array-mutation) to mutate the array ?

**Comment by faGH** [comment]
Indeed.Push. Apologies if that was not clear from my initial post.

**Comment by kevinpschaaf** [comment]
Can you please post a reproduction case that shows the issue you're having?

I made a simple example here based on what you described which works as expected.  Can you modify this to match your usage that is causing the problem?  http://jsbin.com/luwija/edit?html,output

**Comment by mrdewitt** [comment]
How about this?
http://jsbin.com/fuyogonopa/edit?html,output

**Comment by mrdewitt** [comment]
Oops, made a typo.  I will update again if I can create a repro.

**Comment by mrdewitt** [comment]
OK I made a new demo that has an example of unexpected behavior with dom-repeat in it:
http://jsbin.com/zunimigadi/1/edit?html,output

Seems like PolymerElement.push doesn't cause computed properties or observers to fire properly.

**Comment by faGH** [comment]
:)

**Comment by kevinpschaaf** [comment]
Observers/computing functions normally only run when their dependents/arguments change by `===` equality test.  For objects/arrays, this means the _object/array reference_, not sub-properties of it.  However, Polymer provides a handy wildcard syntax for arguments (e.g. `array.*`) that allow you to perform work when the reference _or_ any sub-property change.

Take a look at the section in the docs on [deep path observation](https://www.polymer-project.org/1.0/docs/devguide/properties.html#deep-observation), which covers the change record you get as the argument, which differs slightly from normal arguments.

I updated your example to work using this syntax.
http://jsbin.com/warufo/edit?html,output

Hope that helps!
