### ISSUE TITLE
Data Binding not working

### ISSUE THREAD

**Issue by steelbrain** [Polymer/polymer#2013]
I am using the latest `Polymer 1.0.5` and using `polymer/polymer.html` version.
```html
<dom-module id="header-cart">
  <template>
    <a data-test="{{count}}" class="maia-button button-small pull-right">View cart {{count}}</a>
  </template>
  <script>
    Polymer({
      is: "header-cart",
      ready: function(){
        console.log(this.count)
      },
      properties: {
        count: {
          type: Number,
          value: 1
        }
      }
    })
    var test = document.createElement('header-cart')
    console.log(test.count)
    test.count = 2
    document.body.appendChild(test)
    window.tmp = test
  </script>
</dom-module>
```
When I run the code above in a browser the `data-test` attribute gets removed completely and `{{count}}` in the html remains unchanged.

**Comment by steelbrain** [comment]
It looks like the data binding doesn't work on `a` tags, 'cause I just wrapped the `{{count}}` in a span tag and it works flawlessly

**Comment by ChiragMoradiya** [comment]
Syntax you are using is for property binding, it's not for attribute
binding. If you want to bind to attribute update template as follows:

<template>
    <a data-test$="{{count}}" class="maia-button button-small
pull-right">View cart <span>{{count}}</span></a>
  </template>


Also, notice that I have wrapped {{count}} in <span> tag. Because,
data binding can be done either as 1. Attribute, 2. Property or 3.
TextContent

**Comment by ChiragMoradiya** [comment]
You should refer polymer reference guide on site first. Both rules, I
explained is already well documented there.

**Comment by steelbrain** [comment]
Ah, right, for some reasons they are at the end of the document https://www.polymer-project.org/1.0/docs/devguide/data-binding.html
