### ISSUE TITLE
Property Replacement Quirks

### ISSUE THREAD

**Issue by SumRandomGuy** [Polymer/polymer#2014]
Property replacement does not always work if the replaceable text is not wrapped in tags properly.

This does not work:
(div id="test"){{firstname}} {{lastname}}(/div)

This does:
(div id="test")(span){{firstname}}(/span) (span){{lastname}}(/span)(/div)

Without the tags immediately surrounding the text to be replaced, it does not work.  Even putting a bit of text between the two properties does not resolve the issue:
(div id="test"){{firstname}} testing {{lastname}}(/div)

**Comment by miztroh** [comment]
This is as designed.

https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#binding-to-text-content

"The binding annotation must currently span the entire content of the tag ... String concatenation is not supported inside a tag, and the tag can’t contain any whitespace".

**Comment by SumRandomGuy** [comment]
Mystery solved.

Thanks!
