### ISSUE TITLE
Remove the link underline

### ISSUE THREAD

**Issue by IonicaBizau** [Polymer/polymer#2015]
I suppose that little underline is not supposed to be there! :smile: Somewhere `text-decoration: none;` should be added.

[![screenshot from 2015-07-02 18 58 42](https://cloud.githubusercontent.com/assets/2864371/8481571/7d0580b8-20ec-11e5-8ce6-ddfd5397ae00.png)](https://www.polymer-project.org/1.0/).

**Comment by sorvell** [comment]
This issue tracker is for the core Polymer library, not elements built with it. We'll move this to the appropriate tracker for the element.

**Comment by tjsavage** [comment]
This issue was moved to Polymer/docs#1264
