### ISSUE TITLE
Documentation in paper-radio-group, spelling mistake

### ISSUE THREAD

**Issue by farhaanbukhsh** [Polymer/polymer#2020]
i have attached the screenshot please fix it.

![selection_005](https://cloud.githubusercontent.com/assets/7670449/8498502/fc650e06-21a4-11e5-814e-dc3169183f01.png)

**Comment by sorvell** [comment]
This issue tracker is for the core Polymer library, not elements built with it. We'll move this to the appropriate tracker for the element.
