### ISSUE TITLE
[1.0] I can't get to the on-tap behind a hidden element?

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#2024]
http://jsbin.com/wedogi/edit?html,console,output

I can't get to the on-tap behind a hidden element?

**Comment by LM450N** [comment]
The _hidden_ element is not really hidden. If you remove the `p-test` not hidden from the DOM, you'll still seeing the word "test" surrounded by a red border. Fix this issue and tell us if the _tap_ event is still not fired.

**Comment by gertcuykens** [comment]
Yes but doesn't it suppose to be hidden as in `display none`? I have lots of pages stacked on top of each other in my app?

**Comment by LM450N** [comment]
I guess it's supposed to be hidden. Why you create pages dynamically ? Have you tried to add a section into the [`iron-pages`](https://elements.polymer-project.org/elements/iron-pages) ?

**Comment by ebidel** [comment]
You have a `:host` rule that is taking higher precedence than the `[hidden]` rule.

**Comment by gertcuykens** [comment]
lol I wouldn't found that out in a million years haha thanks :D
