### ISSUE TITLE
Spaces around {{}} breaks interpolation

### ISSUE THREAD

**Issue by Shridhad** [Polymer/polymer#2030]
I came across this following scenario,

* spaces around the `{{}}` breakes interpolation. 
* string interpolation in sentence not working

```html
<dom-element id="my-element">
   <template>
      <div class="element-wrapper">
         <h1>  {{title}}  </h1>
         <span>Hello {{name}}</span>
      </div>
   </template>
</dom-element>
```

Here is what I see as output,

 **{{title}}**
Hello {{name}}

Removing the space around the `{{}}` fixes it.

**Comment by SmokyBob** [comment]
That is the currently expected behavior for dataBindings in 1.0
See [docs](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html), bindings works only when it's the entire content.

To write `Hello {{name}}` you can use a computed property or function.

**Comment by kevinpschaaf** [comment]
As mentioned, this is the current behavior.  String interpolation is on the [near-term roadmap](https://www.polymer-project.org/1.0/docs/#binding-features).
