### ISSUE TITLE
Two-Way Data Binding to new object instance not working. 

### ISSUE THREAD

**Issue by Ermish** [Polymer/polymer#2032]
I'm trying to two-way bind to native elements, and having some trouble with the DOM not updating on change. 

If I have a simple property, it works fine:
`<input type="text" value="{{myData::input}}">`

When I bind to a new object instance and update the binding through javascript, the DOM is not updated:
```
...

<input type="text" value="{{myData.bar::input}}">
<button type="button" on-click="changeBar">Update Me!</button>

...

var Foo = function(){
    this.bar = "polymer";
}

 Polymer({
            is: 'my-object',
            properties: {
                myData : {
                    type: Object,
                    notify: true,
                    readOnly: false
                }
            },
            ready: {
                  this.myData = new Foo();
            },
            changeBar: function(){
                  this.myData.bar = "poly";
            }

```

When I check `this.myData.bar`, it shows up `= "poly"`. However, the DOM is still showing `polymer`.
Also, the changed events are not bubbling up to the parent component.

I've also tried writing the javascript Foo module in several different ways.

Polymer version: 1.0.5/1.0.6

Thanks in advance!

**Comment by ChiragMoradiya** [comment]
Instead using

this.myData.bar = "poly";

try

this.set('myData.bar', 'poly');

**Comment by wesleycho** [comment]
Verified that works [here](http://embed.plnkr.co/m1xDtKirb1JlRuZvqTfs/preview) (source code can be viewed [here](http://plnkr.co/edit/m1xDtKirb1JlRuZvqTfs))

**Comment by ebidel** [comment]
Can you close if that solution is working for you?

**Comment by Ermish** [comment]
Thanks, that works! 
I'll close this, but is `set('', '')` the only way to set the values through js? I'd prefer something less stringly typed.

**Comment by ebidel** [comment]
There are some other ways listed on https://www.polymer-project.org/1.0/docs/devguide/properties.html#observing-path-changes

**Comment by Ermish** [comment]
Thanks, Eric. I'll take a look.
