### ISSUE TITLE
ScrollEvent on HeaderPanel

### ISSUE THREAD

**Issue by azumbrunnen** [Polymer/polymer#2034]
Let's say you a build an application with components that need to observe the scroll position to implement sticky behaviors etc. Since using HeaderPanel will not use the window element but it's own element for scrolling, there is no way we can get the scroll event back to our custom elements isn't there?

So if I were to create my own table with a sticky behavior, I need to know about the scroll position of it's parent container.

```
ready:function(){
        window.addEventListener('scroll', function(){
          console.log('scrollling');
        });
}
````

I understand we have the `on-content-scroll` event on the element itself. But what if we want to create components that need to be aware of the scroll event rather than integrating the listener in the App namespace itself?

For instance, is there _any way_ we can get a scroll event from a paper-panel not a header-paper-panel? I needed to nest these two in my current project.

this will never print scrolling to the console. Any thoughts?

**Comment by kevinpschaaf** [comment]
This issue tracker is for the core Polymer library, not elements built with it.  We'll move this to the appropriate tracker for the element.

**Comment by azumbrunnen** [comment]
Ok thank you. I've found a workaround by firing a custom scroll event on the dom-bind app node which all children can then register to. However, I wish there was a more elegant way to do it.
