### ISSUE TITLE
'custom-style' is not considered when dynamic adding 'style' elements

### ISSUE THREAD

**Issue by manolo** [Polymer/polymer#2035]
When we add dynamically a 'style' tag with the 'is=custom-style' it is not parsed by polymer.
But if the 'style' is inside some other element it works.

This does not work:

           var s = document.createElement('style');
           s.setAttribute('is', 'custom-style');
           s.textContent = "paper-button {color-red}";
           document.body.appendChild(s);

But this works:

           var d = document.createElement('div');
           d.innerHTML = "<style is='custom-style'>paper-button {color:red}</style>";
           document.body.appendChild(d);

**Comment by LM450N** [comment]
Is it a mistyping in the first example at the third line? You have written `paper-button {color-red}` instead of `paper-button {color:red}`.

**Comment by sorvell** [comment]
This is by design. You cannot set the `is` attribute ex post facto to create a type extension custom element (one using the `is` attribute). The correct way to create a custom-style dynamically is:

```
var s = document.createElement('style', 'custom-style');
```

**Comment by manolo** [comment]
Thank @sorvell  for the tip, it works to me.
