### ISSUE TITLE
 dom-if template removes display from inner div style

### ISSUE THREAD

**Issue by bushuyev** [Polymer/polymer#2037]
Hi, 

Could you please comment on http://stackoverflow.com/questions/31248345/polymer-1-0-dom-if-template-removes-display-from-inner-div-style

Thank you.

**Comment by kevinpschaaf** [comment]
Replied on SO.  As noted, we'll plan on fixing this behavior by applying the last value of `display` for children when `if` becomes truthy in the default "hiding" mode of `dom-if`.
