### ISSUE TITLE
iron-ajax header not set

### ISSUE THREAD

**Issue by jkutsko** [Polymer/polymer#2040]
This site describes the problem:
https://github.com/PolymerElements/iron-ajax/issues/51

In short, when making a POST request with a body, setting the handle-as property and/or making the body a json does not make the header contents change to "content-type":json/application. This is not intuitive, and isn't in the documentation. Either the documentation should be fixed to note this, or the POST logic should be smarter.

**Comment by kevinpschaaf** [comment]
This issue tracker is for the core Polymer library, not elements created with it.  Since there is already an open in the proper repo as noted, please comment on that issue.  Thanks.
