### ISSUE TITLE
Polymer element custom style not applied to DOM element that generated through script

### ISSUE THREAD

**Issue by tyohan** [Polymer/polymer#2044]
So i have custom element that generate a div element like below
```
<dom-module id="starfield-plane">
  <style>
    :host  {
      display: block;
      @apply(--layout-fit);
      background-color: #000;
    }

    .starfield {
      height: 100%;
      background-color: rgba(0,0,0,0);
      @apply(--layout-fit);
    }
  </style>
  <template>
  <div id="universe"></div>
  </template>
</dom-module>
<script>
(function () {
      Polymer({
      is:"starfield-plane",
      attached: function() {
          var universe = document.querySelector('#universe');
          var layer = document.createElement('div');
          layer.setAttribute('id', 'layer' + l);
          layer.setAttribute('class', 'starfield');
          universe.appendChild(layer);
          
        }
    });
   })();

```

I found that class starfield will not applied to div element that dynamically generated on element attached. But it works if class style move to global stylesheet file.

**Comment by travellhyne** [comment]
Use `Polymer.dom(this).querySelector` instead of using `document.querySelector`. Internal elements (referred to as local DOM) are not accessible via `document.querySelector`. They are meant to be encapsulated.

**Comment by tyohan** [comment]
@travellhyne no, it's not about query selector.`Polymer.dom(this).querySelector`. Still need to put they css styles on global stylesheet file.

**Comment by LM450N** [comment]
@tyohan I don't know if this will work but have you tried to call the [Polymer.updateStyles](https://www.polymer-project.org/1.0/docs/devguide/styling.html#style-api) method on `universe` ?

**Comment by kevinpschaaf** [comment]
There are two problems with your code:

1. `universe` is in `starfield-plane`'s local DOM template, so you can just access it with `this.$.universe` using Polymer's [automatic node finding](https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#node-finding).  If you were to use `querySelector`, you would need to use Polymer's [dom API](https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#dom-api) `Polymer.dom(this.root).querySelector('#universe')`.

2. You also need to use `Polymer.dom` to append the node (e.g. `Polymer.dom(this.$.universe).appendChild(layer)`.

Working example here:  http://jsbin.com/liviyu/edit?html,output
