### ISSUE TITLE
Request: Make user able to change TRACK_DISTANCE for on-track gesture

### ISSUE THREAD

**Issue by loekup** [Polymer/polymer#2045]
Hey guys, is there a way to change to TRACK_DISTANCE var in Gestures.html? 

Currently working on a app that has drag/drop functionality aswell as scroll functionality.
The 5px value is too small and causes the track to fire while scrolling the content

Grts, Loek

**Comment by TomasAgoston** [comment]
I support that argument. TRACK_DISTANCE should be higher or custom settable. 

Also prevents the tap due to small (TRACK_DISTANCE) mouse cursor movement.

**Comment by TimvdLippe** [comment]
This issue is quite old and we have no plans to make any configuration changes to the gesture system. Therefore, as part of a cleanup, I am closing this issue.
