### ISSUE TITLE
Can not observe changes to array deeper than 3 or more dimensions?

### ISSUE THREAD

**Issue by masaoliou** [Polymer/polymer#2047]
index.html:

    <!DOCTYPE html>
    <html>
      <head>
        <script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
        <link rel="import" href="my-element.html">
      </head>
      <body>
        <my-element></my-element>
      </body>
    </html>

my-element.html:

    <link rel="import" href="bower_components/polymer/polymer.html">
    <dom-module id="my-element"></dom-module>
    <script>
        Polymer({
            is: "my-element",
            properties:{
                arr:{
                    type:Array,
                    value:[[1,[2,null],3],[11,[22,null],33]],
    					observer:"ArrayChanged"
                }
            },
    		ready:function(){
    			for(var i=0;i < this.arr.length;++i)
    				this.splice("arr."+i+".1",1,0,this.arr[i][1][0]+1);
    			for(var i=0;i < this.arr.length;++i)
    				console.log(this.arr[i][1][1]);
    		},
    		ArrayChanged:function(n,o){
    			console.log(n[0][1][1]); //this.splice() does not notify?
    		}
    	});
    </script>

**Comment by LM450N** [comment]
I think the [Array.observation](https://www.polymer-project.org/1.0/docs/devguide/properties.html#array-observation) documentation could help you. :book:

**Comment by masaoliou** [comment]
Yes. I have re-read that documentation. It does help. Thank you!
