### ISSUE TITLE
How to binding data from local json file. What i do wrong in this code? plz

### ISSUE THREAD

**Issue by adisak1618** [Polymer/polymer#2048]
i use jQuery to get persons.json from local file and set to this.employees. what should i do?  

```javascript

<link rel="import" href="../bower_components/polymer/polymer.html">



<script type="text/javascript" src="../bower_components/jquery-2.1.0.min/index.js"></script>


            <!--- render menu item ----->
              <dom-module id="employee-list">
                  <link rel="import" type="css" href="x-app.css">
                  <template>

                    <paper-menu class="list" on-iron-activate="_listTap">
                    <template is="dom-repeat" items="{{employees}}">
                        
                               
                        <paper-item>
                            <div> <span>{{item.nickname}}</span> </div>
                            <div> <span>{{item.phone}}</span> </div>
                        </paper-item>
                                 
                    </template>
                      </paper-menu>

                  </template>

                  <script>
                    Polymer({
                      is: 'employee-list',
                      ready: function() {
                          
                          
                            console.log(this.employees);
                         $.get('src/Persons.json',function(data){
                            this.employees = $.parseJSON(data).results;
                             console.log(this.employees);
                         });
                      
                           
                            
                      }
                    });
                  </script>

                </dom-module>
              <!------- end render menu item ---------->
```

**Comment by adisak1618** [comment]
json file look like this

{ "results": [
	{
        "address": "",
        "createdAt": "2015-06-13T15:59:54.223Z",
        "email": "",
        "facebook": "dtac",
        "fbID": "dtac",
        "fname": "Dtac",
        "instagram": "",
        "lineID": "",
        "listObjID": "CImULW8LTV",
        "lname": "",
        "nickname": "",
        "objectId": "qHAjGpfqP6",
        "phone": "1678",
        "position": "Data Call Center",
        "updatedAt": "2015-06-18T17:34:47.786Z"
    }
]}

**Comment by adisak1618** [comment]
i think, it because response time from jquery to get data.

**Comment by brian-cruickshank** [comment]
I think it's because you're using 'this' inside your callback function.
Try the following:

var _self = this;

$.get('src/Persons.json',function(data){
   _self.employees = $.parseJSON(data).results;
   console.log(_self.employees);
 });

**Comment by adisak1618** [comment]
@brian-cruickshank  Wowwww!! it work!!!    
lot of thank :)

may be i need to read more, why can't use this in callback function

**Comment by brian-cruickshank** [comment]
'this' in javascript is very different than 'this' in object-oriented
languages.  An oversimplified explanation is that 'this' is determined by
the call-site (where the callback function is called from).  Putting a
breakpoint in your callback function and evaluating 'this' is one way to
get a feel for it.

I've found the "You Don't Know JS" series of books - "this & Object
Prototypes" and "Scope and Closures" to be worthwhile reading.
Some online links to check into:
-
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures

Brian

**Comment by LM450N** [comment]
I think you can also use the JavaScript [Function.bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) instead of closure (I prefer this way).

_Example:_
```javascript
$.get('src/Persons.json', function(data) {
    this.employees = $.parseJSON(data).results;
    console.log(this.employees);
}.bind(this));
```

And I think you can close the issue :wink:

**Comment by adisak1618** [comment]
thank you,  it's work also @kevinpschaaf
