### ISSUE TITLE
Plans for dependency management in Polymer

### ISSUE THREAD

**Issue by greenify** [Polymer/polymer#2049]
Hey there,

we (the guys from [BioJS](http://biojs.net)) are currently working on a policy to be able to migrate all our components to web components. In fact we are super happy about this step as we finally will be able to provide encapsulated, custom html elements than can be used to visualize biological data in a browser and obviously we plan to use the amazing Polymer library :)

However we have been having a [discussion](https://github.com/biojs/biojs3/issues/4) over the last days on the dependency management in Polymer. To put it in a nutshell "html imports" are great, but not ideal as they enforce a relative structure on one's code base and can't handle version conflicts. In fact we have been experimenting with using SystemJS as a module loader. 

So we would be super happy if you - as Polymer community - could give us an advice of how you plan to deal with dependencies in the future, so that we don't end up forking Polymer to "Biopolymer" ;-)

https://github.com/biojs/biojs3/issues/4

Cheers,
Seb

**Comment by azakus** [comment]
Polymer uses HTML Imports right now, and we have plans to work with ES6 modules when they ship.

**Comment by olegomon** [comment]
+1 ES6 Modules
