### ISSUE TITLE
polymer-project.org pre.prettyprint horizontal scrollbar

### ISSUE THREAD

**Issue by flaiker** [Polymer/polymer#2050]
Opening polymer-project.org in Chrome gives me horizontal scrollbars in code areas:
![image](https://cloud.githubusercontent.com/assets/5270359/8580025/7db2e462-25b8-11e5-93c4-35e55e3be02f.png)

Seems to be related to the width of the page content. In Firefox the container is just wider so the code fits the pre element:
![image](https://cloud.githubusercontent.com/assets/5270359/8580068/b74fc4a6-25b8-11e5-9799-a30f15badc21.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/5270359/8580075/d014ac36-25b8-11e5-8595-34db7ce8709b.png)

I also noticed this on various pages in the documentation.
Not sure if there is a better place to report this, I could not find a Github repo for this website (nor an about-us page) and I don't think this is it's own webcomponent is it?

**Comment by kevinpschaaf** [comment]
This issue tracker is for the core Polymer library.  We'll move this to the `docs` tracker where we track documentation issues.  Thanks.

**Comment by tjsavage** [comment]
This issue was moved to Polymer/docs#1263
