### ISSUE TITLE
Missing github icon on the site polymer-project.org

### ISSUE THREAD

**Issue by besuhoff** [Polymer/polymer#2053]
Ubuntu / Google Chrome Version 43.0.2357.81 (64-bit)

![selection_200](https://cloud.githubusercontent.com/assets/6132126/8595582/304dfb86-2652-11e5-947e-e90b0c50eb11.png)

**Comment by kevinpschaaf** [comment]
This issue tracker is for the core Polymer library. We'll move this to the docs tracker where we track documentation issues. Thanks

**Comment by tjsavage** [comment]
This issue was moved to Polymer/docs#1262
