### ISSUE TITLE
The element registration outside of <dom-module>

### ISSUE THREAD

**Issue by antonmoiseev** [Polymer/polymer#2054]
It seems like it possible to register an element outside of the `<script>` tag placed into the `<dom-module>`. However I noticed a timing issue when the HTML file containing `<dom-module>` and the JS file containing the element registration are loaded asynchronously. It looks like if `Polymer()` is invoked before `<dom-module>` is added to the DOM, the element is not properly rendered.

Is it even supposed to work or the fact that it works for me sometimes is just a coincidence and not recommended practice?

**Comment by kevinpschaaf** [comment]
These are the strict requirements:

* If your element has local DOM, it must be defined in a `<template>` placed in a `<dom-module>`
* If your element has local DOM, the `Polymer()` invocation must follow the `<template>` (either inside the `<dom-module>` or following it.

We'll add this clarification to the [local DOM](https://www.polymer-project.org/1.0/docs/devguide/local-dom.html) section of the docs.

**Comment by antonmoiseev** [comment]
I see. Thank you @kevinpschaaf!

**Comment by arthurevans** [comment]
Cleaning up old issues. This has been documented for a while.
