### ISSUE TITLE
Missing documentation for iron-icons

### ISSUE THREAD

**Issue by adrifelt** [Polymer/polymer#2055]
There's no information about iron-icons in the element catalog for polymer 1.0. In contrast, 0.5 documentation has a great page with examples of all the different icons.

<img width="1325" alt="screen shot 2015-07-09 at 6 18 08 am" src="https://cloud.githubusercontent.com/assets/4962198/8600674/d68ac240-2602-11e5-91ea-6a1f8f868586.png">

**Comment by kevinpschaaf** [comment]
This issue tracker is for the core Polymer library, not elements created with it.  We'll move this issue to the correct tracker.

**Comment by tjsavage** [comment]
This issue was moved to Polymer/polymer-element-catalog#151
