### ISSUE TITLE
Proposal for error when there are duplicate IDs

### ISSUE THREAD

**Issue by Chariyski** [Polymer/polymer#2057]
Hi, 

you have created a really great job with v1.0 and the environment is really friendly for learning. 

So back to the topic, I've a proposal for a feature - **add check for duplicate ID attributes** . The reason for the proposal is for better project maintenance. 
Today when I was playing with some elements, I've copied the paper-input component several times, and forgot to change one of the ID attributes. When it was time to get the values of the inputs I've realized that one of them was wrong. After 20min. wandering, I've realized that two components have identical ID. Imagine to have some big application with a bunch of people working on it. It is quite possible for the same mistake to appear. For this reason some kind of a warning will be great!

I hope that this proposal is reasonable enough to be a new feature in Polymer.

Best regards,
Krasimir

**Comment by kevinpschaaf** [comment]
We'll add this to our Polymer linter backlog.  Thanks for the idea.

**Comment by Chariyski** [comment]
Great and thanks for the fast response.

**Comment by TimvdLippe** [comment]
@rictic Something for the linter I guess?

**Comment by TimvdLippe** [comment]
This issue was moved to Polymer/polymer-linter#171
