### ISSUE TITLE
uncompressed version and firefox minification assert error

### ISSUE THREAD

**Issue by mateusmaso** [Polymer/polymer#206]
while working with chrome I noticed that an unexpected error ocurred when I tested the plataform.min.js in firefox:

```
Error: Assertion failed
...(b):!1},compareDocumentPosition:function(a){return t.call(this.impl,m(a))}}),i(f...
```

my appeal is to allow developers use an uncompressed versions of plataform.js and polymer.js for debugging reasons, allowing a faster feedback to support the polyfill project.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) release of Polymer - please feel free to re-open if this is incorrect.
