### ISSUE TITLE
[1.0] Uncaught TypeError: Illegal invocation   from   document.createElement("template", "dom-template").stamp().id 

### ISSUE THREAD

**Issue by jcmoore** [Polymer/polymer#2061]
Trying to get or set the "id" field of a stamped dom-template instance throws an `Uncaught TypeError: Illegal invocation` -- run:

`document.createElement("template", "dom-template").stamp().id`

or:

`document.createElement("template", "dom-template").stamp({id:0})`

in the console (I'm in Chrome 43).  Is there something I'm missing in the use of the .stamp() API?

**Comment by kevinpschaaf** [comment]
This is expected as implemented.

TemplateInstances returned from `Templatizer`'s `stamp` method are instances of `Polymer.Base`, which extends `HTMLElement` but are not actually created as elements (they are anonymous instances that manage the data-binding for a set of DOM stamped from the template), so touching any properties native to `HTMLElement` will throw.

As such, you should avoid `HTMLElement` property names for user properties.
