### ISSUE TITLE
[1.0] dom-repeat {{myitems[item].album}}

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#2066]
item is 3 8 5 9 form a array [3,8,5,9] named keys
i need this in the following sequence `myitems[3].album myitems[8].album myitems[5].album myitems[9].album`

```html
<template is="dom-repeat" items="{{keys}}">
      <p data-id$="{{item}}" data-name$="{{myitems[item].album}}" ...
```
`<p data-id$="{{item}}"` this part works and gets to be 3 8 5 9
`data-name$="{{myitems[item].album}}"` this part doesn't get parsed in 1.0 it did work in 0.5 in de form of items="{{item in keys}}" and then do "{{myitems[item].album}}"

**Comment by LM450N** [comment]
You can use the [computed binding](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#annotated-computed). I did a [Plunkr](http://plnkr.co/edit/CGkWw0?p=info) for you.

But please, do not open an issue on the tracker for a programming question. Use [StackOverflow with the _polymer_](https://stackoverflow.com/questions/tagged/polymer) tag instead.

**Comment by gertcuykens** [comment]
I asked on slack first if it should work and the conclusion was it should? The solution you have is a nice workaround but allot of boilerplate for something that should work? So for me `{{myitems[item].album}}` not working is a bug. If not please elaborate why it is not a bug?

**Comment by gertcuykens** [comment]
never mind just one of does 1.0 things to get used too

**Comment by LM450N** [comment]
When I read the section [Binding to structured data](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#path-binding) I don't think it's a bug.

![image](https://cloud.githubusercontent.com/assets/2325091/8640827/23168f62-2906-11e5-99fd-f570667bf0dc.png)

**Comment by gertcuykens** [comment]
Yea your right
