### ISSUE TITLE
notifyPath + dom-repeat do not work with new array items

### ISSUE THREAD

**Issue by miyconst** [Polymer/polymer#2068]
Polymer 1.0 does not track data model changes automatically, there is a `notifyPath` method to notify Polymer elements about changes in data model.
https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#set-path

What path should be notified when a new array item inserted to force refresh of `<template is="dom-repeat">`?

Non of these work:
```js
this.notifyPath("array", this.array);
this.notifyPath("array.1", this.array[1]);
this.set("array." + this.array.length, {});
```

Here is a Plunker example to play with:
http://plnkr.co/edit/UyoKIA90kJkkydO7Rhv4?p=preview

**Comment by pflannery** [comment]
I believe the problem occurs because changing the array before calling ```notifyPath``` causes ```notifyPath``` to detect no changes between the ```this.array``` and the ```value``` being passed to ```notifyPath``` function.

here are some alternatives to your plnkr

```js
root.changeProduct = function() {
  root.notifyPath("products.0.name", "intel " + root.products[0].name);
};

root.addProductByPush = function() {
  root.notifyPath("products", root.products.concat({name: "fx-8350"}));
};
```

**Comment by miyconst** [comment]
Thank you for the answer, but I believe you didn't even try the Plunker example.

This is definitely not because of
>because changing the array before calling `notifyPath` causes `notifyPath` to detect no changes between the `this.array` and the `value` being passed to `notifyPath` function.

- The *Change product* button works, in spite of it calls `notifyPath` after the change being made.
```js
root.changeProduct = function() {
    root.products[0].name = "intel " + root.products[0].name;
    root.notifyPath("products.0.name", root.products[0].name);
};
```

- `array.concat` would work only inside a Polymer element. In my case changes come from a third party library, and I want to notify Polymer element with no changes to the view model.

**Comment by miyconst** [comment]
This one works:

```js
root.addProductByPush = function() {
    root.products.push({ name: "fx-8350" });
    root.notifyPath("products", root.products.slice());
};
```

But in this case (same as `array.concat`) the `notifyPath` value argument is a new array, and I would like to keep the old one, only notify Polymer about changes inside.

**Comment by pflannery** [comment]
@miyconst I did try the example!

> here are some alternatives to your plnkr

I just gave some alternatives which also work! 
Slice is a good way to go too ;)

**Comment by miyconst** [comment]
@pflannery then I am really lost.

The `notifyPath` function does not change view model, it only notifies Polymer about already existing changes.

Your example would work if `notifyPath` would be replaced with `set`, which would replace entire array of `products` with a new one, and this is what I want to avoid.

Correct me if I am wrong.

**Comment by mikkokam** [comment]
Did you try 

```
root.addProductByPush = function() {
    root.push("products", { name: "fx-8350" });
};
```

**Comment by miyconst** [comment]
@mikkokam I did try, it works, not in my case though.

I have an object, which is shared between a Polymer element and a third party library. The library does some changes in the array, and I want to notify the Polymer element about that change.

Your suggestion works inside Polymer elements only.

**Comment by mikkokam** [comment]
True. This is what I have been trying to solve myself, as well:
This is the final missing piece in my simple attempt to implement FLUX architecture with Polymer; a **change** event causing a refresh from extrenal data. 

In my case, we should have a way to compare two Arrays: the external and the Polymer one, and update the changed elements in Polymer way.

Seems possible with an utility, comparing the two Arrays and using Polymer Array mutation methods to update only the changed ones.

**Comment by miyconst** [comment]
So, currently there is no way to notify Polymer about a change inside an array? Looks like I have to use `array.slice()` then.

**Comment by mikkokam** [comment]
Made a simple array sync utility to test things out. Seems to work as intended - at least for my usage for FLUX.

The idea: keep two Arrays, external data + local data. The local one to be used in dom-repeat.
The utility syncArrays then keeps these in sync and uses Polymer Array mutation methods to keep things up to date. **Only the changes** will be propagated.

http://plnkr.co/edit/Gu1bsFgvd76ofyvQwdz6?p=preview

**Comment by miyconst** [comment]
@mikkokam thank you, your solution works.

It does not fit my case though. 
The data model is not known in advance and may contain many arrays with lots of data.
Copying all of them is not a good idea.

**Comment by dombre** [comment]
@miyconst I have exactly the same problem as you (third party library) and solved it with a combination of `notifyPath`and `_notifySplice(array, path, startIndex, addedCounter, removedItemsArray)`. I use `notifyPath` if the array instance or an exisiting item changes, `notifySplice` if an item was added or deleted.

**Comment by miyconst** [comment]
@dombre, this is something I was looking for!

There is still a bug though. I have updated my Plunker using your approach, but instead of pushing new product to the array, I insert it at position 0.

`_notifySplice` works fine and `dom-repeat` updates, but the elements inside the `dom-repeat` still remember their binding path.

The `Change product` button changes the first product and then notifies Polymer with:
```js
root.notifyPath("products.0.name", root.products[0].name);
```

But Polymer updates item `1`, which previously was `0`.

http://plnkr.co/edit/UyoKIA90kJkkydO7Rhv4?p=preview
- Press button `Add new with Array.push`.
- Press button `Change product`.

And you will see what I talk about.

**Comment by jongeho1** [comment]
@miyconst 

The code doesn't appear to be doing a push (as the object is not being spliced onto the end your array). Aren't you shifting all the elements of the array and not telling polymer about it?

**Comment by jongeho1** [comment]
@miyconst apologizes wanted to include some ~code, something like so was intended?

```javascript
   root.addProductByPush = function() {
        //root.products.push({ name: "fx-8350" });
        //root._notifySplice(root.products, 'products', root.products.length - 1, 1, []);
        root.products.splice(root.products.length, 0, { name: "fx-8350" });
        root._notifySplice(root.products, 'products', root.products.length-1, 1, 0);
      };
```

I think the push method also works; however, kinda fubar you have to call the private api though!

**Comment by miyconst** [comment]
@jongeho1 

In my case the changes to the array is not limited to `push` operation. It can be `add item at` or `remove item at`.

Your code splices an item to the end of the array, and my code splices an item to the beginning of the array.

My case breaks up Polymer binding, because it "remembers" path for `dom-bind` items. This makes the `products.1` item react to `products.0` changes.

**Comment by jongeho1** [comment]
@miyconst ah! the example method and button are misleadingly named and require much context to understand what is being conveyed! I looked at it for the insert case quickly and gathered it may be unsupported.

Like mentioned above, the code modifying the beginning of the array and shifting all the indices.  Indices appear to be initially used as collection keys for digging deeper into the collection being notified. When the splice/insert is notified on the user array, the collection adds the object with key "2" to the model not "0". This is when the view index and model key become out of sync so notifying based on "index" instead of "key' has become unsafe. Polymer doesn't appear re-balance the model keys with view indices and has it registered ``products.2``. The splices on the model always appear to be added with a push to the user array (the end) to obtain a model key.

If you notify using the collection key, then it seems to work:

```javascript

      root.changeProductNameForIndex0 = function() {
         
        //view to change         
        var domRepeatIndex = 0;
        
        //obtain the model key for the first index
        var key = Polymer.Collection.get(root.get("products")).getKey(root.products[domRepeatIndex]);
        
        //build path to name
        var itemPath = ["products",key,"name"].join(".");
        
        //external change to view
        root.products[domRepeatIndex].name = "intel " + root.products[domRepeatIndex].name;
        
        //tell polymer about the change to the model
        root.notifyPath(itemPath, root.products[domRepeatIndex].name);
      
      };

```

**Comment by miyconst** [comment]
@jongeho1 

Well, this works, but it is too complicated..

I have a big view model, with arrays inside arrays, moreover there might be objects with `0`, `1` properties. Calculating the key for each array item being updated is kind of ridiculous.

**Comment by jongeho1** [comment]
@miyconst not trying to sell you the sandwich, merely trying to tell you what it looks like and can be arguably be an unsupported limitation that it has no lettuce. Sandwich aside, sounds like your model's size + structure make it complex rather than a key lookup. 

This https://github.com/Polymer/polymer/issues/2007 may be helpful and seems to have some symmetry with what I described.

**Comment by miyconst** [comment]
@jongeho1 

I will probably use your solution, and thank you.

Just I want a fix on Polymer level, not a complicated hack to make it work.

**Comment by dombre** [comment]
@miyconst here is another sandwich: https://github.com/ESTOS/estos-databinding-behavior Maybe this is useful for you, too. But keep in mind this is my first attempt for a more general solution to this problem.

**Comment by tomalec** [comment]
There is yet another sandwich: https://github.com/Juicy/dom-bind-notifier or rather juicy-fruit ;)
Custom element which, once put inside your `<template is="dom-bind">` observes the changes and notifies `dom-bind` for you.

**Comment by tomalec** [comment]
I suspect, I might encounter the cause of a root issue. And it seemed not to be a problem with `_notifySplice` but with `notifyPath`, which according to [docs](http://polymer.github.io/polymer/) should consume 
> path {string} Path that should be notified.

Similar to other methods, like `.set`, `.get`, `.splice`. But it occurred that it is **NOT** the same path, so it's not the path in your object which uses indexes, but a path in Polymer's Collection which uses keys. I would say, it will be nice to clarify it in docs.

Therefore, to use `notifyPath` as other methods in API, I need to get correct path first. I did it with the same way `.set` method does: https://github.com/Juicy/dom-bind-notifier/blob/master/dom-bind-notifier.html#L250

It's pretty universal, structure independent way to translate real path, to the one you can use in `notifyPath`, so you can use it without a need to create custom element per object, or even any custom element at all.

However it's definitely ugly to store such copy of Polymer internals in your own code.

I thought about a PR with fix to use external path as input for external calls to public `notifyPath` (it is called internally many times as well), but I'm not sure if there is any other use case for that.

**Comment by ebidel** [comment]
This issue is pretty old, but observing array adds/removes is described in the docs:
https://www.polymer-project.org/1.0/docs/devguide/properties.html#array-observation

**Comment by raghanag** [comment]
i was wondering i have the same requirement, but my array is array of objects, can someone tell me how to achieve template refresh.

rows:{type:Array,observe:true,notify: true,value: [{"id":1,"value":["w"]},{"id":2,"value":["w"]}]}

and i have the template like this.

<button on-click="addRows" class="btn btn--primary">Add Rows</button>
			<template is="dom-repeat" items="{{rows}}" id="rowdiv">
				<button on-click="addCols" class="btn btn--primary">Add {{item.id}} Columns</button>
			</template>

			<template is="dom-repeat" items="{{rows}}" id="maindiv">
				<div class="layout__row">
				<template is="dom-repeat" items="{{item.value}}">
					<div class="layout__block" id$="{{item}}">
						<button class="btn btn--primary margins">Add {{item}} Widget</button>
					</div>
				</template>
				</div>
				</template>

addRows: function(){
						this.push("rows", {"id":this.rows.length+1,"value":["w"]} );
						this.$.maindiv.render();
						this.$.rowdiv.render();
						console.log(this.rows);
					}

Add Rows is working perfectly, but the addcols function is modifying the attribute but dom is not getting changed.

addCols: function(e){
						var arr = e.model.item.id;
						var ind;
						for(var i=0;i<this.rows.length;i++){
							if(this.rows[i].id === arr){
								ind = i;
//								this.push("rows[i].value","w");
								this.rows[i].value.push("a");
								this.$.maindiv.notifyPath('rows.i.value', this.$.maindiv.rows[i].value);
							}
						}
this.$.maindiv.render();
						this.$.rowdiv.render();
						console.log(this.rows);

					}

can someone advise on how to resolve this. thanks,

**Comment by kf6nux** [comment]
@raghanag You should be able to use polymer's [array mutation](https://www.polymer-project.org/1.0/docs/devguide/properties.html#array-mutation) methods for your purpose.

e.g. this.push('rows.'+i+'.value', 'a');
