### ISSUE TITLE
Multiple behaviors with same property.

### ISSUE THREAD

**Issue by hourliert** [Polymer/polymer#2069]
Hi,

I would like to know if it's possible (or plan) to apply 2 behaviors defining the same property (for instance: `animationConfig`) and if this 2 objects will be merged in the resulting component.

This could be very useful if you define a `PageExitBehavior` which configure the exit animation and a `PageEntryBehavior` which configure the entry animation.

I see a workaround: exposing a property in the behavior defining the `entry` or `exit` animation with an observer and merge this object with the `animationConfig` object in the observer handler. Is this the recommend solution?

Thanks.

**Comment by tswebcomponents** [comment]
and related: https://github.com/PolymerElements/paper-slider/issues/47

Can behaviors (so mixins/traits) have properties of another type like mentioned in the issue 47?

Thanks.

**Comment by TimvdLippe** [comment]
Behaviors are Polymer 1-specific, so we will not make any more enhancements to their "behavior" (no pun intended). Sharing of functionality is now advised as mixin (https://www.polymer-project.org/2.0/docs/devguide/registering-elements#using-mixins) If you still want to achieve what you want,  you can implement it with http://jsbin.com/paginisohi/1/edit?html,console,output
