### ISSUE TITLE
Fail more gracefully on unsupported browsers

### ISSUE THREAD

**Issue by jkomoros** [Polymer/polymer#207]
Polymer only works on modern browsers. Currently if you use a browser that's not supported, the app will fail in various, sometimes non-obvious ways.

In an ideal world we'd do something more reasonable like detect if you're on an unsupported browser and show a dialog that says something like "Polymer only works on modern browsers. Your browser is not fully supported and this application might not work." There should also be a button to "try anyway". It's not ideal, but it's better than what we have now.

I consider this a blocker to hosting Sandbox for people to play around without a checkout.

**Comment by oleersoy** [comment]
Is there an API we can use to augment this feature?  More specifically:
http://stackoverflow.com/questions/30666587/detect-browser-support-fo-polymer

TIA,
- Ole

**Comment by gusdecool** [comment]
@singhalpriyank how @azakus resolve this issue? any example?
