### ISSUE TITLE
dom-repeat simple question, how to bind [[index]] to attr href

### ISSUE THREAD

**Issue by adisak1618** [Polymer/polymer#2070]
i use [[index]] to render the index of item to attribute href like this

<a href="person-info/{{index}}">{{item.name}}</a>  

but it work on this

<a href="{{index}}">{{item.name}}</a>  

but i need to render path like  person-info/9

what to do?? plz

**Comment by LM450N** [comment]
Your links are broken. I think you have copied-pasted some code lines without using the markdown syntax and they are interpreted.

Please do not use the issues tracker to asking basic programming question. Use [StackOverflow with the _polymer_](https://stackoverflow.com/questions/tagged/polymer) tag instead.

**Comment by adisak1618** [comment]
thank you
