### ISSUE TITLE
dom-module not working in body tags in Firefox

### ISSUE THREAD

**Issue by Mygod** [Polymer/polymer#2071]
I'd like to define a `dom-module` in `body` tag and the code works fine in Chrome. However this error shows up when I'm testing it in Firefox.

    ReferenceError: Polymer is not defined

The elements I defined in the htmls that get imported work fine though.

**Comment by kevinpschaaf** [comment]
In order to call `Polymer` from the main document, please wrap it in a call to `HTMLImports.whenReady`, as in the following JSBin:

http://jsbin.com/pucome/1/edit?html,output

**Comment by Mygod** [comment]
Oh, can this be found in the documentation? Because I didn't know that. :-/

Thanks for your help.
