### ISSUE TITLE
Will polymer-gestures be migrated completely?

### ISSUE THREAD

**Issue by Jamtis** [Polymer/polymer#2073]
Hi,

at the moment polymer 1.0 supports tap, down, up and track events.

Will the other events (hold, pinch, flick...) be migrated from version 0.5?

Greetings Nicholas

**Comment by azakus** [comment]
There's still some open questions about what the Material Design elements need to have implemented to match the spec. I expect to add most, if not all, the previous suite of gestures to 1.0 at some point, but it is mostly a matter of prioritization and need.

**Comment by Jamtis** [comment]
Thanks for the answer.
So I guess it could take quite a while...

**Comment by Jamtis** [comment]
@azakus How and where is the discussion about supported gestures ongoing?
I'd love to have a list of candidates/excludes on the [doc page](https://www.polymer-project.org/1.0/docs/devguide/events.html).

**Comment by Jamtis** [comment]
@azakus What's the current state on hold,pinch,flick?

**Comment by azakus** [comment]
The current plan is to implement these based on user demand, but we haven't seen a lot of demand for those gestures as of yet.

Open to evidence suggesting higher demand :).

**Comment by Jamtis** [comment]
I think hold might have some use cases in web apps.
Maybe pinch and flick not so much...

**Comment by Jookus** [comment]
Please support those events, that would be very useful ;)

**Comment by Hunsin** [comment]
Native support of these events will be great~
I'm building web apps that users can upload pictures, zoom and rotate, etc.
At the moment I'm trying to integrate hammer.js with Polymer, and it's not quite handy...

**Comment by sasivarnan** [comment]
+1 for on-hold event

**Comment by emanuela-dominte** [comment]
+1 for pinch please, hold

**Comment by TimvdLippe** [comment]
Because of the trade-off between implementation time, maintenance burden and eventual new features, we will not be spending work on this specific feature. Therefore, I am closing this issue.
