### ISSUE TITLE
Set/Map properties

### ISSUE THREAD

**Issue by Jamtis** [Polymer/polymer#2074]
Hi,

I think Array are not enough today!

Polymer should support Sets and Maps as well.

Like this:

```
properties: {
    prop: {
        type: Set,
        value: function() {return new Set();},
        notify: true
    }
}
```

Therefore the `Polymer.Base` must support add/delete/set (set is a little difficult) functions similar to the push/splices functions for arrays.

What do you guys think?

Is this a general necessity?

How can it be accomplished?

**Comment by TimvdLippe** [comment]
Yes you can! Please check out the JSBin in https://github.com/Polymer/polymer/issues/3751#issuecomment-329300479 for an example.
