### ISSUE TITLE
nesting a core-dropdown on a custom pol component prevents it's closing by similar instances

### ISSUE THREAD

**Issue by tonosama-atlacatl** [Polymer/polymer#2084]
I created a custom dart/polymer component with this code:
```
...
<a id="row-options-button" class="optionsBtn" href="#" style=""
            title="Options" on-click="{{ openDropdown }}" relative>
             <i id="ellipsisIcon" class="icon fa fa-ellipsis-v"></i>
             <core-dropdown id="optionsDropDown" class="colored" layered="true" autoCloseDisabled="false">
                 <core-selector single valueattr="label">
                    <core-item label="Display for 8 seconds"></core-item>
                 </core-selector>
             </core-dropdown>
         </a>
    </template>
</polymer-element>
```
**The Problem/Bug:** 
If I deploy multiple instances of this component on the same screen. Clicking on another instance of the same component does NOT close the previous core-dropdown menu, and sometimes clicking on a different component does NOT close this component's dropdown.

I was going to attempt to traverse all the shadow doms on my doc to close all instances, but this just sounded like mad science... Is there a way to close all core-dropdowns on a doc regardless if they're inside a shadow dom or not?

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
