### ISSUE TITLE
css variables don't work inline

### ISSUE THREAD

**Issue by BLamy** [Polymer/polymer#2086]
Trying to use css variables inline doesn't work. 
```
<link rel="import" href="../../bower_components/paper-styles/paper-styles.html">
...
<div style='background-color: var(--paper-red-500)" ></div>
```

The result I need to resort to making css classes which look like (taken from the neon-elements 'shared.css')
```
.red-100 {
  background: var(--google-red-100);
}

.yellow-100 {
  background: var(--google-yellow-100);
}
```
Which works but is kind of a let down because I thought variables and mixins where suppose to stop us from having to define classes like this.

**Comment by sorvell** [comment]
Using variables directly in the style attribute is not something that's supported by Polymer's custom properties shim. Polymer's support for custom properties is primarily designed to provide a way for elements to expose a styling api which can be used in any styling scope independent of local dom boundaries.

This shim has other limitations as well, see [Styling local DOM](https://www.polymer-project.org/1.0/docs/devguide/styling.html) for more information.
