### ISSUE TITLE
Parent event not triggering

### ISSUE THREAD

**Issue by klarkc** [Polymer/polymer#2087]
Hello, I was testing some things, I just can't figure why this does not work:

I created a custom element named my-ii
```html
<script>
    Polymer({
        is: 'my-ii',
        ready: function() {
            this.fire('myEvent', this);
        }
    });
</script>
```
So I created this element:
```html
<dom-module id="hello-world">
    <template>
        <p>Hello... <my-ii id="myi">You</my-ii></p>
    </template>
    <script>
        Polymer({
            is: "hello-world",
            listener: {
                'myi.myEvent': 'myEvent'
            },
            myEvent: function(event) {
                console.log(event);
                window.alert('You!');
            }
        });
    </script>
</dom-module>
```
Live example: http://jsbin.com/lujerikuya/edit?html,console,output

But the myEvent function is never called. The element is being loaded, the ready function of my-ii is being called, the event is not being triggered on the parent element (hello-world). I am following the docs: https://www.polymer-project.org/1.0/docs/devguide/events.html#event-listeners

**Comment by kevinpschaaf** [comment]
Typo in your example: `listener` should be [`listeners`](https://www.polymer-project.org/1.0/docs/devguide/events.html#event-listeners).

Working example: http://jsbin.com/xejaza/edit?html,console,output
