### ISSUE TITLE
array-selector: Invalid value used as weak map key

### ISSUE THREAD

**Issue by jarrodek** [Polymer/polymer#2088]
I receive "Invalid value used as weak map key" when I try to select an item in array-selector:

```javascript
this.$.selector.select(item);
```
where `item` is a single String.
Debugging the code I discovered that this is caused by the line:
```javascript
var icol = Polymer.Collection.get(this.items);
```
in `array-selector` definition. `this.items`'s value is `undefined` which cause an error. It should be Array instead at this point.

**Comment by jarrodek** [comment]
It seems that it was my error. I've set the same variable for binding to the `items` and `selected` attributes
```javascript
items="{{_selected}}" selected="{{_selected}}"
```
which caused an error.
I think this ticket should be closed.

**Comment by kevinpschaaf** [comment]
No prob, thanks for follow-up.
