### ISSUE TITLE
dom-bind not working

### ISSUE THREAD

**Issue by Mygod** [Polymer/polymer#2091]
Here's the sample code: http://jsbin.com/donubekebo/1/edit?html,output

Am I doing anything wrong?

**Comment by kevinpschaaf** [comment]
A couple of issues in your sample:

1. `dom-bind` stamps asynchronously, so to interact with elements that it will stamp you should listen for the `dom-change` event before attempting to select them.

2. `dom-bind` stamps its children _immediately before_ its position in the DOM, not inside of it, so your selector `#dom-bind-wrapper x-outer` will not find the stamped children.

3. Also note that without waiting for the `dom-change` event, you can set properties on the `dom-bind` template element itself, and these will propagate to the stamped elements once they do stamp.

Working demo:

http://jsbin.com/mesebo/edit?html,output
