### ISSUE TITLE
Getting error while trying Ripple animation. Uncaught NotSupportedError: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.

### ISSUE THREAD

**Issue by ankurvr7003** [Polymer/polymer#2092]
I am trying to implement ripple and reverse-ripple animation in my application. My application is running on Polymer v1.0. 

When i test this animation in separate page then it is working fine but when i am trying to test inside my application it shows javascript error 
> Uncaught NotSupportedError: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.

My app have header and side menu bar. And one thing i want to let you know is whole application is mixed up with polymer elements and other libraries like (Twitter Bootstrap, jQuery, etc).

Please help me short this out.
Thanks in advance

**Comment by tjsavage** [comment]
This issue was moved to PolymerElements/paper-ripple#28

**Comment by LIZIMEME** [comment]
$.each(imgs,function(index, el) {
    
   $(this).animate( );

})
