### ISSUE TITLE
Standard Polymer demos not working iOS9 Beta

### ISSUE THREAD

**Issue by markhats** [Polymer/polymer#2094]
None of the standard Polymer demos seem to work on the latest iOS9 Beta 3. This is now a public beta.
e.g.

https://www.polymer-project.org/0.5/components/paper-calculator/demo.html

https://www.polymer-project.org/0.5/components/paper-elements/demo.html#core-toolbar

https://polymer-topeka.appspot.com/

**Comment by kevinpschaaf** [comment]
This is looking like an issue with Safari 9 breaking the polyfill, which is already logged here: https://github.com/webcomponents/webcomponentsjs/issues/348.

We'll close this issue and track it there.  Thanks for the note.
