### ISSUE TITLE
accessing an element with this.$.<id> from an event fired function

### ISSUE THREAD

**Issue by Toddses** [Polymer/polymer#2095]
trying to figure out the best practice for accomplishing this. as it is right now, you can't access `this.$` from an attached event listener. For instance i have an element with the id `glass`

```js
Polymer({
  is: "flux-frosted-window",
  _resize: function(e) {
    console.log('_resize ' + this.$.glass);
  },
  attached: function() {
    console.log('attached ' + this.$.glass);
    window.addEventListener('resize', this._resize);
  }
});
```

in `attached` i can reference `this.$.glass` just fine, but in `_resize` it is undefined. i got around this limitation by

```js
(function () {
  var $el;

  Polymer({
    is: "flux-frosted-window",
    _resize: function(e) {
      console.log('_resize ' + $el);
    },
    attached: function() {
      console.log('attached ' + this.$.glass);

      $el = this.$.glass;
      window.addEventListener('resize', this._resize);
    }
  });
})();
```

Would this be considered bad practice? It appears the `$el` variable is local to the component, so I don't think its too dangerous caching it into a global, but I wasn't sure if this behavior may potentially change. Further, is there a better way to attach a listener to the resize event for a component? All this seems to work fine in chrome, safari, and firefox, so for the moment it seems to be a good solution. I guess I am concerned this may not be a smart way to handle the situation.

**Comment by timeu** [comment]
You can use `bind`: `window.addEventListener('resize', this._resize.this(bind));`
https://msdn.microsoft.com/library/dn569317(v=vs.94).aspx

**Comment by kevinpschaaf** [comment]
You definitely don't want to put `$el` in a closure, because you're effectively making it shared between each new instance of `flux-frosted-window`, since when each instance of it is `attached` it update that variable in the closure accessible from each instance (which is not what you intended).

As mentioned, all you need to do is bind the handler to `this` before passing to `addEventListener` so that it is invoked on the correct scope.

**Comment by chuckh** [comment]
This is an actual working example:
http://jsbin.com/remano/edit?html,js,console,output.

On Thu, Jul 16, 2015 at 10:43 AM, Ümit Seren <notifications@github.com>
wrote:

> You can use bind: window.addEventListener('resize',
> this._resize.this(bind));
> https://msdn.microsoft.com/library/dn569317(v=vs.94).aspx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Polymer/polymer/issues/2095#issuecomment-122032423>.
>



-- 
Chuck Horton
actionplanr.com
www.hware.com
chuck@hware.com
www.twitter.com/chuckhorton
530.268.5840

Let us create a world that works for all.

**Comment by Toddses** [comment]
thanks for the help! :+1:
