### ISSUE TITLE
Array-like objects fail to update the template

### ISSUE THREAD

**Issue by filaraujo** [Polymer/polymer#2096]
When working with array like objects, data-binded properties do not properly update the view later when setting to those values.

http://jsbin.com/mamogo/1/edit?html,output

seems to be linked to the notifyPath reporting changes as 'complexArray..splices'

**Comment by kevinpschaaf** [comment]
Will be fixed in https://github.com/Polymer/polymer/pull/2097

Confirmed fix in repro case here:
http://jsbin.com/sedoqebuqe/edit?html,output

**Comment by filaraujo** [comment]
you sir are an angel in human form!
