### ISSUE TITLE
Ship a vulcanized "polymer.js" for development

### ISSUE THREAD

**Issue by nippur72** [Polymer/polymer#2101]
It seems there is a [bug in webcomponentsjs](https://github.com/webcomponents/webcomponentsjs/issues/347) that causes Polymer to be loaded after the user scripts (in IE and FF), making it `undefined` in places where it shouldn't.

While waiting for that to be fixed, one possible solution (at least for development purposes) could be providing a `polymer.js` file that could be referenced via `<script>`, avoiding the faulty HTML import.

**Comment by sorvell** [comment]
As noted in the [webcomponentsjs issue](https://github.com/webcomponents/webcomponentsjs/issues/347), this is a limitation of the HTMLImports polyfill. The `HTMLImportsLoaded` event can be used to process main document scripts after HTMLImports have loaded.

Polymer actually is available as a script, but we recommend loading it via the HTMLImport. This ensures Polymer can be loaded efficiently (not re-fetched) when multiple imports reference it. While loading Polymer as a script would ensure it's loaded before subsequent scripts, other HTMLImports would still be pending and thus it's likely that the `HTMLImportsLoaded` event would still be necessary.

**Comment by nippur72** [comment]
> Polymer actually is available as a script

could you please tell me where is it? I can only see the .htmls. 

And this polyfill limitation is a real trap!

**Comment by sorvell** [comment]
I'm sorry, I was incorrect. The Polymer releases contain only a .html file.

Again, the recommended pattern is to wait for the `HTMLImportsLoaded` event.

**Comment by nippur72** [comment]
ok thanks, I'll try to adhere to the standard

**Comment by nippur72** [comment]
Uhm, I think I am forced to use `<script>`, because mine is an edge case:

[My library](https://github.com/nippur72/PolymerTS) depends on Polymer and ok, I can wait for the `HTMLImportsLoaded` event to initialize it. 

But my library also provides a `polymer.Base` object to use in `class extends`, so when there's a
```HTML
<link rel="import" href="elements/myelement.html">
```
my lib is not initialized yet (because it's waiting for `HTMLImportsLoaded`) and so `myelement` fails to extend from `polymer.Base` object (note the lowercase 'p').

It's a sort of race condition. I don't see how to fix it, other than adopting clumsy event waiting code everywhere. 

So my question is now, is there a way to produce a `polymer.js` ?

**Comment by nippur72** [comment]
Forget the previous comment, I think I've found a workaround.
