### ISSUE TITLE
upcoming 1.0.7 release - Object.defineProperty  defined arrays are not properly updating templates

### ISSUE THREAD

**Issue by filaraujo** [Polymer/polymer#2102]
When defining an array with Object.defineProperty the values are not updating the template when pushing to that array.  The length is however

http://jsbin.com/leyero/edit?html,output

**Comment by sorvell** [comment]
Fixed in https://github.com/Polymer/polymer/pull/2099.

**Comment by filaraujo** [comment]
thank you!
