### ISSUE TITLE
Auto find fails to find elements surrounded by dom-if

### ISSUE THREAD

**Issue by masaoliou** [Polymer/polymer#2103]
Please click on the third button to see the result.
Is this an intended feature?

	<!DOCTYPE html>
	<html>
	<head>
		<script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
		<link rel="import" href="bower_components/polymer/polymer.html">
	</head>
	<body>
		<dom-module id="x-test">
			<template>
				<template is="dom-if" if="true">
					<button id="b1" class="b1">button 1</button>
				</template>
				<button id="b2">button 2</button>
				<button on-tap="clicked">Click Me</button>
			</template>
		</dom-module>
		<script>
		HTMLImports.whenReady(function(){
			Polymer({
				is: 'x-test',
				clicked:function(){
					alert(this.$.b1); //"undefined"
					alert(Polymer.dom(this.root).querySelector(".b1")); //object
					alert(this.$.b2); //object
				}
			});
		});
		</script>
		<x-test></x-test>
	</body>
	</html>

**Comment by sorvell** [comment]
We're considering adding this. It sounds simple, but there are a number of related issues to consider so we'll need to think about it a bit.

In the meantime, I'd like to point out that you can use the `$$` method to find the element which is just a little less verbose than the alternative that you're correctly using:

```
  this.$$('#b1');
```

**Comment by masaoliou** [comment]
Thank you for the comments!

**Comment by Mygod** [comment]
+1
