### ISSUE TITLE
Paper-drawer-panel with paper-header-panel (mode="waterfall-tall") scroll, not working on Firefox

### ISSUE THREAD

**Issue by FranNoriega** [Polymer/polymer#2106]
Issue
-------------

When you use a *paper-drawer-panel*, and you append a *paper-header-panel* as a child, in firefox, the "waterfall-tall" mode doesn't work (the header doesn't condense). It does work on Chrome.
If you remove the *paper-drawer-panel*, leaving just the *paper-header-panel*, it works great.
Don't know what else to do.
(*Note: I post the issue here because there is neither a "paper-drawer-panel" nor a "paper-header-panel" repository.*)

Code
-------------------
```html
<!DOCTYPE html>

<html lang="en">
    <head>
    <!-- Scripts -->
    <script src="libs/bower_components/webcomponentsjs/webcomponents-lite.js" type="text/javascript"></script>
    <link rel="import" href="libs/bower_components/polymer/polymer.html">
    </head>
    <link rel="import" href="libs/bower_components/paper-material/paper-material.html">
    <link rel="import" href="libs/bower_components/paper-drawer-panel/paper-drawer-panel.html">
    <link rel="import" href="libs/bower_components/paper-header-panel/paper-header-panel.html">
    <link rel="import" href="libs/bower_components/paper-toolbar/paper-toolbar.html">
    <paper-drawer-panel force-narrow="true">
        <paper-header-panel drawer>
            <div>Menu</div>
        </paper-header-panel>
        <paper-header-panel main mode="waterfall-tall" tallClass="medium-tall" shadow="true">
            <paper-toolbar justify="center">
                <link rel="import" href="libs/bower_components/iron-image/iron-image.html">
                <link rel="import" href="libs/bower_components/iron-icons/av-icons.html">
                <link rel="import" href="libs/bower_components/iron-icons/iron-icons.html">
                <link rel="import" href="libs/bower_components/paper-icon-button/paper-icon-button.html">
                <paper-icon-button class="bottom" icon="icons:menu" paper-drawer-toggle></paper-icon-button>
                <link rel="import" href="libs/bower_components/font-roboto/roboto.html">
                <span class="bottom title">Title</span>
            </paper-toolbar>
            <div class="content fit">
                content
            </div>
        </paper-header-panel>
    </paper-drawer-panel>
```

Screenshot
-------------------------
![proof](https://cloud.githubusercontent.com/assets/3894464/8757650/66f977a8-2cb2-11e5-8ead-e7e0941ba17a.png)

As you can see, the scroll bar is in the middle, the *paper-header-panel* has the waterfall-tall mode, but it's not condensing.

Additional information
--------------
I've tried several things :

Change the classes in both, drawer and header (every combination you can imagine):
- *flex* and *layout vertical fullbleed* classes.

Change attributes in both, drawer and header (every combination):
- In drawer: *force-narrow*, forcing *height* to 2000px
- In header: Adding and deleting *main* attribute, adding and deleting *tallClass*, forcing *height* of 2000px

None of them did the worked

**Comment by sorvell** [comment]
The issue tracker is for the Polymer core library. We'll make sure this issue gets moved to the appropriate repo.

**Comment by FranNoriega** [comment]
I fix it.
I solved it wrapping all the body content in a template tag, like this:

```html
<body>
    <template is="dom-bind" id="app">
    ...
   </template
</body
```

And adding "dom-change" event listener to the template, in my script file:

```javascript
app.addEventListener("dom-change",function(){
    ...
});
```

Sorry for any inconvenience
