### ISSUE TITLE
Provide a public api to get computed custom style properties for an element

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#2108]
Currently there is `_styleProperties` but this is private. We should consider adding something like `this.customStyle.getComputedStyle`

**Comment by bedeoverend** [comment]
+1 Is there any update or ETA on this? Would love to see it integrated

**Comment by seaneking** [comment]
Looks like this is fixed in https://github.com/Polymer/polymer/issues/2690

**Comment by TimvdLippe** [comment]
Is implemented as [`getComputedStyleValue`](https://www.polymer-project.org/2.0/docs/api/mixins/Polymer.LegacyElementMixin#method-getComputedStyleValue)
