### ISSUE TITLE
Consider allowing <polymer-element> to accept a prototype chain

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#211]
A user tried this construction inside a <polymer-element>

    Polymer('x-foo', (function () {
      var knob = function() {
        this.foo = 'foo';
      }
      knob.prototype.zonk = 'zonk'
      return new knob();
    })());

The user was confused that the resulting element had a 'foo' property but not a 'zonk' property.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) release of Polymer - please feel free to re-open if this is incorrect.
