### ISSUE TITLE
TypeError: Value does not implement interface Node. and other weirdness in Firefox 

### ISSUE THREAD

**Issue by kentaromiura** [Polymer/polymer#212]
Using the same test page with polymer.min.js

Chrome : 
>   document.documentElement == document.getElementsByTagName('html')[0] // true
>   document.documentElement instanceof HTMLElement // true
>   document.getElementsByTagName('html')[0] instanceof HTMLElement //true
>   Object.prototype.toString.call(document.documentElement) // [object HTMLHtmlElement]
>   Object.prototype.toString.call(document.getElementsByTagName('html')[0]) //[object HTMLHtmlElement]
>   document.documentElement.contains(document.querySelector('#ID')) //true
>   document.getElementsByTagName('html')[0].contains(document.querySelector('#ID'))  //true

in FF:
>   document.documentElement == document.getElementsByTagName('html')[0] //false
>   document.documentElement instanceof HTMLElement // false
>   document.getElementsByTagName('html')[0] instanceof HTMLElement //true
>   Object.prototype.toString.call(document.documentElement) // [object HTMLHtmlElement]
>   Object.prototype.toString.call(document.getElementsByTagName('html')[0]) //[object Object]
>   document.documentElement.contains(document.querySelector('#ID')) //TypeError: Value does not implement interface Node.
>   document.getElementsByTagName('html')[0].contains(document.querySelector('#ID')) //true

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) release of Polymer - please feel free to re-open if this is incorrect.
