### ISSUE TITLE
Element properties are undefined when rendering template

### ISSUE THREAD

**Issue by mjgreen145** [Polymer/polymer#2121]
Hey, 

I having an issue trying to do something which seems like it should be simple.
When using a function to get a computed property, the property of the element is undefined.  

See this JSBin: http://jsbin.com/dehiloqawo/edit?html,console,output

I have found that after rendering (where I am logging out the property, it exists. Also, if I wrap the div inside a dom-if template with a condition which is always true, then it renders correctly:

http://jsbin.com/jifiweyade/edit?html,console,output

I don't know whether I'm going about this the wrong way, or whether there is an issue with Polymer. It seems related to either [#310](https://github.com/webcomponents/webcomponentsjs/pull/310) or [#1500](https://github.com/Polymer/polymer/issues/1500), but both of these seems to have been solved.

Any help greatly appreciated.

**Comment by kevinpschaaf** [comment]
Computed properties only compute when their _dependencies_ are set or change.  Your `_getDisplayName` function has a dependency on `this.name` but didn't declare it as a dependency in its signature, and so it is not being re-computed when name is set. Declaring name in the function signature  (e.g. `_getDisplayName(name)` tells Polymer to compute whenever `name` changes.

http://jsbin.com/qipaja/edit?html,console,output

**Comment by mjgreen145** [comment]
Thanks very much @kevinpschaaf
