### ISSUE TITLE
Observation of array.splices does not work

### ISSUE THREAD

**Issue by danimoh** [Polymer/polymer#2123]
Hola.

It seems that observation of array splices via array.splices does not work.
The used Polymer version is 1.0.6.
Here an example snippet:

**Working code using deep path observation:**

```HTML
<dom-module id="friends-list">
	<style>
		:host {
			display: block;
		}
	</style>
	<template>
		<div>
			Friends of: <span>{{user.name}}</span>
			<br/>
			Friends count: <span>{{computeFriendsCountOfUser(friends.*, user.name)}}</span>
			<br/>
			Friends: <span>{{computeFriendsOfUser(friends.*, user.name)}}</span>
		</div>
	</template>
</dom-module>
<script>
	(function () {
		Polymer({
			is: 'friends-list',

			properties: {
				friends: {
					type: Object,
					value: function() {
						return {
							'Lukas': ['Marie', 'Hans'],
							'Hans': ['Harry']
						};
					},
					notify: true
				},
				user: {
					type: Object,
					value: function() {
						return {
							name: 'Lukas'
						};
					}
				}
			},

			computeFriendsOfUser: function(friendsChanges, userName) {
				console.log('computeFriendsOfUser called', friendsChanges);
				return friendsChanges.base[userName] || [];
			},

			computeFriendsCountOfUser: function(friendsChanges, userName) {
				return (friendsChanges.base[userName] || []).length;
			},

			ready: function() {
				var that = this;

				window.debug = window.debug || {};
				window.debug.getThis = function() {
					return that;
				}
			}
		});
	})();
</script>
```

Especially mind, the use of deep path observation here:
```HTML
Friends count: <span>{{computeFriendsCountOfUser(friends.*, user.name)}}</span>
<br/>
Friends: <span>{{computeFriendsOfUser(friends.*, user.name)}}</span>
```

When using array.splices:
```HTML
Friends count: <span>{{computeFriendsCountOfUser(friends.splices, user.name)}}</span>
<br/>
Friends: <span>{{computeFriendsOfUser(friends.splices, user.name)}}</span>
```
The callbacks do not get triggered anymore. Especially the line `console.log('computeFriendsOfUser called', friendsChanges);` does not get called anymore.

When using deep path observation via friends.*, the line `console.log('computeFriendsOfUser called', friendsChanges);` gets performed. However the indexSplices and keySplices entries of the logged friendsChanges object are null although the path points correctly to splices, e.g. "friends.Lukas.splices".

**Data changes that do not work for array.splices:**
```Javascript
window.debug.getThis().set('user.name', 'Hans');
window.debug.getThis().set('user.name', 'Lilli');
window.debug.getThis().set('user.name', 'Lukas');
window.debug.getThis().push('friends.Lukas', 'Lilli');
```

The [docs](https://www.polymer-project.org/1.0/docs/devguide/properties.html) suggest that the array.splices syntax should be supported.

Have a nice day and thanks for your great work on Polymer

**Comment by kevinpschaaf** [comment]
Closing, per response in #2122, which should cover both.  Please re-open if we missed something.  Thanks.
