### ISSUE TITLE
HTML Form submit event not being triggered

### ISSUE THREAD

**Issue by steelbrain** [Polymer/polymer#2128]
Consider you have the following markup
```html
<form id="form" action="javascript:" method="post">
  <input type="text" name="username" />
</form>
<script>
var form = document.getElementById("form")
form.on('submit', function(e){
  e.preventDefault()
  console.log("Hey")
})
</script>
```
now if you focus the input element and press enter, the submit event won't be triggered.
Now if you add `<button>Something</button>` without the form bounds, pressing enter after focusing the event or clicking the button, both would work.
Now if you replace that button with a paper-button `<paper-button raised>Hey</paper-button>`, submit will be impossible again because there's no `button` in the form.
Now if you add `is="iron-form"` to the tag, and the form will be submitted by the paper-button now but it won't trigger the native `submit` event, not even the `iron-form-submit` event.

I am using Google Chrome 43.0.2357.134

**Comment by steelbrain** [comment]
Maybe this can be solved by making `paper-button` extend the `button` tag?

**Comment by tjsavage** [comment]
Hm... Seems to me like an issue with `iron-form` - will move there.

**Comment by tjsavage** [comment]
This issue was moved to PolymerElements/paper-button#34
