### ISSUE TITLE
Error on documentacion 

### ISSUE THREAD

**Issue by summers173** [Polymer/polymer#2129]
On this section

https://www.polymer-project.org/1.0/docs/devguide/events.html#gestures

On the code 'Example with listeners:' the code

listeners: {
        track: 'dragme.handleTrack'
      },

is not working, acording to the above documentation should be:

listeners: {
        'dragme.track': 'handleTrack'
      },

Regards

**Comment by tjsavage** [comment]
This issue was moved to Polymer/docs#1270
