### ISSUE TITLE
updateStyles() will throw exception when webcomponents are loaded asynchronous (in FF and IE)

### ISSUE THREAD

**Issue by dombre** [Polymer/polymer#2130]
Polymer.updateStyles() will throw an exception when the webcomponents are loaded dynamically. The argument `node` is in this case undefined for `Polymer.StyleUtil.forEachStyleRule` resulting in a `TypeError: node is undefined`.

This is only an issue in Firefox and IE. It *does* work in Chrome. 

Here is a minimal example:

1. Click the Button 'load elements'
2. Click the Button 'update styles'

Unexpected behavior: Exception in FF and IE. 
Expected behavior: the toolbar changes to red (it does so in Chrome).

```html
<!doctype html>

<html>
<head>
  <script src="../bower_components/webcomponentsjs/webcomponents-lite.js"></script>
</head>

<body>

  <paper-toolbar>Test</paper-toolbar>

  <button onclick="loadElements()">1. load elements</button>
  <button onclick="updateStyles()">2. update styles</button>

  <script>

    function updateStyles() {
      Polymer.updateStyles({ '--paper-toolbar-background': 'red' });
    }

    function loadElements() {
      var elImport = document.createElement('link');
      elImport.rel = 'import';
      elImport.href = '../bower_components/paper-toolbar/paper-toolbar.html';

      document.head.appendChild(elImport);
    }

  </script>

</body>
</html>
```

**Comment by dombre** [comment]
After fiddling around a bit I have found out that it does work if Polymer is already registered.

Change the `loadElements` function from the above example to this
```javascript
function loadElements() {
      var elImport = document.createElement('link');
      elImport.rel = 'import';
      elImport.href = '../bower_components/polymer/polymer.html';
      elImport.onload = function() {
            Polymer.importHref('../bower_components/paper-toolbar/paper-toolbar.html');
      };

      document.head.appendChild(elImport);
}
```
and the custom css property will be applied correctly in FF and IE.

**Comment by sorvell** [comment]
I can confirm this problem. It's a bug in the webcomponentsjs polyfills, particularly the interaction of asynchronously loaded imports and registering custom elements in them. The elements can upgraded in unexpected order in this case.

Closing this issue in favor of https://github.com/webcomponents/webcomponentsjs/issues/357 where this problem should be resolved.
