### ISSUE TITLE
Thoughts on registering behaviors (non-globals)

### ISSUE THREAD

**Issue by benjaminapetersen** [Polymer/polymer#2133]
Love the idea of behaviors (new since I was last in a Polymer project)!

Thoughts on a simple way to register behaviors to get them out of global scope but still allow sharing?  My initial impression would be to do something to the effect of `Polymer.behavior('someBehavior', { /*..*/ })` and then be able to access them more or less the same way in an element definition `Polymer({
  is: 'super-element',
  behaviors: ['someBehavior']
});`  The behavior names would have to be strings at this point to allow for lookup, but might make for a tidier global scope.

**Comment by TimvdLippe** [comment]
With HTML imports, behaviors will still be referenced in the global manner. Using ES6 modules, you can remove the need for cluttering the global scope and simply `export` and `import` your behaviors. Since this issue is solved by using a different loading mechanism, I am closing this issue for now.
