### ISSUE TITLE
Permanent sw-import.js ... ?

### ISSUE THREAD

**Issue by lukeed** [Polymer/polymer#2136]
Hi all,

Sorry ahead of time -- I don't full understand service workers yet.

I was poking around inside the starter kit & got to a point where I wanted to test out the mobile offline capabilities. So I turned on sw-import, everything cached correctly. No problems here.

However!

Now, in a completely different, work-related project, the sw-import.js file is still attached to my Chrome, somehow(?).

It's caching all of this project's development assets, which **is** cool, but also really annoying atm.
Also, every time I attempt to use DevTools Console, its scope (I guess you can call it that?) is selected to sw-import.js. This also means I can't access `document` until I switch the scope back to `<top frame>`

How do I turn this off??

Attached is a screenshot of Console, from within the *other*, non-Polymer project. You can see that the scope is set to sw-import.js. The server is actually turned OFF here, but the page (and all its linked pages) are fully functional. The errors are BrowserSync's socket looking for an instance, but the server is off.

![screen shot 2015-07-23 at 12 00 43 am](https://cloud.githubusercontent.com/assets/5855893/8844949/62d57890-30cf-11e5-8d09-32937f3d73c3.png)

**Comment by lukeed** [comment]
A full restart of Chrome fixed the issue.

Although, I'd still like to know if it's possible to turn off a service worker without a full restart.
Because of this, leaving the issue open. Hopefully someone has an answer :8ball:

**Comment by kevinpschaaf** [comment]
Have you tried chrome://serviceworker-internals/ to unregister the SW?

There are more details here:
http://www.html5rocks.com/en/tutorials/service-worker/introduction/

**Comment by lukeed** [comment]
Looks like `chrome://inspect/#service-workers` would have been it, thanks!

Had totally forgotten about chrome:://inspect... wish there was a link to it from Console or something

**Comment by Huxpro** [comment]
@kevinpschaaf  thanks

**Comment by samccone** [comment]
cc @paulirish (real world example of someone getting confused)^^^

Looks to be a bit more confusion around what we were talking about last week via the console context ;)

**Comment by birkir** [comment]
Also, the service workers can be explored in DevTools by enabling an experimental flag in the settings.
<img width="1003" alt="screen shot 2015-09-27 at 23 51 15" src="https://cloud.githubusercontent.com/assets/180773/10125856/aef8ec8e-6572-11e5-91c2-1fa0bff3ae59.png">
