### ISSUE TITLE
TypeError: factory(...) is undefined

### ISSUE THREAD

**Issue by andrerodri** [Polymer/polymer#2138]
Hi, i am having this error when i use the following code:
Polymer.dom(this).appendChild(xmlhttp.responseText);

also when i use:
Polymer.dom(this.$.dump).appendChild(xmlhttp.responseText);

where dump is an id of a div inside my dom-module:
```
<div id="gallery">
      <paper-button class="back-button" on-click="return" raised><-</paper-button>
      <p>Image Gallery</p>
      <div id="dump">

      </div>
 </div>
```
gives me this error:
this.$ is undefined

any ideia? thx for the help...

**Comment by sorvell** [comment]
You cannot append text directly to an element. Make a text node first and append that. For example,

```
var textNode = document.createTextNode(xmlhttp.responseText);
Polymer.dom(this).appendChild(textNode);
```
