### ISSUE TITLE
Incorrect Redirect

### ISSUE THREAD

**Issue by jpmedley** [Polymer/polymer#2143]
The file polymer-tutorial-master/README.md contains a link to http://polymer-project.org/docs/start/tutorial/intro.html, which redirects to a location for 0.5 documentation. Since 1.0 has been released, I'm guessing this is incorrect.

**Comment by TimvdLippe** [comment]
ping @arthurevans

**Comment by arthurevans** [comment]
Where did you find the file? If this was in Polymer/polymer-tutorial, the link is correct (that's the 0.5 tutorial), but we ought to add a deprecation and pointer to the 1.0 tutorial.

**Comment by TimvdLippe** [comment]
Closing this issue as the docs are now updated for both 1.0 and 2.0 and I can't find this link any longer.
