### ISSUE TITLE
Clarification on Behavior Lifecycle Callback Order

### ISSUE THREAD

**Issue by zerodevx** [Polymer/polymer#2144]
According to the docs (https://www.polymer-project.org/1.0/docs/devguide/behaviors.html), 
> Lifecycle callbacks are called on the base prototype first, then for each behavior in the order given in the `behaviors` array.

which I understand is `element` first, then `behaviors`.

I'm using Chrome 43, and it seems lifecycle callbacks are called on `behaviors` first, then `element`? Is this expected?

Repro (http://jsbin.com/xibijujaje/edit?html,console)

Thanks,
J

**Comment by kevinpschaaf** [comment]
Confirm the typo in the documentation, you are correct it is "behaviors first in the order given in the behaviors array, followed by the prototype."

There is already a bug open on our documentation issue tracker here, so I'll close this one in lieu of that one: https://github.com/Polymer/docs/issues/1258 (and bump it).

Thanks for the report.
