### ISSUE TITLE
innerText

### ISSUE THREAD

**Issue by deni35** [Polymer/polymer#2147]
Why does your dom not support the innerText ? 
I try to use the textContent:

``` js
Polymer.dom(msg).textContent = text;
```

but it doesn't support a new line character.

Now I use the next code:

``` js
Polymer.dom(msg).innerHTML = text.replace(new RegExp('\n', 'g'), '<br>');
Polymer.dom.flush();
```

It works.

I think that it would be the best to have simply access to content element. For example: 

``` js
message.content.innerText = text; // or innerHtml or textContent.
```

Or to override this properties that it works as native shadow dom, if it's possible.

**Comment by kevinpschaaf** [comment]
Ok, we'll consider adding proper `textContent` support as a feature enhancement.

**Comment by TimvdLippe** [comment]
`Polymer.dom` has been removed in Polymer 2, so I think we can close this issue?

**Comment by TimvdLippe** [comment]
Closing per above comment.
