### ISSUE TITLE
Suggestion: dom-recursive element for tree structured data

### ISSUE THREAD

**Issue by makroiss** [Polymer/polymer#2151]
Usage would be as follows:

```
var animals= {
    title: "mammal",
    subspecies: [ {
        title: "tiger",
        subspecies: [ {
            title: "white tiger"
        } ]
    }, {
        title: "wolf"
    } ]
}

<template is="dom-recursive" tree="{{animals}}" children="subspecies">
<span>{{item.title}}</span>
<span>{{depth}}</span>
<span>{{parent.title}}</span>
</template>
```

while depth and parent are automatically calculated

**Comment by TimvdLippe** [comment]
There are various elements available on webcomponents.org at https://www.webcomponents.org/search/tree. For example I found https://www.webcomponents.org/element/nuxeo/nuxeo-ui-elements/elements/nuxeo-tree which might fit your usecase. Therefore I am closing this issue, as the community has some ready-made solutions.
