### ISSUE TITLE
Polymer and Turbolinks doesn't load content

### ISSUE THREAD

**Issue by nonameolsson** [Polymer/polymer#2153]
As you can see in the video, the new content isn't being loaded into the DOM. Is this because of how Polymer and Turbolinks works?

https://www.youtube.com/watch?v=Zqtn9uxI1xs

Update with a simple rails app: https://github.com/nonameolsson/polymerapp

**Comment by kevinpschaaf** [comment]
We'll need a _minimum reproduction test case_ to help debug your issue.

Can you try and stand up a very simple example that exhibits the problem?

**Comment by nonameolsson** [comment]
@kevinpschaaf I created a basic Rails app with polymer and paper- drawer. I'll post the link to the repo in the issue content. 
Is it okay with this example?

**Comment by kevinpschaaf** [comment]
Sure, you can link the repo, but it will probably be worth your time to create the most bare-bones example possible that reproduces the problem you are seeing (i.e. remove as much unrelated complexity as possible).

**Comment by azakus** [comment]
Closed due to age, please reopen if this is still a problem.
