### ISSUE TITLE
Property bindings not working in templates with whitespaces or other combinations

### ISSUE THREAD

**Issue by codependent** [Polymer/polymer#2156]
In the quick tour property binding example, there is a component defined this way:

```
<dom-module id="name-tag">

  <template>
    <!-- bind to the "owner" property -->
    This is <b>{{owner}}</b>'s name-tag element.
  </template>

  <script>
  Polymer({
    is: "name-tag",
    ready: function() {
      // set this element's owner property
      this.owner = "Daniel";
    }
  });
  </script>
  
</dom-module>
```

If the `<b>` tags are removed:
```
  <template>
    <!-- bind to the "owner" property -->
    This is {{owner}}'s name-tag element.
  </template>
```

We would expect to have `This is Daniel's name-tag element.`, but the content that is rendered is `This is {{owner}}'s name-tag element.`.

The same happen trying other stuff, such as several properties, etc:

`This is {{owner}}{{owner}}'s name-tag element.`
`This is {{owner}}-{{owner}}'s name-tag element.`

Here is a test [JSFiddle](https://jsfiddle.net/fwtewh8n/2/)

**Comment by timeu** [comment]
According to the [documentation](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#binding-to-text-content): 
> String concatenation is not supported inside a tag, and the tag can’t contain any whitespace

So you must wrap the binding into a tag: `This is <span>{{owner}}</span>'s name-tag element.`

**Comment by codependent** [comment]
Er, right... I should've seen it, sorry.

Anyway, any plans to support this in the future?

**Comment by timeu** [comment]
AFAIK it is on the roadmap: https://www.polymer-project.org/1.0/docs/#binding-features

**Comment by codependent** [comment]
@timeu Thanks for the info!! I'm closing the issue then
