### ISSUE TITLE
paper-header-panel layout issue - good in jsbin but bad locally. 

### ISSUE THREAD

**Issue by dman777** [Polymer/polymer#2159]
I am not sure if this is a issue with `paper-header-panel` or with the layout system. In http://jsbin.com/zuvami/edit?html,css,output, the image is under the  `paper-header-panel` as it should be....this is proof of how it should work. 

But locally, `paper-header-panel`  is `603px` in height and flexes...the height grows/shrinks with a empty gap  pushing the bottom image. 

![pic2](https://cloud.githubusercontent.com/assets/887815/8922573/3c2b105e-34aa-11e5-87b4-51d3c5dd5fdc.jpg)
![pic3](https://cloud.githubusercontent.com/assets/887815/8922587/54e269b2-34aa-11e5-9ac6-b09f44012a72.jpg)

Same code between jsbin and locally. Here are the script files I am using locally:

```html
  <script src="bower_components/webcomponentsjs/webcomponents.js"></script>
  <link rel="import" href="bower_components/paper-header-panel/paper-header-panel.html">
  <link rel="import" href="bower_components/paper-tabs/paper-tabs.html">
  <link rel="import" href="bower_components/paper-toolbar/paper-toolbar.html">
  <link rel="import" href="bower_components/iron-flex-layout/classes/iron-flex-layout.html">
  <link rel="import" href="bower_components/polymer/polymer.html">
  <link rel="import" href="custom_elements/video-player.html">
  <link rel="stylesheet" href="css/main.css">
```

I am using:
iron-overlay-behavior - 1.0.4
paper-header-panel 1.0.2
polymer 1.0.3
webcomponents 0.7.3

**Comment by robrez** [comment]
I'm not sure if this intentional or not, but I noticed that your `<div>` is outside the `<paper-header-panel>`.

Whenever I've used it, my content has all been inside the header-panel tags; not unlike this snippet from paper-header-panel/demo/index.html..

```
      <paper-header-panel class="blue">
        <div class="paper-header">standard</div> <!-- paper-toolbar works here -->
        <div class="content"></div>
      </paper-header-panel>
```

**Comment by dman777** [comment]
I modified `bower_components/paper-header-panel/paper-header-panel.html` and I removed:
```html
<link rel="import" href="../polymer/polymer.html">
<link rel="import" href="../iron-flex-layout/iron-flex-layout.html">

```

and it made the issue *better*. The gap was gone!

![pic4](https://cloud.githubusercontent.com/assets/887815/8948829/4279311c-3571-11e5-94c5-3019a4dd6a35.jpg)

**Comment by dman777** [comment]
After doing some experiementing, I removed `<link rel="import" href="bower_components/paper-header-panel/paper-header-panel.html">` and it fixed the issue. This makes no sense to me because I am using `<paper-header-panel>` and the header still shows. Where is `paper-header-panel` coming from?

```html
<!doctype html>
<html>

<head>

  <script src="bower_components/webcomponentsjs/webcomponents.js"></script>

  <link rel="import" href="bower_components/paper-tabs/paper-tabs.html">
  <link rel="import" href="bower_components/paper-toolbar/paper-toolbar.html">
  <link rel="import" href="bower_components/iron-flex-layout/classes/iron-flex-layout.html">
  <link rel="import" href="bower_components/polymer/polymer.html">
  <link rel="import" href="custom_elements/video-player.html">
  <link rel="stylesheet" href="css/main.css">
  <style is="custom-style">
    body {
      font-family: sans-serif;
    }
    paper-tab {
      flex: none;
    }
  </style>
</head>
<body>
  <paper-header-panel>
    <paper-toolbar>
        <div class='title'>
          TITLE
        </div>
        <paper-tabs>
          <paper-tab>
              ABOUT
          </paper-tab>
          <paper-tab>
            <div>
              TOUR SCHEDULE
            </div>
          </paper-tab>
            <paper-tab>
              <div>
                VIDEOS
              </div>
            </paper-tab>
            <paper-tab>
              <div>
                HOST
              </div>
            </paper-tab>
            <paper-tab>
              <div>
                LONG TITLE THIS IS
              </div>
            </paper-tab>
        </paper-tabs>
    </paper-toolbar>
  </paper-header-panel>
    <div class="flex relative" style="width: 100%; height: 100%">
      <div id="video-photo-container" class="fit">
      </div>
    </div>
</body>
<script src="http://104.130.126.121:35729/livereload.js?snipver=1"></script>
</html>
```

![pic4](https://cloud.githubusercontent.com/assets/887815/8948905/f7a53798-3571-11e5-8dc0-0e6902cb6adb.jpg)

**Comment by dman777** [comment]
Moving to https://github.com/PolymerElements/paper-header-panel/issues/34
