### ISSUE TITLE
Feature Request: a "when ready" behaviour

### ISSUE THREAD

**Issue by tigerhawkvok** [Polymer/polymer#2160]
What I imagine is this:

At any point, one may create an object with the following:

```javascript
var myElementRuntimeCallback = {
  selector: "element-selector > here",
  run: function() {}
}
```

then, attach this to, say, `Polymer.whenReady`:

```javascript
window.Polymer.whenReady.push(myElementRuntimeCallback);
```

When appended to the `whenReady` key, that `myElementRuntimeCallback.selector` is checked to see if that element (a) exists and (b) is attached.

If it exists and is attached, `myElementRuntimeCallback.run` is run immediately

If it exists and is not attached, the `run` is used as the `attached` callback for the element matching the selector.

If it does not exist, it is simply stored. When a new element is created, the list of selectors is checked for a match, and any matches are attached to the `attached` event. 

Hope this isn't a duplicate, or something existing I just completely missed/misunderstood.

**Comment by azakus** [comment]
We don't plan on implementing this in Polymer, but you do something like this by overriding `document.registerElement` and tracking the "readyness" of elements on your own.
