### ISSUE TITLE
Unable To run Any polymer designed app on node server

### ISSUE THREAD

**Issue by ramaraman** [Polymer/polymer#2161]
Now I am trying from last many weeks i am unable to run polymer designed web page on my node server!!
All i get is everythng blank!!
![image](https://cloud.githubusercontent.com/assets/13233022/8930264/674fa9e8-34e1-11e5-940c-43e5ccd32488.png)

(index html)
![image](https://cloud.githubusercontent.com/assets/13233022/8930287/843cfdc6-34e1-11e5-9ef7-b3dde3d3a1a1.png)

(java script)
![image](https://cloud.githubusercontent.com/assets/13233022/8930313/ae191940-34e1-11e5-9bfb-bb04698d83a9.png)

**Comment by toadkicker** [comment]
This sounds like you might be missing the path to webcomponents.js from what I guess. The fact the body tag has an unresolved attribute means that your js isn't being executed on the browser side. It's worth checking other requests for content and make sure that node isn't sending index.html on every request.

**Comment by ramaraman** [comment]
Dear brother @toadkicker  actually,
I am trying to run that on http server but i am unable to render any file on node's http server.
The same code is working great with python !!

**Comment by totrash** [comment]
Please paste a Network tab results from Chrome DevTools

**Comment by biels** [comment]
Is there any way to render polymer applications in a node.js http server? I know http-server does but can't find out how.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
