### ISSUE TITLE
Internet Explorer - not working at all

### ISSUE THREAD

**Issue by g00fy-** [Polymer/polymer#217]
From what I understand, polymer should work with the most recent version of IE.
I have been visiting polymer website for 3 weeks now, trying to find out if it's really compatible with IE, but the examples posted on the `Getting started` page don't work at all.

Did I miss something ? Are there any examples of polymer working on IE 10.0.7 + ?

**Comment by dimuthu28** [comment]
hi sjmiles,
i want to know whether polymer compatible with IE 9 or not (it is says most of features are work with IE 9) so would like to know what are the feature that support for IE9.
