### ISSUE TITLE
Non Supported Browser Event Hook

### ISSUE THREAD

**Issue by oleersoy** [Polymer/polymer#2171]
In this issue:
https://github.com/Polymer/polymer/issues/207

It says that Polymer will trigger a dialog box if the client does not support Polymer.  Is it possible to listen for this event?

**Comment by pensierinmusica** [comment]
+1, imho this would be very much needed!

@ebidel, @arthurevans, @addyosmani is this being implemented?

(relates to https://github.com/webcomponents/webcomponentsjs/issues/26)

**Comment by TimvdLippe** [comment]
If you load the polyfills (https://www.webcomponents.org/polyfills) browsers that do not have implemented the native API are supported as well.
