### ISSUE TITLE
Support Array.reverse on element prototype

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#2175]
I'm reversing an array and it's not being picked up by the data binding system.

**Comment by kevinpschaaf** [comment]
In general, we'd prefer people use `dom-repeat`'s sort feature rather than do in-place sort/reverse of the array (note we don't support in-place `sort` on Polymer.Base either).

In the short-term, you should be able to do `this.myArray = this.myArray.slice().reverse();`

**Comment by ebidel** [comment]
That's my current workaround: https://github.com/GoogleChrome/chromium-dashboard/blob/1.0/static/elements/chromedash-metrics.html#L142

In my case there are two issues with using `dom-repeat`'s sort. 
- The docs say you need to add/remove from the array for the dom-repeat to sort. Is there a way to re-render dom-repeat's model without changing array.length?
- I have a `sortOrder` object that's responsible for managing the sorting state of the NAME/PERCENTAGE columns (https://www.chromestatus.com/metrics/css/popularity). My `dom-repeat` sorts a single `viewList` based on user selection.

There might be a more idiomatic 1.0 way to do `#2`.

**Comment by kevinpschaaf** [comment]
For #1, you can kick it with `render()` (https://github.com/Polymer/polymer/blob/master/src/lib/template/dom-repeat.html#L79-L82), although I've also gotten into the habit of using an computing function for the actual sort function that is dependent on an outside property (e.g. `sortOrder`), and returns a new sort function that closes over the outside property.

For example:
```html
<dom-repeat items="{{items}}" sort="{{computeSort(sortOrder)}}">
```
```js
computeSort: function(sortOrder) {
  return function(itemA, itemB) {
    return itemA.foo.localeCompare(itemB.foo) * sortOrder;
  }
}
```
Note that normally `sort` takes a literal string as the name of the sort function (no binding), but it can also take a function reference directly; so we can bind an inline function to `sort` that returns a new sort function each time the dependent `sortOrder` property changes, which will cause the list to be re-sorted with that function directly.  Not sure if this matches your exact case or not...?

**Comment by arthurevans** [comment]
You don't mention why you're re-sorting (besides changing the sort order) but if you're changing values used by the sort function, you can use the `observe` property to re-sort when certain item properties change, like:

    <dom-repeat items="{{items}}" sort="{{computeSort(sortOrder)}}" observe="name percentage">

**Comment by ebidel** [comment]
@kevinpschaaf that's a really good idea. I didn't realize it could take a binding. I'll give it a try and report back. 

@arthurevans that would be useful, but I'm not changing any property values. Just _what_ prop is sorted.

**Comment by TimvdLippe** [comment]
Still an issue with Polymer 2: http://jsbin.com/komohelayo/edit?html,console,output

**Comment by TimvdLippe** [comment]
Actually, this is now possible in Polymer 2 with the `MutableData` mixin: http://jsbin.com/helefatowa/edit?html,console,output This is documented at https://www.polymer-project.org/2.0/docs/devguide/model-data#array-mutation

> Use the MutableData mixin. For elements that include the Polymer.MutableData mixin, calling set or notifyPath on an object or array causes Polymer to re-evaluate the entire object graph starting at that object or array, even if the object or array itself hasn't changed. For details, see Using the MutableData mixin.
