### ISSUE TITLE
paper-scroll-header-panel content wont scroll on iOS only

### ISSUE THREAD

**Issue by tehaaron** [Polymer/polymer#2178]
I have a pretty straight-forward SPA that uses paper-scroll-header-panel, paper-toolbar, paper-tabs, and iron-pages. When I click on the first paper-tab in iOS and it displays the corresponding iron-page it does not allow me to scroll down and view the iron-page content below the fold...However, if I click another tab and then come back the scrolling works fine.

I can see the content cut off on the bottom of the screen but when you drag up it just pulls the page off the bottom of the screen as if it was the end of the page.

Here is the very basic html structure:
```html
<paper-scroll-header-panel condenses keep-condensed-header>
    <paper-toolbar class="tall layout horizontal" id="title-toolbar">
      <div class="bottom bottom-container horizontal layout">
        <div class="bottom-title paper-font-subhead">Title</div>
      </div>

    </paper-toolbar>
    <div id="content" class="content-dark">
      <div class="horizontal center-justified layout">
        <!-- some body content here -->
      </div>

      <paper-toolbar justify="center">
          <paper-tabs selected="{{selected}}" class="fit" scrollable>
              <paper-tab>1</paper-tab>
              <paper-tab>2</paper-tab>
              <paper-tab>3</paper-tab>
              <paper-tab>4</paper-tab>
          </paper-tabs>
      </paper-toolbar>
        <iron-pages selected="{{selected}}">
            <div><!-- page content --></div>
            <div><!-- page content --></div>
            <div><!-- page content --></div>
            <div><!-- page content --></div>
        </iron-pages>
    </div>
  </paper-scroll-header-panel>
```

**Comment by tehaaron** [comment]
Originally, I had opted not to have a tab selected by default. However, when I decided to have a tab selected on load via the below code I no longer ran into this issue. It still seems to be a problem though as you shouldn't have to have one selected from the start.

window.addEventListener('WebComponentsReady', function() {
    // imports are loaded and elements have been registered
    var template = document.querySelector('template[is="dom-bind"]');
    template.selected = 0; // selected is an index by default
});

**Comment by robrez** [comment]
I saw this happen sporadically on my nexus 6 recently (maybe not limited to ios).

@tehaaron - You may want to move the issue over to the element's page.
https://github.com/PolymerElements/paper-scroll-header-panel/issues

**Comment by tehaaron** [comment]
I moved this issue to the paper-scroll-header-panel repository as suggested by @robrez.

**Comment by kevinpschaaf** [comment]
Closing, moved to https://github.com/PolymerElements/paper-scroll-header-panel/issues/35.
