### ISSUE TITLE
paper-checkbox doesn't allow the use of keyboard

### ISSUE THREAD

**Issue by rasto68** [Polymer/polymer#2179]
I noticed this when adding a checkbox to my own app, and the demo page confirms it:
https://elements.polymer-project.org/elements/paper-checkbox?view=demo:demo/index.html

If you tab through the checkboxes the focus animation plays (and pauses ?) but you can't change the checkbox using the keyboard. I've tried this against Chrome, Firefox and IE on windows.

**Comment by rasto68** [comment]
I've just upgraded my app to use the 1.0.5 release of the checkbox and keyboard input now works.

I guess the demo page is using the same (1.0.0) version that the catalog/my collection option gives you. If the documentation points you at 1.0.0 then that is almost certainly the version you will download, so I guess it would be nice if this could be kept in sync with new releases although I appreciate that this requires additional effort.

**Comment by peduxe** [comment]
You're right, it's deps is still on 1.0.0.

https://github.com/PolymerElements/paper-checkbox/blob/master/bower.json#L35

The catalog itself is using Polymer the latest, v1.08.
![Polymer.version](http://i.imgur.com/KkgGVwI.png)

**Comment by frankiefu** [comment]
The version seems correct to me.  `bower install --save PolymerElements/paper-checkbox#^1.0.0` seems to give me the right stuffs (1.0.5 paper-checkbox and 1.0.8 polymer).  I think you might be hitting an issue in paper-checkbox which sometimes keyboard might not work.  I have filed an issue in paper-checkbox here: https://github.com/PolymerElements/paper-checkbox/issues/46

**Comment by rasto68** [comment]
The following is the bower command that you get if you copy the text from the documentation, when I ran this I got the 1.0 version of the checkbox:

bower install --save PolymerElements/paper-checkbox

This is the command that people will use if they follow the documentation, so maybe this needs to be updated.

![checkbox](https://cloud.githubusercontent.com/assets/3791099/9054792/be2f583a-3a7c-11e5-9cd5-0a34cfabadcd.png)
