### ISSUE TITLE
computed binding multiple arguments not called

### ISSUE THREAD

**Issue by TimWillis** [Polymer/polymer#2184]
When I do something like this ->

```html
<span hidden$="[[compare(items.totalCost,items.totalCost_2)]]">test</span>
```
```js
, compare: function(var_1, var_2){
        return (var_1 == var_2)
    }
```
the compare function does not get called if items.totalCost is undefined, but if I only pass one argument to compare -> $<span hidden$="[[compare(items.totalCost)]]"> the compare function is called.

**Comment by robrez** [comment]
this was also raised here the other day:
https://github.com/Polymer/polymer/issues/2158

From the [docs](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#dependent-properties):
>The computing function is not called until all dependent properties are defined (!=undefined).

**Comment by kevinpschaaf** [comment]
Closing as a duplicate of #2158
