### ISSUE TITLE
Custom CSS properties & styling distributed children

### ISSUE THREAD

**Issue by miztroh-zz** [Polymer/polymer#2188]
I have a custom element that serves as a wrapper for page content.  I am intending for this element to style its distributed children to ensure a consistent theme.  I've come across the following issue in the `style` portion of my `dom-module`.  The CSS snippet below renders `paper-checkbox` as shown in the attached image.

```
#contentWrapper > ::content paper-checkbox {
      --paper-checkbox-checked-color: red;
      --paper-checkbox-checked-ink-color: red;
      --paper-checkbox-unchecked-color: red;
      --paper-checkbox-unchecked-ink-color: red;
      background: red;
}
```

![paper-checkbox](https://cloud.githubusercontent.com/assets/2515209/9045293/ab27e6ca-39e7-11e5-9cd7-f6e816f13dd4.png)

As you can see, the background (made red for testing purposes) renders as expected.  However, none of the custom properties seem to work.  Am I doing something wrong?

**Comment by kevinpschaaf** [comment]
This is currently not supported.  The custom property shim only allows assignment of variables in its host element (the owner of the local dom root), not its light parent tree (where you put the `::content` rule).

Minimum repro: http://jsbin.com/ruyicin/edit?html,console,output

For now, the only workaround we have to give you is to find the elements you want to style, manually set their custom style (e.g. `element.customStyle['--paper-checkbox-checked-color'] = 'red';`) and call `element.updateStyles()`.

Workaround applied to above example: http://jsbin.com/zigolo/edit?html,console,output

We have ideas on how to improve the shim to support this, so we'll keep the issue open to track addition of that feature.

**Comment by miztroh** [comment]
@kevinpschaaf Is it possible to watch for changes to distributed children?  Then I could modify ``element.customStyle`` and call ``element.updateStyles()`` more dynamically.

**Comment by kevinpschaaf** [comment]
We are working on a "distributed children changed" event/callback right now that will definitely help your use case. You can follow this issue https://github.com/Polymer/polymer/issues/1773 for status.

**Comment by miztroh** [comment]
@kevinpschaaf Awesome.  Thanks for pointing me to that other issue.

**Comment by miztroh** [comment]
My situation involves a custom element that acts as a wrapper for page content.  The custom element includes all the header, search, nav, and footer elements.  Page content comes through as distributed children.  In light of the 1.1 release, the following is a better (hopefully temporary) workaround for me to enable my custom element to theme its children:

```
Polymer(
	{
		is: 'my-custom-element',
		ready: function () {
			var ss_link = document.createElement('link');
			ss_link.rel = 'import';
			ss_link.href = '/path/to/my-shared-styles/my-shared-styles.html';
			document.head.appendChild(ss_link);
			
			var ss_style = document.createElement('style', 'custom-style');
			ss_style.setAttribute('include', 'my-shared-styles');
			document.head.appendChild(ss_style);
		}
	}
);
```

**Comment by klebba** [comment]
It would be great if the docs made mention of this limitation
