### ISSUE TITLE
Use platform.js to overwrite native (faulty) web components behavior

### ISSUE THREAD

**Issue by freddyb** [Polymer/polymer#2189]
I am on an unstable browser version and would like to continue using platform.js even though the browser seems to have web components (but does not fully). platform.js feature detection bails out early, but I would like it not to.

Any hints on how to get this? I'd be happy to add a one-line-patch to my local version of platform.js if this does not work with vanilla Polymer.

**Comment by kevinpschaaf** [comment]
[`platform.js`](https://github.com/Polymer/platform) is very old and deprecated and is no longer being maintained at this point; it was migrated last year to [`webcomponents.js`](https://github.com/webcomponents/webcomponentsjs).  (Additionally as you may be aware, Polymer 1.0 as moved away from the full webcomponents polyfill and only requires the `webcomponents-lite.js` polyfill, so support for older versions of Polymer requiring those polyfills will be limited at this point).

That said, if you could provide some more information about the exact browser version and nature of the problem, we might be able to give some quick advice on how to unblock you.

**Comment by freddyb** [comment]
The platform I am on is a Firefox OS nightly build, but you can easily reproduce using Firefox Nightly for Desktop.

Steps to Repeat:
  1. Download and run Firefox Nightly from http://nightly.mozilla.org/
  2. Go visit a web page that uses platform.js, e.g. http://mozbrick.github.io/brick-appbar/ and observe that it looks like a horizontal, top-aligned app bar.
  3. In another tab, go to the URL `about:config` and set the `dom.webcomponents.enabled` preference to `true`
  4. Refresh the first tab and observe that it does not work anymore.

My assumption was that platform.js bails out, even though the native support is not complete. I understand that your polyfill is certainly not meant to test all the features, to make sure that native support is actually complete. I know I am on Nightly and thus on unsafe grounds.

But it would be very useful to know if my assumption is correct and would like to identify where platform.js tests for native support to bail out early. I would like to avoid this in my specific case.

I assume that this might still be the case for your new polyfills, but will test and report back in another comment soon.

**Comment by freddyb** [comment]
I have confirmed that the same behavior (see Steps to Repeat in my previous comment) can be observed with `webcomponents.js`.

**Comment by kevinpschaaf** [comment]
In platform.js, you should be able to put flags on the query string (or alternatively as attributes on the `<script src="platform.js">` tag) that force the polyfills on.

See https://github.com/Polymer/platform-dev/blob/master/platform.js#L29 for the logic that determines whether to polyfill Shadow DOM. There's a similar `register` flag for Custom Elements.

Can you try `?shadow=true&register=true` on your URL to see if that helps?

**Comment by freddyb** [comment]
That does not seem to work, nope.

**Comment by azakus** [comment]
With `webcomponents.js`, you can use `wc-shadow` and `wc-register` flags in the window location to turn off native Custom Elements and Shadow DOM: http://output.jsbin.com/sulote?wc-shadow&wc-register
