### ISSUE TITLE
The `offsetParent` is wrong in the `attached` callback

### ISSUE THREAD

**Issue by notwaldorf** [Polymer/polymer#2193]
on Chrome 43.0.2357.134 (Official Build) (64-bit), this code doesn't have an `offsetParent`. It works on FF and Safari:

https://gist.github.com/notwaldorf/44da856a3debdc8ab289

**Comment by sorvell** [comment]
This looks like a Chrome bug to me. I've filed:

https://code.google.com/p/chromium/issues/detail?id=516550

**Comment by sorvell** [comment]
After discussing this with some Blink engineers, it looks like fixing the bug will take a non-trivial amount of time. In the meantime, Polymer can use a slightly beefed up version of `Polymer.ImportStatus.whenLoaded(cb)` to defer calling `attached` slightly to avoid querying style/layout data too soon.
