### ISSUE TITLE
Change on-click event in an element

### ISSUE THREAD

**Issue by andrerodri** [Polymer/polymer#2199]
Hello all,

i want to give thanks for helping me previously with an issue i had. This time, i ran into a more difficult one: i need to change the function that is called in an on-click event for an element. Here is my html code:

```html
<dom-module id="single-question">
...
<template>
...
<button id="ba1-q1" class="btn add-more" type="button" on-click="addMore">+</button>
...
</template>
...
</dom-module>
```

and my javascript code to capture that button and what i want to do:
```javascript
var button = Polymer.dom(this.root).querySelector("#ba1-q1");
button.innerHTML = "-";
button.on-click = function(){
    alert("bluuuuuu");
}

or

var button = Polymer.dom(this.root).querySelector("#b"+t.id);
button.innerHTML = "-";
button.on-click = this.removeAnswer();
}
```
where removeAnswer() is a function defined inside Polymer element definition, in javascript code.
I know you can change/remove a function that is called with onClick and eventListeners but i want to do the same here in Polymer. Any ideia?

**Comment by sorvell** [comment]
First, I encourage you to put the indirection you need inside the click handler so you don't have to change the handler function itself. For example,

```
clickHandler: function() {
  // manage setting this 'state' property where you need to change the behavior...
  if (this._stateA) {
    // do state A...
  }  else {
    // do other state...
  }
}
```

Second, you can use `listen` and `unlisten` which are minimal sugar around `add/removeEventListener`.  Here's an example:

http://jsbin.com/megenazuha/1/edit?html,output
