### ISSUE TITLE
Event target with Shadow DOM

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#2200]
I'm using Shadow DOM and such piece of code:
```html
<template is="dom-repeat" items="[[list]]">
	<cs-music-playlist-item data-index$="[[index]]" on-tap="play">
		<template is="dom-if" if="[[item.playing]]">
			<i class$="[[icon_class(item.icon)]]"></i>
		</template>
		<span>[[item.artist_title]]</span>
	</cs-music-playlist-item>
</template>
```
Now I'm clicking on `span`.

`play` handler gets element's root as `event.target` and `span` as `event.originalTarget`, but I've attached event to another element.

The question is why is it so? There should be an easier way of getting `cs-music-playlist-item` than iterating `even.path`.
There was `sender` argument in Polymer 0.5, but I do not see anything like this anymore.

Source code and complete example here: https://github.com/nazar-pc/CleverStyle-Music/blob/polymer-1.0/html/cs-music-playlist/index.html

**Comment by kevinpschaaf** [comment]
@azakus PTAL

**Comment by azakus** [comment]
`event.currentTarget` is the property you want to be reading, as it is the node currently handling the event. [MDN Article](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget)

**Comment by nazar-pc** [comment]
Thanks, don't know how I missed that
