### ISSUE TITLE
this.splice() doesn't work as expected, requires notifyPath call

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#2203]
HTML
```html
<template is="dom-repeat" items="[[list]]">
	<cs-music-playlist-item data-index$="[[index]]" on-tap="play" playing$="[[item.playing]]">
		<template is="dom-if" if="[[item.playing]]">
			<i class$="[[icon_class(item.icon)]]" data-index$="[[index]]"></i>
		</template>
		<span data-index$="[[index]]">[[item.artist_title]]</span>
	</cs-music-playlist-item>
</template>
```
CoffeeScript
```coffeescript
update_status	: (new_id) ->
	@list.forEach (data, index) =>
		if (
			data.id == new_id ||
			(
				data.playing && !new_id
			)
		)
			data.playing	= true
			data.icon		= if cs.bus.state.player == 'playing' then 'play' else 'pause'
			@splice('list', index, 1, data)
		else if data.playing
			data.playing	= false
			delete data.icon
			@splice('list', index, 1, data)
icon_class		: (icon) ->
	"fa fa-#{icon}"
```
Looks like this should be enough, but indeed it is not, icon is updated only for element, that had icon during initial rendering, other icons never appear in DOM, also `playing` property never appear on other elements as well.
However, manual notification for all sub-properties finally works:
```coffeescript
update_status	: (new_id) ->
	@list.forEach (data, index) =>
		if (
			data.id == new_id ||
			(
				data.playing && !new_id
			)
		)
			data.playing	= true
			data.icon		= if cs.bus.state.player == 'playing' then 'play' else 'pause'
			@notifyPath('list.' + index + '.playing', data.playing)
			@notifyPath('list.' + index + '.icon', data.icon)
		else if data.playing
			data.playing	= false
			delete data.icon
			@notifyPath('list.' + index + '.playing', data.playing)
			@notifyPath('list.' + index + '.icon', data.icon)
icon_class		: (icon) ->
	"fa fa-#{icon}"
```

`@notifyPath('list.' + index)` also is not enough, only explicit notification of every property helps.
I'm using Shadow DOM if it is relevant here.
Source code here: https://github.com/nazar-pc/CleverStyle-Music/tree/polymer-1.0/html/cs-music-playlist

To be honest, Polymer 1.0 is barely usable with multitude of such tricks I've encountered while migrating relatively simple app from Polymer 0.5 where there was not only a bit more magic, but everything worked as expected, I have no idea how it is called stable...

**Comment by kevinpschaaf** [comment]
In Polymer 1.0, you can assign data directly to _element properties_, but performing assignments to _object sub-properties_ outside of Polymer's purview require using Polymer's `set` API for the changes to be observable (set performs both the assignment and the notification).  This is indeed an ergonomic concession for the very real benefit of a simpler, synchronous system that does not rely on polling polyfills.

In your code above, you can simply write:

```js
if (data.id == new_id || (data.playing && !new_id)) {
  this.set(['list', index, 'playing'], true);
  this.set(['list', index, 'icon'], cs.bus.state.player == 'playing' ? 'play' : 'pause');
} else if (data.playing) {
  this.set(['list', index, 'playing'], false);
  this.set(['list', index, 'icon'], null)
}
```

**Comment by nazar-pc** [comment]
But what if modifications come from outside?
There should be a way to notify path change recursively deeper into structure, while currently it works only on targeting path.
Also `splice()` is in your API for a reason, but it doesn't cause changes in rendered list on modification. I've removed one item and inserted another, yes this is the same item, but anyway after such explicit modification it should walk through all sub-properties and check whether they change.
