### ISSUE TITLE
polymer break point

### ISSUE THREAD

**Issue by justinww001** [Polymer/polymer#2213]
After working on a project for about a month, I have found something that is beginning to trouble me. Whenever I place www in the url, it breaks the polymer elements and background colors disappear. If the www is left out, everything acts perfectly normal. Is there a reason for this?

**Comment by kevinpschaaf** [comment]
Can you provide a link to your app or a way for us to reproduce your issue?  I can't think of anything that would cause that off the top of my head.

**Comment by justinww001** [comment]
Sure, here is the project I have been working on:

With www: http://www.velma.com/content/velma_credittips

Without www: http://velma.com/content/velma_credittips

**Comment by Foorack** [comment]
My Chrome reported this: 
> "Imported resource from origin 'http://velma.com' has been blocked from loading by Cross-Origin
> Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested
> resource. Origin 'http://www.velma.com' is therefore not allowed access."

Basically the most common browsers block access when www.velma.com try and import resources from velma.com. They are two different domains and allowing this would be cross-site-scripting. In your code I can see that you have hard-coded the website such as:

``` <!--Polymer-->
    <script src="http://velma.com/content/polymer/webcomponentsjs/webcomponents-lite.min.js"></script>
    <script src="http://velma.com/content/polymer/polymer/polymer.html"></script>
    <link rel="import" href="http://velma.com/content/polymer/all-imports.html">
```

Try change all your links to:

``` <!--Polymer-->
    <script src="../polymer/webcomponentsjs/webcomponents-lite.min.js"></script>
    <script src="../polymer/polymer/polymer.html"></script>
    <link rel="import" href="../polymer/all-imports.html">
```

I would not say this is a bug in Polymer. :-)

**Comment by justinww001** [comment]
Thank you for the help! I have been wondering what was causing this issue.

**Comment by sorvell** [comment]
Closing since this was sorted out.
