### ISSUE TITLE
Warn on camelCase mistakes?

### ISSUE THREAD

**Issue by danmane** [Polymer/polymer#2215]
It's easy to make mistakes with the camelCase -> camel-case conversion where one writes camelCase as a property and then tries to assign it in html without turning it into a dashed name.

Would it be possible to detect when the developer has done this, and then print a warning to console? Eg if we detect property "camelcase" is assigned on an element, and there is no "camelcase" property but there is "camel-case", then print a warning to console saying the developer probably messed up.

**Comment by lucasfanning** [comment]
it is easy, we can:
   use it: http://gabceb.github.io/underscore.string.site/ ,    _.camelize( or _.dasherize_ ... function
any problem , see the implementation;
just need to know the code part to change.

**Comment by kevinpschaaf** [comment]
We are in the process of developing a linter tool that will catch as many common developer errors as possible, and this is definitely something on the radar for that.

**Comment by Jamtis** [comment]
Why are the properties in the doc still camelCase?

Is the conversion to camel-case on the to-do list or is there any particular reason that the doc use camelCase?

**Comment by ebidel** [comment]
Our style is camelcased JS properties. That's why they show up that way in the doc. Any time you use a property as an attribute, you need to use dash "-" case. See https://www.polymer-project.org/1.0/docs/devguide/properties.html#attribute-deserialization.

**Comment by Jamtis** [comment]
@ebidel Thanks for the clarification.

**Comment by azakus** [comment]
Closing due to age, please reopen if this is still an issue.
