### ISSUE TITLE
Tooltip demo returns 404 error

### ISSUE THREAD

**Issue by mschwart** [Polymer/polymer#2216]
Steps:
1. Go to https://www.polymer-project.org/0.5/docs/elements/core-tooltip.html
2. Click on Demo button

Expected: show demo screen
Result:
```
Error: Not Found

The requested URL /0.5/components/core-tooltip/demo.html was not found on this server.
```

**Comment by tjsavage** [comment]
This issue was moved to Polymer/docs#1294
