### ISSUE TITLE
Ripple effect not showing on tablet+ layout

### ISSUE THREAD

**Issue by summers173** [Polymer/polymer#2217]
You can reproduce this in the start page of polymer-starter-kit-light-1.0.3

The ripple effect on any paper-icon-button is not showing well, or disappears pretty quickly if the layout of the page is in "bigger mode", it only works well i the layout is small (phones), if you expand the browser window thus changing the layout to a bigger mode the ripple effect don't show well.

It´s is strange but actually in Internet Explorer behaves ok.

Regards

**Comment by tjsavage** [comment]
This issue was moved to PolymerElements/paper-icon-button#31
