### ISSUE TITLE
paper-item 1.0.2 docs reference paper-item-body (which does not exist)

### ISSUE THREAD

**Issue by mkpartnersDev1** [Polymer/polymer#2219]
As far as I can tell, paper-item-body does not (or no longer) exist.  Unfortunately, the docs for paper-item, makes it look like it does: https://elements.polymer-project.org/elements/paper-item

**Comment by tjsavage** [comment]
`paper-item-body` is a part of `paper-item`:

https://github.com/PolymerElements/paper-item/blob/master/paper-item-body.html
