### ISSUE TITLE
Allow creating <polymer-element>s without Shadow DOM

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#222]
I recently had some [back and forth with Bruch Lawson](https://twitter.com/brucel/status/360791389350543361) on the overuse of wrapping everything in and element hidden by Shadow DOM. We need to do a better job of telling people to use Shadow DOM where it makes sense.

To that end, Polymer auto-creates Shadow DOM from the first `<template>` if find.
We should allow users to create `<polymer-element>`s that don't create Shadow DOM.

If there's a way to already do this, let me know so we can get it documented.

**Comment by graphicbeacon** [comment]
@arthurevans Thanks for this information. Was what I was looking for :+1:

**Comment by antitoxic** [comment]
@arthurevans,  @sjmiles, @sorvell does any of you have even the vaguest idea for 0.8 release month? 

I know Polymer is in dev preview, but it is, by all indicators (w3c web components, ease of use, data-binding, html imports...), the library that will shape the web. I can't find anything that is nearly usable as Polymer. I desperately want to use it. 

Few things stop me. One big thing is the low shadow-dom proliferation and webcomponents.js edge cases (firefox bugs I ran into, selector bugs, drag and drop things.. etc).

If the date on which polymer starts supporting lightdom (aka no shadowdom) is relatively known I can arrange future projects around it.

**Comment by addyosmani** [comment]
@antitoxic See https://github.com/Polymer/polymer/blob/0.8-preview/PRIMER.md for our current thinking around 0.8. It's a moving target, however if you read through you'll discover the team have been exploring an alternative to native ShadowDOM for unsupported browsers. In those targets, Polymer provides local DOM using an SD-like thing called ShadyDOM. Hopefully this will alleviate some of the concerns around native SD proliferation. FF are also working on a native implementation of it. 

With respect to webcomponents.js and bugs, we're working on better continuous integration for our tests and hope to improve the stability of the polyfills for edge-cases. If there's anything specific that catches you out, please feel free to file a bug and we'll take a look at it.

**Comment by antitoxic** [comment]
Thank you @addyosmani . I had a read. It's tasty. It doesn't hint about dates but I guess that's how things are. 

Is the "shady" :smiley: DOM expected before 0.8?

In the meantime I'm [exploring options in SO](http://stackoverflow.com/questions/28370178/stable-webcomponent-like-templating-engine-with-data-binding?noredirect=1#comment45083706_28370178) but it's seem it's an offtopic there.

It seems that I have spend some time thinking about anguarjs directives way to go about it.

**Comment by arthurevans** [comment]
Nope. Shady DOM (working title) and the local DOM abstraction are 0.8 features.

**Comment by antitoxic** [comment]
@arthurevans thank you.

**Comment by fernandopasik** [comment]
@arthurevans is there a way to create custom elements without shadow DOM in the current polymer 1.0 ?

**Comment by arthurevans** [comment]
Yes. If your element doesn't have a local DOM template, it won't have a
local DOM tree (shady/shadow DOM).

**Comment by fernandopasik** [comment]
How would this change in order to do that?
```
<dom-module id="x-foo">
  <template>I am x-foo!</template>
  <script>
    Polymer({
      is: 'x-foo'
    });
  </script>
</dom-module>
```

**Comment by ebidel** [comment]
Remove the dom-module and just keep your script tag.

**Comment by fernandopasik** [comment]
When I do that I don't have any html in the element. What I thought it would do is the template is appended.

```
<template>I am x-foo!</template>
  <script>
    Polymer({
      is: 'x-foo'
    });
  </script>
```

**Comment by fernandopasik** [comment]
@ebidel what I'm trying to achieve is doing this with polymer:

```
<template>
  This one <b>doesn't have shadow dom</b> and <i>without Polymer</i>.
</template>
<script>
  var thisDocument = document.currentScript.ownerDocument;
  var proto = Object.create(HTMLElement.prototype, {
    createdCallback: {
      value: function() {
        var t = thisDocument.querySelector('template');
        var clone = document.importNode(t.content, true);
        this.appendChild(clone);
      }
    }
  });
  document.registerElement('without-polymer', {prototype: proto});
</script>
```

**Comment by ebidel** [comment]
I see. We don't have easy mechanics for stamping templates outside of
Polymer. Closest is dom-bind.

**Comment by fernandopasik** [comment]
ok thanks for your help!

**Comment by Roxy94** [comment]
Is it possible to create a Polymer element in the light DOM using Polymer 2 ?

**Comment by mrdevin** [comment]
👍

**Comment by mindthetic** [comment]
Currently there is no way to achieve the same as the below from within a custom element without using the `!important` flag.

```html
<style>
    h1 {
        color: green;
    }
    custom-element h1 {
        color: red;
    }
</style>
```

This is probably my biggest stumbling block with using Polymer at the moment. 😢
