### ISSUE TITLE
handler function for  events for a dynamicaly added element using polymer dom 

### ISSUE THREAD

**Issue by mukuljp** [Polymer/polymer#2222]
inputel.addEventListener("click", this.handleInput);

I have defined handleInput in the polymer scope.

 handleInput: function () {
                    console.log(this.properties);
}

cannot access other defined properties or variables , only the clicked input element is getting in this function

**Comment by timeu** [comment]
You need to bind `this`:

`inputel.addEventListener("click", this.handleInput.bind(this));`

**Comment by mukuljp** [comment]
That worked thank you
