### ISSUE TITLE
Polymer 1.0 and 0.5 docs easily confused

### ISSUE THREAD

**Issue by danmane** [Polymer/polymer#2226]
I frequently find myself confusing the 0.5 docs for the 1.0 docs because the styling on the site is identical. Could you change the color on the 0.5 docs header, or put a warning banner of some kind, so I can immediately tell when I'm reading outdated docs?

**Comment by dandv** [comment]
:+1: Also, the 1.0 or even 0.5 docs keep showing up in the first Google search results page. This is a big problem when it comes to the "new" (though it's unclear how) Paper Elements demo - see https://github.com/PolymerElements/paper-checkbox/issues/58

Googling "paper elements demo" produces https://www.polymer-project.org/1.0/components/paper-elements/demo.html#paper-checkbox, but the correct demo is https://elements.polymer-project.org/browse?package=paper-elements

Some deprecation notices would be great.

**Comment by ebidel** [comment]
@dandv filed for https://github.com/Polymer/polymer/issues/2392. Everything under https://www.polymer-project.org/1.0/components/ is actually 0.5 components/demos. It's no bueno

**Comment by arthurevans** [comment]
This issue was moved to Polymer/docs#1333
