### ISSUE TITLE
Document new style recommendations

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#2229]
As a result of #1876, we're changing our recommendation for how styles should be loaded and shared (will be merged via #2198).

* `<link rel="import" type="css">` will be *deprecated*. This syntax allowed users to use a pure .css file, but the file is parsed as HTML which is a security and performance concern.
* Instead, `<dom-module>` is the recommended way to share style data. Styles should be defined in a `<template>` inside a `<dom-module>` so they are not parsed by the browser, and the `<dom-module>` should be placed in an HTMLImport that's used where needed. We'll be providing a tool to help turn .css files into this format. Here's an example of the syntax:

  ```html
  <!-- shared-styles.html -->
  <dom-module id="shared-styles">
    <template>
      <style>
        .red { color: red; }
      </style> 
    </template>
  </dom-module>
```

* Style data contained in `<dom-module>`'s can be 'included' in element styles or `custom-style` elements using the `include` attribute. For example,

  ```html
  <!-- using shared styles in an element -->
  <link rel="import" href="../shared-styles/shared-styles.html">
  <dom-module id="x-foo">
    <template>
      <style include="shared-styles"></style>
      <style>:host { display: block; }</style>
      Hi
    </template>
    <script>Polymer({is: 'x-foo'});</script>
  </dom-module>

  <!-- or -->
  <!-- using shared styles in a custom-style -->
  <link rel="import" href="../shared-styles/shared-styles.html">
  <style is="custom-style" include="shared-styles"></style>
  ```
 * Previously we recommended that `<style>`s be placed inside an element's `<dom-module>` but outside the template. This is still supported but it is slower than placing the styles in the template so it's no longer recommended.

**Comment by mfrost66** [comment]
This effectively prevents use of CSS processors (sass/stylus) and hides css inside of .html files.  A tool (or vulcanize support) that automatically imported/converted the .css files would possible allow the best of both worlds.

**Comment by sorvell** [comment]
Vulcanize actually does optionally convert link elements as needed.

We also plan to create a simple tool to convert a `*.css` file into an HTMLImport containing a `dom-module` to support this type of use case.

**Comment by mfrost66** [comment]
vulcanize supports inlining css via the now deprecated <link type=css> tag.  Can we count on long-term support for the --inline-css or do you see this being removed as that feature is now deprecated? 

If possible, I'd love to see first-class support for keeping styles in .css files with as little hoop-jumping as possible. Keeping and/or enhancing(add support for dom-module via attribute) the existing vulcanize css-inline would work great for us - although I realize it doesn't help those who don't vulcanize.

**Comment by nazar-pc** [comment]
Why do we need one more tool just to import style? This seems to be an overkill from any point of view.
There should be always possibility to imprort arbitraty CSS file directly.

**Comment by arthurevans** [comment]
Closing issue as documented:

https://www.polymer-project.org/1.0/docs/release-notes.html#release-110httpsgithubcompolymerpolymertreev110-2015-08-13
https://www.polymer-project.org/1.0/docs/devguide/styling.html#style-modules

**Comment by sankethkatta** [comment]
Was this "tool" to convert .css files ever created? If so anyone have a link?

**Comment by jonmann20** [comment]
@sankethkatta I wrote a gulp task to do this using modifyFile and rename.

```
		gulp.task('cssToPolymerStyleModules', () => {
			return gulp.src('/out/*.css').
				pipe(modifyFile((content, path, file) => {
					const start = `<dom-module id="${file.stem}-styles"><template><style>`;
					const end = '</style></template></dom-module>';

					return `${start}${content}${end}`;
				})).
				pipe(rename({
					suffix: '-styles',
					extname: '.html'
				})).
				pipe(gulp.dest('out'));
		});
```
