### ISSUE TITLE
Memory not getting released on page reload in Safari

### ISSUE THREAD

**Issue by Compufreak345** [Polymer/polymer#2231]
I am not quite sure if this is an Safari or an Polymer issue, but it's worth finding out.

The issue can be reproduced by visiting https://polymer-project.org with some smaller numbers than in my case, but it's there.

Numbers from my application : On the first page load the memory footprint is OK (~130MB). But every time I refresh the page, the RAM usage gets increased by something between 40 and 100MB. I don't need the page to remember anything when the user leaves it, so I don't understand what is happening there. And it's not just like memory that gets released when needed, it leads to the point where my MacBook (8GB RAM) is starting to get really slow after developing for about 30 minutes... I do not have any plugins installed.

A more detailed description and some screenshots of the RAM usage are available at http://stackoverflow.com/questions/31891543/polymer-safari-huge-ram-usage-increase-on-each-page-reload . 

P.S.: I read about general Safari RAM issues, but the posts about this are mostly 3 years old.

**Comment by sorvell** [comment]
We haven't seen issues like this. Would you be able to provide a test case that we can investigate? Thanks.

**Comment by Compufreak345** [comment]
Hm I think it's a problem with my system, sorry to have bothered you. I can see the same behavior for every page I visit, it was just the first that went overboard because I refreshed it so often...
