### ISSUE TITLE
Pseudo selectors in dom-repeat

### ISSUE THREAD

**Issue by bjarosze** [Polymer/polymer#2232]
Hi,

I am trying to decorate each element in my component, e.g.:

```
<my-elem>
  <a href="#">first</a>
  <a href="#">second</a>
</my-elem>
```

should generate:
```
<my-elem>
  <ul>
    <li><a href="#">first</a></li>
    <li><a href="#">second</a></li>
  </ul>
</my-elem>
```

What I try to do is to use ```<content>``` tag with ```:nth-child``` selected in dom-repeat, but it seems that pseudo selectors don't work in dom-repeat.

Here is simplified example:

Definition of my-elem:
```
<dom-module id="my-elem">
  <template>
    <content select="a:nth-child(1)"></content>
  </template>

  <script>
    Polymer({
      is: "my-elem",
    });
  </script>
</dom-module>
```

Example above works (only first element is rendered), but if I put content into dom-repeat, like example below, it stops to work (none of elements are rendered):
```
<dom-module id="my-elem">
  <template>
    <template is="dom-repeat" items="{{items}}">
      <content select="a:nth-child(1)"></content>
    </template>
  </template>

  <script>
    Polymer({
      is: "my-elem",
      ready: function () {
        this.items = [1, 2];
      }
    });
  </script>
</dom-module>
```

Why pseudo selectors don't work in dom-repeat?

**Comment by kevinpschaaf** [comment]
The Shadow DOM spec does not support positional selectors for the `<content>` `select` attribute.  It only supports a limited subset of simple selectors: http://www.w3.org/TR/shadow-dom/#satisfying-matching-criteria
