### ISSUE TITLE
Not possible to use expression inside attribute

### ISSUE THREAD

**Issue by eximius313** [Polymer/polymer#2234]
I'm iterating through some elements:
```
<template is="dom-repeat" items="{{json}}">
<a href="{{item.url}}"><div class="image" style="background-image: url('{{item.logoUrl}}')"></div></a>
</template>
```
while ```href="{{item.url}}"``` works, the ```style="background-image: url('{{item.logoUrl}}')"``` don't

Could you please allow using expressions inside attibutes?

**Comment by timeu** [comment]
This is currently not supported as mentioned in the [docs](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#binding-to-text-content). 

There is an open [ticket](https://github.com/Polymer/polymer/issues/2182) for supporting interpolation.

In the meantime you need to data-bind the entire `style` content: `style="{{_computeStyle(item.LogoUrl)}}"`.

**Comment by eximius313** [comment]
Thanks for the hint. I will follow the ticket which you have provided.

**Comment by kevinpschaaf** [comment]
Closing as noted.
