### ISSUE TITLE
Invalid childNodes on previous parent is returned after calling domApi.appendChild

### ISSUE THREAD

**Issue by eeid26** [Polymer/polymer#2235]
http://jsbin.com/litugehexu/edit?html,console,output

Also the following issue could be a different mutation of the reported issue. Both issue are due to caching the _lightChildren on the parent

After calling domApi(customElement).appendChild(domApi(customElement).nextSibling) and then flush, the nextSibling of the custom element is not reported correctly by domApi.

http://jsbin.com/hijoxawewa/edit?html,console,output

**Comment by sorvell** [comment]
Thanks for the detailed reproductions. Yes, both issues look like the same problem.

**Comment by eeid26** [comment]
Thank you. it's working now.
