### ISSUE TITLE
"dom-if" inside "dom-bind"

### ISSUE THREAD

**Issue by g-ortuno** [Polymer/polymer#2236]
Is such a thing supported? If so where are you supposed to change the attribute passed to the `if`?

```html
<template is="dom-bind" id="app">
  <template is="dom-if" if="{{supported}}">
    <div>Yay!</div>
  </template>
</template>

**Comment by timeu** [comment]
Yes put a script tag at the bottom of the page and add this: 
```html
<script>
     app = document.querySelector('#app');
     app.supported = true;
</script>
```

https://jsbin.com/xejoja/edit?html,output

**Comment by kevinpschaaf** [comment]
The binding scope for the template stamped by `dom-bind` is the `<template is="dom-bind">` element itself.  As @timeu noted the `{{supported}}` property in the template can be changed by modifying the `supported` property on the `dom-bind` itself.
