### ISSUE TITLE
No way of passing objects when creating an element with document.createElement()

### ISSUE THREAD

**Issue by nourikhalass** [Polymer/polymer#2238]
### Problem
There is no way to provide objects when constructing an element via 
````javascript
document.createElement('x-element')
````
Something of the form
````javascript
document.createElement('x-element')(valueA, valueB, valueC)
````
Would be nice. This would allow you to set properties when intializing an element.

#### Possible workaround's
A) Provide your own function to allow this behavior
*Not sure if it is a good practice to preform*
````javascript
// Creating the element
document.createElement('x-element').with(valueA, valueB, valueC)

// In your Polymer({}) of x-element
Polymer({
  
  properties: {
    propertyA: String,
    probertyB: Number,
    propertyC: Boolean
  }

  with: function(valueA, valueB, valueC){
    this.propertyA = valueA;
    this.propertyB = valueB;
    this.propertyC = valueC;
    return this;   
  }

});
````

B) Expose a constructor that allows passing objects when passing the element to Polymer({})
*This is mentioned in the (rather difficult to understand and unclear) [documentation](https://www.polymer-project.org/1.0/docs/devguide/registering-elements.html#register-element)*
````javascript
// register an element
MyElement = Polymer({

  is: 'my-element',

  // See below for lifecycle callbacks
  created: function() {
    this.textContent = 'My element!';
  }

  factoryImpl: function(valueA, valueB){
    // Do something with the arguments
  this.propertyA = valueA;
  this.propertyB = valueB;
});

// create an instance with createElement, you can not provide constructor arguments here:
var el1 = document.createElement('my-element');

// ... or with the constructor, you can pass in constructor arguments and the handling of them happens via factoryImpl():
var el2 = new MyElement(valueA, valueB);
 ````

**Comment by kevinpschaaf** [comment]
This is a fundamental limitation of the DOM API `createElement`.  Since it a.) doesn't allow custom arguments, and b.) returns an element instance, what you suggested would indeed be nice, but it's not possible.

As you noted, we have first-class support for constructors with arguments (by providing a `factoryImpl` method on the prototype), and this is our recommended way of addressing this.  Your `with` pattern is also perfectly fine.

**Comment by nourikhalass** [comment]
Thanks for clearing things up. Good to know that the ````with```` pattern is fine to use.
