### ISSUE TITLE
⚠️ Warn users against gotchas when using object literal property

### ISSUE THREAD

**Issue by samccone** [Polymer/polymer#2240]
This bit me today :calendar: , and I think a :warning: warning or :rotating_light: helpful message in the console ala react would help a bunch. :bow: 
#### :goat: Example

``` js
Polymer({
  is: 'goat-eater',
  properties: {
    goats: {
      type: Object,
      value: {
        heads: 1
      }
    }
  },
  attached: function() {
    this.goats.heads++;
    console.log('i have eaten ' + this.goats.heads + ' goat heads');
  } 
});
```

``` html
<goat-eater></goat-eater>
<goat-eater></goat-eater>
<goat-eater></goat-eater>
```

Then in the console I see

```
> i have eaten 1 goat heads
> i have eaten 2 goat heads
> i have eaten 3 goat heads
```

**wat** 

This was pretty darn confusing, until I was like oh yes prototypically inheritance :lollipop: 

``` diff
Polymer({
  is: 'goat-eater',
  properties: {
    goats: {
      type: Object,
-      value: {
+      value: function() {
+       return {
          heads: 1
        }
+     }        
+    }
  }
```

---
### TLDR;

I am willing to bet quite a few people have gotten caught up on using object literal props, it also seems like something that could be `console.warned` against quite easily, given the fact that we have `type` to look at.

Thoughts? Terrible Idea? Let me know :microphone: 

Thanks for your :watch: Time :sparkles:

**Comment by addyosmani** [comment]
Afaik We've documented this but agree a warning could be valuable. We've discussed improving warnings/tips around gotchas in the console some time ago but this is definitely an area that could use some more work.

**Comment by samccone** [comment]
:book: https://www.polymer-project.org/1.0/docs/devguide/properties.html#configure-values

This raises a great question, do we want people to ever "use" this feature? Are there legitimate use cases?

**Comment by sorvell** [comment]
@garlicnation This is probably a good candidate for the linter tool.

**Comment by brettpostin** [comment]
+1 for some form of warning/linting. It's very easy to get caught out by this, especially in a componentised world where this is not the obvious behaviour.

**Comment by TimvdLippe** [comment]
This issue was moved to Polymer/polymer-linter#172
