### ISSUE TITLE
Templates don't support computed bindings

### ISSUE THREAD

**Issue by Jamtis** [Polymer/polymer#2241]
@eximius313 came up with [an example](https://jsbin.com/namoxiketi/1/edit?html,css,console,output) where computed bindings don't work.

The `compute method '_computeClass' not defined"` error occurs because the property is evaluated before the method is defined...

A possible solution could be to "remember" the missing method on first evaluation and observe that property.
So when the method gets defined the attribute value can be properly re-evaluated.

**Comment by sorvell** [comment]
I can confirm this issue, but I'm not sure this exact use case is worth supporting.

This issue should not be hit with bindings inside an element. Using a `dom-bind` element, the script should be placed outside the binding template. Here's a working example: 

https://jsbin.com/coseyonuhu/1/edit?html,css,console,output

Is there a specific reason that placing the script inside the template is necessary?

**Comment by Jamtis** [comment]
I don't see one at the moment.
Maybe @eximius313 can provide a use case.

**Comment by eximius313** [comment]
Maybe no, but then documentation should inform that it is forbidden, perhaps?

**Comment by Jamtis** [comment]
I suggest dropping this.
Though I agree with @eximius313 to state that out explicitly in the docs.
