### ISSUE TITLE
🎷 provide a computed helper for JSON.stringify

### ISSUE THREAD

**Issue by samccone** [Polymer/polymer#2244]
### What:question:

As a user of polymer, and in general a web app developer, when consuming a new API I would like to quickly throw some code onto the page to print a deserialized object on the screen.

Currently `{{foo}}` results _as expected_ in `Object object` which is... somewhat useless when rapid prototyping.

---
##### Take for instance

``` html
    <ul>
      <template is="dom-repeat" items="{{tracks.weeklyalbumchart.album}}">
        <li>
          <p>{{item}}</p>
        </li>
      </template>
    </ul>
```

**results in the fun ol**

![screen shot 2015-08-10 at 10 08 31 pm](https://cloud.githubusercontent.com/assets/883126/9188643/5cb566f0-3fac-11e5-81b3-47940268bca0.png)

It would be so swell to see something like :shell: 
![screen shot 2015-08-10 at 10 09 09 pm](https://cloud.githubusercontent.com/assets/883126/9188651/734c7dea-3fac-11e5-9358-6b426f60ac54.png)
### Why

As a JS developer, I am used to being able to throw something like

```
{{JSON.stringify(item)}}
```

into my page to get a quick look at the object and then to work forward from there. 

Now this can be done with a total hack :hocho: job :construction_worker: 

![screen shot 2015-08-10 at 10 11 12 pm](https://cloud.githubusercontent.com/assets/883126/9188680/c9225ff0-3fac-11e5-87ae-602ceb3c56df.png)

But this seems like a more work than it should take. Now I totally understand that this is helper for developing, more than anything else, however I think that the use case is common enough to developers that this would be super swell and dandy :lollipop: 

Thoughts? Terrible Idea? Scope bleed? :dog: 

Thanks!

**Comment by LusciousPear** [comment]
+1, I'd certainly use it.

**Comment by arthurevans** [comment]
A more general way to do this would be to define a helper method:

    <p>{{stringify(item, item.*)}}</p>

... 

    stringify: function(obj) {
      return JSON.stringify(obj);
    }

The `item.*` is probably overkill, but it makes sure stringify is called when a sub-property of `item` changes.

You could also throw this method into a behavior that you could use in any element you're creating.

**Comment by samccone** [comment]
yep totally @arthurevans ended up using that exact approach... 

nevertheless I think I might make the argument that this is super common use case and might make sense in core?

**Comment by sorvell** [comment]
We're considering adding a set of helper methods specifically to aid in common computed bindings cases. We'll put this suggestion in that bucket, thanks.

**Comment by TimvdLippe** [comment]
So this is possible with setting the property `JSON.stringify` on the element: http://jsbin.com/nimiyem/edit?html,console,output In Polymer 2 you can extract this assignment to a base class if you want, or add the one-liner. Given that this is a niche-feature primary for development and the one-liner solution exists, we would like to keep our API slim and not include this in core.
