### ISSUE TITLE
Allow manipulation of element constructor at registration time

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#225]
Users have requested the ability to manipulate an element's constructor at registration time.

We could add support for this by adding a callback to the Polymer registration method, something like:

  Polymer('x-foo', {
    stuff: 'things'
  }, function(ctor) {
    // do stuff with ctor
  });

Note that since the constructor is generated via document.register and register upgrades synchronously, it's not guaranteed that elements will be upgraded after this callback runs. (see http://jsbin.com/olasep/1/edit. This requires document.register which is available in chrome canary with experimental web platform features on).

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) release of Polymer - please feel free to re-open if this is incorrect.
