### ISSUE TITLE
Setting data-bound property in created event results in error "Cannot read property 'propName' of undefined"

### ISSUE THREAD

**Issue by govis** [Polymer/polymer#2250]
If you try use created phase to assign value to a property that has been bound to in component's template you will get an error <code>Uncaught TypeError: Cannot read property 'test' of undefined</code>

<pre><code>
&lt;template>
    &lt;span>[[test]]&lt;/span>
&lt;/template>

created: function () {
    this.test = 'abc';
}
</code></pre>

Error is thrown from <code>var old = this.\__data\__[property];</code> line in <code>_propertySetter</code>

Thanks

**Comment by timeu** [comment]
You can't access properties or data-binding features in the `created` callback (they haven't been setup at that point yet). AFAIK you have to do it in the `ready` callback.   
But if just want to define a default value than do it directly inside the `properties` definition: 

```
properties: {
  test: {
     type: String,
     value: 'abc'
  }
}
```

**Comment by govis** [comment]
Thanks for response. In my case the property value is an object that requires a reference to the element itself, so I do it in code.

In case of component composition parent's ready seems to be firing after it's children and sometimes it's too late to initialize some state-related properties needed to establish relationship between parent and it's children.

Interestingly enough, if a property is not data-bound one can initialize it in created without any problems. Also, <code>get Property1() { return ...; }</code> declared directly on the component seems to get ovewritten with an <code>undefined</code> value if there's a binding to it in the component's template.

**Comment by sorvell** [comment]
What @timeu said is correct. Property values should be configured in the `properties` object. As @govis notes, you can use a function to define an instance object.

If communication with an element's parent is required, this cannot be done sooner than the `attached` method. It's only after the element is `attached` that it's guaranteed to have a parent.
