### ISSUE TITLE
{{text::input}} does not react to input.val( newText ) and input.trigger("input")

### ISSUE THREAD

**Issue by deni35** [Polymer/polymer#2252]
I have a html:

    <input id="my-input" type="text" value={{text::input}} />
    <div>[[text]]</div>

And I have a JQuery code:

    input.val( newText );
    input.trigger("input");

But this code doesn't update data binding model. That is `<div>[[text]]</div>` is not updated.
May be it's a bug, may be this code is wrong, but I spent a few days and I can't get it to work.

**Comment by sorvell** [comment]
The `input` event of the `<input>` element fires in response to keyboard input, not setting the value property (which `.val(newText)` does). The [.trigger](http://api.jquery.com/trigger/) method only calls listeners added via jquery. The input element fires no event when the value property is set directly. Instead, I recommend setting the element's `text` property directly in this case.

Alternatively, if you need an input element with better support for 2-way data binding, you can use [iron-input](https://github.com/PolymerElements/iron-input)'s `bindValue` property.
