### ISSUE TITLE
injectBoundHTML disappeared?

### ISSUE THREAD

**Issue by apowers313** [Polymer/polymer#2254]
The [Migration Guide](https://www.polymer-project.org/1.0/docs/migration.html) and [Release Notes](https://www.polymer-project.org/1.0/docs/release-notes.html) for Polymer 1.0 don't mention that injectBoundHTML was removed but... it doesn't seem to exist in Polymer anymore.

Is that an oversight in the documentation?

**Comment by ebidel** [comment]
This issue was moved to Polymer/docs#1297
