### ISSUE TITLE
this.set('x', array) is not equivalent to this.splice('x', 0, this[x].length, ...array)

### ISSUE THREAD

**Issue by Parakleta** [Polymer/polymer#2256]
I have found that if I just `set` a new array over an old array it seems that Polymer is reusing the existing elements which in the case that there are sub-properties missing in the new array the sub-properties from the old array are being preserved (since they are not overwritten by new values).

If I splice out all of the old array values and insert all of the new ones I get properly created fresh elements without the old sub-properties.

I don't know if this is the intended behaviour or not, obviously re-using elements is more efficient, but in my case led to incorrect behaviour which I wasn't expecting.

**Comment by sorvell** [comment]
Yes, it's the `dom-repeat` element in particular that re-uses existing dom when it can for efficiency. The best way to handle this is to not have holes in your properties like this. However, that said, we are planning to add an option to `dom-repeat` to be more careful about re-using elements.

**Comment by kriswillis** [comment]
This option would be useful; I've just stumbled across the same problem where I have a `dom-repeat` that contains some `dom-if` blocks for rendering items with different properties. I was getting left-over properties from the previous array of items in my new set.

**Comment by kriswillis** [comment]
Although using `splice` instead of `set` to "clear down" my array initially done the trick, it seems that implementing a sort on the `dom-repeat` undoes this effort and properties from objects previously in that position are appearing in newly sorted objects.

**Comment by TimvdLippe** [comment]
Since Polymer 2 databinding uses identity checks, this should now work properly: http://jsbin.com/namehulifu/edit?html,output Please let me know if I missed something in your original request by modifying my JSBin that shows the issue.
