### ISSUE TITLE
Strange issue with data binding when properties are in prototype

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#2257]
```html
<dom-module id="my-element">
    <template>   
      <span>{{x}}</span>
      <span>{{y}}</span>
    </template>
    <script>
      Polymer({
        is: 'my-element',
        x: 'x',
        y: '',
        ready: function () {
          this.y = 'y';
        }
      });
    </script>
</dom-module>
```
In this example only `y` will be rendered, `x` property of created element is `undefined` O_o.

**Comment by MarkDurbin104** [comment]
you need a properties: {} section around your properties
```Polymer({
         properties: {
          is: 'my-element',
          x: 'x',
          y: '',
        }
        ready: function () {
          this.y = 'y';
        }
      });
```

**Comment by MarkDurbin104** [comment]
Oh, they also need to be in the format:
```shared:{type:String},
route: {type: String, value:"home", notify: true},
drawerWidth: {type: String, value:"200px", notify: true},```

**Comment by nazar-pc** [comment]
I do not need, setting them in runtime is OK, moreover I don't need to put `is` there.
Yes, putting in `properties` works, but I do not want them to be in properties.
I found issue - prototype's value is loosing during accessors creation, I'm working on PR to fix that, few minutes.

**Comment by nazar-pc** [comment]
PR #2258

**Comment by nazar-pc** [comment]
Well, it will not work as I expected, at least in current Polymer architecture, but rewriting original prototype property with accessors was really incorrect.
Are there any plans to support bindings to properties that are not in `properties`, like it was in Polymer 0.5? Would be nice to have it as one-time bindings without any notification system and things like that, it might be even faster in some cases.

**Comment by sorvell** [comment]
The supported way to define default values for properties is via the value field for a property in the `properties` object. After review, we've decided not to support 2 ways to do this.
