### ISSUE TITLE
firebase-document documentation wrong

### ISSUE THREAD

**Issue by salah-saleh** [Polymer/polymer#2259]
https://elements.polymer-project.org/elements/firebase-element?active=firebase-document
missing the close markup /firebase-document

**Comment by arthurevans** [comment]
The issue's in the API doc comments here: https://github.com/GoogleWebComponents/firebase-element/blob/master/firebase-document.html.

**Comment by ebidel** [comment]
This issue was moved to GoogleWebComponents/firebase-element#50
