### ISSUE TITLE
same CSS custom variables with host/child causes infinite loop

### ISSUE THREAD

**Issue by m4b** [Polymer/polymer#2265]
### Problem

It looks like it's turtles all the way down if:
1. Both a parent and child element have the same CSS custom variable, say `--foo-var`;
2. The parent sets the child's `--foo-var` using its `--foo-var`.
3. The parent has the child-embedded.
4. The parent and child dom-modules are defined in separate documents.
### Example

Place this dom-module in `infinite-loop.html`:

``` html
<dom-module id="infinite-loop">
  <style>
    :host {
      --font-size: 16px;
    }

    child-el {
      --font-size: var(--font-size);
    }
  </style>
  <template>
    <div>I'm a CSS Custom var loop</div>
    <child-el></child-el>
  </template>
  <script>
    Polymer({
      is: 'infinite-loop',
      ready: function() {
        console.log('ready');
      }
    });
  </script>
</dom-module>
```

And place the child in `child-el.html`:

``` html
<dom-module id="child-el">
  <style>
    :host {
      --font-size: 16px;
    }
  </style>
  <template>
    <div>
      nom nom nom nom
    </div>
  </template>
  <script>
    Polymer({
      is: 'child-el'

    });
  </script>
</dom-module>
```

And then use the parent (`infinite-loop.html`) in the base index:

``` html
<html>
...
<infinite-loop></infinite-loop>
</html>
```

You should see something like:

```
Uncaught RangeError: Maximum call stack size exceededPolymer.StyleProperties.valueForProperty
@ 
polymer.html:2584Polymer.StyleProperties.valueForProperty.fn @ 
polymer.html:2591Polymer.StyleProperties.valueForProperty @ 
polymer.html:2594Polymer.StyleProperties.valueForProperty.fn @ 
polymer.html:2591Polymer.StyleProperties.valueForProperty @ 
polymer.html:2594Polymer.StyleProperties.valueForProperty.fn @
...
```

**Comment by m4b** [comment]
This excellent artist rendering describes the problem in more detail:
![turtles](http://images.tribe.net/tribe/upload/photo/bbe/14b/bbe14bdc-d48f-4ec7-a675-184caea3deb2)

**Comment by sorvell** [comment]
Thanks for the repro but the picture explains it best. We'll look into fixing this.

**Comment by m4b** [comment]
Sorry, I should have added the artist's rendition first; I'll know better next time.

**Comment by TimvdLippe** [comment]
The line that results in an infinite loop is [this](https://github.com/Polymer/polymer/blob/master/src/standard/x-styling.html#L176).

In this situation `scopeProps = { --font-size: "var(--font-size) }"` which denotes the child-element. Consequently, `props = { --font-size: "16px" }` with `scope = infinite-loop`. Then all fields of `scopeProps` are mixed into `props` which overwrites the field `--font-size`. Lastly, `reify` will try to look up the value for `--font-size` in the properties finding `var(--font-size)` and recursively looks up `--font-size` which results in the infinite loop.

Somehow there needs to be a distinction between parent scope and child scope where the child is only allowed to look up values in the parent scope. If I fix this issue by passing the `scopeProps` and look up the value there, obviously a lot of tests are failing. I don't have time right now to continue debugging, but hopefully this information is useful for someone else currently investigating this issue.

**Comment by azakus** [comment]
Same issue as https://github.com/webcomponents/shadycss/issues/136
