### ISSUE TITLE
No way to dynamically add to a CSS mixins without destroying other values

### ISSUE THREAD

**Issue by newfivefour** [Polymer/polymer#2268]
Say, in a generic custom element, in Polymer 1.0.9, you have a mixin like this:

```
.name {
    @apply(--some-theme);
}
```

And, outside the element, styling it, you have:

```
 <style is="custom-style">
            an-element {
                --some-theme: {
                    color: orange;
                    background-color: blue;
                };
            }
  </style>
```

If, in a click listener, for the element 'an-element', I try to modify the customStyle:

```
               var t = Polymer.dom(e).localTarget;
               t.customStyle['--some-theme'] = 'background-color:pink';
               t.updateStyles()
```

Then it will change the background color, but also remove the 'color: orange' style we specified.

Is there a way to only modify a single value in a CSS mixin, without obliterating the rest of the values in such?

Note: I can't see a way of grabbing the existing values for the CSS mixin to modify.

Full source:

``` html
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
            <script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
            <link rel="import" href="bower_components/polymer/polymer.html">
            <dom-module id="an-element">
                <style>
                    .name {
                        @apply(--some-theme);
                    }
                </style>
                <template>
                    <div class="name">some text here</span>
                </template>
            </dom-module>
            <script>
                Polymer({
                    is: "an-element"
                });
            </script>
            <style is="custom-style">
                an-element {
                    --some-theme: {
                        color: orange;
                        background-color: blue;
                    };
                }
            </style>
        </head>

        <body>
            <template id="app" is="dom-bind">
                <an-element on-tap="clicky">
                </an-element>
            </template>
        </body>

        <script>
           window.addEventListener('WebComponentsReady', function(e) { 
                var t = document.querySelector('#app');
                t.clicky= function(e) {
                   var t = Polymer.dom(e).localTarget;
                   t.customStyle['--some-theme'] = 'background-color:pink';
                   t.updateStyles();
                };
           });
        </script>
    </html>
```

**Comment by sorvell** [comment]
We're planning to add an api to query your computed style properties (currently available on the private `_styleProperties`) which should make this easier.

**Comment by ghstahl** [comment]
https://jsfiddle.net/ghstahl/6w8sajnt/3/

Hopefully this is related.  
What I want is the ability to swap out the entire paper-material mixins based upon a class change.
In my example, I compute a new class name based upon a toggle.  'is-hot', 'is-cold'.  You can see the class being swapped in and out.

I am barely a css idiot, so probably what I have done is not right css.
I tried styling that looked like this.

paper-button.is-hot{
 --shadow-elevation-2dp: {---}
}

from what I can tell, the paper-material styles only get updated when elevation changes.

So far the only success I have had to swap styles is doing what newfivefour did.

**Comment by beckula** [comment]
Sorvell how are things progressing with the API to obtain computed style properties?

**Comment by arthurevans** [comment]
Added in [Release 1.2.2](https://www.polymer-project.org/1.0/docs/release-notes.html#release-122httpsgithubcompolymerpolymertreev122-2015-11-12). 

See also: https://github.com/Polymer/polymer/issues/2690

**Comment by beckula** [comment]
Thanks!

**Comment by marco9446** [comment]
hi. I'm facing the same problem described in this issue and i'm still not able to change one style property without removing the others.
I have tried to use the getComputedStyle function but it returns a read only object and so i can't directly modify the value returned.
I think that i misunderstood the purpose of getComputedStyle(). 
Could you please explain how to achieve my goal

**Comment by AlexNasonov** [comment]
Need to modify mixin dynamically too. Is this problem solved?

**Comment by ggirard07** [comment]
Can't find anything in 2.0 to do this too. Right?

**Comment by azakus** [comment]
This is a known limitation of the `@apply` shim, as documented here: https://github.com/webcomponents/shadycss#status

The ApplyShim is provided for backwards compatibility for Polymer 1 and 2, and will only receive the most critical of bug fixes.

In this case, the effort required to allow for modifying mixins at runtime is prohibitively expensive, and will not be supported.
