### ISSUE TITLE
CSS Variable styling: using var(...) overrides a more specific selector

### ISSUE THREAD

**Issue by doliver-pulsemining** [Polymer/polymer#2272]
Setting Polymer elements CSS properties using CSS variables does not allow more specific CSS selectors to override the property unless they also are CSS variables.

The following code will result in all div elements being `--red-color` even when they have `class='green'`
```
<dom-module id='x-test'>
  <style>
    div {
      color: var(--red-color);
    }
    div.green {
      color: green;
    }
  </style>
  <template>
    <div class='green'>Green text is red</div>
  </template>
</dom-module>
```

Full example of issue: http://jsbin.com/xopovovema/edit?html,output

**Comment by sorvell** [comment]
This is a known issue and is something we plan to address soon. Closing this issue in favor of https://github.com/Polymer/polymer/issues/1873.
