### ISSUE TITLE
Polymer needs an html lint

### ISSUE THREAD

**Issue by gazal-k** [Polymer/polymer#2273]
Not sure whether [yaniswang/HTMLHint](https://github.com/yaniswang/HTMLHint) will address the quirks in polymer's HTML syntax. Here's the issue open against it: https://github.com/yaniswang/HTMLHint/issues/44

PS: Not sure whether the issue belongs here or should be raised against polymer starter kit.

**Comment by peduxe** [comment]
I think there's already a lint tool being created, although you can disable some rules on your project folder's `.htmlhintrc` file.

**Comment by gazal-k** [comment]
@peduxe is this lint tool being created on github? I tried searching, couldn't find any. Can you please share any relevant links?

**Comment by peduxe** [comment]
@gazal-k https://github.com/PolymerLabs try there, lots of experiments

**Comment by azakus** [comment]
We have a linter tool [polylint](https://github.com/polymerlabs/polylint) that should help with this issue.
