### ISSUE TITLE
Computed properties with the same names as methods

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#2274]
```coffeescript
Polymer(
...
	properties:
		pagination_options	:
			type		: String
			computed	: 'pagination_options(users_count, search_limit, search_page)'
...
	pagination_options		: (users_count, search_limit, search_page) ->
		# whatever
)
```
```haml
%dom-module(id="cs-system-admin-users-list")
	%ul.uk-pagination(on-click="page_click" data-uk-pagination$="[[pagination_options]]")
```
From binding syntax it should be clear and everything should work as expected, however I'm getting:
> [cs-system-admin-users-list::_computeEffect]: compute method `pagination_options` not defined

Firefox Nightly 43 & Chromium 44

I think it is quite natural case and should be supported. When method and property are different everything works fine.

**Comment by azakus** [comment]
Thanks for the suggestions, but we're opting not to do this because we think it will be more confusing than helpful.
