### ISSUE TITLE
Windows 10 / Edge / InternetExplorer

### ISSUE THREAD

**Issue by ARMistice** [Polymer/polymer#2275]
On Windows 10 with InternetExplorer / Edge

https://elements.polymer-project.org/elements/paper-button?view=demo:demo/index.ht

Changeing the frame size or clicking buttons make everything flicker.
Seems to be a problem with the "ripple" effects

![image](https://cloud.githubusercontent.com/assets/312925/9277826/dbf9214c-42ac-11e5-870b-cdb7ba24e69b.png)

**Comment by azakus** [comment]
This issue was moved to PolymerElements/paper-button#44
