### ISSUE TITLE
[1.1.0] dom-repeat template: elements not found via querySelectorAll

### ISSUE THREAD

**Issue by BigBen1307** [Polymer/polymer#2277]
Since version 1.1.0 i am unable to find elements inside a dom-repeat via `Polymer.dom(this.root).querySelectorAll('.sound-items paper-item')` that have been rendered from an array. The resulting nodelist is empty. Reverting back to version 1.0.9. fixed the problem. A demo with the bug will be provided soon.

**Comment by robrez** [comment]
Looks like a duplicate of https://github.com/Polymer/polymer/issues/2276

**Comment by BigBen1307** [comment]
yes indeed. it wasn't there when i started writing my issue :). i will post my demo with the bug there.

see #2276
