### ISSUE TITLE
notifyPath should propagate to subproperties

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#2279]
Initially issue was discovered in #2203, now another person encountered similar issue on Slack channel.

``` javascript
this.notifyPath('x', value)
```

Should notify all bindings to `x`, `x.y`, `x.y.z` and so on. Currently it notifies `x` only.
It is surprising that such propagation doesn't happen and this frustrates people.
There is no discussion about efficiency, if it makes sense - comparing previous and current subproperty values might be reasonable, but if I explicitly notify root - all subproperties should be notified as well.

As the last resort additional argument for `this.notifyPath()` might be added for this.
@kevinpschaaf

**Comment by samccone** [comment]
:+1: this is the issue that I reported in slack, totally was very confusing.

**Comment by azakus** [comment]
This should be considered with #2724 at the same time, as they are related concepts.

**Comment by TimvdLippe** [comment]
In Polymer 2 `notifyPath` will now trigger for object references as well as deep paths: http://jsbin.com/larejeduju/1/edit?html,console,output
