### ISSUE TITLE
Support negation of parameters sent to computed bindings

### ISSUE THREAD

**Issue by miztroh-zz** [Polymer/polymer#2281]
e.g. `<div hidden$="{{hideThis(foo, !bar)}}">Hello, world!</div>`

As it stands, attempting to negate a parameter causes the computed bindings to silently fail.

**Comment by nazar-pc** [comment]
Should be quite easy to implement, I'll try to take a look at this

**Comment by pkaske** [comment]
What are the pros of implementing that in the parser? Couldn't you just negate the parameter in your computed function?

**Comment by nazar-pc** [comment]
@pkaske, not always.
Imagine you have loop that generates pairs of blocks. Depending on sub-property you'll add some class to one of these two blocks. It is quite natural to use property directly in one case and negate it for another.
Sometimes this is just a matter of readability.

**Comment by pkaske** [comment]
@nazar-pc I don't see how your example of the loop wouldn't work without negation in the binding declaration, but I agree with your point regarding readability.

**Comment by nazar-pc** [comment]
@pkaske I meant you'd need to add class to either one element or another, so you'll use the same computed binding to property, but with negation for second block.

**Comment by pkaske** [comment]
@nazar-pc Ahhh, now I get it. Thanks for teaching me that :)

**Comment by miztroh** [comment]
Or, if you have a function that determines if multiple values are truthy that you want to use with inputs that may or may not be falsey, e.g. ``and(truthy, !falsey)``.

**Comment by nazar-pc** [comment]
@miztroh, well, my PR #2247 contains `xor` alongside with others if you need it)
