### ISSUE TITLE
[Chrome] 'Uncaught ReferenceError: window is not defined' after reload

### ISSUE THREAD

**Issue by exoer** [Polymer/polymer#2284]
I have created a clean polymer starter kit project using yeoman and the polymer generator.

In Chrome (not Chrome Canari or Safari) i can't access the window object or localStorage after the project is reloaded when it is served from the gulp development server. 

    Uncaught ReferenceError: window is not defined

![screen shot 2015-08-16 at 11 57 20](https://cloud.githubusercontent.com/assets/557371/9292840/131a7790-440e-11e5-8883-8f29b1e08415.png)

**Comment by tylercollier** [comment]
Right above where you typed in `window`, do you see the dropdown for the frame context? Make sure you are in the context you expect, e.g. "<top frame>".
