### ISSUE TITLE
Support for transitions in iron-pages

### ISSUE THREAD

**Issue by syeshchenko** [Polymer/polymer#2285]
Are there any plans to add support for page transitions to iron-pages, similar to what was done for core-animated-pages with transitions="slide-from-right" attribute?

**Comment by zerodevx** [comment]
It has already been implemented - `<neon-animated-pages>` under [neon-animation](https://github.com/PolymerElements/neon-animation). In any case, you should raise issues under the correct section - in this instance the [iron-page](https://github.com/PolymerElements/iron-pages) Github page.

**Comment by syeshchenko** [comment]
Thanks!
