### ISSUE TITLE
paper-menu-button Bug on tap

### ISSUE THREAD

**Issue by summers173** [Polymer/polymer#2289]
Sometimes (not always) when in the documentation example

<paper-menu-button>
  <paper-icon-button icon="menu" class="dropdown-trigger"></paper-icon-button>
  <paper-menu class="dropdown-content">
    <paper-item>Share</paper-item>
    <paper-item>Settings</paper-item>
    <paper-item>Help</paper-item>
  </paper-menu>
</paper-menu-button>

when you tap on paper-icon-button (mobile and desktop) the ink expands but the menu does not open, you have to click right in the middle in order to the event propagate, and sometimes this don't even work.

Thanks in advanced

**Comment by tjsavage** [comment]
This issue was moved to PolymerElements/paper-icon-button#35
