### ISSUE TITLE
Array mutation methods cause IE to crash

### ISSUE THREAD

**Issue by kgastelum** [Polymer/polymer#2292]
Working on a component that data binds to an array of complex objects.  The initial rendering is fine; however, when the data changes, using the mutation methods to modify the property will cause IE to crash.

```
    this.splice("shapedData.groupedData", 0, this.shapedData.groupedData.length);
```

for (var x: number = 0; x < newdata.length; ++x) {
                this.push("shapedData.groupedData", newdata[x]);
            }

**Comment by azakus** [comment]
Hmm, I can't seem to reproduce this in IE 10, 11, or Edge.

Can you try with https://github.com/Polymer/polymer/pull/2314 applied?

**Comment by kgastelum** [comment]
Thank you for the quick response…

I do not believe this is a polymer issue; rather, it is IE (go figure…).  I have <div style=’display:table’… in my template and children of that div that are <div style=’display:table-row…> etc…  when changing the data using the array mutation methods, which causes the elements to be removed and rendered again, IE will crash.

I will try with #2314 just to see.

Thanks

**Comment by lrbridge** [comment]
I'm seeing the same behavior with array mutation methods and IE 11.  I tried Polymer 1.2.1 but I still have the same issue.  Looks like it crashes in polymer-mini.html on ```nativeAppendChild.call(container, node);```.

Did you ever get it working @kgastelum ?

**Comment by lrbridge** [comment]
Posting this in case it helps someone else...

We used dom-repeat with fake table classes (instead of table/tr/td because of https://github.com/Polymer/polymer/issues/1567), but then it was crashing in IE unless we remove the display: table and display: table-row styles.

I finally figured out it works with 0.7.16 webcomponents.js but NOT with 0.7.16 webcomponents-lite.js, so we'll be using webcomponents.js now.

https://jsfiddle.net/fkgzceaa/3/

**Comment by azakus** [comment]
Wow that's nuts. The difference you're seeing is probably due to webcomponents.js using the ShadowDOM Polyfill (-lite never uses the polyfill), and that is probably smoothing over the IE bug internally.

**Comment by mdwragg** [comment]
+1 @robdodson @tjsavage - please can we we get help either working around this or getting a fix prioritised? This is affecting the browser support of GE Digital's Predix polymer-based Platform. We're getting crashes across IE10 and 11 with custom Polymer components that we've created. We're actively trying to work around it on our end but really need your help to get past this blocker.

As always, thanks.

(p.s. I could've sworn I sent this message yesterday but I can't find it - apologies if I've asked the same thing twice!).

**Comment by tjsavage** [comment]
We can prioritize, my understanding is this may likely take a good amount of digging to get a root cause & fix. @azakus any thoughts on a workaround?

**Comment by mdwragg** [comment]
Thanks @tjsavage! We really appreciate your help.

**Comment by azakus** [comment]
If you replace the table styling with `display: block` and `display: inline-block`, then this doesn't crash. This has to be some weird IE bug regarding table layout.

**Comment by mdwragg** [comment]
Yeah... We'd love to use a normal table but 'cause #1567 ;-)

**Comment by azakus** [comment]
I traced this into `dom-repeat`'s `_detachInstance` function. If I try to step to this function, IE crashes: https://github.com/Polymer/polymer/blob/master/src/lib/template/dom-repeat.html#L623

@kevinpschaaf I might need some help here.

**Comment by azakus** [comment]
Ok, I got to the same spot as https://github.com/Polymer/polymer/issues/2292#issuecomment-155563648

**Comment by azakus** [comment]
I can change this to `container.appendChild(node)`, but that still crashes.

**Comment by azakus** [comment]
Ok, looks like removing the text node from its parent is the crasher.

**Comment by azakus** [comment]
WHOA, if you put `strip-whitespace` attribute on the `dom-repeat` elements, then it doesn't crash!

**Comment by mdwragg** [comment]
Whoa indeed... must try that! Thanks for digging in @azakus

**Comment by mdwragg** [comment]
Workaround works for me too. Thanks again for investigating @azakus!

**Comment by kevin-wise-infusionsoft** [comment]
FWIW we ran across this today in a case where an array was being replaced with a new array which was a subset of the previous array.  The same workaround works for us.  We have dozens of places where we are using arrays with dom-repeat but only one seems to need the workaround.  That's a little disturbing!

**Comment by kevin-wise-infusionsoft** [comment]
Any chance of making strip-whitespace the default?  If it fixes the issue and boosts performance, why not?  Is there some downside?

**Comment by TimvdLippe** [comment]
@kevin-wise-infusionsoft There is an already open issue to discuss this feature: #3363

**Comment by cgug** [comment]
So besides a `strip-whitespace` workaround is there any actual fix for this year old issue? I use splice a lot and need to support IE 11.

**Comment by PascalLaier** [comment]
Up! It seems in Polymer 1.9.1 this is still an Issue.

**Comment by ntarora** [comment]
Yep still an issue in 1.11.0, no issues applying the workaround
