### ISSUE TITLE
Polymer.Base.set doesn't call notifyPath if root argument is provided

### ISSUE THREAD

**Issue by mgiuffrida** [Polymer/polymer#2296]
[`Polymer.Base.set(path, value, root)`](http://polymer.github.io/polymer/#methods) takes an optional `root` param, the "Root object from which the path is evaluated."

The documentation fails to mention that calling `obj.set(path, value, root)` [will not result in `obj.notifyPath` being called](https://github.com/Polymer/polymer/blob/720f2c004d830428557bfe3992d84dff5c9a02f2/src/standard/notify-path.html#L169). I guess this makes sense because you don't know the path of `root`, but you _could_ know it (it's just metadata of a property). I think the documentation should clearly call this out. (Or find a way to always call `notifyPath`. It's really weird that there's an "overloaded" way of calling `set` that doesn't notify.)

**Comment by arthurevans** [comment]
+1. I found this very confusing when I was wrestling with `set`.

`root` can be useful on `get` as in the demo code here: https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#array-binding

The use case for it on `set` is more opaque to me, but at any rate, it should be documented.

**Comment by kevinpschaaf** [comment]
The value of `root` on `set` is dubious; we should just update the documentation and deprecate it in the future.

**Comment by mgiuffrida** [comment]
:+1:

**Comment by TimvdLippe** [comment]
The [documentation](https://www.polymer-project.org/2.0/docs/api/elements/Polymer.Element#method-set) has been updated to make this more clear:

> `root` Root object from which the path is evaluated. When specified, no notification will occur.
