### ISSUE TITLE
Support CSS @import in new styling system.

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#2300]
```
<dom-module id="syntax-colors">
  <template>
    <style>@import url(../highlightjs/styles/default.css);</style>
  </template>
</dom-module>
```

So users can use an existing stylesheet and also avoid a build tool.

**Comment by sorvell** [comment]
Due to our need to manipulate style data to provide scoping and custom property-like support, this data must be available to javascript. Unfortunately, when `@import` is used, we are not guaranteed to be able to access the styling data. 

Therefore, we don't plan to add support for this.
