### ISSUE TITLE
Polymer.updateStyles under SHADY DOM

### ISSUE THREAD

**Issue by summers173** [Polymer/polymer#2301]
This instruction behaves as expected on Shadow DOM

```
Polymer.updateStyles({'--accent-color': 'red']});
```

All components change, but in Shady dom, some components as 'paper-button' does not change, I got

```
<style is="custom-style">
    :root {
        --paper-button: {
            background: var(--accent-color);
            color: var(--white);
        }
    }
</style>
```

This and other elements that obey the style rule does not change under SHADY DOM.

**Comment by srijken** [comment]
I have a repro based on Polymer 2.0 that demonstrates the same: https://github.com/srijken/polymer-issuerepro

Do you want to track this here or in a new issue?

**Comment by azakus** [comment]
Duplicate of #2268
