### ISSUE TITLE
<content> tags inside of conditional templates don't become insertions points

### ISSUE THREAD

**Issue by miztroh** [Polymer/polymer#2302]

**Comment by sorvell** [comment]
Could you provide a test case of this issue?

There's a [known issue](https://github.com/Polymer/polymer/issues/2276) in Polymer 1.1 release that should be fixed shortly. I also recommend testing after that fix lands.

**Comment by nelsonsilva** [comment]
@sorvell I think something like: https://jsbin.com/napezi/1/edit illustrates the issue, right @miztroh ?

**Comment by miztroh** [comment]
In a simplified test case, this ended up working as expected.  I've already revised my complex use case to avoid the issue I was experiencing.  I'll close this issue for now and reopen if I come across it again.
