### ISSUE TITLE
FIXME comment in paper-styles/demo/index.html

### ISSUE THREAD

**Issue by davidfstr** [Polymer/polymer#2305]
There is a FIXME comment in paper-styles/demo/index.html related to #1415, which has been closed. Therefore I suspect the FIXME can either be addressed or deleted.

Repro steps:
* bower install PolymerElements/paper-styles#^1.0.0
* cat bower_components/paper-styles/demo/index.html | grep FIXME

Expected results:
* The grep yields no lines.

Actual results:
* The grep emits a single line.

In case you're wondering how I found this, the phrase "FIXME" is flagged by checkin guards in my build system.

**Comment by ebidel** [comment]
This issue was moved to PolymerElements/paper-styles#54
