### ISSUE TITLE
Newer Chrome is not Respecting Polymer Styling Api While Older Chromium is

### ISSUE THREAD

**Issue by dman777** [Polymer/polymer#2307]
-----------------------------------------------------------------------------
###### update: 
forgot to add that I am using Polymer 1.1 locally, not sure which polymer library the plunker is using 

###### update 2: 
After work I tried the chromium version with my local Polymer 1.1 instead of the plunker, the styling api does not work. The below also doesn't change the shadow. The only way to make the shadow modifier work,  I had to modify paper-header-panel.css and remove box-shadow styling in it :
Note: this is only for local polymer, not whatever plunker is using. 
```
body /deep/ .paper-header-panel-0 #dropShadow {
  height: 8px;
  box-shadow: inset 0px 24px 7px -20px rgba(0,0,0,0.4);
}
```
--------------------------------------------------------------------------------------
[This is the plunker used](http://plnkr.co/edit/NjYmhWYesQMxhB6WjniU?p=preview)

```html
 paper-header-panel {
      --paper-header-panel-shadow: {
        height: 500px;
        box-shadow: inset 100px 100px 100px 100px rgba(0,0,0,0.4);
      };
  }
``` 

The above code is not being effective on `Google Chrome 44.0.2403.155`. However, it is being effective on the older `Chromium 38.0.2125.101`:

In this comparison, Chromium browser is on the left while Chrome is on the right
![pic](https://cloud.githubusercontent.com/assets/887815/9346979/2bb2170e-45e9-11e5-83e0-832608858155.jpg)

-------------------------------------------------------------------------------------
![pic](https://cloud.githubusercontent.com/assets/887815/9347062/5de45a7e-45ea-11e5-990b-c9dcc1bbc919.jpg)

**Comment by frankiefu** [comment]
The issue is in paper-header-panel (https://github.com/PolymerElements/paper-header-panel/issues/38) which is fixed.  Please try with the latest and see if the issue is still there.

**Comment by sorvell** [comment]
Closed based on previous comment and age. Please re-open the issue on paper-header-panel if it returns. Thanks.
