### ISSUE TITLE
$ object (this.$) not inherited properly on FF40 and FF41(possible earlier versions) in polymer#1.1.0

### ISSUE THREAD

**Issue by KaptenJansson** [Polymer/polymer#2309]
When trying to reference an element like so:

`Polymer.dom(this.$.element).appendChild(childElement);`

we get `this.$ is undefined` when using polymer#1.1.0 while it works fine in polymer#1.0.9 on FF40 and FF41.

Chrome works fine in either case.

**Comment by sorvell** [comment]
If `this.$` is undefined, it's likely that something is wrong in the bootup/lifecycle process of the element. We'll need some additional information (where is that call being made?) and ideally a test case to help.

**Comment by KaptenJansson** [comment]
Code is from here https://github.com/webrtc/testrtc/blob/master/src/ui/testrtc-suite.html#L108.

If you want, I could push it in a non working order to a 1-dot.appspot.com instance?

**Comment by azakus** [comment]
Closing due to age. Please reopen if this is still an issue. We're happing to help debug a working test case.
