### ISSUE TITLE
IE11 error "unable to get property '_lightChildren' when component is just a <content> tag

### ISSUE THREAD

**Issue by twlamb** [Polymer/polymer#2310]
If you create a component such as:

```html
<link rel="import" href="../bower_components/polymer/polymer.html" />

<dom-module id="test-component">
    <template>
        <content></content>
    </template>
</dom-module>
<script>
    Polymer({
        is: "test-component"
    });
</script>
```

IE11 will throw an error when the page is rendered.  It seems the page renders OK, but if you use "unresolved" on the body of your page, it will never resolve.

If you add an html tag around `<content>` such as a `<div>`
```html
<link rel="import" href="../bower_components/polymer/polymer.html" />

<dom-module id="test-component">
    <template>
        <div>
            <content></content>
        </div>
    </template>
</dom-module>
<script>
    Polymer({
        is: "test-component"
    });
</script>
```
Then it works just fine.  If you use a paper-material in your page and "unresolved" it will never be removed in IE11, since paper-material's template is just `<content></content>`.

**Comment by sorvell** [comment]
@rictic Since we've discovered this is a` webcomponentsjs` issue, can you close this in favor of that one when it's filed? Thanks.
