### ISSUE TITLE
$$(selector) within template instance.

### ISSUE THREAD

**Issue by nloewen** [Polymer/polymer#2312]
I have a project using polymer 1.0 with a dom-repeat template set up something like this.

```
...
<paper-menu>
    <template is="dom-repeat" items="list">
        <paper-item>
            <paper-item-body>{{item}}</paper-item-body>
            <paper-icon-button on-tap="handleButton">
        </paper-item>
    </template>
</paper-menu>
...
```

In the handleButton function, I want access to the <paper-item-body> in the template instance. My function accesses it like this

```
...
handleButton: function(event) {
    var item-body = event.model.$$("paper-item-body");
    // Do stuff with item-body
    ...
},
...
```

This works well in my project using Polymer 1.0. Using Polymer 1.1, ```e.model.&&("*")``` always returns undefined. What I'm confused about is that when I attempted to create an example project showing it working in Polymer 1.0 and broken in 1.1 for a bug report, I was unable to show it working in 1.0. Is it a bug that this doesn't work or is this a bug that it does? What is the recommended way to perform a selector query within a repeated template instance?

**Comment by azakus** [comment]
This is an unintended effect of reusing `Polymer.Base` as the prototype of template instances.

`$$` always looks at the element's root, but `event.model` is not really an element, and the stamped children would not even ben in the root, as they are light dom children of the host.

If you really need to do this, you can use `Polymer.dom(event).localTarget.previousElementSibling` to get to the `paper-item-body`.

**Comment by nloewen** [comment]
Thanks
