### ISSUE TITLE
dom-repeat property bindings fall out of sync

### ISSUE THREAD

**Issue by JakeGrice** [Polymer/polymer#2313]
Example markup:

    <template id="my-template" is="dom-repeat" items="{{catalog.tabs}}" as="tab" index-as="tabIndex">
        <span>{{tab.label}}</span>
        <span>{{tab.itemCount}}</span>
    </template>

Example JS:

    this.catalog.tabs[0].tabCount = 123;
    this.set('catalog.tabs', this.catalog.tabs); // Doesn't work
    this.$['my-template'].render(); // Doesn't work

Inspecting the data on the template by using `document.querySelector('* /deep/ #my-template")`

The `_instances[0].__data__` property reveals that the `tabCount` property is populated on the `tab` object, yet the `tab.itemCount` binding doesn't work. See the screenshot where the `itemCount` value is now out of sync.

![polymer binding](https://cloud.githubusercontent.com/assets/3504661/9365798/880f924a-4681-11e5-93bc-2a4af707a6dc.PNG)

After digging into the internals and trying everything, the only working solution is pretty messy:

    var tabs = this.catalog.tabs;
    this.set('catalog.tabs', null);
    this.async(function() {
        this.set('catalog.tabs', tabs);
    });

I would imagine this is a pretty critical bug. Note: This worked flawlessly in 0.5. The version I'm on now is 1.1.0.

**Comment by kevinpschaaf** [comment]
This is currently by design.  You will need to use `this.set('catalog.tabs.0.tabCount', 123);` to properly notify the `dom-repeat`.

We have a task to improve this but as it's a breaking change it wouldn't land until the next major release of Polymer: https://github.com/Polymer/polymer/issues/3343

**Comment by JakeGrice** [comment]
Thanks for the info! :+1:
