### ISSUE TITLE
polymer-project.org Element catalog - downloading individual elements error

### ISSUE THREAD

**Issue by pippintook** [Polymer/polymer#2317]
After selecting the  "elements folder" method and then clicking download, I get this error message -
![screenshot 2015-08-20 at 07 06 32](https://cloud.githubusercontent.com/assets/11688445/9369051/2dd8c420-470a-11e5-919f-790f96138925.png)
I'm on the latest Chrome OS dev channel.

**Comment by tjsavage** [comment]
This issue was moved to Polymer/polymer-element-catalog#168
