### ISSUE TITLE
Unexpected css ordering: variables override rules defined later

### ISSUE THREAD

**Issue by lesliana** [Polymer/polymer#2318]
As an example, if you have an element with the class 'title', and for some reason your css looks like:

.title {
  background-color: var(--my-red);
}
.title {
  background-color: yellow;
}

The title will appear red, because red is a variable, even though you would expect the yellow definition to override the earlier definition.

**Comment by sorvell** [comment]
This is a known issue that we're working to address. Closing this issue in favor of https://github.com/Polymer/polymer/issues/1873 where we are tracking progress.

**Comment by JeremybellEU** [comment]
@lesliana https://github.com/Polymer/polymer/issues/2318 has just been created to probably track the progress of this bug.
