### ISSUE TITLE
Binding to innerHTML (or any element property)

### ISSUE THREAD

**Issue by urandom** [Polymer/polymer#2320]
Currently, if you are very stubborn, you can trick polymer to do just that by writing this very weird binding: ```<div inner-h-t-m-l="[[ _computeMyHTML(some_data) ]]"></div>```. While this kinda-sorta works, it doesn't quite feel like the best one can achieve in life.

So here's hoping that a better solution can be invented. One that can write to any element _property_, be that innerHTML, textContent, scrollTop, or whatever. Something sort of like: 
``` <div innerHTML*="[[ _computeMyHTML(some_data) ]]" scrollTop*="[[ _scrollTopProp ]]"></div>```

**Comment by azakus** [comment]
Those values can't be observed, so the best you could get is a one way setter. Both of your example properties are not ones I would ever advise setting. Do you have some other properties that are not attribute backed that would be useful?

**Comment by urandom** [comment]
A one-way setter would be perfect. I can't think of any other properties that would be useful, though just setting innerHTML would be very useful.

**Comment by azakus** [comment]
I don't we want to support that. You can always use a observer to set those values yourself.

**Comment by arthurevans** [comment]
Note that while binding to specific properties like `innerHTML` and `scrollTop` may not be a great idea, Polymer's binding system already does exactly what you asked for by default: bind to element _properties_.

Because of the way Polymer [maps attribute names to property names](https://www.polymer-project.org/1.0/docs/devguide/properties.html#property-name-mapping), `inner-h-t-m-l` maps to `innerHTML` and `scroll-top` to `scrollTop`. `text-content` works fine, too, but we generally use:

    <tag>{{binding}}</tag>

As shorthand. 

Here's a don't-try-this-at-home jsbin that uses all three:

http://jsbin.com/siyoca/edit?html,console,output

**Comment by urandom** [comment]
@azakus : No, not really. I don't think there's any way to actually set the innerHTML of an element inside a template element used by something like iron-list, for example. While my current solution ('inner-h-t-m-l') is ugly, it's at least elegant and easy to both use and understand. Having to resort to some sort of special listener (i.e. some sort of special 'item-recycled' event of the iron-list) for this would first have to involve actually finding if such a listener even exist, and if you are lucky and one does exist and suits you, you'd then have to write a potentially cumbersome callback for it just to fill out that property of some inner element.

**Comment by matthew-dean** [comment]
Vue.js uses the `v-html` tag to bind an expression to the element contents and have that expression be accessible as one of the properties. That is, there are very reasonable use cases when `<tag>{{binding}}</tag>` is not appropriate.  Seems rational to add to Polymer for the same reasons.

**Comment by voondo** [comment]
@azakus no way to reconsider your decision ? I agree with @urandom and @matthew-dean, having a special (even one-way) binding like `inner-html` would be great (I feel bad to write `inner-h-t-m-l` but I feel more bad to have to use observers for a such simple need)

**Comment by jsilvermist** [comment]
I don't understand why this is an issue, don't we already have this functionality? What's the big issue of a few extra hyphens?

**Comment by voondo** [comment]
Indeed this is not a big issue if the backward compatibility wouldn't break in future.
But anyway it looks like an ugly hack.
