### ISSUE TITLE
polymer does not expand data attributes on custom elements

### ISSUE THREAD

**Issue by urandom** [Polymer/polymer#2324]
When writing the following:
```html
   <paper-button data-some-stuff="[[ _computeMyStuff(someProperty) ]]"></paper-button>
```
the data attribute gets discarded from the element when everything is ready. Placing the same data attribute on a 'div' or some other standard element works fine in comparison.

**Comment by nazar-pc** [comment]
I think this works as expected, since you're binding to property, not attribute.
Try this instead:
```html
   <paper-button data-some-stuff$="[[ _computeMyStuff(someProperty) ]]"></paper-button>
```
Here is documentation: https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#attribute-binding

**Comment by urandom** [comment]
Yes, that seems to work as expected (I always forget about this syntax). It's my error, sorry for wasting time.
