### ISSUE TITLE
Data binding in attribute fails

### ISSUE THREAD

**Issue by theboyWhoCriedWoolf** [Polymer/polymer#2326]
I don't seem to be able to data bind to any html attributes, I have tried using square and curly brackets:

where fooStyle  = "background-color:red;"
```
<div class="foo" style="[[fooStyle]]" > </div>
```

**Comment by miztroh** [comment]
Try ``style$="{{fooStyle}}"``.

**Comment by miztroh** [comment]
Sorry for the bad formatting.  It was an email response.  All you're really
missing is the $.  You can still use one-way binding like you were in your
example.

**Comment by theboyWhoCriedWoolf** [comment]
amazing thanks
