### ISSUE TITLE
Polymer.html file script issue

### ISSUE THREAD

**Issue by uppalapati41** [Polymer/polymer#2327]
Was working on project where am using polymer for creation of custom elements and i have downloaded ploymer zip file and ruining project everything was working fine up to IE 9 but when i make a reference to below link code it is not loading in IE 9 and throwing script error before creating Polymer object not exactly sure what was going wrong.

<link rel="import"
      href="http://www.polymer-project.org/1.0/samples/components/polymer/polymer.html">

**Comment by sorvell** [comment]
IE9 is not a browser that's supported by Polymer so your mileage may vary, please see https://www.polymer-project.org/1.0/resources/compatibility.html.
