### ISSUE TITLE
Support elements defining custom properties values for light dom nodes

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#2328]
For example, an element that defines color values for its light dom paper-radio-buttons:
```
#container ::content paper-radio-button {
   --paper-radio-button-checked-ink-color: red;
   --paper-radio-button-checked-color: red;
  --paper-radio-button-unchecked-color: red;
}
```

**Comment by miztroh** [comment]
@ebidel Duplicate of https://github.com/Polymer/polymer/issues/2188.

**Comment by sorvell** [comment]
Good call @miztroh, closing in favor of https://github.com/Polymer/polymer/issues/2188.
