### ISSUE TITLE
ES6: Better support for ES6 class syntax

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#2329]
@sjmiles and I talked about this syntax. Can we land this asap before the Summit?

```
class MyElement {
    registered() { // TODO: Polymer core make this work
      this.is = 'my-element';  
      this.properties = {
        foo: {
          type: String,
          value: 'foo prop made it!!'
        }
      }; 
    }

    // everything else is business as usual
    created() {}
    ready() {}
    attached() {}
    detached() {}
    attributeChanged() {}
  }

  Polymer(MyElement); // TODO: Polymer core need to support taking `MyElement` instead of `MyElement.prototype`.
```

```
    // @sjmiles: We will put this in Polymer core
    Polymer.Base.registerCallback = function() {
      this._doBehavior('registered'); // abstract
      this._registerFeatures();  // abstract
    };
```

**Comment by laco0416** [comment]
:+1:

**Comment by redian** [comment]
+1

**Comment by ikeagold** [comment]
:+1:

**Comment by JableSoHo** [comment]
When I declare properties in my ES6 class as shown above it works fine, but when I add an observer to a property the observer function does not fire.  I have a jsbin that illustrates this:

http://jsbin.com/senulobuho/edit?html,js,output

**Comment by laco0416** [comment]
@JableSoHo i think `this.properties` is a mistake. `properties` should be *static* like as `get is()`. 

http://jsbin.com/yajehiweha/edit?html,js,console,output

**Comment by JableSoHo** [comment]
@laco0416 Thanks a lot, that fixed the issue!!

**Comment by sjmiles** [comment]
@laco0416, @JableSoHo: beware of making a `properties` getter that returns an inline object. Polymer uses `this.properties` more than once, and the getter as written will return a new object every time.

**Comment by sjmiles** [comment]
These requests should be fulfilled now via https://github.com/Polymer/polymer/pull/2365

**Comment by ebidel** [comment]
Confirmed the changes :100:

**Comment by JableSoHo** [comment]
@sjmiles Would it be best then to declare this.properties in the registered function and in the getter just return that?

**Comment by ebidel** [comment]
@JableSoHo.  See my syntax in https://github.com/Polymer/polymer/issues/2329#issue-102177066

**Comment by JableSoHo** [comment]
@ebidel I used your syntax which works.  Except now neon-animations, and dialog buttons throw an exception. This is the exception : 

Uncaught TypeError: Illegal constructorPolymer.NeonAnimationRunnerBehaviorImpl._configureAnimationEffects @ neon-animation-runner-behavior.html:44Polymer.NeonAnimationRunnerBehaviorImpl.playAnimation @ neon-animation-runner-behavior.html:81Polymer._renderOpened @ iron-dropdown.html:288(anonymous function) @ iron-overlay-behavior.html:255Polymer.Async._atEndOfMicrotask @ async.html:50

**Comment by ebidel** [comment]
Can you file a bug over on that repo along with the codes snippet you're using to register the element?

**Comment by JableSoHo** [comment]
Ive logged an issue.  [#2382](https://github.com/Polymer/polymer/issues/2382)

**Comment by wenerme** [comment]
Is [this](http://stackoverflow.com/a/32689976/1870054) the right way to register behaviors in es6 ?

**Comment by ebidel** [comment]
@kevinpschaaf is https://github.com/MartinMoizard/polymer/commit/4e1c81dc2944ce5943a1d91a035f260ab2583560 the right order?
