### ISSUE TITLE
Should debounce's return value be documented?

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#2333]
Re: https://github.com/Polymer/polymer/commit/fb521205520f2319d2c3a715027687a6711d1813
Added a return value, it's not documented.

Not sure if this matters--I think the end-user-visible version of debounce might be elsewhere...? And I'm not sure what I'd be using the debouncer for, anyway. But in the interest of Full API documentation, I'm filing this issue anyway.

**Comment by sorvell** [comment]
Electing not to document this at this time.
