### ISSUE TITLE
_addComplexObserverEffect adds useless property effects for litteral arguments

### ISSUE THREAD

**Issue by david-saslawsky** [Polymer/polymer#2336]
When you declare an observer like this one: `observe(12,"foo",bar.*)` then `_addComplexObserverEffect()` will create a property effect for `12` and `"foo"`.

Looks like a `if(arg.litteral)` is missing in this function.

```
_addComplexObserverEffect: function(observer) {
  var sig = this._parseMethod(observer);
    sig.args.forEach(function(arg) {
      if(arg.litteral)
        return;
      this._addPropertyEffect(arg.model, 'complexObserver', {
        method: sig.method,
        args: sig.args,
        trigger: arg
      });
    }, this);
},
```

**Comment by JeremybellEU** [comment]
Referencing #3153 as it solved a similar issue, but with parent properties.

**Comment by TimvdLippe** [comment]
This should since be fixed as computed functions now keep track if they were static or not.
