### ISSUE TITLE
Polymer.dom can call some shady dom code when running shadow dom

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#2341]
For example, the dom mutation methods call shady dom code paths. Instead they should be routed to the native dom methods: `appendChild`, `insertBefore`, `removeChild`, `replaceChild`, `cloneNode`.

**Comment by sorvell** [comment]
NOTE: https://github.com/Polymer/polymer/pull/2338 was submitted to correct this issue, but I think we should just branch these methods earlier instead.

**Comment by sorvell** [comment]
@rictic Would you mind taking a look at my PR for this https://github.com/Polymer/polymer/pull/2342 and testing it out. Feel free to merge it if it looks ok. Thanks!

**Comment by rictic** [comment]
Running tests

**Comment by rictic** [comment]
The tests that were failing before are passing now. I'll do a full run and merge this tonight if all's well.
