### ISSUE TITLE
Double negation support

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#2343]
It is sometimes convenient to use double negation.
For instance, sometimes you have numeric property and you want other element to have `active` property if only number is non-zero, in this case double negation is useful in order to pass boolean value instead of numeric:
```html
<my-element attr$="[[!!numeric_prop]]"></my-element>
```

It is much nicer to have just `attr` instead of `attr="5"`.
Probably, related to #2182, but I'm not sure.

**Comment by azakus** [comment]
We're not very interested in expanding the vocabulary of expressions right now.
You can always make a computed function that applies a boolean pass over the input:

```html
<my-element attr$="[[bool(numeric_prop)]]"></my-element>
```
```js
  bool: function(prop) {
    return !!prop;
  }
```
