### ISSUE TITLE
Binding to reflected property

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#2344]
```haml
%dom-module(id="cs-icon")
	%template
		%template(is="dom-if" if="[[multiple_icons]]")
			X
		%template(is="dom-if" if="[[!multiple_icons]]")
			Y
	%script(src="script.js")
```
```coffeescript
Polymer(
	'is'				: 'cs-icon'
	properties			:
		icon			:
			reflectToAttribute	: true
			type				: String
		multiple_icons	:
			computed	: '_multiple_icons(icon)'
			type		: Boolean
	_multiple_icons : (icon) ->
		icon.split(' ').length > 1
)
```
```html
<cs-icon icon="[[icon]]"></cs-icon>
```
Two issues here:
* eventually neither `X` nor `Y` is shown, even though computed `multiple_icons` is boolean
* while `icon` property is reflected, attribute is removed during binding to property

No errors in browser console.
When bind as to attribute, everything works as expected.

**Comment by sorvell** [comment]
Closed in favor of https://github.com/Polymer/polymer/issues/2348.
