### ISSUE TITLE
Documentation for `preserve-content`?

### ISSUE THREAD

**Issue by pkaske** [Polymer/polymer#2346]
I scratched my head for quite some time till I found out about the `preserve-content` attribute on  templates to keep them untouched by polymer.
Is this somewhere in the docs? I couldn't find it. If it's missing, it's maybe something worth mentioning :wink:

**Comment by Sleeckx** [comment]
+1

Would like to know if this feature is here to stay as well.

**Comment by arthurevans** [comment]
@kevinpschaaf Is this OK to document? If so, going to move it to the docs repo.

**Comment by dlasky** [comment]
we would like to use this as well if its safe to do so

**Comment by kevinpschaaf** [comment]
Yep, let's document.

Adding `preserve-content` to a template nested within a Polymer element's top-level template will:
* prevent bindings from being parsed (and removed) from the template
* prevent special handling of nested template's `content` fragment; specifically, the `content` fragment of a nested template is normally cached by Polymer and cleared, to be handed back to the template (as `_content`) prior to `ready` time.  This is done for a number of reasons including performance (avoids the cost of unnecessarily cloning elements in nested template contents) and to avoid `HTMLTemplateElement` bugs on certain platform/versions (older Chrome versions upgraded elements in nested templates when cloning outer templates, and Safari failed to deep-clone nested template contents).

**Comment by arthurevans** [comment]
This issue was moved to Polymer/docs#1462
