### ISSUE TITLE
Overlapping buttons when the screen size is reduced

### ISSUE THREAD

**Issue by srgummad** [Polymer/polymer#2351]
The buttons near the footer and above it overlap when the screen size is reduced. The same is observed when the site is opened in a mobile.
![polymer-issue](https://cloud.githubusercontent.com/assets/10765108/9429284/ea0c25c0-4998-11e5-89d4-63f21eb935ed.JPG)

Also for these two buttons....

![polymer-issue2](https://cloud.githubusercontent.com/assets/10765108/9429285/fe82eab6-4998-11e5-9833-2bd49a2b7fd0.JPG)

**Comment by azakus** [comment]
@arthurevans I know we're going to redo the landing site at some point. Leaving this up to you if we bother fixing this before that.

**Comment by azakus** [comment]
This issue was moved to Polymer/docs#1549
