### ISSUE TITLE
X does not clear the search box results on 'element catalog' - intended behavior? 

### ISSUE THREAD

**Issue by dman777** [Polymer/polymer#2352]
On https://elements.polymer-project.org/:

1) I type in the search box with `all elements`.
2) I clear the search box by hitting the x
3) Although the search box clears visually, it does not really clear
4) I have to hit backspace to clear out the empty search box to get all results to show on a empty search box. 

I'm not sure, maybe this is the intended behavior. Logically, I would expect the search results to clear(and all elements to show on `all elements`) when I clear the search box by hitting the `x`.

**Comment by ebidel** [comment]
This issue was moved to Polymer/polymer-element-catalog#206
