### ISSUE TITLE
Browser Sync is too slow

### ISSUE THREAD

**Issue by baazoo** [Polymer/polymer#2353]
Browser Sync is useless due to a long refresh time and I don't know what is causing it.

I went through a lot of trouble to get Polymer running especially to fix socket.io issues. I finally did it but had to leave my project on August 1. I came back to project on August 21 and started from scratch. First updated the polymer generator and then:
```
yo polymer
gulp serve
```
All good up to here. The start page loads in a reasonable amount of time. However, after the first edit, it takes around 10 seconds for the page to refresh.

Console log:
``
Resource interpreted as Document but transferred with MIME type text/css: "http://localhost:3000/bower_components/paper-drawer-panel/paper-drawer-panel.css".
localhost/:61 Resource interpreted as Document but transferred with MIME type text/css: "http://localhost:3000/bower_components/paper-item/paper-item-shared.css".
localhost/:61 Resource interpreted as Document but transferred with MIME type text/css: "http://localhost:3000/bower_components/paper-menu/paper-menu-shared.css".
``

I am sure that I didn't have this issue in the previous version.

**Comment by baazoo** [comment]
I could fix the issue "for now" by closing the inspector window.

**Comment by arthurvr** [comment]
I suspect you're talking about the PSKs browsersync setup, so this isn't really the right repo. Try here: https://github.com/polymerelements/polymer-starter-kit/issues. It is, though, very likely that the issue you're having is a browsersync one, unrelated to PSK, as we have a very basic setup.

**Comment by ebidel** [comment]
Yea @baazoo. Do you mind posting this over there?
