### ISSUE TITLE
Binding to element itself

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#2354]
``` html
<template is="dom-bind">
    <section is="cs-section-modal" this="{{modal}}">One Two Three</section>
    <button bind="[[modal]]" action="open" is="cs-button" type="button">Button</button>
</template>
```

Eventually when button is clicked `modal.open` will be called (yes, with correct `this` in method) and modal will be opened.
This can be achieved with simple behavior:

``` coffeescript
Polymer.cs.behaviors.this =
    properties  :
        'this'  :
            notify      : true
            readOnly    : true
            type        : Object
    ready : ->
        @_setThis(@)
```

But I can make PR if you like this to make it native feature, since it is really nice and quite useful.

**Comment by TimvdLippe** [comment]
It took some tinkering, but you can do this in Polymer 2: http://jsbin.com/nahidepide/edit?html,console,output It probably requires some refinement by storing it on the prototype instead, but you can store the metadata and then later use it.

**Comment by nazar-pc** [comment]
It incredibly complex piece of code for such a trivial feature! If that is the only way to implement it with classes, I'll never switch to them.
I've implemented it MUCH simpler with legacy behavior here (same as first comment, but in JS): https://github.com/nazar-pc/CleverStyle-Framework/blob/f0ead79cfcdc49880c4923bb33caabf6db5ac61d/assets/html/CleverStyle%20Widgets/cs-0-behaviors-%26-mixins/common/this.js

However, there was no question about whether it is possible or not, implementation exists in first comment since 2015. The idea was to add this to the Polymer itself, since this seems to be a useful feature.
