### ISSUE TITLE
Imported styles take precedence over local styles when declared in same tag

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#2357]
So, if I do:

    <style include="shared-styles">
      .foo { color: red; }
    </style>

I would expect the local `.foo` rule to override any imported one. But it _appears_ that the imported rules are added after any rules defined in the body of the tag, so they take precedence:

http://jsbin.com/jivupu/edit?html,output

I'm not sure whether a) this is the expected behavior, and b) whether we even want to document using a style tag with both `include` and local rules.

Please advise, @sorvell. Thanks.

**Comment by sorvell** [comment]
This is expected at the moment. I have to admit that mixing use of a style with include and content inside it is not something that I considered too deeply. I think it could be reasonable to change the behavior to make the includes first.

**Comment by sorvell** [comment]
Fwiw, sharing styles either with custom-style or in an element have the same 'include applies last' behavior. If we change it in custom-style, we should probably change it for other elements as well.
