### ISSUE TITLE
unable to access polymer-project.org - SSL connection error

### ISSUE THREAD

**Issue by sjama** [Polymer/polymer#2358]
polymer-project.org is mostly inaccessible. 

www and blog are down, although the elements catalog strangely works.
I suspect this maybe isp specific because it worked when I visited a coffee shop earlier.

Chrome Error Message: 
SSL connection error 
ERR_SSL_PROTOCOL_ERROR

related to #894

**Comment by tjsavage** [comment]
I'm unable to reproduce this - are you still seeing this error today?

**Comment by sjama** [comment]
Yep still the same. It's not just my laptop either, its the same on my phone. 
But as I mentioned earlier I think its only affecting some ISP/areas.

I got around it for now by installing a proxy extension, it works like a vpn.

**Comment by sjama** [comment]
yay, this seems to have been fixed. Closing.
