### ISSUE TITLE
`undefined` values are not consistently prevented from entering the configuration process

### ISSUE THREAD

**Issue by sjmiles** [Polymer/polymer#2360]
Generally setting a value to `undefined` is an anti-pattern, since we use `undefined` to indicate the state of not being set.

In fact, if you try set a value explicitly to `undefined` as a value in `properties`, the configuration object summarily ignores it. 

However, if you bind to an object path that evaluates to `undefined` or that cannot be evaluated, the configuration code does not ignore this value, leading to an inconsistency (and scenarios where it's impossible to control an element value with defaulting, see @sjmiles for specfics).

Ignoring `undefined` as a configuration value when it flows from bindings is a reasonably easy change which restores consistent behavior (i.e. see https://github.com/Polymer/polymer/blob/master/src/standard/configure.html#L70).

Note that make the behavior consistent can result in two change sequences in certain scenarios which is sub-optimal, again see @sjmiles for specfics). It seems that the 'treat undefined structured values as null` gambit coincidentally resolves this problem optimally, but we plan on evaluating that change separately.

**Comment by sjmiles** [comment]
CC @kevinpschaaf @sorvell

**Comment by miztroh** [comment]
@kevinpschaaf Any update here?  This issue is apparently causing rendering issues.

https://github.com/PolymerElements/paper-input/issues/145

**Comment by miztroh** [comment]
@sjmiles bump?

**Comment by TimvdLippe** [comment]
This still happens. In this JSBin (http://jsbin.com/pubexoroma/edit?html,console,output) the observer should run, given that the value is explicitly defined.

**Comment by kevinpschaaf** [comment]
Updated jsBin that shows binding an undefined sub-property from host to child.

* In 1.x, the child observer did not run at all (neither with default nor with the bound `undefined` value): http://jsbin.com/yofezo/1/edit?html,console,output
* In 2.x, the child observer runs with `undefined` from the host, as it registers this as a change from the default value: http://jsbin.com/zevari/edit?html,console,output

Closing, as this has been resolved in 2.x, and we recommend all users to upgrade to this version.
