### ISSUE TITLE
binding to functions (c.f. dom-repeat)

### ISSUE THREAD

**Issue by sjmiles** [Polymer/polymer#2362]
Dom-repeat allows binding to a named function in it's host scope. This is a useful feature but it only works for one level.

if x-list contains:
  `<template is="dom-repeat" filter="{{filter}}">`

user of x-list wants to do:
  `<x-list filter="{{filter}}">`

then they must declare `filter` in an unpleasant manner:

```
properties: {
  filter: {
    value: function() {
      return function(item) {
        return item.good;
      }
    }
  }
}
```

I don't actually have a solution, just wanted to capture the issue.

**Comment by birkir** [comment]
This is where ES6 shines.
```javascript
properties: {
  filter: {
    value: () => item => item.good
  }
}
```

But still, what identifies the value function from the returned function of the value? The only thing I can think of is the arguments. A value property should never use arguments, so they can be identified as such, but its still a bad solution.

```javascript
// Only execute non-argument functions
return value.toString().match(/function \(\w+\)/g)) ? value : value();
```
