### ISSUE TITLE
ES6: vulcanize + babel produces errors b/c of strict mode issue(s)

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#2363]
Atm, building an element in ES6 classes requires a transpiler like babel to work x-browser. That workflow looks something like this:

1. vulcanize | cripser (to get separate output.js file)
3. babel output.js

The full command is below. BabelJS adds `"use strict";` to the top of the transpiled output:

![screen shot 2015-08-24 at 4 26 47 pm](https://cloud.githubusercontent.com/assets/238208/9455202/83e2f55e-4a7d-11e5-839a-4ed67972bbb8.png)

Unfortunately, this means JS errors, as parts of core 'use strict' and other parts do not.

**Fix**
Easiest fix is to get ride of [this global](https://github.com/Polymer/polymer/blob/master/src/lib/settings.html#L12), make it `window.Polymer = {...`. I've confirmed changing this one line in the transpiled output works!

` vulcanize polymer.html --inline-script | crisper -h polymer.v.html -j polymer.v.b.js; babel --compact false polymer.v.b.js -o polymer.v.b.js
`

**Comment by addyosmani** [comment]
Fixed as of https://github.com/Polymer/polymer/commit/a75133d319feb6574533c94448984fb35f53df1a?
