### ISSUE TITLE
change event on radio-button-group

### ISSUE THREAD

**Issue by patrick11conway** [Polymer/polymer#2364]
1: I cant find documentation on how to use the change event for radio-button-group
what is the correct usage?

2:
document.querySelector('#radio-group-id').select($('#template').val());

document.querySelector('#radio-group-id').change(alert('change));

For the above code..the change event only fires on the javascript select...clicking on a radio button does not fire the change event

3.
$('.radio-button-class').change(function(){   
alert('change);
});

this code fires on each click change...but when I change the selected radio with up and down arrow keys the event is not fired

**Comment by azakus** [comment]
This looks like you might be mixing polymer and jquery. Can you post an example of the problem as you see it with something like JSBin?

**Comment by pconway11** [comment]
If I remember correctly I tried jquery as a fallback because document.querySelector().change() didnt fire on click.
Ive abandoned polymer for now so you may close this issue if you like.
