### ISSUE TITLE
Not all bindings ready during `ready` call as stated in docs

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#2366]
Here is quote from documentation:

> The ready callback is called when an element’s local DOM is ready.
> 
> It is called after the element’s template has been stamped and all elements inside the element’s local DOM have been configured (with values bound from parents, deserialized attributes, or else default values) and had their ready method called.
> 
> Implement ready when it’s necessary to manipulate an element’s local DOM when the element is constructed.

Here is simple test case: http://jsbin.com/mequziketo/3/edit?html,output
In console `false` will be three times, while one should be 1 `true`. Properties (attributes) are not ready at this stage.

Using `attached` instead of `ready` works.

Applying all of my patches from PRs that fixes some other issues didn't help, so this is a new one.

@sjmiles

**Comment by mvpmvh** [comment]
is this technically working as designed?? the `ready` function indicates that the local DOM is all set, but anything inside the `<content>` tag is considered to be part of the light DOM.

Here is the more relevant quote from documentation:

> In particular, there are no guarantees with regard to initialization timing between sibling elements or **between parents and light DOM children**. You should not rely on observed timing to be identical across browsers, except as noted below.

> For a given element:

> * The created callback is always called before ready.
> * The ready callback is always called before attached.
> * The ready callback is called on any **local DOM children** before it’s called on the host element.
> * This means that an element’s **light DOM children** may be initialized **before or after** the parent element, and an element’s siblings may become ready in any order.

> For accessing sibling elements when an element initializes you can call async from inside the attached callback

**Comment by nazar-pc** [comment]
Well, maybe...
Here is another example: http://jsbin.com/jenicamiva/1/edit?html,output
`input`s are in local DOM of `x-wrapper`, but do not exists at all at `ready` stage.
Which means that `dom-repeat` didn't even start at that time or bindings were not propagated to `dom-repeat`.
This all seems very tricky.

**Comment by mvpmvh** [comment]
to make sure I'm following along correctly: are you saying in your new link that you're expecting `this.shadowRoot.querySelector('input').checked;` to not throw an undefined exception?  

I didn't know `this.shadowRoot` was a way to query. If `this.shadowRoot` allows for querying beyond just local DOM, including all of the shadowDOM, how do you know that the shadowDOM is fully constructed by the time the `ready` function of a root polymer element is invoked? It still seems to me like you're trying to assume a non-local DOM element is available to query against in a wrapping element, whether it be the immediate parent or at an even higher level. Unless I'm misunderstanding something, it still seems like the safest way to access lightDOM elements is in the `attached` state.

**Comment by nazar-pc** [comment]
I'm using `this.shadowRoot` directly because of full WebComponents polyfill and I don't really like `Polymer.dom(this)`  kind of things, I want to be closer to native way of doing it.
Shadow DOM is a local DOM indeed:
> We call the DOM that an element is in charge of creating and managing its local DOM. This is distinct from the element’s children which are sometimes called its light DOM for clarity.

> Polymer supports multiple local DOM implementations. On browsers that support shadow DOM, shadow DOM may be used to create local DOM. On other supported browsers, Polymer provides local DOM via a custom implementation called shady DOM which is inspired by and compatible with shadow DOM.

So yes, `<input>` should be in what is called "local DOM" in Polymer's therminology, Shadow DOM in this specific example.

I have such feeling that there is some gap between moment when `dom-repeat` says it is ready and when it gets array to loop over, namely, bindings are established later than they should. So turns out that it is not actually ready at the `ready` stage.

**Comment by hawkett** [comment]
[Here is another example of this issue using pure Polymer](http://jsbin.com/sumule/edit?html,console,output)

On the ```ready()``` call, elements inside a ```dom-if``` are not yet stamped - they only become accessible at some later time, which as far as I can tell has no lifecycle callback. 

As noted by OP, the docs state that ```ready``` is called when everything in the Local DOM is finished. 

This made me wonder whether a ```dom-if``` was considered Local DOM, but the [docs on Local Dom](https://www.polymer-project.org/1.0/docs/devguide/local-dom.html) certainly seem to imply that it is by drawing a distinction between _statically_ created and _dynamically_ created Local Dom:

> Note: Nodes created dynamically using data binding (including those in  dom-repeat and dom-if templates) are not added to the this.$ hash. The hash includes only statically created local DOM nodes (that is, the nodes defined in the element’s outermost template).

**Comment by azakus** [comment]
Yes, `dom-if` and probably all elements using the `Templatizer` behavior will render themselves asynchronously.

@sorvell This could use some documentation.

**Comment by arthurevans** [comment]
The `dom-change` event fired by the `Templatizer` elements is documented here:

https://www.polymer-project.org/1.0/docs/devguide/templates.html#dom-change

However, there are a few things that could be documented better:

- The description of the `ready` callback should probably explicitly refer to the fact that the `dom-if`, `dom-repeat`, `dom-bind` elements aren't going to be ready at the same time. It's a common enough confusion that it should be called out.
- This could also be made clear on the description of each of the individual elements.
- Finally, because of the async nature of the Polymer.dom APIs, I think when `dom-change` fires the DOM may not actually have _changed_ yet.  But perhaps that isn't an issue anymore.
