### ISSUE TITLE
Polymer 1.0 gestures / track events -- what happened to xDirection & yDirection?

### ISSUE THREAD

**Issue by klebba** [Polymer/polymer#2369]
Previously in 0.5 there were `xDirection` and `yDirection` properties on track events; is there no alternative in 1.0?

**Comment by azakus** [comment]
`xDirection` and `yDirection` were just `dx >= 0 ? 1 : -1` and `dy >= 0 ? 1 : -1`.

**Comment by klebba** [comment]
@azakus got it -- thanks
