### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SriramWTC** [Polymer/polymer#2370]
I am getting uncaught error:polymer not defined error whenver running the application in browser.How can we resolve this error

**Comment by azakus** [comment]
Can you post an example using JSBin please?

If you are defining an element in the main document, and using polymer as an import, you should make sure to use the `WebComponentsReady` event or `HTMLImports.whenReady` function before trying to call `Polymer`

index.html:
```html
<!doctype html>
<script src="bower_components/webcomponents/webcomponents-lite.js"></script>
<link rel="import" href="bower_components/polymer/polymer.html">

<dom-module id="my-element">
<script>
HTMLImports.whenReady(function() {
  Polymer({
    is: 'my-element'
  });
});
</script>
</dom-module>
```

**Comment by azakus** [comment]
Closing due to age, please reopen if this is still an issue.
