### ISSUE TITLE
Overwriting behavior properties doesn't remove observers.

### ISSUE THREAD

**Issue by Pupix** [Polymer/polymer#2371]
Given the following behavior: 

```js
Polymer.OverlayBehavior = {

    properties: {
        visible: {
            notify: true,
            observer: '_visibleChanged',
            reflectToAttribute: true,
            type: Boolean,
            value: false
        }
    },

    _visibleChanged: function () {
        console.log('behavior message');
    }
};
```

After using it inside an element that overrides the configuration of `visible`:

```js
Polymer({
    is: 'overlay-element',

    behaviors: [Polymer.OverlayBehavior]

    properties: {
        visible: {
            notify: true,
            observer: '_visibleChanged2', //New observer function
            readOnly: true, //Became read only
            reflectToAttribute: true,
            type: Boolean,
            value: false
        }
    },

    _visibleChanged2: function () {
        console.log('element message');
    }
});
```

Changing `visible`'s value will now call both observers, even if the `visible` property has been overwritten by the element.

```js
document.querySelector('overlay-element')._setVisible(true);
-> "behavior message"
-> "element message"
```

As you may have seen, I used two different functions in my example, to make it easier to distinguish between the two. Even if the function has the same name, or is overwritten by the element, it will be called twice.

**Comment by azakus** [comment]
This is by design. Observers do not override each other, so multiple behaviors can observe the same property for the behavior's intended purpose.

**Comment by arthurevans** [comment]
So I get this clear (for the docs), if you want to _override_ what the behavior is currently doing, you need to override `_visibleChanged` in your element, but _not_ add a new `observer` entry on the property.

**Comment by Pupix** [comment]
@azakus Yea, figured that much.
Thanks for clearing everything out tho.
