### ISSUE TITLE
ES6 classes: Infer is property from class name (make it optional)

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#2383]
It would be cool to make setting `this.is` optional in `beforeRegistered()`. Can polymer core do something like below to make it optional?

```
class StockTicker {
    beforeRegistered() {
        // Takes camelcase class name "StockTicker" -> "stock-ticker".
        let is = this.constructor.name.replace(/\W+/g, '-')
            .replace(/([a-z\d])([A-Z])/g, '$1-$2').toLowerCase();
        this.is  = is;
    }
}
```

**Comment by ebidel** [comment]
cc @nicolasgarnier

**Comment by nicolasgarnier** [comment]
This totally makes sense as the 'is' information is (kinda) redundant to the Class name.

**Comment by laco0416** [comment]
:+1:

**Comment by birkir** [comment]
Well, currently the tag feature generates an `is` property on the prototype based on a hierarchy, so I can see no problems with adding method that bases that value of given class name.

https://github.com/Polymer/polymer/blob/master/src/micro/tag.html#L19

**Comment by ebidel** [comment]
@birkir right. If you're using `<dom-module>`, `is` is inferred from its `name` attr. However, if you leave it off, it breaks under vulcanize.

**Comment by sjmiles** [comment]
I've generally been reluctant to build-in a convention that associates your `constructor` function name with your element name via a transformation, but since it's optional (and this association seems defacto anyway) I think this is probably ok.

**Comment by TimvdLippe** [comment]
As we are now relying on `customElements.define`, I am not sure what we can do there. It seems that we can (in a hacky way) get the dash-case name of the constructor name: http://jsbin.com/yorivuyada/edit?html,console,output

**Comment by TimvdLippe** [comment]
Closing this per above comment. Please reopen if there is still an issue/enhancement we have to address.
