### ISSUE TITLE
Polymer not working correctly when activating shadow dom for firefox with flags in about:config

### ISSUE THREAD

**Issue by Spreadyy** [Polymer/polymer#2385]
The screenshot at the end of the post shows [polymer-project.org]() in firefox developer edition.
To test the new shadow dom feature I edited the flag "dom.webcomponents.enabled" as described in http://caniuse.com/#feat=shadowdom.
My guess is that polymer detects this change (shadow-dom-enabled) and doesn't use the shady dom anymore, but tries to work with the implementation of firefox' shadow dom. Maybe Polymer should test whether the shadow dom is working correctly before switching solutions. Then again, this is just a guess and honestly I don't know if this edge case should be handled (After all, you can break everything in about:config).
![polymer-project.org screenshot](https://cloud.githubusercontent.com/assets/12650063/9559632/c5f34c06-4df6-11e5-9496-a1411acd728c.png)

**Comment by arthurevans** [comment]
This is a known issue with the current polyfill, documented on the browser compatibility page.

https://www.polymer-project.org/1.0/resources/compatibility.html

Related to: https://github.com/webcomponents/webcomponentsjs/issues/289

**Comment by Spreadyy** [comment]
So you decided to use Firefox' implementation so they can test their shadow dom? Pretty good.
