### ISSUE TITLE
Perf: Polymer.Base.debounce slow in FF

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#2387]
I'm exploring how to improve unbelivable slowness of nested `dom-bind > dom-if > dom-if` and found one trick, replace this:
```javascript
debounce: function (jobName, callback, wait) {
	return this._debouncers[jobName] = Polymer.Debounce.call(this, this._debouncers[jobName], callback, wait);
},
```
with this:
```javascript
debounce: function (jobName, callback, wait) {
	callback = callback.bind(this);
	if (!wait) {
		callback()
	} else {
		setTimeout(callback, wait);
	}
},
```

Initial load become A LOT faster in Firefox, also I do not see any visual/functional issues or error messages in console.
What it actually does and might such change have some bad consequences?
It is quite difficult to trace how it works.
Firefox works with Shadow DOM and full polyfill, maybe it is connected somehow with Shady DOM...

My guess is that this was added to make smoother load on browser, but in fact with this debouncer Firefox freezes for 7 seconds and without it for just 2.5 seconds... It does make a huge difference.

**Comment by nazar-pc** [comment]
Well, replacing `Polymer.Debounce` with the same thing results in even further boost.

**Comment by marcus7777** [comment]
How do I understand it debouncers stops functions firing too frequently.eg. typing into input box searchn after something that stops typing.

**Comment by nazar-pc** [comment]
No, as I understand it works with rendering and life cycle in general, debouncing input events is not Polymer's job, it sends such events af often, as needed.

**Comment by marcus7777** [comment]
I've used it successfully to do just that. But maybe it was more than that, I am often wrong.

**Comment by IntranetFactory** [comment]
debounce is a generic utility function - see https://www.polymer-project.org/1.0/docs/devguide/utility-functions.html

We use it e.g. to throttle ajax requests.

**Comment by ebidel** [comment]
From the API docs (http://polymer.github.io/polymer/):

> Call debounce to collapse multiple requests for a named task into one invocation which is made after the wait time has elapsed with no new request. If no wait time is given, the callback will be called at microtask timing (guaranteed before paint).

debounce is helpful when you want to ensure a piece of code only runs once (if called numerous times) in a certain time frame. Most people think of this as throttling. Other libraries like underscore have similar mecahnisms: http://underscorejs.org/#debounce

**Comment by nazar-pc** [comment]
I think question was misinterpreted, I'm curious how it is used internally, and why it causes so huge overhead, especially in Firefox.

**Comment by ebidel** [comment]
My apologies. I did not read your first comment closely enough (only the title and followup posts). I'll reopen and leave this to @sorvell @kevinpschaaf @sjmiles  to see if there's a perf win somewhere.

**Comment by devinivy** [comment]
Is it possible that the issue is not one of _performance_, but the simple fact that the debouncing is happening on the tail end rather than head end of the function calls.  That is, you have to wait for the specified wait time before the first time the debounced function is called.

**Comment by azakus** [comment]
The API contract of `debounce` is that the callback is fired a MicroTask timing (mutation observer callback timing), and this change to `setTimeout` would not guarantee that same contract.

If this change works for your apps, free free to use it, but we can't accept this change into Polymer, as it may break other applications.

In general, Polymer is not going to focus on improving the performance of the Shadow DOM Polyfill, as it is intended solely for platform compatibility.
