### ISSUE TITLE
How to style the element which was dynamically append to the custom element.

### ISSUE THREAD

**Issue by wonsikin** [Polymer/polymer#2388]
```javascript
<dom-module id="my-element">
  <style>
    :host {
      display: block;
    }

    .test {
      color: red;
    }
  </style>
  <template>
    <button type="button" name="button" on-tap="handleButtonTapped">action</button>
    <div class="test">Hello World</div>
  </template>
  <script>
    (function() {
      Polymer({
        is: 'my-element',

        properties: {},
        handleButtonTapped: function() {
          var el1 = document.createElement('div');
          el1.innerText = 'Hello World';
          el1.setAttribute('class', 'test');
          this.shadyRoot.host.appendChild(el1)
        }
      });
    })();
  </script>
</dom-module>
```

I want the font color of the element that created in the method `handleButtonTapped` to be red. But in fact it was black;

**Comment by sorvell** [comment]
By design an element's styling comes from the local dom tree in which it exists. Therefore, when you add `el1` to the `host` element, it will be styled in that scope. 

Couple of minor points:
 * this.shadyRoot.host === this
 * make sure to use Polymer.dom when appending

**Comment by wonsikin** [comment]
@sorvell Thank you very much! It works now.
I have to manipulating the dom because I want to draw a chart via d3.js in a custom element .

**Comment by dlsso** [comment]
A note for those using compiled style sheets:

srovell's approach won't work, but an alternative solution I found was doing `Polymer.dom(this.root).appendChild(el)` which works but at the wrong location as noted by yattias, followed by `Polymer.dom(this.root).querySelector('.your-selector-here').appendChild(el)` to move  to the correct location.

Appears to get styles applied twice, but haven't seen any adverse side effects yet.
