### ISSUE TITLE
https://polymer-topeka.appspot.com/ page not working properly

### ISSUE THREAD

**Issue by RiazAhamed** [Polymer/polymer#2390]
![polymer-topeka-appspot-pages-bug](https://cloud.githubusercontent.com/assets/10165089/9597487/ea8c9bfc-509f-11e5-9ec0-6008f236058d.png)

**Comment by azakus** [comment]
No one has been maintaining that demo. @tjsavage, should this get some attention?

**Comment by tjsavage** [comment]
This issue was moved to Polymer/topeka#35
