### ISSUE TITLE
Strange behavior with custom "value" property

### ISSUE THREAD

**Issue by miyconst** [Polymer/polymer#2391]
I have a custom Polymer component which has a property:

```js
value: {
    type: String,
    value: "",
    observer: "valueChanged"
}
```

And I noticed that the value of the property being changed when it should not. Here is a minimal example to reproduce the issue: https://jsfiddle.net/vskkLr1t/1/.

Steps to reproduce:

1. Open console.
2. Input `1` in the first field.
3. Wait till the sum updates.
4. Input `2` in the second field.
5. The sum (`value` property) will be set to `2`.
6. Wait till the sum is updated again, this time to `3` which is correct.

Console output:
```
1: valueChanged 1
2: valueChanged 1
3: valueChanged 2
4: valueChanged 3
```

The lines 1 and 3 should not be there.

Exactly same code works as expected if I rename property from `value` to `v`: https://jsfiddle.net/vskkLr1t/.

**Comment by azakus** [comment]
The change event from the input bubbles, so you're setting `model.value` to the value of each input individually from the change events, then the timeout in `abChanged` will set value to what you expected.

A better setup would be to use a complex observer and just observe the `value` property like this example: http://jsbin.com/xaqana/edit?html,console,output
