### ISSUE TITLE
1.0 component demos like to 0.5 demos

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#2392]
Googling "paper elements demo" produces https://www.polymer-project.org/1.0/components/paper-elements/demo.html#paper-checkbox, but the correct demo is https://elements.polymer-project.org/browse?package=paper-elements

This is no good and very confusing. We need to kill the components under 1.0, unless we're going to update them to 1.0.

**Comment by arthurevans** [comment]
Already working on it ...

Those are the components the web site runs on so .. we can't get rid of them just yet ;-). But we can keep them from getting indexed.

**Comment by ebidel** [comment]
This issue was moved to Polymer/docs#1331
