### ISSUE TITLE
Problem when setting a JSON Object and accessing it <template>

### ISSUE THREAD

**Issue by fenerlee1907** [Polymer/polymer#2393]
Today, I faced a strange problem while migrating my project to Polymer 1.0. I have a JSON object which has sub values. After my Polymer component is created and ready to use, I change my JSON object as:

``` javascript
this.school.name = "New School";
```

After I change the value as shown, the value inside my template is not updated! There is nothing in the <span> below:

``` javascript
<template>
     <span>{{school.name}}</span>
</template>
```

I tried everything and finally realise that setting JSON object value in a different way solves my problem:

``` javascript
this.school["name"] = "New School";
```

I think there is a problem in the serialization process of Polymer for JSON objects. I am not sure if somebody faces the same problem but it needs to be fixed. There are a lot of JSON objects declarations in my project with "." notation and because of this problem, I needed to change them all.

**Comment by timeu** [comment]
You need to use the [set](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#set-path) method to notify the data-binding about the changed sub-property (see [docs](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#path-binding) for more information): 

This should work:
```Javascript
this.set('school.name','New School');
```

**Comment by fenerlee1907** [comment]
I've tried this one and it worked, thank you. But I still have a question in my mind. How is it possible to effect DOM by using two different notation while setting a sub-property of a JSON object? Both are giving me the same result when I print them out, but the first one cannot change DOM:
```javascript
this.school.name = "New School";
```
```javascript
this.school["name"] = "New School";
```

**Comment by TimvdLippe** [comment]
Both assignments to a subproperty now work in Polymer 2: http://jsbin.com/nebazadaze/edit?html,console,output
