### ISSUE TITLE
`dom-bind` is not actually ready when `HTMLImportsLoaded` fires.

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer#2396]
When `HTMLImportsLoaded` fires, `dom-bind` is still waiting for the document to become ready and for all possible imports to be loaded before it receives its full API. This causes problems in basic cases like: http://jsbin.com/cudiqo/1/edit?html,js,console,output

Note: even though the item appears, there is an exception in the console.

**Comment by TimvdLippe** [comment]
The exception does not appear any longer in Polymer 2: http://jsbin.com/yiluxihasa/edit?html,console,output
