### ISSUE TITLE
Custom elements defined on the initial page don't work in IE and FF in Polymer 1.1.0

### ISSUE THREAD

**Issue by kevin-wise-infusionsoft** [Polymer/polymer#2398]
If you define a custom element in the root file, i.e. not loaded by HTML imports, the element will work in Chrome, but not in Firefox or IE.  This is despite registering the element after HTMLImportsLoaded. In FF & IE it doesn't even initialize the element.  It works fine in Polymer 1.0.9 but not in 1.1.0 or later.

**Comment by kevin-wise-infusionsoft** [comment]
I took a look at the commits for 1.1.0 and tracked it down to this commit:

https://github.com/Polymer/polymer/commit/051e1bf

If I add lines 90-91 and 95-97 from the old file back in, everything starts working again.  Another developer on my team found that another workaround is to use the full webcomponents.js instead of webcomponents-lite.js.

Of course elements aren't normally defined on the root page other than in demos, but I suspect this also will affect vulcanized sites.

**Comment by arthurevans** [comment]
Interesting -- I didn't think that had *ever* worked on Firefox & IE.

Note here with workaround:

https://www.polymer-project.org/1.0/docs/devguide/registering-elements.html#main-document-definitions

**Comment by kevin-wise-infusionsoft** [comment]
We have HTMLImports.whenReady in our demo pages as noted in that doc.  The HTMLImports workaround used to work, but it doesn't work after 1.0.9.

**Comment by kevin-wise-infusionsoft** [comment]
Hmm, I looked a little closer and it seems we aren't using the exact workaround specified.  We are using `document.addEventListener('HTMLImportsLoaded', callback)` instead of `HTMLImports.whenReady(callback)'.  I'll try changing it and see if that works.

**Comment by kevin-wise-infusionsoft** [comment]
Update: when I replaced `document.addEventListener('HTMLImportsLoaded', callback)` with `HTMLImports.whenReady(callback)` the demo page starts working in FF and IE.  It looks like the vulcanized version of our site still doesn't work in IE unless we use the full webcomponents.js.  But, based on the fact that the vulcanized version does work in FF whereas the demo pages didn't work in either, it seems like the demo page issue and vulcanize issue are not the same issue.  So I'm going to close this issue.
