### ISSUE TITLE
Add support for string concatenation in text bindings

### ISSUE THREAD

**Issue by jevonearth** [Polymer/polymer#2401]
1.0 dropped support for string concatenation in data bindings. A workaround for now is to use [computed bindings][2]. There's hints that string concatenation support will be added back in a future release. Opening this issue so users have something to keep track of.

The data binding section of the [Developer Guide][1] states: 

> String concatenation is not supported inside a tag, and the tag can’t contain any whitespace

  [1]: https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#binding-to-text-content
  [2]: http://stackoverflow.com/a/30541458/1183499

**Comment by timeu** [comment]
If I am not mistaken, there is already an [open ticket](https://github.com/Polymer/polymer/issues/2182):

**Comment by jevonearth** [comment]
Thanks @timeu 

I didn't find that ticket, as I was searching for "concatenation", which is the term used in the dev guide. Closing this ticket.
