### ISSUE TITLE
Question about Selection/Range and shady dom

### ISSUE THREAD

**Issue by eeid26** [Polymer/polymer#2402]
Is Range and Selection is going to be supported or partially supported in shady dom? 
https://developer.mozilla.org/en-US/docs/Web/API/Selection
https://developer.mozilla.org/en-US/docs/Web/API/Range

Some work was done in webcomponents SD before.

**Comment by azakus** [comment]
Based on the difficultly of the implementation for the ShadowDOM polyfill, we will probably not implement this for ShadyDOM.
