### ISSUE TITLE
SVG elements inconsistently get scoped

### ISSUE THREAD

**Issue by ktiedt** [Polymer/polymer#2407]
It appears that there are 2 code paths happening for style scoping... one here: https://github.com/Polymer/polymer/blob/master/src/standard/styling.html#L122 which does not treat SVG consistently due to the possibility that SVG elements can sometimes have .className == an SVGAnimatedString object... this will cause scopeSubtree to "skip" them since className = "new string" will just fail silently.

It seems the fix for #1490 should be expanded to be more generic to encompass all cases where styling my cross path with SVG elements.

Huge thanks to @arthurevans for helping track down why *some* SVG elements worked and others did not and still some did only under certain conditions.

Tagging @sorvell since the related fixes were primarily his work.

**Comment by ktiedt** [comment]
Is there by chance a rough ETA on when this might get fixed? Team lead will be asking for details in our next meeting, hoping to have something I can give them. Thanks!

**Comment by ktiedt** [comment]
Ping? still looking for any feedback here...

**Comment by arthurevans** [comment]
@sorvell @kevinpschaaf @sjmiles It seems like `scopeSubtree` should be using `Polymer.StyleTransformer` rather than going its own way...?

**Comment by azakus** [comment]
Is there a simple test case that I could include for the patch I'm writing?

**Comment by ktiedt** [comment]
A simple D3 chart inside an element would suffice, that is how I came across this problem. I can see about creating a demo if you aren't able to.

**Comment by arthurevans** [comment]
retcon'ing bug title so it'll make more sense in the release notes. Because yes, I care.
