### ISSUE TITLE
Cannot link 3 paths together using `linkPaths`

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#2408]
`linkPaths` allows 2 paths to be associated such that notifications for one are automatically forwarded to the other.

However, the link path notifications stop once one linked path matching the name is found; it should continue such that several aliases for the same path are possible.

**Comment by danimoh** [comment]
Wasn't this solved with release 1.1.4 from 2015/09/25?
I think in the release notes (https://www.polymer-project.org/1.0/docs/release-notes.html) you referenced the wrong issue by a typo ;)

**Comment by kevinpschaaf** [comment]
@danimoh Yes, thank you!  Closing as resolved by https://github.com/MartinMoizard/polymer/commit/54778f2054316a15e7edce046178d8f9f143d59a.

**Comment by supermuka** [comment]
I am with similar problem with Dart Polymer 1.0 (1.0.0-rc.7). How to know if this issues is resolved in Dart Polymer too?

**Comment by zoechi** [comment]
@supermuka The [CHANGELOG.md](https://github.com/dart-lang/polymer_interop/blob/1.0.0-rc.5/CHANGELOG.md) shows that Dart Polymer was updated to Polymer JS 1.2.0 with the 1.0.0-rc.4 version.
