### ISSUE TITLE
{{test(t1, t2)}}

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#2412]
For me it would make more sense to only call the function test if both t1 and t2 are changed.

```js 
this.t1 = 't'
this.t2 = 't' <- now test gets triggert because both t1 and t2 are changed.
```

Wil prevent prevent side effects where one variable is not yet set when test is triggert.

**Comment by miztroh** [comment]
This is something developers will just need to handle on their end.

```
test: function (t1, t2) {
	if (t1 === undefined || t2 === undefined) return;
}
```

**Comment by gertcuykens** [comment]
Stil think it is boilerplate code that can be prevented. Also it gets complex when you have to compare if both are actually changed, not just undefined when the function gets called multiple times.

**Comment by miztroh** [comment]
But it's not possible to change 2 variables at the same time.  Your code  ``this.t1 = 't'; this.t2 = 't';`` would result in ``test`` being called twice.  I'm not sure what (if any) mechanism Polymer offers for getting the previous values within a multiple observer context, but you could manually save the values within the ``test`` function (e.g. ``this._t1 = t1; this._t2 = t2;``).

**Comment by gertcuykens** [comment]
My solution at the moment is never to use two or more function arguments and just merge them into one argument :) But I garantie you there going to be allot of people not thinking about this stuff and assume it only get called once.

What about a more drastic polymer approach and only make the first argument as observable?

**Comment by miztroh** [comment]
That approach would severely limit flexibility for developers.  The current approach gives each developer the flexibility to handle changes however they choose.  I would say that the whole purpose of multiple property observers is to take action when any one of a set of properties changes.  If you want something different than that, perhaps you could set up different observers for each property.

```
t1: {
	type: String,
	observer: '_t1Changed'
},
t2: {
	type: String,
	observer: '_t2Changed'
}
```

**Comment by gertcuykens** [comment]
I Agree, closing it. Thanks
