### ISSUE TITLE
Address shortcomings of `linkPath` feature

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#2414]
- `linkPaths` only deals with forwarding path notifications; if the object at the linked path changes on either side, the expectation should probably be that the object is set to the other linked paths.
- The feature requires that objects at both paths passed to `linkPaths` are the same; it should probably just set them and enforce the requirement

**Comment by danimoh** [comment]
Yep, I also would like to see this implemented please.
Here is a small plunker showing the issue: http://plnkr.co/edit/CVJY08eizxHTJkHeic8q?p=preview

**Comment by 4d4841** [comment]
I'm fiddling around this, not sure if I should override `_setPendingPropertyOrPath` like in this jsbin below (remove XXX from function name to take effect) or if I should observe .* changes and keep the values in synced manually (would appreciate some examples)
http://jsbin.com/xemeroz/edit?html,output
