### ISSUE TITLE
paper-dialog with entry-animation removes focus from autofocus element

### ISSUE THREAD

**Issue by viridium** [Polymer/polymer#2417]
In a `paper-dialog`, I have a `paper-input` with `autofocus`. When the dialog opens, the input is focused. So far so good.

Add an `entry-animation` to the dialog, and the input loses focus as soon as the animation is done.

**Comment by emankovski1** [comment]
+1

**Comment by azakus** [comment]
This issue was moved to PolymerElements/paper-dialog#66
