### ISSUE TITLE
Element with autofocus only gets autofocus the first time the dialog is opened

### ISSUE THREAD

**Issue by viridium** [Polymer/polymer#2418]
In a `paper-dialog`, I have a `paper-input` with `autofocus`. Open the dialog once -- the autofocus works fine. Open the dialog a second time -- the input no longer has focus.

**Comment by quaintcow** [comment]
Happens with me too. calling .focus() doesn't appear to help either.

**Comment by azakus** [comment]
This issue was moved to PolymerElements/paper-dialog#65
