### ISSUE TITLE
deprecated style warning in console please

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#2420]
I just realised the style engine is completely different when looking at the chrome inspector. A warning message should be displayed in the console to indicate a element that stil is using the old style outside template stuff.

**Comment by gertcuykens** [comment]
better yet remove the old style rendering completely to save bytes

**Comment by TimvdLippe** [comment]
Polymer 2 issues a warning when a style is defined outside the template (http://jsbin.com/koruvutoxu/edit?html,console,output) and the linter shows (and fixes) the warning as well (https://github.com/Polymer/polymer-linter/pull/15/files)
