### ISSUE TITLE
Two-way data binding through property-changed does not work for dom-bind

### ISSUE THREAD

**Issue by tomalec** [Polymer/polymer#2421]
I'm not sure whether it's a bug in Polymer, docs, or just my misunderstanding.

I'm trying to make Polymer's two-way data binding work with my native custom elements within auto-binding `dom-bind`.
I follow [the docs](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#change-notification-protocol) which says:
>When using a Polymer element with other elements or frameworks, you can manually attach an on-property-changed listener to an element to be notified of property changes, and take the necessary actions based on the new value.

So I created an element, and attached binding to it:
```html
<my-element notify="{{text}}"></my-element>
```
Then, to follow notification protocol, I attached listeners to `property-changed` event, I have tried attaching them via `addEventListener`, `on-property-changed` attribute, none of those worked.

Property gets changed, but I get no notification, and cannot use it.

Live example: http://jsbin.com/dijequ/edit?html,output

I'm using it within `dom-bind` element, and I cannot use `$=` as I need direct property binding, as in my real case I need to bind to a shared data object, (not a `JSON.stringify`ied clone of it)

How can I make `dom-bind` notify my element on property changes, in the same way it does for Polymer elements?  (without defining by own setter)

**Comment by travellhyne** [comment]
Only Polymer elements releases a `property-changed` event. Since you are creating a vanilla web component, you have to create that event yourself. https://developer.mozilla.org/en/docs/Web/API/CustomEvent

**Comment by tomalec** [comment]
But when should I create it? I thought that  `dom-bind` is changing my
element property, so it is in charge of triggering such event.
8 wrz 2015 07:27 "Neil John Ramal" <notifications@github.com> napisał(a):

**Comment by tomalec** [comment]
AS you can see in here I'm attaching such listener to the annotated element in here http://jsbin.com/dijequ/edit?html,output,
and I have also tried attaching `property-changed` listener to the `dom-bind` itself http://jsbin.com/qubuku/edit?html,output

None of those worked.

**Comment by azakus** [comment]
No, Polymer will just set the property on your element. It is up to your element to notice the property change and fire the event

Here is a working JSBin of your example: http://jsbin.com/zujoju/edit?html,console,output

**Comment by tomalec** [comment]
Thanks :)
