### ISSUE TITLE
Can't apply styles to dynamically created elements in the shady dom.

### ISSUE THREAD

**Issue by notwaldorf** [Polymer/polymer#2426]
This is a contrived example, but it's a simplified version of what `<marked-element>` does in the wild.

```html
<link rel="import" href="../../polymer/polymer.html">
<dom-module id="simple-element">
  <template>
    <style is="custom-style">
      .markdown-html p {
        color: red;
      }
    </style>

    <div class="markdown-html" id="ok"></div>

  </template>

  <script>
    Polymer({
      is: 'simple-element',

      attached: function() {
        this.$.ok.innerHTML = '<p>HAI I AM TRAPPED INSIDE THE WEB</p>';
        // None of these do anything in the shady DOM.
        Polymer.updateStyles();
        this.updateStyles();
      }
    });
  </script>
</dom-module>
```

In the shadow DOM, the `<p>` is red, without any of the `updateStyles()` calls. There is no combination of `updateStyles` incantations I can do do make the `<p>` turn red in the shady DOM.

Halp?

**Comment by notwaldorf** [comment]
Oh! Ignore me! `<marked-element>` is borked and should use `Polymer.dom(this.$.ok).innerHTML = '<p>...</p>` instead. Closing this, but leaving it for posterity. :balloon:

**Comment by frezelth** [comment]
Hi!
It seems that this does not work anymore in Polymer 2.0. Is there another way to do it?
Thanks!

**Comment by TimvdLippe** [comment]
@frezelth Please create a new issue with a JSBin showing what you expected to happen and what actually happened.

**Comment by frezelth** [comment]
My mistake, it works even without the Polymer.dom() call. My style element was not correctly defined, sorry for that.

**Comment by TimvdLippe** [comment]
No problem! Glad it was fixed :smile:
