### ISSUE TITLE
Client Rectangle Not Updated in attached() in Chrome

### ISSUE THREAD

**Issue by yagni** [Polymer/polymer#2430]
clientWidth/clientHeight appear to not be set sometimes within attached() (also happens in ready()). At first I thought it was related to iron-pages, but I was able to create a minimal Plunker that reproduces the problem:

http://plnkr.co/edit/lch33KEQxtEusIrKo79k?p=preview

Note that the advice given [here](https://github.com/Polymer/polymer/issues/1898) seems to work (see commented out parts in above Plunker), but I feel like a wait should be unnecessary for such a simple case.

This only seems to happen on Chrome, not Firefox or IE.

**Comment by azakus** [comment]
Cant reproduce in Polymer 1.2.1. I suspect https://github.com/Polymer/polymer/commit/2bffc4c fixed this for you.

**Comment by azakus** [comment]
JSBin example: http://jsbin.com/kexaho/edit?html,output
