### ISSUE TITLE
https://www.polymer-project.org/1.0/ not work correctly in Safari windows

### ISSUE THREAD

**Issue by phucnguyenhoang** [Polymer/polymer#2431]
Hi team,

I just installed Safari browser in windows 8 and access to https://www.polymer-project.org/1.0/ but the website doesn't work correctly.

**Comment by miztroh** [comment]
Safari on Windows is no longer being developed.  It hasn't been updated in quite some time.  I don't think it's considered a "modern browser".

**Comment by arthurevans** [comment]
Correct, Apple discontinued Safari for Windows after version 5. We support Safari 8+:

https://www.polymer-project.org/1.0/resources/compatibility.html

Given that Windows Safari was last updated in 2012, I would strongly advise against using it for security reasons as well.
