### ISSUE TITLE
dom-repeat items property doesn't update when items change itself

### ISSUE THREAD

**Issue by fxedel** [Polymer/polymer#2433]
I've got a dom-repeating template inside of an autobinding template which adds multiple custom elements:

```html
<template is="dom-bind" id="app">
 
  <template is="dom-repeat" items="{{data}}">

    <custom-element
      name="{{item.name}}"
      value="{{item.value}}">
    </custom-element>

  </template>

</template>
```

The custom element itself has a button which increases the `value` property. The value is displayed correctly inside of the element's dom, but when I use `app.data[index].value`, I always get the old value, so it doesn't update.

My custom element:

```html
<dom-module id="custom-element">

  <template>

    <span class="name">{{name}}</span>
    <span class="value">{{value}}</span>
    <paper-icon-button icon="add" on-tap="{{increase}}"></paper-icon-button>

  </template>

  <script>
    Polymer({
      is: 'custom-element',
      
      properties: {
        name: String,
        value: Number,
      },

      increase: function() {
        this.value++;
      }
    });
  </script>

</dom-module>
```

And running this code in the browser console always returns the same number – it doesn't matter if or how often I've tapped the button of the first custom element in the list:

```JS
console.log(document.querySelector('#app').data[0].value)
```

Am I doing something wrong or is this a bug?

Thanks in advance, Felix

**Comment by JaySunSyn** [comment]
@fxedel try:

    properties: {
        name: String,
        value: {
          type: Number,
          notify: true,
          reflectToAttribute: true
        }
    },

**Comment by fxedel** [comment]
Thanks @JaySunSyn, it worked!

**Comment by JaySunSyn** [comment]
@fxedel great :) Pls close the issue.
