### ISSUE TITLE
Add Support For ES6+ in Polymer Workflow

### ISSUE THREAD

**Issue by karthickszen** [Polymer/polymer#2436]
For a web framework that is 'designed to  leverage the evolving web platform on modern browsers', the lack of support for ES6 is a contradiction in terms.

Is there any way right now for me to reuse ES6 classes and services inside a Polymer element class? Specifically, can we import ES6 classes into a Polymer class, using SystemJS, along the lines of Angular2?  As far as transpilers are concerned, I'm partial to babel, but at this point, I'm open to anything that works.

**Comment by ebidel** [comment]
We have a talk tomorrow at Polymer Summit for ES6 + Polymer :)
https://www.polymer-project.org/summit

Preemptively, here are a couple of resources:
- registration from es6 classes: https://github.com/Polymer/polymer/issues/2329
- babel support - https://github.com/Polymer/polymer/issues/2363
- import module defintion - github.com/PolymerLabs/IMD

Modules are the least baked and not even done at the spec level. The spec needs to define how HTML Imports + ES6 modules will work. They don't have an answer, so it's hard for us to make a recommendation as well. However, check out the Imports module definition that @justinfagnani put together (github.com/PolymerLabs/IMD). It uses HTML Imports to load component code and AMD-style syntax for defining deps.

Closing this as it's not an issue. But feel free to discuss more on the mailing list.
