### ISSUE TITLE
Animation loses proper state

### ISSUE THREAD

**Issue by tjboAtVidao** [Polymer/polymer#2441]
https://elements.polymer-project.org/elements/neon-animation?view=demo:demo/index.html&active=neon-animated-pages

If you spam click this enough, eventually the animation will lose state. It's not a massive problem but seems to get worse when you have other elements on your page... I think I can solve it in our project by a de-throttle or de-bounce, or if there was a function that was like "isAnimationStillRunning()?"... but I consider this a bug within Polymer.

**Comment by azakus** [comment]
This issue was moved to PolymerElements/neon-animation#103
