### ISSUE TITLE
 synthesized mouse events created by touch are focusing the native elements

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#2442]
First I tried something simple but that works as expected http://output.jsbin.com/nepute

So i can only show you a complex example with lots of things going on because I have no idea what is causing the problem.

Note this is only happening on my nexus 7 that is uptodate with the latest android version.

Step 1) 

Open http://gcl-12.appspot.com/ in chrome android

Step 2)

Click the last radio button 
![image](https://cloud.githubusercontent.com/assets/863731/9921565/114c2140-5cdf-11e5-9ced-f0e9dc8f886c.png)

Step 3)

Pic something in the list but the tricky part is you have to aim with something from the previous page

![image](https://cloud.githubusercontent.com/assets/863731/9921583/5788d284-5cdf-11e5-986a-0927c34acda7.png)

Step 4)

You wil notice that it switch pages but also triggers the click event on the changed page element where your finger was located.

![image](https://cloud.githubusercontent.com/assets/863731/9921615/aa7ee0fa-5cdf-11e5-959e-7a29e8862a3f.png)

Which is especially enoying if your finger was pointing to a url.

I hope you can reproduce because it is driving me nuts :)

Note you wil have to try a few times depending on how you tap

PS The ripple effect is also very buggy on my android and the animation get stuck often.

**Comment by azakus** [comment]
This looks like the iron-list is synchronously being shown and hidden.
When the list is hidden, the synthesized mouse events created by the touch are focusing the native elements.

Can you try closing the dialog containing the iron-list asynchronously?

**Comment by gertcuykens** [comment]
I am using `on-selected-item-changed="itemChanged"` ? Is there a other way?

```
            <iron-list id="list" class="flex" items="{{queryChanged(query)}}" on-selected-item-changed="itemChanged" selection-enabled>
                <template>
                    <div class$="[[_computedClass(selected)]]" style="padding:0 20px">
                        <span class="flex">{{item.CL_NOMCLUB}}</span>
                        <span class="flex" style="text-align:right">{{item.CL_CODCLUB}}</span>
                        <span style="text-align:right; width:30px">{{item.CL_CODPAYS}}</span>
                    </div>
                </template>
            </iron-list>
```
```
itemChanged: function() {
                if (this.$.list.selectedItem === null) return;
                this.acp = this.$.list.selectedItem.CL_CODCLUB
                this.club = this.$.list.selectedItem.CL_NOMCLUB
                this.page = 0;
            },
```

**Comment by gertcuykens** [comment]
Aaaaa you mean like this right?
`this.async(function() {this.page = 0;}, null, 1000);`
trying it hold on

**Comment by gertcuykens** [comment]
Yeeeeeej it works :D alelooia

**Comment by gertcuykens** [comment]
Note that I need to set the timeout high enough like 500 or something, where the user can still manage to select a other thing in the list quicly

**Comment by gertcuykens** [comment]
ps do you also know why my ripple animation sucks on android chrome?

**Comment by gertcuykens** [comment]
Wait a minuten I need to do this sync trick for the date picker too. PS you can't expect for developers to apply this sync thing to any ok or cancel button on every overlay right ?
