### ISSUE TITLE
angular-material namespace collating with polymer.

### ISSUE THREAD

**Issue by samio80** [Polymer/polymer#2443]
Is there anyway to scope polymer layouts statements like flex** to use something instead like polymerl-flex so that does not interfere with other layouts engines?

**Comment by samio80** [comment]
I'm gonna ask something maybe silly? but it's not one of the scopes of the web components to isolate styles to avoid conflicts with another web components. I see iron-flex and other components are mixing styles with another frameworks which makes not possible to guarantee delivery of those web components. I realized this problem does not go playing together with angular-material but also with another libraries and the application itself.

**Comment by ebidel** [comment]
It's unfortunately angular-material decide to use the same naming conventions as Polymer. However, not that the layout attributes have moved to classes so `flex` is not `class="flex"`. On their site, it looks like they use attributes so there should be fewer conflicts that before.

Until Shadow DOM is native in browsers, we're stuck with Shady DOM. Unfortunately, it does not have the same style scoping that the native API has.
