### ISSUE TITLE
No error logs on undefined event listener or non-existent element

### ISSUE THREAD

**Issue by Saneyan** [Polymer/polymer#2445]
I'm using Polymer at version (v1.1.2).
Polymer does not output error logs and render custom elements when missing type event listener name or target element. So, it's hard to find the reason why there is no reaction at all.

Here is a example snippet:
```
<dom-module id="user-view">
<template>
  <div>
    <div id="name">...</div>
  </div>
</template>
<script>
// No error logs on undefined event listener or non-existent element.
Polymer({
  is: 'user-view',
  listeners = {
    'tap': 'showInf', // Missing type event listener name
    'nam.tap': 'showName' // or target element ID.
  },
  showInfo: function () {...},
  showName: function () {...}
});
</script>
</dom-module>
```

Could you add the debug feature?
Thanks.

**Comment by birkir** [comment]
Consider using the polylint tool to debug. https://github.com/PolymerLabs/polylint

**Comment by azakus** [comment]
Polymer will alert you if your event listener reference is undefined during the runtime, but we suggest using polylint for linting your code ahead of time.

JSBin of dynamic error printing: http://jsbin.com/fahilo/edit?html,console,output
