### ISSUE TITLE
this.set (deep) property changes not propagating to parent element

### ISSUE THREAD

**Issue by kristfal** [Polymer/polymer#2450]
Hey, having issues propagating an object's sub property changes.

```
Polymer({
is: 'place-detail',
properties: {
  selectedplace: {
    type: Object,
    notify: true,
    reflectToAttribute: true  // testing
  }
},
observers: [
  'placeHandler(selectedplace)'
],
editName: function(newname) {
  if (newname !== this.selectedplace.name) {
    this.debounce('updateDescription', function(){
      this.set('selectedplace.name', newname);
      this.set('selectedplace.dirty', true);
    }, 1000);
  }
}
});
```

Passing a `newname` to the `editName` method updates the `selectedplace` object, and changes are propagated to data bindings watching `{{selectedplace.name}}` in the local DOM as expected.

However, these changes are not propagated to the parent element property, nor any observers watching the object such as `placeHandler`. For observers to fire, deep watching is required:

```
observers: [
  'placeHandler(selectedplace.*)'
]
```

Looking at the polymer docs, deep watching shouldn't be required in this situation, but only for a property such as `selectedplace.name.first`. Is this expected behavior? If so, how do I propagate the change upwards to the parent element's properties?

**Comment by kristfal** [comment]
#2279 Related. Seems not like a bug, but a potential enhancement.

**Comment by jfrazzano** [comment]
We had the same issue. Did the same deep watch and are now playing with a "buffer" with service element cache, and local storage. We also used an iron signal as a work around.  

In our tests we could get the value in a console.log anywhere we wanted and could--I believe--get the value back up in an input but we could not pull it back to the parent without "firing it"/sending it up another level to the parent parent and letting it drop down. 

Good to know the problem was not unique to our work. 

Any ideas on the nuts and bolts of the problem?

**Comment by kristfal** [comment]
@jfrazzano Thanks. Also jumping on the iron signal bandwagon. Wish it wasn't needed.

**Comment by jfrazzano** [comment]
I know. It's a bummer. I wish the curly braces worked everywhere and that we could easily dynamically generate properties.  But the new standards--at least based on the stuff at chromium developers and Mozilla developers--seem to promise a way to do that soonish--at least before my two year old is in first grade. :-).

**Comment by jfrazzano** [comment]
Here is the doc from github on the method we are pursuing--rewriting parts of the attribute changed API--

https://github.com/Polymer/polymer/blob/selectable-array-selector/src/micro/attributes.html

**Comment by devinivy** [comment]
I can't say that I see this as an issue.  #2279 is saying that a change to `x` should notify `x.subProp`.  You're saying a change to `x.subProp` should notify `x`.  It seems clear that we can't have it both ways, and I think #2279 is the pattern that makes the most sense.

Could you possibly do the following,
```js
observers: [
  'placeHandler(selectedplace.*)'
],

placeHandler: function() {
  // Manually notify the path upon any deep change
  this.notifyPath('selectedplace', this.selectedplace);
}
```

**Comment by kristfal** [comment]
@devinivy Not sure if I get your line of thought.

`this.set` is a [convenience method](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#set-path) that also trigger `this.notifyPath`. Both should handle identically in terms of propagation.

Adding the deep observer doesn't propagate changes upwards due to #2279 anyway.

**Comment by devinivy** [comment]
In the example above, the root path is notified manually when any deep change occurs.  Otherwise the root path would not have been notified when a property is changed.

**Comment by azakus** [comment]
This syntax is required if you are trying to observe subproperties of `selectedplace`:

```js
observers: [
  'placeHandler(selectedplace.*)'
],
```

`placeHandler(selectedplace)` will only update if value of the reference that `selectedplace` is pointing to changes.

**Comment by devinivy** [comment]
@azakus would notifying the `selectedplace` path manually (using `notifyPath()`) upon an observed change to `selectedplace.*` achieve what @kristfal is trying to do?

**Comment by azakus** [comment]
That sounds like what #2279 would like to have happen. It doesn't right now.

**Comment by kevinpschaaf** [comment]
Linking this issue to https://github.com/Polymer/polymer/issues/2724, which would potentially solve part of the problem (is a breaking change, however, so likely wouldn't land in short-term).

@devinivy Path notifications are not propagated if the value _at the path_ (ignoring deep sub-properties) did not change, so it would not.  As @azakus mentioned we may investigate a "force deep notification" solution for that use case as part of #2279.
