### ISSUE TITLE
polymer 1.0 patch-dom.htm error 

### ISSUE THREAD

**Issue by emmanuelbuah** [Polymer/polymer#2453]
Uncaught TypeError: Cannot read property '_finishDistribute' of undefined 
FYI - patch-dom is placed after webcomponent-lite.js and before vulcanized imports.

**Comment by arthurevans** [comment]
I think it needs to be placed after polymer.html but before the elements that rely on it. So if you're vulcanizing, you'll probably need to vulcanize so that polymer.html is excluded from the vulcanized bundle.

**Comment by emmanuelbuah** [comment]
@arthurevans Thanks but looks like that introduces layout and event issues in firefox and safari. Below is are my imports for vulcanize. 

```
  <link rel="import" href="polymer/polymer.html">
  <link rel="import" href="patch-dom.html">
  <link rel="import" href="iron-flex-layout/iron-flex-layout.html">
  <link rel="import" href="iron-flex-layout/classes/iron-flex-layout.html">
  <link rel="import" href="iron-flex-layout/classes/iron-shadow-flex-layout.html">
  <link rel="import" href="paper-styles/paper-styles.html">
  <link rel="import" href="paper-button/paper-button.html">
  <link rel="import" href="paper-drawer-panel/paper-drawer-panel.html">
  <link rel="import" href="paper-header-panel/paper-header-panel.html">
```

Per your comment, polymer.html is imported before patch-dom.hmtl, followed by polymer elements. This resolves the "Cannot read property '_finishDistribute' of undefined " error but introduces layout and event issues in firefox and safari.  Here is a link - http://polymerpatchdom.meteor.com to my live demo/sample to demonstrate the issue with firefox and safari after making these changes. The navigation doesn't work and buttons loose their drop shadows. Compared to this live demo with no patch-dome.hmt - polymershadow.meteor.com.

**Comment by arthurevans** [comment]
@emmanuelbuah Do you have the source code available anywhere?

**Comment by emmanuelbuah** [comment]
@arthurevans  Yes. The source code is available at https://github.com/emmanuelbuah/meteorpolymer. Instructions provided in ReadMe file.

**Comment by emmanuelbuah** [comment]
@arthurevans Let me know if you can help resolve this issue. I'd love to clear this webkit(firefox/safari) issue in order to push ahead with my project. I'm currently stuck.

**Comment by emmanuelbuah** [comment]
@arthurevans I just wanted to say thanks for attending to this ticket. I have decide to drop polymer for my service www.huqoo.com because we've been struggling with 1.0 upgrade. This ticket being one of them. You will find more out meteor + polymer community concerns here - https://gitter.im/emmanuelbuah/MeteorPolymer. In any case, I know you guys are busy with other issue. I just wanted to share this. Again, thanks.

**Comment by TimvdLippe** [comment]
patch-dom has since been removed, thus I am closing this issue. Polymer 2 should have fixed a lot of such issues, so hopefully @emmanuelbuah you can try it out and let us know if your experience is improved!
