### ISSUE TITLE
CSS in comments is not ignored by Polymer.

### ISSUE THREAD

**Issue by ktiedt** [Polymer/polymer#2455]
```
      /*paper-submenu::shadow paper-item::shadow iron-icon {
        position: absolute;
        top: 4px;
      }*/
```

Just an example, the above CSS continued to be perpetuated to the element despite comments.

**Comment by JeremybellEU** [comment]
In #2473 a testcase was added to test the reported bug, however CI reports it is working correctly. Additional replication steps would be needed to narrow down a bug, or this issue could be closed via the PR?

**Comment by ktiedt** [comment]
I just tested this and either the problem is fixed or, there was some other underlying cause, but definitely closeable from my perspective.
