### ISSUE TITLE
Custom element environment specification

### ISSUE THREAD

**Issue by wienczny** [Polymer/polymer#2458]
For me custom elements should be like any old dom element. A developer should able to build any currently existing element using custom elements. Some of the old elements require a specific dom structure to fulfill their purpose. Think of ```<ol>``` that contain ```<li>``` as example. For custom elements there currently is no standard way to specify a restriction to the placement of the element. 
Interesting to developers might be :

- What elements are allowed inside my custom element's content
- What elements are allowed arround my custom element
- What elements are allowed to be siblings of my custom elements (Not yet used anywhere)
- As the developer fully controls the custom element's shadow dom there is no need to specify restrictions for elements placed there.

Another dimension would be distance. The restriction could apply to immediate, nested or both elements (Use CSS-Selectors?).
Finally I could imagine cases where the existence or the absence of an element could make a difference to a custom element.

This feature is useful in several stages of development:
- IDEs could pick up the restriction to add element suggestions when writing elements.
- While putting a page together there should be warnings in the browser about elements placed at the wrong location.

I'm not sure whether the restrictions should be enforced in production because of the implications for size and performance.

---
I already talked with some engineer about this at the summit and would like to thank you for this great event.

**Comment by davidrissato** [comment]
I think those restrictions should be addressed by XSD/DTD specs, this way editors could easily read and apply constraints. But I disagree in the part that it should go deep. If you say that your component accepts a <li> tag, the reponsability of checking what <li> accepts inside itself must be addressed by the <li> tag, and not anyone other container tag. This way you prevent a misuse of existing tags and keep things separeted.
By the way, content tag already has a mechanism to filter first level childs.

**Comment by wienczny** [comment]
I'm fine with using XSD/DTD but those documents have to be packed with the custom component to be useful. If you want this there will have to be a standard way to embed it into the custom element definition. The XSD/DTDs of multiple elements will also have to be merged with the default html ones to be useful.
Maybe deep constraints are not useful at all. I just wanted to get a discussion startet.
Are you talking about the 'select'-attribute in your last sentence? It is useful if you have more than one content-element and need to split the provided content up. CSS-Selectors would require to use the ```<div is="custom-element">```-syntax as they don't (yet?) match on inherited custom components.

**Comment by azakus** [comment]
From what I can see, what you're proposing would have to be implemented in the HTML parser to truly decide the placement of elements, and that isn't something Polymer can control.

The CustomElements spec is probably the best venue for your idea: https://github.com/w3c/webcomponents

**Comment by arthurevans** [comment]
One thought: if you're thinking about enforcing on the _authoring_ end, it would be possible to establish a documentation convention for what kind of elements a given custom element accepts as children, such that IDEs and linters could check composition. This would have no effect 

(I'd also point out, though, that the restrictions on what an `<select>` or `<table>` can contain cause all kinds of problems with custom elements; in the end, those hardcoded notions that "X takes only Ys" make the native elements dramatically less useful than if they were stated in terms of interfaces or duck types, like "X takes only elements with a `value` property.")
