### ISSUE TITLE
Element property validation and valid values

### ISSUE THREAD

**Issue by wienczny** [Polymer/polymer#2459]
There should be a way to specify the valid values for an element property and to validate a given value.

Currently you are able to restrict the type of a property. You could use a type of 'String' but it is not possible to restrict the input to values 'one', 'two', 'three'  for example.
On the other side it should be possible to validate the input to an attribute/property and refuse to change it if the value does not match a certain criteria.

Let's have look a iron-selector as example:
If you have html like this (taken from the docs)

```
<iron-selector attr-for-selected="name" selected="foo">
    <div name="foo">Foo</div>
    <div name="bar">Bar</div>
    <div name="zot">Zot</div>
  </iron-selector>
```

and hava a look at the 'selected'-attribute/property. Only 'foo', 'bar' and 'zot' are possible values. To assist developers I would suggest that there is an optional function added to the property definition that returns the currently valid values (the values may change). This function could be accessible by an implicit attribute like 'selected--values'.
Additionally there should be another function that validates the input before it is applied to the data-binding. If you tried to set 'selected' to a value of 'baz' the input should be denied.

**Comment by azakus** [comment]
You can implement this in your element yourself actually with a behavior.

Here's a probably-too-terse examples: [IronValidatableBehavior](https://elements.polymer-project.org/elements/iron-validatable-behavior) and [IronValidatorBehavior](https://elements.polymer-project.org/elements/iron-validator-behavior)

**Comment by wienczny** [comment]
Behaviors are only a partial solution. Every developer will have their own way to implement this. I propose a default way to be able to have tooling around it. If you are using a decent IDE are going to miss code completion for polymer elements ;)

**Comment by azakus** [comment]
Hopefully soon decent IDEs will use some of the tooling that we provide, like [polylint](https://github.com/PolymerLabs/polylint) and that will help quite a bit.

At this stage though, there are other, larger issues that have to be tackled first before "nice to have" features like this can be implemented, especially given the many, possibly-conflicting opinions everyone will have about validation.

**Comment by wienczny** [comment]
You choose the priorities. I just hope to see at least a long term vision. There are still some areas where native elements behave different to custom ones. I want to help close this gap.

**Comment by StokeMasterJack** [comment]
As a point of reference, checkout how powerful and elegant React handles this issue. In React you can declare prop types, just like in Polymer. But it's more useful:

1. You can specify an _enum_ propType (which is what the original issue was requesting). See color property below.

2. You can specify Object type (like in Polymer) but you can also specify the object's _shape_. See the point property below.

3. Also, since React components are just JavaScript functions, you can add your own custom code to validate properties. See example below. Note how this prevents the component from ever entering an invalid state. 

```
function MyComponent({name,point,color}) {
	if(point.x < 0) throw new Error("Invalid value for point.x");
	if(point.y < 0) throw new Error("Invalid value for point.x");
	//render component here
}

MyComponent.propTypes{
	name: React.PropTypes.string.isRequired,
	point: React.PropTypes.shape({
          x: React.PropTypes.number,
          y: React.PropTypes.number
    }).isRequired,
    color: React.PropTypes.oneOf(['Red', 'Green','Blue'])
}
```

**Comment by StokeMasterJack** [comment]
I wrote a blog post comparing property validation in React versus Polymer:

https://medium.com/@daveford/property-validation-in-polymer-and-react-edb446d328fd#.z9f6hp8ud

**Comment by jfrazzano** [comment]
Our other issue is compliance with the same standard that caused the issues above discussed. 

To accord with that standard as an author we must "destroy" an element, including an input, before re-typing it

This is no ones fault. And it certainly is not a polymer or Google issue. These guys fought hard for some logic in the spec and in the underlying 
API standard causing us and the browser venders an issue 

The only way I see to comply with the destroy requirement is to use strings, and self parse by domain;

Then every element or component or whatever is effectively "destroyed" on re-render. 

Its not a bad solution. 
Just a lot of work and sorta sad for the component world, which really is awesome

**Comment by TimvdLippe** [comment]
This is now possible in Polymer 2 with overriding `_setProperty`: http://jsbin.com/foliqiwaga/edit?html,console,output For documentation check out https://www.polymer-project.org/2.0/docs/api/elements/Polymer.Element#method-_setProperty
