### ISSUE TITLE
addFeature boundMethod to polymer standard

### ISSUE THREAD

**Issue by atotic** [Polymer/polymer#2460]
When interacting with javascript libraries, I often create bound methods, and it is always messy. Where do I create a bound method? What do I call it? Do I even bother cacheing it? 

It'd be nice if polymer had a call for creating and cacheing bound methods. I propose

```
/**
 * convenience method for: this_boundMethodName = this[methodName].bind(this);
 * @param {String} methodName -- name of the method to bind
 * @return {Function} -- method bound to this
 */
boundMethod: function(methodName)
```

In my tree, I've counted 16 method bounds in iron, 13 in paper, 17 in google. It complements .listen.

This is the implementation I use in my own projects:

```
Polymer.Base._addFeature({


  boundMethod: function(methodName) {
    if (this.__boundMethods && methodName in this.__boundMethods) {
      return this.__boundMethods[methodName];
    }

    if (!(methodName in this)) {
      this._warn(host._logf('boundMethod', 'bound method `' +
            methodName + '` not defined'));
      return null;
    }

    if (!this.__boundMethods) {
      this.__boundMethods = {};
    }

    this.__boundMethods[methodName] = this[methodName].bind(this);
    return this.__boundMethods[methodName];
  }
});
```

**Comment by nazar-pc** [comment]
Would be nice to have.
Also I have another variation of the same issue.
I have some custom elements with `this` property and custom button.
What I'd like to do is:
```html
<template is="dom-bind">
	<button type="button" is="cs-button" on-tap="[[modal.open]]">Button</button>
	<section is="cs-section-modal" this="{{modal}}">One Two Three</section>
</template>
```
But instead I'm currently forced to largely overcomplicate `cs-button` and write this:
```html
<template is="dom-bind">
	<button type="button" is="cs-button" action="open" bind="[[modal]]">Button</button>
	<section is="cs-section-modal" this="{{modal}}">One Two Three</section>
</template>
```

While most likely we'll want methods to be bound, it is not clear whether we're binding method or just property, so I'd suggest a bit of extended syntax `[[modal~open]]`. This syntax is used in LiveScript and looks good.

**Comment by TimvdLippe** [comment]
You can simply do `this.methodName = this.methodName.bind(this)` to achieve what you want: http://jsbin.com/lixipemano/edit?html,console,output
