### ISSUE TITLE
Property changed notification documentation

### ISSUE THREAD

**Issue by tpluscode** [Polymer/polymer#2461]
Hi. I've found in the [documentation](https://www.polymer-project.org/1.0/docs/devguide/properties.html#notify) that a `propertyName-changed` event should be fired for properties with `notify: true`. However it seems that a `property-name-changed` event is fired instead

**Comment by addyosmani** [comment]
From the docs: `In order to configure camel-case properties of elements using attributes, dash- case should be used in the attribute name.`. I assume we mean this should also be applied to change event names as well, but could be more explicit about it.

**Comment by kevinpschaaf** [comment]
@ tpluscode Thanks for highlighting the inconsistency.

@arthurevans Can we make
> When a property is set to notify: true, an event, propertyName-changed, is fired whenever the property value changes. 

read

> When a property is set to notify: true, an event, property-name-changed, is fired whenever the property value changes. 

instead?

**Comment by MeTaNoV** [comment]
+1 saw it but was too lazy to PR'ed... :)

**Comment by arthurevans** [comment]
Ah, sure. Can you clarify what `property-name-changed` means, though?

Are we saying that the event takes the dash-case version of the name? Or that the literal `name` is added?

**Comment by MeTaNoV** [comment]
I think we are talking about the dashed case version of the name!

**Comment by arthurevans** [comment]
This issue was moved to Polymer/docs#1437
