### ISSUE TITLE
Containerless custom elements

### ISSUE THREAD

**Issue by danielbaak** [Polymer/polymer#2462]
While trying to implement a html table element in polymer, I came across this usecase

```html
<table>
  <thead>
  <tr>
    <th>first</th>
    <th>second</th>
    <th>third</th>
  </tr>
  </thead>
  <tbody>
    <template is="dom-repeat" items="{{entries}}">
      <my-table-row data="{{item}}"></my-table-row>
    </template>
  </tbody>
</table>
```

Since polymer creates the custom element dom inside `<my-table-row>`  the table rows only span the first header column.

Is anyone else coming across use cases for containerless custom elements?

Cheers,
Daniel

**Comment by justincy** [comment]
There is an article about this for version 0.5: https://www.polymer-project.org/0.5/resources/faq.html#option-tr. I don't know if the functionality was ported to 1.0.

**Comment by danielbaak** [comment]
@justincy that feature is no longer necessary in 1.0. 

My issue isn't with not being able to insert <template> tags in tables, that works properly. What I'd like to do is insert self made components instead of <tr></tr>  for modularity.

It's just a nice to have.

In 1.0 the following works, it's just not optimally modular for large `<tr></tr>` contents.

```html
<table>
  <thead>
  <tr>
    <th>first</th>
    <th>second</th>
    <th>third</th>
  </tr>
  </thead>
  <tbody>
    <template is="dom-repeat" items="{{entries}}">
      <tr>
        <td>{{item.attrOne}}</td>
        <td>{{item.attrTwo}}</td>
        <td>{{item.attrThree}}</td>
      </tr>
    </template>
  </tbody>
</table>
```

**Comment by azakus** [comment]
You can extend a table element yourself: `<tr is="my-table-rot">`, but tables are unfortunately very picky about what elements can be in them, and the HTML parser will kick out anything that isn't valid.
