### ISSUE TITLE
CSS adjacent sibling selector inconsistent across Shadey and Shadow DOM

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer#2463]
Consider the following test case...

with ShadowDOM: http://output.jsbin.com/picixu/6?dom=shadow
with ShadeyDOM: http://output.jsbin.com/picixu/6

The problem is that, depending on content projection, the composed tree in ShadeyDOM may cause adjacency selectors not to match in some cases. In this case, an adjacency selector that should match and color some text red fails to match in ShadeyDOM.

/cc @sorvell

**Comment by azakus** [comment]
Eek, I don't think there's a lot we can do here. Since Shadydom has to use the DOM as the composed tree, making sibling selectors work would require building arbitrary "style scopes" that could apply to partial subtrees. That might be tricky to get right.

Up to you @sorvell

**Comment by TimvdLippe** [comment]
This is still an issue: http://jsbin.com/gijaza/edit?html,output Moving it to shadydom instead.

**Comment by TimvdLippe** [comment]
This issue was moved to webcomponents/shadydom#201
