### ISSUE TITLE
async import based on router .. binding not work .. 

### ISSUE THREAD

**Issue by TamerZorba** [Polymer/polymer#2464]
Hello,
i am trying to access data throw 2 elements that i import them asynchronously using dom-if
so my main code is 
```
			
			<template is="dom-if" if="{{equal('course',route)}}">
				<link rel="import" href="course-view/course-view.html">
				<course-view id="course-view" course-data="{{cdata}}"></course-view>
			</template>
			
			<template is="dom-if" if="{{equal('lecture',route)}}">
				<link rel="import" href="lecture-view/lecture-view.html">
				<lecture-view id="lecture-view" course-data="{{cdata}}" ></lecture-view>
			</template>
```

and the property in the first element (course-view) is setted to string and notify true .. 
so when the router is setted to course .. the first element set the courseData value to (hello world) and when the router changed it goes to view the other element (lecture-view) and their is data binding to view the courseData value .. 

when the (import) is outside the dom-if every thing work fine .. but like what i showed up here its not working and not binding any thing .. is theirs a better way to do that or its just a bug ..

by the way i tried to create element for data binding only to share the data outside any dom-if .. and still not work ..

**Comment by azakus** [comment]
HTML Imports added in this way are asynchronous, so the Polymer databinding will fire before the element is upgraded, and the element will not notice that the `corseData` property has been set.

Instead of using a dom-if here, it might be easier to use a hidden attribute. You probably don't want to add and remove imports if the route changes.

```html
<lecture-view id="lecture-view" course-data="{{cdata}}" hidden$="{{equal('lecture', route)}}"></lecture-view>
```

**Comment by azakus** [comment]
Closing due to age, please reopen if this is still an issue.
