### ISSUE TITLE
call super() method for behavior inheritance / overloading

### ISSUE THREAD

**Issue by gronke** [Polymer/polymer#2466]
When using behaviors for element composition/inheritance it would be neat to be able to call `super()` on overloaded methods. I'd expect `super()` to look in the previous inherited behavior for a function with the same name.

```javascript
var SuperBehavior = {
  attached: function() {
    this.doSomething();
  },
  doSomething: function() {
    console.log('foo');
 }
}

Polymer({
  is: 'super-demo',
  behaviors: [SuperBehavior],
  doSomething() {
    super();
    console.log('bar');
  }
});
```

### expected console output
```
foo
bar
```

**Comment by justincy** [comment]
Why can't you just do `SuperBehavior.doSomething()` instead? I think that's why the [docs ](https://www.polymer-project.org/1.0/docs/devguide/behaviors.html#extending) say 

> Naming each element in the behavior array is a good practice, since it allows behaviors to explicitly reference methods on the behaviors they extend (for example, NewBehaviorImpl can call to methods on OldBehavior).

**Comment by gronke** [comment]
@justincy great, sometimes it can be that easy :bulb: Thank you very much!

```javascript
var SuperBehavior = {
  attached: function() {
    this.doSomething();
  },
  doSomething: function() {
    console.log('foo');
 }
}

Polymer({
  is: 'super-demo',
  behaviors: [SuperBehavior],
  doSomething() {
    SuperBehavior.doSomething.apply(arguments);
    console.log('bar');
  }
});
```

**Comment by pik** [comment]
I'd suggest re-opening this - if an element takes on multiple behaviours, especially since some behaviours are actually arrays containing several - it can take lookup time to determine which behaviour to call for the super method. It would make great sense if `super()` just worked, perhaps with es6 classes this will be possible to do for behaviours ?

**Comment by thakurprateek2** [comment]
Instead of apply I suggest use bind
var doSomethingFn = uperBehavior.doSomething.bind(this);
doSomethingFn ();
