### ISSUE TITLE
Leak: the heap keeps increasing after each page refresh

### ISSUE THREAD

**Issue by MartinMoizard** [Polymer/polymer#2468]
I am not sure if this is a Chrome or a Polymer issue, but here is what I observe:
1 - Open https://elements.polymer-project.org/ in Chrome
2 - Open the Dev tools
3 - Take a heap snapshot
4 - Refresh the page (Cmd + R or F5)
5 - Take a heap snapshot

Result: the heap size keeps increasing after each refresh (14.8MB, then 30.6MB then 46.3MB etc.)
What's expected: same heap size after each refresh

Tested on Chrome Version 45.0.2454.99 (64-bit) on Mac OS 10.10.5

**Comment by zoechi** [comment]
Possible dupe of #2452

**Comment by MartinMoizard** [comment]
@zoechi Yes it is, I'll close this one.
