### ISSUE TITLE
Perspective transform on host nodes?

### ISSUE THREAD

**Issue by maxsteenbergen** [Polymer/polymer#2472]
It seems like CSS transforms on :host selectors get ignored, like in this following example -> http://jsbin.com/jibonopowa/edit?html,output 

I'm not sure if it's a limitation, a bug or by design, but I ran into it. Any ideas?

**Comment by azakus** [comment]
Use `display: block`, by default custom elements are `display: inline`

http://jsbin.com/fireli/edit?html,output
