### ISSUE TITLE
:last-child selector broken inside dom-repeat

### ISSUE THREAD

**Issue by robrez** [Polymer/polymer#2475]
I can't get :last-child to work for the last element inside a dom-repeat...

[the codepen](http://codepen.io/robrez/pen/ZbpqXM?editors=100)
[the gh gist](https://gist.github.com/robrez/69a843e2fa8511ba4709)

I think it's because the template itself becomes the last-child...
![domrepeat](https://cloud.githubusercontent.com/assets/1993389/10084613/07b2d430-62ca-11e5-8b6d-c2ed5a778c0f.png)

**Comment by maxsteenbergen** [comment]
You could just try ````:nth-last-child(2)```` instead of ````:last-child````

**Comment by miztroh** [comment]
Or ``:last-of-type``.

**Comment by robrez** [comment]
Thanks for the workarounds. I was trying to turn off border-bottom on the last child... I swapped border-bottom for border-top and last-child for first-child.

Still seams like the last-child selector should work.

I'll close the issue if the polymer team doesn't consider it a bug.

**Comment by miztroh** [comment]
``:last-child`` won't work because the last child is the ``dom-repeat`` template.

**Comment by nazar-pc** [comment]
+1 @miztroh, it shouldn't work this way, `<template>` is really last child, nothing wrong here.

**Comment by azakus** [comment]
Yes, `:last-child` refers to the element that is the last child of it's parent element, so `<template is="dom-repeat">` would be the last child. https://developer.mozilla.org/en-US/docs/Web/CSS/%3Alast-child

**Comment by lcassiano1612** [comment]
You can user this:

.row:nth-last-child(2)
