### ISSUE TITLE
Investigate why CI is failing

### ISSUE THREAD

**Issue by samccone** [Polymer/polymer#2476]
CI is currently failing on both ie10 and ie11. Due to the current failure on HEAD all incoming PRs are marked as red whether or not they added any new regressions. The red state adds additional burden on maintainers to go an manually diff the test logs to see if any new regressions were added. It also makes it much harder / impossible for contributors to know if their patch caused regressions.

Getting CI into a stable green state would ideally allow for more contributions from others, as well as allow for faster iteration within polymer core.

Let me know what you think, Thanks :sparkles:

**Comment by JeremybellEU** [comment]
Yes completely agree. When I created my PR and saw the CI failure I was confused, but apparently it was failing on other tests.

**Comment by kevinpschaaf** [comment]
Solved, per https://github.com/Polymer/polymer/issues/2582.  All tests are green, and we've switched from our internally-managed CI server to Travis as well.

**Comment by samccone** [comment]
A+ work @kevinpschaaf
