### ISSUE TITLE
Dynamically added elements don't get data-binded

### ISSUE THREAD

**Issue by avdaredevil** [Polymer/polymer#2477]
I have a dashboard form of an app that is fully written in Polymer, however when I AJAX fetch a sub page within the app, I create elements that need to be binded in relation to the app, I was able to get around this problem by nesting dom-binds [which allowed for a second scope]
To get the parent template values binded I also make \<ap-listener property="[[narrow]]" bind-to="#s" as="narrow"\> in the parent template.

However these only work if the listeners were already in my main app file and not created after the AJAX call.

So Polymer has an issue with not being able to create data-binding with elements created dynamically.

**Comment by zoechi** [comment]
Can you please add some more code? How do you add the element?

**Comment by zerodevx** [comment]
Polymer 1.0+ does not support imperative data-binding. Because bindings are baked during element **registration** time. Only exception of late-bind is in a `<template is="dom-bind">` instance. You might find this https://github.com/Polymer/polymer/issues/2131 and this https://github.com/Polymer/polymer/issues/1778 useful.

**Comment by avdaredevil** [comment]
Is there a way to expose the polymer API, so that the same logic can be applied to a custom element. This way polymer can still act as a usable front end framework?

**Comment by ebidel** [comment]
#1778 is for exposing that API. Please use declarative bindings for now.
That's the recommend approach anyways.

**Comment by 4dinterface** [comment]
Unable to write the generators forms.

**Comment by syntax42** [comment]
I must say that i think this is the biggest limitation i have found in Polymer: Not being able to databind to dynamically created elements. For a one page webapp, like the one i am currently developing, there is simply no way to know from page load, what or how many elements is needed in the entire life time of the session. :-(

**Comment by AliMD** [comment]
I hope this code useful: https://github.com/Polymer/polymer/issues/1778#issuecomment-240698278
