### ISSUE TITLE
All Documentation on Polymer Website is hidden

### ISSUE THREAD

**Issue by ethancalvo** [Polymer/polymer#2478]
it appears all the marked-elements with a class of iron-doc-viewer have the hidden class applied to the content node.

This is making dev a bit more time-consuming.

**Comment by samccone** [comment]
Hi @ethancalvo thanks for the feedback, I have filed in issue in the marked element repo
https://github.com/PolymerElements/marked-element/issues/15

Since this is most likely a question around that element and not polymer core.

**Comment by ebidel** [comment]
This issue was moved to Polymer/marked-element#11
