### ISSUE TITLE
setting innerHTML does not create custom elements correctly in IE/Mozilla... maybe others

### ISSUE THREAD

**Issue by MKuenzi** [Polymer/polymer#2479]
I'm not sure if this is a bug or just a limitation but I wanted to get any information I could about this.

If I have the following code:

```javascript
var myDiv = document.createElement("div");
myDiv.innerHTML = "<div><my-control></my-control></div>";
```

I notice the behavior is different when comparing Chome to IE/Mozilla.  In Chrome the element gets created fine and ends up with the template inserted and everything working great.

In IE/Mozilla I am left with a dud element. I understand your documentation says you must create elements through document.createElement() or the constructor.  I was curious if this is supposed to be supported or if there is a workaround for this sort of scenario of loading HTML dynamically like this.

Thanks in advance!
Mike

**Comment by ebidel** [comment]
Yes this should work, even under the polyfill. @sorvell @kevinpschaaf @sjmiles

**Comment by kevinpschaaf** [comment]
The CustomElements polyfill can only upgrade Custom Elements that have been attached to the document (since it relies on a MutationObserver on document to find them).  If you create a detached node and innerHTML content containing Custom Elements, the document's MutationObserver will not see them yet, hence they will only be upgraded when attached.  This is a limitation of the polyfill.

See below, the inserted `my-control` will only be upgraded once its container is appended to the document.
http://jsbin.com/mirituyetu/edit?html,console,output

**Comment by ebidel** [comment]
@kevinpschaaf @arthurevans is this documented anywhere? I may have known this at one point, but have since forgotten. Would be good to document it.

**Comment by kevinpschaaf** [comment]
Not sure, maybe we should add doc that lists polyfill limitations/differences if we don't have something like that already...

**Comment by arthurevans** [comment]
We do not have it. I think we had a few notes on shadow DOM on the old site.
And there are polyfill notes on webcomponents.io. Those notes used to be on the Polymer site. Some of those may be relevant. I think we should come up with a list, provide a summary of polyfill limitations on p-p.org, and also make sure individual limitations are noted on webcomponents.io.

In this case, is it true that the element _will_ be upgraded if you  use `document.createElement` or the constructor, and the issue only occurs if the parser creates but does not attach the docs -- for example, using `innerHTML`, cloning a template's contents manually, or copying contents from a `<link rel="import">`?

**Comment by ebidel** [comment]
Let's  start a doc!

**Comment by Pupix** [comment]
I am running into a similar problem on Firefox/EDGE (it works on Chrome). If I do `innerHTML` on an element with a `slot`, whatever tags I passed into the `innerHTML` don't get upgraded. [Example](http://jsbin.com/podovizoji/1/edit?html,console,output)

Is there a workaround for this?
