### ISSUE TITLE
custom-style: using async import fails to shim styles

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#2481]
Using paper-styles.html (where polymer.html is a sub-import) fails to apply the styling - http://jsbin.com/fujiqixaki/edit?html,output:

```
<link rel="import" href="https://polygit.org/polymer/components/paper-styles/color.html" async>
<style is="custom-style">
  body {
    background: var(--paper-green-500);
  }
</style>
```

Interestingly, using an async polymer.html on the main page WORKS - http://jsbin.com/tuxajomelo/edit?html,output:

```
<link rel="import" href="https://polygit.org/polymer/components/polymer/polymer.html" async>
<style is="custom-style">
  :root {
    --paper-green-500: green;
  }
  body {
    background: var(--paper-green-500);
  }
</style>
```

**Comment by ebidel** [comment]
@sorvell wanted to verify these two upgrades happen for sync and non-async:

**non-async** case
1. color.html
2. loads polymer.html
3. upgrades custom-style in color.html
4. upgrades custom-style in main document

**async** case
1. async color.html
2. loads polymer 
3. upgrades custom-style in main document*
4. upgrades custom-style in color.html

Results: In both cases, 3 and 4 are upgraded. Repo:

```<script>
function logStuff(importDoc) {
  var importStyle = importDoc.import.querySelector('style');
  console.log('custom-style upgraded in color.html import:',
              importStyle.__isPolymerInstance__);

  var mainDocStyle = document.querySelector('style');
  console.log('custom-style upgraded in main doc:',
              mainDocStyle.__isPolymerInstance__);
}
</script>

<link rel="import" href="https://polygit.org/polymer/components/paper-styles/color.html"
      async onload="logStuff(this)">

<style is="custom-style">
  body {
    background: var(--paper-green-500);
    color: white;
  }
</style>

<p>Background should be green.</p>
```

Drop this in a page and toggle the `async` attr. Sync will show a green page. async will not.

**Comment by ebidel** [comment]
With `async`, the custom-style upgrades are main doc, then import. Without it, the order is import, then main doc.

**Comment by jmcgdz** [comment]
@ebidel 

I am upgrading to 1.1.3 and seeing a similar issue with elements that are created after ready(), 
like select2 selects after data is returned from an ajax call.

Does that sound like the same issue?

Also, is there a programmatic way to reapply the styles?

**Comment by ebidel** [comment]
Sounds different. This is about async imports. I doubt they're using them.

select2 might not be using `Polymer.dom()`? For that kind of 3rd party that doesn't use Polymer's stuff, you can use `scopeSubtree`:  https://github.com/Polymer/polymer/issues/2299

**Comment by jmcgdz** [comment]
@ebidel Yep, that's the one. Confirmed. Thanks for the workaround

**Comment by ebidel** [comment]
Related: https://github.com/Polymer/polymer/issues/2522#issuecomment-155625966

**Comment by valdrinkoshi** [comment]
Also this one seems related: https://github.com/PolymerElements/iron-overlay-behavior/issues/23

**Comment by rodrigogoncalves** [comment]
> Also, is there a programmatic way to reapply the styles?

**Comment by 2pha** [comment]
I came across this issue today when trying to add a splash screen following the [polymer starter kit performance docs](https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/polymer-perf.md)

**Comment by TimvdLippe** [comment]
I am closing this issue as it suffers from the same root problem described in #2522. Please see https://github.com/Polymer/polymer/issues/2522#issuecomment-347171067 and https://github.com/Polymer/polymer/issues/2522#issuecomment-363562974 for more information.
