### ISSUE TITLE
CSS parser: incorrectly handing polybuild output

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#2483]
When Polybuild crushes element CSS and removes whitespace, custom property rules end up running into each other. Unfortunately, this causes our parser's regexing to start ignore rules. The issue can be seen when you have two `--var` in a row (one won't do it).

    top: 400px;--paper-fab-background: var(--paper-green-500);--paper-fab-keyboard-focus-background: var(--paper-green-700);

putting as space in between properties works:

    top: 400px; --paper-fab-background: var(--paper-green-500); --paper-fab-keyboard-focus-background: var(--paper-green-700);

http://jsbin.com/wayoholaxi/edit?html,output - you'll see `top: 400px` is ignored

cc @azakus

**Comment by ebidel** [comment]
@sorvell @azakus wdyt? This blocks usage of polybuild. I'd really like us to start recommending that as a one-stop-shop tool.

**Comment by Nick-Ewer** [comment]
Any solution for this? We're using polybuild and I'm having issues when doing the same thing.

**Comment by JeremybellEU** [comment]
Just stumbled on this issue. #2662 has been merged which touches the variable issue. @ebidel can you confirm/deny it is fixed now? Else I can take a look again on how to fix the regex.

**Comment by azakus** [comment]
@JeremybellEU No worries. PRs don't run in Safari or IE because we run those on SauceLabs and keep the credentials encrypted. Travis only decrypts the credentials when the PR or branch is on the same origin.

**Comment by azakus** [comment]
Most of the time, that should be enough. Styles are annoying though...

**Comment by azakus** [comment]
Ugh, looks like this line https://github.com/Polymer/polymer/blob/master/test/unit/custom-style.html#L258 became `top: 12px;;` in Safari

**Comment by JeremybellEU** [comment]
Hm, could you maybe escape the `{` and similar characters in the regex and try again? So:
`/(?:^[^;\-\s\}]+)?--[^;\{]*?:[^\{\};]*?(?:[;\n]|$)/gim`. Seems really weird if Safari would parse this differently.

**Comment by azakus** [comment]
Nope, that doesn't work.
I've tried rebasing this patch against 1.2.3 to see if anything else that was merged could be a problem, but it looks isolated to this commit.

**Comment by JeremybellEU** [comment]
Urgh, maybe it is best to revert the PR for now and someone with Safari can investigate the issue. I can only guess at this point, since Safari can not be installed on Linux...
