### ISSUE TITLE
 http://polymer.github.io/polymer/ out of date

### ISSUE THREAD

**Issue by marcus7777** [Polymer/polymer#2488]
I was using http://polymer.github.io/polymer/ for ref it out of date compair with http://open-elements.org/bower_components/polymer/

**Comment by marcus7777** [comment]
update bower on gh-pages??

**Comment by ebidel** [comment]
@garlicnation @azakus  who and how do we maintain this? Can it somehow be automated for each polymer release?

**Comment by TimvdLippe** [comment]
The github pages can probably be removed/disabled, as we now have https://www.polymer-project.org/2.0/docs/devguide/feature-overview

**Comment by marcus7777** [comment]
Has an easily distracted person it's easy to look up API on:
https://dev.open-elements.org/bower_components/polymer/#Polymer.Base

**Comment by TimvdLippe** [comment]
polymer.github.io has been disabled in favor of polymer-project.org

@marcus7777 The full official documentation is available at https://www.polymer-project.org/2.0/docs/api/

**Comment by marcus7777** [comment]
okay :)
