### ISSUE TITLE
calling `set` with array index notifies wrong path to observers

### ISSUE THREAD

**Issue by jakemac53** [Polymer/polymer#2490]
http://plnkr.co/edit/3pPwKUF1eHubaiBcZdRR?p=preview

If you open up the console you will see the following messages:

```
path:  myArray.2.value
new value:  undefined
path:  myArray.1.value
new value:  6
```

These should look the same (other than the first new value being 4). The path which was passed after the call to `set` is the wrong path, where the path passed after the call to `notifyPath` is correct. 

What is actually happening here is the `key` from the Polymer Collection object is leaking out to the public api.... (the Polymer Collection key for the index `1` is `2`).

**Comment by tomalec** [comment]
Seems to be related to https://github.com/Polymer/polymer/issues/2248 and https://github.com/Polymer/polymer/issues/2007#issuecomment-119305600

**Comment by dam0vm3nt** [comment]
@jakemac53 I think that the proposed solution is not the right for your use case. You need actual indexes to be able to update the dart side correctly, or am I wrong?

**Comment by jakemac53** [comment]
@dam0vm3nt The only case where this breaks down is if the notified path ends in a key, then I have to do an O(n) lookup to find the index for the item at that key.

**Comment by dam0vm3nt** [comment]
Mmh, will (the o(n) look up) work even if items are int?

Il giorno mer 30 set 2015 21:27 Jacob MacDonald <notifications@github.com>
ha scritto:

**Comment by jakemac53** [comment]
Duplicate items are actually not allowed, and will break in other ways :(

**Comment by dam0vm3nt** [comment]
Ack.

2015-09-30 23:31 GMT+02:00 Jacob MacDonald <notifications@github.com>:

**Comment by jakemac53** [comment]
Ya I can't find the issue right now but there is one, and there is an experimental workaround. I think basically they just wrap values in an object so they aren't identical any longer...

**Comment by jakemac53** [comment]
This is resolved now as far as I know, key paths are indicated with a `#`.

**Comment by dam0vm3nt** [comment]
yep, confirmed. Tnx.
