### ISSUE TITLE
`inst.__setProperty is not a function` when splicing under some conditions

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer#2491]
Please consider the following simplified test case: http://jsbin.com/zetiyu/3/edit?html,js

When splicing data under certain conditions, it's possible for a `splice` to cause the data binding system to attempt to set a property on a `TemplateInstance` (https://github.com/Polymer/polymer/blob/0f8483da48dc3747f3c4bdd439b95c4bce2897d7/src/lib/template/dom-repeat.html#L613-L620) within a period of stasis where said instance has been swapped out for a placeholder value in the relevant `template is="dom-repeat"` (relevant line that originates error here: https://github.com/Polymer/polymer/blob/0f8483da48dc3747f3c4bdd439b95c4bce2897d7/src/lib/template/dom-repeat.html#L535).

It's not obvious to me why this particular arrangement (as shown in the test case) causes the problem to manifest. However, it was easy enough to hit in the wild in a sample application I wrote that involved nested `template is="dom-repeat"` paired with `firebase-collection` instances.

**Comment by cdata** [comment]
Just want to give a bump to this. It's very easy for me to hit it from various `firebase-collection` related databinding scenarios.

**Comment by cdata** [comment]
I have made a further-simplified test case. The exception is different, but I believe it is related to the same problem. Properties are assigned at an inopportune time, which is to say a time when the objects whose properties are being assigned have been swapped out by placeholders.

Please find the simplified test case here: http://jsbin.com/cobere/4/edit?html,js

**Comment by cdata** [comment]
Spoke with @kevinpschaaf . The fundamental problem appears to be re-entrance into the array change notification system when `firebase-collection` (or whoever) causes a splice-within-a-splice scenario to occur. I am investigating an alternative to `firebase-collection`'s implementation to see if we can work around this.

The original test case demonstrates that it is possible to hit an undefined condition in the databinding system using idiomatic Polymer data-binding primitives. So, I'm leaving the issue open.

**Comment by azakus** [comment]
@cdata Is this still an issue?

**Comment by cdata** [comment]
It is still an issue, as so-called re-entrance is not supported by the data-binding system. My understanding of this issue is that it is a known short-coming and that my expectations fall into the category of "not (yet) supported."

### What I expect
I expect to be able to cause `splice` changes safely from within a function that happens to be called in the same synchronous call-stack after a handler of some other `splice` to the same object (or an object that affects / is-affected-by it through data-binding arrangements).

### What we have today
If I cause a `splice` within the call-stack of another `splice` handler to the same (or related) object, it is considered a re-entrant call and subject to undefined and / or exception-throwing side-effects.

I suggest that this issue should remain open for documentation purposes and labelled as `enhancement`. However, I'm happy for the issue to be closed if it's just noise for others or if there is a dupe.

**Comment by TimvdLippe** [comment]
Both JSBins seem to be working now with Polymer 2: http://jsbin.com/luqeqezato/edit?html,js,console,output and http://jsbin.com/mipixosicu/edit?html,js,console,output
