### ISSUE TITLE
Expose Polymer(dom).outerHTML

### ISSUE THREAD

**Issue by kaste** [Polymer/polymer#2492]
It seems like you already implemented outerHTML https://github.com/Polymer/polymer/blob/3b0d10b4da804703d493da7bd0b5c22fc6f7b173/src/lib/dom-innerHTML.html#L85

Can we have it?

**Comment by mrft** [comment]
+1

**Comment by TimvdLippe** [comment]
Closing as the Dom API is on the legacy element in Polymer 2.
