### ISSUE TITLE
Custom property classes overriding

### ISSUE THREAD

**Issue by tenhobi** [Polymer/polymer#2494]
I have element like the bellow, where I set padding-left using custom property on observer event.

1) 

``` html
<dom-module id="alfa-beta">
    <style>
        :host .block {
            padding-left: var(--block-padding);
        }
    </style>

    <template>
        <span class="block>xxx</span>
        <div class="content" hidden$="{{!open}}">
            <content></content>
       </div>
    </template>

    <script>
        Polymer({
            is: "alfa-beta",
            properties: {
                // Level of element deep.
                level: {
                    type: Number,
                    value: 0,
                    observer: '_levelChanged'
                },
                ...
            },

            _levelChanged: function (newValue) {
                if (!this.add) {
                    this.customStyle['--block-padding'] = ((newValue == 0) ? 29 : (newValue == 1) ? 33 : 33 + (newValue - 1) * 18) + "px";
                    this.updateStyles();
                }
            },
            ...
        });
    </script>
</dom-module>
```

And I use it like this: (classes are used after page load - from example 3)

2)

``` html
<alfa-beta></alfa-beta>
<alfa-beta></alfa-beta>
<alfa-beta level="0" class="alfa-beta-0"> 
    <alfa-beta level="1" class="alfa-beta-1"></alfa-beta>
    <alfa-beta level="1" class="alfa-beta-1"></alfa-beta>
    <alfa-beta level="1" class="alfa-beta-1"></alfa-beta>
</alfa-beta>
```

After page load, each element is like with level="0", because it load each style for the custom property like this: (and it should be from 0 to 1 to work correctly)

3)

``` html
<style scope="alfa-beta"></style>
<style scope="alfa-beta-1"></style>
<style scope="alfa-beta-0"></style>
```

And it (alfa-beta-0) overrides all rules before (alfa-beta-*). I had fixed it using:

4)

```
:host > .block {
    padding-left: var(--block-padding);
}
```

**I think it is an issue with custom property classes overriding.** (Element has unwanted styles from parent element)

**Comment by azakus** [comment]
This seems like a known limitation of the CSS Custom Variables shim:
> Within a given element’s local DOM scope, a custom property can only have a single value. 
https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-properties-shim---limitations-and-api-details

**Comment by HoBi** [comment]
@azakus I do not think so this is some big issue. Just instead of creating scope styles this way:

```
<style scope="alfa-beta"></style>
<style scope="alfa-beta-3"></style>
<style scope="alfa-beta-2"></style>
<style scope="alfa-beta-1"></style>
<style scope="alfa-beta-0"></style>
```

It should be like this and there will be no problem. So make it conversely.

```
<style scope="alfa-beta"></style>
<style scope="alfa-beta-0"></style>
<style scope="alfa-beta-1"></style>
<style scope="alfa-beta-2"></style>
<style scope="alfa-beta-3"></style>
```

**Comment by azakus** [comment]
This is a limitation of the Custom Properties shim. For efficiency, descendant selectors are used as a scoping mechanism, and this is problematic when nesting elements in themselves.
We will not fix this for the 1.x line.

In the future, we may decide to provide a more strict, and slower, scoping mechanism if this case proves to be important.

**Comment by TimvdLippe** [comment]
Closing per above comment.
