### ISSUE TITLE
`dom-repeat` in vanilla template does not stamp

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer#2495]
Please consider this simplified test case: http://jsbin.com/budeqi/2

When stamping a vanilla template containing a `dom-repeat`, Safari 8 (and I suspect Safari 7 + all IE, although I have not confirmed this) does not stamp a nested `dom-repeat`.

This is particularly problematic for `test-fixture`, which is supposed to be able to stamp arbitrary DOM from vanilla templates.

**Comment by azakus** [comment]
This looks working to me.

**Comment by tomalec** [comment]
+1 it does not work for me neither in IE11.0.9600.18125 nor Edge 20.10240.16384.0

Same goes for `dom-bind`

**Comment by azakus** [comment]
Should be fixed with https://github.com/webcomponents/webcomponentsjs/pull/489

**Comment by TimvdLippe** [comment]
Yup this is working now: http://jsbin.com/juviyikuxu/edit?html,output

**Comment by tomalec** [comment]
`dom-bind` stamped from template, works as well http://jsbin.com/lekuvekora/edit?html,js,output
