### ISSUE TITLE
Dynamic content and styles on 1.1.3

### ISSUE THREAD

**Issue by jmcgdz** [Polymer/polymer#2496]
Still working on an upgrade and just cannot get this to work ...

I have an element that I need to allow dynamic content and external styles set on that content.

So the model is like:

```
{
    html: '<div>text</div>',
    css: 'div { color: blue; } body { background: yellow; }'
}
```

In previous versions of polymer, at least .5 and .8 this was possible, but I thought it was working in 1.0 also. However, it is breaking now and I need a work around.

This was my best shot, but the styles were not applied on the 'div', however the body was yellow:
(ya there is some jquery in there)

```
, _modelChanged: function(n) { 
    this._injectModelHTML();
    this._setStylesOnDynamicContent();
}

, _setStylesOnDynamicContent: function(n) {

    // Scope dynamic content first
    var innerContent = $(this).find('.inner-content').first().get(0);
    this.scopeSubtree(innerContent, true);

    // Now add our styles to the style doc
    this._injectStyleTag();

    // ???
    // Polymer.Base._prepStyles();

    // Now update styles
    this.updateStyles();
}

, _injectModelHTML: function() {
    this.$.content.innerHTML = this.model.html;
}

, _injectStyleTag: function() {
    $(this).append('<style id="model-styles" is="custom-style">'+this.model.css+'</style>');
}
```

Does anyone know of a way to add dynamic css then apply it to dynamic content?

**Comment by justjico** [comment]
+1

**Comment by jmcgdz** [comment]
Ok, guys, I needed to solve this so this was my solution for anybody else who needs to do something like this.

I made a behavior with these mehtods:

```javascript
// Copied from a closure inside scopeSubtree() here:
// https://github.com/Polymer/polymer/blob/master/src/standard/styling.html#L120

_scopify: function(node, nodeName) { var self = this;
    // node.className = self._scopeElementClass(node, nodeName);
    var n$ = node.querySelectorAll('*');
    Array.prototype.forEach.call(n$, function(n) {
        if(n.nodeName==='TEMPLATE'){
            return;
        }
        this._addElementStyle(n, nodeName);
        // n.className = self._scopeElementClass(n, nodeName);
    }.bind(this));
}



// Mostly from here: https://github.com/Polymer/polymer/blob/master/src/lib/style-transformer.html#L73

, _addElementStyle: function(element, scope) { var self = this;
    // note: svg on IE does not have classList so fallback to class
    if (element.classList) {
      element.classList.add(scope);
    } else if (element.getAttribute) {
      element.setAttribute('class', c + (c ? ' ' : '') + ' ' + scope);
    }
}



// https://github.com/Polymer/polymer/blob/master/src/lib/style-transformer.html#L114

, _prepareModelCss: function(styleText, scope) { var self = this;
    return Polymer.StyleTransformer.css(styleText, scope);
}
```




Most of that code is from polymer, but I could not reuse the pieces I needed, so I made that small behavior.

So basically this is the sequence to achieve the goal:

1. The element loads and has a model property (like a Backbone model object JSON)

2. The model.html gets injected into the element's content

3. Scope the element with model.id ```self._scopify(this, 'guid-'+self.model.guid);```

4. Then scope and add the model.css (note not custom-style):

```javascript
var prepped = self._prepareModelCss(self.model.css, 'guid-'+self.model.guid);
$(self).append('<style id="widget-model-styles">'+prepped+'</style>');
```

Now all of the model.css rules are applied to element and safely scoped.

If there is a better way to do this with Polymer itself as is, I could not find it.

**Comment by TimvdLippe** [comment]
Ref: https://github.com/Polymer/polymer/pull/3362#issuecomment-179567407

**Comment by TimvdLippe** [comment]
Closing this per above comment. For CSS you can use CSS variables, for HTML you can write the logic yourself. Since it would be unsafe to directly assign (see discussion in #3362) we are not allowing this feature.
