### ISSUE TITLE
dom-repeat doesn't reflect the changes on the property

### ISSUE THREAD

**Issue by elegos** [Polymer/polymer#2498]
Hello!

I'm trying to figure out how the dom-repeat feature works. I'm currently playing with the starter kit (full version) and I'm tinkering around the "my-list" element.

When I update the "items" property (type: Array, notify: true), I expect the dom-repeat template to read the change and refresh the view. Evidently the property is not being observed, and as such the expected behavior doesn't exist.

This is what I'm doing right now:

    document.querySelector('my-list').items.push('Whatever')

From the documentation:

> Mutations to the items array itself (push, pop, splice, shift, unshift) must be performed using methods provided on Polymer elements, such that the changes are observable to any elements bound to the same array in the tree.

So I've created two custom functions inside the Polymer my-list definition, as follow:

          pushItem: function (element) {
              this.items.push(element);
          },
          
          deleteItem: function (element) {
              if (typeof element === 'string') {
                  var i = 0;
                  for (i = 0; i < items.length; i++) {
                      if (items[i] === element) {
                          break;
                      }
                  }
                  if (i != items.length) {
                      this.items.slice(i, 1);
                  }
              }
              else if (typeof element === 'number' && element > -1) {
                  this.items.slice(element, 1);
              }
          }

Unfortunately even using this approach it seems that the value is not being observed by the template dom-repeat.

**Expected behavior**: to make the list change with the new content
**Observed behavior**: the element's `items` attribute is being altered, but no graphical change.

**Tests made on browser**: Iceweasel 38.3.0 (Debian 8 Jessie)

Even if this may not be a proper bug, how can I make the attributes observable from the template's dom-repeat point of view?

Thanks

EDIT: further reading lead me to "discover" this.push('property', element). Where can I find the list of polymer-defined functions? For instance I tried with this.slice('property', index, num), but "this.slice" is not defined.

Thanks

**Comment by samccone** [comment]
the list of "smart" array mutation methods can be found here https://www.polymer-project.org/1.0/docs/devguide/properties.html#array-observation

This confused me as well initially, +1 to thinking how we can elevate this info better :space_invader:

**Comment by elegos** [comment]
Thank you samccone for the hint!

Wouldn't it be possible, somehow, to not directly expose the properties, but objects that interactwith them "transparently"? So for example element.myArray.push will internally call this.push('myArray', theObject)?

I know this would mean changing how it's designed right now... and would let any property to be observable (not a good idea indeed)... maybe a property's property? (sorry for the word joke)... something like "objectTranslate: (bool)" or similar, if set to true my logic kicks in...

**Comment by azakus** [comment]
I don't think we want to be in the business of modifying Array prototypes to make the data binding system slightly more convenient. That's a good way to get *weird* bugs.
