### ISSUE TITLE
Various micro optimizations

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#2502]
I was investigating potential bottlenecks and some possibilities for optimizations and prepared PR for that #2368.
Main changes:
* use `while` instead of `.slice()` to copy array
* `Array.isArray(..)` replaced by `.. instanceof Array`
* `this.items` cached into local variable in order to avoid repeated getter calls
* also check added in one place to avoid `Array` being treated as `Object`, which in that case might make difference

**Comment by azakus** [comment]
Please see https://github.com/Polymer/polymer/pull/2368#issuecomment-176491515
