### ISSUE TITLE
Improve notifyPath/notifySplices API for public usage

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#2509]
The current path notification API has a couple of warts making it problematic for use by data adapter layers providing alternate forms of data observation:

* `notifyPath` accepts only collection keys for arrays (as opposed to array indicies as `set` does).  With the changes to resolve https://github.com/Polymer/polymer/issues/2007, `set` will accept either keys or indicies, and the public version of `notifyPath` should do so as well; this will likely involve refactoring internal usage of `notifyPath` to avoid the overhead of key/index disambiguation when it is known that the path is key-based
* `_notifySplices` is currently private and undocumented; for a fully operable data observation layer, this needs to be exposed publicly

**Comment by kevinpschaaf** [comment]
PR here: https://github.com/Polymer/polymer/pull/2513

**Comment by devinivy** [comment]
@kevinpschaaf I think the docs may need some adjustment now, given that `set` no longer leverages `notifyPath` for sugar.  Thinking of [this](https://github.com/Polymer/polymer/blob/master/PRIMER.md#set-path) quote,
> Since in the majority of cases, `notifyPath` will be called directly after an assignment, a convenience function `set` is provided that performs both the assignment and notify actions.

I realize that it doesn't explicitly say that `set` uses `notifyPath` directly, but it seems to imply that this is the case.  Now `set` uses the private interface `_notifyPath`.

Out of curiosity, is there any way `set`, `splice`, `push`, etc. could continue to use the `notifyPath` public interface?  We were patching `notifyPath` to add functionality to `set`, `splice`, `push`, etc.  It's a nice assumption to be able to make, that `notifyPath` is used by all those methods.

**Comment by kevinpschaaf** [comment]
That the other API's now use `_notifyPath` rather than the public `notifyPath` is an implementations detail.  We do this for performance reasons: since the public `notifyPath` has to do the index->key normalization, we are careful to only do that once in the other public API's, and call `_notifyPath` internally, which accepts only pre-normalized key-based paths.  So I don't think we'd consider changing that back as it's a performance consideration.

**Comment by devinivy** [comment]
Cool– that makes sense.  Thanks for getting back!
