### ISSUE TITLE
Polymer "inheritance" proposal - expose more mixins!!

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#2510]
_From @kristianmandrup on September 30, 2015 7:45_

I fully understand why you wen't away from full components inheritance. A crude weapon indeed.
However it would be VERY convenient if all elements exposed their style, properties and behaviour as mixins for other elements to build on. 

This IS currently possible, so it is only a matter of enhancing existing elements to follow this pattern to allow for better composition. 

This would also help to solve the "problem" with the content selector limitation: https://github.com/Polymer/core-selector/issues/39

Example `paper-scroll-header-panel`

``` js
var mixinElement = Polymer.registry('paper-scroll-header-panel')

Polymer.extend({
  properties: [
    mixinElement.properties, 
    AnotherSetOfproperties, 
  ],
  behaviors: [
    myOtherMixinElement.behaviors,
    someNiceBehavior,
    mixinElement.behaviors
  ]
}, {
  // my specific element overrides and customizations
});
```

You could of course see a behavior as a full set of properties and methods which form a logical unit. Then expose methods and properties as separate mixin units as well. Then allow full inheritance as a convenience, which simply inherits all behaviors and the shared styles exposed by the elements as well.
Provide full flexibility and granular control.

Cheers!

_Copied from original issue: PolymerLabs/polymer-patterns#46_

**Comment by ebidel** [comment]
_From @kristianmandrup on September 30, 2015 13:44_

After some research into `polymer` core I see the following methods are already available, however not really documented very well. I guess they could be used as a starting point?

```js
Polymer.Base

     * @method extend
     * @param {Object} prototype Target object to copy properties to.
     * @param {Object} api Source object to copy properties from.
     * @return {Object} prototype object that was passed as first argument.
     */
    extend: function(prototype, api) {

    /**
     * Copies props from a source object to a target object.
     *
     * Note, this method uses a simple `for...in` strategy for enumerating
     * properties.  To ensure only `ownProperties` are copied from source
     * to target and that accessor implementations are copied, use `extend`.
     *
     * @method mixin
     * @param {Object} target Target object to copy properties to.
     * @param {Object} source Source object to copy properties from.
     * @return {Object} Target object that was passed as first argument.
     */
    mixin: function(target, source) {
      for (var i in source) {
        target[i] = source[i];
      }
      return target;
    },

    copyOwnProperty: function(name, source, target) {

  Polymer.Base.chainObject = function(object, inherited) {
```

**Comment by jfrazzano** [comment]
Eric, wow. Thanks. That's cool.

**Comment by jaichandra** [comment]
I have been trying to do this for a while and I finally got a version working. Here's the link: https://plnkr.co/edit/S3hwK5?p=preview. I have only tested these with paper-elements, but it works for me so far. Below is the mixin for quick review:
```
Polymer.TemplateMixin = (element) => {
    let superClass = document.createElement(element).constructor;
    return class extends superClass {

        static get template() {
            if (!this.hasOwnProperty('_template')) {
                this._template = Polymer.DomModule.import(this.is, 'template') ||
                    Object.getPrototypeOf(this.prototype).constructor.template;
            }
            return this._template;
        }

        static finalize() {
            console.log(this);
            try {
                let superTemplate = superClass.template;
                let cssText = Polymer.StyleGather.cssFromTemplate(this.template.cloneNode(true));
                if (cssText) {
                    let style = document.createElement('style');
                    style.textContent = cssText;
                    superTemplate.content.insertBefore(style, this.getInsertionPoint(superTemplate));
                }
                this._template = superTemplate.cloneNode(true);
                super.finalize();
            } catch (e) {
                console.log(e);
            }
        }

        static getInsertionPoint(template) {
            // return slot location or last element in the template (ignore the last text node);
            return template.content.querySelectorAll('slot')[0] ||
                template.content.lastChild.previousSibling;
        }
    }
}

```

**Comment by kristianmandrup** [comment]
@jaichandra
 Sweet :) I hope this gets built in with Polymer 2.0 at some point.

**Comment by jaichandra** [comment]
The above code certainly has performance limitations. I would need help figuring out a much cleaner way in Polymer to ensure each component does this template merge only once.

**Comment by kristianmandrup** [comment]
I created this [Polymer extension](https://github.com/kristianmandrup/polymer-ext) years ago.
Allows a Polymer 1.0 element to be extended.

```js
var myElement = Polymer.findRegistered('my-element');

  // Each key: properties, props, methods act as a mixin.
  // properties - properties object
  // props - all attributes (non-functions)
  // methods: - all own functions
  // behaviors: - all own functions and attributes
  var myExtension = Polymer.extend({
    parent: myElement,
    // properties: myElement.properties,
    // props: myElement.props,
    // methods: myElement.methods,
    // behaviors: myElement.behaviors
  }, {
    is: 'ext-element',
  });

  Polymer(myExtension);
```

**Comment by jaichandra** [comment]
@kristianmandrup I got the performance issue fixed. Updated above code with latest.

**Comment by TimvdLippe** [comment]
This has shipped with the native API of [`customElements.get`](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/get) and inheritance with ES6 class extension :tada:
