### ISSUE TITLE
Add optional way to strip whitespace from templates

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#2511]
It's typically a very minor performance improvement if whitespace is stripped from templates, but it's cumbersome to write html this way. We could expose a `strip-whitespace` option to templates that would be processed at registration time and would strip all whitespace from templates.

**Comment by ebidel** [comment]
Could this just be the default? You can't look inside a template in the
tools and generated dom will be formatted.

**Comment by samccone** [comment]
whitespace sometimes can be really important in templates, I wonder if automatically stripping by default might break what people expect and be quite difficult to debug.

**Comment by ebidel** [comment]
<template> is DOM based, where whitespace doesn't matter.

**Comment by samccone** [comment]
oh perhaps I am not correctly understanding what
> whitespace is stripped from templates

means then :wink:

**Comment by ebidel** [comment]
@samccone it's a blink bug where style recalc takes a large amont of time on textnodes:
https://code.google.com/p/chromium/issues/detail?id=399816

**Comment by ebidel** [comment]
This is fixed from Steve's commit.

**Comment by idanen** [comment]
The addition of this feature caused a weird bug for me when using `paper-toggle-button` in an AngularJS app.
When used in a container that repeats using `ng-repeat` the toggle-button is drawn twice.
I made a plunkr demoing the issue: [plunkr](http://plnkr.co/edit/sDPxgi)
When removing the `strip-whitespace` attribute, it goes back to normal.
I'm not sure whether to open a new issue or just re-opening this one...
