### ISSUE TITLE
Idea: Yell at users when they use camelCase in element attributes ⚠️

### ISSUE THREAD

**Issue by samccone** [Polymer/polymer#2516]
consider the following usecase:

```html
<x-foo zapBar="1"></x-foo>
```

```js
Polymer({
  is: 'x-foo',
  properties: {
    zapBar: String
  }
})
```

should yield a nice **console.warn** :warning: 

It is my suspicion that this would save people quite a bit of time.

**Comment by blasten** [comment]
I think the linter https://github.com/PolymerLabs/polylint will handle this case.

**Comment by ebidel** [comment]
It would be nice to get https://github.com/PolymerLabs/polybuild/issues/7 in, so `polybuild` can be used for building + linting. So may `poly-*`!

**Comment by addyosmani** [comment]
Polylint does indeed currently cover this usecase. Imo, rather than including additional `console.warn` statements, we should encourage folks to use that tool. Also should get editor support via plugins soon.

**Comment by samccone** [comment]
Ok 😎
