### ISSUE TITLE
ES6: support class extends

### ISSUE THREAD

**Issue by gutenye** [Polymer/polymer#2520]
Given

```
class Base {
   say() { .. }
}

class User extends Base { }
Polymer(User)
```

It's not working. tested on `v1.1.4`

possible related to https://github.com/Polymer/polymer/pull/2365#discussion_r37827984

**Comment by ebidel** [comment]
Confirmed this doesn't work. Repo: http://jsbin.com/wahepakeri/edit?html,output

Note, vanilla custom elements can extend from a base class that's extending `HTMLElement`: 
http://jsbin.com/neyijafoqo/edit?html,output

**Comment by sjmiles** [comment]
Polymer doesn't currently support chained-prototypes as arguments to `Polymer()` in any context. This is a Roadmap Feature.

**Comment by ebidel** [comment]
If we get element inheritance back, does it unlock this feature?

**Comment by sjmiles** [comment]
It's more complicated than that.

**Comment by laco0416** [comment]
@sjmiles  I tried to solve this issue.
https://github.com/Polymer/polymer/pull/2604
Please review this!

**Comment by azakus** [comment]
We're currently working on inheritance support, and we will have a better opportunity to support this use case, #3345.

There are 4 cases we will support for inheritance

1. `MyPolymerElement extends OtherPolymerElement`
1. `MyPolymerElement extends HTMLElement`
1. `MyPolymerElement extends HTMLOtherNativeElement`
1. `MyPolymerElement extends RandomJSClass`

For case 1, the answer is simple: do nothing.
For case 2 and 3, we will need to replace the native html element prototype with one that includes `Polymer.base`.
For case 4, we will find the lowest prototype, Object, and replace that with `Polymer.Base` on `HTMLElement`.

**Comment by laco0416** [comment]
@azakus multi-staged inheritance will be supported?

```
class MyBaseElement extends SomeClass

class MyElement extends MyBaseElement
```

**Comment by azakus** [comment]
@laco0416 That should work, but my original statement in https://github.com/Polymer/polymer/issues/2520#issuecomment-176497918 appears to be too hard.

With a few helper functions we can support these use cases:

1. `class MyElement`
2. `class MyElement extends Polymer.Element` where `Polymer.Element` is `HTMLElement` plus the Polymer base class
3. `class MyElement extends Polymer.Extend('input')` where `Polymer.Extend` creates `HTMLInputElement` chained with Polymer base class
4. `class MyElement extends Polymer.Extend('other-polymer-element')`, which can be equivalent to `class MyElement extends OtherPolymerElement`

**Comment by TimvdLippe** [comment]
I suppose with Polymer 2 class-based syntax this issue has been resolved?

**Comment by TimvdLippe** [comment]
Closing this per above comment.
