### ISSUE TITLE
Uncaught ReferenceError: CustomEvent is not defined at .../...//bower_components/webcomponentsjs/webcomponents-lite.js:1327

### ISSUE THREAD

**Issue by andrerodri** [Polymer/polymer#2521]
i am having this error when i load a Play framework template (called web view) in an app running on android 4.4.2. In this template, i am loading a polymer element. this is my header:

```javascript
<head>
    <title>My Page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.css">
    <link rel="import" href='@routes.Assets.versioned("bower_components/polymer/polymer.html")'>
    <script src="http://code.jquery.com/jquery-1.8.2.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.js"></script>
    <script src="http://cdn-na.infragistics.com/igniteui/2014.2/latest/mobile/js/infragistics.mobile.js"></script>
    <script src='@routes.Assets.versioned("bower_components/webcomponentsjs/webcomponents-lite.js")'></script>
    <link rel="import" href='@routes.Assets.versioned("bower_components/components/surveys/survey-confirmation/show-rating-answer.html")'>
```

it gives this error in webcomponent-lite.js:
Uncaught ReferenceError: CustomEvent is not defined at http://....(url hidden).../assets/bower_components/webcomponentsjs/webcomponents-lite.js:1327.

any idea whats going on and how to fix it? thx in advanced :-)

**Comment by clintwood** [comment]
It may be due to IE ([see here](http://caniuse.com/#feat=customevent)), you don't say what you running on, in that case try using a polyfill [custom-event](https://www.npmjs.com/package/custom-event).  I'm not sure if WebComponents polyfills are supposed to polyfill this or not.  all I know is I use the references polyfill via browserify!

**Comment by tjsavage** [comment]
Try loading the webcomponents-lite polyfill before importing Polymer?

**Comment by azakus** [comment]
Hmm, `CustomEvent` should work in 4.4.2. Can you make a simpler repro to try with?

**Comment by azakus** [comment]
Closing due to age, please reopen if this is still an issue.
