### ISSUE TITLE
Optimize performance of listening to gesture events.

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#2523]
In a fairly minimal polymer element, calling `listen` to get `down` events is a good bit more expensive than calling `addEventListener`. The difference is about 10% in the creation time of a trivial element. It'd be great if we could reduce that overhead.

**Comment by samccone** [comment]
@sorvell can you provide some insight into how you profiled this?

**Comment by azakus** [comment]
So, it looks like the majority of the cost is associated with the `this.listen` API.
Because `this.listen` has a convenient "lookup" property for event handler names, we have to make some bookkeeping to support the `unlisten` case.

**Comment by azakus** [comment]
I'm going to close this since no action needs to be taken right now.
