### ISSUE TITLE
Variables in Polymer

### ISSUE THREAD

**Issue by andreasonny83** [Polymer/polymer#2524]
Hi,
I'm a little bit confused about the way the variables work in Polymer so I'm not sure the following is a real bug.
Supposed the following code:
```
Polymer({
	is: 'lq-login',
	properties: {
		input_field: {
			type: Object,
			value: function() {
				return {};
			}
		},

		reset_fields: {
			type: Object,
			readOnly: true,
			value: function() {
				return {
					email: '',
					password: ''
				};
			}
		}

	},
```
I want to reset input_field to the reset_fields object every time I tap the 'reset' button.
I tried these 2 ways inside a the following function:
```
resetFields: function() {
  // 1st try
  this.set( 'input_field', this.reset_fields );
  // 2nd try
  this.input_field = this.reset_fields;
}
 ```
This is just working the first time because, after that reset_fields is always equal to input_field even if reset_fields is readOnly.

It works fine if I reset the single elements individually in this way:
```
resetFields: function() {
  this.set( 'input_field.email', this.reset_fields.email );
  this.set( 'input_field.password', this.reset_fields.password );
}
```

Am I doing something wrong ?

**Comment by zoechi** [comment]
I guess you just need to create a copy, otherwise both variables reference the same array. 
```js
setFields: function() {
  // 1st try
  this.set( 'input_field', this.reset_fields.slice());
}
```

**Comment by andreasonny83** [comment]
I cannot use slice(). It doesn't work with Objects

**Comment by zoechi** [comment]
Sorry, didn't look close enough, but as far as I know the function assigned to `value: ...` is only executed the first time (for initialization). I think you need to create a copy otherwise both fields reference the same object.

**Comment by andreasonny83** [comment]
correct but even if I set the object using a copy of reset_filed I can still see the wrong behaviour.
```
setFields: function() {
  var copy_reset_fields = this.reset_fields;
  this.set( 'input_field', copy_reset_fields );
}
```

After this point, every time an input_field's item change, copy_reset_fields and reset_fields change as well

**Comment by zoechi** [comment]
You still didn't create a copy, you just pass a reference around. I'm not a JS dev, but Google came up with http://stackoverflow.com/questions/728360/most-elegant-way-to-clone-a-javascript-object

**Comment by andreasonny83** [comment]
Yes, that might be the answer I'm looking for. Thank you

**Comment by andreasonny83** [comment]
Yes, that might be the answer I'm looking for. Thank you
