### ISSUE TITLE
Any plan to publish Polymer elements into NPM?

### ISSUE THREAD

**Issue by tapas4java** [Polymer/polymer#2525]
Hi,

I know Polymer works great with Bower but due to some reason I want to use NPM as single tool for all ui dependency management. Is there any plan to publish Polymer elements into NPM repo??

**Comment by addyosmani** [comment]
See my meeting notes with npm at https://github.com/npm/npm/wiki/npm-%E2%87%94-Polymer-brainstorming-session and also the discussion at https://github.com/Polymer/polymer/issues/326#issuecomment-113594766. Until we officially support npm, you might be able to get Polymer and npm working together using napa: http://stackoverflow.com/a/32165436

**Comment by tapas4java** [comment]
Thanks @addyosmani

**Comment by surajpatil14** [comment]
Sir, i have installed sudo npm install -g bower
sudo npm install -g polymer-cli
and
polymer-startpolymer

but still i am not able to view polymer project on my vps server. but if i deploy same to google app engine thens its working fine.  kindly help us to deploy same on over server too

my web server urs is : http://www.cartseller.com/webapp/
app engine : https://webapp-1470592722173.appspot.com/


Regards
