### ISSUE TITLE
Dom-repeat filter/sort depending on element's properties

### ISSUE THREAD

**Issue by Jamtis** [Polymer/polymer#2530]
Dom-repeat's filter/sort function lack the ability to recompute on changes of external properties.

[Here's a fiddle](https://jsfiddle.net/jamtis/zo4Laa9v/).

Well, there's the `observe` property... but it can only observe item properties.

My proposal is to let `observe` listen to the elements properties by default and use `item.property` to listen to item properties.

This feature doesn't seem to be to hard to implement.

Maybe I overlooked something trivial.
If there's a easy way to accomplish filtering/sorting on element property changes, please tell me so.

**Comment by miztroh** [comment]
+1

**Comment by jshcrowthe** [comment]
If I understand you correctly what you are looking to do is doable. I have modified your jsfiddle here to illustrate **my** solution:

[Updated fiddle](https://jsfiddle.net/64b4akrb/) 

The theory is instead of passing a function directly to the filter attribute you return a function to the filter attribute.

So to modify the [example in the docs](https://www.polymer-project.org/1.0/docs/devguide/templates.html#filtering-and-sorting-lists) to be customizable it'd look like the following:

```javascript
isType: function(type) {
  return function(item) {
      return item.type == type || item.manager.type == type;
  }
}
```
And in your html:
```markup
<input type="text" value="{{type::input}}>
<template is="dom-repeat" items="{{employees}}"
    filter="{{isType(type)}}" observe="type manager.type">
```

**Comment by Jamtis** [comment]
@jshcrowthe Thanks for the solution.
It's a nice workaround but I see an performance issue in recreating a function on each property change (in comparison to an invocation).
Still works for me right now. :+1:

**Comment by ebidel** [comment]
Yea, defining `filter` to return a function is the recommend approach if you want something more custom. See https://github.com/Polymer/polymer/issues/2175#issuecomment-127415081.

**Comment by Jamtis** [comment]
@ebidel What do you think about changing the "closure" of the observe property to the element instead of the item?
I think recreating a function on each property change seems a bit inadequate to me, since it's the properties that change and not actually the way the function works.

Letting observe listen to property changes on element level instead of item level would provide a neat way to declare all dependent properties while optimising performance.

`<template observe="itemprop">` would be `<template observe="elementprop item.itemprop">`.

**Comment by miztroh** [comment]
@Jamtis If an element had a property called ``item``, your suggestion wouldn't work.  It's probably a lot less messy to just leave it as it is.  When I initially gave this a +1, it hadn't occurred to me that you could  data bind a function to that property.

**Comment by Jamtis** [comment]
Well I doubt that it's senseful to declare a `item` property on an element that uses `item` as an iterating value.
However I think it's not much of a deal to change the scope of the `observe` property and I would be a unified dependency declaration + performance enhancement.

**Comment by miztroh** [comment]
@Jamtis What I mean is this:

Say element ``x-foo`` has a property called ``item`` and its local DOM has a ``dom-repeat``.  If you're exposing ``x-foo``'s local DOM scope to ``dom-repeat``'s ``observe``, then how does it know whether to observe ``x-foo``'s ``item`` or the ``item`` generated by the ``dom-repeat``?

Sure, you can avoid this pitfall by not making sure ``x-foo`` doesn't have a property called ``item`` or using ``as="somethingElse"`` on the ``dom-repeat``, but it seems like the existing way of handling this works and doesn't allow for this pitfall at all.

**Comment by Jamtis** [comment]
Yeah, I agree with you.

There is an overlap of the `item` property of `x-foo` and the `item` of the `dom-repeat`.

At the moment this pitfall also exists:

```
<x-foo item="{{item}}">
  <template is="dom-repeat">
    <div>{{item}}</div>
  </template>
</x-foo>
```

This current version also leaves a ambiguity of which `item` is to be used.

**Comment by Jamtis** [comment]
Maybe add `performance` tag.

**Comment by kevinpschaaf** [comment]
Due to the way the binding system is architected, elements only receive path notifications for objects to which they are bound.  i.e. `<template is="dom-repeat" items="{{myItems}}">` will see path notifications for any change to `myItems` and its sub-paths, but not for `randomProperty` on its host which its filter function may depend on.  It's for this reason we haven't done the obvious and defined the `observe` property to observe any host property.

**Comment by Jamtis** [comment]
Thanks for the explanation.
I guess due to p3 this issue will not be resolved anytime soon...
The createFilterFunction method works well at the moment but is there a reason not to change the observe-scope in the future?
