### ISSUE TITLE
Polymer events creates a new bound handler for every `listen` call

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer#2534]
As discussed in person, this could be made slightly more optimal by looking to see if a listener has been created already.

Fixing this would allow `listen` to be called n times with the same arguments, while ensuring that only one listener is ever actually added.

**Comment by cdata** [comment]
This bugfix blocks https://github.com/PolymerElements/iron-selector/pull/64

**Comment by azakus** [comment]
This is a bug in `events` module, not in `gestures`.

**Comment by cdata** [comment]
Amended the title.

**Comment by cdata** [comment]
We merged a temporary patch to `IronSelectable` where we do our own book-keeping. When this is closed, we should go back and clean up the extra book keeping in https://github.com/PolymerElements/iron-selector/pull/70
