### ISSUE TITLE
dom-repeat bound to an object's array property does not get re-rendered on array change

### ISSUE THREAD

**Issue by nilpotence** [Polymer/polymer#2536]
I have the following data-binding scenario :

``` html
<dom-module id="my-elem">
    <template is="dom-repeat" items="{{selectArray(map.*, selected)}}">
        <p>{{item}}</p>
    </template>
</dom-module>
<script>
    Polymer({
        is: 'my-elem',
        properties: { map: { type: Object, notify: true }, selected: {type: String, notify: true} },
        selectArray: function(map, selected){
            return this.map[this.selected];
        },

        getsRendered: function(){
            this.set('selected', 'A');
            this.set('map.A', []);
            this.push('map.A', 'some item');
        },

        doesntGetRendered: function(){
            this.set('selected', 'A');
            this.set('map.A', []);

            this.async(function(){
                this.push('map.A', 'some item');
            });
        },

    }
</script>
```

In the _'getsRendered'_ method, the template gets re-rendered because the _'A'_ property was added to the map object, but in the async part of the _'doesntGetRendered'_ method, only elements of _'map.A'_ are added and thus the template doesn't re-render.

It seems like dom-repeat ignores events on path _'map.A.*'_, how can I make the template re-render beside using template.render() explicitly ? Is that intentional or is it a bug ?

**Comment by azakus** [comment]
I think this syntax breaks the change observer because the array used for `dom-repeat` is not statically resolvable to the backing array.

@kevinpschaaf is this supported syntax?

**Comment by azakus** [comment]
This seems like it should work. I'll take a look.

**Comment by TimvdLippe** [comment]
Seems to be working now with a regular object: http://jsbin.com/sulonomuba/edit?html,console,output
