### ISSUE TITLE
Polymer.dom: appendChild to parentNode during ready can fail

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#2544]
Appending a node to a Polymer element's parentNode (which may be a root) in `ready` can fail (node is never appended to document).

Example:

```js
      ready: function() {
        var div = document.createElement('div');
        div.textContent = 'never stamped!';
        var parent = Polymer.dom(this).parentNode;
        // Will properly append async to ready
        // this.async(function() { Polymer.dom(parent).appendChild(div); });
      }
```

Repro: http://jsbin.com/kimodi/edit?html,output

**Comment by sorvell** [comment]
Appears to be working now: http://jsbin.com/lamuma/edit?html,output. Please re-open if the problem comes up again.
