### ISSUE TITLE
CDN for Polymer

### ISSUE THREAD

**Issue by Download** [Polymer/polymer#2546]
I was looking for CDN info for Polymer and found this old [FAQ page](https://www.polymer-project.org/0.5/resources/faq.html#is-the-code-hosted-on-a-cdn), but the CDN info it contains is only for 0.5...

I could not find a CDN for 1.0 so I set up one myself. Feel free to link to it in your new FAQ. It's based on a simple Bower project that includes all elements and is hosted on GitHub where it can make use of the awesome [RawGit](http://rawgit.com/) to function as a CDN. 

**[polymer-cdn](download.github.io/polymer-cdn)**

I'm hoping it can be helpful. 

Kind regards,

-Stijn

**Comment by addyosmani** [comment]
We have an official CDN project for Polymer 1.0 called PolyGit. You can check it out at http://polygit.org/. We currently use it all over the place for prototypes and quick issue reproductions. Although it's not well listed on the site atm, we plan on fleshing out a tools page that includes a mention of it.
