### ISSUE TITLE
Polymer.Bind & notify-path: Consider combining and normalizing prepareModel

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#2547]
Currently the `Polymer.Bind` library is responsible for creating property effects, property accessors, and the glue code that wires accessors to effects.  The `notify-path` module on `Polymer.Base` is responsible for the entry point into path-based effects (which eventually callback into the property-based effect implementation).

This issue is to consider combining the two modules.

In particular, `Polymer.Templatizer` supports templatizing a template that is not itself: contrast `<template is="dom-repeat">` (Templatizer client templatizes itself) vs. `<iron-list><template>...</template></iron-list>` (Templatizer client templatizes separate template).  In order to support the latter use case, the vanilla template must be imbued with property effects, which forward outer scope properties into template instances and vice-versa.  `Polymer.Bind.prepareModel` allows mixing the _property_-based API onto an element; however since API support for subpath effects comes from `notify-path`, there is currently a `Polymer.Base.prepareModelNotifyPath` method to copy the relevant path API.  All of this has the opportunity to be combined into one API.

**Comment by azakus** [comment]
@kevinpschaaf did this ever happen?

**Comment by kevinpschaaf** [comment]
No, it should go on the "re-layering/maintenance re-factoring" pile.

**Comment by TimvdLippe** [comment]
If I am not mistaken, this has resulted in the `property-effects` mixin which has both behavior. Can we close this issue?

**Comment by kevinpschaaf** [comment]
Yes, path and property handling were normalized in 2.0 in `property-effects` as you said.  Closing.
