### ISSUE TITLE
[::shadow] Recursive styles are not resolved

### ISSUE THREAD

**Issue by BLamy** [Polymer/polymer#2551]
I'm trying to style to do a type of recursive styling where an element will style light dom children of the same type. 

![Bug](http://i.imgur.com/QWbI8iZ.png)

As you can see in the picture the statically written height property is set fine however, the variable is not resolved. 

Going the ::shadow route works as intended
![works](http://i.imgur.com/oZ6pSAG.png)

**Comment by ebidel** [comment]
`:host::content` should be `:host ::content`. Note the space. That might work under shady dom but it won't work under native shadow dom.

If you're changing classes dynamically, it make be that you need to call `updatesStyles`:
https://www.polymer-project.org/1.0/docs/devguide/styling.html#style-api

**Comment by ebidel** [comment]
By regression, do you mean this was working before a new release broke you?

**Comment by BLamy** [comment]
Regression just meant it was and edge case I could do using the deprecated shadow/deep API but not the 1.0 styling api. 

I tried the space between host and content and it still didn't work. I was just trying to be fancy and create one single element that could be infinity nested within itself to create a tree. But I'll just create a parent and child element.

**Comment by azakus** [comment]
I believe this case is too dynamic for our current custom properties shim, as it would require watching the distributed children change and push style information into those children as they are distributed.

@sorvell sound about right?

**Comment by azakus** [comment]
This is not something we can support with the CSS Property shim.
