### ISSUE TITLE
[Question] Why is there Polymer.Base.set/notifyPath?

### ISSUE THREAD

**Issue by Jamtis** [Polymer/polymer#2552]
I wonder why these are used to set values to paths?

I understand that these methods are supposed to fire `property-changed` events to notify elements that something changed.

But isn't this what `Object.observe` is for?

**Comment by arthurevans** [comment]
Polymer 1.0 doesn't use `Object.observe`. Both native `Object.observe` and the `Object.observe` polyfill had performance issues under different circumstances.

**Comment by Jamtis** [comment]
Thanks.
