### ISSUE TITLE
malformed observer registration yields a difficult to debug error

### ISSUE THREAD

**Issue by samccone** [Polymer/polymer#2555]
```js
...
observers: ['foo(zap, tap']
...
```

![screen shot 2015-10-09 at 1 52 52 pm](https://cloud.githubusercontent.com/assets/883126/10405342/129c8af2-6e8d-11e5-9ad1-88a32d3ada37.png)

Seems like something we might want to catch and surface a bit better

**Comment by samccone** [comment]
best
day
ever

**Comment by JeremybellEU** [comment]
Thanks @samccone :heart:
