### ISSUE TITLE
Setting gold-email-input's auto-validate to "false" in the html does not work

### ISSUE THREAD

**Issue by exactspace** [Polymer/polymer#2561]
If I create a gold-email-input and set the auto-validate to false, (auto-validate="false") it still autovalidates!  This works differently than say a paper-input that I can actually set auto-validate="false" within the html, and it doesn't autovalidate. However, if I get rid of "auto-validate" in gold-email-input it will set it to false as it's default. 

Even if I set the gold-email-input attribute "auto-validate" to "false" in JavaScript, it has no effect.

**Comment by LM450N** [comment]
Please move this issuer to this [tracker](https://github.com/PolymerElements/gold-email-input/issues?q=is%3Aopen+is%3Aissue).

**Comment by exactspace** [comment]
Sorry I think I'm too much of a newb to figure out how to move it. I will close this and make a new issue in that tracker. Thanks.

**Comment by LM450N** [comment]
:+1: I don't think it's possible to move an issue. I would have done the same thing. :wink:
