### ISSUE TITLE
Setting properties before upgrade overrides Polymer's setters using the polyfill.

### ISSUE THREAD

**Issue by blasten** [Polymer/polymer#2562]
Please try this jsbin in safari: http://jsbin.com/zifigi/edit?html,output.  The code for x-example is available in https://gist.githubusercontent.com/blasten/861b640568f8b8268f89/raw/b6eab660b4cf6e439404e310e921f1cd5e27ae05/x-example.html

**Comment by sorvell** [comment]
Manipulating elements before `WebComponentsReady` is not supported when custom elements are not implemented natively in the browser.

What's happening here is the instance property is covering up the setter/getter that Polymer installs on the element prototype. Polymer could detect this and correct the problem, but it would incur a per instance cost that we'll need to evaluate.
