### ISSUE TITLE
Observing two arrays initially fails silently.

### ISSUE THREAD

**Issue by impguard** [Polymer/polymer#2563]
The documentation notes that observing array changes can be accomplished by observing `array.splices`. However, when the array is freshly initialized, the splices property is non-existent, causing the following observing method to not be called when there are two arrays being observed:

```
observers: [
    arraysChanged(array1.splices, array2.splices)
]
```

If `array1` and `array2` are being populated/selected by a dropdown menu (for instance), the `arraysChanged` method will not be called until the user has selected something from both dropdown menus once. This causes `array1` and `array2` to both have valid non-null splices properties.

The two workarounds is to initialize `array1` and `array2` with a splices property or to add two observers:

```
observers: [
    arraysChanged(array1.splices),
    arraysChanged(array2.splices)
]
```

Ideally, arraysChanged can still be called with a null argument when the property fails or at least report an error.

**Comment by kevinpschaaf** [comment]
As a workaround, you can do:

```
observers: [
    arraysChanged(array1.*, array2.*)
]
```

and

```
arraysChanged: function(array1Info, array2Info) {
  if (array1Info.path == 'array1.splices') {
    ...
  }
  if (array2Info.path == 'array2.splices') {
    ...
  }
}
```

**Comment by David-Mulder** [comment]
Ah, really painful issue this, because stuff like

    x(array.splices, object.*)

doesn't work either, nor does

    x(prop, array.splices)

which has caused me already a lot of headaches

**Comment by devinivy** [comment]
This is a bit of a pain point, but I understand why it works this way.  @kevinpschaaf's workaround isn't too, too bad.  Otherwise, your observing function would be passed `undefined` values when there is no splice for one of the arrays.

**Comment by David-Mulder** [comment]
@devinivy Nothing wrong with getting passed `undefined` or `null`, the important thing is that observing for example a `string` and an `array` together is practically impossible right now, but often required.

**Comment by devinivy** [comment]
Yeah, I misspoke.  I was thinking of getting passed `undefined` when one of the splices has _never_ been set– point being that it's currently consistent with the fact that observers wait for all paths to be initialized to something other than `undefined`.  Overall I think I still agree that splices should probably be an exception to that rule, or should be initialized to a special value upon array creation.
