### ISSUE TITLE
Provide error hook for sending diagnostic data

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#2566]
Users wishing to detect client-side runtime errors for diagnostic reporting to a backend service need a way to hook errors from each entry point that code may be run.

This may be structured as a separate optional import that can be loaded after polymer.html that patches the entry points to call an error handler.

**Comment by ebidel** [comment]
Is there more you had in mind other than `window.error`? It catches all client-side errors and works well with tools like Google Analytics.

example usage:
https://github.com/GoogleChrome/ioweb2015/blob/21d7a80aefd6a76474fcdb700ac9965cd4c7800f/app/templates/layout_error.html#L97-L110

ga supports error event. Super handy for realtime reporting:
https://github.com/GoogleChrome/ioweb2015/blob/21d7a80aefd6a76474fcdb700ac9965cd4c7800f/app/scripts/analytics.js#L14

**Comment by kevinpschaaf** [comment]
Sorry, should have added that detail.  window.onerror does not provide detailed error information (e.g. error type, stack, etc.) for cross-domain loaded scripts on IE (even when cors is enabled, apparently).  This is the crux of why this feature was requested.

http://jsbin.com/dateto/edit?html,console,output
