### ISSUE TITLE
Broken docs on Chromium 

### ISSUE THREAD

**Issue by nverba** [Polymer/polymer#2569]
After an update today, the Polymer element docs can't open individual element pages, or the demos.
For example, https://elements.polymer-project.org/elements/iron-form won't load/render due to error:

`Uncaught TypeError: this.docElements.find is not a function`

I haven't been able to confirm this issue with anyone else.
Chromium Version 44.0.2403.89 Built on Ubuntu 14.04, running on LinuxMint 17.2 (64-bit).

**Comment by ebidel** [comment]
The latest chrome stable is 46. Can you try that? I'm not able to repo this
on chrome Android 46.

**Comment by VaibhavAjayGupta** [comment]
+1

**Comment by nverba** [comment]
Version 45.0.2454.101 was the latest available to my distro, it also resolves this issue. Thanks for the quick response. :)
