### ISSUE TITLE
Element Queries

### ISSUE THREAD

**Issue by BLamy** [Polymer/polymer#2570]
I'd really like to see Polymer push for Element Queries as an addition to it's styling system. It just doesn't make sense that I have all this modularity but I'm still forced to style out of the viewport. 

Until we can style based off of `:host`'s properties we will not have true modularity. 

Even an official iron-element-query element would be a step in the right direction. Element query CSS is so clean, and just seems to fit 'the polymer way of doing things'

I've tried using 
https://github.com/marcj/css-element-queries

But it seems to only work in chrome.

**Comment by miztroh** [comment]
@BLamy Element Queries aren't part of the CSS spec right?  Isn't this just something that various JavaScript libraries implement with varying degrees of success?  Aren't EQs subject to circular dependency issues?  The Polymer team seems fairly committed to following / advancing the spec.  There doesn't seem to be any spec involved here.

http://www.xanthir.com/b4VG0

**Comment by ebidel** [comment]
That's right. Tab has explicitly said EQs are a hard problem and there's no spec in the works. I'm not sure what Polymer could provide here without platform support. The current solutions are pretty hacky IMO.

**Comment by BLamy** [comment]
Does the polymer team have anything in the works that is similar to EQ? I've been using polymer for a decent amount of time now and having to use media queries seems to always make my element 'context-sensitve'.

**Comment by ebidel** [comment]
No, nothing in the works.

**Comment by BLamy** [comment]
Straight forward. I won't be offended if you close this.

**Comment by SaschaNaz** [comment]
I also need this feature, sad that there is no active discussion about this.
