### ISSUE TITLE
Data binding and element recreation

### ISSUE THREAD

**Issue by deni35** [Polymer/polymer#2576]
I have the animated element. For restart an animation I'm forced recreate this element.
But inside this element I have: `<div>[[error_message_text]]</div>`.
After recreation this code: `self.error_message_text = 'bla-bla'` gets not working.

**Comment by ebidel** [comment]
Please post a reproducible jsbin using polygit.org.

**Comment by deni35** [comment]
Ok. I've done sample.
http://plnkr.co/edit/7CUhWiMKsNtxc17ODZtK?p=preview
