### ISSUE TITLE
behaviors with behaviors

### ISSUE THREAD

**Issue by TimWillis** [Polymer/polymer#2577]
Not really a bug, but not sure where to leave feedback.

Behaviors are great, but I would like to have behaviors with behaviors. If I have a group of components that all use the same list of behaviors instead of writing behaviors: [ behave1, behave2, behave3...] I would like to have 1 behavior named behave_group1 that has behaviors: [ behave1, behave2, behave3...], then in each component I can just put behaviors: [behave_group1]

If there is another place to put feedback please let me know.

**Comment by jmcgdz** [comment]
@TimWillis This is interesting ...

Have you tried making an html file that you can import with a namespaced array of all the behaviors and passing that in as the array? It might work like:

```behaviors: NS.mayBehaviorsArray```

**Comment by jmcgdz** [comment]
@TimWillis Actually, I did know this already, just spacing out.

Read here: https://www.polymer-project.org/1.0/docs/devguide/behaviors.html

```
To extend a behavior, or create a behavior that includes an existing behavior, you can define a behavior as an array of behaviors:
```

```html
<!-- import an existing behavior -->
<link rel="import" href="oldbehavior.html">

<script>
  // Implement the extended behavior
  NewBehaviorImpl = {
    // new stuff here 
  }

  // Define the behavior
  NewBehavior = [ OldBehavior, NewBehaviorImpl ]
</script>
```

You should close this issue.

**Comment by TimWillis** [comment]
Awesome, thank you!
