### ISSUE TITLE
Handle quoted strings when parsing annotations and method calls

### ISSUE THREAD

**Issue by david-saslawsky** [Polymer/polymer#2579]
The Polymer annotation and function parsers should be aware of quoted string literals 
For example, The following annotation fails without a proper error message:
````
[[localize("Welcome back, (Mr {0})")]]
````

This would fix #1784, #2295 and any other tricky case where a string contains chars like `}`, `]`, `)`

**Comment by TimvdLippe** [comment]
I think this issue was fixed as of #3017

**Comment by kevinpschaaf** [comment]
This is fixed per #3017 assuming commas are escaped as described in the docs: https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#literals

**Comment by azakus** [comment]
JSBin working with escaped commas: http://jsbin.com/jimave/edit?html,output
