### ISSUE TITLE
IE test regressions in dom-repeat, dom-bind, and dom-module-inline

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#2582]
IE tests have been failing due to an arcane timing bug in webcomponents-js, which have masked a couple of other bugs that have snuck in.

**Comment by samccone** [comment]
xref https://github.com/Polymer/polymer/issues/2476
xref https://github.com/Polymer/polymer/issues/850

**Comment by kevinpschaaf** [comment]
Once https://github.com/webcomponents/webcomponentsjs/issues/416 is resolved, we'll push fixes to the remaining regressions.
