### ISSUE TITLE
`Polymer.dom(...).observeNodes` does not notify for some DOM removal

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer#2587]
Please see the contrived test case here: http://jsbin.com/dajife/2

Removing nodes from the example element (notably, an element without a shadow root), fails to cause an expected notification from `observeNodes`.

**Comment by sorvell** [comment]
Confirmed. The issue is that we're only notifying if we have an existing logical parent for the node that's added somewhere else. This is not a sufficient check and we'll need to fallback to using composed parent.

**Comment by cdata** [comment]
This issue supports https://github.com/PolymerElements/iron-selector/pull/73.
