### ISSUE TITLE
Losing this.variable when using computed binding

### ISSUE THREAD

**Issue by edfungus** [Polymer/polymer#2589]
For some reason when I use computed binding, I do not have reference to variables in 'this' unless I pass in a variable like this.address into the function. For example, if I have three properties:

```
address: {
  type: String,
  value: ""
},
port: {
  type: String,
  value: ""
},
clientName: {
  type: String,
  value: ""
}
```
and I got make a computed binding like:
```
<paper-button disabled$="{{inputCheck()}}"> </paper-button>
...
inputCheck: function(){
          console.log(this.address);
          console.log(this.port);
          console.log(this.clientName);
}
```
I get all undefined. Where it gets interesting is when I pass this.address into the computed binding like so:
```
<paper-button disabled$="{{inputCheck(address)}}"> </paper-button>
```
I able to print just the address. But when I pass this.port, I print BOTH address and port. With this pattern, when I pass this.clientName, I get all three. 

So the ordering of the properties is making some difference to what variable is kept in scope? This seems odd and not like expect behavior.

**Comment by miztroh** [comment]
My guess is that at the point when inputCheck is being called, the other properties are actually not defined yet.  I don't think there's anything wrong with your scope.  The order in which you declare properties affects the order in which they are initially defined.  My suggestion would be to make inputCheck dependant on all three: inputCheck(address, port,  clientName).  Then you can validate the parameters each time the function is called.

**Comment by ebidel** [comment]
What @miztroh said :) If you care about all three of those properties in `inputCheck`, than you need to compute it based on those dependencies changing:  `inputCheck(address, port, clientName)`. Note polymer will not call `inputCheck` until all three deps are no longer  `undefined`. After they're all defined, it'll be called whenever one of the deps changes.
