### ISSUE TITLE
Cloning and editing Polymer on Linux machines causes diff clutter

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/polymer#2592]
When developing Polymer on a Linux machine, diff clutter is caused due to line-ending changes. In order to globally configure line-endings and prevent this clutter from happening, a .gitattributes file should be added.

Steps to reproduce (on a Linux machine):
1. Clone/Fork Polymer
2. Open the project in your prefered editor
3. Open a file with `\r\n` line-endings (currently on master: `src/lib/css-parse.html`)
4. Insert a character somewhere in the file
5. Save the file
6. Delete the just inserted character (e.g. no textual changes should remain)
7. Save the file
8. Run `git diff` and observe the output below:

```javascript
diff --git a/src/lib/css-parse.html b/src/lib/css-parse.html
index a176d7c..30c9bee 100644
--- a/src/lib/css-parse.html
+++ b/src/lib/css-parse.html
@@ -43,7 +43,7 @@ Polymer.CssParse = (function() {
             n = {start: i+1, parent: p, previous: previous};
             p.rules.push(n);
             break;
-          case this.CLOSE_BRACE: 
+          case this.CLOSE_BRACE:
             //console.groupEnd(n.start);
             n.end = i+1;
             n = n.parent || root;
@@ -84,9 +84,9 @@ Polymer.CssParse = (function() {
       if (r$) {
         for (var i=0, l=r$.length, r; (i<l) && (r=r$[i]); i++) {
           this._parseCss(r, text);
-        }  
+        }
       }
-      return node;  
+      return node;
     },
 
     // stringify parsed css.
@@ -99,10 +99,10 @@ Polymer.CssParse = (function() {
         if (r$ && (preserveProperties || !this._hasMixinRules(r$))) {
           for (var i=0, l=r$.length, r; (i<l) && (r=r$[i]); i++) {
             cssText = this.stringify(r, preserveProperties, cssText);
-          }  
+          }
         } else {
-          cssText = preserveProperties ? node.cssText : 
-            this.removeCustomProps(node.cssText);  
+          cssText = preserveProperties ? node.cssText :
+            this.removeCustomProps(node.cssText);
           cssText = cssText.trim();
           if (cssText) {
             cssText = '  ' + cssText + '\n';
@@ -138,7 +138,7 @@ Polymer.CssParse = (function() {
     },
 
     removeCustomPropApply: function(cssText) {
-      return cssText            
+      return cssText
         .replace(this._rx.mixinApply, '')
         .replace(this._rx.varApply, '');
     },
@@ -171,7 +171,7 @@ Polymer.CssParse = (function() {
   };
 
 
-  // exports 
+  // exports
   return api;
 
 })();
```
The actual changes are `^M` characters indicating the line-ending changed.
![image](https://cloud.githubusercontent.com/assets/5948271/10564396/b2fc1ba8-75b2-11e5-912d-3d628758d8b8.png)

Currently if you want to get rid of these changes:
1. Add a `.gitattributes` in the top-level folder
2. In the file insert `* binary`
3. `git add .`
4. `git reset --hard`

However this makes you lose ALL changes you made.
Therefore to prevent diff clutter and being able to contribute on Linux machines, the `.gitattributes` file should be added with `* text=auto`

**Comment by JeremybellEU** [comment]
This issue should be reopened as of #3164
