### ISSUE TITLE
Core Scaffold missing in 1.0?

### ISSUE THREAD

**Issue by sweatstudio** [Polymer/polymer#2593]
Apparently core-scaffold in version 0.5 is not compatible with IOS9, I didn't see the component in 1.0 only the drawer and header as two separate components. Is someone creating a DOM for this?

**Comment by BLamy** [comment]
Use Polymer Starter Kit.

**Comment by sweatstudio** [comment]
Thanks for the feedback BLamy.  I will check it out.  My webapp was created with 0.6 version and I am currently looking for a quicker fix to make it compatible for IOS 9.  Over 100 users complaining.   Painful.

**Comment by LM450N** [comment]
With a little luck, you could port your app to 1.0 using [PolyUp](https://github.com/PolymerLabs/polyup). May the :four_leaf_clover: force be with you!

**Comment by ebidel** [comment]
We don't have plans to make a 1.0 core-scaffold, but you you can compose it via the parts mentioned in https://github.com/Polymer/polymer/issues/2593#issue-112024143. You could also use PolyUp to port the 0.5 element for your own needs :)

**Comment by sweatstudio** [comment]
Thank you everyone for the suggestions.  So far most of the elements on 1.0 is working well on IOS9.  I will take a look at PolyUP... and the Starter Kit.....    I will close this thread now.
