### ISSUE TITLE
toggleAttribute value

### ISSUE THREAD

**Issue by charbelrami** [Polymer/polymer#2594]
It would be nice to have a value parameter
https://github.com/Polymer/polymer/blob/master/src/standard/utils.html#L61-L71

``` js
toggleAttribute: function(name, bool, node) {
  node = node || this;
  if (arguments.length == 1) {
    bool = !node.hasAttribute(name);
  }
  if (bool) {
    Polymer.dom(node).setAttribute(name, '');
  } else {
    Polymer.dom(node).removeAttribute(name);
  }
},
```

becomes

``` js
toggleAttribute: function(name, bool, node, val) {
  node = node || this;
  val = val || '';
  if (arguments.length == 1) {
    bool = !node.hasAttribute(name);
  }
  if (bool) {
    Polymer.dom(node).setAttribute(name, val);
  } else {
    Polymer.dom(node).removeAttribute(name);
  }
},
```

If you agree, I could create a pull request

Thanks

**Comment by azakus** [comment]
I think the intention of that API is more to handle the fact that boolean attributes (ones that either exist, or don't), are more annoying to update than those take take a value.

For attributes that expect values, you can just use `Polymer.dom(node).setAttribute(attr, '')`.

**Comment by TimvdLippe** [comment]
Closing per above comment and because `toggleAttribute` is on the legacy element mixin.
