### ISSUE TITLE
ReferenceError: Polymer is not defined

### ISSUE THREAD

**Issue by sajjadmurtaza-ror** [Polymer/polymer#2597]
When i start gulp serve am facing following error

ReferenceError: Polymer is not defined http://localhost:5000/elements/my-greeting/my-greeting.html:30
ReferenceError: Polymer is not defined http://localhost:5000/elements/my-list/my-list.html:30

Here is code of my-greeting.

   (function() {
    'use strict';

    Polymer({
      is: 'my-greeting',

      properties: {
        greeting: {
          type: String,
          value: 'Welcome!',
          notify: true
        }
      }
    });
    
![screenshot from 2015-10-19 16 34 05](https://cloud.githubusercontent.com/assets/8552702/10576928/9a6cbad8-7680-11e5-98d6-cc2bd3ad22d5.png)
})();

**Comment by ebidel** [comment]
Check that you're importing polymer.html in your elements. This guide shoukd help: https://www.polymer-project.org/1.0/docs/start/reusableelements.html
