### ISSUE TITLE
Property Validations

### ISSUE THREAD

**Issue by BLamy** [Polymer/polymer#2598]
I'd like to see a more strict system behind Property types. I understand that polymer encompasses all primitives as well as the catch all 'Object' type. 

However, what i've been finding is that sometimes Object is just too generic. I would love if I could create my own validation which allow me to create more complex types.

A really good example of this being done can be seen in the sails.js docs:
http://sailsjs.org/documentation/concepts/models-and-orm/validations

A proposed API would look a little like this.

``` javascript
    Polymer({
      is: 'x-foo',
     /**
      * Can handle two kinds of children. 
      * 1) Validations. 
             typeof === function
      * 2) Types
            typeof === Object
      **/ 
      types: {

       /**
        *  Validations can be created here. 
        *  For example one could polyfill `required` as follows
        required:function(val){
           return (typeof val !== 'undefined')
         }
        */
        is_point: function(geoLocation){
          return geoLocation.x && geoLocation.y
        },

       /**
        * Custom types provide mixed in validations
        * Must inherit a type:
        * Boolean, Date, Number, String, Array or Object
        *
        * (or another custom type one of which has an inheritance chain which resolves to a primitive type)
        *// 
        email: {
          type: String, 
          minLength: 3,
          validate: function(val){
              return _.isEmail(val);
           }
         }
      },
      properties: {
        firstName: {
          type: String,
          required: true,
          minLength: 5,
          maxLength: 15
        },

        location: {
          type: Object,
          /**
          * Validations are used as follows:
          */
          is_point: true 
        },

        email: {
          /**
           * Email was defined as a custom type
           */
          type: 'email' 
        },

        password: {
          type: String,
          /**
           * The Validate function can be added inline
           */
          validate: function(password) {
             return password === this.passwordConfirmation;
          }
        },

        passwordConfirmation: {
          type: String
        },

        state: {
         type: String,
         enum: ['pending', 'approved', 'denied']
        },

        color: {
          type: String,
          matches: /[0-9a-fA-F]{6}/
      } 
    }
    });
```

Types should be able to be mixed in using behaviors.

``` javascript
behaviors: [
    Polymer.Types.MySQL
]
```

If a property fails validations a message is logged to the console and the value is not set.

**Comment by samccone** [comment]
:+1: to this idea :)

**Comment by MartinsThiago** [comment]
Nice, but could not it be implemented just with a behavior... I mean it would be awesome having it native... but Polymer itself is already a bit big

```
behaviors: [
    Validators
]
```

probably the tools for creating these things we already have :smile:... nope?

**Comment by bendavis78** [comment]
I think this would add API bloat and would make more sense in a behavior. However, I think this use-case (and others) can be solved by allowing custom data types, and offloading custom validation and (de)serialization logic onto that object.

**Comment by MartinsThiago** [comment]
I don't know how it behaves with class
Could also be an alternative:
```
properties: {
        firstName: MyEmailClass
}
```

**Comment by BLamy** [comment]
@MartinsThiago What i'm describing cannot be done using a behavior. It also wouldn't add much to the file size.

A simple change to polymer's setters/getters for properties may yield an API similar to this:
```javascript
modelName: {
    type: String,
    beforeChange: function(values){},
    afterChange: function(newlyInsertedRecord){}
}
```

As you can imagine, these functions would be called before and after the property changes. Thankfully, Polymer, already has an equivalent to afterChange. This is when the `modelName-changed` event is fired. There is a shortcut to bind this event to a function using `observer`.


Unfortunately, there is no such thing as `observer` or `eventName-changed` for beforeChange. One could imagine there being a `validate` function which is to `beforeChange`; what `observer` is to `afterChange`.
```javascript
modelName: {
    type: String,
    observer: '_modelNameChanged',
    validate: '_validateModelName'
}
```

Unlike an `observer` we need to return a value from our function. To solve this we can do one of two things. 

1) Use a Middleware/Promisy pattern

```javascript
_validateModelName: function(values, resolve, reject){
  if (values) {
      resolve(); // The value will not be set until resolve() is called. 
  } else { 
      reject();
  }
```

2) Don't make validate the result of an event. Instead make it a synchronous call. 
```javascript
modelName: {
    type: String,
    observer: '_modelNameChanged',
    validate: function(values){
        return true;
    }
}
```

I went for option 2 in the OP, as validations should be quick operations. Therefore, it would probably be best to avoid the complexities of async.

After all this one would be able to do something like 
```html
<link rel="import" href="/bower_components/polymer-validations/mysql.html">
```
```javascript
behaviors: [
 Polymer.types.mysql
],
properties: {
    timestamp: {
        type: Integer,
        validate: 'TIMESTAMP'
    }
}
```

Any value assigned to my `timestamp` property is a valid Unix timestamp as defined by the 'TIMESTAMP' function inside of Polymer.types.mysql




For bonus points, I went on to talk about how we can group validation functions into custom types and compose them using behaviors.

**Comment by BLamy** [comment]
Since I feel pretty strongly about adding this to polymer i've began writing my own fork with validations. 

My plan eventually implement two new extensions to Polymer.Base.
1) rules - can be used to define a validation rule and used inside of a property
2) types - can be used wrap rules together to define a 'type'. And be used in place of the primitives that polymer can serialize and unserialize natively. 

Here is the fork:
https://github.com/Polymer/polymer/compare/master...BLamy:master

So far I have rules working adding ~50 lines to the code base. After writing a few more test I may submit a PR.

**Comment by BLamy** [comment]
https://github.com/Polymer/polymer/pull/2677

**Comment by bendavis78** [comment]
Personally I'm not a fan of the `types` dict on the Polymer object -- it seems to add a lot of bloat, and calling it "types" is confusing if it works differently from the native types (eg, `type: Date`). We already have a way of defining custom "types" in javascript (that being a simple constructor). Why not just have a base polymer type that can be extended to create custom types, and those custom type implementations could have their own validators, serializers, and deserializers? That way the Polymer object API doesn't have to change at all:
```javascript
var Email = Polymer.Base.extend(Polymer.Type, {
  nativeType: String,
  validate: function(val){
    return _.isEmail(val);
  }
});

Polymer({
  is: 'x-foo',
  properties: {
    email: {
      type: Email
    }
  }
});
```

**Comment by zoechi** [comment]
Interesting idea. Where would you handle validation errors (for example show an indicator in the UI for a related input element).

**Comment by BLamy** [comment]
@bendavis78 I really like your approach, however, after playing with a couple of different approaches I highly recommend against the inline 'validate' method in your custom type. Validation rules are compossible meaning more then one can be set to a property. Types are not. Polymer considers using inheritance over composition to be an anti-pattern. 
My fear is new people would create classical inheritance of types and ignore that validation rules exist all together. 




@zoechi You should look at the pull request that I reference in this thread it has video tutorials covering most usecases.

**Comment by zoechi** [comment]
@BLamy 
- you are right about compoability
- I meant @bendavis78 idea is interesting but ... (see previous line). I saw your videos already. Great work!

**Comment by TimvdLippe** [comment]
This is now possible in Polymer 2 with overriding `_setProperty`: http://jsbin.com/foliqiwaga/edit?html,console,output For documentation check out https://www.polymer-project.org/2.0/docs/api/elements/Polymer.Element#method-_setProperty
