### ISSUE TITLE
polymer 1.1.5: Uncaught TypeError: Polymer.Base.mixin is not a function

### ISSUE THREAD

**Issue by flyntde** [Polymer/polymer#2601]
This error seems to only occur on Chrome (Version 46.0.2490.71 (64-bit)) on my macbook.  I cannot reproduce on Ubuntu Linux with same version of Chrome.  I also cannot reproduce this using Safari Version 9.0 (11601.1.56) on the same macbook.  

Specific line of code is 1275 in polymer.html.

For a simple app that I can use to demonstrate the problem, see: https://github.com/flyntde/poly.git

It is just using web components-lite.js and the paper-badge element.  In Chrome, I see the text 'count' but not the badge, and I see the error message (Polymer.Base.mixin is not a function polymer.html:1275).

**Comment by flyntde** [comment]
Another bit of information:  I serve the app via browser-sync; when I visit the external site (explicit IP address in url), I cannot reproduce the problem. When I visit http://localhost:5000, I see the error.  

Perhaps this only happens to me on my mac or is a timing issue?

**Comment by ebidel** [comment]
@flyntde please post a working jsbin using https://polygit.org/ so we can test.

**Comment by arthurevans** [comment]
The repro in the repo is quite simple. The code works fine in jsbin:

http://jsbin.com/fuyasah/edit?html,console,output

Sounds like the issue is specific to browser sync?

**Comment by flyntde** [comment]
@arthurevans 
> Sounds like the issue is specific to browser sync?

Perhaps.  This is a curious problem, but I think it is not a problem with polymer.  

For some reason, localhost:5000 using chrome on my mac causes the error I have described.  On a different mac, there is no problem.  It **only** occurs when I run browser-sync and then access localhost:5000 on chrome.  If I change the port to say 5009, the problem goes away.  If I use safari on localhost:5000, the problem goes away.  If I use 127.0.0.1:5000 on chrome, the problem goes away.

For some reason, localhost:5000 + browser sync + chrome + polymer.html on my mac is jinxed.  Any other combination will not exhibit the problem.  I cannot determine the problem but I will just switch to a different port.

**Comment by ebidel** [comment]
Going to close then :)
