### ISSUE TITLE
paper-menu tap event not fired at the first click on the inner elements in Safari and Firefox

### ISSUE THREAD

**Issue by morganwu** [Polymer/polymer#2605]
I have the issue in Safari(Version 9.0.1 ) and Firefox( Version 36.0.1 ), but not in latest Chrome. It can be reproduced in [polymer-starter-kit](https://github.com/PolymerElements/polymer-starter-kit) project, if you click exactly on the icon or text inside a paper-menu, nothing happen, but it works when you click it again. And it's the same with icon button as I tested in my environment.

**Comment by rubenstolk** [comment]
+1 This issue is severe, breaks user experience in Safari (I can at least confirm Safari on Mac, haven't tested Firefox much)

**Comment by rubenstolk** [comment]
https://github.com/PolymerElements/paper-menu/issues/27

**Comment by diddledan** [comment]
gist of a minimal element that exhibits the behaviour in safari 9.0.2 (11601.3.9) on os x el capitan, firefox 43.0 on the same mac (I'll download 44 nightly later today to check there): https://gist.github.com/diddledan/18e1a3889a6ba014469e

**Comment by Giggiux** [comment]
I think this was fixed in PolymerElements/paper-menu#31

**Comment by TimvdLippe** [comment]
I think so as well, closing per above comment. If you can still reproduce this, please reopen with an updated JSBin based on http://jsbin.com/luhaxab/edit?html,output
