### ISSUE TITLE
Native shadow dom prevents ripple on page load

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#2607]
1. Load https://elements.polymer-project.org/bower_components/paper-button/demo/index.html?dom=shadow (not native sd is enabled)
2. Click a button. You will not see a ripple.
3. Click it again. You will see a ripple!

Gestures stuff  (https://github.com/Polymer/polymer/blob/master/src/standard/gestures.html#L199) seems to be eating the first click. Subsequent button clicks ripple dandily!

**Comment by azakus** [comment]
I think this is actually caused by paper-ripple being created dynamically.

**Comment by azakus** [comment]
This is the real bug: https://github.com/PolymerElements/paper-behaviors/blob/master/paper-ripple-behavior.html#L84

**Comment by azakus** [comment]
In native Shadow Dom `domContainer`, the shadowroot, will not contain `target`, the host element.
I'm not sure why this check even exists.

**Comment by azakus** [comment]
This issue was moved to PolymerElements/paper-behaviors#42
