### ISSUE TITLE
Custom css properties don't work in ::content style

### ISSUE THREAD

**Issue by govis** [Polymer/polymer#2608]
Take paper-menu.html for example, add a style to change selected item's background color:
<pre><code>.selectable-content > ::content > *.iron-selected {
    background-color: red;
}</code></pre>
It works, but not if you do it with the custom css property:<pre><code>.selectable-content > ::content > * {
    --paper-item-selected: {
        background-color: red;
    };
}</code></pre>

Use the default paper-menu demo page to test it.

It does work when defined at the root of paper-menu.html
<pre><code>&lt;style is="custom-style">
    :root {
        --paper-item-selected: {
            background-color: red;
        };
    }
&lt;/style></code></pre>

Might also be related to #2596

**Comment by azakus** [comment]
This is a known limitation of the custom styling shim: https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-properties-shim---limitations-and-api-details

Essentially, it is prohibitively expensive to recalculate styling information dynamically, and distributing elements via `<content>` is a very dynamic process.

@sorvell for review.

**Comment by azakus** [comment]
Closing due to age, and a known limitation.
