### ISSUE TITLE
JSON attributes with non-primative values are not de-serialized properly 

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#2609]
This is an issue affecting `<google-map>`

In the following example, `additionalMapOptions` will not be de-serialized into a JSON object because of the value `google.maps.ControlPosition.TOP_RIGHT`. If you substitute a Number val (e.g. `3`). It works.

```
<google-map additional-map-options='{"zoomControlOptions": {"position": google.maps.ControlPosition.TOP_RIGHT}}'>
```

**Comment by ebidel** [comment]
Technically, `JSON.parse('{"zoomControlOptions":{"position":google.maps.ControlPosition.TOP_RIGHT}}')` throws an error in JSON.parse. Not sure what we want to do about this.

**Comment by ebidel** [comment]
Feel free to close if there's nothing we can do.

**Comment by arthurevans** [comment]
Does it not work if it's quoted? To be valid JSON it'd have to be: 

    "position": "google.maps.ControlPosition.TOP_RIGHT"

**Comment by ebidel** [comment]
In the maps api, `google.maps.ControlPosition.TOP_RIGHT` resolves to an enum value. A string is valid JSON  but wouldn't set position correctly.

**Comment by azakus** [comment]
Wouldn't the provided JSON have to use the enum's value? If we have to look up variable values from the runtime, that isn't JSON anymore, but something that needs to use `eval`.

**Comment by jongeho1** [comment]
I do encounter this a lot using polymer and in nodejs and have to comply with valid json and store the dotted path to an object reference as a string. For most cases, using a common behavior function (similar to the below) in a computed property function works out well for me. 

```javascript
pathToReference: function (obj, dottedPath) {
                try {
                    return dottedPath.split(".").reduce(function (o, x) {
                        return o[x]
                    }, obj);
                } catch (excep) {
                    return null;
                }
}
```

Be interested to know alternatives.
