### ISSUE TITLE
getContentChildren API docs should be clearer

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#2612]
API docs say, "CSS selector to choose the desired `<content>`."

This is a little confusing because each content element may contain a selector in its `select` attribute, but we don't match _that_ selector, we need to specify a CSS selector that selects the content element itself.

Maybe say:

```
CSS selector that matches the desired <content> element. For example, the element:

    <content id="content1" select=".stuff"></content>

Matches the selectors `#content1`  or `content[select=".stuff"]`.  
```

**Comment by samccone** [comment]
yes to this :+1:

**Comment by abdonrd** [comment]
:+1:

**Comment by TimvdLippe** [comment]
Still an issue in the legacy docs: https://www.polymer-project.org/2.0/docs/api/mixins/Polymer.LegacyElementMixin#method-getContentChildren
