### ISSUE TITLE
Document Polymer.DomApi

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#2613]
Somehow, we need to make this show up in the API docs:

http://polymer.github.io/polymer/

It's not there. It has a ton of methods and properties. Some of which aren't in the docs or the Primer, like `queryDistributedElements`.

**Comment by ebidel** [comment]
@garlicnation @azakus can we automate this gh-pages deploy when new releases are cut. I was worried this would happen with the API docs :\

**Comment by garlicnation** [comment]
@ebidel The problem is using cdn.rawgit to try and get a master version of the docs. Since the result is cached, repushing won't even fix the issue.

**Comment by garlicnation** [comment]
We have to change where the docs load from to point to a source that can give us true HEAD

**Comment by ebidel** [comment]
Serving from cdn.rawgit is clever! What about setting the the URL to i-c-p in JS
based on the day? That would cache bust it but keep around for a reasonable period of time.

**Comment by ebidel** [comment]
I misunderstood @arthurevans's original comment. Looks like `Polymer.DomApi` just needs to be documented.

**Comment by arthurevans** [comment]
Exactly. I think it's actually documented, but hydrolysis doesn't seem to process them.

**Comment by arthurevans** [comment]
OK, moving to hydrolysis and bumping, because we really need these docs.
(Automatically updating the API reference would be REAL HELPFUL too, because at the moment I think it's several releases out of date.)

**Comment by arthurevans** [comment]
This issue was moved to Polymer/hydrolysis#190
