### ISSUE TITLE
Eliminate needless jargon is the element catalog

### ISSUE THREAD

**Issue by CSEMike** [Polymer/polymer#2615]
The Polymer element catalog is extremely useful. It's my first stop when searching for how to express my UI using Polymer elements.
  https://elements.polymer-project.org/browse?package=platinum-elements

A frustration, however, is navigating the top-level jargon. What's a Gold element, and why is it different than a Neon element? Is the element I'm looking for a Molecule, or an... Iron something?

I know there's some internal theory as to why these have different names, but as a user, the need to internalize Polymer jargon to understand the difference seems needless.

I'm writing to request a flat list that is presented without jargon. I would like to use command-F in my browser to search for keywords like 'popup'. This would greatly accelerate my use of the Polymer docs and would be much appreciated.

**Comment by ebidel** [comment]
This issue was moved to Polymer/polymer-element-catalog#201
