### ISSUE TITLE
Paper dropdown menus near the bottom of the window should drop up

### ISSUE THREAD

**Issue by CSEMike** [Polymer/polymer#2616]
Paper dropdowns near the bottom of the window always open down, creating a compressed scroll area that's very difficult to navigate. (This is doubly challenging on OSX, wherein scroll bars are invisible by default.)

A video illustrates this issue in the demo page --
https://drive.google.com/file/d/0B8dway2WcUoSNWZrcFc3LVI0aGM/view?usp=sharing

I'd expect the behavior of polyer dropdowns to match other UI dropdown widgets and drop 'up' rather than down if the dropdown is too close to the bottom of the window and has more room above than below.

**Comment by miztroh** [comment]
+1!

**Comment by azakus** [comment]
This issue was moved to PolymerElements/paper-dropdown-menu#85
