### ISSUE TITLE
Polymer.html should self-contained

### ISSUE THREAD

**Issue by indolering** [Polymer/polymer#2617]
`polymer.html` imports both mini and micro, adding 3 round trips to the server before content can be stamped out.  While this may be desirable during development, the deployment version of Polymer should be self-contained.

**Comment by ebidel** [comment]
We recommend using vulcanize for productionizing apps.

**Comment by indolering** [comment]
But there are time when it is difficult to include Polymer within the app, for example, if you need to inject data into the element.  This is a common pattern with unit tests and would preclude those tests from being run on the "production" version of the app.  You can just vulcanize Polymer proper but most libraries include a minified version of the library in the standard distribution.

**Comment by indolering** [comment]
> You can just vulcanize Polymer proper

In our deployment model we opportunistically load common libraries (i.e. lazy loading at the login page) and then reuse the same URLs later on.  Now I'm stuck maintaining a custom version of Polymer for production ... as is anyone providing a CDN for Polymer.
