### ISSUE TITLE
getDistributedNodes behavior is inconsistent.

### ISSUE THREAD

**Issue by ktiedt** [Polymer/polymer#2618]
```
        <div class="no-show">
          <content id="title" select=".console-title"></content>
        </div>
        // this.$.title.getDistributedNodes() == []
```

vs
```
          <content id="title" select=".console-title"></content>
          // this.$.title.getDistributedNodes() == [ <div> ]
```

Ultimately this negated my need to call getDistributedNodes() but it was an unexpected behavior...

**Comment by ebidel** [comment]
Can you please post a jsbin of the repo?

**Comment by ktiedt** [comment]
Hmmm, I cant seem to trigger the exact same behavior...  Now I just get 0 lengths for both cases

http://jsbin.com/qodoracofe/1/edit?html,console,output

**Comment by azakus** [comment]
Use `Polymer.dom()` around the content element. https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#dom-api

http://jsbin.com/vocizu/edit?html,console,output
