### ISSUE TITLE
Publish list of reserved property names

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer#2619]
Using a property name that Polymer uses can lead to some very subtle bugs. We should publish a list of reserved public and private properties names that elements should not use. The linter should warn on usage.

**Comment by rodrigogoncalves** [comment]
Just spent an hour trying to debug what came to be the [unadverted] usage of a reserved property name. This will be definitely a helpful documentation.

**Comment by MeTaNoV** [comment]
+1

**Comment by withgallantry** [comment]
+1
Spent better part of a day debugging something that turned out to be a reserved word 'profile'

**Comment by web-padawan** [comment]
Faced this issue for 1.9 today by defining property with name `_serialized`. This stopped working attribute bindings for element.

**Comment by wojinwomacka** [comment]
`lang`  You can use it as primitive property, but not as a function.
