### ISSUE TITLE
Scrolling in element catalog not functioning.

### ISSUE THREAD

**Issue by arcio** [Polymer/polymer#2620]
I'm working in chrome Version 46.0.2490.71 (64-bit)
When viewing the catalog the left-hand column won't scroll.

For instance:
https://elements.polymer-project.org/elements/neon-animation

The page will scroll but the left column will not. You have to zoom out to be able to see the entire list.

**Comment by abdonrd** [comment]
I confirm the problem.

**Comment by ebidel** [comment]
This issue was moved to Polymer/polymer-element-catalog#204
