### ISSUE TITLE
Private properties

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/polymer#2622]
# Use-case

Currently properties allow you to declare specific fields in a Polymer object. These properties are bound to the template and have various useful additions like `observers` and `value`. However, if you want to benefit from these behaviours, without letting the property 'leak' to the declaring parent, you have to use the following method:

``` html
<template>
    <span>{{myBinding}}</span>
</template>
<script>
  Polymer({
    ...
    properties: {
    },
    ready: function() {
      this.myBinding = "My Binding";
      this.async(function() {
        this.myBinding = "Rebound binding";
      }, 1000);
    },
    ...
  });
</script>
```

Above example will initially display `My Binding` and after 1 second `Rebound binding`. This is working as expected, however all other nice things are not available. In order to make that work, the property should be defined in `properties`.
# Proposed API

In order to support such private properties, I propose the following API:

``` html
<template>
    <span>{{myBinding}}</span>
</template>
<script>
  Polymer({
    ...
    properties: {
      myBinding: {
        type: String,
        private: true
      }
    },
    ready: function() {
      this.async(function() {
        this.myBinding = "Rebound binding";
      }, 1000);
    },
    ...
  });
</script>
```

The extra option is called `private` and is by default `false`. Consider the following declaration:

``` html
<template>
    <element-with-private-binding private-binding="{{binding}}"></element-with-private-binding>
</template>
<script>
  Polymer({
    ...
  });
</script>
```

If the private-binding is declared `private: true`, the following effects will happen:
1. When a parent declares the element with the property as value, the binding is not created to the parent. The declaring parent will not receive the new value of `private-binding` when its value is updated. It could also be made more strict by throwing an exception, but that would be up for debate.
2.  When the property of the child is updated, the `{value}-changed`-event will not be fired to the parent. Also when the parent declares `on-private-binding={{callback}}` an exception could be thrown, but that would be up for debate.
# Affected code

I have no experience in these specific parts of the Polymer codebase. So far I found only 1 line which I assume does the notifying. I assume source is the property, but I don't know for certain.
[_notifyEffect](https://github.com/Polymer/polymer/blob/master/src/lib/bind/effects.html#L43) should then become `if (!fromAbove && !source.private) {`

[The function](https://github.com/Polymer/polymer/blob/master/src/standard/effectBuilder.html#L50) that does the `properties` parsing is probably the better place to do this filtering

Probably I missed a lot of things, so please post which parts of the codebase would also be affected.

**Comment by azakus** [comment]
This seems like a reasonable first draft for a design doc.

@kevinpschaaf @sorvell @sjmiles @tjsavage Thoughts?

**Comment by kevinpschaaf** [comment]
By convention we disambiguate "public" and "private" API by prefixing private/protected properties with `_`.  As there is no true concept of "private" in JS, we consciously avoid adding runtime code to try and maintain a closer illusion to private.  The underscore prefix convention serves as a good enough warning to users of the element that they are doing something wrong:

```html
<element-with-private-binding _private-binding="{{binding}}">
                              ^ User knowingly used private API
```

As such, we're unlikely to visit such an API change in the near term.

**Comment by arturparkhisenko** [comment]
:+1: I also met a case when i need private property but all what i found is: https://gist.github.com/robdodson/4e9d836e8bec1e2c5532
as i said in polymer.slack: `Polymer here to simplify webcomponents, but if i use this wrapper thats means only one thing: polymer must simplify this too!?`. Thanks @metanov for discussing this.
Also with this wrapper i have to use jsbin like in this example (wrap(wrap(polymer())())())():
```js
HTMLImports.whenReady(function() {
  (function(document) {
    Polymer({
       //stuff
    });
  })(document);
});
```

**Comment by JeremybellEU** [comment]
@arturparkhisenko thanks for posting the gist. It is indeed a workaround, but if I am not mistaken the variable `foo` in the gist is static for all instances of the element, am I?

**Comment by arturparkhisenko** [comment]
@JeremybellEU http://jsbin.com/konegarime/1/edit?html,console,output

**Comment by javiervelezreyes** [comment]
I also agree that encapsulation is a general good idea to keep simple & clean the public API of a web component. Nevertheless, not always it is a matter of adding new restrictions like 'private' qualifier. On the contrary, less syntactic restrictions would move to creativity.

For example lets consider observers within the properties object. They are essentially private logic. Imagine that observers handlers could be defined inline and not [only] as a string reference. In such manner, they could be delegated to other helper objects or  hidden references within a closure. In code:

     properties : {
         x : {
              type : Number
              value : 0
              observer: function () {  helper.xHandler();  }
         },
         y : {
              type : Number
              value : 0
              observer: function () { yHandler();  }
         }
     }

**Comment by TimvdLippe** [comment]
I think we can close this issue and instead rely on solutions like Typescript: http://www.typescriptlang.org/docs/handbook/classes.html#understanding-private

**Comment by TimvdLippe** [comment]
Closing per above comment.
