### ISSUE TITLE
Paper-input bug in firefox

### ISSUE THREAD

**Issue by NitroBAY** [Polymer/polymer#2624]
Bug with paper-input in last version of firefox (and I don't even dare to talk about IE :-1: I'm doubt about the capocity of Polymer is able to make real project) 
CHROME
![chrome](https://cloud.githubusercontent.com/assets/9869317/10719456/519d519c-7b89-11e5-9a1a-7cdc787298da.png)
FIREFOX
![firefox](https://cloud.githubusercontent.com/assets/9869317/10719457/5482e840-7b89-11e5-8087-32fd2cd1b46c.png)
Here's why it's buggy : 
![bug](https://cloud.githubusercontent.com/assets/9869317/10719462/68a6f762-7b89-11e5-831f-476fa75ce8c6.png)
BTW in chrome autocomplete="off" don't work in chrome neither the way to remove this horrible yellow !! Is that relative to Chrome or .... once again to "Polymer"

**Comment by NitroBAY** [comment]
UP?

**Comment by ebidel** [comment]
This issue was moved to PolymerElements/paper-input#217
