### ISSUE TITLE
Life cycle issue: childElementCount not correct in polyfill'd browsers

### ISSUE THREAD

**Issue by MartinMoizard** [Polymer/polymer#2628]
Writing a wct test to cover a new feature I'm adding to the Polymer Dom API, I noticed a strange life cycle issue with Safari (9.0.1) and Firefox.

The issue appears when creating programmatically a Polymer component. For example, given the following component:

```
<dom-module id="x-focusable">
 <template>
   <div tabindex="1">x-focusable</div>
 </template>
 <script>
   Polymer({
     is: 'x-focusable'
   });
 </script>
</dom-module>
```

The following unit test fails on Safari and Firefox (browers without native shadow):

```
test('Polymer.dom should have one child with a dynamic allocation', function () {
    if (Polymer.Settings.useNativeShadow) {
      return;
    }
    var a = document.createElement('x-focusable');
    Polymer.dom(document.body).appendChild(a);
    Polymer.dom.flush();
    if (Polymer.Settings.useShadow) {
      assert.equal(a.childElementCount, 0);
      assert.equal(window.unwrap(a).childElementCount, 1);  // <-- fails here
    } else {
      assert.equal(a.childElementCount, 1);
      assert.equal(Polymer.dom(a).children.length, 0);
    }
    Polymer.dom(document.body).removeChild(a);
  });
```

However x-focusable has 1 div in its definition. I created a branch to illustrate this issue: https://github.com/MartinMoizard/polymer/tree/lifeCycleIssue.

Thank you

**Comment by hypnoce** [comment]
+1

**Comment by azakus** [comment]
This is sort of a known issue: https://github.com/Polymer/polymer/blob/master/src/lib/dom-api-flush.html#L50-L54.

Basically, the ShadowDOM polyfill is hiding the creation of the shadowroot from Polymer's MutationObserver it uses for `Polymer.dom.flush`. You can wait one async call to work around.

**Comment by TimvdLippe** [comment]
This is quite an old issue and I can't find the definition of `window.unwrap` in either the polyfills or Polymer. When trying to reproduce this problem, I was unsuccesful (http://jsbin.com/zulinipoco/edit?html,console,output) This returns 1 for me all the time.

Therefore I think this has been solved along the way. Feel free to reopen with an updated JSBin if you are still experiencing issues.
