### ISSUE TITLE
array-selector: toggling multi attribute causes a TypeError on the next selection event

### ISSUE THREAD

**Issue by jtakacs** [Polymer/polymer#2629]
When an `array-selector` is in single mode and there is an element selected, after switching to multi mode, the `this.selected` array is not initialized, it still holds the previous single element.
The error is caused by line 137, I believe this `if` statement is unnecessary.

```
      // Initialize selection
      if (this.multi) {
        if (!this.selected || this.selected.length) {  // line 137, this should be removed
          this.selected = [];
          this._selectedColl = Polymer.Collection.get(this.selected);
        } // line 140, closing bracket for line 137, this should be removed also
      } else {
        this.selected = null;
        this._selectedColl = null;
      }
```

**Comment by azakus** [comment]
Agreed, `clearSelection` should always clear the selection.

@kevinpschaaf was the intention to try and save the selected value if transitioning from single to multi?

**Comment by TimvdLippe** [comment]
This appears to be fixed in Polymer 2: http://jsbin.com/vihahuqata/edit?html,console,output
