### ISSUE TITLE
Two-way binding annotations in local template do not update `readOnly` properties

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer#2632]
This may be a deliberate design choice, and it's fine if it stays the way it is. However, I would like to submit for consideration the following:

Two-way binding annotations signal an intention from the element author that - even if a property is marked as `readOnly` - the property should be updated when the bound value notifies. Perhaps Polymer should automatically update `readOnly` properties in such conditions.

**Comment by azakus** [comment]
By "local template", I assume you mean the template of the element that has the readOnly property?
I think this would need some additional logic in the notification handling that checked the origin of the notification event.

**Comment by cdata** [comment]
> By "local template", I assume you mean the template of the element that has the readOnly property

Yes.

**Comment by LukeXuan** [comment]
@cdata @azakus 
I'd like to know is this issue related to my question.
When I set property `si` of `my-element` to be `readOnly: true`, and bind `si` to the attribute of `selected-item` of a `iron-list`, which is a child element of `my-element`. It does not update the value of `si`.

**Comment by LukeXuan** [comment]
Addition:
When I bind `someReadOnlyProp` to a child element, it won't work.
When I bind `someReadOnlyProp.subProp` to a child element, it works.
I think these two behaviour is inconsistent.

**Comment by kaste** [comment]
I have a PR for this #3580 ready. My #3551 is a dup of this issue, but it has a better code example why this might be a (really) good change. :cake:

**Comment by TimvdLippe** [comment]
Yup still an issue with Polymer 2: http://jsbin.com/natumubedu/edit?html,console,output
