### ISSUE TITLE
Dom-repeat: Only works in one direction

### ISSUE THREAD

**Issue by quaintcow** [Polymer/polymer#2633]
It'd be super helpful if Dom-repeat could prepend not just append when it's stamping out the templates

**Comment by arthurevans** [comment]
What do you mean? Prepend to what?

**Comment by quaintcow** [comment]
What I mean is that templates are stamped downwards. Is there a way to do it in reverse?

**Comment by ebidel** [comment]
I think explaining your use case would be helpful :)

**Comment by quaintcow** [comment]
I'm building a real-time application using Firebase. You can think of it as being similar to twitter where new tweets appear at the top

**Comment by zoechi** [comment]
You can specify a sort function https://www.polymer-project.org/1.0/docs/devguide/templates.html#filtering-and-sorting-lists

**Comment by arthurevans** [comment]
I think that if you have a repro case where you can show that your app isn't responsive when you hit N entries, you should attach it. I'm not sure whether that's going to be the case for a reasonable number of posts (say, 200).

Most twitter-style web apps show a comparatively small set of posts at one time, and lazy-load in chunks. Twitter itself lazy loads 20 posts at a time on the bottom as you scroll down. At the top, it displays a  **View _N_ new Tweets** button and lets the user decide when to load stuff. 

Subjectively, around 200-300 posts the list is getting a little unwieldy. It appears that if you press the "load new" button it trims the list to the last 200 posts (I'm doing `document.querySelectorAll('li.stream-item')` which appears to select the individual posts).

From a UX point of view, if you load new posts at the top without an explicit user request, you're likely to throw off the scroll position where the user is reading.

Note the the Twitter API returns results in reverse-chronological order in the first place, so it doesn't need to sort results. If you control the back end for your application, you might want to think about the API. This document, while specific to Twitter's API, outlines some of the issues with paging a timeline and how Twitter has addressed some of these challenges.

https://dev.twitter.com/rest/public/timelines

**Comment by quaintcow** [comment]
okay thanks to everyone for the help. I'll likely do some more research into reversing the Firebase results
