### ISSUE TITLE
Polymer.dom(e).localTarget irregularity

### ISSUE THREAD

**Issue by maxsteenbergen** [Polymer/polymer#2634]
While I was trying to get data binding up and running using fire(), I noticed that there's something weird going on with the Event object. Whenever I dump the entire (Polymer-wrapped) Event in the console, the ``localTarget`` entry is bound to the DOM element I'd expect and want. However, when I dump the localTarget directly, it is bound to the child element firing the event, i.e. the ``rootTarget``. I've attached my code below, along with the console output it produces. 

````
updateLatLonValues: function(e){
  console.log(Polymer.dom(e), Polymer.dom(e).localTarget)
}
````
produces the following console output:
![screen shot 2015-10-27 at 15 36 59](https://cloud.githubusercontent.com/assets/574278/10761212/9b8d62e6-7cc0-11e5-9506-79d4fe3a6efc.png)

**Comment by JeremybellEU** [comment]
Hey @maxsteenbergen ,

I have tried to reproduce this issue, but with no success. When I output both objects, I correctly see that the event.localTarget corresponds to the second output. Are you able to write a minimal test case which shows the irregularity?

This behaviour is actually tested for parent and parent-parent relation [here](https://github.com/Polymer/polymer/blob/master/test/unit/polymer-dom.js#L545) and [here](https://github.com/Polymer/polymer/blob/master/test/unit/polymer-dom.js#L558). The tests have not failed on CI nor my local environment.

**Comment by azakus** [comment]
`localTarget` and `rootTarget` are getters, so if you click them in the inspector to "open" them, they will run after the event was dispatched and give you the wrong results.

The only value you can trust those values to be correct is inside of an event handler.
