### ISSUE TITLE
How would you bind an Array to an Element and notify the change, if you construct it by FactoryImpl?

### ISSUE THREAD

**Issue by fooloomanzii** [Polymer/polymer#2636]
If I create elements by FactoryImpl, and give an array as an argument, then I can not observe the change on the array, even if I use the recommended methods. I also tried to use notifyPath or the observer to catch the changeRecord, but it's always just observed on creation and not after. 

Here is an example: 
http://plnkr.co/edit/SUbJisDSF8hIYzb0z6Av?p=preview

The DOM-structure would show, that the elements array, which was used to create the element, had changed by any mutation. But it is not notified

**Comment by ebidel** [comment]
Please ask questions like this on Stackoverflow or Slack.

**Comment by fooloomanzii** [comment]
It is not documented
