### ISSUE TITLE
Enhancements to DOM Distribution.

### ISSUE THREAD

**Issue by PaulHMason** [Polymer/polymer#2640]
Hi

Not quite sure where to put this, or if it's been addressed before (I can't find anything in the Polymer issues). Basically, what I want to be able to do is intelligently distribute content elements in a Polymer element template. e.g. If I have a parent custom element that can host child custom elements:

```
<my-parent>
  <my-child></my-child>
  <my-child></my-child>
  <my-child></my-child>
</my-parent>
```

I want to be able to define a parent template something like this:

```
<dom-module id="my-parent">
  <template>
    <!-- Some Elements -->
    <h1>A Heading </h1>

    <template is="dom-repeat" items="my-child">
      <!-- Some other elements that bind to child properties -->
      <span>{{item.property1}}</span>

      <!-- Insert the actual my-child element here -->
      <content select="{{item}}"></content>

      <!-- Some other elements that bind to child properties -->
      <span>{{item.property2}}</span>
    </template>
  </template>
</dom-module>
```

Where the dom-repeat uses a selector to create the items to iterate over.

Are there any plans for this type of enhancement?

**Comment by timeu** [comment]
There is proposal for slot based shadow dom/content distribution which migh help with your use case: 

https://lists.w3.org/Archives/Public/public-webapps/2015AprJun/0184.html
https://www.webkit.org/blog/4096/introducing-shadow-dom-api/

Safari/Webkit already has implemented it in Nightly and I guess the Chrome team is also working on it. 

Regarding Polyfill in webcomponents.js/Polymer @robdodson said: 
> "there's a branch of Polymer with shady dom support for slots that we'll be releasing soonish."
(source: https://plus.google.com/+RobDodson/posts/8dbEcU8xrNP)

**Comment by azakus** [comment]
@timeu Slot would not actually help in this case. Both `<content select>` and `<slot name>` work with declarative syntax (content with anything that can use querySelector, slot only with a `slot` attribute on the node).

What you're asking for would require an imperative content distribution API, which is a scheduled topic for ShadowDOM version 2.

As a workaround, if you can find a way to mark your elements declaratively, then you can use multiple `<content select>` elements.

**Comment by TimvdLippe** [comment]
Closing this in favor of the specification discussions over at https://github.com/w3c/webcomponents/issues?utf8=%E2%9C%93&q=label%3Ashadow-dom+ Feel free to open an issue there to start/continue the discussion on imperative slot distribution.
