### ISSUE TITLE
Gestures.handleNative sometimes throws "Unable to get property mousedown of undefined or null reference" in IE11

### ISSUE THREAD

**Issue by wicksell** [Polymer/polymer#2641]
When using `<paper-dropdown-menu>` and selecting an item in IE11 I get the error "Unable to get property mousedown of undefined or null reference". The error originates from `Gestures.handleNative`. The statement `node[GESTURE_KEY]` is undefined. If i add the following line 
```javascript
    if (!gobj) gobj = unwrap(node)[GESTURE_KEY];
```
everything works perfect. So the problem seems to be that the node is not wrapped when passed to `Gestures.add` but is when the event is received.

**Comment by wicksell** [comment]
I have investigated my problem further and found that it may be related to #1001. A change to iron-overlay-behavior adds a gesture listener on document, see PolymerElements/iron-overlay-behavior@ad1cda00708d1a79539b7ef511454d576ed779f6. On registration document is not wrapped but webcomponentsjs always wrap events when Shadow DOM is polyfilled so in `Gestures.handleNative` the event target is wrapped and thus the property `GESTURE_KEY` is not available.

**Comment by azakus** [comment]
Just need to land https://github.com/webcomponents/webcomponentsjs/pull/434 first, then I can make this work as expected.
