### ISSUE TITLE
Support Edge on Windows

### ISSUE THREAD

**Issue by gedw99** [Polymer/polymer#2643]
Its weird that the browser compat page does not even mention Edge

https://www.polymer-project.org/1.0/resources/compatibility.html

Can you please let us know, as its really important to know for doing real projects

**Comment by ebidel** [comment]
Isn't Edge assumed in IE 10+?

**Comment by moderndeveloperllc** [comment]
@ebidel Most of the sites like caniuse, Are We Componentized Yet, et al. break them out. I think it has to do with the fact that they are on different development paths and code bases. Components support may never make it's way into IE11, but only into Edge. Not an immediate issue, but could cause confusion in the future at any time.

**Comment by gedw99** [comment]
What do you mean "in".

On Windows 10, Edge and IE10 are different browsers.  I can start them up as different apps. I have no idea if they shared code bases.
IE 10 is basically there so companies can run their old Active X stuff.
Edge is there to save us giving up on Windows browser :)

Its an immediate issue if your trying to write code on Windows. For example at the moment 2 polymer apps dye on Edge.

**Comment by ebidel** [comment]
When I read "IE 10+" looking at a library's support, my assumption is that it will work in newer versions of IE. For me that includes Edge, but I understand the distinction and that Edge is a different engine. We should probably be more precise on the compat table. There are a couple of open bugs to make that page more friendly.

**Comment by gedw99** [comment]
@ebidel 
Yep please.  Its also a compliance thing. Its hard hard sell to the Managers if the page has no Edge.

**Comment by arthurevans** [comment]
For the short term, you can show your manager the note on that page that reads: `* includes Edge`. We'll definitely work on making it more manager-friendly, though :grinning:

**Comment by gedw99** [comment]
Thanks. I actually did not see that.
The point is that on windows they are completly different browsers. For me its  ambiguous.
