### ISSUE TITLE
this.push doesn't notify changes to computed property

### ISSUE THREAD

**Issue by lapteuh** [Polymer/polymer#2644]
I have array property and computed property that depend on array. When i use `this.push()` method, my computed property doesn't recompute.

**Comment by ebidel** [comment]
Please include a jsbin that repos the issue.

**Comment by chiefcll** [comment]
We're seeing something similar... We think its related to #2007 - The changes now send notification changes of array.#1.prop rather than array.1.prop - so if you set up any observer on that property without the # it won't get called.

**Comment by samccone** [comment]
I think this is also related
https://github.com/Polymer/polymer/issues/2556

**Comment by chiefcll** [comment]
http://plnkr.co/edit/5UW4wKanTR5v9Z7P79P3?p=preview

**Comment by ebidel** [comment]
Using https://rawgit.com/Polymer/polymer/v1.1.5/polymer.html in that demo, I see two console logs
Using https://rawgit.com/Polymer/polymer/v1.2.0/polymer.html, I see one :(

This is a regression.

**Comment by ebidel** [comment]
So I'm told from @kevinpschaaf this was never supposed to work. It's even documented as such: https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#array-binding.

> binding to or observing array indices is not supported.  i.e. `observer: [ 'myArrayChanged(myArray.1.value)' ]` and `{{myArray.1.value}}`

> that was never intended to be supported, so the fact that it changed is a result of relying on an unsupported feature

> reason is that all path notifications for arrays are done as keys; observing an index (i.e. as an observer dep or binding) would require reverse lookup from key back to index, which is an O(n) operation for each

**Comment by ebidel** [comment]
Closing as per the observation in the previous comment.

**Comment by lapteuh** [comment]
@ebidel please see: http://plnkr.co/edit/iNVTULU8w4bXxjyxunsd?p=preview

**Comment by kevinpschaaf** [comment]
@lapteuh `computeMyComputedArray(myArray)` only re-computes when the `myArray` reference itself changes.  To re-compute on any deep change to `myArray`, use `computeMyComputedArray(myArray.*)`:

http://plnkr.co/edit/348Amty1bSJMEZX5g4dy?p=preview

**Comment by lapteuh** [comment]
@kevinpschaaf thanks.
