### ISSUE TITLE
`getEffective*` methods not working as intended?

### ISSUE THREAD

**Issue by jakemac53** [Polymer/polymer#2648]
Not entirely sure if I am just misinterpreting what these methods are supposed to do since there isn't much documentation, but a few tests are failing in the Polymer Dart package:

https://github.com/dart-lang/polymer_interop/blob/f2607ff4df413b7ba3cfb6f259a082225f32cc60/test/polymer_base_test.dart#L462

html for the test is here https://github.com/dart-lang/polymer_interop/blob/f2607ff4df413b7ba3cfb6f259a082225f32cc60/test/polymer_base_test.html

**Comment by arthurevans** [comment]
Doc site just updated:

https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#effective-children

Offhand, the test looks wrong to me -- shouldn't the order for the first test be a, b, c, d, j, e, h, i, k, l?

**Comment by jakemac53** [comment]
heh, I think that is the ordering which I was getting in the test, so it seems that I just was misinterpreting what the functions are supposed to do

**Comment by jakemac53** [comment]
Now that I have some docs to look at that should help :)

**Comment by jakemac53** [comment]
Just to be clear, the elements should be in the order in which they originally appeared in the light dom, not the order in which they appear after dom distribution

**Comment by jakemac53** [comment]
Yes this makes sense now, thanks for the clarification

**Comment by arthurevans** [comment]
I think they should be ordered as-distributed (@sorvell can correct me here). But from your tests, it looks like the effective children of `#child` post-distribution should be as I wrote above -- for example, I can't see any reason why `a` would not be the first child.

Put another way, the children should be returned in the same order they're rendered in (I think?).

Polymer core probably needs a few more unit tests here.

**Comment by jakemac53** [comment]
So the template for `distributed-element` looks like:

```html
<content select=".foo" id="selected"></content>
<content id="default"></content >
```

Since the div with `c` as the text has the `foo` class it gets put before everything else.

**Comment by jakemac53** [comment]
That being said I think the current behavior is actually correct after reading the documentation, it is giving you the effective light dom basically, not the effective local dom.
