### ISSUE TITLE
Clarification on nested templates, conditionals and side effects

### ISSUE THREAD

**Issue by michaelsbradleyjr** [Polymer/polymer#265]
With reference to sample code:

http://jsbin.com/aqaFOCa/1/edit

https://gist.github.com/michaelsbradleyjr/6400707

The template which repeats over `multiples` is nested inside a template which is predicated on the value of `base` being an even number.

However, in cases where `base` is not even, though the nested template is not rendered (the template for the non-even case is rendered instead), the `t1Changed` method for the `test-nested-li` elements is still being called, as evidenced in the "Log" section at the bottom of the page.

This might be seen as a surprising result inasmuch as wrapping JavaScript code in an `if` will prevent said code from causing side effects when the expression inside `if (...)` evaluates to something falsy.

However, given the nature of MDV bindings, perhaps this kind of behavior is expected and needs to be planned for when writing methods like `t1Changed`.

Clarification would be appreciated.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) release of Polymer - please feel free to re-open if this is incorrect.
