### ISSUE TITLE
Several icons not show in Firefox

### ISSUE THREAD

**Issue by shawnsz** [Polymer/polymer#2651]
Hi,

I'm using Polymer in my website. It's cool. But I found some icons not working in Firefox. Please take a look:
https://elements.polymer-project.org/elements/iron-icons?view=demo:demo/index.html

Several icons not show in Firefox. 
browser version: 41.0.2
OS: Windows 7 Professional Service Pack 1.

works fine in Chrome and IE 11

icons:flight-takeoff
icons:event-seat
icons:gif
icons:indeterminate-check-box

Thanks!
Shawn

**Comment by azakus** [comment]
This issue was moved to PolymerElements/iron-icons#32
