### ISSUE TITLE
Allow late upgrading of bound elements

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#2653]
Currently elements that are bound (i.e. have data pushed to them by their host) must be upgraded prior to data propagation.  This is because the act of upgrading installs accessors on the element via its prototype, which may be shadowed by data values propagated to the instance earlier by the host.

This is typically not an issue when an element imports all of its dependencies before registering, which guarantees that when a host stamps its template, the children upgrade prior to the host pushing its data.

However, to support lazy upgrade use cases, elements would need to support reading instance values for properties with accessors, deleting the instance values, and passing them into the initial configuration / setters.  This should likely be an option via an attribute (e.g. `late-bind`) so that all instances aren't taxed with this extra processing.

**Comment by ebidel** [comment]
+1. In :santa:'s lazy loading system, we had to use `getAttribute()` to poke at values before elements were upgraded and bound.

**Comment by samccone** [comment]
:+1: oh this would be magical :sparkles:

**Comment by robdodson** [comment]
yeah very much want this!

**Comment by tpluscode** [comment]
:+1:

**Comment by srikkbhat** [comment]
+1.

Couple of observations. Reference plunker: http://plnkr.co/edit/4WEsWabS3nNSacyimwst

1. The boolean property is pushed to lazy element - `show-boolean`. 
2. The value initialization of the property in lazy element is ignored - `my-element-two.shared-value`. This looks odd.

**Comment by TimvdLippe** [comment]
When using async HTML imports I encountered this issue too. I have tried to dig into the code to develop a solution, but sadly it is not clear enough where the issue is and how it can be solved.

**Comment by kevinpschaaf** [comment]
Essentially a dupe of https://github.com/Polymer/polymer/issues/2348, which has been addressed in https://github.com/Polymer/polymer/pull/3417.
