### ISSUE TITLE
Problem extending "tr" with td contents in template

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#266]
The following was posted as a Custom Elements issue, but `<polymer-element>` should have the same problem:

Not high priority but I thought I'd pass this along. We had a bug report from trying to make a custom element that extends "tr". The problem is illustrated by this example:

```html
<element name="x-game" extends="tr">      
<template>
  <td>{{game.id}}</td>
</template>
```

Unless the browser has native `<template>` it won't work because the TD is not allowed there. So this is only an issue with the polyfill. If you have native template, it should work as expected.

MDV has a similar problem and works around it by supporting the template *attribute* on table nodes. That lets you put templates in tables, but I can't see how that would help here. The best idea I can come up with is to build the DOM imperatively. Which might be okay if this problem doesn't happen frequently.

(Feel free to close if this outside the scope of custom elements! I couldn't quite figure the best place to report it. Original discussion is here:
https://groups.google.com/a/dartlang.org/forum/?fromgroups#!topic/web-ui/5bCCd_M0nps)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) release of Polymer - please feel free to re-open if this is incorrect.
