### ISSUE TITLE
Custom properties with 'var' in the value aren't applied

### ISSUE THREAD

**Issue by robdodson** [Polymer/polymer#2660]
ex: `--my-font: 'Varela Round'` will not be applied because of the word `Var` in `Varela`. @sorvell :cry:

**Comment by ebidel** [comment]
From http://stackoverflow.com/questions/33445674/how-to-get-google-fonts-to-work-in-polymer-1-1-web-component

**Comment by JeremybellEU** [comment]
Well that was an evening of edge-cases and testing, but I think I cracked it now. #2662 shows the reported fixed behaviour.

The multiple mentions are due to FireFox and Chrome parsing css selectors differently, but unrelated to the actual purpose of testing. Sorry for the spam.
