### ISSUE TITLE
Sub-Arrays notification propagation and binding

### ISSUE THREAD

**Issue by manfield** [Polymer/polymer#2665]
We have a huge doubt.
It deals with sub-array elements' values binding.

In the next example:
http://plnkr.co/edit/dOt2T1OcMkw2kp5g72MY?p=preview

You may see that binding works as expected when the value of array's item changes (clicking on TEST1).
It doesn't when the the value belongs to an item of an array's item (look what happens when you click on TEST2 button: the change is notified - if you look at js console - but binding does not work).

So, doubt is: is this the expected behavior and we have to find a workaround according to the situation, or may it be considered a bug?

Thanks a lot

**Comment by azakus** [comment]
Hmm, The observer actually saw the change, so I wonder if this is actually just a bug in the "needs to refresh" algorithm.

@kevinpschaaf Simpler example: http://jsbin.com/sinule/edit?html,console,output

**Comment by kevinpschaaf** [comment]
Bindings such as `[[items.0.value]]` are not supported.  

Please note the docs related to binding to specific array elements by index for alternative ways to accomplish this: https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#array-binding
