### ISSUE TITLE
Change paths are ambigious

### ISSUE THREAD

**Issue by David-Mulder** [Polymer/polymer#2668]
Let's say we have an array `[1,2,3]` and then call `.unshift(0)` on it, when next observing for changes on the array both item number 0 and number 1 will give a change path `arrayName.#0`. Either `arrayName.#3` or `arrayName.0` for the first item would make sense, but `arrayName.#0` definitely does not.

Here is an example: http://david-mulder.github.io/leather-editable-list/components/leather-editable-list/demo/changeBug.html

**Comment by kevinpschaaf** [comment]
From code inspection, the issue appears to be that in `_forwardInstanceProp`/`_forwardInstancePath`, you are notifying a _key_-based path (prefixed with `#`) using the _index_ set in `_restructureItems` (https://github.com/David-Mulder/leather-editable-list/blob/master/leather-editable-list.html#L162).

If you remove the `#` from the path in these two cases, does that fix your problem?

**Comment by David-Mulder** [comment]
@kevinpschaaf Ehm, if I change to to not use key-based paths I am notifying the wrong index and the entire component breaks. If you pull and remove the `#` you will see that it doesn't work without at all and more important that with the `#` I am definitely notifying the right path always. The issue is on the observing end.

**Comment by David-Mulder** [comment]
@kevinpschaaf Going to close this issue and instead open an issue that we really need some documentation on arrays, their indexes, and `Polymer.Collection`... your solution wouldn't work for obvious reasons, but you were correct in pointing out what the underlying problem was (though I am quite confused how so much could work as well as it did~).
