### ISSUE TITLE
dialog noCancelOnEscKey is broken

### ISSUE THREAD

**Issue by borismus** [Polymer/polymer#2669]
Regardless of whether or not this boolean value is set to true or false, the dialog can always be canceled with ESC.

**Comment by zoechi** [comment]
This should be reported in the GitHub repo of the element. If you look up an element in https://elements.polymer-project.org/ it has a link to the source repo.

**Comment by arthurevans** [comment]
This issue was moved to PolymerElements/iron-overlay-behavior#50
