### ISSUE TITLE
Multiple spaces between selector classes

### ISSUE THREAD

**Issue by tschwartz** [Polymer/polymer#2670]
Currently it seems like there is an issue where multiple spaces between classes will cause that selector to not be applied.
```
.parent .child-0 {}
.parent  .child-1 {} // double space between classes in selector will not be applied to element
```
Once fixed of course things are fine but was quite painful to track down.

**Comment by samccone** [comment]
@nazar-pc Does one of your outstanding PRs resolve this?

**Comment by nazar-pc** [comment]
I've just added one for this: #2671
A lot of work with different aspects of CSS parser recently :smile:
