### ISSUE TITLE
Different results based on the order of element properties

### ISSUE THREAD

**Issue by nomego** [Polymer/polymer#2674]
I just encountered a scenario where the order of the element properties in the `properties` object made a difference to the behavior of the element.

I believe that this is a bug since I haven't read anywhere in the documentation that the property order matters, and a JavaScript object is generally considered unordered, unless it's an array.

Example code at:
http://jsbin.com/zuyuzaqiwe/edit?html,console,output

Once the `iv2` property is registered, the observer is immediately called, even before the `kicker` property is registered. In this case, this causes `kicker` to be undefined as `observe` is run, causing `this.kicker += 1` to turn `kicker` into `NaN`.

This somehow also overrides the default value of `kicker`, since it never gets its `0` value.
In `attached`, `NaN += 1` is still `NaN`, so no change is observed for the actual kick.

However, moving the declaration of `kicker` to somewhere "earlier" in the properties object, the default `0` value is set before the `iv2` observer is run.

(Yes the code itself is very weird, it's just to highlight this behavior.)

**Comment by miztroh** [comment]
Yes, the order of properties matters.  Basically, you just need to make your observer function observe for both ``iv2`` and ``kicker``.

http://jsbin.com/befirakife/edit?html,console,output

**Comment by TimvdLippe** [comment]
Seems to be working properly with Polymer 2 now: http://jsbin.com/sihayudemo/edit?html,console,output
