### ISSUE TITLE
Unable to notify two elements about same splice: Uncaught Error: unexpected key undefined

### ISSUE THREAD

**Issue by miyconst** [Polymer/polymer#2680]
On my page I have two `<template is="dom-bind">` which bound to same model with an array.

When an array item being removed by third party library I notify the templates with `_notifySplice` method. Everything works fine under Polymer 1.1.x, but Polymer 1.2.x fails to notify second template with the following exception:

```
Uncaught Error: unexpected key undefined
```

Here is a fiddle to demonstrate the exception: http://fiddle.jshell.net/417e3ybz/.

Before you ask: I do need two or more `dom-bind` templates on same page, and yes, they have to be bound to same model.

**Comment by azakus** [comment]
`notifySplices` is now a public API, so you should probably avoid using the private version.
Using 1 model for N repeats is not supported as the repeats are sharing a backing store collection.

@kevinpschaaf might have some workarounds, or ideas for implementation enhancements.

**Comment by miyconst** [comment]
I have updated the fiddle with usage of public `notifySplices` method: http://fiddle.jshell.net/417e3ybz/1/, but this does not eliminate the exception.

**Comment by arthurevans** [comment]
I would use an elements for this, but I managed to get it working with nested `dom-bind` templates. This probably voids your warranties...But it appears to work.

Basically: create two (or more) separate variables that point to the same _model_ object. Bind to those, then use `linkPaths` to let Polymer know that there's another path that needs to be _notified_, but it's really the _same object_ so Polymer won't attempt to mutate the underlying collection that it uses to keep track of the array.

http://fiddle.jshell.net/417e3ybz/

Note that you can remove the inner `dom-bind` templates without affecting the logic:

http://fiddle.jshell.net/r9ansc9r/

You can also do the same thing inside an element. 

I defer to @kevinpschaaf on whether this is a good idea.

**Comment by tomalec** [comment]
Thanks @arthurevans for examples and explanations.

Unfortunately, we cannot use them, as in our case model is a JSON, so we cannot add such references.  

 --- 

> Also, I have to say I'm curious about the use case that absolutely requires multiple dom-binds on the same page with the same data.

In our case we build a page out of partials (provided by different parties) based on JSON view-model.
So briefly, **build dynamic UI entirely from server-driven JSON view-models**.

1. Load master HTML with root `dom-bind`, for example:

  ```html
<template is="dom-bind" id="root">
      <h1>{{title}}</h1>
      <div><!-- subpage content -->
          <template is="imported-template" content$="{{content.html}}" model="{{content.model}}"></template>
      </div>
      ...
</template>
```
2. Fetch JSON view-model (and keep it with sync with [PuppetJS](https://github.com/PuppetJs/PuppetJs) - something like `firebase-element`, but uses JSON Patch standard, OT & other magic, to keep everything in sync), for example:

 ```js
var viewmodel = {
        title: "Hello Arthur",
        content: {
            html: "/path/to/partial.html",
            model: {
                 greeting: "Welcome to JSON driven SPA",
                 // ...
            }
        },
        // ...
}
```
3. Use data and `{{}}` bindings to fill the `template is="dom-bind"`,
4. Where needed, load partial's markup [`<imported-template>`](https://github.com/Juicy/imported-template) (vanilla) custom element imports partial template (using HTML Imports to cover script's execution, caching, etc. natively), for example:

  ```html
<template is="dom-bind" id="nested">
    <h2>{{model.greeting}}</h2>
    ...
</template>
```
  then it attaches data-model to it, and stamps it to the main document.
5. If there is any other (nested) partial to imports it as well.

That is how we ends up with HTML
```html
<h1>Hello Arthur</h1>
<div><!-- subpage content -->
    <template is="imported-template" content="/path/to/partial.html">
</template>

    <h2>Welcome to JSON driven SPA</h2>
    ...
    <template is="dom-bind" id="nested">
        <h2>{{model.greeting}}</h2>
        ...
    </template>
</div>
...
<template is="dom-bind" id="root">
    <h1>{{title}}</h1>
    <div><!-- subpage content -->
        <template is="imported-template" content$="{{content.html}}" model="{{content.model}}"></template>
    </div>
    ...
</template>
```
where root `dom-bind` is bound to `viewmodel`, and nested `dom-bind` to `viewmodel.content.model`

**Comment by kevinpschaaf** [comment]
The 1.x issue here was related to how the `Collection` abstraction worked for managing unique keys to array items, which would get out of sync if a mutation to the same array needed to be notified to two unbound parts of the tree.

The `Collection` abstraction was removed in 2.x, and `dom-repeat` will now re-render on any notification of `splices`, so this is now fixed in Polymer 2.x.

http://jsbin.com/loqukaw/edit?html,output

Closing, as there is no real non-breaking solution to fix this in 1.x; users should upgrade if facing this issue.
