### ISSUE TITLE
Add style element dynamically works with shadow, but not with shady DOM

### ISSUE THREAD

**Issue by zoechi** [Polymer/polymer#2681]
I have an element (sorry for the Dart code, I'm not used to work with JS)

``` html
<dom-module id='my-theme'>
  <template>
    <style>
      :host {
        display: block;
        border: solid 1px red;
      }
      .style-me {
        border: solid 3px lightgreen;
      }
    </style>
    <div>my-theme</div>
  </template>
</dom-module>
```

``` html
<dom-module id='some-element'>
  <template>
    <span id="placeholder"></span>
    <div class="style-me">style-me some text</div>
    <div>theme:<span>[[theme]]</span></div>
  </template>
</dom-module>
```

``` dart
@PolymerRegister('some-element')
class SomeElement extends PolymerElement {
  SomeElement.created() : super.created();

  @Property(observer: 'themeChangeHandler') String theme;

  @reflectable
  void themeChangeHandler([newValue, oldValue]) {
    final root = new PolymerDom(this.root);
    root
        .querySelectorAll('[theme]')
        .forEach((dom.Element e) => root.removeChild(e));
    root.insertBefore(
        new dom.Element.tag('style', 'custom-style')
          ..attributes['theme'] = theme
          ..attributes['include'] = theme == null ? 'default-theme' : theme,
        $['placeholder']);
    // PolymerDom.flush(); // tried, but works without in shadow DOM
    // updateStyles(); // tried, but works without in shadow DOM
  }
}
```

**Comment by zoechi** [comment]
I updated the code. It works better with local shady DOM but the styles are still not applied.

**Comment by zoechi** [comment]
**My use case**
My use case is https://github.com/bwu-dart/bwu_datagrid (a grid/spreadsheet component), currently a Polymer Dart (Polymer JS 0.5) project.

The cells are created dynamically and the user can pass all kind of configuration data like `CSS` class name for a column. This only makes sense if the user also is able to set specific styles for the CSS classes passed with the column configuration.
Also plugins can be added which add to and modify the grid HTML and the user should be able to style all this to his liking.

**Simplified example**
https://github.com/bwu-dart-playground/polymer1/tree/master/dynamic_style_module/web

- `grid_element.dart` contains most code to build the grid HTML
- `grid_element.html` some required style rules (not intended to be changed by users)
- `default_theme.html` example styles (supposed to be provided by users)
- `app_element.dart` the configuration data
- `column_config.dart`

Most style rules in `default_theme.html` could be added statically and using mixins to allow customization but the last two rules show examples where user-provided CSS classes are used in combination with static CSS classes. 

In bwu_datagrid there is an unlimited number of possible combination of component-provided and user-provided class names, especially when features like grouping and aggregation are used (like in http://bwu-dart.github.io/bwu_datagrid/example/grouping.html).
As far as I understand style mixins, there is no way to support such an unlimited number of combinations of CSS classes in selectors.

**Related problem**
Another related requirement is that the colums horizontal position and width is set by dynamically created style rules (see https://github.com/bwu-dart-playground/polymer1/blob/604191c6b1583347d3f79fb4366cd50fa0030154/dynamic_style_module/web/grid_element.dart#L86-L86). I wasn't able to make this work yet using the `Polymer.dom` API. It doesn't allow to add a style element to the component. This is used to support reordering and resizing columns using drag-n-drop where only the style rules (for left and right position of the cells) are updated (this still works in Polymer 1.0 with the code from the Polymer 0.5 project with shady DOM but not in shadow DOM).

**Alternative approach**
One alternative approach, as mentioned by @arthurevans in the Slack #polymer channel, is to render the cells in the light DOM. I have yet to investigate how and if this would work out.

**Comment by zoechi** [comment]
Actually it seems with full shadow DOM polyfill it's working in Chrome and Firefox (not tested elsewhere). That would be sufficient for me. 
If you don't plan to fix this for shady DOM you can close this issue.

**Comment by azakus** [comment]
Just to recap, you want to be able to inject new stylesheets into an element because you want to allow user defined styles to apply to entirely arbitrary elements.
And you can't rely on `@apply` because the user can define arbitrary specificity for those styles.

I'm not sure that the ShadyDOM styling mechanisms have enough hooks for what you want, and we may not want to support it.

@sorvell WDYT?

**Comment by zoechi** [comment]
In Firefox, even with shadow DOM, dynamically added styles work only with dynamically added elements. Styles are not applied to elements statically added to the dom-module's template. 
In Chrome everything works fine (not tested other browsers)

**Comment by zoechi** [comment]
It works fine in Firefox with shadow DOM. #2701 was causing the troubles mentioned in my previous comment.

**Comment by TimvdLippe** [comment]
Per https://github.com/Polymer/polymer/issues/2681#issuecomment-154102827 I am closing this issue. This is a known limitation of ShadyCSS (https://github.com/webcomponents/shadycss#limitations) and it seems that there are other approaches that fit your usecase :smile:
