### ISSUE TITLE
Fatal call on undefined node in IE11

### ISSUE THREAD

**Issue by fozziethebeat** [Polymer/polymer#2682]
I'm loading a Polymer 1.0 app in IE 11 and getting the following fatal javascript error found in polymer-mini.html:

```
function saveLightChildrenIfNeeded(node) {
  if (!node._lightChildren) {
    X Unable to get property '_lightChildren' on undefined or null reference
   ....
```

This happens during the general set of initialization for some element but I can't determine which.  I've only seen this happen in IE 11.  This doesn't happen for IE 9 or any other browsers.

**Comment by nazar-pc** [comment]
Can you try Polymer 1.2.1 first?
Test case on jsfiddle/jsbin would also help a lot.

**Comment by baseten** [comment]
I have this happening too and I'm using Polymer 1.2.1, also only in IE11, IE10 is fine. It seems to happen sporadically so perhaps is some sort of race condition? I'll see if I can put together a minimal reproduction.

**Comment by nazar-pc** [comment]
I'd suggest to prepare non-minified well formatted version of Polymer and try to debug it in browser with breakpoints and traversing stacktrace back and forth (if IE have such features).

**Comment by dombre** [comment]
I think the problem only occurs on IE Version 11.0.9600.16384

With any newer IE versions i don't get this error (for example with 11.0.9600.18098).

If you need this old version of IE, it is included in the virtual machine "IE11 on Win8.1" (https://dev.windows.com/en-us/microsoft-edge/tools/vms/windows/)

**Comment by dombre** [comment]
Version 11.0.9600.17031 is probably also affected (some user on polymer.slack.com reported that he gets this error with the .17031 version)

**Comment by wetherbeei** [comment]
Triggers occasionally on IE11 (11.0.9600.17126):

Stack:
saveLightChildrenIfNeeded(c.parentNode)
_createLocalRoot
_setupRoot
_ready
_tryReady
_initFeatures
Polymer.Base.createdCallback

    if (!node._lightChildren)
Exception: "Unable to get property '_lightChildren' of undefined or null reference"

c.parentNode is null, c is a <content> element that isn't attached to the DOM yet. It's inside a <template is="dom-if"> element that isn't stamped for the first time yet.


    <template is="dom-if" if="{{computed(a)}}">
        <a is="custom-element" ...><paper-button>{{computed(b)}}</paper-button></a>
    </template>

    <dom-module id="custom-element">
        <template>
            <... other elements ... >
            <content></content>
        </template>
    </dom-module>

**Comment by dtruffaut** [comment]
I have a similar problem

Here are the screenshots :

IE11 :
http://www.kirikoo.net/images/14Anonyme-20160818-130837.png

IE10-IE9:
http://www.kirikoo.net/images/14Anonyme-20160818-131245.png

IE8 (I guess it is a different bug from polymer init when scaffolding, but I let you know as it also concerns IE compatibility)
http://www.kirikoo.net/images/14Anonyme-20160818-131452.png

Note that it works perfectly on Chrome and Firefox.

**Comment by azakus** [comment]
Hmm, I wonder if this is related to https://github.com/webcomponents/template/pull/23
