### ISSUE TITLE
gestures.html

### ISSUE THREAD

**Issue by mug3n** [Polymer/polymer#2683]
Line 204 - gs = gob[type]; 
if (!gs) ...
and each line like that will throw an error on iOS. Using a non-object as an object is not allowed. It's a pure syntax problem.
I can fix it myself, but is it worth a fork?

**Comment by azakus** [comment]
I'm not sure I understand what you're saying, but this sounds like #2641

**Comment by mug3n** [comment]
No, I saw #2641, it's similar, but not the same. Variable gobj is undefined in the given context (something went wrong) and trying to get a key(type's value) of gobj throws an error. 
TypeError: undefined is not an object (evaluating 'gobj[type]')

**Comment by azakus** [comment]
No, that's actually the same problem: https://github.com/Polymer/polymer/blob/master/src/standard/gestures.html#L203-L204:
```js
var gobj = node[GESTURE_KEY];
var gs = gobj[type];
```

Should be fixed by #2684

**Comment by mug3n** [comment]
Jeez I just ran through it, didn't even read it properly. Sorry for that. 
Cheers!

**Comment by azakus** [comment]
No problem, I hope to have this fixed really soon.
