### ISSUE TITLE
Format-detection breaks data binding (Apple UIWebView)

### ISSUE THREAD

**Issue by ronnyroeller** [Polymer/polymer#2688]
I bind a string property `text` as following:
```html
<div>[[text]]</div>
```

I run this element in Apple UIWebView. When changing the value of the `text` property during runtime, the old content partially remains in the `<div>`.

I suspect this is caused by UIWebView changing the internal HTML to make the phone numbers clickable. I see the following in the Safari inspector when setting `text` to `+31600000000`:

```html
<div><a dir="ltr" href="tel:+31600000000" x-apple-data-detectors="true" x-apple-data-detectors-type="telephone" x-apple-data-detectors-result="2">+31600000000</a></div>
```

After changing `text` to `+31699999999` this becomes:

```html
<div class="text style-scope paper-contact-phone"><a dir="ltr" href="tel:+31600000000" x-apple-data-detectors="true" x-apple-data-detectors-type="telephone" x-apple-data-detectors-result="0/1">+31600000000</a>+31 6 <a dir="ltr" href="tel:99999999" x-apple-data-detectors="true" x-apple-data-detectors-type="telephone" x-apple-data-detectors-result="0/1">99999999</a></div>
```

Workaround: Instruct UIWebView to not auto-detect phone numbers by adding to the header of the HTML file:
```html
<meta name="format-detection" content="telephone=no">
```

See [Apple documentation](https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html)

**Comment by azakus** [comment]
Seems like maybe a useful tip for Polymer users, but that is an application specific problem, and not something Polymer would fix for you.

**Comment by azakus** [comment]
Closing due to age, please reopen if this is still an issue.
