### ISSUE TITLE
local dom documentation error

### ISSUE THREAD

**Issue by mgiuffrida** [Polymer/polymer#2693]
In https://www.polymer-project.org/1.0/docs/devguide/local-dom.html:

> You can also locate nodes in the local DOM using querySelector, querySelectorAll, or the $$ utility method:

```
var cancelButton = Polymer.dom(this.root).querySelector('#cancelButton');

// Shorthand for finding local DOM children by ID
// (equivalent to the above):
this.$$('cancelButton');
```

Should the last line be `this.$$('#cancelButton');`?

**Comment by arthurevans** [comment]
Why yes. Yes it should. Thank you.
