### ISSUE TITLE
Automatically update API reference when new release is cut

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#2695]
It would be lovely, wouldn't it?

@azakus @garlicnation WDYT?

**Comment by azakus** [comment]
@rictic Do you think tedium is up to the task?

**Comment by rictic** [comment]
What're the steps involved?

**Comment by rictic** [comment]
I believe the API reference is automatically generated: https://www.polymer-project.org/2.0/docs/api/

Is this involving automatic deploying of polymer-project.org when there's a Polymer release?
