### ISSUE TITLE
Let "sort" attribute have default behavior as data binding helper

### ISSUE THREAD

**Issue by pensierinmusica** [Polymer/polymer#2697]
Hi,

Polymer docs on [data binding helper elements](https://www.polymer-project.org/1.0/docs/devguide/templates.html#filtering-and-sorting-lists) state that `sort`:

> Specifies a comparison function following the standard `Array` [sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) API.

In practice though this is not fully implemented, as the attribute today always expects the assignment of a specifc function, and doesn't work otherwise. On the other hand, since often enough `sort` in practice is used to alphabetically sort elements, it could be made so that if the attribute has no value it falls back to default sort behavior (like the standard JS API, when no specific comparison function is defined).

Let's take a look at a couple of code examples.
### Sorting through a custom function

``` html
<template is="dom-repeat" items="{{employees}}" sort="isEmployee" observe="type manager.type">
```
### Default (alphabetical) sorting

``` html
<template is="dom-repeat" items="{{employees}}" sort>
```

@ebidel could this be included in future Polymer releases?

Cheers!

**Comment by JeremybellEU** [comment]
> since often enough sort in practice is used to alphabetically sort elements

This assumption is not true for all lists that I have implemented myself. Moreover, changing the default behaviour of the `dom-repeat` would cause me to implement a custom sort that simply returns the original array for every single `dom-repeat` that I use.

Therefore, I don't think forcing such default behaviour for the sort function is desirable.

**Comment by pensierinmusica** [comment]
@JeremybellEU, that's not what I meant. Please read again above and see the code examples. `<dom-repeat>` would not change its default behavior, only the `sort` attribute when no property is specified.

**Comment by JeremybellEU** [comment]
After more careful rereading of your initial comment with the extra explanation, I understand the reasoning and see the usefulness of this change. It was not clear to me what was being proposed, as I interpreted `if the attribute has no value` that the value was not declared on the parent element.

Sorry for my misunderstanding.
