### ISSUE TITLE
Polymer.dom(parent).removeChild(node) not working outside of Chrome

### ISSUE THREAD

**Issue by pensierinmusica** [Polymer/polymer#2698]
`Polymer.dom(parent).removeChild(node)`, referenced in Polymer docs ([Local DOM Basics and API](https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#dom-api)), doesn't seem to be working outside of Chrome.

I've tried it using Polymer 1.2.1, on Safari 9.0.1, Firefox 35, and iOS 9.1.

On the other hand, oddly enough `Polymer.dom(parent).appendChild(node)` works fine in all browsers I've tested.

Can you please check it out? Thanks!

**Comment by azakus** [comment]
This seems to be working for me in Firefox: http://jsbin.com/fahiwo/edit?html,output
Can you post an example that doesn't work?

**Comment by pensierinmusica** [comment]
```html
<link rel="import" href="../bower_components/polymer/polymer.html">

<dom-module id="my-component">

  <template>

    <div id="container"></div>

    <button on-click="add">Add node</button>

  </template>

  <script>

    Polymer({
      is: "my-component",
      add: function () {
        var node = document.createElement('div');
        node.innerHTML = '<p>I am a new node!</p> <button onclick="document.querySelector(\'my-component\').remove(this)">x remove</button>';
        Polymer.dom(this.$.container).appendChild(node);
      },
      remove: function (node) {
        node = node.parentNode;
        Polymer.dom(this.$.container).removeChild(node);
      }
    });

  </script>

</dom-module>
```

**Comment by miztroh** [comment]
@pensierinmusica Try this:

```
remove: function (node) {
   Polymer.dom(node.parentNode).removeChild(node);
}
```

**Comment by pensierinmusica** [comment]
@miztroh, actually that's exactly what I ended up doing and it works. But why the version posted above doesn't work? Thanks!

**Comment by miztroh** [comment]
@pensierinmusica Your ``add`` function adds elements to ``this.$.container``.  In your version of the ``remove`` function, you set ``node = node.parentNode``, which should be ``this.$.container``.  So, you're basically telling ``this.$.container`` to remove itself.  If you leave out the ``node`` assignment line, the rest of your function will probably work as is (see below).

```
remove: function (node) {
   Polymer.dom(this.$.container).removeChild(node);
}
```

**Comment by pensierinmusica** [comment]
@miztroh, I'm getting a little confused... In my understanding the `node` that is passed to the remove function is the "x remove" `<button>`. Hence its parent should be the unnamed `<div>` that is created on `add()`:

```js
var node = document.createElement('div');
node.innerHTML = '<p>I am a new node!</p> <button onclick="document.querySelector(\'my-component\').remove(this)">x remove</button>';
```

Now, when the user clicks on the "x remove" button, let's walk this through steps for a sec.

1. The `remove` function is called with `node === "x remove button"`;
2. `node` is reassigned to the parent element, so now `node === "unnamed div"`;
3. We ask the `container` div to remove the "unnamed" div:
```js
Polymer.dom(this.$.container).removeChild(node);
```

Am I missing anything? Thx  :)

**Comment by miztroh** [comment]
I didn't see in your message above that you were removing a <b>child</b> of the node you previously added.

In that case, the function I originally posted is what you'll want to use.

**Comment by pensierinmusica** [comment]
@miztroh as I mentioned in https://github.com/Polymer/polymer/issues/2698#issuecomment-163610062 that's what I already ended up doing in my code.

Still, given the code at the top, it's a mistery to me why this works:
```js
Polymer.dom(node.parentNode).removeChild(node);
```

And this doesn't
```js
Polymer.dom(this.$.container).removeChild(node);
```

Any insight?

**Comment by miztroh** [comment]
It does work: http://jsbin.com/cefalitiji/edit?html,output

**Comment by pensierinmusica** [comment]
@miztroh true, now it works, not sure why. Probably something got fixed in the meantime in Polymer's codebase that took care of it. I'd say we can close this issue then. Thanks everyone for helping out!
