### ISSUE TITLE
Styling with full shadow DOM polyfill not working properly in Firefox

### ISSUE THREAD

**Issue by zoechi** [Polymer/polymer#2701]
http://plnkr.co/edit/x9q15ipcsY3wDcMVfVmK?p=options

I either need to disable shadow DOM or prefix selectors with `:host ::content` to get styles applied.

**Comment by azakus** [comment]
Yep, this looks busted.

Simpler example: http://jsbin.com/warapi/edit?html,output

**Comment by arturparkhisenko** [comment]
:+1:

**Comment by untra** [comment]
:+1:

**Comment by arturparkhisenko** [comment]
Need to test it in 1.3.0+ because we have that: https://github.com/Polymer/polymer/commit/d9f3dda

**Comment by felixnielsen** [comment]
hi, using polymer 1.8.0 I am still experiencing issues with scope styles.

using the `webcomponents-lite.min.js` polyfill lib (using Polymer v. 1.8.0)

In firefox (and other polyfill browsers) I am experiencing that elements appended via `inner-h-t-m-l` does not get correct scope classes:
Here, scope classes are set properly: https://www.dropbox.com/s/epohcq9amlxxou9/Screenshot%202017-02-08%2020.53.30.png?dl=0
Here, using inner-h-t-m-l, where scope classes are not set: https://www.dropbox.com/s/v87axaoumi3s5uh/Screenshot%202017-02-08%2020.55.00.png?dl=0

Anyone know of a fix/workaround?

I tried `Polymer.dom.flush();`

**Comment by miztroh** [comment]
Have you tried https://www.polymer-project.org/1.0/docs/api/Polymer.Base#method-scopeSubtree?

**Comment by felixnielsen** [comment]
@miztroh works like a charm, thanks!

**Comment by TimvdLippe** [comment]
Issue seems to be fixed with Polymer 2 in both Firefox and Chrome: http://jsbin.com/regamiqeya/edit?html,console,output
