### ISSUE TITLE
Curly braces within Polymer bindings stopped working with Polymer 1.2

### ISSUE THREAD

**Issue by nomego** [Polymer/polymer#2704]
Our translation system uses placeholders like `{0}` for interpolation, which stopped working now with Polymer 1.2, where the binding string is not evaluated.
Consider the following:

```html
<template>
  <span>{{ _("Hello {0}", userName) }}</span>
</template>
```

In Polymer 1.0, this results in "Hello user", but in Polymer 1.2, the whole expression is printed verbatim, i.e. `{{ _("Hello {0}", userName) }}`.

**Comment by ebidel** [comment]
1.1.5 was the last time this worked: http://jsbin.com/jafimawiyi/edit?html,output

**Comment by JeremybellEU** [comment]
I have some spare time this evening and can investigate if you want.

**Comment by zoechi** [comment]
I guess it's related to the new compound binding

**Comment by JeremybellEU** [comment]
Got permission of @kevinpschaaf to ninja this issue. Travis passed on #2705.
