### ISSUE TITLE
Define more clearly which Polymer methods can be called statically

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#2706]
Right now some but not all methods on `Polymer.Base` can be called statically. For example, `Polymer.Base.importHref` can but `Polymer.Base.$$` cannot. When some of these methods work, users may assume incorrectly that all of them will work. The primary purpose of `Polymer.Base` is to be the element base prototype for Polymer elements, and it's a non-goal that all methods on `Polymer.Base` work statically.

We should probably move to a different name on Polymer for static methods and deprecate statically calling methods on `Polymer.Base`.

Recently, this broke when we changed `fire` to call another method on `Polymer.Base` (e.g. https://github.com/Polymer/polymer/blob/micro-perf/src/standard/utils.html#L222 broke because of this https://github.com/PolymerElements/iron-test-helpers/blob/master/mock-interactions.js#L110).

**Comment by TimvdLippe** [comment]
Static methods are now annotated properly and [visible in the docs](https://www.polymer-project.org/2.0/docs/api/elements/Polymer.Element)
