### ISSUE TITLE
CSS variables with parenthesis

### ISSUE THREAD

**Issue by felixzapata** [Polymer/polymer#2709]
Hi, I think that with next example the shim about the css variables should not work:

```
<dom-module id="my-element">
  <style>
    :host {
      --main-color: {red};
    }
    span {
      color: var(--main-color);
    }
  </style>
  <template>
    <span>I'm <b>my-element</b>. This is my Shadow DOM.</span>
  </template>
</dom-module>
```

I mean, according with the CSS specification about CSS variables, the parenthesis in this case are not valid. If you try this example without Polymer:

```
<style>
body {
  --background:red;
  background:var(--background);
}
</style>
```

will show the body with a red background. But if you use the next:

```
<style>
body {
  --background:{red};
  background:var(--background);
}
</style>
```

the background will be the default.

**Comment by azakus** [comment]
I'm not sure what you mean.
Are you saying that you expect `--main-color: {red};` to work, but it does not; 
or that you expect `--main-color:{red};` to not work, but it does?

**Comment by felixzapata** [comment]
`--main-color:{red}` should not work

**Comment by arthurevans** [comment]
Repro:

http://jsbin.com/qalaho/6/edit?html,output

I believe this shouldn't work, and our shim appears to be making it work.

    /* custom property is OK */
    --background: red;

    /* mixin is OK */
    --background: { background-color: red; }

    /* this here is broken */
    --background: {red};

**Comment by azakus** [comment]
Gotcha.

The shim doesn't validate CSS, only applies a light set of transformations over the text of the styles.
This may change in the future if we can craft a good enough parser, but for right now we are prioritizing speed over complete correctness.

For now, you should find which element sets up that variable and file an issue, or fix it if you own that element.

**Comment by samccone** [comment]
just a follow up here, any word on a potential fix? Over in PSK land we would like to move to gulp-clean-css but are currently blocked by this quirk of the shim.

**Comment by TimvdLippe** [comment]
Seems to be fixed in Polymer 2: http://jsbin.com/puhovazama/edit?html,console,output
