### ISSUE TITLE
notifySplices does not work for nested arrays

### ISSUE THREAD

**Issue by tomalec** [Polymer/polymer#2710]
I'm trying to use new `notifySplices` method in the way I used old `_notifySplice`, to notify `dom-bind` about a change that was made in nested array of my model:

```js
var old_value = model.path_to.array[0].nested_array[0];
model.path_to.array[0].nested_array[0] = new_value;
// ...
domBind.notifySplices(
  "model.path_to.array.0.nested_array", 
  [{
    object: model.path_to.array[0].nested_array,
    index: 0, 
    addedCount: 1, 
    removed: [old_value],
    type: 'splice'
  }]
);
```
And this does not notify my template, here live example: http://jsbin.com/felonif/3/edit?html,console,output.
(same code for just `model.path_to.array` works fine)

Previously, I tried to use `notifyPath`, and `_notifySplice` with `Polymer.Collection` hacking #2540.
I suspect the issue may be related to the same `Polymer.Collection` key fetching but in [`.get` method](https://github.com/Polymer/polymer/commit/3c25d25a7af57ce725ba8b8cb94f82824728d7c8#diff-5e6bf13e22ada8ee1cd62fa8448650a0R253), used after @kevinpschaaf's "Improve notifyPath/notifySplices API for public usage" #2509

**Comment by tomalec** [comment]
This seems to be a mismatch between given path with `#`s and `effect.value` given by indexes, at https://github.com/Polymer/polymer/blob/f58d9faf54948c8df300eedd2379459e82ffce32/src/standard/notify-path.html#L289

**Comment by tomalec** [comment]
The issue was with `items="{{model.path_to.array.0.nested_array}}"`
after changing it to 
```html
<template is="dom-repeat" items="{{model.path_to.array}}">
     <template is="dom-repeat" items="{{item.nested_array}}">
         <span>{{item.prop}}</span>
     </template>
</template>
```
it works
http://jsbin.com/felonif/5/edit?html,console,output

**Comment by miyconst** [comment]
Looks like this is what I was saying long time ago.

We also have a test case for this scenario:
https://github.com/Juicy/dom-bind-notifier/blob/gh-pages/tests/smoke/arrays.html#L422
