### ISSUE TITLE
Remove old branches

### ISSUE THREAD

**Issue by abdonrd** [Polymer/polymer#2713]
I think that we can remove the old [branches](https://github.com/Polymer/polymer/branches/all):
- `templatizeRender` (already closed)
- `2504-kschaaf-templatizer-props` (already merged)
- `fix-rare-ie11-bug` (already closed)
- `2016-kschaaf-computed-setter` (already merged)
- `style-fixes` (already merged)
- `custom-style-fix` (already merged)
- `easy-builds`
- `0.8-preview`

and moore...

**Comment by TimvdLippe** [comment]
Most of the branches have been cleaned up, we are down to 34 now. Still leaving this open as there are some branches that need more discussion.

**Comment by TimvdLippe** [comment]
Branches are now nicely cleaned up and we are maintaining this better, so I am closing this issue for now.
