### ISSUE TITLE
Error: JSHint failed for: app/scripts/app.js, app/elements/routing.html, app/elements/my-greeting/my-greeting.html, app/elements/my-list/my-list.html

### ISSUE THREAD

**Issue by migueltv** [Polymer/polymer#2715]
I get this error after running gulp

[20:52:29] Using gulpfile ~/tob-budget/gulpfile.js
[20:52:29] Starting 'clean'...
[20:52:29] Finished 'clean' after 209 ms
[20:52:29] Starting 'default'...
[20:52:29] Starting 'copy'...
[20:52:29] Starting 'styles'...
[20:52:30] styles all files 98 B
[20:52:30] Finished 'styles' after 568 ms
[20:52:31] copy all files 12.9 MB
[20:52:31] Finished 'copy' after 1.47 s
[20:52:31] Starting 'elements'...
[20:52:31] Finished 'elements' after 4.33 ms
[20:52:31] Starting 'jshint'...
[20:52:31] Starting 'images'...
[20:52:31] Starting 'fonts'...
[20:52:31] Starting 'html'...
[20:52:32] Finished 'fonts' after 355 ms

app/scripts/app.js
  line 52  col 5  'Polymer' is not defined.
  line 55  col 5  'Polymer' is not defined.
  line 58  col 5  'Polymer' is not defined.

  ⚠  3 warnings

app/elements/routing.html
  line 23  col 5  'app' is not defined.
  line 28  col 3  'page' is not defined.
  line 29  col 5  'app' is not defined.
  line 32  col 3  'page' is not defined.
  line 33  col 5  'app' is not defined.
  line 36  col 3  'page' is not defined.
  line 37  col 5  'app' is not defined.
  line 38  col 5  'app' is not defined.
  line 41  col 3  'page' is not defined.
  line 42  col 5  'app' is not defined.
  line 46  col 3  'page' is not defined.

  ⚠  11 warnings

app/elements/my-greeting/my-greeting.html
  line 29  col 3  Missing 'new' prefix when invoking a constructor.
  line 29  col 3  'Polymer' is not defined.

  ⚠  2 warnings

app/elements/my-list/my-list.html
  line 30  col 3  Missing 'new' prefix when invoking a constructor.
  line 30  col 3  'Polymer' is not defined.

  ⚠  2 warnings

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: JSHint failed for: app/scripts/app.js, app/elements/routing.html, app/elements/my-greeting/my-greeting.html, app/elements/my-list/my-list.html

node --version && npm --version 
v0.12.4
2.10.1

Can you please help me?

**Comment by LM450N** [comment]
JSHint tells you your code has syntax errors. To make the build pass, you have to fix them. For example, Polymer has to be declared as global into the `.jshintrc` file. For the missing _new_ keyword, just add them. And so on...

**Comment by samccone** [comment]
looks like an issue for polymer-starter-kit and not polymer proper 
https://github.com/PolymerElements/polymer-starter-kit/

**Comment by migueltv** [comment]
Sorry, it really is about polymer-starter-kit :(

I'm going to declare the variables and correct the warnings in .jshintrc

Thanks LM450N

**Comment by samccone** [comment]
cc: @ebidel to close since this is "resolved" and not polymer core
