### ISSUE TITLE
Normalize events generated by Polymer

### ISSUE THREAD

**Issue by David-Mulder** [Polymer/polymer#2723]
When an `on-tap` event is triggered we already have a 'Polymer event' and a 'source event' (`event.detail.sourceEvent`)... and then there is the normalized event we get from `Polymer.dom(event)`. Simply put this is a (very confusing) mess and should seriously be brought back to at most two events.

Just putting this up for discussion here, as I sincerely feel this is even harder to understand than most of Polymer (often ugly) performance trade-offs/optimizations.

**Comment by azakus** [comment]
You should not have to look at the `sourceEvent` often, if ever. It only exists for accessing properties that are rarely used that we have not bothered to facade on the gesture event, like `pageX` and `shiftKey`.

The normalization `Polymer.dom(event)` provides is only for dynamic properties that change over the lifetime of the event, most of which are not needed for normal operations.
It does not provide a full facade of the given event, and will be deprecated once ShadowDOM exists in all platforms.

**Comment by David-Mulder** [comment]
@azakus Ehm, the normalization that `Polymer.dom(event)` provides is crucial in both Shadow and Shady DOM, because right now Shadow and Shady DOM give different values for `.target` and `.srcElement`~ I am not even sure where it pulls it's information from, because on non-Chrome browsers I wasn't even able to pierce the Shadow DOM and find the (shadow) element the user clicked/tapped on.

**Comment by azakus** [comment]
Given that `Polymer.dom(event)` is a seperate concertn, can you draft up a proposal of exactly what you want to see on the gesture event objects?

**Comment by David-Mulder** [comment]
Honestly, I don't understand the Shadow and Shady DOM setups well enough when it comes to this that I would feel confident setting up such a proposal. As I said before, I don't even get how some of the retrieved information was found, so all I can say is that the following sounds sensible: Bring it back to two event objects, the Polymer one and the `sourceEvent` one. Make `Polymer.dom(event)` something you won't need at all (and if it has a use still make it very clear what that specific use is, because right now that's not clear at all) and make sure the 'standard' event is one which looks the same in Shady and Shadow DOM.
