### ISSUE TITLE
Consider making observers for objects/arrays always run on deep changes

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#2724]
Many users find it unexpected when an observer such as the following does not run when an object or array's sub-property changes (it only runs when the object _reference_ changes, not when a sub-property changes):

``` js
observers: [
   'itemChanged(item)'
]
```

For deep observation of object sub-properties, we include a wildcard syntax:

``` js
observers: [
   'itemChanged(item.*)'
]
```

This issue is to consider calling the observer in the former case whenever deep property changes.  The only difference would be that the latter provides an "info" object (with `path`, `value`, and `base`), while the former would provide the base object whose sub-properties may have changed.

**Comment by David-Mulder** [comment]
Note: Just make sure that this time round if you make a non-backwards compatible change like this you up the MAJOR version number in semver, not a MINOR one like with the (non backwards) change with `#n` array paths.

**Comment by frezelth** [comment]
Is this still planned?

**Comment by TimvdLippe** [comment]
In polymer 2 deep paths are now properly notifying when listening to just the object reference: http://jsbin.com/misajulifo/edit?html,console,output
