### ISSUE TITLE
Documentation for array indexes and `Polymer.Collection`

### ISSUE THREAD

**Issue by David-Mulder** [Polymer/polymer#2725]
So... after having fought with this A LOT I am just going to put a request for documentation out here:

 - What's the difference between `array.n` and `array.#m`? (I get this part, but as far as I know this isn't documented anywhere)
 - If I have `n`, how do I get `#m`? (Provided that my understanding is correct that `#m` is constant regardless of array manipulation)
 - Maybe some generic advice on when to use what and how.

**Comment by arthurevans** [comment]
This issue was moved to Polymer/docs#1427
