### ISSUE TITLE
fx.sort is not a function in polymer.html @ line 1442

### ISSUE THREAD

**Issue by JamesCoyle** [Polymer/polymer#2726]
I'm probably being a complete moron and have messed up the most simple thing but I can't for the life of me solve this issue. I am getting this error in the console every time I try to import `polymer.html` or any of my custom polymer elements:

    Uncaught TypeError: fx.sort is not a functionPolymer.Bind.createBindings @ polymer.html:1442
      Polymer.Base._addFeature._prepBindings @ polymer.html:1641
      Polymer.Base._addFeature._registerFeatures @ polymer.html:3367
      Polymer.Base.registerCallback @ polymer-micro.html:144
      desugar @ polymer-micro.html:73
      window.Polymer @ polymer-micro.html:57
      (anonymous function) @ polymer.html:3401
      (anonymous function) @ polymer.html:3454

I have included the `webcomponents.min.js` before the imports and all of the files exist on the server and have been correctly retrieved as far as I can see. I have also tried deleting all the files from the server and re-uploading them including updating bower to make sure I have the latest version. Everything was working fine a few weeks ago when I last worked on this project so I am reasonably confident everything I've done is correct.

Site link if it helps: http://solus-softworks.com/

**Comment by azakus** [comment]
Looks like the `_propertyEffects` of the `custom-style` element ended up as a weird object with `forEach` in it. This gets set to `fx` in `_prepBindings` and throws.

**Comment by azakus** [comment]
Ah, it's from your `solus.js`:

```js
//allow element lists to be iterated over
Object.prototype.forEach = Array.prototype.forEach;
NodeList.prototype.forEach = Array.prototype.forEach;
StyleSheetList.prototype.forEach = Array.prototype.forEach;
```

Don't do that.

**Comment by azakus** [comment]
As a hacky workaround, use defineProperty

```js
Object.defineProperty(NodeList.prototype, {
value: Array.prototype.forEach
});
```

Still, don't do that for Object at the very least. If you need to iterate, make those objects arrays first with `Array.prototype.slice.call(obj)` or ES6's `Array.from(obj)`
