### ISSUE TITLE
Check if an element has been registered

### ISSUE THREAD

**Issue by felixzapata** [Polymer/polymer#2730]
hi, in my current project, I have errors in the console about elements that have been registered. This errors are related with some partials vulcanized elements. 

I have a base file with some `core` elements (this file is vulcanized) and then, each element in different pages will have their own components. 

Based on an idea of @jorgecasar, I suggest this code inside `polymer-bootstrap.html` to avoid these console errors:

```
      if (!Polymer.telemetry.isRegistered(prototype.is)) {
        Polymer.telemetry._registrate(prototype);
        document.registerElement(prototype.is, options);
      }
```

The idea is simple, add a method to `telemetry` to check if the new component has been registered. If is not, we register it. 

I've used my current project to test and check the result with the new code. I will try to make a test inside Polymer to send the pull request with the modifications.

**Comment by garryyao** [comment]
+1

**Comment by TimvdLippe** [comment]
In Polymer 2, before you call `customElements.define`, you can call [`customElements.get`](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/get) to check if the element was already registered. This should implement the behavior that you would need.
