### ISSUE TITLE
Registering invalid element name or re-using name should not crash app

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#2735]
Currently, trying to register an invalid custom element name or re-registering an existing naw causes JS errors and a white screen of death. This is because `document.registerElement()` throws and further JS doesn't run.

This can be very frustrating for developers. A bad name or re-use of an existing name should "crash" an app! Polymer mini can smooth this over.

Examples:

```
Polymer({is: 'x'}); // Attempt to register an invalid CE name bombs out app.
Polymer({is: 'x-foo'});
Polymer({is: 'x-foo'}); // Attempt to re-register an existing name bombs out app!
console.log('I wont run');
```

**Comment by samccone** [comment]
yes please :dancer:

**Comment by sorvell** [comment]
Closing this since we're not adding new features to Polymer 1.x. In Polymer 2.x the user calls `customElements.define` and just gets the native error message if the element is already defined.
