### ISSUE TITLE
Missing "paper-behaviors.html"

### ISSUE THREAD

**Issue by JKWA** [Polymer/polymer#2738]
"paper-elements.html" imports "paper-behaviors.html", which does not exist.
<link rel="import" href="../paper-behaviors/paper-behaviors.html">

**Comment by fredj** [comment]
@JKWA an issue has already been opened in the paper-elements repository, see https://github.com/PolymerElements/paper-elements/issues/54

**Comment by azakus** [comment]
Closing as duplicate of PolymerElements/paper-elements#54
