### ISSUE TITLE
Defining custom properties in mixins

### ISSUE THREAD

**Issue by David-Mulder** [Polymer/polymer#2740]
I have read through all open issues about mixins, but I can't find anything about the fact that custom properties do not seem to work in mixins.

And before you criticize this isn't necessary (as someone else did):
1. It doesn't make sense from a usage point of view that they behave differently
2. Let me give en example where I need it, I have a `<paper-datatable>` with checkboxes in it ( http://david-mulder.github.io/paper-datatable/components/paper-datatable/demo/theming.html ). If I next wish to allow the user to change only the `<paper-checkbox>` in the header I would have to expose custom variables for every variable of `<paper-checkbox>`

**Comment by azakus** [comment]
Sorry, I'm not sure what you mean by custom properties "don't seem to work" in mixins.

Can you post a small JSBin sample that points out what you mean?

**Comment by David-Mulder** [comment]
Oh wow, never saw the reply, my bad, here you go: 

http://jsbin.com/jucavikiju/edit?html,output

**Comment by ebidel** [comment]
Spec-wise, I'm not sure if you're supposed to be able to define a custom property in a mixin. This could also be a parsing bug on our end. @sorvell will know.

In the meantime, you can define classes for specific paper-card/paper-checkbox to style them differently:

```
:root{
      --some-mixin: {
        color: green;
      };
    }
    paper-card.yellow {
      --paper-card-header-color: yellow;
      @apply(--some-mixin);
    }
```

**Comment by sorvell** [comment]
Defining a custom property within another custom property is not something
Polymer currently supports. Since the `@apply` native feature is still
being spec'd, it's unclear if it will be available in a future native
implementation.

**Comment by TimvdLippe** [comment]
I am closing this issue as a wont-fix, as this is an upstream issue for the apply specification. If you would like to contribution to the spec, please check it out at https://tabatkins.github.io/specs/css-apply-rule/, although I am not sure if the specification has a champion still.
