### ISSUE TITLE
No new line or space between variable definitions adds second variable as regular style rule

### ISSUE THREAD

**Issue by rubenstolk** [Polymer/polymer#2742]
When my (custom) stylesheet looks like:

```--google-123: #123123; --google-456: #51a6e0```

Everything is normal, both the variables get interpreted well. However, when there is not line break or space between the two definitions, e.g.:

```--google-123: #123123;--google-456: #51a6e0```

... everything works but in my dom explorer I see that the browser tries to add the rule ```--google-456: #51a6e0``` (see image).

Of course it doesn't really harm because the rule doesn't make sense, however in cases of minifying `css` this becomes an issue because all variables will be added like this and I think it adds a performance hit as well.

<img width="325" alt="screen shot 2015-11-16 at 14 25 39" src="https://cloud.githubusercontent.com/assets/692644/11177765/f4b5a25e-8c6d-11e5-90bb-85a3bf541545.png">

**Comment by rubenstolk** [comment]
I think this might be one of the reasons that @addyosmani has removed `polyclean` from his PSK because `polyclean` puts all CSS on the same line without any spaces between rules.

**Comment by JeremybellEU** [comment]
Probably a duplicate of #2483 which is fixed in #2689

**Comment by rubenstolk** [comment]
OK definitely a duplicate of #2483
