### ISSUE TITLE
_bindingRegex + _parseBindings erroneously removing template contents 

### ISSUE THREAD

**Issue by Westbrook** [Polymer/polymer#2743]
As demonstrated in the following Plunker the current regex employed by _bindingRegex fails to appropriately parse the `{` to begin the object notation in the template when employed in _parseBindings.  Here I've replaced the character with a property binding but that's no good...

http://plnkr.co/edit/wzKmEx34SDmVsR9B5WvI?p=preview

Code inline:
```
<dom-module id="x-test">
	     <template>
	         {
	          "@context": "http://schema.org"
	          "@type": "ImageObject",
	          "author": "[[author]]"
	         }
	       <br/>
	       [[hack]]
	          "@context": "http://schema.org"
	          "@type": "ImageObject",
	          "author": "[[author]]"
	         }
	     </template> 
	  </dom-module>
	  <script>
	  Polymer({
    is: 'x-test',
    properties: {
      author: {
        type: String,
        value: 'test'
      },
      hack: {
        type: String,
        value: '{'
      }
    }
	  });
	  </script>
</dom-module>
```

**Comment by kevinpschaaf** [comment]
Will be resolved in https://github.com/Polymer/polymer/pull/3017.

Updated plnkr:
http://plnkr.co/edit/cuU5jkzlsf4HvHTdgVqx?p=preview

**Comment by Westbrook** [comment]
Thanks @kevinpschaaf this looks great.  What's more, I dig polygit a little more every day for things like the returned plnkr!

Closing in reference to #3017
