### ISSUE TITLE
Create time URL resolution of relative URLs in special attributes is undocumented.

### ISSUE THREAD

**Issue by bicknellr** [Polymer/polymer#2748]
The URL resolution that happens at create time for the special set of attributes [listed here](https://github.com/Polymer/polymer/blob/a2e2a118bab73ec3b31b654adf474252d5cb6194/src/lib/resolve-url.html#L71-L74) is undocumented can be confusing when you notice it after using both static values and bindings for these attributes.

See PolymerElements/iron-image#39 for context.

**Comment by manfield** [comment]
After updating Polymer I spent some hours to understand why a view was broken. 
I had an absolute url in a src attribute, and it caused an unhandled exception that caused js stop responding in container components. Finally I found that the issue was the one you're reporting.

**Comment by TimvdLippe** [comment]
This behavior is no longer existent in Polymer 2: https://www.polymer-project.org/2.0/docs/upgrade#urls-in-templates
