### ISSUE TITLE
In elements.polymer-project.org/elements/iron-ajax, clicking on "Demo" takes you to a strange video feed

### ISSUE THREAD

**Issue by mercmobily** [Polymer/polymer#2750]
If you go to http://elements.polymer-project.org/elements/iron-ajax, clicking on "Demo" takes you to a strange page with a list of videos rather than a demo.
What's even stranger, at least two videos in the feed seem to be about Polymer Clay figures rather than Polymer itself (as in, the software).

Sorry to pollute the main issue list, but I just couldn't find the right spot for this report... the iron-ajax repo doesn't seem to be at fault, and I cannot find the repository for elements.polymer-project.org!

**Comment by ebidel** [comment]
That is the demo :) It's a .json free from the YouTube API.

**Comment by mercmobily** [comment]
Oh my, I feel so so so so so so so so so so stupid!!!!!
