### ISSUE TITLE
Consider issues related to property bindings to accessor properties

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#277]
Should we support published/bindable properties that are accessors?

Consider that if A is bound to B and B is a getter/setter, then setting A may result in the value A not being the value that was set.

Presumably in the case that the user does this on the object containing B, there is some expectation that this may occur. Imagine for example, a selector that has a valid index range of 0-10 and the user sets the value to 11 and the setting is disallowed.

If that selector's index is bound to something else (imagine a complex graph of bindings) it's much harder to reason about the expected/allowed values and the user may be confused.

There's a separate issue related to published properties: currently we get the value of published properties on the element prototype to infer property type. For accessors we should not do this as the value very possibly will not make sense. Instead we should probably just pick a type.

**Comment by RenaudF** [comment]
The previous fiddle doesn't work for me but I think it's the same issue I have here: http://stackoverflow.com/questions/28348140/polymer-single-template-instances-not-updating

**Comment by christianbauer** [comment]
I only use JS in anger, so I have no idea whats really happening here. But what I'm seeing in my code right now seems related, and I'm a bit surprised that it works in FF, Safari, but not in Chrome. If it would be broken everywhere I could at least give up and not use getters/setters at all. 

```
<polymer-element name="some-test">
    <template>
        Some attribute: {{someObject.someAttribute}}
        <br/>
        Some tick: {{foo}}
        <br/>
        <button on-click="{{update}}">Update</button>
    </template>
    <script>
        Polymer({
            created: function () {
                this.someObject = {};

                var _someAttribute;
                Object.defineProperty(this.someObject, 'someAttribute', {
                    get: function () {
                        return _someAttribute;
                    },
                    set: function (v) {
                        _someAttribute = v;
                    }
                });

            },
            update: function () {
                this.someObject.someAttribute = "Hello " + Math.random();
                // TODO If you add this, it works in Chrome, too!
                // this.foo = "Tick " + Math.random();
            }
        });
    </script>
</polymer-element>
<some-test></some-test>
```

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
