### ISSUE TITLE
Can not invoke insertBefore() with parameter document/document.documentElement.firstChild/document.documentElement.lastChild

### ISSUE THREAD

**Issue by xfcjscn** [Polymer/polymer#287]
document, document.documentElement.firstChild, document.documentElement.lastChild are native dom object. They cannot pass assertIsNodeWrapper() during insertion. 
I got this issue which I include jquery-ui into my page. 
Below is the track trace:
Uncaught Error: Assertion failed wrappers.js:29
assert wrappers.js:29
assertIsNodeWrapper Node.js:19
mixin.insertBefore Node.js:238
constructors.forEach.names.forEach.constructor.(anonymous function) wrappers.js:337
(anonymous function) jquery-ui.js:12502
(anonymous function) jquery-ui.js:12511
(anonymous function) jquery-ui.js:12513

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
