### ISSUE TITLE
new Event breaks IE11

### ISSUE THREAD

**Issue by davidlwatsonjr** [Polymer/polymer#3014]
The new code to cache events is using `new Event`:

https://github.com/Polymer/polymer/blob/cb68ce54ebdcfb2d6f7342e801574881fb158076/src/standard/utils.html#L245

This breaks IE11:
`Object doesn't support this action`

Should this be a CustomEvent instead of an Event?

**Comment by davidlwatsonjr** [comment]
https://github.com/Polymer/polymer/pull/3015

**Comment by azakus** [comment]
Do you have webcomponents.js v0.7.18 installed? We provide a polyfill for the `Event` constructor.

**Comment by jshcrowthe** [comment]
I was having this issue as well. Updating to `v0.7.18` solved it for me.

**Comment by azakus** [comment]
@jshcrowthe Polymer 1.2.3+ depends on webcomponents `v0.7.18`.
Are you saying that bower didn't update them together for you?

**Comment by jshcrowthe** [comment]
I wasn't consuming webcomponentsjs via bower due to some weirdness in my asset pipeline. The polymer update did request `v0.7.18` I just had to manually bring it over.

**Comment by davidlwatsonjr** [comment]
Closing as 0.7.18 fixes the issue.
