### ISSUE TITLE
Enable CSS rules on top level element attributes

### ISSUE THREAD

**Issue by fozziethebeat** [Polymer/polymer#3016]
I'd like to specify a rule within a custom element that depends on the state of a top level element, such as body or html.  So something like this:

    <style>
      html[dir="rtl"] #someSubElement {
      ....
      }
    </style>

However, when doing this, polymer renames the styles for my custom element to be something like

    html[dir="rtl"].my-custom-element #someSubElement.my-custom-element { ... }

Which prevents the rule from ever applying.

Is there any way to scope only part of the CSS rule to the custom element?  Otherwise this requires tagging each potential element that needs RTL information with a RTL class, which is a lot less elegant.

**Comment by arthurevans** [comment]
That's what the `:host-context` selector is for:

    :host-context(html[rtl]) { 
      ...
    }

**Comment by fozziethebeat** [comment]
That's awesome and just what I needed!

Can that be added to the basic [Styling local DOM](https://www.polymer-project.org/1.0/docs/devguide/styling.html) guide?  I discovered it's in Eric's post about [shadow dom](http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/) which i never got to reading.

**Comment by arthurevans** [comment]
Absolutely should be there. Let's just move this bug over to the docs repo.

**Comment by arthurevans** [comment]
This issue was moved to Polymer/docs#1438
