### ISSUE TITLE
Observers being called before the element is ready or attached.

### ISSUE THREAD

**Issue by tbone587** [Polymer/polymer#3021]
It seems like the properties are parsed in order and if you have an observer setup on a property which references a property declared after, that property will be undefined.

properties:{

```
"myObject":{
    "type": Object
    "value": { "someProp": null }
    "observer": "myObjectChanged"
}

"myBoolean":{
    "type": Boolean,
    "value": false

}
```

}

myObjectChanged: function(_arg1, _arg2){

```
// This logs as undefined when the observer runs before this element is ready or attached.
console.log( this.myBoolean );
```

}

**Comment by arthurevans** [comment]
Yep. If you depend on multiple properties, you should be using a multi-property observer:

    observers: [
       'myObjectChanged(myObject, myBoolean)'
    ]

**Comment by tbone587** [comment]
That makes sense, however the only reason i went with the other way is because I wanted to see the old and new values on the observer.  So I still feel like this is a bug, unless this was intended behavior.

**Comment by arodic** [comment]
I think this is the consequence of observers being synchronous. I managed to work around this issue by adding debouncers to most of the observer functions. However, this proved to be a bad practice leading to more unexpected behaviors. IMHO, the observers should stay synchronous, EXCEPT in the case of initialization. In other words, if the element is not ready, the observers should hold off from firing right away.

**Comment by ciampo** [comment]
Any update on how to work around this?

**Comment by TimvdLippe** [comment]
This has been fixed in Polymer 2: http://jsbin.com/qolotufudu/edit?html,console,output
