### ISSUE TITLE
dom-change event does not fire when HTML is moved to modal

### ISSUE THREAD

**Issue by philmh-isams** [Polymer/polymer#3024]
I have a Polymer element that has a dom-if template with a on-dom-change attribute, and inside is a div that calls a function to set the id:
```
<template is="dom-if" if="{{!isCombined(item)}}" on-dom-change="fieldChanged">
    <div id$="[[internalId(item.id)]]"></div>
</template>
```

When I first load my page, this builds and fires the dom-change event handler "fieldChanged".

However, I am using this template within a nanoModal and it seems the dom-repeat and dom-if templates are executing as I can see the internalId function being called, but the fieldChanged event handler is not being fired.

Many thanks.

**Comment by arthurevans** [comment]
Are you expecting the `dom-change` event to be fired when the `isCombined(item)` value changes? Or the `internalId(item.id)` value? It should only be fired for the former. 

Not familiar with nanoModal, but perhaps you can include a little more code to clarify the issue.

**Comment by philmh-isams** [comment]
That would explain it. Is there a way to know when a <template> has finished rendering its contents?
I have resolved the issue by using 'async' with a slight delay for now, but wondered if there might be a better way, as I need the <div> elements to exist in the DOM before I execute another process.

It may be that the use of Polymer is incorrect as the <div> tags are being converted into other DOM elements, like input and select, depending on some configuration values supplied. It may be correct to use dom-if, but the there are multiple conditions and this section of code is used twice in the Polymer component. It may be that the component is too complex.

**Comment by azakus** [comment]
If you depend on the element existing then you can remove the dom-if and just use hidden, as it would be effectively the same.
```html
<div id$="[[internalId(item.id)]]" hidden$="{{!isCombined(item)}}"></div>
```

**Comment by philmh-isams** [comment]
The issue is with the dom-repeat too, and not just the dom-if. Both are asynchronous calls.
