### ISSUE TITLE
upgrading to polymer 1.2.3 broke height

### ISSUE THREAD

**Issue by bastienarm** [Polymer/polymer#3028]
Hi there, 

I've just updated polymer from 1.2.1 to 1.2.3 (with a lot of polymer elements upgrade too)

When reloading my application, the html was not filling the entire page.
When taking a look at the css, i saw that the height of the <html> is 488.031px, without changing anything, and a 8px margin has been added to my body.

Does anyone encountered the same proble, or anyone has an idea about what goes wrong?

**Comment by zerodevx** [comment]
Is your body full-bleed? Something like:

```html
<style>
  html, body {
    margin: 0;
    height: 100vh;
  }
</style>
```
http://jsbin.com/satafajugu/edit?html,output

**Comment by ebidel** [comment]
Make sure you're importing the layout classes if you're using full bleed or using @zerodex's suggested CSS.

**Comment by bastienarm** [comment]
Ok, found it, thanks @zerodevx and @ebidel 

My body was :

```html 
<body unresolved class="fullbleed layout vertical">
</body>
```

But the iron-flex-layout.html wasn't included, that's why my body was not filling the entire page.

But, question : why before the update, no problem was encountered with the height of my body despite the fact that the iron-flex-layout was not included?
