### ISSUE TITLE
xlink:href bindings do not work

### ISSUE THREAD

**Issue by atotic** [Polymer/polymer#3060]
Inside an `<svg>` tag, binding to `<image xlink:href="{{imageUrl}}">` does not work.

Example: http://jsbin.com/ronuve/5/edit?html,output

I assume this is probably a general: "namespace bindings do not work" bug.

**Comment by Xaviju** [comment]
I've been trying to do it and experiencing same behavior
```<use xlink:href="{{icon}}"></use>``` or ```<use xlink:href$="{{icon}}"></use>```
The output is fine but the svg does not appear. If I add the code without the binding it works correctly
``` <use xlink:href="icon-error"></use> ```
Output is the same (except the polymer added classes) in devtools so its kind of a poltergeist to me.

Any workarounds?

**Comment by atotic** [comment]
Only workaround is to set attributes manually. You need to use namespace syntax:
```
element.setAttributeNS('http://www.w3.org/1999/xlink' , 'href', '#' + this.icon);

**Comment by Xaviju** [comment]
Another workaround is to share styles between components https://www.polymer-project.org/1.0/docs/devguide/styling.html#style-modules

**Comment by zoechi** [comment]
@Xaviju are you sure this is related to this issue?

**Comment by Xaviju** [comment]
oops! removing it!
