### ISSUE TITLE
Observers being called repeatedly when multiple property changes at the sametime.

### ISSUE THREAD

**Issue by yutingzhao1991** [Polymer/polymer#3061]
```js
observers: [ 'valueChanged(startDate,endDate)' ],

this.startDate = moment(start).format(DATE_FORMAT)
this.endDate = moment(end).format(DATE_FORMAT)
// then valueChanged will be called twice.
```
Is this is a bug ?
Any solution to resolve this problem ?

**Comment by yutingzhao1991** [comment]
I get a solution by myself. see [polymer-ext](https://github.com/yutingzhao1991/polymer-ext)

Add a extension option `asyncObservers` to Polymer.

**Comment by adelarosab** [comment]
Hi @yutingzhao1991, this is the expected behaviour.

You are observing two attributes. Every time you do an assignation, it produces a change in the DOM element. So one of your attributes is changing and the handler is triggered.

You can avoid null values just adding some conditions to your code. 
```javascript
if (startDate !== undefined && endDate !== undefined) {
    // do stuff
}
```

Or you can use `async` and `debounce` function in your observer trying to condense your calls.
```javascript
valueChanged: function(startDate, endDate) {
    this.async(this.debounce(this._valueChanged));
}
```

**Comment by yutingzhao1991** [comment]
@adelarosab Thanks. I Got it. But in my practice it is a frequently-used situation. Is it has any possibility to add a official api to Polymer?

**Comment by adelarosab** [comment]
@yutingzhao1991 I'm not part of the Google Team. But I guess with [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) as background, they'll keep the behaviour as simple as they can.

In fact, there is no way to assign/set several attributes in a DOM element at the same time.

I was thinking, and it could be a chance for you. You can use an `async` object.
```javascript
properties: {
    [...]
    async: {
        observer: 'valueChanged'
        type: Object,
        value: {
            endDate: 'whatelse', // nesspreso
            startDate: 'whatever'
        }
    }
}
```

```javascript
this.async = _.extend(this.async, {
    startDate: 'newDate',
    endDate: 'anotherDate'
});
```

I think with this example, you could group your attributes and make some meaningful observers.

**Comment by azakus** [comment]
@adelarosab is correct, the observer will be called for each argument. You can use `debounce` to wait for both values to update like in this JSBin: http://jsbin.com/kocegi/edit?html,console,output

I'm closing this issue, but feel free to open one about enhancing observers with your async use case.
