### ISSUE TITLE
Duplicate strings in array while using 'dom-repeat' throws error: 'Uncaught Error: unexpected key undefined'

### ISSUE THREAD

**Issue by chigur** [Polymer/polymer#3062]
Following is the element I made which throws an error mentioned in the title.

``` html
<link rel="import" href="../polymer/polymer.html" />

<dom-module id="data-list">
    <template>
        <template is="dom-repeat" items={{data}}>
            <div>{{item}}</div>
        </template>
    </template>
    <script>
        Polymer({
            is: 'data-list',

            properties: {
                data: {
                    type: Array,
                    value: function() {
                        return ['Random', 'Random'];
                    },
                    notify: true
                }
            },

            attached: function() {
                this.splice('data', 0, 1);
                this.splice('data', 0, 1);
            }
        });
    </script>
</dom-module>
```

This is caused by storing values of an array as keys in the object [`pmap`](https://github.com/Polymer/polymer/blob/master/src/lib/collection.html#L47).

**Comment by fredefox** [comment]
I have noticed this too. Only after seeing this issue did I realize that it happens when you use non-unique values in the array. Do you have a work-around?

**Comment by chigur** [comment]
@fredefox Using objects instead of primitive values should do the trick.

**Comment by fredefox** [comment]
Right you are! Thank you.

**Comment by chigur** [comment]
I would really love to contribute a PR for this bug if somebody guides me on how to go about it. It would be my first ever PR on GitHub :).

**Comment by MeTaNoV** [comment]
Just go ahead by following this: https://github.com/Polymer/project/blob/master/Contributing.md

**Comment by StokeMasterJack** [comment]
I too am getting this error. I am using an array of object which may contain duplicates. It happens on this line:

this.splice('selected', indexToRemove, 1);

and it seems t happen when deleting a duplicate for the second time.

**Comment by electrovir** [comment]
I have an issue related to this but I am not getting an error thrown.  Instead, when I use dom-repeat to bind an array with non-unique strings to input boxes, editing the text inside any input besides the first (using normal user interaction) changes the value in the first input box.

**Comment by TimvdLippe** [comment]
This has been fixed in Polymer 2: http://jsbin.com/fuqarizedo/edit?html,console,output
