### ISSUE TITLE
'Learn more' link on Polymer home page briefly loads tutorial page then reloads home page 

### ISSUE THREAD

**Issue by spoogle** [Polymer/polymer#3069]
On chrome most recent, iOS 9.1, iPhone 5S, hitting the 'Learn more' link on Polymer home page briefly loads a page which starts loading 'Introducing Polymer 1.0' but does not fully load it and then it reloads the Polymer home page.

**Comment by ebidel** [comment]
This issue was moved to Polymer/docs#1440
