### ISSUE TITLE
Loading a javascript file imperatively?

### ISSUE THREAD

**Issue by MeTaNoV** [Polymer/polymer#3070]
Hi,
I would like load a javascript module at run-time on certain condition, therefore, I would like to move my current:

`<script src="../path/to/file.js"></script>`

in a code like:

`loadScript(srcRef, onload, onerror)`

in a similar fashion to `importRef` for HTML file
Any suggestions?
(Note: I would like to avoid wrapping the script inside another HTML file)

**Comment by bedeoverend** [comment]
Take a look at [this sitepoint post](http://www.sitepoint.com/dynamically-load-jquery-library-javascript/) on dynamically loading the jQuery script - they show an example script that exposes a `loadScript` function that takes the first parameter url and second a callback on success. Is that kind of function what you're after? Should also be pretty easy to tweak that function to add in callback for errors - its just dynamically creating a script tag and assigning listeners.

**Comment by MeTaNoV** [comment]
Thanks @bedeoverend , basically yes! :)
I think I will write it and PR it! I thought there were some extra work done in importHref, but that is not the case, so the implementation will indeed be straightforward!
Something like this:
```javascript
    loadScript: function(source, onload, onerror) {
      var s = document.createElement('script');
      s.src = source;
      var self = this;
      if (onload) {
        s.onload = function(e) {
          return onload.call(self, e);
        }
      }
      if (onerror) {
        s.onerror = function(e) {
          return onerror.call(self, e);
        }
      }
      document.head.appendChild(s);
      return s;
    },
```
I just have to add the test... :)

**Comment by ebidel** [comment]
`imporHref` is basically just this, but for .html files (imports):
https://github.com/Polymer/polymer/blob/cb68ce54ebdcfb2d6f7342e801574881fb158076/src/standard/utils.html#L363

Going to close this since the OP's question was answered.
