### ISSUE TITLE
Polymer Component Communication

### ISSUE THREAD

**Issue by paranoid-android** [Polymer/polymer#3071]
Hello,

One challenge I find with Polymer is in component communication model. Often times I have elements nested 3 or more levels deep. Especially when laying out components, I run into problems passing messages between components. 

In Angular, I have access to a ($broadcast)[https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$broadcast] method to send messages to children elements. There is also the ($emit)[https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$emit] method to send messages up the chain.

From what I can tell, Polymer has listeners. However, listeners only work with the immediate parent. In addition, there isn't a good way to send a message down the tree. The only way I could figure out is to use a DOM selector and then call a method on a component that way. Is my understanding correct or is there something I'm missing. The Angular approach seems easier to work with.

**Comment by LM450N** [comment]
Maybe [Pub/Sub](https://elements.polymer-project.org/elements/iron-signals) could help you.

**Comment by ebidel** [comment]
I wrote a lengthy article on approaches for communicating between elements:
https://www.polymer-project.org/0.5/articles/communication.html

It's targeted at Polymer 0.5, but the ideas are still sound. As @LM450N points out, for 1.0 https://elements.polymer-project.org/elements/iron-signals exists for pub/sub.

**Comment by ebidel** [comment]
Closing as this is a question and not an issue.
