### ISSUE TITLE
Unable to install paper elements

### ISSUE THREAD

**Issue by paranoid-android** [Polymer/polymer#3072]
Hello,

I am working on a Polymer app. I attempted to install the Iron elements and Paper elements via bower. In an attempt to do this, I followed the docs provided (here)[https://elements.polymer-project.org/guides/using-elements]. I ran the following from the command-line:

```
bower install PolymerElements/iron-elements --save
bower install PolymerElements/paper-elements --save
```

The iron elements installed properly. However, when I attempted to install the paper elements, I received the following error:

```
bower EMALFORMED    Failed to read /Users/user/MyProject/src/res/packages/paper-dialog-scrollable/.bower.json
```

I'm not sure why I would receive this error attempting to install the components.

**Comment by ebidel** [comment]
I just ran `bower install PolymerElements/paper-elements --save` without issue. What version of bower are you using?

**Comment by paranoid-android** [comment]
@ebidel I am using Bower 1.6.5.

**Comment by ebidel** [comment]
Can you try:

`bower cache clean`
`rm -rf bower_components`
`bower install`

**Comment by paranoid-android** [comment]
Awesome. That worked! Thank you for helping me get over this hump so I can dive into Polymer over the holiday!
