### ISSUE TITLE
Reduce `dom-if` performance overhead

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#3073]
Today there is more runtime overhead for using a `dom-if` than desirable.

The following possible low-hanging fruit have been identified:
- Default `false` values for `restamp` and `if` cause observers & debouncers to queue that ultimately no-op for falsey templates
- Templatizer handling for late-binding of outer parent (host) properties is costly and can be optimized to avoid use of actual getters
- Use of the Templatizer archetype seems like a non-value-add indirection since there is only ever one instance

**Comment by azakus** [comment]
@kevinpschaaf is this still relevant?

**Comment by kevinpschaaf** [comment]
Yes, I have a branch with at least the first 2 covered in https://github.com/Polymer/polymer/tree/3073-kschaaf-domif-perf that we should button up and merge.  Can put that on my list this week.

**Comment by TimvdLippe** [comment]
Closing per https://github.com/Polymer/polymer/pull/3440#issuecomment-320828223
