### ISSUE TITLE
Events guide doesn't mention `x-changed` events.

### ISSUE THREAD

**Issue by bicknellr** [Polymer/polymer#3078]
The [events guide](https://www.polymer-project.org/1.0/docs/devguide/events.html) doesn't talk about `x-changed` events even though it explains other globally available events (i.e. gestures). However, `x-changed` events are explained in the [data binding guide](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html), maybe we should add a short description and a link?

**Comment by ebidel** [comment]
This issue was moved to Polymer/docs#1444
