### ISSUE TITLE
Declaratively binding sub properties

### ISSUE THREAD

**Issue by David-Mulder** [Polymer/polymer#3081]
Looking through all open and countless more closed issues is a daunting task, but I couldn't find an issue for this. It would be very useful if it was possible to declaratively bind to a sub property of an element. To give a typical example, let's say we have a generic element that consumes an API `<my-api>`. We set a method and bind the data:

```
 <my-api method="users/list" data="{{data}}"></my-api>
```

so far so good, but then we wish to request a specific user and we have to send along specific parameters. In my project I build an element like

```
<my-api method="user/:id" params="{{params}}" data="{{data}}" auto></my-api>
```

and then have to have an observer on `userId` which in turn sets `params.id` as `this.userId`, as we can't declare _all_ properties that all the different API calls need we have to use a generic `params` attribute, but it would be great if we could instead write:

```
<my-api method="user/:id" params.id="{{userId}}" data="{{data}}" auto></my-api>
```

The only downside would be that the `.` is a valid attribute name character, and yet wouldn't be supported by Polymer... but I hardly think it would work now either way.

**Comment by TimvdLippe** [comment]
In Polymer 2 you can actually do this: http://jsbin.com/xinonuhapu/edit?html,console,output Override `_parseTemplateNodeAttribute` and then evaluate the binding and use `_setPendingPropertyOrPath` to set the property.
