### ISSUE TITLE
Media queries don't (always) work in a style module

### ISSUE THREAD

**Issue by bushuyev** [Polymer/polymer#3087]
Please take a look at 
http://plnkr.co/edit/ig2qpsguLzpBgwRx0RjE?p=preview

ZZZ supposed to be green when less than 30em and red otherwise
When opened in chrome dev tools emulating mobile device, the color doesn't change on resize if loading from here
http://run.plnkr.co/plunks/ig2qpsguLzpBgwRx0RjE/

but it works when loading from within pluk:
http://embed.plnkr.co/ig2qpsguLzpBgwRx0RjE/preview

**Comment by ebidel** [comment]
http://run.plnkr.co/plunks/ig2qpsguLzpBgwRx0RjE/ changes from red -> green when I resize both Chrome and FF. What are the exact repo steps?

**Comment by bushuyev** [comment]
The seps are just open the dev tools and resize. The video: https://www.dropbox.com/s/zdrqeq0od7r70nf/out.mkv?dl=0

And it works in FF for me too. The Chrome version is 46.0.2490.86 (64-bit).

**Comment by bushuyev** [comment]
and it also doesn't  work from real mobile dev (lenovo A316, chrome  46.0.2490.76). At least when I scale the screen so that zzz occupy all width it's still red.

**Comment by JeremybellEU** [comment]
Looking at the video, I see a difference on the right part of the screen.
In the working example, there is a small margin between the red background and the right border of the screen.
However, in the broken example, this margin does not exist.

I have tried to replicate this specific issue, but was unsuccessful. Could you maybe (in the broken example) inspect the width of the element? It might be overflowing or something similar.

**Comment by ebidel** [comment]
You're testing in device mode emulation, perhaps its a bug in that tool? When I tested, I just resized the browser window.

**Comment by bushuyev** [comment]
Perhaps, but both are made by google:) And it didn't work in Lenovo too. I'll try to find more devices to test in.

**Comment by bushuyev** [comment]
there were no  <meta name="viewport" content="width=device-width, initial-scale=1">... so the plnkr is just broken. Sorry for taking your time.

Although the real app I have problem in still doesn't work with very same symptoms as plnkr and it has meta. So there maybe something else.
