### ISSUE TITLE
`linkPaths` doesn't accept arrays as paths

### ISSUE THREAD

**Issue by David-Mulder** [Polymer/polymer#3090]
Most (if not all) functions seem to allow arrays instead of paths (which is absolutely wonderful, as it looks a million times better), however this seems not to be the case for `linkPaths`.

**Comment by devinivy** [comment]
Agreed that this is a small issue.  This seems like low-hanging fruit– would a PR be considered?

**Comment by kevinpschaaf** [comment]
@devinivy Sure thing!  It can just call `_get` similar to other public path API's to create a string path from an array/string with array indices converted to keys:

```
        var info = {};
        var array = this._get(path, this, info);
        // ... link using `info.path`
```

**Comment by devinivy** [comment]
Finally got around to this– PR posted at #3558.

**Comment by TimvdLippe** [comment]
This was implemented in Polymer 2: https://www.polymer-project.org/2.0/docs/api/mixins/Polymer.PropertyEffects#method-linkPaths Sorry for not notifying you sooner :cry:
