### ISSUE TITLE
Warn when using incorrect binding syntax on native elements?

### ISSUE THREAD

**Issue by indolering** [Polymer/polymer#3091]
I just wasted a day chasing down a bug in how IE/Edge handled a binding to a numeric input field (`<input type="number" value="[[value]]">`) and the solution was to use `value$="[[value]]"` instead.  I've created tickets to improve the docs and Polylint, but both the `$=` and `{{hostProp::target-change-event}}` have caused me a quite a bit of frustration.

I suspect this is a pain point for newbies in general and it would be ideal if Polymer warned when using incorrect bindings on native elements.

**Comment by MeTaNoV** [comment]
I did it too, and since then, I am more cautious...

@garlicnation  +1 if Polylint could detect that!

**Comment by azakus** [comment]
Related to (and probably blocked on) #3367

**Comment by TimvdLippe** [comment]
The Polymer linter now warns on such errors. Check out https://github.com/Polymer/polymer-linter/blob/master/src/polymer/set-unknown-attribute.ts for the implementation. You can install the linter in your editor as well by installing either https://github.com/polymer/atom-plugin or https://github.com/polymer/vscode-plugin
