### ISSUE TITLE
No email from slack community signup

### ISSUE THREAD

**Issue by QuantumInformation** [Polymer/polymer#3096]
I tried to sign up for the slack community but I get no email.

![image](https://cloud.githubusercontent.com/assets/216566/11429343/9c51d4a8-946e-11e5-939a-3f7905b9d5e4.png)

![image](https://cloud.githubusercontent.com/assets/216566/11429345/a6643f1c-946e-11e5-8cd3-6b8a87570c43.png)

**Comment by MeTaNoV** [comment]
Not really the place to report...
