### ISSUE TITLE
platinum-sw-fetch event handler for POST requests

### ISSUE THREAD

**Issue by ioantomulesei** [Polymer/polymer#3097]
I'm using platinum-sw-fetch component to map fetch requests to handlers inside service workers. It works well for "GET" requests but not for "POST" requests. One of my use case is returning fixture data for my requests.
After digging polymer code, I found that are defined routes (by sw-toolbox library) only for "GET" requests:
```javascript

sw-toolbox-setup.js
...
 if (typeof handler === 'function') {
        global.toolbox.router.get(routeParams[0], handler, originParam);
      } else {
        console.error('Unable to register sw-toolbox route: ', routeParams);
      }
...
```

Is there an option for registering handlers for "POST" request?

**Comment by adelarosab** [comment]
Hi @ioantomulesei,

This is just a suggestion because I'm not part of the Google team, but I think this issue should be reported in https://github.com/PolymerElements/platinum-sw/issues (which is the repo of platinum elements).

**Comment by ebidel** [comment]
This issue was moved to PolymerElements/platinum-sw#82
