### ISSUE TITLE
Form generator. Dynamically added elements don't get data-binded. 

### ISSUE THREAD

**Issue by 4dinterface** [Polymer/polymer#3098]
Unable to write the generators form. I can not anticipate all the possible controls in the template.
Please return the data binding for dynamically created elements.

**Comment by hickscorp** [comment]
I'm facing a similar problem (From what I understand of the OP =/ ).
What would be the 1.0 equivalent of the processed [described here](https://groups.google.com/forum/#!msg/polymer-dev/tiVpGwMJSKo/-72lTvDr7XIJ), eg the old `.bind()` method?

**Comment by azakus** [comment]
@kevinpschaaf, @sorvell thoughts on adding back this functionality?

**Comment by azakus** [comment]
Dupe of #1303
