### ISSUE TITLE
Appending an element to <content> 

### ISSUE THREAD

**Issue by mercmobily** [Polymer/polymer#3102]
I have the simplest element ever created:

    <link rel="import" href="bower_components/polymer/polymer.html">

    <dom-module id="observing-test">
      <template>
        <p>This is the title:</p>
        <content id="top" select="#title"></content>
        <p>This is the content:</p>
        <content id="bottom" select="#content"></content>
      </template>

      <script>
        Polymer( {
          is: 'observing-test',

          ready: function(){
            console.log("Ready!");

            Polymer.dom( this.$.top ).observeNodes( function( info ) {
              console.log(" TOP CHANGED!", info );
            });

            Polymer.dom( this.$.bottom ).observeNodes( function( info ) {
              console.log(" BOTTOM CHANGED!", info );
            });
          },

          attached: function(){
            console.log("Attached!");
            OT = this;
          }

        })
      </script>
    </dom-module>

Using it the usual way:

    <!doctype html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="description" content="The basic page">
      <meta name="author" content="Tony Mobily">
      <title>The title</title>
      <link rel="import" href="test-component.html">
    </head>

    <body>

    <observing-test>
      <div id="title"><p>TITLE!</p></div>
      <div id="content"><p>CONTENT!</p></div>
    </observing-test>

    </body>

Question: how can I add an element to either one of them so that the observer is actually triggered? (other than when the element is created) In theory, it shouldn't even be possible since the selector here  `<content id="top" select="#title"></content>` should attach the element that, in the light DOM, has the matching ID.

So, does it actually ever make sense to observe `<content>` nodes? I am very confused about this (but then again, I am easily confused!)

**Comment by azakus** [comment]
Make sure to use `Polymer.dom(element).appendChild` to trigger distribution and fire the observer: http://jsbin.com/qopowu/edit?html,js,console,output

**Comment by mercmobily** [comment]
Allow me to actually answer this question, since somebody else might be interested in the future.

If you have an element like this:

        <link rel="import" href="bower_components/polymer/polymer.html">
        <dom-module id="observing-test">
          <template>
            <p>This is the list of lines:</p>
            <content id="c" select=".line"></content>
          </template>

          <script>
            Polymer( {
              is: 'observing-test',

              ready: function(){
                console.log("Ready!");

                Polymer.dom( this.$.c ).observeNodes( function( info ) {
                  console.log("CHANGED!", info );
                });
              },

              attached: function(){
                console.log("Attached!");
                // GLOBAL, so that we can play we it in the console
                OT = this;
              }

            })
          </script>
        </dom-module>

Keep in mind that the composite DOM is the result of the local DOM, with `<content>` tags resolved.
So, in order to "add" element to what's placed in leu of  a <content> element with a `select`, you need to add elements to the light DOM that will match the `<content>`'s selection.
For example if your page  contains:

    <observing-test>
      <p>Some content</p>
      <p class="line">Moved line 1</p>
      <p class="line">Moved line 2</p>
      <hr>
      <p class="line">Moved line 3</p>
    </observing-test>

If you then create an element:

    p = document.createElement('p')
    p.appendChild(   document.createTextNode('text')   )
    p.className = 'line'

And add it to the light DOM:

    Polymer.dom( OT ).appendChild( p )

The observer on the `<content>` element gets triggered.
Note that you _must_ assign the class before hand. If you do:

    p = document.createElement('p')
    p.appendChild(   document.createTextNode('text')   )

And then you append the child:

    Polymer.dom( OT ).appendChild( p )

And only _then_ you add the right class to the element:

    p.className = 'line'

The callback doesn't get triggered.

The original question didn't really "work" because the filter was based on an ID. So, only one element is ever going to match -- and therefore get selected by `<content>`.

**Comment by azakus** [comment]
> The original question didn't really "work" because the filter was based on an ID. So, only one element is ever going to match -- and therefore get selected by <content>.

This is technically not true. Nothing is stopping you from using the same ID multiple times, and all should match the selector for `<content>`

**Comment by mercmobily** [comment]
A little bit off-topic, but still...

In HTML4, the  [the specs](http://www.w3.org/TR/html4/struct/global.html
) say:

    7.5.2 Element identifiers: the id and class attributes
    Attribute definitions
    id = name [CS]
      This attribute assigns a name to an element. This name must be unique in a document.

[HTML5](http://www.w3.org/TR/html5/dom.html#the-id-attribute) is less specific:

    3.2.5.1 The id attribute
    The id attribute specifies its element's unique identifier (ID). [DOM]

But still... aren't we really meant to keep IDs unique?

**Comment by MeTaNoV** [comment]
that's the purpose of an ID, no? :)
