### ISSUE TITLE
Dynamically creating an element causes `dataHost` to stay `undefined`

### ISSUE THREAD

**Issue by David-Mulder** [Polymer/polymer#3103]
Per title, using

    var el = document.createElement(...);
    someEl.appendChild(el); // Polymer.dom(someEl).appendChild(el)

will end up with an `undefined` `dataHost`.

**Comment by David-Mulder** [comment]
And just for the record, I am perfectly aware that `dataHost` isn't a publicly documented property, however consistent `dataHost` behavior is quite important when you are working with the `templatizer` behavior.

**Comment by David-Mulder** [comment]
For anybody encountering this issue: Right now I added a hack where I set the `dataHost` automatically to the `parentNode` `dataHost` if `dataHost` is `undefined`.

**Comment by azakus** [comment]
I think this is a dupe of #3098

**Comment by azakus** [comment]
Actually, a specific duplicate of missing support for dynamic data binding, #1303

**Comment by bluEEil** [comment]
Hello, I have come to the same problem recently and couldn't find a solution in present time. I also didn't find any answers in #1303 (which Im not sure how is relevant exactly) any ideas how I can achieve this to work?
