### ISSUE TITLE
paper-input underline breaks if a paper-dialog is opened as an on-focus event

### ISSUE THREAD

**Issue by ianbitts** [Polymer/polymer#3104]
The animated underline of a paper-input element becomes becomes stuck in the "focused" state if a paper-dialog is toggled as an on-focus event of the paper-input element.

Example code:
```
<paper-input id="myInput" on-focus="_toggleDialog"></paper-input>
<paper-input id="myOtherInput"></paper-input>
<paper-dialog id="myDialog></paper-dialog>
<script>
_toggleDialog: function() {
    this.$.myDialog.toggle();   
}
</script>
```

**Comment by ebidel** [comment]
This issue was moved to PolymerElements/paper-input#263
