### ISSUE TITLE
`elementForItem` on dom-repeat

### ISSUE THREAD

**Issue by David-Mulder** [Polymer/polymer#3105]
This might sound like a weird request as one normally shouldn't manipulate the DOM directly, however realistically this is something one does end up needing from time to time. For example when implementing the Material Design Data Table spec you end up needing to set tooltips depending on whether a table header overflows. Easy enough to do, but you do need to get a reference to the specific element to check the overflow. I normally end up adding a data property and then querying for it, but that's quite ugly in practice.

**Comment by sandro-k** [comment]
Had the same issue a couple of times. Right now I am using a unique data attribute or ID value to find the right element. Not as clean as I want it to be and would be very interested in a proper solution.
