### ISSUE TITLE
Unable to install polymer through bower 

### ISSUE THREAD

**Issue by JuanAntelo** [Polymer/polymer#3106]
Here is my bower.json 
```
{
  "name": "polymer3",
  "authors": [
    "junior <antelo.juan@gmail.com>"
  ],
  "description": "",
  "main": "",
  "moduleType": [],
  "license": "MIT",
  "homepage": "",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "app/bower_components",
    "test",
    "tests"
  ]
}
```

Here are the commands I am running in my terminal : 

```
➜  polymer3  bower install --save Polymer/polymer#^1.2.0
zsh: no matches found: Polymer/polymer#^1.2.0
➜  polymer3  bower install --save Polymer/polymer#^1.0.0
zsh: no matches found: Polymer/polymer#^1.0.0
```

**Comment by ebidel** [comment]
I'm unable to repo this using bower 1.6.8. You could also try `bower cache; bower install --save Polymer/polymer#^1.2.0`. Or use the full github url instead of the shorthand.

**Comment by JuanAntelo** [comment]
I upgraded my bower to 1.6.8 and ```bower install --save Polymer/polymer#^1.2.0``` still did not work. 

However when I pulled directly from git I was able to get it to work.
