### ISSUE TITLE
Typo in Guides & Resources (https://www.polymer-project.org/1.0/)

### ISSUE THREAD

**Issue by anujgtm** [Polymer/polymer#3109]
From Guides & Resources page navigate to Browser Compatibility ( https://www.polymer-project.org/1.0/resources/compatibility.html)

Under subheading - Should I use webcomponents-lite.js or webcomponents.js? 

This is misspelled as Thsi

"Thsi version contains the full Shadow DOM polyfill, which is known to have performance overhead."

**Comment by arthurevans** [comment]
Already fixed in https://github.com/Polymer/docs/commit/ed894ddf56321086b145286fc65a20ba372fbf2a, which will show up the next time we update the site. Thanks for the report!
