### ISSUE TITLE
importHref should load imports asynchronously

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#3113]
`Polymer.Base.importHref` doesn't load imports asynchronously. In apps, this can cause layout flashes as the import is added to the DOM and loads. I've witnessed this on a couple of apps were we're using `importHref` to dynamically load bundles, asynchronously.

Instead, loading it with the `async` attr take it out of rendering and solves the issue.

**Comment by kevinpschaaf** [comment]
Can you provide a repro of how the layout "flashes" when a sync import is added to the document?

It doesn't make sense that a sync import would cause fouc and that making it async would fix it, without there being some sort of underlying Chrome bug, so it's worth understanding what you're actually seeing.

**Comment by ebidel** [comment]
Sure. Here are some examples.

Sync load (flash):

![sync](https://cloud.githubusercontent.com/assets/238208/11493213/e8ffeac6-97aa-11e5-9f9a-59933979d7a2.gif)

Sync load (flash):

![codelabs_sync](https://cloud.githubusercontent.com/assets/238208/11493217/ffb1d892-97aa-11e5-909c-d7103024af77.gif)

Async load (no flash, but you see elements fade in when they're upgraded):

![codelabs_async](https://cloud.githubusercontent.com/assets/238208/11493220/0ea91752-97ab-11e5-9791-cecf0671289d.gif)

Test app (run in canary so you dont need to babel):

1. `git clone https://github.com/ebidel/polymer-experiments`
-  `cd polymer-experiments/polymersummit/fouc/`
- `bower install`
- Remove ".v" in https://github.com/ebidel/polymer-experiments/blob/master/polymersummit/fouc/binding.html#L10 to use the unvulcanized version.

Serve up binding.html. It won't produce a flash.

5. To make it flash, change https://github.com/ebidel/polymer-experiments/blob/master/polymersummit/fouc/elements/bootstrap.html#L61 by adding `false` as a 2nd param to `importHref`. That makes it sync:

        importHref('elements/elements-no-polymer.v.html', false).then(function(link) {

**Comment by kevinpschaaf** [comment]
Reproduced the blinking issue down to an apparent chrome bug related to async imports, filed here: https://code.google.com/p/chromium/issues/detail?id=564758

**Comment by JeremybellEU** [comment]
@kevinpschaaf Your link results in a 403.

**Comment by ebidel** [comment]
It's restricted, internal for some reason.

**Comment by kevinpschaaf** [comment]
@JeremybellEU Sorry, should be unrestricted now.

**Comment by JeremybellEU** [comment]
:+1:

**Comment by ebidel** [comment]
Default will be sync, but we're adding the optional 4th arg for async :)
