### ISSUE TITLE
Using default values with computed properties can result in observers being called twice.

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#3117]
Default values are not supported for computed properties. However, these values can sometimes be applied during configuration. This should explicitly be disabled and a check for default values with computed properties should be added to the linter.

We may consider adding better support for computed property defaults in the future, but getting these values to configure properly will require some work.

**Comment by sorvell** [comment]
Note, users that want default values for computed properties should be able to set the value at `ready` time if it is unset.

**Comment by hickscorp** [comment]
No idea if this is related. Yesterday I observed a rather odd bug.
I had a component defined with a property, having a default value.
When the component was instantiated twice, I discovered that both component were actually sharing the same instance of the property... Will try to put up a JSBin showing the issue.

**Comment by MeTaNoV** [comment]
this is normal: if we want a different value at each instance, you must use a function (See [Documentation](https://www.polymer-project.org/1.0/docs/devguide/properties.html#configure-values))

**Comment by devinivy** [comment]
@sorvell do I understand you correctly– you may actually set the value of a computed property during `ready()` if it is not yet set, but not during any other time?  I'm surprised that there's any time that the computed property could be set– I think this is a little confusing and would support having the ability to set defaults for computed properties.

**Comment by TimvdLippe** [comment]
This seems to be fixed in Polymer 2: http://jsbin.com/xiteteqeyo/edit?html,console,output
