### ISSUE TITLE
An elegant way to store globals without bothering about creation order

### ISSUE THREAD

**Issue by hickscorp** [Polymer/polymer#3118]
Hello,

I faced a problem recently using Polymer, and found a very elegant solution that I would like to share.

Let's say that inside multiple components you would like to use a shared component containing globals, or even logic that you want to share. A mixin is out of the question, as you want to encapsulate your business logic inside something that makes sense, and is accessed in some kind of a **singleton** way (Eg for any "registration identifier" you use, a single instance of an object should always be retrieve, wherever in your application you ask for it).

Using globals is neat, but what if your component takes time to initialize, maybe it won't be ready when other components will need it.

So I came up with this idea: a deferred registry, here comes a bit of code:

```
<link rel="import" href="../polymer/polymer.html">


<dom-module id="pqr-deferred-registry">
  <template>
    I am an object deferred registry, and I'm completelly hidden.
  </template>
</dom-module>

<script>
  'use strict';
  (function() {
    var instances   = {};

    var Deferred  = function() {
      this.promise  = new Promise(
        (function(resolve, reject) {
          this.resolve = resolve;
          this.reject = reject;
        }).bind(this)
      );
      this.then     = this.promise.then.bind(this.promise);
      this.catch    = this.promise.catch.bind(this.promise);
    };

    Polymer({
      is:             'pqr-deferred-registry',
      hostAttributes: {
        hidden:         true,
      },
      properties:     {
        instances:      {
          type:           Object,
          readOnly:         true
        }
      },
      _deferOrReuse:  function(tag) {
        var p           = instances[tag];
        if (!p)
          p             = instances[tag] = new Deferred;
        return          p;
      },
      set:            function(tag, obj) {
        this._deferOrReuse(tag).resolve(obj);
      },
      get:            function(tag) {
        return this._deferOrReuse(tag).promise
      }
    });
  })();
</script>
```

Basically you could put inside any of your component a small invocation of this registry, like so:

```
<pqr-deferred-registry id="registry"></pqr-deferred-registry>
```

Note that doing so will allow a component to access the registry using `this.$.registry`. It's also worth mentioning that whatever the `id`, the same "static" backend is used inside the registry, so all instances of the registry will be able to access objects you register inside.

Then, anywhere from your component, you could register something with the registry, let's say in a component `x-foo`:

```
...
ready: {
  this.$.registry.set('myAwesomeObject', something);
},
...
```

Now, let's say another component of yours (Let's say `x-bar`) needs to access this object you've set... But you're not sure if when your component needs it it's registered yet. The registry has you covered:

```
...
_fromAnyMethod: {
  this.$.registry.get('myAwesomeObject').then((function(res) {
    // At this point, the "res" variable points to the object that will be or was registered.
  }).bind(this));
},
```

What do you guys think? Anything already in the code base that would make this useless / duplicate?

**Comment by hickscorp** [comment]
@MeTaNoV What does "/sub" mean?

**Comment by MeTaNoV** [comment]
@hickscorp (subscribe so that I am notified by email :) it is just a dummy comment)

**Comment by hickscorp** [comment]
@MeTaNoV Oh! That explains a lot now. Thanks for explaining :)

**Comment by MeTaNoV** [comment]
@hickscorp BTW, `<iron-meta>` does not solve already your use-case?

**Comment by hickscorp** [comment]
@MeTaNoV  No, as I sometimes discovered that the value wasn't yet set in the central store (Race condition on element creation, sometimes I get a read before a register). This is why I've put some lightweight deferred resolution mechanisms in it.

**Comment by azakus** [comment]
One problem I see with your approach here is that you can't update any values in the store.
Once an `instance` is resolved for a `tag`, the backing Promise will always return that value.

Perhaps an evolution of this could be added to `iron-meta` at some point, but that is outside the scope of Polymer itself.

If you'd like, I can move this issue to the `iron-meta` repo.

**Comment by MeTaNoV** [comment]
oh yeah @azakus , I use `akc-meta` currently because it supports data-binding...

**Comment by hickscorp** [comment]
@azakus What do you mean you cannot update a value? `registry.set('foo', myNewValue);'`, then any subsequent call to `registry.get('foo').then(...);` will resolve to the new one.

**Comment by azakus** [comment]
@hickscorp This should be a pretty straightforward example of the problem: http://jsbin.com/nafawi/edit?html,output.

Calling `set` again with the same key will not update the value, as you can't re-resolve a Promise.

**Comment by hickscorp** [comment]
@azakus You're right! We should close this issue for now.
