### ISSUE TITLE
Nested component observation. I'm confused.

### ISSUE THREAD

**Issue by hickscorp** [Polymer/polymer#3120]
Hello,

Edit: This might be related to #3120.

Consider [this example](http://jsbin.com/hozifuhuqe/edit?html,console,output) (See gist [right here](https://gist.github.com/anonymous/b9df2b4ea800eafbe203)).

A parent (`x-parent`) component instantiates a child component (`x-foo`) and grabs a reference to it (`this.foo = this.$.foo;` maybe that's what i'm doing wrong?), to pass it to another child component (`x-bar`) via binding (`<x-bar foo="{{foo}}"></x-bar>`).

Then, the `x-parent` and `x-bar` components try to observe a path in the `x-foo` instance (`status`).

## Expected result:

Whenever the `x-foo` component sets its status to something different, all 3 components should be notified, as they all subscribed to it.

## Observed behavior:

At first, all 3 components are notified of the `x-foo`'s status change. But then, only the `x-foo` continues to get notified, both the `x-parent` and the `x-bar` skip notifications.

## Explanation Needed / Docs Clarification:

There should be some way to:

- Have a property set to an instance of another component (Via it's `id` maybe?).
- Be able to bind to properties within nested components.

## Notes

I tried messing around with virtually everything I could think of. I tried observing `foo.*`, I tried using listeners to `something-changed`, etc. Every time I'm hitting a different wall, so I really think it's a matter of explaining me (And maybe clarifying the documentation) how to achieve this very specific scenario of having nested components references being observed.

**Comment by MeTaNoV** [comment]
From what I understand, you try to bind a property to the instance of an element?
The serialization/deserialization of attributes will rip off all methods of that reference, therefore it cannot work as expected.

**Comment by hickscorp** [comment]
@MeTaNoV I'm not sure I understand what you mean. I'm not using `reflectToAttribute`, as I'm trying to pass references to the same objects around, therefore I didn't know there was any de/serialization involved in the binding process.

Basically: If you bind to x.foo and if x is a property of the current component, everything works. But if you bind to x.foo and if x is an instance of another component (That you grab using `this.$.x`), then it only gets notified once.

What is the correct way to bind to properties of components once you hold a reference to the component?

**Comment by hickscorp** [comment]
More or less solved by using a completely static approach to bindings.
