### ISSUE TITLE
data binding to "is" attribute not working

### ISSUE THREAD

**Issue by rhasson** [Polymer/polymer#3122]
I'm trying to dynamically via dom-repeat display a number of custom elements.  I have a data array similar to the one below called "names" where the el_name property contains the name of the custom element to display.

```javascript
names = [ {el_name: 'tmpl-one'}, {el_name: 'tmpl-two'} ]
```
When I try to dynamically assign this variable to the "is" attribute it does not properly load the custom element but instead gives me an empty div.
```html
<template is="dom-repeat" items="{{names}}">
    <div is="{{item.el_name}}"></div>
</template>
```
I also tried this which didn't work
```html
<div is$="{{item.el_name}}"></div>
```
When I statically type in the name of the template it loads the custom element fine.
```html
<template is="dom-repeat" items="{{names}}">
    <div is="tmpl-one"></div>
</template>
```
tmpl-one.html - 

```html
<dom-module id="tmpl-one">
<template>
  <paper-icon-item>...</paper-icon-item>
</template>
<script>
Polymer({
    is: 'tmpl-one',
    extends: 'div'
})
</script>
</dom-module>

**Comment by MeTaNoV** [comment]
`names` should have a `JSON` format try this out:
```json
names = '[ {"el_name": "tmpl-one"}, {"el_name": "tmpl-two"} ]'
```

**Comment by zoechi** [comment]
I assume this is not supported

http://w3c.github.io/webcomponents/spec/custom/#instantiating-custom-elements

> After a custom element is instantiated, changing the value of the is attribute must not affect this element's custom element type.

**Comment by rhasson** [comment]
@MeTaNoV that didn't work either.

@zoechi I guess that could be the problem.  Do you know of a way to insert a custom element via dom-repeat instead of via javascript?

**Comment by zoechi** [comment]
@rhasson 
I'm using Polymer from Dart. I build an element for that ;-)
https://github.com/bwu-dart/bwu_bind_html/blob/master/lib/bwu_bind_html.dart
Shouldn't be to hard to port it to JS (such an element probably already exists for JS)
This way you can add an HTML string in dom-repeat.

**Comment by rhasson** [comment]
@zoechi after some experimentation I believe your approach is the best
option.

Thanks
Roy

**Comment by ebidel** [comment]
That's right. Changing `is` after the fact is not supported by the spec.
