### ISSUE TITLE
Question: this.set not working correctly on IE 10 

### ISSUE THREAD

**Issue by PhilKearney** [Polymer/polymer#3124]
Hi there,

I have a function that updates an object. For example it could be.

this.set("myObj.prop","123");

The binding works fine in Chrome and Firefox but not in IE.

I even tried doing this 

this.set("myObj.prop","123");
this.notifyPath("myObj",this.myObj);

this doesn't work either. The only way I have got it to work with IE is to do the following.
myObj.prop = "123";
this.notifyPath("myObj",this.myObj);

Is there no way to get This.set to work on IE?

Thanks.

**Comment by kevinpschaaf** [comment]
Can you clone [this jsBin](http://jsbin.com/jitome/1/edit?html,output) and try and make a reproduction that shows how it fails?

**Comment by PhilKearney** [comment]
Never mind, It is working correctly now. I was doing something silly. Thanks for your comments.
