### ISSUE TITLE
When element is detached and reattached, its dom-ifs are torn down and restamped

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer#3125]
This invalidates references to the dom inside the dom-if.

e.g. http://jsbin.com/vicowoxohi/1/edit?html,console,output -- the timer changes updates on restamp

**Comment by kevinpschaaf** [comment]
Will be fixed PR in https://github.com/Polymer/polymer/pull/3160.

JSBin repro using PR branch: http://jsbin.com/fuyuka/edit?html,console,output
