### ISSUE TITLE
Polybuild breaks @apply rules

### ISSUE THREAD

**Issue by vaadin-marcus** [Polymer/polymer#3126]
After running the dist target with PSK, it seems that any @apply mixins get broken. polymer#1.2.3

Below is an example: 

Running with `gulp serve`
<img width="439" alt="apply-normal" src="https://cloud.githubusercontent.com/assets/883698/11547037/dac80130-9905-11e5-90e0-83aa5f70179b.png">

Running with `gulp serve:dist`
<img width="393" alt="apply-polybuild" src="https://cloud.githubusercontent.com/assets/883698/11547039/dcc5a500-9905-11e5-9e71-e7289d57ad1f.png">

**Comment by ebidel** [comment]
This issue was moved to PolymerLabs/polybuild#22
