### ISSUE TITLE
Observing an Object which key contains a "dot".

### ISSUE THREAD

**Issue by hickscorp** [Polymer/polymer#3127]
Let's say a property is declared as follows:

```
myProp: {
  type: Object,
  value: function() {
    'foo.baz': "hello",
    'foo': {
      'bar': 'world';
    }
  }
}
```

Then its a no brainer to observe `myProp.foo.bar`... But how about `myProp['foo.baz']`?
Sometimes, especially when using a property to store an object as a handy dictionary for indexing data, the keypaths come from an outside API... with dots. An escape character could be nice to use, eg: observing `myProp.foo\.baz` would be the equivalent of observing what's in `myProp['foo.baz']`.

**Comment by tomalec** [comment]
As mentioned at https://github.com/Polymer/polymer/issues/2007#issuecomment-130490390 same goes with `#` in Object key.

**Comment by hickscorp** [comment]
@tomalec Ok :)

**Comment by andybons** [comment]
Since there are two methods of passing arguments to these methods (a string or array), can the array method be the way that keys with dots in them are passed?

**Comment by tomalec** [comment]
This is also a reason to use [JSON Pointer [RFC 6901]](https://tools.ietf.org/html/rfc6901) standard, as mentioned in https://github.com/Polymer/polymer/issues/2446

- it's well defined,
- it makes it more inter-operable with other systems,
- it has escaping rules,
- it supports any key JSON supports,

**Comment by davidmaxwaterman** [comment]
Also a problem in Polymer 2.x.
I hit this, and decided to try @andybons suggestion of passing using an array. Unfortunately, line 240 of path,html does this:

https://github.com/Polymer/polymer/blob/master/lib/utils/path.html#L240
```
      let parts = this.split(path);
```

irrespective of if path is a string or an array. So, it changes `["prop", "password.txt"]` into `["prop", "password", "txt"]`.

I'm not sure what the logic is there, but it's not what I would have expected. Looks like a code smell to me...

**Comment by davidmaxwaterman** [comment]
I made a simple change:

```
240       let parts = (path instanceof Array?path:this.split(path);
```

and it works as expected.

**Comment by davidmaxwaterman** [comment]
Is there no prospect of this being fixed? ...it's been a while now and I've just hit it again :/
