### ISSUE TITLE
iron-flex-layout and Deprecating /deep/

### ISSUE THREAD

**Issue by MaciejHanajczyk** [Polymer/polymer#3129]
Hi,
I'm deeply concerned about latest post on Polymer Blog: Deprecating /deep/
https://blog.polymer-project.org/announcements/2015/12/01/deprecating-deep/ …

Does it mean that we will lose this fantastic ability to use pre-defined layout classes for any DOM element?

```
<html>
<head>
  <link rel="import" href="iron-flex-layout/iron-flex-layout.html">
</head>

<body>
  <div class="flex-horizontal">
    <div>one</div>
    <div class="flexchild">two (flex)</div>
    <div>three</div>
  </div>
</body>
</html>
```

Will the above code still render properly with flexbox layout?

**Comment by abdonrd** [comment]
Yes, buy now you can use the mixins. :)

**Comment by MaciejHanajczyk** [comment]
That's great,
but I my concern regarded future versions of Polymer.

The ability to use pre-defined layout classes for any DOM element is brilliant.
It fits perfectly to Polymer style of creating web apps and it's really great for anyone learning FlexBox layout.

**Comment by timeu** [comment]
You can continue to use the layout classes but you need to import the layout classes in every element you want to use them (because /deep/ is deprecated)

**Comment by MaciejHanajczyk** [comment]
Thanks,
now it makes sense.
