### ISSUE TITLE
I don't like the `html import`!

### ISSUE THREAD

**Issue by yutingzhao1991** [Polymer/polymer#3130]
I want to manage polymer component with npm and webpack.

Although  said polymer use the HTML import to deal with dependence is to emulate the webcomponents standard, but I think it actually hinder the development of polymer. The official standard is not necessarily the standard of people's recognition, web's modular standard is still based on npm. Webpack is good, Polymer is expected to officially support a NPM and webpack can be used to regulate the components, so that to promote the ecological construction of polymer components. See how many of the components of the react-xxx are now.

**Comment by ebidel** [comment]
I think you mean Bower? HTML Imports have nothing to do with npm. The former provides a client-side loading solution for web components, the latter provides package management. As of now, Imports are the way to load components and do dep management.

There's discussion [here](https://github.com/Polymer/polymer/issues/2578) on switching to npm.
