### ISSUE TITLE
Expose `inst.observe`

### ISSUE THREAD

**Issue by hickscorp** [Polymer/polymer#3150]
When creating complex components, it is sometimes a requirement to establish dynamic observers (At run time). Polymer currently exposes the `.listen()` method (Which I think is undocumented?), but there is nothing about observers.

The big issue with the `.listen()` method is that you cannot do it with a keypath on an Object (Eg on a property `foo.bar`, you have to listen directly to `foo-changed` and then check the path in your callback).

What would be interesting and restoring a little bit of the meta programming javascript flavor in Polymer while waiting for the `.bind()` method to be back would be to expose an `.observe()` method supporting keypath, and complex arguments. Eg:

```
this.observe('_myPropChanged(myProp.foo.bar)');
// Or like the original static `observers: []` syntax allows:
this.observe('_myPropChanged(myProp.foo.bar.*, anotherProp.splices)');
// Or even getting some fancy-fancy things done:
this.observe('_'+methodName+'(myProp.'+path+')');
```

**Comment by azakus** [comment]
`this.listen(node, eventName, methodName)` is just a wrapper for event handlers.
It is roughly equivalent to `node.addEventListener(eventName, this[methodName].bind(this))`

It is a public method and documented: https://github.com/Polymer/polymer/blob/master/src/standard/events.html#L76-L97

Is what you want basically a way to add observers at runtime in addition to the `observers` array that is used at construction time? https://www.polymer-project.org/1.0/docs/devguide/properties.html#observing-path-changes

**Comment by devinivy** [comment]
I agree that this would be nice.  Mostly applicable to specific array elements, array splices, and deep properties.  Otherwise the `-changed` events seem sufficient.

**Comment by TimvdLippe** [comment]
Polymer 2 has [`createMethodObserver`](https://www.polymer-project.org/2.0/docs/api/elements/Polymer.Element#method-createMethodObserver) which implements this behavior :tada:
