### ISSUE TITLE
tap fires on slide 

### ISSUE THREAD

**Issue by frostius** [Polymer/polymer#3154]
I'm confused by tap - either its broken, useless, or I don't get it.  It fires even if the touchstart and touchend fire on different elements.  Click only fires when start/end elements are the same (cause that'd be crazy otherwise, right?)  Modern (the two I'm testing on) browsers generate a click for touch events.  Is this a polyfill?  If so, it's not working the same.  If not, what is the intent?

I've simply reverted to using click and behavior is as desired - at least on the browsers I'm using.  They generate click for touch events but only when start/end elements are the same.

**Comment by azakus** [comment]
I'm not sure I follow. There is no "slide" event, maybe you meant "track"? Track should be preventing tap events from being generated, so an example would be very helpful.

As for the nature of tap, it is a click-esque event that works around the click delay of certain mobile browsers, while having a consistent targeting behavior (synthesized click events on touchscreens will target the most "clickable" element in a certain region, which may not be the element you wanted).

**Comment by mfrost66** [comment]
By "slide" I mean a touchstart, touchmove, touchend sequence

**Comment by azakus** [comment]
Hmm, `tap` will not fire if you move more than `25px` from the start position (based on clientX and clientY). If you use the `track` event, that distance shrinks to `4px`.

The track event combines touchstart, touchmove, touchend, and mousedown, mousemove, mouseup flows into the same event type.

**Comment by mfrost66** [comment]
That's not what I was seeing.  I was getting tap events when
touchstart/touchend where on different elements and definitely more than
25px distance using the latest chrome on android & a window touch laptop.

I solved by not using tap so I no longer have a dependency on it - should
be simple to recreate if you don't already have a unit test
