### ISSUE TITLE
Text node children with bindings cause dom-if templates to update incorrectly.

### ISSUE THREAD

**Issue by bicknellr** [Polymer/polymer#3157]
(Relaying a bug @kevinpschaaf reduced offline.) If a text node containing bindings is a child of a dom-if template, text updates don't always work as expected.

[JSBin](http://jsbin.com/xipetopesa/1/edit?html,output)

1. Type into field.
2. Check the checkbox; the text shown is correct.
3. Uncheck the checkbox.
4. Type into field.
5. Text incorrectly appears in dom-if even though the checkbox is not checked. (Text would be correct if visible.)
6. Click checkbox to show text; text is shown with previous value (as entered in step 1).

(The binding within the span works as expected throughout.)

**Comment by kevinpschaaf** [comment]
Will be fixed by PR https://github.com/Polymer/polymer/pull/3161.

JSBin repro using PR branch: http://jsbin.com/moguna/edit?html,output
