### ISSUE TITLE
css custom properties not penetrating into content

### ISSUE THREAD

**Issue by mfrost66** [Polymer/polymer#3158]
From polymer style [documentation](https://www.polymer-project.org/1.0/docs/devguide/styling.html#xscope-styling-details)

> > > These custom properties can be defined similarly to other standard CSS properties and **will inherit from the point of definition down the composed DOM tree**, similar to the effect of color and font-family

In the example below, "inner content" should be colored red.

test.html

``` html
<!DOCTYPE html>
<html>
<head>
  <script charset="utf-8" src="bower_components/webcomponentsjs/webcomponents.js"></script>
  <link rel="import" href="bower_components/polymer/polymer.html">
  <link rel="import" href="my-modules.html">
</head>
<body>
<my-paragraph>
  <my-text>inner content</my-text>
</my-paragraph>
</body>
<script>
</script>
</html>
```

my-modules.html

``` html
<dom-module id="my-text">
  <style>
    :host {
      display: block;
      color:var(--my-text-color,blue);
    }
  </style>
  <template><content></content></template>
  <script> Polymer({ is:'my-text'}) </script>
</dom-module>
<dom-module id="my-paragraph">
  <style>
    :host { --my-text-color:red; }
    :host ::content * { --my-text-color:red; } /*tried this too*/
  </style>
  <template>
    <my-text>Outer content</my-text>
    <content></content>
  </template>
  <script> Polymer({ is:'my-paragraph'}) </script>
</dom-module>
```

**Comment by nazar-pc** [comment]
You are correct, custom properties do penetrate into depth, but not styles themselves.
Which means that `color:var(--my-text-color,blue);` does work, it just doesn't affect plain contents.
You can confirm it by changing your element as following:
```html
<dom-module id="my-text">
  <style>
    :host {
      display: block;
      color:var(--my-text-color,blue);
    }
  </style>
  <template>host's content</template>
  <script> Polymer({ is:'my-text'}) </script>
</dom-module>
```

**Comment by mfrost66** [comment]
```html
<dom-module id="my-paragraph">
  <style>
    :host { --my-text-color:red; }
```
should change the value of --my-text-color to 'red' for the <my-paragraph> sub-tree.  

In steps:
1. ```<my-paragraph>``` changes ```--my-text-color``` to 'red' for it's sub-tree
2. ```<my-text>``` element gets inserted into ```<my-paragraph>``` as content
3. ```<my-paragraph><my-text>``` style ```color:var(--my-text-color,blue)``` should use the value of 'red' for --my-text-color

**Comment by nazar-pc** [comment]
Correct, but your text is not in `:host`, it is in `:host ::content`

**Comment by mfrost66** [comment]
Again, per the documentation: "point of definition down the composed DOM tree" which should include content. If it doesn't, it should be called out - but it would seem almost useless to have theming that doesn't apply to content

That said, you'll note I tried both variations in the example, just in case. 

```html
<style>
    :host { --my-text-color:red; }
    :host ::content * { --my-text-color:red; } /*tried this too*/
  </style>
```

**Comment by nazar-pc** [comment]
Try just `:host ::content`, without star. Also jsbin would help to make sure we are all on the same page.
Also, clarify please about browser you're using (I assume Chrome/Chromium).

**Comment by mfrost66** [comment]
I didn't do a jsbin as I don't have an easy reference to your custom build.

Here is a [plunker](http://plnkr.co/edit/CNnFplJoVTjKfESZ5xoi?p=preview)
that uses the latest build on rawgit

**Comment by nazar-pc** [comment]
I've played with it, and it seems like a bug

**Comment by Xaviju** [comment]
Same problem here, expected my custom properties to go into the ```::content```.

**Comment by Xaviju** [comment]
According to documentation: https://www.polymer-project.org/1.0/docs/devguide/styling.html#xscope-styling

>One solution the Shadow DOM spec authors provided to address the theming problem are the /deep/ and ::shadow combinators, which allow writing rules that pierce through the Shadow DOM encapsulation boundary. Although Polymer 0.5 promoted this mechanism for theming, it was ultimately unsatisfying for several reasons:
>Using /deep/ and ::shadow leads to verbose and difficult to understand selectors.
>**For the reasons above, the Polymer team is currently exploring other options for theming that address the shortcomings above and provide a possible path to obsolescence of /deep/ and ::shadow altogether.**

But seems that there is no alternative so far for theming other than sharing a style file across all components (not tested yet).

**Comment by carolirod** [comment]
please hear us!
+1 to solve this one
maybe @sorvell knows something about it? 

Thanks!!

**Comment by oscarmarina** [comment]
It may be related to this issue: #1787

**Comment by azakus** [comment]
This requires recursing through distribution points to collect styles, which is a performance concern. We may look at this for the next major version of Polymer.

**Comment by mfrost66** [comment]
A reasonable point of view - 18 months ago before you documented, released
and pronounced polymer v1.0 as "production ready".  There should be a
warning somewhere on the main project page to prevent others from
attempting to use this half-baked bug-ridden project

**Comment by TimvdLippe** [comment]
This appears to be working correctly in both Chrome (native Shadow DOM) and Firefox (shadyDom): http://jsbin.com/bebocoyiqe/edit?html,output Therefore I am closing this issue as it was probably fixed along the way in Polymer 2 or the v1 polyfills.
