### ISSUE TITLE
Dom-repeat not working in IE 11/Edge

### ISSUE THREAD

**Issue by pvseshu** [Polymer/polymer#3159]
I am trying to implement dom-repeat in polymer 1.0, it is working as expected in chrome. But the same code is not working in IE 11. Any work around for the issue. 

![untitled](https://cloud.githubusercontent.com/assets/3065055/11602700/84f3c704-9a99-11e5-9048-3f993cb1088e.png)

**Comment by BLamy** [comment]
Do you have the web-components polyfills imported on the page using this?

**Comment by pvseshu** [comment]
Yes i have used <script src="../bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>

**Comment by whathelll** [comment]
we found that it was because on IE the polyfills takes some time to load, so if we had assigned the array object before elements are upgraded the setters don't get called, which means nothing works. 

What we found works was in the property definition have it return an empty array on default
            properties: {
                data: {
                    type: Array,
                    notify: true,
                    value: function() {
                        return [];
                    }
                },
            },


in the html
var el = document.getElementById('blah-blah');
    if(el.data) {
        el.data = lobData;
    } else {
        //FOR IE and other browsers which require polyfill
        window.addEventListener('WebComponentsReady', function(e) {
          el.data = lobData;
        });
    }

**Comment by pvseshu** [comment]
I have tested that scenario also, but didn’t worked. I have tested in other way as well, after 1 or 2 mins of page load, I have tried to pass data explicitly by calling function but that also didn’t worked. Can you please let me know if you have any other work around.

**Comment by azakus** [comment]
Is this file the main page? If so, wrap the call to Polymer in `addEventListener('WebComponentsReady, function() { Polymer(...) })`.

HTML Imports polyfill can't block scripts from executing before imports are loaded like the native implementation can in Chrome.

**Comment by azakus** [comment]
This issue has no reproducible steps. Please comment on this issue if it still occurs, with a JSBin containing a set of reproducible steps. See [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs) for details.
