### ISSUE TITLE
Fix min CSS branch fails on Safari

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/polymer#3166]
#2689 introduced fixes for parsing of minimized CSS. However, after merging, the tests failed on Safari. I am not able to run the tests on Safari because it can't be installed on Linux. Therefore the following steps might be needed to investigate the issue:

The changes of the PR are available in [this branch](https://github.com/Polymer/polymer/tree/JeremybellEU-fix-min-css).

There are two possible problems:
1. The regex does not match on Safari due to a different regex engine.  This can be tested by entering the following in the console:
```js
"top: 12px;--variable-from-other-variable: var(--variable-into-first-variable);--variable-from-another-variable: var(--variable-into-second-variable); --variable-from-last-variable: var(--variable-into-third-variable);".match(/(?:^[^;\-\s}]+)?--[^;{]*?:[^{};]*?(?:[;\n]|$)/gim)
```
If the output is false, then the regex does not work on Safari. Else the output should be:
```js
["--variable-from-other-variable: var(--variable-into-first-variable);", "--variable-from-another-variable: var(--variable-into-second-variable);", "--variable-from-last-variable: var(--variable-into-third-variable);"]
```
2. Secondly, it could be a styling issue on Safari. To test this, run `polyserve` and open `http://localhost:8080/components/polymer/test/unit/custom-style.html`. Verify that `child-of-child-with-var` textContent has:
```css
bottom: 9px;
left: 10px;
right: 11px;
```
If this is not the case, styling of Safari is different than the other browsers and a possible fix is to change the CSS-properties defined at https://github.com/Polymer/polymer/pull/2689/files#diff-5ccfdb2810bc155fcc15b5a27ae88be4R273 to other properties like `border-bottom-width`.

**Comment by JeremybellEU** [comment]
@JWGmeligMeyling tested the regex and confirmed it worked. So the failing test is probably related to the `bottom` css attribute.

**Comment by rubenstolk** [comment]
As far as I can see, the element in the test suite is given `bottom`, `left` and `right` properties, however the element doesn't have any value for `position` (default `static`). The difference between Chrome and Safari for `window.getComputedStyle(document.querySelector('child-of-child-with-var')).bottom` is:

- Safari: `"auto"`
- Chrome: `"9px"`

Submitted a PR: https://github.com/Polymer/polymer/pull/3240

**Comment by TimvdLippe** [comment]
Landed in #3241, woohoo! Thanks a ton @rubenstolk

**Comment by rubenstolk** [comment]
:+1:

**Comment by samccone** [comment]
:clap: @rubenstolk :bouquet:
