### ISSUE TITLE
Behaviors and types

### ISSUE THREAD

**Issue by David-Mulder** [Polymer/polymer#3167]
So, if we have a behavior that sets

```
  value: {
    notify: true,
    type: String
  },
```

and an element that sets

```
  value: {
    notify: true,
    type: Object
  },
```

then for some reason it will fail to parse an attribute such as `value='{"red":255,"green":155,"blue":55}'`. If we inspect the `properties` property it will correctly show `type: Object()`, however inspecting the `value` property will show `'{"red":255,"green":155,"blue":55}'`. No idea what's causing this, but makes behaviors like `iron-form-element-behavior` entirely unusable in all but the simplest of situations.

**Comment by TimvdLippe** [comment]
This has been fixed in Polymer 2: http://jsbin.com/zewihimiki/edit?html,console,output
