### ISSUE TITLE
getPropertyInfo returns first behavior-defined property, not last

### ISSUE THREAD

**Issue by mgiuffrida** [Polymer/polymer#3168]
In an element with multiple behaviors, the **latest** behavior that defines a property determines that property.

Calling getPropertyInfo(property) on that element will return the property info from the **first** behavior that defined the property, which seems inconsistent.

[Example jsfiddle](http://jsfiddle.net/4L58c4e0/)

```
var BehaviorA = {
  properties: {
    c: {
      type: String,
      value: 'BehaviorA.c'
    }
  }
};
var BehaviorB = {
  properties: {
    c: {
      type: String,
      value: 'BehaviorB.c'
    }
  }
};
Polymer({
  is: 'x-blah',
  behaviors: [BehaviorA, BehaviorB],
  ready: function() {
    this.info = JSON.stringify(this.getPropertyInfo('c'));  // {value: 'BehaviorA.c'}
  }
});
```

**Comment by TimvdLippe** [comment]
Closing this issue as this API has been deprecated, among other reasons because of issues like this one.
