### ISSUE TITLE
how to dynamically append an element to dom-if?

### ISSUE THREAD

**Issue by Qvatra** [Polymer/polymer#3169]
My goal is to append an element to existing dom-if dynamically. Problem is that after appending I can see appended element in the DOM three but it never reacts on condition and stays always hidden.

```
<template>
    <template id="domif" is="dom-if" if="[[condition]]" restamp></template>
</template>

ready() {
    var el = document.createElement("input");
    Polymer.dom(this.$.domif).appendChild(el);
    Polymer.dom.flush();
}
```

Exploring DOM with hardcoded dom-if and input shows that <input /> element is actually not a child of dom-if but lives next to it..

```
<template>
    <template is="dom-if" if="[[condition]]" restamp>
       <input />
    </template>
</template>
```

That gave me a clue that I probably should append my element next to dom-if... But now the biggest question is how to say to dom-if that appended element should be rendered if condition is satisfied. Any ideas?

stackOverflow: http://stackoverflow.com/questions/34137859/how-to-dynamically-append-an-element-to-dom-if-in-polymer

**Comment by ebidel** [comment]
Let's keep questions to SO.
