### ISSUE TITLE
Way to trigger rerender of element-template

### ISSUE THREAD

**Issue by flash1293** [Polymer/polymer#3173]
Is there a way to explicitly trigger rerendering of the template of an element?

My problem is there is no way convincing the polymer-template the underlying data has changed without setting the path to a new reference:

``` js
var data = ['one', 'two'];
this.set("data", data); //one and two appear in the template
//...
data.push('three');
this.set("data", data); //nothing happens because polymer thinks it already knows the object
```

Here is a fiddle illustrating the problem
https://jsfiddle.net/cb5tL3md/1/

I am aware of stuff like `this.push`, but, at least in my case, the code mutating the data is not part of the component itself and is not aware of polymer.

**Comment by chigur** [comment]
You can use the method [`notifySplices`](https://github.com/Polymer/polymer/blob/4d45842a40064d509ec97ac897c2f4fb8782ffdc/src/standard/notify-path.html#L408).

**Comment by flash1293** [comment]
I am searching for a generic way, data could also be a complex object.

**Comment by chigur** [comment]
Are you looking for some API in Polyner which can diff the object, find out what parts have changed and update the template accordingly?, because I am looking for the exact same thing.

**Comment by flash1293** [comment]
I do :) its pretty surprising there is no way to do this - the only workaround I know of is creating a shallow clone of the object before assigning it using `this.set`

**Comment by chigur** [comment]
In my case I've handled `notifyPath` and `notifySplices` myself for the fear that cloning might introduce a significant performance overhead. I don't know if it is strictly relevant but [this](https://github.com/Polymer/polymer/issues/2752) issue may throw some more light on the current problem.

**Comment by flowlo** [comment]
Looking for the same thing. I have a `function Tree` that represents a data structure that I modify with `tree.add(...)`. Calling `this.notifyPath` didn't help, so I ended up cloning my datastructure. Now observers are called, but Polymer does not re-render elements in the template.

**Comment by TimvdLippe** [comment]
This is now possible in Polymer 2 with the `MutableData` mixin: http://jsbin.com/witodegani/1/edit?html,console,output This is documented at https://www.polymer-project.org/2.0/docs/devguide/model-data#array-mutation

> Use the MutableData mixin. For elements that include the Polymer.MutableData mixin, calling set or notifyPath on an object or array causes Polymer to re-evaluate the entire object graph starting at that object or array, even if the object or array itself hasn't changed. For details, see Using the MutableData mixin.
