### ISSUE TITLE
prepareModelNotifyPath shows up in API docs

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#3175]
`prepareModelNotifyPath` shows up in the API docs, with only the single line here as its description:

https://github.com/Polymer/polymer/blob/4d45842a40064d509ec97ac897c2f4fb8782ffdc/src/standard/notify-path.html#L604

Looks like this should be a private method.

Also looks like if you use // comments, hydrolysis only picks up the last line. Does that sound right, @garlicnation?

**Comment by TimvdLippe** [comment]
Closing this as only concerning Polymer 1. This should no longer happen with Polymer 2.
