### ISSUE TITLE
Add convenience method for local DOM querySelectorAll, much like $$ for local DOM querySelector

### ISSUE THREAD

**Issue by joineral32-cengage** [Polymer/polymer#3183]
Polymer has a utility method $$ that provides a shorthand for querying individual elements on an element's local dom. This is very helpful and my colleagues and myself enjoy using this utility method. So much so, in fact, that we would like something similar for querySelectorAll against the local DOM.

I have opened up a pull request that adds a $$$ utility method which performs querySelectorAll against an element's local DOM, in a very similar fashion to $$: https://github.com/Polymer/polymer/pull/3186

**Comment by dsschnau** [comment]
+1, just had the same idea. beats having to write `Polymer.dom(this.root).querySelectorAll(...)`

**Comment by jimsimon-cengage** [comment]
+1

**Comment by mkimitch** [comment]
+1

**Comment by TimvdLippe** [comment]
`$$` has been removed, as the native API is a lot more intuitive: `this.shadowRoot.querySelector` Moreover, all other native DOM APIs are available on `this.shadowRoot`, including `querySelectorAll`. For more information on the discussion, see #3186. Therefore, I am closing this issue.
