### ISSUE TITLE
querySelector queries for more than just first match

### ISSUE THREAD

**Issue by joineral32** [Polymer/polymer#3185]
querySelector currently delegates to querySelectorAll, and then returns the first match found by querySelectorAll. I was wondering if there was a particular reason for this.

If there isn't, and it is better to stop querying once a match is found, I have created a pull request for doing exactly that: https://github.com/Polymer/polymer/pull/3184

**Comment by TimvdLippe** [comment]
Closing per https://github.com/Polymer/polymer/pull/3184#issuecomment-179550238
