### ISSUE TITLE
Feature Request: Support !! in bindings

### ISSUE THREAD

**Issue by opus1269** [Polymer/polymer#3188]
This makes for a slick way to bind to boolean attributes with non-boolean properties that can be truthy or falsey

For instance, a possible use case from iron-image

```js
       /**
         * Sets a sizing option for the image.  Valid values are `contain` (full
         * aspect ratio of the image is contained within the element and
         * letterboxed) or `cover` (image is cropped in order to fully cover the
         * bounds of the element), or `null` (default: image takes natural size).
         */
        sizing: {
          type: String,
          value: null
        },
```
...

```html
    <div id="backdrop" hidden$="[[!sizing]]"></div>
    <img id="img" role="none" hidden$="[[!!sizing]]">
```

Otherwise, you need to put it in a computed binding.

ht to @bicknellr for the idea.

**Comment by Jamtis** [comment]
Can you please provide a use-case where the `hidden` tag must be `true` instead of the `sizing`value.
When I see 'hiding' I think about CSS selectors that apply some `display`styles, however `div[hidden] {}` would also match `<div hidden$="[[sizing]]">`.

**Comment by JeremybellEU** [comment]
This has been previously requested in #2343 . The official response was:

> We're not very interested in expanding the vocabulary of expressions right now.
You can always make a computed function that applies a boolean pass over the input:

```html
<my-element attr$="[[bool(numeric_prop)]]"></my-element>
```

```js
  bool: function(prop) {
    return !!prop;
  }
```

**Comment by opus1269** [comment]
@JeremybellEU Thanks for the info.
