### ISSUE TITLE
Default values for CSS vars fails

### ISSUE THREAD

**Issue by eloypastor** [Polymer/polymer#3190]
Default values for CSS vars fails when a default value es complex, like a gradient for example.

See this [project](https://github.com/eloypastor/test_styles)

For this style 

`background:  var(--fx-webkit-background, -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(255,0,0,.65)), color-stop(100%,rgba(0,0,255,.65))));`

the style result is

`background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(255,0,0,.65)), color-stop(100%,rgba(0,0,255,.65)))));`

The last two parenthesis will be removed.

**Comment by zoechi** [comment]
probably a dup of #3221

**Comment by azakus** [comment]
Looks like this case is still a problem.

**Comment by azakus** [comment]
The variable matcher regex is at fault here, as it will match up until the comma between color stops. This regex is at peak complexity, so I think we will have to make a small custom state machine to replace it.
