### ISSUE TITLE
Observer functions in dom-repeat are not correctly updated for non set operations

### ISSUE THREAD

**Issue by samccone** [Polymer/polymer#3191]
##### Template: :scroll:

``` html
<template is="dom-repeat" items="[[getFoo(foo.*)]]">
   <p>[[item]]</p>
</template>
```
##### Component: :large_orange_diamond:

``` js
this.push('foo', Math.random());
```

``` js
getFoo: function(f) {
  return f.base.concat(['wow']);
}
```
##### Expected: :cat2:

When I :pushpin: push elements into foo, they should show up in the DOM
##### IRL: :earth_asia:

nothing shows up :cry: 
##### Hack Fix: :computer:

calling :ear: set and reassigning the entire `foo` entity correctly shows things 

---
- :fire: **broken example** - http://jsbin.com/gixedavoti/1/edit?html,output
- :white_check_mark: **working hacked example** - http://jsbin.com/kibutanave/1/edit?html,output

**Comment by MeTaNoV** [comment]
:100: :ice_cream: :sun_with_face:

**Comment by azakus** [comment]
@kevinpschaaf this sounds familiar, can you dedupe?

**Comment by TimvdLippe** [comment]
This is still an issue with Polymer 2: http://jsbin.com/xumuyixege/edit?html,console,output
