### ISSUE TITLE
broken images for cards in paper-elements catalog

### ISSUE THREAD

**Issue by skybrian** [Polymer/polymer#3195]
https://elements.polymer-project.org/browse?package=paper-elements&view=cards

On this page, some Paper elements have meaningful images (like paper-input) and others are random squiggles. (For example, paper-badge, paper-behaviors, and paper-button have the same sqiggle - perhaps a placeholder?) Others like paper-card and paper-item have a different sqiggle, but still not meaningful.

Also, there's a broken image for paper-dropdown-menu.

**Comment by azakus** [comment]
This issue was moved to Polymer/polymer-element-catalog#227
