### ISSUE TITLE
Cloning a div with custom elements inside it is not returning an exact clone

### ISSUE THREAD

**Issue by suneelv** [Polymer/polymer#3197]
http://jsbin.com/zuruqomubo/edit?html,output
​
http://jsbin.com/xiqevugeyi/1/edit?html,output

If the custom element has multiple insertion points, cloning is not working properly

**Comment by azakus** [comment]
Can you describe what you expect to happen? Your examples are not clear.

**Comment by suneelv** [comment]
markup of the cloned elements is not the same as the markup of the original element. 
In the first example, "First Para" and "last paragrah" divs are added twice.

In the second example, when I have cloneNode method inside the custom element, which uses polymer's clone method, cloning works correctly. But when the same element is inside a div and if I clone the div, then things repeat

Cloned element should have the same markup as the original element.
This messing up happens when there are insertion points in a template. Something similar happens with some other paper elements too (paper-header-panel)

**Comment by kaste** [comment]
Here is a simplified version http://jsbin.com/lununumadi/1/edit?html,output of what @suneelv means.

@azakus can you look into it again, please? Very irritating right now.

**Comment by kaste** [comment]
Stupid me! You have to use the `Polymer.dom()` wrapper of course. http://jsbin.com/dinopihacu/1/edit?html,output
