### ISSUE TITLE
Support Symbol type attributes

### ISSUE THREAD

**Issue by panuhorsmalahti** [Polymer/polymer#3198]
Documentation doesn't mention if ``Symbol`` is a supported type for an attribute.

**Comment by ebidel** [comment]
Properties can be of any type, but `Symbol` can't be [de]serialized when using an attribute for initialization or during attribute reflection.

From the docs:
> The type system includes support for Boolean and Number values, Object and Array values expressed as JSON, or Date objects expressed as any Date-parsable string representation.

The docs are unclear that properties can be any JS type (including new ES6 features). I'm going to move this over there so we get it documented :)

**Comment by ebidel** [comment]
This issue was moved to Polymer/docs#1469
