### ISSUE TITLE
Document styling with custom-style affects local DOM when using Shady DOM

### ISSUE THREAD

**Issue by brianreeve** [Polymer/polymer#3205]
custom-style tags defining document styling (eg. https://github.com/brianreeve/shady-dom-specificity/blob/master/demo/index.html#L9-L14) affect the local DOM of custom elements when using Shady DOM.

This works fine with native Shadow DOM in Chrome.

However, when using Shady DOM the document styling resolves to style definitions which have higher specificity than the styling in the x-menu element.

I created a quick example illustrating this issue here: https://github.com/brianreeve/shady-dom-specificity

**Comment by azakus** [comment]
Simpler demo: http://jsbin.com/mituyibuzu/edit?html,output
Using `.class ::content div` will not override outside styling.
Using `#container ::content div` will.

**Comment by azakus** [comment]
This is a limitation of the selector transforming for ShadyDOM. You can affect the styles you want by adding specificity to the content selector. One easy way to do this is to use `:not(.random-class)`.

To fix this in Polymer, we need to study if adding specificity this way is sustainable. If we determine that this strategy works, we may add this to the next major version.
