### ISSUE TITLE
dom-repeat does not provide filtered length

### ISSUE THREAD

**Issue by Jamtis** [Polymer/polymer#3207]
Is there a way to bind a property to the number of filtered items?

Something similar to this:
`<template is="dom-repeat" items="{{items}}" filter="{{filterFunction(filter)}}" filtered-length="{{length}}">`
.

**Comment by arthurevans** [comment]
This is avsilable in master (as `renderedItemCount`). See: #3065.

I don't think we've had a release since this was merged.

**Comment by Jamtis** [comment]
Good timing. :laughing:

**Comment by kevinpschaaf** [comment]
Closing as resolved by #3065
