### ISSUE TITLE
Getting started without node etc.

### ISSUE THREAD

**Issue by grokys** [Polymer/polymer#3209]
I have a designer colleague who wants to try out Polymer but the "Getting Started" section dives in pretty deep for him: installing node, bower, gulp and the getting the Polymer Starter Kit etc.

He wants to just download the .zip file and paste some .html to get him started. I imagine this would be common among designers. Should a small tutorial such as this be added to the "Getting Started" section? I can submit a PR if so.

In the meantime, I have created a .jsbin for him, but the roboto font isn't being applied. What am I missing? http://jsbin.com/pofatasoji/1/edit?html,output

**Comment by MeTaNoV** [comment]
Maybe he can check out the PSK light version here: https://github.com/polymerelements/polymer-starter-kit/releases/tag/v1.2.1

**Comment by miztroh** [comment]
@grokys Even if there was a simple zip download of Polymer and all the elements you want to use, your friend would still have to run a web server to use them.  HTML Imports don't work on file:// pages.  He'd could run a node server, or a LAMP stack, or the Chrome Dev Editor which has its own built-in server.

**Comment by tjsavage** [comment]
Moving this to the docs repo for better visibility.

At least for downloading elements without bower, the [Polymer Element Catalog](https://elements.polymer-project.org/) lets you add individual elements to a collection (by clicking the star on each element, either from the list view or on the element documentation page), and then download the entire collection as a zip file. The feature isn't terribly discoverable so we're working on a refresh of the catalog.

**Comment by tjsavage** [comment]
This issue was moved to Polymer/docs#1470

**Comment by jongeho1** [comment]
@grokys the chrome dev editor makes it really easy to assemble some elements with some out of the box templates.

https://chrome.google.com/webstore/detail/chrome-dev-editor-develop/pnoffddplpippgcfjdhbmhkofpnaalpg

Thanks

Jon

**Comment by grokys** [comment]
Thanks @jongeho1 that's got him started! Might be worth linking to that tool somewhere...
