### ISSUE TITLE
Inconsistencies observing specific array elements

### ISSUE THREAD

**Issue by devinivy** [Polymer/polymer#3211]
When I observe a specific array element, it may or may not be notified properly depending on how the element is changed.  This _seems_ to be an issue in 1.2 but not prior to that, though I'm not entirely positive.  Previous to 1.2 I would (referring to the example) observe `arrayProperty.0` rather than `arrayProperty.#0`.

Additionally, I've become very fuzzy on when `#n` element observers need to be used.  I can only get this working with `#n` array element observers, so I'll give an example using that, but any info on this topic would also be very useful.

Ex.

``` js
Polymer({

 /* ... */

  observe: [
    '_watchIt(arrayProperty.#0)'
  ],

  // _watchIt is notified
  ready: function() {
    this.arrayProperty = ['init'];
  },

  // _watchIt is notified
  mutateWithSet: function() {
    this.set('arrayProperty.#0', 'changed with set');
  },

  // _watchIt is not notified
  mutateWithSplice: function() {
    this.splice('arrayProperty', 0, 1, 'changed with splice');
  }

});
```

**Comment by TimvdLippe** [comment]
This is still an issue in 2.x: http://jsbin.com/mucacepibe/edit?html,console,output
