### ISSUE TITLE
Missing Polymer.dom()._query

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#3214]
After commit 306cc8130e4cab12d6e05eec6097e1ad85220c50 from #3112 Shadow DOM support is broken.
Calling `Polymer.updateStyles()` results in:
> TypeError: Polymer.dom(...)._query is not a function at HTMLElement.Polymer.Base._addFeature._updateRootStyles (...) at Function.Polymer.updateStyles (...) at HTMLDocument.ready_callback (...) at ...

Namely, Shadow DOM version of `Polymer.dom(...)` does not have `_query()` method used here: https://github.com/Polymer/polymer/blob/e3753dbaeb84e415311f478eea4dbc7c733bad6c/src/standard/x-styling.html#L262

This should be fixed before next release.
@sorvell @kevinpschaaf

**Comment by nazar-pc** [comment]
Fixed in #3215

**Comment by devinivy** [comment]
Is there a simple test to be written to catch future regressions?

**Comment by nazar-pc** [comment]
Yes, you're pointing to right location. I decided to reuse existing tests.
