### ISSUE TITLE
Dynamically added components w/behavior data binding issue

### ISSUE THREAD

**Issue by BootsSiR** [Polymer/polymer#3218]
I am experiencing an 'issue' that may be normal behaviour but I'm going to try and explain it below.  Take a project with a behavior and three components.  The behavior has a property defined and each dynamic element has a property defined.

    test-behavior
        property: behaviorProperty
    main-element
    dynamic-element-one (inherits test-behavior)
        property: localProperty
    dynamic-element-two (inherits test-behavior)
        property: localProperty

from within main-element if I dynamically add both components via:

    var component1 = document.createElement('dynamic-element-one');
    Polymer.dom(this.$.componentContainer).appendChild(component1);

    var component2 = document.createElement('dynamic-element-two');
    Polymer.dom(this.$.componentContainer).appendChild(component2);

If either of the dynamic elements databind and modify the behaviorProperty it seems to modify it for both dynamic elements.  If either of the dynamic elements databind and modify their localProperty, they stay independent.  

How can I add these components dynamically and avoid this 'crossing of wires' ?  I hope this was enough information to describe what I'm seeing.  I'm not ruling out the possibility of me doing something wrong.  This is my first Polymer project :)

**Comment by miztroh** [comment]
My guess is that your behavior is not setting up an array or object property correctly.

Instead of this:
```
properties: {
   foo: {
      type: Object,
      value: {bar: 1}
   },
   bar: {
      type: Array,
      value: ['foo']
   }
}
```

You should do this:
```
properties: {
   foo: {
      type: Object,
      value: function () {
         return {bar: 1};
      }
   },
   bar: {
      type: Array,
      value: function () {
         return ['foo'];
      }
   }
}
```

Otherwise, a single object or array instance is shared between all elements that inherit the shared behavior.

**Comment by BootsSiR** [comment]
Thanks very much.  I'm away from the code ATM but I am doing what you describe and I'm fairly certain this is my issue.  Will close once I confirm.

Steve

**Comment by BootsSiR** [comment]
Confirmed.  Thanks Jonathan.
