### ISSUE TITLE
paper-ripple sets transform every frame instead of using accelerated animation

### ISSUE THREAD

**Issue by danakj** [Polymer/polymer#3219]
Rather than setting a new scale every frame, the effect would achieve better performance across browsers by using an accelerated animation. This would provide the browser with more hints to avoid re-raster on every frame.

The bug occurs in the drawRipple method https://code.google.com/p/chromium/codesearch#chromium/src/third_party/catapult/third_party/polymer/components/paper-ripple/paper-ripple.html&l=190

It can be reproduced by paper-button/demo.html, which is run by telemetry bots as per https://code.google.com/p/chromium/issues/detail?id=563504#c16

See more details here: https://code.google.com/p/chromium/issues/detail?id=563504#c18

**Comment by ebidel** [comment]
This issue was moved to PolymerElements/paper-ripple#67
