### ISSUE TITLE
Cannot query elements of dom-bind template from outside script element

### ISSUE THREAD

**Issue by eximius313** [Polymer/polymer#3220]
As outcome of this [issue](https://github.com/Polymer/polymer/issues/2241) states: 
```
Using a dom-bind element, the script should be placed outside the binding template
```
Unfortunately there are some issues with this approach:
This [JSBin](http://jsbin.com/welugoceti/1/edit?html,console,output) shows what happens when ```script``` tag is inside ```template``` tag - you can query for template's inner elements.
In this [JSBin](http://jsbin.com/tanococifu/1/edit?html,console,output) ```script``` tag is outside ```template``` tag and all variables are nulls.

Which approach is then correct?

**Comment by zoechi** [comment]
If the script is outside the template you need to wait for Polymer to be ready  https://www.polymer-project.org/1.0/docs/migration.html#polymer-ready

**Comment by ebidel** [comment]
There's also the `dom-change` event for dom-bind'ing templates:
https://www.polymer-project.org/1.0/docs/devguide/templates.html#dom-change
