### ISSUE TITLE
Defining CSS variables with a `var([...])` value

### ISSUE THREAD

**Issue by David-Mulder** [Polymer/polymer#3223]
Updating post for the sake of clarity: Issue was obfuscated by a (stupid) 'typo' which was correctly noticed by Ebidel. Issue that's left (which was from the beginning the core issue) is that

    --my-var: var(--another-var);

isn't working (nor any variations as can be seen below). This can be for example useful if you have multiple defaults (e.g. a generic custom property for all checkboxes and a specific custom property for the checkbox in the header)

---

Old post, please ignore: 

> Sorry for the harsh and somewhat undescriptive title, but compare:

> - [This JSBin made using Polymer](http://jsbin.com/peboqecono/1/edit?html,output)
> - [To this plain CSS in Firefox or Chrome Canary](https://jsfiddle.net/7fz12wze/3/)

> Maybe it's all the same bug that's triggering the entire issue - though if so I have no idea what the linking factor is what gave rise to the mentioned generic title - , but the linked JSBin contains 6 examples which all work in Chrome Canary and Firefox, but not in the Polymer polyfill. And if you wonder why those kind of constructions would be valuable: Sometimes you need more than one default.

**Comment by David-Mulder** [comment]
And for that matter, the above JSBin uses the official syntax, but it's not working with `var(--first-var, --second-var)` either. Reporting that issue separately.

**Comment by zoechi** [comment]
Can you please elaborate a bit what you expect and what you get instead?

**Comment by David-Mulder** [comment]
@zoechi: I expect the same behavior as in Chrome Canary and Firefox as seen in the JSFiddle, I get `yellow`, `yellow`, `black`, `black`, `black`, `black`.

**Comment by ebidel** [comment]
The last isn't white because you have a typo. It's using the class 'five' instead of 'six'. The rest appear to be bugs:

-  Not sure if we support defining a property from a `var`: `--some-variable: var(--some-undefined, --some-default);`
- You should be able to define/redefine properties in selectors. eg, `paper-card.one {...`

**Comment by ebidel** [comment]
@sorvell can you please take a look?

**Comment by David-Mulder** [comment]
@ebidel: Oh wow, even asked over on slack for a sanity check@number six, but nobody noticed... that's embarrassing :angel: Will change the title to reflect it as well.

**Comment by azakus** [comment]
A limitation of the CSS property shim is that variables can only have one value within a given scope, and only variables defined in `:host` or `:root` can be used in that scope. Variables defined in other selectors will only apply in descendant scopes

Here's your example modified to work with the given limitations: http://jsbin.com/xonunij/edit?html,output

In addition, Polymer now has the ability to use native css variables when the flags `lazyRegister` and `useNativeCSSProperties` are set: http://jsbin.com/disolin/edit?html,output
