### ISSUE TITLE
`var()` fallback syntax

### ISSUE THREAD

**Issue by David-Mulder** [Polymer/polymer#3224]
If I am understanding the spec correctly it should be

    some-prop: var(--some-var, var(--some-var));

not

    some-prop: var(--some-var, --some-var);

per

 >     var() = var( <custom-property-name> [, <declaration-value> ]? )

Source: http://www.w3.org/TR/css-variables/#funcdef-var

where the second argument is a `<declaration value>`, not a `<custom-property-name>`.

This is reinforced by the fact that the first syntax isn't working in browser implementations and it makes very little sense when you think about it.

**Comment by zoechi** [comment]
Looks similar to #3221

**Comment by David-Mulder** [comment]
@zoechi: Well, this is about the correctness of the currently used syntax, the other issues are about a bug in the parser. They will probably be fixed at the same time, but are two entirely different issues.

**Comment by azakus** [comment]
Both syntaxes are supported with #3587
