### ISSUE TITLE
Hard to start

### ISSUE THREAD

**Issue by josejmoran** [Polymer/polymer#3228]
Hi guys,

I have tried to use Polymer.  I like it.  But I do find that is not clear how I can start and index.html and try to use iron-elements or paper-elements or any.

It will be great if you create an example indicating what we need to include in an index.html file to make use of Polymer

I do like it a lot, but have a few days trying to use it unsuccessfully.

**Comment by PaulHMason** [comment]
Have a look on the Google Developer's channel on YouTube, particularly Rob Dodson's polycast videos. The Polymer Summit videos are also very useful. https://www.polymer-project.org/summit

**Comment by josejmoran** [comment]
Thanks Paul for the help.

Jose

On Tue, Dec 22, 2015 at 3:28 AM, Paul Mason <notifications@github.com>
wrote:

> Have a look on the Google Developer's channel on YouTube, particularly Rob
> Dodson's polycast videos. The Polymer Summit videos are also very useful.
> https://www.polymer-project.org/summit
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Polymer/polymer/issues/3228#issuecomment-166552271>.
>



-- 
Regards,

Jose J. Moran
336-347-8688

**Comment by ebidel** [comment]
There's a guide here on using elements:
https://elements.polymer-project.org/guides/using-elements

and a getting started guide here:
https://www.polymer-project.org/1.0/docs/start/psk/set-up.html
