### ISSUE TITLE
iron-swipeable-container isn't working with dynamically added content

### ISSUE THREAD

**Issue by chriswalz** [Polymer/polymer#3230]
It works when I have elements inside of <iron-swipeable-container></iron-swipeable-container> declaratively; however, if I add elements using javascript those don't work.

**Comment by zoechi** [comment]
Can you provide a Plunker/JSBin to demonstrate the issue?

**Comment by chriswalz** [comment]
http://jsbin.com/jiyoqawobo/edit?html,console,output

In case something goes wrong with JSBIN. 
<!DOCTYPE html>
<html>  
<head>
  <meta charset="utf-8">
  <title>Polymer Bin</title>
  <script src="https://rawgit.com/webcomponents/webcomponentsjs/master/webcomponents.js"></script>
  
  <base href="http://element-party.xyz/">
  <link rel="import" href="all-elements.html">
  
</head>
<body class="fullbleed layout vertical">
        <iron-swipeable-container class="swipe" id="feed">
        <paper-material elevation="1">
          <p class="paper-font-body2">This is swipeable.</p>
        </paper-material>
      </iron-swipeable-container>
  </script>
</dom-module>
<script>
  elm = document.querySelector('#feed');
  n = document.createElement('paper-material');
  n.textContent = "This isn't :()";
  elm.appendChild(n);
</script>
</html>

**Comment by zoechi** [comment]
If you run code outside of Polymer elements where you want to access Polymer elements you have to wait until Polymer is fully initialized https://www.polymer-project.org/1.0/docs/migration.html#polymer-ready

**Comment by arthurevans** [comment]
I think the main problem here is that you need to use the Polymer.DOM API to add might DOM  children, otherwise it gets confused:

http://jsbin.com/kosuxenuxi/edit?html,console,output

**Comment by chriswalz** [comment]
Thanks, using the Polymer.DOM API worked.

**Comment by ebidel** [comment]
Marking as WIP then.
