### ISSUE TITLE
Window context when accessing this

### ISSUE THREAD

**Issue by luii** [Polymer/polymer#3231]
When i call `this` in a function in the Element script i get the window context?!

```js
<link rel="import" href="../../../bower_components/polymer/polymer.html">

<dom-module id="channel-view">
  <style></style>
  <template>
    <template is="dom-repeat"
              items="{{channels}}"
              as="channel">
      <span>{{channel}}</span>
    </template>
    <button on-tap="_onTap"></button>
    <input on-add-channel="addChannel">
  </template>
  <script>
    Polymer({
      is: "channel-view",
      properties: {
        channels: Array,
      },
      _onTap: () => {
        console.log(this); //<-- this prints the global window context
        this.fire('add-channel')
      },
      addChannel: (event) => {
        this.push('channels', {})
      }
    });
  </script>
</dom-module>
```

I tested it on FF (latest), Chrome and Electron they all have the same context

**Comment by miztroh** [comment]
Looks like that's some sort of bug specific to arrow functions.  When you do it this way, the bug disappears:

```
_onTap: function () {
	//...
}
```

**Comment by luii** [comment]
This solves my problem, thank you so much!!

**Comment by miztroh** [comment]
@luii Yeah, it looks like arrow functions work this way by design.

"Arrow functions capture the this value of the enclosing context".

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions
