### ISSUE TITLE
SVG <use> tags inside dom-repeat

### ISSUE THREAD

**Issue by maxsteenbergen** [Polymer/polymer#3232]
I'm iterating over an object using dom-repeat, and want to reference different icons from an SVG sprite sheet with each iteration. To add an icon, I'm trying to use the `<use xlink:href="sprite.svg#id">` method, mixed with Polymer's computed bindings. Here's the code inside the dom-repeat block:

``` html
<template is='dom-repeat' items="{{currentPlan.functionalities}}">
  <div class="resourceRow rowParent">
     <div class="functionIconContainer columnParent">
        <svg><use xlink:href$="{{ _getIconURL(item.id) }}"/></svg>
      </div>
  </div>
</template>
```

& the JS logic: 

``` js
_getIconURL: function(iconID){
  var url = "sprite.svg#" + iconID;
  return url;
}
```

This code outputs what I want it to, as far as I can see in Dev Tools, but still the icon doesn't show up. For reference, here's an example of what is written to the DOM:

``` html
<svg class="style-scope">
   <use class="style-scope" xlink:href="sprite.svg#id" />
</svg>
```

Is this a bug or my misunderstanding?

**Comment by zoechi** [comment]
Cross-posting from http://stackoverflow.com/questions/34434881/svg-use-tags-within-polymer-dom-repeat

**Comment by maxsteenbergen** [comment]
@zoechi IS that a no-no? I'll delete either one if so.

**Comment by zoechi** [comment]
Basically I think it's OK but you should cross-link to make it easy on both ends to see if someone already answered.

That said, GitHub issues are for bugs not for questions, therefore you should check previously if it's actually a bug. Asking on SO is a good way to find that out.
If you're pretty sure it's a bug, check if someone else already reported it. If not, it's great to create a bug report, ideally with a Plunker/JSBin that allows to easily reproduce the problem.
I'm no official here, that's just what I gathered from following the activities here.

**Comment by maxsteenbergen** [comment]
Ok, not sure if this really counts as a solution, but it fixes my immediate problem. I've attached an on-dom-change event handler to the dom-repeat block, which gets called on well, DOM changes. Then I loop through each icon container and set its innerHTML to itself. I don't know what it does, but it somehow forces a re-evaluation of that part of the DOM, causing my icons to show up. It's the simplest of code:

_forceRedraw: function(){
 var functionIcons =document.querySelectorAll('div.functionIconContainer');
  _.each(functionIcons, function(iconContainer){
    iconContainer.innerHTML = iconContainer.innerHTML;
  })
}
'Lo, it works!

Still not sure it this is a Polymer bug or not.

**Comment by azakus** [comment]
Hi, can you provide a JSBin containing a set of reproducible steps? See [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs) for details.

I'll bet the issue here is that we don't fix the href difference between the import document location and the main document location on the svg use element when creating instances.

**Comment by zoechi** [comment]
Angular2 has the same issue. Would be interesting if the workaround someone mentioned there today works in Polymer as well

```html
<svg><use xlink:href="" xlink:href$="{{ _getIconURL(item.id) }}"/></svg>
```

**Comment by TimvdLippe** [comment]
Closing this per https://github.com/Polymer/polymer/issues/3232#issuecomment-183456326

**Comment by davidmaxwaterman** [comment]
I can confirm that the w/a detailed in @zoechi 's post does indeed work.
