### ISSUE TITLE
this._doBehavior is not a function

### ISSUE THREAD

**Issue by Xeselaro** [Polymer/polymer#3235]
On `element.innerHTML = '<custom-x></custom-x>'` this error appears:

> Uncaught TypeError: this._doBehavior is not a function
>  &nbsp;&nbsp; &nbsp;&nbsp; Polymer.Base.detachedCallback	@	polymer-micro.html:161

polymer-micro.html
   ` detachedCallback: function () {
    this.isAttached = false;
    this._doBehavior('detached');
    },`

**Comment by andrewebdev** [comment]
I've encountered the same error, but it only happens occasionally for me.
I can post a full example of this on a live site soon-ish.

**Comment by samccone** [comment]
looking forward to seeing the test case @andrewebdev thanks!

**Comment by andrewebdev** [comment]
hmm, somehow after I pushed my code live, I'm not getting this error anymore. So my example would not be valid. Sorry guys :(

**Comment by azakus** [comment]
This issue has no reproducible steps. Please comment on this issue if it still occurs, with a JSBin containing a set of reproducible steps. See [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs) for details.
