### ISSUE TITLE
Polymer ERROR - IE11

### ISSUE THREAD

**Issue by yonathan9669** [Polymer/polymer#3236]
Well, I really made a deep search before to ask for your help boys, but I'm stuck getting a project run on IE11.

I can't really find out the error and it looks like if the problem were within the polymer library.

![error1-2](https://cloud.githubusercontent.com/assets/897389/12006868/3265c0cc-abbb-11e5-9f7d-0d4d6bcbfaa6.PNG)

The microsoft helper just says that a thrown error is not been captured, and I can't find any similar problem on the web, the weird is that after reload the browser and A LOT of wait time, the project show up (not fully working) but at least is navigable.

![error2-2](https://cloud.githubusercontent.com/assets/897389/12006919/ac7038b4-abbd-11e5-819c-7644c73f2a31.PNG)

I made several test but I got quite more doubts, for example the PSK works just fine I made changes and It still works, I already check all the versions of my libraries.

![dependencies](https://cloud.githubusercontent.com/assets/897389/12006927/69817238-abbe-11e5-8729-830bd164686c.PNG)

The project was build under the PSK structure.

**Comment by ebidel** [comment]
The issue tracker isn't a great place to debug apps. I'd recommend posting on the Slack channel or on StackOverflow with a jsbin that repos the issue.
