### ISSUE TITLE
(Angular 2.0.0 beta.0 + Polymer 1.0) paper-input data binding not working on IE11

### ISSUE THREAD

**Issue by ldtung** [Polymer/polymer#3237]
I have a paper-input component declared as below, where myField is a field initialized with value="TestValue"

paper-input ngDefaultControl [(ngModel)]="myField" label="my label"

On chrome, it's working fine, "TestValue" is displayed when loading screen.
The two way data binding working fine.
but on IE11, "TestValue" is not displayed. Even if i changed value in paper-input to something else,
the data model is not updated.

I debugged into the code, and see that NG2 has already updated the paper-input's value to "TestValue" when rendering the screen but seems the input inside does not see the same value

Any idea?

**Comment by ebidel** [comment]
This issue was moved to PolymerElements/paper-input#298
