### ISSUE TITLE
Mixin for paper-material

### ISSUE THREAD

**Issue by kimberleyhansen** [Polymer/polymer#3242]
Would love a mixin for paper-material to easily enable changing stuff like background-color globally.

Edit: not sure if this is the right place for this...

**Comment by TimvdLippe** [comment]
Hey Kimberley,

We talked about this issue on Slack. You can create an issue at the paper material repository at https://github.com/PolymerElements/paper-material/issues

**Comment by kimberleyhansen** [comment]
Thanks so much. I feel...dumb, haha. You've been a big help.

**Comment by TimvdLippe** [comment]
No problem. Do hesitate to poke Slack again when you are having problems.
