### ISSUE TITLE
Process catch-all <content></content> after filtered <content select="selection"></content>'s

### ISSUE THREAD

**Issue by drarmstr** [Polymer/polymer#3243]
`<content></content>` tags in the shadow DOM can be used to pull in light DOM elements to the local DOM.  A selector can be applied to filter nodes: `<content select="selector"></content>`.  The order of the `<content>` tags is important because selectors are not guaranteed to be non-overlapping.  Once a node is pulled into the local DOM it is no longer available for a subsequent `<content>` tag.  However, it would be useful if the "_catchall_" `<content></content>` were processed last, after all `<content>` tags with a `select` attribute.  This way they could be followed with more selective selections.

For example:

    <dom-module>
        <template>
            <div>
                 <content select="header"></content>
            </div>
            <div>
                <content></content>
            </div>
            <div>
                <content select="footer"></content>
            </div>
        </template>
    </dom-module>

**Comment by ebidel** [comment]
Unfortunately, handling of the default `<content></content>` is part of the shadow dom spec and not something Polymer can change. One thing you can do is use CSS to "adjust" where things are rendered. In your example, you could use the `order` property to change the rendering order of the divs.
