### ISSUE TITLE
paper-input two-way binding with shadow is not working on chrome

### ISSUE THREAD

**Issue by robertsab** [Polymer/polymer#3244]
paper-input two-way binding with shady is working on chrome(ubuntu 47.0.2526.106 (64-bit)) and it is not working with shadow on chrome

using Polymer 1.2.1.

**Comment by zoechi** [comment]
"it's not working" is pretty vague. Can you provide a Plunker that demonstrates the issue?

**Comment by robertsab** [comment]
http://jsbin.com/gojuseremi/edit?html,output

**Comment by ebidel** [comment]
This issue was moved to PolymerElements/paper-input#297
