### ISSUE TITLE
Pass parameters to annotated event listeners

### ISSUE THREAD

**Issue by pensierinmusica** [Polymer/polymer#3246]
Hi,

I'd like to be able to directly pass parameters to [annotated event listeners](https://www.polymer-project.org/1.0/docs/devguide/events.html#annotated-listeners).

``` html
<dom-module id="x-custom">

  <template>
    <button on-click="handleClick('hello')">Kick Me</button>
    <button on-click="handleClick('bye')">Kick Me</button>
  </template>

  <script>

    Polymer({

      is: 'x-custom',

      handleClick: function(text) {
        alert(text);
      }

    });

  </script>

</dom-module>
```

I know this can be achieved through `data` attributes, but why not doing it directly then?

Thanks, cheers!

**Comment by Hunsin** [comment]
Hi, I wonder what this will be in 2.0?

**Comment by femiadeyemi** [comment]
any update on this?

**Comment by web-padawan** [comment]
This looks like an opinionated enhancement which violates KISS principle.
In the plain DOM events, we don't have such stuff and Polymer tries to get as closer to the platform as possible.
We could just specify some data-attributes on the target element instead, and then check event target in the listener.

**Comment by pensierinmusica** [comment]
@web-padawan I know it can be done that way, but there are cases where it'd be nice to be able to directly pass a parameter, like you normally do in any function call. Indirectly using attributes adds complexity that maybe could be avoided.
