### ISSUE TITLE
dom-repeat doesn't sort properly when updated with a larger array

### ISSUE THREAD

**Issue by drarmstr** [Polymer/polymer#3247]
When using `dom-repeat` with an items array and a `sort` attribute, it will properly sort the items.  However, if I update the items array from a callback handler to a new array that is longer than the previous one, then it will not be sorted properly.  It appears that the items are actually sorted in the correct order, however the items start somewhere in the middle of the list and then wrap around.  It appears that the number of items wrapped around at the end is equal to the same number of items that was in the previous items array.  So, I would suspect this bug is due to some DOM node reuse perhaps?

To clarify the array ordering, if the previous array had 3 items and the new array has 10 items, then the new sort order is: `3, 4, 5, 6, 7, 8, 9, 0, 1, 2`

As a workaround I was able to get the correct sort order by delaying setting of the new array in the callback as follows.  (`index` is the property bound to `items` in the `dom-repeat`)  I'm not sure why this helps.

```
event_callback(e:CustomEvent) {
    setTimeout(()=> { this.index = e.detail.response; }, 0);
}
```

**Comment by zoechi** [comment]
I think this should be `this.set('index', e.detail.response)`

**Comment by drarmstr** [comment]
Yeah, I tried using `set()` also, it didn't make a difference.
