### ISSUE TITLE
paper-tabs selected issue

### ISSUE THREAD

**Issue by brusand** [Polymer/polymer#3248]
hi the community

here is a coepen to illustrate my issue :+1: http://codepen.io/burno75/pen/LGbLoM

working : remove jack paper-tab -> annick selected and content 2 displayed OK
not working : remove annick  paper-tab -> KO jack paper-tab not selected (and  his iron-page content1 not visible)

Any idea ?

is there any compenent like chrome tabs ?

best regards
Bruno

**Comment by ebidel** [comment]
This issue was moved to PolymerElements/paper-tabs#118
