### ISSUE TITLE
XML Demo for Iron-Ajax

### ISSUE THREAD

**Issue by chriswalz** [Polymer/polymer#3250]
Would be nice to see a demo for Iron-Ajax with XML. I can't seem to get it working.

**Comment by zoechi** [comment]
Wasn't XML support removed from Chrome a while ago or at least deprecated? Without XML support from the browser, this would be difficult.

**Comment by ebidel** [comment]
That's XLST. It would be hard to remove XML from the web platform :)

This bug is more appropriate on the iron-ajax issue tracker, but you should be able to get the `.responseXML` from the element's xhr object.

**Comment by zoechi** [comment]
Didn't follow the discussions, just remember reading it a while ago.
https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/ZvArHAXyAHM/ftybb0waCKYJ
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/zIg2KC7PyH0%5B126-150%5D
