### ISSUE TITLE
Attach code when visiting elements demo page

### ISSUE THREAD

**Issue by xiulunlin** [Polymer/polymer#3251]
It would be easier and faster for starters to understand how demos are created..

**Comment by zoechi** [comment]
What do you mean by "attach code"?  The elemens pages have a link to the element and demo source.

**Comment by ebidel** [comment]
We're working on catalog updates that will show demo + code together. cc @tjsavage @notwaldorf

**Comment by ebidel** [comment]
This issue was moved to Polymer/polymer-element-catalog#229
