### ISSUE TITLE
Elements do not render when opening a tab in the background...

### ISSUE THREAD

**Issue by zboralski** [Polymer/polymer#3252]
If I open a link on my polymer app in a background tab it won’t load until I select the tab... I get the same issue both in Safari and Chrome. 

I first thought it was an iron-pages issue, so I moved my element outside of iron-pages... The element now sit in my index.html's template dom-bind... it is binded to iron-page-url and wait for the url path to change... 

If the url path changes to '/url/' it checks a token in local storage and navigate to the url in the query string if the token is valid.

**Comment by zboralski** [comment]
Even if I tried to do something in the element's created method, nothing happens until I click the tab:

```
      created: function(selected) {
        if (window.location.href.substring(0,25) === 'http://localhost:5001/url') {
          window.location.href = 'https://google.com';
          console.log('eee');
      },
```

created won't be called until I select the tab.

**Comment by zboralski** [comment]
I think this is the issue : 

http://stackoverflow.com/questions/32212256/what-happens-or-doesnt-happen-in-a-chrome-tab-opened-in-the-background

**Comment by ebidel** [comment]
Looks like [some parts of core](https://github.com/Polymer/polymer/blob/1c67a5e09ee883c1fd5bba86462943e8926e24b2/src/lib/render-status.html) delay work until after `requestAnimationFrame` for various reasons. 

As SO points out, Blink throttles rAF calls if the tab is in the background.

It's easy to observe this behavior on https://www.chromestatus.com/features Opening it in a background tab (or refresh the page and quickly switching to another tab), the feature list never fully loads.

**Comment by cdata** [comment]
I'm going to close this issue tentatively in favor of https://github.com/Polymer/polymer/issues/3252 which contains repro steps.

FWIW this behavior should change in the next major version release of Polymer so that elements can upgrade in tabs that don't have focus.
