### ISSUE TITLE
dom-repeat filter not updating when entire Array item is set

### ISSUE THREAD

**Issue by stevenjb** [Polymer/polymer#3254]
Summary:

```
 <template is="dom-repeat" filter="aFilter" observe="show" items="{{items}}">
        <div>{{item.name}}</div>
    </template>

  properties: {  items: { type: Array, value: function() { return [ 
        {show: false, name: 'A'}, 
        {show: true, name: 'B'}, 
      ]}
  }
```

This updates the dom-repeat as expected:

```
this.set('items.0.show', true);
```

This however does not update the dom-repeat, although I would expect it to:

```
  var newItem = { show: true, name: 'A' };
  this.set('items.0', newItem);
```

As a workaround I am using splice, which works as expected:

```
this.splice('items', 0, 1, newItem);
```

Fiddle: https://jsfiddle.net/stevenjb_chromium/nbndnsk7/

**Comment by zoechi** [comment]
When you enclose code blocks in triple backticks source code becomes more readable (single backtick for inline code)

**Comment by ebidel** [comment]
@kevinpschaaf is this expected. I would expect this to work as well, but `splice` is also a proper "workaround".

**Comment by kevinpschaaf** [comment]
Confirmed this is a bug with the `observe` handling when replacing items.  Marking as bug.
