### ISSUE TITLE
Firebase Element: Error if setting location declaratively from parent

### ISSUE THREAD

**Issue by chriswalz** [Polymer/polymer#3257]
I have this code below in an element called **\<spark-input\>**
**\<firebase-collection location="https://removed.firebaseio.com/{{store}}" \>\</firebase-collection\>**

In another element I have this declaration.  
**\<spark-input store="posts"\>\</spark-input\>** 

I get this error: **'FIREBASE FATAL ERROR: Cannot parse Firebase url. Please use https://\<YOUR FIREBASE\>.firebaseio.com'**

**Comment by chriswalz** [comment]
My work clunky work around
    <spark-input store="posts"></spark-input>
    <firebase-collection location="https://removed.firebaseio.com/{{a}}" ></firebase-collection>
     post: function() {
          this.a = this.store;
          // post code
    }

**Comment by ebidel** [comment]
This issue was moved to GoogleWebComponents/firebase-element#97
