### ISSUE TITLE
Native Webcomponents in Firefox with Polymer not working

### ISSUE THREAD

**Issue by jogibear9988** [Polymer/polymer#3258]
I use folloging Code in HTML

    <body unresolved class="hold-transition skin-green sidebar-mini">
        <template is="dom-bind" id="app">

if I enable native Webcomponents vis about:config in firefox, my body keeps empty!

has anyone tried polymer dom-bind with firefox native support?

**Comment by jogibear9988** [comment]
Also Polymer Site seems to not work correctly with Webcomponents in FF enabled!

**Comment by jogibear9988** [comment]
This is how the site looks like:

<img width="1291" alt="bildschirmfoto 2015-12-31 um 17 02 04" src="https://cloud.githubusercontent.com/assets/364896/12065951/3fc35850-afe0-11e5-9c7a-7b3969c32a12.png">

**Comment by ebidel** [comment]
FF's implementation(s) are not complete and do not work with the flag on. Please turn it off.
