### ISSUE TITLE
confused about `ready` lifecycle callback order

### ISSUE THREAD

**Issue by Jeff17Robbins** [Polymer/polymer#3261]
[ready.html source](https://github.com/Polymer/polymer/blob/master/src/mini/ready.html) states about the `ready` callback that **it's called parent (host) to child:**

```
Provides `ready` lifecycle callback which is called parent to child.

This can be useful in a number of cases. Here are some examples:

Setting a default property value that should have a side effect: To ensure
the side effect, an element must set a default value no sooner than
`created`; however, since `created` flows child to host, this is before the
host has had a chance to set a property value on the child. The `ready`
method solves this problem since it's called host to child.
```

But in logging the `ready` callback in several elements in the Polymer [todo-mvc example](https://github.com/tastejs/todomvc/tree/gh-pages/examples/polymer) (

[flatiron-director.html.txt](https://github.com/Polymer/polymer/files/76119/flatiron-director.html.txt)
[iron-localstorage.html.txt](https://github.com/Polymer/polymer/files/76122/iron-localstorage.html.txt)
[td-input.html.txt](https://github.com/Polymer/polymer/files/76121/td-input.html.txt)
[td-item.html.txt](https://github.com/Polymer/polymer/files/76120/td-item.html.txt)
[td-model.html.txt](https://github.com/Polymer/polymer/files/76123/td-model.html.txt)
[td-todos.html.txt](https://github.com/Polymer/polymer/files/76124/td-todos.html.txt)

by editing my local copy of these elements as attached above), I noticed that the `ready` order seems to be child to host, not host to child.

The element structure in the Polymer todo-mvc app is roughly:

```
td-model    
    iron-localstorage
td-todos    
    flatiron-director
    input is="td-input"
```

Yet here is is the logged order of the `ready` callbacks:

```
IRON-LOCALSTORAGE ready
TD-MODEL ready
FLATIRON-DIRECTOR ready
INPUT ready
TD-TODOS ready
```

The top of `<td-todos>`'s`<template>` is:

```
<dom-module id="td-todos">
    <template strip-whitespace>
        <style>
            :host {
                display: block;
            }
        </style>
        <flatiron-director route="{{route}}" hidden></flatiron-director>
```

I am assuming this means that `<flatiron-director>` is the `child` and `<td-todos>` is the `parent`.  Yet the `ready` callback in `<flatiron-director>` is called before the `ready` callback in `<td-todos>`.

How ought I reconcile this with the code's comment that the `ready` lifecycle callback is called parent to child?

Furthermore, similar logging in the `created` lifecycle callbacks produces this log:

```
TD-MODEL created
IRON-LOCALSTORAGE created
TD-TODOS created
FLATIRON-DIRECTOR created
INPUT created
```

This would seem to contradict the code comment's claim that:

```
...`created` flows child to host,
```

since `<td-todos>`'s created is called before `<flatiron-director>`'s.   

Is the comment wrong?  Or is my interpretation about the logging I added to the Polymer todo-mvc app misleading somehow?

**Comment by TimvdLippe** [comment]
Sorry for not responding sooner :cry: `ready` is now the same as `connected` with custom elements v1: http://jsbin.com/xuwugubuso/edit?html,console,output For more information about the transformation of callbacks, see https://www.polymer-project.org/2.0/docs/about_20#lifecycle-changes

If you need to know when a child has finished loading, you can fire an event in the child to notify the parent. That way the parent can react to the initialized child and do its appropriate work. Polymer no longer maintains this work for you.
