### ISSUE TITLE
initialization issue with WebComponentsReady and also components sync 

### ISSUE THREAD

**Issue by dman777** [Polymer/polymer#3262]
Polymer 1.2.3

For `WebComponentsReady` and also component initialization being sync, there is a issue where the elements are not ready yet when `WebComponentsReady`  fires or synchronous initialization when a script to manipulate DOM is placed last. 

When attaching event listeners to my polymer elements, sometimes the elements are not ready. 

For an example, in ` panel.addEventListener("content-scroll", moveTitle);` `panel` will be undefined. 
If I took out panel, it would be a different element with same issue for attaching a listener(`mainPanelContent` has happened before). 

It's important that I point out that this issue is not consistent and is random. 

This happens both with `WebComponentsReady` in Firefox and in Chrome with the `initialize.js` file being placed last in index.html.

From the bottom portion of my index.html, where it is 2nd to last line:

###### index.html
```html
    </template>
	</body>
  <link rel="import" href="imports.html" async>
  <script src="http://104.2xxxxxx/livereload.js?snipver=1"></script>
```
###### app/imports.html 
```html
one@public-node ~/github/resume $ cat app/imports.html 
...
<script src="js/misc.js" ></script>
<script src="bower_components/page/page.js"></script>
<script src="js/router.js"></script>
<script src="js/resume.js"></script>
<script src="js/pdf.js"></script>
<script src="js/pdf.worker.js"></script>
<script src="js/initialize.js" defer></script>
```

###### initialize.js
```js

function makeGlobalElements() {
  //elements is not routing list, routing list is elementList
  panel = Polymer.dom(document.rootElement).querySelector('paper-header-panel[main]');
  rippleElement = Polymer.dom(document.rootElement).querySelector('#ripple-element');
  toolbar = Polymer.dom(document.rootElement).querySelector('#main-toolbar');
  headerName = Polymer.dom(document.rootElement).querySelector('#name-title');
  drawer = Polymer.dom(document.rootElement).querySelector('paper-drawer-panel');
  mainPanelContent = Polymer.dom(document.rootElement).querySelector('#mainPanelContent');
};

function attatchListeners() {
  panel.addEventListener("content-scroll", moveTitle);
  ['webkitAnimationEnd', 'animationend']
  .forEach(function(vendor) {
    mainPanelContent.addEventListener(vendor, function (animationEvent) {
      if (animationEvent.animationName === "slide-down") {
        afterSlideDown.runStack();
        mainPanelContent.classList.remove('slide-down-now');
      }
    });
    headerName.addEventListener(vendor, function() { 
      headerName.classList.remove('fade-title'); 
    });
  });
};

//polymer bug where elements aren't ready in time
function safetyCheck() {
  var elements = [panel, rippleElement, toolbar, headerName,
   drawer, mainPanelContent];

  var completed = elements.every(function(el) {
    if (el !== null && typeof el !== 'undefined' && el.nodeType === 1) {
      return true;
    } else {
      return false;
    }
  });

  if (!completed) {
    console.log('Elements weren\'t ready, running again');
    makeGlobalElements();
  }
};


function initializeYay() {
  makeGlobalElements();
  safetyCheck();
  attatchListeners();
  setUpRoutes();
  removeSplash();
  //fetchPdfjs();
}

if (!webComponentsSupported) {
  document.addEventListener('WebComponentsReady', initializeYay);
} else {
  initializeYay();
}

```

###### pollyfill.js to show how I handle chrome/non chrome:

```js
one@public-node ~/github/resume $ cat app/js/polyfill.js 
// 4. Conditionally load the webcomponents polyfill if needed by the browser.
// This feature detect will need to change over time as browsers implement
// different features.
var webComponentsSupported = ('registerElement' in document
    && 'import' in document.createElement('link')
    && 'content' in document.createElement('template'));


function createScript(file) {
  var script = document.createElement('script');
  script.async = true;
  script.src = file;
  document.head.appendChild(script);
}

function createLink(file) {
  var link = document.createElement('link');
  link.async = true;
  link.href = file;
  link.rel = 'import';
  document.head.appendChild(link);
}


if (!webComponentsSupported) {
  createScript('../bower_components/webcomponentsjs/webcomponents-lite.min.js');
  createLink('../css/non-chrome-shadow.html');
} else {
  createLink('../css/chrome-shadow.html');
} 

```

![not-ready](https://cloud.githubusercontent.com/assets/887815/12073597/93f545da-b0eb-11e5-9f23-62eecf265702.jpg)

**Comment by ebidel** [comment]
Noticing a couple of things:
- you're using `async` imports. If you remove `async` does it help? Timing issues may be related to https://github.com/Polymer/polymer/issues/3095
- You have `</template>` in your main page. If you're using dom-bind, you should wait for the `dom-change`event for the template to stamp and before querying nodes in the DOM
- Since you're querying elements in the main page, there's no need to use the `Polymer.dom(document.rootElement)` api.

**Comment by dman777** [comment]
*  I removed `async` but it did not help(did it again right afterwards).
* I did try the `dom-change` event in the past but it didn't work for me in my use case.....it's awhile back, can not remember why. 
* Thanks, I changed them back. I only had the `Polymer.dom(document.rootElement)` for trouble shooting. 

I can't help thinking if this might have something to do with the browser cache. When I close the connect server sometimes I can still refresh the page and this issue will be more consistent.

**Comment by ebidel** [comment]
In that case, debug with the Devtools open and the "Disable cache" checkbox checked in the network panel. You can also try vulcanizing the app to remove timing issues from the equation.

**Comment by ebidel** [comment]
Can you also try to load the polyfills directly to see if that changes anything for you?

**Comment by dman777** [comment]
Hi, this was a issue when I used to inject polyfills regardless(before optimization scripts). I also had the issue with disable cache.  Also, this was on development with livereload.  I wrote a script to reload the page if elements aren't ready. I am now deployed to production and haven't done much with it since...taking a much needed break from it :) Occasionally, I will load it up from prod to enjoy it and I haven't had the issue come up. That could be from the script or nginx since both have been used at the same time.

**Comment by ebidel** [comment]
Going to close then.

**Comment by dman777** [comment]
Hello,

I recently stopped using http2 push and I am now using vulcanize with html, css, js inline. I thought this might not be a issue any more, so I commented out the reload:

```javascript

function initializeYay() {
  makeGlobalElements()
    .then(function() {
    attatchListeners();
    setUpRoutes();
    fetchPdfjs();
    removeSplash();
  })
  .catch(function() {
    //location.reload();
    console.log('error init');
  });
}
```

But the issue happen to me on the production server. I tried it a few times and I could not reproduce the issue again...so it's random(inconsistent).
