### ISSUE TITLE
dom-change not invoked in Chrome with jQuery's replaceWith

### ISSUE THREAD

**Issue by eximius313** [Polymer/polymer#3275]
I have a template:

```
<div id="form">
    <template is="dom-bind" id="myTemplate">
        <!-- some code -->
    </template>
    <script>
        var myTemplate = document.getElementById('myTemplate');
        myTemplate.addEventListener('dom-change', function() {
            //initializing functions
        });
    </script>
</div>
```

now when I perform Ajax request and replace the form (where `event.detail.response` is exactly the same div served by the server):

```
$('#form').replaceWith(event.detail.response);
```
- In Firefox `dom-change` is being invoked
- In Chrome `dom-change` is **not** being invoked

**Comment by azakus** [comment]
Can you post a reproducible example with [jsbin](http://jsbin.com) or a similar tool?

**Comment by eximius313** [comment]
Here is JSBin which shows this situation:
https://jsbin.com/vutunucuqe/1/edit?html,console,output

Please click on the "latest" ```CLICK ME``` button and observe how Chrome "freezes" while Firefox is still serving new "responses" and invoking script.

The example is not ideal, but it demonstrates **realy serious issue**: 
If we have a from, which is using Polymer components, and these components require even simple bindings or attaching events - we **must** attach them in on ```dom-change``` because **otherwise they'll not work on Firefox**. BUT when the form validates and server sends "new version" Firefox performs ```dom-change``` and all bindings works again **but Chrome doesn't** (which causes that **in Chrome form doesn't work properly after first validation**).

I hope that I have explained it well.
Kind regards.

**Comment by TimvdLippe** [comment]
@eximius313 I am unable to reproduce this issue with Polymer 2: https://jsbin.com/fonacokeka/edit?html,console,output Could you let us know if this still an issue?
