### ISSUE TITLE
Feature: binded binding

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#3277]
Sorry for a bit confusing title.
Feature is related to declarative combining of various elements together.

How it works for me now:

``` html
<template is="dom-bind">
    <section is="cs-section-modal" this="{{modal}}">One Two Three</section>
    <button bind="[[modal]]" action="open" is="cs-button" type="button">Button</button>
</template>
```

In example above `modal.open` will be called on button click.

What I'd like to have is following:

``` html
<template is="dom-bind">
    <section is="cs-section-modal" this="{{modal}}">One Two Three</section>
    <button on-tap="modal~open" type="button">Button</button>
</template>
```

or another way binding to arbitrary property:

``` html
<template is="dom-bind">
    <section is="cs-section-modal" this="{{modal}}">One Two Three</section>
    <button action="[[modal~open]]" is="cs-button" type="button">Button</button>
</template>
```

`modal~open` is equivalent to passing `modal.open.bind(modal)`. `~` symbol is taken from LiveScript, which might be familiar to some JavaScript developers and visually shows that `open` have some binding relation to `modal`. Also there is no need for special processing in target element, any method can be passes to regular events.

**Comment by TimvdLippe** [comment]
I am not sure if I understand your request correctly, but would #3259 also fix the problem?

**Comment by nazar-pc** [comment]
It is kind of similar, but in my case it would be more generic and explicit: `on-tap="$.ajax~generateRequest"` (though, I haven't tried yet if dots are supported here at all, I was originally thinking about not only events listeners, but about generic binding to arbitrary property).
I've also corrected example above to remove brackets in `on-tap`.
It is not always the case that you have `id` on that element.

It should works exactly the same way as now, but call `.bind(..)` to preserve `this` inside that binded method.
