### ISSUE TITLE
content[select] selects only direct child nodes

### ISSUE THREAD

**Issue by Jamtis** [Polymer/polymer#3278]
The docs state that ["The <content> element supports a select attribute which filters nodes via a simple selector."](https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#dom-distribution).
However only **direct child** nodes can be selected, as you can see here: https://jsfiddle.net/jamtis/5heqzwru/

```
<dom-module id="content-select">
  <template>
    <div class="content-wrapper">
      <content select=".direct-child>.sub-child"></content>
      <content select=".no-container"></content>
    </div>
  </template>
</dom-module>

<content-select>
  <div class="direct-child no-container">
     Direct Child
  </div>
  <div class="direct-child">
    <div class="sub-child">
      Sub Child
    </div>
  </div>
</content-select>
```

Only `.no-container` (the direct child) will be inserted into the `content-select` element.

The formulation "via a simple selector" suggests that every content node can be adressed.
I am not sure if this behavior is intended.
Personally I don't see a reason not to allow sub child selection.

Anyways I think the doc needs a clarification.

**Comment by azakus** [comment]
Yes, this is intended behavior, and is the behavior described in the ShadowDOM spec.

@arthurevans, @kaycebasques maybe this could be tightened up the docs a bit?

**Comment by TimvdLippe** [comment]
`<content>` has been replaced with `<slot>` and its selection mechanism is described at https://www.polymer-project.org/2.0/docs/devguide/shadow-dom#multi-level-distribution
> A named slot only accepts top-level children that have a matching slot attribute:
