### ISSUE TITLE
Array updates not observed, template value not recomputed.

### ISSUE THREAD

**Issue by danostrowski** [Polymer/polymer#3280]
This is possibly a duplicate, or related to, these two issues:

https://github.com/Polymer/polymer/issues/3254
https://github.com/Polymer/polymer/issues/3239

I am trying to get a CSS value to be different based on whether an array has a length of 0 or >0. However, `this.push('path', val)` doesn't seem to notify or redraw the template when updating an array property.

I've put together a couple fiddles showing this. The square SHOULD change to have the "some" class which would have a different background color. You can see in the logging that initially either the method (computed value) or the observer is called on first loading up... but then when the tap happens, neither are called.

Example A, changing a variable when the notify goes off... https://jsfiddle.net/qez3thqr/
Example B, slightly different, using a computed value... https://jsfiddle.net/19pfuwby/

**Comment by arthurevans** [comment]
This simple property observer isn't what you want. It will only fire when the entire array is replaced.
(Like, `this.history = [ "New Thing" ];`)

There are a couple of simple but less obvious ways to handle this. The simplest is to have your computed binding take `history.length` as a dependent property.

You can also use `history.splices` (to get all array mutations) and `history.*` (to get array mutations + subproperty changes). But in this case, `history.length` is the simplest thing to do.

**Comment by danostrowski** [comment]
Hey Arthur, thanks for the reply.

So I went back. As you suggested, if you completely replace the array, a single observer on `history` works. If you use `history.length` and pass it to a method for the `on-tap` it works. Cool.

However, what I found was that setting up an "observers" array looking at `history.splices` or `history.*` does *not* seem to work. The `historyChanged` observer doesn't seem to fire in either of the following scenarios.

Looking at `history.splices` ... https://jsfiddle.net/ug3spghy/
Looking at `history.*` ... https://jsfiddle.net/7avvzaxo/

Am I seeing this correctly? I'm setting observers up like so:

```
observers: [
    'historyChanged(history.*)'
],
```

Shouldn't the observer function fire, here?

**Comment by arthurevans** [comment]
You have a typo--your observers array is inside the properties object,
where it should be a separate object.

Also, these observers don't give you newval/oldval arguments, they give you
a change record. Here's a description of the change record for array
changes:

https://www.polymer-project.org/1.0/docs/devguide/properties.html#array-observation

If you do a wildcard observer (`history.*`), the change record includes a
`path` property, so you can tell what changed. (So in this case, if it's an
array mutation, you'd get a change record with a path of `history.splices`,
and the `indexSplices` and `keySplices` properties as described above).

More info:

https://www.polymer-project.org/1.0/docs/devguide/properties.html#deep-observation

Hope this helps.
Cheers,
Arthur

**Comment by danostrowski** [comment]
Oh gosh, apologies, I should have done a doc check before I modified those fiddles. Thanks!

**Comment by davidmaxwaterman** [comment]
New(er) links, in case it helps anyone else:

https://www.polymer-project.org/1.0/docs/devguide/observers#array-observation
https://www.polymer-project.org/1.0/docs/devguide/observers#deep-observation
