### ISSUE TITLE
SCRIPT1003: Expected ':' IE11

### ISSUE THREAD

**Issue by khoanguyenlio** [Polymer/polymer#3281]
i got an issues in IE 11, when I use my custom element. It's normal in chrome but in IE11 I got this problem 
![bug](https://cloud.githubusercontent.com/assets/9152575/12193260/047bb5b4-b619-11e5-9caa-a60d149b4a51.jpg)
Failed to open data:text/javascript;charset=utf-8,   (function () {

**Comment by khoanguyenlio** [comment]
Just syntax, i declare a function lkie _renderClosed(){} -> should use _renderClosed: function(){}.
Still work in Chomre but not for IE/FF

**Comment by samccone** [comment]
@khoanguyenlio can you post the JS from your component here?

Also sometimes stackoverflow is a better place to ask these questions to get general debugging tips.

**Comment by khoanguyenlio** [comment]
@samccone thank you :+1: 
`<script>`
	`Polymer({
	    is: 'spas2-date-picker',

	    properties: {
	        value: {
	            type: Array,
	            observer: 'bindValueChanged'
	        },
	        minDate: {
	            type: Array
	        },
	        maxDate: {
	            type: Array
	        },
	        inValid: {
	            type: Boolean,
                observer: 'bindInValidChanged'
	        }
	    },

		showDatePickerDialog: function () {
			this.$.spas2dialogDatePicker.open();
		},
		onChangeDatePicker() {
			this.$.spas2dateField.value = new Date(this.$.spas2picker.date).format('yyyy-mm-dd');
			this.value = this.$.spas2dateField.value;
		}
`</script>`

i got this error cuz -> onChangeDatePicker() {} is wrong. -> onChangeDatePicker: function() {

**Comment by jogibear9988** [comment]
if you found out, maybe close the issue?

**Comment by mutovkin** [comment]
I wonder what was the issue? Having similar error in IE11 now.

**Comment by rozzamozza** [comment]
I have a similar issue in IE11 - any ideas?

**Comment by rozzamozza** [comment]
The problem (which happened to me too) can be fixed by chnaging:
     onChangeDatePicker(){
to:
     onChangeDatePicker : function(){

**Comment by bgoerdt** [comment]
I am also having this issue, but the errors are coming from Polymer code files like lib/utils/case-map.html.js and /lib/elements/dom-module.html.js. I am just trying to get the basic CustomElement example to work in IE 11. Is anyone else seeing this?
