### ISSUE TITLE
seed-element github page not found

### ISSUE THREAD

**Issue by maxgrass** [Polymer/polymer#3282]
On the page https://www.polymer-project.org/1.0/docs/start/reusableelements.html#local-dependencies

search for this sentence:

"You can check out the live version of this page for the seed-element project."

"live" is a link to github pages, which is broken:
http://polymerlabs.github.io/seed-element/components/seed-element/

**Comment by dsschnau** [comment]
I think the link should point [here instead](https://github.com/PolymerElements/seed-element)

**Comment by azakus** [comment]
Looks resolved in those other repos.
