### ISSUE TITLE
submenu.toggle() is not a function

### ISSUE THREAD

**Issue by Xeselaro** [Polymer/polymer#3283]
BUG:
document.querySelector('#submenuelement').toggle() is not a function

**Comment by azakus** [comment]
Can you post a reproducible example with [jsbin](http://jsbin.com)?

This should also be posted to the [paper-menu](https://github.com/polymerelements/paper-menu) repo

**Comment by azakus** [comment]
This issue was moved to PolymerElements/paper-menu#81
