### ISSUE TITLE
Relative paths do not resolve correctly with MDV

### ISSUE THREAD

**Issue by arodic** [Polymer/polymer#329]
The following element should have two images pointing to the same relative src. However, the first one resolves the path relative to the element's path and the other one resolves relative to index.html

http://aleksandarrodic.com/temp/polymer-bug/

Here is the code:
```
<polymer-element name="src-bug">
    <template>
    <style>
      @host {
        * {
          display: block;
        }
        * > img {
          width: 64px;
          height: 64px;
        }
      }
    </style>
    <img src="./images/ash_uvgrid01.jpg"/>
    <img src="{{src}}"/>
    </template>
    <script>
        Polymer('src-bug', {
            src: "./images/ash_uvgrid01.jpg"
        });
    </script>
</polymer-element>
```

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
