### ISSUE TITLE
Use polymer emelents within angular 2 application

### ISSUE THREAD

**Issue by SimonKunz** [Polymer/polymer#3290]
I'm having some problems when using custom polymer elements within an angular 2 application.

I described the issue here:
http://stackoverflow.com/questions/34779175/polymer-elements-within-angular-2-component

Any ideas on how to fix this would be very much appreciated.

**Comment by ebidel** [comment]
Let's keep the conversation on SO. The issue tracker is not a place for debugging apps :)
