### ISSUE TITLE
<array-selector> not firing updates or observers on select

### ISSUE THREAD

**Issue by jshcrowthe** [Polymer/polymer#3293]
In working with `iron-list` I discovered what I believe to be an issue with `array-selector`.

When the value of `selected` is changed (a user selects/deselects items) the `<property>`-changed event as well as any observers associated with the property are not firing.

The example provided here is using `iron-list` however if you put an observer on `iron-list`'s `selectedItems` prop you will see the same behavior.

https://jsfiddle.net/jshcrowthe/L936q2mq/4/

**Comment by arthurevans** [comment]
In multi-select mode, `selectedItems` is going to be an Array, not an object. And if you want to listen for change events when items are added or removed from it, you'll need to register an observer like this:

      observers: [
        '_logChange(selected.*)'
      ],
      _logChange: function(changeRecord) {
         ... 
      }

You'll need to change the observer and check the change record's `path` property to  filter out the changes you're interested in.

**Comment by jshcrowthe** [comment]
@arthurevans Thanks for getting back to me so quick!

So if I am understanding correctly because it's an Array in a property declared type `Object` there aren't any notifications that fire when any of the Array helpers are used then?

**Comment by arthurevans** [comment]
@jshcrowthe No, the declaration of `Object` doesn't really have any effect here. It's only used when you set a property from markup with a string literal. 

You're not getting notifications on a simple property observer because the value of `selected` isn't changing—it's still the same old array, it's just getting new items added and removed. That's why you need an array observer or deep property observer.

**Comment by jshcrowthe** [comment]
Wow, in tinkering with this I realized I totally misunderstood what the array mutation methods are doing, I was under the impression that they also notified those listening on an array that the array had changed.

Is this intentional behavior? Or is this something that could be changed? It seems like the array having an item added to it changes the array.
