### ISSUE TITLE
window.Polymer is not available in WebComponentsReady event listener

### ISSUE THREAD

**Issue by aditya1** [Polymer/polymer#3294]
Hi Guys,

I'm relatively new to Polymer development. I'm trying to load write a unit test using Jasmin to test my polymer component. I do not have any html file for this test, only I've is JS file and trying to import Polymer library from JS. Following is the code I've written for it. 

        var head = document.getElementsByTagName('head')[0];
    var script = document.createElement('script');
    
    script.type = 'text/javascript';
    script.src = '../../Polymer-1.1.4/webcomponents-lite.js';
    head.appendChild(script);
    var link = document.createElement('link');
    link.rel = 'import';
    link.href ='../../Polymer-1.1.4/polymer.html';
    head.appendChild(link);
    
    var link1 = document.createElement('link');
    link1.rel = 'import';
    link1.href = '../../SMAProcSP/sp-base/sp-base.html';
    head.appendChild(link1);
    if(window.Polymer){
		console.log("Polymer is loaded");
		Polymer.Base.importHref('../../SMAProcWebAuthoringUIUtils/cmp-process-composer-tester/cmp-process-composer-tester.html',function(){
			var pcTester = document.createElement('cmp-process-composer-tester');
			pcTester.addEventListener('cmptesterattached',function(){
				
				
			});
		});
	}
	else{
		window.addEventListener('WebComponentsReady', function(){
			console.log("Now Polymer is loaded");
			window.Polymer.Base.importHref('../../SMAProcWebAuthoringUIUtils/cmp-process-composer-tester/cmp-process-composer-tester.html',function(){
				var pcTester = document.createElement('cmp-process-composer-tester');
				pcTester.addEventListener('cmptesterattached',function(){
					
					
				});
			});
			
		});
	}

Whenever I'm trying to call Polymer.Base or window.Polymer.Base I always get as "Uncaught ReferenceError: Polymer is not defined" or undefined. Your help will be much appreciated.

**Comment by ebidel** [comment]
Seems like a race condition with loading polymer.html async. You could setup a listener on the import the loads polymer:

    link.href ='../../Polymer-1.1.4/polymer.html';
    link.onload = function () {...}

But is there a reason you're loading things in js? It's much easier to use a declarative `<script>` tag and `<link rel=import>` on the page. That way, you're also guaranteed loading order.
