### ISSUE TITLE
Paper elements are not loaded correctly in Chrome

### ISSUE THREAD

**Issue by TitanNano** [Polymer/polymer#3297]
Hello,

When I'm cloning my DOM from an template element, the paper elements are not correctly loaded in Chrome. They work just fine in Firefox though...
I don't get any errors from Polymer in the browser console, so I don't know what exactly is the problem. 

I have an example here: http://titannano.github.io/VocabularyTrainer/
It works well in Firefox, but not with Chrome. If anyone wants to test this you will have to use Chrome Canary since the code requires Proxies.

I hope this maybe can get fixed.

**Comment by ebidel** [comment]
You have a ton of imports that are never loaded/registered:

<img width="1146" alt="screen shot 2016-01-15 at 9 03 51 am" src="https://cloud.githubusercontent.com/assets/238208/12359383/fe08bfb2-bb66-11e5-8c34-aaf0dd2cb40f.png">

I'm not sure what `rel="import-async"` is but you should change them to `rel="import"`. If you want the import be async, add the `async` attribute.

<img width="704" alt="screen shot 2016-01-15 at 9 04 09 am" src="https://cloud.githubusercontent.com/assets/238208/12359381/faa3ff76-bb66-11e5-9d28-96efb37a5789.png">

**Comment by TitanNano** [comment]
the `import-async` is there so polymer won't load them. I did this because the paper spinner wouldn't render before all the elements are loaded. This way I wait until the ready event fires

```JavaScript
if (window.Polymer && window.Polymer.ImportStatus._ready) {
    Polymer.ImportStatus.whenReady(bootstrap);
} else {
    window.addEventListener('WebComponentsReady', bootstrap);
}
```
and then replace the other elements
```JavaScript
    [].slice.apply(document.querySelectorAll('link[rel="import-async"]')).forEach(element => {
        let node = document.createElement('link');

        node.setAttribute('rel', 'import');
        node.setAttribute('href', element.href);

        queue.push(new Promise(success => node.addEventListener('load', success)));

        element.parentNode.replaceChild(node, element);
    });
```

**Comment by ebidel** [comment]
Love the ES6 :) You could also put the rest of the imports in a rest.html and load that separately from the spinner.

FWIW, I ran https://gist.github.com/ebidel/cea24a0c4fdcda8f8af2 and still same unregistered elements. This was after the page was fully loaded and the spinner was gone.

**Comment by TitanNano** [comment]
I don't get the unregistered errors at all. Do I need to enable any options in chrome to see them?

**Comment by TitanNano** [comment]
I disable the spinner as soon as all the elements are loaded. In previous test everything worked fine, but when I put the HTML into the template tags it stopped working in chrome.

```JavaScript
        let node = template.content.cloneNode(true);
```
for some reason this doesn't work in chrome but in Firefox with just the web-components shim.

**Comment by ebidel** [comment]
> when I put the HTML into the template tags

Can you provide an example? Sounds like a difference between native imports and the polyfill?

**Comment by TitanNano** [comment]
```HTML
        <template id="word-editor" replace>
            <paper-header-panel flex mode="waterfall" bind-class="{ style-xs-hide: hideEditor() }">
                <div class="paper-header style-primary">
                    <paper-icon-button class="style-xs-show" bind-events="{click:closeEditor}" icon="icons:chevron-left"></paper-icon-button>
                    <span class="style-header-title">Word Editor</span>
                </div>
                <div layout align-items="center center" class="content">
                    <div flex="50" bind-display="hasItem()">
                        <paper-input type="text" label="{{profile.targetLang}}" bind-value="{{item.text}}"></paper-input>
                        <paper-input type="text" label="{{profile.userLang}}" bind-value="{{item.translation}}"></paper-input>
                        <paper-input type="text" label="Pronounciation" bind-value="{{item.pronounciation}}"></paper-input>
                        <paper-input type="text" label="Priority" bind-value="{{item.priority}}"></paper-input>
                        <div class="form-item" layout>
                            <label>Accuracy: </label>
                            <paper-progress bind-value="item.getAccuracy()" flex></paper-progress>
                        </div>
                        <div class="form-item" layout>
                            <label>{{getRemainingTests()}} correct tests remaining for full accuracy</label>
                        </div>
                        <div class="style-form-actions" layout align-items="end start">
                            <paper-button class="style-warn" bind-enabled="checkNew()" bind-events="{click:removeItem}">Remove</paper-button>
                        </div>
                    </div>
                </div>
        </template>
```
this is the main view in a template tag.

as soon as all the elements are loaded I register the template element in my data binding engine

```JavaScript
    /** @type {ScopePrototype} */
    let { scope } = DataBinding.makeTemplate('#main-view', {
        profile : null,

        $methods : {
            manageWords : function(){
                UiPage.activate('word-manager');
            },

            trainWords : function(){
                UiPage.activate('word-trainer');
            },

            reset : function(){
                this.profile.progress = 0;

                this.profile.wordList.forEach(word => {
                    word.tests = 0;
                    word.right = 0;
                    word.priority = 0;
                });

                Profile.save(this.profile);
            }
        }
    });
```

which then clones the template content, processes all my bindings and replaces the template tag with the final DOM sub-tree

```javascript
let node = template.content.cloneNode(true);
[...]
template.parentNode.replaceChild(node, template);
```

**Comment by ebidel** [comment]
Try using `document.importNode(t.content, true);` instead of `cloneNode`. The former is needed because  custom elements in templates are not upgraded. `importNode` will bring in the definitions.

Example: http://jsbin.com/kuhucoropi/edit?html,output

**Comment by TitanNano** [comment]
thanks a lot! now it works 😄:+1:
How is that with the `rest.html` meant? 
I put it like this:
```HTML
    <link rel="import" href="components/paper-spinner/paper-spinner.html">
    <link rel="import" href="rest.html">
```
and the rest.html
```html
<link rel="import" href="components/paper-header-panel/paper-header-panel.html">
<link rel="import" href="components/paper-progress/paper-progress.html">
<link rel="import" href="components/paper-button/paper-button.html">
<link rel="import" href="components/paper-icon-button/paper-icon-button.html">
<link rel="import" href="components/paper-input/all-imports.html">
<link rel="import" href="components/paper-listbox/paper-listbox.html">
<link rel="import" href="components/paper-item/all-imports.html">
<link rel="import" href="components/iron-icons/iron-icons.html">
<link rel="import" href="components/paper-tooltip/paper-tooltip.html">
```
but this doesn't change that all imports need to be done before any custom element is rendered and so the spinner doesn't show up until everything is loaded.
