### ISSUE TITLE
where are the gulpfile.js?

### ISSUE THREAD

**Issue by jairorudas** [Polymer/polymer#3298]
Good morning, 

Where I find the gulpfile in the polymer-stater-kit ?

Thank!

**Comment by addyosmani** [comment]
This is the file you're looking for: https://github.com/PolymerElements/polymer-starter-kit/blob/master/gulpfile.js

For Polymer Starter Kit issues or questions, please note that https://github.com/PolymerElements/polymer-starter-kit/ is the repo you're after.
