### ISSUE TITLE
Changes to sub-property bindings do notify parent object

### ISSUE THREAD

**Issue by kbenjamin** [Polymer/polymer#3303]
When making changes to a bound sub-property, the sub-property is correctly notified. The containing object, however, is not. 

As a work-around, cloning the object and calling `this.set('obj', clone)` works. 

I've build a simple test case here: http://jsbin.com/labayexova/edit?html,console,output

It's the lack of notification that's the issue.

Am I missing something here? Shouldn't this 'just work'?

**Comment by kaste** [comment]
This is intended behavior: You either subscribe to `item` or `item.*`. So instead of `item.property = {{compute(item)}}` you should use `item.property = {{compute(item.*)}}`. 

http://jsbin.com/pevetihaya/1/edit?html,console,output

**Comment by kbenjamin** [comment]
Then how do you do something like a form with fields bound to a selected
item from iron-list or another object?

In my example, I purposely bound to `item` to show that it doesn't get
notification when a sub property changes.

In a real world example, I am binding via node attributes an object i.e.
`<my-el selected="{{item}}">`. I tried `item.*` but that doesn't work at
all.

I can post a more complex example, if needed.

Thanks for your help, Ken

**Comment by kaste** [comment]
But these are comletely different things: `{{compute(item)}}` is a computed property. And: `<my-el selected="{{item}}">` is the usual annotation/binding. Inside `my-el` you get notified about `item.*` changes via an observer.

**Comment by kbenjamin** [comment]
Actually, you don't, which is why I posted this in the first place. As for
being different, why would they be, at least so far as both the dom
property and the internal reference to it both need notification?

**Comment by kaste** [comment]
Look at: http://jsbin.com/pevetihaya/2/edit?html,console,output

**Comment by kbenjamin** [comment]
Sorry, my JSBin wasn't saved so you have a lot of junk from earlier tests. I've taken what you're saying about computed properties and ran a test case which does work, as you say:
http://jsbin.com/jozinoboli/1/edit?html,console,output

I'm going to have to back and figure out why in my actual app, which has slightly more complex linkages, I'm not getting the bindings to notify. I've been working hard on it, so it's not for a lack of trying that I've come to post here.

I'm thinking that, perhaps, it might be related to https://github.com/Polymer/polymer/issues/3300.

Let me look this over tomorrow and I'll repost and / or close this item then.

Thanks again, Ken

**Comment by kbenjamin** [comment]
This was my issue, not a bug, so thank you for all your help.

Please correct me if I'm wrong below but here are my lessons learned and, perhaps, tips for future documentation improvements re. data binding:

1. Bound properties are references or pointers to the same Object, i.e.
```
<my-widget item="{{hotitem}}"></my-widget>
<your-widget selected="{{hotitem}}></yourwidget>
```
`hotitem`, `item`, and `selected` all point to the _same_ Object unless you mess up this next point...

2. Objects must only have their `value` set once, i.e.
Either set the value of `item` _or_ set the value of `selected`. Not both. If you set both, you get two Objects, not one, and the binding (pointer) which is `hotitem` will only point to one of them and not the other.

3. `<array-selector>` does not update the array when the selected object changes. You must use the Polymer Array methods in an `observer(s)` function.
(This would be a nice feature to have and would save having to do a find and splice externally.)
