### ISSUE TITLE
:host selectors work differently under Shadow DOM and shady DOM

### ISSUE THREAD

**Issue by mgiuffrida** [Polymer/polymer#3312]
CSS selectors like `:host.className` don't seem to work under shadow DOM in Chrome, but do work under shady DOM.

Conversely, `:host-context(:host.className)` doesn't work under shady DOM, but does work under shadow DOM.
- `:host.green { color: green; }`
  -  Works in shady DOM: http://jsfiddle.net/mgiuffrida/whL7n62m/
  - Doesn't work in shadow DOM: http://jsfiddle.net/mgiuffrida/ym39fs8x/
- `:host-context(:host.green) { color: green; }`
  - Doesn't work in shady DOM: http://jsfiddle.net/mgiuffrida/7o9eq5n1/
  - Works in shadow DOM: http://jsfiddle.net/mgiuffrida/qvswxkmb/

**Comment by azogheb** [comment]
I believe the issue you are having is due to the misplaced selector for ```.green```

See http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/#toc-style-host

"The functional form of ```:host(<selector>)``` allows you to target the host element if it matches a ```<selector>```."

Try 
```:host(.green) { color: green; }```

For ```:host-context(:host.green) { color: green; }``` I do not believe this is valid based on the doc above as "The ```:host-context(<selector>)``` pseudo class matches the host element if it or any of its ancestors matches ```<selector>```."

**Comment by mgiuffrida** [comment]
Thanks @azogheb, you're absolutely right. To the docs repo!

For host-context, I would then expect `:host-context(:host(.green))` to work, but it doesn't. Still, it would be redundant so it doesn't really matter, because I can achieve the same result just by using `:host(.green)`. The fact that the seemingly nonsensical `:host-context(:host.green)` works at all in shadow DOM may just be a fluke.

**Comment by zoechi** [comment]
What is `:host-context(:host.green)` supposed to be doing? I don't think this is a valid selector.

**Comment by mgiuffrida** [comment]
> What is `:host-context(:host.green)` supposed to be doing? I don't think this is a valid selector.

Yes, it's weird. I was just trying to find a selector for "the current element if class=green" and it happened to work in shadow DOM.

`:host(.green)` is the proper format.

**Comment by azogheb** [comment]
Awesome. Seems to have worked out! @mgiuffrida please feel free to go ahead and close this issue if you feel it has been resolved

**Comment by mgiuffrida** [comment]
I've seen owners move bugs to the docs repo before. I think that's what should happen here, since we clearly need to add an example to the docs.

@azakus could you move this?

**Comment by equinusocio** [comment]
On ShadowDOM v1 this doesn't work (it works on ShadyDOM)

```css
:host-context(.GreatParent) :host {
  /* ... */
}

```

**Comment by TimvdLippe** [comment]
http://jsbin.com/zujozenaxo/edit?html,output appears to be working in shadow dom (black, red, blue) In shady dom, the host-context does not appear to be working. This seems to be as a result of https://github.com/webcomponents/shadycss/issues/74#issuecomment-291350193
