### ISSUE TITLE
Compound bindings' behavior for undefined is inconvenient

### ISSUE THREAD

**Issue by tommie** [Polymer/polymer#3315]
From the docs, introduced in #2554:

> Compound bindings are re-evaluated whenever the value of any of the individual bindings changes. Undefined values are interpolated as empty strings.

This means two different input types result in an empty string (`undefined` and ""). It would be more useful if

``` html
<img src$="https://www.example.com/profiles/{{userId}}.jpg">
```

was equivalent to

``` html
<img src$='{{concat("https://www.example.com/profiles/", userId, ".jpg")}}'>
```

for a reasonable interpretation of `concat`. In this case, the whole `src` will be `undefined` until all dependents are defined, as indicated in the docs:

> The computing function is not called until all dependent properties are defined (`!=undefined`).

This would avoid the need for a computing function in the common string concatenation case and make the use more type-safe.

**Comment by miztroh** [comment]
While your suggestion would certainly be convenient for some, I don't think it's consistent with how the databinding system is set up.  You can now have multiple, separate bindings within attributes, textContent, etc.

```<div>[[foo]] [[bar]]</div>``` is not a compound binding
```<div>[[concat(foo, bar)]]</div>``` is a compound binding

It's possible that some authors may want ``foo`` to display, even if ``bar`` is ``undefined``.

However, you could avoid the need for a ``concat`` function like so:

```
<template is="dom-if" if="[[userId]]">
	<img src$="https://www.example.com/profiles/[[userId]].jpg">
</template>
```

**Comment by tommie** [comment]
Sorry, I was unclear. I'd only do this for attributes, which have a concept of types since they map to JS properties under the hood. It makes less sense for CDATA since that will be converted to text regardless. So I agree about your `<div>` case.

The `dom-if` solution is even more inconvenient than `concat` if there is more than one parameter since we can't do `&&` expressions in data bindings anymore.

**Comment by miztroh** [comment]
Yeah, I'd just put a concat function in a behavior that you share across any elements where it's needed.  Here's one I use all the time.

```
MIZTROH = window.MIZTROH || {};

MIZTROH.StringBehavior = {
	_join: function (by) {
		return Array.prototype.splice.call(arguments, 1).join(by);
	},
	_split: function (by, string) {
		return string.split(by);
	}
};
```

**Comment by tommie** [comment]
Yeah, that's a better way. Maybe we could even get that as a "feature" rather than behavior upstream since it's pretty common?

I realize that `class$="static {{dynamic}} {{dynamic2}}"` is a degenerate case where the current behavior makes as much sense as in the CDATA case. So one size does not fit all. Could be configurable per attribute, but that would just makes the rules complicated.

**Comment by TimvdLippe** [comment]
This is a deliberate decision in the data-binding system, to make data propagation as intuitive as possible with certain trade-offs. You can implement the behavior you want for these use-cases by using a computed method like @miztroh pointed out.
