### ISSUE TITLE
Array splicing and dom-repeat lead to wrong path in deep property observers

### ISSUE THREAD

**Issue by robdodson** [Polymer/polymer#3316]
Copied over from polymer-dev mailing list.

> When adding an element in array, using splice method, and then change a subproperty from the added item, the path from array observation is not the correct one.

[Example fiddle](https://jsfiddle.net/simona_butnaru/zfwewthr/5/)

I would expect the last value logged by `dataChanged` would be `persons.2.name` but it's `persons.11.name`

**Comment by kaycebasques** [comment]
I think I documented this recently but the change is not live yet. What the user is seeing is intended behavior. See --> https://github.com/Polymer/docs/pull/1457/files#diff-07936cc3163b32c7b2a4f859ae877754R550

**Comment by arthurevans** [comment]
I think this is a dup of #2470?

**Comment by kaste** [comment]
Well, it should not log `persons.11.name` but `persons.#11.name`? `#` denoting it's not an index you can simply work with. Otherwise it's of course a dup.

**Comment by robdodson** [comment]
Yeah it's a dup of #2470, same user and same jsfiddle. Let's continue the discussion over there.
