### ISSUE TITLE
Polymer fails to instantiate elements defined as ES6 classes.

### ISSUE THREAD

**Issue by Cu3PO42** [Polymer/polymer#3320]
I am currently migrating an application I'm writing to ES6 completely, since it runs in Electron and with the update to v0.36 that is now based on Chrome 47, which natively supports a lot of ES6 features - specifically classes. I use TypeScript and PolymerTS to write my elements, which always worked fine up till now. However Polymer doesn't seem to be liking ES6 classes. Upon application start I get a lot of errors.

```
Uncaught TypeError: Class constructors cannot be invoked without 'new'DomApi._addNode @ polymer-mini.html:446
bv-dumper.js:31 Uncaught TypeError: Class constructors cannot be invoked without 'new' DomApi._addNode @ polymer-mini.html:446
file-input.js:22 Uncaught TypeError: Class constructors cannot be invoked without 'new' DomApi._addNode @ polymer-mini.html:446
pkm-list.js:39 Uncaught TypeError: Class constructors cannot be invoked without 'new' DomApi._addNode @ polymer-mini.html:446
save-dumper.js:31 Uncaught TypeError: Class constructors cannot be invoked without 'new' DomApi._addNode @ polymer-mini.html:446
file-input.js:22 Uncaught TypeError: Class constructors cannot be invoked without 'new' DomApi._addNode @ polymer-mini.html:446
pkm-list.js:39 Uncaught TypeError: Class constructors cannot be invoked without 'new' DomApi._addNode @ polymer-mini.html:446
keysav-options.js:70 Uncaught TypeError: Class constructors cannot be invoked without 'new' DomApi._addNode @ polymer-mini.html:446
key-breaker.js:23 Uncaught TypeError: Class constructors cannot be invoked without 'new' DomApi._addNode @ polymer-mini.html:446
3 file-input.js:22 Uncaught TypeError: Class constructors cannot be invoked without 'new' DomApi._addNode @ polymer-mini.html:446
keysav-about.js:13 Uncaught TypeError: Class constructors cannot be invoked without 'new' DomApi._addNode @ polymer-mini.html:446
external-link.js:15 Uncaught TypeError: Class constructors cannot be invoked without 'new'
```

I presume that it worked fine before I migrated to ES6 since the compiled ES5 classes didn't enforce 'new'. I would really rather not add Babel to compile to ES5 for the added complexity and since, to be honest, seems unnecessary to me. My code can be found [here](https://github.com/Cu3PO42/KeySAVe/tree/migrate-es7). My dependencies are up to date.

**Comment by samccone** [comment]
@Cu3PO42 would you mind creating a reduced test case of the bug for us to look at? (preferably in vanilla es6 js)

Here is a nice boilerplate case to use https://jsfiddle.net/Laq60ge0/

Thanks fro reporting this :sparkles:

**Comment by Cu3PO42** [comment]
I will try to create a minimal example. Currently I can't get it to work, however. PolymerTS does a lot of magic copying attributes around, I will reproduce that as best as I can and report back.

**Comment by samccone** [comment]
@Cu3PO42 perhaps if you took the compiled JS for your broken example and pasted it into the fiddle that would be a good place to start. :)

**Comment by Cu3PO42** [comment]
[This](https://jsfiddle.net/wotzkrna/1/) is the core of what PolymerTS does with the class prototype. Currently the fiddle crashes in the `copyMembers` function for a reason not apparent to me. I will try to look into it tomorrow more.

**Comment by samccone** [comment]
@Cu3PO42 I wonder if a better place to open this bug would be here: https://github.com/nippur72/PolymerTS

**Comment by ebidel** [comment]
Check out https://www.polymer-project.org/1.0/articles/es6.html#defining-polymer-elements-from-a-class. There are a couple of issues with how you've defined your class and how it's passed to `Polymer()`.

- there's no need to `extend HTMLElement`. Polymer does that for you
- `is` should be defined in `beforeRegister()`
- you're also using `Polymer/paper-slider` (which is the 0.5 version). You want `PolymerElements/paper-slider` in your fiddle.

Works (I removed copyMembers though): http://jsbin.com/minezus/edit?html,output

**Comment by Cu3PO42** [comment]
@samccone I didn't think so, since the error was thrown from Polymer and looked like a possible collision with ES6 classes requiring new.

@ebidel Concerning the slider, I didn't even notice that was in there. I just modified the fiddle @samccone provided. I still have to wonder, though, is doing something like `copyMembers` plainly wrong or just unnecessary? If the latter should be the case, I really can't explain the behavior I am getting currently.

**Comment by Cu3PO42** [comment]
In writing a new library to assist me with writing Polymer elements in TypeScript I now figured out what the problem is. Since Polymer does not call the constructor, PolymerTS does something like this:

```javascript
        if (klass.prototype.factoryImpl !== undefined)
            throw new Error("Do not use factoryImpl(), use constructor() instead");
        var cachedFactoryImplArgs = [];
        klass.prototype.factoryImpl = function() {
            cachedFactoryImplArgs = arguments;
        }
        if (klass.prototype.attached !== undefined) {
            var attached = klass.prototype.attached;
            klass.prototype.attached = function() {
                klass.apply(this, cachedFactoryImplArgs);
                attached.call(this);
            };
        } else {
            klass.prototype.attached = function() {
                console.log(klass.toString());
                klass.apply(this, cachedFactoryImplArgs);
            };
        }
```

That is, it overwrites `attached` and calls the constructor from there. Now with ES5 "classes" that works fine, since you can just `apply` that function. However with native classes that throws the error I was getting. Unfortunately there does not seem to be a way to accomplish this behavior without breaking under ES6.
