### ISSUE TITLE
dom-repeat missing sort fn is a very unfriendly error message

### ISSUE THREAD

**Issue by samccone** [Polymer/polymer#3327]
When you are moving around code and refactoring (or just making a typo) if you mess up the name that you set for the `sort` attribute for you `dom-repeat` directive.. the error message is pretty confusing

``` js
Polymer({
  //...
  fooz: function() {} 
 // ^ incorrect method name
});
```

``` html
<template is="dom-repeat" sort="foo" items="[[things]]">
</template>
```

![screen shot 2016-01-23 at 10 03 48 am](https://cloud.githubusercontent.com/assets/883126/12531789/a44cc934-c1b8-11e5-91a2-ea7b2ded6545.png)

---

Instead of the hard failure here, I think that we should throw a nice user friendly `console.warn` :warning: 

Thanks for taking the time to read this issue, I am more than willing to open the patch :sparkles:  for this but I wanted to first elicit feedback as to not waste anyones time. :clock10:

**Comment by TimvdLippe** [comment]
Yes a more friendly warning pre-emptively would be a lot better. Recently #2657 was merged which solved a very similar problem. Maybe it is a good idea to broaden this issue by looking at all "string-lookup functions" and create developer friendly error messages?
