### ISSUE TITLE
I can only add a function by name to the prototype listeners and behaviors

### ISSUE THREAD

**Issue by eeid26** [Polymer/polymer#3330]
To be able to add function (not name) in the listeners object helps.

This pull request tries to solve this issue.
https://github.com/Polymer/polymer/pull/3329

**Comment by TimvdLippe** [comment]
Maybe I am missing something, but in what situation would you prefer `'disabled-changed': proto._disabledChanged` over `'disabled-changed': '_disabledChanged'`? If you want a method from a specific `Behavior`, this behavior should be added last in the `this.behaviors` array.

**Comment by eeid26** [comment]
The change is to allow the calls to propagate to the element prototype AND any behaviour that has _disabledChanged registered with their listener. 

With the current implementation, only one listener function can be called when i.e. disabled-changed is fired. With the new change more than one listener can be registered in different behaviours or the prototype and they all get called unless the higher listener calls  event.stopImmediatePropagation();

**Comment by TimvdLippe** [comment]
There is #3284 that fixes #1593 which allows for defining multiple listeners in an `on-*` method. This could be broadened to also include the `listeners` object (if this was not already working, I need to check that out). Would that also solve your issue?

The only caveat is that the behavior methods should be named differently, but this is in line with inheritance in programming languages.

**Comment by eeid26** [comment]
The change you referenced does not solve the problem I am trying to avoid.

I want to avoid naming my functions in different behaviours as
_disabledChanged_BehaviorOne
_disabledChanged_BehaviorTwo
_disabledChanged_BehaviorThree

I just want to name them all _disabledChanged 

I disagree overridden functions have different names in any programming language inheritance model that I know. They all have the same name.

The difference in this new model from other strongly typed languages is, the overriden function has to call super._disabledChanged() in order for the supertype function to be invoked.

With this change the inheritance model would be an implied call to super.disabledChanged() unless the overriden function (or the higher listener) calls  event.stopImmediatePropagation();

There are no really overriden function here, its just a list of listeners that gets called in the order they are added. They have been added in away to simulate an inheritance model without calling super.
  _

**Comment by TimvdLippe** [comment]
Inheritance in Polymer custom elements is currently not possible, but there is an ongoing effort to discover what is possible there and if it could be added back. I think that would solve the use-case differently, without requiring direct references of functions in the `listeners` object. My 2 cents.

**Comment by eeid26** [comment]
That is why I did not want to use the word "inheritance". You brought it up. The model is really closer to implementing aspects than inheritance in strongly typed languages. You see behaviors could be dynamically added or not to the prototype when the element is constructed.

**Comment by TimvdLippe** [comment]
Closing this issue per https://github.com/Polymer/polymer/pull/3329#issuecomment-321377632 In Polymer 2, you can use the native `this.addEventListener` which takes a function closure.
