### ISSUE TITLE
iron-ajax demo not working

### ISSUE THREAD

**Issue by ryanwtyler** [Polymer/polymer#3335]
I installed the PSK1.1.2 via gulp and bower.  The iron ajax demo doesn't work.  the index.html points to some files that are much further up in the file directory and I get 404s.

**Comment by azakus** [comment]
The demos are written to work on the [Polymer Element Catalog](https://elements.polymer-project.org). You can get the same demo working by using [polyserve](https://www.npmjs.com/package/polyserve) to route the dependencies correctly.

Here's also a working version of the demo from the catalog: https://elements.polymer-project.org/elements/iron-ajax?view=demo:demo/index.html&active=iron-ajax
