### ISSUE TITLE
scopeSubtree duplicates classes on successive runs

### ISSUE THREAD

**Issue by miztroh** [Polymer/polymer#3336]
I've been developing a WYSIWYG editor with undo / redo management.  As part of the setup, I call `this.scopeSubtree(node, true)` where `this` is the editor custom element and `node` is its local DOM `contenteditable` node.  This helps ensure that the editable content is properly scoped for styles.

First, I start with some basic content:
`<p><a href="#">Hello</a>, World!</p>`

The scopeSubtree MutationObserver does its thing and updates the content to this:
`<p class="style-scope wysiwyg-editable"><a href="#" class="style-scope wysiwyg-editable">Hello</a>, World!</p>`

So far, so good.  I keep this version as the first in history and I discard the unscoped version.  However, look at what happens when I make my first edit by selecting this content and bolding it:

`<p class="style-scope wysiwyg-editable style-scope wysiwyg-editable"><b class="style-scope wysiwyg-editable"><a href="#" class="style-scope wysiwyg-editable style-scope wysiwyg-editable style-scope wysiwyg-editable style-scope wysiwyg-editable">Hello</a>, World!</b></p>`

As you can see, the classes `style-scope wysiwyg-editable` are getting applied in an additive fashion, so older nodes have multiple occurences of them.  `scopeSubtree` needs to allow for only one occurrence of each class per node.

**Comment by miztroh** [comment]
Here's a JSBin: http://jsbin.com/kuyirimiti/edit?html,output

**Comment by nazar-pc** [comment]
If you specify second argument as `true` - you need to call it only once on parent element and everything inside will be automatically handled by MutationObserver afterwards. Code itself doesn't have any protection from repeated calls (I've being looking for this a while ago as well).

**Comment by miztroh** [comment]
Already aware of the second argument, as mentioned above.

**Comment by miztroh** [comment]
Ping.

**Comment by n1ywb** [comment]
Can confirm, this behavior is insane

![image](https://cloud.githubusercontent.com/assets/316961/21355768/4199bf28-c69d-11e6-9e6c-61d4a63914a6.png)

**Comment by TimvdLippe** [comment]
This should be fixed in ShadyCSS: http://jsbin.com/jedorakoxu/edit?html,console,output working in both Firefox and Chrome.
