### ISSUE TITLE
Use native css custom properties when available

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#3339]
Currently, even when native css custom properties are available, Polymer still shims css custom properties. We cannot simply turn off the shimming in this case because Polymer uses an unimplemented but proposed native feature `@apply`.

We'll need to shim `@apply` as css custom properties to be able to use native css custom properties.

**Comment by mgiuffrida** [comment]
Great, glad to see this is high priority! :+1:

**Comment by abdonrd** [comment]
:+1:

**Comment by klebba** [comment]
:+1:

**Comment by Jamtis** [comment]
:+1:

**Comment by ebidel** [comment]
Any word on this @sorvell? I think some of this has landed?

**Comment by ebidel** [comment]
This landed as an opt-in features in 1.6.0!

https://www.polymer-project.org/1.0/docs/release-notes#v-1-6-0

**Comment by mgiuffrida** [comment]
It does have several issues, so buyer beware: #3803 #3800  #3801 #3802  #3806 #3807 (some fixed in master)

**Comment by ebidel** [comment]
Reopening for @sorvell to close when he things this is ready for mass exposure.

**Comment by abdonrd** [comment]
@ebidel ready? :)

**Comment by ebidel** [comment]
Seems like all the open issues are closed.

**Comment by mgiuffrida** [comment]
we switched it on in Chrome WebUI and nothing has caught fire yet

**Comment by abdonrd** [comment]
Nice! 🎉
