### ISSUE TITLE
Default to ShadowDom when using full polyfill

### ISSUE THREAD

**Issue by indolering** [Polymer/polymer#3340]
Switching Polymer to using the ShadowDom currently requires setting a global JS variable (`window.Polymer.dom = 'shadow';`) but the use of the ShadowDom is implied when using the full WebComponents polyfill.  Setting this global variable is also a pain for anyone that is using CSP as it requires maintaining a 2-line JS script and this script must be loaded before anything else.

Instead, Polymer should default to the ShadowDom when the full WebComponents polyfill is loaded.  A data-\* attribute on the WebComponents script tag would also work.

**Comment by indolering** [comment]
Cross reference #1887.

**Comment by klebba** [comment]
:+1: Ideally Polymer would default to native ShadowDOM with no polyfills loaded, but it _always_ defaults to shady DOM right now. The WebComponents polyfills have nothing to do with this setting

**Comment by indolering** [comment]
> Ideally Polymer would default to native ShadowDOM with no polyfills loaded, but it always defaults to shady DOM right now.

They will default to the ShadowDOM [once 2 or 3 browsers offer native support](https://github.com/Polymer/polymer/issues/1887#issuecomment-175358707).

> The WebComponents polyfills have nothing to do with this setting

You cannot deploy a Polymer element to a production environment without the WebComponents polyfill.  So, practically speaking, Polymer requires the WebComponents Polyfill.  The `webcomponents-lite.js` polyfill doesn't provide support for the ShadowDom, which is a very good indicator that ShadowDom functionality isn't needed.

But, if someone has concerns about violating layers of abstraction, we could create a switch within the element....

**Comment by klebba** [comment]
> You cannot deploy a Polymer element to a production environment without the WebComponents polyfill.

This is not true. Chrome extensions do not require the polyfills, for example

**Comment by nazar-pc** [comment]
Really :+1: for having Shadow DOM if either native support available or full polyfill is present.
But there is a trick with forthcoming Web Components v1 implementation, which differs from v0 and can (at least potentially) create incompatibilities.

P.S. I'm using Shadow DOM since 0.5 and it works fine for me (I'm not including polyfill on page in browsers with native Shadow DOM and have full polyfill otherwise).

**Comment by indolering** [comment]
@klebba this is not the ticket to advocate for enabling the ShadowDOM by default, #1887 is.  

>>You cannot deploy a Polymer element to a production environment without the WebComponents polyfill.

> This is not true. Chrome extensions do not require the polyfills, for example

By "production" I meant production websites, not specialty runtime environments : )

**Comment by indolering** [comment]
@klebba Are you against using a `data-*` attribute, perhaps on a `<meta>` tag or the Polymer `<link>` tag?  The Polymer devs have made it clear that they won't switch to using the ShadowDOM by default for some time and I'm just trying to make it easier to configure full ShadowDOM support since I will have to support IE11 and Safari 9 for a few years.

**Comment by klebba** [comment]
@indolering 

> By "production" I meant production websites, not specialty runtime environments : )

Intranets are another example where the polyfills aren't necessarily required

I'm not sure what problem you're having with `Polymer.dom = 'shadow'` in your CSP configuration; are you using Vulcanize and Crisper to pack your app? The way I sorted this out was to wrap the `polymer.html` import in another import like `my-polymer.html` and use that everywhere. The ShadowDOM configuration is then always guaranteed to be present and loaded before `polymer.html`

**Comment by indolering** [comment]
> Intranets are another example where the polyfills aren't necessarily required

I get that there are some cases in which the polyfill isn't needed, but the vast majority of users will need the Polyfills for a long time.  That's all I'm saying.

> I'm not sure what problem you're having with Polymer.dom = 'shadow' in your CSP configuration; are you using Vulcanize and Crisper to pack your app? 

How is this different from creating an external JS file and importing that everywhere?  I'm just saying that auto-detection or an HTML attribute would be more ergonomic.

**Comment by azakus** [comment]
Given the vastly different environment created by the ShadowDOM polyfill, I think this change would need a lot of discussion, and might be considered a breaking change (at least of expectations).

**Comment by indolering** [comment]
> Given the vastly different environment created by the ShadowDOM polyfill, I think this change would need a lot of discussion, and might be considered a breaking change (at least of expectations).

Agreed, but we could just tie it to when we switch to ShadowDOM by default for browsers that support ShadowDOM natively.  That's already had plenty of discussion : )

An HTML attribute wouldn't break anything.  But if this is at least a planned feature, I don't think it makes sense to bother with an HTML attribute.

**Comment by TimvdLippe** [comment]
Polymer 2 now has shadow dom by default, if the polyfill is not loaded: https://github.com/Polymer/polymer/blob/44fd1eaa6a4fb3d797155ea9c9b286f7bcca6dbb/lib/utils/settings.html#L25
