### ISSUE TITLE
[1.0] Suitable polyfills for IE9 

### ISSUE THREAD

**Issue by luttfioz** [Polymer/polymer#3342]
Hi,
Can we use polymer for IE9? Is there any polyfills for that?
Thanks

**Comment by arturparkhisenko** [comment]
@luttfioz look at [this(webcomponentsjs#browser-support)](https://github.com/WebComponents/webcomponentsjs#browser-support)

**Comment by luttfioz** [comment]
@arturparkhisenko Is webcomponentjs the only polyfill for polymer?

**Comment by arturparkhisenko** [comment]
@luttfioz dunno, never saw anything like this and all current choises doesnt support ie < 10, i mean x-tag and bosonic.

**Comment by azakus** [comment]
Polymer is not going to officially support IE 9.
That said, if you don't use the ShadowDOM polyfill, it _might_ just work.
I think the biggest problems would be styling of elements, as flexbox is not implemented in IE 9.
