### ISSUE TITLE
Do not require notifyPath or set to update subproperties of Objects

### ISSUE THREAD

**Issue by azakus** [Polymer/polymer#3343]
Based on user feeback, a confusing and cumbersome part of the databinding system is that changing data-bound objects' subproperties require using the `set` api, or duplicating the path to the subproperty with `notifyPath`.

Instead, we should disable identity checking for objects and always dirty check subproperties for them to allow users to either set the root object directly, or call `notifyPath`, in an easier fashion.

**Comment by MeTaNoV** [comment]
+1

**Comment by TimvdLippe** [comment]
This could be added quite easily in #3238 in [the property dirty check method](https://github.com/Polymer/polymer/pull/3238/files#diff-c8d866d6e3371fd7ff2315aab52c74c6R81)

**Comment by TimvdLippe** [comment]
This has shipped in the mixing [MutableData](https://www.polymer-project.org/2.0/docs/api/mixins/Polymer.MutableData)
