### ISSUE TITLE
Add support for element inheritance

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#3345]
Here's a strawman:

```
Polymer({
  is: 'x-base'
});

Polymer({
  is: 'x-foo',
  extends: 'x-base'
});
```

Issues: 
- this will need to be integrated with Polymer's behavior system.
- we'll want to expose a way to modify/merge super/subclass templates.

**Comment by samccone** [comment]
##### Past work xref

https://github.com/Polymer/polymer/issues/2510
https://github.com/Polymer/polymer/pull/2604
https://github.com/Polymer/polymer/issues/2520
https://github.com/Polymer/polymer/issues/2280

**Comment by TimvdLippe** [comment]
Project issue with more discussion and thoughts: https://github.com/Polymer/project/issues/12

**Comment by abdonrd** [comment]
Any news about this?

**Comment by HappyZone** [comment]
+1

**Comment by TimvdLippe** [comment]
#3577 has been opened for quite a while. Could you provide any update when we can expect this feature on landing?

**Comment by mpsh** [comment]
When we can expect this feature?

**Comment by TimvdLippe** [comment]
I think with the class-based native inheritance custom elements v1 syntax we can close this issue.

**Comment by TimvdLippe** [comment]
Closing per above comment.
