### ISSUE TITLE
Bound input values are reset when you hit the back button in Safari... 

### ISSUE THREAD

**Issue by zboralski** [Polymer/polymer#3346]
I thought it was a paper-input [issue](https://github.com/PolymerElements/paper-input/issues/309#issuecomment-176497246)... but native input and iron-input are also affected...

This issue seems to be limited to the Mobile Safari and OS X's Safari user agents. 

```html
      <paper-input id="input" name="search" value="{{q}}" autocorrect="off" autocomplete="off"
      icon="search" autocapitalize="off" on-button-click="performSearch"></paper-input>
```

If I navigate away from the page and hit back... the value of the input field is reset. If I inspect my element my `q` property is still set correctly.

Here is a good way to reproduce the issue: 

Navigate to `https://elements.polymer-project.org/browse?q=test`

The input field is set to `test`

![screen shot 2016-01-29 at 08 22 15](https://cloud.githubusercontent.com/assets/104316/12670572/6e76f8e0-c661-11e5-9f15-1d5b639bcc31.png)

Now open the console and navigate away from the page :

```js
window.location.href = "https://google.com"
```
Hit the back button .... the bound property is still set to 'test' as you can see :

![screen shot 2016-01-29 at 08 21 20](https://cloud.githubusercontent.com/assets/104316/12670549/4d3de148-c661-11e5-8f89-283f5568bb79.png)

The input field isn't set. 

I think this is a polymer issue... Other sites are not affected (or maybe they implemented a workaround): 

Navigate to `https://github.com/polymer/?utf8=✓&query=test`

Hit the pricing link in the bottom right corner... then hit the back button and the input field will still be set to 'test'

**Comment by zboralski** [comment]
Some clarifications:

I tried intercepting the pageshow invest to set the input value back to 'test' ... but it has no effect because the input value is still set correctly :

```js
app.$.searchBar.q -> test
app.$.searchBar.$.input.value -> test
```

The input field just won't display its value...  I really don't understand..

**Comment by zboralski** [comment]
I found a really ugly workaround... 

```js
      ready: function() {
        window.onpageshow = function(event) {
          var t = this.q;
          this.q = '';
          if (event.persisted) {
            setTimeout(function() {
              this.q = t;
            }.bind(this), 1);
          }
        }.bind(this);
      },
```

**Comment by azakus** [comment]
If this is a problem with the _native_ input element, then this might be a platform issue in safari.
It looks like Github uses some sort of `defaultValue` hack to reset the value of the input on page change.

However, the right place to implement something like that would be in `iron-input`.
