### ISSUE TITLE
Data binding variable with dash

### ISSUE THREAD

**Issue by joshuajohnson814** [Polymer/polymer#3349]
As of Polymer 1.2.4 I can no longer data bind to a variable name with a dash in it.

`selected-family="{{ styles.h1.font-family }}"`

When I debug the literal value of selectedFamily is "{{styles.h1.font-family}}". This was working in 1.2.3.

**Comment by bpinney** [comment]
I'm also having this issue, I have a bunch of hyphenated data bindings that no longer work.
