### ISSUE TITLE
dom-if (in restamp mode) should not forward changes as soon as `if` gets false 

### ISSUE THREAD

**Issue by kaste** [Polymer/polymer#3353]
A completely idiotic example can be found here: http://jsbin.com/tifuciyawo/edit?html,console

B/c of the debounced render, the stamped instance usually gets notified about all changes that happen in the current microtask even if the instance will teardown at the end of the microtask as a result of `render`. 

Low hanging fruit: 

```
_forwardParentProp: function (prop, value) {
  if (this.restamp && !this.if) { return; }
  ...
},
_forwardParentPath: function (path, value) {
  if (this.restamp && !this.if) { return; }
  ...
} 
```

Additionally the effects should be sorted so that child templates (or: effects pointing to a `_parent_...`) are applied at the end.

**Comment by kevinpschaaf** [comment]
Considering this blocked on https://github.com/Polymer/polymer/issues/3343 per comments on https://github.com/Polymer/polymer/pull/3355#issuecomment-179599682
