### ISSUE TITLE
editable-name-tag.html in "quick tour" has incorrect imports (they are correct in the plunker linked code)

### ISSUE THREAD

**Issue by robokyle** [Polymer/polymer#3356]
I've been following the polymer quick tour from scratch in plunker, following the code in the tutorial, not from the plunker links. Couldn't get iron-input to load:
GET http://run.plnkr.co/EkeSvJ2gUlBk4kt9/bower_components/iron-input/iron-input.html 404 (Not Found)
run.plnkr.co/:1 GET http://run.plnkr.co/EkeSvJ2gUlBk4kt9/bower_components/polymer/polymer.html 404 (Not Found)

But discovered that the plunker link from the tutorial contains the correct code.

So this is what should be at the top of the page to make the code work in plunker - 

<link rel="import"
      href="http://www.polymer-project.org/1.0/components/polymer/polymer.html">

<link rel="import"
      href="http://www.polymer-project.org/1.0/components/iron-input/iron-input.html">
      
Very nice tutorial/intro to the concepts, by the way!

**Comment by azakus** [comment]
This issue was moved to Polymer/docs#1536
