### ISSUE TITLE
Use Polymer.dom(element).innerHTML without scoping the subtree

### ISSUE THREAD

**Issue by miztroh** [Polymer/polymer#3357]
In certain contexts like WYSIWYG editors, it would be useful to be able to call ``Polymer.dom(element).innerHTML = html;`` without creating scoping classes on the new HTML.  I don't want to call ``element.innerHTML = html;`` because of Shady DOM considerations.  Is there any way to work around this?

**Comment by azakus** [comment]
You can disable scoping for a given element by setting `this._encapsulateStyle` to `false`

Here's a JSBin example: http://jsbin.com/wequpix/edit?html,output
