### ISSUE TITLE
1.2.4 causes InvalidCharacterError on class$ attributes when using setAttribute

### ISSUE THREAD

**Issue by n4gashi** [Polymer/polymer#3359]
I am currently using `video.js` in a component that I've created at n4gashi/videojs-element.

I've recently ran on this issue where updating to Polymer version 1.2.4 is breaking the video.js code, because videojs is using setAttribute on it's code to replicate attributes on the `<video>` HTML tag.

Here is the InvalidVCharacterError console error : 
<img width="1425" alt="screen shot 2016-02-02 at 10 41 26 am" src="https://cloud.githubusercontent.com/assets/10873860/12760105/9fa5e968-c999-11e5-86b8-77801bd0c34e.png">

Here is the video.js code causing the issue : 

```
Object.getOwnPropertyNames(attrs).forEach(function (attr) {
      // workaround so we don't totally break IE7
      // http://stackoverflow.com/questions/3653444/css-styles-not-applied-on-dynamic-elements-in-internet-explorer-7
      if (attr === 'class') {
        el.className = attrs[attr];
      } else {
        el.setAttribute(attr, attrs[attr]);
      }
    });

```

I wish I had the fix but unfortunately i do not have the time to get my hands dirty right now. Just reporting this cause I feel like it should be compatible with libraries using setAttribute as this is a common method. Even if duplicating attributes may be an edge case, I feel like this is not the only library to do this, so could be cool to fix this.

Thanks !

**Comment by ebidel** [comment]
Did this code work in 1.2.3?

https://github.com/Polymer/polymer/commit/07d8c06 and https://github.com/Polymer/polymer/commit/690838a may be related.

cc @azakus

**Comment by TimvdLippe** [comment]
I am unable to reproduce the issue: http://jsbin.com/quleyuwisi/edit?html,console,output Please reopen this issue if you can provide a JSBin which shows the error.
