### ISSUE TITLE
Bindings not firing for dynamically imported element

### ISSUE THREAD

**Issue by tpluscode** [Polymer/polymer#3360]
Man, that was hard to replicate :sweat:. I'm observing an issue with dynamically imported element when its property is set with binding or code. See [my plunk](https://plnkr.co/edit/CYXrUy7xUcsKkKJzK1S2?p=preview) for an example. 

I have an element, which is loaded dynamically and a property set with an auto-binding template and an additional restamping `dom-if` to demonstrate what happens when the element is added and remove to DOM on subsequent clicks.

However the same problem occurs if only the element in question remains and its property is set like

```` js
document.querySelector('will-load-dynamically').directProp = 'lower case text';
```

As you can see no binding inside the `<will-load-dynamically>` is bound: not the property itself, neither computed property nor observer function.

**Comment by tpluscode** [comment]
Oh I just realized that this problem doesn't occur if I use attribute binding or set attribute value instead instead.

``` html
<will-load-dynamically direct-prop$="{{text}}"></will-load-dynamically>
```

or 

``` js
document.querySelector('will-load-dynamically').setAttribute('direct-prop', 'lower case text');
```

**Comment by TimvdLippe** [comment]
I think this is a dupe of #2653?

**Comment by tpluscode** [comment]
It is indeed.
