### ISSUE TITLE
Add a Polymer setting to default all templates with strip-whitespace

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/polymer#3363]
As a Polymer user, it would be nice to have a global Polymer setting for `strip-whitespace` instead of manually adding `strip-whitespace` to every template element.
If a template has intended white-space, maybe a `no-strip-whitespace` could be added as negation for the global setting.

**Comment by azakus** [comment]
I think the biggest problem here would be understanding when this setting breaks other elements you have imported, because they expected the default behavior.
Still, it seems like a worthy topic for discussion.

**Comment by TimvdLippe** [comment]
By overriding `_parseTemplate` a user can do this themselves now: http://jsbin.com/cidogimofe/edit?html,console,output
