### ISSUE TITLE
<template> doesn't bind to class attribute in Shady DOM

### ISSUE THREAD

**Issue by Saulis** [Polymer/polymer#3364]
Hi!

It seems that when a `<template>` is used without a parent scope, binding a value to `class` attribute doesn't work correctly in Shady DOM. Based on my testing, also the Shadow DOM polyfill works incorrectly. Native Shadow DOM on Chrome **works** perfectly.

As an example,

````html
<body>
  <template is="dom-repeat" items='["foo", "bar"]'>
    <div class$=[[item]] clazz$="[[item]]">[[item]]</div>
  </template>
</body>
````

actually renders:

````html
<div clazz="foo">foo</div>
<div clazz="bar">bar</div>
````

While as:

````html
<body>
  <template is="dom-bind">
    <template is="dom-repeat" items='["foo", "bar"]'>
      <div class$=[[item]] clazz$="[[item]]">[[item]]</div>
    </template>
  </template>
</body>
```` 

renders correctly:

````html
<div class="foo" clazz="foo">foo</div>
<div class="bar" clazz="bar">bar</div>
````

Similarly, any component using templates like `iron-list` fails to render the `class` attribute correctly if it not nested under another component or `dom-bind`:

````html
<body>
  <iron-list items='["foo", "bar"]'>
    <template>
      <div class$=[[item]] clazz$="[[item]]">[[item]]</div>
    </template>
  </iron-list>
</body>
````

I've created a simple jsbin here: http://jsbin.com/mayexiditu/edit?html,output

Tested on Chrome 47, Polymer v1.2.4. (and also v1.0.0, v1.1.0, v1.2.0)

I can manage using a `dom-bind` as a workaround, but any help would be highly appreciated!

p.s. might be related with #2434.

**Comment by azakus** [comment]
Thanks a lot for filing this issue! We'll triage and take a look at it as soon as possible!

**Comment by TimvdLippe** [comment]
I can investigate this issue tomorrow
