### ISSUE TITLE
Low-level features injection

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#3366]
Having https://github.com/Polymer/polymer/pull/2205 and https://github.com/Polymer/polymer/pull/2247 rejected, I'm requesting something to provide low-level injection points to Polymer library in order to allow mentioned features (and definitely others of that kind) to be injected into Polymer globally.

My current Polymer build contains 8 (including those 2 rejected) patches on top of vanilla Polymer. Having to support mentioned patches forever is not fun and including behaviors manually everywhere is not convenient either.

Expected UX is `window.Polymer` to be used not only to specify settings (like forcing Shadow DOM), but also include something that will affect Polymer's internals, like globally applied behaviors.

**Comment by azakus** [comment]
Thanks for filing this.

Currently, Polymer isn't really prepared for deep feature tweaking like you have described. We're discussing ways to internally split up all the library components to have better defined interfaces.

If done right, this could allow for the kinds of tweaks you'd like to make for your applications in a clean way.

**Comment by nazar-pc** [comment]
I was thinking about alternative approach - to fire some event before final setting `window.Polymer`, so that it will be possible to call `Polymer.Base._addFeature()`

**Comment by TimvdLippe** [comment]
The default computed bindings are now possible by creating your custom base class that `extends HTMLElement` and then you extend from that base-class when you define your own element.

The former, to modify the property parsing, is not yet possible. There are a lot of new protected hooks to alter the behavior of creating property effects, but parsing the properties object is still internal: https://github.com/Polymer/polymer/blob/ca1ce19682b0003359090491d7e81a58d26b9a4a/lib/mixins/element-mixin.html#L155
