### ISSUE TITLE
Add support for building versions of Polymer with and without verbose error messages

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#3367]
Right now Polymer includes relatively few error and warning messages. We've instead recommended using [Polylint](https://github.com/PolymerLabs/polylint).

However, [users have requested](https://github.com/Polymer/polymer/pull/2736) a tool-free way to use a development mode of Polymer that produces more verbose warnings and errors. We're open to this idea, but these warnings cannot be included in the production build of Polymer. We need to add support for including or not these errors/warnings in a build and then we can easily make the two versions available.

**Comment by samccone** [comment]
checkout:
https://github.com/mishoo/UglifyJS2 under `drop_console` <--- seems like all we should need right?

**Comment by samccone** [comment]
we could also use conditional compilation if we want a bit more control, simple enough :)

https://github.com/mishoo/UglifyJS2#conditional-compilation
