### ISSUE TITLE
Investigate linters

### ISSUE THREAD

**Issue by azakus** [Polymer/polymer#3368]
We should use some sort of javascript linter on Polymer to make sure we don't ship any weirdo bugs.

However, there are *a lot* of linters, so we need to pick a good one!
Evaluate:

- [x]  eslint (#2600)
- [x]  jshint
- [x] jscs - really more of a code formatter
- [x] xo

**Comment by samccone** [comment]
eslint has the greatest mindshare atm followed by jshint

**Comment by fredj** [comment]
With eslint, you can create shareable config an used it across multiple projects.
There's already an "official" [eslint-config-google](https://www.npmjs.com/package/eslint-config-google) for Google.

**Comment by abdonrd** [comment]
Only Javascript? I think it would be great to have another linter also for HTML and CSS.
But perhaps it fits more with the PaperElements?

**Comment by ebidel** [comment]
+1 eslint. We're using it on all chrome samples now. It serves there
purpose of jscs and jshint.

**Comment by azakus** [comment]
@abdonrd We have [polylint](https://github.com/PolymerLabs/polylint) for linting elements, and I've never found html linters or css linters to ever really be useful (especially with new standards like Custom Elements and CSS Custom Properties).

**Comment by mercmobily** [comment]
My humble 2c: +1 for eslint

**Comment by abdonrd** [comment]
@azakus right! If we improve the polylint maybe is the better option. Thanks!

**Comment by azakus** [comment]
ESLint is the winner. Closing this issue with #3382
