### ISSUE TITLE
Is it possible to load polymer as a <script> instead of a <link> ?

### ISSUE THREAD

**Issue by yattias** [Polymer/polymer#3376]
I have a chrome extension and loading polymer via an html import leads to many complications. Is it possible to load it as a script instead?

**Comment by ebidel** [comment]
We only provide Polymer core as a .html file because it contains DOM/markup as well as script. HTML imports are an ideal delivery tool for that setup.

Can you elaborate on the complications?

**Comment by yattias** [comment]
Of course. 

I am using polymer in a chrome extension. Chrome extensions typically execute javascript in a different context than the host page thus preventing the extension from potentially conflicting with the host page's namespace. Unfortunately as it stands, only javascript can be loaded into a different namespace and not HTML. Not to mention, Chrome extensions prevent the developer from registering custom elements.

Luckily, there is a workaround and that is to dynamically create a ``<link rel="import">`` and inject Polymer as well as my components into the page which leads to another issue being ``Polymer`` is now available in the global namespace and can potentially cause conflicts if the host page has Polymer loaded.

I am currently handling this by obfuscating Polymer but was hoping for a better solution.

**Comment by azakus** [comment]
You can probably accomplish this with [vulcanize](https://www.npmjs.com/package/vulcanize) and [crisper](https://www.npmjs.com/package/crisper)
```
vulcanize polymer.html | crisper -h polymer.build.html -j polymer.build.js
```
I'm not sure that you would need anything in `polymer.build.html`.

We're probably not going to supply a pure js file for 1.x, as it would not fit will with our use of HTML Imports for code loading.

**Comment by yattias** [comment]
Okay cool.

And yes, I am using both at the moment.
