### ISSUE TITLE
Load Polymer on any exiting webpage

### ISSUE THREAD

**Issue by yattias** [Polymer/polymer#3380]
I am developing an extension which uses Polymer. If Polymer exists on the page, things start to break.
I am trying to figure out a solid strategy of loading Polymer in a way that doesn't conflict with the current page's Polymer (if one exists).

I am currently loading Polymer and my components as such:

```
  function loadRes(res) {
    return new Promise(
      function(resolve, reject) {
        var link = document.createElement('link');
        link.setAttribute('rel', 'import');
        link.setAttribute('href', res);
        link.onload = function() {
          resolve(res);
        };
        document.head.appendChild(link);
      });
  }

  loadRes(chrome.extension.getURL("polymer/polymer.html")) 
  .then( loadRes(component1Url)) )
  .then( loadRes(component2Url)) )
  ...
```

In addition, I have a gulp job to obfuscate the names of all custom elements within the extension as such:

```
gulp.task('build:polymer', function(){
  gulp.src(polymer)
    .pipe(replace('Polymer', 'Polymer' + APP_KEY))
    .pipe(replace('dom-module', 'dom-module-' + APP_KEY))
    .pipe(replace('custom-style', 'custom-style-' + APP_KEY))
    .pipe(replace('dom-template', 'dom-template-' + APP_KEY))
    .pipe(replace('dom-repeat', 'dom-repeat-' + APP_KEY))
    .pipe(replace('array-selector', 'array-selector-' + APP_KEY))
    .pipe(replace('dom-if', 'dom-if-' + APP_KEY))
    .pipe(replace('dom-bind', 'dom-bind-' + APP_KEY))
    .pipe(gulp.dest('vendor/polymer'));
});
```

I realize this is ugly but this is a last resort type of solution. The above works in most sites which use polymer but still cause unexpected issues - I suspect due to other stuff being bound to `window`.

Is there a cleaner way of approaching this?

**Comment by azakus** [comment]
Currently I don't think there is a cleaner approach. Custom Elements currently share a global registry, though there are ideas to fix this in the spec (https://github.com/w3c/webcomponents/issues/369, https://github.com/w3c/webcomponents/issues/236, https://github.com/w3c/webcomponents/issues/344).

One change we could make for Polymer (in a semver-major release) would be to separate the Polymer provided custom elements from the main Polymer import, so that you wouldn't conflict on those elements.

**Comment by yattias** [comment]
thanks @azakus, any change in that respect will be very helpful.

**Comment by TimvdLippe** [comment]
Polymer 2 element-mixin does not load the custom elements by default. Thus I think we can close this issue.
