### ISSUE TITLE
Polymer components don't encapsulate javascript

### ISSUE THREAD

**Issue by yattias** [Polymer/polymer#3384]
I know that encapsulation of javascript is not part of the web component W3C spec but, what are some strategies for avoiding global namespace pollution with Polymer?

For example, if I include ``<script src="./jquery.js"></script>`` in my Polymer component then $ leaks into the the host page's window object. This is very problematic for me as I am using Polymer in a chrome extension.

**Comment by azakus** [comment]
HTML Imports doesn't provide a method of encapsulating javascript execution like ES2015 modules (though there are [proposals](https://github.com/w3c/webcomponents/blob/gh-pages/proposals/HTML-Imports-and-ES-Modules.md) for them to play together).

This means you'll have to use some other method of encapsulating javascript, such as using [IIFEs](https://en.wikipedia.org/wiki/Immediately-invoked_function_expression#Usage) or require.js, AMD, etc.

We have an experimental AMD implementation that uses HTML Imports for the actual loading called [IMD](https://github.com/polymerlabs/imd) that you could also try.
