### ISSUE TITLE
dom-repeat: Getting a property from a [parent dom-repeat template] to a [child/nested dom-repeat template]

### ISSUE THREAD

**Issue by myuseringithub** [Polymer/polymer#3391]
How can I pass a property to the scope of nested dom-repeat ? If I have a property defined with notify: true in a parent scope and I wish to use that variable in a child template dom-repeat element, what should I do to bind it ?
![dom-reapeat](https://cloud.githubusercontent.com/assets/7758497/12897903/ec86d828-ceb2-11e5-87f6-4a842eadc5f6.PNG)

What I'm trying to achieve is actually filtering Questions from a List according to search string matching both the Question title and the Answer choices. Where the search value is passed from the:
Main scope (of an app view custom element) → ↻ List examination (containing questions of specific examination year) → ↻ Question → ↻ Answers (choice answers for the question) ?
*↻ is a repeated element (using template dom-repeat).

Thanks !

**Comment by azakus** [comment]
You can use the `as` attribute to name the scope of items being repeated over, and access other scopes:
https://www.polymer-project.org/1.0/docs/devguide/templates.html#nesting-templates

**Comment by TimvdLippe** [comment]
Closing this issue per above comment. Feel free to reopen if you were still running into problems.
