### ISSUE TITLE
Does shady-DOM remove too many elements?

### ISSUE THREAD

**Issue by czellweg** [Polymer/polymer#3394]
I have come across a peculiar problem which doesn't seem to make sense to me.
Earlier versions of `polymer-mini.html` contained a method named `getComposedChildren`:

``` javascript
function getComposedChildren(node) {
  if (!node._composedChildren) {
    node._composedChildren = arrayCopyChildNodes(node);
  }
  return node._composedChildren;
}
```

This method seems to have been replaced by `TreeApi.Composed.getChildNodes` (compare method `_updateChildNodes` and how the _composed_ nodes are being evaluated). However, `TreeApi.Composed.getChildNodes` potentially includes more nodes than what was returned in earlier versions through `getComposedChildren`.

In my example, this leads to crucial HTML nodes being removed from the DOM which is not desired. The HTML in question looks as follows (I'm using a polymer wrapper around selectize.js):

``` html
<selectize-wrapper id="selectizeWrapper" required="" label="Channels" placeholder="Please select channels to retrieve data from" max-items="1000" hide-selected="" class="style-scope psi-channel-select" invalid="" aria-invalid="true">
   <paper-input-container id="input" class="style-scope selectize-wrapper x-scope paper-input-container-0">
      <div class="floated-label-placeholder style-scope paper-input-container">&nbsp;</div>
      <template is="dom-if" class="style-scope paper-input-container"></template>
      <div class="input-content style-scope paper-input-container">
         <div class="label-and-input-container style-scope paper-input-container" id="labelAndInputContainer" style="position: relative;">
            <label class="style-scope selectize-wrapper">
            <span class="style-scope selectize-wrapper" hidden="">Channels</span>
            <span class="style-scope selectize-wrapper">Please select channels to retrieve data from</span>
            </label><input id="rawInput" is="iron-input" class="spinner style-scope selectize-wrapper selectized" tabindex="-1" value="" style="display: none;">
            <div class="selectize-control spinner style-scope selectize-wrapper multi plugin-remove_button">
               <div class="selectize-input items not-full has-options focus dropdown-active"><input type="text" autocomplete="off" tabindex="" style="width: 4px; opacity: 1; position: relative; left: 0px;"></div>
               <div class="selectize-dropdown multi spinner style-scope selectize-wrapper plugin-remove_button" style="display: block; visibility: visible; width: 380px; top: 18px; left: 0px;">
                  <div class="selectize-dropdown-content">
                     <div data-value="BoolScalar" data-selectable="" class="option">BoolScalar</div>
                     <div data-value="BoolWaveform" data-selectable="" class="option active">BoolWaveform</div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <div class="underline is-highlighted style-scope paper-input-container">
         <div class="unfocused-line style-scope paper-input-container"></div>
         <div class="focused-line style-scope paper-input-container"></div>
      </div>
      <div class="add-on-content is-highlighted style-scope paper-input-container">
         <paper-input-error id="errorMessage" class="style-scope selectize-wrapper x-scope paper-input-error-0" add-on="" invalid="">
            Please select a value
         </paper-input-error>
      </div>
   </paper-input-container>
</selectize-wrapper>
```

Since the implementation of `Polymer.TreeApi.arrayCopyChildNodes` looks like this:

``` javascript
Polymer.TreeApi = {

  arrayCopyChildNodes: function (parent) {
    var copy = [], i = 0;
    for (var n = parent.firstChild; n; n = n.nextSibling) {
      copy[i++] = n;
    }
    return copy;
  }
...
};
```

when `parent === div#labelAndInputContainer`, we get `div.selectize-control` as part of the children. This is different from what we used to get back from `getComposedChildren` (`div.selectize-control` not included).

Subsequently, in method `_updateChildNodes(container, children)`, if the container does not include the same children as the provided children in the argument, those children will be removed:

``` javascript
  _updateChildNodes: function (container, children) {
    var composed = TreeApi.Composed.getChildNodes(container);
    var splices = Polymer.ArraySplice.calculateSplices(children, composed);
    for (var i = 0, d = 0, s; i < splices.length && (s = splices[i]); i++) {
      for (var j = 0, n; j < s.removed.length && (n = s.removed[j]); j++) {
        if (TreeApi.Composed.getParentNode(n) === container) {
          TreeApi.Composed.removeChild(container, n);
        }
        composed.splice(s.index + d, 1);
      }
      d -= s.addedCount;
    }
    for (var i = 0, s, next; i < splices.length && (s = splices[i]); i++) {
      next = composed[s.index];
      for (var j = s.index, n; j < s.index + s.addedCount; j++) {
        n = children[j];
        TreeApi.Composed.insertBefore(container, n, next);
        composed.splice(j, 0, n);
      }
    }
  }
```

Can someone explain why this is the case & what can be done to convince Polymer not to remove this node? It's probably just an issue of me not understanding the internals / implications of shady-DOM so apologies for my ignorance.

**Comment by azakus** [comment]
Hi, can you provide a JSBin containing a set of reproducible steps? See [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs) for details.

**Comment by czellweg** [comment]
I had some issues setting up a JSBin but I have created a small demo on the `gh-pages` branch of my element, I hope that works too? See here: http://czellweg.github.io/selectize-wrapper/components/selectize-wrapper/demo/index2.html

To reproduce:

1. klick on the input field and select a value from the list
2. remove the just selected element by clicking on the small `x`
3. note that now the no input is possible anymore because the `div` element with class `selectize-control` has been removed through the above-mentioned (see my initial comment) process
 

What seems to cause this issue, in addition to what I have already described:
- the removal of the element comes as a result of the element being validatable, i.e. once the validation has run, Polymer will then ultimately re-run the `_updateChildNodes` code
- this results in the `div class='selectize-control...'` element to be removed

Have I fundamentally missed something? Or how can I tell Polymer that this element should not be removed?

**Comment by PkmX** [comment]
I could reproduce a somewhat similar problem by:

```javascript
var pm = document.createElement("paper-material");
pm.style = "width: 100px; height: 100px;"; // Make it visible
pm.appendChild(document.createElement("div"));
pm.appendChild(document.createElement("paper-ripple"));
document.body.appendChild(pm);
```

On polymer 1.3.0 and Chromium 48, clicking on the `<paper-material>` removes **both** `<div>` and `<paper-ripple>` from the parent.

Surprisingly, this bug only triggers on polymer >= 1.2.4 (incl. 1.3.0) on Chromium 48 when the elements are created and inserted by JS. It works if they are declared in the HTML, or if it is run on Firefox 44, or if I downgrade polymer to 1.2.3.

I think it is a critical issue. I cannot use most of the paper elements as a result of this since the ripple effect would remove the wrong stuffs, and my elements are generated by JS dynamically.

**Comment by arthurevans** [comment]
@PkmX The issue you report is because you're not using the `Polymer.dom()` methods to insert the children, so you're effectively adding them to the `paper-material` tag's local DOM. 

Here are the docs on the DOM API:

https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#dom-api

Here's a jsbin using `Polymer.dom`: 

http://jsbin.com/dosasi/5/edit?html,output

This works in Chrome, Firefox, and Safari. When I remove the `Polymer.dom`, it doesn't work in any of them. I also tried changing the Polymer version to 1.2.3, and I didn't see any difference on any of those platforms.

@czellweg I looked at your demo, but it's still 500 lines of JS, plus 2000 lines of selectize, and I really can't tell what's going on here. Although I suspect the core of the issue is the same, that selectize doesn't know about the Polymer DOM API, so the nodes aren't being identified correctly.

**Comment by czellweg** [comment]
@arthurevans Understood, so forking selectize and make it Polymer-aware, i.e. making sure that the _added_ DOM elements use `Polymer.dom()`, should do the trick then. I will try this out.

Thanks for your help.

**Comment by TimvdLippe** [comment]
Since `Polymer.dom` is removed in Polymer 2 and you can now use the normal dom API's this issue should be resolved. I updated the JSBin to Polymer 2 (http://jsbin.com/wuzunoxume/edit?html,console,output) and was unable to reproduce the issue.
