### ISSUE TITLE
Link leads to 404 page

### ISSUE THREAD

**Issue by saniko** [Polymer/polymer#3395]
https://www.polymer-project.org/1.0/docs/start/reusableelements.html#documentation

Under Documentation section the "demo" link leads to 404 page.

FYI.

**Comment by saniko** [comment]
same on:
https://www.polymer-project.org/1.0/docs/start/reusableelements.html#share

links should be updated.

**Comment by arthurevans** [comment]
This issue was moved to Polymer/docs#1529
