### ISSUE TITLE
Internet Explorer flexbox issue with "dom-is" and "dom-repeat" templates.

### ISSUE THREAD

**Issue by PaulHMason** [Polymer/polymer#3402]
This is a bit of a strange issue. If you have a dom-repeat inside a flexbox container the first child isn't left aligned flush with the left edge and the last child item isn't right aligned flush with the right edge (it's left aligned within it's proportional area, not right aligned) in IE11 (fine in Chrome and FF). If you simply add the child items without a template then they render fine. The background line has no bearing on the issue - it's still a problem if you remove it.

_Edit: Actually, the left-most item is still incorrect in Chrome and FF even when you don't use a template repeater._

Is there any work around for this?

Here's a simple element to illustrate the issue:

````
<link rel="import" href="../../bower_components/polymer/polymer.html" />
<link rel="import" href="../../bower_components/iron-flex-layout/iron-flex-layout.html" />
<dom-module id="my-stepper">
    <template>
        <style>
            :host {
                display: block;
            }

            .step-container {
                background: white;
                @apply(--layout-horizontal);
                @apply(--layout-justified);
            }

            .step-label {
                background: aqua;
                z-index: 1;
                padding: 8px 16px;
            }

            .step-container-line {
                position: fixed;
                width: 100%;
                height: 1px;
                top: 18px;
                background-color: silver;
                z-index: 0;
            }
        </style>

        <div class="step-container">
            <!-- Incorrect Rendering in IE11
            <template is="dom-repeat" items="{{steps}}">
                <span class="step-label">{{item}}</span>
            </template>
            -->

            <!-- Renders fine in all browsers-->
            <span class="step-label">Step One</span>
            <span class="step-label">Step Two</span>
            <span class="step-label">Step Three</span>
            <span class="step-label">Step Four</span>
            <span class="step-label">Step Five</span>
        </div>
        <div class="step-container-line"></div>
    </template>

    <script>
        Polymer({
            is: "my-stepper",

            properties: {
                steps: {
                    type: Array,
                    value: function () {
                        return ["Step One", "Step Two", "Step Three", "Step Four", "Step Five"];
                    }
                }
            }
        });
    </script>
</dom-module>
````

**Comment by azakus** [comment]
Can you confirm if you still see this behavior without the `iron-flex-layout`?

**Comment by PaulHMason** [comment]
Yes, the behavior is still the same if I do this:

````
.step-container {
                background: white;
                /*
                @apply(--layout-horizontal);
                @apply(--layout-justified);
                */
                display: -ms-flexbox;
                display: -webkit-flex;
                display: flex;
                
                -ms-flex-direction: row;
                -webkit-flex-direction: row;
                flex-direction: row;
                
                -ms-flex-pack: justify;
                -webkit-justify-content: space-between;
                justify-content: space-between;
            }
````

**Comment by kaste** [comment]
Cannot reproduce, tried this bin https://jsbin.com/reragapote/edit?html,output 

(I actually also had problems with flexbox, but was never able to reproduce.)

**Comment by PaulHMason** [comment]
I see the issue in your bin (on Windows 8.1 and 10). It's fine in Chrome, FF and Edge - just IE11 has a problem.

**Comment by kaste** [comment]
Can you take a screenshot?

Also: I thought something is wrong on Chrome / FF as well?

Paul <notifications@github.com> schrieb am Sa., 13. Feb. 2016 14:07:

**Comment by PaulHMason** [comment]
Here's a screenshot:

![templateflexboxissue](https://cloud.githubusercontent.com/assets/1944711/13027784/607b0cd0-d265-11e5-875a-58808e28b4a7.png)

**Comment by kaste** [comment]
Yeah, I see it too. Seems like the `<template>` tag claims space.

**Comment by kaste** [comment]
Actually, this is the same issue I had before but I never found a simple test case for it. :clap:

**Comment by PaulHMason** [comment]
Ah, you're right - all browsers show a child count of 6 (5 steps and the template), but IE is incorrectly including the template element as a flex child (with a width of zero) at the end.

**Comment by PaulHMason** [comment]
Now that I know what the problem is, the workaround is simple - just set `display: none` on the template.

````
#flex-template {
  display: none;
}

<template is="dom-repeat" items="{{steps}}" id="flex-template">
  <span class="step-label">{{item}}</span>
</template>
````

**Comment by ebidel** [comment]
This is likely because IE 11 does not have native support for `<template>` but edge does. 

At some point, the wc.js polyfills had polyfill styling for template to set `display: none`. Is that gone?

**Comment by PaulHMason** [comment]
This issue has been logged against wc.js. @azakus 

https://github.com/webcomponents/webcomponentsjs/issues/481
https://github.com/webcomponents/webcomponentsjs/pull/483

**Comment by maartenst** [comment]
this seems to be happening in chrome 60 too
