### ISSUE TITLE
Events bubble across native SD boundery

### ISSUE THREAD

**Issue by pkaske** [Polymer/polymer#3403]
Here there,

I'm getting events I shouldn't, at least I think so. I have nested web components, both have a notifying `value` prop. The child's `value` prop is bound to the parents `value`. I attached a `value-changed` event listener to the parent element at document level. Now when the value of the child is changed the binding does it's job as expected, but I get two `value-changed` events. One comes from the parent element and one from the child. I assume the one from the child shouldn't reach the document level, right?

This only happens in native SD.

I made you guys a [jsbin](https://jsbin.com/cugopikotu/edit?html,console,output) to reproduce that.  
Uncomment the `window.Polymer.dom = 'shadow';` line to get the strange behavior.

**Comment by azakus** [comment]
This is actually correct according to the [ShadowDOM event retargeting spec](http://w3c.github.io/webcomponents/spec/shadow/#event-dispatch)

Here's an example JSBin that show that this is just a part of ShadowDOM: https://jsbin.com/cugopikotu/edit?html,output

There is some movement on the spec to change this behavior (maybe this issue https://github.com/w3c/webcomponents/issues/61), but it is operating as spec'd.

**Comment by pkaske** [comment]
Got it! Thanks for taking the time to explain this to me!
