### ISSUE TITLE
Attribute with compound binding not being applied in Safari.

### ISSUE THREAD

**Issue by barischj** [Polymer/polymer#3404]
I have below some very simple code. Almost as simple as the `<proto-element>` in `https://www.polymer-project.org/1.0/docs/start/quick-tour.html`.

The issue in this code is the following style is not being applied in Safari, but is in Chrome and Firefox.
`<div style="background-color: {{item.hsl}}"> `

This is the full code for the element:
```html
<link rel="import" href="bower_components/polymer/polymer.html">

<dom-module is="issue-elem">
  
  <template>
    <template is="dom-repeat" items="{{items}}">
      <div style="background-color: {{item.hsl}}">
        <div>I should have a background color.</div>
      </div>
    </template>
  </template>

  <script>
    Polymer({
      is: "issue-elem",
      properties: {
        items: {
          type: Array,
          value: null
        }
      },
      ready: function() {
        var items = [{}, {}, {}]
        items.map(function(item) {
          item.hsl = "hsl(100, 90%, 65%)"
        })
        this.set("items", items)
      }
    })
  </script>

</dom-module>
```

In Safari:
<img width="231" alt="screen shot 2016-02-10 at 13 40 18" src="https://cloud.githubusercontent.com/assets/6631452/12948950/3aa6531c-cffd-11e5-9dc2-399ec6f0c4c2.png">

In Chrome:
<img width="235" alt="screen shot 2016-02-10 at 13 40 28" src="https://cloud.githubusercontent.com/assets/6631452/12948955/414aa600-cffd-11e5-98fb-a9a54e7ac1b2.png">

In Firefox:
<img width="228" alt="screen shot 2016-02-10 at 13 50 58" src="https://cloud.githubusercontent.com/assets/6631452/12948973/591e381e-cffd-11e5-981e-46bebc3e69e2.png">

Here is a zip file with a folder containing an index.html, issue-elem.html and the necessary bower dependencies:
[issue.zip](https://github.com/Polymer/polymer/files/124831/issue.zip)

**Comment by miztroh** [comment]
You need to use ``<div style$="background-color: {{item.hsl}}">``.

**Comment by miztroh** [comment]
On another note, you might as well use [[]], since that binding is only one-way.

**Comment by barischj** [comment]
Thank you very much!
Perhaps it's not a good idea for `<div style="background-color: {{item.hsl}}">` to work in Chrome and Firefox, since it's not correct code. Though I have no idea if that's possible.

**Comment by miztroh** [comment]
My suggestion is the way you're supposed to do it across the board to avoid issues like this.

**Comment by mercmobily** [comment]
@miztroh I think it's best to close this ticket since it provides a clear solution to the problem!

**Comment by azakus** [comment]
@miztroh is correct, you need to use `style$="background-color: {{item.hsl}}"`. The reason is that *without* the `$`, this will try to set the style *property*, which is an object. 

The `$` will make sure you set the style *attribute*.

https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#attribute-binding
