### ISSUE TITLE
non-standard globals

### ISSUE THREAD

**Issue by timoxley** [Polymer/polymer#341]
Polymer is leaking a lot of random stuff into the global namespace. Is there a potential strategy/policy that could be adopted to **prevent creation of any non-standard globals** other than the absolute bare minimum (e.g. nest everything custom under `window.Platform`)?

At time of writing, the polymer-platform leaks the following globals. I have taken a stab at which of these are standard, which are non-standard.

#### Potentially standard

* Observer
* ArrayObserver
* ArraySplice
* ObjectObserver
* PathObserver
* CompoundPathObserver
* Path
* ShadowRoot
* Inspector
* HTMLImports
* CustomElements
* PointerEvent
* PointerGestures

#### Potentially non-standard, consider removing:

* Platform
* logFlags
* ShadowDOMPolyfill
* wrap
* unwrap
* templateContent
* sinspect
* shadowize
* esprima
* PolymerExpressions
* polymerWrapper_
* JsMutationObserver
* PointerEventsPolyfill

There's probably even more globals in the full polymer project.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
