### ISSUE TITLE
Observers registered twice when extending from same Behavior twice

### ISSUE THREAD

**Issue by reinert** [Polymer/polymer#3412]
Suppose the following scenario:

```js
  BaseBehavior = {
    ...
    observers: [ '_propChanged(prop)' ]
     ...
  }
```
```js
  SideBehaviorImpl = {
    ...
  }
  // extend BaseBehavior
  SideBehavior = [ BaseBehavior, SideBehaviorImpl ]
```
```html
  <dom-module id="plot-series">
    ...
    behaviors: [ BaseBehavior, SideBehavior ]
    ...
  </dom-module>
```

Polymer is registering `_propChanged` twice because of the indirect 'duplicate' inheritance. So whenever prop changes `_propChanged` function is called twice.

I believe Polymer should treat this scenario as a single inheritance.

I don't know if this is a bug or is expected. Just reporting.

**Comment by azakus** [comment]
Should be fixed by https://github.com/Polymer/polymer/pull/3386

**Comment by azakus** [comment]
Sorry, should be closed when that PR lands, not before. :)

**Comment by TimvdLippe** [comment]
Fixed ;)

**Comment by reinert** [comment]
Thanks!
