### ISSUE TITLE
[feature request] dom-if deferred or maybe dom-deferred element

### ISSUE THREAD

**Issue by ktiedt** [Polymer/polymer#3416]
Use case:
    Lazy rendering of nested elements where an animation may later hide them, basically only delay showing the elements, after that, it is up to the user to hide them as desired.

Basically in it's current implementation, dom-if wlil break the animation because once FALSE, hidden gets applied causing an immediate jump the dom layout. This can be achieved with a computed function but in also comes with the overhead of juggling the state that the computed uses where a custom element could just flip a bit and be on its way.

**Comment by azakus** [comment]
Can you draft up a bit more of what you'd like to see in terms of syntax and behavior?

**Comment by ktiedt** [comment]
Not sure what more I can express about the behavior...

the TL;DR; is, a dom-if like element, that doesnt toggle [hidden] after it has been stamped the first time

so...
```
<template is="dom-if" if="[[sometimesTrueSometimesNot]] deferred>
    <div>Once I am stamped, this content is not automatically [hidden] once sometimesTrueSometimesNot becomes false again. It is up to the application to hide me</div>
</template>
```

As I stated, the purpose of this would be to allow lazy rendering of animate-able recursive objects

Think, a nested menu/submenu layout that has sub menues 5 deep... there is no need to stamp the dom for all layers of the menu until a submenu is toggled open... BUT once it has been opened, the collapsing animation is lost currently when a dom-if becomes falsey again, it just snaps out of existence because [hidden] gets applied.

**Comment by Bamieh** [comment]
@ktiedt i am pretty sure you can wrap the dom-if with a custom component that can do the intended job for you. this custom element will set the [[sometimesTrueSometimesNot]] to false after the animation/duration is done.

**Comment by ktiedt** [comment]
It is completely achievable right now, with extra code to track what has been toggled and latching the if's TRUE. I am merely saying that with minor tweaks this could be a handy feature of dom-if or something similar to it that would not require an additional registry object to track these states for every possible use-case in an application.
