### ISSUE TITLE
Two-way data binding issue

### ISSUE THREAD

**Issue by ahcheqiu** [Polymer/polymer#3421]
I have an element like this:
```
<dom-module id="my-elem">
    <template>
        <paper-input value="{{value}}" type="Number"></paper-input>
    </template>
    <script>
        Polymer({
            is: "my-elem"
        });
    </script>
</dom-module>
```
And test code like this
```
<template is="dom-bind">
    <my-elem value="{{value}}"></my-elem>
    <paper-input value="{{value}}" type="Number"></paper-input>
</template>
```

I expected that my-elem and paper-input will always display the same number.
But when I change the value of my-elem, paper-input do not change.
And when I change the value of paper-input, my-elem do change. 

What can I do to fix this issue?

**Comment by TimvdLippe** [comment]
Values are propagated towards the parent if they have `notify: true`. Therefore to fix the issue, create `my-elem` with:

```js
Polymer({
  is: 'my-elem',
  properties: {
    value: {
      type: Number,
      notify: true
    }
  }
});
```
