### ISSUE TITLE
Error when calling set or notifyPath on a two-way bound property from within dom-template

### ISSUE THREAD

**Issue by Sleeckx** [Polymer/polymer#3422]
Reproducible test case can be found here: http://jsbin.com/dunikitije/edit?html,console,output

Possibly related to issue #3307

**Comment by kevinpschaaf** [comment]
Confirmed this is also an issue in Polymer 2 (it is blocked on #4458 as well).

Added fix in PR for #4458 to avoid bug, making this work (added a trivial implementation of `<dom-template>`, since we no longer ship that in Polymer 2): http://jsbin.com/lixawu/edit?html,console,output
