### ISSUE TITLE
getOwnPropertyNames in Polymer.StyleProperties.reify can cause error to be thrown

### ISSUE THREAD

**Issue by jarrodek** [Polymer/polymer#3424]
When you use libraries or have own code that is extending JavaScript's Object prototype the Polymer.StyleProperties.valueForProperty will thrown an error:

> Uncaught TypeError: property.indexOf is not a function

This is caused by not type checking after calling `getOwnPropertyNames()` in Polymer.StyleProperties.reify.

## Steps to reproduce the problem
1. Extend Object prototype 
```
Object.prototype.anyFunction = function() {};
```
2. Run any Polymer app

## Expected output
Program is running as designed, no errors in a console

## Actual output 
Errors are thrown in a console and polymer is not bootstrapping the app.

## Suggested solution
There should be type check for property:
```
if (property && typeof property  === 'string') {
  if (property.indexOf(';') >= 0) {
     //...
}
```

**Comment by azakus** [comment]
Modifying the prototype of `Object` is a bad idea.
Any loop that uses `for in` will break, as well as `"anyFunction" in anyObject`.

I can't see a break in `reify` in my [JSBin](http://jsbin.com/jomeve/1/edit?html,console,output), but I do see one in `Polymer.Base._listenListeners`, and I'm sure there are plenty more.

You should probably re-evaluate your use of a script that modifies prototypes, it will probably break much more of your code than it is worth using.

If you _really_ need this function, you can set it to be non-enumerable:
```js
Object.defineProperty(Object.prototype, 'anyFunction', {
  enumerable: false, //default
  value: anyFunction
});
```

**Comment by jarrodek** [comment]
You are right. Benefits of having this function defined in Object are not worth trouble that I may have later. I'll do it differently.
