### ISSUE TITLE
[feature request] silent properties setting

### ISSUE THREAD

**Issue by fgirardey** [Polymer/polymer#3426]
Hi everyone,

It could be useful in some cases to use `this.set` with a silent param to avoid event trigger. Don't you think ?

[Backbone](http://backbonejs.org/#Events-catalog) has such a thing.

**Comment by felixnielsen** [comment]
+1

**Comment by TimvdLippe** [comment]
@fgirardey Could you supply a JSBin which shows what you are trying to achieve and when the event is unexpected? Then we can investigate and hopefully resolve this issue.

**Comment by TimvdLippe** [comment]
I am closing this for now, as we require a JSBin or larger explanation of the requested feature. Feel free to reopen this issue when you supplied this!
