### ISSUE TITLE
Support ES class properties proposal in Polymer element definition

### ISSUE THREAD

**Issue by jrajav** [Polymer/polymer#3428]
If Polymer supports class properties as defined in https://github.com/jeffmo/es-class-fields-and-static-properties and provided by Babel plugin http://babeljs.io/docs/plugins/transform-class-properties/, it simplifies class definition and brings it in line with the object interface. See these examples:

es2015.js: Current syntax without properties
es-class-properties.js: Syntax possible with properties support (Currently fails with Polymer since it does not read properties)
https://gist.github.com/jrajav/c5f28442f2adca77ff5e

Transpiled output of each:
https://gist.github.com/jrajav/091389d04571b3415e69

**Comment by jrajav** [comment]
Refer to https://www.polymer-project.org/1.0/articles/es6.html for existing ES2015 class functionality

**Comment by azakus** [comment]
We are working on this in the `extends` branch: https://github.com/Polymer/polymer/pull/3375.

**Comment by prisis** [comment]
@azakus have you a date for me when the es6 support is ready?
Or do you need some help?

**Comment by mbana** [comment]
does this work?
if so can we get a working example in the browser pls, or failing that the version of Polymer to download that supports this.

**Comment by TimvdLippe** [comment]
The ES6 syntax in Polymer 2 supports all the features that are natively available. Until the TC39 proposal is merged, the `static get properties() {...}` notation should be used. Once the proposal is accepted and implemented, you could define it as `properties = {...}`. Closing this issue as it will be resolved by the TC39.
