### ISSUE TITLE
Is  `a.b` syntax in `listeners` really going to go?

### ISSUE THREAD

**Issue by mercmobily** [Polymer/polymer#3429]
I am referring to [This ticket in the documentation](https://github.com/Polymer/docs/issues/1516) as well as [this comment](https://github.com/Polymer/polymer/blob/master/src/standard/events.html#L58) in the source.

So... is the `a.b` syntax really going to be deprecated?

If so... may I ask you why? Without it, the use of `listeners` is really quite severely crippled, and it would leave the annotations as the only real alternative. At this point, wouldn't it make sense to get rid of `listeners` altogether?

@sorvell you made the deprecation comment... can you enlighten us?

**Comment by TimvdLippe** [comment]
> At this point, wouldn't it make sense to get rid of listeners altogether?

This is exactly what happened. Since it is deprecated now, I am closing this issue. Please reopen if you have any more questions.
