### ISSUE TITLE
Allow pre-emptive memory freeing methods before element is detached

### ISSUE THREAD

**Issue by avdaredevil** [Polymer/polymer#3431]
Sorry if this is a duplicate, but I am using the element [highcharts-chart](https://github.com/avdaredevil/highcharts-chart) which is created dynamically in a dom-repeat controlled by a curried filter.

But when the filter updates the charts get updated [added/removed], however the recommended `destroy()` function on the charts is impossible to run when they're in the `dom-repeat` loop, as there is no way to know which ones are being detached.

**Comment by azakus** [comment]
Hi, can you provide a JSBin containing a set of reproducible steps? See [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs) for details.

**Comment by avdaredevil** [comment]
[Here it is](https://jsbin.com/zugeqe/1/edit?html)!

I just need the removed elements to have the `.destroy()` method run. This is the library for [Higcharts-Chart](https://github.com/avdaredevil/highcharts-chart)

**Comment by arthurevans** [comment]
Hi,

It seems like highcharts-chart is doing a bunch of static initialization in
its `ready` method that should probably be done elsewhere.

You could destroy the chart object in the `detached` callback and create it
in `attached`. If that happens to frequently you could debounce the destroy
call and cancel it if the element is re-attached in a short period of time.

I don't know the highcharts library, so I don't know exactly what signals
you need to listen for, but it seems like (based on your demo),
you might want to destroy and recreate charts in setData.



On Fri, Feb 19, 2016 at 5:17 PM, Apoorv Verma [AP] <notifications@github.com

**Comment by avdaredevil** [comment]
@arthurevans I like your feedback about the detached callback, but more importantly your debounced suggestion. Could you possibly provide a code example/JSBin on how that could be implemented. 

Apologies if this falls outside the scope of the issue. But I feel it might help anyone else running into similar issues.

**Comment by TimvdLippe** [comment]
@avdaredevil The comment of Arthur concerns the [`Polymer.Debouncer`](https://www.polymer-project.org/2.0/docs/api/classes/Polymer.Debouncer). I am closing this issue as the provided solutions should help you out with `detached` + `destroy`. Please let us know if you are still running into issues.
