### ISSUE TITLE
Investigate "issue template"

### ISSUE THREAD

**Issue by azakus** [Polymer/polymer#3432]
According to https://github.com/dear-github/dear-github/issues/125, it looks like issue templates are now silently supported. We should have one.

**Comment by samccone** [comment]
it is sooo amazing

https://github.com/samccone/issue-template

**Comment by TimvdLippe** [comment]
The template of @samccone does not work on mobile? Also is there an official post of GitHub on the usage and implications of the template?

Other than that, really awesome new feature!

**Comment by abdonrd** [comment]
Awesome feature!

**Comment by azakus** [comment]
@TimvdLippe Not yet, but you can see one here: https://github.com/owncloud/core/issues/new

**Comment by samccone** [comment]
yeah the feature is broken on mobile :(
