### ISSUE TITLE
Nested property/functional binding

### ISSUE THREAD

**Issue by avdaredevil** [Polymer/polymer#3434]
### Description [_Feature request_]

Allow for Polymer to support nested functions in binding for example:

``` html
<my-element bind="[[ternary(_equal(selection,1), 'a', 'b')]]"></my-element>
```

where I would have my macros defined as:

``` javascript
app.ternary = (a,b,c) => a?b:c
app._equal = (a,b) => a==b
```

Currently a functional macro in Polymer only allows all arguments to be variables or primitives like Numbers and Strings. This feature would greatly bolster the expressiveness of Polymer and allow for more complex and sophisticated bindings.

**Comment by avdaredevil** [comment]
Any updates? @azakus

**Comment by gitact** [comment]
Iteresting observation.
Any updates?
