### ISSUE TITLE
Phantom on-change events when binding to numeric input via value$

### ISSUE THREAD

**Issue by indolering** [Polymer/polymer#3436]
### Description
Mousing-over the up/down UI widgets of a `<input type="number" value$="param">` element triggers on-change events in Chrome.

#### Live Demo
http://jsbin.com/wucuzoz/3/edit?html,console,output

#### Steps to Reproduce
1. Mouse over up/down UI widget.
2. Keep trying.

#### Expected Results
Nothingness.

#### Actual Results
Function bound to on-change event fires. 

### Browsers Affected
- [X] Chrome
- [ ] Firefox
- [ ] Edge?
- [ ] Safari 9
- [ ] Safari 8?
- [ ] IE 11?

Did not test Safari 8, Edge, nor IE.
### Versions
- Polymer: v1.2.4/master
- webcomponents: v0.7.20

**Comment by azakus** [comment]
JSBin showing the same behavior without polymer: http://jsbin.com/xucarow/edit?html,console,output

**Comment by azakus** [comment]
Looks like the first time you interact with an input of type=number that had value set with `setAttribute`, it will fire a `change` event.

**Comment by azakus** [comment]
This seems like a Chrome bug, filed https://code.google.com/p/chromium/issues/detail?id=588008.

**Comment by azakus** [comment]
Fixed in Chrome with https://codereview.chromium.org/1719843002
