### ISSUE TITLE
JS dependency manegment 

### ISSUE THREAD

**Issue by AgrawalAmey** [Polymer/polymer#3441]
Recently I have been working on a project where a diverse team of developers are using various javascript libraries. The de-duping behavior eliminates the duplication but as all the loaded resources same namespace, managing dependencies become big problem. What is the best way to manage this issue? How do the polymer catalog elements share resources?

**Comment by ebidel** [comment]
Thanks for the issue. This type of question is more appropriate for SO or Slack. Can you ask folks over there?
