### ISSUE TITLE
Youtube Video Dissappears ...

### ISSUE THREAD

**Issue by ACC-Medlink** [Polymer/polymer#3445]
### Description

I have a youtube video placed inside of an element that is animated into and out of the viewable screen area by clicking a watch button. When you make the initial click to display the video it is there. If I close the element without playing the video then if I try to display the video a second time it is gone or non responsive. 

If I start the video playing when I display it, then I can leave and come back to it. 
#### Live Demo

https://medic-trans.com/landing-page2
#### Steps to Reproduce

1 click watch button
2 click close button
3 click watch button
#### Expected Results

Video expected to be there after each click of watch button
#### Actual Results

1)Video There - after first click of watch button
2)Video Gone - after second click of watch button
### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [x] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions
- Polymer: v1.2.3 (use `Polymer.version`)
- webcomponents: vX.X.X (use `bower ls` or `npm ls`) - not sure

**Comment by azakus** [comment]
Sorry, I can't seem to find the `watch` button on your site.
Can you make an small example with JSBin (starter template: https://jsbin.com/xukike/edit?html,output) and post that here?

**Comment by TimvdLippe** [comment]
Closing per above comment. Please reopen if you can submit a small JSBin that we can investigate.
