### ISSUE TITLE
Pattern to update data dynamically via comet/server side push

### ISSUE THREAD

**Issue by mercmobily** [Polymer/polymer#3449]
### Description

At the moment, we can easily create a simple [select menu that will depend on an AJAX call](http://jsbin.com/xuyoki/edit?html,output).
This is all fine and dandy, except:

* If the server notifies that there is a new category, the selects won't change (high priority)
* If I delete a category within the application, every select within the application should stop having it as an option. Note that it would be less-than-ideal to wait for the server to propagate the change back since it was generated locally (medium-high priority)
* When the application is loaded, the initial category data is in the page itself and is automatically loaded. this  will save 15 calls at load time if the application has 15 selects) (medium priority)
* If I have 10 of these in a SPA, this will end up making 10 calls (low priority)

Now, all this has several implications as it implies that:

* Data binding can happen towards a somehow "global" variable
* Data binding is actually two-way (if somewhere in the application I delete a category, the assumption is that a DELETE request has also been sent to the server)
* It's possible to notify _all_ of the selects that a change has happened
* This should be agnostic to the comet protocol. It should also be agnostic on how the application decides on what to listen to in terms of changes.

I have only just learned the whole data binding section of Polymer. I have been trying to figure out how to make something like this happen, but unsuccessfully.

I am aware of `iron-meta`, but I am not sure how that would be part of this picture -- especially in terms of 2-way binding.

https://jsbin.com/xukike/edit?html,output This is just a simple select based on an AJAX call. 

Ideas?

**Comment by mercmobily** [comment]
Random ideas:

* The caching could happen with porting this to 1.0: https://github.com/domderen/cachable-ajax/blob/master/cachable-ajax.html (although it would be a pain for now, since there is no way to extend an existing element)

* The "update data" could happen by simply surrounding the showing element with a `<change-aware>` element, and then getting "change-aware" to capture the  "server-data-change" event (fired at `body` level), and then do whatever is needed to the element (adding, editing, deleting an element). This would make everything nicely incapsulated, with each element effectively using a copy of the data and having `change-aware` to make changes to it using the right setters. 

Has anything like this been done before? Or people just put up with select menus that will only update when the SPA is reloaded? (ugh)

**Comment by mercmobily** [comment]
Well my "surrounding" element idea seems to work:

http://jsbin.com/tubexe/edit?html,output#

Here, the surrounding element gets the child (and it needs to be _one_) and adds something.
Data can be either an object, or an array of objects.
Assuming that `change-aware` will capture events and will check that they apply to the current contained element (mainly depending on the filtering options of the AJAX request), this could be a good way to go. The real challenge is to make this generic enough so that it could be used by *anybody* regardless of the server-side protocol.

I really, really look forward to the very moment we can finally extend non-native elements...

**Comment by azakus** [comment]
It doesn't seem like you're really reporting a bug with Polymer, so I'm going to to close this issue.

Element inheritance is on our [2016 roadmap](https://blog.polymer-project.org/announcements/2016/02/16/2016-roadmap/) and hope to have the first experiments out soon for people to experiment with.

**Comment by mercmobily** [comment]
I asked if there was a clear pattern to face this problem. I take this closure as "there isn't". Sorry to pollute the issue list with a non-bug...
