### ISSUE TITLE
Loosen undefined rule for computational expressions

### ISSUE THREAD

**Issue by kaste** [Polymer/polymer#3453]
As implemented in #3452.
- Let developers opt-in to see undefined's in observers et.al.
- Let computed properties and annotations evaluate to undefined if their dependencies cannot be fulfilled

Can be seen as an add-on to #3423, could be applied individually as well. All in all non breaking change. 

Ad 1: Since users sometimes want to see undefined's, provide a way to mark some of the dependencies of the computation as optional as follows `fn(?foo.bar)`. This usually comes in handy if `foo.bar` becomes unreachable, maybe simply because `foo` no longer has the member `bar`. This is exactly the case of `dom-repeat`'s invariant (See #3423 for that).

Note that there is no notion of a configuration phase for observers et.al. anymore (which Polymer didn't implement anyway). The arguments for an observer can either be fulfilled or the user opts-in and thus guards her code to see undefined's. 

Ad 2: Consider the following: 

```
  <div>[[foo.bar]]</div>
  <div>[[fn(foo.bar, otherProp)]]</div>
```

If `foo.bar` becomes unreachable (thus undefined) the first div will see an update to its textContent, the second one will not update at all (which is a bug #2158). This is hard to work around b/c a computed property wouldn't update as well. The proposal is that for computed properties as well as for computed annotations the assigned value switches to undefined if the dependencies cannot be fulfilled and thus the actual computation cannot be evaluated. ... I hear you cry. Just let that sink for a moment.

The idea here is (of course) that for `fn(foo)` if the computation cannot be evaluated its result is literally _undefined_. You can as above now opt-in and mark some arguments as optional, which allows you to do something like `_OR(?foo.a, foo.b)`, which is otherwise not possible atm.

**Comment by TimvdLippe** [comment]
Observers run with `undefined` in Polymer 2 as described in [the upgrade guide](https://www.polymer-project.org/2.0/docs/upgrade#update-observers), therefore I am closing this issue.
