### ISSUE TITLE
Add polyfill support for `:not([class])` within scoped styles

### ISSUE THREAD

**Issue by hguiney** [Polymer/polymer#3458]
### Description

When using Shady DOM, targeting elements with `:not([class])` in a `<template>`-scoped `<style>` block generates an oxymoron rule, e.g. `.my-widget:not([class])`, that can never match anything.
#### Live Demo

https://jsbin.com/turuder/7/edit?html,output
#### Steps to Reproduce

```
<dom-module id="my-widget">
  <template>
    <style>
      :not([class]) {
        color: purple;
      }
    </style>
    <div class="my-widget">
      <p>Shadow paragraph, should be purple</p>
      <p class="my-widget__paragraph">Shadow paragraph, should be black</p>
    </div><!--/.my-widget-->
  </template>
  <script>
    HTMLImports.whenReady(function() {
      Polymer({
        is: 'my-widget'
      });
    });
  </script>
</dom-module>

<my-widget></my-widget>
```
#### Expected Results

Unclassed shadow paragraph's text color should be purple.
#### Actual Results

Unclassed shadow paragraph's text color is black.
### Browsers Affected

- [x] Chrome 
- [ ] Chrome with `window.Polymer.dom = 'shadow';`
- [x] Firefox
### Versions

- Polymer: v1.2.4
- webcomponents: v0.7.21

**Comment by arthurevans** [comment]
Since shady DOM uses classes to simulate shadow DOM encapsulation, I think this may be a hard limitation of shady DOM that just needs to be documented explicitly.

Unless @sorvell can think of some magic transform to make this work.

**Comment by azakus** [comment]
@arthurevans Not only the Shady DOM mechanics, but the CSS variable and `@apply` shimming requires generating classes as well.

We should just add this to the docs as not supported.

**Comment by azakus** [comment]
@arthurevans Should an issue be filed on the docs repo?

**Comment by hguiney** [comment]
I think documentation would help either way, but another option would be to replace `:not([class])` rules  into, ironically, a class, such as `.not-class`. The selector could be tested against the raw component HTML, prior to the addition of polyfill helper classes, to determine which elements would get that class. Not sure how that would work with dynamically generated elements, but perhaps there could be a public method somewhere on `Polymer` that could reevaluate as-needed? Just thinking out loud here.

**Comment by danbeam** [comment]
this is kind of a bummer

**Comment by TimvdLippe** [comment]
This appears to be documented at https://www.polymer-project.org/2.0/docs/devguide/shadow-dom#shady-css-polyfill now

> To emulate encapsulation, the shady CSS polyfill adds classes to elements inside a shady DOM tree. It also rewrites style rules defined inside an element's template so that they're confined to the element.
