### ISSUE TITLE
Cloning custom-element including <content> duplicates its nodes?

### ISSUE THREAD

**Issue by xliiv** [Polymer/polymer#3463]
### Description

Element child are duplicated when ```<content></content>``` is included.

#### Live Demo
http://jsbin.com/selikifeja/1/edit?html,console,output

#### Steps to Reproduce

1. Click on trigger button http://jsbin.com/selikifeja/1/edit?html,console,output

#### Expected Results
Cloned element has the same content as cloning element.

#### Actual Results

```<h2>Before</h2>``` and ```<h2>After</h2>``` are duplicated

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge ?
- [ ] Safari 9 ?
- [ ] Safari 8 ?
- [ ] IE 11 ?

### Versions

- Polymer: v1.2.4
- webcomponents: v0.7.21

**Comment by sorvell** [comment]
You'll need to clone the element using Polymer's `Polymer.dom` api to be compatible with both native Shadow DOM and Polymer's Shady DOM shim.

Here's a link to the docs about this: https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#dom-api.

Here's a working example: http://jsbin.com/lujipax/1/edit?html,output

**Comment by arthurevans** [comment]
@sorvell Note that we currently don't document `cloneNode` as one of the `Polymer.dom` APIs, because... I had no idea it'd been added.

Our current manual doc solution for `Polymer.dom` is not holding up well. 

See also: https://github.com/Polymer/hydrolysis/issues/190

**Comment by arthurevans** [comment]
In the mean time, should I just move this to the docs repo and document `cloneNode`?

**Comment by sorvell** [comment]
@arthurevans +1 Thanks.

**Comment by xliiv** [comment]
I'm confirming that using `Polymer.dom(..)` it's the solution.
So I think this issue can be closed.
Thanks.
