### ISSUE TITLE
dom-bind disappears when not distributed by shadow host

### ISSUE THREAD

**Issue by tomalec** [Polymer/polymer#3464]
### Description
When `template is="dom-bind"` is inserted to shadow host, but not distributed, then it it is not available in document tree.

#### Live Demo
http://jsbin.com/bekoxi/edit?html,js,console,output

#### Steps to Reproduce
1. Create `my-element` witch shadow dom, and content distribution
2. Append `my-element` to `document.body`
3. Create `template` with `<template is="dom-bind">` inside.
4. Stamp `template` contents into `<my-element>`

#### Expected Results
`<template is="dom-bind">` element is available in document tree (light DOM), for example to be selected with `querySelector`, or removed.

#### Actual Results
`dom-bind`'s content is stamped, but the element itself is not.

### Browsers Affected
- [ ] Chrome
- [x] Firefox
- [x] IE 11

I didn't check, but I suspect, other polyfilled browsers are also affected
- [x] Edge
- [x] Safari 9
- [x] Safari 8 

### Versions
- Polymer: v1.3.0
- webcomponents.js: 0.7.21

### Other comments
When the parent/host element, does not have shadow tree, stamping works as expected.

**Comment by tomalec** [comment]
It seems to be rather webcomponentsjs issue https://github.com/webcomponents/webcomponentsjs/issues/498

**Comment by azakus** [comment]
Closing for webcomponents/webcomponentsjs#498, thanks for simplifying the reproduction!
