### ISSUE TITLE
dotjs tamplate and polymer

### ISSUE THREAD

**Issue by saniko** [Polymer/polymer#3466]
Hi,

Any examples of combining the two in polymer template?
I'm using a polymer element from backbone view + translations keys via dotjs

Best.

**Comment by azakus** [comment]
Probably better to ask this on [stackoverflow](http://stackoverflow.com/questions/tagged/polymer), our [Slack channel](https://bit.ly/polymerslack), or the [mailing list](https://groups.google.com/forum/#!forum/polymer-dev)
