### ISSUE TITLE
Polymer.* methods missing from API docs

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#3467]
### Description

No docs for Polymer.isInstance, updateStyles, etc.

https://www.polymer-project.org/1.0/api/

Not sure if the API docs are missing, or if hydrolysis is not catching them.

**Comment by TimvdLippe** [comment]
Seems to be fixed now: https://www.polymer-project.org/1.0/docs/api/classes/Polymer.Base#method-updateStyles
