### ISSUE TITLE
Array sort mutation method

### ISSUE THREAD

**Issue by indolering** [Polymer/polymer#3468]
Polymer requires the use of array mutation methods to update data-bindings to array.  However, Polymer currently lacks a method for notifying it of when an array has been sorted.  This is partially addressed by the array-binding helper methods `filter` and `sort`, but this doesn't extend outside of these specific helper methods. If this is covered by notifyPath or notifySplices, it needs to be documented.

**Comment by azakus** [comment]
This will more generally be fixed with #3343, but there may be something you can do in the short term. @kevinpschaaf any ideas?

**Comment by TimvdLippe** [comment]
This is now possible in Polymer 2 with the `MutableData` mixin: http://jsbin.com/muleruwike/edit?html,console,output This is documented at https://www.polymer-project.org/2.0/docs/devguide/model-data#array-mutation

> Use the MutableData mixin. For elements that include the Polymer.MutableData mixin, calling set or notifyPath on an object or array causes Polymer to re-evaluate the entire object graph starting at that object or array, even if the object or array itself hasn't changed. For details, see Using the MutableData mixin.
