### ISSUE TITLE
Avoid parsing strings for computed properties.

### ISSUE THREAD

**Issue by freshp86** [Polymer/polymer#3469]
Currently the syntax for a computed property is as follows (example)

```
properties {
  a: string,
  b: string,
  c: {
    type: string,
    computed: 'someFunction_(a,b)',
  },
},
someFunction_: function(a, b) { return a + b; },
```

My understanding is that the underlying system is using the "computed" string to know which properties would trigger a re-calculation of the computed proprety (which means it is parsing the "computed" property string),

How about an alternate format that achieves the same functionality but without the parsing.

```
properties {
  a: string,
  b: string,
  c: {
    type: string,
    dependencies: [this.a, this.b],
    computed: function(a, b) { return a + b; }
  },
}
```

Besides the benefit of not having to parse a string, an anonymous function can be used, which is less verbose.

**Comment by kaste** [comment]
The API would be more like: 

```
properties {
  a: String,
  b: String,
  c: {
    type: String,
    dependencies: ['a', 'b'],
    computed: function(a, b) { return a + b; }
  },
}
```
b/c `this` is of no use here and we allow `a.b.c` or `a.*` etc. as dependencies. I *could* do this if this feature request gets accepted. I know this codepath pretty well.

FWIW I use ES whatever with babel currently and thus use a decorator for this:

```
  @computed
  c(a, b) => {}
```

**Comment by motss** [comment]
How about omitting the `dependencies`?

```
properties {
  a: String,
  b: String,
  c: {
    type: String,
    computed: function(a, b) { return a + b; } // the parameters (a, b) have to be one of the properties.
  }
}

**Comment by freshp86** [comment]
@kaste : Your suggestion seems fine. I was not sure if `this` made sense in that context. Regarding `a.b.c`, could you clarify what the params passed to the anonymous function will be? For example

```
properties {
  a: {
    type: Object,
    value: function() { return {foo: 'bar'}; },
  }
  b: String,
  c: {
    type: String,
    dependencies: ['a.foo', 'b'],
    computed: function(foo, b) { return foo + b; } // is the 1st argument a.foo or a?
  },
}
```

@motss: How will Polymer know what to pass to the anonymous function without the `dependencies` field? I don't think it is possible, but not 100% sure.

**Comment by kaste** [comment]
It's `a.foo`.

The other thing is reflecting the function definition. That rules out
because JS minimizers will change the argument names.

freshp86 <notifications@github.com> schrieb am Do., 25. Feb. 2016 19:08:

**Comment by azakus** [comment]
This seems like a rather small change, but there is a use case missing for providing literals to the computed function, like `_computeFoo("hello", a)` allows for.
I don't think we'll accept adding this feature right now, as we're currently refactoring all the parts of Polymer into more easily consumable, separable sub-libraries.
When that effort is done, it should be pretty simple for you to make this work in your elements as you see fit.

**Comment by freshp86** [comment]
Thanks for considering.
Regarding the use-case of passing literals, is that use-case a real issue for computed properties? If a literal was to be passed, why not just use the literal in the anonymous function directly, without passing it as a param/dependency? (My understanding is that the same literal would be always passed, no way to pass a different one, since an anonymous function is being used, see modified example below).

```
// snippet from previous comments
c: {
    type: String,
    dependencies: ['a.foo', 'b'],
    computed: function(foo, b) { return foo + b + 'someLiteralString'; }
  },
```

**Comment by miztroh** [comment]
Think of a date property that you want formatted different ways for data
binding purposes.  You could have multiple computed properties passing a
different format string each time, all to the same function.

**Comment by freshp86** [comment]
@miztroh: If I understand correctly your example, it can be addressed as follows.

```
properties: {
  date: Date,
  dateAsFoo: {
    type: String,
    dependencies: ['date'],
    computed: function(date) {  return this.format_('fooformat', date); },
  },
  dateAsBar: {
    type: String,
    dependencies: ['date'],
    computed: function(date) {  return this.format_('barformat', date); },
  },
},
format_: function(format, date) { // format as string here },
```
A computed property can only depend on other Polymer properties, so I don't see the need for passing string literals to it. By "depend" I mean what needs to change to trigger a re-calculation.

Overall, I think that parsing function names and parameter names as strings is a code smell. I understand that parsing is necessary for stuff that resides in HTML, but for stuff that is already in JS, seems unnecessary. Also it makes Polymer code very idiomatic, and harder to use with various other tools (like type-checkers/compilers/minifiers etc).

**Comment by TimvdLippe** [comment]
In Polymer 2 you can now quite easily implement this behavior yourself :tada: http://jsbin.com/pebiyovata/edit?html,console,output Therefore I am closing this issue.
