### ISSUE TITLE
quick tour doesn't explain how to install iron-input into bower

### ISSUE THREAD

**Issue by hanwen** [Polymer/polymer#3471]
https://www.polymer-project.org/1.0/docs/start/getting-the-code.html says "For this reason we recommend starting with Bower if possible."

and https://www.polymer-project.org/1.0/docs/start/quick-tour.html has examples with bower_components hrefs, but the example "editable-name-tag" uses iron-input, and that is not installed by default. This is especially confounding because there is no error message; the widget just doesn't behave as expected. 

I finally figured it out, and I could work out what to do using https://elements.polymer-project.org/guides/using-elements#installing-with-bower, but Getting started should include a note.

**Comment by azakus** [comment]
This issue was moved to Polymer/docs#1559
