### ISSUE TITLE
CSS custom props: update all element usage of default values

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#3474]
To support native custom properties, we need to update all element usage of default values to include `var()`. For example, `background: var(--color, var(--pink));` instead of  `background: var(--color, --pink);`.

This works in Canary:

```
<style>
  :root {
    --pink: pink;
  }
  .test {
    background: var(--color, var(--pink)); 
  }
</style>
<div class="test">I should have a pink bg</div>
```

This does not work in Canary:

```
<style>
  :root {
    --pink: pink;
  }
  .test {
    background: var(--color, --pink); 
  }
</style>
<div class="test">I should have a pink bg</div>
```

Furthermore, the style shimmer needs to be update to support the native case. Part of https://github.com/Polymer/polymer/issues/3339.

Currently, this does not work with the style shimmer in canary (http://jsbin.com/vibewugabe/edit?html,output):

```
<link rel="import" href="https://rawgit.com/Polymer/polymer/v1.3.0/polymer.html">

<style is="custom-style">
  :root {
    --pink: pink;
  }
.test {
  --color: red;
  background: var(--color, var(--pink)); 
}
</style>
<body>

  <div class="test">I should have a pink bg</div>
```

**Comment by JosefJezek** [comment]
Also not working media queries... :-(

```css
:root {
  --gutter: 4px;
}

section {
  margin: var(--gutter);
}

@media (min-width: 600px) {
  :root {
    --gutter: 16px;
  }
}
```

**Comment by TimvdLippe** [comment]
This has been fixed in Polymer 2: http://jsbin.com/yupopajogi/edit?html,output
