### ISSUE TITLE
CSS keyframes reference incorrectly renamed when prefixed by another keyframes set

### ISSUE THREAD

**Issue by keanulee** [Polymer/polymer#3475]
### Description

If keyframes `slide` and `slide-back` are defined in a element, the `slide-back` keyframes declaration are renamed to `@keyframes slide-back-x-el-0 {...}`, but the animation property is incorrectly renamed to `animation: slide-x-el-0-back`.
#### Live Demo

https://jsbin.com/vidaxokeho/edit?html,output
### Browsers Affected

- [x] Chrome
### Versions

- Polymer: v1.3.0

**Comment by keanulee** [comment]
Thanks to @traviskaufman who found this in https://github.com/PolymerElements/paper-linear-progress/pull/1

**Comment by azakus** [comment]
Yep, the animation name replacer is not quite smart enough. This issue also exists in Polymer 2 with ShadyCSS as webcomponents/shadycss#148

**Comment by TimvdLippe** [comment]
This was fixed in #5038
