### ISSUE TITLE
Polymer-project.org: Back button does not work

### ISSUE THREAD

**Issue by newfivefour** [Polymer/polymer#3477]
I can't find a better place to put this since there seems not be to a Polymer website repo.

0. Go the polymer site: https://www.polymer-project.org/
0. Press Guides and Resources button
0. Press the back button
0. Nothing happens

Expected: You go back to the page you were on.

If you press it again, you do.

Browsers affected: Firefox 46.0a2, Chromium 48. Chromium mobile 47.

Can we fix this? It'd be nice to have polymer-project.org has something I can show clients in regard to operational back button in a mobile site.

**Comment by arthurevans** [comment]
Hi @newfivefour. We're working on a new version of the site, but it's a way off. In the meanwhile, I don't recommend showing clients polymer-project.org as a demo; the code is quite old and it has a number of issues that are impossible for us to address without rewriting it. 

On the brighter side, the element catalog, though it has its share of issues, does handle the back button correctly:

https://elements.polymer-project.org/

The Polymer website repo is here, by the way:

https://github.com/Polymer/docs

And if you're curious, the Polymer catalog repo is over here:

https://github.com/Polymer/polymer-element-catalog

I'm going to close this one, with apologies, as "will-not-fix, we'll try and do better next time."
