### ISSUE TITLE
Shady DOM and local <input> and label's 'for' attribute incorrect working

### ISSUE THREAD

**Issue by kirill-kravchenko** [Polymer/polymer#3478]
Hello! I have the following custom component:
`

    <dom-module id="custom-textfield">

	    <template>
		    <label for="input">Label</label>
		    <input id="input" type="text" "/>
	    </template>

     </dom-module>

`

And I am trying to use it in my html file like this:
`

    <custom-textfield></custom-textfield>
    <custom-textfield></custom-textfield>

`

When I click on label tag in the second <custom-textfield> - the expected value is 'input in second custom-textfield get focused', but in this case I get incorrect behavior.
JSBin example here: https://jsbin.com/yuzehehuci/edit?html,output

**Comment by MeTaNoV** [comment]
`id` attribute is supposed to be unique which is not the case in your example, hence the incorrect behavior.

**Comment by kirill-kravchenko** [comment]
Correct link https://jsbin.com/yuzehehuci/edit?html,output

**Comment by kirill-kravchenko** [comment]
@MeTaNoV But Polymer allows multiple id attributes in single HTML document...

**Comment by miztroh** [comment]
It's likely going to be difficult to override the native behavior and make this work under Shady DOM.  You might look at using ``iron-input`` / ``paper-input``.  Additionally, you could get rid of the ``for="input"`` and just add an ``on-tap`` handler to the label and focus the input manually.

**Comment by IntranetFactory** [comment]
We use https://github.com/PolymerElements/iron-label for labels in Shady Dom. They provide a working for= in Shady DOM.

**Comment by miztroh** [comment]
@IntranetFactory Good call.  I hadn't thought about that.

**Comment by azakus** [comment]
@kirill-kravchenko Unfortunately, making the `for` attribute work would require generating unique IDs in ShadyDOM, which would also require far more complicated and expensive CSS modifications than we would like.

As @IntranetFactory and @miztroh pointed out, there are a few workarounds, such as using `iron-label`.

You can also do this:
```html
<label>
Label <input id="input" type="text">
</label>
```

like in this JSBin: https://jsbin.com/qelapum/edit?html,output
