### ISSUE TITLE
preventDispose does not propagate to sub-elements inside an element's shadowRoot

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#348]
Setting preventDispose = true will prevent an element from unbinding. However, sub-elements inside the element's shadowRoot will still unbind. This makes the property cumbersome/impractical. 

This is the case because the sub-elements don't themselves have preventDispose set and will still get a leftViewCallback where the unbinding is initiated.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
