### ISSUE TITLE
Typo on google-signin-aware doc page

### ISSUE THREAD

**Issue by hernanhiguera** [Polymer/polymer#3481]
Just want to note that the docs page for the google-signin-aware element has a typo in the closing template tag and may lend itself for confusion to some people.

cheers!

The link to the page only seems to work if I copy/paste into a tab.
https://elements.polymer-project.org/elements/google-signin?active=google-signin-aware

**Comment by azakus** [comment]
Thanks, this looks like it should go instead on the [google-signin element](https://github.com/GoogleWebComponents/google-signin)

I'm going to clean up this issue and move it over there.

**Comment by azakus** [comment]
This issue was moved to GoogleWebComponents/google-signin#131
