### ISSUE TITLE
Is possible to use iron-icon with paper-dropdown-menu?

### ISSUE THREAD

**Issue by JeffGillin** [Polymer/polymer#3482]
I wanted to see if it's possible to have a paper-dropdown-menu that uses just an icon, and has the drop-down when clicked.  If not, is there another means of doing this using the existing components?
Thanks,
Jeff

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests. Please use other channels like Slack, StackOverflow, Google Groups for support questions.

I guess you can use it like shown here https://elements.polymer-project.org/elements/paper-dropdown-menu where you use the `<paper-item>` without a text (not tried).

**Comment by JeffGillin** [comment]
Gotcha, will do

**Comment by azakus** [comment]
Looks like this resolved itself. Closing.
