### ISSUE TITLE
document.tap triggered after button.click

### ISSUE THREAD

**Issue by valdrinkoshi** [Polymer/polymer#3483]
### Description

On desktop, `tap` event listeners on `document` (with `useCapture = true`) should be called before any element's `click` event. Instead, the element's `click` event gets fired before `document`'s `tap`
#### Live Demo

http://jsbin.com/laxoda/2/edit?html,output
#### Steps to Reproduce
1. Add any element on your document (e.g. `button`) with `onclick="elementClick()"`
2. Add a `document.addEventListener("tap", documentTap, true);` (also enable document-wide tap)
3. Click on the button
#### Expected Results

We should see the following output on the jsbin:

```
document click
document tap
button click
button tap
```
#### Actual Results

We instead see this:

```
document click
button click
document tap
button tap
```
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11
### Versions

- Polymer: vX.X.X
- webcomponents: vX.X.X

**Comment by azakus** [comment]
It looks like you only have the tap listener on document, which means button will receive click well before the event bubbles to the document tap recognizer.

Since gesture event listeners are not capturing, this is working as I would expect.

**Comment by arthurevans** [comment]
Is the fact that gesture events can't useCapture something we should document? Currently not mentioned.

Also, the Polymer.Gestures.add() method is not documented here currently:

https://www.polymer-project.org/1.0/docs/devguide/events.html#gestures

Polymer.Gestures doesn't show in the API reference, either:

https://www.polymer-project.org/1.0/api/

**Comment by azakus** [comment]
No one should really use `Polymer.Gestures` directly in my opinion.
Everything useful there is exposed in `Polymer.Base` (`Polymer.Gestures.add` is the underlying api to `Polymer.Base._listen` for gesture events).

I think the fact that gestures are not capturing is fine to document. Technically you _could_ make a capturing gesture listener, but it would rely on the a bubbling event to hit a recognizer first.

**Comment by valdrinkoshi** [comment]
Orthogonal/related to this: inline listener for `tap` won't work (e.g. `<button ontap="doSomething()">` http://jsbin.com/sabega/2/edit?html,output

**Comment by azakus** [comment]
Yeah, that will never work. Inline handlers like that are only fired for native events.

**Comment by valdrinkoshi** [comment]
Understood.
While I understand that on desktop we need to depend on `click` in order to fire `tap`, can we at least have intercept the `document.click` and fire the `tap` before any other `click` event?
Either
```
document click
document tap
button click
button tap
```
or
```
document click
document tap
button tap
button click
```

**Comment by dbatiste** [comment]
I've encountered a similar issue - apologies if it's different.  This is what I observe:

mobile: touch-start, tap, touch-end, focus, click
desktop: focus, tap, click

In a case where tapping on an opener (ex. a flyout menu) where focus should be moved to the first menu item, on mobile the focus is subsequently moved out back to the opener where the tap event occurred.  Perhaps I am using on-tap (on opener) when I should not be?
