### ISSUE TITLE
Cannot get secend time the same content

### ISSUE THREAD

**Issue by a8775** [Polymer/polymer#3486]
Hi,

What I would like to accomplish is to get two times the same content in two places of my template.

```HTML
<dom-module id="content-select">
  <template>
    <div class="content-wrapper">
      <content select=".direct-child-1"></content>
      <content select=".direct-child-1"></content>
      <content select=".direct-child-2"></content>
    </div>
  </template>
</dom-module>

<content-select>
  <div class="direct-child-1">
     Child 1
  </div>
  <div class="direct-child-2">
      Child 2
  </div>
</content-select>
```

I would like the result to be:
Child 1
Child 1
Child 2

Here is the full code example in jsfiddle:

https://jsfiddle.net/a8775/zw0knde9/

Thanks :)

**Comment by azakus** [comment]
Sorry, you can do that. Elements are only distributed to one insertion point in the ShadowDOM spec: https://w3c.github.io/webcomponents/spec/shadow/#slotting-algorithm
