### ISSUE TITLE
[contenteditable] divs are not style scoped correctly in the shadow DOM.

### ISSUE THREAD

**Issue by notwaldorf** [Polymer/polymer#3489]
Here's a demo of the issue: http://jsbin.com/witelo/edit?html,output

In the Shady DOM, if a custom element `x-foo` has a `.bar br` style, it won't do anything because it's actually being rewritten to `.bar.x-foo br.x-foo` which isn't actually a thing. 

To fix it, you either need to add a `.bar ::content br` rule, or a `this.scopeSubtree` call, and both of these are mysterious.

**Comment by azakus** [comment]
Yep, `scopeSubtree` is required when HTML is added to an element outside of Polymer's control, as in this case.
