### ISSUE TITLE
Consider using an HTML Linter

### ISSUE THREAD

**Issue by gaurav21r** [Polymer/polymer#3490]
I've observed one of the incidental goals of Polymer (and indeed WebComponents in general) is to try to migrate a lot of imperative JS Code to declarative HTML. `iron-ajax` being a golden example of this.

As developers use more and more HTML in their projects (more tags, more nesting, more attributes) I think it should be important to add (and extend) an HTML Linter.

According to our research at https://github.com/rcorp/standard-project-structure/issues/4, 
[HTMLhint](https://github.com/yaniswang/HTMLHint) is the best one out there. How about a standard `.htmlhintrc` file for all **PolymerElements**, **Demos** and **Docs** ?

If it can be included in the starter kit even better!

**Comment by abdonrd** [comment]
I like the idea! Maybe with [`polylint`](https://github.com/PolymerLabs/polylint).

**Comment by gaurav21r** [comment]
@abdonrd Does POlylint support pluggable rules? Also HTMLHint is more popular and general purpose linter for HTML and not just Polymer.

Any specific feature of polylint thats missing in HTMLHint in your opinion?

**Comment by abdonrd** [comment]
I'm not sure, but @garlicnation maybe can help with it. :)

**Comment by gaurav21r** [comment]
@azakus thanks for looking into this. Would like to hear your thoughts!

**Comment by gaurav21r** [comment]
@garlicnation Your thoughts? @abdonrd Any Updates?

**Comment by abdonrd** [comment]
@gaurav21r I haven't news. :(

**Comment by TimvdLippe** [comment]
The [new linter](https://github.com/polymer/polymer-linter) supports various linting rules and can be easily extended. The linter is also integrated in the several editor plugins for smooth integration into your workflow. You can still adopt the HTMLHint if you want to into your own build configuration.
