### ISSUE TITLE
On mobile device (like iPad 2), when there is an element that has action (like button or list item) and it is displayed on top of a paper-input, tapping on the action element will also trigger tap on the  paper-input

### ISSUE THREAD

**Issue by sharon26** [Polymer/polymer#3491]
### Description

I encounter the following Polymer issue:
On mobile device (like iPad 2), when there is an element that has action (like button or list item) and it is displayed on top of a paper-input, tapping on the action element will also trigger tap on the  paper-input.  

Example 1:
1. Click on the "Dialog" button, the dialog is opened and display two buttons.
    Notice that in the screen the "Button 2" is located on top of "text input2"
2. Tap on the "Button 2", and the dialog is closed
    But "text input2" get the focus and keyboard is opened (as if I tap on it). 

Example 2:
1. Click on the "List" paper-dropdown-menu, the list is displayed
    Notice that the last item in the list in over "text input3"
2. Tap on the last item in the list, the item is selected
    But "text input3" get the focus and keyboard is opened (as if I tap on it). 

Tapping on button in a dialog or select item from a list should not trigger tapping on element that it is covered.
#### Live Demo

see video https://goo.gl/photos/YUsm1GFfJXLsvoPh9 

``` html
<link rel="import" href="../paper-input/paper-input.html">
<link rel="import" href="../paper-dropdown-menu/paper-dropdown-menu.html">
<link rel="import" href="../paper-item/paper-item.html">
<link rel="import" href="../paper-listbox/paper-listbox.html">
<link rel="import" href="../paper-button/paper-button.html"> 
<link rel="import" href="../iron-dropdown/iron-dropdown.html">
<link rel="import" href="../paper-dialog/paper-dialog.html">


<dom-module id="tri-people-view">
    <style>
    paper-tabs {
      width: 400px;
    }

    .vertical-section-container {
      max-width: 500px;
    }

    paper-dropdown-menu {
      width: 400px;
    }

    paper-dialog.size-position {
      position: fixed;
      top: 16px;
      left: 16px;
      width: 300px;
      height: 300px;
      overflow: auto;
    }

    </style>

    <template>

    <paper-button on-tap="openDialog"  style="width:200px">Dialog</paper-button>

    <paper-dialog id="dialog"  class="size-position">
      <h2>Dialog Title</h2>
      <p>test.</p>
      <div>
        <paper-button on-tap="func1">Button 1</paper-button>
        <paper-button on-tap="func1">Button 2</paper-button>
      </div>
    </paper-dialog>


    <paper-dropdown-menu label="List" horizontal-align="left">
      <paper-listbox class="dropdown-content">
        <paper-item>AAAA</paper-item>
        <paper-item>BBBB</paper-item>
        <paper-item>CCCC</paper-item>
        <paper-item>DDDD</paper-item>
        <paper-item>EEEE</paper-item>
        <paper-item>FFFF</paper-item>
        <paper-item>GGGG</paper-item>
        <paper-item>HHHH</paper-item>
        <paper-item>IIII</paper-item>
        <paper-item>JJJJ</paper-item>
      </paper-listbox>
    </paper-dropdown-menu>

    <paper-input label="text input1"></paper-input>
    <paper-input label="text input2"></paper-input>
    <paper-input label="text input3"></paper-input>
    <paper-input label="text input4"></paper-input>

    </template>
</dom-module>
<script>
    Polymer({

        is: "tri-people-view",

      openDropdown: function() {
        this.$.dropdown.open();
      },

      openDialog: function() {
        this.$.dialog.open();
      },

      func1: function() {
        console.log("func1");
        this.$.dialog.close();
      }

    });
</script>

<style is="custom-style">
* {
      --paper-item-min-height: 12px;

}
</style>
```
#### Steps to Reproduce

See example 1 & 2 above
### Browsers Affected

- [x] Chrome on Mobile device such iPad 2 mini
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions

- Polymer: v1.2.4
- webcomponents: v0.7.20

**Comment by hypnoce** [comment]
Chrome on iOS devices is no more than a webview running webkit (WKWebWiew since iOS8).
I ran into the same king of issues and it appeared to be the 350ms tap delay on mobile WebKit.
In iOS 9.3 they added a way to remove such delay. But it is only valid in safari >= 9.1 not WKWebView.

Did you get a chance to try your case on safari 9.1 using the fast tap feature ?

**Comment by sharon26** [comment]
Any updates on this issue?
Issue still exist on Devices / Touch screen  Android and iPad with Chrome, Safari, Desktop (device simulator: iPhone, Galaxy).
The touch screen action on one element trigger a touch screen event on the element that it covers.

**Comment by hosing-lee** [comment]
I'm experiencing the same problem, I have added a on-tap on the underlying input field, but no event is trigger although the input field automatically gets a focus.
