### ISSUE TITLE
Style guide not consistent with flex-layout guide

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#3493]
https://www.polymer-project.org/1.0/docs/devguide/styling.html
```Polymer uses Shadow DOM styling rules for providing scoped styling of the element’s local DOM. Scoped styles should be provided via <style> tags placed **inside** the element’s local DOM <template>.```

https://elements.polymer-project.org/guides/flex-layout

That seems like outside to me :p

**Comment by arthurevans** [comment]
This issue was moved to Polymer/docs#1579
