### ISSUE TITLE
Clean the API of Web Components

### ISSUE THREAD

**Issue by javiervelezreyes** [Polymer/polymer#3496]
The public API of a web component is plenty of handy methods that can be publicly accessed from the outside as if they were business methods of the component. Examples of this kind on add-ons in the component API are those described in Utility functions [https://goo.gl/TB7vkx]  or those used for array observation [https://goo.gl/djzhv0]. Nevertheless, this kind of capabilities should not be included as public methods in the API as they are only of interest for web component's developers and not for web component's users.

A better approach to provide this capability is by creating a factory method within the `Polymer` object. Just as an example:

```
Polymer.helper (this).fire (...);
Polymer.helper (this).push ('myArray', 0);
Polymer.helper (this).async (...);
```

Or if you prefer:

```
var utils = Polymer.helper (this);
...
utils.fire (...);
utils.push ('myArray', 0);
utils.async (...);
```

**Comment by kaste** [comment]
The canonical way for privatizing methods is just to give them an underscore. Otherwise it's of course smelly and perhaps confusing that every Polymer custom element implements an array interface. The real issue here is that Polymer leaves perhaps dozens of methods on the prototype that can't be used even by the developer. These are just left behind the registration, pre-creation noise.

**Comment by javiervelezreyes** [comment]
Totally agree with you. May be it could be an improvement for future
versions. Just let me show an example about why this could be relevant from
the practical point of view. In Polymer there is imposible to define an
attribute named 'fire'.


*Javier Vélez Reyes*Ph. D. Computer Science
javier.velez.reyes@gmail.com


*La cura para el aburrimiento es la curiosidad. *
*No hay cura para la curiosidad. **  Dorothy Parker. 1893 - 1967*

[LinkedIn - javiervelezreyes] <http://es.linkedin.com/in/javiervelezreyes/>
[Google+ - plus.google.com/+javiervelezreyes]
<http://gplus.to/javiervelezreyes>
[Youtube - youtube.com/c/javiervelezreyes]
<http://gplus.to/javiervelezreyes>
[Twitter - @javiervelezreye] <https://twitter.com/javiervelezreye>

2016-03-13 1:31 GMT+01:00 Herr Kaste <notifications@github.com>:

**Comment by TimvdLippe** [comment]
Almost all of the Polymer API is now private or protected, leaving very few functions public: https://www.polymer-project.org/2.0/docs/api/elements/Polymer.Element Most of the previously public functions are now protected or deprecated. Thanks for your feedback!
