### ISSUE TITLE
Errors thrown using dom-if templates in combination with dom-repeat's

### ISSUE THREAD

**Issue by fabianbormann** [Polymer/polymer#3497]
### Description

Hi, 
we created a polymer element [gn-map](https://github.com/Greennav/gn-map) to display different maps using a `map-type` property.
Therefore we use dummy elements `gn-map`, `gn-poly`, `gn-point` that are going be replaced with `google-map` or `osm-map`   depending on the `map-type`. In the [implementation](https://github.com/Greennav/gn-map/blob/master/gn-map.html#L30) we use a composition of conditional templates and dom-repeat's and that works pretty good but if the `map-type` changes in runtime many errors will thrown.

> "Uncaught exception(anonymous function) @ polymer.html:1564Polymer.Base._addFeature._notifyListener @ polymer.html:2016(anonymous function) @ polymer.html:1588Polymer.Base._addFeature.fire @ polymer.html:1335Polymer.Bind._modelApi._notifyChange @ polymer.html:1428Polymer.Base.extend._notifyEffect @ 
> ...

Is this happen because of the nested using of dom-repeat's together with dom-if?
Thanks :)
#### Steps to Reproduce
1. git clone https://github.com/Greennav/gn-map.git
2. cd gn-map && bower install
3. polyserve
4. goto http://localhost:8080/components/gn-map/demo/index.html
5. open DevTools and change `map-type` of `<gn-map>` to "OpenStreetMap"
6. change the location (by dragging) and the errors appear the console

![screen](https://cloud.githubusercontent.com/assets/1525818/13557402/d0aac04a-e3ef-11e5-973f-dfcc51cafc82.png)
#### Expected Results

An exchange of the `google-map` by the `osm-map` elements in the DOM without error messages
#### Actual Results

Errors thrown and the `google-map` elements are still visible in the DOM with `style="display: none;"`
### Browsers Affected
- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions
- Polymer: v1.3.1
- webcomponents: v0.7.21

**Comment by TimvdLippe** [comment]
It seems like the original element has been deleted. We can reopen this issue when a JSBin is supplied that shows the problem, which we can debug and hopefully resolve.
