### ISSUE TITLE
reflected properties with leading upper case letter throw exceptions

### ISSUE THREAD

**Issue by azakus** [Polymer/polymer#3500]
#### Live Demo

http://jsbin.com/mocakesixa/edit?html,console,output

### Versions

- Polymer: v1.3.1

**Comment by TimvdLippe** [comment]
Originally discovered at https://github.com/Polymer/polymer/pull/3279#issuecomment-170236517

**Comment by azakus** [comment]
@TimvdLippe Ah yeah. The problem we found is that `-foo` is not a valid attribute, so `setAttribute` calls will throw, which we didn't think about at the time.

**Comment by TimvdLippe** [comment]
@azakus Yes I did not expect it break in this case. Glad at least it is clear where the bug is =]
