### ISSUE TITLE
The custom style shim should stick the `:root` styles on `html` and not `body`

### ISSUE THREAD

**Issue by notwaldorf** [Polymer/polymer#3503]
This is to be able to workaround the `default-theme` issue (https://github.com/PolymerElements/paper-styles/issues/93) by allowing a user to override the `:root` styles present in `default-theme.html` with their own `body {...}` styles. 

I thiiiiink this should work (currently doesn't): http://jsbin.com/revini/edit?html,output

(Sample JSBin using native custom properties: http://jsbin.com/vibadelure/edit?html,output)

**Comment by abdonrd** [comment]
@notwaldorf the example with the native custom properties works for me in Google Chrome v49. :)

**Comment by notwaldorf** [comment]
@abdonrd Yes, but the equivalent one using the custom style shim doesn't, which is what this issue is about :)

**Comment by abdonrd** [comment]
@notwaldorf yes, I said because in the JSBin there are a note: `Note: This only works on Chrome Canary, with the experimental features flag turned on in chrome://flags`
