### ISSUE TITLE
`:last-of-type` selector on a custom element in a `dom-repeat` doesn't match in IE

### ISSUE THREAD

**Issue by garrettn** [Polymer/polymer#3504]
### Description

I have a list of elements being repeated inside a `dom-repeat` template, and I want to apply a bottom border to every element except the last one. I want to use the `:last-of-type` selector to single out the last element (`:last-child` doesn't work because the template element is inserted after the last repeated element in the actual DOM). This works in Chrome, Firefox, and Safari, but not IE (I haven't tested it on Edge but I suspect it would be the same as IE).

The interesting thing is that this appears to occur only when the repeated element is a custom element. With native elements it works just as it should.

I found a workaround by applying classes to the repeated elements based on their index, but I would prefer that the CSS selector work consistently across browsers.
#### Live Demo

https://jsbin.com/fiqoyiyazi/edit?html,output

Even though the `:last-of-type` selector is wrapped in a `:not()`, that doesn't seem to affect whether it behaves as it should. (In other words `:not` is not the problem.)
#### Steps to Reproduce
1. create a custom element with `display: block` applied to the `:host`
2. in another element, put the custom element inside a `dom-repeat` template
3. use CSS to target only the last repeated element using `:last-of-type`, or everything but the last element using `:not(:last-of-type)`
#### Expected Results

The styles should apply correctly to the last element only, or to everything but the last element.
#### Actual Results

All the repeated elements get the same style, as if `:last-of-type` wasn't in the CSS at all.
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge (possibly)
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11
### Versions

- Polymer: v1.3.1
- webcomponents: v0.7.21

**Comment by ebidel** [comment]
I think this is related to the fact that IE doesn't have native `<template>` support and the rest of the browsers do? Edge does :)
