### ISSUE TITLE
dom-repeat: Array property has global state across repeated elements

### ISSUE THREAD

**Issue by johnlim** [Polymer/polymer#3505]
#### Live Demo
Please run the project from https://github.com/johnlim/todo-list/tree/bug

#### Steps to Reproduce
1. Run the app from https://github.com/johnlim/todo-list/tree/bug 
2. This project is a fork from https://github.com/PolymerLabs/todo-list and code changes can be view in commit 7f34c99a60bc9e0ed6817d888131a10bf0be2508
3. Once launched, open the app in a Chrome browser and open the developer tools console
4. Click the todo items
5. You will see from the console log that the array property, myArray is shared across the dom-repeated items (i.e. it stores the ids of the other repeated elements into the array)

#### Expected Results
The array should only store its own id.

#### Actual Results
The array stores other element's ids which indicates that it has a global state.

### Browsers Affected

- [ * ] Chrome (tested only on chrome)
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v1.3.1
- webcomponents: v0.7.21

**Comment by kaste** [comment]
Added a note on your repo.

**Comment by johnlim** [comment]
@kaste Thanks for the note. 

For those who happen to reference this issue, the document mentions ```When initializing a property to an object or array value, use a function to ensure that each element gets its own copy of the value, rather than having an object or array shared across all instances of the element.``` I'm closing this issue since this behaviour is by design. 

I'm just wondering though if Polymer should automatically `ensure that each element gets its own copy of the value` since it's expected that web components are encapsulated  and stand-alone components and having to explicitly handle that makes it a little counter-intuitive.  Just my 2c worth. :)

**Comment by kobleistvan** [comment]
Jesus, it took me 2 days to get here. Why isn't this clearer in the docs?!
