### ISSUE TITLE
Dynamic nature of `ev.target`/`Polymer.dom(ev).localTarget`

### ISSUE THREAD

**Issue by David-Mulder** [Polymer/polymer#3506]
Given

    <paper-input on-keyup="listener"></paper-input>

and in `listener`

    console.log(Polymer.dom(ev).localTarget);
    setTimeout(function(){
        console.log(Polymer.dom(ev).localTarget);
    });

the output will not be the same.

---

Even more confusing if you have in `listener`:

    console.log(ev, ev.target);

the output might end up looking like

![image](https://cloud.githubusercontent.com/assets/46602/13731757/492740b2-e971-11e5-97fc-58454964b120.png)

---

More screenshots and discussion (if the above is unclear) @ https://polymer.slack.com/archives/general/p1457900657000457 . Not entirely sure whether this is just a thing that should be documented or whether it's something that actually needs fixing, but at the very least it can be incredibly confusing and something should be done about it.

**Comment by azakus** [comment]
This is ShadowDOM event retargeting at work (and the Shady equivalent), and is documented here: https://w3c.github.io/webcomponents/spec/shadow/#event-target-retargeting and here: https://www.polymer-project.org/1.0/docs/devguide/events.html#retargeting
