### ISSUE TITLE
API for notifying when element setup has completed

### ISSUE THREAD

**Issue by indolering** [Polymer/polymer#3507]
It would be ideal if Polymer provided an interface so that elements can signal when they have completed setting themselves up.

~~For example, [web-component-tester will run tests](https://github.com/Polymer/web-component-tester/issues/188#issuecomment-125380886) before data bindings have synced up and dom-if elements have completed stamping out the dom.~~ Turns out dom-if changes are handled asynchronously and this is probably a problem to be solved by `<test-fixture>`.

There are also situations when there are more complex interactions between elements, such as observers acting on data bindings from a parent element.  I've also had situations in which I needed data from an API call to initialize an element.  Perhaps this could be addressed by making lifecycle callback async: supplying an optional done() callback and allowing us to return a promise.

**Comment by ebidel** [comment]
It's possible dom-if's would never be stamped (based on the components state). API calls are also not deterministic. How would Polymer know about an API request?

For this type of thing, we recommend the component author determine when an element is "ready" and fire their own event. For example, we did that in the Google Codelab elements to signify when all codelab steps were ready, syntax highlighted, etc. https://github.com/googlecodelabs/codelab-components/blob/f6f5deb690b42e342a9d57ea3b8c95b8538bfc9f/google-codelab.html#L369

**Comment by indolering** [comment]
> It's possible dom-if's would never be stamped (based on the components state).

Ahh, because they might be dependent on a property that is null when things are initially stamped out?

> How would Polymer know about an API request?

By telling Polymer by manually firing an event or calling a function after I've completed setting things up.

>For this type of thing, we recommend the component author determine when an element is "ready" and fire their own event.

So I agree and that's what I did for my own element.  I'm just saying it would be nice if there was a standard "ready" event/API instead of having to reinvent it for each element (and everything that depends on it).

I'm not sure of the right way to do it, it's just something I've had to reinvent multiple times in the exact same way.  We can't cover all use cases, but this just feels like something that should come standard.

**Comment by kbenjamin** [comment]
@indolering Have you tried listening for the `WebComponentsReady` event? It seems to work as you want. Note that it's not a standard event but something the webcomponents.js (or lite) polyfill fires once all the elements in a page are set up.

As @ebidel points out, anything in a `dom-if` won't get set up until the conditional becomes true (and no new event will be fired) but for other use cases it might help.

**Comment by MeTaNoV** [comment]
@kbenjamin  `dom-change` gets fired within all template helper elements, e.g. when the `if` condition of a `dom-if` change.

**Comment by indolering** [comment]
The primary focus of the request is aimed at other setup steps that have to be taken, not just `dom-if` statements.  During instances where I can check the local variables to see if a `dom-if` statement will be executed, I could add a listener for `dom-change` events and trigger a custom "ready" event.  However, it would be nice if there was an API for signaling that my element is ready, so that I don't have to reinvent the wheel each time.  

But this might be out-of-scope, I'm not sure what impact the ready event has on parent elements and I don't necessarily want to delay them from stamping out their `dom`.  Maybe it would be better to create an `iron-init` or `iron-ready` behavior.

**Comment by kbenjamin** [comment]
@indolering Maybe it would be helpful if you could be more explicit about what you'd like to see that goes beyond the lifecycle callbacks, `dom-change` (thanks, @MeTaNoV), and `WebComponentsReady`?

In my experience so far, I've not found a need for more than that combined with property change `observer(s)` to fire up my app regardless of where I'm deep linked to within.

Also, if you've been working with Polymer 1.2 and below, there is a major improvement in 1.3 that resolves much (but not all) of the need to handle delayed data binding issues as data binding now occurs on un-upgraded elements so once they upgrade the `observer(s)` do their thing automatically. See #3492 for some relevant discussion.

**Comment by TimvdLippe** [comment]
This has been natively implemented as [customElements.whenDefined](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/whenDefined)
