### ISSUE TITLE
Register elements lazily at first instance time

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#3508]
When elements are registered, work is done to create the element's prototype (for example, its template is parsed, styles are shimmed, property accessors are created). If elements are registered but not used, for example, at first paint time, then registration work can delay first paint unnecessarily.

By default, Polymer should perform as many registration tasks as possible when the first instance of an element is created.

**Comment by samccone** [comment]
woohoo this is great, @kevinpschaaf @sorvell do you have any profiles with the before and after?

I would love to see the improvement here!
