### ISSUE TITLE
Property naming conventions are not obvious in docs.

### ISSUE THREAD

**Issue by zhaoz** [Polymer/polymer#3511]
The docs do not mention property naming conventions and requirements for properties.

We have broken on things such as naming a property 'FPS', this is not allowed but it is not obvious to all developers.

It would be valuable to have this mentioned in the docs on polymer-project.org

**Comment by TimvdLippe** [comment]
The property name `FPS` is actually allowed, but the implementation broke the code. https://github.com/Polymer/polymer/pull/3501 fixed that. Other than that, any docs updates are @arthurevans ' duty at https://github.com/Polymer/docs

**Comment by ebidel** [comment]
This issue was moved to Polymer/docs#1589
