### ISSUE TITLE
Inline attribute binding as [style$="..."] overwrites the element inline style entirely.

### ISSUE THREAD

**Issue by andreventuravale** [Polymer/polymer#3512]
As a way to set css properties dynamically style$="..." is a nice opiton, however it has a "side effect" (a expected one) that overwrites the inline style of the target element entirely.

It would be nice to have a binding convention or syntax, binding to single properties, or a group of properties only (just the ones specified in the expression), something like:

```html
<div style-color$="{{color}}"></div>
```
Or to only the ones that figures in the expression.

Ex: setting only the color and font-weight and not overwriting the entire inline style.

```html
<div style$$="color: {{color}}; font-weight: {{fontWeight}};"></div>
```

**Comment by ebidel** [comment]
`<div style$="background: red; color: {{color}}; font-weight: {{fontWeight}};"></div>` should already be possible.

**Comment by andreventuravale** [comment]
Umm... I have a scenario where I set a style property programmatically, like:

```javascript
ready: function () {
    this.$.myElement.style.color = 'blue'
}
```
And it works, but as soon as the bindings are written, what I had set, programmatically, is overwritten.
