### ISSUE TITLE
Complement to issue #3512, about the [style$] behavior and alternatives to style binding.

### ISSUE THREAD

**Issue by andreventuravale** [Polymer/polymer#3513]
Complementing the issue #3512:

I have a scenario where I set a style property programmatically, like:

ready: function () {
    this.$.myElement.style.color = 'blue'
}

And it works, but as soon as the bindings are written, what I had set, programmatically, is overwritten.

**Comment by ebidel** [comment]
This is expected, right? Why not apply classes to change the styling. That gives you finer grain control. Or using a combination of `style` and `class`.

**Comment by ebidel** [comment]
Marking as WAI. The expectation is that any manual tweeks to a property/attribute would  be override by bindings. You can use computed bindings, compound bindings, or a combo of `style` and `class` to have more control.
