### ISSUE TITLE
function property binding not working inside dom-if

### ISSUE THREAD

**Issue by Gabez0r** [Polymer/polymer#3515]
The binding of properties of type function does not seem to work as expected inside dom-if. The bound function is never called.

Please consider the following example:

```
<dom-module id="test-element">
  <template>
    <h3>Next paragraph will display 'text' (function property outside dom-if):</h3>
    <p>[[translate('text')]]</p>
    <template is="dom-if" if="[[visible]]">
      <h3>However, the next paragraph will be empty (function property inside dom-if):</h3>
      <p>[[translate('text')]]</p>
    </template>
  </template>
</dom-module>

<script>
  Polymer({
    is: 'test-element',

    properties: {
      translate: {
        type: Function,
        value: function () {
          return function(str) {
            return str;
          }
        }
      },
      visible: {
        type: Boolean,
        value: true
      }
    }
  });
</script>
```

By placing a breakpoint in the translate function, I found that it is called in the first paragraph but ignored in the second paragraph, inside the dom-if, which results in it being empty.

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [ ] Edge (possibly)
- [x] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v1.3.1
- webcomponents: v0.7.21

**Comment by kaste** [comment]
That's a bug in the annotator. I'll try a PR.
