### ISSUE TITLE
It's very easy to create a shared instance array or object property without realising the implications. 

### ISSUE THREAD

**Issue by rasto68** [Polymer/polymer#3516]
Following on from the discussion here:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/polymer-dev/pa_Ak2ATRw8/F_507ptDGQAJ

I managed to get caught out because I had created an array type property with a default value of []. When creating multiple instances of my element this array was then shared across the instances. Although the polymer docs do mention this problem, and the solution, I didn't find the documentation to be particularly clear. I know its a general JavaScript issue, but having a property type that behaves very differently to the other available types leads to confusion.

Another option would be to modify the _configureProperties method to detect array/object property values and output a console message suggesting that the function wrapping workaround be used.

**Comment by samccone** [comment]
dup: https://github.com/Polymer/polymer/issues/2240

**Comment by rasto68** [comment]
I like the idea of getting the linter to pick this up.

**Comment by samccone** [comment]
I will close this and we can migrate the discussion over to 2240
