### ISSUE TITLE
Local install via Bower causing some elements to not render

### ISSUE THREAD

**Issue by jeffdahl** [Polymer/polymer#3518]
### Description
Pulling from local directory after following instructions on https://www.polymer-project.org/1.0/docs/start/getting-the-code.html will not render the prefix and suffix elements of the following example code:
```html
<body>
<paper-input label="total">
  <div prefix>$</div>
  <paper-icon-button suffix icon="clear"></paper-icon-button>
</paper-input>
</body>
```

#### Live Demo
https://jsbin.com/yujoqipazo/1/edit?html,output

#### Steps to Reproduce
1. Move Live Demo code to local machine.
2. Comment out libraries form `https://polygit.org/components/`
3. Insert libraries from Bower install.  For example:
```html
<!-- <base href="https://polygit.org/components/">
  <script src="webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="polymer/polymer.html">
  <link rel="import" href="paper-input/paper-input.html">
  <link rel="import" href="iron-icon/iron-icon.html">
  <link rel="import" href="iron-icons/iron-icons.html">
  <link rel="import" href="paper-icon-button/paper-icon-button.html"> -->

<script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>
<link rel="import" href="bower_components/polymer/polymer.html">
<link rel="import" href="bower_components/paper-input/paper-input.html">
<link rel="import" href="bower_components/iron-icon/iron-icon.html">
<link rel="import" href="bower_components/iron-icons/iron-icons.html">
<link rel="import" href="bower_components/paper-icon-button/paper-icon-button.html">
```

#### Expected Results
_$total______________________X_

#### Actual Results
_total_________________________

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11

### Versions
- Polymer: v1.4.0
- webcomponents: v0.7.21

![screenshot](https://cloud.githubusercontent.com/assets/6977031/13894668/dfd29f34-ed27-11e5-8416-38c647995672.png)

**Comment by ebidel** [comment]
Can you verify that all of these elements are being installed locally and part of your bower.json?

This bookmarklet is also useful for listing unregistered elements:
https://gist.github.com/ebidel/cea24a0c4fdcda8f8af2
