### ISSUE TITLE
Iron-ajax URL prefix

### ISSUE THREAD

**Issue by peter-bocak** [Polymer/polymer#3520]
Improvement tip:
I am using iron-ajax elements in my polymer application for calling backend services. Backend services are published on different URLs for production and development environment:
e.g.: 
Development: backend: http://localhost:8080/rest, polymer app: http://localhost:5000/
Production: backend: https://example.com/rest, , polymer app: https://example.com/

For this reason, It would be better to have an option for setting iron-ajax url prefix globally (somehow) and use only relative urls in iron-ajax.

For the nonce, i've created all iron-ajax elements programmatically in "ready" function, what:

- significantly reduces code readibility 
- it isn't possible to use iron-ajax in declarative way for real (non-helloworld) applications.

### Versions

- Polymer: v1.2.3
- webcomponents: v0.7.20

**Comment by jrajav** [comment]
I feel like this might be a little beyond the scope of iron-ajax, providing "smarter" but more complex logic than just providing AJAX capabilities.

However, that aside, I'd also just like to point out that you can write an API-aware ajax element in a more declarative way, as well. For relatively simple APIs I very often create specialized elements that wrap single API calls (<api-list>, <api-create>), in order to make the API itself declarative within the Polymer app. For APIs that require security tokens, retry logic, or other things that require insight into iron-ajax you can also extend it and overwrite methods to set the url, headers, etc, to create your own <api-ajax> kind of element. And, with either method, you can then introduce a build step to either replace placeholder strings in your elements, or swap out a "local" element for a "prod" api element that knows to replace the localhost:8080 absolute url with a relative url.

**Comment by ebidel** [comment]
Agreed with @jrajav. This feels out of scope for iron-ajax and there are ways to do this in your own setup.

**Comment by peter-bocak** [comment]
Thank you @jrajav for the clarification. I have to agree any global configuration violates component oriented model of polymer. 

I've succefully reimplemented my services in similar way you suggested, but instead of implementing new component, I decide to use behavior feature of Polymer which better fits my needs.

I am leaving the code here, if somebody interested in or want to use similar aproach in his own app:

```
Polymer.ServicesBehaviorImpl = {

backendUrl: {
      createBuckets: serviceBasePath + 'media/createUploadBuckets/{count}',
      // ... other url templates
},

_backendUrl: function(template, params) {
    return template.replace(/{\w+}/g, function(all) {
     var propertyName = all.replace(/[{}]/g, '');
      return ('' + params[propertyName]) || all;
    });
},

callService: function(options) {
      var method = options.method || 'GET';
      var urlTemplate = options.urlTemplate || '[SERVICE_URL_NOT_DEFINED]';
      var responseCallback = options.responseCallback || function() {};
      var errorResponseCallback = options.errorResponseCallback || function() {};
      var data = options.data || {};
      var authenticated = options.authenticated || false;
      var conditionalAuthentication = options.conditionalAuthentication || false;
      var request = document.createElement('iron-ajax');
      var external = options.external || false;
      var authHeader = authenticated || (conditionalAuthentication && this.isAuthenticated());
      var that = this;

      request.method = method;
      if (options.handleAs) {
        request.handleAs = options.handleAs;
      }
      if (options.body) {
        request.body = options.body;
      }
      if (options.contentType) {
        request.contentType = options.contentType;
      }
      request.url = this._backendUrl(urlTemplate, data);
      if (authHeader) {
        request.headers = {
          'Authorization': 'Bearer ' + this._userToken()
        };
      }
      request.addEventListener('error', function(e) {
        // refresh token when expired and call service again
        if (e.detail.request.status === 401 && e.detail.request.xhr.response.reason === 'expired') {
          that.refreshToken(function() {
            request.headers = {
              'Authorization': 'Bearer ' + that._userToken()
            };
            request.generateRequest();
          });
        }
      });
      request.addEventListener('response', function(e) {
        responseCallback(e);
        request.remove();
      });
      request.addEventListener('error', function(e) {
        errorResponseCallback(e);
        request.remove();
      });
      request.generateRequest();
    },

    /** Periodically calls service until it's stopped by stopConditionCallback or explicitly by stopPollingService **/
    pollingService: function(interval, options, stopConditionFunction) {
      var that = this;
      stopConditionFunction = stopConditionFunction || function() {
        return false;
      };

      var serviceId = setInterval(function() {
        if (stopConditionFunction()) {
          clearInterval(serviceId);
          return;
        }
        that.callService(options);
      }, interval);
      return serviceId;
    },

    stopPollingService: function(serviceId) {
      clearInterval(serviceId);
    }

/** service example call *//
createBucketService: function(count, callback) {
      this.callService({
        authenticated: true,
        method: 'POST',
        urlTemplate: this.backendUrl.createBuckets,
        responseCallback: callback,
        data: {
          count: count
        }
      });
    }
}
```
