### ISSUE TITLE
Mixed content error - google fonts?

### ISSUE THREAD

**Issue by chriswalz** [Polymer/polymer#3522]
#### Expected Results
No error is thrown

#### Actual Results
Repeated Mixed content errors: 

Mixed Content: The page at 'https://example.firebaseapp.com/' was loaded over HTTPS, but requested an insecure font 'http://themes.googleusercontent.com/static/fonts/rosarivo/v1/OGdIq-p0tOtBN2VMVvO9W_esZW2xOQ-xsNqO47m55DA.woff'. This request has been blocked; the content must be served over HTTPS.

A single Uncaught RangeError: Maximum call stack size exceeded' error

### Browsers Affected
 (only ones I've tested)
- [x ] Chrome
- [x ] Safari 9

### Versions

- Polymer: v1.4.0
- webcomponents: vX.X.X 

Is there a way to fix this? I'm also getting another error 'Uncaught RangeError: Maximum call stack size exceeded'

**Comment by Bamieh** [comment]
@chriswalz i believe the Uncaught RangeError has nothing to do with the font. Usually this happens when you try to put events on a HUGE list, or an infinite loop, etc.

you can load the font over HTTPS with the same link, maybe you can try to change it and see whats the result afterwards?

**Comment by ebidel** [comment]
This issue tracker is for the Polymer core library.
