### ISSUE TITLE
lazyRegister: Uncaught TypeError: Cannot read property '_catchFirstRender' of undefined

### ISSUE THREAD

**Issue by fleckdalm** [Polymer/polymer#3523]
When settings lazyRegister to true, the site doesnt load and there seems to be an exception in the api:
`polymer-micro.html:164 Uncaught TypeError: Cannot read property '_catchFirstRender' of undefined(anonymous function) @ polymer-micro.html:164checkDone @ webcomponents-lite.js:1196watchImportsLoad @ webcomponents-lite.js:1219(anonymous function) @ webcomponents-lite.js:1167whenDocumentReady @ webcomponents-lite.js:1185checkReady @ webcomponents-lite.js:1180`
unfortunately until now i was unable to track down what exactly is causing the exception.

**Comment by Bamieh** [comment]
@fleckdalm
I tried lazy loading polymer alone with some custom components and it did work, maybe you have neon animation loaded?
```
As of this release there is a known issue with the neon animation elements not working when lazy registration is enabled.
```
to fix that, follow the following text in the release note:
```
If you have specific element that relies on the default (immediate) registration behavior, call ensureRegisterFinished on its prototype:

var EagerElement = Polymer({ is: "eager-element"});
EagerElement.prototype.ensureRegisterFinished();
```

**Comment by sorvell** [comment]
We'll need more information to act on this report. Can you please provide a link to a reduced test case or a live example the shows the problem? Thanks.

**Comment by fleckdalm** [comment]
Sorry guys, I'm working on a project for my company (which is still in early development) so I'm unable to provide any real source code. Additionally I tried to track down the bug for an hour without any success and unfortunately I really can't invest any more time in this at the moment. 

I can definitely say that its not the fault of the neon elements as I tried removing all of them from the project without any success. Also it seems to be no timing problem as I tried wrapping the call to ensureRegisterFinished() in a setTimeout without success. I also tried removing some of my other dependencies but I have just too much to try all. 

Here is my bower.json, maybe this is of any help for you:
`{
  "name": "",
  "private": true,
  "dependencies": {
    "iron-elements": "PolymerElements/iron-elements#^1.0.0",
    "neon-elements": "PolymerElements/neon-elements#^1.0.0",
    "page": "visionmedia/page.js#~1.6.4",
    "paper-elements": "PolymerElements/paper-elements#^1.0.1",
    "platinum-elements": "PolymerElements/platinum-elements#^1.1.0",
    "polymer": "Polymer/polymer#^1.2.0",
    "iron-swipeable-pages": "^1.0.4",
    "google-map": "GoogleWebComponents/google-map#^1.1.10",
    "vaadin-combo-box": "^1.0.0-alpha5",
    "jv-datepicker": "^2.1.9",
    "paper-date-picker": "polymer-paper-date-picker#^1.1.2",
    "paper-stepper": "polymer-paper-stepper#^1.1.0",
    "paper-time-picker": "^1.1.1",
    "gold-elements": "PolymerElements/gold-elements#^1.0.1",
    "gold-iban-input": "^1.0.0",
    "lazy-pages": "^0.8.5",
    "app-layout": "PolymerLabs/app-layout#^0.0.14",
    "vaadin-date-picker": "^1.0.0-alpha4"
  },
  "devDependencies": {
    "web-component-tester": "^4.0.0"
  },
  "ignore": [],
  "resolutions": {
    "polymer": "^1.2.4",
    "iron-list": "^1.0.0",
    "web-animations-js": "2.1.4",
    "app-layout": "^0.0.14"
  }
}
`
And my index.html with most of the code stripped out:
`<html lang="en">

<head>
    
    <link rel="stylesheet" href="styles/main.css">
    
    

    
    <script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>
    <script>
        window.Polymer = {lazyRegister: true};
    </script>
    
</head>

<body class="loading">
<span id="browser-sync-binding"></span>
<template is="dom-bind" id="polymerApp">
</template>


<link rel="import" href="elements/elements.html"/>


<style is="custom-style" include="shared-styles"></style>



<script type="text/javascript" src="cordova.js"></script>

<script type="text/javascript" src="scripts/load_cordova.js"></script>
<script type="text/javascript" src="js_libs/jQuery.1.12.0.js"></script>
<script type="text/javascript" src="js_libs/velocity.min.js"></script>
<script type="text/javascript" src="js_libs/velocity.ui.js"></script>
<script type="text/javascript" src="js_libs/tinycolor.js"></script>



<script src="scripts/app.js"></script>

<script type="text/javascript" src="scripts/utils.js"></script>
<script type="text/javascript" src="scripts/main.js"></script>

</body>

</html>`

Hope this is at least somehow useful - if you have any questions I will be eager to answer them! Thanks for your help!

**Comment by fleckdalm** [comment]
I have no idea why but it seems no to be related to lazy loading but to the polymer settings in general.
I tried setting the dom setting by copying the code snippet from here (https://www.polymer-project.org/1.0/docs/devguide/settings.html) and inserting it at the right point (see my structure above) and the same error happens.

**Comment by Everlag** [comment]
I'm having the same issue myself in trying lazyRegister for my company's project. Even more, I also can't set any of the the settings without getting the same issue.

I tried reproducing the issue in PSK, which my project started from, but had no luck. The repo with my changes is [here](https://github.com/Everlag/psk-lazyRegister-reproduce). I lazily instantiate individual routes but that doesn't seem to be the cause.

**Comment by NicolasRannou** [comment]
Hi guys - had the same issues an the "fix" is to import you elements asynchronously:

BAD:
``` 
  ...
  <link rel="manifest" href="/manifest.json">
  <script src="/bower_components/webcomponentsjs/webcomponents-lite.js"></script>

  <link rel="import" href="/src/chris-ultron/chris-ultron.html">
  ...
```

GOOD:
```
  ...
  <link rel="manifest" href="/manifest.json">
  <script src="/bower_components/webcomponentsjs/webcomponents-lite.js"></script>

  <link rel="import" href="/src/chris-ultron/chris-ultron.html" async>
  ...
```

**Comment by Everlag** [comment]
That fixed the issue for me. It seems odd that it should work but thanks for finding a solution.

**Comment by ankon** [comment]
I ran into this issue after applying crisper on my index.html file.
~~~~
gulp.src('app/index.html')
.pipe($.crisper({ scriptInHead:false })))
...
~~~~

The problem is that crisper in that configuration moves the lazyRegister code block in index.html to the bottom. Moving the reference back to _before_ the first element import fixes things.

So, I guess loading the elements asynchronously just reorders things properly again (depending on browser)?

**Comment by schlm3** [comment]
Today, I debugged a very similar error within our app. We switched to PRPL-Pattern (lazy loading) a few days ago and some functionality was not working anymore, giving us 
`"Uncaught TypeError: Cannot read property '_createEventHandler' of undefined at TemplateInstance._listenImpl [as listen] (polymer.html:4474) at TemplateInstance._marshalAnnotatedListeners (polymer.html:494) at TemplateInstance._constructorImpl (polymer.html:4459) at new TemplateInstance (polymer.html:4274) at HTMLElement.stamp (polymer.html:4498) at HTMLElement._createPool (iron-list.html:925) .... "`
 I've tried the suggested workarounds above, but none of them helped.
Finally I found the error in a missing import statement (iron-list) in one of our custom components.
Hope it helps other users to find the cause of similar problems.

**Comment by visionscaper** [comment]
FYI, I came across this issue after someone had repurposed the top-level <template> as a dom-if template, thus there was no top-level <template> wrapper in the component definition. :-/

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with Polymer 2 for us to be able to debug and potentially fix. Polymer 2 fixes a large amount of issues, probably including this one as well.

Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with Polymer 2.  Thank you!
