### ISSUE TITLE
lazyRegister: elements in <content> happens too early

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/polymer#3524]
### Description

When using `lazyRegister = true`, elements first rendered inside a `<content>` of a different element causes the registration to happen too early. Instead of registering on actual stamping time of `<content>`, the element is registered when the parent container element is stamped.
#### Live Demo

https://jsbin.com/metuqakuyu/edit?html,console,output
#### Steps to Reproduce
1. Open the JSbin
2. Observe that `parsing x-foo` is outputted to the console
3. Observe that `parsing x-bar` is outputted to the console after 1 second
4. Observe that `parsing x-bar-child` is outputted to the console after 1 second
#### Expected Results

`parsing x-bar-child` is outputted to the console after 2 seconds
#### Actual Results

`parsing x-bar-child` is outputted to the console after 1 second
### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions
- Polymer: v1.4.0
- webcomponents: v0.7.21

**Comment by sorvell** [comment]
Unless I am mistaken about the setup, this is expected behavior.

Looking at the jsbin, The `x-bar-child` element is created when the `dom-if` inside `x-foo` stamps its content, at the same time as the `x-bar` element. That the `x-bar` element distributes `x-bar-child` to an insertion point is a detail about itself which should not influence the lifecycle of the `x-bar-child` element.

**Comment by TimvdLippe** [comment]
We are using this pattern in our routing solution. We have an `iron-pages` element with `div`'s with the correct routes. Then inside the divs, we have zero or more checks. For example: Is the user logged in? The checks use the decorator pattern by using `<content>`; each decorator defines a condition with `dom-if` where the `<content>` is placed and a possible fallback if the condition was false.

This solution would greatly benefit from lazy-registering as a regular routing solution, as we do not want to register page-elements that we do not require on page load. However, as they are placed inside the `iron-pages`, the above described issue happens and the elements are registered on page load.

**Comment by kf6nux** [comment]
@TimvdLippe We are following a similar pattern.  What work around are you using in the mean time?  Currently, I'm looking at dynamically creating/inserting elements into the `iron-pages`, but I'd love to hear alternative solutions.

**Comment by TimvdLippe** [comment]
At the moment it does not work and I have not been able to figure out a nice workaround. Sorry :(

**Comment by TimvdLippe** [comment]
Closing this issue as working as intended. Whenever elements are in the light dom, they will be registered at the moment the parent of the light dom is registered.
