### ISSUE TITLE
Workaround for escaping annotations with “square-brace” / “curly-brace” syntax

### ISSUE THREAD

**Issue by leogr** [Polymer/polymer#3527]
**Issue**
Assume you need to set the literal value `[[WIP]]` to an element's property (or an attribute). 

Due to the "square-brace" syntax (`[[]]`), the following code does not work:

``` html
<my-element title="[[WIP]]"></my-element>
```

The reason is that the [annotation parser](https://github.com/Polymer/polymer/blob/d385873e3696aade3d122cb1c28f0ce8f6af4b35/src/lib/annotations/annotations.html) treats `[[WIP]]` as an annotation for data binding.

Currently, I have not found any documented way to escape the “square-brace” / “curly-brace” syntax. I just found [this TODO](https://github.com/Polymer/polymer/blob/d385873e3696aade3d122cb1c28f0ce8f6af4b35/src/lib/annotations/annotations.html#L111):

``` js
    // TODO(kschaaf): We could modify this to allow an escape mechanism by
    // looking for the escape sequence in each of the matches and converting
    // the part back to a literal type, and then bailing if only literals
    // were found
    _parseBindings: function(text) {
```

**Use cases**
Escaping annotation can be very useful when you work with server-side generated HTML, or when you need to pass a JSON serialised string, for example:

``` html
<my-element values='{"foo":"{{baz}}"}'></my-element>
```

**Workaround**
But I found a working workaround doing so:

``` html
<my-element title="[[serialize('[[WIP]]')]]"></my-element>
```

It works because `template` has the `serialize` method that does nothing when the input is a `String`, as documented [here](https://www.polymer-project.org/1.0/docs/devguide/properties.html#attribute-serialization), and so the first passed param is returned untouched.  

**Questions**
I don't think that it's a definitive solution but I would like to know:
- Is it an acceptable way to escape the annotation syntax?
- Is there a better way to escape the annotations? 
- Or will it be available in next release?

Currently, I'm just trying to understand which is the best approach for this use case.

> I used the `[[..]]` syntax as example, but it works for `{{..}}` too
> This workaround could also work for https://github.com/Polymer/TemplateBinding/issues/186

**Comment by leogr** [comment]
The https://github.com/Polymer/polymer/pull/3529 could be a definitive solution

**Comment by TimvdLippe** [comment]
@leogr was correct that that PR was intended to implement this. However, we decided to not configure this globally. Rather you can implemented this functionality yourself in `_parseBindings`. For more info see https://github.com/Polymer/polymer/pull/3529#issuecomment-329634308
