### ISSUE TITLE
Custom instance properties for `dom-repeat`

### ISSUE THREAD

**Issue by MeTaNoV** [Polymer/polymer#3534]
### Description

`dom-repeat` is currently defining two instances properties, namely the one specified by `as` and `indexAs`. I have a use case, where I would like to introduce my own set of instance properties, like in the following:

``` html
<template is="dom-repeat"
          items="{{computeArrayKeys(profile.favorites)}}"
          as="favorite" strip-whitespace>
  <firebase-document
    location="{{computeGameLocation(favorite)}}"
    data='{{_game}}'>
  </firebase-document>
  <a class="menu-content" data-route="game" href$="[[baseUrl]]game/[[favorite]]">
    <iron-icon icon="bgo:game"></iron-icon>
    <span>[[_game.name]]</span>
  </a>
</template>
```

where `_game` would be an example
### Solution

Introduce a `customInstanceProperties` array property for `dom-repeat` that is used to initialize `instanceProps` in `ready` function. The example would then be something like:

``` html
<template is="dom-repeat"
          items="{{computeArrayKeys(profile.favorites)}}"
          as="favorite" strip-whitespace
          custom-instance-properties='["_game"]'>
  <firebase-document
    location="{{computeGameLocation(favorite)}}"
    data='{{_game}}'>
  </firebase-document>
  <a class="menu-content" data-route="game" href$="[[baseUrl]]game/[[favorite]]">
    <iron-icon icon="bgo:game"></iron-icon>
    <span>[[_game.name]]</span>
  </a>
</template>
```

The portion of code would go in `ready`

``` javascript
...
      this.customInstanceProperties.forEach(function(customInstanceProperty) {
        this._instanceProps[customInstanceProperty] = true;
      })
...
```

I can propose a PR to add this functionnality.

**Comment by TimvdLippe** [comment]
Could you give an example output of `computeArrayKeys`? I think that `_game` is a property of index. If that is true, how would this extra `instanceProps` be benificial over `{{index._game}}`?

**Comment by MeTaNoV** [comment]
If `_game` was a property of index, there would be no need for this... In this example, `items` will be an array of key, and for each of those key, I need to retrieve the associated information.

**Comment by ktiedt** [comment]
I briefly commented on slack but will put the full statement here. This doesn't really explain what you are asking for, at least not very well. For instance, what is `_game` and where does it come from?

It really seems like you are just asking for another way to define a computed binding if I am reading this correctly.

**Comment by arthurevans** [comment]
I think what @MeTaNoV is asking for is a place to stick generated values associated with the template instance.

In this case, I think it could be accomplished by changing `computeArrayKeys` to return an array of objects: `{key: someKey}`, and then do:

    <firebase-document
    location="{{computeGameLocation(favorite.key)}}"
    data='{{favorite._game}}'>

I'm not sure offhand how well this approach will work. Another approach would be to have the component manage its data loading more actively.

**Comment by MeTaNoV** [comment]
you are right @arthurevans , that it exactly the use-case I pointed out. 

Your workaround is probably working but it kinda seems weird to "allocate" some place for instance binding othe input array of the `dom-repeat`.

I would prefer to explicitely declare the instance variables I am going to use like one does in the `properties` of a Polymer element.

**Comment by fleckdalm** [comment]
I agree with @MeTaNoV!
My use case would be to have several google-map components which are connected to google-map-directions components using map={{map}}. All of these pairs should be created multiple times in a dom-repeat. This should easily be possible without the data-bindings of the different dom-repeat items effecting each other. I understand that I could maybe bind it in a way like map={{item.map}} nevertheless I'm not sure if thats a good solution.

**Comment by MeTaNoV** [comment]
Just adding a simpler example, yet pointing out this need:

```html
        <template is="dom-repeat" items="[[spinners]]" as="spinner">
          <div class="actived">
            <paper-checkbox checked="{{active}}">Spinner {{index}}</paper-checkbox>
            <spinkit-element
              active="[[active]]"
              name="[[spinner.name]]"
              color="[[spinner.color]]"
              size="60">
            </spinkit-element>
          </div>
        </template>
```
in that case, active is an output of the `paper-checkbox` to be used directly by the `spinkit-element`. Adding, as @arthurevans mentioned, the active property to the `spinner` element of the array provide a workaround, but it is really not optimal, because someone reading the code therefore think of it as a real array property.
