### ISSUE TITLE
dom-bind needs updated for lazy registration

### ISSUE THREAD

**Issue by deedubbu** [Polymer/polymer#3535]
### Description

`dom-bind` currently has an override of the `_registerFeatures` method which restricts the initialization of the element to a minimum. However, with the addition of the lazy registration feature in Polymer 1.4, a portion of the base functionality of `_registerFeatures` was split off into a separate method named `_finishRegisterFeatures`. The `dom-bind` code was not however updated to override the new `_finishRegisterFeatures` method. While I have not seen this have a negative affect on base Polymer code, I work on a project that has an element that mimics `dom-bind` and we were running into issues with template property accessors being referenced before `__data__` had been initialized. We've fixed this in our code by overriding `_finishRegisterFeatures` with an empty function and figured it was worth opening an issue here to at least make it known for consideration.
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11
### Versions
- Polymer: v1.4+

**Comment by azakus** [comment]
@deedubbu It seems like you said that `dom-bind` is actually working for you? Is this just reporting a perceived inconsistency, or an actual bug with your use of `dom-bind`?

**Comment by deedubbu** [comment]
Only perceived based on the issues our element had. I have not run into issues using `dom-bind`, though to be honest I don't directly use it very often. If there is no need to modify `dom-bind`, feel free to close this issue. Just wanted to make sure it was intentionally not updated when the API split.

**Comment by TimvdLippe** [comment]
This has been removed in Polymer 2 (https://github.com/Polymer/polymer/blob/master/lib/elements/dom-bind.html) and should not be an issue any longer.
