### ISSUE TITLE
gestures does not identify Windows Phones to be touch only.

### ISSUE THREAD

**Issue by zhaoz** [Polymer/polymer#3538]
### Description

https://github.com/Polymer/polymer/blob/fdd49418c348349ad9dd68020b523f28db3722cb/src/standard/gestures.html#L42

This check here does not correctly identify windows phone devices to be touch only.
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11

Ideally we would do feature detection here instead of checking UAs if possible.

**Comment by cdata** [comment]
I would like to second the proposal that we move away from UA testing and prefer feature detection if possible.

**Comment by azakus** [comment]
Unfortunately, UA sniffing is the only way to really tell if TouchEvents will be the expected input, as there are no good cross platform feature detections for "has a mouse attached".

**Comment by cdata** [comment]
I would argue that UA sniffing is ineffective at "really" telling you this as well. It has some probability of being correct, but is still very much a shot in the dark (and will result in a lot of false negatives or false positives depending on how it is used).

**Comment by azakus** [comment]
Absolutely. UA sniffing for touch is the worst option and only option.
