### ISSUE TITLE
Expose synchronous behavior option for attached/detached

### ISSUE THREAD

**Issue by dfreedm** [Polymer/polymer#3543]
Copied from https://github.com/Polymer/polymer/issues/3531#issuecomment-202631009

> @peteblois: Is there any way to force tree construction to be synchronous? This async attached is problematic because it's only sometimes async. Async detached seems to be going in the wrong direction.
> 
> We're trying to eke every millisecond out of startup time that we can- deferring view construction until after the first animation frame just to get consistent load behavior seems like the wrong solution.
> 
> I'd much prefer to be able to make a call to Polymer.RenderStatus.makeReady and have a predictable system.

**Comment by azakus** [comment]
`Polymer.dom.flush` does make attached and detached synchronous, but the first attached is delayed by `renderStatus`, which is async.

It should be possible to make `Polymer.dom.flush` trigger the renderStatus work
