### ISSUE TITLE
<style is="custom-style"></style> as <content></content>

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#3545]
Is it possible to add a new feature to be able to do custom-style as content?

Example use case:
http://stackoverflow.com/questions/36297000/iron-iconset-svg-and-var-primary-text-color

Would be much easier if `<style is="custom-style"></style>` was suported as content

**Comment by azakus** [comment]
Maybe in the glorious future land where CSS Custom Properties are native, and `custom-style` just does selector rewriting. For now, it would be pretty complicated to flow the values correctly when a `<style>` element is distributed.

I don't think we'll support this until CSS catches up.
