### ISSUE TITLE
dom-repeat does not re-render when modifying items property

### ISSUE THREAD

**Issue by tstewart15** [Polymer/polymer#3548]
In the demo below, I maintain a global `items` variable that represents the data that I wish to display in the dom-repeat template.

In an event handler, I attempt to update the display by modifying the global `items` variable, then calling `this.set("myItems", items)` to update the "items" data-binding for the dom-repeat with the newly modified array.

ISSUE: The dom-repeat does not update its item instances with the new value (`selected`).

#### Demo
http://jsbin.com/keyida/4/edit?html,console,output

**Comment by kaste** [comment]
That's a known limitation. Do something like this: http://jsbin.com/kikepe/1/edit?html,console,output

**Comment by arthurevans** [comment]
Yes, currently you need to call `set` for the _exact_ path that changed, there's no way to tell Polymer, "all values under this path may have changed."

(That is an improvement that the core team are looking at for the future—there are cases where this would be very handy.)

**Comment by tstewart15** [comment]
@kaste Thanks! Unfortunately, my jsbin is a simplified version of what I actually have in my application, so the fix is not as trivial.

In my real world app, the "global data array" is being maintained and output from a separate component. My desire is to simply data-bind this output data array directly to the dom-repeat, but the issue from the original demo is what's preventing me from doing so. It will require a lot of additional work to trigger the appropriate deep-path notifications every time the data array is changed, like you've done in your response.

@arthurevans You are correct that this would be very handy! Is there an issue I can track to get updates?

**Comment by kaste** [comment]
I actually have a non-public fork that enables that. Unfortunately it relies on PRs not merged yet. Very painful to do it manually. I've been there.
