### ISSUE TITLE
paper-spinner still takes up space when not active

### ISSUE THREAD

**Issue by lesliana** [Polymer/polymer#3549]
When the paper-spinner is not active, it is aria-hidden and its children have opacity:0, but the <paper-spinner> element itself is still display:inline-block and takes up space (by default, 28x28px).

This means that a user who is trying to click on an element behind the invisible spinner could end up clicking on the spinner, so their click on the element won't appear to work.  The spinner should have display:none or be equivalently hidden and not take up any space when it's inactive.

**Comment by cdata** [comment]
This issue was moved to PolymerElements/paper-spinner#48
