### ISSUE TITLE
Allow read-only properties to participate in upwards data flow.

### ISSUE THREAD

**Issue by kaste** [Polymer/polymer#3551]
Yes, that is participate on `upwards`; restrict like before on `downwards`. 

I think using composition the following element should just work. 

``` html

    <dom-module id="x-ample">
        <template>
            <x-ajax response="{{data}}" url="[[url]]"></x-ajax>
        </template>
        <script>
            Polymer({
                is: 'x-ample',
                properties: {
                    userId: String,
                    url: {
                        computed: '_computeUrl(userId)',
                        readOnly: true
                    },
                    data: {
                        notify: true,
                        readOnly: true
                    },
                },
                _computeUrl: function(userId) {
                    return '/user/' + userId;
                }
            });
        </script>
    <dom-module>

```

Current behavior is, that passing `url` down will work. Yeah, why not, you opted in. But getting the `response` and let it flow up doesn't. That's completely unnecessary b/c that would be opt-in as well.  

Obviously readOnly protects us correctly to not get values from above.

http://jsbin.com/vudovi/edit?html,output

**Comment by kaste** [comment]
Dup of #2632? But this one has the better description/example code.

**Comment by L-u-k-e** [comment]
+1

**Comment by TimvdLippe** [comment]
This change would greatly improve the usecase of writing wrappers around other custom elements. Currently it requires hacks such as `computed: '_is(read-only-property)'` with `_is: function(e) { return e; }` to actually make it work.

**Comment by Nipperstick** [comment]
Essentially a property that can be mutated only at the discretion of it's class is what we would traditionally call _private_.  The data binding rules associated to {{}} and [[]] gives that class control over when the value is provided to its children by reference or by value.  This seems really consistent with normal coding practices.  Would this be better implemented as 'private' instead of as 'readOnly', and deprecate 'readOnly'?

**Comment by Nipperstick** [comment]
This is still a problem in 2.x - can we relabel?
