### ISSUE TITLE
Coma in binding literal

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#3556]
#### Steps to Reproduce
```html
<template is="dom-repeat" items="[[sections]]" as="section">
	[[if(index, ',_', '_')]] [[section.title]]
</template>
<script>
...
	'if'   : function (condition, then, otherwise) {
		return condition ? then : otherwise;
	}
...
</script>
```

#### Expected Results
`_title1,_title2,_title3`

#### Actual Results
` title1 title2 title3` (note, space at the beginning as well)

So, with coma everything goes very wrong, however, with:
```
[[if(index, '+_', '_')]] [[section.title]]
```
Actual result is:
```
`_title1+_title2+_title3`
```

### Versions

- Polymer: v1.4.0
- webcomponents: None, native Shadow DOM

I'll try to take a look later to fix RegExp or somehow in a light way (without full-featured parsing).

**Comment by TimvdLippe** [comment]
So this also took me quite some time to figure out, but then I realized it is intended behavior. You must escape comma's in data-binding expressions: https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#literals

This is a working expression: `{{computeCompound(value, '\,_', value)}}`

**Comment by nazar-pc** [comment]
Thanks, @TimvdLippe, I missed that somehow.

**Comment by jfrazzano** [comment]
thank you!
