### ISSUE TITLE
Changing the implementation of _showHideChildren in Templatizer

### ISSUE THREAD

**Issue by MeTaNoV** [Polymer/polymer#3557]
### Description

Currently the `templatizer` is defining its `_showHideChildren` implementation using CSS `display: none`. While providing a proper behavior most of the time in the browser, it can have some undesired behavior due to Aria constraint. It might be semantically more accurate to use the global `hidden` attribute for such a purpose.
See: 
- http://stackoverflow.com/questions/6708247/what-is-the-difference-between-the-hidden-attribute-html5-and-the-displaynone
  and
- http://w3c.github.io/html/editing.html#the-hidden-attribute

Using the `hidden` would also enable component such as `iron-pages` to be able to be refactored to have a similar behavior using `dom-if` w/ or w/o `restamp` specified by filtering with a `selectable` selector excluding the `hidden` pages which is impossible currently since `display: none` is used to hide the non-selected pages and `dom-if` w/o `restamp` is also `display: none`

To see the difference in the case of `iron-pages` with both kind of `dom-if`, one could play with the following jsbin: http://jsbin.com/xasuxe/edit?html,output

**Comment by TimvdLippe** [comment]
We are keeping the CSS display for now, as this is more optimized and works out of the box. If you would like to use `hidden` instead, you can do so by overriding `_showHideChildren` and implementing it yourself: http://jsbin.com/zuxeziwate/edit?html,console,output
