### ISSUE TITLE
Property bindings on dynamically created elements via Polymer.Base.create

### ISSUE THREAD

**Issue by 43081j** [Polymer/polymer#3559]
### Description

When creating child elements dynamically like so:

    this.$.container.appendChild(this.create('my-element-' + foo, {
        item: this.item
    });

Change notification ("two-way binding") is essentially lost. If the parent changes `item` in some way, the child is never notified and vice versa.

### Example:

[Here](http://plnkr.co/edit/QE7P7tV2PxLZ5BU0wldf?p=preview).

If you click either button, the other doesn't receive the new value. Also, the observer in the parent only fires when the button in the parent is clicked, not the child.

This is true in all 1.x versions by the looks of it.

Is this just by design? If so, what is the recommended way of dynamically creating elements like the above? The tag name needs to be computed in my case.

**Comment by kaste** [comment]
Asked once a week. Close this and follow #3460 instead.

**Comment by azakus** [comment]
Closing for #3460
