### ISSUE TITLE
DOM element that appears in tapped location becomes focused.

### ISSUE THREAD

**Issue by japacible** [Polymer/polymer#3561]
### Description

If I tap on an element that is then switched out with another element (e.g. updated condition for template or hidden attribute), the new element will be focused.

This issue's example will be with paper-menu/paper-item. It affects other elements as well. This is not an issue with just clicking, just touch/tapping.
#### Live Demo

https://jsbin.com/vafubuvivo/edit?html,output
also at https://github.com/japacible/tap-switch-menu
#### Steps to Reproduce
1. Create two menus and populate them. Only allow one menu to be shown at a time; in other words, they should be overlapping. Selecting any item in the menu should switch visibility of the two menus.
2. In Chrome DevTools (Right click > Inspect), force touch sensor (overflow icon > More tools > sensors > Touch). Observe the cursor is now a grey circle.
3. Use the cursor to 'tap' any of the items on the menu.
#### Expected Results

The menus will switch visibility.
#### Actual Results

The menus switch visibility and the newly surfaced item that is where the touch event happened is focused.
### Browsers Affected
- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

I've only tested on Chrome since this was affecting some work in Chromium. See crbug.com/599043.
### Versions
- Polymer: v1.4.0
- webcomponents: v0.7.21

**Comment by ebidel** [comment]
@azakus might have insight into the touch stuff.

**Comment by japacible** [comment]
@azakus friendly ping, any updates on this?

**Comment by japacible** [comment]
@ebidel @azakus friendly ping

**Comment by alexclarkofficial** [comment]
I think this is related to #3704
