### ISSUE TITLE
Huge loading time on iOS safari 

### ISSUE THREAD

**Issue by fleckdalm** [Polymer/polymer#3565]
I have rather big app with about 60 html imports. In Chrome on Desktop it loads in under 1 second and on Android in the webview it needs about 1-2 seconds. However if it's loaded on iOS in the mobile webview the initial loading takes more than 12 seconds! This is really huge and totally unacceptable for production usage! Are there any improvements planned for this in the near future?

**Comment by noahlaux** [comment]
sounds like you have to [vulcanize](https://github.com/Polymer/vulcanize) your project

**Comment by fleckdalm** [comment]
Of course I use vulcanization. My project is based on the polymer starter kit so the whole build process  is in place. It's only on iOS that worse.

**Comment by JanGunzenhauser** [comment]
Vulcanization is not the problem here. Loading the imports is just as fast (or slow) as in other browsers but the time required to render the components varies a lot between them, e.g. Chrome being the fastest and Safari being the slowest (by far, especially on iOS). My uneducated guess would be that it comes down to different levels of supporting web components. Any other explanations?

**Comment by ebidel** [comment]
@fleckdalm do you have a demo page? It would be great if you could run https://gist.github.com/ebidel/57c9e9379ec6b0bda16d and provide the console output here.

**Comment by fleckdalm** [comment]
Unfortunately I don't have a demo page as this is an internal application I'm currently working on and it won't be published soon. 

I'm unable to run your script in iOS Safari (which would be the most relevant) because you are using chrome functions in it. However here is the output from chrome:

> First paint took 237.928955078125 ms
VM32064:9 Load took 3013 ms
VM32064:20 Custom element instances: 565
VM32064:25 === Properties set to reflectToAttribute ===
VM32064:29 paper-ripple.animating
VM32064:29 paper-material.elevation
VM32064:29 paper-material.animated
VM32064:29 paper-tab.link
VM32064:29 paper-input-error.invalid
VM32064:29 google-map.latitude
VM32064:29 google-map.longitude
VM32064:29 app-drawer.opened
VM32064:29 app-drawer.persistent
VM32064:29 app-drawer.position
VM32064:29 app-drawer.swipeOpen
VM32064:29 app-drawer-layout.narrow
VM32064:29 app-header-layout.hasScrollingRegion
VM32064:29 app-header.shadow
VM32064:29 paper-button.raised
VM32064:29 iron-overlay-backdrop.opened
VM32064:29 iron-dropdown.horizontalAlign
VM32064:29 iron-dropdown.verticalAlign
VM32064:29 kwc-i18n.var
VM32064:29 kwc-date-format.output
VM32064:29 vaadin-combo-box-overlay.touchDevice
VM32064:29 vaadin-combo-box.label
VM32064:29 paper-step.opened
VM32064:29 paper-step.editable
VM32064:29 paper-step.selectable
VM32064:29 paper-fab.mini
VM32064:29 paper-progress.disabled
VM32064:29 geo-location.latitude
VM32064:29 geo-location.longitude
VM32064:46 Total properties set to reflectToAttribute: 29
VM32064:52 === HTML Imports load times ===
VM32064:60 2 imports loaded from the main page. Total time: 27.714999999999918ms
VM32064:61 (index)       url                                                                                ms      
                      0              "http://localhost:5000/elements/elements.html"            9.115000000000009
                      1               "http://localhost:5000/elements/lazy-elements.html"   18.59999999999991

**Comment by fleckdalm** [comment]
I suppose its more a general iOS problem but in case its relevant, here is a list of my imports:
```
<!--
@license
Copyright (c) 2015 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
-->

<!-- Iron elements -->
<link rel="import" href="../bower_components/iron-flex-layout/iron-flex-layout.html">
<link rel="import" href="../bower_components/iron-icons/iron-icons.html">
<link rel="import" href="../bower_components/iron-icons/communication-icons.html">
<link rel="import" href="../bower_components/iron-icons/social-icons.html">
<link rel="import" href="../bower_components/iron-icons/maps-icons.html">
<link rel="import" href="../bower_components/iron-icons/image-icons.html">
<link rel="import" href="../bower_components/iron-icon/iron-icon.html">
<link rel="import" href="../bower_components/iron-icons/av-icons.html">
<link rel="import" href="../bower_components/iron-icons/device-icons.html">
<link rel="import" href="../bower_components/iron-pages/iron-pages.html">
<link rel="import" href="../bower_components/iron-list/iron-list.html">
<link rel="import" href="../bower_components/iron-localstorage/iron-localstorage.html">

<!-- Paper elements -->
<link rel="import" href="../bower_components/paper-icon-button/paper-icon-button.html">
<link rel="import" href="../bower_components/paper-item/paper-item.html">
<link rel="import" href="../bower_components/paper-material/paper-material.html">
<link rel="import" href="../bower_components/paper-menu/paper-menu.html">
<link rel="import" href="../bower_components/paper-styles/typography.html">
<link rel="import" href="../bower_components/paper-tabs/paper-tabs.html">
<link rel="import" href="../bower_components/paper-tabs/paper-tab.html">
<link rel="import" href="../bower_components/paper-input/paper-input.html">

<!--Other Polymer Elements-->
<link rel="import" href="profile-vcard/profile-vcard.html">
<link rel="import" href="../bower_components/google-map/google-map-elements.html">
<link rel="import" href="../bower_components/lazy-pages/lazy-pages.html">
<link rel="import" href="../bower_components/iron-swipeable-pages/iron-swipeable-pages.html">

<!--App layout, polymer experiments branch-->
<link rel="import" href="../bower_components/app-layout/app-drawer-layout/app-drawer-layout.html">
<link rel="import" href="../bower_components/app-layout/app-header-layout/app-header-layout.html">
<link rel="import" href="../bower_components/app-layout/app-header/app-header.html">
<link rel="import" href="../bower_components/app-layout/app-drawer/app-drawer.html">
<link rel="import" href="../bower_components/app-layout/app-toolbar/app-toolbar.html">


<!-- Uncomment next block to enable Service Worker Support (2/2) -->
<!--
<link rel="import" href="../bower_components/platinum-sw/platinum-sw-cache.html">
<link rel="import" href="../bower_components/platinum-sw/platinum-sw-register.html">
-->

<!-- Configure your routes here CURRENTLY NOT IN USE -->
<!--link rel="import" href="routing.html"-->

<!--my elements-->
<link rel="import" href="../styles/app-theme.html">
<link rel="import" href="../styles/shared-styles.html">
<link rel="import" href="app-intro/app-intro.html">
<link rel="import" href="my-app-menu/my-app-menu.html">
<link rel="import" href="step-dots/step-dots.html">
<link rel="import" href="authorized-content-view/authorized-content-view.html">

<!--app pages-->
<link rel="import" href="my-efm-page/my-efm-page.html">
<link rel="import" href="schaden-page/schaden-page.html">
<link rel="import" href="beratungs-page/beratungs-page.html">
<link rel="import" href="wissenswertes-page/wissenswertes-page.html">

<!--Lazy loaded elements-->
<!--element imports that can be loaded lazily-->

<!--iron elements are basic, they should never be loaded lazily!-->

<!--other elements sorted by importance-->
<link rel="import" href="../bower_components/paper-input/paper-textarea.html">
<link rel="import" href="login-form/login-form.html">
<link rel="import" href="../bower_components/gold-email-input/gold-email-input.html">
<link rel="import" href="../bower_components/gold-phone-input/gold-phone-input.html">
<link rel="import" href="load-button/load-button.html">
<link rel="import" href="news-post/news-post.html">
<link rel="import" href="../bower_components/paper-dialog/paper-dialog.html">
<link rel="import" href="../bower_components/paper-radio-button/paper-radio-button.html">
<link rel="import" href="../bower_components/paper-radio-group/paper-radio-group.html">
<link rel="import" href="../bower_components/paper-checkbox/paper-checkbox.html">
<link rel="import" href="../bower_components/paper-toast/paper-toast.html">
<link rel="import" href="my-notification-elements/my-notification-elements.html">
<link rel="import" href="date-picker-button/date-picker-button.html">
<link rel="import" href="../bower_components/kwc-date-format/kwc-date-format.html">
<link rel="import" href="../bower_components/vaadin-combo-box/vaadin-combo-box.html">
<link rel="import" href="schaden-tutorials/schaden-tutorials.html">
<link rel="import" href="timepicker-input/timepicker-input.html">
<link rel="import" href="../bower_components/paper-stepper/paper-stepper.html">
<link rel="import" href="../bower_components/paper-stepper/paper-step.html">
<link rel="import" href="process-arrow/process-arrow.html">
<link rel="import" href="audio-text-input/audio-text-input.html">
<link rel="import" href="../bower_components/paper-fab/paper-fab.html">
<link rel="import" href="../bower_components/paper-spinner/paper-spinner.html">
<link rel="import" href="../bower_components/neon-animation/neon-animated-pages.html">
<link rel="import" href="../bower_components/neon-animation/neon-animations.html">
<link rel="import" href="../bower_components/paper-audio-player/paper-audio-player.html">
<link rel="import" href="message-with-files/message-with-files.html">
<link rel="import" href="../bower_components/geo-location/geo-location.html">
```

**Comment by ebidel** [comment]
That's quite a few elements. One thing I immediately see is that you're bringing in all of the icon sets and bundles like google-maps-elements. Do you need all those or can you be more selective? e.g. only import the icons and map elements you need. 

Also double check that you're still using all these imports. All these element registrations come with a cost, so be sure you're only using what you need. Lazy loading can also be your friend.

**Comment by ebidel** [comment]
I'm going to close this b/c there's nothing actionable we can take from this bug. Ultimately, it looks like you can do much more in slimming down the imports you're using and lazy loading stuff where possible.

**Comment by fleckdalm** [comment]
@ebidel 

Unfortunately I really need all those elements. In addition to that I'm already doing lazy loading which improves the situation a bit but I have to load a certain set of elements at the beginning (for the user to see at least some content) and while loading the lazy elements the app is very laggy so thats also not a really good solution.

Anyway, my point was not only that performance should be generally improved (which would be good as well) but also that performance is ok everywhere except Safari (on Mobile) and this could be something you could work on.

**Comment by YingshanDeng** [comment]
@ebidel Hello, In my project, I also have encountered this problem and don't know how to do. This is the demo page: http://dev.d.wps.cn/v/8kZOB. You can open in iOS Safari and found that have long time to show the page but work well on PC or Android. Any guide, thank you! 😀

**Comment by YingshanDeng** [comment]
@ebidel I found the problem which make the page has huge loading time. 
![image](https://cloud.githubusercontent.com/assets/7246595/16943439/538fc468-4dce-11e6-9069-f69742613593.png)
In my project, I found that parse the CSS take too much time.  In my project, there is a component html file which has 1000 line css 😱. And I remove it all then run again. work well. 
But I don't know why the parse css text cost so much time? How to solve this problem? Thank you!

**Comment by YingshanDeng** [comment]
Sorry, Finally I found it is I converts the image to base64  in the component html file that make the parsing css slow. And then cause the page loading slow. All deal.

**Comment by ebidel** [comment]
@YingshanDeng can you post a jsbin with an example?

**Comment by YingshanDeng** [comment]
@ebidel It is my problem. In my component file.
```
<dom-module>
	<template>
		<style>
			.a {
				background-image: url(...);
			}
			.b {
				background-image: url(...);
			}
			.c {
				background-image: url(...);
			}
			/* ... */
		</style>
	</template>
</dom-module>
```
And when I run gulp tasks to build the release file, there is a task css-base64 will transform all resources found in a CSS into base64-encoded data URI strings. So the css text become very big.And it make the polymer parse the css text long time.
```
gulp.task('css-base64', function () {
    return gulp.src([
        'dist/styles/**/*.css', 
        'dist/views/**/*.html'
    ], {base: 'dist'})
        .pipe(cssBase64({
            maxWeightResource: 20 * 1024, // bytes
            extensionsAllowed: ['.gif', '.jpg', '.png', '.svg']
        }))
        .pipe(gulp.dest('dist/'));
});
```
Now I remove this task, and it work well and load the page fast. And the right way to solve the background image link is to covert a set of images into a spritesheet. I'm doing this now.

Thank you for you reply. 😀

**Comment by motss** [comment]
@YingshanDeng What is the average size of your images?

This might help, I think.
https://youtu.be/iAgSvlYavX0?t=10m35s
