### ISSUE TITLE
preventDefault only works in a tap handler if the source was a click, not a touch

### ISSUE THREAD

**Issue by lesliana** [Polymer/polymer#3567]
If you call event.preventDefault() in a tap handler, it will only prevent default if the source event was a click, but not if the source was a touch.

This means that if I have a tap handler on a site with touch input and I want to prevent default, I need to add a touchend handler and call event.preventDefault there.  This leads to having two handlers for the same event (a tap and a touchend handler) in many places across the site, which isn't ideal.

In gestures.html (https://github.com/Polymer/polymer/blob/master/src/standard/gestures.html#L395), preventDefault is called for click events only, because for a touch the sourceEvent is Touch (changedTouches[0]) rather than something from the browser's event chain, like touchend.

**Comment by cdata** [comment]
Here is a reduced test case: http://jsbin.com/hisozi/3

It appears as though an unchecked ghost click fires on the `<a>`. The expectation is that this event would be default prevented. However, it appears that it is not being prevented.

**Comment by hypnoce** [comment]
Hi,

seems like touch events are fired [giving an instance of a Touch object](https://github.com/Polymer/polymer/blob/18bf9d4e34cd0bb3463c4d56a52e685709c5acd2/src/standard/gestures.html#L668) as sourceEvent.
The Touch object has no preventDefault method. Therefore, in the fire method, even if preventDefault is called on a tap event, [the original event won't be default prevented](https://github.com/Polymer/polymer/blob/18bf9d4e34cd0bb3463c4d56a52e685709c5acd2/src/standard/gestures.html#L393).

I have the same issue when I want to prevent default a track event.

Thanks

**Comment by eeid26** [comment]
as a workaround

Try to add a touchstart handler to your listener object that has tap or track handlers. You can call preventDefault on the event you receive. This event is the same event that started the tap or the tracking. 

```javascript
    listeners : {
      'touchstart': '_preventDefault',
      'tap': '_tapHandler'
     },

    _preventDefault: function(event) {
      event.preventDefault();
    }

```

**Comment by hypnoce** [comment]
@azakus In the polymer documentation, it says 
> sourceEvent—the original DOM event that caused the [...] action
But in case of touch events, this is not the case. Do you think the doc should be changed ? Or maybe the sourceEvent should be the actual event and use another object to get event positions.

**Comment by thearegee** [comment]
Any movement on this?

**Comment by thearegee** [comment]
@azakus is there any movement on this?
