### ISSUE TITLE
proposal for lazy custom event firing

### ISSUE THREAD

**Issue by d1manson** [Polymer/polymer#3568]
Suppose an element wants to offer a custom event to interested listeners, but it requires time/money/whatever to compute the `detail` object for the event. So it would be nice to be able to avoid doing so unless the event actually has some listeners.

In many cases this may seem like an over-the-top optimization, but from the point of view of the element designer it's great because you can have a single "heavy" element that does all kinds of exciting things, with almost zero-overhead if the exciting things are not being used by a given instance of the element.

For example, imagine you are designing a map element and deciding whether to offer a "mousemove-city" event, and/or a "mousemove-restaurant" event. Computing those data requires (a) having a mousemove handler, (b) working out the gps coordinates under the mouse; (c) obtaining a set of candidate cities/restaurants from the cloud/cache and (d) finding the nearest one.  While (a) and (b) are not exactly expensive, (b) and maybe (c) are.  

There are several possible solutions to this:
1. move the nearest-x logic out of the element entirely (i.e. to a basic js handler of some kind)
2. create specialized versions of the component with one or more extra features
3. have an attribute that toggles the handler on/off

Number (1) is un-polymeric as it doesn't give you nice declarative city/restaurant events. It also means the mapping-related code is no longer within the map element, which is bad for maintainability. Number (2) is okish - perhaps the Polymeric way to do this is implementing each event type as a `behaviour`, but then you have to create a separate element definition for each set of behaviours you want to use and you can't easily toggle them on/off...so that could end up being messy too. (3) is also okish, but only works well imperatively or if you know there is only ever going to be a single listener for each event type (because otherwise the listeners need to cooperate in terms of ref counting).

This could be implemented in at least two ways: either there could simply be a `Base.hasListenersFor('someEvent')` method, or, better still, there could be add/remove listener events with names like `'add-listener-some-event'`, `'remove-listener-some-event'`.  Hopefully this wouldn't in itself add a lot of overhead.

**Comment by TimvdLippe** [comment]
I am inclined to close this issue, as it seems very computationally intensive to determine if an event is actually used or not. Nonetheless, I think this optimization is worth exploring and maybe a minifier could be written to achieve this behavior?

@d1manson If you don't object, I am closing this issue soon. Feel free to express your opinion/ideas if you can think of an easy to achieve this!
