### ISSUE TITLE
Element (re)registration errors when loading polymer.html more than once

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#357]
I'm updating the site the latest Thanksgiving Odyssey Bowertopia Feast and running into issues with inline <polymer-element>s. The [recommended]( https://gist.github.com/sorvell/7682389) way is:

    <head>
        <script src="components/platform/platform.js"></script>
        <link rel="import" href="components/polymer/polymer.html">
        <link rel="import" href="components/polymer-ui-menu/polymer-ui-menu.html">
    </head>
    <body>
      <x-hi></x-hi>
      <polymer-element name="x-hi">
        ...
      </polymer-element>
    </body>

In Canary under native stuff, mixing element imports and explicitly loading polymer.html in the main page causes re-registration errors:

![screen shot 2013-11-29 at 12 42 50 pm](https://f.cloud.github.com/assets/238208/1647261/769c6368-5938-11e3-9c13-876d190b3b08.png)

The quick fix is for me to move the element into an import, but **we should make these two scenarios play well together**.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
