### ISSUE TITLE
Only the first template in a polymer-element is processed by the styling shim

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#358]
The instanceTemplate api allows for a custom element to instantiate a template of choice. It's required that this template has already had its styles shimmed. Polymer element does this only to the first template in a polymer element.

It would be better to handle this as templates are used via instanceTemplate. We could shim styles in templates that have not already been processed.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
