### ISSUE TITLE
Inconsistent behaviour of paper drawer panel when dynamically instantiated

### ISSUE THREAD

**Issue by ancellitto** [Polymer/polymer#3581]
The problem occurs when the paper drawer panel is removed and new instance is added to the DOM again.
(I am using the gwt wrapper of polymer and I have reported the same issue in their git hub page aswell.But still now there is no response and i feel the issue is with polymer than the wrapper)
On further inspecting the DOM i  have noticed that DOM changes when it is reinitialized.
Initially the contained elements are added inside an iron selector
![beforedynamicinitialization](https://cloud.githubusercontent.com/assets/6533212/14342071/95c5f9a8-fcb4-11e5-8c32-6989feef6de7.jpg)
On clicking the button on the header panel,the paper-drawer-panel  gets reinitialized.Now the contained widgets are added at the same level as iron selector.
![afterdynamicinitialization](https://cloud.githubusercontent.com/assets/6533212/14342243/e00426ce-fcb5-11e5-8c4a-1e8ca8572e6f.jpg)
Please check the demo project to reproduce the issue.
[Demo Project(this demo is in gwt)](https://github.com/ancellitto/Polymer/tree/master/gwtpolymerdemo)

**Comment by azakus** [comment]
@blasten Can you confirm if this is a Polymer or paper-drawer-panel bug?

**Comment by blasten** [comment]
would take a look

**Comment by TimvdLippe** [comment]
`paper-drawer-layout` has since been deprecated and replaced by [`app-layout`](https://github.com/polymerelements/app-layout). If you are still encountering issues, please open an issue there.
