### ISSUE TITLE
content is undefined when extending template using class syntax

### ISSUE THREAD

**Issue by bedeoverend** [Polymer/polymer#3582]
### Description

`this.content` is undefined when extending `template` using `class` syntax
#### Live Demo

http://jsbin.com/debihucuha/2/edit?html,console,output
#### Steps to Reproduce

1. Create custom element that extends template using ES6 Class syntax
2. Check `content` property on element
#### Expected Results

Should return document-fragment of template
#### Actual Results

Returns undefined
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions

- Polymer: v1.4.0
- webcomponents: v0.7.21

**Comment by azakus** [comment]
This isn't supported yet, but we are considering it for the inheritance implementation.

**Comment by bedeoverend** [comment]
@azakus is this only for extending `template` or others as well? Also - where's the best place to keep track of the inheritance implementation? Thanks

**Comment by TimvdLippe** [comment]
Since inheritance of native elements is not supported in Polymer 2 and class inheritance has been implemented by taking advantage of JavaScript classes, I am closing this issue.
