### ISSUE TITLE
Polymer.Bind - unused `_dataEventCache` question

### ISSUE THREAD

**Issue by MatthewVita** [Polymer/polymer#3588]
Quick question,

It appears that the following event cache store is not being used: https://github.com/Polymer/polymer/blob/master/src/lib/bind/accessors.html#L14

Can I submit a PR removing this or am I missing something w.r.t. to the importance of keeping this around?

Thanks.

NOTE: I didn't feel that I should following the issue submission guidelines since there is no issue with this  -- just a potential clean up item. "Version" is latest Polymer on `master` (1.4.0)

**Comment by kaste** [comment]
Go for it :smile:

**Comment by azakus** [comment]
Looks totally unused.

**Comment by MatthewVita** [comment]
https://github.com/Polymer/polymer/pull/3591 ready to go!
