### ISSUE TITLE
attach-detach-timing tests are flaky

### ISSUE THREAD

**Issue by kaste** [Polymer/polymer#3589]
attach-detach-timing.html mostly succeeds, but once in awhile fails. All three tests in that file show this behavior. I had this on travis builds as well as locally. PTAL @azakus

**Comment by kaste** [comment]
E.g. https://travis-ci.org/Polymer/polymer/builds/123298983

**Comment by azakus** [comment]
Yeah, they've only started to become flaky in Chrome 50. We'll need to investigate that.

**Comment by TimvdLippe** [comment]
We haven't observed the flakiness in a while, therefore I am closing this issue.
