### ISSUE TITLE
perf - notify changes to properties of objects in array

### ISSUE THREAD

**Issue by d1manson** [Polymer/polymer#3595]
In [this jsbin](https://jsbin.com/hojuquyehu/1/edit?html), I have essentialy the following setup:

``` html
<dom-module id="person-x">  /* details omitted */
    <span style$="background:[[personal_info.color]]">[[personal_info.name]]</span>
</dom-module>

<template is="dom-bind" id="app">
     <template is="dom-repeat" items="[[people]]">
         <person-x personal_info="[[item]]"></person-x>  
     </template>
</template>
```

and I try updating the `person.color` value of 100 random people inside a `setInterval` (well it's not really 100 people because some are updated multiple times, but it is still 100 updates).

Using current polymer machinery it takes about 7ms to do this update on my PC, which is not exactly fast.  And, note that this is a kind of best case scenario because there's so few other elements involved and a very shallow hierarchy.

I encountered this perf problem while refactoring an app and ended up writing a "`shortcutNotify`" pair of behaviors to get around it.

In this case, the [new version of the jsbin](https://jsbin.com/berineqeve/edit?html) [_Edit: link updated_] is not that much faster, taking roughly 50% of the time, but for more complex hierarchies and with a greater number of observers hooked into the array this difference is more significant.

Given that I encountered a problem and was reasonably pleased with the solution I thought it was worth sharing it here.

---
### Usage:

The following is to be used when an object has various properties that are known to only be of interest to a very specific set of elements.   The "target" elements should use the `Polymer.ShortcutNotifyTargetBehavior()`,  behavior factory function, passing in an array of path strings.  For example:

``` html
<dom-module id="lovely-view">
  <template>
    some_property is: [[my_model.some_property]]
  </template>
  <script>
    Polymer({
      is: 'lovely-view',
      behaviors: [
        Polymer.ShortcutNotifyTargetBehavior(['my_model'])
      ],
      properties: {
         my_model: {
            // whatever
         }
      }
    });
  < /script>
</dom-module>
```

The "notifier" element should use the `Polymer.ShortcutNotifierBehavior`, and then replace calls like this:

``` javascript
this.notifyPath('some_array.#42.some_property', mutated_object.some_property);
```

with this:

``` javascript
this.shortcutNotify('some_property', mutated_object.some_property, mutated_object);
```

Note how here we only use the final suffix for the path, and we provide the actual object as the final argument.

I think this mechanism supports multi-part paths, but I haven't tested it.
### Implementation

``` javascript
(function(){
  let targetsForModel = new WeakMap();
  let OLD_MODEL_PREFIX = '_oldModelFor_';
  Polymer.ShortcutNotifyTargetBehavior = function(paths) {
    return {
      observers: (function(){
        let observers = [];
        for(let [ii, path] of paths.entries()){
          observers.push('_updateShorcutMapping("' + path + '", ' + path + ')');
        }
        return observers;
      })(),
      _updateShorcutMapping: function(path, newModel){
          this._removeAsTargetForModel(path);
          this._addAsTargetForModel(path, newModel);
      },
      attached: function(){
        this._isAttached = true;
        for(let path of paths){
          this._addAsTargetForModel(path, this.get(path));
        }
      },
      detached: function(){
        this._isAttached = false;
        for(let path of paths){
          this._removeAsTargetForModel(path);
        }
      },
      _removeAsTargetForModel: function(path){
        let oldModel = this[OLD_MODEL_PREFIX + path];
        let oldTargets;
        if(oldModel && (typeof oldModel === "object") && (oldTargets=targetsForModel.get(oldModel))){
          let oldIdx = -1;
          for(let [ii, target] of oldTargets.entries()){
            if(target.el === this){
              oldIdx = ii;
              break;
            }
          }
          if(oldIdx !== -1){
            if(oldTargets.length === 1){
              targetsForModel.delete(oldModel); // this was the only remaining target for the given model
            } else {
              oldTargets.splice(oldIdx, 1); // there are still other targets observing this model
            }
          }
        }
      },
      _addAsTargetForModel: function(path, newModel){
        if(this._isAttached && newModel && (typeof newModel === "object")){
          let newTargets = targetsForModel.get(newModel);
          if(!newTargets){
            newTargets = [];
            targetsForModel.set(newModel, newTargets);
          }
          newTargets.push({
            el: this,
            prefix: path
          });
          this[OLD_MODEL_PREFIX + path] = newModel;
        }
      }
    }
  };
  Polymer.ShortcutNotifierBehavior = {
      shortcutNotify: function(path, value, model){
        let targets = targetsForModel.get(model) || [];
        for(let target of targets){
          target.el.notifyPath(target.prefix + "." + path, value, true);
        }
      }
  };
})();
```

**Comment by kaste** [comment]
Your second JSBin doesn't use your behaviour; or I'm blind and stupid. Also you use `app.set(...)` in JSBin 1, but said `shortcutNotify` is a replacement for `notifyPath`. :confused: And then: `shortcutNotify` uses notifyPath internally, just with `fromAbove` set to true. (Which is a huge improvement b/c otherwise you fire 200 (!) events up on each interval.)

**Comment by d1manson** [comment]
Yeah looks like I managed to not save the final edits to the second jsbin, apologies. (I can't fix it right now, but will do so shortly).

As to the `.set` vs `.notifyPath` - internally the main thing that `set` does is is to call `notifyPath`, so it's pretty much the same thing perf-wise.  And yes, my behavior does indeed use `notifyPath` from above, which allows it to percolate down at the target location, the point is that it gets to the target location directly without traversing the rest of the app's model hierarchy (which can be an expensive operation when arrays with lots of observers are involved).

**Comment by kaste** [comment]
Yeah, but using `set` you cannot set fromAbove. And then you get faster by not doing the same thing. In this case any element above your `x-detail` will not know about the `color` changes. (Which can be ... well ... okay of course.)

**Comment by d1manson** [comment]
Exactly. It's trying to avoid doing the full notify in order to achieve better perf..it is in essence a hack, but one that tries to be sort of close to the standard polymeric way of doing things.

Note that in the example I give here the notification is happening at the top level, the dom bind, but in my actual usage case it was contained within an element itself (i actually had three different elements generating three arrays of graphical plots which had to be shown in a single list grouped by array index).

**Comment by kaste** [comment]
You can look at https://jsbin.com/posirunupo/2/edit?html,output which is roughly twice as fast as your original jsbin. (Using #3596 and fromAbove set to true.)

**Comment by d1manson** [comment]
I've just updated the original jsbin...hopefully I got it right this time.

Before using your PR version, I tried just using Polymer 1.4 with `set(path, value, true)` in my actual app and it didn't work..I wasn't clear whether you thought it should do?  

Then I had a go with your PR, but ran into problems during page load..

![image](https://cloud.githubusercontent.com/assets/4244876/14588739/7f8ecdce-04c8-11e6-8b75-a8061c7644e0.png)

I tried removing my `.shortcutNotify` stuff but it didn't seem to help

If you are interested, you can view the code for my project [here](https://github.com/d1manson/waveform). (You won't be able to do much without some sample data though, which I could provide if you really want.)

**Comment by kaste** [comment]
Sorry for the confusion. The PR is not for production. I just used it here to set fromAbove using `set()`. And the JSBin had no iron-list. FWIW in iron-list it should be
```
-   item._templateInstance[prop] = value;
+   item._templateInstance.__setProperty(prop, value, true);
```

Thanks for the updated JSBin. Got it. Yours is super-fast :+1: :zap:

**Comment by TimvdLippe** [comment]
@d1manson I have updated your JSBin to Polymer 2 and the perf seems quite reasonable: https://jsbin.com/jupaxayoca/edit?html,console,output I recognize this issue is quite old, are you still encountering perf issues?

**Comment by d1manson** [comment]
The project that this issue relates to is not actively being maintained, unfortunately (and is still on polymer 1.7). But, if the jsbin is good in Polymer 2 then i'm certainly happy for this issue to be closed.

**Comment by TimvdLippe** [comment]
Okay thanks for letting us know!
