### ISSUE TITLE
nested <template is="dom-repeat">s use object identity, preventing data binding updates when outer array is set to a new array of the same (updated) objects

### ISSUE THREAD

**Issue by mgiuffrida** [Polymer/polymer#3603]
[Fiddle is worth a thousand words.](https://jsfiddle.net/92g83zgb/7/)

Suppose we have an `Array` property which holds `Array`s:

```
list: {
  type: Array,
  value: [[obj1, obj2,],] // array of arrays of objects
}
```

and we display these in the DOM with `dom-repeat`s:

```
<template is="dom-repeat" items="[[list]]" as="innerList">
  <template is="dom-repeat" items="[[innerList]]">
    <paper-checkbox checked="{{item.enabled}}">[[item.name]]</paper-checkbox>
  </template>
</template>
```

Changing the value of `list` to a new array of the same values:

```
this.list = [[obj1, obj2,],];
```

should (IMO) update all of the data in each dom-repeat. So I should be able to do this:

```
// Invert the `enabled` value of an object in the nested array.
obj1.enabled = !obj1.enabled;
// Set `list` to a new array so Polymer treats it as a new object and re-binds stuff.
this.list = [[obj1, obj2,],];
```

But the nested `dom-repeat` does not update: the checkbox remains the same. I have to do this:

```
this.set('list.0.0.enabled', !this.list[0][0].enabled);
```

In my use case, I am replacing the entire array (it may be ordered differently or use different nested arrays entirely) after updating properties of the underlying objects, but the underlying objects in the nested arrays are drawn from a fixed pool rather than created anew each time.

This also repros for arrays of objects with arrays.

**Comment by kaste** [comment]
All Polymer uses object identity right now. Changing this is not trivial. #3596 for a possible commit path.

**Comment by mgiuffrida** [comment]
This should at least be clearly noted in the docs, especially in cases like templates where you would otherwise expect changes to top-level arrays propagate.

I haven't found a great workaround. Calling `notifyPath` a hundred times for each sub-property, or cloning all sub-objects whenever the top-level property changes, are both icky.

**Comment by web-padawan** [comment]
I faced this issue with 1.9.3 today when trying to reset nested `dom-repeat` containing array of objects with nested arrrays. Should this be considered as "_wontfix_" for 1.x?

**Comment by TimvdLippe** [comment]
This has been fixed in Polymer 2: http://jsbin.com/kesurehipi/edit?html,console,output We will not ship a fix for 1.x as it will be a breaking change in terms of data-binding (as objects are now dirty in Polymer 2).
