### ISSUE TITLE
Binding to text content without escaping HTML

### ISSUE THREAD

**Issue by dandv** [Polymer/polymer#3607]
The PSK includes a list element that iterates through an array of [items](https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/elements/my-list/my-list.html#L49). Conveniently, any HTML string in the items is properly escaped when [binding to text content](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#binding-to-text-content).

Is there a way to pass down raw HTML, without escaping? A use case would be including HTML in that list, e.g.

``` js
ready: function() {
  this.items = [
    'Responsive Web App boilerplate',
    '<a href="https://github.com/PolymerElements/iron-elements">Iron Elements</a> and Paper Elements',
            ....
```

**Comment by TimvdLippe** [comment]
This was proposed in #3362 and rejected due to security concerns.

**Comment by dandv** [comment]
I figured the security implications prevailed; however, nearly all template
languages provide a mechanism for HTML pass-thru, e.g. triple brace in
Mustache/Handlebars.

**Comment by miztroh** [comment]
You can do this now with ``<div inner-h-t-m-l="{{foo}}"></div>``.

**Comment by TimvdLippe** [comment]
Closing per https://github.com/Polymer/polymer/pull/3362#issuecomment-179599413 You can define your own binding parser in Polymer 2 (override [`_parseBindings`](https://www.polymer-project.org/2.0/docs/api/elements/Polymer.Element#method-_parseBindings)) to define your own expressions in a base class.
