### ISSUE TITLE
:host(tag-name) does not work in <style> inside <template>

### ISSUE THREAD

**Issue by mgiuffrida** [Polymer/polymer#3610]
https://jsfiddle.net/vtr4fsgs/

Expected: `.host(x-foo) { color: blue; }` causes the element to be `color: blue`
Actual: the element is unstyled

See [the :host selector](https://drafts.csswg.org/css-scoping/#selectordef-host) and [a working non-Polymer example](https://jsfiddle.net/o5pbbrxf/).

@notwaldorf this is what prevents you from using `:host(paper-item), :host(paper-item-body), :host(paper-icon-item)` in `paper-item-shared-styles.html`.

**Comment by danbeam** [comment]
this is probably related to https://github.com/Polymer/polymer/issues/1952

**Comment by notwaldorf** [comment]
Thanks @azakus! 🍻 🎉
