### ISSUE TITLE
error when re-rendering nested polymer components

### ISSUE THREAD

**Issue by dinnot** [Polymer/polymer#3611]
### Description

Error when re-rendering nested polymer components which make dom manipulations on ready.
#### Live Demo

http://plnkr.co/edit/8F7f86kln7uzjMlnc8x0?p=preview
#### Steps to Reproduce

You have to have the following to make polymer revert to original content after it being manipulated from outside polymer:
1. 2 nested polymer components; 
2. Inner one must do dom manipulation on ready; 
3.  There must be a 3rd party library changing the content of the outer one (like angular or, like in the plnkr above, js dom manipulation);
4. I seem to get this only on polymer >= 1.2.4
#### Expected Results

"old" to change into "new" in 5s
no console logs after "updated"
#### Actual Results

text changed back to "old" immediately after being changed to "new" so "old" is displayed on the screen after 5s
new element detached from dom and old element re-attached to dom after dom update (look in console)
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11
### Versions

- Polymer: v >= 1.2.4
- webcomponents: any

**Comment by kaste** [comment]
Must use the `Polymer.dom()` wrapper. http://plnkr.co/edit/1dFTEwzZlnb1J3dgjZUR?p=preview

**Comment by dinnot** [comment]
Hi @kaste . Thanks for your answer. Unfortunately, although that's a valid fix for the provided plnker, we can't really apply that as in our original case (much larger application) the re-rendering is done by angular. 

I dont know if that would help anybody, but the commit that triggered this problem is: https://github.com/Polymer/polymer/commit/306cc8130e4cab12d6e05eec6097e1ad85220c50

Thank you

**Comment by TimvdLippe** [comment]
The `Polymer.dom()` wrapper has been removed and the integration with Angular should thus be fixed. Please let us know if you are still running into issues.
