### ISSUE TITLE
_warn() is broken

### ISSUE THREAD

**Issue by MajorBreakfast** [Polymer/polymer#3615]
Here's how it looks like if I call `_warn()` in the console (In my app it's called from somewhere inside neon animation). As you can see it's broken for some reason. How did THIS slip through the unit tests? :) I'm using `Polymer@1.4.0`.

![polymer-warn](https://cloud.githubusercontent.com/assets/340142/14769432/461386da-0a58-11e6-932a-a853a72ecedd.jpg)

![polymer-warn2](https://cloud.githubusercontent.com/assets/340142/14769466/0c3620ac-0a59-11e6-84a3-e1eb2343efc7.jpg)

**Comment by kaste** [comment]
Hm, seems like they merged and released code that relies on code which is in Polymer master but not yet released to public.

**Comment by MajorBreakfast** [comment]
Yah, that sounds right. I hope that this is fixed soon. I can't upgrade polymer in my app because of this :(

**Comment by TimvdLippe** [comment]
This has been fixed since and the elements have been updated to reflect this change.
