### ISSUE TITLE
dom-repeat not working fine when trying to swap array objects

### ISSUE THREAD

**Issue by raghav135** [Polymer/polymer#3616]
### Description

dom-repeat not working fine when trying to swap array objects
#### Live Demo

http://plnkr.co/edit/SRSp0Le4vuW3zlmAAJX7?p=preview
#### Steps to Reproduce
1. create a dom-repeat of array
2. swap array objects
3. dom repeat behaving wierdly
#### Expected Results

The array items should match the dom repeat values
#### Actual Results

There is a mismatch between what is shown in dom repeat and what array contains.
### Browsers Affected

Could simulate in chrome 50.0.2661.87 m , firefox 42.0
I dont think it is browser specific
### Versions
- Polymer: v1.4.0 , I could simulate in 1.1 and 1.2 as well
- webcomponents: v0.7.21

**Comment by arthurevans** [comment]
You're swapping the array you're adding a duplicate copy of `src` to the array, which confuses the `dom-repeat`.

Here's a simpler method that doesn't add a duplicate element:

```
var removed = self.splice('arr', srcIndex, 1);
self.splice('arr', destIndex, 0, removed[0]);
```

**Comment by raghav135** [comment]
Thanks for this, infact I suspected this, and tried this code before raising the issue.
It didnt work for me:
                var srcIndex = 0;
                var destIndex = 2;
                var d = self.splice('arr', destIndex, 1);
                var s = self.splice('arr', srcIndex, 1);
                self.splice('arr', destIndex, 0, s[0]);
                self.splice('arr', srcIndex, 0, d[0]);

Kindly note that the code with 1 removal will only work for swapping elements which are next to each other in array.
