### ISSUE TITLE
Feature Request: Global Polymer attributes with data-binding ability. Or global document data-binding.

### ISSUE THREAD

**Issue by myuseringithub** [Polymer/polymer#3618]
Create global parameters with 2 way data-binding which can be used throughout the app.

In some use cases, all the code or custom elements cannot be used inside a main x-app element, rather should be used in document dom for example. In these cases regular data binding through intermediate custom element is not possible. So the rational solution would be a global one (maybe attached to the Document root object or to the Polymer object).

I think these feature will give more approaches to developers & simplify stuff. Not in every case, events up & setting properties down, is possible. 

Thank you.

**Comment by azakus** [comment]
Sorry, I'm not really understanding what you are asking for.
Can you write up an example, maybe with some code?

**Comment by myuseringithub** [comment]
Thanks for replying. In I/O 2016 the problem is explained and a solution is provided, which works great. 
https://youtu.be/__KvYxcIIm8?list=PLOU2XLYxmsILe6_eGvDN3GyiodoV3qNSC&t=1339
