### ISSUE TITLE
Using __proto__ instead of Object.create

### ISSUE THREAD

**Issue by dotnetCarpenter** [Polymer/polymer#3619]
I just took polymer for a test run and the first warning I got in Firefox Dev tool was: `mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create`. The culprit is [line 198 in src/lib/base.html](https://github.com/Polymer/polymer/blob/3bd83871564770551b90926e746c5d651d60942e/src/lib/base.html#L198)

The check seems odd

``` js
Polymer.Base.chainObject = function (object, inherited) {
  if (object && inherited && object !== inherited) {
    if (!Object.__proto__) {  // <- odd detection - is it a feature detection or guard?
      object = Polymer.Base.extend(Object.create(inherited), object);
    }
    object.__proto__ = inherited;
    }
  return object;
};
```

Given that `__proto__` is standardize and  `Object.create` is the preferred choice, It is a weird choice to put in the core of Polymer. I'm guessing that this is either an error or you are working around a certain browser.

I'm guessing to what you're trying to accomplish but it seems to me that if you want to simulate multiple inheritance, you could do a mixin on the prototype, without throwing away the old prototype.
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11
### Versions

- Polymer: v1.4.0
- webcomponents: v0.7.22

**Comment by azakus** [comment]
IE 10 does not support `__proto__`, which explains the if/else. Why `__proto__` instead of `Object.create`? I'm not sure, maybe the `chainObject` method is expected to return the same object...

**Comment by TimvdLippe** [comment]
The code has since been updated to use `__proto__`. If you still encounter this issue, please reopen with a JSBin we can execute and debug.

**Comment by dotnetCarpenter** [comment]
@TimvdLippe The point was to **use `Object.create`** instead of `__proto__` since it destroys browser optimization by bailing out of the type. But never mind... I moved on.

https://stackoverflow.com/a/23809148/205696
