### ISSUE TITLE
[Proposal] Add transformer support to data binding

### ISSUE THREAD

**Issue by jolleekin** [Polymer/polymer#3621]
I'm not sure how PolymerJS handles this, but using Dart, there is no easy way to bind a property/path of types other than string to an input element. In Polymer Dart 0.5, I can create a transformer and use it in the binding expressions. In Polymer 1.0, transformer behaviors must be manually implemented for each property or path. If there are tens or even hundreds of properties or paths that require transformers, it's just too painful to implement.
## Polymer 0.5 (Dart)

``` dart
class IntToStringTransformer extends Transformer<String, int> {
  String forward(int i) => i != null ? '$i' : '';

  int reverse(String s) => int.parse(s, onError: (_) => null);
}

class MyElement extends PolymerElement {
  MyElement.created() : super.created();

  @observable
  int count;

  final IntToStringTransformer int2string = new IntToStringTransformer();
}
```

``` html
<polymer-element name="my-element">
  <template>
    <input type="text" value="{{count | int2string}}" />
  </template>
</polymer-element>
```
## Polymer 1.0 (Dart) - Work-around to add support for transformers

``` dart
class MyElement extends PolymerElement {
  MyElement.created() : super.created();

  @Property(observer: 'countChanged')
  int count;

  @Property(observer: 'countStringChanged')
  String countString;

  @reflectable
  void countChanged(_, __) {
    set('countString', count != null ? '$count' : '');
  }

  @reflectable
  void countStringChanged(_, __) {
    set('count', int.parse(countString, onError: (_) => null));
  }
```

``` html
<dom-module id="my-element">
  <template>
    <input type="text" value="{{countString::change}}" />
  </template>
</dom-module>
```

**Comment by TimvdLippe** [comment]
You can define your own binding parser in Polymer 2 (override [`_parseBindings`](https://www.polymer-project.org/2.0/docs/api/elements/Polymer.Element#method-_parseBindings)) to define your own expressions in a base class to achieve the functionality you want.
