### ISSUE TITLE
Separating the JS and CSS into different files

### ISSUE THREAD

**Issue by mbana** [Polymer/polymer#3622]
Two questions, seeing as the documentation doesn't clearly state it:

1. I am are trying to make separate files for the JS and CSS sections of an element. I cannot find anything in the docs the specifies the official way of doing this for _both_ the JS and CSS. A CSS example is available here: https://www.polymer-project.org/1.0/docs/devguide/feature-overview.html. 
2. Does the JS code go inside the dom-module or after it. Again, the documentation lists both ways.

The documentation really needs to be updated as I feel this is making people believe that you cannot separate these out.

**Comment by ebidel** [comment]
You can put the `<script>` anywhere after the `<dom-module>` is defined. One reason `Polymer({is: 'my-element')` takes the name of a dom-module as the `is` property is to associate the script with your markup.  Potentially, this means you can have a single compiled `<script>` at the bottom of your page. The calls to `Polymer()` dont need to be in the element's dom-module. We typically just do that for readability and modularity.

**Comment by ebidel** [comment]
@arthurevans @kaycebasques  for the docs FYI

**Comment by mbana** [comment]
Thanks. So what's the official way of moving the inline CSS into separate files without having to create intermediate html files with ``<style>`` that house the CSS just for that module?

**Comment by ebidel** [comment]
Are you talking about moving `<style>` that polymer elements define into separate files? We don't have a tool for that. However, one issue with moving styles outside of the `<dom-module>` in general is that they would no longer be scoped to the element's shadow dom.

Given your own elements, we have a websevice (and there's a gulp plugin) that takes a .css file and wraps it in a style-module: https://www.polymer-project.org/1.0/tools/overview.html#polystyle

**Comment by mbana** [comment]
Thanks. I mean, using https://www.polymer-project.org/1.0/docs/devguide/feature-overview.html as an exampe, what's the _defacto_ way of moving the css defined in the the ``style`` tags to a separate file:

```
  <template>
    <style>
      /* CSS rules for your element */
    </style>
  
    <!-- local DOM for your element -->

    <div>{{greeting}}</div> <!-- data bindings in local DOM -->
  </template>
```
