### ISSUE TITLE
Upwards binding to `null` will not work at initialization time.

### ISSUE THREAD

**Issue by Pupix** [Polymer/polymer#3624]
### Description

Binding an outer element's nested property (`foo.bar`) to a readOnly property of an inner element (`bar`) will not update the external one when the elements are initialized, if the readOnly value is `null`. It works just fine with other defined values.  
#### Live Demo

http://jsbin.com/zofeyefebo/edit?html,console#H:L20

You can change the highlighted line with any other defined value and see that both changes will be logged.
#### Steps to Reproduce

1. Create an outer element with an object property called `foo`

``` js
{
    type: Object,
    value: function () { return {}; }
}
```

2. Create an inner element with a property called `bar`

``` js
{
    type: Object,
    readOnly: true,
    notify: true,
    value: null
}
```

3. Two-way bind `foo.bar` from the outer element to the inner's bar property
#### Expected Results

Outer element's `foo.bar` would get the inner's bar value and become `null`
#### Actual Results

The binding is being ignored and the outer element's `foo.bar` is not being set.
### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Edge

Haven't tested these ones
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions
- Polymer: v1.4.0
- webcomponents: v0.7.21

**Comment by kaste** [comment]
This is introduced here https://github.com/Polymer/polymer/blob/master/src/lib/bind/accessors.html#L235

My PR #3550 fixes this here https://github.com/Polymer/polymer/pull/3550/commits/af97faf9b9e91216229d9bb58d4dcf71f9808a04

**Comment by Pupix** [comment]
Thanks for taking care of it!

Waiting patiently for merge and next release. :unamused:

**Comment by kaste** [comment]
Patiently... well that PR is a month old without even a single comment. :camel:

**Comment by Pupix** [comment]
Perhaps whoever's in charge of PRs is on vacation :tropical_drink: , who knows. My guess is that they will do a bump to 1.5.0 before (or during) I/O, just like last year.

**Comment by ebidel** [comment]
Everyone is extremely heads down for Google I/O atm. Thanks for being
patient!

**Comment by Pupix** [comment]
@ebidel you are still busy with Google I/O? 😒

**Comment by Pupix** [comment]
@ebidel @azakus are you guys gonna fix this?

**Comment by TimvdLippe** [comment]
This has been fixed in Polymer 2: http://jsbin.com/gebalugetu/edit?html,console,output
