### ISSUE TITLE
Feature request -- event handling for non-visual components without DOM

### ISSUE THREAD

**Issue by JeffGillin** [Polymer/polymer#3627]
Just wanted to add a feature request.
I use some components as non-visual components, just like a class in traditional OO language.  
Events fired in these components do not get caught by the component that instantiates the non-visual component unless the non-visual component is added to the DOM.  i don't know if it's possible to work it so that these also can get caught above (have non-dom events as well), but I found it kind of "hacky" feeling have to add the non-visual component to the dom in order to get the event to be caught.

**Comment by kaste** [comment]
Hm, this should just work. Something like this perhaps: http://jsbin.com/guwemaqezu/edit?html,console,output

**Comment by JeffGillin** [comment]
Thanks, I must have had something else going on.
