### ISSUE TITLE
Unable to import external css files into a shared-styles module

### ISSUE THREAD

**Issue by johnwhitton** [Polymer/polymer#3628]
### Description
I am trying to import an external stylesheet into a shared styles module, as referred to in the [documentation](https://www.polymer-project.org/1.0/docs/devguide/styling.html#style-modules) and [release notes](https://blog.polymer-project.org/announcements/2015/08/13/1.1-release/)

#### Steps to Reproduce

1. Create colorjw.css which contains
```
.colorjw {
    color: blue;
  }
```
2. Create a colorjw-styles.html _( a styles module)_
```
<link rel="import" href="../bower_components/polymer/polymer.html">

<!-- Testing how to import an external stylesheet -->
<dom-module id="colorjw-styles">
  <template>
      <link rel="stylesheet" type="text/css" href="./colorjw.css">
  </template>
</dom-module>
```
3. Reference the styles module in my custom element colorjw-app.html
```
<link rel="import" href="../../bower_components/polymer/polymer.html">

<!-- Styles -->
<link rel="import" href="../../styles/shared-styles.html">
<link rel="import" href="../../styles/dapp-styles/dapp-styles.html">
<!-- <link rel="import" href="../../styles/dapp-styles.html"> -->


<dom-module id="colorjw-app">
  <template>
     <style include="shared-styles"></style>
     <style include="dapp-styles"></style>


  <h1>Hello</h1>
  <div class="colorjw">
    Div text
  </div>
  </template>

  <script>
    Polymer({
      is: 'colorjw-app'
    });
  </script>
</dom-module>
```

#### Expected Results
The text _Div Text_ should be blue

#### Actual Results
The text color has not been changed as the styling was not picked up

### Browsers Affected
I have only tested on Chrome

### Versions
- Polymer: v1.4.0
- webcomponents: v0.7.21

### Please note 
If you use the below version of colorjw-styles.html then it works as expected i.e. _div text_ is blue
```
<link rel="import" href="../bower_components/polymer/polymer.html">

<!-- Testing how to import an external stylesheet -->
<dom-module id="colorjw-styles">
  <template>
  <style>
  .colorjw {
      color: blue;
    }
  </style>
  </template>
</dom-module>
```

**Comment by notwaldorf** [comment]
Closing; plain importing of CSS stylesheets is not supported like that (see [this](https://github.com/PolymerElements/iron-flex-layout/issues/88#issuecomment-203692575) for a more detailed explanation of possible ways of importing CSS).

Talked offline, and the solution is to wrap the _actual contents_ of the stylesheet in a `dom-module`, not the import.
