### ISSUE TITLE
DOM properties not computable in attached callback

### ISSUE THREAD

**Issue by mgiuffrida** [Polymer/polymer#3629]
Tracking bug for the issue we discussed wherein properties like `this.offsetHeight` are `0`, even
in `attached` or after the `attached` call but before `document.readyState` is `'complete'`.

@sorvell, @kevinpschaaf

**Comment by azakus** [comment]
Sounds like a platform issue?

**Comment by jfrazzano** [comment]
I found that by recording unfound,0ed, null or uncomsoled dimension/Dom properties in an array/map generated by an observer In a bound element property, I got the a rather large compilation of values that could be reduced to a usable value for dynamic sizing on various screen sizes, browsers and devices. 

I did this months ago on older polymer and did not push impl forward, but have used sane approach a bunch.  It has seemed to give values not consolatory absent setting them with polymer methods to an independant value map

**Comment by mgiuffrida** [comment]
@noms Turns out this is what I was hitting, again. Even this:

```
attached: function() {
  requestAnimationFrame(function() {
    setTimeout(function() {
      measureStuff();
   }, 0);
  }); 
},
```

doesn't help because `measureStuff` may run when `document.readyState == 'interactive'` (after `DOMContentLoaded`, after the element is attached, but before `load`).

**Comment by mgiuffrida** [comment]
So, to really wait for a useful render, we need to wait for the `load` event, or `document.readyState == 'completed'`.

I suspect that this "fix" would break a bunch of stuff, so maybe put it behind a setting? In Chrome's MD Settings we'd get a big FOUC.

[Here's my proposed fix and repro](https://github.com/mgiuffrida/polymer/commit/88daab4a4e095b49717dcade3b40fcc135a2381a):

Smallest repro case I could come up with; it requires a `<script>` followed by a `<link>` in the entry file for some reason. If you run `polyserve` and open `render_status_example.html`, you'll see the problem:

```
> offsetParent in attached    null
> readyState    interactive
> offsetParent later    <body>​…​</body>​
```

If you append `?waitForLoad` to the URL, it works, because it actually waits for the `load` event:

```
> offsetParent in attached    <body>​…​</body>​
> readyState    complete
> offsetParent later        <body>​…​</body>​
```

Please take a look. Implementing this would mean we can render sooner, because we're currently doing work before we have to since whenReady/afterNextRender don't wait for the page to finish loading.

**Comment by mgiuffrida** [comment]
@sorvell @kevinpschaaf

**Comment by mgiuffrida** [comment]
AFAICT, [this is a bug (or a "feature") in Chrome](crbug.com/638074) caused by `<link>` tags in the `<body>`. If we can move our `<link>`s to `<head>` we may get the desired behavior.

**Comment by TimvdLippe** [comment]
I am unable to reproduce this issue (http://jsbin.com/suzikuvopa/edit?html,console,output) Feel free to reopen this issue if you can supply a JSBin that shows the issue still exists.
