### ISSUE TITLE
One-way binding still changes object by reference

### ISSUE THREAD

**Issue by 43081j** [Polymer/polymer#3634]
### Description

If you bind a property of a child to some object on the parent and it then changes a sub-property, the parent's object also changes.

So, say you have `item="[[item]]"`, then change `item.foo` in the child, the parent's `item.foo` will also be changed (as it is the _same object_).

Only the change notification is being prevented by it being one-way, is this by design? Or should it create a copy?

#### Live Demo

http://plnkr.co/edit/vVKlDeqovrTnrmkcV6uY?p=preview

#### Steps to Reproduce

* Click `el-b`, it will set `item.x` to 7
* Click `el-a` (with dev tools open), you will hit a break point and `this.item.x` will be 7
* You verify this by `$('el-a').item === $('el-b').item`

#### Expected Results

`el-b` should have created some copy of the object when first trying to modify it, to keep the binding truly one-way.

#### Actual Results

Both elements reference the same object so any sub-property changes affect both.

**Comment by kaste** [comment]
That's the intended behavior.

**Comment by 43081j** [comment]
ah this is what I was hoping for, I created this rather for an explanation than a bug.

so the intended behaviour is that one vs two way binding is simply the change notification? rather than the actual change.

**Comment by kaste** [comment]
Essentially yes.

**Comment by 43081j** [comment]
Alright, cool.

Closing because this is by design.
