### ISSUE TITLE
Add some ways to debug polymer elements

### ISSUE THREAD

**Issue by ellenaua** [Polymer/polymer#3635]
Our application is built from Polymer elements (custom and written by us) and we need a way to debug elements: to see when they're "ready", "attached", to see registered observers and property changes. 

How can we achieve that? 

Could you please add some variables to enable debug mode?

**Comment by BLamy** [comment]
Everything you describe is possible using chrome devtools out of the box.

**Comment by TimvdLippe** [comment]
Closing per above comment. Chrome dev tools should be sufficient to be able to keep track of the lifecycle of elements.
