### ISSUE TITLE
Attachment timing subtly differs under Shadow and Shady DOM

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#3637]
When an element is registered asynchronously, under Shady DOM attached for hosted elements fires for all nested elements after all nested element observers have run. Under Shadow DOM, attached fires after each nested element's observers run. In general, attachment state is _not_ something that should be relied on in observers (due to the fact that an element may be created outside of dom and attached later); however, the inconsistency between Shady and Shadow DOM is a subtle difference that should be eliminated if possible. Polymer should normalize to the Shady attached behavior.

Behavior under Shady DOM: http://jsbin.com/nudaqozari/1/edit?html,console,output.

Behavior under Shadow DOM: http://jsbin.com/bagoyihoye/edit?html,console,output.

**Comment by azakus** [comment]
This timing change breaks the contract that local dom is distributed before `ready` callback. If we still want this change, it will have to keep that contract.

**Comment by sorvell** [comment]
The original links are now out of date. Here are updated examples that show the issue persists in Polymer 1.x:

* ShadyDOM: http://jsbin.com/vihexahixo/1/edit?html,console,output
* ShadowDOM: http://jsbin.com/canavigudu/1/edit?html,console,output

This issue has been *fixed* in Polymer 2.x

* ShadyDOM: http://jsbin.com/tayagifeja/1/edit?html,console,output
* ShadowDOM: http://jsbin.com/tamugeleyu/1/edit?html,console,output

Closing this issue since it has been corrected in Polymer 2.x and is too difficult to address without breaking changes in 1.x.
