### ISSUE TITLE
Calling importHref multiple times with the same url adds the link unnecessarily

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#3638]
When an import has already been loaded, we can avoid creating an import and putting it into dom. This is a minor ergonomic issue that would keep the head clean of multiple unnecessary imports.

**Comment by abdonrd** [comment]
@sorvell It is fixed?

**Comment by sorvell** [comment]
Yes, will be included in the next release.

**Comment by abdonrd** [comment]
@sorvell awesome! :)

**Comment by bastienarm** [comment]
is this a real problem to have X many times the same import, or does it have some perf issues? (just for understanding)
