### ISSUE TITLE
Feature requrest: an element method to atomically set multiple properties

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer#3640]
As an element author, there are times in which multiple `notify` properties are updated in response to another property changing. Currently these changes will happen in a certain order, and change notifications will happen synchronously and in that order, resulting in observers seeing an inconsistent view of these properties.

It would be nice to be able to set multiple properties atomically, such that there's no externally visible observable time in which some of the properties have been updated and others haven't. 

This appears to be possible if we provided a method that first updates `__data__`, and then does notification.

**Comment by cdata** [comment]
Please refer to this discussion [here](https://github.com/PolymerElements/carbon-route/pull/93#discussion_r62398465) for context.

**Comment by dsmilkov** [comment]
+1. I've ran across this problem multiple times.

**Comment by fromSpace** [comment]
I believe the best way to do this is to have a mergeToProperty() function you can call.

It would be something like 

`element.deepCallback(function(){host.property` = object.assign(function convertValToObj(val){return {value:val;} , host.property)});`

**Comment by fromSpace** [comment]
I believe the best way to do this is to have a mergeToProperty() function you can call.

It would be something like 

`element.deepCallback(function(){host.property` = object.assign(function convertValToObj(val){return {value:val;} , host.property)});`
 Then afterwords, you will have to call notifyAll, you may have some other steps required if observing multiple deep properies outside of this element. notifyPath will not work. notifyAll may cause a dirty check worthy of performance consideration in this situation. 

If only a function such as just notify() would allow me to pass array of objects for props I changed, where each object looks like [this is specifically for deep property groups, that have some relationship where they should propagate as a group, such as waiting for a promise to resolve, observers for all of these properties would be called in one big swoop, on a single event, and those observers would handle as if called individually, possibly copy to new properties as a new object, or as reference. The group notify should be able to propogate and be handled by all observers of the group property itself, with the requirment of deep bindings, deep bindings can cause a lot of confusing, I would like to change that, such that redux can give us a greater application state and is helpful for component integration testing, group properties can be very helpfull in assessing a greater state at runtime. This is why this should be added, and it will help with the setMultipleProperties issue as well, some of the base functions to make this work are easily adapted for the setMultipleProperties case as well]
The object layout I propose to pass for each property in the property group.
{
prop.path:'/sompath', /*Path changes as propagated, no idea how to do this yet*/
propagate_as_independent_change:false,
continue_to_propagate_with_this_group: /*false=fullstop, true=surviving member of group moves on*/
}

Please advise if there is already a solution to this, not sure if my approach is the best.

**Comment by arthurevans** [comment]
This exists in 2.0-preview as `setProperties`

**Comment by TimvdLippe** [comment]
Closing per https://github.com/Polymer/polymer/pull/3641#issuecomment-320832350 and above comment
