### ISSUE TITLE
Replace the suffix '-changed' by Polymer.Base._EVENT_CHANGED

### ISSUE THREAD

**Issue by jorgecasar** [Polymer/polymer#3643]
### Description

There are several references to `'-changed'` in the code and exist a constan in `Polymer.Base` called `_EVENT_CHANGED`. It would be a good idea centralize the suffix in one place.
#### Live Demo

N/A
#### Steps to Reproduce

Find `'-changed'` in all project.
#### Expected Results

Use `Polymer.Base._EVENT_CHANGED` everywhere.
#### Actual Results

The suffix `'-changed'`appear in 4 times in 3 files.
### Browsers Affected

N/A
### Versions
- Polymer: v1.4.0 and below.
- webcomponents: N/A

**Comment by jorgecasar** [comment]
@azakus What do you need to investigate?

Polymer.Base._EVENT_CHANGED is defined in https://github.com/Polymer/polymer/blob/e614e811fa151d105239b1d5d5521fd2322700f1/src/standard/notify-path.html#L382 then you can use it internally, right?

**Comment by TimvdLippe** [comment]
Closing per https://github.com/Polymer/polymer/pull/3644#issuecomment-320833419
