### ISSUE TITLE
Listing of children with Polymer.dom(<element>).children stops at script tags

### ISSUE THREAD

**Issue by jcage2010** [Polymer/polymer#3649]
#### Live Demo

https://jsbin.com/qaqoqunawe/edit?html,console,output
#### Steps to Reproduce
1. Create a custom element which has a content node in its template
2. Include children in its light DOM, a `<script>` element amongst them
3. Inpect `Polymer.dom(this).children` in the element's `attached` function. It will list the `<script>` element as the last, even if there are more children after it.

For example, 

```
  <my-app>
    <div id="c1"></div>
    <script></script>
    <div id="c3"></div>
  </my-app>
```

3 children should be listed, but because the `<script`> tag is present, only #c1 and `<script>` will be listed
### Browsers Affected

- [*] Chrome
### Versions

- Polymer: v1.2.4
- webcomponents: v 0.7.20

**Comment by TimvdLippe** [comment]
`Polymer.dom` is now deprecated for reasons such as the one in this issue. You can now use the native API instead :smile:
