### ISSUE TITLE
Data-binding class member methods

### ISSUE THREAD

**Issue by lastmjs** [Polymer/polymer#3653]
Here is the [jsBin](https://jsbin.com/fakitim/edit?html,console) of the issue I'm having. I'm wondering why we can't data-bind a class member method to a property of another element? The code below and in the jsBin log testMethod as undefined. If you get rid of the binding in the template, it logs correctly.

```
<!doctype html>
<html>
<head>
  <base href="https://polygit.org/components/">
  <script src="webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="polymer/polymer.html">
</head>
<body>


  <dom-module id="test-component">
    <template>
      <div foo="[[testMethod]]"></div>
    </template>

    <script>
      class TestComponent {
        beforeRegister() {
          this.is = 'test-component';
        }

        ready() {
          console.log(this.testMethod);
        }

        testMethod() {

        }
      }

      Polymer(TestComponent);
    </script>
  </dom-module>

  <test-component></test-component>
</body>
</html>
```

This problem exists even without using es6 classes, as can be seen in this [jsBin](https://jsbin.com/pajadec/edit?html,console). I feel that any property of your element should be able to be data-bound, providing less boiler-plate. This is also how event listener "bindings" work, you just pass in the name of the function to an attribute of another element, and it just works.

**Comment by 43081j** [comment]
It seems like this should be structured differently if you feel the need to pass methods around, as elements should only really care about themselves and public methods/properties of their children, _not_ what contains them.

However, if you really wanted to pass a function, you'd instead have a property with its `value` set to a function I suppose.

**Comment by azakus** [comment]
You can only bind to properties defined in a `properties` block.

**Comment by azakus** [comment]
To answer your second point, event listeners are special. The value of the function is not passed around, the `on-event="handlerFn"` binding just uses the value of the attribute to dereference from the element the name of the function to invoke.

**Comment by lastmjs** [comment]
@azakus Yes, I suppose the point I'm trying to make is that it is the same concept. You pass the name of a function to an attribute on another element. I don't see why there is a need to declare properties that are passed into child elements. I don't want the rest of the world to see these functions/methods, just the immediate child elements, and so I don't want them declared as properties, or I don't think they should need to be declared as properties. That is extra boilerplate compared to just passing in the value of the method. 

@43081j Are you saying anything data-bound from a parent element to its children should be declared in a property? What if I don't want to expose properties to elements outside of my element, but I do want to data-bind into child elements? I think that is legitimate, and we shouldn't have to declare properties to do that. I think we should be able to data-bind any JavaScript property on the context of the element to child element properties. Is my thinking flawed?

**Comment by lastmjs** [comment]
And for context, see [express-web-components](https://github.com/scramjs/express-web-components/blob/master/README.md) I'm trying to allow Express middleware handler functions as class member methods. Right now I have to explicitly add the handler functions to the context of the element. Can you see how allowing member methods to be data-bound is desirable in this case?

**Comment by lastmjs** [comment]
As an update, it looks like you will be able to bind a host element's class member methods to a child element's properties in Polymer 2, see the [jsBin](https://jsbin.com/fakitim/edit?html,console)

**Comment by jfrazzano** [comment]
Awesome… that would be so nice.  Getter-setter bind eventually?
