### ISSUE TITLE
Polymer startup overwrite bower.json

### ISSUE THREAD

**Issue by CharlesHurt** [Polymer/polymer#3654]
I am writing a Polymer app from scratch installing and using the PSK.

1) I landed at https://www.polymer-project.org/1.0/docs/start/getting-the-code.html
which directed me to create a bower.json file.

2) A few steps further down,  I was directed to download the PSK, which, when installed, will overwrite the first bower.json.  

Just thought I would let you guys know so you can smooth over directions.

**Comment by TimvdLippe** [comment]
This should now have been streamlined with `polymer init` which has the option to initialize the PSK: https://www.polymer-project.org/2.0/start/toolbox/set-up
