### ISSUE TITLE
Support 'contenteditable' two-way binding, just like input tag !

### ISSUE THREAD

**Issue by myuseringithub** [Polymer/polymer#3656]
Hi, 
As stated in the documentation **textContent** binding is only one-way **host-to-child**. I would like Polymer to support **two-way binding** for elements with **contenteditable** set to true. 
I've managed to achieved two way binding by notifying/updating binding on change (for contenteditable on-input) event. While for a single property it is an easy task, but what about a bunch of nested objects bindings in a repeat template, where each one should support two way binding with contenteditable.

Example of two way binding achieved for a single data property with contenteditable - 
[http://jsbin.com/samiba/70/edit?html,output](http://jsbin.com/samiba/70/edit?html,output)

**2-way binding for both textContent & InnerHTML** attributes, when using **contenteditable** will be appreciated, or at least a workaround to solve it. Thanks

**Comment by myuseringithub** [comment]
I've managed to add support for two-way binding using Polymer's event observers. 
`<span text-content="{{value::input}}" contenteditable></span>
`

**Comment by shahraship** [comment]
how would you get html string out of contenteditable? text content only returns the text, while stripping out the html.

**Comment by myuseringithub** [comment]
@shahraship For my use case I needed only text values, were they are bound to Firebase document field, allowing realtime value changes. You could refer to the documentation for other node properties, that may satisfy your needs. https://developer.mozilla.org/en/docs/Web/API/Node/textContent

**Comment by svralkar30** [comment]
In **contenteditable**, I've achieved the **two way binding** with help of the **blur** event and **innerHTML** attribute.

in .html:

    <div placeholder="Write your message.."(blur)="getContent($event.target.innerHTML)" contenteditable [innerHTML]="content"></div>

In .ts:

    getContent(innerText){
      this.content = innerText;
    }
