### ISSUE TITLE
dom-module's _template is occasionally not available

### ISSUE THREAD

**Issue by Jamtis** [Polymer/polymer#3657]
Sometimes when using native (with async tag) HTMLImports I get errors containing `$` (automated node finding).
#### Live Demo

https://jamtis.github.io/polymer-HTMLImport-bug/build/index/index.html
https://jamtis.github.io/polymer-HTMLImport-bug/build/index/index-L1.html
https://jamtis.github.io/polymer-HTMLImport-bug/build/index/index-L2.html

```
  ...
  <link rel="import" href="/vulcanized-deps.html" async>
  <link rel="stylesheet" href="some-stylesheet.css"><!-- L1 -->
  <script src="register-x-foo.js" async></script>
</head>
<body>
  <dom-module id="x-foo">
    <link rel="import" type="css" href="x-foo.css"><!-- L2 -->
    <template>
      <paper-header-panel>
      ...
      </paper-header-panel>
    </template>
  </dom-module>
```
#### Steps to Reproduce

Load the page, open the dev tools.
Wait until error is catched, the page reloads itself... (usually within 5min an error occurs to me)
I didn't find a deterministic way to reproduce the bug.
#### Expected Results

The createdCallback of the `x-foo` element expects `this._template` to exist but sometimes it doesn't...
#### Actual Results

As a result `$` can not access the template, leading to errors.
![screenshot 2016-05-16 at 01 44 14](https://cloud.githubusercontent.com/assets/3067604/15277532/d4a81888-1b07-11e6-9f6f-c746f7865d99.png)
#### Comments

When L1 or L2 is removed, the bug does not occur to me, which might be incoherent.
ShadowDOM doesn't affect the occurance.
Due to L2 my guess is 'deprecated external stylesheets' could cause this.
### Browsers Affected
- [x] Chrome/51.0.2704
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions
- Polymer: v1.4.0
- webcomponents: ---

**Comment by aigan** [comment]
I submitted #4443 as a consistent example of probably the same bug

**Comment by TimvdLippe** [comment]
Closing this issue as an upstream Chrome issue filed at https://bugs.chromium.org/p/chromium/issues/detail?id=669710
