### ISSUE TITLE
Template-repeat regenerates elements instead of updating them.

### ISSUE THREAD

**Issue by myuseringithub** [Polymer/polymer#3659]
Input/contenteditable connected to firebase loses focus on key press.. because the content is regenerated instead of data updating.

http://jsbin.com/diqabi/46/edit?html,output
Firebase: https://intense-heat-1283.firebaseio.com/test.json

Any fix provided ?

**Comment by Fausto-theXS** [comment]
Not a fix but kind of a dirty workaround, by including a filter in the dom-repeat that always return true, it'd keep the focus.
Don't ask me why, because I don't know
Here the modified code
http://jsbin.com/sohahuzeqi/1/edit?html,output

**Comment by myuseringithub** [comment]
You are my HERO ! I was going crazy about this. Thanks so much. I want to buy you a coffee !

**Comment by TimvdLippe** [comment]
`firebase-element` has [been deprecated](https://github.com/GoogleWebComponents/firebase-element) and I am unable to fix your JSBin. If you are still experiencing issues, please reopen this issue with an up-to-date JSBin.
