### ISSUE TITLE
Display message "not found" once the filter/search is empty with dom-if

### ISSUE THREAD

**Issue by bbayo4** [Polymer/polymer#3660]
Trying to display a message if the filter/search is empty but seems like the template is not stamping in the dom.
#### Live Demo

http://plnkr.co/edit/Qy6LeAfe93u4CK2G43eX?p=preview

Thanks

**Comment by TimvdLippe** [comment]
This issue is quite broad and old. If you are still having issues, please open a question on [StackOverflow](https://stackoverflow.com/questions/tagged/polymer) instead.
