### ISSUE TITLE
will Polymer support 'A' type Component?

### ISSUE THREAD

**Issue by Colstuwjx** [Polymer/polymer#3664]
### Description

As I known, AngularJS directive supports 'E' and 'A' type directives which 'E' is similar to Polymer Element, but I still cannot find any 'A' type component in Polymer way.

Will it support this type component?
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions

- Polymer: v1.X.X
- webcomponents: vX.X.X

**Comment by travellhyne** [comment]
The Web Components spec provides a new way of registering new custom elements, not attributes, although you can apply new attributes to custom elements.

**Comment by Pablo-Ivan** [comment]
As @travellhyne says, you can do that by simply:
```
<dom-module id="my-element">
  <template>
     <p>Custom Element with custom attribute {{attr}}, hooray!</p>
     <script>
       Polymer({
         is: 'my-element',
         properties: {
           attr: String
         }
       })
     </script>
  </template>
</dom-module>
<!--and its usage-->
<my-element directive="a custom attribute"></my-element>
```

**Comment by TimvdLippe** [comment]
Closing this issue as it is vague (see https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs). If you still think this is an issue in Polymer 2, please reopen this issue with a more elaborate description.
