### ISSUE TITLE
setScrollDirection seems like stopped working?

### ISSUE THREAD

**Issue by blasten** [Polymer/polymer#3667]
#### Live Demo

https://elements.polymer-project.org/bower_components/paper-drawer-panel/demo/index.html
#### Steps to Reproduce
1. Add some content to the drawer so that it overflows. 
2. Set `overflow-y:auto` to the drawer
3. Try it on Chrome for Android
#### Expected Results

If I scroll down, I don't expect the drawer to close, because it has `setScrollDirection('y')`.
#### Actual Results

The drawer closes when I scroll the content.
### Browsers Affected

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions

- Polymer: v1.4.0

**Comment by TimvdLippe** [comment]
Closing this issue as it concerns `paper-drawer-panel` which has been deprecated in favor of [`app-layout`](https://github.com/polymerelements/app-layout)
