### ISSUE TITLE
binding hidden$ to an empty string value hides the element

### ISSUE THREAD

**Issue by rdcronin** [Polymer/polymer#3669]
if I have an element
`<div hidden$="[[emptyStr]]"></div>`
I expect hidden$ to evaluate to '' (empty string), which in turn evaluates to false - that is, the element should be visible.  This doesn't seem to work.  Binding instead to a helper function

```
<div hidden$="[[isStrEmpty(emptyStr)]]"></div>
...
isStrEmpty: function() { return !!this.emptyStr; },
```

works as expected.

A fiddle is worth a thousand words, courtesy of mgiuffrida:
https://jsfiddle.net/mgiuffrida/7L9dmz58/

**Comment by azakus** [comment]
Why would that evaluate to false if you have `type: String` in your property declaration? The hidden attribute is a boolean attribute, so if it is present with _any_ value on the element, that element will be hidden, and `type: String` will set `<div hidden="">`

**Comment by mgiuffrida** [comment]
> The hidden attribute is a boolean attribute, so if it is present with any value on the element, that element will be hidden, and `type: String` will set `<div hidden="">`

Well that's not entirely true, [`type: String, value: undefined` doesn't behave that way](https://jsfiddle.net/ozgghntm/). Also a super fun bug in there when you toggle the string property to `'foo'` and back to `undefined` with the big red button!

![bug](http://i.imgur.com/BiGES76.png)

i thought there was another issue open similar to this, but I can't find it now.

see also #2343 which I think would have removed the need for the computed function here.

**Comment by kjlubick** [comment]
This problem also manifests if you bind to a Number and the number goes to zero.  The element stays hidden, even though I would expect the falsey value to make it be visible

https://jsfiddle.net/ea25mmqz/

**Comment by TimvdLippe** [comment]
`undefined` seems to be working properly with Polymer 2: http://jsbin.com/zacoqixoka/edit?html,console,output however `0` and `""` do not.
