### ISSUE TITLE
How to get your polymer progressive webapp working on http2?

### ISSUE THREAD

**Issue by kanodia** [Polymer/polymer#3671]

**Comment by azakus** [comment]
To use http/2, you'll need to use SSL with a certificate, or have a hosting provider that does that for you. AppEngine will provide http/2 automatically, while if you make your own server you can follow the instructions for enabling http/2 on your webserver of choice (https://mozilla.github.io/server-side-tls/ssl-config-generator/ is very handy for generating configs)
