### ISSUE TITLE
How to set a child property from parent property and double data binding in Js codes?

### ISSUE THREAD

**Issue by hzmnet** [Polymer/polymer#3672]
How to set a child property from parent property and double data binding in Js codes?

**Comment by azakus** [comment]
I'm sorry, I don't understand your question. Maybe you can search on [StackOverflow](https://stackoverflow.com/questions/tagged/polymer) or use our [slack channel](https://polymer-slack.herokuapp.com/). Github issues should only be for bug reports or feature requests.

**Comment by hzmnet** [comment]
there 2 elements with same property mode.
ele1, ele2
In ele1's  Ready()

ready:function(){
         ele2=  CrerateElement(ele2) //not full codes
         ele2.mode=this.mode; // ele2.mode didnot changing when ele1 change mode value. they not bindding each other
}

**Comment by naoak** [comment]
@hzmnet This might help you.
http://stackoverflow.com/questions/30615549/data-binding-in-a-dynamically-inserted-polymer-element
