### ISSUE TITLE
Shady adds a ton of comments to head

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#3673]
Using many components in an app adds a lot of needless comments to the `<head>`.

![screen shot 2016-05-23 at 2 03 01 pm](https://cloud.githubusercontent.com/assets/238208/15484584/89e07140-20ef-11e6-8b71-c3079ad758f1.png)

Do we need to add these? Would be cool to remove as a nice microperf opt and DOM cleanup.

**Comment by 43081j** [comment]
These appear to be a placeholder so any CSS can be appended to the DOM in the correct order (always after its associated comment).

Maybe we could instead keep ordering state in memory rather than DOM.

**Comment by TimvdLippe** [comment]
This issue was moved to webcomponents/shadydom#209
