### ISSUE TITLE
notifyPath doesn't work if there is a period in the key name

### ISSUE THREAD

**Issue by dandelionmane** [Polymer/polymer#3675]
### Description

If you have a dict with arbitrary key names, it is impossible to use notifyPath to alert an update if the key contains a period.
#### Live Demo

https://jsbin.com/badibewoda/edit?html,console,output
#### Steps to Reproduce

Run the jsbin provided above, in which the dict has keys with periods and keys without periods.
#### Expected Results

It should notify two changes after the ----start---- line in console, for both calls to notifyPath.
#### Actual Results

Only one change is notified.
### Versions
- Polymer: v1.4.0
- webcomponents: vX.X.X

**Comment by azakus** [comment]
I think this is a known issue, but we should document that case if so.

**Comment by tomalec** [comment]
Related issues: https://github.com/Polymer/polymer/issues/3127, https://github.com/Polymer/polymer/issues/2446

**Comment by tpluscode** [comment]
Would it be possible to overload `notifyPath()`, `set()` etc. so that it takes either a string or an array? It would make the two called below equivalent.

``` javascript
this.nofityPath("some.long.path", value);
this.nofityPath([ "some", "long", "path" ], value);
```

If one wanted to notify path with periods in keys, the array version can be used, where each element is a property name.

**Comment by tpluscode** [comment]
Oh, I see that the `_getPathParts` function already handles arrays but still splits each element on dots. I guess that another solution is in order.

**Comment by TimvdLippe** [comment]
It seems that your original JSBin now properly shows two change notifications as well as the correct value for the second property. If you are still experiencing issues, please reopen this issue with a JSBin that shows the issue.

**Comment by TimvdLippe** [comment]
https://jsbin.com/badibewoda/edit?html,console,output is the JSBin that works with Polymer 2 btw
