### ISSUE TITLE
Custom css properties are ignored when assigning a css class dynamically

### ISSUE THREAD

**Issue by BrechtBa** [Polymer/polymer#3683]
### Description
In Chromium, custom css properties defined in a class selector are ignored when the class is assigned dynamically.
Below is an example where the background of a paper-card is altered in a class. With the static class definition the background is as expected, but with the dynamic class assignment the background does not alter. The same goes for other custom css variables is other elements.

In Firefox the behavior is as expected. I do not have access to other browsers.

#### Live Demo
https://jsbin.com/dacososana/1/edit?html,output

### Versions
- Polymer: v1.4.0
- webcomponents: v0.7.22

**Comment by TimvdLippe** [comment]
I think this is one of the limitations of the shim, as described here: https://www.polymer-project.org/1.0/docs/devguide/styling#custom-properties-shim-limitations

**Comment by BrechtBa** [comment]
You are correct,
but it does work in Firefox.
Furthermore, calling this.updateStyles() or Polymer.updateStyles() does not apply the new style as is described.

**Comment by sorvell** [comment]
You need to call `updateStyles` after the element is attached to the dom. Here's a working version: https://jsbin.com/holajepeja/edit?html,output. 

As noted above the need to call `updateStyles` is a limitation of the custom properties shim. The need to call it after the element is attached is a bug that we're working on addressing, it's reported here: https://github.com/Polymer/polymer/issues/3530.

**Comment by sorvell** [comment]
Closing based on explanation. Please re-open with more info if more clarification is needed.
