### ISSUE TITLE
can not found the elements by this.$.XXX which inside the  dom-if 

### ISSUE THREAD

**Issue by hzmnet** [Polymer/polymer#3689]
#### Live Demo

https://jsbin.com/xukike/edit?html,output
### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions

- Polymer: vX.X.X
- webcomponents: vX.X.X

**Comment by motss** [comment]
@hzmnet You need to use `this.$$.<id>` to find elements that generate dynamically.

**Comment by dgabrielli76** [comment]
Your issue and your jsbin are not very explicit.
Could you please give us a better example and more explanation about your problem?

If you want to find an element with its id you need to use `this.$.<id>`.
If you want to find an element with its name you need to use `this.$$.('element-name')`.
You can also use [Polymer DOM API](https://www.polymer-project.org/1.0/docs/devguide/local-dom) to find an element through the shadow DOM.

I hope this answer will help you, if not I would be pleased to discuss with you about it if you give us more details.

**Comment by TimvdLippe** [comment]
This is a limitation of creation of the `this.$` hash as described here: https://www.polymer-project.org/1.0/docs/devguide/local-dom#node-finding

> Note: Nodes created dynamically using data binding (including those in dom-repeat and dom-iftemplates) are not added to the this.$ hash. The hash includes only statically created local DOM nodes (that is, the nodes defined in the element's outermost template).

**Comment by TimvdLippe** [comment]
Closing per above comment.
