### ISSUE TITLE
:host(.xxx) is rewritten to `undefined

### ISSUE THREAD

**Issue by zoechi** [Polymer/polymer#3690]
#### Live Demo

https://jsbin.com/xukike/edit?html,output

I'll try to add a repo case in JS later. I'm using this in Dart an am not fluent in JS

#### Steps to Reproduce

Example:

I have this style module which I add dynamically to the element like explained in https://github.com/Polymer/polymer/issues/2681

```
<!DOCTYPE html>
<dom-module id="bwu-datagrid-default-theme-column-header">
  <template>
    <!--suppress CssOptimizeSimilarProperties -->
    <style>
      :host(.ui-state-default) {
        background: url('../../../packages/bwu_datagrid/asset/images/header-columns-bg.gif') repeat-x center bottom;
        border-right: 1px solid silver;
      }

      :host(.bwu-datagrid-header-column:hover),
      :host(.bwu-datagrid-header-column-active) {
        background: white url('../../../packages/bwu_datagrid/asset/images/header-columns-over-bg.gif') repeat-x center bottom;
      }

      :host(.bwu-datagrid-header-column-sorted) {
        font-style: italic;
      }

      :host(.bwu-datagrid-header-column-sorted) ::content > .bwu-datagrid-column-name {
        border: solid 3px red !important;
        order: 1;
      }
      :host(.bwu-datagrid-header-column-sorted) ::content > .bwu-datagrid-sort-indicator {
        padding-right: 2px;
      }
    </style>
  </template>
</dom-module>
```

full webcomponents polyfills loaded and shadow DOM enabled

#### Expected Results

there should be no `undefined` in the selector

#### Actual Results

no errors

```
 :host(.bwu-datagrid-header-column-sorted) ::content > .bwu-datagrid-column-name {
```
is rewritten to 

```
undefined.bwu-datagrid-header-column-sorted  > .bwu-datagrid-column-name {
```

Full result copied from Firefox console

```
<style include="bwu-datagrid-default-theme-column-header" bwu-datagrid-theme="bwu-datagrid-default-theme" is="custom-style">:not([style-scope]):not(.style-scope):host(.ui-state-default) {
  background: url('http://localhost:63342/bwu_datagrid/example_/web/packages/bwu_datagrid/asset/images/header-columns-bg.gif') repeat-x center bottom;
        border-right: 1px solid silver;
}

:not([style-scope]):not(.style-scope):host(.bwu-datagrid-header-column:hover),:not([style-scope]):not(.style-scope):host(.bwu-datagrid-header-column-active) {
  background: white url('http://localhost:63342/bwu_datagrid/example_/web/packages/bwu_datagrid/asset/images/header-columns-over-bg.gif') repeat-x center bottom;
}

:not([style-scope]):not(.style-scope):host(.bwu-datagrid-header-column-sorted) {
  font-style: italic;
}

undefined.bwu-datagrid-header-column-sorted  > .bwu-datagrid-column-name {
  border: solid 3px red !important;
        order: 1;
}

undefined.bwu-datagrid-header-column-sorted  > .bwu-datagrid-sort-indicator {
  padding-right: 2px;
}

</style>
```

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Edge (probably - not installed)
- [ ] Safari 9 (probably - not installed)
- [ ] Safari 8 (probably - not installed)
- [ ] IE 11 (probably - not installed)

Works fine in Chrome

### Versions

- Polymer: v1.4 according to https://github.com/dart-lang/polymer_interop/blob/master/CHANGELOG.md (Dart polymer interop polymer_interop 1.0.0-rc.9)
- webcomponents: 0.7.21. according to the changelog in https://github.com/dart-lang/web-components/blob/master/CHANGELOG.md (Dart web_components 0.12.3)

**Comment by sorvell** [comment]
It looks like you're using a `:host` selector in a style that's included in a `custom-style`. If so, that's not a supported use case. The `:host` selector is intended to be used only within a style targeting a custom element. The `custom-style` element exists to provide shady-dom shimmed styling for the entire document.

**Comment by sorvell** [comment]
Closing based on explanation. If this needs further clarification or was not interpreted correctly, please feel free to re-open with more information.

**Comment by zoechi** [comment]
@sorvell Thanks for the explanation, that makes sense. 

It's a powerful way to style elements and to work around a serious limitation of Polymer. Do you have any plans to address these limitations eventually (like demonstrated in #2681)?
