### ISSUE TITLE
Obscure error fired when numerical values are set to CSS custom properties via this.customStyles

### ISSUE THREAD

**Issue by lozandier** [Polymer/polymer#3694]
### Description

An obscure exception is thrown (`property.indexOf is not a function`) when numerical values  (or other non string values) are set to CSS custom properties via `this.customStyles`

This makes it problematic to recover from or to understand and so on. 
#### Live Demo

http://codepen.io/lozandier/pen/8ce0995ea6c5b174b3147f66d7450def
#### Steps to Reproduce
1. Create a custom element & append it to page
2. Optionally set custom variables in its designated stylesheet
3. In its ready/attached state, attempt to change an existing or
   -->
#### Expected Results

- When style-centric statements are ran with a nonstring value— such as `this.customStyle['--baz'] = 2;`  the method should fire an exception like the other core methods do when they encounter an invalid intent by end users that their intent is invalid and steps to provide explicitly a string value.
- Alternatively, the setter should scrutinize the set value (i.e. using `typeof`) and correctly change it to `string` internally for common primitives sensible for style declarations such as `Number`.  
#### Actual Results

  `this.customStyle['--baz'] = 2;` causes an `TypeError` exception be thrown: `VM3064 style-properties.html:127 Uncaught TypeError: property.indexOf is not a function`
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11
### Versions

- Polymer:  all versions
- webcomponents: n/a

**Comment by TimvdLippe** [comment]
The error is no longer thrown. Closing in favor of #3695
