### ISSUE TITLE
API doc for `customStyle` should mention that values must be strings

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#3695]
### Description

```
this.customStyle['--baz'] = 2;
```

Throws an error, "TypeError: property.indexOf is not a function".

```
this.customStyle['--baz'] = '2';
```

Does not. We should warn people about that. Or just convert to string, one or the other.
#### Live Demo

https://jsbin.com/rihavekara/edit?html,console,output

Click da button, see da error.
#### Steps to Reproduce

See above.
### Versions
- Polymer: v1.5.0
- webcomponents: v0.7.22

**Comment by TimvdLippe** [comment]
The error no longer throws, but it now requires the following: https://jsbin.com/voxuzeqesu/edit?html,console,output

**Comment by TimvdLippe** [comment]
Actually, it is now documented: https://www.polymer-project.org/2.0/docs/api/elements/Polymer.Element#method-updateStyles

> The optional parameter overrides inline custom property styles with an object of properties where the keys are CSS properties, and the values are strings.
