### ISSUE TITLE
dom-repeat: re-rendering does not use chunking

### ISSUE THREAD

**Issue by dickp** [Polymer/polymer#3699]
### Description

When a dom-repeat template is set up to use chunking, and render() is called after the items array has been bound, it is then rendered all at once not incrementally.
#### Live Demo

https://jsbin.com/fakiraqoki/edit?html,output

This jsbin creates a dom-repeat template with a filter.  When the 'RE-RENDER' button is tapped, the filtering is updated and render() is called.  The browser page then freezes until the entire list is rendered, when it should be re-rendering in chunks.
#### Steps to Reproduce

1. Create a template with is="dom-repeat" and bind items.
2. At some point after it has finished rendering, call render().
#### Expected Results

List rendering is performed in chunks.
#### Actual Results

With a large array, the browser freezes until the entire list is rendered.
### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

(I don't think this is browser-dependent!)
### Versions

- Polymer: v1.4.0
- webcomponents: v0.7.22

**Comment by dickp** [comment]
Suggested fix:

```javascript
diff --git a/src/lib/template/dom-repeat.html b/src/lib/template/dom-repeat.html
index 63c548a..1bb522e 100644
--- a/src/lib/template/dom-repeat.html
+++ b/src/lib/template/dom-repeat.html
@@ -412,6 +412,7 @@ Then the `observe` property should be configured as follows:
       // Choose rendering path: full vs. incremental using splices
       if (this._needFullRefresh) {
         // Full refresh when items, sort, or filter change, or when render() called
+        this._initializeChunking();
         this._applyFullRefresh();
         this._needFullRefresh = false;
       } else if (this._keySplices.length) {
```

If this fix is acceptable I'll submit a PR.

**Comment by b-times-b** [comment]
Works fine for me! Great! +1
