### ISSUE TITLE
Polymer with Angular2

### ISSUE THREAD

**Issue by JesusSD** [Polymer/polymer#3701]
Material2 components for Angular2 are few and unstable and seems to remain so for a long time and to use quality components with "Material Design" must be used Polymer components and integrate them into angular 2 Incredible !.

PLEASE GOOGLE: Join and integrate natively Polymer and Angular2 unifying the syntax (now is a war, Polimer VS Angular2 while React is the real enemy). and also create components valid for desktop and mobile simultaneously as Ionic2 natively (One component for all platforms).﻿

**Comment by web-padawan** [comment]
Have a look at [Angular2-Polymer](https://github.com/vaadin/angular2-polymer) by Vaadin.

**Comment by zoechi** [comment]
Also posted on angular#9108 Polymer and Angular2 are quite different and target different use cases even though there is some overlap. 
Unifying is quite unrealistic.
