### ISSUE TITLE
Document this.root

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#3703]
_From @mgiuffrida on June 9, 2016 18:20_

`this.root` is mentioned [in the Local DOM guide](https://www.polymer-project.org/1.0/docs/devguide/local-dom) but not in the [`Polymer.Base` API](https://www.polymer-project.org/1.0/docs/api/Polymer.Base).

_Copied from original issue: Polymer/docs#1655_

**Comment by arthurevans** [comment]
Hey folks,

Can we add API docs for this? Or is this one of the things the current API doc system rejects?

**Comment by TimvdLippe** [comment]
`this.root` no longer exists. The Polymer 2 native equivalent is `this.shadowRoot`.
