### ISSUE TITLE
Tap events leak within nodes

### ISSUE THREAD

**Issue by valdrinkoshi** [Polymer/polymer#3704]
### Description

`tap` event leaks to elements underneath an opaque element when the top element gets hidden on tap.
This issue is causing problems like this one https://github.com/PolymerElements/paper-dialog/issues/59
#### Live Demo

http://jsbin.com/kugepa/3/edit?html,output
#### Steps to Reproduce
- open http://jsbin.com/kugepa/3/ in Chrome in iPhone 6 mode (using the developer toolbar)
- press the element on top (in the area intersecting the bottom element)
- notice that the bottom element gets the focus
#### Expected Results

When using `tap` listener, the bottom element gets the focus event
#### Actual Results

The bottom element should not get the focus.
### Browsers Affected

- [x] Chrome (Android Nexus 5x)
- [x] Chrome (in phone simulator mode)

**Comment by valdrinkoshi** [comment]
@azakus can you PTAL?

**Comment by azakus** [comment]
Looks like this is just about focus, not about the other element getting tap? If so, then I'm not surprised. The focus events follow the synthesized mouse events, and only the click is prevented, but the focus may fire.
The only solution may be blocking the focus event like the click event in a document-wide capturing listener.

**Comment by rubenstolk** [comment]
The issue looks minor but majorly affects user experience, especially while developing hybrid apps (it seems to affect iOS in UIWebViews).

**Comment by rubenstolk** [comment]
@azakus:

Adding `focus` to `deps` and `flow.end` for the tap event plus a simple:

```js
focus: function(e) {
  e.stopImmediatePropagation();
}
```

Seems to solve this issue.

However, I'm not into the whole `gestures` thing so not sure if this is the right approach and if we should create a PR for it. Let me know if I should...

**Comment by alexclarkofficial** [comment]
I think this bug is actually more substantial than just focus events. I've set up a demo to show a `tap` event being handled and then a subsequent `click` event being handled on the element now in the original elements place.

*Live Demo*
http://jsbin.com/fumosehaso/edit?html,output

*Steps to Reproduce*

- open http://jsbin.com/fumosehaso/ in Chrome in iPhone 6 mode (using the developer toolbar)
- press the element on left
- notice both elements disappear

*Expected Results*
The element on the left disappears and the element on the right shifts into its place.

*Actual Results*
Both elements disappear.

**Comment by rubenstolk** [comment]
@alexclarkofficial I think that your solution does not solve the original problem of this issue, namely the fact that an underlying element receives focus when an overlaying element becomes invisible as a result of a `tap`.

The PR I created (https://github.com/Polymer/polymer/pull/3866) does solve that issue. Can someone have a look? @azakus?

**Comment by azakus** [comment]
This is still an issue, but like I said in https://github.com/Polymer/polymer/pull/3866#issuecomment-259838528, the right fix is to block the next `focus` event inside of the ghost click prevention mechanism.
