### ISSUE TITLE
Some icons render in safari but not in chrome 

### ISSUE THREAD

**Issue by erinhong17** [Polymer/polymer#3707]
I was having trouble viewing the "search" and "clear" icon on Chrome after I had installed the <paper-search-bar> component from https://customelements.io. After trying to add iron-icons to other places outside of the paper search bar, icons such as "search" and "clear" do not generate but the "menu" icon that came with the downloaded package from polymer appeared just fine. This error seems to be either a  Chrome Error or the iron-icons. 

`<paper-search-bar icon="search"></paper-search-bar>`
Does nothing different since the default is already set to icon="search"

`<paper-search-bar icon="menu"></paper-search-bar>`
Shows the menu icon where the search icon should be 
### Search bar should look like:

(http://collaborne.github.io/paper-search/components/paper-search/ )
### What does it look like?:

same as demo except no search icon is visible (exists and is detectable by inspecting) and once you type the "clear" icon is not visible but is also detectable by inspecting 
### DOES NOT work on Chrome

Version 51.0.2704.79 (64-bit) on Mac Book Pro OS X El Captain Version 10.11.4
### DOES work on Safari

Version 9.1 (11601.5.17.1)
### Expected Results:
- no error is thrown 
- icon will be present but svg is not generated 
### Steps:
1. Install Polymer 
2. Install paper-search from https://customelements.io and all iron-icon dependencies on Polymer 
3. On my-app.html, I added the <paper-search-bar> within the <app-toolbar> 
4. Ran in Chrome (Changed none of the properties since default was already set to "search" and nothing but the "filter" icon showed up.) 
### Browsers Affected

- [ x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

**Comment by arthurevans** [comment]
It looks like the element sets the icon color to `--disabled-text-color`, so you should make sure that's not set to the background color:

https://github.com/Collaborne/paper-search/blob/master/paper-search-bar.html#L35

But it sounds like this was working when you specified `icon="menu"`?

This is not an element maintained by the Polymer team, so I think you should probably report this over on the repo: 

https://github.com/Collaborne/paper-search

**Comment by arthurevans** [comment]
I should add: if you can reproduce this behavior _outside_ `paper-search-bar`, it's either a Chrome bug or (most likely) a Polymer or `iron-icon` bug.

**Comment by TimvdLippe** [comment]
This issue seems to be fixed, as I can not reproduce the issue any longer on https://www.webcomponents.org/element/Collaborne/paper-search Adding both `icon="search"` and `icon="menu"` to the element are working. If you are still experiencing issues, please open an issue on https://github.com/Collaborne/paper-search for further assistance.
