### ISSUE TITLE
Stop bubbling from a child in a custom element

### ISSUE THREAD

**Issue by ardf69** [Polymer/polymer#3710]
I'm working with angular2 and polymer. All seems to wok well but I found a strange behaviour on the `<property>-changed` propagation. I have a custom element with a property named value and inside it there is an paper-input that has the same property name. When I write in the paper-input the value-changed event propagates outside the custom element that I don't want. Is there a way to avoid the bubbling?

Ciao Angelo

**Comment by pkaske** [comment]
Afaik not. You need to check the rootTarget in your handler. That would be `Polymer.dom(e).rootTarget`.

**Comment by kaste** [comment]
Duplicate #3226 et.al.

The check Polymer internally uses is `e.path[0] === e.target`.
 
Can be closed?

**Comment by ardf69** [comment]
The problem is the event from the child cannot stopped with stopPropagation since on chrome, after the first stopPropagation, all the same kind of events don't work anymore; this is dued to the caching events management.

**Comment by ardf69** [comment]
I did some check on the specification on ShadowDom and I must say the use of stopPropagation with the cache is buggy. In particular, according to https://www.w3.org/TR/shadow-dom/#event-dispatch

3. For each object in event path where the relative target is same as the object, invoke its event listeners, with event event, as long as event's stop propagation flag is unset

So if I call stopPropagation the event should be removed from the cache (see the problems with chrome).

Ciao Angelo

**Comment by ardf69** [comment]
In attachment you'll find the patch to let work stopPropagation.

Ciao Angelo

[patch.txt](https://github.com/Polymer/polymer/files/463930/patch.txt)

**Comment by TimvdLippe** [comment]
In 2.0 these events [no longer bubble](https://github.com/Polymer/polymer/blob/ca1ce19682b0003359090491d7e81a58d26b9a4a/lib/mixins/property-effects.html#L301). Please reopen this issue if you can supply a JSBin which shows the issue.
