### ISSUE TITLE
Dom-repeat does not work well with flat array

### ISSUE THREAD

**Issue by anhvupham** [Polymer/polymer#3712]
### Description

Dom-repeat generates the new item with the value of the previous item of flat array.
#### Live Demo

http://jsbin.com/wefofe/edit?html,output
#### Steps to Reproduce
1. Click More to add an input
2. Enter something to that input
3. Click More again to add another input
#### Expected Results

The new input should have blank value
#### Actual Results

The new input have value of last input.

**Comment by TimvdLippe** [comment]
Closing as the issue in the provided JSBin is not occuring any longer :tada:

**Comment by arthurevans** [comment]
I think this may have been because of the limitation that 1.x couldn't handle arrays of primitives:

https://www.polymer-project.org/1.0/docs/devguide/model-data#work-with-arrays

That limitation doesn't exist in 2.0.
