### ISSUE TITLE
Odd data-binding behaviour in nested polymer elements

### ISSUE THREAD

**Issue by HaykoKoryun** [Polymer/polymer#3714]
I was trying to debug a recent app and found this little oddity.

First take a look at the example [here](https://jsfiddle.net/HaykoKoryun/jdgm3t9m/) and then read the following explanation of the issue.

#### Explanation
The first element has a bound property `background-color` which defaults to `#ff00ff`. It uses this color to style the tip of the flag in the template and when the its `DOM` is ready it updates its `background-color` `CSS` property with the same color.

The second element just wraps the first element, binding its own `color` property to the inner element's `background-color` property.

And here is where things get weird. The tip gets styled with the right color; you can see it's _yellow_ in the example. However the background color is the default color as if the `background-color` property hasn't been set at all. That's impossible as the tip wouldn't be _yellow_ then.

To overcome the issue you can change the name of the property binding in the template of `filter-flag` from `background-color` to `backgroundColor` (line 26 of the HTML in the example).

It seems like there is an issue somewhere in the function that maps property names with hyphens in the template to their camelCase counterparts in the properties of the Polymer element.

#### Expected Results
Bound properties with hyphens in their names should work in nested Polymer elements.

#### Actual Results
Bound properties with hyphens in their names seem not to work properly in nested Polymer elements.

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v1.5.0
- webcomponents: v0.7.22

**Comment by arthurevans** [comment]
You need to bind to the property name (camelCase), not the attribute name (dash-case):

    style="border-left-color:{{backgroundColor}}"

Working version:

https://jsfiddle.net/d8aj49kg/

Note that instead of waiting 5 seconds, you can wait for the `WebComponentsReady` event, as shown in this version.

Closing because I don't think this is a bug. If this change doesn't fix your problem, add a note in here and I'll reopen. Thanks.

**Comment by HaykoKoryun** [comment]
@arthurevans oh yes I tried that and it worked, but I think it's a bit ambiguous that the hyphenated version works inside the original polymer element, but only partially when that polymer element is inside another element.
