### ISSUE TITLE
PWA for Desktops

### ISSUE THREAD

**Issue by brpatel0202** [Polymer/polymer#3715]
Feature Request

**Comment by joeblew99** [comment]
i dont knwo what PWA is .

But i am guessing that you can just use electron should be enough, just like using cordova for mobile.

**Comment by LM450N** [comment]
[**P**rogressive **W**eb **A**pp](https://developers.google.com/web/progressive-web-apps/)

**Comment by joeblew99** [comment]
ah yes i see.

So if its for Desktops, i guess its electron to contain it ?

**Comment by LM450N** [comment]
It think PWA for desktop is not "an issue" related to Polymer. If you are able to run an web app on a desktop Polymer should work.

The question is "__How can I create a web app that follows the PWA spec?__".

And you're right, [Electron](http://electron.atom.io/) could be a really [good choice](https://discuss.atom.io/t/does-polymer-work-with-electron/23314?source_topic_id=24305)! 💯

**Comment by joeblew99** [comment]
@LM450N thanks, wil try it out
