### ISSUE TITLE
Paper Toast component open method not working in IE

### ISSUE THREAD

**Issue by pvseshu** [Polymer/polymer#3716]
In my project we are trying to implement paper toast components, but open method is not working in IE browser. I have tried in different ways by using webcomponents-lite.js/webcomponent.js but everytime it is failing. Is it know bug or something wrong in my code(Below is sample code). 

![polymer](https://cloud.githubusercontent.com/assets/3065055/16102377/b19e754c-3323-11e6-83df-498026b245b0.png)

**Comment by iSuslov** [comment]
what is msgToast variable referring to? Did you try first

> var msgToast = document.getElementById('msgToast'); 

and then work with the toast?

**Comment by TimvdLippe** [comment]
Closing this issue as it misses a runnable JSBin which shows the error. Please open an issue on https://github.com/PolymerElements/paper-toast if you can still reproduce this issue.
