### ISSUE TITLE
Content not distributing for Google Play Music in shady-dom and Chrome

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer#3717]
### Description

`<paper-header-panel>` has two `<content>` children, one that does a couple of queries, the other that selects for `*`. We've got a page where native shadow dom is distributing but shady dom in Chrome appears not to be for the second `<content>` (and possibly the first).
#### Live Demo

In these demos `div#gifting-background` should be distributed inside of `<paper-header-panel>`'s `div#mainContent`. 

Compare:
- https://play.google.com/music/gift?dom=shadow (correct)
- https://play.google.com/music/gift in Firefox or Safari (correct)
- https://play.google.com/music/gift in Chrome (incorrect)

The `<paper-header-panel>` is a direct child of body so it's easy to find in the inspector.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
### Versions
- Polymer: v1.4.0
- webcomponents: v0.7.22

**Comment by TimvdLippe** [comment]
Closing this issue as the problem seems to be resolved. Opening the links all show the same behavior.
