### ISSUE TITLE
Binding in <style> doesn't work under native shadow dom.

### ISSUE THREAD

**Issue by nanowang** [Polymer/polymer#3718]
### Description

Binding in `<style>` doesn't work under native shadow dom.
#### Live Demo

https://jsbin.com/kizanul/edit?html,console,output
#### Steps to Reproduce
1. wait for the script to be executed
#### Expected Results

A red element
#### Actual Results

A transparent element
#### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
#### Versions
- Polymer: latest(1.5)
- webcomponents: latest

**Comment by motss** [comment]
@nanowang Never knew you can do like this.

**Comment by nanowang** [comment]
Why not. Style tag shouldn't be special.

**Comment by TimvdLippe** [comment]
Your JSBin seems to not work with shady dom either. Also this is not designed to be working, you should use `css-variables` instead.
