### ISSUE TITLE
The result from importHref is not the same as link import.

### ISSUE THREAD

**Issue by supachailllpay** [Polymer/polymer#3727]
#### Description
When I use importHref to import my-element into my-app, it looks like something went wrong about the dependency loading. The --layout-fit mixin in iron-image (in my-element) doesn't apply.

#### Live Demo
https://plnkr.co/edit/FaYYjKcOrLYfDnLAI0YO?p=preview

#### Steps to Reproduce
1. Open the live demo and go to my-app.html
2. Uncomment "import my-element" at the top and in the script tag comment out "importHref"
3. See the result

**Comment by nick-woodward** [comment]
@supachailllpay 
Here's a half-way decent workaround until this gets resolved.
```javascript
this.importHref('my-element.html');
this.querySelector('my-element').updateStyles(); // this is the part you care about
```

**Comment by nick-woodward** [comment]
Seems this has already been resolved in master.
```sh
$ bower i Polymer/polymer#master
```
[Live Demo](https://plnkr.co/edit/iEKsGul7UB8yzqTt5Yx3?p=preview) _(I ended up using rawgit because I couldn't get polygit to pull polymer from master)_

**Comment by supachailllpay** [comment]
Thank you for the information, nick-woodward.
