### ISSUE TITLE
Polymer webcomponents.js and materializecss.js issue.

### ISSUE THREAD

**Issue by krsrk** [Polymer/polymer#3728]
When i try to include webcomponentsjs.js in my project to launch my web components, i throws an error on Jquery; i thought this was a Jquery error but it´s the materializecss.js; when i included the libraries in my project like this:

```
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
<script src="bower_components/webcomponentsjs/webcomponents.js"></script>
```

The error behaviour comes if i make any click on the screen; and throws this:

**TypeError: a.getAttribute is not a function
...0;return void 0!==f?f:c.attributes||!p?a.getAttribute(b):(f=a.getAttributeNode(b...**

This error happens in Firefox 47, in Chrome doesnt throw anything.

Hope you can help me with this issue.

Regards.

#### Live Demo

https://jsbin.com/xukike/edit?html,output
### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions

- Polymer: v1.0
- webcomponents: v0.7.22

**Comment by TimvdLippe** [comment]
Closing this issue as no runnable JSBin was posted. Please reopen this issue with a JSBin that shows the issue.
