### ISSUE TITLE
Polymer.dom.appendChild() does not append comment nodes on Shady

### ISSUE THREAD

**Issue by Saulis** [Polymer/polymer#3742]
When I run: 

``` js
var foo = document.createComment('foo');
var bar = document.createComment('bar');

Polymer.dom(this).appendChild(foo);
this.appendChild(bar);

console.log(foo.parentElement && foo.parentElement.tagName);
console.log(bar.parentElement && bar.parentElement.tagName);
```

with Shady DOM `bar` will have the correct parent element but `foo` isn't appended and `parentElement` is null. With Shadow DOM (Chrome) nodes are appended correctly.
#### Live Demo

http://jsbin.com/hoyeco/1/edit?html,console,output
#### Steps to Reproduce
1. Click on the button
#### Expected Results
- Console should print 2x 'X-FOO'
- `<x-foo>` should have childs `<!--foo-->` AND `<!--bar-->` 
#### Actual Results
- Console prints 'null' and 'X-FOO'
- `<x-foo>` has child `<!--bar-->` only
### Browsers Affected
- Tested on OSX Chrome 50
### Versions
- Tested on v1.5.0

**Comment by TimvdLippe** [comment]
Closing this issue as `Polymer.dom` has been deprecated. In Polymer 2 you can now use the native `appendChild` method.
