### ISSUE TITLE
dom-repeat render() bug when outer changing array

### ISSUE THREAD

**Issue by Fame513** [Polymer/polymer#3744]
### Description

When you change array, that dom-repeat is using , without Polymer methods, and than call render(), new dom elements are added, but binding values are empty.
#### Live Demo

https://jsfiddle.net/6rLksujt/
#### Steps to Reproduce
1. Create `dom-repeat` template
2. Push new items to array with array.push() method
3. Call render() for dom-repeat
#### Expected Results

Appeared new item with pushed value
#### Actual Results

Appeared new item with empty value
### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions
- Polymer: v1.5.0
- webcomponents: v0.7.22

**Comment by motss** [comment]
@Fame513 Could it be because you're not using Polymer's own utility method `push` just like your `innerAdd`. Your `OuterAdd` pushes data into the array however that did not update the property to trigger re-rendering.

**Comment by Fame513** [comment]
@motss Yes, I understand it, but if I change array in another place (for example I have one big global array that can be changed), and I want to update list, I call render() for dom-repeat, and it show me new list item, but with empty value. I think render method is exactly for that things, because if I use Polymer array mutation method, dom-repeat will render automatically.

**Comment by TimvdLippe** [comment]
The JSFiddle appears to be working properly with Polymer 2 now. It was probably fixed somewhere along the way. Sorry for not notifying you sooner.
