### ISSUE TITLE
Add "changed" event for paper-dropdown-menu

### ISSUE THREAD

**Issue by santiago-elustondo** [Polymer/polymer#3747]
The [paper-input](https://elements.polymer-project.org/elements/paper-input) component has a "changed" event that you can use to implement 2-way binding. I'm looking for an equivalent for [paper-dropdown-menu](https://elements.polymer-project.org/elements/paper-dropdown-menu). The paper-dropdown-menu api provides the "value" property as a getter, but not as an event.

[paper-listbox](https://elements.polymer-project.org/elements/paper-listbox) has an event like the one described ("iron-select"), but the event data does not tell you which paper-dropdown-menu it is a child of.

So far the best way I've been able to accomplish data binding is by listening to all paper-listbox "iron-select" events, and then grabbing the values of all dropdowns every time.

In Angular2:

```
/* template */

<paper-dropdown-menu #dropdown1 label="Your favourite pastry">
  <paper-listbox (iron-select)="onSelectDropdown($event)" class="dropdown-content">
    <paper-item>Croissant</paper-item>
    <paper-item>Donut</paper-item>
    <paper-item>Financier</paper-item>
    <paper-item>Madeleine</paper-item>
  </paper-listbox>
</paper-dropdown-menu>

//and another 2...

/* class */

@ViewChild('dropdown1') dropdown1:any;
@ViewChild('dropdown2') dropdown2:any;
@ViewChild('dropdown3') dropdown3:any;

onSelectDropdown(event:any){
  setTimeout(()=>{
    this.data = {
     thing1: this.dropdown1.nativeElement.value;
     thing2: this.dropdown2.nativeElement.value;
     thing3: this.dropdown3.nativeElement.value;
    }
  }, 0);
}
```

This does not seem like a very elegant way to do it, especially since I have to wrap the getter ("value") calls in a timeout. This is because the event fires before it propagates to the parent (paper-dropdown-menu).

**Comment by Fausto-theXS** [comment]
What I do is observe the property selected on paper-listbox 
`<paper-listbox class="dropdown-content" selected="{{selected}}">
`...  
`selected: { type:String, observer: "_selected", notify:true },
`
That on selecting a new value provides both previous and new selected
```
      _selected: function(selected, previous) {
        this.fire('xs-select-changed', {selected:selected, previous:previous});
      }
```

**Comment by aneesshameed** [comment]
Not a good solution but we can also use 'on-click' attached to paper-item.
```
<paper-dropdown-menu #dropdown1 label="Your favourite pastry">
  <paper-listbox class="dropdown-content">
    <paper-item on-click="selectionChanged">Croissant</paper-item>
    <paper-item on-click="selectionChanged">Donut</paper-item>
    <paper-item on-click="selectionChanged">Financier</paper-item>
    <paper-item on-click="selectionChanged">Madeleine</paper-item>
  </paper-listbox>
</paper-dropdown-menu>
```

**Comment by TimvdLippe** [comment]
You can listen to [`value-changed`](https://www.webcomponents.org/element/PolymerElements/paper-dropdown-menu/elements/paper-dropdown-menu#event-value-changed), so I think your issue has been addressed since you opened it.

**Comment by wearecharette** [comment]
Couldn't get value-changed to fire an event, but found on-iron-select in the source which worked.
