### ISSUE TITLE
ES6 types not available in property declaration

### ISSUE THREAD

**Issue by phidias51** [Polymer/polymer#3751]
It would be useful if we could take advantage of ES6 types like Maps & Sets.  I'd like to be able to a declare a property like this:

```
linkMap: {
                type: Map,
                readonly: true,
                value: [
                    ['pubmed','http://www.ncbi.nlm.nih.gov/pubmed/'],
                    ['gene','http://www.ncbi.nlm.nih.gov/gene/'],
                    ['trial','http://www.clinicaltrials.gov/show/']

                ]
            }
```

However, when I do that I get an Uncaught TypeError when I try to use linkMap. 
 polymer-mini.html:2061 Uncaught TypeError: Cannot read property 'get' of undefined

Oddly enough, I can use maps inside of methods, I just can declare them as properties.

**Comment by noahlaux** [comment]
For structured data (like objects, arrays and maps) you should instead do a function that returns your value:
```js
linkMap: {
    type: Map,
    readonly: true,
    value: function () {
	    return [
	        ['pubmed','http://www.ncbi.nlm.nih.gov/pubmed/'],
	        ['gene','http://www.ncbi.nlm.nih.gov/gene/'],
	        ['trial','http://www.clinicaltrials.gov/show/']
	    ];
	}
}
```

**Comment by phidias51** [comment]
The problem with that approach is that it doesn't fit with the model previously established for how Arrays are used.  Map's should be a first-class citizen just as Arrays are.  Wrapping it in a function is counter-intuitive.

**Comment by BLamy** [comment]
Adding ES6 types would be nice but it's really just be a bandaid solution.The real problem is probably the lack of ability to define your own types. 

https://github.com/Polymer/polymer/pull/2677

**Comment by phidias51** [comment]
@BLamy: I agree. Adding support for ES6 classes would make a lot of things easier.

**Comment by noahlaux** [comment]
it's not counter intuitive in this context. The whole polymer object literal is prototypal so if you don't wrap your structured data in functions all instances of your element would share the same instance of your map (object, array etc). This has nothing to do with Polymer, that's fundamental to javascript.

**Comment by phidias51** [comment]
@noahlaux To me a first class citizen is Array.  You can set it's value with the same type of array declaration that you have in JavaScript. Everything is completely consistent, and therefore intuitive.  To declare a Map should be just as easy as my previous example.  

Removing the "readOnly" part of the equation for a minute, the straight map declaration should work.  If something is declared readOnly, then the behind the scenes it should make it a static constant. No extra fiddly bits necessary. :-)

**Comment by noahlaux** [comment]
Maybe we are not talking about the same, but in what situation would you do:
```js
linkMap: {
    type: Array,
    value: [
		'http://www.ncbi.nlm.nih.gov/pubmed/',
        'http://www.ncbi.nlm.nih.gov/gene/',
        'http://www.clinicaltrials.gov/show/'
    ]
}
```
I don't see the use case for that, as I'm most likely to be building a reusable component that has a high chance of being injected multiple times on the page. With this approach it would have unpredictable behavior as my array would be shared among my instances. Maybe you're talking about something else?

**Comment by phidias51** [comment]
@noahlaux The linkMap in this case contains link prefixes.  This makes it easier to specify links without having to remember specific prefixes. 

Something like this: 
```
<my-link type="pubmed" id="1234567"></my-link>
```

Will result in this:
```
<a href="http://www.ncbi.nlm.nih.gov/pubmed/1234567">[PMID: 1234567]</a>
```

A 'computed' url property would take care of the concatenation.

```
_computeUrl: function(linkMap, type, id){
   var map = new Map(linkMap);
   var url = map.get(type);
   return url + id;
``
assuming that the linkMap was declared as an Array of map entries.

In Java or Groovy, the linkMap would typically be defined as **static** and **final** to insure that only one immutable copy is floating around in memory.  Something similar in a Map declaration (or any other type of declaration) would be useful.

**Comment by TimvdLippe** [comment]
You can initialize the `Map` in the `value` property to work with the data-binding system: http://jsbin.com/cucerobuce/edit?html,console,output Polymer poses no limitation of using any arbitrary type as the type and return type of `value`.

**Comment by phidias51** [comment]
@TimvdLippe although you can do it with a function (as you demonstrate in the jsbin), that wasn't what I was looking for. (see initial request). What I'd like to be able to do is a simple Map declaration as shown in the first comment, and to do Set declarations in a similar manner.

```
linkSet: {
    type: Set,
    readonly: true,
    value:[
            'http://www.ncbi.nlm.nih.gov/pubmed/',
            'http://www.ncbi.nlm.nih.gov/gene/',
            'trial','http://www.clinicaltrials.gov/show/'
        ];
    }
}

```

Whatever declaration happens to the right of the colon should be exactly the same as you would if you were just writing a simple declaration.

```
 const linkSet = new Set([
            'http://www.ncbi.nlm.nih.gov/pubmed/',
            'http://www.ncbi.nlm.nih.gov/gene/',
            'trial','http://www.clinicaltrials.gov/show/'
        ]);

```

That said, I modified your jsbin and it seems to work properly.  I was able to interrogate the map like this document.querySelector("my-element").map.get('pubmed') and it works.
