### ISSUE TITLE
HTML Forms

### ISSUE THREAD

**Issue by StokeMasterJack** [Polymer/polymer#3753]
I would like to see a better way to use components inside of an html form. 

For example, suppose I have a form like this:

```
<form action="action.jsp">
    <input name="date-start"/>
    <input name="date-end"/>
    <input name="name-first"/>
    <input name="name-last"/>
</form>
```

that gets submitted like this:

`action.jsp?date-start=2016-06-01&date-end=2016-06-30&name-first=Joe&name-last=Smith`

I would like to create the same form using components like this:

```
<form action="action.jsp">
    <date-range name="date">
    <full-name name="name">
</form>
```

that gets submitted exactly the same way as the example above:

`action.jsp?date-start=2016-06-01&date-end=2016-06-30&name-first=Joe&name-last=Smith`

**Comment by StokeMasterJack** [comment]
PS: I am aware that iron-form is available. But this solution has some problems. For one, it does not emulate native form submission very well. In a normal html form, when you submit, the current page is automatically replaced by whatever is returned by the action URL. This doesn't seem to happen with iron-form. Second. It only allows your component to contribute a _single_ value to the submitted data. In the example I gave each component contributes _two_ values to the submitted data.

The idea is to take an existing form and update it to use components without having to redo a lot of other code.

**Comment by TimvdLippe** [comment]
Sadly HTML parsers inside forms are not capable of working with custom elements. For a more elaborate explanation and solutions, check out these 2 Polycasts: https://www.youtube.com/watch?v=AVXu1_vaY2U and https://www.youtube.com/watch?v=K76g5DGCBOk
