### ISSUE TITLE
:root values are ignored when styles are imported by a file loaded with importHref()

### ISSUE THREAD

**Issue by mercmobily** [Polymer/polymer#3754]
- Polymer: v1.5.0
- webcomponents: v0.7.22 
-Polymer-cli: 0.11.1

I am posting this here because it seems to be a broader Polymer issue, although it's showing with the paper widgets.

If you start with polymer-cli's basic application, you end up with `index.html`, `my-app.html`, and `my-view[123].html`. I am serving this using `polymer serve`.

I opened up `my-view1.html` and added:

    <link rel="import" href="../bower_components/paper-card/paper-card.html">

And then lower down:

    <paper-card heading="Card Title 1" elevation="2">
        <div class="card-content">Some content</div>
        <div class="card-content">Some more content</div>
        <div class="card-actions">
          <paper-button>Some action</paper-button>
        </div>
      </paper-card>

**There was no way to actually see the shadow regardless of the elevation.**

In the CSS (after inspection), I had for that widget:

    :host([elevation="2"]) {
      ;
    }

Note that the actual source is:

      :host([elevation="2"]) {
        @apply(--shadow-elevation-4dp);
      }

So, `--shadow-elevation-4dp` wasn't defined. And YET, `paper-material-shared-styles.html` *starts with*:

    <link rel="import" href="../paper-styles/shadow.html">

Which sets at  `:root {` level:

      --shadow-elevation-4dp: {
          box-shadow: 0 4px 5px 0 rgba(0, 0, 0, 0.14),
                      0 1px 10px 0 rgba(0, 0, 0, 0.12),
                      0 2px 4px -1px rgba(0, 0, 0, 0.4);
        };

The "solution" is to add this to `my-app.html`:

    <link rel="import" href="../bower_components/paper-styles/paper-styles.html">

Bingo! The shadows appear magically. But... why?
Even adding that line to `my-view1.html` gives you no shadows -- which has me very confused.
If `my-view1.html` contains:

    <link rel="import" href="../bower_components/paper-styles/paper-styles.html">
    <link rel="import" href="../bower_components/polymer/polymer.html">
    <link rel="import" href="../bower_components/paper-card/paper-card.html">

Surely, `paper-styles.html` would be interpreted first. This would set `--shadow-elevation-4dp` at `:root` level, and then `paper-card.html` should have those values ready. And yet... it doesn't.

Now:

* I feel that a user should be able to import `paper-card/paper-card.html` and see things that "just work"
* I feel that since `paper-styles.html` is loaded first, it should set the custom CSS properties at `:root` level
* If this is how it's intended to work ( (a) I hope not (b) If so, why?), then it should be clearly documented.

Or... Am I missing something monstrously obvious?

**Comment by mercmobily** [comment]
To add to the issue: I wonder if this could be due to the fact that my-view1.html is loaded dynamically?

        this.importHref(
          this.resolveUrl('my-' + page + '.html'), null, null, true);

Merc.

**Comment by mercmobily** [comment]
The more I look at it, the more it looks like a bug.
`paper-material-shadow.html` ever so clearly states:

    <link rel="import" href="../paper-styles/shadow.html">

Which ever so clearly sets:

    :root {
      ......
      --shadow-elevation-2dp: {
        box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14),
                    0 1px 5px 0 rgba(0, 0, 0, 0.12),
                    0 3px 1px -2px rgba(0, 0, 0, 0.2);
      };

So when `paper-material-shadow.html` refers to 

    @apply(--shadow-elevation-2dp);

It surely *must* be able to resolve it!

I normally debug things, but here... I have frankly no idea where to start. I need to check why that `--shadow-elevation-2dp` isn't set when it's supposed to be... any hints on how to do it would be most welcome!

**Comment by mercmobily** [comment]
Yep, that *is* the issue: if you add

    <link rel="import" href="my-view1.html">

to `my-app.html`, hence loading `my-view1.html` the "classical" way... the shadows are there.
Updating the title accordingly. I hope what I am doing is helping...

**Comment by mercmobily** [comment]
Seriously... [Polymer 1.6.0 fixes it](https://github.com/Polymer/polymer/releases/tag/v1.6.0)... and it was released TODAY, a couple of hours after I did the latest update to the test environment.

So yes, it's fixed. 

------------------
The custom property shim will now correctly re-calculate custom property style values when global <style is="custom-style"> elements are loaded async (e.g. via use of lazy-loading).

importHref() will now ensure lazily-loaded element definitions result in tree-order upgrades when using polyfill, which should result in more deterministic behavior when using lazy-loading patterns.
-------------------

Well at least I was right in my diagnosis...

**Comment by cherukumilli** [comment]
@mercmobily 
did you try this on polymer v1.6.0?

I see different kinds of issues with :root in polymer v1.6.0. and using the new `useNativeCSSProperties: true` 
I have two theme files:
`app-theme.html` and 
'default-theme.html from paper-styles`

I don't see the styles in app-theme.html on the child elements. 
Elements only use the styles in the bigger file `default-theme.html`

If I set `useNativeCSSProperties: false` then everything works `fine`

Sorry for the rant...

Would like to know your experiences with v1.6.0 after you upgrade to it...

**Comment by mercmobily** [comment]
The problem I reported above seems to be totally fixed. But if you can clearly reproduce a different problem, then you should definitely open an issue here!
