### ISSUE TITLE
Templatizer: repeated templatize() doesn't forward root properties when _forwardParentProp is set.

### ISSUE THREAD

**Issue by icmdaf** [Polymer/polymer#3755]
### Description

When calling `templatize()` on the same template _again_, and `_forwardParentProp` is present, parent properties aren't forwarded.
#### Live Demo

http://codepen.io/hanger/pen/KrmrJA?editors=1010
#### Observed Results

In the live demo code:

``` javascript
Polymer({
  is: 'x-el',
  behaviors: [Polymer.Templatizer],
  _forwardParentProp() {},
  ready() {
    const tplA = this.querySelector('template.a');
    for(let i = 0 ; i < 3 ; i++) {
      this.templatize(tplA);
      this.appendChild(this.stamp({nameA: i}).root);
    }
  },
});
```

shows the wrong output

> 0 a: fromRoot
> 1 a:
> 2 a:

But

``` javascript
Polymer({
  is: 'x-el',
  behaviors: [Polymer.Templatizer],
  _forwardParentProp() {},
  ready() {
    const tplA = this.querySelector('template.a');
    this.templatize(tplA); // outside loop
    for(let i = 0 ; i < 3 ; i++) {
      this.appendChild(this.stamp({nameA: i}).root);
    }
  },
});
```

and

``` javascript
Polymer({
  is: 'x-el',
  behaviors: [Polymer.Templatizer],
  // no _forwardParentProp
  ready() {
    const tplA = this.querySelector('template.a');
    for(let i = 0 ; i < 3 ; i++) {
      this.templatize(tplA);
      this.appendChild(this.stamp({nameA: i}).root);
    }
  },
});
```

show the correct output

> 0 a: fromRoot
> 1 a: fromRoot
> 2 a: fromRoot
#### Expected Results

In all three cases, the parent binding should be forwarded, not only when calling `templatize()` for the first time. The method specifically deals with the case where it's called repeatedly, so it seems this is supported.

We call `templatize()` multiple times because we want to use multiple templates. Unfortunately `stamp()` doesn't accept the template to use as an argument.
What does work is calling `templatize()` once for each template and setting the private variables `stamp()` reads to switch instead:

``` javascript
this.templatize(tplA);
this.templatize(tplB);

for(let i = 0 ; i < 3 ; i++) {
  this._templatized = tplA;
  this.ctor = tplA._content._ctor;
  this.appendChild(this.stamp({nameA: i}).root);

  this._templatized = tplB;
  this.ctor = tplB._content._ctor;
  this.appendChild(this.stamp({nameB: i}).root);
}
```

I think two things should be done about this:
1. Fix the bug in `templatize()` causing the breakage.
2. Add a template override parameter to `stamp()`:

``` javascript
    /** ...
     * @param {HTMLTemplateElement=} template The template to use (must have been
     *   processed with templatize before), if not given, use the last templatized one.
     */
  stamp: function(model, template) {
      model = model || {};
      var ctor = template ? template._content._ctor : this.ctor;
      if (this._parentProps) {
        var templatized = template ? template : this._templatized;
        for (var prop in this._parentProps) {
          if (model[prop] === undefined) {
            model[prop] = templatized[this._parentPropPrefix + prop];
          }
        }
      }
      return new ctor(model, this);
    },
```

**Comment by icmdaf** [comment]
This is not only triggered when trying to use multiple templates, but also in web component tests using a fixture containing an element that uses the templatizer. The fixture is supposedly torn down at the end, but because the templatizer adds `_content._ctor` to the original element, this persists between test cases, breaking their isolation: every test case in my suite passes on its own, but the suite fails with the errors described in the bug.
A workaround I found is to manually remove the `_content._ctor` from all templates:

```javascript
  teardown(function() {
    for (let template of document.querySelectorAll('template')) {
      if (template._content) {
        template._content._ctor = undefined;
        template._content = undefined;
      }
    }
  });
```

**Comment by liabru** [comment]
I'm having the same (or similar) issues, by making multiple calls to `this.templatize(template)` and `this.stamp()` on the same templates. Works the first time on a given template, but any subsequent calls to `this.stamp()` do not apply bound values on creation. 

I noticed that making changes to bound values _after creation_ do seem to propagate correctly to the stamped elements, indicating that the bindings are there. So I tried the solutions proposed above and many other attempts including `_prepParentProperties` but none worked for me. 

I ended up by initialising the bound values manually at creation time. This seems to work for now... it's a bit of a hack, but in case it helps anyone:

```js
  // this overrides the default from Polymer.Templatizer
  stamp: function(model) {
    model = model || {};

    if (this._parentProps) {
      var templatized = this._templatized;
      for (var prop in this._parentProps) {
        if (model[prop] === undefined) {
          model[prop] = templatized[this._parentPropPrefix + prop];

          // this is a fix for missing initial bindings on subsequent stamps
          // https://github.com/Polymer/polymer/issues/3755
          if (model[prop] === undefined) {
            model[prop] = this._getBinding(prop, this.dataHost);
          }
        }
      }
    }

    return new this.ctor(model, this);
  },

  _getBinding: function(prop, dataHost) {
    var data = dataHost && dataHost.__data__;

    if (!data) {
      return undefined;
    }

    if (prop in data) {
      return data[prop];
    }

    return this._getBinding(prop, dataHost.dataHost);
  }
```

**Comment by nelsonsilva** [comment]
Ran into this same issue. @liabru workaround seems to do the trick 👍

**Comment by TimvdLippe** [comment]
With the new model of `Polymer.Templatize.templatize` (https://github.com/Polymer/polymer/blob/72a59f77cd5375d3bb691b0396c1f4b30ac722d8/lib/utils/templatize.html) this issue has been resolved. You can now stamp multiple unique templates. An example which uses 2 templates and correctly implements `forwardHostProp` is http://jsbin.com/zoludihiqo/edit?html,console,output
