### ISSUE TITLE
Why load the same html file twice?

### ISSUE THREAD

**Issue by YingshanDeng** [Polymer/polymer#3759]
Hello, In my project, the index.html import another html file 
```
<link rel="import" href="/views/index/indexContainer.build.html">
```
And when I open the index.html in browser, I found the indexContainer.build.html file load twice.
![image](https://cloud.githubusercontent.com/assets/7246595/16515605/84449764-3fa5-11e6-8522-b9c9f90ed8ee.png)

I don't know why. And I open the polymer website: https://www.polymer-project.org/1.0/
And found the same thing
![image](https://cloud.githubusercontent.com/assets/7246595/16515632/af24f122-3fa5-11e6-97ee-7b924ac5435b.png)

**Comment by naoak** [comment]
I've met a similar issue on Chrome 48.0.2564.23 beta (64-bit). In my case, I guess devTools bug or something.

**Comment by BLamy** [comment]
Doesn't look like a dev tools bug given the fact that they have a different timeline.

**Comment by akheelkm007** [comment]
I am also facing the same issue on Chrome Version 51.0.2704.84 (64-bit).
Works fine on Firefox 44.0 though.

**Comment by akheelkm007** [comment]
@naoak I don't think it's a devTools bug. I am currently working on a website with Polymer and when I test it with a local server, I get two requests for a component "xl-app".

`127.0.0.1 - - [01/Jul/2016 18:55:24] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Jul/2016 18:55:24] "GET /src/xl-app.html HTTP/1.1" 200 -
127.0.0.1 - - [01/Jul/2016 18:55:40] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Jul/2016 18:55:40] "GET /src/xl-app.html HTTP/1.1" 200 -
127.0.0.1 - - [01/Jul/2016 18:55:41] "GET /images/excel.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Jul/2016 18:55:41] "GET /src/xl-view1.html HTTP/1.1" 200 -
127.0.0.1 - - [01/Jul/2016 18:55:41] "GET /images/icons/excel-32x39.png HTTP/1.1" 200 -
`

**Comment by abdonrd** [comment]
@paulirish said it's a Chrome bug: https://github.com/PolymerElements/polymer-starter-kit/issues/791#issuecomment-209502458

**Comment by YingshanDeng** [comment]
OK，thank you all 👍
