### ISSUE TITLE
[1.x, 2.x] Tests are running in old version of Firefox

### ISSUE THREAD

**Issue by tomalec** [Polymer/polymer#3760]
### Description

Due to the Firefox - Selenium bug, Firefox version was changed to `46.0`.

It's no longer necessary as SeleniumHQ/selenium/issues/2110 is fixed.
#### Live Demo
- 1.6.0 https://travis-ci.org/Polymer/polymer/builds/141155291
- 2.0-preview https://travis-ci.org/Polymer/polymer/builds/164159514
#### Steps to Reproduce
1. Run travis
#### Expected Results

Tested in `latest`
#### Actual Results

Tested in `46.0`
### Browsers Affected

n/a
### Versions
- Polymer: v1.6.0, v2.0-preview
- webcomponents: n/a

**Comment by tomalec** [comment]
@tjsavage it also applies to 2.0 https://github.com/Polymer/polymer/blob/2.0-preview/.travis.yml#L6

**Comment by kevinpschaaf** [comment]
Closing, as we now test the latest version of Firefox on Travis.
