### ISSUE TITLE
Is there a page contains all the elements of a polymer pages, will not happen again what elements 404.

### ISSUE THREAD

**Issue by 2947721120** [Polymer/polymer#3763]
#### Live Demo

https://jsbin.com/xukike/edit?html,output

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: vX.X.X
- webcomponents: vX.X.X

**Comment by LM450N** [comment]
I don't understand what do you mean. Are you looking for the [Polymer elements](https://elements.polymer-project.org/browse) ?

**Comment by 2947721120** [comment]
Is a polymer often have to import html. 404 will often appear that page!
Those pages should be the elements of it? There are no configured all of a page (that includes all the elements published)
One will import a page, a lot of trouble!

**Comment by ebidel** [comment]
Not sure what this is after, but imports are the dependency system for Polymer's web components. You need to import an element (definition) to use the element.

You can create an import that imports all the elements of a given collection. For example, paper-elements has one of these: https://github.com/PolymerElements/paper-elements/blob/master/paper-elements.html
