### ISSUE TITLE
Uncaught TypeError in polymer-mini.html:2044

### ISSUE THREAD

**Issue by 5amfung** [Polymer/polymer#3766]
I'm getting this from the console.

![image](https://cloud.githubusercontent.com/assets/371691/16637632/442d1f86-4395-11e6-8569-034dd3d83fd4.png)

This is the html I'm trying to show:

```
<app-drawer-layout>
    <app-drawer>
        <app-toolbar style="background-color: #4285f4; color: white;">Infocery</app-toolbar>
    </app-drawer>

    <app-header-layout>
        <app-header reveals effects="waterfall">
            <app-toolbar>
                <paper-icon-button icon="menu" drawer-toggle></paper-icon-button>
                <div title>{{ title }}</div>
                <paper-icon-button icon="search"></paper-icon-button>
            </app-toolbar>
        </app-header>

        <!-- Main content -->
        <div class="layout vertical" style="padding: 16px;">
            <router-outlet></router-outlet>
        </div>
    </app-header-layout>

</app-drawer-layout>

```
#### Actual Results

I expect no TypeError.
### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions
- Polymer: polymer#1.6.0
- webcomponents: app-layout#0.9.1

**Comment by TimvdLippe** [comment]
Closing this issue as it lacks a runnable JSBin. If you still can reproduce this issue, please open an issue at https://github.com/polymerelements/app-layout
