### ISSUE TITLE
notifyPath should re-set root-properties when the binding target does not support notifyPath

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#3767]
### Description

When handling path notifications, `notifyPath` should set root-properties when the binding target does not support `notifyPath`.  There are 2 cases where a path notification currently gets dropped on the floor:
- The binding target is not a Polymer element and thus does not support path notifications, e.g. `<a href="/list?items={{items}}>`, where `items` is e.g. an Array that should be stringified
- The binding target _is_ a Polymer element, but the binding is to a property that doesn't have property effects, e.g. `<my-element>{{items}}</my-element>`, where `items` is an Array that should be stringified into `textContent`
#### Live Demo

https://jsbin.com/coluvaw/1/edit?html,output
#### Steps to Reproduce
1. open link
2. click "add friends" button
#### Expected Results

0,1,2,3,4
#### Actual Results

0,1,2,3
### Browsers Affected

All
### Versions
- Polymer: v1.6

**Comment by robdodson** [comment]
Poke. Any plans to implement this?

**Comment by TimvdLippe** [comment]
Closing as this appears to be fixed in Polymer 2: https://jsbin.com/yuxupefone/edit?html,console,output
