### ISSUE TITLE
rules inside media queries don't apply correctly in IE 11 and 10

### ISSUE THREAD

**Issue by blasten** [Polymer/polymer#3770]
### Description
Rules inside media queries don't apply correctly if custom properties are used inside a `:host` rule.

#### Live Demo

(Open in IE 11 or IE 10)  The box should match the background color.
http://jsbin.com/qanepud/edit?html,output

#### Steps to Reproduce

1. Consume a custom property e.g. `color: var(--color, red);`
2. Set that `--color` property from a `:host` rule inside a media query.
3. Add a few other rules to the media query to change the appearance of the page.
4. Call `updateStyles` on window resize.
5. Try to resize the window until it hits the media query.
-->

#### Expected Results

The rules inside the media query should take effect if the media query is matching. Similarly the properties that consume a custom property set from a media query should update their value.

#### Actual Results
Rules inside the media query are occasionally ignored similarly custom properties aren't set properly.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [X] IE 11
- [X] IE 10

### Versions

- Polymer: v1.6.0
- webcomponents: latest

**Comment by azakus** [comment]
Seeing similar behavior in this JSBin that doesn't have Polymer at all: http://jsbin.com/vocoqu/edit?html,output

**Comment by azakus** [comment]
It looks like this is a style-recalc bug in related to `@media` rules in styles that are outside the DOM. The simplest fix is to rebuild the CSSOM by resetting the textContent of the cached style node.
