### ISSUE TITLE
error:   Could not download release from Polymer/app-drawer-template error:   Uncaught exception: getaddrinfo EAI_AGAIN api.github.com:443 error:   Error: getaddrinfo EAI_AGAIN api.github.com:443

### ISSUE THREAD

**Issue by skeleton007** [Polymer/polymer#3771]
`error:   Could not download release from Polymer/app-drawer-template
error:   Uncaught exception: getaddrinfo EAI_AGAIN api.github.com:443
error:   Error: getaddrinfo EAI_AGAIN api.github.com:443
`

Unable to get data. i'm behind proxy server

**Comment by TimvdLippe** [comment]
Please follow the guidelines for creating issues at https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs
