### ISSUE TITLE
Passing property name in property observer effect to the observing method

### ISSUE THREAD

**Issue by aahoo** [Polymer/polymer#3775]
Changing [this line](https://github.com/Polymer/polymer/blob/master/src/lib/bind/effects.html#L49) to

``` js
      fn.call(this, value, old, effect.property);
```

will make property observers way more useful. They can virtually replace the complex observer effect. In addition, the function being called knows **what** has changed **from** what **to** what to take the needed action.

**Comment by kaste** [comment]
Ideally we would just get the whole event information. See #3554 where I propose to also get the `fromAbove` value. Likewise #3573 where I propose `custom effects` which get both the `path` (property) you want and the `fromAbove` flag.

**Comment by TimvdLippe** [comment]
In general simple observers do not need this information, as they should be unique. If you do want to have 1 observer for all your properties, you can implement that yourself with a solution like http://jsbin.com/jiyawurudo/edit?html,console,output In general, the advice is to not duplicate this behavior and instead use a complex observer for these purposes.
