### ISSUE TITLE
Failed to execute 'registerElement' on 'Document': Registration failed for type 'dom-module'. A type with that name is already registered.

### ISSUE THREAD

**Issue by chiukit** [Polymer/polymer#3778]
### Example code

example code 1: https://jsbin.com/bidahevowu/edit?html
example code 2: https://jsbin.com/babudihugu/edit?html,js
#### Steps to Reproduce
1. Upload Web component to S3 (please see example code 1)
2. Load the web component by using js (please see example code 2)
#### Expected Results

No error is throw
#### Actual Results

polymer-micro.html:347 Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'dom-module'. A type with that name is already registered.

Detail: https://i.imgsafe.org/4f904161fa.png
### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions

- Polymer: v1.6.0
- webcomponents: v0.7.22

**Comment by iSuslov** [comment]
I just faced the same issue. I have everything working on dev mode, but after build it throws the same error. What's that?

**Comment by AmitM30** [comment]
Hey, I am facing similar issue on Chrome 38 browser:
Failed to execute 'registerElement' on 'Document': Registration failed for type 'iron-request'. A type with that name is already registered.

"platform": "Linux armv7l",
"vendor": "Google Inc.",
"userAgent": "Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-G531H Build/LMY48B) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.3 Chrome/38.0.2125.102 Mobile Safari/537.36",
"browserVersion": "Chrome 38"

**Comment by iSuslov** [comment]
@AmitM30 take a look on this issue, maybe you will find a workaround https://github.com/Polymer/polymer/issues/4134

**Comment by Ram-SR** [comment]
I have the same issue

**Comment by TimvdLippe** [comment]
Please follow the guidelines for creating issues at https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs
