### ISSUE TITLE
:host(tag-name:focus):before does not work in the shady dom

### ISSUE THREAD

**Issue by notwaldorf** [Polymer/polymer#3781]
This came up in https://github.com/PolymerElements/paper-item/issues/85

**Comment by mgiuffrida** [comment]
Thanks for tracking this down. Here's a fiddle showing the style applying to the entire focused element, not just the `:before` content, in shady DOM: https://jsfiddle.net/6z7rb91q/

**Comment by arthurevans** [comment]
Shouldn't that be:

    :host(x-foo:focus:before)?

​That works correctly for me in both shadow and shady.

OK,
Arthur
​

**Comment by notwaldorf** [comment]
@sorvell says that unlike `:focus`, `:before` is a pseudo-element and shouldn't go in the brackets. The fact that it works is an accident and, at least in the `paper-item` PR, it doesn't work in the shadow DOM

**Comment by TimvdLippe** [comment]
This appears to be fixed. In Firefox and Chrome in http://jsbin.com/cihuvugela/edit?html,output I can click the text "my element" and it receives a red background color.
