### ISSUE TITLE
Should queryDistributedElements(slctr) be  queryEffectiveChildNodes(slctr)?

### ISSUE THREAD

**Issue by mercmobily** [Polymer/polymer#3783]
It's a tricky question. Please allow me to go back one step and make a short summary of Polymer's own ["children" API](https://github.com/Polymer/polymer/blob/master/src/standard/utils.html). Here they are, with a brief description for each "group" (please bear with me)

**Group 1**  
`getEffectiveChildNodes()`, `getEffectiveChildren()` and `getEffectiveTextContent()` Executive summary: they simply return nodes from the the LIGHT DOM using the DOM's `getEffectiveChildNodes()` call. Elements distributed via `<content>` are included. NOTE: `getEffectiveChildren()` will filter so that only `Node.ELEMENT_NODE` are returned, while `getEffectiveTextContent()` will filter so that only `node.COMMENT_NODE` elements are returned

```
getEffectiveChildNodes: function() {
  return Polymer.dom(this).getEffectiveChildNodes();
},
getEffectiveChildren: function() {
  var list = Polymer.dom(this).getEffectiveChildNodes();
  return list.filter(function(n) {
    return (n.nodeType === Node.ELEMENT_NODE);
  });
},
getEffectiveTextContent: function() {
  var cn = this.getEffectiveChildNodes();
  var tc = [];
  for (var i=0, c; (c = cn[i]); i++) {
    if (c.nodeType !== Node.COMMENT_NODE) {
      tc.push(Polymer.dom(c).textContent);
    }
  }
  return tc.join('');
},
```

**Group 2**  
`queryEffectiveChildren(slctr)` and `queryAllEffectiveChildren(slctr)` simply query the LIGHT DOM using `queryDistributedElements(slctr)`. 

```
queryEffectiveChildren: function(slctr) {
  var e$ = Polymer.dom(this).queryDistributedElements(slctr);
  return e$ && e$[0];
},
queryAllEffectiveChildren: function(slctr) {
  return Polymer.dom(this).queryDistributedElements(slctr);
},
```

**Group 3**  
`getContentChildNodes(slctr)` and `getContentChildren(slctr)` They look for slctr (or 'content' by default) in the LOCAL DOM, and then use DOM's `getDistributedNodes()` to find out what nodes were distributed

```
getContentChildNodes: function(slctr) {
  var content = Polymer.dom(this.root).querySelector(slctr || 'content');
  return content ? Polymer.dom(content).getDistributedNodes() : [];
},
getContentChildren: function(slctr) {
  return this.getContentChildNodes(slctr).filter(function(n) {
    return (n.nodeType === Node.ELEMENT_NODE);
  });
},
```

The "low-level" shad[y|om] calls used here are:
- `getDistributedNodes()`. This is the only "native" one used when using Shadow DOM.
- `getEffectiveChildNodes()`. This is implemented using `getDistributedNodes()` whenever a `<content>` element is met
- `queryDistributedElements(slctr)`. This is effectively a filter to `getEffectiveChildNodes()`.

Now, since `queryDistributedElements()` is effectively a `getEffectivechildren()` with querying abilities on top, wouldn't it make more sense (especially having seen the API above) to call it `queryEffectiveChildNodes()`? 

Bonus question:

Which methods are likely to make it to the Shadow DOM standard? I know `getDistributedNodes()` is. I realise the need for the concept of "effective children", to vouch for the case where you have:

```
<container-element>

  <some-fancy-element>
    <content></content>
  </some-fancy-element>

</container-element>
```

Here `<some-fancy-element>` has `<content>` in its light DOM, but that `<content>` actually becomes whatever `<container-element>` distributes. This is a tricky situation, and knowing the _effective children_ is important. So, shouldn't it be part of the Shadow DOM specs? Or, will it be?

**Comment by TimvdLippe** [comment]
Sorry for not getting back to you sooner. As `Polymer.dom` is deprecated, I am going to close this issue. The native API's can now be used with Polymer, so that should resolve the ambiguity :smile:
