### ISSUE TITLE
Perf: Do not add document-level blocking touch listeners

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#3787]
All polymer apps get a touch listener added to `document` by default?

<img width="459" alt="screen shot 2016-07-19 at 5 46 31 pm" src="https://cloud.githubusercontent.com/assets/238208/16971477/f0eb25e0-4dd8-11e6-9edc-f6870391873c.png">
<img width="420" alt="screen shot 2016-07-19 at 5 47 01 pm" src="https://cloud.githubusercontent.com/assets/238208/16971476/f0eaa228-4dd8-11e6-88c4-65f6eb667e14.png">
<img width="414" alt="screen shot 2016-07-19 at 5 47 29 pm" src="https://cloud.githubusercontent.com/assets/238208/16971478/f0ee8e7e-4dd8-11e6-82c1-e7485d76fbdc.png">

Doing so is typically frowned upon b/c it can have negative effects on page load and scrolling perf, especially on mobile. What are these events for? Can they be passive events by default...or can we have users opt-into passive events somehow if they know they're not going to call `preventDefault()`?

https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md

cc @RByers @azakus

**Comment by RByers** [comment]
Back in the day I know @azakus worked to ensure this wasn't necessary (it was one of the original complaints about the PointerEventPolyfill).  We're pretty close to [forcing all touch listeners on the document to be passive by default anyway](https://github.com/WICG/interventions/issues/18) - you can enabled this in chrome://flags, and I haven't noticed any issues with polymer.  So perhaps it's easy to just make these listeners passive?

**Comment by eduardosada** [comment]
What can we do about this? Any idea?

**Comment by esd100** [comment]
What is going here and why is there no final answer?

I'm getting thousands of console warnings:
```Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.```

**Comment by bennypowers** [comment]
Is this the `_globalOnClick` listener in [iron-location](https://github.com/PolymerElements/iron-location/blob/master/iron-location.html#L273)?

**Comment by Thkasis** [comment]
Just wondering if there's any updates on this?!
