### ISSUE TITLE
Template tags contents style scope not updating when added to elements local dom.

### ISSUE THREAD

**Issue by jrmerz** [Polymer/polymer#3788]
### Description

When a custom element adds a <template /> from it's light dom to its local dom, the contents of the template are not properly scoped when styled.
#### Live Demo

https://jsbin.com/towovoqihu/edit?html,output
#### Steps to Reproduce
1. Create `my-element`
   1. add styles for contents of template to be stamped
   2. move template tag from light dom to local dom (see js bin) 
2. Append `my-element` to document.body
   1. add `template` tag to `my-elements` local dom with content to be styled 
3. stamp template to local dom
#### Expected Results

templates contents are styled via my-element
#### Actual Results

templates contents are **not** styled via my-element
### Browsers Affected
- [x] Chrome
- [x] Firefox
- [ ] Edge (not tested)
- [x] Safari 9
- [ ] Safari 8 (not tested)
- [ ] IE 11 (not tested)
### Versions
- Polymer: v1.6.0
- webcomponents: v0.7.22

**Comment by TimvdLippe** [comment]
Closing this issue as it concerns `Polymer.dom` which has been deprecated and is on the legacy mixin. You can use the native DOM API's instead.
