### ISSUE TITLE
How to genereate spritesheet and auto replace css?

### ISSUE THREAD

**Issue by YingshanDeng** [Polymer/polymer#3789]
Hello, In Polymer project build release, there is a task that generate the images into spritesheets and then auto replace the css. And now I can deal with one component file. It is my demo: https://github.com/YingshanDeng/polymer-generate-spritesheet. Any guid, thank you! 

@ebidel

**Comment by ebidel** [comment]
This seems specific to your app and unrelated to an issue in Polymer.
