### ISSUE TITLE
Issue warning when attempting to define a native DOM property on the prototype

### ISSUE THREAD

**Issue by azakus** [Polymer/polymer#379]
Due to the magical ways that native DOM properties are handled by the browser, we should try to warn users if they attempt to define properties like "id" or "title" themselves.

In particular if we can emit a warning on things like

```html
<polymer-element name="x-foo" attributes="id title">
```

We can save users on some real headaches.

This will fix issues like #332.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
