### ISSUE TITLE
mixin escapes local style scope for multiple elements

### ISSUE THREAD

**Issue by yangchenyun** [Polymer/polymer#3791]
### Description

In a DOM where there are indirectly nested elements; mixin for the top one will affect the rest.
@justinfagnani I encounter this bug multiple times when developing go/yelement, the current workaround for me is the use `!important` on nested mixin items.
#### Live Demo

https://jsfiddle.net/bysyoLk8/
#### Expected Results

first shadow is shown; the nested shadow should be none
first panel has padding, the nested should be none
#### Actual Results

shadow mixin of the outermost component is used for all components
padding is used for all nested components
### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions
- Polymer: HEAD
- webcomponents: a few, <paper-header-panel> in example, <app-drawer>'s `#containerContent` etc.

**Comment by TimvdLippe** [comment]
This issue was moved to webcomponents/shadycss#161
