### ISSUE TITLE
Outdated Docs

### ISSUE THREAD

**Issue by Pablo-Ivan** [Polymer/polymer#3792]
Ok, so I can see that in NPM and the changelog, Polymer is now 1.6.0, this was amde 21 days ago yet the docs still showing 1.5.0 as the latest version.

**Comment by ebidel** [comment]
Can you point us to what docs you're referring to?

**Comment by arthurevans** [comment]
The 1.6.0 release notes haven't been posted yet. Sorry for the delay. Working on getting those posted today.

**Comment by Pablo-Ivan** [comment]
@ebidel This [Docs](https://www.polymer-project.org/1.0/docs/release-notes)

**Comment by arthurevans** [comment]
Redeployed the docs site. Sorry for the confusion.
