### ISSUE TITLE
Proposal: Add logger as global setting

### ISSUE THREAD

**Issue by abdonrd** [Polymer/polymer#3795]
As we discussed here https://github.com/PolymerElements/iron-ajax/pull/200#issuecomment-234109205 with @valdrinkoshi...

Perhaps add a `logger` [Polymer global settings](https://www.polymer-project.org/1.0/docs/devguide/settings) might be a good idea?

Something like:

``` html
<script>
  window.Polymer = {
    logger: true
  };
</script>
```

**Comment by TimvdLippe** [comment]
The original `_warn` and friends have been removed, therefore I am closing this issue.
