### ISSUE TITLE
Style caching can be incorrect in document when `style is=custom-style` is used

### ISSUE THREAD

**Issue by azakus** [Polymer/polymer#3801]
#### Live Demo

test/smoke/custom-style-cache.html

#### Expected Results
First element has a font-size of 32px
Second element has a font-size of 12px

#### Actual Results
Both elements have a font-size of 32px

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions

- Polymer: v1.6.0

**Comment by sorvell** [comment]
Quick debugging note: the test case is fixed if `Polymer.updateStyles()` is called.

**Comment by sorvell** [comment]
The style caching system relies on the ability to know the [index](https://github.com/Polymer/polymer/blob/master/src/lib/style-properties.html#L268) of each style rule. This indexing is performed not by the css parser but by the `StyleProperties.decorateStyles`. It is therefore required that a host has called this method prior to any elements in that scope calling `_updateStyleProperties` and looking up their scope style rules.

This should be guaranteed for any element scopes, but it is not guaranteed for the root styling scope, `Polymer.StyleDefaults`. `StyleDefaults` only decorates its styles the first time `_styleProperties` is read.

This may be [after](https://github.com/Polymer/polymer/blob/master/src/standard/x-styling.html#L168) an element in this scope calls `_updateStyleProperties` and tries to [calculate scope data](https://github.com/Polymer/polymer/blob/master/src/standard/x-styling.html#L104).

One way to fix this is to make sure the scope has `_styleProperties` right when the scope is determined at the top of `_updateStyleProperties`.
