### ISSUE TITLE
Custom CSS variable shim applies invalid custom variables

### ISSUE THREAD

**Issue by mgiuffrida** [Polymer/polymer#3803]
Hooray for [red herrings](https://github.com/Polymer/polymer/issues/3802)! What does this do?

```
:host {
  --my-color: inherit;
  color: var(--my-color, red); /* Spoiler: Should resolve to red. */
}
```

To [substitute a var()](https://www.w3.org/TR/css-variables/):

* If the value of the custom property named by the first argument to the var() function is **anything but the initial value**, replace the var() function by the value of the corresponding custom property.
* Otherwise, if the var() function has a fallback value as its second argument, **replace the var() function by the fallback value.**

[Without useNativeCSSProperties, this doesn't work](https://jsfiddle.net/mgiuffrida/xhc8cdtd/) in a dom-module.

I tried testing in a `<style is="custom-style">` without a dom-module, but [NO variables seem to work in a custom-style](https://jsfiddle.net/mgiuffrida/29z1Lvhr/) without useNativeCSSProperties.

**Comment by mgiuffrida** [comment]
If I'm correct that `useNativeCSSProperties` causes 1.6.0 to do the right thing here, then this isn't a regression: [same repro in 1.1.0](https://jsfiddle.net/mgiuffrida/zskqLf4q/). But it does mean that enabling `useNativeCSSProperties` changes the behavior of some stuff which happens to break Chrome UI.

**Comment by sorvell** [comment]
The issue here is that the custom property shim does not treat the values of `initial` or `inherit` correctly.

To fix `inherit` we will need to copy the element host's property value to the element.
To fix `initial` we will need to ensure that property resolution uses the fallback value in this case.
