### ISSUE TITLE
dom-repeat current item via event

### ISSUE THREAD

**Issue by mbana** [Polymer/polymer#3804]
Hi.

I am the only one who likes wrapping dom-repeat items into separate components? See this http://plnkr.co/edit/cgSRDI?p=preview which does https://www.polymer-project.org/1.0/docs/devguide/templates#handling-events but pushes the responsibility of getting the current model item to the `s-menu-item` vs:

``` javascript
      order: function(e) {
        var model = e.model;
        model.set('item.ordered', model.item.ordered+1);
      }
```

or better yet allow the click handler to execute an atomic function call on the model object that way, we don't need to create functions.

**Comment by kaste** [comment]
Is this a question, a proposal or a bug description? Sorry I don't quite understand.

**Comment by TimvdLippe** [comment]
This issue is quite old and the intent is not clear to me. I am closing this for now, but feel free to reopen if you think we have to address a bug/feature on Polymer still.
