### ISSUE TITLE
queryEffectiveChildren only returning a list of *direct* children: alternative

### ISSUE THREAD

**Issue by mercmobily** [Polymer/polymer#3805]
Hi,

At the moment `this.queryEffectiveChildren` will only return the FIRST level of children. This is due to the fact that `queryDistributedElements` is not recursive.

When writing decorators, it's often important to return _all_ of them. For example, I want to look for a specific element in my light DOM and listen to events on that.

The implementation is super trivial and it's very similar to the current implementation:

```
  Polymer.DomApi.prototype.queryDistributedElements = function( selector ){
    var list = [];
    function visit( node ){
      var c$ = Polymer.dom( node ).getEffectiveChildNodes();
      for( var i = 0, l = c$.length, c; (i < l), ( c = c$[ i ] ); i ++ ){
        if (c.nodeType === Node.ELEMENT_NODE ){

          // If selector matches, add
          if( Polymer.DomApi.matchesSelector.call( c, selector ) ){
            list.push( c );
          }
          visit( c );
        }
      }
    }
    visit( this );
    return list;
  }
```

I realise there are performance issues here, but... what's the alternative, really?

**Comment by mercmobily** [comment]
For what it's worth, at the moment it's easy to have a "deep selector" with Polymer with the following monkey patching:

    <script>
        Polymer.DomApi.prototype.queryDistributedElementsDeep = function( selector ){
          var list = [];
          function visit( node ){
            var c$ = Polymer.dom( node ).getEffectiveChildNodes();
            for( var i = 0, l = c$.length, c; (i < l), ( c = c$[ i ] ); i ++ ){
              if (c.nodeType === Node.ELEMENT_NODE ){

                // If selector matches, add
                if( Polymer.DomApi.matchesSelector.call( c, selector ) ){
                  list.push( c );
                }
                visit( c );
              }
            }
          }
          visit( this );
          return list;
        }

        Polymer.Base.queryEffectiveChildrenDeep = function( slctr ){
          var e$ = Polymer.dom(this).queryDistributedElementsDeep(slctr);
          return e$ && e$[0];
        }

        Polymer.Base.queryAllEffectiveChildrenDeep = function( slctr ){
          return Polymer.dom(this).queryDistributedElementsDeep(slctr);
        }
    </script>

Is it worthwhile for me to make a Github module with these functions?

**Comment by mercmobily** [comment]
@tjsavage Taylor, so that I know... does the `1.x` tag mean that what I wrote actually makes sense?

**Comment by tjsavage** [comment]
I've mass-applied the `1.x` tag to issues that apply to Polymer version 1.x, to keep these issues separate from 2.0-related issues

**Comment by mercmobily** [comment]
Ahahaha wishful thinking on my side!

**Comment by TimvdLippe** [comment]
@mercmobily Could you check with Polymer 2 (https://www.polymer-project.org/2.0/docs/upgrade#polymer-dom-apis) that the new version still has this issue? We would need a JSBin to show the issue.

**Comment by mercmobily** [comment]
I have never used Polymer 2. I am a little clumsy with it I am afraid. Tim, can I ask you -- as a favour -- to send me a link to a "blank" JSBin that actually works with P2? I am failing miserably at doing just that... Plus, I guess things will work on Chrome since there will be no need to transpiling, right?

**Comment by TimvdLippe** [comment]
@mercmobily http://jsbin.com/luhaxab/edit?html,output is the JSBin we use for that. It is included in the CONTRIBUTING.md: https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs Happy to help you out if you have trouble reproducing the issue in that JSBin :smile:

**Comment by mercmobily** [comment]
You just made my life so much easier, I feel ashamed of even being here :D
Will get to it this morning...!

**Comment by mercmobily** [comment]
Tim, can I be a royal pain and can I ask for a jsbin that uses Polymer 1,
so that I can compare the two and show the differences? I seem to have lost
all of my jsbins and pain killers are not helping me right now. This is the
last stupid favour I ask, I promise.

**Comment by TimvdLippe** [comment]
Sadly its a long weekend, so I can only check it on tuesday. Do keep in mind that we will not make any enhancements to Polymer 1, so we advise you to upgrade to 2 instead.

**Comment by mercmobily** [comment]
Oh don't worry about that actually, I will just make sure it all works in
Polymer 2.

**Comment by TimvdLippe** [comment]
I am closing this issue for now. Feel free to reopen if you managed to create a new JSBin with Polymer 2 :smile:
