### ISSUE TITLE
Type extending a blacklisted element should not let the developer apply styles.

### ISSUE THREAD

**Issue by robdodson** [Polymer/polymer#3808]
The Shadow DOM spec states that some elements can not have their UA shadow roots replaced with author defined shadow roots https://www.w3.org/TR/2014/WD-shadow-dom-20140617/#html-elements-and-their-shadow-trees but using Shady DOM you can do this which leads to confusion when native Shadow DOM is turned on.

Example: https://jsbin.com/wuyesi/5/edit?html,output
Toggle the setting from `shady` to `shadow` and see that the type extended input is no longer styled and the error `VM84 polymer-mini.html:1999 Uncaught InvalidStateError: Failed to execute 'createShadowRoot' on 'Element': Shadow root cannot be created on a host which already hosts an user-agent shadow tree.` is thrown.

It would be nice if Shady DOM behaved like native Shadow DOM here so developers don't accidentally rely on this behavior.

**Comment by TimvdLippe** [comment]
This has been fixed in Polymer 2: http://jsbin.com/canupevugi/edit?html,console,output per https://github.com/Polymer/polymer/blob/4a2d427f5d18ddc78fd31e1e33ff35443e381007/lib/mixins/element-mixin.html#L687
