### ISSUE TITLE
querySelector fails to find distributed node under certain circumstances

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#3809]
### Description

In following sample:

``` html
<dom-module id="my-element">
  <template>
    <div id="content">
      <content></content>
    </div>
  </template>
</dom-module>
<script>
  Polymer({
    'is': 'my-element',
    properties: {
      'this': {
        notify: true,
        readOnly: true,
        type: Object
      }
    },
    attached: function(){
      if (!this['this']) {
        this._setThis(this);
      }
    }
  });
  console.log(document.querySelector('body > my-element > button'));
</script>
<my-element>
  <button></button>
</my-element>
```

`my-element > button` doesn't work.
#### Live Demo

https://jsbin.com/renoracuxu/edit?html,output
#### Steps to Reproduce

Just look at console in demo
#### Expected Results

In Chromium you'll see `<button></button>`
#### Actual Results

In Firefox `null`
### Browsers Affected
- [ ] Chrome
- [x] Firefox
### Versions
- Polymer: v1.6.0
- webcomponents: v0.7.22

**Comment by TimvdLippe** [comment]
I think this is a known limitation of the shim, as it moves around nodes to be able to mimic slots. WDYT @azakus ?
