### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by gondar00** [Polymer/polymer#3810]
![screenshot from 2016-07-26 16 40 17](https://cloud.githubusercontent.com/assets/12490590/17135901/d56218b6-534f-11e6-97c9-8695355a85d3.png)

**Comment by gondar00** [comment]
Fixed by upgrading nodejs to the latest version. 
http://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version

**Comment by kaste** [comment]
Then, this can be closed?

**Comment by TimvdLippe** [comment]
Closing per above comment.
