### ISSUE TITLE
app-drawer-layout stylings ignore app-header custom element 

### ISSUE THREAD

**Issue by erinhong17** [Polymer/polymer#3813]
### Bug Description
Css styling and other rules do not reach custom app-header element. 
For example, the menu paper icon button is expected to be invisible and drawer is visible until screen is small enough where drawer hides, menu button is visible and functions to open drawer. 

Bug: Stylings on the content from app-drawer-layout does not reach paper-icon-button within a custom element `#contentContainer:not(.narrow) > ::content > ::content > ::content[drawer-toggle] { display:none;}` <br/ >
Menu appears from the beginning with drawer, clicking on menu button to toggle the drawer no longer works which is expected to work with the drawer-toggle property. <br />
Noticed that header is also no longer fixed and scrolls with the remainder of the app-header-layout has-scrolling-region property. 

#### Steps to Reproduce
1. Open my-app.html found in demo/ create own 
2. Within  `<app-header-layout>`, create custom element for ex `<my-header>`
HTML Skeleton for `<my-header>`: <br/>
`<app-header>`   <br/>
`<app-toolbar> `<br/>
`<paper-icon-button icon="menu" drawer-toggle></paper-icon-button>`<br/>
`<div title>My Title</div>`<br/>
`</app-toolbar>`<br/>
`</app-header>`

### Browsers Affected

- [x] Chrome

**Comment by ebidel** [comment]
This issue was moved to PolymerElements/app-layout#321
