### ISSUE TITLE
importHref only triggers onload and onerror if first invocation has listeners

### ISSUE THREAD

**Issue by TimLuq** [Polymer/polymer#3814]
### Description

`Polymer.Base.importHref` only triggers `onload` and `onerror` if first invocation has listeners. If another call to the same URI is made with load or error listeners these will never be called.

Imagine a scenario where two different components lazyload the same import, one of which cares for load events and one who just progressively enhance the experience. If the one which doesn't need to know whether or not the load is complete is initiated before the component that cares no load event will be triggered at all.
#### Live Demo

Example using a delayed prefetch for `paper-toast`. The button _Your toast_ must be clicked at least once before prefetching is complete to be able to show a toast using that button.
https://jsbin.com/behoyu/15/edit?html,output
#### Steps to Reproduce
1. Call `Polymer.Base.importHref('a.html', null, null, true)`
2. Wait for load to complete.
3. Call `Polymer.Base.importHref('a.html', e => console.log('onload', e), e => console.log('onerror', e), true)`

Neither `onload` nor `onerror` will be shown in the console.
#### Expected Results

Ordering of the two calls in the example should be of no consequence. The `load` or `error` listeners should be called in either case.
##### Expected Results - Example
1. Call `Polymer.Base.importHref('a.html', null, null, true)`
2. Wait for load to complete.
3. Call `Polymer.Base.importHref('a.html', e => console.log('onload', e), e => console.log('onerror', e), true)`

and
1. Call `Polymer.Base.importHref('a.html', () => {}, () => {}, true)`
2. Wait for load to complete.
3. Call `Polymer.Base.importHref('a.html', e => console.log('onload', e), e => console.log('onerror', e), true)`

should generate the same console output.
#### Actual Results

If first call is with no listeners the load and error callbacks in subsequent calls will never fire.
### Browsers Affected

All
### Versions
- Polymer: my guess is since #3638 got fixed.

**Comment by ebidel** [comment]
Looks like a regression. #3638 looks like an obvious culprit. cc @sorvell

**Comment by TimLuq** [comment]
Made a pull request for one way to resolve this issue. The pull request always adds a listener to set `__firedLoad` or `__firedError` on the first call even if no user callback is given.
