### ISSUE TITLE
Avatar shown on wrong email account

### ISSUE THREAD

**Issue by mikebobadilla** [Polymer/polymer#3820]
I received an email and the avatar of the person below showed up in that emails avatar position.

![image](https://cloud.githubusercontent.com/assets/5985141/17194284/07b9cec8-540c-11e6-938e-de73c29dc63a.png)

**Comment by Pablo-Ivan** [comment]
How is this relevant to Polymer?

**Comment by mikebobadilla** [comment]
you know what, Im really sorry.

Mike Bobadilla

Sent from
https://polymail.io/

On Wed, Jul 27, 2016 at 4:45 PM "Pablo Ivan G. Soto"

<
mailto:
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

How is this relevant to Polymer?

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/Polymer/polymer/issues/3820#issuecomment-235755300
, or
