### ISSUE TITLE
array-selector to select all / deselect all

### ISSUE THREAD

**Issue by sowsan** [Polymer/polymer#3827]
Looking at the documentation it seems we can't do select all / deselect all with array-selector. It would be great if this element can get that feature. Its very common that we have to use select all / deselect all. Anyone knows how we can implement a work-around for this with array-selector ? I tried to at onload to iterate the master array and run the code to select / deselect all but its not working for me. Thanks for your help !

**Comment by Westbrook** [comment]
@tjsavage as this relates to the two PR's that reference this, it seems that the `2.x` label for this issue would be appropriate as well.

Might also go a good distance towards finishing the conversation around those two PRs so we could see these features hit production on both branches of the project. 

Let me know if there is anything I can do to help move this forward.

**Comment by TimvdLippe** [comment]
Closing per https://github.com/Polymer/polymer/pull/4699#issuecomment-331311907 In Polymer 2 you extend `array-selector` and implement this functionality yourself 😄
