### ISSUE TITLE
Weird behavior when binding input to array using dom-repeat

### ISSUE THREAD

**Issue by Holi0317** [Polymer/polymer#3828]
### Description

This happens when I try to bind array to input.

[![](https://img.youtube.com/vi/F55Re09GcOc/0.jpg)](https://www.youtube.com/watch?v=F55Re09GcOc)

(The video uses paper-input. But native input is tested, in the jsbin below, and have same problem)

(Console logs the array value when paper-input fires changes event)

The array binded have correct data. But value in input and rendered value is not.

Also, forcing the dom-repeat element to re-render causes weird data populated into input.
### Expected outcome

Value in input should have same value with array binded with dom-repeat
### Actual outcome

Weird and incorrect data rendered and input value are not correct.
### Live Demo

https://jsbin.com/vayoqu/edit?html,output
### Steps to reproduce
1. Create an array property and bind that into dom-repeat
2. Inside dom-repeat template, place a input element
3. Run the page. Change input value in the last element. The first one syncs value with the last one.
### Browsers Affected

Tested on Chromium 52.0.2743.82
### Versions
- Polymer: master branch
- webcomponents: Chrome native

**Comment by miopa** [comment]
I'm experiencing the same issue. It happens on any input in dom-repeat that is iron-input.

The wierd behavior is triggered when at least two input fields are empty. The input that got empty last, recieves the characters typed in the inputs that got empty before.

Tested on latest Chromium, Opera and Firefox.

**Comment by TimvdLippe** [comment]
I am unable to reproduce this issue with Polymer 2: http://jsbin.com/lipawerowe/edit?html,console,output All values appear to be correctly reflected in the `array` and no data is duplicated.
