### ISSUE TITLE
Provide a way to remove array from Polymer.Collection (memory leak?)

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#3831]
_From @danimoh on August 1, 2016 9:24_

Hello.

I can register interest in the tracking of keys of array items by Polymer.Collection.get(myArray).
However, it can happen that you don't need that array anymore, e.g. if you do something like this.set('myArray', newArray);

In this case, I would like the initial array that myArray pointed to to get garbage collected. It's reference however is still contained in Polymer._collections which would prevent carbage collection.

Ist this handled by Polymer internally or is this a memory leak?

_Copied from original issue: Polymer/docs#1698_

**Comment by kaste** [comment]
Polymer._collections is a WeakMap so this alone shouldn't leak.

**Comment by TimvdLippe** [comment]
`Polymer.Collection` has been deprecated and removed, therefore I am closing this issue.
