### ISSUE TITLE
ApplyShim creates spurious shorthand properties that override set properties

### ISSUE THREAD

**Issue by mgiuffrida** [Polymer/polymer#3832]
Since the other issues I've reported been fixed, I thought I'd open some new ones :smiling_imp:

This issue is similar to #3802 but still occurs.

https://jsfiddle.net/mgiuffrida/s1dvLsee/

With useNativeCSSProperties on, ApplyShim `@apply`s a mixin by setting all the properties ever used by that mixin. When a given component doesn't have that property set (the custom property the shim creates is empty), the entire property declaration is invalid, so the browser makes that property inherit (for an "inherited property") or gives it the initial value.

Unfortunately, properties are not mutually exclusive:

```
div {
  --my-background-color: green;
  background-color: var(--my-background-color);
  background: var(--my-background);
}

==============
`getComputedStyle(div).backgroundColor == "rgba(0, 0, 0, 0)"` // initial value
```

This means that if something, somewhere, in my project puts a `background` property in a mixin value, and something unrelated puts a `background-color` property in the mixin value (not necessarily for the same element), then depending on the order of those files, one of the elements' backgrounds becomes... transparent.

Fun fact: For an example with two elements (one given a background in the mixin, the other given a background-color), there is no ordering of the elements, their declarations, the styles, etc. in which one of them does not have an incorrect (transparent) background.
# 

In addition to shorthand properties, there are properties whose computed values depend on other properties, e.g. line-height depends on font-size. I wonder if a similar situation could make a dependent property compute the wrong value.

**Comment by mgiuffrida** [comment]
This can also happen with just one mixin if the element sets a default before `@apply`ing the mixin:

https://jsfiddle.net/mgiuffrida/db4o2osy/

**Comment by azakus** [comment]
That second fiddle is unfortunately much harder to get right. Currently, the Apply shim does not check selectors for matches, but keeps a global map for mixins. We don't know that we shouldn't apply the mixin there :/

**Comment by azakus** [comment]
It seems like the only way to solve this is to take all shorthand properties defined in mixins and expand them to all granular properties.

For example,
```css
--foo: {
  background: blue;
};
/* later */
@apply --foo;
```
becomes
```css
--foo_-_background-image: none
--foo_-_background-position: 0% 0%
--foo_-_background-size: auto auto
--foo_-_background-repeat: repeat
--foo_-_background-origin: padding-box
--foo_-_background-clip: border-box
--foo_-_background-attachment: scroll
--foo_-_background-color: blue;
/* later */
background-image: var(--foo_-_background-image);
background-position: var(--foo_-_background-position);
background-size: var(--foo_-_background-size);
background-repeat: var(--foo_-_background-repeat);
background-origin: var(--foo_-_background-origin);
background-clip: var(--foo_-_background-clip);
background-attachment: var(--foo_-_background-attachment);
background-color: var(--foo_-_background-color);
```

This would require knowing all shorthand properties and their expansions, with each one being special.

**Comment by sorvell** [comment]
Solving this generally seems costly as @azakus notes. However, we may be able to make some incremental improvements by:
* sorting the application of variables by length to favor consistently the expando versions (e.g. `background-image` would come after `background`.
* collecting expando defaults into shorthand variable's default.

These changes would fix the `border` but not the `background` in this example from #4471: http://plnkr.co/edit/RIJMTN6aM9zcXnAed5hO?p=preview, but at least there would be a consistent way to think about what's happening.

**Comment by LarsDenBakker** [comment]
https://github.com/Polymer/polymer/issues/4471 was closed in favor of this. However this is still open.

This seems like quite a serious bug. We have a very large application, and we run into this every now and then. Right now I'm advising developers not to use CSS mixins anymore, or to not use shorthand properties. 

Is there a long term solution for this, or are we going to wait for part/theme? If so, probably best to warn developers of the issue in documentation.

**Comment by TimvdLippe** [comment]
I have opened https://github.com/webcomponents/shadycss/pull/157 to add this as a known limitation. We advise developers to not use mixins in these cases, as of complications in the polyfill as shown in this issue. In the future, `::part` and `::theme` will be used which should not exhibit this problem.

**Comment by azakus** [comment]
This is a known limitation of the `@apply` shim, as documented here: https://github.com/webcomponents/shadycss#status

The ApplyShim is provided for backwards compatibility for Polymer 1 and 2, and will only receive the most critical of bug fixes.

We recommend not using shorthand properties in mixins if possible to avoid the situation you see.
