### ISSUE TITLE
var() functions rewritten incorrectly with useNativeCSSProperties=true

### ISSUE THREAD

**Issue by mgiuffrida** [Polymer/polymer#3836]
Polymer rewrites

> color: var(--empty-prop, var(--my-set-color, --another-empty-prop));

as

> color: var(--empty-prop, var(--my-set-color,var(--another-empty-prop));)

which is invalid syntax.

Polymer also rewrites:

> color: var(--empty-prop, --my-set-color);

which should set `color` to `--my-set-color` (an INVALID value) as:

> var(--empty-prop,var(--my-set-color))

which sets `color` to `var(--my-set-color)` which can be substituted with an actual color when the `--my-set-color` property is set.

Polymer Fiddle: https://jsfiddle.net/mgiuffrida/rhr7m5ad/
Without Polymer: https://jsfiddle.net/mgiuffrida/5wmme0xa/

**Comment by mgiuffrida** [comment]
I guess this rewriting is somewhat necessary, because a **huge** number of PolymerElements use fallback values that *aren't actually correct* as far as I can tell (and in Chrome's implementation), and these would stop working with `useNativeCustomProperties: true` if the values weren't rewritten.

I haven't bothered to check the entire PolymerElements repo, but in the PolymerElements used in Chromium, [the incorrect var() syntax is used in more elements](https://goo.gl/HEGAOj) than the correct syntax.

> color: var(--paper-input-container-color, --secondary-text-color); /* Wrong */

The syntax of `var()` is:

> `var() = var( <custom-property-name> [, <declaration-value> ]? )`

where the `<declaration-value>` is basically anything.

The substitution process does NOT use the fallback value as the input of the current `var()` function being substituted -- it uses it as the result of the substitution:

> Otherwise, if the var() function has a fallback value as its second argument, replace the var() function by the fallback value. If there are any var() references in the fallback, substitute them as well.

==============

Unfortunately, Polymer's style shim that it uses even with `useNativeCustomProperties: true` only rewrites *some* stuff. So here's an example where `paper-checkbox` is doing everything  wrong:

https://jsfiddle.net/mgiuffrida/wfxhjf94/

Multiple ]invalid rules](https://github.com/PolymerElements/paper-checkbox/blob/master/paper-checkbox.html#L186) get partially rewritten, but not completely, with native custom properties, making the style "wrong" per the author's intent.

**Comment by azakus** [comment]
This is just a slight bug in the apply shim, as it only knows how to fix up variable syntax of `var(--a, --b)`.

**Comment by mgiuffrida** [comment]
@azakus So the apply shim refers to more than the shim used for @apply? It's also responsible for tracking all custom properties and rewriting `var()` values, even with no mixins?

**Comment by azakus** [comment]
It only rewrites that particular usage of var and a few other things that
are not valid syntax because it was expedient do them with the more
expensive mixing work.

**Comment by azakus** [comment]
In your paper-checkbox example, it looks like `--primary-text-color` is not used as a fallback variable: https://github.com/PolymerElements/paper-checkbox/blob/master/paper-checkbox.html#L190-L193. Seems like a bug that should be filed on that element.

**Comment by mgiuffrida** [comment]
@azakus Yet it's still red if you disable `useNativeCSSProperties`, because the shim doesn't rewrite the fallback variable when it's not set, so the color rule is invalid and the `#checkboxLabel` rule is allowed to win (instead of the `:host([checked]) #checkboxLabel` rule causing the color to reset to `inherit`).

**Comment by mgiuffrida** [comment]
So I agree there's a bug in `paper-checkbox`, and there `var()` rewriting bug mentioned above in https://github.com/Polymer/polymer/issues/3836#issuecomment-237729340, but there are still cases where the shim doesn't have the same result when `useNativeCSSProperties` is true.

**Comment by azakus** [comment]
Yeah, it seems pretty obvious now that we should be testing all of our elements with the `useNativeCSSProperties` flag set so we can see what other odd behaviors are happening, both as a test of the Apply shim, and as a test of the elements.
