### ISSUE TITLE
Feature request: Provide old values for deep property changes

### ISSUE THREAD

**Issue by icmdaf** [Polymer/polymer#3839]
Currently, only single property observers get the old and new values; a sub-property observer only receives the current value; and deep property change records don't include a field for the old value.

Obviously sub-property observers can't be changed to report the old value since they can only use the value as the single argument; but adding a new field "oldValue" to the change record for deep property observers wouldn't break anything.

It's currently very hard or maybe even impossible in corner-cases to reconstruct the previous value, but it should be relatively easy for Polymer to retrieve it.

http://codepen.io/hanger/pen/NAObRZ?editors=0012

Changing `hello` to `world` calls the three different observers I have on the property like this:

``` javascript
propertyObserver("world", "hello")
pathObserver("world")
deepObserver({base: "world", path: "myprop", value: "world"})
```

``` javascript
Polymer({
  is: 'x-test',
  properties: {
    myprop: {
      type: Object,
      observer: 'propertyObserver'
    }
  },
  observers: [
    'pathObserver(myprop)',
    'deepObserver(myprop.*)',
  ],
  propertyObserver() { console.log('propertyObserver', arguments); },
  pathObserver() { console.log('pathObserver', arguments); },
  deepObserver(){ console.log('deepObserver', arguments); },
  ready() {
    console.log('ready');
    this.myprop = 'hello';
    this.myprop = 'world';
  }
});
```

**Comment by icmdaf** [comment]
My use-case in this instance is this: I want to build an undo manager for a complex editor which stores its entire state as one JSON object at the root, with sub-editors simply binding to paths. The JSON can be loaded/stored directly using i.e. iron-ajax.
To avoid hooking the undo behavior into every single control, I want to use one deep observer `trackUndo(data.*)` and save `{path, newValue, oldValue}` records, so that I can simply undo `this.set(path, newValue)` as `this.set(path, oldValue)`.

Currently, to get the old value, I'm manually recording the previous observed values, which works for cases like `prop = {}; set('prop.deep', 123);` but not for `prop = {deep: 123};` which doesn't notify on the 'prop.deep' path...

```javascript
const previous = new Map();

trackUndo(change) {
  const old = previous.get(change.path);
  doSomething(change.value, old);
  previous.set(change.path, change.value);
}

**Comment by TimvdLippe** [comment]
For performance (mostly memory) reasons we do not store this data. If you would like to implement this behavior, it should be straightforward to store the data in a "previous" variable (http://jsbin.com/nolaborabu/edit?html,console,output). Since we have no plans on storing more information on Polymer elements and a userland solution is available, I am closing this issue. If you feel we have missed a use-case, feel free to reopen and we can discuss it!
