### ISSUE TITLE
issue in whenHostOrRootRule function

### ISSUE THREAD

**Issue by flyingfish2016** [Polymer/polymer#3840]
https://github.com/Polymer/polymer/blob/c1ebf1efba484c525c7cacaeea7fef8a480d0f95/src/lib/style-properties.html

 whenHostOrRootRule: function(scope, rule, style, callback) {
        if (!rule.propertyInfo) {
          **self.decorateRule(rule);  // Not correct. "self" should be "this".**
        }
        if (!rule.propertyInfo.properties) {
          return;
        }

**Comment by kaste** [comment]
Shouldn't _eslint_ catch something like this?

**Comment by flyingfish2016** [comment]
I know very little of eslint.
By default, "self" refers to the Window object if that affects.

**Comment by TimvdLippe** [comment]
This seems to be fixed in [the polyfill](https://github.com/webcomponents/shadycss/blob/4edbee4dd503ba348ab682104fc81bf01430aaa9/src/style-properties.js#L300)
