### ISSUE TITLE
How should CSS Resets be applied to Polymer components?

### ISSUE THREAD

**Issue by oleersoy** [Polymer/polymer#3842]
I asked on Stackoverflow first just in case this had been knocked out already:
http://stackoverflow.com/questions/38794689/how-should-css-resets-be-applied-to-polymer-components

**Comment by oleersoy** [comment]
Perhaps instead of applying them a linter could notify the developer of css resets that are not applied, and the dev could just add these to the component if deemed necessary.  I've tried to capture resets from various frameworks here:

[superfly-css-foundation](https://www.npmjs.com/package/superfly-css-foundation)  

It could be used baseline for what the linter would report.

**Comment by oleersoy** [comment]
So I'm not sure the answer I received on SO in correct, because here it says that inheritable styles pierce the shadow boundary ... https://developers.google.com/web/fundamentals/primers/shadowdom/  ... is this  currently how it works in polymer?

**Comment by ebidel** [comment]
Left a comment on SO. Let's keep it going over there.
