### ISSUE TITLE
Be more precise about the origin of webcomponentsjs in bower.js

### ISSUE THREAD

**Issue by bartolom** [Polymer/polymer#3843]
### Description

The bower.json file uses a abbreviated version to reference webcomponentsjs
`"webcomponentsjs": "^0.7.20"`
It would be nice if it could be more precise about the origin of webcomponentsjs like
`"webcomponentsjs": "webcomponents/webcomponentsjs#^0.7.20"`

The reason is that I'm trying to make Polymer (and the Polymer Elements) work on Java/JVM micro services. In Java dependencies are usually not resolved with Bower but rather with tools like Maven or Gradle.

There is a nice project called https://webjars.org which bridges the JavaScript/Bower world with the Java/Maven/Gradle world. The above change makes the dependency more explicit and makes it easer for Java developers to create custom builds and use alternative repositories and forked versions of webcomponentsjs without causing ambiguity for the Java build system. 

This issue is related to https://github.com/PolymerLabs/tedium/issues/47
#### Steps to Reproduce

inspect: https://github.com/Polymer/polymer/blob/master/bower.json
#### Expected Results

`"webcomponentsjs": "webcomponents/webcomponentsjs#^0.7.20"`
#### Actual Results

`"webcomponentsjs": "^0.7.20"`
### Browsers Affected

This does not affect browsers, but rather build system on the JVM like Maven and Gradle. It seems that it is less important for JavaScript which uses Bower for Polymer
### Versions
- Polymer: v1.6.1
- webcomponents: v0.7.20

**Comment by TimvdLippe** [comment]
@azakus This seems like a change that should be unharmful. WDYT?

**Comment by TimvdLippe** [comment]
This has been fixed in #3844
