### ISSUE TITLE
Need a way to delay element readiness from behavior

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#3845]
Currently I have behavior that injects translations into custom element in form of a simple `key: value` object like following:
```javascript
var language = {
    properties: {
        Language: {
            type  : Object,
            value : translations
        }
    }
}
Polymer({
...
    behaviors: [language]
});
```
However, I'd like to move to asynchronous translations loading, but for this I also need to delay element `ready` callback until translations are ready.
Potentially, there can be multiple such behaviors, so redefining `factoryImpl` is not a solution here, however I do not see an appropriate API for this at the moment.

Currently thinking about design with using promise as return value from `ready` callback in behavior like following:
```javascript
var language = {
    properties: {
        Language: {
            type  : Object
        }
    },
    ready : function () {
        return load_translations().then(function (translations) {
            this.translations = translations;
        });
    }
}
```

**Comment by LM450N** [comment]
Maybe your behavior could have a `_translationsLoaded` method that will be called when the translations are loaded. Then you'll only have to use this callback instead of  `ready`.

**Comment by kaste** [comment]
`Ready`ness is bottom-up or child-to-host, so I don't think delaying can be an option here.

**Comment by nazar-pc** [comment]
It doesn't matter, I'd like `ready()` callback on particular element to be called only after translations being loaded.
Your https://github.com/Polymer/polymer/pull/3358 helps in most cases, but there is still possibility to catch some issues when translations are used in code, not in template.

**Comment by kaste** [comment]
In your code example above you define a ready() function which returns a Promise. Since this ready() callback actually needs to be called to 'start' the promise, I assumed you want other ready-callbacks to be delayed until this Promise settles.

**Comment by nazar-pc** [comment]
You're right, it is clunky, but at least `ready` in element declaration and in other methods it will have desired effect.

**Comment by nazar-pc** [comment]
Well, with 2.x that doesn't have `ready` I think this is not really relevant anymore and no one will likely ever fix it. Moreover, depending on the use case it can be kind of worked around.
