### ISSUE TITLE
Shadow DOM and custom properties: 'x-foo *x-foo' is not a valid selector

### ISSUE THREAD

**Issue by mgiuffrida** [Polymer/polymer#3846]
With Shadow DOM enabled: https://jsfiddle.net/mgiuffrida/sfw6r5xo/

```
<style>
  :host * {
    --some-color: red;
    color: var(--some-color);
  }
</style>
```

throws:

> Uncaught SyntaxError: Failed to execute 'matches' on 'Element': 'x-foo *x-foo' is not a valid selector.

I know Polymer's shim doesn't support defining custom properties on local DOM like this, but a slightly more complex example works in shady DOM (but still throws in local DOM): https://jsfiddle.net/mgiuffrida/nfwzu62f/

```
  :host, :host * {
    --some-color: red;
    color: var(--some-color);  /* actually makes things red, in shady DOM */
  }
```

> Uncaught SyntaxError: Failed to execute 'matches' on 'Element': 'x-foo,x-foo *x-foo' is not a valid selector.

**Comment by TimvdLippe** [comment]
Seems to be working now in Polymer 2: http://jsbin.com/sikufinici/edit?html,console,output
