### ISSUE TITLE
Add possibility for property composition

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/polymer#3847]
### Description

Wrapping elements is currently a cumbersome process. While element inheritance would solve a good portion of the issues, sometimes this is not feasible due to using the mediator pattern with other (custom) elements.

These problems are apparent in pull requests/issues like https://github.com/PolymerElements/app-route/pull/135, https://github.com/PolymerElements/paper-dropdown-menu/pull/178 which also depended on https://github.com/PolymerElements/paper-menu-button/pull/96 as a result of a change in `iron-dropdown`.
### Proposed API

To automatically expose such properties to wrapper elements, add a new `composeWith` which references the `id` of the to-be-composed element.

``` html
<template>
  <child-element id="idOfElement"></child-element>
</template>
```

``` js
Polymer({
  is: 'parent-element',
  <...>
  composeWith: [
    'idOfElement'
  ],
  <...>
});
```

Given that `child-element` exposes the properties `foo` and `bar`, whenever the property `foo` is set on the `parent-element`, the value is automatically propagated to the `child-element` in its template. Consequently, if `foo` is set to `notify: true`, the `parent-element` will also notify changes.

In essence this composition similar to behaviors, however it only exposes properties to the parent and automatically processes updates to their values in both directions. Overriding properties should be equal to the process employed with behaviors.

**Comment by mercmobily** [comment]
* What would happen when composing multiple children with clashing properties?
* What about attributes? (ones that are assigned as $= in the child element)

I have to say... I don't know. It feels to me like there would be so many moving parts automatically bundled together...

**Comment by TimvdLippe** [comment]
In case of multiple children, using `composeWith`:
```html
<template>
  <element-one id="firstElement"></element-one>
  <element-two id="secondElement"></element-two>
</template>
```
```js
Polymer({
  is: 'parent-element',
  <...>
  composeWith: [
    'firstElement',
    'secondElement'
  ],
  <...>
});
```

Whereas the current version would be
```html
<template>
  <element-one id="firstElement" value1="{{value1}}" value2="{{value2}}"></element-one>
  <element-two id="secondElement" value1="{{value1}}" value2="{{value2}}"></element-two>
</template>
```
```js
Polymer({
  is: 'parent-element',
  <...>
  properties: {
    value1: {
      type: String,
      notify: true
    },
    value2: {
      type: String,
      notify: true
    }
  },
  <...>
});
```

While the boilerplate is significantly reduced, the most important result is that when a property is added to firstElement this is also reflected in `parent-element`. This exactly prevents pull-requests as described in the issue description.

**Comment by TimvdLippe** [comment]
This is now possible with custom element inheritance and retrieving `super.template`.
