### ISSUE TITLE
In an element's `attached()` callback, can I be 100% sure that all elements in the host's LIGHT DOM are `ready()`ed?

### ISSUE THREAD

**Issue by mercmobily** [Polymer/polymer#3849]
Imagine you have an element like this:

```
<hot-realtime-field save-url="/users/579c/surname">
  <paper-toggle-button name="accept" label="Accept?">Accept?</paper-toggle-button>
</hot-realtime-field>
```

Where `hot-realtime-field` checks its first child (paper-input) and wants to check if it's a checkbox-like widget using `iron-form`'s `_usesCheckedInsteadOfValue()` on it (yes, yes, I know, it's a non-public API...).

Considering this code:

```
if (unshownForm._usesCheckedInsteadOfValue(this._firstChild))
  this._firstChild.treatAsChecked = true;
```

If I run it in `hot-realtime-field`'s `ready()` callback, I end up with the check failing because `paper-toggle-button` is still unreadied (in fact, it looks like a non-polymer one in the console).

However, if I run the code above in `hot-realtime-field`'s `attached()` callback, things work.

Can I trust this?

**Comment by kaste** [comment]
I don't think so. 

> Because custom element reaction code can perform its own mutations, it is not possible to give a global ordering guarantee across multiple elements.
https://www.w3.org/TR/custom-elements/#custom-element-reactions

**Comment by mercmobily** [comment]
OK but...

...but if you have an element that wants to interact with elements in its light DOM (as in my case, check some of the child element's attributes to decide how to behave), how would I possibly code it so that I am 100% sure that I am not stumbling upon timing issues?

**Comment by TimvdLippe** [comment]
This is indeed defined in the custom elements specification, as @kaste pointed out. If you would like to discuss this behavior, please open an issue at https://github.com/w3c/webcomponents
