### ISSUE TITLE
observe-js: status?

### ISSUE THREAD

**Issue by mbana** [Polymer/polymer#3850]
https://github.com/Polymer/observe-js

how does Polymer do databinding? If Polymer doesn't use `observe-js` are there plans to split out the core so one can use it without Polymer? I use Chrome 50+ and `Platform.performMicrotaskCheckpoint()` is required everywhere - a pain.

I have parts of my app which do not require Polymer. However, I would like to use the eventing notification system that Polymer uses. I do like `PathObserver` for example. This sort of makes testing much easier on my side.

**Comment by ebidel** [comment]
Rob has a great video on the data binding system: https://www.youtube.com/watch?v=1sx6YNn58OQ

The TLDR, is that it uses getters/setters. That's why you specify your properties in `properties` and computed functions and observers take a list of dependencies.

**Comment by mbana** [comment]
are there plan to split this out from the core of Polymer.
so it can reused by other people, sorta like observe-js did.

**Comment by ebidel** [comment]
The observe-js isn't used by Polymer anymore. I'm not sure what you mean by split it out, it already has its own repo. 

Polymer 2.0 will likely have a way to use each feature, standalone. Stay tuned.
