### ISSUE TITLE
iron-iconset-svg.html:50 Uncaught TypeError: Polymer is not a function

### ISSUE THREAD

**Issue by sowsan** [Polymer/polymer#3853]
getting the error message of iron-iconset-svg.html:50 Uncaught TypeError: Polymer is not a function intermittently and all of the icons in the polymer web app are not displaying. Using Polymer 1.6. Anyone have experienced this issue ?

**Comment by TimvdLippe** [comment]
Please follow the guidelines for creating issues at https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs
