### ISSUE TITLE
Polymer should set failed Array JSON parse back to undefined, not null

### ISSUE THREAD

**Issue by robdodson** [Polymer/polymer#3860]
I think this line, https://github.com/Polymer/polymer/blob/master/src/micro/attributes.html#L211, should set the value to `undefined`, not `null`. Setting it to `null` will cause observers to run and is somewhat incompatible with the Object parsing code right above. If I understand that code correctly, if an Object parse fails it has the potential to leave the value undefined. @kevinpschaaf

**Comment by TimvdLippe** [comment]
@robdodson Is this still an issue for you in Polymer 2?
