### ISSUE TITLE
SVG styling not working in Edge browser

### ISSUE THREAD

**Issue by prumbles** [Polymer/polymer#3861]
In Microsoft's Edge browser, SVG elements such as `path` do not get styles from style tag in a Polymer element.

1. In Chrome, go to http://codepen.io/prumbles/pen/XKOKmb
2. Notice a red horizontal line
3. In an Edge browser, go to the same url

##### Expected Results
A red line should show in Edge

#### Actual Results
No red line is shown in Edge

**Comment by prumbles** [comment]
This is a real issue, but I'm closing it for now, because the codepen link is not correct.  I will fix and repost.

**Comment by F2X** [comment]
I think it's a style issue on Firefox and Edge, try:
```css
#cont * {
    box-sizing: border-box;
}
```
