### ISSUE TITLE
Recursive <dom-module> inside table

### ISSUE THREAD

**Issue by DeadcatDev** [Polymer/polymer#3863]
### Description

I made a simple recursive dom-module as follow:

```
<dom-module id="recursive-tree">
    <template>
        <template is="dom-repeat" items="{{recursivedata}}" as="node">
            <tr>
                <td>{{node.name}}</td>
            </tr>
            <template is="dom-if" if="{{node.children[0]}}">
                <recursive-tree recursivedata="{{node.children}}"></recursive-tree>
            </template>
        </template>
    </template>
</dom-module>

<script>
    Polymer({
        is: 'recursive-tree',
        properties: {
            recursivedata: {
                type: Array
            }
        }
    });
</script>
```

Just for feed the < table >'s and use it this way:

```
                    <table>
                        <tbody>
                            <recursive-tree table="true" recursivedata="{{nodes}}"></recursive-tree>
                        </tbody>
                    </table>
```

but i end with parallel < table > and < recursive-tree > instead of nested :

![poly_rec](https://cloud.githubusercontent.com/assets/15237149/17643270/1d53c570-6165-11e6-8a15-867aeb2b4678.png)
#### Steps to Reproduce
1. Just copy element and use
2. mock data as follow:
   [{"name":"main","children":[{"name":"sub"},{"name":"sub"}]},{"name":"main2","children":[{"name":"sub2"},{"name":"sub2"}]}] etc.
### Browsers Affected
- [X ] Chrome
  rest not tested
### Versions
- Polymer: v1.6.0

**Comment by miztroh** [comment]
Certain elements can only accept a specific set of child elements.  When an invalid child element is added, browsers typically kick that out as a sibling of its parent.  I think that's what's happening here.

**Comment by DeadcatDev** [comment]
May it be, but any idea to build recursive table content using Polymer?

**Comment by gkjohnson** [comment]
Is there any reason you have to use an html table element? Why not just use divs, spans, and some custom styling to achieve that?

**Comment by DeadcatDev** [comment]
@gkjohnson Yes (i need it) and No (i cant use other element). Table means table. And i want table.

@miztroh Thanks for that workaround i will test it, hope it will work (vaadin-grid and other cases) :)

**Comment by motss** [comment]
While for my use case, see https://jsbin.com/talovu/edit?html,output, only happens on IE11 while other browsers just worked fine.

**Comment by DeadcatDev** [comment]
Thanks that all my project moved to angular. No more Polymer in my live. Im closing this guys, sorry.
