### ISSUE TITLE
SVG icons inside paper-button does not work in Edge

### ISSUE THREAD

**Issue by jeffkevin** [Polymer/polymer#3864]
### Description
SVG iron-icons does not appear in Microsoft Edge when it is inside paper-button element.

#### Live Demo
https://elements.polymer-project.org/elements/paper-button?view=demo:demo/index.html&active=paper-button

#### Expected Results
SVG should appear in paper-buttons

#### Actual Results
No SVG icons visible.

### Browsers Affected
- Microsoft Edge

**Comment by jeffkevin** [comment]
Take note that iron-icons outside paper-button element does not have these problem.

**Comment by prumbles** [comment]
It works for me.  I attached a screenshot of the link you provided in my Edge browser.

![ironiconsinsidebuttons_edge](https://cloud.githubusercontent.com/assets/4001288/17645891/fb749c16-6166-11e6-800b-2c61eda2c23d.png)

**Comment by jeffkevin** [comment]
Maybe its on our end... closing this issue.
