### ISSUE TITLE
Improve error message for hyphenless component names

### ISSUE THREAD

**Issue by dtruffaut** [Polymer/polymer#3867]
### Description

When I create a polymer element without hyphen in its name, an error is raised, but the message is quite obscure... Let's say it does not help the developer.

Please consider updating the message with a more meaningful content.
#### Steps to Reproduce
1. Create new element `test`
2. Use the element `test`
3. Refresh the page
#### Expected Results

polymer-micro.html:65 Uncaught SyntaxError: Failed to execute 'registerElement' on 'Document': Registration failed for element 'test'. Element name must contain an hyphen: '-'. Example: 'my-test'. See https://www.w3.org/TR/custom-elements/#valid-custom-element-name for reference.
#### Actual Results

polymer-micro.html:65 Uncaught SyntaxError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'test'. The type name is invalid.
### Browsers Affected

Tested on Chrome
### Versions
- Polymer: v1.6.1
- webcomponents: v0.7.22
### See also:

https://github.com/divshot/ele-web/issues/22
https://github.com/Polymer/polymer/issues/1163

**Comment by ebidel** [comment]
I've had a [PR](https://github.com/Polymer/polymer/pull/2736) open for 10 months that fixes this and adds some other helpful debugging stuff.

I don't thin the core team is going to add this. But the good news is custom elements v1 has an improved error message when you try to register an element name without a "-".

**Comment by TimvdLippe** [comment]
As Polymer 2 uses the v1 API, this error message is controlled by the spec. If you execute it today, you receive: `Failed to execute 'define' on 'CustomElementRegistry': "foo" is not a valid custom element name`. If you would like to see a change in this error message, please open an issue on https://github.com/w3c/webcomponents
