### ISSUE TITLE
Blog demo no longer works

### ISSUE THREAD

**Issue by oleersoy** [Polymer/polymer#3874]
The demos contain in [Encapsulated Routing with Elements](https://www.polymer-project.org/1.0/blog/routing) no longer render.  Tried both chrome and firefox on ubuntu 14.04.

**Comment by TimvdLippe** [comment]
It seems polygit2 is down as a lot of 503 errors are thrown. See for example https://polygit2.appspot.com/components/webcomponentsjs/webcomponents-lite.js

**Comment by oleersoy** [comment]
Looks like it's back up now.

**Comment by arthurevans** [comment]
Thanks for the heads-up!
