### ISSUE TITLE
Rapid prototyping with transitive NPM dependency element resolution

### ISSUE THREAD

**Issue by oleersoy** [Polymer/polymer#3875]
This is issue has been created to explore an architecture for allowing rapid prototyping using NPM dependencies that have sub components with conflicting versions.  It is a fork of of [Adding Polymer Dependencies to NPM](https://github.com/Polymer/polymer/issues/326).

Ideally it will result in an exhaustive list of potential show stoppers.  I have started with a question on SO here:
http://stackoverflow.com/questions/39086720/applying-css-to-dynamically-named-polymer-elements

**Comment by oleersoy** [comment]
At first I was thinking that the browser would detect collisions and extend the element name of the transitive dependency.  But this can also be done during development.

1) Declare dependencies in package.json
2) Scan dependencies Polymer.js major version conflicts
3) Scan dependencies for transitive version conflicts
4) Create a new flat layout that removes transitive conflicts by extending the element name (Similar to .bower)
5) Go to work

For **2** I think that the developer would have to manually resolve the issue.  For example if they found and declared a component that uses Polymer 0.5 vs the rest of them using Polymer 1.1.  I'm assuming that components need to be at least major version compatible with respect to `polymer.js`.  Is that a good assumption?

**Comment by oleersoy** [comment]
Link to Domenics blog for managing peer dependencies (Polymer.js): https://blog.domenic.me/peer-dependencies/

**Comment by oleersoy** [comment]
I created a new organization for prototyping various out modules associated with this work.  For project layout I'm using this:
https://github.com/supericium/pli

So below when you see directories like `src/main/wc` these come from the above linked project.

This layout would allow unique homes for css, templates, and javascript that can be then built and assembled into the web component.  For example before the CSS is placed in the component `<style>` tag, we may want to run it through various tools such as autoprefixer, etc.

The meaty part:

```
Create the new web component source:
src/main/wc/my-wc.html

Dependency structure would look like this:
my-wc
  wc1
   - wc3(v1)
  wc2
   - wc3(v2)

node_modules (Directory)
  wc1
  - wc2
     - wc3(v1)
  wc2
   -wc3(v2)

We have version conflicts on wc3.  So when compiling the project we flatten the dependencies and recompile corresponding html imports:

target/main/wc
   - my-wc
   - wc1 (Recompiled import for wc3-v1)
   - wc2 (Recompiled import for wc3-v2)
   - wc3-v1 (Recompiled component to include version tag)
   - wc3-v2 (Recompiled component to include version tag)
```
Thoughts?

**Comment by oleersoy** [comment]
Linking an article discussing various asset management issues.

[The problem with using HTML imports for Dependency Management](https://www.tjvantoll.com/2014/08/12/the-problem-with-using-html-imports-for-dependency-management/)

Looks like linting for various versions of the same resource, such as moment.js or jquery, would also be required in order to minimize the dependency graph.

**Comment by oleersoy** [comment]
Seems like components need a peer dependency management mechanism not just for Polymer itself, but for other resources as well.  For example the `time-formatting` component works with this version range of `moment.js` [2.05.1, 2.14.1].  This way the construction of the flat layout of dependencies can account for version requirements, and select the most recent version(s) that's the best fit across the board.

For example if one component requires `moment.js` from [1.3 to 1.99] and another can only use 2.14.1 and up, then put both version 1.99 and 2.14.1 or the most recent `moment.js` package in the dependency repository.

I would think that each top level folder should include a version number - so we have:
- moment.js-1.99/moment.js
- moment.js-2.14.1/moment.js

**Comment by oleersoy** [comment]
[Transpiling NPM packages directly into the JSPM packages folder?](https://github.com/jspm/registry/issues/967#issuecomment-244935606)

**Comment by oleersoy** [comment]
Version conflict must also be taken into account when creating custom elements through extension.  For example:
```class FancyDrawer extends AppDrawer```

I think JSPM deals with that, but need to prototype to verify.

**Comment by TimvdLippe** [comment]
Thanks for the suggestions and sorry for the late reply. The overall discussion to switch to NPM is ongoing and you can follow the progress at #326. If you have any specific comment, probably https://github.com/package-community/discussions/issues/2 is a good starting point if you would like to join the discussion.
