### ISSUE TITLE
Issue with paper-dialog size in Polymer v1.X

### ISSUE THREAD

**Issue by troy8** [Polymer/polymer#3877]
I have following paper-dialog sekeleton setup inside one of my custom element.

```
<paper-dialog id="error_dialog">
   <h2>{{error_message}}</h2>
   <p>{{error_detail}}</p>
</paper-dialog>
```
as and when I get any error I update the values of "error_message" and "error_detail" and open the dialog, something like this dynamically by calling the showErrorInDialog method

```
showErrorInDialog: function(err) {
     this.error_message = err.message;
     this.error_detail = err.detail;
     this.$.error_dialog.opened = true;
}
```
But, the problem is, the paper-dialog width is only considered as per the width of h2 tag, e.g.

if h2 is "Error" and "p" is "There is an error with the connection, please check.", then paper-dialog width is as per the "Error" text in h2 only.

Please suggest what I am doing wrong.

Same post in stack http://stackoverflow.com/questions/39076054/issue-with-paper-dialog-size-in-polymer-v1-x?noredirect=1#comment65518885_39076054

**Comment by ebidel** [comment]
This issue was moved to PolymerElements/paper-dialog#126
