### ISSUE TITLE
Computing on an Array and a literal has inconsistent behavior?

### ISSUE THREAD

**Issue by pik** [Polymer/polymer#3879]
### Description

The following compute is computed on init `"_computeArray(orgArray.splices)"` but it doesn't seem to be possible (?) to know from `_computeArray` that `orgArray` is what was passed in (since the computed function is called with `splices`) - I have tried using something like this "_computeArray(orgArray.splices, 'orgArray')" - but this has the effect that the computed is not called on init (even though orgArray has 2 values). 
#### Live Demo

http://plnkr.co/edit/OMKjXEp67dnRhWDeYY6T?p=preview 

(If the push is uncommented in attached than it computes correctly, or if the second variable is removed from the computed)
#### Expected Results

For the computation to occur on init as it does with only the splices of the original array for an argument. 
#### Actual Results

Value is not computed until the original array is modified.
### Browsers Affected

- [X] Chrome
- [X] Firefox

**Comment by arthurevans** [comment]
The `.splices` path doesn't notify when the array itself changes, only when it's spliced. So in most cases you're better off using the wildcard, `orgArray.*` instead: https://www.polymer-project.org/1.0/docs/devguide/observers#deep-observation

For a wildcard observer, you get a change record argument that includes a `base` property—that will be the array you're observing. (In the case of a `.splices` change record, you can look at `indexSplices.object`).

So you can simplify this to:

```
properties: {
    ... 
  computedArray: {
    type: Array,
    computed: "_computedArray(orgArray.*)"
   }, 
},
_computedArray: function(_) {
  return _.base.map((item) => {
    return item + 's'
  })
}, 
```

Here it is running:

http://plnkr.co/edit/umP8AMvGyM4zx6SNa38r?p=preview

**Comment by pik** [comment]
@arthurevans - Thanks for the reply - that's not really what the docs suggest (maybe they could be clarified?):
> Array mutation paths

> When used as the last segment in a path, splices represents any array mutations to the identified array (additions or deletions). For example, if users is an array, the path users.splices identifies any additions to or deletions from the array.

 also I'm not really sure how your answer explains why ` "_computeArray(orgArray.splices)"` computes initially but ` "_computeArray(orgArray.splices, 'orgArray')"` does not - what's special about the later as opposed to the former?

**Comment by arthurevans** [comment]
Hm. Do you mean it could be clearer here that `.splices` doesn't notify when you replace the whole array? I agree, the next paragraph talks about limitations but omits this important note.

Computed properties and complex observers aren't actually supposed to support literals at all. According to the docs, literals are only supported on computed bindings. So the fact that it does anything is a little unexpected. A simpler approach would simply be to pass the array directly instead of having he indirection and the `this.get` call: 

`'_computeArray(orgArray.splices, orgArray)'` 

(Or, as I said, use `changeRecord.base`.)

There is an issue elsewhere with a multi-property observer with a `.splices` path not firing when a single-property observer with `.splices` does. The inconsistency you're seeing may be related:     https://github.com/Polymer/polymer/issues/3878

**Comment by pik** [comment]
> Hm. Do you mean it could be clearer here that .splices doesn't notify when you replace the whole array? I agree, the next paragraph talks about limitations but omits this important note.

Yes, that would be good (unrelated to the bug filing though). Also not that `splices` is notified with `undefined` when the array is initialized when it is a single argument to the computed. 

> Computed properties and complex observers aren't actually supposed to support literals at all. According to the docs, literals are only supported on computed bindings. So the fact that it does anything is a little unexpected. A simpler approach would simply be to pass the array directly instead of having he indirection and the this.get call: 
I guess it's an undefined detail that literals do work? That said I very much think it would be good if they were, since that allows one to write generic methods in a behavior which can be re-used (or otherwise to have every computed splice / changes to pass in the base property name being modified). 

> There is an issue elsewhere with a multi-property observer with a .splices path not firing when a single-property observer with .splices does. The inconsistency you're seeing may be related: #3878

I can't make much sense of the bug report, but yes that would be the correct summary of this issue. Particularly neither `_computedArray(orgArray.splices, orgArray.*)` or `_computedArray(orgArray.splices, 'literal')` will fire when initialized although as I mentioned the singular `_computedArray(orgArray.splices)` does fire.  I suspect this might be related to the multi-property computed requirement that both properties be defined ? Where as `.splices` is not defined until it is pushed to. 

I suppose the solution is to not use `.splices` at all (since it's current implementation is pretty useless) but to use `orgArray.*` always. This does have a disadvantage though, that in fact `.*` on an array is triggered twice for `push` action (once on `.splices` and once on `.length`) so one must guard against performing (e.g. if using an observer) the same action twice for a single event, which is again an implementation detail but perhaps not so nice to expose users to.

**Comment by TimvdLippe** [comment]
It has been a while and this area of docs has significantly improved: https://www.polymer-project.org/2.0/docs/devguide/observers#array-observation including the following note:

> Polymer only calls the array mutation observer when the array items change, not for changes to the top-level array

Therefore I am closing this issue. @pik feel free to reopen if you are still running into issues!
