### ISSUE TITLE
Provide equivalent for angular's `ng-cloak` 

### ISSUE THREAD

**Issue by ergo** [Polymer/polymer#3880]
Hello,

Is there a chance we can get an equivalent of:

https://docs.angularjs.org/api/ng/directive/ngCloak

Directive for polymer?

I tried using `unresolved` attribute on body and `:unresolved` pseudo-selector but that doesn't seem to work with shady dom (at least on firefox). Unresolved works OK when one is dealing with a SPA, but I'm using only some polymer elements in our application.

So when I do something like: 

    <paper-tooltip>the name means "different lizard"</paper-tooltip>

The tooltip will be visible for the user before all elements load, I'm looking for a way around this problem.
So far the only reliable solution would be to listen for an event on load and remove a class like `polymer-cloak` from all elements that have it. I think it would be beneficial to have support for this in the base.

**Comment by ebidel** [comment]
Polymer 0.5 used to remove `unresolved` attributes on individual elements for you but it was removed for perf and to reduce lib size. 

As you suggest, adding an attribute and removing it yourself at `WebComponentsReady` is the recommended approach.

```
<style>
  my-element {
    transition: opacity 1300ms ease-in-out;
  }
  [unresolved] {
    opacity: 0;
  }
</style>

window.addEventListener('WebComponentsReady', e => {
    const unresolved = document.querySelectorAll('[unresolved]');
    Array.from(unresolved).forEach(el => {
      el.removeAttribute('unresolved');
    });
  });
```

http://jsbin.com/sihazavaje/edit?html,output
