### ISSUE TITLE
CSS variables without a fallback should use unset as the fallback

### ISSUE THREAD

**Issue by sparhami** [Polymer/polymer#3881]
### Description

CSS variables that have not be defined should be treated as unset. They are currently ignored. See: https://drafts.csswg.org/css-variables/#invalid-at-computed-value-time

This behavior causes problems when using `useNativeCSSProperties` since the behavior differs between browsers that do and do not support custom properties.
#### Live Demo

https://jsbin.com/viyarefiqo/1/edit?html,output
#### Steps to Reproduce
1. Give an element `color: red`
2. Give the element `color: var(--my-nonexistent-color)` in a rule with more specificity or that appears after in the stylesheet
#### Expected Results

The element inherits the color from the parent
#### Actual Results

The element uses `color: red`
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11
### Versions
- Polymer: v1.6.1
- webcomponents-lite: 0.7.22

**Comment by azakus** [comment]
Looks like IE 10 & 11 and Safari < 9.1 don't implement the 'unset' keyword. IE doesn't implement 'initial', or 'inherit', so those are just broken, but I _could_ implement 'unset' as 'inherit' or 'initial' with a mapping.

WDYT @sorvell?

**Comment by TimvdLippe** [comment]
Closing per https://github.com/Polymer/polymer/pull/3883#issuecomment-329641377
