### ISSUE TITLE
Configuring object and array properties inside of the `dom-repeat` requires $ binding

### ISSUE THREAD

**Issue by web-padawan** [Polymer/polymer#3885]
### Description

Inside of `dom-repeat` template, the attributes in JSON are not deserialized into properties, as it is [expected](https://www.polymer-project.org/1.0/docs/devguide/properties#configuring-object-and-array-properties).  Adding `$` helps, see note below.
#### Live Demo

https://jsbin.com/tuwoli/edit?html,console,output
#### Steps to Reproduce
1. Create `dom-repeat` template
2. Put element with attribute (e.g. `params`) which contains JSON expected to be deserialized
3. Setup the observer, like `_paramsChanged(params.*)`
#### Expected Results

An object in JSON format is deserialized into property.
#### Actual Results

No deserialization happens, the observer contains `base` and `value` as strings: 

```
{
  base: "{ \"title\": \"Bar\" }",
  path: "params",
  value: "{ \"title\": \"Bar\" }"
}
```
#### Note

Adding an explicit attribute binding helps. You can see the difference in the JSBin. 

This code works:

```
      <template is="dom-repeat" items="[[items]]">
        <x-element params$='{ "title": "[[item.title]]" }'></x-element>
      </template>
```

While this one does not:

```
      <template is="dom-repeat" items="[[items]]">
        <x-element params='{ "title": "[[item.title]]" }'></x-element>
      </template>
```
### Browsers Affected

- [x] Chrome
- [x] Firefox
### Versions
- Polymer: v1.6.1

**Comment by web-padawan** [comment]
UPD: can also be reproduced inside of `dom-if`

**Comment by web-padawan** [comment]
Still relevant for 2.0: http://jsbin.com/vexizun/edit?html,console,output

/cc @TimvdLippe, please check this during your spring cleaning 😃

**Comment by arthurevans** [comment]
This is WAI. Anything with a binding annotation in it is a property binding, not an attribute binding.

This sets the `params` property to the string `{ "title": "Foo" }` for example.

`params='{ "title": "[[item.title]]" }'`

There's no deserialization involved: the params attribute is never touched.

On the other hand, this sets the `params` attribute:

`params$='{ "title": "[[item.title]]" }'`

Accordingly, the value is deserialized into the `params` property.

https://www.polymer-project.org/2.0/docs/devguide/data-binding#anatomy-of-a-data-binding

**Comment by web-padawan** [comment]
@arthurevans got it, thanks!
