### ISSUE TITLE
Possible memory leak in configure implementation (_config)

### ISSUE THREAD

**Issue by 43081j** [Polymer/polymer#3886]
It seems there may be some memory leak in the configure implementation [here](https://github.com/Polymer/polymer/blob/master/src/standard/configure.html).

Essentially, it appears that sometimes `el._config[prop] !== el[prop]`.

I have an element with property containing something like the following:

``` javascript
{
    "node": HTMLElement
}
```

This eventually changes so `node` becomes a different element (a child of `el`).

At this point, the previous node becomes detached from the DOM but still referenced by `el._config[prop].node`, whereas `el[prop].node` is of course the new node. With many elements, this can mean you actually have 2x the number of nodes in memory.

I will try create some steps to reproduce but am currently having trouble with that, will edit my post if I figure it out.

**Comment by TimvdLippe** [comment]
Closing as the original file has been removed in Polymer 2.
