### ISSUE TITLE
Move ApplyShim to webcomponentsjs

### ISSUE THREAD

**Issue by matthewp** [Polymer/polymer#3888]
Is there any particular reason why the shim is in Polymer?  Looking [at the code](https://github.com/Polymer/polymer/blob/ac4d4ac5d7bb42df9cbd063691780e28bfc28817/src/lib/apply-shim.html) it does depend on `Polymer.StyleUtil`, but I assume the functionality it uses of that could be pulled out as well.  I'm willing to help with this if there's not a good reason for it to stay here.

**Comment by ebidel** [comment]
This is happening as part of 2.0.

**Comment by TimvdLippe** [comment]
Closing per above comment :tada:
