### ISSUE TITLE
Using an external file to load resource does not work on firefox 44

### ISSUE THREAD

**Issue by bastienarm** [Polymer/polymer#3889]
I'm using polymer to build a web application

Everything is fine on chrome, but nothing will load on firefox.
After searching, it seems that's a good practice to use HTMLImports.whenReady callback to be sure that everything is loaded.
Using an external file to load resource does not work on firefox 44

index.html :

```
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">

    <script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>
    <script src="bower_components/lodash/lodash.js"></script>
    <script src="lib/md5/md5.js"></script>
    <script src="bower_components/page/page.js"></script>

    <link rel="import" href="utils/behaviors/i18n/i18n.html">

    <link rel="import" href="elements/elements.html">
    <link href="res/css/app.css" rel="stylesheet"/>
  </head>
  <body unresolved class="layout vertical">
    <insitu-application id="application"></insitu-application>
  </body>
</html>
```

elements/elements.html is something like this :

```
<link rel="import" href="insitu-widgets/common/insitu-widget-content-text-rules-small.html">
<link rel="import" href="insitu-widgets/common/insitu-widget-content-text.html">
```

(around 200 lines)

Using elements/elements.html will perfectly works on chrome, but not on firefox. If I remove the import of elements/elements.html and put all the import in the index.html, it seems to work (only seems, i just import 2 or 3 template to have something else than a blank screen)

Is it normal?

**Comment by bastienarm** [comment]
Hmm, in my index.html is use

```
<link rel="import" href="elements/elements.html">
```

which reference all my custom HTML files.

It seems that using an external file like this one to import all files will not work with firefox

**Comment by bastienarm** [comment]
Ok, let's improved it

index.html :
```
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">

    <script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>
    <script src="bower_components/lodash/lodash.js"></script>
    <script src="lib/md5/md5.js"></script>
    <script src="bower_components/page/page.js"></script>

    <link rel="import" href="utils/behaviors/i18n/i18n.html">

    <link rel="import" href="elements/elements.html">
    <link href="res/css/app.css" rel="stylesheet"/>
  </head>
  <body unresolved class="layout vertical">
    <insitu-application id="application"></insitu-application>
  </body>
</html>
```

elements/elements.html is something like this :
```
<link rel="import" href="insitu-widgets/common/insitu-widget-content-text-rules-small.html">
<link rel="import" href="insitu-widgets/common/insitu-widget-content-text.html">
```

(around 200 lines)

Using elements/elements.html will perfectly works on chrome, but not on firefox. If I remove the import of elements/elements.html and put all the import in the index.html, it seems to work (only seems, i just import 2 or 3 template to have something else than a blank screen)

Is it normal?

**Comment by bastienarm** [comment]
Ok, it finally seems that's because high number of imports inside my elements.html.

Tried to split import into each module, but it seems that around 25/30 imports, firefox doesn't want to load anything.

Any solution?

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with Polymer 2 for us to be able to debug and potentially fix. Polymer 2 fixes a large amount of issues, probably including this one as well.

Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with Polymer 2.  Thank you!
