### ISSUE TITLE
TypeError: Identifier XXX has already been declared - on external scripts load

### ISSUE THREAD

**Issue by AlexNasonov** [Polymer/polymer#3890]
If I load the same script that contains ES6 class definition few times in different components on the same page, I get `TypeError: Identifier 'ClassName' has already been declared`. But it seems OK if I change class definition to JS regular function.

**Comment by TimvdLippe** [comment]
Please follow the guidelines for creating issues at https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs
