### ISSUE TITLE
iOS Safari not supporting touch-action style resulting in improper disabling of scrolling with elements that have track event attached

### ISSUE THREAD

**Issue by chachkovivan** [Polymer/polymer#3891]
### Description

According to the Polymer documentation, the elements with track event enabled should disable scrolling by default.
In the Gestured.html there is a test for native support of gestures through touch-action style

"var HAS_NATIVE_TA = typeof document.head.style.touchAction === 'string';"

later on, the code is using HAS_NATIVE_TA variable to branch the logic to either rely on the native support of the style by the browser or through Gestures.handleTouchAction(ev); method.

According to the WebKit bug report:
https://bugs.webkit.org/show_bug.cgi?id=149854

the support in web kit is limited to "manipulation" setting and "pan-x" and "pan-y" styles are not supported. This results in scrolling still happening in iOS browsers even though an element has track event enabled.
#### Steps to Reproduce
1. Create and element with a node with "track" event handler.
2. Using iOS Safari move finger up or down over the node.
3. Observe the document scroll.
#### Expected Results

The scrolling must not be happening.
#### Actual Results

The document is scrolling.
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ x] Safari 9
- [x ] Safari 8
- [ ] IE 11
### Versions

- Polymer: v1.6.1
- webcomponents: vX.X.X 
### Suggested fix

Perhaps the test for touch-action style support should be enhanced

Replace:
"var HAS_NATIVE_TA = typeof document.head.style.touchAction === 'string';"

With:
var HAS_NATIVE_TA = false;
if(typeof document.head.style.touchAction === 'string')
{
      document.head.style.touchAction="pan-y";
      HAS_NATIVE_TA = document.head.style.touchAction === 'pan-y';
}

**Comment by kobleistvan** [comment]
Any updates on this? Seems to still happen to me...
