### ISSUE TITLE
Delete subproperty observably.

### ISSUE THREAD

**Issue by MarcMouallem** [Polymer/polymer#3892]
Currently the `set` method, documented  [here](https://www.polymer-project.org/1.0/docs/devguide/data-system#make-observable-changes), can be used to mutate a sub property observably. However there is no Polymer mutate and notify convenience method for the JavaScript `delete` operation. The current means of doing so, shown below, is not pretty.
### Current

```
delete this.myObject.mySubProperty;
this.notifyPath('myObject.mySubProperty');
```
### Proposed

```
this.delete('myObject.mySubProperty');
```

**Comment by cheesemuffinish** [comment]
We are having this same problem. We are currently overriding the dirty checking as per the documentation, but that feels horribly hacky.

**Comment by TimvdLippe** [comment]
Closing as duplicate of https://github.com/Polymer/polymer/issues/2565#issuecomment-357517156
