### ISSUE TITLE
polymer elements and security

### ISSUE THREAD

**Issue by Alphapage** [Polymer/polymer#3898]
Hello,

I can't find any info about how security is performed if you want to isolate a webcomponent in polymer. Sorry.
I want to include a webcomponent from a third party website, but I don't to share my dom or my website data: cookies...

I'd like to know if the best way to isolate is to encapsulate the webcomponent in an iframe or if there is any special property to enable such a security in polymer.

Thanks in advance for your help.

**Comment by arthurevans** [comment]
The reason there's no discussion of this is because Web Components don't provide any new secure features. To isolate third-party components, use an iframe.
