### ISSUE TITLE
on-click is not fired by the Enter key

### ISSUE THREAD

**Issue by TedDriggs** [Polymer/polymer#390]
Fiddle is here: http://jsbin.com/UkERoXA/2/

It is common in JS to use 'click' to mean activated by any input, including touch, mouse, and keyboard. The inability to activate bound clicks with the enter key is an accessibility issue for people who need to use keyboard navigation, and a convenience issue for those who want to.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
