### ISSUE TITLE
Polymer not working after updating

### ISSUE THREAD

**Issue by PuruVijay14** [Polymer/polymer#3900]
#### Live Demo

https://jsbin.com/xukike/edit?html,output

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: vX.X.X
- webcomponents: vX.X.X

**Comment by ebidel** [comment]
Please reopen when you have steps and a jsbin to repro the issue.
