### ISSUE TITLE
:root[dir="rtl"] does not work with shimed CSS properties

### ISSUE THREAD

**Issue by azakus** [Polymer/polymer#3902]
#### Live Demo

With `useNativeCSSProperties`
http://jsbin.com/zoloru/edit?html,output

Without:
http://jsbin.com/qezehez/edit?html,output

**Comment by eeid26** [comment]
Actually there is another annoying bug that makes supporting rtl in polymer not as easy as it should be.
(I already reported the bug before and it was marked as a duplicate and it wasn't really.)

a rule like
:host([some-attribute]):host-context([dir='rtl']) 
works in shadow dom and it does not work in shady dom.

Example showing the bug using a modified version of your Example:
with shadow dom (Works)
http://jsbin.com/dutihahuye/edit?html,output

with shady dom (Does not work)
http://jsbin.com/sumihenefu/edit?html,output

**Comment by helenxywu** [comment]
@eeid26  Have you tried the workaround here https://github.com/webcomponents/webcomponentsjs/issues/16?

**Comment by eeid26** [comment]
Thank you @helenxywu
Yes I tried it before and I tried it now and it did not work for me. Even the example in the link did not work for me.

**Comment by helenxywu** [comment]
yea you're right I'm filing another bug for that. https://github.com/Polymer/polymer/issues/3904
