### ISSUE TITLE
Polymer on NPM stuck on version 1.2.5

### ISSUE THREAD

**Issue by lukasoppermann** [Polymer/polymer#3903]
Hey,

could you please publish 1.6.1 to npm? Thanks.

**Comment by ebidel** [comment]
This is something we need to do for 2.0!

**Comment by d4l3k** [comment]
Can we at least push v1.7.0 to NPM?

**Comment by reicruz** [comment]
Has this gotten any attention to push the latest version? Or are you waiting until 2.0 to publish a new version on npm?

**Comment by seaneking** [comment]
Bump. We're aiming for full Yarn support for our components to start moving away from Bower but not being able to pull in Polymer as a peer dep is stopping us from doing that. Is there anything blocking publishing 1.7 to NPM (for Yarn)?

**Comment by justinfagnani** [comment]
The client-side packages in the `@polymer` scope are still experimental as of now. We're trying to ready all the pieces that will let published fully supported packages, but we're not there yet. We're focused on getting 2.0 out the door, and then npm/yarn support will be top priority.

**Comment by pomber** [comment]
2.0 is on [NPM](https://www.npmjs.com/package/@polymer/polymer)

**Comment by leogr** [comment]
Is it still experimental?

**Comment by seaneking** [comment]
Also looks like all the other packages in the `@polymer` scope are still alpha versions (0.0.x) - is there a timeline to bump those?

**Comment by pomber** [comment]
>Is it still experimental?  

[Yes](https://github.com/Polymer/polymer/issues/4611#issuecomment-302565375)

**Comment by mrjoops** [comment]
Recently, while installing polymer2 through npm, the following message was brought to my attention:

> ...psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects!

This message appears since late may as a npm deprecated message, and also on the bower.io and in it repo README.

Obviously it's not an easy task since the documentation and the starter kit heavily depends on bower, and Polymer/polymer is not the only repo to update, but migrating to npm seems the way to go.

**Comment by web-padawan** [comment]
@mrjoops please see #326 - it is the original issue to track npm progress

**Comment by TimvdLippe** [comment]
Closing this issue per https://github.com/Polymer/polymer/issues/326#issuecomment-387910751 `@polymer/polymer` is now maintained on NPM since version 3 🎉
