### ISSUE TITLE
observers: 'myObserver' should trigger a warning

### ISSUE THREAD

**Issue by bennypowers** [Polymer/polymer#3907]
### Description

When definine a single observer on `observers:{}`, the observer fails silently. 
#### Live Demo

https://jsbin.com/topicukejo/edit?html,console,output
#### Expected Results

I would expect a console warning that an array of observers is expected
#### Actual Results

Silent failure is the best kind of failure.

**Comment by TimvdLippe** [comment]
This issue was moved to Polymer/polymer-linter#156
