### ISSUE TITLE
importHref fails to fetch resource when it's used offline, then while online

### ISSUE THREAD

**Issue by Gaubee** [Polymer/polymer#3908]
### Description

Page returned from the offline to the online state, the original request error page(404) can not be requested again.
#### Live Demo

https://jsbin.com/xukike/edit?html,output
### Browsers Affected

- [x] Chrome
- [ ] Safari 8
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] IE 11
### Versions

- Polymer: v1.6.1
- webcomponents: vX.X.X

**Comment by ebidel** [comment]
Please post a jsbin that repos the issue and reopen when you do.

**Comment by TimvdLippe** [comment]
@ebidel https://jsbin.com/foduvubici/edit?html,console,output

**Comment by ebidel** [comment]
Thanks for that. Looks like this is because `imporHref` maintains an internal cache (https://github.com/Polymer/polymer/blob/06bc9dbe34042268b94e60374910b6d6ce1ae3d7/src/standard/utils.html#L395).
