### ISSUE TITLE
Data change notifications not working when a property is defined in DOM

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#3912]
_From @e111077 on August 1, 2016 19:20_

There is an issue with change events not notifying when you specify a data binding. Here is an example:

``` html
<link rel="import" href="../../polymer/polymer.html">

<dom-module id="asdf-asdf">
  <script>
    Polymer({
      is: 'asdf-asdf',

      properties: {
        a: {
          type: Object,
          value: function() {return {path: null};},
          notify: true
        },

        b: {
          type: Object,
          value: function() {return {path: null};},
          notify: true
        }
      },

      observers: [
        'aPathChanged(a.path)',
        'bPathChanged(b.path)'
      ],

      // propagates a.path to b.path
      aPathChanged: function() {
        if (this.a.path === this.b.path) {
          return;
        }
        console.log('setting path in ' + this.id + ' for b to ' + this.a.path);

        this.set('b.path', this.a.path);
      },

      // propagates b.path to a.path
      bPathChanged: function() {
        if (this.b.path === this.a.path) {
          return;
        }
        console.log('setting path in ' + this.id + ' for a to ' + this.b.path);

        this.set('a.path', this.b.path);
      }
    });
  </script>
</dom-module>

<dom-module id="asdf-asdf-parent">
  <template>
    <asdf-asdf id="first" a="{{c}}" b="{{d}}"></asdf-asdf>
    <asdf-asdf id="second" a="{{d}}"></asdf-asdf>
  </template>
  <script>
    Polymer({
      is: 'asdf-asdf-parent',

      properties: {
        c: {
          type: Object
        },

        d: {
          type: Object
        }
      }
    });
  </script>
</dom-module>

<asdf-asdf-parent></asdf-asdf-parent>
<script>
  var element = document.querySelector('asdf-asdf-parent');
  element.$.first.a = {'path': 'asdf'};
</script>

```
# Expected Result

It should print:

```
setting path in first for b to asdf
setting path in second for b to asdf
```

additionally, `element.$.second.b` should be `{ path : 'asdf' }`
# Actual Result

It prints:

```
setting path in first for b to asdf
```

and `element.$.second.b` is `{ path : null }` which is the default value despite `element.$.second.a` being changed to `{ path : 'asdf' }` due to data binding.
# Additional Detail

It works as expected if you don't bind anything to `a` in `id="first"` i.e. you change

``` html
<asdf-asdf id="first" a="{{c}}" b="{{d}}"></asdf-asdf>
```

to

``` html
 <asdf-asdf id="first" b="{{d}}"></asdf-asdf>
```
# Workaround

You can manually call `this.notifyPath` after each `this.set`.

_Copied from original issue: PolymerLabs/alacarte#19_

**Comment by kevinpschaaf** [comment]
_From @e111077 on August 1, 2016 22:35_

Further investigation shows that changing `element.$.first.b` or `element.$.second.a` seem to give the expected result, but changes to the ends of this chain (`first.a` and `second.b`) fail.

**Comment by kevinpschaaf** [comment]
_From @notwaldorf on August 2, 2016 21:43_

Note from the future: this works if `value` is a notifying property, so I think my example is a different bug.


Here's my super tiny repro steps, just in case:

<b>me-ow.html</b>
```html
<link rel="import" href="../polymer/polymer.html">
<dom-module id="me-ow">
  <template>
    <div>value: [[value]]</div>
  </template>
  <script>
      Polymer({
        is: 'me-ow',
        properties: {
          value: {
            type: String,
            observer: '_valueChanged'
          }
        },
        _valueChanged: function() {
          // manually notify because we don't want to notify until after setting value
          // (this is a thing iron-input needs)
          this.fire('value-changed', {value: this.value});
        }
      });
  </script>
</dom-module>
```

<b>index.html</b>
```html
<html>
<head>
  <script src="../webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="me-ow.html">
</head>
<body>
<dom-bind>
  <template>
    <me-ow value="{{value}}" id="i"></me-ow>
    bind to <code>value</code>: {{value}}</br>
    <button onclick="i.value='banana'">set value to "banana"</button>
  </template>
</dom-bind>
</body>
</html>
```

**Comment by kevinpschaaf** [comment]
_From @sorvell on August 10, 2016 20:54_

@e111077 Note that is probably not related to the issue here, but... Accessing `this.b` in an observer that only depends on `a.path` is an anti-pattern (e.g. `if (this.a.path === this.b.path) {`). Can you avoid doing that?

**Comment by kevinpschaaf** [comment]
_From @e111077 on August 10, 2016 21:18_

@sorvell This used to not have to have this anti-pattern because we had a pattern that used `linkPaths` which currently is not compatible with alacarte. Is the functionality being dropped, or is it just not implemented yet?

**Comment by kevinpschaaf** [comment]
_From @sorvell on August 10, 2016 23:25_

See https://github.com/PolymerLabs/alacarte/issues/50.

**Comment by kevinpschaaf** [comment]
`linkPaths` is now implemented, and the original issue no longer repros (http://jsbin.com/digixepule/edit?html,console,output matches expected results).  Closing!

**Comment by retrocausal** [comment]
@kevinpschaaf  Hi, I was browsing through issues for when observers do not track array mutations when the arrays are two-way bound to another element , and wanted to check before I reopen this, or create a new issue.

I have two elements, bound via an array property, notifying host<=>target

the problem is, until I explicitly call `this.<array>.splice()` , the observers on either element do not pick up mutations, even though I use proper polymer mutation methods and specify paths as needed.

such as `this.push('path',value);`

**Comment by TimvdLippe** [comment]
@retrocausal Please open a new issue with a runnable JSBin and we will take a look :smile:
