### ISSUE TITLE
I think <style is="custom-style" include="foo"> is broken

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#3917]
_From @notwaldorf on August 10, 2016 18:33_

I certainly can't successfully hold it in the same way as before. Halp.

**index.html**
```
<html>
<head>
  <script src="../webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="../polymer/polymer.html">
  <link rel="import" href="shared-styles.html">
  <style is="custom-style" include="shared-styles"></style>
</head>
<body>
  <h1>meow</h1>
</body>
</html>
```

**shared-styles.html**
```
<script>console.log('shared-styles loaded');</script>
<dom-module id="shared-styles">
  <template>
    <style>
      body {
        background: cornflowerblue;
      }
      h1 {
        color: red;
      }
    </style>
  </template>
</dom-module>
```

`shared-styles loaded` gets printed, but the styles don't get applied. I tried this on Chrome stable and Canary and Safari.

/cc @sorvell @azakus 

_Copied from original issue: PolymerLabs/alacarte#49_

**Comment by sorvell** [comment]
Should now be fixed in the `2.x-preview` branch.
