### ISSUE TITLE
Binding to the class attribute (`class$="[[...`) overwrites shady DOM classes.

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#3918]
_From @bicknellr on August 10, 2016 1:5_

A handful of elements use bindings reflected to the class attribute to add or remove them based on current state. The result of this binding ends up removing classes used by shady DOM to scope styles.

_Copied from original issue: PolymerLabs/alacarte#46_

**Comment by sorvell** [comment]
Blocked on https://github.com/webcomponents/shadydom/issues/2.

**Comment by sorvell** [comment]
Fixed!
