### ISSUE TITLE
`dom-repeat` has some issues in stamping when it is distributed content in ShadyDOM

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#3919]
_From @valdrinkoshi on August 19, 2016 0:51_

In ShadyDOM mode, `dom-repeat` has some issues in stamping when it is distributed content, e.g.

``` html
<!-- x-outer template -->
    <template>
      <x-inner>
        <slot></slot>
      </x-inner>
    </template>

<!-- dom-repeat in x-outer -->
  <x-outer>
    <dom-repeat items='[{"name": "item0"}]'>
      <template>
        <div id$="[[item.name]]">{{item.name}}</div>
      </template>
    </dom-repeat>
  </x-outer>
```

http://jsbin.com/jadedag/2/edit?html,console,output

_Copied from original issue: PolymerLabs/alacarte#73_

**Comment by kevinpschaaf** [comment]
_From @sorvell on August 22, 2016 17:2_

The issue here is that the `dom-repeat` is getting patched by `x-outer` when it creates its shadowRoot and then un-patched when it upgrades. Since `dom-repeat` does not create a shadowRoot (the only way an element kicks off patching currently), it never gets re-patched.

This problem is similar to #62. Both of these issues are suggesting that the mechanism via which an element is patched is going to need some work.

**Comment by sorvell** [comment]
No longer relevant.
