### ISSUE TITLE
Use cases for AsyncRender

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#3920]
_From @blasten on August 19, 2016 23:37_

The [AsyncRender](https://github.com/PolymerLabs/alacarte/blob/master/src/utils/async-render.html) module has a `beforeRender` and `afterRender` method. I think those methods could be used for DOM measure and mutations respectively. I wanted to see if that is the case, and if so, could they have a more intuitive name/ maybe promise-based API? I found myself doing this every time I want to minimize layout thrashing. Wondering about your thoughts @kevinpschaaf @sorvell Thanks!

_Copied from original issue: PolymerLabs/alacarte#76_

**Comment by kevinpschaaf** [comment]
@blasten This API is primarily an API provided for backwards-compatibility; `afterRender` was primarily added for deferring non-critical work to post-paint.

You're free to use the `beforeRender` (which is really just rAF) API to batch measurements, but the problem in general is more complex when you get to element composition, and I would be inclined to focus on helping work out what the right platform primitive to ensure interoperability will be, then polyfill that.

Given that Polymer data binding currently propagates _writes_ downward into the dom synchronously, this lends itself to batching reads in e.g. beforeRender/rAF, and then doing writes after that (not necessarily batched; batching only needs to happen for reads _or_ writes, but not both, to prevent layout thrash).

**Comment by blasten** [comment]
@kevinpschaaf sounds good! @justinfagnani had a design doc around this issue.

**Comment by kevinpschaaf** [comment]
Closing, no planned changes here.
