### ISSUE TITLE
linkPaths does not work with array index paths

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#3921]
It's unclear whether this is a bug or not, but calling `linkPaths` with an array index path, like `data.0.items` appears to fail silently.

Looking at `linkPaths`, it appears that's because we maintain a list of bound paths, but since array changes are always notified with key paths, these don't get mapped.

Arguably, this behavior is correct, since a mapping between `data.0.items` and `items` would be unstable. However if that's the case, I think the docs should reflect this (and the method could throw an error if you pass in an index path.
### Description

Run demo. Notice that the two paths (`people` and `data.0.items` don't update in lockstep. Switching to the key path causes the arrays to update correctly.
#### Live Demo

https://jsbin.com/qivalipadu/1/edit?html,output
### Versions

Polymer 1.6.1.

**Comment by elonmallin** [comment]
Noticed the jsbin used the workaround solution with `Collection.get(...).getKey(...)` so copied it and added the line showing the bug here: https://jsbin.com/kutunotuxo/1/edit?html,output

**Comment by elonmallin** [comment]
Potentially if the right solution is to throw an error maybe it would be good with some function to convert an index path to a key path in polymer. Something like: https://gist.github.com/elonmallin/9a63c8c61cabeba5f17588c4a989a7b3

**Comment by devinivy** [comment]
Related to #3558.  Especially see the tests, which shows `linkPaths()` linking array items.

**Comment by arthurevans** [comment]
Actually, I don't think this is related to #3558. That's about the _format_ in which we specify paths (to anything). That is, `linkPaths(['one', 'two'], 'three')` == `linkPaths('one.two', 'three')`.

This issue has to do with what the path _identifies_. In particular, whether you can have a path segment that's an array _index_ (`array.11`) as opposed to a key (`array.#7`).

**Comment by devinivy** [comment]
Ah, but see the test also linking array paths,
```js
el.linkPaths(['b', 'arr', 0], ['a', 'arr', 0]);
```

**Comment by kevinpschaaf** [comment]
Resolved on 2.0-preview via changes to remove `Polymer.Collection` and key-based path notification, as well as more robust `linkPaths` which calls `Polymer.Path.normalize` to normalize an Array-based path argument to a string before linking.

Will keep open as a 1.x tracking issue.
