### ISSUE TITLE
methods to deeply query the dom require CompatElementMixin

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#3922]
_From @valdrinkoshi on August 22, 2016 21:30_

Methods like `queryDistributedElements` are declared in `Polymer.CompatElementMixin`, so this requires the author of a mixin to depend on the user to pass `Polymer.CompatElement`. Instead, it would be cool to have these methods accessible as a separate library - maybe `Polymer.Dom`?

_Copied from original issue: PolymerLabs/alacarte#79_

**Comment by kevinpschaaf** [comment]
_From @sorvell on August 26, 2016 0:9_

It's reasonable to move this stuff into a separate library like `dom-query-utils`or something that `CompatElement` consumes and facades. PR's welcome =)

**Comment by kevinpschaaf** [comment]
May combine with `observeNodes` (#3923) implementation into a mixin with "effective children" helper utilities.

**Comment by sorvell** [comment]
We've decided not to push using an abstraction for this type of dom querying v. using standard platform methods. For that reason, we're electing not to include a mixin separate from the legacy api.
