### ISSUE TITLE
Polymer.Base._warn et logging friends

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#3926]
_From @valdrinkoshi on August 24, 2016 0:26_

Will these be ported to 2.0?

_Copied from original issue: PolymerLabs/alacarte#88_

**Comment by sorvell** [comment]
Probably makes sense to be implemented as a logging mixin that is then used by `Polymer.LegacyElement`

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/polymer/pull/4156.
