### ISSUE TITLE
Clicking an input throws error in event-mixin.js

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#3929]
It's not easy to throw a test page up for 2.0 stuff atm, but I have a simple input on the page. When I click it, event-mixin.js:71 throws an error.

<img width="1128" alt="screen shot 2016-09-09 at 4 57 19 pm" src="https://cloud.githubusercontent.com/assets/238208/18406181/8999b57e-76ae-11e6-9417-59f913602ae8.png">

**Comment by ebidel** [comment]
cc @azakus so you're aware

**Comment by notwaldorf** [comment]
This _should_ be fixed in the latest commit (i stopped seeing it after a bower update)

**Comment by jfrazzano** [comment]
+10

**Comment by ebidel** [comment]
Latest shadydom commit?

**Comment by notwaldorf** [comment]
@ebidel yup, i think https://github.com/webcomponents/shadydom/commit/5169cad1e216f83fd033f66e4799e019509df62d

**Comment by sorvell** [comment]
Seems gtg: http://jsbin.com/vayebit/edit?html,console,output. Please re-open if the issue resurfaces.
