### ISSUE TITLE
`this.$` is undefined on `attached()` with native ShadowDom

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#3930]
_From @valdrinkoshi on August 26, 2016 22:35_

`x-1` contains a `x-2` in its shadowRoot.
When `x-2`'s attached is invoked, `this.$` is `undefined` (native ShadowDom)

```html
<dom-module id="x-1">
  <template>
    <style>
      :host {
        display: block;
        padding: 10px;
        border: 1px solid;
      }
    </style>
    <x-2>
      <content></content>
      <slot></slot>
    </x-2>
  </template>
  <script>
    Polymer({
      is: 'x-1'
    });
  </script>
</dom-module>


<dom-module id="x-2">
  <template>
    <div id="wrapper">
      <content id="content"></content>
      <slot id="slot"></slot>
    </div>
  </template>
  <script>
    Polymer({
      is: 'x-2',
      attached: function() {
        console.log(this.$);
      }
    });
  </script>
</dom-module>

<x-1>
  <div> hello </div>
</x-1>
```

_Copied from original issue: PolymerLabs/alacarte#96_

**Comment by kevinpschaaf** [comment]
_From @valdrinkoshi on August 26, 2016 22:43_

@sorvell is this related to https://github.com/PolymerLabs/alacarte/issues/71?

**Comment by kevinpschaaf** [comment]
_From @sorvell on August 26, 2016 23:29_

yes

**Comment by sorvell** [comment]
Will be addressed via https://github.com/Polymer/polymer/issues/3933.

**Comment by kevinpschaaf** [comment]
Resolved via https://github.com/Polymer/polymer/pull/3947
