### ISSUE TITLE
Consider deferring `attached` to emulate 1.0 callback timing

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#3933]
_From @sorvell on August 29, 2016 21:27_

Related issues: #71, #96.

In 1.0, elements were ensured to be readied before being attached. This allowed use of local dom and (at lease naive) measurement in attached.

This was achieved specifically by deferring `attached` until after `ready` if the system tried to call it too soon.

We could retain this guarantee without explicitly deferring `attached` by readying (flushing) an element before attaching its local dom. This would change the guarantees around `ready`. Specifically, it would be unsupported to look at `shadowRoot` in ready.

Perhaps we should simply add back the defer `attached` behavior from 1.0 to ensure as little breakage for users of the 'legacy' api as possible.

_Copied from original issue: PolymerLabs/alacarte#102_

**Comment by sorvell** [comment]
This will likely not be addressed in `Polymer.Element` where we are not inclined to introduce new lifecycle (`attached`). Based on feedback we'll see if we need to add guidance around how to account for this.

**Comment by kevinpschaaf** [comment]
Resolved via https://github.com/Polymer/polymer/pull/3947
