### ISSUE TITLE
Polymer.Gestures: change addListener back to add for compatibility

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#3936]
_From @valdrinkoshi on August 31, 2016 23:31_

`Polymer.Gestures.add/remove` got mapped to `Polymer.Element.events.addListener`, but it would be nice to have the old `Polymer.Gestures` for legacy reasons

_Copied from original issue: PolymerLabs/alacarte#107_

**Comment by kevinpschaaf** [comment]
_From @sorvell on September 1, 2016 18:58_

This is currently renamed to `Polymer.Gestures.addListener`, but we'll change the name back to `add` to avoid the bc issue.

**Comment by azakus** [comment]
Fixed with #4346
