### ISSUE TITLE
`getComputedStyleValue` returns values with surrounding whitespace

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#3939]
_From @bicknellr on September 8, 2016 21:18_

```html
<html>
<head>
  <script src="../webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="../polymer/polymer.html">
</head>
<body>
  <dom-module id="test-element">
    <template>
      <style>
        span {
          color: var(--test-prop, red);
        }
      </style>
      <span id="span">span</span>
    </template>
    <script>
      Polymer({
        is: 'test-element',
      });
    </script>
  </dom-module>

  <custom-style>
    <style is="custom-style">
      test-element {
        --test-prop: green;
      }
    </style>
  </custom-style>
  <test-element></test-element>
</body>
</html>
```

`document.querySelector('test-element').getComputedStyleValue('--test-prop')`
returns `" green"`

_Copied from original issue: PolymerLabs/alacarte#117_

**Comment by sorvell** [comment]
Should be addressed via https://github.com/webcomponents/shadycss/issues/4.

**Comment by azakus** [comment]
Closed for webcomponents/shadycss#4

**Comment by azakus** [comment]
Native CSS properties count everything after the `:` as part of the value: http://jsbin.com/kewaver/edit?html,console,output

**Comment by bicknellr** [comment]
Strange, I guess that makes sense though since a CSS custom property value can be any valid CSS value. I think I was expecting it to be reserialized from the already parsed tokens or something; maybe I should bring this up on the CSSOM spec repo..

**Comment by jfrazzano** [comment]
You can strip the whitespace, which is… well, on dynamic layouts it can be a mixed bag.  Is there another way to move up the shadow for parent/grandparent computed properties through content or to grab the things like width/height early to use in Iron resize? now I am passing the values I need up through proxies so a two way bind on late to render/transition drawers won’t miss their resize or their transition/self-adjustment/child adjustment.  Its not terrible, but any cool way to snag sometimes tough to grab computed styles would rock.

Thanks.

Sincerely,

Jason
