### ISSUE TITLE
Reintroduce listen/unlisten as an optional util

### ISSUE THREAD

**Issue by 43081j** [Polymer/polymer#3949]
2.x.

We now rely on adding event listeners and dispatching events manually, which is great and removes some complexity.

However, `listen(...)` had some very useful logic to handle bound listeners using a WeakMap (so unused listeners/elements would be garbage collected). 

We are now back to having to do this, in every element where it is needed:

``` javascript
this._boundHandler = this._handler.bind(this);
// ...
this.addEventListener('event', this._boundHandler);
// ...
this.removeEventListener('event', this._boundHandler);
```

Would it be worth reintroducing the logic we had but as some kind of util? 

It had some useful re-usable logic, such as avoiding duplicate handlers, automatically binding the scope, an internal weakmap of the handlers (rather than us having a `_boundHandler` in our element), etc.

**Comment by btelles** [comment]
Agreed. And I'd like to add that having a simple map of {"event" : "handler"} is much easier to glance at than this.addEventListener('interestingBit', this.otherInterestingBit).

**Comment by sorvell** [comment]
This is provided as part of the `Polymer.LegacyElementMixin`.
