### ISSUE TITLE
Compatibility set method no longer accepts third argument

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer#3953]
In Polymer 1.x, a user could update an arbitrary object via the following usage of `this.set`:

```javascript
Polymer({
  // ...
  someMethod: function() {
    var myObject = {
      foo: 1
    };
    this.set('foo', 2, myObject);
  }
});
```

However, `set` in Polymer 2.0-preview does not support this third-argument usage.

**Comment by kaste** [comment]
I remember that I proposed to remove this third argument. What's the use case here?

**Comment by cdata** [comment]
The use case is API compatibility with 1.0. Yes, the argument is vestigial,
but it is no less used in the real world and will impact hybrid-mode
migrations to 2.0.

**Comment by kevinpschaaf** [comment]
Resolved by https://github.com/Polymer/polymer/pull/3970
