### ISSUE TITLE
Missing API doc for isAttached property

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#3956]
_From @lingtalfi on August 23, 2016 17:40_

In the source code of the app-drawer element,  the isAttached property is used.

``` js
// line 236 if app-drawer.html
      observers: [
        'resetLayout(position, isAttached)',
        '_resetPosition(align, isAttached)'
      ],
```

Cannot found that property/attribute in the doc.
I searched that page: https://www.polymer-project.org/1.0/docs/devguide/observers, and googled it too.

Maybe it's not intended to be used by developers?
But if it is, it should be documented.

_Copied from original issue: Polymer/docs#1721_

**Comment by arthurevans** [comment]
I thought I'd already filed a bug on this one, but I can't find it. `isAttached` is missing from the API docs.

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/polymer/pull/4368.
