### ISSUE TITLE
Paper badge does not render inside firefox  48.0

### ISSUE THREAD

**Issue by oleersoy** [Polymer/polymer#3962]
Firefox 48.0 released  August 2, 2016 on Ubuntu 14.04 LTS.  Trying rendering this link in it:
https://elements.polymer-project.org/elements/paper-badge?view=demo:demo/index.html&active=paper-badge

Also try this link:
https://elements.polymer-project.org/elements/iron-iconset-svg?view=demo:demo/index.html&active=iron-iconset-svg

I suspect that the root cause is causing issues with many of the demos.

**Comment by TimvdLippe** [comment]
Please follow the guidelines for creating issues at https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs
