### ISSUE TITLE
domHost throws because getRootNode isn't implemented yet.

### ISSUE THREAD

**Issue by blasten** [Polymer/polymer#3963]
If I try to read:

``` js
element.domHost
```

I get: 

```
Error: this.getRootNode is not a function
```

In Chrome beta, it defaults to the native method https://dom.spec.whatwg.org/#dom-node-getrootnode. I tested in stable.

**Comment by sorvell** [comment]
Should be fixed, but we'll add a test.

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/polymer/pull/4337.
