### ISSUE TITLE
Huge performance degradation between Polymer 1.4 and 1.6 on IE11

### ISSUE THREAD

**Issue by mdwragg** [Polymer/polymer#3965]
Hi,

We're seeing a huge performance degradation between Polymer 1.4.x and Polymer 1.6.x for a specific component of ours (GE Digital's Polymer-based design system): https://github.com/PredixDev/px-data-table

This only happens in IE11, I've built a couple of examples to show this below. Behind each of those github pages is a minimal demo showing the behaviour.

#### Live Demo
Fast: https://mdwragg.github.io/polymer14-data-table/
Slow: https://mdwragg.github.io/polymer16-data-table/

and repos:

https://github.com/mdwragg/polymer14-data-table
https://github.com/mdwragg/polymer16-data-table

#### Steps to Reproduce
Load up the `polymer14` url, note how it is snappy on IE11, now load up the `polymer16` URL and note how slow it is...

#### Expected Results
Performance should be comparable between the two.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11

Thanks!
Martin.

**Comment by sjmiles** [comment]
Fwiw, I traced the problem to this commit https://github.com/Polymer/polymer/commit/80be0df49b4c9e4f5d755f3a42fb23a447d5b284.

**Comment by sjmiles** [comment]
It looks like the @media query refresh installed in the commit above is happening too frequently for the large style-sheets used by the demo, causing the slow down.

Gating the refresh instead of performing it on every `applyElementStyle` is likely to mitigate the problem. 

I was suggested by Steve that moving lines 510-513:

```js
        // @media rules may be stale in IE 10 and 11
        if (IS_IE) {
          style.textContent = style.textContent;
        }
```

to inside the conditional at line 496:

```js
          // shady and cache hit but not in document
          } else if (!style.parentNode) {
            styleUtil.applyStyle(style, null, element._scopeStyle);
          }
```
might be a fix. 

I can confirm it mitigates the performance problem, but @azakus will need to take a look.

Also, while we're here, should `style.textContent = style.textContent` be `style.textContent = cssText;`?

**Comment by mdwragg** [comment]
Thanks x 💯  for digging in guys - GE always appreciates our friends at Polymer helping out!

(cc @tjsavage @robdodson - thank you)

**Comment by sjmiles** [comment]
@mdwragg: thank you for the thorough repro content, it makes all the difference.

**Comment by mdwragg** [comment]
@sjmiles - you're very welcome! Thanks too for the swift resolution.

**Comment by mdwragg** [comment]
Oh, one last question, just so I can advise the engineering teams @ GE relying on this fix. Will this make it into a patch release of Polymer 1.x? I know you guys are pushing for Polymer 2.x right now so was just interested to know how/if that effected the next 1.x release. Thanks guys.

**Comment by azakus** [comment]
Yes, this will be in the next 1.x release.

**Comment by mdwragg** [comment]
Awesome, thanks @azakus!
