### ISSUE TITLE
WebComponentsReady will not fire without the wjs import

### ISSUE THREAD

**Issue by jay8t6** [Polymer/polymer#3966]
WebComponentsReady event does not fire if there are no imports to webcomponentsjs-lite or webcomponentsjs full versions. How do we handle the ready event on evergreen browsers like chrome?

**Comment by ebidel** [comment]
Check out https://gist.github.com/ebidel/1d5ede1e35b6f426a2a7#file-wcr_lazyload-html-L20-L27

**Comment by jay8t6** [comment]
Great, thanks!

**Comment by jay8t6** [comment]
On a second note, this seems to be fired way earlier than I want it to fire, it fires at the right time if I include wcjs lite version... any idea?

**Comment by ebidel** [comment]
The timing of the native apis and the polyfills will be different. What do you mean by "at right time"?

**Comment by jay8t6** [comment]
@ebidel The timing on the polyfill seems to fire correctly. I am trying to add a loading animation on the index page, I am not able to access the loading container to hide it if I use the approach you provided. It fires way too early before the DOM is ready. But if I use the lite version, I am able to access the loading container on WebComponentsReady.

**Comment by ebidel** [comment]
You'll have to post a repro.

**Comment by daslicht** [comment]
```           
 window.addEventListener('WebComponentsReady', () =>{
                console.log('WebComponentsReady')
            });
```
doens't fire in Chome but Safari
