### ISSUE TITLE
Array-selector not implemented in 2.0

### ISSUE THREAD

**Issue by e111077** [Polymer/polymer#3973]
[`array-selector`](https://www.polymer-project.org/1.0/docs/api/array-selector) doesn't seem to exist in 2.0. Is it going to be implemented, or are we dropping it?

**Comment by jay8t6** [comment]
check their README.md, it says array selector is not yet implemented.

https://github.com/Polymer/polymer/tree/2.0-preview

**Comment by e111077** [comment]
@jay8t6 *facepalm* thanks
