### ISSUE TITLE
Property Validation

### ISSUE THREAD

**Issue by StokeMasterJack** [Polymer/polymer#3975]
In a normal JavaScript class I can use constructor and setters to ensure that my object is never passed invalid values and thus never enters an invalid state.

I would be nice to have this in Polymer.

Here is why I am asking. I have a bug resulting from one of my component properties having an invalid value. I’m not sure how it became invalid. Normally, my first step would be to ensure that it’s not being passed bad values. I would do this by using constructors and setters.

With Polymer being a layer of magic on top of Plain Old JavaScript, I’m not sure how to approach this problem.

**Comment by StokeMasterJack** [comment]
Here is the bug I am getting in my browser. 

![057](https://cloud.githubusercontent.com/assets/123349/18733555/d0c01d96-8020-11e6-88bf-6a1f41d4f79b.png)

I would rather fail-fast and signal the problem further upstream.

**Comment by LM450N** [comment]
It seems the `function` keyword is missing from the definition.

```javascript
getValue: function() {
  ...
}
```

What's the error message specified by the browser?

**Comment by StokeMasterJack** [comment]
I wan't asking for help finding my bug (but thanks anyway). I was asking
for how to use Polymer to ensure that a component never enters an invalid
state.

By the way, this is a Chrome-only app and is thus using ES6. in ES6 you
don't need the function keyword.

**Comment by LM450N** [comment]
There is several ways to do "dirty checking". This issue is related to the implementation of your component so I think it should be described on StackOverflow.

Throwing the exception in the `setValue` method could help you to figure out when the value is altered.

_Forgive me for my lack of knowledge about ES6._

**Comment by TimvdLippe** [comment]
This is now possible in Polymer 2 with overriding `_setProperty`: http://jsbin.com/foliqiwaga/edit?html,console,output
