### ISSUE TITLE
feature request: open tracing support

### ISSUE THREAD

**Issue by gedw99** [Polymer/polymer#3978]
http://opentracing.io/integration/

I would like to raise this, and will explain why. Please comment on this idea / feature request.

I build backends in golang and frontends in polymer. 
For golang open tracing is backed into GRPC, and so i get it for free.
For the Frontend there is an offical js lib:
https://github.com/opentracing/opentracing-javascript

wrapping as a Polymer Behaviour would be awesome because then as a developer i can trace backend and frontend from anywhere. I have not tested it but even source labs manual tests could be traced i believe.

**Comment by timeu** [comment]
The JS lib for opentracing is for node.js backends. 
I don't really think that it works in the browser context and even if it does, it does not really belong into the Polymer core library. 
There should be rather a 3rd party web-component  that exposes it as a behavior.

**Comment by gedw99** [comment]
Well Google are using it with grpc so much that I think it's a good idea
for Google to make the polymer web component.

iMHO

**Comment by TimvdLippe** [comment]
Closing per https://github.com/Polymer/polymer/issues/3978#issuecomment-248897492 This will not be integrated in the Polymer core library.
