### ISSUE TITLE
Allow setting `attachShadow` options when creating an element

### ISSUE THREAD

**Issue by valdrinkoshi** [Polymer/polymer#3988]
Element authors should be able to configure the options passed to `attachShadow` (e.g. `mode: 'open'` or `delegatesFocus: true`)

**Comment by valdrinkoshi** [comment]
Maybe a new field in the static config? e.g.
```javascript
// 2.x way, with classes
class MyElement extends Polymer.Element {
  static get is() {
    return 'my-element';
  }

  static get config() {
    return {
      shadowOptions: {
        mode: 'open',
        delegatesFocus: true
      }
    };
  }
}

// The 1.x way
Polymer({
  is: 'my-element',
  shadowOptions: {
    mode: 'open',
    delegatesFocus: true
  }
});
```

@sorvell @kevinpschaaf WDYT?

**Comment by kevinpschaaf** [comment]
For now `Polymer.Element` has an `_attachDom` API meant to be overridden to attach DOM to the element in a non-default way, so you can do this:

```js
_attachDom(dom) {
  if (!this.shadowRoot) {
    this.attachShadow({mode: 'open', delegatesFocus: true});
    this.shadowRoot.appendChild(dom);
  }
  return this.shadowRoot;
}
```

I'd recommend doing that for now; I'm inclined not to add more declarative API, but we can discuss.

**Comment by valdrinkoshi** [comment]
Yeah I think overriding it is more than enough 👌 
nit: this should be safer
```js
_attachDom(dom) {
  // Create shadowRoot only when there is content to be added
  if (dom && this.attachShadow && !this.shadowRoot) {
    this.attachShadow({ mode: 'open', delegatesFocus: true });
  }
  super._attachDom(dom);
}
```

**Comment by MartinsThiago** [comment]
I definitely agree, overriding is the way to go o/

**Comment by MartinsThiago** [comment]
But, I suggest renaming `_attachDom` -> `attachDom` once it's a method "meant" to be overriden

**Comment by sorvell** [comment]
Yup, overriding is the way to go here. We're going to leave the method name as-is (`_attachDom`) since a single underscore is, by our Polymer convention, a "protected" method that can be called by subclassers but should not be called by users of the element.
