### ISSUE TITLE
`:root` and `:host > *` should produce same styling

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#3991]
In Polymer 2.x `:root` has been replaced inside elements with `:host > *`. This is an indication to the custom property shim that any custom properties used in that selector should apply anywhere in the host. Polymer should make this work in 1.x to ease forward compatibility with 2.x. There are a few issues with the current behavior:

* Under ShadowDOM, there is an exception when using `:host > *` (http://jsbin.com/gafare/edit?html,output).

* Under ShadowDOM, `:root` is not converted to `:host > *` (http://jsbin.com/yiwevak/edit?html,output)

* Under ShadyDOM, `:root` is converted to `.my-element-0 .my-element:root`which does not match (http://jsbin.com/vivitec/edit?html,output).

**Comment by azakus** [comment]
The third bullet is just a product of the second bullet.
