### ISSUE TITLE
Feature request: Apply ES6 Class in behaviors

### ISSUE THREAD

**Issue by adaliszk** [Polymer/polymer#3993]
Currently I can make Polymer element with ES6 class like 

```
class MyElement {
    beforeRegister() {
        this.is = 'my-element';
    }
}

Polymer( MyElement );
```

but for for behavior I must save and instance from my behavior class to be applied as a behavior:

```
class MyCustomBehavior {
    get properties() {
        return { something: String };
    }
    attached() {
        console.debug('Element Attached to the DOM!');
    }
}
var MyBehavior = new MyCustomBehavior();

class MyElement {
    get behaviors() { return [MyBehavior]; }
    beforeRegister() {
        this.is = 'my-element';
    }
}
```

I know that 2.0 is will be out soon, but can you add a little code to the 1.6.x so the behaviors could accept a class as it's item and polymer do the rest? 😇
### Versions
- Polymer: v1.6.1
- Webcomponents: v0.7.22

**Comment by TimvdLippe** [comment]
Behaviors are supported in Polymer 2 with https://www.polymer-project.org/2.0/docs/api/#function-Polymer.mixinBehaviors which does not require a concrete instance (just an object). Therefore I think we can close this issue as it has been addressed since.
