### ISSUE TITLE
Feature request (2.0): make template getter accept string ( inline templates )

### ISSUE THREAD

**Issue by Hotell** [Polymer/polymer#3994]
#### Steps to Reproduce

Currently when using module bundlers like webpack, I would like to write component template inline ( like in other frameworks Angular/React ).
In polymer 2.0, this is possible but forces to create unnecessary boilerplate. Instead it should be allowed/handled by Polymer itself.

This is also useful if user wants to have external template in separate `*.html` file and import it directly to the class via webpack loader.
#### Expected Results

``` typescript
export class MyButton extends Polymer.Element {

  static get is() { return 'my-button' }

  static get template() {
   return `<template>
        <button><slot>Hello button!</slot></button>
    </template>`;
  }
}
```
#### Actual Results

``` typescript
export class MyButton extends Polymer.Element {

  static get is() { return 'my-button' }

  static get template() {
    const template = document.createElement( 'template' );
    const content = `
        <button><slot>Hello button!</slot></button>
    `;
    template.innerHTML = content;
    return template;
  }
}
```
### Versions

- Polymer: v2.0.0-preview
- webcomponents: v1

**Comment by sorvell** [comment]
Added via https://github.com/Polymer/polymer/pull/4332.
