### ISSUE TITLE
computed binding function is passed with an old dependency

### ISSUE THREAD

**Issue by frankiefu** [Polymer/polymer#3998]
- checkout shop 2.0-preview branch:
`git clone git@github.com:Polymer/shop.git; cd shop; git checkout 2.0-preview; git pull; bower install;`
- run the app
- click on Men's Outerwear tab; it should show the correct list of items
- click on Ladies Outerwear tab; it should again show the correct list of items
- now click on Men's Outerwear tab again; the items are still showing Ladies Outerwears.

If you put a breakpoint at shop-list.html#L161, you can see `items` is referring the old value.

**Comment by kevinpschaaf** [comment]
@johnlim Likely a different issue; could you make a reduced jsBin repro and open a separate issue? Thanks.

**Comment by johnlim** [comment]
@kevinpschaaf Upon further investigation, it seems to be a problem between keyboard and chair. Sorry for the false alarm.

**Comment by kevinpschaaf** [comment]
Resolved via #4057
