### ISSUE TITLE
`getEffectiveChildNodes` doesn't look into a node's ShadowRoot, only its light DOM content

### ISSUE THREAD

**Issue by bicknellr** [Polymer/polymer#4000]
### Description
`getEffectiveChildNodes` should return the 'children' of an element in the composed tree but it doesn't expand the content of the node's ShadowRoot, if any.

For example, given this DOM setup:
```html
<test-element>
  <!-- shadow -->
    <test-element id="inner">
      <!-- shadow -->
        <div id="A"></div>
        <slot></slot>
      <!-- /shadow -->
      <div id="B"></div>
      <slot></slot>
    </test-element>
  <!-- /shadow -->
  <div id="C"></div>
</test-element>
```
`#inner.getEffectiveChildNodes()` returns [`#B`, `#C`] rather than the expected  [`#A`, `#B`, `#C`].
#### Live Demo
https://jsbin.com/yaduwu/1/edit?html,output

#### Expected Results
The elements returned from `getEffectiveChildNodes` in the above example should be [`#A`, `#B`, `#C`].

#### Actual Results
The elements returned from `getEffectiveChildNodes` in the above example are [`#B`, `#C`].

### Browsers Affected
All

### Versions
- Polymer: 2.0-preview branch
- webcomponents: v1 branch

**Comment by arthurevans** [comment]
I don't think that's what it's supposed to do. It's supposed to give you the light DOM children, with any `<slot>` elements replaced by their assigned nodes.

https://www.polymer-project.org/1.0/docs/devguide/local-dom#effective-children

**Comment by bicknellr** [comment]
Huh, yeah, thanks for pointing that out!
