### ISSUE TITLE
Gestures reset when element upgrades 

### ISSUE THREAD

**Issue by tgsergeant** [Polymer/polymer#4002]
### Description

When I lazily upgrade an element (by not importing the html file until it is needed), gesture listeners added to the element before it is upgraded are reset and stop working.
#### Live Demo

https://jsbin.com/bigipakohi/edit?html,console,output
#### Steps to Reproduce
1. Open JSbin link
2. Click the 'Click me!' button, and observe that 'tap' is recorded to the console.
3. Click 'Load paper-icon-button-light' and wait for the button to upgrade into a paper-icon-button-light
4. Click the 'Click me!' button again
#### Expected Results

'tap' should still be logged to the console.
#### Actual Results

'tap' is not logged to the console.

Using the 'inspect gestures' button, you can see that the `click` gesture handle disappeared from the button when it was upgraded.

Having inspected the code, I believe the root cause is [this line](https://github.com/Polymer/polymer/blob/80640c81ed66e320b96c51c7729b8a0792ce95ad/src/standard/gestures.html#L707), which resets the gesture state during element setup. The bug would probably be fixed by either removing that line, or adding a guard to it:

``` javascript
if (!this.__polymerGestures)
  this.__polymerGestures = null;
```
### Browsers Affected

Reproduces in:
- Chrome
- Firefox

Untested:
- Edge
- Safari 9
- Safari 8
- IE 11
### Versions

- Polymer: v1.6.1

**Comment by tgsergeant** [comment]
I should mention that there's an easy workaround for this specific case: use `on-click` instead of `on-tap`. There are probably other cases which are less easy to work around.

**Comment by danbeam** [comment]
@tjsavage

**Comment by tjsavage** [comment]
@azakus is this intended behavior?

**Comment by TimvdLippe** [comment]
This appears to be fixed, as I am unable to reproduce this problem with the latest version of Polymer in the supplied JSBin.
