### ISSUE TITLE
2.0 - properly expose #ensureAttribute method on Polymer.Element

### ISSUE THREAD

**Issue by Hotell** [Polymer/polymer#4003]
### Description

In 2.0-preview `ensureAttribute` method is mentioned to be used instead of 1.x `hostAttributes`.

Problem is that it's  exposed only as *private* via `_ensureAttribute`

#### Expected Results

```typescript
export class MyButton extends Polymer.Element {

  static get is() { return 'my-button' }

  ready(){
    // Polymer bug! in docs it's stated that ensureAttribute exist but it doesn't
    this.ensureAttribute( 'type', 'button' );
    this.ensureAttribute( 'role', 'button' );
    this.ensureAttribute( 'tabindex', 0 );
    super.ready();
  }
}
```

#### Actual Results

```typescript
export class MyButton extends Polymer.Element {

  static get is() { return 'my-button' }

  ready(){
    // Polymer bug! in docs it's stated that ensureAttribute exist but it doesn't
    this._ensureAttribute( 'type', 'button' );
    this._ensureAttribute( 'role', 'button' );
    this._ensureAttribute( 'tabindex', 0 );
    super.ready();
  }
}
```

### Versions

- Polymer: v2.0.0-preview
- webcomponents: v1

**Comment by kevinpschaaf** [comment]
This was just a mistake in the slide; updated here: https://github.com/Polymer/polymer/commit/426f2346bfe5b93df38e86b8d58902fb09cd9c8d

We are following a convention in the 2.0 source where `_`-prefixed API's are _protected_ (intended for calling or overriding by subclassers of `Polymer.Element`), and `_ensureAttribute` falls into this category.
