### ISSUE TITLE
Style inside a custom template element is copied into parent element's style.

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/polymer#4005]
### Description

Style inside a custom template element is copied into parent element's style.
#### Live Demo

http://jsbin.com/sofumij/edit?html,output
#### Steps to Reproduce

examine the output - style is copied irrespective of value of dark property.

**Comment by davidmaxwaterman** [comment]
So, this is when I have a `<template is="dom-if">` inside a polymer element's template and *that* contains a `<style>` element. When Polymer processes the polymer element's template, it copies all the `<style>` elements into the parent element's style element, including the `dom-if` one - that's obviously not "what the user wanted".
I found that, by restricting the selector to `template:not([is])` (it is currently simply `template` in addition to a couple of other selectors), it prevented this behaviour and my app worked as intended. There seemed to be no side effects, but I could understand that you guys might know better if there's a better way and/or if it is a bad idea in general.

**Comment by sorvell** [comment]
Due to the issues with polyfilling style scoping, styles inside a `dom-if` or any nested template are not supported. Styles should be placed at the top level of the element template. If you need more dynamism, we recommend using css selectors.

**Comment by davidmaxwaterman** [comment]
Could you add this decision to Polymer lint and the docs? Thanks.
