### ISSUE TITLE
Paper-button still is highlighted if tabbing out of focus while rippling very quickly.

### ISSUE THREAD

**Issue by sammiequon71** [Polymer/polymer#4008]
### Description
When pressing space bar to activate a button, trying to tab to another button quickly causes the first button to remain highlighted.

#### Live Demo
https://jsbin.com/kelosizida/edit?html,output

#### Expected Results
The first button should not be highlighted if tabbed out quickly.

#### Actual Results
The first button is highlighted if tabbed out quickly.

### Browsers Affected

- [ x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v1.0
- webcomponents: vX.X.X

**Comment by kevinpschaaf** [comment]
This issue was moved to PolymerElements/paper-button#135

**Comment by kevinpschaaf** [comment]
Moved this issue to the `paper-button` issue tracker.
