### ISSUE TITLE
`getComputedStyleValue` returns the empty string during attached

### ISSUE THREAD

**Issue by bicknellr** [Polymer/polymer#4009]
### Description

Here's a list because I couldn't figure out how to write this as prose without it getting too confusing...

Conditions:
- ShadyDOM shim is not being used.
  - Chrome Canary + `--enable-blink-features=CustomElementsV1`
- A `<test-element>` is in the _root_ document.
- The definition of `<test-element>` is as a legacy element in an _imported_ document.
- The template for `<test-element>` contains this CSS:

``` css
:host {
  --test-prop-with-default: var(--test-prop, 123px);
}
```
- The element is being upgraded.
- The `attached` callback is being called during the upgrade.
#### Expected:
- Calling `this.getComputedStyleValue('--test-prop-with-default');` returns `'123px'`.
#### Actual:
- Calling `this.getComputedStyleValue('--test-prop-with-default');` returns the empty string.
#### Live Demo

https://bicknellr.github.io/polymer-scratch-space/20160927121704_import-styles/
### Browsers Affected

Chrome Canary
### Versions
- Polymer: 2.0-preview branch (81c55b5)
- webcomponents: v1 branch (9892fbc)
- shadydom: master branch (f4b1ebf)
- shadycss: master branch (c4b58b3)
- custom-elements: master branch (a0f55ec)

**Comment by sorvell** [comment]
I believe this is due to: https://bugs.chromium.org/p/chromium/issues/detail?id=516550.

To read style information safely from `connectedCallback`, you must do so in a `requestAnimationFrame`.

Polymer 1.x deferred `attached` until at least the first frame was ready; however, this introduced other undesirable timing issues. For 2.x the current plan is to force users to measure via `requestAnimationFrame`. It would be useful to know if this will not be satisfying for some reason.

**Comment by bicknellr** [comment]
The reason I bring this up is, in paper-checkbox, I'm checking to see if the property was set outside the component and deciding whether or not to set it programmatically based on that. paper-checkbox needs to set this property manually since there's no way to round in CSS calc. (https://github.com/PolymerElements/paper-checkbox/pull/135)

FWIW, I don't think delaying by rAF would be particularly problematic - just my usual grumbling that the element won't be stable until some arbitrary time after create. That bug looks like a convincing source so I starred it. Seems weird that `display: none;` would have affects outside of just box layout / `getComputedStyle` stuff.

**Comment by sorvell** [comment]
`requestAnimationFrame` can yield before the document is complete. For that reason it might be necessary to check `document.readyState` (at least interactive) and `requestAnimationFrame` again if necessary. Polymer has a `Polymer.AsyncRender.beforeRender` helper that could gain this ability if we decide it's valuable.
