### ISSUE TITLE
Disable CSS default of Polymer

### ISSUE THREAD

**Issue by rokity** [Polymer/polymer#4011]
Hi

I'm working on  page where style it's already done, I need to disable all css of Polymer. There is a way ?
I see ::shadow  but it doesn't work.
Someone have an idea?

Thanks

**Comment by LM450N** [comment]
This is a question for [StackOverflow](https://stackoverflow.com/questions/22971335/disable-default-polymer-css).

**Comment by TimvdLippe** [comment]
Please follow the guidelines for creating issues at https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs
