### ISSUE TITLE
Polymer2 dom-repeat listener functions

### ISSUE THREAD

**Issue by e111077** [Polymer/polymer#4016]
### Description
When attaching an `on-tap` handler inside of an element within a `dom-repeat` in polymer 2, the handler is not called.

#### Live Demo
http://jsbin.com/dadelafuma/1/edit?html,output

#### Steps to Reproduce
1. Add a function to an `on-<event>` attribute inside a dom-repeat
2. Try your best to trigger that event

#### Expected Results
event handler should be called

#### Actual Results
event handler is not called

### Versions
- Polymer: v2

**Comment by kevinpschaaf** [comment]
Fixed by https://github.com/Polymer/polymer/pull/4063.
