### ISSUE TITLE
It's technically possible to implement Webpack HMR for Polymer components?

### ISSUE THREAD

**Issue by YingshanDeng** [Polymer/polymer#4018]
Would it be technically possible to implement a loader for Webpack that takes advantage of HMR to use with Polymer ? Thank you!  What I found in stackoverflow: http://stackoverflow.com/questions/36685968/its-technically-possible-to-implement-webpack-hmr-for-polymer-components?answertab=votes#tab-top

**Comment by aruntk** [comment]
I've built a package to handle polymer/webcomponents files and html imports (with HMR support)

https://github.com/aruntk/wc-loader. check out.

Demo https://github.com/aruntk/polymer-webpack-demo

**Comment by sorvell** [comment]
Great contribution, thanks!
