### ISSUE TITLE
Polymer.dom(element).innerHTML setter exceptioning

### ISSUE THREAD

**Issue by e111077** [Polymer/polymer#4021]
### Description
In Polymer2, when setting the innerHTML of an element using the Polymer.dom API, it throws an exception pointing to the setter function in the `forwardProperties` function in `polymer.dom.html`

#### Live Demo
https://jsbin.com/borumacuhu/1/edit?html,console,output

#### Steps to Reproduce
1. Select an element and save it to a variable, `a`
2. Call `Polymer.dom(a).innerHTML = 'asdasdfjaslk;djfa'`

#### Expected Results
It should change the innerhtml
#### Actual Results
throws an error

### Versions

- Polymer: v2

**Comment by frankiefu** [comment]
See the same issue, seems related to this commit: https://github.com/Polymer/polymer/commit/79dcd2f88a3c71e128a9a49e3174379c89de95e3#commitcomment-19245432

**Comment by jfrazzano** [comment]
Beat me to the punch, as always, Framkie. 

Issues I think also relate to an implimentation on spe. Of template strings 

I saw it in a handler attempt to hit inner HTML out of scope of the template replace mrs

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/polymer/pull/4030.
