### ISSUE TITLE
:host[attributeName] css selector not working with "dom: 'shadow'" setting

### ISSUE THREAD

**Issue by elonmallin** [Polymer/polymer#4029]
When using the shadow dom and not the shady polyfill, the selector `:host[attributeName]` is not working.

## Example
```
window.Polymer = { lazyRegister: true, dom: 'shadow' }; // dom: 'shady' is working
```
```
// Some custom element
:host[opened] {
  background-color: red;
}
...
properties: {
  opened: {
    type: Boolean,
    reflectToAttribute: true
  }
}
```

Expecting the background color to be red when this element is `opened` but this doesn't happen.

### Browsers Affected
- [x] Chrome (only browser tested)

### Versions
- Polymer: 1.7.0

**Comment by web-padawan** [comment]
Try using `:host([opened])` instead.

**Comment by elonmallin** [comment]
Yea, that works. Any idea why? Didn't find any docs about it.

**Comment by web-padawan** [comment]
See [this article](https://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/) describing `v0` spec.

**Comment by elonmallin** [comment]
Oh I see, thanks. Thought it was some polymer reason but then it's not ok. Closing.
