### ISSUE TITLE
paper fab not rendering icon when iron-icons is imported by parent and child

### ISSUE THREAD

**Issue by jordyvandomselaar** [Polymer/polymer#4031]
### Description

I'm using polymer starter kit, inside `my-app` there's `<app-toolbar>`. Inside that toolbar I've added `<paper-fab icon="add"></paper-fab>`. To make `paper-fab` render correctly I've added an import to the icons: `<link rel="import" href="../bower_components/iron-icons/iron-icons.html">`. Inside `my-app` I have a view: `<home-view name="home" on-navigate="navigate_by_event"></home-view>` with more `paper-fab`s: `<paper-fab icon="arrow-forward" mini class="questionlist-go"
                                       target$="/questionlist/show/[[item.id]]"
                                       on-tap="navigateToQuestionlist"></paper-fab>`. When `iron-icons` is imported by `my-app` they don't render. When they're not imported in `my-app` they do.
#### Steps to Reproduce
1. Create new starter kit project
2. Add sub-element to `my-app`
3. Import `iron-icons` in both
4. Add `paper-fabs` to both
#### Expected Results

Lovely paper-fabs
#### Actual Results

blank paper-fabs, circle with no icon
### Browsers Affected

- [x ] Chrome
- [x ] Firefox
### Versions

- Polymer: v1.6.1
- webcomponents: v0.7.22

**Comment by TimvdLippe** [comment]
Please follow the guidelines for creating issues at https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs
