### ISSUE TITLE
Fowarding a click event in iOS Safari

### ISSUE THREAD

**Issue by Westbrook** [Polymer/polymer#4032]
When you are attempting to trigger a 'click' event via `elm.click()` in response to clicking another element or a track event to an `<a href="#"/>` the move from v1.6.1 to v1.7.0 has done something to how long that takes such that iOS Safari will no longer trigger the click event.
#### Live Demo

http://plnkr.co/edit/8FbHPz4H4TNYZnHO8xui?p=preview
#### Steps to Reproduce
1. Listen to a 'click', 'tap', or 'track' event
2. Pass that interaction to an `<a href="#"/>` via `elm.click()`
#### Expected Results
1. The target element's click handler will be triggered (see any other browser)
#### Actual Results
1. The target element's click handler won't be triggered when in iOS Safari
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
- [x] iOS Safari
### Versions
- Polymer: v1.7.0

**Comment by ronnyroeller** [comment]
Same problem here.
This prevents using a styled element like `paper-icon-button` to trigger a hidden `<input type=file>` for file uploads.

**Comment by Westbrook** [comment]
@azakus do have any thoughts on this issue? If there were any where you could point me to help, I'd be happy to. This puts a nice roadblock between my team and actively being able to plan for moving our components to hybrid versions of themselves in advance of the 2.0 conversion.

**Comment by sedestrian** [comment]
Same here, any solutions yet?

**Comment by Westbrook** [comment]
With some help of the Slack channel I've been informed that the following might be a good solutions for the `<input type=file>` version of this issue: http://plnkr.co/edit/bWJiz8vuLVzTFd56ZMgF?p=preview However, in that `var evt = new MouseEvent("click");` creates an un-cancelable event I am unable to use it in the case that I'd like feed the reality around clicking the `<a/>` into my SPA as opposed to a full page load.

**Comment by marxtseng** [comment]
@Westbrook change <a/> href to "javascript:;" is work
<a id="target" href="#" on-tap="_goalClick>Then Me</a>
<a id="target" href="javascript:;" on-tap="_goalClick">Then Me</a>

**Comment by azakus** [comment]
This is probably the same issue as #4128, I'll confirm.

**Comment by azakus** [comment]
Confirmed fixed in master with #4128

**Comment by Westbrook** [comment]
@azakus do you know if there are any plans around cutting a 1.7.1 so that fixes like this don't block preparations for hybrid elements, etc?
