### ISSUE TITLE
`setScrollDirection` doesn't map values before passing to `setTouchAction`

### ISSUE THREAD

**Issue by bicknellr** [Polymer/polymer#4033]
### Description

`setScrollDirection` previously accepted only 'x', 'y', 'none', and 'auto' and mapped these before passing them to `setTouchAction`. The work-around is to call `Polymer.Gestures.setTouchAction` yourself with the real value.

Here's the old map:
https://github.com/Polymer/polymer/blob/80640c81ed66e320b96c51c7729b8a0792ce95ad/src/standard/gestures.html#L697
### Versions
- Polymer: 2.0-preview branch

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/polymer/pull/4347.
