### ISSUE TITLE
Polymer.dom().querySelectorAll() should return an Array

### ISSUE THREAD

**Issue by valdrinkoshi** [Polymer/polymer#4039]
`Polymer.dom().querySelectorAll()` should return an `Array` instance in order to be compatible with 1.x. Currently, 2.x returns a `NodeList` instance when used with native shadow dom

**Comment by TimvdLippe** [comment]
This is a documented breaking change:

> Hybrid elements need to keep using the Polymer.dom API. However, note that in 2.0, for native methods and properties that return a NodeList, Polymer.dom APIs also return NodeList, not Array. If you're using any native Array methods on the returned object, you need to update your code.

https://www.polymer-project.org/2.0/docs/upgrade#polymer-dom-apis
