### ISSUE TITLE
Binding doesn't work with javascript variables

### ISSUE THREAD

**Issue by AlexAlabyev** [Polymer/polymer#4040]
### Description
I'm a newbie in web dev and I'm sorry if I'm doing an obvious mistake here, but for some reason the calculated values in javascript don't change default values in `properties: { }` and aren't getting sent into `<p>` tags.
```

<dom-module id="my-view1">
<template>
   ...  

  <div>                      
      <p id="views" style="display:inline; ">100/Amount of views: [[ytr]]</p>
      <p id="youtubeRequest" style="display:inline">Amount of views: [[ytr3]]</p>
  </div>
  ... 
</template>

 <script>
   Polymer({
     is: 'my-view1',
    properties: {
        ytr: {
            type: Number,
            value: 0
        },
        ytr3: {
            type: Number,
            value: 0
        }
    },
     ready: function()
     {
       function getViews(params) {
         $.ajax({
           url: "https://www.googleapis.com/youtube/v3/channels?part=statistics&key=MyAPIkeyHere",
           jsonp: "callback",
           dataType: "jsonp",
           success: function(response) {
             this.ytr = response.items[0].statistics.viewCount;
             var ytr2  = 100 / ytr;
             this.ytr3 = ytr2.toPrecision(1);
             },
         });
       }
       getViews()
    }
 </script>
</dom-module>

```

## **Outcome**

It just sends default values  (0 and 0) to the `<p>` tags instead of binding the calculated values.

**Comment by web-padawan** [comment]
You are just loosing `this`. Use `bind(this)` or `var self = this;` before `getViews` fu nction definition.
BTW using jQuery is not a Polymer way. Have a look at `iron-jsonp-library` instead.

**Comment by AlexAlabyev** [comment]
@web-padawan thank you for the answer Sergey. It works now. I'm building my app alone and the only help is google and people like you so thank you so much, you are awesome!
