### ISSUE TITLE
Allow passing data into <content>

### ISSUE THREAD

**Issue by slawomir-brzezinski-at-interxion** [Polymer/polymer#4042]
Or simply offer a feature to render content in the context of the hosting web component - similar to Ractive's [{{>content}}](http://docs.ractivejs.org/latest/components#content) statement (besides the [{{yield}}](http://docs.ractivejs.org/latest/components#yield) keyword, which is equivalent of current polymer behavior).

This would make it easy to create own components that, just like the [`dom-repeat`](https://github.com/Polymer/polymer/blob/master/src/lib/template/dom-repeat.html), can introduce variables into scope, e.g. be able to easily implement https://github.com/PolymerElements/iron-list/issues/139.

Or, it would be easy to cover scenarios where the Web component also offers some data for consumption by the user, e.g.:

**`my-component`:**

```
<script>
    Polymer(
        properties: { somePropOfComponent: Object }
    )
</script>
<template>
  <content some-attribute-to-pass-host-data-context></content>
</template>
```

**usage:**

```
<my-component>
  {{somePropOfComponent}}
</my-component>
```

The workarounds that require users to rewrite HTML contents (e.g. [here](http://stackoverflow.com/questions/26369519/bind-data-to-content-element-in-polymer)) are pretty ugly and get dangerously close to XSS injection.

**Comment by dnesteryuk** [comment]
This behavior is achievable with the current Polymer implementation which supplies the [Polymer.Templatizer behavior](https://www.polymer-project.org/1.0/docs/api/Polymer.Templatizer):

```html
<dom-module id="page-er">
  <template>
    <content></content>
  </template>
  <script>
    Polymer({
      is: 'page-er',

     // properties and methods

      ready: function () {
        var template = this.queryEffectiveChildren('template');
        this.dataHost = this;
        this.templatize(template);
        this.instance = this.stamp();
        Polymer.dom(this).appendChild(this.instance.root);
     }
  });
  </script>
</dom-module>
```

and you use it like this:

```html
<page-er perpage="5" currentpage="0">
  <template>
    <template is="dom-repeat" items="[[currentRange]]" as="n">
      <button data-item$="[[n]]" on-click="setPage">[[computePageNum(n)]]</button>
    </template>
  </template>
</page-er>
```

Even the event handlers work. The complete working example can be [found here](https://github.com/dnesteryuk/page-er/blob/chore/upgrade-dependencies/demo/custom.html#L23-L43) and [here](https://github.com/dnesteryuk/page-er/blob/chore/upgrade-dependencies/page-er.html#L404-L424) is the element.

### Is it a good approach? 

It might be since it uses the api of Polymer, but I may be wrong here :blush: The core team will correct me.

**Comment by slawomir-brzezinski-at-interxion** [comment]
@dnesteryuk thanks a lot for pointing at it. I will give it a try.

I would still suggest Polymer team to consider making this a bit easier, i.e. not requiring the extra `<template>` and perhaps just be able to have a special attribute on `<content>` like in the proposed solution, to stay the preferred option over any other frameworks (not to have to sacrifice simplicity to use it).

**Comment by TimvdLippe** [comment]
Closing this as `<content>` has been removed. With regard to `<slot>`, check out https://github.com/Polymer/polymer/issues/5101#issuecomment-364070335
