### ISSUE TITLE
importHref missing from Polymer.Element

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#4045]
This isn't listed as one of the "removed APIs".

Is this one of the "sugared utility APIs" described in the README? It seems like a non-trivial amount of code to do it right, and we use it heavily.

**Comment by arthurevans** [comment]
In particular, currently used for PRPL pattern, so Shop, PSK, etc.

**Comment by arthurevans** [comment]
Per discussions: `importHref` isn't instance-related, and the core team is trying to remove non-instance related methods from the instance and make them available some other way.

Where this ends up (and whether it comes with `polymer-element.html` by default or is loaded as part of a separate import) is TBD. For the time being, you can do this:

```
<!-- load full polymer import, not polymer-element -->
<link rel="import" href="/path/to/polymer/polymer.html">

 ...
Polymer.Base.importHref(url, onLoad, onError, async);
```

Since it's not an instance method, the onLoad and onError callbacks need to be bound to `this` to be equivalent to the instance method. However, in ES6 this can be as simple as:

```
Polymer.Base.importHref('/foo/bar', ()=>this.onLoad(), ()=>this.onError(), true);
```

cc: @sorvell to see if I got that all right.

**Comment by sorvell** [comment]
We're inclined to move this to `Polymer.Utils.importHref`. We'll continue to keep the existing instance method in `Polymer.LegacyElement` (aka what you get when call Polymer({...}).

**Comment by kevinpschaaf** [comment]
Resolved via https://github.com/Polymer/polymer/pull/4091
