### ISSUE TITLE
getDistributedNodes() returns textNodes

### ISSUE THREAD

**Issue by valdrinkoshi** [Polymer/polymer#4047]
In 1.x, `Polymer.dom(this.$.content).getDistributedNodes()` returns only Elements (skipping the textNodes).
In 2.x `getDistributedNodes` (or `getEffectiveChildren`) would return also the textNodes.
To support dual mode, elements would have to change

``` js
get contentElement() {
  return Polymer.dom(this.$.content).getDistributedNodes()[0];
}
```

to something like this:

``` js
get contentElement() {
  var nodes = Polymer.dom(this.$.content).getEffectiveChildNodes();
  for (var i = 0; i < nodes.length; i++) {
    if (nodes[i].nodeType === Node.ELEMENT_NODE) {
      return nodes[i];
    }
  }
}
```

Which is too verbose :/

Do you plan to keep the 1.x behavior (filter out text nodes)?

**Comment by arthurevans** [comment]
Per spec, `getDistributedNodes` should return text nodes. If you're using 1.7, think you're seeing something else here.

Namely, we're converting a plain `<slot>` to `<content select=":not([slot])">` to match the v1 behavior, but that means that a `<slot>` in 1.7 will never get text nodes.

If you convert it back to a `<content>` element, you'll see it does include text nodes.

See here:

https://jsbin.com/lomeheb/2/edit?html,output

**Comment by e111077** [comment]
Ping on this. This is causing issues with compatibility where you have to support both 2.x and 1.x. This seems to be the best workaround I can think of to at least display the text nodes.

```html
<dom-module id="projected-workaround">
  <template>
    <slot></slot>
    <content></content>
    <script>...</script>
  </template>
</dom-module>
```

This works in 2.x just fine, but in 1.7 consider the following:
```html
<projected-workaround><span>123</span>456<span>789</span></projected-workaround>
```

in 2.x it spits out `123456789`. In 1.7 it splits them into `123789456`.

**Comment by valdrinkoshi** [comment]
@e111077 nit: you don't need <content> in 1.7 & the script should be outside the template

**Comment by e111077** [comment]
talk with Valdrin offline we came up with a workaround that works. I just had to switch the content and the slot order.

```html
<dom-module id="projected-workaround">
  <template>
    <content></content>
    <slot></slot>
  </template>
  <script>...</script>
</dom-module>
```

**Comment by keanulee** [comment]
In light of this, I think we should make `<slot>` -> `<content>` (with no selector) in Polymer 1.7.0. Including light DOM elements with `[slot=*]` would be a difference from Shadow DOM v1, but missing text nodes seems like a bigger issue.

cc @sorvell @frankiefu

**Comment by frankiefu** [comment]
@keanulee I think this is fixed in master: https://github.com/Polymer/polymer/commit/87e312f1d72366f35028d742acd028929106501f
