### ISSUE TITLE
Multilevel slot distribution doesn't work correctly in 1.7.0

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#4050]
### Description

When you have two levels of slots, and the lower-most slot has a `name`, the contents don't render correctly.
#### Live Demo

In 1.7:

http://jsbin.com/cacedey/3/edit?html,console,output

In 2.0
http://jsbin.com/qitoti/6/edit?html,output
#### Steps to Reproduce

In both of these cases, the light DOM content should appear and be colored red.
In 1.7, the two-level (distributed) nodes don't appear at all, but the one-level (assigned) nodes
appear correctly.

```
  <my-element><span>Light DOM content, redistributed.</span></my-element>
  <my-child><span slot="child-slot">Light DOM content, assigned.</my-child>

  <dom-module id="my-child">
    <template>
      <style>
        #container ::slotted(*) {
          color: red;
        }
      </style>
      <div>Hello I am my-child, and here's my distributed stuff:</div>
      <div id="container"><slot name="child-slot"></slot></container>
    </template>
  </dom-module>

  <dom-module id="my-element">
    <template>
      <my-child>
        <slot slot="child-slot">Fallback content</slot>
      </my-child>
    </template>
   </dom-module>
```

(Note: we see the same error if the parent slot is named as well, which is shown in the jsbins above.)
#### Expected Results

Both elements show their light DOM content.
#### Actual Results

my-element does _not_ show its light DOM content.
### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Safari 9

Not tested:
- [ ] Edge
- [ ] Safari 8
- [ ] IE 11
### Versions
- Polymer: v1.7.0
- webcomponents: (latest stable off of polygit)

**Comment by arthurevans** [comment]
Not sure if we can make this work right, but if not, we need to note it as a limitation and provide workarounds for hybrid elements.

**Comment by sorvell** [comment]
I believe this will just be a limitation for hybrid elements that's due to the differences between the distribution mechanisms between v0 and v1 Shadow DOM. All slots in the distribution tree can share the same slot/name or be catchall but there's no easy way to re-route the content.
