### ISSUE TITLE
Running polymer init results in an error

### ISSUE THREAD

**Issue by Gespinha** [Polymer/polymer#4052]
Hi there,

After installing `polymer-cli` and atempting to call `polymer init`, the following error is displayed:

```
$ polymer init
/usr/local/lib/node_modules/polymer-cli/bin/polymer.js:16
const resolve = require('resolve');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I have `polymer-cli` installed as a global package. Initially I thought I could have something wrong in my package folder. So I uninstalled all my npm modules and cleaned my npm cache, but nothing changed and I keep getting the same error.

Is this a known issue? Can anyone help me making polymer work?

**Comment by web-padawan** [comment]
Seems that you have node v 0.12 or older. If so, please install LTS (6.x) node.

**Comment by Gespinha** [comment]
@web-padawan I've managed to reconfigure homebrew's links to fix that issue, so I am now using node 6.7.0, but it now returns the following:

```
polymer init
-bash: polymer: command not found
```

Any clues on what is going wrong?

**Comment by web-padawan** [comment]
Now you need to run `npm i -g polymer-cli` again. Changing node version usually requires this for globally installed packages (because npm itself has been reinstalled).

**Comment by Gespinha** [comment]
@web-padawan Did that an it still doesn't work. Returns the same erro: `polymer: command not found`

**Comment by kevinpschaaf** [comment]
This issue was moved to Polymer/polymer-cli#437
