### ISSUE TITLE
Deep property change from undefined to null is not propagated

### ISSUE THREAD

**Issue by fejesjoco** [Polymer/polymer#4053]
Repro: http://jsbin.com/xatiqibofu/edit?html,output

The code changes a deep property and displays the object. Initially the object is empty. When I change the property to "x", the result becomes {property: "x"} which is expected. When I change property to null, it should become {property: null}, but instead it stays empty. The change is not even propagated at all.

I understand how undefined is handled strangely, but this is null which should work like any valid value. So hopefully this is just an oversight, ie. somewhere you're checking "if (oldvalue == newvalue)", and undefined happens to be == to null, but instead it should be ===, which would work. (I see you have a well thought out comparison here: https://github.com/Polymer/polymer/blob/ff6e884ef4f309d41491333860a8bc9c2f178696/src/standard/notify-path.html#L100)

**Comment by TimvdLippe** [comment]
Seems that your issue has been fixed, as the JSBin shows `{"property":null}` now.
