### ISSUE TITLE
[2.x] $= does not work for custom elements that extends template

### ISSUE THREAD

**Issue by tomalec** [Polymer/polymer#4060]
### Description
Binding data through `$=` to the custom element that extends `<template>` crashes entire template binding.

#### Live Demo
https://jsbin.com/javoluduli/1/edit?html,console,output

#### Steps to Reproduce
1. Create `<dom-bind>` with `<template is="my-element" attr$="{{model}}">` inside
2. Append it to document.body
3. Attach some data `domBind.set('model','something')`.

#### Expected Results
```html
<template is="my-element" attr="something">
```
should be stamped.

#### Actual Results
```log
Uncaught InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': 'content$' is not a valid attribute name.
```
 is thrown

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Edge
- ? Safari 9
- ? Safari 8
- [x] IE 11

### Versions
- Polymer: # 2.0-preview @70133aa69753fc375cfb108337e944333b160883
- webcomponents: # v1 @9892fbccde417a7b0cbf9c181e35b56e28d7e808

### Debugging results

It seems that `parseChildNodesAnnotations` at https://github.com/Polymer/polymer/blob/2.0-preview/src/template/annotations.html#L250

Does nothing regarding bindings for template element.

### Proposed fix

https://github.com/Polymer/polymer/pull/4069

**Comment by kevinpschaaf** [comment]
Fixed via https://github.com/Polymer/polymer/pull/4069
