### ISSUE TITLE
[2.x] dom-bind stamps <template is="my-el"> as <my-el>

### ISSUE THREAD

**Issue by tomalec** [Polymer/polymer#4068]
### Description
Template binding fails to stamp template with is attribute.

#### Live Demo
https://jsbin.com/bacoteb/7/edit?html,console,output

#### Steps to Reproduce
```html
  <dom-bind>
    <template>
        <template is="my-template"></template>
    </template>
  </dom-bind>
```

#### Expected Results
`<template>` element should be stamped.
```html
<template is="my-template"></template>
<dom-bind>...</dom-bind>
```

#### Actual Results
`<my-template>` is stamped
`<template>` element should be stamped.
```html
<my-template></my-template>
<dom-bind>...</dom-bind>
```

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- ? Safari 9
- ? Safari 8
- [x] IE 11

### Versions
- Polymer: # 2.0-preview @70133aa69753fc375cfb108337e944333b160883
- webcomponents: # v1 webcomponents/webcomponentsjs@9892fbccde417a7b0cbf9c181e35b56e28d7e808

### Debugging results

`<template>` (w/o is attribute) is stamped correctly, other native elements are also stamped as `<nativeelement is="my-element">`

### Proposed fix

https://github.com/Polymer/polymer/pull/4069

**Comment by kevinpschaaf** [comment]
Fixed via Fixed via https://github.com/Polymer/polymer/pull/4069
