### ISSUE TITLE
_addComplexObserverEffect does not work with default value() 

### ISSUE THREAD

**Issue by pik** [Polymer/polymer#4074]
#### Live Demo
https://github.com/pik/polymer-complex-observer-undefined/blob/master/polymer-complex-observer-undefined.html

#### Steps to Reproduce
`_addComplexObserverEffect` is called for the `observers` array on each polymer element during prep: https://github.com/Polymer/polymer/blob/master/polymer.html#L58

Using `_addComplexObserverEffect` dynamically though leads to some edge-case behaviors, for example `value()` from a property is not correctly set and an undefined change-set is passed through `node._propertySetter`.

I'm not sure why the default `foo: {value() { return 'bar' } }` doesn't translate directly to something like (Since this is not the first bug I have encountered with a property value being undefined when a default `value()` has been supplied. )
```es6
Object.defineProperty(myElement, 'foo', { get() { if (this._foo === undefined) return 'bar' } })
```

### Versions
- Polymer: "1.6.1"

**Comment by kevinpschaaf** [comment]
This API is not documented for public usage, so it's not tested or guaranteed to work for the use cases you described above.  Polymer 1.0 does not have public support for adding instance-time property effects.  We intend to support more of these use cases in the 2.0 release (with documented, tested API's); however, it's unlikely that we will be adding support for new features/use cases like this in the 1.x codebase. 

If you want to dynamically add effects, the only supported way is to meta-program into the `properties` configuration data before registration (per class, not per instance).

> I'm not sure why the default foo: {value() { return 'bar' } } doesn't translate directly to something like

To answer your question though, Polymer uses a "push"-based effect system, where side-effects to properties happen as a result of _setting_ data through the system (as opposed to _reading_ data at some periodicity).  As such, simply having a getter return the default would not cause that default value to have side-effects run; the default value needs to be _set_ into the accessor to trigger the effects. Part of what's missing from the 1.x implementation to support instance-time effects is a contract for when/how dynamically-added effects would have their effects run with the current (or default) value.  And new feature-work like this will mostly be taking place in the 2.x codebase going forward.
