### ISSUE TITLE
Preview Branch still says 1.6.1

### ISSUE THREAD

**Issue by rwatts3** [Polymer/polymer#4077]
Greetings,

The preview branch still says 1.6.1 which makes it a little difficult to determine if the project is truly under 2.0-preview especially when two projects are worked on and one is being migrated following the guides.

https://github.com/Polymer/polymer/blob/2.0-preview/bower.json#L3

**Comment by kevinpschaaf** [comment]
Thanks, we'll fix that up.

**Comment by kevinpschaaf** [comment]
Fixed in https://github.com/Polymer/polymer/commit/db91aa0d70250f1b88b549b00ede5fdaf0ad6e91

**Comment by rwatts3** [comment]
Thank you
