### ISSUE TITLE
Object property changes only observed the first time

### ISSUE THREAD

**Issue by NicolasRannou** [Polymer/polymer#4081]
Setting object properties in a `<child-element>` from a `<parent-element>` is only picked up by the `<child-element>` the first time.
Next time the `<parent-element>` tries to set the property, the `<child-element>` will not get updated.

https://jsbin.com/zayevirere/edit?html,output

which would be the best practice to update the value of the object and ensure polymer picks it up?

**Comment by kevinpschaaf** [comment]
You need to 2-way bind `{{my}}` into `<my-element>` to ensure the host `<my-app>` sees mutations to the shared object that occur in the child element.  The reason the second one fails is that Polymer's dirty checking sees that `'rocks'` is the last known value of `my.deep.value` the host knew about, and so it doesn't re-propagate the change.  By two-way binding, you ensure the host is in sync with mutations that occur below.

Works: https://jsbin.com/cuperok/edit?html,output
