### ISSUE TITLE
iframes not registered on window.frames with shadow dom

### ISSUE THREAD

**Issue by crookedneighbor** [Polymer/polymer#4086]
### Description

When configuring Polymer with 

```js
window.Polymer = {
  dom: 'shadow'
};
```

iframes on the page are not added to `window.frames`. So if an iframe relies on `window.parent.frames` to work, it does not.

I work for [Braintree](https://www.braintreepayments.com/), and our product [Hosted Fields](https://developers.braintreepayments.com/guides/hosted-fields/overview/javascript/v3) uses iframes to enter sensitive credit card data in a PCI compliant manner. The [iframes are initialized by looping through the iframes on the page as referenced by window.parent.frames](https://github.com/braintree/braintree-web/blob/ffc3324662529e4351e926ce846370ca32dc6a99/src/hosted-fields/internal/assemble-iframes.js#L7-L15). Since the shadow dom obscures the iframes, the inputs never initialize.

From what I can tell, having the shadow dom obscure the iframes on the page is working as y'all intend. Does that mean that projects that require access to `window.frames` cannot use the shadow dom? Is there another way to reference frames on the page?

#### Live Demo

I've created a [github page that reports the number of frames on the parent page](https://crookedneighbor.github.io/number-of-parent-frames/). I've used that as an iframe in the following examples.

Without `dom: 'shadow'`, iframes are registered just fine: https://jsbin.com/nugajab/edit?html,output

WIth `dom: 'shadow'`, they are not: https://jsbin.com/qopaku/edit?html,output

### Versions
- Polymer: v1.7.0
- webcomponents: v0.7.22

**Comment by kevinpschaaf** [comment]
First, just a point of order -- this is really a Shadow DOM spec use case/question, as Polymer is a user of Shadow DOM, but not the spec owner.  There was a spec issue https://github.com/w3c/webcomponents/issues/145 that discussed and concluded that `window.frames` would not include `<iframe>`s in shadow roots, but I don't see a direct "scoped" replacement for it having been added to the spec (for example, I might imagine e.g. `shadowRoot.frames` being added as a replacement, but it wasn't).  You might consider opening an issue on that tracker for something like that.

> Does that mean that projects that require access to window.frames cannot use the shadow dom? Is there another way to reference frames on the page?

In general, adding the concept of "scoping and encapsulation" to the web should be seen as a good thing that adds predictability and guarantees when combining code from different authors.  But it does often come at the cost of some "global conveniences" we could previously take advantage of (like being able to easily access any iframe anywhere), in the same way that e.g. encapsulation in Java means code can no longer access every variable in the program -- with similar benefits and loss of shortcuts we could have employed in lesser-encapsulated languages.  This does require rethinking and adapting solutions to fit the new model.

In this particular case, when a shadow DOM host (usually a custom element) is hosting a Braintree iframe that needs to be initialized, it would be reasonable to require the shadow host to invoke a Braintree library function to initialize any iframes in its scope (e.g. `Braintree.initializeHostedFieldsInRoot(this.shadowRoot)`, which could e.g. `querySelector` for potential iframes in the shadow root).  This is consistent with the controlled, "opt-in" model that scoping implies, as opposed to the legacy "any actor may act on anything" sort of wild west that has plagued the web in the past and made it _harder_ to integrate 3rd-party libraries.

I can sympathize with a counter-argument that says "but it was easier when all the user had to do was drop my script on her page and I could find all the iframes", but this is just a fundamental tradeoff that comes with the addition of primitives for scoping.  Going forward I think it will be important for library authors to consider the implications that Shadow DOM scoping implies, and provide alternate/additional library API's for users in those environments.  Does that make sense?

**Comment by kevinpschaaf** [comment]
@crookedneighbor I'll go ahead and close this, assuming this answered your question -- if not just let me know.

Also, I'll just make a plug for [Custom Elements](https://developers.google.com/web/fundamentals/getting-started/primers/customelements) here -- it seems they would be a perfect fit for your "Hosted Fields" product, since custom elements are a new browser primitive that allow defining new HTML tags and provide lifecycle hooks for e.g. initializing private implementation (the iframe) which can be hidden away in the Shadow DOM as an implementation detail, and your API can be exposed as a simple HTML tag with properties/events.  Might consider it for the next version of your SDK. :)

**Comment by crookedneighbor** [comment]
Thanks for your thorough explanation @kevinpschaaf!
