### ISSUE TITLE
Warn on `this.listen` and `this.unlisten` calls if `node` argument does not exist

### ISSUE THREAD

**Issue by azakus** [Polymer/polymer#4089]
Either with the `listeners` block, or imperatively, if the node given to `this.listen` is null, the only error the user sees is `"Uncaught TypeError: Invalid value used as weak map key"`

**Comment by TimvdLippe** [comment]
Seems to be fixed now in Polymer 2: http://jsbin.com/qafuqohacu/edit?html,console,output
