### ISSUE TITLE
i can't install polymer in Window 10

### ISSUE THREAD

**Issue by karangoswami31** [Polymer/polymer#4093]
Help me out i can't install Polymer

D:\>npm install -g polymer-cli
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
C:\Users\karan\AppData\Roaming\npm\polymer -> C:\Users\karan\AppData\Roaming\npm\node_modules\polymer-cli\bin\polymer.js

> sauce-connect-launcher@0.16.0 postinstall C:\Users\karan\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\sauce-connect-launcher
> node scripts/install.js || nodejs scripts/install.js

> wct-sauce@1.8.5 postinstall C:\Users\karan\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\wct-sauce
> node scripts/postinstall.js

Prefetching the Sauce Connect binary.
Missing Sauce Connect local proxy, downloading dependency
This will only happen once.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
 npm WARN install:wct-sauce@1.8.5 wct-sauce@1.8.5 postinstall: `node scripts/postinstall.js`
npm WARN install:wct-sauce@1.8.5 Exit status 1
C:\Users\karan\AppData\Roaming\npm
`-- polymer-cli@0.16.0
  `-- web-component-tester@4.3.5
    `-- test-fixture@1.1.1  (git://github.com/polymerelements/test-fixture.git#05514d6f32ade6fe54de5b242bbb43ea9dcff3c0)

**Comment by karangoswami31** [comment]
D:\3rd>polymer init
'uname' is not recognized as an internal or external command,
operable program or batch file.
? Which starter template would you like to use? shop
info:    Running template shop...
info:    Downloading latest release of Polymer/shop
error:   Could not download release from Polymer/shop
error:   Uncaught exception: unable to verify the first certificate
error:   Error: unable to verify the first certificate
    at __dirname.sendError (C:\Users\karan\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\github\lib\index.js:780:19)
    at C:\Users\karan\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\github\lib\index.js:789:29
    at callCallback (C:\Users\karan\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\github\lib\index.js:665:17)
    at ClientRequest.<anonymous> (C:\Users\karan\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\github\lib\index.js:737:17)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)

**Comment by TimvdLippe** [comment]
Please ask such questions on the Polymer Slack (https://polymer-slack.herokuapp.com/) or on Stackoverflow (http://stackoverflow.com/questions/tagged/polymer).

**Comment by kevinpschaaf** [comment]
This issue was moved to Polymer/polymer-cli#449
