### ISSUE TITLE
Missing event model from templatized instance

### ISSUE THREAD

**Issue by toddradigan** [Polymer/polymer#4095]
### Description
When listening to events (such as on-tap) on templatized instances, the event does not contain the model property (e.model -> TemplateInstance)

#### Live Demo
https://toddradigan.github.io/templatize-testing/

the listener set up in src/list-container/list-container.html correctly captures tap events for all templatized items
```
listeners: {
  'tap': 'tapItem'
},
```

the event fired from "type b" _does_ correctly have the model property (likely because the template already has another on-tap handler)
```
      <template is='dom-template' item='[[item]]' item-type='b'>
        <span on-tap='_do'>[[item.value]]</span>
      </template>
```

the event fired from "type a" does not have the model property bound to the instance
```
      <template is='dom-template' item='[[item]]' item-type='a'>
        <span>[[item.value]]</span>
      </template>
```

#### Steps to Reproduce
1. Create listener for tap events in custom element
2. Templatize and stamp instances of a template
3. Tap any of those instances
4. Observe that event, when handled by the listener you set up, does not have model property

#### Expected Results
event for templatized instance will have model property

#### Actual Results
event for templatized instance only has model property if template already contains handler for that event type

### Browsers Affected
- [x] Chrome
- [?] Firefox
- [?] Edge
- [?] Safari 9
- [?] Safari 8
- [?] IE 11

### Versions
- Polymer: v1.7.0
- webcomponents: v0.7.22

**Comment by kevinpschaaf** [comment]
Model-decorated events are not supported when using event delegation outside the template.  You need to add an event listener inside the template as in your first example to get decorated events.

Alternatively, you can use the event delegation pattern and call `dom-repeat`'s [`modelForElement()`](https://www.polymer-project.org/1.0/docs/api/dom-repeat#method-modelForElement) API on `event.target`, e.g.:

```js
tapItem: function(event) {
  var model = this.$.domRepeat.modelForElement(event.target);
  ...
}

**Comment by toddradigan** [comment]
thanks!
