### ISSUE TITLE
Polymer import causing React component to break

### ISSUE THREAD

**Issue by StokeMasterJack** [Polymer/polymer#4101]
Had the following React code and everything worked perfectly:

```
render() {
        return (
            <div>
                <Select.Async value={this.state.value} onChange={this.onChange}
                              loadOptions={this.getOptions}
                />
            </div>
        );
}
```

`<Select.Async>` is a React component from react-select.

Then I added a web component and suddenly React-select started rendering incorrectly. No text would show up in the input box.

```
render() {
        return (
            <div>
                <link rel="import" href="/components/paper-button/paper-button.html"/>
                <paper-button/>
                <Select.Async value={this.state.value} onChange={this.onChange}
                              loadOptions={this.getOptions}
                />
            </div>
        );
}
```

It took me hours to isolate the problem. I finally figured out that if I moved the link tag out of the React component and into the head section of my html then it works. But, other than React-select, I have been using this technique (import a web component from within a React component) just fine.

Not sure if this is a problem with polymer or with react-select.

I tried to create a plunk but I couldn't get paper-button to load correctly from a CDN.

One other things to note: It didn't really matter which web component I was importing.

**Comment by web-padawan** [comment]
AFAIK calling `render` should just return a markup, and putting HTML import there is not a good idea due to the async import nature. Another thing is that custom elements always must have closing tags.

**Comment by kevinpschaaf** [comment]
Definitely would not recommend using the `<link rel="import">` in React's render; generally `<link>`s should be placed in head or imperatively added e.g. when the React component is loaded, something like:

```js
let link = Object.assign(document.createElement('link'), {
  rel: 'import',
  href: '/components/paper-button/paper-button.html'
});
document.head.appendChild(link);
```
