### ISSUE TITLE
Wrong usage of Polymer.RenderStatus.afterNextRender in the upgrade guide

### ISSUE THREAD

**Issue by Pupix** [Polymer/polymer#4104]
### Description

In the [upgrade guide](https://www.polymer-project.org/2.0/docs/upgrade#callback-contracts-have-changed) `Polymer.RenderStatus.afterNextRender` gets used with a function as its first parameter

``` js
attached: function() {
  Polymer.RenderStatus.afterNextRender(function() {
     // measure something
  }.bind(this))
}
```

however this throws an error. The method definition expects the first parameter to be an element (thisArg of the function) [source code](https://github.com/Polymer/polymer/blob/ff6e884ef4f309d41491333860a8bc9c2f178696/src/lib/render-status.html#L55)
#### Steps to Reproduce
1. Create any element
2. Add Polymer.RenderStatus.afterNextRender with a function as first parameter
### Versions

- Polymer: v1.7.0

**Comment by motss** [comment]
@Pupix Yup, the correct usage supposed to be like this:

```js
attached: function () {
  const ensureThisElemRendered = this;
  Polymer.RenderStatus.afterNextRender(ensureThisElemRendered, function runAfterRender() { ... })
}
```

**Comment by ebidel** [comment]
cc @arthurevans

**Comment by arthurevans** [comment]
Oops. Right you are. (Although @motss I think the first argument is simply the `this` argument to pass to the callback.)

**Comment by valdrinkoshi** [comment]
@kevinpschaaf @arthurevans  changing the `afterNextRender` input signature makes it impossible to write hybrid elements that work in 1.x and 2.x.

**Comment by arthurevans** [comment]
@valdrinkoshi I think there's already a fix in the works: https://github.com/Polymer/polymer/pull/4323

**Comment by TimvdLippe** [comment]
This has been fixed in https://www.polymer-project.org/2.0/docs/upgrade#callback-contracts-have-changed
