### ISSUE TITLE
Css features not working 2.x

### ISSUE THREAD

**Issue by MartinsThiago** [Polymer/polymer#4111]
I am trying to use `iron-image`, but I see my images are not being displayed on Polymer 2

The problem is `iron-image` re-uses css from `iron-flex-layout.html` through @apply... by inspecting the page I see the css is not being processed

See bellow... I am not using any polyfill (once this feature is from polymer itself, right?)

![image](https://cloud.githubusercontent.com/assets/8419829/19811245/536e6332-9d0f-11e6-837c-e72974494f6c.png)

**Comment by kevinpschaaf** [comment]
In 2.x support for `@apply` was moved out of `Polymer` and into the `shadycss` polyfill, as it is polyfilling a proposed platform feature.  As such, you need to load at least the `shadycss` polyfill.  That said, I've [updated the readme](https://github.com/Polymer/polymer/commit/b008825dd8a456bda245122a00f0435140084ba0?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8) to recommend just loading the full `webcomponents-lite.js` polyfill for the time being, until we do some more refactoring and testing of loading individual polyfills in a more alacarte fashion.

**Comment by MartinsThiago** [comment]
Worked! Thks!
