### ISSUE TITLE
Nested components added with document.createElement are removed on click. (Chrome only)

### ISSUE THREAD

**Issue by krisnye** [Polymer/polymer#4113]
### Description

Nested components added with document.createElement are removed on click.
#### Live Demo

http://viewpath4.appspot.com/polymer-remove-bug.html
#### Steps to Reproduce
1. Dynamically add a Card and add a Button to it.
   
   ```
   let card = document.createElement('paper-card')
   let button = document.createElement('paper-button')
   button.appendChild(document.createTextNode('Click me and I disappear'))
   card.appendChild(button)
   document.body.appendChild(card)
   ```
2. Click the Button.
#### Expected Results

Button remains on the page.
#### Actual Results

Button disappears.
### Browsers Affected
- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions
- Polymer: v1.7.0
- webcomponents: v0.7.22

**Comment by web-padawan** [comment]
Looks like this is the case there using `Polymer.dom(parent).appendChild(child)` is required by 1.x

**Comment by sorvell** [comment]
In order to manipulate DOM in Polymer 1.x the `Polymer.dom` api must be used. So here's how your example code needs to change:

```js
let card = document.createElement('paper-card')
let button = document.createElement('paper-button')
Polymer.dom(button).appendChild(document.createTextNode('Click me and I disappear'))
Polymer.dom(card).appendChild(button)
document.body.appendChild(card)
```

We're removing the requirement to use the `Polymer dom` api in Polymer 2.x which is currently in preview release.

**Comment by sorvell** [comment]
Please feel free to re-open the issue if the problem persists after making the recommended changes.

**Comment by krisnye** [comment]
I can confirm this fixed the problem.
