### ISSUE TITLE
paper-toggle-button has surprising behavior when trying to select text

### ISSUE THREAD

**Issue by robertkaplow** [Polymer/polymer#4116]
#### Live Demo
https://elements.polymer-project.org/elements/paper-toggle-button?view=demo:demo/index.html&active=paper-toggle-button

#### Expected Results
Expected able to select text without modiflying slider.

#### Actual Results
Sliders are modified, and text is unable to be selected for disabled.

### Browsers Affected

- [X ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
Whatever version the demo is currently running

**Comment by azakus** [comment]
This issue was moved to PolymerElements/paper-toggle-button#108
