### ISSUE TITLE
Does Polymer use native Shadow DOM on Safari 10?

### ISSUE THREAD

**Issue by motss** [Polymer/polymer#4120]
Does Polymer opt for native Shadow DOM on Safari 10 when it has [native support](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html) on Shadow DOM v1?

### Browsers Affected

- [x] Safari 10

### Versions
- Polymer: v1.7.0
- webcomponents: v0.7.20

**Comment by ebidel** [comment]
Polymer 1.0 doesn't use native shadow dom by default. It will use Shady DOM. You can opt-into native shadow dom using the `dom: 'shadow'` flag: https://www.polymer-project.org/1.0/docs/devguide/settings

**Comment by arthurevans** [comment]
Also, Polymer 1.x relies on the shadow DOM **v0** specification that was shipped in Chrome, which will not be shipped in Safari. So it'll always use shady DOM on Safari. 

**Polymer 2.x** relies on the new **v1** spec, which is shipping in Safari, Chrome, and soon other browsers. However, note that Polymer 2.x is a pre-release preview branch, the Safari shadow DOM implementation is very new and relatively untested—likewise, the v1 polyfills. So you should be aware the Polymer 2.0 on Safari is likely to present some challenges in the near term.

**Comment by motss** [comment]
@ebidel @arthurevans That basically explains everything. I don't see Safari 10 using Shadow DOM even after the following configuration:

```js
  window.Polymer = {
    dom: 'shadow',
    lazyRegister: 'max',
    useNativeCSSProperties: true,
  };
```

And `console.log(Polymer.Settings)` states `hasShadow: false`.

**Comment by ebidel** [comment]
Well, you said you're using polymer 1 ehich doesn't use the new v1
polyfills
