### ISSUE TITLE
Documentation Not working for Polymer 2.0 / Native Web Components

### ISSUE THREAD

**Issue by gaurav21r** [Polymer/polymer#4121]
According to https://youtu.be/guYHn0P8bKQ?list=PLNYkxOF6rcICc687SxHQRuo9TVNOJelSZ&t=631
The Polymer Analyzer now understands Native Web Components, Polymer 1.0 and Polymer 2.0! :open_mouth: :smile: :+1: 

However when I tried to document using the usual Comment convention (albeit in JSDoc style as given here https://www.polymer-project.org/1.0/docs/tools/documentation#element-summaries) for my native WebComponent `MyElement extends HTMLElement`, the `<iron-component-page>` rendered a **No documentation found.**

**Comment by justinfagnani** [comment]
`<iron-component-page>` does not yet use the new Analyzer. The new tools are pre-release and not integrated into everything yet.

**Comment by gaurav21r** [comment]
@justinfagnani Is there a branch in `<iron-component-page>` where the new Analyzer is being integrated? We may be able to contribute / give feedback on its working since we've worked with the Analyzer and have a few native components we want to see the documentation for.

**Comment by justinfagnani** [comment]
@gaurav21r no, no one's working on iron-component-page just yet. One difference going forward is that we don't intend to run the Analyzer in-browser for documentation, but to base documentation on the Analyzer's JSON output.

**Comment by kevinpschaaf** [comment]
This issue was moved to PolymerElements/iron-component-page#121
