### ISSUE TITLE
2.0-preview: extend & property override, issue with effects

### ISSUE THREAD

**Issue by mkazlauskas** [Polymer/polymer#4122]
### Description
When extending a Polymer element in 2.0, cannot use `computed` for overridden property that is used in some other `computed` property  in original element. 

#### Live Demo
http://jsbin.com/namabazoke/1/edit?html,output

#### Expected Results
Computed effect works

#### Actual Results
Computed effect doesn't work and in fact makes the original property `undefined`.

### Browsers Affected
- [ X] Chrome
- Not sure about others

### Versions
- Polymer: 2.0-preview
- webcomponents: v1

### Notes
I believe the problem is [this `if` statement](https://github.com/Polymer/polymer/blob/2.0-preview/src/elements/element.html#L214).

If I understand it correctly, it checks whether property is used in any computed bindings and doesn't create an effect if it is, which doesn't make much sense. If that's true, then there is also a bug with other effects.

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/polymer/pull/4132.
