### ISSUE TITLE
css custom properties cannot be queried in elements that do not apply properties

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#4125]
If an element does not apply custom property values, then it does not compute custom properties. This done as an optimization, but it's observable when the user calls `getComputedStyleValue`.  For example:

Demo here: http://jsbin.com/kuwaqi/edit?html,output

There may be other observable effects, but if this is the only one, then simply ensuring that properties are calculated when `getComputedStyleValue` is called could be a sufficient fix.

**Comment by sorvell** [comment]
e.g. forcing custom style calculation manually fixes the issue and this could be ensured in `getComputedStyleValue`: http://jsbin.com/monirobujo/1/edit?html,output.

**Comment by ktiedt** [comment]
It also prevents even setting them programatically but the fix @sorvell posted fixes that too it seems.
