### ISSUE TITLE
Update `importHref` in 2.x-preview branch to match implementation in master

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#4126]
The implementation in the 2.x-preview branch is outdated. This merge should be done after https://github.com/Polymer/polymer/pull/4114 gets merged to 1.x.

**Comment by kevinpschaaf** [comment]
The refactor to 2.0-preview was actually merged first: https://github.com/Polymer/polymer/pull/4305.

The 1.x update is pending here: https://github.com/Polymer/polymer/pull/4209 (supersedes https://github.com/Polymer/polymer/pull/4209, which should be closed).
