### ISSUE TITLE
Touch devices: No mouse events on elements for 2.5s when overlaid by elements using gestures

### ISSUE THREAD

**Issue by keanulee** [Polymer/polymer#4128]
### Description
On touch devices, when a `<button>` is covered by a Polymer element that uses gestures (e.g. one with a `down` listener) and the Polymer element is moved, the `<button>` does not receive mouse events for 2.5s since `POINTERSTATE.mouse.target` is not cleared.

#### Live Demo
http://jsbin.com/runayep/edit?html,output

#### Steps to Reproduce
1. On a touch device (or mobile emulation in Chrome), tap the button to open the drawer
2. Tap the button to close the drawer
3. Immediately, tap the button to open the drawer again

#### Expected Results
The drawer opens

#### Actual Results
The drawer does not open, but clicking the button after 2.5s does.

### Browsers Affected
All

### Versions
- Polymer: v1.7.0

**Comment by MartinsThiago** [comment]
It's still happening =(

See #4211
