### ISSUE TITLE
Click on disabled paper-item in paper-menu it closes the menu dropdown

### ISSUE THREAD

**Issue by prudhvit** [Polymer/polymer#4130]
### Description
Click on disabled paper-item in paper-menu it closes the paper-menu dropdown please refer the code

#### Code
`<paper-header-panel id ="coreHeaderPanel" mode="standard"> <paper-toolbar id="controls" class="horizontal-section"> <paper-menu-button vertical-align="top" horizontal-align="left" title="Main menu" id="mainMenu"> <paper-icon-button icon="menu" class="dropdown-trigger" alt="menu"></paper-icon-button> <paper-menu class="dropdown-content"> <paper-item id="1">1</paper-item> <paper-item id="2"disabled="true">2</paper-item> <paper-item id="3"disabled="true">3</paper-item> <paper-item id="4">3</paper-item> <paper-item id="5" disabled="true">4</paper-item> </paper-menu> </paper-menu-button> </paper-toolbar> </paper-header-panel>`
#### Steps to Reproduce

1. click on menu icon (it opens menu dropdown).
2. click on any disabled menu item.

#### Expected Results
Drop down menu should not close when click on disabled menu item

#### Actual Results
Drop down menu is closing when click on disabled menu item

### Browsers Affected

- [x ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v1.X.X

**Comment by azakus** [comment]
This issue was moved to PolymerElements/paper-item#98
