### ISSUE TITLE
Implement build time optimizations

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#4137]
In addition to polymer [build](https://www.polymer-project.org/1.0/docs/tools/polymer-cli) and the [polymer css build](https://github.com/PolymerLabs/polymer-css-build), there are a number of other possible build time optimizations that are worth exploring. Our current timeline is to invest in these features shortly after shipping version 2.0 of Polymer.

* [strip whitespace](https://github.com/Polymer/vulcanize/issues/396)
* pre-compile parsing of templates for bindings
* pre-compile polymer classes to include behaviors and property effects

**Comment by TimvdLippe** [comment]
Pre-building has been researched and a prototype is available at https://github.com/polymerlabs/loose-it Any further issues/improvements can be filed in that repository.
