### ISSUE TITLE
Expose hooks for setting values to dom

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#4138]
Users may want to apply transforms on property data that will be set to dom. For example, a user might want to ensure that `innerHTML` cannot be set without sanitizing a value. Polymer should expose hooks so users can customize this behavior.

**Comment by azakus** [comment]
A user could hook `_computeFinalAnnotationValue` to modify what will be set to the property binding

Example: http://jsbin.com/lijakuc/edit?html,output

**Comment by TimvdLippe** [comment]
This has been implemented as [`sanitizeDOMValue`](https://www.polymer-project.org/2.0/docs/devguide/settings)
