### ISSUE TITLE
Cannot access content (childNodes) in nested Polymer Element

### ISSUE THREAD

**Issue by tomalec** [Polymer/polymer#414]
I try to nest one component into another, and access content (light DOM) given to outer element one in inner one.

``` html
<polymer-element name="x-foo" noscript>
  <template>
    <h1>Foo</h1>
    <content></content>
  </template>
</polymer-element>

<polymer-element name="x-bar" noscript>
  <template>
    <h1>Bar</h1>
      <x-foo>
          <content></content>
      </x-foo>
  </template>
</polymer-element>

<x-foo>
  <p>Content</p>
</x-foo>
<x-bar>
  <p>Nested content</p>
</x-bar>
```

seems to render fine. 
However, I cannot get `<p>Nested content</p>` as `x-foo` content:

``` javascript
Polymer('x-foo',{
  ready: function(){
    console.log(
      this.children,
      this.shadowRoot.querySelector('content').getDistributedNodes()
    );
  }
});
```

Full example is here: http://jsfiddle.net/tomalec/T7k3C/2/

Is this a bug, or I should access it some other way?

**Comment by kristianmandrup** [comment]
Could you have a look at this please :) 

https://github.com/PolymerElements/paper-scroll-header-panel/issues/50#issuecomment-144122643
