### ISSUE TITLE
Component Model

### ISSUE THREAD

**Issue by christchron** [Polymer/polymer#4141]
Polymer is one of JavaScript libraries that use component-based software engineering approach. In the CBSE, there are some component models such as EJB model, COM model, .NET model, etc. I want to know which component model did Polymer use (this means the web components) ? Or Polymer is using different kind of component model? I'm doing some research about Polymer behaviour based on its component-based Software Engineering. So, i want to ask for help if there're some documentations about Polymer Component, its model, and anything that can help my research. Thank you before, if you're willing to help please send it to my email: randichil@gmail.com

**Comment by sorvell** [comment]
Polymer uses web components. Here's a [good place to start](https://www.html5rocks.com/en/tutorials/webcomponents/customelements/).
