### ISSUE TITLE
Support DOMTokenList-style attribute values for type:Array properties

### ISSUE THREAD

**Issue by tommie** [Polymer/polymer#4142]
### Description
A common pattern in HTML is to use a [DOMTokenList](https://developer.mozilla.org/en/docs/Web/API/DOMTokenList) to specify a set of strings. In Polymer, we have to choose whether we want the attribute as a literal to be simple (type string), or whether the code that uses the property is simple (type array).

It would be nice if Polymer parsed strings not beginning with a bracket as a DOMTokenList, for Array-typed properties.

#### Live Demo
https://jsbin.com/nenomubido/1/edit?html,output

#### Expected Results
["abc", "def"]
["abc", "def"]

#### Actual Results
null
["abc", "def"]

### Browsers Affected
n/a

### Versions
- Polymer: v1
- webcomponents: n/a

**Comment by TimvdLippe** [comment]
It seems that your original JSBin is the general Polymer JSBin. We can reopen this issue when a JSBin is supplied that shows the problem, which we can debug and hopefully resolve.
