### ISSUE TITLE
attributeChanged event not firing in Firefox

### ISSUE THREAD

**Issue by csakaszamok** [Polymer/polymer#4146]
### Description
attributeChanged event not firing in Firefox

#### Steps to Reproduce
I just installed a clean polymer cli app (starter-kit).
I added this event for my-view1+2+3:

```
attributeChanged: function(name, type) {
        console.log(this.localName + '#' + this.id + ' attribute ' + name +
          ' was changed to ' + this.getAttribute(name));
      }

```
#### Expected Results
When i click "View Two" menu item, then console output (in chrome):
```
  my-view1# attribute class was changed to 
  my-view2# attribute class was changed to iron-selected
```

#### Actual Results
When i click "View Two" menu item in FF, then console output is empty.

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v1.7.0
- webcomponents: v0.7.23 
- Firefox: v49.0, v52.01a1 (..etc)

**Comment by sz332** [comment]
I ran into the same problem, and the following code snippet shows how:

`<dom-module id="my-hello">
    <template>

        <div>
            <my-component id="comp"></my-component>
        </div>

	</template>
</dom-module>


<script>
    Polymer({
        is: 'my-hello',
        attached: function() {
            this.$.comp.classList.add("test");
        }
    });
</script>
`

`<dom-module id="my-component">
    <template>
        <div id="text">This entry will be selected</div>
	</template>
</dom-module>


<script>
    Polymer({
        is: 'my-component',

        attributeChanged: function(attrname, oldval, newval) {
            this.$.text.innerText = "This is replaced";
        }

    });
</script>`

**Comment by sz332** [comment]
If someone else finds this bug, and wants to use iron-pages, here is a solution:

```
  <iron-pages id="ironpage" attr-for-selected="name" on-iron-select="_select" >
            <div name="1">Not me</div>
            <my-component name="2"></my-component>
  </iron-pages>

    _select: function(e, data) {
            if (data.item.onSelect !== undefined) {
                data.item.onSelect();
            }
        },


```

**Comment by TimvdLippe** [comment]
Please follow the guidelines for creating issues at https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs
