### ISSUE TITLE
this.fire event not caught when called  from parent to child

### ISSUE THREAD

**Issue by marko911** [Polymer/polymer#4147]
`setTimeout(()=>{
                    self.fire('itemResize')
                },200)`

In my event listener for 'itemResize' I just console.log and it never gets hit. What am I missing?

**Comment by MartinsThiago** [comment]
It's hard to guess with this line only

**Comment by marko911** [comment]
Sorry. Here are some  details:

component gd-dashboard:
`attached(){`
                `
                this.initMenu()`
               ` this.render()`
               ` setTimeout(()=>this.fire('itemResize'),4000)`
           ` }`

component gd-column : 
`ready(){`
               ` this.addEventListener('itemResize', this.marko )`
         `   }`
           ` marko(){`
               ` console.log('marko')
            }`


gd-column is a child of gd-dashboard, the console.log never fires.

**Comment by marko911** [comment]
Its not even the timeout part I realized, did a few other tests where I added the event listeners in child elements in the this.listeners property and then fired the event from the parent and the child never fires the callback for that listener. 

Not sure if this makes a difference, but the child elements are created in a dom-repeat.

**Comment by MartinsThiago** [comment]
It seems fine, are you using Polymer 2.0?

If so you need to call super() on ready and attached()... otherwise try to make sure if attached is really being called

**Comment by MartinsThiago** [comment]
on gd-component... why your add an event listener on `this`?

**Comment by MartinsThiago** [comment]
Commonly events are for communication from child to parent...

So `gd-column` needs to have a method `resize`
Then `gd-dashboard` will manage all `gd-column` children

**Comment by marko911** [comment]
Well I need to send communication from parent to child but I cant do it directly, bascially the tree goes : 

<gd-dashboard>
     <gd-col-wrap> 
           <gd-column></gd-column> .... on repeat 
  <gd-col-wrap>
</gd-dashboard>

When the gd-col-wrap changes size, gd-dashboards gets the message because i have some functions there that manage that functionality, and once that function is called , I want to notify the gd-column items. 

I changed from adding event listener to this to adding them in the this.listeners property in my class definition. But regardless, I have code that defines an event listener on the polymer component using this.addEventListener('something', callback) ....and other parts of the code would fire 'something' and my callback would fire. But I noticed that it doesn't happen if I do it from Parent to child.

**Comment by MartinsThiago** [comment]
You will have to change your gd-column for something like:

```js
//gd-column
ready() {
  var chart = document.getElementById("dashboardId");
  chart.addEventListener('itemResize', this.marko.bind(this));
}
```

**Comment by marko911** [comment]
Thanks, that worked. But for future reference, should I maybe design my app structure in a way where I just use declarative handler and pass child objects inside a <content> tag , that way I can directly bind the on-[something] events for those children ?

**Comment by MartinsThiago** [comment]
Yup... Probably this is the best solution. 

Adding the event listener the way I suggested earlier works, but it will make things harder to deal  with

**Comment by IchordeDionysos** [comment]
Well you can add the content with display nine, so you can reference it by calling `this.querySelectorAll('gd-column')`. And then call functions on them

**Comment by sorvell** [comment]
Seems resolved. Please re-open if more discussion is needed.
