### ISSUE TITLE
Unclear exception when binding a property to <textarea> (IE11)

### ISSUE THREAD

**Issue by ronnyroeller** [Polymer/polymer#4150]
### Description
When assigning an attribute to <textarea> via `=` instead of `$=`, IE11 throws the following exception:
`Unable to get property '_propertyInfo' of undefined or null reference.`

Chrome, Firefox, Safari, and Edge handle this situation. Assigning an attribute via `$=` to an `<input>` element works as well on IE11.

It would be useful to have a better error message as it's rather difficult to debug this bug.

More detailed description: [Polymer + IE11 fail: Unable to get property ‘_propertyInfo’](https://medium.com/collaborne-engineering/polymer-ie11-fail-unable-to-get-property-propertyinfo-e3bef228919d#.haaq8c3ka)

#### Live Demo
https://jsbin.com/sehimorilu/edit?html

#### Steps to Reproduce
1. Add `<textarea>` element
2. Bind attribute via `=`
3. Load in IE11

#### Expected Results
- Meaningful warning
- Textarea shows

#### Actual Results
- Exception is thrown
- Textarea is not shown

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11

### Versions
- Polymer: v1.7.0
- webcomponents: v0.7.23

**Comment by TimvdLippe** [comment]
@ronnyroeller Could you run https://jsbin.com/rufiloxosi/edit?html,console,output and confirm/deny if this is still an issue in IE11 with Polymer 2?

**Comment by TimvdLippe** [comment]
Closing this per above comment. Please reopen if this still exists.
