### ISSUE TITLE
Simple binding for custom CSS variables.

### ISSUE THREAD

**Issue by josheverett** [Polymer/polymer#4151]
### Description
I find myself regularly writing boilerplate code like the following to update custom CSS variables: 

```js
Polymer({
  is: 'x-foo',
  properties: {
    backgroundColor: {
      type: String,
      observer: 'backgroundColorChanged_'
    },
    textColor: {
      type: String,
      observer: 'textColorChanged_'
    }
  },
  backgroundColorChanged_: function(value) {
    this.customStyle['--x-foo-background-color'] = value;
    this.updateStyles();
  },
  textColorChanged_: function(value) {
    this.customStyle['--x-foo-text-color'] = value;
    this.updateStyles();
  }
});
```

For straightforward cases like this, it would be nice to have a way to declare these bindings the same way you do for normal properties. Below is a spitball example of what a sugary version could look like:

```js
Polymer({
  is: 'x-foo',
  properties: {
    backgroundColor: '--x-foo-background-color',
    textColor: '--x-foo-text-color'
  }
});
```

I'd be happy to submit a PR for this behavior, but would be good to get some feedback on the idea first.

**Comment by TimvdLippe** [comment]
Actually you can use the variables directly, see this jsbin as example: https://jsbin.com/peyeyezemo/edit?html,output

**Comment by josheverett** [comment]
But what about the case where the color is provided to my-element-user dynamically? Example: https://jsbin.com/dusujepedo/1/edit?html,output

**Comment by TimvdLippe** [comment]
Hm yes for the top-level element you need to write the boilerplate. But for all elements down the tree you can use css-variables like normal.

**Comment by TimvdLippe** [comment]
^^ Note to myself: No this was definitely not intended and has since been fixed.

**Comment by TimvdLippe** [comment]
Okay, this was quite fun to figure out, but there is an elegant Polymer 2 mixin solution for this problem: http://jsbin.com/fupohiqeta/edit?html,console,output Since this is quite an unique use-case and the mixin is quite easy to write, I am inclined to close this issue as there is little incentive for us to maintain this opinionated mixin.
