### ISSUE TITLE
attached callback called twice for nodes in shadowRoots

### ISSUE THREAD

**Issue by valdrinkoshi** [Polymer/polymer#4152]
x-outer has an x-inner node in its shadowRoot.
x-inner's attached callback is called twice with polymer 2.x, while instead it should be called only once (as in 1.x).
Check the logs of this http://jsbin.com/gisuqo/4/edit?html,console,output

**Comment by valdrinkoshi** [comment]
Correction: in 1.x the behavior is the same as in 2.x when we set Polymer to use `dom: 'shadow'`
http://jsbin.com/gisuqo/5/edit?html,console,output

**Comment by valdrinkoshi** [comment]
oh gosh...I just forgot to close a tag ;_; http://jsbin.com/gisuqo/7/edit?html,console,output

**Comment by amiorenstx** [comment]
> oh gosh...I just forgot to close a tag ;_; http://jsbin.com/gisuqo/7/edit?html,console,output

got here for the exact same reason. tag not closed
