### ISSUE TITLE
Atomic readonly updates

### ISSUE THREAD

**Issue by e111077** [Polymer/polymer#4153]
Polymer 2 introduced `this.setProperties({...})`, but it is still impossible to atomically update a read-only property along with editable properties.

**Comment by kevinpschaaf** [comment]
We'd recommend using some of the new protected API's to achieve this (`setProperties` is a _public_ interface, which should probably maintain the readonly facade).

Instead, you can do the following, which bypasses `readOnly` checks.
```js
this._setPendingProperty('a', 123);
this._setPendingProperty('b', 456);
this._setPendingProperty('c', 789);
this._flushProperties();
```
