### ISSUE TITLE
does Polymer support server side rendering?

### ISSUE THREAD

**Issue by mikeandersun** [Polymer/polymer#4155]
As comparison with reactjs [here](http://www.cuelogic.com/blog/polymer-vs-react-comparison-between-two-front-end-javascript-libraries/) polymer not support  full server side rendering. 
Is it possible in polymer v2?

**Comment by treshugart** [comment]
In short, no. More info [here](https://github.com/Polymer/polymer/issues/3955).

**Comment by sorvell** [comment]
Closed in favor of issue noted above.

**Comment by dman777** [comment]
This is not true, chomestatus.com is server side rendered with Polymer and Django.
