### ISSUE TITLE
Consider making Polymer 2.x property effects more configurable by subclasses

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#4157]
Currently property effects are built using the `config` object. The `config` of a super class is automatically applied to a subclass. In addition there are certain rules that govern configuration (e.g. once a property is readOnly it cannot become not readOnly). This limits a subclass' ability to customize itself.

Ideally a subclass would have complete control over its properties and their effects. This is likely possible in the current system (by implementing `finalize` but it's a bit awkward.

A related issue is that code in a superclass may break based on changing how properties are configured. For example, we may want to remove the `_setFoo(value)` setter for a readonly property `foo` in favor of `_setReadOnly('foo', value)` so that code in a superclass does not break if a property is changed not to be readOnly.

**Comment by joh1234** [comment]
Update README
https://goo.gl/JBljdR

**Comment by sorvell** [comment]
Specifically, support could be added for configuring or resetting property effects. As explained, the current `readOnly` implementation limits this.

**Comment by sorvell** [comment]
Closing this as YAGNI. Re-open if we can provide specific important use cases to support.
