### ISSUE TITLE
[2.0-preview] dom-module should check if value changed in `attributeChangedCallback`

### ISSUE THREAD

**Issue by valdrinkoshi** [Polymer/polymer#4158]
Since `attributeChangedCallback` should be fired each time an attribute is set, there is a risk to enter in an infinite loop attributeChangedCallback -> register -> attributeChangedCallback -> register.
It would be safer to check if the value changed in `attributeChangedCallback`
```js
class DomModule extends HTMLElement {

    static get observedAttributes() { return ['id'] }

    attributeChangedCallback(name, value, old) {
      if (old !== value)
        this.register();
    }

**Comment by sorvell** [comment]
Done (https://github.com/Polymer/polymer/blob/2.0-preview/src/elements/dom-module.html#L39).
