### ISSUE TITLE
[2.0-preview] CSS Mixins values are not applied with updateStyles()

### ISSUE THREAD

**Issue by naoak** [Polymer/polymer#4159]
### Description
CSS mixins values which are dynamically set with updateStyles() are not applied.

#### Live Demo
v1: http://jsbin.com/yobobefami/1/edit?html,console,output
v2: http://jsbin.com/qavajalive/edit?html,console,output

#### Steps to Reproduce
1. Run with JS on v2 demo.

#### Expected Results
`x-foo` should be rendered with red and 64px.
#### Actual Results
`x-foo` is rendered with red, but not with 64px.

### Browsers Affected

- [x] Chrome
- [x] Safari 10

### Versions
- Polymer: 2.0-preview
- webcomponents: v1

**Comment by sorvell** [comment]
This is not supported in Polymer 1.x or 2.x when using native css custom properties. Here is an [explanation](https://github.com/webcomponents/shadycss#imperative-values-for-custom-properties).

Note, you can force use of ShadyDOM and shimmed custom properties for continued support. Here's a working version of the jsbin: http://jsbin.com/wetocex/edit?html,output.
