### ISSUE TITLE
[2.0-preview] can't access to `this.$` nodes when providing properties' default values

### ISSUE THREAD

**Issue by valdrinkoshi** [Polymer/polymer#4160]
In 1.x one can access to `this.$` nodes when providing a property default value, e.g.
```js
properties: {
  button: {
    type: HTMLElement,
    value: function() {
      return this.$.btn;
    }
  }
}
```

This is no longer possible in 2.x http://jsbin.com/mohotas/4/edit?html,console,output

**Comment by sorvell** [comment]
We're inclined to make this a breaking change unless it causes undo harm. This can be done in `ready`. Will that be sufficient?

**Comment by valdrinkoshi** [comment]
Setting it on `ready` is sufficient & doesn't trigger twice observers. @notwaldorf @cdata opinions on this?

**Comment by sorvell** [comment]
Looks sufficiently handled. Please re-open if any new issues crop up.
