### ISSUE TITLE
[2.0-preview] Path-based changes to array sub-key only notifies first time per index

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer#4163]
### Description
I was attempting to manipulate a sub-key of an item in an array (a simple boolean property). I noticed that only the first change to an item at a given index would actually notify of the change to the sub-key.

If I had an element in `fooArray`, and changed it like this:

```javascript
this.set('fooArray.0.bool', true);
```

The change would notify. As an eventual side-effect of this notification, the first element is removed from the array (so 'fooArray.0' should refer to a new object). A subsequent change to the array using the same path did not result in a notification.

#### Live Demo
http://jsbin.com/tubajo/edit?html,console,output

#### Steps to Reproduce
 1. Open the live demo URL
 2. Click the button labeled "Acknowledge next item", note the console output
 3. Click the button labeled "Add item"
 4. Click the button labeled "Acknowledge next item", note the console output

#### Expected Results
The complete console output should read:

```
"Array path changed: fooArray"
"Acknowledging item at index 0..."
"Array path changed: fooArray.0.acknowledged"
"Removing acknowledged item!"
"Array path changed: fooArray.splices"
"Array path changed: fooArray.length"
"Array path changed: fooArray.splices"
"Array path changed: fooArray.length"
"Added item to fooArray, now it has length 1"
"Acknowledging item at index 0..."
"Array path changed: fooArray.0.acknowledged" <-- Important!
"Removing acknowledged item!"
"Array path changed: fooArray.splices"
"Array path changed: fooArray.length"
```

#### Actual Results
The console output actually reads:

```
"Array path changed: fooArray"
"Acknowledging item at index 0..."
"Array path changed: fooArray.0.acknowledged"
"Removing acknowledged item!"
"Array path changed: fooArray.splices"
"Array path changed: fooArray.length"
"Array path changed: fooArray.splices"
"Array path changed: fooArray.length"
"Added item to fooArray, now it has length 1"
"Acknowledging item at index 0..."
```

NOTE: The change notification for `fooArray.0.acknowledged` does not occur.

### Versions
- Polymer: 2.0-preview

**Comment by kevinpschaaf** [comment]
This was due to invalid index-based array paths being cached in local `__data` storage.  Fix in progress on https://github.com/Polymer/polymer/tree/2.0-data-updates.

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/polymer/pull/4221.
