### ISSUE TITLE
Light DOM allow access to both local methods and containing element methods

### ISSUE THREAD

**Issue by nicholaswmin** [Polymer/polymer#4164]
I'm trying to build an `<editable-list>`  which would `dom-repeat` items declared in it's Light DOM

Ideally, I should be able to use it like so:

    <user-list>
      <editable-list data="{{data}}">
        <template id="items">
          <h4>[[item.name]]</h4>
          
          <template is="dom-if" if="{{isAuthorized(item)}}">
            <span> - Is authorized</span>
          </template>
          
          <button on-tap="deleteRow"> Delete this row </button>
        </template>
      </editable-list>
    <user-list>

**tl;dr**

The `<editable-list>`s Light DOM accesses 2 functions, one of which is contained in `<user-list>` and the other in `<editable-list>`. I can get either one *or* the other to be defined, but not both.

----

I've made this happen by using the Light Dom documentation to create elements that wrap content within them.

The problem I have is the following.

- In the above example, I'm calling a function via the `<dom-if>`, called `isAuthorized()`. 

- `isAuthorized()` exists in the component that encapsulates the `<editable-list>` itself. 

So naturally I got this error when I tried to run the above:

> compute method `isAuthorized` not defined

To mitigate this, I've rescoped the `repeater` so it uses the parent element methods, via setting the `dataHost` property
    
    // Templatize Light DOM
    const template = this.querySelector("#items");
    this.$.repeater.templatize(template);
    Polymer.Bind.prepareModel(this.$.repeater);
    Polymer.Base.prepareModelNotifyPath(this.$.repeater);
    
    // Rescope the repeated Light DOM to point to the parent
    var dataHost = (this.dataHost && this.dataHost._rootDataHost) || this.dataHost;
    this.$.repeater.dataHost = dataHost;

### New issues after rescoping:

- The delete button I have in `<editable-list>` calls a function that exists in `<editable-list>`. 

- The `dataHost` rescoping I did prevents me from accessing this method since I only have access to the encapsulating element's (parent) methods.

Is there any way to go around this problem? Like a way to "merge" the methods of `<editable-list>` and parent element so I can use both elements method from the Light DOM?

-----

### Editable List Component:

    <base href="https://polygit.org/components/">
    <script src="webcomponentsjs/webcomponents-lite.min.js"></script>
    <link href="polymer/polymer.html" rel="import">

    <dom-module id="editable-list">
      <template>
        <content></content>
        <template is="dom-repeat" id="repeater" items="{{data}}"></template>
      </template>
      <script>
        HTMLImports.whenReady(function() {
          "use strict";

          Polymer({

            is: "editable-list",
            
            ready: function() {
              const template = this.querySelector("#items");
              this.$.repeater.templatize(template);
              Polymer.Bind.prepareModel(this.$.repeater);
              Polymer.Base.prepareModelNotifyPath(this.$.repeater);
            },
            
            deleteRow: function() {
              alert("assume this row is deleted")
            }

          });
        });
      </script>
    </dom-module>

    <user-list></user-list>

### User List Component (contains the editable list)

    <base href="https://polygit.org/components/">
    <script src="webcomponentsjs/webcomponents-lite.min.js"></script>
    <link href="polymer/polymer.html" rel="import">

    <dom-module id="user-list">
      <template>
        <editable-list data="{{data}}">
          <template id="items">
            <h4>[[item.name]]</h4>
            <template is="dom-if" if="{{isAuthorized(item)}}">
              <span> - Is authorized</span>
            </template>
            <button on-tap="deleteRow"> Delete this row </button>
          </template>
        </editable-list>
      </template>
      <script>
        HTMLImports.whenReady(function() {
          "use strict";

          Polymer({

            is: "user-list",
            properties: {
             data: {
               type: Array,
               value: [
                {
                  name: "Foo",
                  authorized: true
                },
                {
                  name: "Bar",
                  authorized: false
                }
               ]
             }
            },
            
            isAuthorized: function(user) {
              if (user.authorized) return true;
              else return false;
            }

          });
        });
      </script>
    </dom-module>

    <user-list></user-list>

Here's an example [JSFiddle][1]. Please note that it's not really working since `dataHost` seems to be undefined in JSFiddle. It might/or not give an overview of the code in any case

  [1]: https://jsfiddle.net/g1259q4j/8/

**Comment by TimvdLippe** [comment]
@nicholaswmin Sorry for the very late response. Reading this issue, I would say that this is working as intended. The scopes for methods is the usage of these methods. You can not pass on a method of a custom element in a new scope. Instead, you can delegate the calls from the outer element to the usage element. E.g. have an `isAuthorized` in the outer element that simply calls the `isAuthorized` of the element you are using. Would that work for you?

**Comment by nicholaswmin** [comment]
@TimvdLippe Perhaps, It's been a long time since I've made this question. Let's close it down and reopen later if needed, which I doubt.

Thanks for the response.

**Comment by TimvdLippe** [comment]
Yes apologies for the long delay. Trying to go through all issues, but it was quite a bunch :stuck_out_tongue: Let's close and feel free to reopen if you run into issues again.
