### ISSUE TITLE
:host selector names are concatenated in shadow dom mode when applying mixins, resulting in errors

### ISSUE THREAD

**Issue by whenlit** [Polymer/polymer#4165]
### Description
When an element defines a mixin on `:host some-selector` and also applies a mixin(any mixin) to any selector, a nonsensical selector is created somewhere in Polymer's bowels. This results in the script breaking when the resulting selector is invalid. For example, when the original selector is `:host.some-class [some-attribute]`, the resulting selector will be `element-name.some-class [some-attribute]element-name`, resulting in an error:

> polymer.html:3637Uncaught DOMException: Failed to execute 'matches' on 'Element': 'element-name.some-class [some-attribute]element-name' is not a valid selector.

This also happens when the element does not apply a mixin but does contain another element that does apply a mixin.

Only shadow DOM is affected by this.

#### Live Demo
One element using and applying the mixin: 
http://plnkr.co/edit/zsSAV8Kuboq8UJZpz5yM?p=preview

Element using a mixin, contained element applying another mixin: 
http://plnkr.co/edit/J2Dp7tE7kbxpamd5uoBr?p=preview

### Reproduce
1. Go to one of the above Plunkers, with Chrome;
2. Find errors in the console.

#### Expected Results
No errors, mixins are applied.

#### Actual Results
Errors appear in the console.

### Browsers Affected

- [ X ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v1.7.0
- webcomponents: v0.7.23

**Comment by whenlit** [comment]
This is probably the same problem as #3846.

**Comment by TimvdLippe** [comment]
The original Plunkers do not show an error on the console. Are you still able to reproduce this issue @whenlit ?

**Comment by whenlit** [comment]
Unfortunately I don't have access to the original code anymore, but I see the error doesn't appear now. I did try the jsfiddle in the issue I linked to (#3846) with the most recent version of polymer, and that appears to work now too. It seems reasonable to assume the issue has gone away. Maybe @mgiuffrida knows more.

**Comment by TimvdLippe** [comment]
@whenlit Great to hear! Can confirm that I can't reproduce #3846 any longer as well. Cheers :smile:
