### ISSUE TITLE
Memory retention of DOM objects in `dom-if` when restamp is true

### ISSUE THREAD

**Issue by jarrodek** [Polymer/polymer#4166]
### Description
Right now I'm analysing my app in terms of memory usage because I have a suspicion of a memory leak somewhere in the app.
While I was investigating the detached DOM nodes I noticed that some elements that are children of the `dom-if` template (with restamp property set) as still in the memory. They are not active (don't receive data binding or perform any operation) but they exists and take memory.

This is a screenshot of the profile snapshot:
![image](https://cloud.githubusercontent.com/assets/3320020/20491133/50d5516a-b008-11e6-86f4-6c2251831f4d.png)

The `HTMLElement` in the Object pane is the element that was wrapped with the `dom-if` template.
As far as I understand how the `dom-if` should work, the element shouldn't be retained in the memory. 

I'm wondering if that might be caused by data binding. In this particular case the removed element is activated in the app, then, after app settings initialisation, it should be removed (wherever the reason). But during the initialisation time element receives an object via data binding which it's properties are later propagated to child elements. So my guess is that this object keeps the removed element alive. Passed object is referenced in the main script and other elements uses it. 

This is the code:
```
<template is="dom-if" if="[[!usePouchDb]]" restamp="true">
                <arc-request-controller on-iron-deselect="_cancelEvent" on-iron-select="_cancelEvent" request-loading="{{requestLoading}}" has-response="{{hasResponse}}" opened="{{requestOpened}}" request="{{request}}" response="{{response}}" active-request="{{activeRequest}}" route-params="[[params]]">
                  <arc-request-view on-iron-deselect="_cancelEvent" on-iron-select="_cancelEvent" request-loading="[[requestLoading]]" opened="{{requestOpened}}" request="{{request}}"></arc-request-view>
                  <template is="dom-if" if="[[hasResponse]]">
                    <arc-response-view opened="[[requestOpened]]" response="[[response]]" request="[[activeRequest]]"></arc-response-view>
                  </template>
                  <arc-save-dialog-view on-iron-deselect="_cancelEvent" on-iron-select="_cancelEvent" id="saveRequestUi"></arc-save-dialog-view>
                </arc-request-controller>
              </template>
```

#### Steps to Reproduce
1. Add any element that is wrapped with template `dom-if` and restamp property set.
2. In Chrome DevTools go to Profiles > Check Take Heap Snapshot > Take snapshot
3. In the snapshot, filter by `Detached`
4. Try to find an element that matches tested element. It should be one of the detached elements.

### Versions
- Polymer: v1.7.0
- webcomponents: v0.7.23

**Comment by Eymerich01** [comment]
there is not workaround for it? :(

**Comment by Eymerich01** [comment]
I cannot believe that no one of Polymer team write a correct procedure to remove leak memory for polymer components (on detach for example ) :(
There is a memory leak study on polymer 2.0 ?

**Comment by TimvdLippe** [comment]
I am unable to reproduce this issue in http://jsbin.com/xevafukaxe/edit?html,console,output Performing a memory snapshot shows that at most one span is kept in memory, but that's because it originates from the `document-fragment` from the dom-if template. Could you elaborate on this issue?

**Comment by jarrodek** [comment]
I can't reproduce it with current version of the Polymer either. Possibly this was fixed.
