### ISSUE TITLE
shop demo does not work on blackberry Z30

### ISSUE THREAD

**Issue by emailtowalter** [Polymer/polymer#4168]
Unfortunately, some people in the world are still using BB Z30, like myself. The thing is it is corp phone and we want to build app on it.  Is there a plan to make it work? 

Thanks, 

Walter

**Comment by Alos** [comment]
Does the BBZ30's browser support any part of the Web Components spec? Maybe the minimal features required by the polyfills?  Have a look [here](https://github.com/webcomponents/webcomponentsjs).

**Comment by TimvdLippe** [comment]
The shop has been updated to use Polymer 2. If you are still experiencing problems on Blackberry, please open an issue on https://github.com/polymer/shop/issues
