### ISSUE TITLE
detached polymer-element should not auto-register

### ISSUE THREAD

**Issue by jmesserly** [Polymer/polymer#417]
it's causing issues interoping with Angular. From @mhevery:

> The bug you filed, I think is an issue with polymer. I think the polymer is a bit to eager about registering components. I think a DOM which is not connected to the DOM render tree should be inert, and should not cause registration of components. That is the behavior of script tag for example. Only a script tag which is in DOM render tree gets processed/loaded. 

(source: [angular-dart](https://groups.google.com/d/msg/angular-dart/q7wnJ7DDPQg/NTx4sW0aFYYJ) post)

I haven't thought about it deeply but it seems like if I clone a polymer-element, I wouldn't expect it to immediately try and register itself, similar to how nodes inside a `<template>` are inert. Thoughts?

**Comment by ebidel** [comment]
Closing stale issues.
