### ISSUE TITLE
[2.0-preview] Can't access dom-repeat item from declarative event listener

### ISSUE THREAD

**Issue by MartinsThiago** [Polymer/polymer#4170]
### Description

From `input-toggle` I **can't** reach dom-repeat scoped data using declarative event listeners, but I **can** from `input-select`

For `input-toggle` I tried using `event.model.control` and `event.model.item`

```html
<dom-repeat items="[[product.controls]]" as="control" sort="[[_sortControls]]">
  <template>
    <div class="food-control">
      
      <dom-if if="[[_isToggleControl(control.type)]]">
        <template>
          <input-toggle class="food-control--input" 
            checked
            on-checked-changed="_writeToggle"
            style="font-size: .8em; padding-right: 15px"></input-toggle>
        </template>
      </dom-if>

      <dom-if if="[[!_isToggleControl(control.type)]]">
        <template>
          <input-select class="food-control--select"
            options="[[control.options]]"
            on-selection-changed="_writeSelection"
            display-field="title"
            multiple="[[_isMultiSelectionControl(control.type)]]"></input-select>
        </template>
      </dom-if>

    </div>
  </template>
</dom-repeat>
```
#### Live Demo

https://58346943a7e2d226df59557a--rangs-client.netlify.com/subway

#### Steps to Reproduce
Access the live demo and...

![untitled screencast 1](https://cloud.githubusercontent.com/assets/8419829/20536570/7370f376-b0e1-11e6-85b0-03d70b857e99.gif)

#### Expected Results
Retrieve dom-repeat item through events

#### Actual Results
It's working for one of the two elements (quite weird)

### Browsers Affected
Possibly all of them
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: 2.0-preview
- webcomponents: none

**Comment by arthurevans** [comment]
That _is_ really weird. Perhaps it has something to do with which one is displayed first?

The live demo doesn't seem to be working at the moment (I'm only seeing the header followed by a blank page), so I can't poke further there.

One workaround would be to add an ID on the `dom-repeat` and use `modelForElement` to get the model info that's not getting attached to the event:

    var model = this.$.repeater.modelForElement(e.target);
    console.log(model.control);

**Comment by MartinsThiago** [comment]
The workaround did it

About the displayed order, only one of them are displayed per line

**Comment by MartinsThiago** [comment]
I assume you're browser is updated, but anyway I'm running Chrome 54

It's strange it didn't run on your browser, the URL points to a static build (which I used to record the screen)... I'll try to dive into dom-repeat to figure it out

**Comment by arthurevans** [comment]
OK, yeah, the demo is working for me now.

There's a known issue with `dom-if` not propagating event data from an outer `dom-repeat`:
https://github.com/Polymer/polymer/issues/2574

What's interesting is that you're only seeing this for _one_ of your `dom-if`s. I can't figure out why you're getting the model data for the other one.

**Comment by MartinsThiago** [comment]
I think I am getting closer...

I simplified my markup and I found that it's possible to retrieve data from `e.model.item` only when inner `dom-if` have some binding

```html
<dom-repeat items="[[product.controls]]" sort="[[_sortControls]]">
  <template>

    <div on-click="_logModelItem">simple (works)</div><br>

    <dom-if if>
      <template>
        <div on-click="_logModelItem">dom-if-simple (don't)</div><br>
      </template>
    </dom-if>

    <dom-if if>
      <template>
        <div on-click="_logModelItem"
             any="[[_simpleLog(item)]]">dom-if-complex (works)</div><br>
      </template>
    </dom-if>

  </template>
</dom-repeat>
```

```js
...
_writeModelItem(e) {
  console.log(e.model.item);
}

_simpleLog(value) {
  console.log(value);
}
...
```

**Comment by MartinsThiago** [comment]
Here's the log after clicking on each one

![image](https://cloud.githubusercontent.com/assets/8419829/20541991/b486723c-b0e6-11e6-9be3-6ca5985546aa.png)

**Comment by MartinsThiago** [comment]
I also force bower to reinstall polymer-2.0 to assure I have the latest commits

**Comment by sorvell** [comment]
Addressed via https://github.com/Polymer/polymer/pull/4339.
