### ISSUE TITLE
[2.0-preview] Effects for content stamped by `dom-if` keep running even when !if

### ISSUE THREAD

**Issue by blasten** [Polymer/polymer#4171]
`dom-if` supports a `restamp` mode, however that isn't the default. If a `dom-if` template is stamped, its property effects are enabled during the entire life of the app even if the `if` prop is set to `false` after being `true`.

#### Live Demo
http://jsbin.com/qitifu/edit?html,output

#### Steps to Reproduce
1. Add a the following `dom-if`:
```html
<dom-if if="[[condition]]">
  <template>
     <div>[[prop]]</div>
  </template>
</dom-if>
```
2. Change to `if=true`
3. Change to `if=false`
4. Change `prop`
5. `prop` is actually updated in the DOM even though `if=false`

#### Expected Results
Changing properties that are bound to some nodes shouldn't have any cost when `if=false`

#### Actual Results
It does have a cost

### Browsers Affected

All
### Versions
- Polymer: 2.0-preview

**Comment by kevinpschaaf** [comment]
Fixed in https://github.com/Polymer/polymer/pull/4299!
