### ISSUE TITLE
querySelectorAll behaves differently in shady vs shadow dom.

### ISSUE THREAD

**Issue by admwx7** [Polymer/polymer#4172]
### Description
Noticed this while running my tests in shadow vs shady dom.  I needed to select all children of an id within my element, I was using: `this.querySelectorAll('#id .child');` but it didn't work in shadow dom, did some research and turned to: `this.root.querySelectorAll('#id .child');` which didn't work in shady dom.  Ended up resorting to: `this.$.id.querySelectorAll('.child')` which works in both.

Tried with and without `Polymer.dom`, same results.

#### Live Demo
https://jsfiddle.net/amurdock/z5gbzctc/

#### Steps to Reproduce
1. Create a containing element
2. Add a container div with a class/id to query on
3. Add children elements to your container
4. Attempt to query for all child elements using `this.querySelectorAll` in shadow DOM or `this.root.querySelectorAll` in shady DOM

#### Expected Results
A NodeList of all children

#### Actual Results
An empty node list depending on the DOM used

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v1.6.0, v1.7.0
- webcomponents: v0.7.22

**Comment by miztroh** [comment]
I think this is the expected behavior.  You should probably use ``Polymer.dom(this.$.test).querySelector(...)`` just in case ``this.$.test`` ever becomes a custom element with its own shadow DOM.

**Comment by admwx7** [comment]
I disagree @miztroh checking out the documentation on element.querySelectorAll: https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelectorAll shows what you would expect, one of their examples is querying for grand-children of the element, wouldn't make sense to have that functionality suddenly change once you're running inside of the shadow dom.

Further more, you can get expected functionality using `this.root` instead of `this`.

**Comment by miztroh** [comment]
``querySelector`` and ``querySelectorAll`` are only for light DOM children.  They are not designed to pierce the shadow DOM.  Elements inside of a shadow root are not children of the host element.  They are inside of their own document that has been redistributed to appear inside of the host element.

**Comment by admwx7** [comment]
The example does not pierce the shadow DOM, the query is all done within the same shadowRoot.  If however you're claiming that `this`/`this.root` are not part of the same shadowRoot as all of the elements light DOM, then all of the light DOM documentation is wrong.  And also there's an issue with querySelector[All] ever working from the root level.

At the very least I would expect `Polymer.dom(this.root).querySelectorAll` to function the same in both Shady and Shadow DOMs.  Which should let you query the entire light DOM of your element as long as it isn't piercing the shadow DOM, including children and grand children.

Which keeps consistent with the MDN description if you take it in the context of the partial DOM created for your shadow root.

**Comment by admwx7** [comment]
`Polymer.dom(this.root).querySelector` works consistently, all other variations will not work consistently across both DOMs.

Looks like my original issue with `Polymer.dom` not resolving my problem is related back to dom-repeat creating a new shadowRoot within the context of the light DOM.  Updated the JSFiddle to reflect that, going to close this task, thanks @miztroh.
