### ISSUE TITLE
Invalid zip files again

### ISSUE THREAD

**Issue by rubberony** [Polymer/polymer#4174]
Every time I try to download the elements as a zip - invalid archive.

I should mention this is on the polymer element catalog website

Not the first time this issue has occurred it seems.

**Comment by TimvdLippe** [comment]
I have been unable to reproduce this issue. The catalog has been replaced with webcomponents.org in which you can find several collections. They link to GitHub on which you can download the zip. Please file any issues related to webcomponents.org on https://github.com/webcomponents/webcomponents.org/issues or if you downloaded a corrupt zip from GitHub on its corresponding repository.
