### ISSUE TITLE
The generated HTML is not sematic

### ISSUE THREAD

**Issue by tirithen** [Polymer/polymer#4177]
When looking at the header for e.g. the paper-card component (https://elements.polymer-project.org/elements/paper-card) it does not use a h1 tag for the header. I would expect a section tag and a h1 in a card but all I can see are div tags. Is there a good reason for this or was it missed out on by accident?

**Comment by nicholaswmin** [comment]
@tirithen I think this should be posted on paper-card's repo instead https://github.com/PolymerElements/paper-card/issues

**Comment by tirithen** [comment]
Yes you are right, now in https://github.com/PolymerElements/paper-card/issues/89
