### ISSUE TITLE
Binding to HTML5 audio events not working

### ISSUE THREAD

**Issue by cashpipeplusplus** [Polymer/polymer#4178]
### Description
Binding to HTML5 audio events is not working.

I'm trying to bind to timeupdate and durationchange events as described in the docs:
https://www.polymer-project.org/1.0/docs/devguide/data-binding#two-way-native

This appears to have no effect.

I'm doing what's documented as far as I can tell.  If I'm doing it wrong, please let me know how.  I'm also happy to create a PR to update the docs if something's missing.

#### Live Demo
http://jsbin.com/xoxucimawa/2/edit?html,console,output

#### Steps to Reproduce
The docs use this to bind hostTime to video's currentTime through timeupdate events:

```html
<video url="..." current-time="{{hostTime::timeupdate}}">
```

I'm doing something similar:

```html
        <audio
            current-time="{{hostCurrentTime:timeupdate}}"
            duration="{{hostDuration:durationchange}}">
```

#### Expected Results
The host properties change when the audio element fires those events.

#### Actual Results
Nothing changes.  You can see in the jsbin that the relevant events are being fired by the audio element.

### Browsers Affected

- [X] Chrome
- [ ] Firefox (not tested)
- [ ] Edge (not tested)
- [ ] Safari 9 (not tested)
- [ ] Safari 8 (not tested)
- [ ] IE 11 (not tested)

### Versions
- Polymer: v1.7.0
- webcomponents: not sure

**Comment by tony19** [comment]
Your bindings are each missing a colon (should be double-colons):

```html
        <audio
            current-time="{{hostCurrentTime::timeupdate}}"
            duration="{{hostDuration::durationchange}}">
```

[jsbin](http://jsbin.com/mafuluceja/1/edit?html,console,output)

**Comment by cashpipeplusplus** [comment]
Thank you!  That was my mistake.
