### ISSUE TITLE
[2.0-preview] how to write tests that use dom-bind vs <template is="dom-bind">

### ISSUE THREAD

**Issue by notwaldorf** [Polymer/polymer#4180]
In 1.0 I had this code:
```html
<template is="dom-bind" id="bind-to-object">
  <iron-input id="input" bind-value="{{foo}}"></iron-input>
</template>
```

In 2.0, it becomes 
```html
<dom-bind id="bind-to-object">
  <template is="dom-bind">
    <iron-input id="input" bind-value="{{foo}}"></iron-input>
  </template>
</dom-bind>
```

How do I write a test that can set `foo` or get `input` in a hybrid element? I need to write this to work in 2.0:
```js
var ironInput = scope.$.input;
scope.foo = undefined;
```

And this for it to work in 1.0:
```js
var ironInput = scope.querySelector('template').$.input;
scope.querySelector('template').foo = undefined;
```

**Comment by kevinpschaaf** [comment]
In general, the pattern will be to identify which element got upgraded (either the `<dom-bind>` wrapper in 2.0 or the `<template is="dom-bind">` in 1.0) and conditionally choose the scope. 

```html
<dom-bind id="scopeV2">
  <template is="dom-bind" id="scopeV1">
    [[text]]
  </template>
</dom-bind>

<script>
var scope = window.scopeV2.$ ? window.scopeV2 : window.scopeV1;
scope.text = 'works!';
</script>
```

Here I used the existence of the `$` map as an indication of upgrade.  Alternatives would be e.g. checking `Polymer.version[0] == '1'` or `Polymer.isInstance`...
