### ISSUE TITLE
Provide an api for converting a 1.x behavior into a 2.x mixin

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#4181]
Users writing 2.x elements in class based syntax may want to use Polymer 1.x behaviors. This could be made possible via an api that wraps the behavior in a class expression mixin.

**Comment by sorvell** [comment]
This has been exposed as `Polymer.mixinBehaviors([...behaviors...], baseClass)`. 

Leaving this open so it can be documented.

**Comment by kevinpschaaf** [comment]
Closing, as we have a separate tracker for pending API documentation (and it's already been documented in our API documentation branch: https://github.com/Polymer/polymer/compare/2.0-preview...2.0-doc-annotations#diff-ac5771b3a44bf972bca119c60ec3baecR46)
