### ISSUE TITLE
Unable to change focus during 'tap' handler on touchscreen devices

### ISSUE THREAD

**Issue by tgsergeant** [Polymer/polymer#4185]
### Description

If focus changes to another element during a 'tap' handler, the focus will transfer back to the original element when tapped on a touchscreen device.  

(As seen in [crbug.com/624356](https://crbug.com/624356), where a button in chrome://history doesn't work on touch devices)

#### Live Demo
Visit https://jsbin.com/mobukuluhi/1/edit on a touchscreen device (eg, Chrome for Android), or with devtools touch emulation enabled

#### Steps to Reproduce

1. Tap search button

#### Expected Results
Focus should transfer to the search field

#### Actual Results
Focus doesn't change (you might see the search field briefly flicker, but it won't stay focused)

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v1.7.0

(cc @danbeam)

**Comment by arthurevans** [comment]
Isn't this just the default handling for a touch event? I think if you want to avoid it, you need to call `preventDefault` on the tap event:

```
focusSearch: function(e) {
  this.$.searchInput.focus();
  e.preventDefault();
}
```

**Comment by hcarmona** [comment]
There is also the behavior described in http://crbug.com/653415 where the on-tap event will focus a newly visible element underneath where the event took place. Calling `preventDefault` works to avoid focusing this new element, but it seems like unwanted behavior that we would want to focus an element other than the one that was tapped. Quick demo of the behavior: http://jsbin.com/qavizi/2/edit?html,output

**Comment by freshp86** [comment]
FWIW this is not only happening with Polymer's "tap" event, but also with a native "touchstart" event, see https://jsfiddle.net/dtmyhay3/3/ (switch to device mode in dev tools to reproduce).

**Comment by tgsergeant** [comment]
Hmmm, okay. I guess this is a Chrome thing then. It's frustrating that there's a noticable difference like this between `click` and `tap`, but it doesn't look like there's much Polymer can do about it.

**Comment by freshp86** [comment]
We should still determine whether this is according to specification, or happens on Chrome only. Did not try this on Firefox myself (I am not aware of "device mode" for Firefox).

**Comment by tgsergeant** [comment]
@freshp86, using your jsfiddle from above...

* Firefox on Windows 10: Focus returns to buttons regardless of whether `preventDefault` was called (:confused:)
* Edge on Windows 10: Same behavior as Chrome

**Comment by tgsergeant** [comment]
And FWIW, Safari on iPhone is also the same behavior as Chrome.
