### ISSUE TITLE
Shady rendered DOM places style-tags above meta-charset

### ISSUE THREAD

**Issue by erikkroes** [Polymer/polymer#4186]
Not sure if this is the right spot or way to mention this but here goes. 

Currently if the DOM is rendered shady (for example, https://www.polymer-project.org/ in Firefox), style tag are inserted as the first item in the head tag. This easily pushes any charset-declaration out of the first 1024 bytes which I understand to be a no go (https://www.w3.org/TR/html5/document-metadata.html#charset). Could these styles be hooked in at a different point?

**Comment by sorvell** [comment]
Are you seeing any negative result due to this?

It's unclear from the spec that it would be disallowed to insert elements where we do after initial parsing. If this is causing a problem, we can certainly shift the style elements down.

**Comment by TimvdLippe** [comment]
Closing per above comment. We can reopen if the question has been answered :smile:
