### ISSUE TITLE
[2.0-preview] `setScrollDirection` missing from legacy element API

### ISSUE THREAD

**Issue by bicknellr** [Polymer/polymer#4192]
Elements in 1.x had a [`setScrollDirection` method](https://github.com/Polymer/polymer/blob/99c9d6726dbf43a54e3f5e448ce9955de903a197/src/standard/gestures.html#L751) that no longer exists. To work around, call `Polymer.Gestures.setTouchAction` instead, using a value from [this map](https://github.com/Polymer/polymer/blob/99c9d6726dbf43a54e3f5e448ce9955de903a197/src/standard/gestures.html#L707).

**Comment by sorvell** [comment]
Closing as this now exists (https://github.com/Polymer/polymer/blob/2.0-preview/src/legacy/legacy-element-mixin.html#L276).
