### ISSUE TITLE
Template dom-if calling multiple time when validating firebase-query values

### ISSUE THREAD

**Issue by diegopitt** [Polymer/polymer#4195]
In the following snippet I am using a template to show data when proposals.length matches an specific number. The function _disableProposals gets called several times. When hardcoding values ->_disableProposals(3) gets called once. 

```
  <firebase-query
    id="query"
    app-name="vida_fire"
    path="jobs/[[jobKey]]/proposals"
    data="{{proposals}}">
  </firebase-query>
  <template is="dom-if" if="[[_disableProposals(proposals.length)]]">
   <div class="notification">..</div>
  </template>

  _disableProposals: function(num) {
    console.log(num);  //here the console prints several numeric values
    return num === 3;
  }
```

**Comment by TimvdLippe** [comment]
Please follow the guidelines for creating issues at https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs We need a runnable JSBin which shows the issue to debug and potentially solve.
