### ISSUE TITLE
set() has no effect after splice()

### ISSUE THREAD

**Issue by pkaske** [Polymer/polymer#4196]
It seems polymer looses sync when using splice on arrays.

#### Live Demo
http://jsbin.com/qobivafuvo/edit?html,output

#### Steps to Reproduce in the jsbin
1. List of countries shows up; click "Edit third item"-Button
2. The third item in the list changes to '---------'
3. Click the "Splice..."-Button; The third item is removed
4. Click the "Edit third item"-Button again; Nothing happens
-->

#### Expected Results
At the second time clicking "Edit third item", the "new" third item should now read "----------".

#### Actual Results
Nothing happens.

### Browsers Affected
- [x] Chrome
- [x] Firefox

### Versions
Master

**Comment by tony19** [comment]
I don't have an explanation, but the problem seems to related to the key in your [data path](paths-to-array-items). It works correctly if you change:

    demo.set('input.#2.name', '------------');

to:

    demo.set('input.2.name', '------------');

**Comment by pkaske** [comment]
Awesome @tony19,
such an easy workaround! Why didn't I think of this myself...
And this should greatly narrow the problem down for the folks that know the internals of the data binding system.

**Comment by arthurevans** [comment]
Keys are stable: so #2 isn't the third item, it's a stable key to a particular item. If you remove that item and then try to edit it, it's not going to do anything. 

Accessing the items by index does what you want here. (In general, as the success say, you don't need to mess with keys unless you're doing something fancy like making your own dom-repeat or iron-list equivalent.)

So I think this is WAI here.

**Comment by pkaske** [comment]
Got you, @arthurevans! Now the whole `#` thing in the `path` of observer change records finally makes sense to me. I always wondered why it's not just the number.
