### ISSUE TITLE
hover CSS still applied after mouse has left the component

### ISSUE THREAD

**Issue by Moremar** [Polymer/polymer#4197]
### Description
When we have 2 levels of components, the CSS appied on hover to a component sometimes persists even when the mouse has left the component

#### Steps to Reproduce

[polymer_issue.zip](https://github.com/Polymer/polymer/files/630120/polymer_issue.zip)

1. The file my-component.html is a basic web component showing a div with the string "A" when not hovered, and a div containing the string "B" with a colored background when hovered.
The file index.html includes 4 of those components.
2. When hovering slowly those components, they behave correctly, but when hovering them quickly, some of them keep their hover state even if they are not hovered anymore.

#### Expected Results
when the mouse hovers the "A", "B" is displayed instead on a grey background.
when the mouse leaves the "B", the "A" comes back and the grey background disappears.

#### Actual Results
when we quickly hover in and out of the components, some of them sometimes keep their hover state("B" with grey background) even if they are not hovered anymore.

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v1.7.0
- webcomponents: v0.7.22 

### Note
The same issue was created in Chromium in case it is only related to Chrome : 
https://bugs.chromium.org/p/chromium/issues/detail?id=671073

**Comment by TimvdLippe** [comment]
This appears to be fixed in Polymer 2 and working in both Chrome and Firefox: http://jsbin.com/vecugixija/edit?html,console,output
