### ISSUE TITLE
wrong value of Polymer.Settings.useShadow in 2.0-preview

### ISSUE THREAD

**Issue by valdrinkoshi** [Polymer/polymer#4198]
`Polymer.Settings.useShadow` should be `false` when `window.ShadyDOM.inUse = true`
e.g. 
2.0-preview w/ flags `wc-shadydom, wc-ce` http://output.jsbin.com/kiwukim/1/?wc-shadydom=true&wc-ce=true
compared to 
1.x w/ flag `dom=shady` http://output.jsbin.com/kiwukim/2/?dom=shady

**Comment by sorvell** [comment]
It's pretty cumbersome to figure this out in a hybrid compatible way. For that reason we'll go ahead and add some of the polyfill specific info to `Polymer.Settings` in 2.x

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/polymer/pull/4337.
