### ISSUE TITLE
Optimize stylesheet handling for shady css build type

### ISSUE THREAD

**Issue by dfreedm** [Polymer/polymer#4203]
Under shady css builds, the style inside of an element is already modified with shadydom selectors and flattened, so it can just be moved into the `<head>` (the build does not do this to preserve dependency ordering at runtime).

However, Polymer reads in the text content of that style, creates a new style in `<head>`, and sets the text content.

Instead, under shady css builds, Polymer should just move that stylesheet to `<head>`

**Comment by blasten** [comment]
Moving a single stylesheet causes sync style recalcs in Blink and Webkit today.  One engineer from Opera has already started doing some work around this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=567021
