### ISSUE TITLE
Global messaging: when data binding doesn't cut it

### ISSUE THREAD

**Issue by mercmobily** [Polymer/polymer#4206]
I have a rather large application. Imagine this scenario:

* I have a widget buried deep in the element tree that allows me to write a chat message, call it `my-singleadd`
* On the other side of the planet, there is a simple chat widget that shows all messages and allows you to write an extra one, call it `my-chat`
* When a chat message is added within `my-chat`, I have full control and basically push the message manually to the messages array. Easy.
* Attaching with data binding the list of chat messages would be absurd, because 1) `my-singleadd` might be adding a chat message to a different user than the one displayed in `my-chat` 2) `chatMessages` would need to be bound across 95 levels of elements that have nothing to do with messages and chats
* EVEN MORE IMPORTANT, chat messages can come from the "outside". I have successfully established a websocket connection. Now I need to use it.

My current thought, is to use Websocket to receive messages from the main app, and simply broadcast those messages onto the `html` element in the application. The `type` could be `recordChange`, with `table` being the changed table and `op` being either `remove`, or `add` or `update`. In this solution:

* `my-chat` would listen for events of type `websocket` in `html` and react to `recordChange` being `add` and table being `chatMessages`: if the `my-chat` is viewing an exchange with the user and the added record belongs to that chat (comparing userId fields), then bingo

* The infamous `single-add` widget will ALSO fire a `recordChange` event, with `op` being `add` (with an extra `local` parameter being `true`). `my-chat` will react to that event in the exact same way as if the event was generated by a websocked (in fact, apart from `local` being `true`, there would be no difference).

Now... is this a good way to go about this? Please note that I had completed this exact scenario a couple of years back using Dojo, and it worked very well. I just want to make sure I am not being "tainted" by my previous experience and miss completely a much easier way of doing it...

Thank you!

**Comment by TimvdLippe** [comment]
In general if I need to share some global application-specific data, I write a behavior for it. You can see an example here: https://github.com/PolymerElements/app-storage/blob/master/app-network-status-behavior.html

This behavior keeps track of all its instances and notifies them accordingly when 1 value changes.

Do keep in mind that this is usually an anti-pattern, but I think it is justified in rare scenarios such as the one you described.

**Comment by timeu** [comment]
I would go with a state management framework such as [polymer-redux](https://github.com/tur-nr/polymer-redux). This will help a lot with dealing data flow and state management.

**Comment by mercmobily** [comment]
@timeu Sorry i get a stomachache every time I read about redux. I have a bound object and bounce *that* around pretty much the whole app, and that includes user configuration and info. That to me works really well. Redux is:

> Redux is a predictable state container for JavaScript apps. It helps you write applications that behave consistently, run in different environments (client, server, and native), and are easy to test."

This relates with "propagate remote and local changes to data" in such a loose way... And no I am now ready to see every possible data returned by a query to the server as a "state". Really.

Sorry, am I ranting about complexity? 

@timvdlippe I like your idea. It is an anti pattern, which is why it makes me nervous...

**Comment by timeu** [comment]
I think you mis-interpretated that quote.  
Redux is not really about "propagating data from server to client". It's purely about application local state management. 
For me personally, Redux reduced the complexity of dealing with state a lot, because modifications to that state happen in a single place (reducers) and my Polymer components don't need to be bound to a single global object and thus have global knowledge. They only subscribe to slices of the data.  I used this approach in one app where I also used websockets for updates where the websocket messags are converted into Redux actions and the reducers take care of updating the state. 
I think it can be worth looking into it.

**Comment by mercmobily** [comment]
@TimvdLippe  Please don't judge me for this code!

https://gist.github.com/mercmobily/b82ceea6c3bf90d1b0fafd9e577a4c88

I hacked together a behaviour that does what I need. I am just concerned that it might just be way, way too ugly to be used in production.

&lt;dream>What would _really_ rock, is having global-style data binding -- a bit like Meta works, but with notifications (which is basically impossible, I know...) &lt;/dream>

The gist of it is that there's a plain JS object with state variables and methods. One important requirement is to be able to assign a `clientId` *once* (each tab will have its owntab ID), and then have it available to elements using this behaviour (probably including it in ajax forms)
Now with the ugliness:

* **The property   `wsData` is a straight pointer to `object`** (as in, the JS object with methods and properties). This way, I can have an element that uses this behaviour and have:

    <form>
      <input type="hidden" type="clientId" value="{{wsData.clientid}}">
      ....
    </form>

Ugliness level: mild-to-severe. It feels really awkward, to link a Polymer property to a plain object.

* Two properties, `wsUrl` and `wsReconnectDelay`, will programmatically update the object.
Why? this is because I can have `my-app` to use that behaviour, and then specify this in `index.html`:

      <my-app ws-client-id="{{_generateClientId}}" ws-reconnect-delay="10000" >  

But, these properties are "setters" only. Other elements using this behaviour cannot just do `{{wsClientId}}` since they will not be set. They will still need to do `{{wsData.clientid}}`
Ugliness level: medium to mild

* One property, `autoConnect`, will make sure `object.connect()` is called. This means you can have:

      <my-app auto-connect ws-client-id="{{_generateClientId}}" ws-reconnect-delay="10000" >  

* Then `wsSendLocal` and `wsSendWs` are used to broadcast a message either locally, or through the open websocket. For example adding a chat message will require me to broadcast a new message locally, so that two far away corners of my app can react to it. When adding a chat message record, I will make sure I include the `clientId` (or `tabId`), so that the sever won't broadcast the message back to me. Obviously, those messages can also come from the websocket (for example, I wrote the message from another open tab in my application). The handling code is the same, for local messages and remote ones.

Is your head exploding yet? Do you think this is just way too ugly?

**Comment by TimvdLippe** [comment]
@mercmobily the gist you provided is in my opinion a very big anti-pattern. You are essentially recreating global state of your whole element.

Instead, using behaviors to share 1 global application value is in my opinion okay. For example I had to do it to share the oAuth token to all my `-ajax` elements. For these rare usecases, I think it is justified to use a behavior to mimic a "global" value. However, since this is very easy to screw up and miuse I do not think this should be supported in the core library.

If you are really looking for application wide sharing of multiple values, I would advise you to take another look at `polymer-redux`. It does seem that is the solution you are looking for :smile:

**Comment by mercmobily** [comment]
This whole thing evolved into something "interesting". Close this -- I will show you what I've done with it once I'm finished.
