### ISSUE TITLE
Object/Array typed properties should not fire changed event when they where null and are assigned null again (no change)

### ISSUE THREAD

**Issue by erichmx** [Polymer/polymer#4208]
### Description
I honestly believe this is an issue in 2.0-preview, but I'm new to Polymer.

I think that changes for properties of type object/array should not fire a changed event when they where null and are assigned to null again. Is this correct?

#### Proposed fix

This is the change I did to fix it (the last line), am I missing something?

```javascript

      _shouldPropChange(property, value, old) {
        return (
          // Strict equality check for primitives
          (old !== value && 
           // This ensures old:NaN, value:NaN always returns false
           (old === old || value === value)) ||
          // Objects/Arrays always pass
          (typeof value == 'object' 
                    //don't notify when it was null and is assigned null again
                    && !(old === value && value === null)) 
```

#### Some background

I forked and migrated the vaadin date picker to use Polymer 2.0-preview (I'm not affiliated to vaadin in anyway, I just wanted to know how painful would be to migrate a complex component) and was getting a very weird behavior where the value of the input was being reset when scrolling the calendar because a property that "never changed" was firing its property changed, I spent an entire afternoon trying to pinpoint the problem and the only thing I can say is that I believe is related to **two way binding** marking the selectedDate as changed when nothing had changed.

#### No Live Demo :'(
I'm aware that without the live demo and steps to reproduce usually is very time consuming to fix something, but I believe this is a simple question **"should  Object/Array properties fire a changed event when they where null and are assigned a null again?"**. If a live demo would help I can try to do something simplistic.

### Browsers Affected

- [X ] Chrome (I have only tested in Chrome)
- [ N/A] Firefox
- [ N/A] Edge
- [ N/A] Safari 9
- [ N/A] Safari 8
- [ N/A] IE 11

### Versions

- Polymer: 2.0-preview
- webcomponents: v1

**Comment by MartinsThiago** [comment]
I think it's not an issue with Poly 2.0

As it's on README
- To improve compatibility with top-down data-flow approaches (e.g. Flux), we no longer dirty-check properties whose values are objects or arrays.

Personal opinion -> I think it's ok, polymer should dispatch events **every time a property is set**

**Comment by erichmx** [comment]
@MartinsThiago I had seen that in the README and I'm not proposing to go back to dirty checking objects or not supporting implementations of Flux like Redux or any other, and I don't even want start a war on whether going from null to null should be considered a mutation or not.

What I am saying is that **I don't think that notifying a property change from null to null was the code's author intention**, it can have a very high cost and I don't see any benefit (even [Redux](https://github.com/reactjs/redux/blob/master/src/combineReducers.js) tools like [redux](https://github.com/buunguyen/redux-freeze/blob/master/src/middleware.js)-[freeze](https://github.com/jsdf/deep-freeze/blob/master/index.js) and [redux-freeze-state](https://github.com/jfpalacios/redux-freeze-state/blob/master/index.js)  don't freeze null properties)

I have to admit that I don't use any Flux implementation and I may be missing something.

Maybe @kevinpschaaf or @sorvell could say if that was truly the intention.

**Comment by arthurevans** [comment]
I believe that @erichmx is correct and this is unintentional. No dirty-checking objects is designed to allow subproperty changes to flow through. But `null` doesn't have any subproperties; `null` is always just `null`.

FYI, the core team are looking at changes that might affect this code, so it may be a little while before they get to this issue.

**Comment by erichmx** [comment]
Thank you for your answer @arthurevans. I just saw the branch where, as you said, the team is doing a lot of work on this code!.  

I'll just add that I saw a performance boost when I changed this, and the changed events fired went down to 30% in this (too specific) case, from 2,100 to 700.

**Comment by sorvell** [comment]
Here's a demo of the issue: http://jsbin.com/wejurab/edit?html,console,output.

**Comment by kevinpschaaf** [comment]
@erichmx Sorry for the delay on this.  Agree it does seem best to treat `null` as a primitive (as opposed to object) for purposes of dirty checking and do a strict equality check.  Just put a PR up for this change.  Thanks for pointing it out.

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/polymer/pull/4340.

**Comment by erichmx** [comment]
@kevinpschaaf looks like you already completed the change, thank you! and my apologies for not contributing a solution this time, you were working with a couple of branches with many changes on the dirty checking .
