### ISSUE TITLE
Feature Request: Querying items that are visible in a dom-if

### ISSUE THREAD

**Issue by nicholaswmin** [Polymer/polymer#4210]
### Description

I'd like for a way to select only visible elements in the DOM that are within a `<dom-if>` template that evaluates to true without having to resort to using `restamp`

#### Example

```
<template is="dom-if" if="[[true]]">
  <span>I should be selectable</span>
</template>
<template is="dom-if" if="[[false]]">
  <span>I should not be selectable</span>
</template>

// should return only `<span>I should be selectable</span>`
Polymer.dom(this.root).querySelectorAllVisible("span");
```

The normal behavior of `dom-if` is to stamp contents and then toggle via CSS the visibility of items. This results in the contents being selectable when `querySelectorAll` is called, irregardless of whether they are contained in a "falsey" `dom-if`.

**Comment by motss** [comment]
@nicholaswmin Does `this.$$` work? I tried and it does. 😕

**Comment by nicholaswmin** [comment]
Of course but it selects "falsey" dom-if wrapped elements as well :slightly_smiling_face:

**Comment by motss** [comment]
@nicholaswmin Don't understand how you did it. But I was able to query it, see demo. https://jsbin.com/quyunay/edit?html,output

**Comment by nicholaswmin** [comment]
It's not a matter of rendering issues - it's a matter of selecting only elements that are wrapped in truthy `<dom-if>`'s

For example in this [JSFiddle][1] I would like to get 2 elements but instead I'm getting 3. It's behaving normally. It's not a bug. 

It's a feature request for a new DOM method that would allow me to select only visible nodes


[1]: https://jsfiddle.net/c4xbdjqh/2/

**Comment by TimvdLippe** [comment]
Seems to be working correctly now in Polymer 2: http://jsbin.com/xakihuvebe/edit?html,console,output
