### ISSUE TITLE
Polymer is stopping click propagation

### ISSUE THREAD

**Issue by MartinsThiago** [Polymer/polymer#4211]
### Description
For some reason after I select elements with `iron-selector`, polymer stops clicks propagation for elements outside `iron-selector` **(This happens only with touch devices)**, I dug around and I found the bug happens when this function [gesture-event-listeners.html:61](https://github.com/Polymer/polymer/blob/2.0-preview/src/events/gesture-event-listeners.html#L61-L85) is executed

#### Live Demo
https://jsbin.com/giyopub/edit?html,console,output

#### Steps to Reproduce
1. Open jsbin link
2. Simulate a **touch device** through dev tools
3. Click on first button
4. Click on iron-selector children
5. Click on last button

See this gif
![dec 11 2016 4-50 pm](https://cloud.githubusercontent.com/assets/8419829/21083168/6db49e78-bfe2-11e6-84ec-2542b8a82090.gif)

#### Expected Results
Should log messages to console when first clicking the button

#### Actual Results
It's needed to click a few time to see logs through console

### Browsers Affected
- [x] Chrome
- [ ] Edge

Didn't test other browsers
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v2.0.0-preview (bug may happen with older versions as well)
- webcomponents: none

**Comment by MartinsThiago** [comment]
As GestureEventListener is preventing mouse events for 2500ms, I tried calling `Polymer.Gestures.resetMouseCanceller()` to workaround... but no success :disappointed:

**Comment by afroradiohead** [comment]
+1

**Comment by MartinsThiago** [comment]
Ping @azakus 

Instead of using `document` in these lines [gesture-event-listeners.html:95-97](https://github.com/Polymer/polymer/blob/2.0-preview/src/events/gesture-event-listeners.html#L95-L97)

Could we restrict the listener to specific elements?

**Comment by azakus** [comment]
new JSBin showing 2.0-preview: https://jsbin.com/wigubic/edit?html,console,output

**Comment by azakus** [comment]
Fixed by #4356

**Comment by MartinsThiago** [comment]
ヽ༼ʘ̚ل͜ʘ̚༽ﾉ
You rock

**Comment by myfrom** [comment]
Hello!
I found this issue to be happening in latest Polymer 2.6. In my app, I have a button which has `onclick` listener that creates an input element and simulates a click on it; that click is prevented by `mouseCanceller` function. I found a workaround and I'm working on a JSBin to better illustrate the problem. Should I open a new issue or will this one be reopened?
