### ISSUE TITLE
With ShadyCSS, binding `class` attribute with text + computed expression removes style scoping classes

### ISSUE THREAD

**Issue by keanulee** [Polymer/polymer#4214]
### Description
For example, in [paper-card](https://github.com/PolymerElements/paper-card/blob/2.0-preview/paper-card.html#L139), there's an attribute binding to `class` of the form:

```html
<div class$="title-text [[_computeHeadingClass(image)]]"></div>
```

#### Expected Results
(Rendered DOM - assume `_computeHeadingClass()` returns `''`)
```html
<div class="title-text style-scope paper-card"></div>
```

#### Actual Results
```html
<div class="title-text "></div>
```

### Browsers Affected
All browsers using Shady DOM/CSS.

cc @azakus

**Comment by vpusher** [comment]
👍 

Confirmed. As workaround, the whole value should be bind into a computed expression:

```html
<div class$="[[_computeHeadingClass(image)]]"></div>
```

Nevertheless, being able to bind some raw classes mixed up with a computed expression output is a killer feature.

**Comment by sorvell** [comment]
@azakus Should be fixed, but can you please verify? Thanks.

**Comment by azakus** [comment]
@sorvell nope, if you have any nesting of nodes, ShadyCSS' mutation observer does not catch it.

**Comment by azakus** [comment]
This issue was moved to webcomponents/shadycss#59
