### ISSUE TITLE
Appending a node to the light DOM with slot=...

### ISSUE THREAD

**Issue by blasten** [Polymer/polymer#4215]
The following test fails in Polymer v1 using ShadyDOM in either Firefox 49, Safari 9 or Edge.
```html 
<dom-module id="x-foo">
  <template>
    <style>
      :host {
        display: block;
      }
    </style>
    <div id="test">
      <slot name="test"></slot>
    </div>
  </template>
  <script>
    HTMLImports.whenReady(function() {
      Polymer({
        is: 'x-foo'
      });
    });
  </script>
</dom-module>

<x-foo id="xfoo"></x-foo>

<script>
  HTMLImports.whenReady(function() {
    var xfoo = document.querySelector('#xfoo');
    var item = document.createElement('div');
    item.slot = 'test';
    Polymer.dom(xfoo).appendChild(item);
    Polymer.dom.flush();
    var insertionPoint = Polymer.dom(item).getDestinationInsertionPoints()[0];
    assert.equal(Polymer.dom(insertionPoint).parentNode,  xfoo.$.test);
  });
</script>
```

Tested in Firefox 49.

**Comment by azakus** [comment]
The `slot` property on nodes is not polyfilled in Polymer v1. You should use `Polymer.dom(item).setAttribute('slot', 'test')`.

**Comment by sorvell** [comment]
We could add the `slot` accessor to `Polymer.dom` to facilitate doing this via a property set, but since there is another way to accomplish this (via setting the attribute) and you'd definitely have to use `Polymer.dom` anyway, this seems like a low priority.

**Comment by TimvdLippe** [comment]
This appears to be fixed: http://jsbin.com/zotuqezava/edit?html,console,output Working in Firefox + ShadyDOM.
