### ISSUE TITLE
[2.0-preview] compound bindings throw in Safari 10.

### ISSUE THREAD

**Issue by blasten** [Polymer/polymer#4216]
The following should repro the issue:

```html
<dom-module id="x-grid">
  <template is="dom-repeat" items="[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]">
    <li class="item" style="background-image: url(//lorempixel.com/800/800/nature/?i=[[item]]);">
      <div class="item-title">Nature [[item]]</div>
    </li>
  </template>
</dom-module>
<script>
  HTMLImports.whenReady(function() {
    Polymer({
      is: 'x-grid'
    });
  });
</script>
```
Safari 10 under Shady DOM.

Error: `_atEndOfMicrotask — data:text/javascript;charset=utf-8,%0A…%0A:51TypeError: Attempted to assign to readonly property.`

**Comment by sorvell** [comment]
Attribute binding for `style` should work. Here's an example:

http://jsbin.com/dazonac/edit?html,output

**Comment by blasten** [comment]
You can see the issue here: http://jsbin.com/gixeji/edit?html,output in Safari 10.

**Comment by sorvell** [comment]
The binding to `style` must be an attribute binding. In the example above, it's a property binding.

e.g.

`style="background-image: ...`

must be

`style$="background-image: ...`

**Comment by blasten** [comment]
@sorvell Sorry. That was the actual difference between your jsbin and mine. Would 2.0 support  property binding to `style`? I was under the impression that bindings to `style` *(as a property)* should originate individual `el.style[cssPropName] = ...` updates.
