### ISSUE TITLE
Make `Polymer.RenderStatus._makeReady`public

### ISSUE THREAD

**Issue by blasten** [Polymer/polymer#4217]
Currently, Polymer defers `Ready` until [rAF time](https://github.com/Polymer/polymer/blob/ff6e884ef4f309d41491333860a8bc9c2f178696/src/lib/render-status.html#L47), but it would be useful to expose an API to make rendering happen earlier.

Scenario: A user opens a Polymer app in a background tab and no rendering work happens until the tab becomes active.

**Comment by TimvdLippe** [comment]
`ready` is no longer deferred and eagerly called after [`connectedCallback`](https://github.com/Polymer/polymer/blob/2d739c753446f90b43fac1de528f46fce4e241da/lib/mixins/element-mixin.html#L661) with [`_enableProperties`](https://github.com/Polymer/polymer/blob/2d739c753446f90b43fac1de528f46fce4e241da/lib/mixins/property-accessors.html#L546) so the need for exposing this API is no longer there.
