### ISSUE TITLE
In Safari 9, click events on nested elements do not propagate to parent

### ISSUE THREAD

**Issue by keanulee** [Polymer/polymer#4219]
### Description
In Safari 9 (tested using polyserve transpilation), if I click on the `<iron-icon>` inside `<paper-icon-button>`, then the event listener added by `addEventListener('click', handler)` is not run. However, it does run if any of the following is done:

- Setting `pointer-events: none` on `<iron-icon>`
- Using the `onclick` attribute on `paper-icon-button` instead of `addEventListener()`

Note that this is NOT specific to SVGs - the issue still occurs when using an `<img>` instead of an icon.

#### Live Demo
(Not live - need to use `polyserve` for transpilation to ES5 for Safari 9)

bower.json:
```json
{
  "name": "paper-icon-button",
  "private": true,
  "dependencies": {
    "paper-icon-button": "PolymerElements/paper-icon-button#2.0-preview",
    "iron-icons": "PolymerElements/iron-icons#2.0-preview"
  }
}
```

index.html:
```html
<!doctype html>
<html>
  <head>
    <title>paper-icon-button demo</title>
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1, user-scalable=yes">
    <script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>

    <link rel="import" href="bower_components/iron-icons/iron-icons.html">
    <link rel="import" href="bower_components/paper-icon-button/paper-icon-button.html">
  </head>
  <body>
    <h3>addEventListener()</h3>
    <paper-icon-button id="svgBtn" icon="menu"></paper-icon-button>
    <paper-icon-button id="imgBtn" src="https://assets-cdn.github.com/images/modules/logos_page/Octocat.png"></paper-icon-button>

    <script>
    svgBtn.addEventListener('click', function() { alert('addEventListener') });
    imgBtn.addEventListener('click', function() { alert('addEventListener') });
    </script>

    <h3>onclick=</h3>
    <paper-icon-button onclick="alert('onclick');" icon="menu"></paper-icon-button>
    <paper-icon-button onclick="alert('onclick');" src="https://assets-cdn.github.com/images/modules/logos_page/Octocat.png"></paper-icon-button>
  </body>
</html>
```

#### Steps to Reproduce
`bower i`, then run `polyserve` so that it transpiles to ES5 for Safari 9. Open in Safari 9 VM or iOS 9 Simulator.

#### Expected Results
In the `addEventListener()` demos, clicking on the icon or image inside `<paper-icon-button>` should open an `alert()`

#### Actual Results
The event listener isn't run, and there is no `alert()`.

### Browsers Affected
Safari 9 (OS X and iOS Simulator)

### Versions
Polymer 2

cc @azakus

**Comment by azakus** [comment]
Yep, still happening

**Comment by azakus** [comment]
This is caused by ShadyDOM event patching not handling older browsers without `event.isTrusted`
