### ISSUE TITLE
All templates created by polymer-cli should try to use shadow-dom if possible

### ISSUE THREAD

**Issue by ergo** [Polymer/polymer#4224]
I know this is not the perfect place to post this but I think it should require some decent visibility and can serve as a place of discussion.

So all the element templates that are created by polymer CLI tool by default DO NOT use shadow dom and  just operate on shady. This might be a problem long term because people might assume their components work correctly - where in fact this might be not the case because all kinds of things can go wrong if component was not written with proper encapsulation in mind.

I would suggest maybe it would make more sense to place:

      window.Polymer = {
        dom: 'shadow',
        lazyRegister: true
      };

Like PSK has to be consistent? This is a big change and has serious implications so probably needs some debate.

**Comment by ergo** [comment]
CC @robdodson @arthurevans @notwaldorf

**Comment by robdodson** [comment]
I'm fine with adding it to the two templates that don't have it: `application` and `element`. It looks like `starter-kit`, and `shop` already use `dom: shadow`.

**Comment by TimvdLippe** [comment]
Given that the templates are now using Polymer 2, I think we can close this issue? @robdodson @abdonrd

**Comment by robdodson** [comment]
i'm cool with that

**Comment by abdonrd** [comment]
Yep, thanks @TimvdLippe!
