### ISSUE TITLE
Relative URLs rewritten against the most parent element

### ISSUE THREAD

**Issue by WoodyWoodsta** [Polymer/polymer#4226]
### Description
An example project has a directory structure as below:
```
app/
 ├- elements/
 |   ├- element-1/
 |   |   └- element-1.html
 |   └- element-2/
 |       ├- resources/
 |       |   └- image.png
 |       └- element-2.html
 └- index.html
```

`element-1` is a parent to `element-2` in the DOM via a `slot` and `element-2` contains an `img` as part of its declaration which attempts to load the `image.png` in the element's `resources` folder using the relative url `resources/image.png`. However, polymer rewrites the url as if `resources` is a child directory of `element-1`'s folder.

Similar issue: https://github.com/Polymer/polymer/issues/4213

#### Live Demo
Not quite live, but needed to demonstrate with an actual project structure. An example project can be found here: https://github.com/WoodyWoodsta/polymer-resolve-url-issue

#### Expected Results
Image loads successfully using the relative url, which should resolve to `http://localhost:3000/elements/element-2/resources/image.png`

#### Actual Results
Polymer rewrites the url to `http://localhost:3000/elements/element-1/resources/image.png`
Calling `resolveUrl` on `element-2` returns the correct url.

### Versions

- Polymer: 2.0-preview
- webcomponents: v1

**Comment by azakus** [comment]
I can't reproduce this with your test case. Likely this issue has been solved.
