### ISSUE TITLE
Consider adding temporarily cached path fixup for correctness

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#4227]
https://github.com/Polymer/polymer/pull/4221 introduced a "temporary" cache for dirty checking sub-paths of objects, which is cleared at the end of the turn.  The allows the removal of the 1.x `Collection` abstraction by just notifying index-based array paths, since it avoids index-based paths being cached indefinitely, where splices to the array can leave them invalid.

However, the temp cache is not necessarily sufficient to prevent invalid array paths, since a splice can happen during the same turn with pathological user code; we could introduce a "fixup" at `_setProperty` to clear or adjust the index of temporarily cached array paths if needed.

**Comment by TimvdLippe** [comment]
Yeah, so this "temporary" cache still exists :joy: @kevinpschaaf Is this something we still want to do or shall we close it as wontfix? From the original comment I don't understand it fully and it misses a JSBin.
