### ISSUE TITLE
dom-if renders even if statement is false sometimes

### ISSUE THREAD

**Issue by gathem** [Polymer/polymer#4233]
Posted on stackoverflow.
Here is an image illustrating the bug: http://imgur.com/gallery/wrV9m

#### Live Demo

Time consuming to setup a JSBin.

#### Steps to Reproduce
Its easy on my local to reproduce but not easy to reproduce on a jsbin.
It works several times until it gets in a funky state, and then everytime the dom-if will render the template regardless of whether the statement is true or false.

### Browsers Affected

- [x ] Chrome
- [ x] Firefox
- [ ] Edge // untested
- [x ] Safari 9
- [ ] Safari 8 // untested
- [ ] IE 11 // untested

### Versions
- Polymer: v1.5.0

**Comment by TimvdLippe** [comment]
For us to debug this issue we would need a running JSBin. Please reopen this issue if you have been able to reproduce it in JSBin or supply a complete `index.html` which we can load in the browser to test. Reading the description, I am not able to reproduce your issue.
