### ISSUE TITLE
Polymer 2.0 - Dblclick is not bubbling up

### ISSUE THREAD

**Issue by afroradiohead** [Polymer/polymer#4234]
http://codepen.io/anon/pen/ObYaqX?editors=1000

If you look at the example you'll notice a **blue box** with **black box** inside

The **blue box** is listening to the dblclick event, however when you click the **black box** the dblclick event does not trickle up to the **blue box**... any idea why?

_(If you replace dblclick with click you'll see it works that way, which is odd)_

**Comment by sorvell** [comment]
Here's a slightly updated example that works x-browser: http://codepen.io/anon/pen/wJBJyd?editors=1000. 

Closing since this no longer seems to repro on the example. Please re-open if the problem resurfaces.
