### ISSUE TITLE
Catching websocket events in an element that also runs importHref breaks importHref

### ISSUE THREAD

**Issue by mercmobily** [Polymer/polymer#4235]
This took a lot of debugging.
Basically, using the debugger in a callback for a websocket renders importHref useless.
I am filing this seemingly ridiculously edge case because it might possibly be the symptom for something more serious (maybe, for example, this is not just for websocket events?)

Luckily I found an easy way to reproduce it.

#### Steps to Reproduce

1)
Clone the Polymer Starter Kit, using `polymer init`

2)
Add the following to `my-app.html`:

     attached: function(){

        try {
          var socket = new WebSocket( 'ws://127.0.0.1:8082/' );
        } catch (e ){
          console.log("Error: ", e );
        }
        socket.onerror = function(){ debugger; };
      }

3)
Open the page with Crome Debugger open.

#### Expected Results
The debugger triggers, and once the app is restarted, everything works as expected

#### Actual Results
The `importHref` call doesn't seem to work.
Please note that this is _not_ a problem due to the fact that the websocket fails. The same thing happens if `debugger` is placed in the onopen callback of the socket. It's just much harder to reproduce with `onopen` as you need to have a websocket server on the other end.

### Browsers Affected

- [X] Chrome 53
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
Polymer 1.7.1

**Comment by TimvdLippe** [comment]
This is a bizarre edge-case and I can not reproduce this issue in a JSBin. If you are still encountering issues, please reopen with a runnable JSBin that shows the issue.
