### ISSUE TITLE
polymer-project.org not rendering(Google maps error)

### ISSUE THREAD

**Issue by brylie** [Polymer/polymer#4236]
The [Polymer](https://polymer-project.org) website is not rendering. There is an error in the browser console:

```
"No Google Maps API Key or Client ID specified. See https://developers.google.com/maps/documentation/javascript/get-api-key for instructions to get started with a key or client id."  index.js:16:25183

"Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys"  util.js:211:33
```
![peek 2016-12-29 13-04](https://cloud.githubusercontent.com/assets/17307/21542590/8765b58a-cdc7-11e6-9fe5-a13af363c633.gif)

**Comment by brylie** [comment]
I am using Firefox 50.1.0

**Comment by arthurevans** [comment]
Dup of Polymer/docs#1851, which has been resolved.
