### ISSUE TITLE
404 : https://www.polymer-project.org/1.0/

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [Polymer/polymer#4237]
https://www.polymer-project.org/1.0/

**404** ???

**Comment by arthurevans** [comment]
I can't reproduce this. Is there any chance you're being blocked by a firewall or something?

Thanks, 
Arthur

**Comment by ernsheong** [comment]
https://github.com/Polymer/polymer/issues/4264

**Comment by devilbags** [comment]
Samething here. Potential problems with SSL certificate? Although this should never happen to Google
<img width="743" alt="screen shot 2017-01-24 at 9 50 29 am" src="https://cloud.githubusercontent.com/assets/11239869/22252176/56178658-e21b-11e6-9f6d-40ef038001e0.png">
