### ISSUE TITLE
[Feature Request] Dom-Repeat for (array-like) objects (e.g. Firebase Push-ID)

### ISSUE THREAD

**Issue by derhuebiii** [Polymer/polymer#4238]
I think it would be handy if it would be possible to use Dom Repeat for objects (or at least array like objects) as created by using Firebase push.

An example of implementation can be found here:
http://stackoverflow.com/a/37015188/4178195

Thanks!
Tim

**Comment by TimvdLippe** [comment]
I think this is a duplicate of #1385

**Comment by derhuebiii** [comment]
It is, thanks. 

But unfortunately also no proper workaround solution with two way binding there :(
