### ISSUE TITLE
Error thrown when creating Events with IE11 Polyfill

### ISSUE THREAD

**Issue by tobilen** [Polymer/polymer#4240]
### Description
IE11 Event Constructor cant be called directly ( http://stackoverflow.com/questions/26596123/internet-explorer-9-10-11-event-constructor-doesnt-work ). To circumvent this problem, i've implemented a polyfill which makes use of the createEvent method ( https://msdn.microsoft.com/en-us/library/ff975304(v=vs.85).aspx ):

```
try {
        var shim = new Event("toggle");
      }
      catch (error) {
        var CustomEvent = function(event, params) {
          var evt, origPrevent;
          params = params || {
              bubbles: false,
              cancelable: false,
              detail: undefined
            };

          evt = document.createEvent("CustomEvent");
          evt.initCustomEvent(event, params.bubbles, params.cancelable, params.detail);
          evt.composed = params.composed;

          origPrevent = evt.preventDefault;
          evt.preventDefault = function () {
            origPrevent.call(this);
            try {
              Object.defineProperty(this, 'defaultPrevented', {
                get: function () {
                  return true;
                }
              });
            } catch(e) {
              this.defaultPrevented = true;
            }
          };
          return evt;
        };

        CustomEvent.prototype = window.Event.prototype;
        window.Event = CustomEvent; // expose definition to window
        window.CustomEvent = CustomEvent; // expose definition to window
      }
```

This leads to IE11 throwing when event objects are accessed directly, which is the case in https://github.com/Polymer/polymer/blob/2.0-preview/src/elements/legacy-element.html#L186 and https://github.com/Polymer/polymer/blob/2.0-preview/src/events/gesture-event-listeners.html#L423

> Assignment to read-only properties is not allowed in strict mode

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [X] IE 11

### Versions
- Polymer: v2.0
- webcomponents: v1

**Comment by web-padawan** [comment]
There is another [repo](https://github.com/webcomponents/webcomponents-platform) for polyfills like this one, please check it.

**Comment by azakus** [comment]
As @web-padawan said, this is implemented in https://github.com/webcomponents/webcomponents-platform, which will be loaded by webcomponentsjs for IE11
