### ISSUE TITLE
Forwarding click events in iOS Safari works only once

### ISSUE THREAD

**Issue by platosha** [Polymer/polymer#4242]
### Description

In iOS Safari, in a button click event listener, calling click() on a `<input type="file">` works only once.

Probably something to do with the ghost-click prevention in `src/standard/gestures.html`.

#### Live Demo

http://jsbin.com/poqiledega/3/edit?html,output

#### Steps to Reproduce

1. Add `<button>Trigger</button> <input type="file">` to the document
2. Add a click event listener for the trigger button that forwards clicks to the file input by calling `fileInput.click()`
3. Click the button a few times

#### Expected Results

The file selector dialog opens in any browser any time the button is clicked.

#### Actual Results

In iOS Safari, only first click opens the file dialog. The second and subsequent clicks do nothing.

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
- [x] iOS 10.2 Safari

### Versions
- Polymer:
  - master: only the first click works, as described here
  - v1.7.1: no clicks work
  - v1.7.0 and 1.6.0: all clicks work
- webcomponents: v0.7.22, v0.7.23

**Comment by nachoab** [comment]
In Polymer 2 is happening in Chrome Android too.

Comparing to Polymer 1, there is an extra timeout of MOUSE_TIMEOUT=2500, so there is a click canceling for 2,5s

https://github.com/Polymer/polymer/blob/2.0-preview/src/utils/gestures.html#L110
```js
    POINTERSTATE.mouse.mouseIgnoreJob = Polymer.Debouncer.debounce(
          POINTERSTATE.mouse.mouseIgnoreJob
        , Polymer.Async.timeOut.after(MOUSE_TIMEOUT)
        , unset);
```

I'm not really sure what are you trying to accomplish with this, but couldn't this be too much intervention behind the scenes.? This is not the platform behavior.
 Why not leave the platform as it is and let the user explicitly work around the problem?
