### ISSUE TITLE
async HTML Import delays load event

### ISSUE THREAD

**Issue by Jeff17Robbins** [Polymer/polymer#4243]
### Description
async HTML Import delays load event

#### Live Demo
http://jsbin.com/gerufayexu/edit?html,js,output

#### Steps to Reproduce
click on link -- wait 5 seconds -- only then does window load event fire

**discussion**
Section 6.3 of http://w3c.github.io/webcomponents/spec/imports/ says:

"Every import that is not marked as async delays the load event in the Document."

But as the jsbin shows, an async import **does** delay the load event.  

I'm filing here with Polymer as one of the main consumers of HTML Imports, I thought you folks might have some insight as to this.  Progressive page loading would presumably be enhanced by not holding up the page load waiting for the async import.

#### Expected Results
I expected the load event to fire immediately on page load, and not wait for the async HTML Import.

#### Actual Results
The load event is delayed for the (contrived to illustrate the point) 5 seconds it takes to load the import.

### Browsers Affected
I tested the jsbin link in Chrome Version 55.0.2883.87 m on Windows 10.

**Comment by sorvell** [comment]
That definitely sounds like a bug. Please [file this issue](https://bugs.chromium.org/p/chromium/issues/list) on Chrome.
