### ISSUE TITLE
opera don't show the content.

### ISSUE THREAD

**Issue by jairorudas** [Polymer/polymer#4253]
### Description

Opera browser don´t show de content when I access https://www.polymer-project.org/1.0/docs/browsers

### Browsers Affected

- [ ] Opera

**Comment by jairorudas** [comment]
I readed the documentation. Opera isn´t support yet. ;)

**Comment by web-padawan** [comment]
Which Opera version are you using? If your Opera is up to date, it is supported as well as Chrome (because of using Chromium under the hood), but if you use Opera 12 or earlier (based on Presto), you'll definitely experience some issues.

**Comment by jairorudas** [comment]
I´m using the version 42.0.2393.94 on windows

**Comment by web-padawan** [comment]
Works fine for me with 42.0.2393.94 on Windows 7. Look at the console, are there any errors?

**Comment by jairorudas** [comment]
Yes, it has a warning console: 
`Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.`

`The resource https://www.polymer-project.org/bower_components/webcomponentsjs/webcomponents-lite.min.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.`

and 

`The resource https://www.polymer-project.org/css/site.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.`

**Comment by web-padawan** [comment]
First warning is nothing, but the

**Comment by miopa** [comment]
I have the exact same issue on Opera (42.0.2393.94, Arch Linux). 
In addition, it doesn't show the contents on any page under `https://elements.polymer-project.org/`, with no errors and warnings in the console.

**Comment by web-padawan** [comment]
I think this could be closed now?

/cc @arthurevans

**Comment by arthurevans** [comment]
Haven't heard any more reports, and it's working OK for me on Opera 46/OS X. In the past issues have sometimes been related to extensions, so maybe try opening a window with no extensions, or disabling specific extensions, if you have any (In Opera, **View** > **Show Extensions**).

I'm going to close this. If anyone sees this problem, please file an issue on Polymer/docs with details. Thanks!
