### ISSUE TITLE
issue when install polymer

### ISSUE THREAD

**Issue by FridaCai** [Polymer/polymer#4257]
hi,

when i run "npm install -g polymer-cli"

i got the error message:
[spawn-sync@1.0.15] scripts.postinstall: "node postinstall" at /usr/local/lib/node_modules/.polymer-cli_npminstall/spawn-sync/1.0.15/spawn-sync
[spawn-sync@1.0.15] scripts.postinstall success, use 57ms
[dtrace-provider@0.8.0] scripts.install: "node scripts/install.js" at /usr/local/lib/node_modules/.polymer-cli_npminstall/dtrace-provider/0.8.0/dtrace-provider
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/.polymer-cli_npminstall/dtrace-provider/0.8.0/dtrace-provider/scripts/install.js:19:20)

node -v
v4.7.2

**Comment by TimvdLippe** [comment]
Please open an issue on https://github.com/polymer/polymer-cli/issues if you are still experiencing this problem.
