### ISSUE TITLE
Polymer.RenderStatus not available for Polymer.Element 

### ISSUE THREAD

**Issue by thomasgieling** [Polymer/polymer#4258]
### Description
Polymer.RenderStatus is undefined when extending Polymer.Element. It is available when extending Polymer.LegacyElement

#### Steps to Reproduce
Create an Element that extends Polymer.Element and call Polymer.RenderStatus inside the connectedCallback

```
<link rel="import" href="../../bower_components/polymer/polymer-element.html">
<dom-module id="glass-app">
    <template>
        <style>
        </style>
        <h1>Hello World</h1>
    </template>
    <script>
        // Extend Polymer.Element base class
        class GlassApp extends Polymer.Element {
            static get is() { return 'glass-app'; }
            static get config() {
                return { /* properties, observers meta data */ }
            }
            constructor() {
                super();
            }
            connectedCallback() {
                super.connectedCallback();
                Polymer.RenderStatus.afterNextRender(this, function() {
                    console.log('there should be something meaningful here...')
                });
            }
        customElements.define(GlassApp.is, GlassApp);
    </script>
</dom-module>
```

#### Expected Results
Polymer.RenderStatus is available

#### Actual Results
Polymer.RenderStatus is undefined

### Browsers Affected

- [x ] Chrome
- [x ] Firefox
- [x ] Edge
- [x ] Safari 9
- [x ] Safari 8
- [x ] IE 11

### Versions

- Polymer: v2.0-preview
- webcomponents: v1

**Comment by tony19** [comment]
You need to import `polymer-legacy.html` (or the full `polymer.html`, which includes both `polymer-legacy.html` and `polymer-element.html`).

**Comment by arthurevans** [comment]
Pinging @kevinpschaaf and @sorvell on this one... Is this WAI? If so, what's the recommended approach for people using `polymer-element.html`? Import AsyncRender, or use a platform primitive like `requestAnimationFrame`/`requestIdleCallback`/`setTimeout`?

**Comment by sorvell** [comment]
Users can import `src/utils/render-status.html` to get `Polymer.RenderStatus.afterNextRender`. The method essentially does `requestAnimationFrame` + `setTimeout` and I'm somewhat ambivalent about its use v. other techniques to achieve the same end.
