### ISSUE TITLE
dom-repeat as attribute can cause scope collisions with the host element properties

### ISSUE THREAD

**Issue by ChadKillingsworth** [Polymer/polymer#4261]
### Description
This appears to only affect Polymer 1.x

The `as=""` attribute on a dom-repeat can collide and overwrite a similarly named property on the host element.

#### Live Demo
http://jsbin.com/suwupas/edit?html,js,output

#### Steps to Reproduce
Anytime a dom-repeat `as=""` attribute value is the same name as an existing host-element property, the property effects function overwrites the host element property.

This most readily occurs when property renaming with Closure-compiler is used, but can also occur by accident.

1. Clicking on a button in the live demo will alert an error.
2. Remove the `as="colliding"` and updating the binding expression and the code works as expected.

### Versions
This appears to affect Polymer 1.x versions only. Polymer 2 dom-repeats do not appear to exhibit the same behavior.

**Comment by jadce123** [comment]
GOOD
