### ISSUE TITLE
Add flags to elide events that are strictly unnecessary for downward data-flow

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#4262]
### Description
There are several cases where Polymer will fire events as a result of downward data flow (as opposed to async/user interaction thereof):
* Downward data flow to `notify: true` events
* `dom-repeat` and `dom-if` `dom-change` events
* `dom-repeat`'s `renderedCount` notifying property changes as a result of render

There should be an opt-out from these events to achieve maximum performance.

**Comment by zhaoz** [comment]
How soon do we think we can get this fixed?

**Comment by kevinpschaaf** [comment]
@zhaoz PR incoming: https://github.com/Polymer/polymer/pull/4267
