### ISSUE TITLE
[2.x] array-selector should deselect items that are replaced in the array

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#4263]
### Description
Replacing an item e.g. `this.set('items.2', newVal)` should result in the item being deselected if previously selected, in the same way that doing `this.items[2] = newVal; this.items = this.items;` would do.

#### Live Demo
http://jsbin.com/rawosus/edit?html,output

#### Steps to Reproduce
1. click replace on "a"

#### Expected results
"a" should no longer be in the selected list below the hr

#### Actual results
"a" remains in the selected list

### Versions
- Polymer: v2.x

**Comment by kevinpschaaf** [comment]
cc: @blasten, just FYI haven't forgotten this.

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/polymer/pull/4275.
