### ISSUE TITLE
www.polymer-project.org website with net::ERR_SPDY_PROTOCOL_ERROR in Chrome

### ISSUE THREAD

**Issue by majorbuild** [Polymer/polymer#4270]
The www.polymer-project.org website currently appears to be out of style. Checking the Console in Chrome shows:

GET https://www.polymer-project.org/bower_components/webcomponentsjs/webcomponents-lite.min.js net::ERR_SPDY_PROTOCOL_ERROR
/css/site.css:1 GET https://www.polymer-project.org/css/site.css net::ERR_SPDY_PROTOCOL_ERROR
/js/app.js:1 GET https://www.polymer-project.org/js/app.js net::ERR_SPDY_PROTOCOL_ERROR
/elements/elements.js:1 GET https://www.polymer-project.org/elements/elements.js net::ERR_SPDY_PROTOCOL_ERROR

May refer to the issues here: https://code.google.com/p/googleappengine/issues/detail?id=13502

**Comment by polopatel** [comment]
If you’re an Avast Antivirus user then you can add the site giving you this error to your Avast exclusion list. Sometimes about Avast seems to be triggering this error so to fix the issue we just tell Avast to ignore the pages that it does not like and the error disappears.

1. Open Avast in your desktop
2. Click on Settings
3. Click on Active Protection
4. Click on Customize for Web Shield Protection
5. Add each website separately to the URLs to exclude section.

source : [http://www.OnlyErrors.com](http://www.onlyerrors.com/err_spdy_protocol_error.html)

**Comment by husenmemon** [comment]
Well, Identified the issue deeply and it occurs frequently in Internet Browsers due to some uncommon reasons. I have listed down all the possible solutions and 99% your issue is going to resolve from one of the solution. Try them one by one and do reply which solution solved your issue.

Solutions Page: **[How to Solve Google Chrome’s Error “ERR_SPDY_PROTOCOL_ERROR”](https://howbyte.com/solve-err_spdy_protocol_error/)**

**Comment by arthurevans** [comment]
This error was related to a bug in App Engine that handled some server push requests incorrectly. We worked around it by temporarily disabling push, but this particular bug has been fixed and you shouldn't be seeing it on the Polymer site. Please open a new issue if you see this on the site.
