### ISSUE TITLE
Node distribution

### ISSUE THREAD

**Issue by eduardosada** [Polymer/polymer#4271]
### Description
On Chrome + ShadowDOM when I calling `document.body.appendChild(this);` on `attached` it doesn't move its children.

#### Live Demo
http://codepen.io/eduardosada/pen/pRwEPM

#### Expected Results
![captura de pantalla 2017-01-23 a las 18 53 11](https://cloud.githubusercontent.com/assets/1564224/22215887/3eb66ab6-e19d-11e6-86f7-bcef187f1d1c.png)

#### Actual Results
![captura de pantalla 2017-01-23 a las 18 52 58](https://cloud.githubusercontent.com/assets/1564224/22215888/3ec00184-e19d-11e6-9529-f38b8ab4bd7e.png)

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v1.7.1

**Comment by eduardosada** [comment]
I'm not sure if this is related with https://github.com/Polymer/polymer/issues/4050

**Comment by TimvdLippe** [comment]
This is still an issue with Polymer 2 (http://jsbin.com/bocumizaqa/1/edit?html,output) although I think this is actually working as intended/as specced. Not sure what we can do about this on the Polymer side.
