### ISSUE TITLE
Polymer [2.0-preview] - templatize doesn't work correct

### ISSUE THREAD

**Issue by dhrytsenko** [Polymer/polymer#4274]
I try to use and test new Polymer version from 2.0-preview branch for my element and I have one problem with `Templatizer` which worked correct in Polymer 1.x. 

### Code example
    var template = Polymer.dom(this).querySelector('template');
    this.templatize(template);
    var instance = this.stamp({item: model, column:this, value: this.default, _dataKey: notificationKey});

In console I see this error `this.templatize is undefined`.

Documentations and upgrade guide don't have any notes about changes in this part. 

### Versions
- Polymer: v2.0-preview
- webcomponents: v1

**Comment by jfrazzano** [comment]
When are you trying to stamp? before or after connected… I know this sounds like a really dumb question, cause you can’t be connected till you stamp… but there is a timing issue i have experienced that I `solved` by just letting my clock continually do undone tasks on an interval… checking to see if the tasks get done, you can do it with a generator…(which was way easier when it hoisted, you could skirt the whole issue related to delayed looks at the dom). I wanna try with a proxy, but haven’t quite gotten the hang of them yet.

**Comment by dhrytsenko** [comment]
Thank you for your notes but the problem is not in calling `stamp`. I can't have access to `templatize` function cause it is undefined. It's only avaliable in prototype of `Polymer.Templatizer` and I also can't call it by code like `Polymer.Templatizer.templatize`. It's little confusing cause I must have access to prototype. I can call it only directly from prototype `Polymer.Templatizer.prototype.templatize`

**Comment by jfrazzano** [comment]
Have you forwarded the parent props the template relies on, and where is the template coming from?  Is it a hierarchy issue? or just a random weird “no go”…

Sorry I wasn’t more help.  If you have code I will try it.

**Comment by dhrytsenko** [comment]
Hi. So, I try to test Polymer 2.0 with paper-datatable component. I work with [this file](https://github.com/David-Mulder/paper-datatable/blob/master/paper-datatable-column.html), line 280 used `templatize`. Problem with Polymer 2 in case that `templatize` is undefined. It's only avaliable inside prototype like I noticed above. I think there are new changes in API and maybe now exist another way to use it. I think I must to wait for the new stable release and new docs...
