### ISSUE TITLE
It is not working properly in IE10

### ISSUE THREAD

**Issue by flik** [Polymer/polymer#4278]
#### Live Demo

https://www.polymer-project.org/1.0/start/toolbox/set-up

#### Steps to Reproduce
I have attached screen short of ie10. 

![ie10](https://cloud.githubusercontent.com/assets/900323/22358704/ef3bebbe-e462-11e6-9dec-21694a660934.png)

**Comment by maisnamraju** [comment]
https://www.polymer-project.org/1.0/docs/browsers

Polymer is supported only on IE11 and Edge.

**Comment by TimvdLippe** [comment]
Closing per https://www.polymer-project.org/2.0/docs/browsers as IE10 is not supported.
