### ISSUE TITLE
Array object has null keys and so crashes with TypeError when rendering (dom-repeat?)

### ISSUE THREAD

**Issue by akc42** [Polymer/polymer#4279]
I have a complex variable which is the source for a complex nested set of dom-repeat templates and at the inner level a pair of dom-if templates.

The structure of the variable is

clinicians - array of -> clinician object
each clinician object has a subproperty appointments

appointments - array of -> appointment objects
appointments are of two types based on the sub-property slot 
 if slot is true then this is a minimal object with just a start and end time
 if slot is false then this is a larger object with full details of the appointment.

 Its the two dom-ifs that displays one or other of these types of appointment.

The crash 
```
polymer-mini.html:2042 Uncaught TypeError: Cannot read property 'length' of undefined(…)  polymer-mini.html:2042
    _applySplicesArrayOrder @ polymer.html:4991
    _render @ polymer.html:4842
    complete @ polymer-mini.html:2081
    Debouncer.boundComplete @ polymer-mini.html:2058
    _atEndOfMicrotask @ polymer-mini.html:2036
    window.MutationObserver.observe.characterData @ polymer-mini.html:2051
    
```
I tracked by single stepping through that _applySpicesArrayOrder and the line referenced 4991
```
for (j = 0; j < s.addedKeys.length; j++) {
```
that addedKeys was null.

The large variable (`clinicians`) that I referred to above is manipulated generally by using `this.set` and `this.push` calls.  I have another larger multilayed structure from which clinicians is copied
(its an array of weeks in a month (from first monday before start of month to first sunday after the end of the month, and within that an array of 7 days, where each day is an object which contains the `clinicians` array) also manipulated with set and push this seems to work fully. This is generally building the initial array from full appointments.

But I also manipulate the appointments array of a given clinician by using `this.splice` calls to add or remove the type of appointments that are the `slots`.  I single stepped through one of these splice calls and I can see it asking the polymer collection for a keys and getting a null answer back.  This seems to be stored with the splice record and is the cause of the null `addedKeys` that causes the crash.

Unfortunately all the code is far too large to post here, or in a jsbin. It is also private, so I don't have a public repository that I can share.

These results are with Chrome
### Versions

- Polymer: v1.7.1
- webcomponents: v0.7.23

**Comment by alshakero** [comment]
Hi! Did you solve this? I am facing exactly the same issue.

**Comment by akc42** [comment]
I found the only way to solve this (which made my code extremely complicated) was to delay by calling `this.async()`.  I think template is awaiting until the event loop before processing changes, so you have to wait until after it had a chance to update things before testing them.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with Polymer 2 for us to be able to debug and potentially fix. Polymer 2 fixes a large amount of issues, probably including this one as well.

Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with Polymer 2.  Thank you!

**Comment by akc42** [comment]
I had forgotten about this.  I doesn't happen in Polymer 2.  I took all the async calls away (which much simplified my code).  So I am happy this this is closed.
