### ISSUE TITLE
Attribute binding creates invalid double-quoted attributes

### ISSUE THREAD

**Issue by daniele-orlando** [Polymer/polymer#4286]
### Description
Polymer attribute binding creates invalid double-quoted attributes.
Example

```html
<dom-module id="k-planning-new">
    <template>
        <span class$="[[contractsWidgetClass]]"></span>
    </template>
</dom-module>
```

this produces

```html
<span class=""disabled""></span>
```

which of course is invalid.

But the strange think is that this instead behaves as expected.

```html
<dom-module id="k-planning-new">
    <template>
        <paper-dropdown-menu id="orders"
                             label="Orders"
                             vertical-align="top"
                             horizontal-align="left"
                             disabled="[[ !ordersWidgetIsActive ]]">
            <paper-listbox class="dropdown-content">
                <template is="dom-repeat" items="[[ ordersList ]]">

                    <!-- Note the class. -->
                    <paper-item class$="[[ contractsWidgetClass ]]">
                        [[ item.name ]]
                    </paper-item>
                </template>
            </paper-listbox>
        </paper-dropdown-menu>

    </template>
</dom-module>
```

producing

```html
    ...
                    <paper-item class="disabled">
                        [[ item.name ]]
                    </paper-item>
    ...
```

Tested on `class$` and `style$` attributes.

### Browsers Affected
- [x] Chrome
- [x] Safari 10

### Versions
- Polymer: v1.7.1 and v1.6.1
- webcomponents: v0.7.23

![dom](https://cloud.githubusercontent.com/assets/504386/22488528/dab5a37a-e812-11e6-973a-961938bcd8d1.png)
![prop](https://cloud.githubusercontent.com/assets/504386/22488535/e0974528-e812-11e6-80b5-f37841eee86a.png)

**Comment by daniele-orlando** [comment]
As workaround I'm using this code (that really sucks):
```
<!-- Workaround to make class=$ works. -->
<template is="dom-if" if=""> -->
    <span class$="[[ model.status ]]"></span>
</template>
```

**Comment by TimvdLippe** [comment]
@daniele-orlando Could you create a JSBin which shows this bug in action? Thanks!

**Comment by daniele-orlando** [comment]
Hello dear, I created an example on JSBin very similar in the behavior but the bug doesn't show up in that context. Even in my App in some elements the binding to class works as expected, but in other elements the same code doesn't work.
This was so frustrating that at the end I moved my entire codebase to the usage of `reflectToAttribute`, styling my elements based on custom attributes.

**Comment by TimvdLippe** [comment]
> It was so frustrating that at the end I moved my entire codebase to the usage of reflectToAttribute, styling my elements based on custom attributes.

This is actually the solution we advice, if you want to add styling based on properties. :smile: 

If you ever are able to reproduce this bug, please reopen this issue with the JSBin so that we can have a look and fix it. Thanks!

**Comment by daniele-orlando** [comment]
Thanks!
