### ISSUE TITLE
Interface Definition Needed to Describe the Config Getter

### ISSUE THREAD

**Issue by ChadKillingsworth** [Polymer/polymer#4292]
For 2.0, Closure-compiler needs an interface to provide the type information for the `config` getter. This information will be needed both in the Polymer source (for cases where the source is included in a compilation) and in an extern (for cases where the library is treated as an external dependency).

Unless someone beats me to it, I'll submit a PR with the interface definition. Feel free to bikeshed on the name of the interface. Once settled though, it will be hard coded into the PolymerPass of Closure-compiler.

CC @justinfagnani and @azakus

**Comment by justinfagnani** [comment]
I talked to @azakus briefly about this today, and I don't think he's at this point yet, so a PR will be fine.

As for the color of the shed: `ElementConfiguration`?

**Comment by azakus** [comment]
`ElementConfiguration` sounds fine to me. I'll try to post a rough approximation in a PR for you both to review.

**Comment by azakus** [comment]
@ChadKillingsworth, @justinfagnani How does this look: https://github.com/Polymer/polymer/commit/6cad303c147899cc21c23e74267b808e57e38218 ?

**Comment by azakus** [comment]
FWIW, I need to verify if `properties: { foo: 'bar' }` is still supported as an implied `properties: {foo: {value: 'bar'}}`

**Comment by azakus** [comment]
Ah, I forgot the things that aren't properties

**Comment by ChadKillingsworth** [comment]
Can the config have listeners and observers? That looks like just the `properties` key definition.

**Comment by ChadKillingsworth** [comment]
Nm - you got to the same conclusion...

**Comment by arthurevans** [comment]
`foo: 'bar'` was 0.5.

1.x/2.x supported shorthand is `foo: String`, `foo: Object` etc.

Pretty sure config only takes `properties` and `observers`... No `listeners` in 2.x.

**Comment by azakus** [comment]
@arthurevans thanks!

@ChadKillingsworth updated with 5c5ce0eb

**Comment by azakus** [comment]
Better comparison: https://github.com/Polymer/polymer/compare/2.0-preview...element-config-extern

**Comment by azakus** [comment]
Looks like we may change
```js
static get config() {
  return {
    properties: {},
    observers: []
  }
}
```
 into
```js
static get properties() {
  return {}
}

static get observers() {
  return [];
}
```

**Comment by ChadKillingsworth** [comment]
I'm all for that change

**Comment by ChadKillingsworth** [comment]
So how about `Polmer.ElementPropertyConfiguration`? The type for observers are just `!Array<string>` so we won't need one for that.

**Comment by azakus** [comment]
I named it `Polymer.ElementProperties` in https://github.com/Polymer/polymer/commit/68b37f1485708e9ef48b45b50c1f66093f9f8a15

**Comment by ChadKillingsworth** [comment]
Great! I've updated google/closure-compiler/pull/2338 to use that now. Let the testing commence!
