### ISSUE TITLE
Empty variable is printed as a space character

### ISSUE THREAD

**Issue by jehna** [Polymer/polymer#4295]
### Description

Empty variable is printed as a space ` ` character when printed with `[[variable]]`.

This makes it impossible to use the `:empty` CSS selector.

#### Live Demo
http://jsbin.com/hotufuqetu/1/edit?html,console,output

#### Steps to Reproduce

1. Create a new Polymer component with a property called `empty` with type `String`
2. Do not assign any value for the property
3. Create `div` inside the component
4. Place the variable inside the div: `<div>[[empty]]</div>`

#### Expected Results
The `div` should be empty

#### Actual Results
The `div` has one space letter inside

### Browsers Affected

- [x] Chrome

### Versions
- Polymer: v2.0-preview

**Comment by arthurevans** [comment]
I think this is a duplicate of the 1.x issue, https://github.com/Polymer/polymer/issues/3086, which is related to a binding workaround required by IE.

**Comment by jehna** [comment]
Tested the workaround, it's still working fine for the 2.0 version. Closing this issue as duplicate.
