### ISSUE TITLE
[1.8.0] breaking change for extends:"script"

### ISSUE THREAD

**Issue by nathfisher** [Polymer/polymer#4303]
### Description
After upgrading to 1.8.0 when creating elements with extends:'script' the change to `_getExtendedNativePrototype(tag)` breaks any `<script is="my-el">` elements. 

After some debugging the error seems to occur when copying Polymer.Base props to the HTMLScriptElement and `async` is encountered. Accessing `async` or any other defined property on the script prototype seems to exhibit the same behavior. See below Demos for example of this behavior.
This is apparent with `<script>` because of the shared async function on Polymer.base and the async prop of HTMLScriptElement.

Previously new props were merged via Object.defineProperty but now are overridden via assignment and so didn't encounter the same issue.

Other native elements may experience the same issue if there is a property name collision with Polymer.Base

problematic commit:
https://github.com/Polymer/polymer/commit/3a2c841469c82376dbd76ad06eefd4b892a4ae5a#diff-4b1f207d4738f14c71c357aed8463ddbR562

I know that is= element extension is going away in v2 but for now any elements which `extend:"script"` are going to be broken with 1.8.0.

I personally have removed the element I wrote that was affected by this bug but I'm not sure how many other devs are going to have encountered the same problem.

#### Live Demo
v1.8.0 - Broken:
https://plnkr.co/edit/MDb0SFbqrZ9AvwCtEuD0?p=preview

v.1.7.1 - Working:
http://plnkr.co/edit/uN8zifb5Ee7EtYc0lGtq?p=preview

Accessing properties on <script> prototype:
https://plnkr.co/edit/q0m5HhGbH61SPlOWckZz?p=preview

### Browsers Affected
- [ x ] Chrome
- [ x ] Firefox
- [ ? ] Edge
- [ ? ] Safari 9
- [ ? ] Safari 8
- [ ? ] IE 11

### Versions
- Polymer: v1.8.0

**Comment by TimvdLippe** [comment]
Closing this issue as native element inheritance is not supported in 2.x. Rather, we advise you to compose a `<script>` element instead of overwriting the native behavior of the `<script>` element.
