### ISSUE TITLE
[2.0 preview] Polymer build failing caused by Templatizer behavior

### ISSUE THREAD

**Issue by 200Puls** [Polymer/polymer#4310]
### Description
When using polymer-cli@next and building a project with iron-list an error is thrown because the build tool does not recognize the syntax of the templatizer behavior. 

### Expected outcome
Build should be successful.

### Actual outcome
'SyntaxError: Unexpected token: name (Wt)' }
error:   In /bower_components/iron-list/iron-list.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.Templatizer`. Did you import it? Is it annotated with @polymerBehavior?
error:   Promise rejection: Error: 1 error(s) occurred during build.
error:   Error: 1 error(s) occurred during build.
    at BuildAnalyzer._done (C:\Users\Puls\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\polymer-build\lib\analyzer.js:201:25)
    at BuildAnalyzer.<anonymous> (C:\Users\Puls\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\polymer-build\lib\analyzer.js:185:26)
    at next (native)
    at fulfilled (C:\Users\Puls\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\polymer-build\lib\analyzer.js:17:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)

### Steps to reproduce
1. Put iron-ist element in the page.
2. Call 'polymer build' using polimer-cli@next

**Comment by beenotung** [comment]
typo in steps to reproduce 1?

**Comment by 200Puls** [comment]
yeah  sorry meant iron-list

**Comment by fabysdev** [comment]
Had the same issue.

It worked after adding `/** @polymerBehavior Polymer.Templatizer */` in `/bower_components/polymer/src/legacy/templatizer-behavior.html`.


```
...
(function() {
    'use strict';
    /** @polymerBehavior Polymer.Templatizer */
    let Templatizer = {
...
```

**Comment by FredKSchott** [comment]
This should no longer break your build on the latest version of `polymer-cli@next`. 

@200Puls @beenotung @fabysdev can you try updating the CLI and re-running to confirm?

**Comment by fabysdev** [comment]
@FredKSchott build works again, thank you

**Comment by 200Puls** [comment]
@FredKSchott Yep its working again. Thanks!

**Comment by kofidazy** [comment]
Currently facing this issue when i try to build 

```info:    Clearing build/ directory...
info:    (default) Building...
error:   Promise rejection: Error: ENOENT: no such file or directory, open '/Users/kofiaddo-nyarko/Documents/payhu
b-app/bower_components/polymer/lib/legacy/templatizer-behavior.html'
error:   Error: ENOENT: no such file or directory, open '/Users/kofiaddo-nyarko/Documents/payhub-app/bower_compone
nts/polymer/lib/legacy/templatizer-behavior.html'
    at Error (native)```
