### ISSUE TITLE
Add a new website (StockTik) to Who's-using-Polymer?.md

### ISSUE THREAD

**Issue by Phara0h** [Polymer/polymer#4313]
Could you please add this line to the wiki please? @ebidel 

`- StockTik: A free real time stock ticker [StockTik](http://stocktik.com/)`

Thanks for your time sir!

**Comment by ebidel** [comment]
This looks like a demo app / parked domain.

https://twitter.com/stocktik

**Comment by Phara0h** [comment]
Its not, I just don't update my twitter. lol

**Comment by Phara0h** [comment]
@ebidel Any updates on this mate?

**Comment by Phara0h** [comment]
Need anything further from me to get this pushed through?

**Comment by TimvdLippe** [comment]
Thanks @Phara0h for your suggestion and using Polymer. Sadly as we can not possibly list every single Polymer website, we limit the wiki page to the most notable ones.

**Comment by Phara0h** [comment]
@TimvdLippe  Bit insulting since some of those sites doesn't even resolve an IP. like http://braid.io/

**Comment by TimvdLippe** [comment]
@Phara0h I have removed that website from the wiki. These removals are exactly the reason we are now reluctant to add more websites to the list. Rather we would like to remove those that no longer comply. Thanks for your understanding!
