### ISSUE TITLE
getContentChildren is broken

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#4315]
In a 2.0 hybrid element, `getContentChildren` with no selector returns an empty list, even when the equivalent (`Polymer.dom(slot).getDistributedNodes()`) returns a valid list.

`getContentChildren` when run with a selector fails with the following error:

error TypeError: content.getDistributedNodes is not a function
    at HTMLElement.getContentChildNodes (https://polygit.org/polymer+:2.0-preview/webcomponentsjs+:v1/shadydom+webco…omponents+:master/components/polymer/src/legacy/legacy-element.html:386:34)

#### Live Demo

https://jsbin.com/hoxeza/edit?html,output

#### Steps to Reproduce

Run demo

#### Expected Results

No error, list matches getDistributedNodes();

### Versions

- Polymer: v2.0-preview from polygit
- webcomponents: v1 from polygit

**Comment by kevinpschaaf** [comment]
Fixed via https://github.com/Polymer/polymer/pull/4330.
