### ISSUE TITLE
58dcbc96d2863029c1176fa31a182ee0f0729e23 made private some functions of Polymer.Gestures used by other Polymer elements 

### ISSUE THREAD

**Issue by oi-oy-div** [Polymer/polymer#4317]
There are several cases in 2.0-preview branch where Polymer.Gestures is calling a function which was made private by 58dcbc96d2863029c1176fa31a182ee0f0729e23.

Examples:
* Polymer.Gestures.findOriginalTarget in paper-dropdown-menu.html
* Polymer.Gestures.add                       in iron-overlay-manager.html

**Comment by 200Puls** [comment]
I just encountered the same problem.

**Comment by sorvell** [comment]
Fixed by #4321
