### ISSUE TITLE
Polymer.Class() 's function are not in this  like this.function

### ISSUE THREAD

**Issue by hzmnet** [Polymer/polymer#4319]
#### Live Demo

https://jsbin.com/ruqomijeta/edit?html,console,output

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: vX.X.X
- webcomponents: vX.X.X 

`    <script>
      var test = Polymer.Class({
        
         factoryImpl: function () {
           try{
              this.add('test')  // 
           }catch(e){
             console.log(e)
           }
          
         },
                add: function (domain) {
            console.log('ok')
        },

      });
      
      aa=new test();
    </script>`

**Comment by azakus** [comment]
If you use `Polymer.Class` you have to register the class with `document.registerElement` yourself.
This is shown in the documentation: https://www.polymer-project.org/1.0/docs/devguide/registering-elements#element-constructor

Here's a JSBin example inspired by your code: https://jsbin.com/wiririg/edit?html,console,output

**Comment by hzmnet** [comment]
I knew. but if we use to register. than it is a element not a simple class
