### ISSUE TITLE
Circular import cause application unable to start on IE, Firefox

### ISSUE THREAD

**Issue by crsici** [Polymer/polymer#4325]
It's a mistake to put a circular import into component but it's worth to note it here since there are no provided information or error log to find out the root cause.
Steps to reproduce:
1. Create polymer-starter-kit
2. In src/my-app.html add <link rel="import" href="my-app.html">
Application can't start on IE or FF but it's still working on Chrome. 
Polymer version:  1.4.0
FF: 23.0.1
IE:  11.0.96

**Comment by azakus** [comment]
This issue was moved to PolymerElements/polymer-starter-kit#984
