### ISSUE TITLE
Expose `observeNodes` independent from `Polymer.dom`

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#4336]
The `observeNodes` api should be exposed separately from the legacy api `Polymer.dom` as it is still needed when using `Polymer.Element` and the like.

**Comment by arthurevans** [comment]
Are we adding it to `Polymer.Element`, or making it available elsewhere?

Is this not superseded by `slotchange` in 2.0? Or are we retaining it because it has better ergonomics?

I know: questions, questions.

**Comment by kevinpschaaf** [comment]
@arthurevans `Polymer.FlattenedNodesObserver` will be loadable alacarte via `/src/utils/flattened-nodes-observer.html` (soon to be `/lib/utils/...`).

```js
new Polymer.FlattenedNodesObserver(node, info => {
  console.log(info.target, info.addedNodes, info.removedNodes);
});
```

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/polymer/pull/4337.
