### ISSUE TITLE
Polymer.dom(event).localTarget returns incorrect target

### ISSUE THREAD

**Issue by jaichandra** [Polymer/polymer#4341]
### Description
Polymer.dom(event).localTarget returns incorrect target
The `Polymer.dom(event).localTarget` returns incorrect target (`content`) when the element itself is wrapped inside another element and content is passed as Light DOM.

#### Live Demo
https://jsfiddle.net/kleptomac/v7kjyk7a/

#### Steps to Reproduce
Try above example with and without ShadowDOM

#### Expected Results
`Polymer.dom(event).localTarget` should return the element reference and not `<content>` 

#### Actual Results
`Polymer.dom(event).localTarget` return reference to the `content` element.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v1.8.0
- webcomponents: v0.7.24

**Comment by jaichandra** [comment]
Here's how I am trying to fix the `DomApi` for now. Please let me know if this is going to mess up the whole event flow.
```
(function(){
    Object.defineProperty(Polymer.DomApi.ctor.Event.prototype, 'localTarget', {
        get: function() {
            var current = this.event.currentTarget;
            var currentRoot = current && Polymer.dom(current).getOwnerRoot();
            var p$ = this.path;
            var actualTarget;
            for (var i = 0; i < p$.length; i++) {
                // keep track of last element that has its own scope
                if (p$[i].className && p$[i].className.indexOf('x-scope') > -1)
                    actualTarget = p$[i];
                if (Polymer.dom(p$[i]).getOwnerRoot() === currentRoot) {
                    if (p$[i].localName === 'content' || p$[i].localName === 'slot') {
                        return actualTarget;
                    }
                    return p$[i];
                }
            }
        }
    });
})(Polymer);
```

**Comment by jaichandra** [comment]
The above problem continues to exist in v1.9.1. Event-retargeting works fine when Shadow DOM is enabled. Its a problem with Shady DOM.

**Comment by daniele-orlando** [comment]
Same here.
