### ISSUE TITLE
Getting rid of style includes for better developer experience

### ISSUE THREAD

**Issue by AndreasGalster** [Polymer/polymer#4351]
Currently when using shared styles, we have to use dom modules, which is fine, though I find the usage in the actual components extremely inconvenient, especially for something like a bootstrap-like framework.

https://github.com/Polymer/docs/commit/e7a259ec16284658376e7d3dd85acea5aafb704a#diff-c0f20db21aa9f0874dc0679743db2f1aR361

With 2.0 you're sticking with `<style include='mystyle'>`, which really makes no sense when using a structure such as bootstrap, where the entire framework is built on top of multiple imports, say one for typography, one for variables, one for colors, one for alignment classes, etc. and in the end you can combine them all in one main file, leaving the developer to choose if they just want to import the entire thing or sub-parts of it. If you want to include the entire framework, you'd need to style include every single dom module. 

Are there any plans moving away from the style include syntax in the future? We are already importing the dom module in our component anyway. I understand that you are probably doing style include because otherwise Polymer wouldn't know that this needs to be included as a shared style in the component, but perhaps we can somehow move the style declaration into the actual dom module, so that we don't need to include dozens of styles whenever we want to import multiple shared styles?

This is the challenge I see:

```
<link rel="import" href="my-framework.html">

<dom-module id="new-element">
 	<template>
 		<style include="my-style-module1 my-style-module2 my-style-module3 my-style-module4 my-style-module5 my-style-module6 my-style-module7 my-style-module8 my-style-module9 my-style-module10 my-style-module11 my-style-module12 my-style-module13 my-style-module14"></style>
 	</template>
 </dom-module>
```

It's hard to 1) remember all the names of the styles to include and 2) just adding all those includes is not end-user friendly. Maybe declare something like the below if we know the dom module is a shared style instead of a full webcomponent?

```
<dom-module shared-style id="my-style-module">
```

**Comment by arthurevans** [comment]
This isn't a direct answer to your question, but it occurred to me that you could probably combine style modules like this:

```
  <dom-module id="style-one">
    <template>
      <style>
        :host { 
          --custom-one: red;
        }
      </style>
    </template>
  </dom-module>
  
  <dom-module id="style-two">
    <template>
      <style>
        :host {
          --custom-two: blue;
        }
      </style>
    </template>
  </dom-module>
  
  <dom-module id="style-group">
    <template>
      <style include="style-one style-two">
      </style>
    </template>
  </dom-module> 
```
This appears to work, so you could create your combined style module and import that instead of having a giant list of sub-modules. Whether it's designed to work this way, I couldn't say, but at present it appears to work.
