### ISSUE TITLE
static get config() is not called any more

### ISSUE THREAD

**Issue by tirithen** [Polymer/polymer#4353]
### Description

When I removed and refetched my bower dependencies for Polymer#2.0-preview I noticed that the static config method is not called any more which makes it impossible to define properties. Maybe something was added recently that broke this part. There is a live demo below, when I run locally with updated dependencies the property that I declared and assigned is undefined. Yesterday everything was working fine. The JSBin I provide does not run, but that seem more because of the service than the code I put in there.

#### Live Demo

https://jsbin.com/fuwuliveho/edit?html,console,output

It won't run the script, but there is at least the code

#### Steps to Reproduce

1. Copy code from JSBin
2. Save to file locally
3. Fix the two dependencies
4. Load the page in a browser with the console open

#### Expected Results

The property a-value/aValue should have the value "hello world".

#### Actual Results

The property a-value/aValue is undefined and the static get config method does not seem to be called any more.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: 2.0-preview
- webcomponents: v1

**Comment by tony19** [comment]
See https://github.com/Polymer/polymer/pull/4332. The `config` getter was split out into individual getters for `properties` and `observers`.
