### ISSUE TITLE
Polymer 2.0 preview Issue - Computed Bindings stopped working with this commit

### ISSUE THREAD

**Issue by marybeshaw** [Polymer/polymer#4354]
### Description
I updated my polymer 2.0 preview installation, and computed bindings as well as individual observers stopped working.

Computed binding (such as _getContainerClasses below) is not called:
```HTML
<div class$="[[_getContainerClasses(centered)]]"></div>
```

Individual Observer function such as (observerFunction below) is not called:
```JavaScript
      static get config() {
        return {
          properties: {
            property: {
              type: "String",
              value: "[]",
              observer: "observerFunction"
            }
          }
        }
      }
```

#### Live Demo
Spinner element (which uses a computed binding; I simplified it for sharing):
http://jsbin.com/bafide/1/edit?html,output

Unit test for spinner element:
http://jsbin.com/qunuge/1/edit?html,output

#### Steps to Reproduce
When I pin to commit Polymer/polymer#5c1b11ff0f0b96665f40179e53f2d21a955ef605, unit tests in the second jsbin work.
When I pin to commit Polymer/polymer#38fa1f6b09d03f53115b741a8ce0c27b8bd84f30, the same unit tests do not work.

#### Expected Results
When I update my installation of Polymer/polymer#2.0-preview, computed bindings (and individual observers) should work.

#### Actual Results
When I update my installation of Polymer/polymer#2.0-preview, computed bindings (and individual observers) DO NOT work.

### Browsers Affected

- [X] Chrome

### Versions

- Polymer: v2.0-preview
- webcomponents: v1

**Comment by miztroh** [comment]
``config`` has been replaced with ``properties`` and ``observers``.  See the updated README.

**Comment by MartinsThiago** [comment]
Thks @miztroh

**Comment by marybeshaw** [comment]
Thanks for the information.  I missed that update somehow.
