### ISSUE TITLE
Change URL handling in element templates

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#4357]
Users have requested more flexibility about how urls are dealt with in element templates. See, for example, issue #4213. We plan to change this behavior in Polymer 2.x.

The root problem stems from the following, given: 
```
<template>
  <img src="foo/bar.jpg">
</template>
```

What URL should this `src` be resolved against?

There are multiple answers that make sense: (1) the URL of the HTMLImport in which the element is defined, (2) the main document, (3) some other URL where all page resources are.

Polymer 1.x and related tools had the following, somewhat odd, rules. Inside element templates, the following URLs were re-written to be relative to the HTMLImport in which the element was defined:
* URLs in `<style`> elements
* URLS in attributes: `src`, `style`, `href`, `url`
* URLS in `<form>`'s attribute: action

URLs inside bindings were not re-written. Polymer 1.x provided a `resolveUrl` method that could be called to create a binding with an element HTMLImport document relative URL.

Specifically users have [complained](https://github.com/Polymer/polymer/issues/4213) that it especially does not make sense to re-write `href` attributes for `<a>` elements as this is almost never what the user wants.

**Comment by sorvell** [comment]
Our plan to address this issue is to:
1. continue to re-write URL's in element template `<style>` elements.
1. *not* re-write any URL's in element attributes.
1. add element properties `importPath` and `mainDocPath`. Users can use these properties to easily and explicitly configure URLs. These properties will have defaults but can be overridden. 

To customize how URLs in `<style>` elements are re-written, override the `mainDocPath` property (possibly `stylePath`?).

To create an element URL relative to the element import document:

`<img src="[[importPath]]/foo.jpg">`

To create a main document relative URL:

`<a href="[[mainDocPath]]/routes/main">`

Note that the `mainDocPath` usage is not required, but it is necessary for users of Hybrid mode. This will instruct Polymer 1.x to scope the url relative to the main document. (This feature will need to be added to Polymer 1.x.)

**Comment by kevinpschaaf** [comment]
Resolved via https://github.com/Polymer/polymer/pull/4360 and https://github.com/webcomponents/html-imports/issues/44.

Issue for 1.x forward compatibility added here: https://github.com/Polymer/polymer/issues/4367
