### ISSUE TITLE
Getting "TypeError: Polymer.BaseDescriptors is undefined" on FIREFOX when upgrading to Polymer 1.8

### ISSUE THREAD

**Issue by gitact** [Polymer/polymer#4358]
Upgrading our code from Polymer 1.7 to Polymer 1.8.1 (but it seems the same for Polymer 1.8.0)
i am getting "TypeError: Polymer.BaseDescriptors is undefined" on Firefox 51.0.1
Please note: the project is perfectly working on Chrome (and on Firefox as well if downgrading to Polymer 1.7 )

Polymer 1.8.1
Webcomponents 0.7.24
Firefox 51.0.1

This is a simplified sample page
```
<html>
    <head>
        <title>Test Polymer 1.8</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="bower_components/webcomponentsjs/webcomponents.js"></script>
        <link rel="import" href="bower_components/polymer/polymer.html">
    </head>
</html>

```
Seems to cause on FF "TypeError: Polymer.BaseDescriptors is undefined" 
(followed from other "TypeError: Polymer.DomModule is undefined" and so on)

Any suggestion?

**Comment by web-padawan** [comment]
Please use `webcomponents-lite.js`.

**Comment by gitact** [comment]
okay
