### ISSUE TITLE
Change default dirty check strategy back to strict, add mutable helper

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#4359]
In Polymer 2.0-preview, we made a shift from strict equality dirty checking on all accessors to gate property effect work such as binding and observers, to only dirty checking primitive values and allowing Objects and Arrays set to accessors to always cause side effects.  This was due to a raft of 1.x feedback where users were confused when deep mutations to an object graph (where one or more ancestor objects of the graph did not change) resulted in stale data.

However, in cases where users were using immutable patterns already (as espoused by e.g. redux and other top-down state management libraries), this actually regressed performance since it causes more work to be done to propagate data that didn't actually change.  As it were, those patterns resulted in a perfect fit for Polymer 1.x's strict equality checking and are likely to be patterns we see more and more of in the future.

The fact that this was a breaking change, and after measuring the real-world performance regression in top-down immutable benchmarks (such as [dbmon](http://mathieuancelin.github.io/js-repaint-perfs/)), we're inclined to revert back to strict equality dirty checking at the accessor, and instead make the current "mutable" pattern (skipping dirty-checking for objects & arrays) opt-in via a supported class mixin (and legacy behavior) and settings on e.g. `dom-repeat`.

**Comment by kevinpschaaf** [comment]
Resolved via https://github.com/Polymer/polymer/issues/4361

**Comment by tomusiaka2** [comment]
I'm running into an issue when trying to use `Polymer.MutableData`. According to [documentation](https://www.polymer-project.org/2.0/docs/devguide/data-system#mutable-data): 

> This mutable data mode also lets you batch several changes before invoking property effects:
> ```
> this.property.arrayProperty.push({ name: 'Alice' });
> this.property.stringProperty = 'new value!';
> this.property.counter++;
> this.notifyPath('property');
> ```

Unfortunately, `notifyPath` does not work for the array push when current element is  inside of `dom-repeat`.

Here is an example that worked perfectly fine before this change (I checked out commit 4a6e06d39955e72e8a5c14a45557b1ed938e875c to verify, at that time I did not use  `Polymer.MutableData`).

In my main app element I have:

```html
<template is="dom-repeat" items="{{myData.nameSets}}">
  <checking-mutable-data names="{{item.names}}" name-set="{{item}}"></checking-mutable-data>
</template>
```

and

```javascript
static get properties() {
  return {
    myData: {
      type: Object,
      notify: true,
      value: {nameSets: [{names: ['name']}]}
    }
  }
}
```

This is basically using `dom-repeat` on my element. 

Then, here is now my custom element looks:

```html
<link rel="import" href="components/polymer/polymer-element.html">
<link rel="import" href="components/paper-button/paper-button.html">
<dom-module id="checking-mutable-data">
  <template>
    <style>
      
    </style>
    <p>nameSet.names:</p>
    <ul>
      <template is="dom-repeat" items="[[nameSet.names]]">
        <li>[[item]]
      </template>
    </ul>
    <p>names</p>
    <ul>
      <template is="dom-repeat" items="[[names]]">
        <li>[[item]]
      </template>
    </ul>
    <p><paper-button on-click="addName">Add Name</paper-button><paper-button on-click="reset">Reset</paper-button></p>
  </template>

  <script>
    class CheckingMutableData extends Polymer.MutableData(Polymer.Element) {
      static get is() { return 'checking-mutable-data' }
      
      static get properties() {
        return {
          nameSet: {
            type: Object,
            notify: true
          },
          names: {
            type: Object,
            notify: true
          }
        };
      }
      
      connectedCallback() {
        super.connectedCallback();
      }
      
      addName() {
        this.nameSet.names.push('name '+Math.random());
        this.notifyPath('nameSet');
      }

      reset() {
        this.nameSet = {names: ['reset name']};
        this.notifyPath('appData');
      }
    }
    
    customElements.define(CheckingMutableData.is, CheckingMutableData);
  </script>
</dom-module>
```

If I run this on a commit before these changes, so for example 4a6e06d39955e72e8a5c14a45557b1ed938e875c (without the `Polymer.MutableData` part), it works like you would expect: clicking "Add name" adds a name with some random number to both lists. Clicking reset, updates both lists to have a single name "reset name". 

If I run this on when these changes were merged: 8dc288673c9f1ef3143d61f76830fb121ef395eb, Add name does not work at all while Reset works (so the example in the documentation doesn't work but setting a new array works fine).

If I change reset line to: `this.nameSet.names = ['reset name'];`, it gets even crazier: clicking on "Add name" does nothing, then clicking on "Reset" does nothing, but then clicking again on "Add name" shows the reset name and a new name added in the `nameSet.names` list but does not show it in the `names` list. Then, clicking on "Add name" again does nothing. So something does not seem to be right there.

**Comment by arthurevans** [comment]
@tomusiaka2 For this use case, you need to set the `mutableData` property on the dom-repeat, as well, as described here: https://www.polymer-project.org/2.0/docs/devguide/data-system#optional-mutable-data-for-reusable-elements

**Comment by tomusiaka** [comment]
Thank you, just adding `mutable-data` attribute works. With that attribute it also works well now when on reset I update the array only `this.nameSet.names = ['reset name'];`.

The way I understood the documentation was that if `mutable-data` attribute was to be used I should do `extends Polymer.OptionalMutableData(Polymer.Element)`. However, that did not work but it works well if I keep it at `Polymer.MutableData`:

```javascript
class CheckingMutableData extends Polymer.MutableData(Polymer.Element) {
```

**Comment by tomusiaka2** [comment]
Thank you, just adding `mutable-data` attribute works. With that attribute it also works well now when on reset I update the array only `this.nameSet.names = ['reset name'];`.

The way I understood the documentation was that if `mutable-data` attribute was to be used I should do `extends Polymer.OptionalMutableData(Polymer.Element)`. However, that did not work but it works well if I keep it at `Polymer.MutableData`:

```javascript
class CheckingMutableData extends Polymer.MutableData(Polymer.Element) {
```

**Comment by arthurevans** [comment]
@tomusiaka2 Thanks for the update. I understand the confusion. I'll open a ticket to update the docs here to make this clearer.
