### ISSUE TITLE
Error in template extension example (2.0-preview)

### ISSUE THREAD

**Issue by jouni** [Polymer/polymer#4362]
The example in the source code of `element-mixin.html` does not work as expected. The added element “This came from MySubClass” does not end up in the rendered DOM.

Changing [line 487](https://github.com/Polymer/polymer/blob/2.0-preview/lib/mixins/element-mixin.html#L487) from `memoizedTemplate.appendChild(subContent);` to `memoizedTemplate.content.appendChild(subContent);` fixes the issue.

**Comment by kevinpschaaf** [comment]
Thank you!  Fixed in https://github.com/Polymer/polymer/commit/e14c7558092455ee0d208fb74721fa54f18c9533
