### ISSUE TITLE
No getComputedStyleValue on Polymer.Element?

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#4374]
I suspect it's used significantly less frequently that `updateStyles()`, but it seemed kind of funky to me that we had a facade for `updateStyles` on `Polymer.Element`, but not for `getComputedStyleValue`. 

Currently documented solution for this is:

```
if (ShadyCSS) {
  style = ShadyCSS.getComputedStyleValue('--something');
} else {
  style = getComputedStyle(this, '--something');
}
```
Which hopefully I got right. If not, it's here:

https://github.com/Polymer/docs/blame/master/app/2.0/docs/devguide/custom-css-properties.md#L361

**Comment by kevinpschaaf** [comment]
At one point we discussed patching `getComputedStyleValue` to make the custom property handling in the shim transparent... @azakus ?

**Comment by kevinpschaaf** [comment]
This issue was moved to webcomponents/shadycss#83

**Comment by kevinpschaaf** [comment]
The plan of record will be for `shadycss` to patch `window.getComputedStyle()` to have the return object's `getPropertyValue()` to return the correct value for custom properties.

@arthurevans note the correct incantation is the following (note the native syntax in the else clause is what we would shim to work transparently; the syntax is a bit ugly but that's the native API):

```
if (window.ShadyCSS) {
  style = ShadyCSS.getComputedStyleValue(el, '--something');
} else {
  style = getComputedStyle(el).getPropertyValue('--something');
}
```

**Comment by ThomasSchellenbergNextCentury** [comment]
@kevinpschaaf In your example, what is `el`?  Is it supposed to be `this`?

Also, should the documentation be updated with your example? It's currently showing the old incarnation:  https://www.polymer-project.org/2.0/docs/devguide/custom-css-properties#style-api

**Comment by arthurevans** [comment]
@ThomasSchellenbergNextCentury Oops. Yep, we corrected that in the upgrade guide, but missed that example. I've opened a PR to fix that now, thanks!

`el` in this case is the element you want to get the style from. It doesn't have to be `this`, of course. The original example was written that way because it was replacing the `getComputedStyleValue` method on Polymer 1.x elements.
