### ISSUE TITLE
Mini suggestion; update the GitHub link

### ISSUE THREAD

**Issue by abdonrd** [Polymer/polymer#4375]
Right now the GitHub link is `https://www.polymer-project.org/1.0/`

<img width="1012" alt="screen shot 2017-03-04 at 12 30 47" src="https://cloud.githubusercontent.com/assets/1007051/23578405/715c8cd6-00d6-11e7-8c6c-c10ef90b9f60.png">

I suggested to update as `https://www.polymer-project.org`

<img width="1012" alt="screen shot 2017-03-04 at 12 30 47" src="https://cloud.githubusercontent.com/assets/1007051/23578414/b6455c74-00d6-11e7-9ab5-e80826fca3d9.png">

**Comment by kevinpschaaf** [comment]
Done! Thanks.
