### ISSUE TITLE
How to serve updated app to user?

### ISSUE THREAD

**Issue by wingliu0** [Polymer/polymer#4376]
Users' browser always cached the html imported with <link> tag
During development stage, we can do hard reload. But it is impossible to do that on users' browser. 
I have tried location.reload(true). it doesn't work.
Any method other than `<link rel="import" href="xxx.html?ver=123">`?

**Comment by web-padawan** [comment]
You have to choice one of the options:
1. Use service worker features (but this won't work in Safari and IE)
2. Use finger-printing, e. g. via [gulp-rev-all](https://github.com/smysnk/gulp-rev-all). This is cross-browser and not very hard to implement. I suggest doing this as a final build step after running `polymer-build`.

**Comment by kevinpschaaf** [comment]
HTML imports respect normal cache policies set via server headers, the same as any other resource, so this is a general web development issue, not specific to Polymer.  You'll either need to decide on a suitable cache policy such as a lower [`max-age` or `must-revalidate`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) header, or else use the solutions @web-padawan pointed you to.
