### ISSUE TITLE
[2.0] BC with old behaviors

### ISSUE THREAD

**Issue by dam0vm3nt** [Polymer/polymer#4378]
It would be nice to provide a `LegacyMixin` to enable using v1 behaviors with v2 components. At the moment this is not possible because using `Polymer.mixinBehaviors` on an ES6 class assumes you are starting from a component description (`info`) and it creates another class loosing the original one.

**Comment by miztroh** [comment]
Can you explain what it is that you're losing with this approach?

```JavaScript
class XClass extends Polymer.mixinBehaviors([MyBehavior, MyBehavior2], Polymer.Element) {
  static get is() { return 'x-class'}

  ...
}

customElements.define(XClass.is, XClass);
```

**Comment by dam0vm3nt** [comment]
The problem in that I cannot apply that use case because I've already got a class to which I must apply the behaviors:

    newClass = Polymer.mixinBehaviors([MyBehavior,MyBehavior2],myOldClass);

So the original class (`myOldClass`) get replaced [here](https://github.com/Polymer/polymer/blob/master/lib/legacy/class.html#L104) and then I loose all the metadata because `info.properties` is null in that case (they are already in `info.constructor.properties`).

Just to give more context I'm trying to support Polymer for Dart (see [here](https://github.com/polymer-dart)). My class, to which I must add behaviors is a Dart class translated to ES6 using the new `DDC` (see [here](https://github.com/polymer-dart/polymer_element/blob/master/lib/src/js/polymerize.js#L106)).

**Comment by dam0vm3nt** [comment]
I think that one could just test `typeof info === 'function'` and decide whenever or not to use `GenerateClassFromInfo` or not.

**Comment by sorvell** [comment]
I don't grok the issue here. Here is a jsbin that shows extending an element that has meta-data via `Polymer.mixinBehaviors`. If possible, can you create a version of the jsbin showing the issue?

http://jsbin.com/lahomu/edit?html,output

**Comment by dam0vm3nt** [comment]
Ok, probably I got confused. The problem lies elsewhere in `polymer-redux` [here](https://github.com/tur-nr/polymer-redux/blob/polymer-2/dist/polymer-redux.js#L107) then. It takes the properties from the current constructor ignoring the prototype chain. What is the correct way to collect all the props so that I can ask `polymer-redux` author to change its code ?

**Comment by dam0vm3nt** [comment]
See also https://github.com/tur-nr/polymer-redux/issues/59

**Comment by govis** [comment]
Just tried upgrading  an element to native 2.0 class syntax and used <code>Polymer.mixinBehaviors</code> to mix <code>Polymer.PaperInputBehavior</code> this way, which in turn mixed additional behaviors. Unfortunately it seems that <code>Polymer.mixinBehaviors</code>might not be setting element's <code>this.behaviors</code> property that is used by some hybrid Polymer Elements' behaviors such as <code>Polymer.IronA11yKeysBehavior</code>.

**Comment by sorvell** [comment]
@govis If you can confirm that, would you mind filing a separate issue on that?

**Comment by dam0vm3nt** [comment]
I'm closing this because my issue for now thanks for help guys!

**Comment by govis** [comment]
@sorvell I logged it in the PolymerElements/iron-a11y-keys-behavior repository as I'm not sure if any other PolymerElements/Behaviors make use of this property and if a change to <code>Polymer.mixinBehaviors</code> is warranted to maintain backward compatibility with hybrid Polymer Elements' behaviors or we shall treat it as a breaking API change.

https://github.com/PolymerElements/iron-a11y-keys-behavior/issues/69

As it stands right now it appears that this issue will get in the way of moving any element with a dependency on <code>Polymer.IronA11yKeysBehavior</code> or anything that makes use of <code>this.behaviors</code> to Polymer 2.0 class-based syntax, so could you please follow up with them.
