### ISSUE TITLE
[[importPath]] not working in safari

### ISSUE THREAD

**Issue by jogibear9988** [Polymer/polymer#4379]
If I try to use polymer v2 in Safari, I got the error 404 not found, because it searches for the images in the wrong path.

In chrome the same component works

#### Steps to Reproduce
1. Create a Elemnt with a relative image path to the element

#### Expected Results
Image is loaded

#### Actual Results
Image path is wrong

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [X] Safari 10
- [ ] Safari 8
- [ ] IE 11

### Versions
v 2.0

**Comment by jogibear9988** [comment]
<img hidden id="typeTurnTable" style="position: absolute; height: 107px; width: 107px" src="[[importPath]]images/conveyorSubTypeTurnTable.svg"></img>

**Comment by jogibear9988** [comment]
befor I get a exception from setupCompoundBinding -> "TypeError: Attemped to Assign readonly Property"

**Comment by TimvdLippe** [comment]
You should use `src$=` per https://www.polymer-project.org/1.0/docs/devguide/data-binding#native-binding

**Comment by jogibear9988** [comment]
you're completly right!

**Comment by jogibear9988** [comment]
thanks
