### ISSUE TITLE
Transpiling with Babel es2015 Preset

### ISSUE THREAD

**Issue by ZepAviator** [Polymer/polymer#4381]
### Description
Pipe your build process into Babel
`babel({ presets: ['es2015'] })`

#### Expected Results
A build that runs great in non-es6 browsers (older Safari for instance)

#### Actual Results
```
Uncaught TypeError: Class constructor PolymerElement cannot be invoked without 'new'
```

### Browsers Affected

- [x] Safari 9
- [x] Safari 8

### Versions
"merge-stream": "^1.0.1",
"polymer-build": "^0.8.2",
"babel-core": "^6.23.1",
"babel-eslint": "^7.1.1",
"babel-preset-es2015": "^6.22.0",

**Comment by ZepAviator** [comment]
Partial path to the fix here:
https://github.com/webcomponents/webcomponentsjs/pull/711

Currently related open issue here:
https://github.com/Polymer/polymer-cli/issues/587

**Comment by sorvell** [comment]
The linked issues are now fixed. 

For more information see the `Building for Deployment` section at https://www.polymer-project.org/2.0/start/install-2-0.
