### ISSUE TITLE
Do I need to build before serve on Safari?

### ISSUE THREAD

**Issue by santanafabio** [Polymer/polymer#4382]
can anybody help me with a doubt... I'm testing the new Polymer 2.0 preview on Safari, but it seems that's not working properly. The thing is, I'm using a simple code (just my-element) in the index.htm, loading the polyfill but I'm doing it without build and serving with gulp and BrowserSync. It happens that is working on Chrome and Mozila, but not on the Safari. The component dont even load.

Do I need to build before serve on Safari?

**Comment by web-padawan** [comment]
Try using `polymer serve`, the CLI installed via `npm i -g polymer-cli@next` provides a built-in transpilation support for development.

**Comment by santanafabio** [comment]
@web-padawan but how to test remotely on iPad after build? And why is working on Chrome and Mozila without build, just serving?

**Comment by azakus** [comment]
If you have an older version of iOS, you may need to compile to ES5, as Polymer is distributed as ES6.

`polymer serve` will automatically compile as it serves, and you can test remotely on an iPad by connecting it with to a mac and using Safari's developer tools.
