### ISSUE TITLE
Cannot listen for dom-repeat event 'dom-change'.

### ISSUE THREAD

**Issue by Any1s** [Polymer/polymer#4387]
This affects Polymer 2.0.

I seem not to be able to listen for the 'dom-change' event fired by `dom-repeat` here: https://github.com/Polymer/polymer/blob/58213ee611e936f23be7480043caabfd6af11ef4/lib/elements/dom-repeat.html#L491.  The issue is resolved by setting the `composed` flag on the event to `true` (https://developer.mozilla.org/en-US/docs/Web/API/Event/composed).

I use `dom-repeat` inside of `dom-bind` like this:

```
<dom-module id="test-module">
  <template>
    <dom-bind>
      <dom-repeat …>
        …
      </dom-repeat>
    </dom-bind>
  </template>
</dom-module>
```

#### Expected Results
Be able to listen for the event using something like this:
`this.addEventListener('dom-change', (e) => { console.log(e); });`

#### Actual Results
The listener is not triggered, unless I patch `dom-repeat` to set the `composed` flag on the event to true.

Am I missing something?

**Comment by sorvell** [comment]
This looks like a mistake and reveals a missing test as the intention is that the event is composed. We'll get this addressed.
