### ISSUE TITLE
Please add Throttle utility

### ISSUE THREAD

**Issue by JosefJezek** [Polymer/polymer#4388]
Could you add throttle utility?

- https://css-tricks.com/the-difference-between-throttling-and-debouncing/
- https://lodash.com/docs/4.17.4#throttle
- http://sampsonblog.com/749/simple-throttle-function
- https://jsfiddle.net/jonathansampson/m7G64/

**Comment by cordovapolymer** [comment]
It would be very useful, once debounce is available throttle is a must-have.

**Comment by MeTaNoV** [comment]
can be very useful for certain use-case!

**Comment by kevinpschaaf** [comment]
We've trimmed the core library to be much leaner, and we are unlikely to add more utility API such as this which is better distributed via general purpose utility libraries.

However we encourage developers to create class mixins (using standard ES6 class expressions) and/or simply implement the utility API they desire on a subclass of `Polymer.Element` and use that as the base class for elements developed in your organization.

**Comment by JosefJezek** [comment]
@kevinpschaaf @sorvell @azakus Please create Throttle utility. We need throttle for `resize` and `click` events. Thank you.

- https://stackoverflow.com/questions/27078285/simple-throttle-in-js/
- https://github.com/Polymer/polymer/blob/master/lib/utils/debounce.html

**Comment by merlinnot** [comment]
Why don't you just use lodash? Polymer shouldn't even provide `debounce` method, IMHO.

**Comment by JosefJezek** [comment]
@merlinnot We need throttle mixin for Polymer Elements from Polymer JS Experts... We need maintained mixins from Polymer Team.

**Comment by JosefJezek** [comment]
lodash.min.js has 71KB... How to load only throttle function in Polymer element?

**Comment by arodic** [comment]
@JosefJezek it is extremely easy to write your own throttle function and put it in a behavior for reuse. If you've never done it before, I suggest is as a good exercise to understand behaviors. You can also write your own base class that extends Polymer.Element and includes all the helper functions you want.

However, I suggest staying away from asynchronous behaviors as much as possible.

**Comment by merlinnot** [comment]
You can use `lodash-cli` to create [custom builds](https://lodash.com/custom-builds) which can be damn small if you pick just the methods you need :)

**Comment by JosefJezek** [comment]
Here is utility for Polymer https://github.com/StartPolymer/s-utils
