### ISSUE TITLE
Polymer.Templatize should help in managing stamped instances

### ISSUE THREAD

**Issue by valdrinkoshi** [Polymer/polymer#4392]
Forwarding host properties with templatizer can be confusing, as the user is required to keep track of the stamped instances in order to do the right thing. e.g.
```js
const ctx = this;
this._instance = new (Polymer.Templatize.templatize(templ, this, {
  forwardHostProp(prop, value) {
    // confusing things:
    // 1. the context here is the same as the one outside (ctx === this)
    // 2. this method is invoked before `this.instance` can be assigned
    this._instance && this._instance.forwardHostProp(prop, value);
  }
}))();
// do something with the instance
```
Most of the times all I want is to forward the the instances that I stamped the bound properties.
Ideally, I just want to stamp instances and let Templatizer do the forwarding, something like this:
```js
const instance = new (Polymer.Templatize.templatize(templ, this))();
```
Templatizer could also expose APIs to help handling the stamped instances, e.g. `Polymer.Templatize.getInstancesOf(template)`

**Comment by valdrinkoshi** [comment]
@sorvell @kevinpschaaf FYI

**Comment by kevinpschaaf** [comment]
May consider doing this as an additive change, e.g. if `owner` is supplied but `forwardHostProp` is not, then Templatize will maintain a Set of instances and add a `disposeInstance` API.
