### ISSUE TITLE
UI / JS becomes unresponsive after clicking a mailto link in Internet Explorer 11.

### ISSUE THREAD

**Issue by derrick-burns** [Polymer/polymer#4395]
### Description

UI / JS becomes unresponsive after clicking a mailto link in Internet Explorer 11.
(Can't be reproduced in online sandboxes)

#### Demo

https://github.com/derrick-burns/PolymerIE11MailtoBug

#### Steps to Reproduce

Example:

1. Open file in IE11
2. Click mailto Link
3. Try to switch tabs (nothing happens)

#### Expected Results
Should be able to switch tabs

#### Actual Results
Unable to switch tabs

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11

### Versions

- Polymer: v1.X.X
- webcomponents: v0.7.24

**Comment by mcarey1590** [comment]
I have a similar issue when using a download link `<a href="myExcelFile.xlsm" download="download.xlsm></a>`. Click events no longer fire(or are lost somewhere) for paper-items, paper-tabs, paper-buttons, paper-icon-buttons, etc. I am currently investigating the issue but with little success so far.

**Comment by TimvdLippe** [comment]
I have tried to reproduce this issue for the past hour, but unsuccessfully. If you can still reproduce this issue with Polymer 2 and the updated polyfills, please provide a JSBin based on http://jsbin.com/luhaxab/edit?html,output that shows the issue.
