### ISSUE TITLE
Simple issue data binding two way

### ISSUE THREAD

**Issue by SylvainAssemat** [Polymer/polymer#4401]
Hi all 

Juste a simple issue, can you help please ?
I just wonder why the view is not refreshing when modifying the properties object from the script 

Seems the most basic example, but can't find out what s wrong

Tahnks for your help

<dom-module id="creation-dossier">
    <template>
        
        <style is="custom-style" include="iron-flex iron-flex-alignment iron-positioning">

        </style>
        
        <div class="vertical layout center-justified">

            <div>
                <div>{{session.user.name}}</div>
                <div>{{session.user.id}}</div>
            </div>

            <div class="horizontal layout center-justified">
                <paper-button on-click="envoi" style="margin-top:20px;">
                    <iron-icon icon="send" item-icon></iron-icon>
                    VALIDER</paper-button>
            </div>
        </div>
    </template>	

    <script>
	addEventListener('WebComponentsReady', function() {
            Polymer({
                is: "creation-dossier",
                properties: {
                   session: {
                        type: Object,
                        value: function() { 
                            return { 
                                user: { 
                                    name: "rob",
                                    id: 1 
                                } 
                            }; 
                        }
                    }
                },
                envoi: function(){
                   console.log('this.session.user.name '+ this.session.user.name);
                   console.log('this.session.user.id   '+ this.session.user.id);
                   this.session.user.name = "hello";
                   this.session.user.id = 0;
                   console.log('this.session.user.name '+ this.session.user.name);
                   console.log('this.session.user.id   '+ this.session.user.id);
                }
            });
	});
    </script>

</dom-module>

**Comment by web-padawan** [comment]
You should use `this.set('session.user.name', 'hello')`. See [docs](https://www.polymer-project.org/1.0/docs/devguide/model-data) for details.

**Comment by SylvainAssemat** [comment]
Thanks that 's working
