### ISSUE TITLE
a href not working when on-tap assigned

### ISSUE THREAD

**Issue by Mika83AC** [Polymer/polymer#4408]
Hello everyone,

I've found an issue in Polymer 1.8.x. When I'm using a html link in my polymer element, everything is fine with the link. But when i add a on-tap function to the html link, the link itself doesn't work any more on mobile (used the toggle device function of the chrome dev tools) but the on-tap function is executed. In desktop mode, everything is still fine and both, the link and the on-tap function are executed.

So, 
`<a href$="[[_getItemHref(movie)]]">`
works, and
`<a href$="[[_getItemHref(movie)]]" on-tap="_hideActionOverlay">`
isn't working on mobile (link not executed).

Can anyone confirm this and maybe knows a solution?

Regards,
Michael

**Comment by Mika83AC** [comment]
As well, the link isn't working any more on mobile if it is surrounded by another div that has a on-tap function assigned:

```
<div id="actionOverlay" on-tap="_hideActionOverlay">
	<a href$="[[_getItemHref(movie)]]">
		<paper-icon-button id="iconOpen" icon="open-with" class="actionButton" on-tap="_onOpen"></paper-icon-button>
	</a>
</div>
```

Regards,
Michael

**Comment by stramel** [comment]
@Mika83AC I believe you are looking for `on-click` listener. The `on-tap` event is a custom event implemented in some of the Google components (paper-)

**Comment by Mika83AC** [comment]
No, not really. As [https://www.polymer-project.org/1.0/docs/devguide/gesture-events](url) says, "tap should be used instead of click for the most reliable cross-platform results".

The on-tap event is fired and works, but the a functionality gets lost and the link itself isn't working any longer on mobile. That's my problem. :)

**Comment by stramel** [comment]
Ah, shoot! You are correct! 😅 TIL to read the documentation thoroughly

**Comment by Mika83AC** [comment]
Does anyone know a workaround for this issue until it gets fixes officially?

**Comment by kownacki** [comment]
@Mika83AC I stumbled across the same problem. I think I found a decent workaround.

HTML
```html
<a href="my-url" on-tap="_tapped">link</a>
```

JS
```javascript
_tapped: function(event) {
  // Other stuff you wanna do
  ...

  // Bugfix. 'on-tap' breaks href. See goo.gl/5c3JcK
  history.pushState({}, null, event.target.href);
  // Notifying app-location about url change. See goo.gl/XeR4s0
  this.fire('location-changed');
}
```

Just add last 4 lines of `_tapped` function to your `on-tap` function. Beware that firing `'location-changed'` is a must if you use app-location.

**Comment by kevinpschaaf** [comment]
We can't reproduce this on Polymer 1 or 2:
* Polymer 1: http://jsbin.com/vufakes/edit?html,output
* Polymer 2: http://jsbin.com/jomanaw/edit?html,output

@Mika83AC Are you still having this problem, could you re-open with a repro?  Thanks.
