### ISSUE TITLE
Slow performance with 2.0

### ISSUE THREAD

**Issue by govis** [Polymer/polymer#4411]
### Description

I seem to be noticing some performance issues in 2.0.

I have a page with 12 cards and it takes almost 10 seconds for them to render. That's mostly JS execution after items property of <code>dom-repeat</code> is set. I have been poking at it in Chrome timeline and it seems that bulk of the time (7sec) is spent in <code>ApplyShim._produceCssProperties</code> and ~1sec in <code>ApplyShim.transformCssText</code>. That's on a fast CPU - on a slow one it takes 20+ seconds with Chrome feeling quite unresponsive during that time. 

The page runs in hybrid/legacy mode with things like <code>template is="dom-if"</code> not yet migrated and is unbundled, not built but still fully functional under 2.0rc with everything loaded and trans-coded on the fly. Still same page doesn't take nearly that long in 1.8 under the same scenario and I seem to have noticed it a couple of weeks ago, as when I originally pointed to 2.0-preview earlier in the year performance was closer to that of 1.x.

Once the first set of cards is displayed loading new cards becomes much faster and performance feels normal.

#### Live Demo

I have attached saved timeline for your reference:
[TimelineRawData.zip](https://github.com/Polymer/polymer/files/834412/TimelineRawData.zip)

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v2.0.0-rc.2
- webcomponents: v1.0.0-rc.5

Thank you

**Comment by azakus** [comment]
This sounds like what I fixed in https://github.com/webcomponents/shadycss/pull/65. Can you check again with shadycss v1.0.0-rc.2?

**Comment by govis** [comment]
Ok, thanks for taking a look. I don't have access to my dev setup right now, so will have to try it next week. I'll close it for now and reopen if it still persists. Thanks.

**Comment by ChadKillingsworth** [comment]
@azakus I can confirm that this is solved with ShadyCSS 1.0.0-rc.2.

![polymer performance comparison](https://cloud.githubusercontent.com/assets/1247639/23964623/132d8218-0983-11e7-92ee-780a5cfc9fee.png)

After building with ShadyCSS 1.0.0-rc.2:

![screen shot 2017-03-15 at 1 27 37 pm](https://cloud.githubusercontent.com/assets/1247639/23964677/51630134-0983-11e7-991d-aa5dc09516ba.png)

**Comment by govis** [comment]
Yes, after bumping shadycss up to 1.0.0-rc.2 it became way faster for me as well. Thanks.
