### ISSUE TITLE
Translations for other languages

### ISSUE THREAD

**Issue by devigor** [Polymer/polymer#4415]
Is the project open for contributions from new translations in other languages?

**Comment by kevinpschaaf** [comment]
@arthurevans @wmginsberg Do we have website infrastructure support for multiple languages (or desire to add)?

**Comment by arthurevans** [comment]
We don't currently have the infrastructure. I had a preliminary branch with
support for localized content, but we'd also need to localize the UI.

I would like to get this off the ground this year.

**Comment by web-padawan** [comment]
It's a really nice to have feature, because adding i18n support to docs could promote Polymer, see for example Vue.js. If you guys will implement this once 2.0 API gets stable, I would be glad to help you with the russian translation.

**Comment by dimon-durak** [comment]
@web-padawan - давай переводить вместе

**Comment by web-padawan** [comment]
@dimon-durak OK, but let's speak English here, though 😄  

It would be nice also to create a "russian" room in Slack channel, BTW. At least we already have "spanish", so why not? There are some russian speakers among community here and there.

**Comment by TimvdLippe** [comment]
Closing this issue per https://github.com/Polymer/docs/issues/2249#issuecomment-319233181
