### ISSUE TITLE
CSS @apply from main document doesn't work in Chrome when using webcomponents-loader

### ISSUE THREAD

**Issue by ChadKillingsworth** [Polymer/polymer#4416]
### Description
In Chrome, when using a `<custom-style>` element in the main document, mixins with `@apply` are not properly applied unless the `webcomponents-lite.js` polyfill is included. When using `webcomponents-loader.js` the mixin styles have no effect.

#### Live Demo
https://jsbin.com/tedupi/edit?html,output

#### Steps to Reproduce
Have a `custom-style` element in the main document which defines a CSS property mixin on the `html` element.
Attempt to use the mixin in any element template styles.

### Browsers Affected

- [x] Chrome

### Versions
Polymer 2.0.0-rc.2.

**Comment by ChadKillingsworth** [comment]
I should mention I'm testing this in Chrome 58.

**Comment by 43081j** [comment]
FYI using the loader in latest chrome will result in webcomponentsjs not loading.

So you're seeing a difference because, when loading `lite.js`, you're guaranteeing that webcomponentsjs will load. When loading `loader.js`, feature checks determine that nothing must be loaded, so nothing is.

**Comment by ChadKillingsworth** [comment]
@43081j Correct, but the apply shim should work either way.

**Comment by jouni** [comment]
Apply shim is now opt-in and not part of the default set of polyfills. I suppose webcomponents-lite still imports that for backwards compatibility.

**Comment by 43081j** [comment]
It appears that without webcomponentsjs loaded, `apply-shim` is loaded from the shadycss package.

_With_ webcomponentsjs loaded, `scoping-shim` is loaded from the shadycss package.

Each of those entrypoints produce different logic.

**Comment by 43081j** [comment]
https://jsbin.com/xelaboruco/1/edit?html,output

As you can see, loading webcomponents-lite _first_ solves this timing issue.

The problem was simply that polymer loads the apply shim, which was later overwritten by the scoping shim. If you load the scoping shim first, the apply shim checks for its existence and appends its logic to it.

**Comment by azakus** [comment]
I need to double check this after webcomponents/shadycss#73

**Comment by ChadKillingsworth** [comment]
I'm fairly certain that this issue is now fixed.

**Comment by kirilledelman** [comment]
I can't get custom-style to initialize in main document with either `webcomponents-lite` or `webcomponents-loader`. Following code from iron-flex guide exactly - can't get them to work. No errors.
