### ISSUE TITLE
reflectToAttribute unable to add/remove/add 

### ISSUE THREAD

**Issue by JoelCode** [Polymer/polymer#4425]
### Description

The properties object key reflectToAttribute generating an error after
the following sequence: add property, remove property, add property (error)

### Expected outcome

Add property

### Actual outcome

Error code below:
template-stamp.html:428 Uncaught TypeError: context[methodName] is not a function
    at HTMLElement.handler (template-stamp.html:428)
    at Object._fire (gestures.html:504)
    at Object.forward (gestures.html:799)
    at Object.touchend (gestures.html:788)
    at HTMLElement._handleNative (gestures.html:318)
handler	@	template-stamp.html:428
_fire	@	gestures.html:504
forward	@	gestures.html:799
touchend	@	gestures.html:788
_handleNative	@	gestures.html:318

### Steps to reproduce
      <paper-button raised on-tap="changeAttribute">Attribute True</paper-button>
      <paper-button raised on-tap="changeAttributeFalse">Attribute False</paper-button>

      static get properties() {
        return {
          changeAttribute: {
            type: Boolean,
            reflectToAttribute: true,
          }
        }
      }

      changeAttribute() {
    this.set('changeAttribute', "true");
      }

      changeAttributeFalse() {
    this.set('changeAttribute', "false");
      }

### Browsers Affected

- [X] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by jsilvermist** [comment]
`changeAttribute` and `changeAttribute()` are in the same scope with the same name, try changing one of these to a different name.

**Comment by kevinpschaaf** [comment]
As @jsilvermist said, you are naming both a method `changeAttribute` and a property `changeAttribute`; they need to be different.
