### ISSUE TITLE
Polymer makes browser hang with Shadow DOM polyfill

### ISSUE THREAD

**Issue by esprehn** [Polymer/polymer#443]
If you load my app from https://github.com/esprehn/chromium-codereview without the "Experimental Web Platform Features" flag enabled the tab locks up. It seems there's an infinite loop somewhere.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
