### ISSUE TITLE
Problems with polymer-2-element template

### ISSUE THREAD

**Issue by nicolasr75** [Polymer/polymer#4430]
### Description
The polymer-2-element template does not work because of wrong paths.

#### Steps to Reproduce

Do _polymer init_

Select the _polymer-2-element_ template

Do _polymer serve_ as described in the readme

Start a browser and go to http://localhost:8081

#### Expected Results

The browser should load the page and display _Hello my-elem_
(because I selected my-elem as the element name in the wizard).

#### Actual Results

The page stays blank and the dev tools console shows

GET http://localhost:8081/webcomponentsjs/webcomponents-loader.js 404 (Not Found)
GET http://localhost:8081/iron-component-page/iron-component-page.html 404 (Not Found)

Looking at index.html one can see that the generated paths are missing the bower_components directory. F.e. the generated path to webcomponents is:
../webcomponentsjs/webcomponents-loader.js
 (Note: in the application template this works because the paths are correct there!)

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions

- Polymer: v0.18.0-pre.13
- webcomponents: v1.0.0.-rc.5

**Comment by jsilvermist** [comment]
If you serve with `polymer serve --open` so that it opens to the `components` pseudo directory, does this fix the issue?

**Comment by nicolasr75** [comment]
Well, it opens a description page where I also have a button to start a demo. This demo works. Unfortunately I cannot simply refresh it to view changes in my element. A refresh brings me back to the description page.
I don't understand what's the use of the index.html in the base directory. Looks like I cannot request it, be it with or without `--open`.

**Comment by azakus** [comment]
This issue was moved to Polymer/polymer-cli#610
