### ISSUE TITLE
Inconsistent readme in polymer-2-element template

### ISSUE THREAD

**Issue by nicolasr75** [Polymer/polymer#4431]
### Description
The readme that gets generated by polymer init is inconsistent and seems to be outdated.
#### Steps to Reproduce

Do _polymer init_

Select the _polymer-2-element_ template

Open _readme.md_ and read the instructions for building

Do _polymer build_

Use file explorer to check the generated output.

#### Expected Results

As written in the readme there should be build/bundled and build/unbundled sub folders (but as it seems this is outdated information)

#### Actual Results

Instead of the expected folders there is a folder build/default.

### Versions

- Polymer: 0.18.0-pre.13
- webcomponents: 1.0.0.-rc.5

**Comment by azakus** [comment]
This issue was moved to Polymer/polymer-cli#609
