### ISSUE TITLE
Built-in element extension in V2.

### ISSUE THREAD

**Issue by PaulHMason** [Polymer/polymer#4433]
I'm probably going to be shot for this :)

Is there currently any guidance on how to extend built-in elements? There's a whole thread about "is" with no apparent resolution here: https://github.com/w3c/webcomponents/issues/509

Unfortunately, it's kind of a pressing issue in certain instances (particularly table child elements, which I'm bumping my head against now).

A Polymer only solution isn't ideal, but it looks like the only practical one, if possible.

**Comment by web-padawan** [comment]
See [this comment](https://github.com/webcomponents/custom-elements/pull/42#issuecomment-285445766) for explanation.

**Comment by nazar-pc** [comment]
Also see #3925

**Comment by kevinpschaaf** [comment]
Closing as a dupe of https://github.com/Polymer/polymer/issues/3925, which captures the current state of the issue.
