### ISSUE TITLE
Documentation type on https://www.polymer-project.org/2.0/docs/devguide/data-system

### ISSUE THREAD

**Issue by jpradelle** [Polymer/polymer#4435]
In "Using the MutableData mixin" category:
Missing space betwwen like and dom-repeate: 
"This is true for most simple UI elements. MutableData is likely to be useful for complex reusable elements (likedom-repeat or iron-list), or for application-specific elements that hold complex state information."

**Comment by web-padawan** [comment]
Please submit such issues to the [docs](https://github.com/Polymer/docs) repo, and feel free to send PR's.

**Comment by jpradelle** [comment]
Sorry I didn't found repo, PR is open https://github.com/Polymer/docs/pull/1960
