### ISSUE TITLE
Shadow DOM :host selector not functioning in IE 11

### ISSUE THREAD

**Issue by cary-smith** [Polymer/polymer#4436]
### Description
Was playing with the preview version of Polymer 2.0 and I seem to be having some oddity specifically with IE11 when using the shadow dom polyfill. Styles do not seem to be applying to the element via the `:host` selector, nor is it rendering. I assume I may be missing something but would appreciate verification.

#### Live Demo

http://plnkr.co/edit/oVlCZk?p=preview

#### Expected Results
A bordered box with text in it

#### Actual Results
Empty example page

### Browsers Affected

- [ ] IE 11

### Versions

- Polymer: 2.0-preview

**Comment by cary-smith** [comment]
I suddenly realize there is a loading issue with the ES6 syntax in the `webcomponents-loader.js` (same one used in the docs).

**Comment by JoshuaVSherman** [comment]
Are you kidding me, IE11 !?

**Comment by cary-smith** [comment]
I know....evil beast is still used here :cry:

**Comment by azakus** [comment]
Polymer in that branch is written in ES6, which does not work on IE 11. If you take your example and serve it with `polymer serve` (which compiles for browsers that don't support ES6) it appears to work correctly

**Comment by cary-smith** [comment]
I was able to resolve my own issues but might recommend that the documentation be be updated to not use those links unless IE11 support is dropped (something I wish we could all do). 

For example: 
https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom

Each "See it on Plunker" link will fail for anyone using IE11.
