### ISSUE TITLE
Cannot read Property` localName` of undefined

### ISSUE THREAD

**Issue by Tevinthuku** [Polymer/polymer#4439]
#### Expected Results
Serve The demo pages

#### Actual Results
`Uncaught TypeError: Cannot read property 'localName' of undefined`
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions

- Polymer: v2.0.0.0rc.1
- webcomponents: v1.0.0 rc.5

**Comment by azakus** [comment]
Can you provide more description about how to reproduce this issue?

**Comment by marol-hadidjaja** [comment]
I got this error too....
I've run `polymer init`, and choose second choice (**Polymer 2 element template**) and then run `polymer serve` when I opened the browser (**http://localhost:8081**), I got errors:
1. webcomponentjs-loader.js not found
2. iron-component-page.html not found

After I fixed this errors, just wrong linking, I got `Cannot read property 'localName' of undefined` in my developer tools. Maybe this can help how to solve this bug...

**Comment by jaworskm** [comment]
On Chrome 56, I get this error following the steps above. The issue is that in polydev/src/document-context/measure-custom-element.js on line 29 (see `cb()` below) the callback references ShadyCSS (see second snippet) and `this` is `undefined`. 

The site works in Firefox and Safari just fine; it's a bug with Chrome.

```
function makeMeasurement(operation, tagName, counter, cb) {
        const counterSuffix = counter == null ? '' : ` ${counter}`;
        const startMark = `${prefix}start ${operation} ${tagName}${counterSuffix}`;
        const endMark = `${prefix}end ${operation} ${tagName}${counterSuffix}`;
        const measure = `${prefix}${operation} ${tagName}${counterSuffix}`;
        window.performance.mark(startMark);
        try {
            return cb();
        }
        finally {
            window.performance.mark(endMark);
            window.performance.measure(measure, startMark, endMark);
        }
    }
```

The `cb()` function actually calls

```
connectedCallback() {
        if (window.ShadyCSS) {
          window.ShadyCSS.styleElement(this);
        }
        this._flushProperties();
      }
```

**Comment by joeyroosing** [comment]
Same error occurs when running PSK3 latest RC. Only on chrome (tested on chrome 57)

**Comment by mindon** [comment]
Remove the "Polymer DevTools Extension" if you had installed such an extension :D

**Comment by rictic** [comment]
This is fixed at master in polydev. It looks like the only developer with the credentials to publish the fix is on vacation though.

**Comment by MeTaNoV** [comment]
Was touched by this issue too, ThX for the fix and following now!

**Comment by rictic** [comment]
v0.0.8 is published with the fix!
