### ISSUE TITLE
customElements is not defined

### ISSUE THREAD

**Issue by CaptainCodeman** [Polymer/polymer#4440]
I'm seeing this error on a tablet with an older version of Android and Chrome/39.

What I _think_ is happening is that because the webcomponents-loader loads the actual polyfills asynchronously, in the meantime Chrome processes the html imports and starts loading elements + polymer and it's a race for who wins. When dom-module.htm runs it tries to execute:

`customElements.define('dom-module', DomModule);`

... but customElements may not exist yet because it's loading.

I don't know what the solution should be - maybe something in https://github.com/Polymer/polymer/blob/master/lib/utils/boot.html should be waiting for the WebComponentsReady event and until that happens, anything that needs customElements should be scheduling future calls via an array (just thinking how other google libs like Analytics & Dfp do that kind of thing).

**Comment by CaptainCodeman** [comment]
I think the same issue can cause different symptoms if you have an es5 build on an es6 capable browser - just the error is different this time because the es5->es6 shim might not have loaded before the app elements import and run (sorry, I forgot to make a note of the exact error).

It turns out not to be such an issue though - I'm loading both the webcomponents polyfills and some other polyfills (e.g. `URL` is needed for app-route, `Object.assign` for redux etc...) so I need to delay loading the app shell element _anyway_ plus I've also gone with a split es5 and es6 build and differential serving which means the correct element reference can't be directly in the html anyway (also, the service-worker file needs to change too).

So ... I just wait for the polyfills script load + WebComponentsReady event and then dynamically add the app element and everything it needs is ready. Other than some occasional css issue with the async loading (which I think is fixed but not released yet) everything works fine across all browsers I've tried it with (Chrome, FF, Safari, Edge, IE11).

Performance seems great - adding http/2 push to start the appropriate webcomponents loader and app shell element downloading with the initial index.html response and [lighthouse](https://github.com/GoogleChrome/lighthouse) gives it a score of 💯, yay!

**Comment by CaptainCodeman** [comment]
The latest changes fix this

**Comment by wivdmerwe** [comment]
Hi CaptainCodeman. 

Not sure if I can still comment on this, but I'm experiencing the exact same issue. You seem confident to have found a solution. Please can you help me too. :) Your last comment states that the latest changes fixes the problem. Which changes are you referring to? I've got an angular6 application, and am using angular elements...  My package.json dependency list is as follows:

"dependencies": {
    "@angular/animations": "^6.0.9",
    "@angular/cdk": "^6.3.1",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/elements": "^6.1.0",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/material": "^6.3.1",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@clr/angular": "^0.12.6",
    "@webcomponents/webcomponentsjs": "^2.0.3",
    "angular2-mentions": "^0.7.3",
    "angularfire2": "^5.0.0-rc.11",
    "core-js": "^2.5.4",
    "document-register-element": "^1.7.2",
    "firebase": "^5.3.0",
    "jquery": "^2.1.4",
    "ng2-file-upload": "^1.3.0",
    "ngx-image-cropper": "^0.2.8",
    "ngx-quill": "^3.2.0",
    "ngx-timeago": "^1.0.0",
    "ngx-toastr": "^8.8.0",
    "ngx-uploader": "^6.0.1",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.2.1",
    "zone.js": "^0.8.26",
    "@clr/ui": "^0.12.6",
    "@clr/icons": "^0.12.6",
    "@webcomponents/custom-elements": "^1.0.0"
