### ISSUE TITLE
2.0 Quick Tour code mistake

### ISSUE THREAD

**Issue by chris14465** [Polymer/polymer#4442]
In the 2.0 quick tour under _Declare a property_ the code-preview shows the code from the section before (_Use data binding_). When editing on plunker, the actual code can be seen.

![bildschirmfoto 2017-03-17 um 16 05 04](https://cloud.githubusercontent.com/assets/244036/24049252/c54b578c-0b2b-11e7-9d00-5c7540ca555d.jpg)
![bildschirmfoto 2017-03-17 um 16 05 14](https://cloud.githubusercontent.com/assets/244036/24049251/c5325e62-0b2b-11e7-954c-1e6fabb206e8.jpg)

`static get properties() {
            return {
                owner: {
                    type: String,
                    value: "Daniel",
                }
            };
        }`

is missing.

**Comment by TimvdLippe** [comment]
Fixed in https://github.com/Polymer/docs/commit/13c5d9506f4b6f45f9a45400eba85652a5ea8ad0
