### ISSUE TITLE
Chrome import async bug

### ISSUE THREAD

**Issue by aigan** [Polymer/polymer#4443]
### Description
The second component importing a common component will fail if it's currently being imported async and the second component not importing it async.

#### Live Demo
https://secure.avisita.com/2017/chrome-import-async-bug/example-index.html

Example at https://github.com/aigan/chrome-import-async-bug

#### Steps to Reproduce
1. Install polymer with bower install.
2. Open example-index.html in Chrome (Blink) browser.

#### Expected Results
The h1 from x-header displays.

#### Actual Results
It doesn't. (_template not existing.)

* x-header sync and x-main sync works as expected
* x-header sync and x-main async works as expected
* x-header async and x-main async works as expected
* x-header async and x-main sync do not work in chrome

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Chrome v58
- Polymer: v1.8.1
- webcomponents: v0.7.24

**Comment by aigan** [comment]
Oh. Works well in Polymer 2. :)

**Comment by bedeoverend** [comment]
FWIW might be related to this Blink bug I filed: https://bugs.chromium.org/p/chromium/issues/detail?id=669710. May also relate to #3095

**Comment by TimvdLippe** [comment]
Closing this issue as an upstream Chrome issue filed at https://bugs.chromium.org/p/chromium/issues/detail?id=669710
