### ISSUE TITLE
Uncaught TypeError in Chrome CTRL + reload when compiled as ES5

### ISSUE THREAD

**Issue by majorbuild** [Polymer/polymer#4444]
Live Demo of the problem:

1. Using Chrome, open https://polymer2018.appspot.com/
2. First time it loads OK
3. CTRL + click reload button, page become blank. (this can be repeated, every CTRL + reload fail, every reload works)
4. In Console, there are errors:

VM34 dom-module.html:11 Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at new g (VM34 dom-module.html:11)
    at VM34 dom-module.html:11
    at VM34 dom-module.html:11
VM37 property-accessors.html:14 Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at b.k (VM37 property-accessors.html:14)
    at b.H (VM38 template-stamp.html:12)
    at b.ne (VM39 property-effects.html:19)
    at b.x (VM40 element-mixin.html:17)
    at new b (VM66 my-app.html:13)
    at VM66 my-app.html:13

This demo is created using the polymer-cli, choosing the polymer-2-application

The polymer.json is configured like this (to compile as ES5 for make compatible with old browsers):
```
{
	"lint": {
		"rules": [
			"polymer-2"
		]
	},
	"builds":[
		{
			"js":{
				"compile":true
			}
		}
	]
}

```
And is built using polymer build

**Comment by CaptainCodeman** [comment]
I think you are running into the timing issue where Chrome sees the Html Import and may execute it before the polyfill (added by the loader) runs.

Possible solutions are:

* Use document.write to add the polyfill (within the loader script, instead of adding a script element).
* Remove the import for the app and add it after the WebComponentsReady event has fired (i.e. the polyfill has loaded and run).
* Serve separate es6/es5 versions as appropriate to the browser

**Comment by azakus** [comment]
@FredKSchott can you take a look?

**Comment by FredKSchott** [comment]
This is the timing issue we've been seeing with the `webcomponents-loader.js` and compiled code. It shows up much more frequently with bundled code, but still affects unbundled code occasionally.

We just pushed a fix this morning to the CLI, can you run `npm install -g polymer-cli@next` and try re-building?

**Comment by schrotie** [comment]
Hi there, I've been working with polymer 1 quite a lot and wanted to give polymer 2 a try. I wanted to try it on a new project today, started fresh with polymer-cli and followed the instructions. I did _not_ update npm, but I got a fairly uptodate version which goes with ubuntu's node 6.something. I ran into this error without building and with building. Just started a Polymer 2 App project with the cli and tried it without modifying anything. Got me to a dead stop right at the beginning. I love Polymer and will certainly try again, just wanted to let you know that this will leave a devastating impression on people who give it their first try. I'll be happy to help with debugging this.

**Comment by CaptainCodeman** [comment]
That's why beta and release candidates exist - to flush out exactly these kinds of issues.
The changes already made and released appear to solve this temporary problem. Whenever you're working against unreleased software you need to track the changes closely if you want the important fixes.

**Comment by schrotie** [comment]
Sorry, no offense, I really appreciate what your doing, Polymer may well be the cleanest most consistent approach to web development I have yet seen. I would have assumed that at this point automated tests would catch blockers to the very first recommended and documented steps anybody would do to evaluate 2.0. Maybe its just my system and timing is different on most other systems. Works on Firefox. Sorry for bitching.

**Comment by jfrazzano** [comment]
Are you type scripting the mixin? Did you check decorator length? 

I spent like 10 days hammering a mixin before I modeled on Justin's 

Spec won't let you do any composition from my read unless you stick to the decorator spec

If that isn't it ... That's best I got

**Comment by schrotie** [comment]
I just did `npm install -g polymer-cli@next` and initialized a polymer 2 app from scratch. I still get the same error on Chromium (Ubuntu) with and without build. Both work on Firefox.

**Comment by azakus** [comment]
This issue was moved to Polymer/polymer-cli#641
