### ISSUE TITLE
Possible incorrect variable reference.

### ISSUE THREAD

**Issue by coreyfarrell** [Polymer/polymer#4445]
Sorry if this is not a real bug.  Current code at https://github.com/Polymer/polymer/blame/master/lib/utils/mixin.html#L54 checks for `mixin.__id`, then sets `mixin.__dedupeId`.  Seems like the same property should be used all the time.  This bug report is based purely on my belief that "this looks wrong", I have not seen it cause trouble in real life.

This code was originally added by @sorvell:
* https://github.com/Polymer/polymer/commit/ef695031e2e9e07b6dfc481d4058ae1ac5ff57e0#diff-37d29f6fc5721ddc3d2248a84cfcc681R117

**Comment by azakus** [comment]
Yeah, that seems suspicious. Thanks!

**Comment by azakus** [comment]
The `__dedupeId` is set on mixin function creation, so the check doesn't matter.
The caching functionality also makes sure that any funky nesting of `dedupingMixin` will end in the same output class.
Since the check doesn't work anyway, I'll remove it.
