### ISSUE TITLE
HTML imports or ES6 modules in polymer2

### ISSUE THREAD

**Issue by jogibear9988** [Polymer/polymer#4446]
what is the current plan for polymer2? To use html imports (working via polyfill) or to use es6 modules? (when using es6 modules, how do i import the templates?). Problem is, debuging expirience is very bad, when HTML imports are not natively supported!.

**Comment by azakus** [comment]
We're currently only supporting HTML Imports for using Polymer 2. In the future, we will have tooling and best practices available for using ES6 Modules with Polymer 2, but we're still working that out.

**Comment by jogibear9988** [comment]
Thanks for the info.
Would be nice if the debugging experience in browser not supporting html imports directly could be enhanced.
