### ISSUE TITLE
Question: Gesture events at `touchcancel`

### ISSUE THREAD

**Issue by Westbrook** [Polymer/polymer#4450]
I'm working on some components that are making use of the `track` gesture, and I wanted to see what the internal thoughts were on the `touchcancel` event. It doesn't appear in either the 1.x or 2.x code and I wondered if there were some technical reasons that I didn't know about by which that could be omitted or whether adding that should be added in some way. It's been a couple of years, but @paulirish was [in support of listening to them](https://plus.google.com/+PaulIrish/posts/KTwfn1Y2238), not sure if that is still relevant.

If adding it was an appropriate target, I'd be happy to take a look at putting together a PR. It seems that the event could be roughly analogous to the `touchend`, but the more input there merrier, right? 

Please let me know if that would be seen as a benefit to the project. Thanks!

**Comment by azakus** [comment]
The gesture implementation hasn't had a lot of attention for a while, but it looks like safari has actually implemented `touchcancel` now.

I'd certainly take a look at a PR to integrate `touchcancel` into the gesture system!
