### ISSUE TITLE
paper-autocomplete items not visible due to css 

### ISSUE THREAD

**Issue by sankarbalu1** [Polymer/polymer#4451]
I am facing an issue of listing the items in paper-autocomplete.

![capture](https://cloud.githubusercontent.com/assets/26590731/24184698/439a5c10-0ef5-11e7-9fe5-1b66b1ed4a62.PNG)

![capture2](https://cloud.githubusercontent.com/assets/26590731/24184704/48e13cfc-0ef5-11e7-9ad6-7d9a7643f435.PNG)

`<paper-autocomplete source="{{ _usageMetricList }}" selected="{{ metric }}" value="{{ mName }}" attr-for-value="metricName" attr-for-label="metricName" required auto-validate class="flex">
              <paper-input label="[[ webL10n(l10n, 'targeting.usageMetric') ]]" error-messages="[[ errorMessages ]]" class="flex"></paper-input>
            </paper-autocomplete>`

if I change the z-index of iron-dropdown it will fit on the screen.Can anyone help me on this issue?

**Comment by azakus** [comment]
The `paper-autocomplete` element is not provided by the Polymer team, but can be found here: https://github.com/ellipticaljs/paper-autocomplete.

You should try filing an issue there first.

**Comment by azakus** [comment]
You may also get some better behavior out of https://github.com/samccone/paper-typeahead

**Comment by sankarbalu1** [comment]
Thank you azakus for your valuable reply.
