### ISSUE TITLE
Polymer 2 components not inspectable in IE11

### ISSUE THREAD

**Issue by jehna** [Polymer/polymer#4452]
### Description

Polymer 2 objects cannot be inspected with IE11's developer tools.

#### Live Demo

http://run.plnkr.co/plunks/U3hRP96zlpVhN4aH8E5e/

#### Steps to Reproduce

1. Open the [plnkr link](http://run.plnkr.co/plunks/U3hRP96zlpVhN4aH8E5e/) in IE11
2. Open Developer tools by pressing F12
3. Press "Select Element" button (ctrl+b)
4. Click "This is not inspectable on IE11"

#### Expected Results

The developer tools' Dom Explorer tool should show a `div` element that has the string "This is not inspectable on IE11" text node in it.

#### Actual Results

The Dom Explorer tool highlights the string `<!DOCTYPE html>` and there is nothing inside the `<polymer-test-app>` tag in the Dom Explorer.

![screen shot 2017-03-22 at 14 44 54](https://cloud.githubusercontent.com/assets/2676795/24198359/41909a1a-0f0e-11e7-8ef3-cea562dfd57b.png)

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11 Windows 7
- [x] IE 11 Windows 8.1
- [ ] IE 11 Windows 10

### Versions
- Polymer: 2.0.0-rc.2
- webcomponents: v1.0.0-rc.5

### Source code for the sample

You can see the source code for the plnkr here:

https://github.com/jehna/polymer-ie11-dom-explorer-bug

**Comment by azakus** [comment]
This looks like a ShadyDOM issue, as I can replicate this behavior without Polymer: http://jsbin.com/pukohuj/edit?html,output

FWIW, windows 10's version of IE11 is also pretty busted, with the inspected element being shown above `<html>`

**Comment by azakus** [comment]
This issue was moved to webcomponents/shadydom#117
