### ISSUE TITLE
2.0 rc3 does not work in chromium

### ISSUE THREAD

**Issue by lcottret** [Polymer/polymer#4453]
Hi,

### Description
I did what is explained in Option 1 at https://www.polymer-project.org/2.0/start/install-2-0.
After launching polymer serve, It works well on Firefox but not in chromium. 

#### Expected Results
"Hello polymer-20-test-app" is displayed in the navigator

#### Actual Results
Nothing is displayed in the navigator. Instead, there is this log in the console:
Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at new DomModule (dom-module.html:65)
    at dom-module.html:159
    at dom-module.html:163
property-accessors.html:126 Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at MyApplication.PropertyAccessors (property-accessors.html:126)
    at MyApplication.TemplateStamp (template-stamp.html:461)
    at MyApplication.PropertyEffects (property-effects.html:1212)
    at MyApplication.PolymerElement (element-mixin.html:548)
    at new MyApplication (polymer-20-test-app.html:27)
    at polymer-20-test-app.html:50
http://127.0.0.1:8081/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)

### Browsers Affected
Chromium Version 56.0.2924.76 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

### Versions
Polymer 0.18.0-pre.14

**Comment by azakus** [comment]
This seems like a bug in `polymer serve`. @FredKSchott Can you double-check if "chromium" is checked correctly for `polymer serve` compilation?

**Comment by FredKSchott** [comment]
@azakus you're right, our user-agent parser is reporting the browser name as 'Chrome', while we were expecting "Chrome". I'll create a fix to track in polyserve.

**Comment by FredKSchott** [comment]
The fix for this was merged into polyserve. We'll make sure it goes out in the next release.

@lcottret thanks for filing!

**Comment by moderndeveloperllc** [comment]
@FredKSchott I almost hesitate to ask, but could we fit Opera in there too, or is that too small a user base ([3.8% worldwide](http://gs.statcounter.com/browser-market-share#monthly-201612-201702))? As it's based on the Chromium engine, [Chromium 49 equates to Opera 36](http://www.opera.com/docs/history/).

**Comment by FredKSchott** [comment]
@moderndeveloperllc I've already spent more time on this today than I meant to, but I'd happy provide a review if you want to create a PR to add support.
