### ISSUE TITLE
[1.8] IE11 bug: Unable to get property 'nodeType' of undefined or null reference

### ISSUE THREAD

**Issue by web-padawan** [Polymer/polymer#4455]
### Description

This bug happens in IE11 when parsing some pages. Looks like a bug related to elements composition.

```
SCRIPT5007: TypeError: Unable to get property 'nodeType' of undefined or null reference
```

The only thing I have right now is the following call stack:
```
at Polymer.Annotations._parseNodeAnnotations
 at Polymer.Annotations.parseAnnotations
 at Polymer.Annotations._parseTemplate
 at Polymer.Annotations._parseChildNodesAnnotations
 at Polymer.Annotations._parseElementAnnotations
 at Polymer.Annotations._parseNodeAnnotations
 at Polymer.Annotations._parseChildNodesAnnotations
 at Polymer.Annotations._parseElementAnnotations
 at Polymer.Annotations._parseNodeAnnotations
 at Polymer.Annotations._parseChildNodesAnnotations
```

#### Steps to Reproduce
I didn't manage to localize this bug yet. Reproducing migh require lots of nested components.
Interestigly the UI doesn't get broken, though. I can see the components and interact with them.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11

### Versions
- Polymer: v1.8.1
- webcomponents: v0.7.24

**Comment by azakus** [comment]
Can you provide a link to some example? It is really the only way to help diagnose the issue.

**Comment by web-padawan** [comment]
Seems to be the same as #2682. Will try to create a reduced test case.

**Comment by web-padawan** [comment]
Closing this as no longer relevant. In case someome faces this issue with Polymer 1.x, the problem most likely was in the old version of the template polyfill.
