### ISSUE TITLE
Polymer 2.x on connectedCallback() finding node with $ returns wrong value

### ISSUE THREAD

**Issue by minht11** [Polymer/polymer#4456]
In Polymer 2.x on connectedCallback() or in properties() when trying to find div in element with "$" most of the time it returns wrong result, sometimes it does work correctly. Adding short delay fixes this. This isn't the issue with Polymer 1.x.

```
<dom-module id="my-element">
    <template>
        <div id="findMe"></div>
    </template>
    <script>
        class MyElement extends Polymer.mixinBehaviors(Polymer.NeonSharedElementAnimatableBehavior, Polymer.Element) {
            static get is() {
                return 'my-element'
            }
            connectedCallback() {
                super.connectedCallback();
                console.log(this.$.findMe)
                setTimeout(() => {
                    console.log(this.$.findMe)
                }, 10);
            }
        }
        customElements.define(MyElement.is, MyElement);
```

#### Expected Results
![12](https://cloud.githubusercontent.com/assets/8914032/24267005/8d13d7a0-1011-11e7-992d-24d4a9a1d9f4.png)

#### Actual Results
![11](https://cloud.githubusercontent.com/assets/8914032/24266976/7276cee8-1011-11e7-84b5-0733a2df25ea.png)

**Comment by minht11** [comment]
Same happens with "this"
![13](https://cloud.githubusercontent.com/assets/8914032/24269531/3e9c83a2-101a-11e7-8e7b-003a6c534825.png)

**Comment by azakus** [comment]
I think that's just the developer tools having slightly different representations for the node. I also can't replicate the difference with [this example](http://jsbin.com/bizawec/edit?html,output) in Chrome 57

**Comment by minht11** [comment]
The results are inconsistent for me when using it in my app. I think it depends of code size and number of element. And the problem i am encountering that I cannot set node as propriety value  

`sharedElements: {
                type: Object,
                value: function() {
                    return {
                        'card': this.$.fullCard,
                    };
                }
            },`
gives me result of undefined, however if I set it after delay it works `connectedCallback() {
                super.connectedCallback();
                setTimeout(() =>
                    this.sharedElements = {
                        'card': this.$.fullCard
                    }, 50);
            }` 
It seems that in with higher code size, proprieties are set and connectedCallback() is called before is rendered. That's my speculation. In my testing for it to work correctly delay can be as small as 5ms, but as said it is inconsistent. All of this worked without any delay with Polymer 1.0

I am using latest Electron which is based on Chrome 56
