### ISSUE TITLE
Polymer.Templatize issues.

### ISSUE THREAD

**Issue by jonagh** [Polymer/polymer#4458]
I'm upgrading to Polymer 2.0 and in that process decided to change a component from using Templatizer behaviour to using Poymer.Templatize, which seems to be the new thing to use... but I am having issues getting it to work as expected.

1) The example in the docs fails outright due to the options object being undefined.
https://www.polymer-project.org/2.0/docs/api/namespaces/Polymer.Templatize

`Polymer.Templatize.templatize(template)` errors due to no options object existing,
instead if I pass an empty options object (and owner/this) then it works. Eg: `Polymer.Templatize.templatize(template, this, {})`.
Should the docs be fixed? or should Templatize deal with undefined options?

2) The initial data values are not reflected in the generated template. Am I misunderstanding how this is supposed to work? Setting the values on the instance directly works, but not the initial values!?
For example this won't output 'initial' as expected:
```
let instance = new TemplateClass({myProp: 'initial'});
this.shadowRoot.appendChild(instance.root);
```
but then if you do the following it will output 'new value' correctly:
`instance.myProp = 'new value';`

JSBin example: https://jsbin.com/zimewuf/edit?html,output

PS. Templatize in Polymer.Temp**al**tize.templatize is misspelled in the docs.

Chrome 58
Polymer: 2.0-preview

**Comment by azakus** [comment]
It looks like both `owner` and `options` are required, contrary to the docs.

The `options` argument should just fall back to an empty object, but the `owner` most certainly has to be set, probably to an element instance.

@kevinpschaaf or @sorvell, I'm not sure exactly what `owner` has to be here, can you comment?

**Comment by RoXuS** [comment]
Same behavior since Polymer 2.0, I have to reset the properties on the instance, see https://github.com/RoXuS/paper-datatable-api/blob/2.0-preview/src/paper-datatable-api-column.js#L119.

👍

**Comment by sorvell** [comment]
Sorry for the delay on this. We definitely still need to update the docs here:
* the 2nd `owner` argument to `templatize` is required.
* templatized content is "bound" by default to the owner object and the initial values are only for populating instance properties as specified by passing `instanceProps` in the `options` (3rd) argument to templatize ([example](https://jsbin.com/qewisob/edit?html,output))

**Comment by kevinpschaaf** [comment]
After looking back at the code, seems like use of templatizer without an owner & host property forwarding was just a missed use case.  I'm making a PR that allows this to work, since it's so basic and easy to support:

```html
<template id="myTemplate">
  <div>[[prop]]</div>
</template>

<script>
  const MyTemplate = Polymer.Templatize.templatize(myTemplate);
  const inst = new MyTemplate({prop: 0});
  document.body.appendChild(inst.root);
  setInterval(_ => inst.prop++, 1000);
</script>
```
