### ISSUE TITLE
TypeError: t.getBoundingClientRect is not a function

### ISSUE THREAD

**Issue by valdrinkoshi** [Polymer/polymer#4459]
_From @camargo on March 24, 2017 19:24_

### Description
This is the same issue as #44.

### Expected outcome

No error should be thrown.

### Actual outcome

Getting the error in the console:

`TypeError: t.getBoundingClientRect is not a function`

This is being triggered by https://github.com/PolymerElements/iron-overlay-behavior/blob/master/iron-overlay-manager.html#L46

![capture](https://cloud.githubusercontent.com/assets/683355/24310335/bdb98906-108c-11e7-8e9b-ed19ece13b6a.PNG)

### Steps to reproduce

1. Open Firefox
2. Go to https://www.webcomponents.org/element/PolymerElements/iron-overlay-behavior/demo/demo/index.html
3. Make your window smaller than your screen
4. Click down on the `Plain overlay` button
5. Drag your cursor **while still clicked down** outside of the browser window
6. Release click outside the browser window
7. The error will be in the console

### Browsers Affected

- [ ] Chrome
- [X] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

_Copied from original issue: PolymerElements/iron-overlay-behavior#235_

**Comment by valdrinkoshi** [comment]
In Firefox apparently the `event.target` is `document`, while in the other browsers is `document.documentElement` (aka `<html>`), see a simpler repro http://jsbin.com/mabisob/2/edit?html,console,output
This issue should be resolved in `Polymer.Gestures`, will move the issue there.

**Comment by valdrinkoshi** [comment]
@azakus FYI, this is a good to know behavior also for Polymer's Gesture system in 2.x

**Comment by azakus** [comment]
😩

**Comment by azakus** [comment]
I can't replicate this on Firefox 52, maybe this has fixed itself?

**Comment by azakus** [comment]
In any case, I'll make sure this code path doesn't happen for non-elements just to cover all the bases

**Comment by jfrazzano** [comment]
add a ()… you worked to long… You did enough.  And wow, on the commits guys!!!
