### ISSUE TITLE
Fire method removed in Polymer 2.0

### ISSUE THREAD

**Issue by zaclummys** [Polymer/polymer#4460]
Why **Fire** method was removed in Polymer 2.0?

**Comment by web-padawan** [comment]
It is removed from `Polymer.Element`, but you can use `legacy-element-mixin.html` or just grab it from there and put into your own mixin.

**Comment by azakus** [comment]
If you use the `Polymer()` function to define your element, the `fire()` function is there, but we have removed it from `Polymer.Element` because it is equivalent to `this.dispatchEvent(new Event())`

**Comment by FluorescentHallucinogen** [comment]
@azakus Looks like `this.fire()` method is equivalent to `this.dispatchEvent(new CustomEvent())` that allow to pass data along with the event, not `this.dispatchEvent(new Event())`.

**Comment by moderndeveloperllc** [comment]
And the webcomponents polyfill includes the fixes needed for `new CustomEvent()` to work on IE 9-11, so there is no real reason to use `fire()` unless you have lots in legacy code.
