### ISSUE TITLE
We made it :) we are in ES2015

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#4461]
Today I made my first web application that uses every progressive web app thing in the book using nothing but ES2017 + custom elements

see demo https://github.com/gertcuykens/mollie-api-go 

The bad part only Safari 10.1+ made it so far not even Chrome to be 100% ES2017 which include the module part.

Now the next step will be stuff like this

![image](https://cloud.githubusercontent.com/assets/863731/24332478/7aacf654-1247-11e7-9d8c-5fc81d8461e3.png)

A compiler that knows exactly how your own HTMLElement works, can intellisense all its attributes, functions, event handlers etc and also warn you if you give it the wrong value example a string instead of a number or the wrong element `span` instead of a `p` instance.

So how far are we on the tooling part? Do we have a typing generator for the polymer elements ready that generate a myElement.d.ts that gives us all the information needed?

Another concern of me is that now that I finally have a browser that can do modules and I dont need to do that stupid webpacking or amd modeling anymore it turns out to be far superior for me to use modules instead of html imports when building complex custom elements because i need the compiler to figure out how the bits and pieces fit together and what parts are missing or am I putting together in the wrong way.

Anyway I hope you have access to Safari Tech preview browser and a typescript compiler so I can convince some of you maybe that in the future building a element is going to be different. In the demo above I don't use any framework but it was allot easier for me to put together then working on existing polymer elements. In the past I needed to rely on polymer heavily because of the browser technology restrictions that polymer solves for you. But now that the first browser made it, its maybe time to think about to take another look at how to build web components in the future when every browser has a ES2017 and custom elements stack available?

**Comment by web-padawan** [comment]
Right now Polymer is not designed to be used with ES modules, but this incompatibility between HTML imports and ES modules is known. As @dominiccooney have said in Slack recently,

> We are working on something which integrates HTML import loading with ES6 module loading, which knows how to do this de-duping (it just dedups by URL.) Separately people are looking at the bundling/serving questions. But these things, like ::part, are in the future.

I hope, by the time when ES modules will be wideyl adopted by all evergreen browsers, we might expect to see some progress here.

**Comment by rictic** [comment]
Another thing of interest to monitor is https://github.com/Polymer/gen-typescript-declarations

It's still hacky, and doesn't work yet except in a very narrow sense, but it's moving in this direction.

**Comment by kevinpschaaf** [comment]
Good to hear!  We are actively exploring ways to use Polymer with the upcoming native module loaders so stay tuned.  Going to go ahead and close this issue since there's nothing particularly actionable for the core library.
