### ISSUE TITLE
dom-repeat's renderedItemCount ignores notify-dom-change, when suppressTemplateNotifications is used.

### ISSUE THREAD

**Issue by freshp86** [Polymer/polymer#4465]
See reproduction case at https://jsfiddle.net/kv931mvd/2/.

According to the documentation at https://github.com/Polymer/polymer/releases/tag/v1.8.0, `rendered-item-count` should be updated, if `notify-dom-change` is specified, but it is not. The culprit seems to be at https://github.com/Polymer/polymer/blob/1.x/src/lib/template/dom-repeat.html#L214, where

```
notify: !Polymer.Settings.suppressTemplateNotifications,
```

ignores the presence of `notify-dom-change` attribute. This is affecting Chromium's Settings page, see https://bugs.chromium.org/p/chromium/issues/detail?id=705441.

**Comment by freshp86** [comment]
@sorvell, @kevinpschaaf, @tjsavage, @danbeam

**Comment by kevinpschaaf** [comment]
I believe we considered this issue but the automatic change notification is not easily switched at runtime so we left that as a limitation (apparently it didn't get doc'ed well).

However there's a nice and simple workaround. There's already an event fired every time renderedItemCount changes, and that's dom-change. So you can just specify a custom event for the 2-way binding of `{{renderedItemCount::dom-change}}`.

https://jsfiddle.net/a82zofo5/2/

**Comment by kevinpschaaf** [comment]
Closing, as the workaround should be sufficient for the (advanced) case of using this feature, since the cost of making notify switchable at runtime is out of scope for 1.x.
