### ISSUE TITLE
unwanted html character encoding

### ISSUE THREAD

**Issue by vpusher** [Polymer/polymer#4467]
### Description

I am trying to print some unicode emojis (😀) using html entities markup `(&#xxxxx;)`

Rhe thing is when using a compound binding like `<span>&#[[item]];</span>`, HTML chars seem to be encoded (e.g. `&` => `&amp;`).

Here is the sample. You can test it on the JSbin live demo using the link below.

```html
<dom-bind>
    <template>
            <template is="dom-repeat" items="[[emojis]]">
                <span>&#[[item]];</span>
            </template>
    </template>
</dom-bind>
<script>
    document.querySelector('dom-bind').emojis = Array.from({length: (10160 - 9986)}, (v, k) => k + 9986);
</script>
```

Also, defining a method that would return the whole string entity gives the same result:

```
function (code) {
    return `&#${code};`;
}
```
> This last try seems a bit normal since it will be outputted as a HTML string within the HTML template.

#### Live Demo

https://jsbin.com/juteguwawe/edit?html,output

#### Steps to Reproduce

Use the provided sample.

#### Expected Results

The outputted HTML should looks like: `&#9986;`

#### Actual Results

The outputted HTML looks like: `&amp;#9986;`

So no emoji is printed, but a raw `&#9986;` text is printed instead.

### Browsers Affected

- [x] Chrome

### Versions

- Polymer: v2.0.0-rc.3
- webcomponents: v1.0.0-rc.7

**Comment by azakus** [comment]
How about you make the array using `String.fromCharCode` like this JSBin: https://jsbin.com/ziqisap/edit?html,output

Although, and @notwaldorf can back me up, you should probably use the unicode code points directly, as some can be multiple javascript code points.

**Comment by vpusher** [comment]
@azakus Yes it indeed works, but shouldn't 

```html
<span>&#9986;</span>
```
and 
```html
<span>&#[[item]];</span> <!-- where item = 9986  -->
```
output the same thing ?

**Comment by jsilvermist** [comment]
I believe the way Polymer sets the bindings is using `textContent`, escaping the html.
As a workaround, you can do it like this:
```html
<span inner-h-t-m-l="[[item]]"></span> <!-- where item === '&#9968;' -->
```

**Comment by baocang** [comment]
@jsilvermist You are right, Polymer parse binding use textContent on textNode, property inner-h-t-m-l will transformed to innerHTML, then call _setUnmanagedPropertyToNode(node, prop, value) do node[prop] = value;

**Comment by vpusher** [comment]
Ok thanks for the explanation.

**Comment by baocang** [comment]
@vpusher The best way like @azakus says using  String.fromCharCode; you can do which you like:

```
<dom-module id="character-escape">
    <template>
        <span id="byCode">[[__fromCharCode(character, node)]]</span>
        <span id="byHtml"></span>
        <span id="byTextContent"></span>
        <span inner-h-t-m-l="&#[[character]];"></span>
    </template>
    <script>
        class HTMLSpan extends Polymer.Element {
            static get is() {
                return 'character-escape';
            }

            static get properties() {
                return {
                    character: {
                        type: String,
                        reflectToAttribute: true,
                        observer: '__characterChanged'
                    }
                };
            }

            __fromCharCode(code) {
                if (code) {
                    return String.fromCharCode(code); // I like this way
                }

                return '';
            }

            __characterChanged(newValue, oldValue) {
                if (newValue) {
                    this.$.byHtml.innerHTML = `&#${encodeURIComponent(newValue)};`;
                    this.$.byTextContent.textContent = String.fromCharCode(newValue);
                } else {
                    this.$.byHtml.innerHTML = '';
                    this.byTextContent.textContent = '';
                }
            }

        }

        window.customElements.define(HTMLSpan.is, HTMLSpan);
    </script>
</dom-module>

<character-escape character="9986"></character-escape>
```
