### ISSUE TITLE
Polymer 2.x. Trying to set node directly as propriety value does not work

### ISSUE THREAD

**Issue by minht11** [Polymer/polymer#4468]
### Description

Trying to set node as propriety value throws error
`static get properties() {
                return {
                  elements:{
                      'card': this.$.findMe
                  }
                }
            }`

trying to do that after ready event works as expected
`ready() {
                super.ready();
                this.elements = {
                    'card': this.$.findMe,
                }
            }`

This was not the case in Polymer 1.8

#### Live Demo
https://jsbin.com/vedagequfi/edit?html,output

#### Expected Results
Node should be set as propriety value correctly.

#### Actual Results
Node is not set as propriety value correctly.

Tested on Chrome 57

**Comment by azakus** [comment]
Yes, `properties()` is evaluated far before the shadowdom is created, and this is by design.
As you say, `ready()` works for this because it happens on each instance, and it is the correct time to do this operation.
