### ISSUE TITLE
Problem with array properties referenced from div 

### ISSUE THREAD

**Issue by mlabarre** [Polymer/polymer#4470]
Hello
I try to show/hide some div boxes from Polymer array properties. I have no success with my code. 
The test have 2 boxs. First is displayed the second is hidden. When I click a the button I want the second appears.

Below my code. Any idea ? Thank you very much.

[https://jsfiddle.net/m_labarre/yehkq9e6/](url)

**Comment by web-padawan** [comment]
1. First, you have a typo in the paper-button `on-tap` attribute value (method should have underscore). See the console:

```
[my-test::_createEventHandler]: listener method 'onTap' not defined
```

2. Then, you should use Polymer mutation methods like this:
```js
this.set('boxes.#1.show', true);
```

And the last suggestion: there is a Slack channel for such questions.

**Comment by mlabarre** [comment]
Oops! Right ! Thank you
