### ISSUE TITLE
Polymer 2: CSS mixins applied when they shouldn't

### ISSUE THREAD

**Issue by tlouisse** [Polymer/polymer#4471]
### Description
For instance, when having 'my-element' and '--my-mixin'...:

Inside style tag of 'my-element':

```

<dom-module id="my-element">
...
 <template>
  <style>
...
  :host(.my-class) {
    --my-mixin: {
      background: yellow;
    }
  }
  .mixin-target {
    background-color:green;
    @apply --my-mixin;
  }
...
  </style>
...
  <div class="mixin-target">
    Mixin target
  </div>
...
 </template>
...
</dom-module>

```
Under the hood, the mixin will be translated to a css variable '--my-mixin_-_background'.
These variable are defined in combination with 'my-class' : 

```
  :host(.my-class) {
    --my-mixin_-_background: 'yellow'
  }
```

Let's say we have a demo page with one instance of my-element with the 'my-class' class and one without.

```
<my-element></my-element>
<my-element class="my-class"></my-element>
```

In both cases, 'background: var(--my-mixin_-_background)' will be added to my-element.
In the instantiation without the class though, these variables shouldn't be applied. 
Since they have no value, they will conflict with properties defined earlier.

#### Steps to Reproduce
See 'Description'.

#### Expected Results
Css variables of mixin are not applied to the element without the class

#### Actual Results
Css variables are applied (without having a value) 

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions
- Polymer: v2.0.0-rc.3
- webcomponents: v1.0.0-rc.7

**Comment by azakus** [comment]
Can you link to an example that shows this to be an issue?

`background: var(--my-mixin_-_background)` will only be added to styles that have `@apply --my-mixin` in the template, and I can't see where that would be in your description.

**Comment by tlouisse** [comment]
My example wasn't clear on that point indeed. I added some extra code to illustratie how the mixin would be applied. 

The problem is that regardless of whether 'my-class' is applied on my-element, --my-mixin_-_background will be applied on the ':host' level of my-element. The problem is that in the my-element instantie without my-class, this variable has no value. This would result in an invalid background and cause the green background to disappear(which shouldn't)

**Comment by tlouisse** [comment]
Update: In the meantime I figured out how polygit works and the problem appears to be a bit more subtle: issues arise when 'sub' and 'main' css properties are used (for instance 'background-color' and 'background' or 'border-width' and 'border').

Please see this example:
http://plnkr.co/edit/RIJMTN6aM9zcXnAed5hO?p=preview

The first instance of 'my-element' should have a green background and a 2px, red border.
When looking at .mixin-target, it appears that 'background' is overwritten by 'background-color' and 'border-width' by 'border'.
The padding however works correctly (a fallback was stored with the value of .mixin-target) since a main property(padding) was overwritten with a main property (padding).

**Comment by LarsDenBakker** [comment]
Any update on this?

**Comment by sorvell** [comment]
Sorry for the delay on this. We can confirm the shorthand/expando property issue and we're considering how best to deal with it. 

This is the same core problem as: https://github.com/Polymer/polymer/issues/3832 so we're closing this issue in favor of the other one.
