### ISSUE TITLE
unable to get source event from a 'track' event 

### ISSUE THREAD

**Issue by vpusher** [Polymer/polymer#4472]
### Description

I am using `Polymer.Gestures` to setup some drag n drop capabilities in my component.

Currently, I add a very basic gesture listener like this: `Polymer.Gestures.addListener(myElement, 'track', trackHandler);`

During the drag n drop, I don't want the window to scroll (mostly on mobile). So, I need to prevent default the related source event. Consequently, I need to access that **source (or original) event** that is used by the track gesture behind the scene.

I found that in my `trackHandler(e)`, I can access it through `e.detail.sourceEvent`.

The thing is it only works on non-touch devices. On touch devices, `e.detail.sourceEvent` is an object of type `Touch` instead of a `TouchEvent` (in my mind).

[Touch doc](https://developer.mozilla.org/fr/docs/Web/API/Touch)
[TouchEvent doc](https://developer.mozilla.org/fr/docs/Web/API/TouchEvent)

Finally, there is no way to get the source event.

I know that I can add a listener on `touchmove` events so I can prevent them, but this is dirty and this is not really the point. This is more about having the same behavior on touch and non-touch devices in terms of API, and find a way to get the source event

#### Steps to Reproduce

1. Create a `<div>`. Let's call it **myDiv**.
2. Append `<div>` to `document.body`
3. Add a track gesture: `Polymer.Gestures.addListener(myDiv, 'track', trackHandler);`
4. Touch and move your finger over **myDiv** on a touch device.
5. Inpect the value of `e.detail.sourceEvent` in the `trackHandler` callback.

#### Expected Results

`e.detail.sourceEvent` should return a `MouseEvent` or a `TouchEvent` and not a `Touch` object.

#### Actual Results

Currently, on touch devices, `e.detail.sourceEvent` return a `Touch` object.

### Browsers Affected

- [x] Chrome

(At least)

### Versions

- Polymer: v2.0.0-rc.3
- webcomponents: v1.0.0-rc.7

**Comment by azakus** [comment]
You shouldn't need any calls to `preventDefault` with `track` events.
You can use `Polymer.Gestures.setTouchAction(myElement, 'none')` and the scrolling will be disabled for you.

In terms of `sourceEvent`, I chose to return Touch because it will have the actual `pageX`, `pageY` and other properties for that finger, rather than TouchEvent, which will only have the properties for the first finger.

Do you still see a need to have `sourceEvent` or some other property link to the `TouchEvent`?

**Comment by vpusher** [comment]
@azakus I am more talking about consistency.

✅ On **Chrome mobile** , the page never scrolls, even without any `touch-action` or `preventDefault`.
✅  On **Chrome desktop**, the page scrolls, but we can prevent default the source event
❌ On **Safari iOS**, the page scrolls, so we need to either prevent default the source event or set the `touch-action` property. The first one is impossible since we don't have access to the source event, the second one seems not working.

Here is my sample: https://output.jsbin.com/qibopimaga

> In terms of sourceEvent, I chose to return Touch because it will have the actual pageX, pageY and other properties for that finger, rather than TouchEvent, which will only have the properties for the first finger.

The `TouchEvent` holds all the `Touch` objects (the first and the following), so everything we need's here, we have much more information and it remains consistent (I mean, reading `e.detail.sourceEvent`, I expect to get ... an Event). In the track handler, developers could use the generic approach thanks to `e.detail.dx`, `e.detail.ddx`, `e.detail.dy`, ... so they don't care about the event type (`TouchEvent` or `MouseEvent`). If they do or if they need more advanced data, developers could use the `e.detail.sourceEvent` so they can read the `pageX`, `pageY` or some other stuff...

What about that ?

**Comment by vpusher** [comment]
@azakus Any update ? 😃

**Comment by Neiyo** [comment]
@azakus  I met the problem @vpusher mentioned in his talk about consistency.Any advice?
