### ISSUE TITLE
Shadow DOM Opt-out 

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#4473]
A long time ask from users is to have a way for a dom-module to render light dom instead of shadow dom.

`window.ShadyDOM = {force: true};` can be used to force ShadyDOM but it only works if you load the webcomponents-lite.js polyfills :(

**Comment by azakus** [comment]
If you override `_attachDom` on an element, you can decide where the template from the dom-module is stamped: http://jsbin.com/momusiz/2/edit?html,output

I don't know if this is exposed well enough in the docs though.

**Comment by azakus** [comment]
Here's the relevant docs in the source: https://github.com/Polymer/polymer/blob/master/lib/mixins/element-mixin.html#L635-L663

**Comment by ebidel** [comment]
Oh easy! Yea, would be great to document this prominently.

**Comment by sorvell** [comment]
It's important to note that if you create an element without Shadow DOM, then styling the element must be done cooperatively.

The element should not have a `<style>` in its template, obviously. The document can contains styles for the element but only if the element is not placed in some other element's `shadowRoot`. Alternatively, an element can try to ensure that it has a stylesheet within the root (via `getRootNode()`) in which it's placed, but there is no built in support for this type of thing in Polymer.

**Comment by justinfagnani** [comment]
This is something that should be discouraged though. With the idea that custom elements are just elements and should generally keep expectations around elements, spontaneously spawning children is a pretty big anti-pattern.

**Comment by jfrazzano** [comment]
If we call them web components or download the app icon, to the desktop would that be better?

Any chance components, factories, and instance binding to element properties come back?

Like can we write a letter on the lameness to someone at standards, or some other browser vendors?
We all try are best, and work hard and have powerful machines, and we cant run an app that would win in a race against a 1981 casio watch, priced at $19.99…. it just seems something went terribly wrong, you guys are in the middle, and like businesses are failing… its an anti-pattern… who voted to so painfully narrow the pattern?

**Comment by kevinpschaaf** [comment]
Will be addressed by https://github.com/Polymer/docs/pull/2035 (https://github.com/Polymer/docs/pull/2035/files#diff-31c80b3198abf2eb5491c81ee9d42886R339)
