### ISSUE TITLE
dom-module simple-element has style outside template on IE11

### ISSUE THREAD

**Issue by roniny-afk** [Polymer/polymer#4474]
dom-module simple-element has style outside template on IE11

Example:
1. clone polymer shop at branch 2.0-preview-class
2. edit version polymer to rc.3
2. install  dependencies
3.  build
4.  $ http-server build/bundled-compiled

IE11 is only error.
![image](https://cloud.githubusercontent.com/assets/13883955/24495939/f9cf3d54-1560-11e7-8c62-06c5176454a4.png)

My Project is  same.

### Versions
- Polymer: 2.0.0-rc.3
- webcomponents: 1.0.0-rc.7
- polymer-cli@next 0.18.0-pre.15

**Comment by azakus** [comment]
Are you saying that Polymer CLI generated elements for you that have styles outside of templates, or that only Shop app has this issue?

**Comment by pongpanot-t** [comment]
Polymer CLI generated elements for me that have styles outside of templates.

**Comment by pongpanot-t** [comment]
I just try on "polymer serve" with out build.
It have same issue.

**Comment by sorvell** [comment]
I wasn't able to repro this with the provided steps. Would you mind verifying and refining or giving alternate repro steps? Thanks.

**Comment by alvarezguille** [comment]
I was able to reproduce this with [polymer-2-starter-kit](https://github.com/polymerelements/polymer-starter-kit/tree/2.0-preview
)
### Versions
- polymer-cli: 0.18.0-pre.15
- polymer: 2.0.0-rc.3
- webcomponentsjs: 1.0.0-rc.7

**Comment by pongpanot-t** [comment]
Follow these steps:
- install polymer-cli 0.18.0-pre.15
- polymer init "polymer-2-starter-kit"
- polymer serve

![image](https://cloud.githubusercontent.com/assets/13883955/24846995/4ed0d260-1de8-11e7-962d-90c584b1fb87.png)

**Comment by johnthad** [comment]
I am seeing this problem with `polymer --version` 1.5.7, the SHOP app, and IE11. After running `polymer build`, I `cd build/es5-bundled` and serve the page with Python `SimpleHTTPServer`. 

I'm am seeing this problem with my own apps served by Node 8.9.1 and Express 4.16.2, but that is _the least_ of my problems with IE11, where some pages lock-up _repeatedly_ reloading. (Other problems here with `polymer build` that I'll report elsewhere.)
