### ISSUE TITLE
Polymer.html includes micro and mini resulting in double creation of dom-module

### ISSUE THREAD

**Issue by hvdb** [Polymer/polymer#4475]
### Description

So polymer.html includes polymer-mini.html and mini includes micro.
Which is ok.
But, in mini and micro createElement.('dom-module') is defined.
This results in two createElement.('dom-module') in the vulcanized output.

https://github.com/Polymer/polymer/blob/v1.8.1/polymer-mini.html#L2131
https://github.com/Polymer/polymer/blob/v1.8.1/polymer-micro.html#L414

They are also doing it  in a different way also.

(example: https://raw.githubusercontent.com/hvdb/hvdbPLCliNotDedubbing/master/build/bundled/src/shell.html)
both createElement are added.
And this can result in errors, not in all our apps it is a problem.

Do we do something wrong? Is it intended to have it twice?
Or is it a bug?

#### Steps to Reproduce
Add polymer.html as dependency.

#### Expected Results
don't register the dom-module twice/no duplicate code.

#### Actual Results
https://raw.githubusercontent.com/hvdb/hvdbPLCliNotDedubbing/master/build/bundled/src/shell.html
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions
- Polymer: v1.8.1

**Comment by web-padawan** [comment]
This is OK. Only `document.registerElement` call must be unique for given tag name, but not `document.createElement`>

**Comment by hvdb** [comment]
Right, if i have read the error better i should have seen that >.<

```
Uncaught DOMException: Failed to execute 'registerElement' on 'Document': Registration failed for type 'dom-module'. A type with that name is already registered.
```

Then something is registering dom-module again:/
Will look into the code further!

Still weird to have duplicate code if you ask me.🥇

**Comment by web-padawan** [comment]
There are lots of treads like this... you are likely importing polymer twice from different locations. I hope in the future `polymer lint` will warn about it.

**Comment by azakus** [comment]
Those `createElement` calls are for different purposes, and are intentional.

If you're seeing that `registerElement` error, that means you are importing Polymer twice, as @web-padawan stated.
