### ISSUE TITLE
Make error messages more verbose

### ISSUE THREAD

**Issue by owencm** [Polymer/polymer#4478]
### Description
Some errors aren't very helpful. For example, when passing malformed JSON as a property I see: 

"Polymer::Attributes: couldn`t decode Array as JSON"

but it would have been more helpful to know which string it tried to decode and failed, in this case "['Owen','Elizabeth']".

Preferred error message: "Polymer::Attributes: couldn`t decode Array as JSON: ['Owen','Elizabeth']"

### Versions
- Polymer: "2.0-preview"

**Comment by sorvell** [comment]
We endeavor to make error messages useful in general. 

We'll go ahead and change this one, and welcome other examples that could stand improvement.
