### ISSUE TITLE
Polymer 2 -- support async flag on polymer-element.html import

### ISSUE THREAD

**Issue by bahrus** [Polymer/polymer#4487]
I would like to be able to set the async flag on the polymer element import in order to prevent synchronous blocking:

```html
<link async rel="import" href=".bower_components/polymer/polymer-element.html">
```
and to still be able to extend Polymer.Element.  

Doing so requires knowing when Polymer.Element is defined.  So I'm looking for an elegant way to wait for Polymer.Element to be defined.  The closest thing I can find documented for how to do this is [here](https://www.polymer-project.org/2.0/docs/devguide/registering-elements#main-document-definitions), which uses HTMLImports.whenReady

However:

- HTMLImports is only defined if you use webcomponents-lite.js.  It is not defined if you use webcomponents-loader.js
- Evidently it is not [supposed to support async imports anyway](https://github.com/webcomponents/webcomponentsjs/issues/431).

In my view, the most elegant, intuitive solution for this would be if:

```JavaScript
customElements.whenDefined('dom-module', ...)
```
was fired only after Polymer.Element is defined.  But I'm finding that it is fired before.

**Comment by sorvell** [comment]
You can listen for the `load` event on the import for `polymer-element.html`. Is that sufficient?

**Comment by kevinpschaaf** [comment]
See http://jsbin.com/sucoriz/1/edit?html,output for an example.

Closing, as the `load` event is the correct platform signal to use.

**Comment by bahrus** [comment]
I actually briefly considered this, but I didn't think it would be a very elegant solution (and wasn't sure it would work for multiple components, some of which may load _after._ polymer has already loaded).  It appears to require polluting the global namespace with a unique function for each component one defines.  Perhaps one could programmatically attach an event handler to the first Polymer.element import it finds, but how to query for this node, since the paths might not be the same, in order to avoid that?  One could internally agree to some way of identifying these import dom elements, or make a guess based on  the existence of polymer-element.html in the href, I suppose.

Anyway,  even though this seems ineligant, that's a judgment call, I guess.   I'll play around with this solution, and reopen if I encounter anything insurmountable.

Thanks for the suggestion.

**Comment by bahrus** [comment]
I did encounter what might be an insurmountable problem, or at least one that adds to the inelegance of this solution.  I ran into a bit of a chicken and egg problem. I'm defining the JavaScript in a separate class from the html file.

So, for example:

xtal-checkbox.html:

```html
<link onload="initXtalCheckbox()" rel="import" href="../bower_components/polymer/polymer-element.html">
<dom-module id="xtal-checkbox">
    <template>
        <input checked$="{{isChecked}}" type="checkbox" on-click="handleClickEvent" id="checkbox"/>
    </template>
    <script src="xtal-checkbox.js"></script>
</dom-module>
```

xtal-checkbox.js:
```JavaScript
function initXtalCheckbox(){
        class XtalCheckbox extends Polymer.Element{
        }
}
```
If xtal-checkbox.js happens to load before Polymer does, great.  If not, I get an error that     initXtalCheckbox doesn't exist.

**Comment by bahrus** [comment]
I don't seem to be able to reopen this issue.  In my mind, I'm not yet convinced this is the right solution.

**Comment by bahrus** [comment]
I suppose the way to "fix" both the issue of global function pollution, and the issue above, is to programmatically add the import polymer-element.html statement within the external js file (or wherever the code for the extending class is located, and dynamically add the onload event handler to the dynamically created import element.  Being that Polymer isn't defined, we can't use any utlities Polymer might provide for this.  This might also break tooling that looks for declarative dependencies, and just seems downright complicated for what I suspect will be a commonly desired scenario.

**Comment by bahrus** [comment]
Update:

Well, in the apparent absence of Polymer providing any help with this, and in case you come across this with the same issue I had, and have the same sense of what makes something elegant vs. a hack as I have, the solution I came up with is:

1.  Make all your web components extend Polymer.Element.  But don't make them import the polymer-element.html.  

2.   Instead, make them import a common file.  Let me call it "polymer-loader.html."  This is the one file that imports polymer-element.html, using the declarative

```html
<link async rel="import" href="bower-components/polymer/polymer-element.html" onload="someGlobalFunction()"/>
```  
tag.  Note the on-load function handler within the declarative import, that references a single globally available function.

3.   The globally available function creates an empty custom element within the polymer-loader.html file (no external reference here), something like

```JavaScript
function someGlobalFunction(){
   customElements.define('poly-loader', class extends HTMLElement{});
}
```
 Then define all your classes that extend Polymer.Element within a promise:

```JavaScript
customElements.whenDefined('poly-loader').then(() => {
class MyComponent extends Polymer.Element{
})
customElements.define(MyComponent.is, MyComponent)
});
```
