### ISSUE TITLE
polymer-2-element template fails tests out of the box

### ISSUE THREAD

**Issue by thomastodon** [Polymer/polymer#4491]
### Description
`element.is` returns `undefined` under test in **polymer-2-element** template

#### Steps to Reproduce
- `$ polymer init`
- select `polymer-2-element`
- `$ polymer test -l chrome`

#### Expected Results
```
Tests passed
```

#### Actual Results
```
✖ test/polymer-test_test.html » polymer-test » instantiating the element works
expected undefined to equal 'polymer-test'
```

### Browsers Affected
- [x] Chrome

### Versions
- Polymer: v2.0.0-rc.3
- webcomponents: v1.0.0-rc.7

**Comment by azakus** [comment]
Looks like the generated test is testing `elementInstance.is`, but the `is` getter is on the constructor, so it should be `elementInstance.prototype.constructor.is`

**Comment by azakus** [comment]
This issue was moved to Polymer/polymer-cli#643
