### ISSUE TITLE
Polymer taking 100% CPU on iOS device

### ISSUE THREAD

**Issue by jehna** [Polymer/polymer#4494]
### Description
On specific conditions Polymer uses up to 100% CPU on an iOS device, even on totally static site.

#### Demo
Clone and run the following repository:

https://github.com/jehna/polymer-100-percent-cpu-usage-on-ios-bug

#### Steps to Reproduce

1. Clone the repository https://github.com/jehna/polymer-100-percent-cpu-usage-on-ios-bug
2. Install dependencies with `bower install`
3. Run the web server with `npm run start`
4. Open the site with iOS device on http://localhost:8081

#### Expected Results

The site should render and the CPU usage should drop to almost 0% after the page has been rendered.

#### Actual Results

The page continuously uses 60-100% CPU as long as the user stays on the site.

Screen shot from the xcode's "Energy log" instrument recorded on iPhone 5 on iOS 10.2

![segsgge](https://cloud.githubusercontent.com/assets/2676795/24656953/2b7bc9f4-194d-11e7-8d24-2ccf2ae39ffc.png)

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
- [x] iOS Safari

Tested on iPhone 5 and iPhone 6 plus on iOS 10.2 Safari.

### Versions

- Polymer: ^2.0.0-rc.3
- webcomponents: v1.0.0-rc.7

**Comment by jehna** [comment]
On real devices this bug is 100% reproduceable. On iOS simulator (tested iPhone 6 simulator on iOS 10.2 and iOS 10.3) seems to work only on the first page load.

On initial load the simulator takes 100% CPU:

![screen shot 2017-04-04 at 15 50 11](https://cloud.githubusercontent.com/assets/2676795/24657311/68235484-194e-11e7-9091-965f24699371.png)

After refresh the simulator does not take 100% CPU anymore.

**Comment by sorvell** [comment]
That sounds bad. We'll definitely take a look and see what's up.

**Comment by sorvell** [comment]
Unfortunately, this appears to be a browser bug in Safari/iOS. Here's a minimal repro that does not use Polymer: http://output.jsbin.com/gakasej. I went ahead and filed this as an iOS issue that on that tracker has id 31436795.

In the meantime, I'd recommend trying to avoid one of the necessary conditions required to produce the issue. These appear to be: (1) web font, (2) custom property, (3) transition, (4) background: linear-gradient using custom property.
