### ISSUE TITLE
"ReferenceError: Polymer is not defined" when running the polymer-2-application on Chrome v.27

### ISSUE THREAD

**Issue by gilberto-torrezan** [Polymer/polymer#4495]
One of our customers is building an application with Polymer 2, and he wants it to be crawlable by search bots, such as googlebot. And as far as I know, googlebot uses a very old chrome version (namely - v.27) to parse the page and execute javascript.
So basically, I'm looking for ways to run a Polymer 2 application in that old chrome.

### Description
When running the simple application with Polymer 2, compiling it to ES5 and adding the needed polyfills, the application runs on IE11, but fails to run on Chrome v.27, with the message: `ReferenceError: Polymer is not defined`.

#### Steps to Reproduce
1. Create a new simple project by running `polymer init` and selecting the option `polymer-2-application`.
2. For this test, I used the project name `chrome-test` and main element name also `chrome-test`.
3. Modify the generated bower.json file to include the dependencies needed for the polyfills:
```
{
  "name": "chrome-test",
  "description": "Test for Chrome 27",
  "main": "index.html",
  "dependencies": {
    "polymer": "Polymer/polymer#^2.0.0-rc.3"
  },
  "devDependencies": {
    "iron-component-page": "PolymerElements/iron-component-page#2.0-preview",
    "iron-demo-helpers": "PolymerElements/iron-demo-helpers#2.0-preview",
    "web-component-tester": "v6.0.0-prerelease.5",
    "webcomponentsjs": "webcomponents/webcomponentsjs#1.0.0-rc.7",
    "es6-shim": "paulmillr/es6-shim#v0.35.3",
    "custom-elements-es5-adapter.js": "webcomponents/webcomponentsjs#1.0.0-rc.7"
  },
  "resolutions": {
    "polymer": "^2.0.0-rc.3"
  }
}
```
4. Run `bower install` to download the required libraries
5. Modify the `index.html` file to add the polyfills:
```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, minimum-scale=1, initial-scale=1, user-scalable=yes">

    <title>chrome-test</title>
    <meta name="description" content="chrome-test description">

    <!-- See https://goo.gl/OOhYW5 -->
    <link rel="manifest" href="/manifest.json">

    <script src="/bower_components/es6-shim/es6-shim.min.js"></script>
    <script src="/bower_components/webcomponentsjs/webcomponents-loader.js"></script>

    <link rel="import" href="/src/chrome-test/chrome-test.html">
  </head>
  <body>
    <chrome-test></chrome-test>
  </body>
</html>
```
6. Run the `polymer build --js-compile` command
7. Run the `polymer serve -p 8080` command from the generated `build/default` folder
8. Access `http://localhost:8080/` from Chrome v27.

(Note, if you are running the old Chrome from a VM or a separate machine, you may need to run `polymer serve -p 8080 -H 0.0.0.0`)

#### Expected Results
A sentence `Hello chrome-test` appears in the page.

#### Actual Results
The sentence `Hello chrome-test` appears in all supported browsers, including IE11, but in Chrome v.27 the sentence is not rendered at all, and the console shows the error `ReferenceError: Polymer is not defined`.

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v2.0.0-rc.3
- webcomponents: v1.0.0-rc.7

**Comment by arthurevans** [comment]
Have you tried it without the ES6 shim? Chrome 27 doesn't support ES6 classes, so that's bound to fail. For testing purposes, you might also try it with the full polyfill (`webcomponents-lite.js`) rather than the loader and see if that's causing a problem.

**Comment by gilberto-torrezan** [comment]
Thanks @arthurevans for the reply. Yes I tried without ES6 shim as well, but then receive another error on top of the Polymer one: `ReferenceError: Set is not defined`.

I also tried with the `webcomponents-lite.js` in the place of the loader. No luck as well - I receive the same error.

**Comment by tjsavage** [comment]
Hey @gilberto-torrezan - the [Fetch and Render](https://support.google.com/webmasters/answer/6066468?hl=en) tool is the source-of-truth for seeing what the Googlebot sees. Are you seeing this same problem using this tool?

**Comment by gilberto-torrezan** [comment]
Hi @tjsavage, in fact, the page renders correctly when using the Fetch and Render tool. The confusion about the v27 thing arose because of the browser version used by the tool to preview the website (at the section "This is how a visitor to your website would have seen the page"). It is not related to the actual Googlebot.

So while Polymer 2 is still broken on v27, this is not relevant for the actual problem anymore, which was making a Polymer 2 application crawlable. So I'll close this issue.

Thank you for you help.
