### ISSUE TITLE
setProperties on read-only properties

### ISSUE THREAD

**Issue by e111077** [Polymer/polymer#4498]
### Description

It would be helpful in certain elements like `iron-image` to use `setProperties` on read-only elements where we have to notify the user whether the image has loaded, stopped loading, and errored at the same time. Perhaps an override argument that defaults to false?

`this.setProperties({a: true, b: true}, true)`

### Browsers Affected

- [x] All

### Versions

- Polymer: v2.0.0
- webcomponents: v1

**Comment by kevinpschaaf** [comment]
Yeah, I think we'd consider that.  A `setReadOnly` flag on `setProperties`.
