### ISSUE TITLE
Use of Polymer Elements with Polymer2 (iron-list)

### ISSUE THREAD

**Issue by jogibear9988** [Polymer/polymer#4505]
Is it possible to use the Polymer Elements with the Polymer 2 Version?

**Comment by web-padawan** [comment]
In general, some elements not using deprecated API could just upgrade their dependencies. 
For `iron-list` and other official elements, please check 2.0-preview branch.

**Comment by kevinpschaaf** [comment]
As @web-padawan says, please check for `2.0-preview` branches on elements until the final `2.0` release of elements is announced.  See https://github.com/PolymerElements/iron-list/tree/2.0-preview.

**Comment by jogibear9988** [comment]
Is there an easy way, I could install 2.0preview elements via bower? (so dependencies get also resolved?)
