### ISSUE TITLE
Polymer v2: this.parentElement points to the wrong DOM element when using polyfills

### ISSUE THREAD

**Issue by SchnWalter** [Polymer/polymer#4506]
### Description
`this.parentElement` points to a different DOM element polyfills are used (i.e. FireFox)

#### Demo
I coudn't convice jsbin & polygit to play nice, so I'll paste here bits and pieces required to reproduce this.

#### Steps to Reproduce

1. Create a new `<example-list>` element using `polymer-cli init polymer-2-element`
2. Append this to element template: `<div class="items-wrapper"><slot></slot></div>`
3. Create a new `<example-item>` element and add these lines to the `connectedCallback()` and a click handler:
```
console.log(this.parentElement.tagName + '.' + this.parentElement.className);
console.log(this.parentNode.tagName + '.' + this.parentNode.className);
```
4. Update the demo:
```
<-- head -->
<link rel="import" href="../example-list.html">
<link rel="import" href="../example-item.html">

<-- demo-snippet > template -->
<example-list class="list" label="Distributions">
  <example-item class="item" name="Fedora"></example-item>
  <example-item class="item" name="openSUSE"></example-item>
  <example-item class="item" name="Arch"></example-item>
</example-list>
```
5. Run the demo and click on any of the items.

#### `example-list.html`

```
<link rel="import" href="../polymer/polymer.html">
<dom-module id="example-list">
  <template>
    <style>
      :host {
        display: block;
      }
    </style>

    <h2 class="label">[[label]]</h2>
    <div class="items-wrapper"><slot></slot></div>
  </template>

  <script>
    class ExampleListElement extends Polymer.Element {
      static get is() { return 'example-list'; }
      static get properties() {
        return {
          label: {
            type: String,
            value: 'This is a list'
          }
        };
      }
    }

    window.customElements.define(ExampleListElement.is, ExampleListElement);
  </script>
</dom-module>
```

#### `example-item.html`

```
<link rel="import" href="../polymer/polymer.html">
<dom-module id="example-item">
  <template>
    <style>
      :host {
        display: block;
      }

      div {
        cursor: pointer;
        display: list-item;
        margin-left: 2em;
      }
    </style>

    <div on-click="handleClick">Hello [[name]]!</div>
  </template>

  <script>
    class ExampleItemElement extends Polymer.Element {
      static get is() { return 'example-item'; }

      static get properties() {
        return {
          name: {
            type: String,
            value: ''
          }
        };
      }

      connectedCallback() {
        super.connectedCallback();
        console.log(this.parentElement.tagName + '.' + this.parentElement.className);
        console.log(this.parentNode.tagName + '.' + this.parentNode.className);
      }

      handleClick() {
        console.log(this.parentElement.tagName + '.' + this.parentElement.className);
        console.log(this.parentNode.tagName + '.' + this.parentNode.className);
      }
    }

    window.customElements.define(ExampleItemElement.is, ExampleItemElement);
  </script>
</dom-module>
```

#### Expected Results
You should have the same console log output in browsers that use polyfills (FireFox) and browsers that don't (Chromium/Chrome)

You will see this output for the `connectedCallback()` and the click handler:
> EXAMPLE-LIST.list
> EXAMPLE-LIST.list

#### Actual Results
In borwsers with polyfills (FireFox), you will see this output for the `connectedCallback()`handler:
> EXAMPLE-LIST.list
> EXAMPLE-LIST.list

But for the click handler you will see:
> DIV.items-wrapper style-scope example-list
> EXAMPLE-LIST.list

With `DIV.items-wrapper` being the parent element of the `<slot>` tag inside the shadow dom.

### Browsers Affected
- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v2.0.0-rc.3
- webcomponents: v1.0.0-rc.7

**Comment by sorvell** [comment]
This is a Shady DOM issue. Closing here in favor of https://github.com/webcomponents/shadydom/issues/119.
