### ISSUE TITLE
dom-bind doesn't init `tap` recognizer

### ISSUE THREAD

**Issue by valdrinkoshi** [Polymer/polymer#4509]
In 1.x `logEventType` would be invoked twice, in 2.x only once.
```html
  <dom-bind>
    <template is="dom-bind">
      <button on-tap="logEventType" on-click="logEventType">button</button>
    </template>
  </dom-bind>
```
http://jsbin.com/lixujah/1/edit?html,console,output

It seems that in 2.x `tap` recognizer is not initialized

**Comment by kevinpschaaf** [comment]
Ok, for BC/hybrid we'll add `Polymer.GestureEvents` to `dom-bind`.
