### ISSUE TITLE
Bug in refresh of dom-repeat template with strip-whitespace attribute and dom-if in content

### ISSUE THREAD

**Issue by jpradelle** [Polymer/polymer#4512]
Bug when I add an element in a list which is displayed in a dom-if within a dom-repeat template with strip-whitespace attribute: the new element is not displayed at the good position.

#### Live Demo
https://jsbin.com/kohuhu/edit?html,output

### Versions
I can reproduce with Polymer 1.2.0 to 1.8.1
Seems to be ok with Polymer 2.0.0-rc3

**Comment by TimvdLippe** [comment]
As this has been fixed in Polymer (http://jsbin.com/maxudequwu/edit?html,console,output) I am closing this issue. Please update to the latest version of Polymer to fix such bugs. Thanks for reporting and investigating this was resolved in Polymer 2 vs 1!
