### ISSUE TITLE
dom-bind giving error:  Polymer.OptionalMutableData is not a function

### ISSUE THREAD

**Issue by bahrus** [Polymer/polymer#4517]
### Description
dom-bind giving error:  Polymer.OptionalMutableData is not a function

#### Live Demo
https://rawgit.com/bahrus/xtal/master/tests/xtal-fetch.test2.html

#### Steps to Reproduce
Use this markup:

```html
<html>
    <head>
        <script src="../bower_components/webcomponentsjs/webcomponents-loader.js"></script>
        <link rel="import" href="../bower_components/polymer/polymer-element.html">
        <link rel="import" href="../bower_components/polymer/lib/elements/dom-bind.html">
    </head>
    <body>
        
        <dom-bind>
            <template>
                <input type="text">
            </template>
        </dom-bind>
    </body>
</html>
```

#### Expected Results
No error is thrown

#### Actual Results
I see this in the console
dom-bind.html:19 Uncaught TypeError: Polymer.OptionalMutableData is not a function
    at dom-bind.html:19
    at dom-bind.html:107
(anonymous)	@	dom-bind.html:19
(anonymous)	@	dom-bind.html:107

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: 2.0.0-rc.3
- webcomponents: v1.0.0-rc.7

**Comment by kevinpschaaf** [comment]
Resolved via #4515.
