### ISSUE TITLE
UI was not updated with the Array item 

### ISSUE THREAD

**Issue by yanlee26** [Polymer/polymer#4518]
I defined one class like this
```
class P{}
Object.assign(P.prototype,{
add(){},
remove(){},
//...
})
```
And did as follows:
//1. include this file ``` ```
//2. make an instance of the Outright ```let leg=new P() ```
//3. use the methods or properties of the instance ```leg.clm;leg.mockData;leg.add();leg.insert();leg.remove();leg.change;//... ```

**Comment by kevinpschaaf** [comment]
If you are still having an issue, could you please follow the instructions in https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs and re-open using the issue template with proper live reproduction steps (e.g. [jsBin](http://jsbin.com/tatizip/1/edit?html,output) showing issue)?  Thank you.
