### ISSUE TITLE
Polymer. After dom-repeat, child offsetLeft returns an invalid value

### ISSUE THREAD

**Issue by alberto-donat** [Polymer/polymer#4519]
Hello everybody

I execute a dom-repeat to fill a horizontal flexbox with some items. In dom-change event i'm trying to get the offsetLeft of one of the flexbox childs created, in order to scroll to it to make it visible.

My problem is that, offsetLeft always returns a value corresponding to the first child, no matters what child i ask for. It only happens, after recently execute dom-repeat. If a execute the same code when on-tap a child, it works fine.

Anyone has any suggestion to solve the problem, or other strategy to get the same result ?

Thanks a lot in advance

---
           <div on-tap="_itemTap" class="main-container" id="myCard">
                <template id="lista" is="dom-repeat" items="[[data]]" on-dom-change="_DOMChanged">
                    <visophy-list-day-item
                        id="ID_[[item.id]]" 
                        class="item"
                        top-text="[[item.topText]]"
                        bottom-text="[[item.bottomText]]">
                    </visophy-list-day-item>
                </template>

            </div>
---

---
             this.$.myCard.scrollLeft = (this.$$("#" + item.id).offsetLeft - 
                                                        ((this.$.myCard.offsetWidth)/2) + 
                                                        (this.$.leftButton.offsetWidth*2));
---

**Comment by kevinpschaaf** [comment]
Would you mind throwing that code in a live/working [`jsbin`](http://jsbin.com/tatizip/1/edit?html,output) that shows the issue?  Thanks.

**Comment by kevinpschaaf** [comment]
Also, please be sure to use the [issue template](https://github.com/Polymer/polymer/issues/new) when filing new bugs, including indicating **which version of Polymer your bug applies to**.

**Comment by alberto-donat** [comment]
### Description
After dom-repeat, child offsetLeft returns an invalid value

### Live Demo
http://jsbin.com/vayacaw/edit?html,output

#### Steps to Reproduce
1. Execute dom-repeat
2. on dom-change event, change a property in order to scroll the list

#### Expected Results
Scroll the flexbox to the selected item

#### Actual Results
offsetLeft returns 0, so doesn't scroll
In JSBind, seems to work fine, but doesn't in 

### Browsers Affected
- [ X ] Chrome


### Versions
- Polymer: v1.7.1
- webcomponents: v0.7.23

**Comment by arthurevans** [comment]
Hi Alberto,

I suspect the timing in the JSBin is throwing things off... I was able to reproduce an issue by populating the list at runtime. 

In my case, that turned out to be because the `listDOMChanged` flag was already set (because it fires once when the element is initialized with an empty list). Setting the flag to false before setting new items to the list fixed this problem. Not sure if this is related to the issue you're seeing, but it was the only instance in which I was able to reproduce a similar problem. 

https://jsbin.com/xuhesoz/edit?html,console,output

**Comment by alberto-donat** [comment]
Hi everybody,

I apologize, it's the first time that i use JSBin.

The data to populate the flex panel, is loaded at runtime. The process works well, data is loaded, and dom-repeat creates the DOM nodes for that data, but the issue happens when dom-change event fires. If i execute the same code later, for example a button on_tap event, it works fine. It seems to be a sinchro fail, when dom-repeat finishes, and the nodes created don't get the right properties.


Thanks
