### ISSUE TITLE
Facebook JS SDK Error when including platform.js

### ISSUE THREAD

**Issue by lbertenasco** [Polymer/polymer#452]
Hello, i hope this is the right place to ask for help...

I have been having some trouble trying to add fb-js-sdk to my polymer project, and i failed to find any help on the web.

Here is the code: https://gist.github.com/lbertenasco/9630905

It throws "The string contains invalid characters."

But if you delete this line

    <script src="bower_components/platform/platform.js"></script>

It works perfectly

I think i read that it was a problem with the DOM of the element or something like that...

Feel free to close this if it's not an relevant issue.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

**Comment by ankitkante** [comment]
Hi
I am using polymer-starter-kit having `Polymer 2.0.2`. In index.html, `webcomponents-loader.js` is being loaded like this: 
`<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>`

When I remove this line, Facebook SDK works in Firefox,but, with webcomponents, `FB.api` doesn't work. This is same as @lbertenasco  reported with `Polymer 1` and `platform.js`.

**Comment by ankitkante** [comment]
Ok I figured it out. 
If I add the sdk initialization code in my project's `index.html`, it does not work.
But, if I add it in the `connectedCallback` of  `my-app.html`, the sdk works.
