### ISSUE TITLE
dom-repeat causes mixins in custom-style not to be rewritten.

### ISSUE THREAD

**Issue by bicknellr** [Polymer/polymer#4521]
### Description
A dom-repeat with no content in this particular place in this document causes CSS mixins in the document not to be rewritten into plain CSS variables.

#### Live Demo
http://plnkr.co/edit/py2cAnXP7sT0rrZlgK2o?p=preview

#### Steps to Reproduce
I don't know how to reproduce this other than with the above demo.

#### Expected Results
The CSS mixins are always rewritten.

#### Actual Results
The CSS mixins are not rewritten on the page in that demo with the dom-repeat.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [X] Safari 10
(I didn't test others.)

### Versions
- Polymer: v2.0.0-rc.3
- webcomponents: v1.0.0-rc.7

**Comment by bicknellr** [comment]
cc @azakus

**Comment by azakus** [comment]
Need to investigate if this belongs in Polymer or ShadyCSS

**Comment by azakus** [comment]
Looks like `dom-repeat` and `dom-if` can call into ShadyCSS before the dependencies for `custom-style` have loaded.

However, elements that don't have a `template` like `dom-repeat` don't need to try styling themselves, so the simplest fix is to just ensure that only elements with `template` call into ShadyCSS.
