### ISSUE TITLE
Hybrid usage of dom-bind stamps content in different places in 1.x and 2.x.

### ISSUE THREAD

**Issue by bicknellr** [Polymer/polymer#4536]
In hybrid code, dom-bind (and others) have to be written as a combination of both wrapper and `is=` form:
```html
<dom-bind>
  <template is="dom-bind">
    <some-element></some-element>
  </template>
</dom-bind>
```
In 1.x, the content ends up stamped like this:
```html
<dom-bind>
  <some-element></some-element> <!-- content stamped here -->
  <template is="dom-bind">
    <some-element></some-element>
  </template>
</dom-bind>
```
But in 2.x, the content is stamped like this:
```html
<some-element></some-element> <!-- content stamped here -->
<dom-bind>
  <template is="dom-bind">
    <some-element></some-element>
  </template>
</dom-bind>
```

This can be a problem if the content depends on looking at the tree it's inserted in, such as IronFitBehavior.

#### Expected Results
The content of the dom-bind's template is stamped before the dom-bind element in the 1.x case.

#### Actual Results
The content of the dom-bind's template is stamped inside the dom-bind element but before the template in the 1.x case.

**Comment by kevinpschaaf** [comment]
Fixed via https://github.com/Polymer/polymer/pull/4537. Will be released in `v1.9.1`
