### ISSUE TITLE
Polymer 2.0 library transpilation using Gulp ES6 to ES5 (Documentation Request)

### ISSUE THREAD

**Issue by myuseringithub** [Polymer/polymer#4549]
Wasted a lot of days trying to support ES5 browsers when using Polymer 2.0 ES6 (ES2015+) class-syntax. Finally I got it to work, a simple snippet of code & a paragraph could easily guide me to the answer, instead of digging through `polymer-cli`, `webcomponentsjs`, `polymer-build` trying to understand how to support pre-ES6 browsers. 

## Files to transpile:
- `Polymer/polymer@2.0-preview` library should be transpiled to ES5. As it is released for modern browsers supporting ES6 (no separate ES5 release or transpilation included in the library). 
- Officially released webcomponents 2.0-preview (bower_components) should be transpiled to ES5. 
- Your custom elements should be ofcourse also transpiled.
- `webcomponentsjs` library should be left untouched (do not transpile). 

## Scripts to load: 
Shims/Polyfills to use for adding new features support:
- `webcomponents-lite.js` should be loaded to add shim for new DOM V1 features and others.
- `custom-elements-es5-adapter.js` is used to support modern ES6 browsers (fixing the class inherence issue after transpiling classes to common js), in case the app is served in ES5 only. As there is an option also to server different distribution codes according to the browsers requesting the app (`user-agent`), which is the recommended way for getting best performance on modern browsers.

## Transpilation tool:
- Transpilation of custom elements and officially released webcomponents can be transpiled with regular `babel-preset-es2015 preset`.
- Babel transpilation of the Polymer 2.0 library - for transpilation to work correctly, no modules option should be used - `require('babel-preset-es2015').buildPreset({}, {modules: false});`. As shown in the `polymer-cli` [https://github.com/Polymer/polymer-cli/blob/5cbe87dd90b412c15eac2c6ed8147d59c95b0e6e/src/build/optimize-streams.ts#L25](url) or the example below.

### Example of Gulp build for ES5 transpilation using Babel:
```
const gulp = require('gulp'),
	gulpif = require('gulp-if'),
	HtmlSplitter = require('polymer-build').HtmlSplitter,
	sourcesHtmlSplitter = new HtmlSplitter(),
	babelPresetES2015 = require('babel-preset-es2015'),
	babelPresetES2015NoModules = babelPresetES2015.buildPreset({}, {modules: false}),
	babel = require('gulp-babel')

gulp.task('polymerLibraryTranpilation', () => {
	return gulp.src([
                    './bower_components/polymer/**/*.html'
                ])
		.pipe(sourcesHtmlSplitter.split())
		.pipe( gulpif( /\.js$/, babel({ "presets": [ babelPresetES2015NoModules]}) ) )
		.pipe(sourcesHtmlSplitter.rejoin())
		.pipe(gulp.dest('./bower_components/polymer'))
})

gulp.task('webcomponentsTranspilation', () => {
	return gulp.src([
			'./yourCustomWebcomponentsFolder/**/*.html',
                 	'./bower_components/**/*.html',
			'!' + './bower_components/webcomponentsjs/**/*.html',
			'!' + './bower_components/polymer/**/*.html',
                ])
		.pipe(sourcesHtmlSplitter.split())
		.pipe( gulpif( /\.js$/, babel({ "presets": ['./node_modules/babel-preset-es2015']}) ) )
		.pipe(sourcesHtmlSplitter.rejoin())
		.pipe(gulp.dest('./'))
})

```
_The code snippet is not tested, so expect syntax errors, I actually use a custom very different build, but the concept should be the same._

### Versions: 
Tested on these versions:
- Polymer v2.0.0-rc.6
- Webcomponentsjs v1.0.0-rc.8

In Bower.json (don't forget to persist the versions, as Bower can be hard to work with sometimes):
- `"polymer": "Polymer/polymer#2.0.0-rc.6",` 
- `"webcomponentsjs": "webcomponents/webcomponentsjs#1.0.0-rc.8"`
 
Hope this helps.

**Comment by justinfagnani** [comment]
@arthurevans and @katejeffreys where in the docs do we want a page(s) on compilation? With the polyfills?

**Comment by arthurevans** [comment]
We were going to put that in Kate's build doc: 

https://github.com/Polymer/docs/pull/2028/files

Note that the existing doc covers Polymer CLI, which just does the right thing. For people rolling their own builds, we need to cover what @myuseringithub described above.

Justin, if someone from your team could pitch in with a review of that doc that would be 🥇. Kate will definitely need help with one or more custom build examples.

A couple of people have suggested examples in slack, but I don't have the slightest idea what most of them are doing, and Kate's had even less exposure to gulp than I have. If anyone can come up with a practical, tested, and above all _simple_ example, that would be :100:.

**Comment by myuseringithub** [comment]
@arthurevans Hi there, could you please add a section explaining on which basis should the compiled version be served. i.e. what conditions should be used to differentiate between serving compiled ES5 & serving ES6 code ?

Should I traget browsers below the version that support these features:
• ES6 support.
• Shadow DOM v1

Currently, I use something like the below conditions. Basically serving the compiled version of the app to all browsers that have less than 90% ES6 implementation (Which I looked up on `https://kangax.github.io/compat-table/es6/`)
```
function shouldServeES5(agent) {  // if compiled ES5 code should be served.
    switch (agent.family) {
        case 'Chrome':
            return agent.satisfies('<50.0.0') ? true : false;
        break;
        case 'Firefox': 
            return agent.satisfies('<45.0.0') ? true : false;
        case 'Edge': 
            return agent.satisfies('<14.0.0') ? true : false;
        case 'Safari': 
            return agent.satisfies('<10.0.0') ? true : false;
        default:
            return true
        break;
    }
}
```

**Comment by arthurevans** [comment]
This issue was moved to Polymer/docs#2050
