### ISSUE TITLE
When does [Stable Release v2.0] is coming out?

### ISSUE THREAD

**Issue by AlexAlabyev** [Polymer/polymer#4555]
Could you please shine some light on the plans for **Stable Release v2.0**
Is there a particular release date? Is it going to be days, weeks or months?
Thanks

**Comment by web-padawan** [comment]
I suppose 2.0 will be presented ad [Google IO](https://events.google.com/io/), although not yet sure about how much *stable* it would be by that time.

**Comment by lastmjs** [comment]
It's out now, this should closed :) @alexalabyev

**Comment by AlexAlabyev** [comment]
@lastmjs Yeah, it's probably should be
