### ISSUE TITLE
Problem with styling based on :host class or attribute

### ISSUE THREAD

**Issue by govis** [Polymer/polymer#4562]
### Description
Styling based on :host class or attribute doesn't seem to be working

These don't work
:host.class
:host:not(.class)
:host:not([attr]) 

This one does:
:host([attr]) 

#### Live Demo
http://jsbin.com/pedomufeka/edit?html,output

#### Expected Results
Blue should be blue, red should be red

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v2.0.0-rc.7
- webcomponents: v1.0.0-rc.10
- shadycss: v1.0.0-rc.5

**Comment by web-padawan** [comment]
This is by design. See [spec](https://www.w3.org/TR/css-scoping-1/#host-selector). Some of these used to fork for 1.x in shady mode, but they shouldn't.

**Comment by kevinpschaaf** [comment]
@govis All host compound selectors must be placed in parenthesis after the `:host`, e.g. `:host(<compound>)`.

Here's your jsBin corrected for proper syntax: http://jsbin.com/facohuy/edit?html,output

As @web-padawan noted older shadydom implementations may have accepted looser syntax, but going forward you should only keep to correct syntax per spec.  Thanks!
