### ISSUE TITLE
Polymer breaks with chrome device toolbars device simulation.

### ISSUE THREAD

**Issue by rene-lindner-isw** [Polymer/polymer#4567]
### Description
If you open an Polymer App in Chrome with the device toolbar open, the App chrashes.
Running in "Responsive" works, but when you choose an device and reload, it chrashes.

```
Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at new DomModule (dom-module.html:65)
    at dom-module.html:157
    at dom-module.html:161
```

#### Steps to Reproduce
1. `polymer init`
2. Choose `polymer-2-starter-kit`
3. `polymer serve`
4. Open chrome
5. Open device toolbar (ctrl + shift + m)
6. Choose e.g. iPhone 6
7. Open your starter kit app

#### Expected Results
No error is throw

#### Actual Results
Error is thrown

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: 2.0.0-rc.7
- webcomponents: 1.0.0-rc.11

**Comment by azakus** [comment]
This is actually an issue with `polymer serve` and/or Chrome Dev Tools, as the useragent for "iphone 6" mode is set to Safari 9, which triggers `polymer serve` to compile elements with babel, which requires an ES5 adapter library for use in browsers with native Custom Elements.

**Comment by justinfagnani** [comment]
@rene-lindner-isw: What version of the CLI do you have? Run `polymer --version`

**Comment by aomarks** [comment]
This issue should be fixed as of polymer-cli 0.18.1 (published 4/25).

**Comment by rene-lindner-isw** [comment]
Thanks for your feedback! Updated the cli, fixed the error. Though the result is not really correct, guess the es5 compiling is not finished yet?

For now i just added some custom devices without useragent.

**Comment by aomarks** [comment]
Great! Can you expand on the incorrect result you are still seeing?

**Comment by rene-lindner-isw** [comment]
Sure - e.g. https://github.com/IswPolymerElements/isw-responsive-behavior
CLI 0.18.1, cloned, bower install, polymer serve. No errors in log.

ES6: http://imgbox.com/VY87ccXV
ES5: http://imgbox.com/Fq6hHIuq
