### ISSUE TITLE
Property name "watch" breaks in Firefox

### ISSUE THREAD

**Issue by doctor-g** [Polymer/polymer#4572]
### Description
Using a property called "watch", it will be fine in Chrome, but in Firefox, an error is generated:
>TypeError: fx.push is not a function

The actual variable name there changes depending on the build---we saw something different when running via `polymer serve` vs a live build, for example, but the error is otherwise the same.

#### Live Demo

http://jsbin.com/xurogow/4/edit?html,output

#### Steps to Reproduce
1. Make a new app project with polymer-cli
2. Change `prop1` to `watch`
3. Open on Chrome to see it work, Firefox to see it fail

#### Expected Results
Property works as normal, or at least the linter could give a harsh warning.

#### Actual Results
Console shows the error described above (_x_.push is not a function)

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v1.9.1
- webcomponents: v0.7.24

**Comment by azakus** [comment]
Looks like Firefox has some obscure function called "watch" on the Object prototype: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/watch.

I'm not sure if we can work around that, but it should be worth a look.

**Comment by TimvdLippe** [comment]
It looks like Mozilla is removing this property per Firefox 58 (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/watch). Given that this is a browser-specific issue, unrelated to Polymer, and it will be fixed in the next release of Firefox, I am closing this issue.
