### ISSUE TITLE
Using dynamic function for computed annotations results in warning

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#4575]
### Description
The feature requested in #3299 and implemented in #3358 has minor issue in 2.x, it results in warning:
```
method `xyz` not defined
```

Even though it works fine eventually.

#### Live Demo
http://jsbin.com/feberifezo/1/edit?html,console,output

#### Steps to Reproduce
1. Define computed property with type `Function` and another simple property with type `String` (`Number` should work as well)
2. Use it in element's template with another element's property as argument
3. Add element to the document with another property as it's attribute

#### Expected Results
No warning

#### Actual Results
Warning:
```
method `xyz` not defined
```

### Browsers Affected
Only tested in these:
- [X] Chromium nightly
- [X] Firefox

### Versions
Polymer: 2.0-preview

**Comment by azakus** [comment]
Seems like this line should block printing that warning: https://github.com/Polymer/polymer/blob/master/lib/mixins/property-effects.html#L769

@kevinpschaaf is `dynamicFn` set later?
