### ISSUE TITLE
this.$$ doesn't work in 2.0-preview

### ISSUE THREAD

**Issue by ppeou** [Polymer/polymer#4577]
Hello,

I am following this example to create iron-collapse inside dom-repeat.
https://gist.github.com/vtellier/c2341934ccdd47d70676b3a8e696f40c

I got error stating this.$$ is null. In order to get it to work, I use this.root.querySelector to select corresponding iron-collapse. 

It is my understanding that for locating dynamically-created nodes in element's local DOM, the $$ method provides a shorthand for Polymer.dom(this.root).querySelector() - but doesn't seem to work in Polymer 2.0:

//working code to toggle iron-collapse
var collapse = this.$$ ? this.$$('iron-collapse[ident="' + id + '"]') : null;
if (collapse == null) {
   console.warn('cant use this.$$');
   collapse = this.root.querySelector('iron-collapse[ident="' + id + '"]');
}
collapse.toggle();

**Comment by azakus** [comment]
Seems to work in 2.0.0-rc.7: http://jsbin.com/wepihuy/edit?html,output

**Comment by ppeou** [comment]
would this only work in the hybrid mode? I am using "extends Polymer.Element" to create polymer element.

**Comment by web-padawan** [comment]
@ppeou yes, it is only for hybrid mode. You can implement your own base class and grab the code from [here](https://github.com/Polymer/polymer/blob/master/lib/legacy/legacy-element-mixin.html#L413).
