### ISSUE TITLE
A property's computing function should not be invoked until all dependent properties are defined

### ISSUE THREAD

**Issue by TonyBogdanov** [Polymer/polymer#4578]
### Description
It  is stated in the [v2.0 docs](https://www.polymer-project.org/2.0/docs/devguide/observers) that:

> The computing function is not invoked until **all** dependent properties are defined (!== undefined). 

In reality computing functions, just like complex observers are invoked (the first time) if **at least one** of the dependent properties is defined.

#### Live Demo
https://plnkr.co/edit/kiQvxUR2E8AmR1n5RT1C?p=preview

#### Expected vs Actual Results
When passing both `first` and `last` properties to the `<x-custom>` element, the result is as expected:

> My name is Tony Bogdanov

When neither is set, the property is not computed, which is expected.

When only `first` is set, the result is:

> My name is Tony undefined

Which according to the docs is wrong since not **all** dependent properties are defined.

Is this a Polymer bug or a docs typo?

### Browsers Affected
- [x] Chrome
- [ ] Firefox (not tested)
- [ ] Edge (not tested)
- [ ] Safari 9 (not tested)
- [ ] Safari 8 (not tested)
- [ ] IE 11 (not tested)

### Versions

- Polymer: master
- webcomponents: master

**Comment by web-padawan** [comment]
Not sure but this might be related to [observers change](https://www.polymer-project.org/2.0/docs/upgrade#update-observers).

**Comment by TonyBogdanov** [comment]
Could be, if complex observers and computed properties use the same internal mechanic, but observers **are** properly documented:

> The first call to an observer is deferred until the following criteria are met:

> The element is fully configured (default values have been assigned and data bindings propagated).
**At least one** of the dependencies is defined (that is, they don't have the value undefined).

So, no problem there.

I actually welcome the change to observers' behavior since Polymer 1, because prior it was impossible to create an "or" condition out-of-the-box, e.g. observer be run if **any** of the dependents are defined.

As of right now, "or" is the default behavior, and it's much simpler to change it to an "and" if you need to - just check if **any** of the dependents **aren't** defined and only run your code once they **all** are (check my snippet at the end).

One can do the exact same trick for computed properties to ensure the property is only computed (initially) once all of it's dependent properties are defined, but in my experience the "or" condition for computed properties is a really rare use case.

I think, there are 3 ways this can be handled:

- Change the condition for computed properties back to "and" as it were in Polymer 1.
- Leave the code as-is, but fix the docs so people won't get confused.
- Introduce some way to specify which behavior you need.

P.S. Here's a quick snippet to demonstrate how easy it actually is to turn "or" to "and". It can be used for both properties and observers.

```
class DeferTest extends Polymer.Element {
    static get is() {
        return 'defer-test';
    }

    static get properties() {
        return {
            a: {
                type: String,
                computed: '__defer("computeA", b, c)'
            },
            b: {
                type: String
            },
            c: {
                type: String
            }
        };
    }

    __defer() {
        let args = Array.prototype.slice.call(arguments);
        let call = args.shift();

        for(let dependent of args) {
            if('undefined' === typeof dependent) {
                return;
            }
        }

        return this[call].apply(this, args);
    }
}
```

**Comment by arthurevans** [comment]
Sorry, this is a doc bug—the old note slipped through when I was revising the doc. Rules for computed properties should be identical to complex observers.

**Comment by arthurevans** [comment]
This issue was moved to Polymer/docs#2068
