### ISSUE TITLE
Cannot lazy load/import app-layout-* elements

### ISSUE THREAD

**Issue by kaste** [Polymer/polymer#4580]
My current fast path app shell only uses vanilla custom elements and the new Polymer.Element thing. After the first paint (which is basically TTI) I want to lazy load 
```
   <link rel="import" href="app-layout/app-header/app-header.html">
   <link rel="import" href="app-layout/app-header-layout/app-header-layout.html">
```

which in turn loads the legacy/hybrid wrapper as well. But unfortunately this doens't work. 

From what I see the styles for `#wrapper ::slotted([slot=header])` within `app-header-layout` aren't applied. 
There might be other things as well. E.g. (if I work around this issue) the scroll position always jumps to the top.

#### Live Demo
http://jsbin.com/wavuhigece/edit?html,output

### Browsers Affected
I only checked latest Chrome
- [x] Chrome

### Versions
- Polymer: v2 RC7 master
- webcomponents: master

**Comment by azakus** [comment]
Ah yeah, `polymer-element.html` does not load `<custom-style>` or the the `@apply` shim, which are loaded by `polymer.html`.

If you include those dependencies in the index, I think this works correctly: http://jsbin.com/gipagow/edit?html,output

Unfortunately, we don't support lazy-loading `<custom-style>` or `@apply` right now, as it would require a full style recalculation for every element.
Filed as https://github.com/webcomponents/shadycss/issues/94

**Comment by kaste** [comment]
Your JSBin does not work: The first header doesn't scroll away. Both headers are just fixed at the top. I can get away with this by calling `resetLayout()` after loading. http://jsbin.com/qutaqe/edit?html,output 

Otherwise eager loading those two shims seems okay. They cost ~15kB.
