### ISSUE TITLE
Polymer.version is hardcoded to 2.0-preview and is not updated in build

### ISSUE THREAD

**Issue by alvarezguille** [Polymer/polymer#4582]
### Description
Polymer.version returns `2.0-preview` in apps using v2.0.0-rc.7
It seems to be hardcoded in [boot.html](https://github.com/Polymer/polymer/blob/fe779eaf791647659ac9564e936336102ea3c9ef/lib/utils/boot.html#L47) and not updated in `gulpfile.js` as it used to be in 1.

#### Live Demo

http://jsbin.com/duhicajive/1/edit?html,output

#### Expected Results
Actual version is returned

#### Actual Results
2.0-preview is returned 

### Versions
- Polymer: v2.0.0-rc.7

**Comment by kevinpschaaf** [comment]
Thanks, has been corrected for the `2.0.0-rc.9` and `2.0.0` releases, and we'll maintain this going forward.

**Comment by alvarezguille** [comment]
Thanks and congrats for the stable release!
