### ISSUE TITLE
dom-module doesn't support more than one link[rel=import][type=css]

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#4587]
### Description
```html
<dom-module id="my-element">
    <link rel="import" href="style-1.css" type="css">
    <link rel="import" href="style-2.css" type="css">
    <template>
        <slot></slot>
    </template>
</dom-module>
```

My use case involves Font Awesome, whose CSS file I wanted to include separately. Currently workaround is to use SCSS.

#### Expected Results
Both CSS files included.

#### Actual Results
Second CSS file is ignored.

### Browsers Affected
- [x] Chrome
- [x] Firefox

### Versions
- Polymer: 2.0-preview

**Comment by anuragpathak** [comment]
Unable to reproduce this issue. I have included two css files in one web component and both are imported properly.

Web components version: https://polygit.org/webcomponentsjs+1.0.0-rc.7/components/webcomponentsjs/webcomponents-loader.js

Polymer Version: https://polygit.org/polymer+2.0.0-rc.2/components/polymer/polymer-element.html

Plnkr link : http://plnkr.co/edit/znyjvNUAJvMlcvlvFMwH?p=preview

**Comment by nazar-pc** [comment]
@anuragpathak, thanks, I've just checked once again and found that it was my fault.
