### ISSUE TITLE
Add option to prevent single property observers from firing with undefined values

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#4590]
Given `observers: ['_pathChanged(foo.bar)']` and `element.foo = {}` the `_pathChanged` method will run. This is unfortunate given that Polymer will not call observers with undefined values if there is more than one argument.

It would probably be a breaking change to alter how this works, but an option should be added to, at the least, normalize the behavior with multi-property observers.

**Comment by sorvell** [comment]
Prototyped on Polymer 2.x in https://github.com/Polymer/polymer/tree/4590-kschaaf-args-dirtycheck

**Comment by arthurevans** [comment]
But wouldn't you want this notification if you have `element.foo = { bar: 'something'}` and then you change to `element.foo = {}`?

**Comment by arthurevans** [comment]
Moreover, this _isn't_ right for 2.x in the first place, is it? With multi-property observers, you do receive undefined values. 😕 ❓

**Comment by TimvdLippe** [comment]
Yeah I think this is working as intended, as you do want to receive the updates and you will also receive `undefined` in complex observers. @sorvell I would say we should close this issue as WAI.
