### ISSUE TITLE
Iron Icons not working on IE 11 if used custom image instead of icon

### ISSUE THREAD

**Issue by nishantgirbar** [Polymer/polymer#4591]
In one of my project i was trying to use my custom image as icon in place of icon as below

 <iron-icon title="abc" src="./app/images/log-icon.png" ></iron-icon>

above code is working fine in Chrome but not working on IE

**Comment by sorvell** [comment]
Please make sure to follow the [issue filing guidelines](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs) and file this issue in `iron-icon` [issues list](https://github.com/polymerelements/iron-icon/issues). Thanks.
