### ISSUE TITLE
Inconsistent documentation on computed property behavior

### ISSUE THREAD

**Issue by Gi60s** [Polymer/polymer#4604]
This is the documentation I'm referring to: https://www.polymer-project.org/2.0/docs/devguide/observers#define-a-computed-property

The second paragraph states:

> ...the computing function is run once at initialization if **any** dependencies are defined. After that, the function runs whenever there is an observable change to any dependency.

Five paragraphs lower in the next sub-section **Define a computed property**:

> The computing function is not invoked until **all** dependent properties are defined...

Am I misunderstanding something or is this documentation contradictory?

**Comment by arthurevans** [comment]
D'oh. You are not misunderstanding anything, I missed updating one of the references. The earlier paragraph is correct, the later one is wrong. Thanks for the report!

**Comment by Gi60s** [comment]
Glad I could help. Thanks.

**Comment by arthurevans** [comment]
This issue was moved to Polymer/docs#2137
