### ISSUE TITLE
dom-bind element does not fire dom-change event

### ISSUE THREAD

**Issue by jstnhuang** [Polymer/polymer#4605]
The `<dom-bind>` element does not fire a `dom-change` event [as described](https://www.polymer-project.org/2.0/docs/devguide/templates#dom-bind) in the Polymer 2 docs.

#### Live Demo

http://jsbin.com/royuzagano/edit?html,console,output

#### Steps to Reproduce

1. Load the above demo.
1. Press `Run with JS`
1. The console does not show "template is ready"
1. Press the "Fire event" button
1. Now the console shows "template is ready"

#### Expected Results
The console should show "template is ready" when the document is loaded (i.e., the `Run with JS` button is pressed).

#### Actual Results
"template is ready" is not shown in the console unless you manually dispatch an event by clicking on a button.

### Browsers Affected

- [x] Chrome

Tested on Chrome 58 on Ubuntu 14.04.

In Firefox, "template is ready" is shown on load, but the rest of the jsbin demo doesn't work.

### Versions
- Polymer: v2.0.0
- webcomponents: v1.0.0

**Comment by sorvell** [comment]
For Polymer 2.0, we've elected to make `dom-bind` render synchronously. This means in general, you shouldn't need to listen for the `dom-change` event and if you add an event listener via a script after the `dom-bind` you'll miss the event.

Here's a modified example showing that the event does indeed fire: http://jsbin.com/qudumoc/edit?html,console,output.

The new behavior does make working with the `dom-change` event more cumbersome, but as mentioned, this is now not really needed. 

We'll leave this issue open as at the least we need to make sure the new behavior is correctly documented and so we can consider if perhaps the event should fire asynchronously for ease of use.

**Comment by trentmwillis** [comment]
I've opened a PR to update the docs about this as I just ran into the same issue: https://github.com/Polymer/docs/pull/2216

**Comment by TimvdLippe** [comment]
@trentmwillis Thanks! This seems to be clarified now: https://www.polymer-project.org/2.0/docs/devguide/templates#dom-bind
