### ISSUE TITLE
Reapplying custom-style

### ISSUE THREAD

**Issue by govis** [Polymer/polymer#4610]
### Description
When two lazy loaded elements use the same global css variable name <code>--my-color</code> with different values defined in their respective <code>custom-style's</code> is there a way to reapply the custom-style when we switch between elements? Right now the last loaded custom-style remains in effect and calling <code>updateStyles</code> does not seem to help.

#### Live Demo
http://plnkr.co/edit/hzaKtXOHhT4bRe9V93BQ?p=preview

#### Steps to Reproduce
1. "Page One" is loaded first - it has blue background
2. Click "Next Page" to load "Page Two" - it has purple background
3. Click "Next Page" to load "Page One" again - it now has purple background too

#### Expected Results
Page One to retain blue background

#### Actual Results
Page One becomes purple

### Browsers Affected
- [x] Chrome (others not tested)
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v2.0
- webcomponents: v1.0

**Comment by arthurevans** [comment]
The `custom-style` elements happen to be in the same HTML imports as the element, but there's no other linkage between them. Once that HTML import has been loaded, it remains loaded. So this scheme is not going to work.

The easiest thing to do here would be to set `--my-color` in the element itself (only works for the pages and their descendants, so it can't affect any peers):

http://plnkr.co/edit/6QfejM2b7zs0Ivis0c4B?p=preview

**Comment by govis** [comment]
Thank you - that works for me. I can put the vars in separate dom-modules and load them into pages with style include.

It's likely that loading/switching color themes dynamically will be requested at some point, so it would be interesting to know if it's supported.
