### ISSUE TITLE
Polymer 2.0 API Upgrade CheatSheet

### ISSUE THREAD

**Issue by pkaske** [Polymer/polymer#4615]
I started a cheat sheet for reference with _before_ and _after_ examples when upgrading elements to the Polymer 2.0 api. I found this easier than searching the official docs all the time.

Maybe this is useful for somebody else, so I though I open an issue here.  
(feel free to close if this isn't the right place)

The doc is by no means complete. In fact I just copy and pasted the last 5 minutes from the official doc to get this started. PRs with "cheats" you would like to have for easy access very welcome.

**The cheat sheet is only meant for upgrading to class based elements, right now. Not hybrid.**

https://github.com/pkaske/polymer2.0-upgrade-cheatsheet

**Comment by kevinpschaaf** [comment]
@arthurevans Going to move this over to the docs tracker... maybe you can do a once-over of the content in his cheat-sheet and ensure the upgrade guide covers it?

**Comment by kevinpschaaf** [comment]
This issue was moved to Polymer/docs#2174

**Comment by kevinpschaaf** [comment]
Will also note that @notwaldorf is helpfully maintaining a Polymer 2.0 cheat-sheet on her blog here: https://meowni.ca/posts/polymer-2-cheatsheet/
