### ISSUE TITLE
Make future polymer can available with only polymer-cli

### ISSUE THREAD

**Issue by baocang** [Polymer/polymer#4618]
I have an idea about polymer's components management

polymer.json
==========
```javascript
  "version": "1.0.0",
  "directory": "components",
  "components": {
    "polymer": "Polymer/polymer#^2.0.0"
    /* "polymer": "https://github.com/Polymer/polymer#^2.0.0"*/
  }
```

cache directory
===========
Cache components into directory `.polymer/components/` or `~/.polymer/components/name-of-component/version-of-component/`

how to use
=========

Import component like `<link rel="import" href="components/polymer/polymer-element.html">`

polymer install
===========

Download and cache components into cache directory  via `polymer install`

resolutions
========
Current project specified version

polymer serve
==========
Serve for project and route dependencies from `components` to `src` or cache directory.

polymer build
==========

Merge `.polymer/components/` (or `~/.polymer/components/name-of-component/version-of-component/`) and `src/` into `build/**/components/`.

why
===
This can make future polymer available without relying on node or other package control system.

**Comment by baocang** [comment]
Such as In the future, we can make polymer designer work on iOS or android with polymer-cli.  I think Front End Engineer's will like this.

**Comment by justinfagnani** [comment]
I can't exactly parse the entire proposal here, but I don't think we want to get into the package management game, rather we want to go where the users are, which is npm.

I'm going to close this for now, as our plan of record is to add npm support.
