### ISSUE TITLE
Feature request: vend missing mixins

### ISSUE THREAD

**Issue by notwaldorf** [Polymer/polymer#4625]
In 1.0 we trained people that they could use declarative `listeners` and `hostAttributes` blocks. In 2.0 we took those away but also didn't vend a helpful mixin for them to use.
Note: I am **not** suggesting we put this in `Polymer.Element`, but rather as a standalone thing in the `mixins` folder.

@azakus @tjsavage @sorvell @kevinpschaaf

**Comment by azakus** [comment]
This should be pretty simple. All the required pieces already exist for the legacy `Polymer({})` call.

**Comment by strann** [comment]
@notwaldorf so `hostAttributes` is gone in Polymer 2? I've just spent 30min trying to get it to work after seeing it in the [2.0 api docs](https://www.polymer-project.org/2.0/docs/api/) 😢

**Comment by TimvdLippe** [comment]
@strann Please see https://github.com/Polymer/polymer/pull/4632#issuecomment-353220052 and the linked comment at https://github.com/Polymer/polymer/pull/4632#issuecomment-333881895

**Comment by strann** [comment]
@TimvdLippe thanks, so the reference to `hostAttributes` should be removed from the [api docs](https://www.polymer-project.org/2.0/docs/api/)? Not sure where that documentation lives or I'd drop an issue there (didn't find a reference to it here, though I did find this 😄 )
https://github.com/Polymer/polymer/blob/3a0c3967b770d578590ee16088d062fc1b54e917/README.md#L366

**Comment by TimvdLippe** [comment]
@strann This issue was to ship a mixin for pure Polymer 2 (class-based) syntax. The docs mention the support for the legacy Polymer 1 syntax. The implementation of the legacy compatibility layer is at https://github.com/Polymer/polymer/blob/ee1d71f5f896ee57a0ee6d1f377ae6caa76e556b/lib/legacy/class.html#L218-L225

**Comment by TimvdLippe** [comment]
Closing this per https://github.com/Polymer/polymer/pull/4632#issuecomment-353220052 and https://github.com/Polymer/polymer/pull/4632#issuecomment-333881895
