### ISSUE TITLE
Bower replacement

### ISSUE THREAD

**Issue by jogibear9988** [Polymer/polymer#4627]
As bower does not recoment to be used for new projects, what is the planed tool to use for a new polymer project? example for this?

**Comment by bastiion** [comment]
i'd also like to see yarn support in the first place, which would me to have the recent versions of polymer and elements in npm. If you develop each component of an application in a separate component project, which make perfectly sense in a modular development, you get >= 20 MB of dependencies minimum for each. This wouldn't be the case with a global caching package manager.

**Comment by JoshuaVSherman** [comment]
Me too

**Comment by TimvdLippe** [comment]
You can follow #326 for more updates. The Polymer team is actively researching options atm: https://github.com/Polymer/polymer/issues/326#issuecomment-303148878

**Comment by kevinpschaaf** [comment]
Thanks @TimvdLippe. Closing in favor of #326.
