### ISSUE TITLE
CSS @Import directive does not work in Polymer 2 Elements in Chrome and bleeds Firefox

### ISSUE THREAD

**Issue by gkjohnson** [Polymer/polymer#4629]
### Description
The css `@import` directive does not work properly in shadow dom templates for Polymer 2 Elements, but works as expected when using a native HTMLElement inherited component

The details of the problem are documented in the `plunker` document down below. Basically, it seems that `@import` directives *only* work when there is no semicolon included after it

If you look at at the same demo in firefox you can see the styles imported in the polymer elements are affecting the style of the sibling element with the `example` class, as well

If needed I can break these up into two issues if needed

#### Live Demo
http://plnkr.co/edit/PCx2LHplKlPJ1LIV0EA5?p=preview

#### Steps to Reproduce
Chrome bug repro
1. Create an external style called `external.css` to be used in an element
2. Add a style tag inside the template with exactly the content of `@import "external.css"` (no semicolon)
3. Imported styles function as expected
4. Add a semicolon so the style tag content is `@import "external.css;"`
5. Imported styles do not show up

Firefox bleed repro
1. create an external style called `external.css` to be used in an element that styles a `.example` element
2. Add css import in the Polymer element to import the external style sheet
3. Add a sibling element next to the polymer element instance with the class `example`
4. The styles from the external sheet, despite being imported into the polymer element, are applied to the sibling element as well

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
Polymer 2.x

**Comment by web-padawan** [comment]
Right now only styles in `<style>` tags are supported (and also `<link rel="import">` which is likely to be deprecated). In the Shadow DOM spec, `<link rel="stylesheet">` is described but might be not so easy to polyfill.

**Comment by gkjohnson** [comment]
It looks like this is the relevant issue:
https://github.com/PolymerElements/iron-flex-layout/issues/88#issuecomment-203692575

It makes sense. At the risk of just recreating the conversation from that thread, is there an official stance on how to import external style sheets _without_ wrapping the css source in a dom-module to import? The `<link rel="import" type="css" href="...">` is marked as "deprecated", but there's no reasonable solution for it now except for wrapping existing style sheets (often built for other libraries) in a dom-module, which feels a little gross.

The following discussions, though, basically say that the `type="css"` approach is expected to continue to be supported:
https://github.com/Polymer/polymer/issues/3837
https://github.com/Polymer/polymer/pull/4344

So the mixed signals are a little confusing. Can we expect that by the time it's _actually_ deprecated there will be a suitable replacement for it's functionality that does not require modifying style source to include it in a style-module? Or is it actually ever going to be deprecated?

**Comment by kevinpschaaf** [comment]
@gkjohnson You can assume you can safely use `<link rel="import" type="css" href="...">` for the duration of Polymer 2.0 (i.e., we have no plans to remove it prior to the next major breaking change of the library).  As for the future, as we explore native ES module support in the browser, the solution may need to change along with that.

re: *Chrome bug repro*, this appears to be a `shadycss` `apply-shim` issue; [this updated plunkr](http://plnkr.co/edit/8S85VShD4KGldF7h4phW?p=preview) that does not load the apply shim shows the correct rendering for the @import with the semicolon on Chrome. I've [opened a bug](https://github.com/webcomponents/shadycss/issues/101) on `shadycss` to track this.

re: *Firefox bleed repro*, as noted the `shadycss` shim does not currently support `@import` syntax.  I've added a [note to the `shadycss` documentation](https://github.com/webcomponents/shadycss/commit/05a16c279897fa6d520169a0fad3975fa75ea690#diff-04c6e90faac2675aa89e2176d2eec7d8) to this effect: 

> External stylesheets loaded via `<link rel="stylesheet">` within a shadow root or
> `@import` syntax inside a shadow root's stylesheet are not currently shimmed by
> the polyfill.  This is mainly due to the fact that shimming them would require
> a fetch of the stylesheet text that is async cannot be easily coordinated with
> the upgrade timing of custom elements using them, making it impossible to avoid
> "flash of unstyled content" when running on polyfill.

**Comment by Nitin-Prabhakar** [comment]
@kevinpschaaf 
> You can assume you can safely use <link rel="import" type="css" href="..."> for the duration of Polymer 2.0 (i.e., we have no plans to remove it prior to the next major breaking change of the library). As for the future, as we explore native ES module support in the browser, the solution may need to change along with that.
It seems chrome 59.x with native support for components, ignores an import with rel `import` and `type` css
could not reproduce the issue on other browsers, with polyfills in place. 
Using **polymer 2.0** 

![polymer-issue-link-ignored](https://user-images.githubusercontent.com/15086525/27050923-ecb70470-4fd1-11e7-97a4-93239a8dbe27.png)

**Comment by kevinpschaaf** [comment]
It sounds like you're putting the `<link rel="import" type="css">` inside your `<template>`.  It needs to be _outside_ the template but inside the `<dom-module>` for the element, since we rely on it loading to be able to extract the css text for polyfilling.  See docs here: https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom#external-stylesheets

**Comment by Nitin-Prabhakar** [comment]
yep yep :) . It is outside the shadow tree and inside the dom module as advocated on polymer-project docs.
```
<dom-module id="shared-styler">
    <link rel="import" type="css" href="p_s_m_1.css">
    <template id="shared-style-mod-one">
<!-- content-->
    </template>
</dom-module>
```
This is in chrome 59 alone with native web component support.
The import works fine with **forced** platform polyfills

**Comment by yebrahim** [comment]
+1. A clarification on Polymer's future plan in this regard would be very appreciated.

**Comment by andrew-vandenbrink** [comment]
Create style module and copy paste the whole css content into that module.
It works like charm...
