### ISSUE TITLE
Better error messages for hybrid element migration

### ISSUE THREAD

**Issue by BorntraegerMarc** [Polymer/polymer#4634]
When migration a polymer element from 1.X to 2.X in hybrid mode there is not really any error messages fired, if something is missing. For example:

- Take any element written in Polymer 1.X and upgrade the dependencies to 2.X (without changing the rest of the code)
- If the 1.X element has been using `Behaviors ` or `<content>` there is just no error message anywhere

So if I try to load the element in the browser I just stare at a blank screen. Without any message. Polymer analyzer also does not give me any insight.

I would expect that at least viewing it in the browser would give me some kind of hint, what went wrong.

**Comment by butterandfly** [comment]
Have you try the `polymer lint`? Don't forget to add this:
```
"lint": {
    "rules": ["polymer-2"]
  }
```

**Comment by kevinpschaaf** [comment]
There's still an [open issue on `polymer-linter`](https://github.com/Polymer/polymer-linter/issues/12) to flush out the 2.0 Ruleset, which would include things like this.  This is our preferred strategy to deal with error reporting-- not in the client-side code, but rather vla the tooling.  As such, closing in lieu of https://github.com/Polymer/polymer-linter/issues/12.
