### ISSUE TITLE
Upgrading to Polymer 2, now no elements are showing on page despite being loaded.

### ISSUE THREAD

**Issue by esd100** [Polymer/polymer#4640]
My website using Polymer 1 was nearly complete and working wonderfully.

Thought I would upgrade to Polymer 2 and after installing Polymer 2, deleting bower and upgrading, now none of the elements are displaying. Some of the elements are still working, but none of the elements are being displayed on the screen.

I'm at my wits end and have been trying to figure out what is wrong for >6 hours. I've checked everything including Bower, Manifest, index in my project files, and elements, sources, console, network in the developer console.

The network shows the files are retrieved and loaded. The source files are there. The console shows no clear errors. The project files seem to be correct. 

I even loaded a polymer paper-dialog demo file from my served up polymer project and it didn't work.

But when I download the PSK2 and served it up, it worked fine. So there is something wrong with my project but I can't find what's wrong!

Please help! I don't know what is causing the problem. I will share my repo with you.

**Comment by jsilvermist** [comment]
What happens if you run `polymer lint` on your project?

**Comment by esd100** [comment]
@jsilvermist Nothing major. It actually says there is 1 error, but doesn't actually list what it is.

**Comment by esd100** [comment]
I have no idea why the elements aren't displaying but are present and functional. It's driving me bonkers.

**Comment by jsilvermist** [comment]
Do you have any link to check out?

**Comment by esd100** [comment]
Not sure what you mean by link to check out. I'm really an amateur. I can share the repo with you.

**Comment by jsilvermist** [comment]
You can't pull in elements for 2.0 with bower like that yet, all the grouped *-elements packages still resolve to 1.0 elements, you need to pull in each element you use separately at `^2.0.0` for polymer 2.0 compatible elements.

**Comment by esd100** [comment]
really? what a drag! okay, well, I'll get to work on that. Hopefully that fixes it.

But shouldn't polymer 2 still work with polymer 1 elements? I thought they were trying to "ease" the transition.

**Comment by jsilvermist** [comment]
Yea some of them have already been ported to use the newest version, but no new releases have been tagged yet unfortunately.

**Comment by esd100** [comment]
ahh...maybe I should just not even try to spend a lot of time on this polymer 2 thing then.

**Comment by esd100** [comment]
Ah, So wait, how does that translate to compatibility.

2.0 elements can work with polymer 1
1.0 elements cannot work with polymer 2

Is that right?

**Comment by jsilvermist** [comment]
Well there's the Polymer 1 element's you're used to, new Polymer 2 elements using the es6 `class` syntax, and then hybrid elements, which use the new changes to the html and dom-module like slot instead of content, and a few other things, but still use the legacy polymer 1 style `Polymer({...})` call.

You can find more info here: https://www.polymer-project.org/2.0/docs/devguide/hybrid-elements

**Comment by esd100** [comment]
So, I guess I can't use the platinum-https-redirect anymore in the polymer 2 branch because they haven't touched that in ages (Mar 16, 2016 was the last release)

**Comment by esd100** [comment]
Yeah, I've been meaning to read that document for awhile. I just haven't been able to justify taking the time to work through all this crud.

**Comment by jsilvermist** [comment]
Looking at platinum-https-redirect (see below link) it doesn't seem like it has anything that would cause it to not work on Polymer 2, since it's already basically a hybrid element.

https://github.com/PolymerElements/platinum-https-redirect/blob/master/platinum-https-redirect.html

**Comment by esd100** [comment]
oh, cool. Yeah, I guess you have to go through and check each one to make sure that it fits the bill

**Comment by esd100** [comment]
There's probably no hope for the google-chart element though. I seriously doubt that one would pass muster.

**Comment by esd100** [comment]
Fudge! Why is paper-menu being neglected! Have to redesign the whole page now!

**Comment by jsilvermist** [comment]
Just use [paper-listbox](https://www.webcomponents.org/element/polymerelements/paper-listbox), it's a suitable replacement in most cases.

**Comment by esd100** [comment]
Well, apparently, it's not so simple.  Especially if you have paper-submenu.

https://github.com/PolymerElements/paper-menu/issues/110
https://github.com/PolymerElements/paper-menu/pull/113

**Comment by esd100** [comment]
Well, that helped to put some elements on the page, but the site formatting is now all haywire

**Comment by esd100** [comment]
Apparently neon-animation is now broken and worst of all deprecated too! Can someone explain to me how getting rid of behaviors was thought to be a good idea?

I remember watching the original videos on Polymer and it was advertised as being a platform that would eliminate boilerplate and help amateurs, who just know basic HTML to create websites.

It seems that with the latest generation of Polymer, while some areas have improved, many areas have regressed if measured by the original philosophy of the project.(https://youtu.be/VMVj_jR75vE?t=14m36s and https://youtu.be/DH1vTVkqCDQ?t=12m31s).

Now it seems to build a website, even with Polymer, just ends up being back the way it used to be, end up requiring a lot of intricate knowledge and writing a lot of complex code (heavy lifting) to accomplish things that use to be easy in Polymer 1. For example, I have no idea how to animate stuff in css or web animations. I don't want to have to learn a whole new technology to get elements that have that behavior built in, aka., neon-animation. This is a major step backward.

**Comment by kevinpschaaf** [comment]
@esd100 Sorry to hear your upgrade experience has not met expectations.  We've put a lot of work in to make this breaking change as smooth as possible, insomuch as it's still a breaking change.

To summarize, updating to Polymer 2 does require that all element dependencies be updated to Polymer 2.0.

It sounds like you've hit a few dependencies that haven't been ported to Polymer 2.0 yet.  We're maintaining a list of hybrid-supported elements here: https://www.polymer-project.org/2.0/docs/about_20#elements.  I'd recommend cross-referencing your dependencies against this list and eliminating usage of elements not on this list, or else fork the element and do the minimal work to adhere to the Polymer 2.0 [hybrid rules](https://www.polymer-project.org/2.0/docs/devguide/hybrid-elements) (which are typically very minimal) -- and PR's for this kind of work back to the elements are always appreciated.

**Comment by esd100** [comment]
It's just sad that something that once was once easy to use is now difficult to use. It doesn't seem like progress to me.
