### ISSUE TITLE
Firefox doesn't load script in template

### ISSUE THREAD

**Issue by JanMiksovsky** [Polymer/polymer#465]
See http://jsbin.com/huhis/1/edit. This logs the string "loaded" to the console in Chrome, Canary, and Safari — but not Firefox. (Separate bug: This displays "loaded" *twice* in Safari.

Background: I came across this case in trying to use a defer attribute on a script required by a analytics beacon element that would only be instantiated once per page. I wanted:

* The beacon element to load its own script (rather than requiring the outer page to load the script separately)
* The analytics script to be deferred to avoid delaying rendering of the page
* Some work to be done after the deferred script eventually loaded.

I couldn't work out how to sink an event handler on the script element's load event if the script tag were outside the template. I tried putting the script tag within the template, and that at least let me sink load with `on-load="{{loadedHandler}}"`. This worked everywhere in Firefox, which I isolated to the jsbin above.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

**Comment by halfstrik** [comment]
Still <script> does not get executed if placed inside any custom element (in my case, in <paper-material>). But works in Chromium.
Polymer versions tried: 1.1.3 and latest 1.2.1
