### ISSUE TITLE
How to use an external js with Polymer

### ISSUE THREAD

**Issue by Fratso** [Polymer/polymer#4653]
Hi,

I'm a beginner with Polymer,

I try to add an external library (Stimulsoft - Reports.JS) to my Polymer project.

But when I add the following code in my component : 
`<script src="./scripts/stimulsoft.reports.js"></script>`

I got a DOM Exception from Polymer like this : 
![error](https://cloud.githubusercontent.com/assets/20778296/26679609/31bb2c2c-46d6-11e7-86d9-6767e45eba43.PNG)

I do not understand the source of the problem. Is it possible to use an external js with Polymer ?

**Comment by TimvdLippe** [comment]
Could you post your full component? Seems like a bad positioning of the script tag. Also: it is better to include this script tag in a single `.html` file and then import this `.html` file using the HTML import. That way the import gets deduplicated, preventing you from loading the script twice

**Comment by Fratso** [comment]
Here is my component (1 html file) :
`<link rel="import" href="../../bower_components/polymer/polymer.html">
<link rel="import" href="../../bower_components/app-storage/app-localstorage/app-localstorage-document.html">




<link rel="stylesheet" href="./css/stimulsoft.viewer.office2013.whiteblue.css">


<link rel="stylesheet" href="./css/stimulsoft.designer.office2013.whiteblue.css">





<script src="./scripts/stimulsoft.reports.js"></script>








<dom-module id="sol-report">
    <template>
        <style include="shared-styles">

        </style>

        <div id="htmlContainer" style="font-weight:bold; border:solid 1px red; margin:20px; text-align:center; padding:100px;"></div>
    </template>

    <script>
        //-------------
        // Polymer
        //-------------
        Polymer({
            is: 'sol-report',

            properties : {
                /** Indiquer ici les propriétés Public et Privées dont aura besoin le rapport (URL du mrt, URL des données )*/
                _config: {
                    type: Object
                }
            },

            /**
             * Est
             */
            ready: function(){
                /*Get the configuration*/
                this._config = new Polymer.IronMetaQuery({key: 'config'}).value;
            },

            /**
             * Une fonction custom
             * @param {String} custom_param
             * @returns {String}
             */
            custom_func : function(custom_param){
              console.log('Custom function called !')
            }
        });
    </script>
</dom-module>
`

**Comment by Fratso** [comment]
And here is the script I try to add (I do not know if it could help) : 
[stimulsoft.reports.zip](https://github.com/Polymer/polymer/files/1045158/stimulsoft.reports.zip)

**Comment by jogibear9988** [comment]
I've already had problems with stimulsoft reports in polymer. I've switched to use them in an iframe

**Comment by Fratso** [comment]
Finally, after many search I found that it was the web component **paper-time-picker** use in the bundle project which throw this DOMException when I try to import stimulsoft.reports.js file. But it is possible to use Reports.JS despite this DOMException.
