### ISSUE TITLE
Iterating over dom-repeat stamped children

### ISSUE THREAD

**Issue by govis** [Polymer/polymer#4654]
### Description
We have been relying on <code>connectedCallback</code> to keep track of elements stamped by <code>dom-repeat</code> by adding them to an array maintained in a parent element somewhere up the dom tree.

Now that <code>dom-repeat</code> is smarter and can reuse instances <code>connectedCallback</code> doesn't seem to be firing consistently (see jsbin - bug?).

Given that it's a common use case - why don't we have a standard way to access children currently stamped by the <code>dom-repeat</code> - how about <code>elementForItem</code> method?

#### Live Demo
http://jsbin.com/zigipocire/edit?html,console,output

#### Steps to Reproduce
1. Run the sample, observe 3x"list-item connected" in console
2. Click "Click once"
3. No "list-item connected" are logged for "item 4" and "item 5"

#### Expected Results
5x"list-item connected" in console

#### Actual Results
3x"list-item connected" in console

### Browsers Affected
- [x] Chrome (other not tested)
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v2.x
- webcomponents: v1.x

**Comment by jogibear9988** [comment]
related: https://github.com/PolymerElements/iron-list/pull/427

**Comment by sorvell** [comment]
Would you mind providing a bit more info about why you need to keep track of the repeated children? That will help us understand the use case here.

The `restamp` option [that will be added](https://github.com/Polymer/polymer/pull/4363) to dom-repeat is one way to ensure that new elements are always created and this would also ensure the `connectedCallback`'s run.

We certainly could add an api to get the stamped children as this data is currently tracked privately, but again, we'd like to understand why this is important first. Thanks.

**Comment by govis** [comment]
Thank you for feedback. I have been eyeing the <code>restamp</code> feature of <code>dom-repeat</code> for some time and it's definitely something that I could use when it becomes available.

I have two main use cases for accessing the stamped children:
One is validation - element that acts as a validation context needs to call <code>validate</code> method on its children that are stamped with the dom-repeat (data driven multi-page form that validates user input upon proceeding).

Another is setting properties on list or tree-view items stamped with dom-repeat. Appearance properties like <code>selected</code> or <code>expanded</code> may not belong in the underlying <code>data item</code> due to separation of concerns and need to be set on the dom element directly. In cases when it's not direct result of a user interaction I need to resolve the dom element from the underlying data item. Currently I'm maintaining my own map for that. Thanks.

**Comment by TimvdLippe** [comment]
#4363 has been merged and is scheduled to be published in the next release. Could you confirm your issue is resolved using `restamp`?

**Comment by govis** [comment]
Great, thank you for finally merging this - I'll give it a try when I'm back next week.

**Comment by govis** [comment]
I tested the new <code>restamp</code> feature and it does solve my issue. Thank you for finally merging it.

**Comment by njbartlett** [comment]
Since the restamp feature in #4363 was reverted, can this issue be reopened?

**Comment by TimvdLippe** [comment]
We are now tracking all issues related to `dom-repeat`'s `restamp` in #1713, so please subscribe to that issue.
