### ISSUE TITLE
update mixins within media query

### ISSUE THREAD

**Issue by jay8t6** [Polymer/polymer#4655]
why does this not work?

```
:host {
  --some-mixin-height: 100px;
}

@media screen and (min-width: 320px) and (max-width: 767px) {
  :host {
    --some-mixin-height: 50px;
  }
}
```

**Comment by mrancys** [comment]
it's an issue more about on GH and youtube.

1. https://www.youtube.com/watch?v=_VqeFubvNKw&list=PLNYkxOF6rcIDdS7HWIC_BYRunV6MHs5xo&index=30

2. https://github.com/Polymer/polymer/issues/2149

**Comment by sorvell** [comment]
When native css custom properties are used (*the default* in Polymer 2.x and optional in Polymer 1.x), this should work out of the box in all browsers that support css custom properties (every supported browser except Edge 14 and IE 11).

For these browsers, custom properties are shimmed and do not automatically respond to media query changes. You can add code to automate this as is shown in this jsbin: http://jsbin.com/hepuvol/edit?html,output (resize the rendered window and the border should change height).

There is also [an issue in ShadyCSS](https://github.com/webcomponents/shadycss/issues/103) preventing non-trivial media queries from matching. Hopefully we'll get that fixed quickly.

**Comment by TimvdLippe** [comment]
Closing this in favor of #2149.
