### ISSUE TITLE
Polymer dom-repeat prevent reusing nodes

### ISSUE THREAD

**Issue by napa3um** [Polymer/polymer#4656]
https://stackoverflow.com/questions/37965476/polymer-dom-repeat-prevent-reusing-nodes

Same problem with Polymer 2.x

**Comment by web-padawan** [comment]
Should be fixed by #4363

**Comment by napa3um** [comment]
What for then the additional mechanism for mutation of arrays (this.splice / this.notifySplice), when items key mechanism (as I understood, analogue track-by from Angular)?

**Comment by azakus** [comment]
@napa3um Sorry, I don't understand what you're asking for here. The `restamp` mode in #4363 will indeed solve your issue as @web-padawan suggests, because dom nodes will not be reused.

**Comment by napa3um** [comment]
Restamp will solve, but this.splice/this.notifySplice not worked.
