### ISSUE TITLE
can't use iron-icons#^2.0.0 and polymer#2.0.1 in the same project.

### ISSUE THREAD

**Issue by vdegenne** [Polymer/polymer#4657]
I want to use polymer#2.0.1 with the ES2015 class definition syntax. But when I upgrade my project's elements so they can work with the last version of Polymer, and try to use some icons (iron-icons) nothing is showing up.
I tried to load the demo to be sure i wasn't missing something, but the iron-icons demo is not showing anything as well.

I have to downgrade my polymer to version #1.9.1 and the icons appears again. But then I can't use the ES2015 Polymer.Element class anymore.

**Comment by moderndeveloperllc** [comment]
@vdegenne When you use 2.0.1, are there errors in the browser console that you can paste here?

**Comment by vdegenne** [comment]
@moderndeveloperllc i cleaned my bower.json, and install one element by one element and now it works. I guess one dependency was messing the build.
