### ISSUE TITLE
Update to latest version of web-component-tester

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/polymer#4662]
### Description
`web-component-tester` has released version 6.0.0. The dev dependencies of Polymer still use the latest pre-release, which can thus be bumped to the latest stable version

#### Live Demo

http://jsbin.com/luhaxab/1/edit

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: vX.X.X
- webcomponents: vX.X.X

**Comment by azakus** [comment]
Yep, just have to followthrough on #4600
