### ISSUE TITLE
app-scroll-position doesn’t exist

### ISSUE THREAD

**Issue by hguiney** [Polymer/polymer#4664]
The 2.0 docs [state](https://www.polymer-project.org/2.0/toolbox/app-layout#document-scroller-and-element-scrollers):

> **Manage multiple scrolling views.** If you're using something like `<iron-pages>` to switch views, you can use [`<app-scroll-position>`](https://www.webcomponents.org/element/PolymerElements/app-layout/app-scroll-position) to track scroll position for each of the views. See the API docs for sample usage. `<app-scroll-position>` was renamed in release 2.0 (replacing `<app-scrollpos-control>`).

However, the link on `<app-scroll-position>` turns up a [blank page](https://www.webcomponents.org/element/PolymerElements/app-layout/app-scroll-position). Looks like `<app-scroll-position>` has been [removed](https://github.com/PolymerElements/app-layout/pull/417).

The only [suggested alternative](https://github.com/PolymerElements/app-layout/tree/2.0-preview#changes-in-app-layout-20) is `document.rootScroller`, but that is just a [proposal](https://github.com/bokand/NonDocumentRootScroller) right now and [hasn’t landed in any browsers](https://www.chromestatus.com/feature/4533350404456448#consensus).

**Comment by frankiefu** [comment]
Move to https://github.com/Polymer/docs/issues/2189
