### ISSUE TITLE
so where's wrong?

### ISSUE THREAD

**Issue by yanlee26** [Polymer/polymer#4665]
`
$ npm install -g polymer-cli
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path but we hope you'll help us figure out one.
npm WARN deprecated @types/assert@0.0.29: See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12826
npm ERR! exited with error code: 128

`

**Comment by baocang** [comment]
Is the issue same as this [Polymer/polymer-cli#784](https://github.com/Polymer/polymer-cli/issues/784)?

**Comment by yanlee26** [comment]
yeah,but there's no good solutions yet,waiting

**Comment by azakus** [comment]
@justinfagnani seems like an polymer-cli issue, can you port this over there?

**Comment by justinfagnani** [comment]
This isn't the same as Polymer/polymer-cli#784, which looked like some git/npm/filesystem permissions error. 

This is just deprecation warnings when installing Bower. We know. See #326

**Comment by a1626** [comment]
Any solution/workaround for this yet?

**Comment by TimvdLippe** [comment]
Closing this as I can not reproduce this. Please include full reproduction steps if you are still facing this issue.
