### ISSUE TITLE
Support using coffeescript to define custom elements

### ISSUE THREAD

**Issue by jyasskin** [Polymer/polymer#467]
It's not obvious how to wire up `grunt` and `vulcanize` to support writing custom elements like

```html
<polymer-element name="my-elem">
  <template>...</template>
  <script type="text/coffeescript">
    Polymer 'my-elem',
      var: 'default'
      ready: ->
        # Coffeescript code
      attached: ->
        # More code
  </script>
</polymer-element>
```

so that the coffeescript gets extracted and compiled to js during the build process. If it's already possible, this is a request to document it; if not, this is a request to make `vulcanize` support it.

**Comment by alex88** [comment]
Any update?

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
