### ISSUE TITLE
composedPath() broken for `tap` event on touch devices

### ISSUE THREAD

**Issue by Saulis** [Polymer/polymer#4670]
### Description

`event.composedPath()` is missing the composed elements within shadow root on `tap` event on touch devices. Native events and atleast `down` and `up` gesture events work as expected.

Looks to me like the problem is using a [`Touch` object from `e.changesTouches[0]` as a `sourceEvent`](https://github.com/Polymer/polymer/blob/v2.0.0/lib/utils/gestures.html#L833) instead of the original composed event.

#### Live Demo
http://jsbin.com/pagitax/edit?output

#### Steps to Reproduce
1. Tap on "Tap Me!"
2. See printed out `composedPath()` in console

#### Expected Results
Path should start with: `["DIV", "#document-fragment", "MY-ELEMENT", "BODY", "HTML"...]`

#### Actual Results
Path actually starts with: `["MY-ELEMENT", "BODY", "HTML"...]`

### Verified with
- [x] Chrome 58 emulating Nexus 5X
- [x] Chrome 58 emulating iPhone 6
- [x] iOS Simulator running iPad with iOS 10.3

### Versions
- Polymer: v2.0.x
- webcomponents: v1.0.x

**Comment by azakus** [comment]
Yep, you're right. The right fix is probably to use the original TouchEvent in `findOriginalTarget` to get the proper `composedPath`
