### ISSUE TITLE
web combine stack

### ISSUE THREAD

**Issue by nomads6** [Polymer/polymer#4677]
#### Live Demo

http://jsbin.com/luhaxab/1/edit

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: vX.X.X
- webcomponents: vX.X.X

**Comment by sorvell** [comment]
Please file the [guidelines](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs) when filing an issue.
