### ISSUE TITLE
this.shadowRoot Returns null in Mixin Class’s connectedCallback

### ISSUE THREAD

**Issue by hguiney** [Polymer/polymer#4678]
### Description
Attempting to do a basic mixin with an inherited `connectedCallback`, like so:

```html
<template id="template">
  <div id="shadow-element">Shadow Element</div>
</template>
<!-- … -->
<custom-element></custom-element>
```
```js
window.Singleton = window.Singleton || {};

Singleton.Mixin = ( superclass ) => class extends superclass {
  connectedCallback() {
    const $shadowElement = this.shadowRoot.querySelector( '#shadow-element' );
    console.log( '$shadowElement.textContent', $shadowElement.textContent );
  }
}

// Works when mixing into HTMLElement, but not Polymer.Element:
class CustomElement extends Singleton.Mixin( Polymer.Element ) {
  connectedCallback() {
    super.connectedCallback();
  }
}
```

#### Live Demo
**Test:** [Polymer 2.0](http://jsbin.com/wexoroxami/edit?html,console,output) (doesn’t work)
**Control:** [Vanilla Custom Elements 1.0](http://jsbin.com/derahefimu/edit?html,js,console,output) (works)

#### Steps to Reproduce
1. Define a mixin class _mixin_ with a `connectedCallback` method _superConnected_.
2. Inside _superConnected_, presume that an extending element will have `<div id="shadow-element">Shadow Element</div>` in its shadow tree. Attempt to access this using `this.shadowRoot.querySelector('#shadow-element')`. Log the shadow element’s `textContent` to the console.
3. Define a custom element _customElement_ that extends `Polymer.Element` (or `HTMLElement` in the control case) together with _mixin_.
4. Inside _customElement_’s `template`, create a shadow node `<div id="shadow-element">Shadow Element</div>`.
5. Define _customElement_’s `connectedCallback` to call `super.connectedCallback()`, referencing _superConnected_.

#### Expected Results
In both the test and control case, the console displays the shadow tree `div`.

##### Test
> TypeError: Cannot read property 'querySelector' of null

##### Control
Displays the shadow tree `div`.

### Browsers Affected
macOS Sierra 10.12.5 64-bit:
- [x] Chrome 58.0.3029.110
- [x] Firefox 53.0.3 (Control case also fails due to lack of native Custom Elements v1 support)
- [ ] Edge (Didn’t test)
- [x] Safari 0.1.1 (12603.2.4, r217930) (WebKit Nightly)
- [ ] IE 11 (Didn’t test)

### Versions

- Polymer: v2.0.1
- webcomponents: v1.0.1

**Comment by sorvell** [comment]
A `Polymer.Element`'s `shadowRoot` is created in `connectedCallback` so you can only access it after calling `super.connectedCallback`. For some background on why this is the case see https://github.com/Polymer/polymer/issues/4673#issuecomment-307467946.
