### ISSUE TITLE
css var(--prop1, --fallback1, fallback2) multiple fallbacks results in invalid style

### ISSUE THREAD

**Issue by n1ywb** [Polymer/polymer#4681]
### Description

According to https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables I should be able to specify multiple fallback arguments in var

```  background-color: var(--my-var, --my-background, pink); /* pink if my-var and --my-background are not defined */```

however when I actually try this the style rule generated is FUBAR

https://codepen.io/anon/pen/MoKXRO

Writing `background-color: var(--var-1, --var-2, pink);` results in an invalid style `background-color: --var-2, pink;`

this works fwiw `background-color: var(--var-1, var(--var-2, pink));`

#### Live Demo

https://codepen.io/anon/pen/MoKXRO

#### Steps to Reproduce

use var() with multiple fallbacks

#### Expected Results

valid style rules

#### Actual Results

invalid style rules

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v1.9.1
- webcomponents: vX.X.X

**Comment by sorvell** [comment]
I believe the MDN article is incorrect here (rare but it happens). The nested `var` syntax is required and works as you noted.

Consider this raw example: http://jsbin.com/hamasokanu/1/edit?html,output

**Comment by n1ywb** [comment]
you are correct

the spec says

> The syntax of the fallback, like that of custom properties, allows commas. For example, `var(--foo, red, blue)` defines a fallback of `"red, blue"`; that is, anything between the first comma and the end of the function is considered a fallback value.
