### ISSUE TITLE
On touch screens on-tap functions will still fire on disabled buttons

### ISSUE THREAD

**Issue by rosemariesadler** [Polymer/polymer#4685]
### Description
On touch screens on-tap functions will still fire on disabled buttons

#### Live Demo
http://jsbin.com/yeloki/edit

#### Steps to Reproduce
1. Create `my-element`which has a button in it
2. Give the button an on-tap property and set the button disabled property
3. Put Chrome in responsive mode (or use an actual touch screen)
4. Tap the button

#### Expected Results
Nothing happens

#### Actual Results
The tap function will fire

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge (Unknown)
- [ ] Safari 9 (Unknown)
- [ ] Safari 8 (Unknown)
- [ ] IE 11 (Unknown)

### Versions
- Polymer: v1.9.1
- webcomponents: v0.7.23

**Comment by a1626** [comment]
I don't know i've built cordova apps using `v1.7.0` and have not faced this issue.

But here are some simple workarounds for you to use:

- Add a simple css
   
      button[disabled] {
        pointer-events: none;
      }

- Change `on-tap` to `on-click`

FYI, in your bin you are using Polymer `2.x` instead of `1.9.1` as mentioned.

**Comment by azakus** [comment]
This should be rather easy to fix by checking the `disabled` property of the element we are about to dispatch the `tap` to.
