### ISSUE TITLE
Changes to reflectToAttribute property values not working in Safari

### ISSUE THREAD

**Issue by samiheikki** [Polymer/polymer#4695]
### Description

When adding a property to an element and setting `reflectToAttribute: true`, CSS selectors for that property will work only for the initial value (in Safari). Once the value of the property changes, the corresponding CSS rules are not updated any more. 

#### Live Demo

http://plnkr.co/edit/7kJHee?p=preview

#### Steps to Reproduce
1. Create an element
2. Add a property with `reflectToAttribute: true`
3. Add CSS rules for that attribute
4. Change the value of the property

#### Expected Results
If you are looking at the element using Safari Developer tools, you can see that the actual attribute is shown in the element, but the corresponding CSS rules are not working with the updated value. In the Plunker demo it should flick the span from `display: none` to `inline-block` between every second. Works fine in Chrome and FF, but not in Safari (Version 10.1.1 (12603.2.4))

### Browsers Affected

- [X] Safari 10

### Versions

- Polymer: v2.0.1
- webcomponents: 1.0.0-rc.5

**Comment by Saulis** [comment]
I think the issue is with Safari: https://bugs.webkit.org/show_bug.cgi?id=170762

**Comment by samiheikki** [comment]
Yes, thank you Sauli. Issue seems to be fixed in Safari 11 Technology preview. Went with this workaround for now:

```
// Safari has an issue with repainting shadow root element styles when a host attribute changes.
// Need this workaround (toggle any inline css property on and off) until the issue gets fixed.
// Issue is fixed in Safari 11 Tech Preview version.
if (this._isSafari && this.root) {
  this.root.querySelectorAll('*').forEach(function(el) {
    el.style['-webkit-backface-visibility'] = 'visible';
    el.style['-webkit-backface-visibility'] = '';
  );
}
```
