### ISSUE TITLE
Safari not updating CSS correctly

### ISSUE THREAD

**Issue by loekup** [Polymer/polymer#4701]
### Description

:host selectors are not properly working in Safari,
When using something like `:host([active])` the css updates correctly, but when you use an extra selector after the host (like: `:host([active])  .child`) the style for that element does not update correctly

#### Live Demo

http://jsbin.com/wasupiyafe/edit?html,css,js,output

#### Expected Results

CSS should update as soon as the attribute on the host is set or removed

#### Actual Results

CSS does not update when the attribute on the host is set or removed

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [x] Safari 9
- [x] Safari 8
- [ ] IE 11

### Versions

- Polymer: v2.0.1
- webcomponents: v1.0.1

**Comment by sorvell** [comment]
This is a [bug in Safari](https://bugs.webkit.org/show_bug.cgi?id=170762). It looks like it's fixed in the nightly versions so we're hopeful it will be in the next release.

Until then, you can workaround this by forcing use of the webcomponents polyfills conditionally on Safari.

**Comment by tpluscode** [comment]
@sorvell could you elaborate on the fix? I'm running Safari 10.0.2 and this issue is still there

**Comment by bartwr** [comment]
I found this [workaround](https://github.com/Polymer/polymer/issues/4695#issuecomment-309358103) suggested by @samiheikki. Works well for me.

In my case:

      tapHandler() {
        this.pressed = ! this.pressed;

        // Safari has an issue with repainting shadow root element styles when a host attribute changes.
        // Need this workaround (toggle any inline css property on and off) until the issue gets fixed.
        // Issue is fixed in Safari 11 Tech Preview version.
        // if (this._isSafari && this.root) {
        this.root.querySelectorAll('*').forEach(function(el) {
          el.style['-webkit-backface-visibility'] = 'visible';
          el.style['-webkit-backface-visibility'] = '';
        });
        // }
      }
