### ISSUE TITLE
Polymer 2.0 - issue with dom-repeat inside of html table (using 2.0 composition syntax)

### ISSUE THREAD

**Issue by JeffGillin** [Polymer/polymer#4704]
Hey all,
   I'm working on upgrading some Polymer v1.1 samples to v2.0.
   I'm trying out the new template binding syntax (using composition) as such:

```
<base href="http://polygit.org/polymer+:master/components/"> 
<link href="polymer/polymer-element.html" rel="import">
<link href="polymer/polymer.html" rel="import">
<dom-module id="dom-element">

    <template>
        <table>
            <tr><th>Numbers</th></tr>
            <dom-repeat items="[1,2,3]">
                <template>
                    <tr><td>[[item]]</td></tr>
                </template>
            </dom-repeat>
        </table>
    </template>

    <script>
        class DomElement extends Polymer.Element {
          static get is() { return "dom-element"; }
        }
        customElements.define(DomElement.is, DomElement);
    </script>

</dom-module>
```

The output from this is that the numbers in the dom-repeat display above the header. An inspection of the dom itself shows the tr elements first, then dom-repeat, then table element. Is this "composition" syntax for dom-repeat templates not ready yet? If so, it's certainly not an issue for me. Just wanted to report back on what I'm seeing.`

**Comment by arthurevans** [comment]
I thought the doc was pretty clear that you should only convert `dom-repeat`, `dom-if` and `dom-bind` elements at the document level, not inside an element template.

https://www.polymer-project.org/2.0/docs/upgrade#remove-type-extension-elements
https://www.polymer-project.org/2.0/docs/devguide/templates#dom-repeat

And this is one of the main reasons—the HTML parser has rules about what can go inside a `<table>`. `<template>` is on that list, and `<dom-repeat>` isn't, so the `<dom-repeat>` gets evicted from the table. If you use `<template is="dom-repeat">`, it should work fine.

**Comment by JeffGillin** [comment]
Gotcha, thanks Arthur
