### ISSUE TITLE
Create Polymer.DomSwitch mixin

### ISSUE THREAD

**Issue by coreyfarrell** [Polymer/polymer#4709]
### Description
Create Polymer.DomSwitch mixin or base class which chooses between multiple templates based on the value of the `type` property.

#### Live Demo
https://jsbin.com/mecuhoxadi/edit?html,output

### Versions
- Polymer: master
- webcomponents: master

So far I have only tested this feature on Chrome.

**Comment by romulocintra** [comment]
@coreyfarrell  Great new feature and great job , but i think naming could be more friendly or  adjusted the regular switch sintax : switch , case and default.

**Comment by coreyfarrell** [comment]
Note that DomSwitch is not an element, it's a mixin / base class.  I've gone back and forth between mixin and base class, not sure which is a better way.  Anyways it's not like `dom-if` - currently there is no dom-switch element that can be used ad-hoc.  I can look into that but first I'd like to ensure that the template cloning and stamping is done correctly.

I chose the property `type` to be used in child elements to select the template for use because `<input>` uses `type` to chose between different implementations.  The rest of the naming only effects developers of child elements, not users of those elements.

Am I understanding that you're suggesting child classes be written as such (using case):
```html
<dom-module id="example-element">
  <template case="type1"><div>content for type="type1"</div></template>
  <template default><div>content if we can't match type</div></template>
  <script>
    class ExampleElement extends Polymer.DomSwitch(Polymer.Element) {
      static get is() { return 'example-element'; }
    }
    customElements.define(ExampleElement.is, ExampleElement);
  </script>
</dom-module>
```

Then you'd use the element with:
```html
<example-element type="type1"></example-element>
```

If I'm misunderstanding your suggestion please show a mockup of how you'd like to see an element defined and used (like example-element above).

**Comment by coreyfarrell** [comment]
I've added a `<dom-switch>` element for now but I suspect it will not make the final cut.

The problem is that using it requires having templates inside other templates, so you'd have to use `preserve-content` on each template inside `<dom-switch>`.  Unfortunately this prevents data-binding unless you add attributes to the `dom-switch` element, which would generally make `polymer lint` complain.

**Comment by TimvdLippe** [comment]
Closing per https://github.com/Polymer/polymer/pull/4710#issuecomment-331315289
