### ISSUE TITLE
A case for bringing back `element.getPropertyInfo` to Polymer 2.0 ?

### ISSUE THREAD

**Issue by slawomir-brzezinski-at-interxion** [Polymer/polymer#4713]
### Description

This is a request to restore `element.getPropertyInfo` that's been [removed in Polymer 2.0](https://www.polymer-project.org/2.0/docs/upgrade#removed-apis) or provide something that will allow me to achieve my use case without traversing the `__proto__` chain myself. 

My use case is the high-level [properties-from-ancestor-behavior](https://www.webcomponents.org/element/AqoviaElements/properties-from-ancestor-behavior).
The behavior needs the `propertyInfo.type` to be able to use `this.deserialize(..., type)` to preserve the deserialization rules for a property that is defined outside of this behavior (can be the inheriting component, its base class or any other mixin).

More context in my first question about this on [this Slack thread](https://polymer.slack.com/archives/C03PF4L4L/p1498762545768746).

### Versions

- Polymer: v2.X.X
- webcomponents: v1.X.X

**Comment by TimvdLippe** [comment]
With the new `properties-mixin`, you can now use `_properties` that is a flattened map of all properties:http://jsbin.com/woxilokemi/edit?html,console,output You can retrieve all information on all properties in this map.
