### ISSUE TITLE
modified innerHTML prevents stamping

### ISSUE THREAD

**Issue by fpolowood** [Polymer/polymer#4715]
### Description
An element modified via innerHTML cannot be stamped again

#### Live Demo
https://jsbin.com/yemubuweve/edit?html,console,output

#### Steps to Reproduce
1. Create an array property with three elements
2. create a dom-repeat bound to that property with a div displaying each value of the array
3. modify one of the elements via innerHTML
4. set new values for the array

#### Expected Results
The new values of the array to be displayed

#### Actual Results
The elements that were not modified via innerHTML display the new values, the one that was modified remains untouched.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v2.0.1 
- webcomponents: v1.0.1

**Comment by sorvell** [comment]
This occurs because for efficiency, the repeated elements are re-used when the dom-repeat's array changes. This could be addressed by adding a `restamp` option to `dom-repeat` as has been discussed in https://github.com/Polymer/polymer/issues/1713.

**Comment by TimvdLippe** [comment]
`dom-repeat` with `restamp` has landed in master. @fpolowood could you try out the master version of Polymer and see if that fixes your issue?

**Comment by fpolowood** [comment]
Yes, it does, see jsbin
https://jsbin.com/vuwukevewu/1/edit?html,console,output
Closing
