### ISSUE TITLE
iOS native label -> checkbox tap doesn't always toggle check status

### ISSUE THREAD

**Issue by sacah** [Polymer/polymer#4717]
### Description
Having a LABEL linked with an INPUT CHECKBOX via native FOR attribute, including Polymer 1.9.1/1.9.2, tapping on label doesn't always toggle checkboxes status.

#### Live Demo
https://jsfiddle.net/t2wr2cob/

#### Steps to Reproduce
Visit the above on an iOS device, I tested on iPad 10.3, iPhone 10.3
Tap on the 'Native checkbox' label a few times, it often works the first few times, then you'll see the label highlight as it received the tap, but the checkbox doesn't toggle.
Occasionally it worked every time, I re-ran the fiddle and it would break again.

If you disable polymer 1.9.2 from being loaded, but leave webcomponents-lite loading, problem doesn't exist. It's only when you include polymer.html#v1.9.2 that it breaks.

#### Expected Results
Checkbox toggles on tap

#### Actual Results
Checkbox often does not toggle on tap

### Browsers Affected
- [x] Mobile Safari 10

### Versions
- Polymer: v1.9.2
- webcomponents: v1.9.2

**Comment by straker** [comment]
Tested this with iOS 11 and polymer 2, still broken

**Comment by marybeshaw** [comment]
This is still a problem in Polymer 2.  Any progress?

**Comment by azakus** [comment]
Yep, this is a bug in the ghost click prevention code not understanding label clicks. Should be easy enough to fix by keeping track of label clicks.
