### ISSUE TITLE
 ...psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects! 

### ISSUE THREAD

**Issue by cordovapolymer** [Polymer/polymer#4718]
Bower seems to be deprecated, are there any plans to switch to webpack and yarn?

>  ...psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects! 

P.S. there is another issue about this https://github.com/Polymer/polymer/issues/4665, creating a new one with a clearer title.

**Comment by web-padawan** [comment]
The original issue is #326

**Comment by spyhole** [comment]
yarn + 1

**Comment by azakus** [comment]
Yep, closing for #326. We're still working on the best possible transition from bower, and we want to get it right the first time :)
