### ISSUE TITLE
Polymer 2.0 rendering issue in FireFox in combination with jQuery 3x

### ISSUE THREAD

**Issue by ackaaa** [Polymer/polymer#4719]
[jsbin_example_original.txt](https://github.com/Polymer/polymer/files/1124829/jsbin_example_original.txt)
### Description
First I really love Polymer! But when i tried to update from polymer 1.0 to polymer 2.0 i got some strange rendering bugs in combination with jquery 3.2.1 which not exist in polymer 1.0.

#### Live Demo
https://jsbin.com/bixopasacu/1/edit?html,output

#### Steps to Reproduce
1.) Select a row within the jQuery.Datatable

### Browsers Affected
- [x ] Firefox 54.0.1

![resultinfirefox54](https://user-images.githubusercontent.com/8734235/27866750-cb41cdc0-6197-11e7-8349-b644914c7fc0.PNG)

**Comment by web-padawan** [comment]
Consider using Web Components for [tables](https://www.webcomponents.org/search/table) instead of jQuery widgets. 

In short, jQuery widgets are not aware of the Shadow DOM. As of 1.0 you could still use them somehow because of Shady mode, but 2.0 relies much on the native implementations in Chrome and Safari and uses them by default.

**Comment by motss** [comment]
@ackaaa Please bear in mind that this might be caused by the differences of no native Shadow DOM vs ShadyDOM on Firefox.

**Comment by ackaaa** [comment]
@web-padawan: Thanks for the information. This livedemo is just an easy example to show the problem. But if you use remote data with bigger tables and paging in combination with sorting and columnreordering and all this stuff - there is no other way to go than with jQuery.Datatables till now, unfortunately. Anyway with jquery1.12.4 it´s still working with polymer 2.0 so i will use this for now.

**Comment by ackaaa** [comment]
@motss: Yeah you nailed it. When i put <script>window.ShadyDOM = {force: true};</script> i will get the same behavior in all browsers. So it´s the ShadyDom in FireFox that is causing that problem.

**Comment by H3dz** [comment]
@ackaaa This article by @robdodson might help
https://robdodson.me/dont-use-jquery-with-shadow-dom/

**Comment by ackaaa** [comment]
@H3dz: thanks for the article ...i came over it some days ago too. But i think my problem is a different one because firefox is the only browser where this problem occurs and when i force polymer to use ShadyDom it occurs also in chrome etc. So i think in this special case its the ShadyDom not the ShadowDom.

**Comment by sorvell** [comment]
This issue was moved to webcomponents/shadydom#163
