### ISSUE TITLE
Data binding doesn't parse Japanese unicode characters

### ISSUE THREAD

**Issue by ajiang286** [Polymer/polymer#4723]
Version 1.6.1:

`value="{{data.商品名}}"`
evaluates to the string "{{data.商品名}}" instead of dereferencing data.商品名

**Comment by ajiang286** [comment]
Seems to happen for any non-English/numeric unicode

**Comment by kevinpschaaf** [comment]
The binding parser only considers [valid javascript identifiers](https://developer.mozilla.org/en-US/docs/Glossary/Identifier) for path bindings.

However, as long as you don't need 2-way binding, you can use `[[get('...')]]` to retrieve paths using arbitrary characters by leveraging [computed bindings](https://www.polymer-project.org/2.0/docs/devguide/data-binding#annotated-computed) and the [`get`](https://www.polymer-project.org/2.0/docs/api/elements/Polymer.Element#method-get) method that exists on the Polymer base class:  http://jsbin.com/qucada/edit?html,output

If you need 2-way bindings to paths, you'll need to restrict the data model to valid JS identifiers.

Will one of those solutions work for you?

**Comment by ajiang286** [comment]
I was able to come up with a solution based on your response.  Thanks!

**Comment by TimvdLippe** [comment]
Closing per above comment.

**Comment by TimvdLippe** [comment]
Oh oops. After I closed this issue, I realized exactly the same, but did not reopen this issue. Thanks for doing so @arthurevans ! Note that I published #4768 that solves this particular issue as well :tada:
