### ISSUE TITLE
Feature request: support strip-whitespace when providing the template as a string

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer#4731]

**Comment by arthurevans** [comment]
Ping on this one, relevant to 3.x

**Comment by TimvdLippe** [comment]
Hm, should be quite straightforward. The only thing we need to decide on is how to set the option.

**Comment by beaudesigns** [comment]
From an optimization standpoint, this is going to bite our web application as we upgrade components. We can have thousands of components in the DOM at any given time, so those text nodes really add up.

**Comment by rictic** [comment]
So, I think this will work:

```javascript
class MyElement extends PolymerElement {
  static get template() {
    const myTemplate = html`
        <div> hello world </div>
      `;
    myTemplate.setAttribute('strip-whitespace');
    return myTemplate;
  }
}

**Comment by rictic** [comment]
Yeah, tested it with https://glitch.com/edit/#!/wiry-pediatrician
