### ISSUE TITLE
Optimize the order of utils functions in render-status.html

### ISSUE THREAD

**Issue by zaclummys** [Polymer/polymer#4732]
#### Why
> When visual changes are happening on screen you want to do your work at the right time for the browser, which is right at the start of the frame. The only way to guarantee that your JavaScript will run at the start of a frame is to use **requestAnimationFrame**.
> 
> Frameworks or samples may use **setTimeout** or **setInterval** to do visual changes like animations, but the problem with this is that the callback will run at some point in the frame, possibly right at the end, and that can often have the effect of causing us to miss a frame, resulting in jank.
[Optimize JavaScript Execution - Google Developers](https://developers.google.com/web/fundamentals/performance/rendering/optimize-javascript-execution)

#### Expected Results
The _usage_ and _functionality_ of **requestAnimationFrame** is guaranteed.
```js
function schedule() {
    scheduled = true;
    // before next render
    setTimeout(function() {
        scheduled = false;
        flushQueue(beforeRenderQueue);
        // after the render
        requestAnimationFrame(function() {
            runQueue(afterRenderQueue);
        });
    });
}
```

#### Actual Results
The _usage_ and _functionality_ of **requestAnimationFrame** is lost.

```js
function schedule() {
    scheduled = true;
    // before next render
    requestAnimationFrame(function() {
        scheduled = false;
        flushQueue(beforeRenderQueue);
        // after the render
        setTimeout(function() {
            runQueue(afterRenderQueue);
        });
    });
}
```

**Comment by sorvell** [comment]
The quoted code is in support of methods that are specifically intended to support executing code before and after rendering.

The `requestAnimationFrame` call is used to determine when to fire callbacks registered via `Polymer.RenderStatus.beforeNextRender`. The `setTimeout` is used to determine when to fire callbacks registered via `Polymer.RenderStatus.afterNextRender`. As this is the intended behavior, there's nothing to optimize here. 

Please feel free to re-open with additional info and explanation if we missed something.

**Comment by motss** [comment]
Can do something like this?

```js
Polymer.RenderStatus.afterNextRender(this, () => {
  window.requestAnimationFrame(() => /* Do subsequent task */);
});
```
