### ISSUE TITLE
binded slot inside dom-repeat not working in IE11

### ISSUE THREAD

**Issue by jay8t6** [Polymer/polymer#4733]
### Description

binded slot inside dom-repeat not working in IE11

#### Steps to Reproduce
```
<iron-accordions>
	<template is="dom-repeat" items="[[items]]" index-as="id">
		<iron-accordion>
			<slot name="some-slot-[[id]]">
				First Name: [[item.name]]
			</slot>
		</iron-accordion>
	</template>
</iron-accordions>
```

#### Expected Results
Slot content appearing in each iron-accordion

#### Actual Results
All slots appear in the first accordion

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11

### Versions

- Polymer: v1.x
- webcomponents: v0.x

**Comment by unionthugface** [comment]
Also having this problem with Polymer v2

**Comment by arthurevans** [comment]
Have you tried `name$="some-slot-[[id]]"`? Perhaps this is another property that IE handles differently?

At any rate, I believe slots are assigned based on attributes, not properties, so arguably `slot$=` is more correct.

**Comment by sorvell** [comment]
This issues should be fixed with the latest [webcomponents release 1.0.2](https://github.com/webcomponents/webcomponentsjs/releases/tag/v1.0.2), a related issue in the Shady DOM polyfill was resolved. Please re-open with more information if the issue persists.

**Comment by sorvell** [comment]
Here's a working example: https://glitch.com/edit/#!/emerald-noise.

**Comment by jay8t6** [comment]
@sorvell so there is no fix when using polymer 1.x and wc 0.x?
