### ISSUE TITLE
Uncaught TypeError: Polymer is not a function

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/polymer#4736]
Polymer v1.9.2
polymer-cli v1.3.1
chrome 59.0.3071.115

I was going to add this to https://github.com/Polymer/polymer/issues/4134 because I was hitting that error quite a lot while I was thrashing around trying to make it work, but it seems a little different now, so I'm making a new one.

While I started my app with PSK (November last year), I have changed the loading sequence based on inspiration from of some of Paul Lewis' blogs. That is, I've removed as many dependencies as possible from index.html and used plain old html and css to make it render the same as my shell. I do have my two Polymer elements in my body, but the browser ignores them - they are my-config and my-app (loaded synchronously, since my-app depends on my-config).

On onload, I add the webcomponents-lite js script tag to head, and on WebComponentsReady, I add the import tags for my two polymer elements, so they are upgraded, and when my-app is `ready` it hides the 'first frame' html in the body so my-app becomes visible.

At this point my app starts. my-app and a few other elements in my app lazily load some other elements, but they all use LazyImportsBehavior so they each have a `<link rel-"lazy-import"...` line which, I presume, means the polymer analyser can detect them and I don't need to give them special treatment in polymer.json (right?).

Up until now, I've been using this build target:

```
      "name": "es5-unbundled",
      "js": {
        "minify": false,
        "compile": true
      },
      "css": {"minify": true},
      "html": {"minify": true},
      "addServiceWorker": true
```

Yes, it's no strictly just 'unbundled' since I disabled js minification (it was a while ago, but I think it was something to do with Edge) but that seems to work fine, but I'm now attempting to incorporate bundling, (adding the targets from the newest psk's polymer.json) and that is where I hit the errors mentioned in this issue. At the moment, I'm building with:

`polymer serve build/es5-bundled`

and the error I am getting just:

```
Uncaught TypeError: Polymer is not a function
    at my-config.html:1
```

The first line of my-config.html is a plain old import for polymer.html, so I would have expected polymer.html to be imported and initialised before the Polymer() constructor is called (the import is not async or anything). I can see from the dom in chrome's devtools that, while my-app is upgraded, my-config is not - the link *is* in the head too.

In my polymer.json, I have my-config.html and my-app.html in the fragments object, webcomponents-lite.min.js in the extraDependencies object.

So, I am hoping that someone here can tell me where I need to put what files in my polymer.json file.

**Comment by TimvdLippe** [comment]
I think this is an issue of the [Polymer Bundler](https://github.com/polymer/polymer-bundler)

**Comment by TimvdLippe** [comment]
Closing per above comment. If this is still an issue, please open an issue on the bundler to be able to be triaged there.
