### ISSUE TITLE
this.$.id returns undefined inside a dom-if template

### ISSUE THREAD

**Issue by jmorille** [Polymer/polymer#4738]
### Description
Any element inside the template ```dom-if```  have the  ids not reference with the map ```this.$.``` map
```html
<template is="dom-if" if="[[displayNode]]">
       <h2 id="myNode">Bug [[prop1]]!</h2> 
</template>
```
The call of produce  .```this.$.myNode=undefined.```

like the
```js
   console.log("myButton is myNode is Not juste because is inside a template : ", this.$.myNode);
```
Any call of id outside the template is working.

#### Live Demo 
http://jsbin.com/muquqesuqa/edit?html,console,output

1. Click on "Console Log ids" button
2. and look the console to see the message 

```shell
"myButton is myNode is Not juste because is inside a template : this.$.myNode ==> undefined"
```
produce by the code
```js
printNodeRef() {
    console.log("myButton is found : this.$.myButton ==> "+ this.$.myButton.tagName);
    console.log("myButton is myNode is Not juste because is inside a template : this.$.myNode ==> "+ this.$.myNode);
}
```

#### Steps to Reproduce

1. Create a template dom-if and add any element with an id like  id="myNodeId" 
2. The node  this.$.myNodeId = undefined inside the template
 

#### Expected Results 
```this.$.myNodeId```  sould be the node reference

#### Actual Results 
```this.$.myNodeId``` is ```undefined``` 

### Browsers Affected

- [x] Chrome 
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11

### Versions

- Polymer: v2.0.2
- webcomponents: v1.0.2

**Comment by web-padawan** [comment]
You cannot refer to the nides inside template tags like this, because `this.$` is filled at the component bootstrap and those templates are not yet stamped.

So, it works as intended. There is a `polymer-linter` [issue](https://github.com/Polymer/polymer-linter/issues/9) on this topic.

**Comment by jay8t6** [comment]
do `this.$$('#id')`

**Comment by web-padawan** [comment]
`this.$$` does not exist anymore when using `polymer-element`, you need [legacy-element-mixin](https://github.com/Polymer/polymer/blob/master/lib/legacy/legacy-element-mixin.html#L441) for that.

**Comment by jay8t6** [comment]
@web-padawan so just use `this.root.querySelector('#id')`?

**Comment by jmorille** [comment]
I used '''this.shadowRoot.querySelector('#id');''' and it is working for me.

It just feel strange that in the API it is not availaible in the ```this.$``` map.

**Comment by TimvdLippe** [comment]
For future reference this limitation is listed in https://www.polymer-project.org/2.0/docs/devguide/dom-template#node-finding

> Note: Nodes created dynamically using data binding (including those in dom-repeat and dom-if templates) are not added to the this.$ hash. The hash includes only statically created local DOM nodes (that is, the nodes defined in the element's outermost template).

Thanks @web-padawan for answering this question.

**Comment by yairopro** [comment]
Hi
Is there a reason why Polymer doesn't place a proxy in the `$`.
Like this:
```
this.$ = new Proxy(this.$, {
	get: ($, id) => $[id] || this.shadowRoot.getElementById(id),
	set: ($, id, element) => {
		$[id] = element;
		return true;
	}
});
```

**Comment by TimvdLippe** [comment]
That would be too expensive and Proxies are not supported in IE:
https://caniuse.com/#feat=proxy

**Comment by romanzhivo** [comment]
I had this problem. I think it is because of `<template is="dom-if">` is asynchronyos, and only after some timeout we can to get an element inside the template `dom-if` like this:
`
ready() {
super.ready();
const element = this.shadowRoot.querySelector('#myNode');
}
`
