### ISSUE TITLE
`Dom-module` documentation issue

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#4740]
_From @galanovnick on July 4, 2017 11:39_

In the [dom-module](https://www.polymer-project.org/2.0/docs/api/elements/Polymer.DomModule) documentation we have example with the `import` command. `Import` is presented as a method of the instance but it seems like it's a static method.

Plese, check this out and consider to change `document.createElement('dom-module').import` to `Polymer.DomModule.import`.

_Copied from original issue: Polymer/docs#2236_

**Comment by arthurevans** [comment]
_From @katejeffreys on July 19, 2017 19:42_

@arthurevans Can you comment on this?

**Comment by arthurevans** [comment]
Seems correct—I wonder if @sorvell or @kevinpschaaf can comment if there's any reason it should stay the way it is.

These API docs are built from the Polymer source, so I'll move it over there.

**Comment by TimvdLippe** [comment]
As the API is used in a static fashion (https://github.com/Polymer/polymer/search?utf8=%E2%9C%93&q=Polymer.DomModule&type=) the docs should be updated. Feel free to submit a PR!
