### ISSUE TITLE
Hybrid-style custom-style includes (`:host, html`) do not work in top-level custom-styles with Polymer 1.x

### ISSUE THREAD

**Issue by keanulee** [Polymer/polymer#4742]
### Description
With Polymer 1.x, if I have a custom-style include with `:host, html`, e.g.:

```html
<dom-module id="some-theme">
  <template>
    <style>
      :host, html { ... }
    </style>
  </template>
</dom-module>
```

And use it in a top-level custom-style (i.e. one not inside a Polymer element):

```html
<head>
  <style is="custom-style" include="some-theme"></style>
</head>
```

On browsers without native Shadow DOM (e.g. Firefox), there's a "not a valid selector error":

```
SyntaxError: ':not([style-scope]):not(.style-scope):host,html:not([style-scope]):not(.style-scope)' is not a valid selector
```

#### Live Demo
https://www.polymer-project.org/2.0/docs/api/elements/Polymer.ArraySelector

### Browsers Affected
- [ ] Chrome
- [x] Firefox

### Versions
- Polymer: v1.x 

Ref https://github.com/Polymer/docs/issues/2258
cc @azakus

**Comment by azakus** [comment]
Closed with #4744
