### ISSUE TITLE
Polymer.Path.matches signature different in 1.x compared to 2.x

### ISSUE THREAD

**Issue by valdrinkoshi** [Polymer/polymer#4743]
Signature of `Polymer.Path.matches` is different in 1.x compared to 2.x. Is this expected?
It was introduced in [1.7.0](https://github.com/Polymer/polymer/blob/v1.7.0/polymer.html#L336): 
```js
matches: function(base, wildcard, path) {
```
But was changed starting from [2.0.1](https://github.com/Polymer/polymer/blob/v2.0.1/lib/utils/path.html#L131):
```js
matches: function(base, path) {
```

Also, not all the methods of the 2.x version are available on 1.x (e.g. split, set, get)

**Comment by valdrinkoshi** [comment]
@sorvell FYI

**Comment by azakus** [comment]
@kevinpschaaf

**Comment by TimvdLippe** [comment]
Apparently this function is not documented on `Polymer.Path` (https://www.polymer-project.org/2.0/docs/api/namespaces/Polymer.Path), as it misses the `@memberof` annotation in the JSDoc. I wonder if this was intentional and whether this function is actually part of our public API.
