### ISSUE TITLE
dom-repeat is wrong when attached/detached 

### ISSUE THREAD

**Issue by kolesoffac** [Polymer/polymer#4746]
### Description
When i use `<dom-repeat>`, and when i remove item from items, in detached-method use last id.

#### Live Demo
https://codepen.io/anon/pen/ZJEXqB

#### Steps to Reproduce
Example:

1. Load the page in the demo above.
2. Observe _"attached the DOM! - "_ logged in the console
3. Press the button marked **Remove first item**

#### Expected Results
"attached the DOM! - " "0"
"attached the DOM! - " "1"
"attached the DOM! - " "2"
"detached the DOM! - " "0"

#### Actual Results
"attached the DOM! - " "0"
"attached the DOM! - " "1"
"attached the DOM! - " "2"
"detached the DOM! - " "2"

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions
- Polymer: v2.0.2
- webcomponents: v1.0.0

**Comment by sorvell** [comment]
I believe this is the same basic issue as https://github.com/Polymer/polymer/issues/1713. There's a fix in the works. @kevinpschaaf can you verify?

**Comment by TimvdLippe** [comment]
We have analyzed your use-case and understood the "unexpected behavior". `<dom-repeat>` reuses element nodes for performance reasons. The assumption that the property `layer` remains the same throughout the lifecycle of the custom elements thus becomes incorrect. As such, whenever `layer` changes, in the oberserver you need to update the value of `id` as well.

You can in the future workaround this issue with using the feature `restamp` on `<dom-repeat>`, which is tracked on #1713. Therefore I am closing this issue, feel free to subscribe to #1713.
