### ISSUE TITLE
Legacy Polymer syntax is broken with Polymer 2.0.2 & closure compiler

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#4747]
### Description
Building Polymer 2.0.2 with nightly build of Google Closure Compiler (that supports polymer_version: 2) fails to do anything.
There was no such issue with Polymer 2.0.1 build with stable Google Closure Compiler

#### Live Demo
I've build 2.0.2 locally and uploaded it here: http://plnkr.co/edit/8XJo5n0ZSVDp7j49m2U9?p=preview

#### Steps to Reproduce
1. Build Polymer 2.0.2
2. Include on page
3. Create `my-element` with `Polymer()`

#### Expected Results
Element created, no errors

#### Actual Results
```
Uncaught TypeError: window.Polymer.a is not a function
```

### Browsers Affected
- [x] Chrome
- [x] Firefox

### Versions
- Polymer: v2.0.2
- webcomponents: v1.0.3

**Comment by azakus** [comment]
Yep, we needed to add some instance properties to the externs. You can work around by setting `use_types_for_optimization` to false until the next release.

**Comment by nazar-pc** [comment]
Here is an updated demo with fresh build from master: http://plnkr.co/edit/vsbDPSF4kepnEVLpTezl?p=preview
Issue is not gone, I think this should be reopened.

**Comment by nazar-pc** [comment]
Interesting, looks like `estimate-size` gulp task is fine, while `closure` task if broken.
