### ISSUE TITLE
Documentation incorrect for `reflectToAttribute`

### ISSUE THREAD

**Issue by wchargin** [Polymer/polymer#4749]
[The documentation reads:](https://www.polymer-project.org/1.0/docs/devguide/properties#attribute-reflection)

> In specific cases, it may be useful to keep an HTML attribute value in sync with a property value. This may be achieved by setting `reflectToAttribute: true` on a property in the `properties` configuration object. This will cause any observable change to the property to be serialized out to **an attribute of the same name.**

(emphasis mine)

This is false. A property of the name `_oneTwoThree` will appear as an attribute `_one-two-three`. CSS selectors of the form `:host[_oneTwoThree]` will do nothing, while `:host[_one-two-three]` works fine.

(The same happens without the underscore, of course.)

The docs should instead refer the reader to the section "Property name to attribute name mapping" on the same page. (This section is close enough to correct, though to be careful one should replace "The same mappings happen in reverse when converting property names to attribute names" with "When converting property names to attribute names, the second mapping described above is performed in reverse"; the first mapping is not invertible and is of course not applied.)

[The same issue appears in the 2.0 docs.](https://www.polymer-project.org/2.0/docs/devguide/properties#attribute-reflection)

**Comment by arthurevans** [comment]
Good catch. Thanks!

**Comment by TimvdLippe** [comment]
Opened a PR for this issue: https://github.com/Polymer/docs/pull/2316
