### ISSUE TITLE
published 2.0.2 declares itself as 2.0.1

### ISSUE THREAD

**Issue by gaarf** [Polymer/polymer#4751]
### Description
`window.Polymer.version = '2.0.1';` in published 2.0.2 package

#### Live Demo
http://jsbin.com/jigolezogo/1/edit?html,js,output
https://unpkg.com/@polymer/polymer@2.0.2/lib/utils/boot.html

#### Steps to Reproduce
`console.log(Polymer.version)`

#### Expected Results
2.0.2

#### Actual Results
2.0.1

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions
- Polymer: v2.0.2

**Comment by TimvdLippe** [comment]
Thank you for the issue. We missed this one during the release of the latest version. Bumping the version number is a manual task, but @azakus will bump the version when a new release is published.
