### ISSUE TITLE
slot.assignedNodes() are migrating from one element to another on the same page

### ISSUE THREAD

**Issue by andrewmiroshnichenko** [Polymer/polymer#4755]
### Description
slot.assignedNodes() are migrating from one element to another on the same page
#### Live Demo
Sorry, JSBin don't recognize slot inners at all.
This is github repo I created for this bug demo:
https://github.com/andrewmiroshnichenko/polymer-bug

#### Steps to Reproduce
1. Clone repo
1.1. Make sure you have polymer-cli installed.
1.2 Run `bower install` just to be sure that all deps are fresh
2. Run `polymer serve` in repo's root.
3. Open browser and on demo page you will see array `['Item one', 'Item two']` printed two times despite the fact that second `polymer-bug` element is initialized without children div's.

#### Expected Results
Second `polymer-bug` element should have propList attribute empty

#### Actual Results
Second `polymer-bug` element have propList attribute equal to first one

### Browsers Affected
- [ x] Chrome

### Versions
- Polymer: v2.0.1
- webcomponents: v1.0.4

**Comment by azakus** [comment]
You have a slight bug here: https://github.com/andrewmiroshnichenko/polymer-bug/blob/master/polymer-bug.html#L28-L35

```js
      static get properties() {
        return {
          propList: {
            type: Array,
            value: []
          }
        };
      }
```

should be 
```js
      static get properties() {
        return {
          propList: {
            type: Array,
            value: () => []
          }
        };
      }
```
Otherwise all instances of that element will share the same array for for `propList`

**Comment by andrewmiroshnichenko** [comment]
Thanks @azakus, it solves the problem. Actually I found a ref to this behavior in Polymer docs https://www.polymer-project.org/2.0/docs/devguide/properties#configure-values

> When initializing a property to an object or array value, use a function to ensure that each element gets its own copy of the value, rather than having an object or array shared across all instances of the element.

But is this behavior normal? I mean calling the function to get a "clear" array or object. If yes and shouldn't be changed - than issue can be closed, I think.

**Comment by azakus** [comment]
Yes, this is what is required to get a per-instance array or object from the properties block. That said, it would be better to set those in the constructor of your element, as it is equivalent:
```js
class XFoo extends Polymer.Element {
  constructor() {
    super();
    this.propList = [];
  }
}
```
