### ISSUE TITLE
what is the relation of polymer elements with https://material.io/components/web/catalog/

### ISSUE THREAD

**Issue by spyhole** [Polymer/polymer#4756]

**Comment by web-padawan** [comment]
MDC-Web just rely on the BEM naming convention to emulate CSS scoping. 
They can't be used in polymer elements right now, but this is likely to change regarding upcoming `npm` support and [webpack loader](https://github.com/webpack-contrib/polymer-webpack-loader). So I expect in the future we will be able to do something similar to [Aurelia examples](https://github.com/material-components/material-components-web/blob/master/framework-examples/aurelia/src/components/button/mdc-button.ts).

**Comment by spyhole** [comment]
many thanks @web-padawan, you answered me some doubts

**Comment by spyhole** [comment]
@web-padawan thanks again

**Comment by TimvdLippe** [comment]
Closing as the original question has been answered.

**Comment by spyhole** [comment]
okey
