### ISSUE TITLE
already defined exception thrown when using different webcomponents import locations.

### ISSUE THREAD

**Issue by vdegenne** [Polymer/polymer#4758]
Is there a way to prevent Polymer of trying to import two same files ? It won't import two same files if the import url is similar and will use the cache instead but if the url is different it will import again resulting in some redefining errors. Is there a mechanism to prevent this if, for instance, the uri between two import url are similar (e.g. polymer/polymer.html).
I am using two different locations where I import custom elements, those custom elements are importing relatively other elements, if these different locations import same files, it will throw the error I mentioned. I think this is an issue because it is common to fetch components from different locations, and that is the modularity webcomponents prone to offer.

Here's an illustration so you really understand the issue.

<img src="https://image.ibb.co/jdUPfQ/Untitled_4.png">

<img src="https://image.ibb.co/gy9UEk/polymer_fail.png">

**Comment by TimvdLippe** [comment]
I don't see a real solution here, other than adding a proxy in between your clusters. That way the url is the same, but the actual location is different.

**Comment by TimvdLippe** [comment]
Closing this per above comment as a wont fix. The specification states that deduplication is performed per URL, which means that the URL of a component should remain the same throughout your application.
