### ISSUE TITLE
“Maximum stack size exceeded” when using “this.super” in Polymer hierarchies

### ISSUE THREAD

**Issue by secretrobotron** [Polymer/polymer#476]
_Cross-posted on stackoverflow: http://stackoverflow.com/questions/23144799/maximum-stack-size-exceeded-when-using-this-super-in-polymer-hierarchies_

When we have element hierarchies that have overridden parent functions, we run into a "Maximum stack size exceeded" from time to time. Most recently, I noticed the error creep up in a situation like this:

```html
<polymer-element name="element-a" noscript></polymer-element>

<polymer-element name="element-b" extends="element-a">
  <script>
    Polymer('element-b', {
      attached: function () { this.super(); }
    });
  </script>
</polymer-element>

<polymer-element name="element-c" extends="element-b">
  <script>
    Polymer('element-c', {
      attached: function () {this.super();  }
    });
  </script>
</polymer-element>
```

http://jsbin.com/guqeyome/2/edit

My thinking was that if element A doesn't have an "attached" function, the super call in element C will eventually call nothing. Instead, it calls element B's "attached" function, which spins up an infinite recursion situation. The solution is to have an empty "attached" function in element A.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
