### ISSUE TITLE
Error polyfillWrapFlushCallback thrown after cache deletion on IE 11

### ISSUE THREAD

**Issue by BorntraegerMarc** [Polymer/polymer#4760]
### Description

Error `Unable to get property 'polyfillWrapFlushCallback' of undefined or null reference` is thrown every time I reload a polymer app without cache.

This only happens after the cache has been cleared. If you reload the web page everything works fine again.

#### Live Demo

http://jsbin.com/luhaxab/1/edit

#### Steps to Reproduce

1. Create any polymer app
2. Clear cache of IE
3. Open up app
4. See error:
![image](https://user-images.githubusercontent.com/7549295/28797830-ec54e8d4-7642-11e7-922f-0e34e9b9df14.png)
5. Reload the app (only by pressing F5):
![image](https://user-images.githubusercontent.com/7549295/28797843-f6a1c668-7642-11e7-948d-fdc27fc9f729.png)

#### Expected Results
No error is throw

#### Actual Results
Error is thrown

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [X] IE 11

### Versions

- Polymer: v2.0.2
- webcomponents: v1.0.1

**Comment by azakus** [comment]
I don't seem to be getting that error with newer webcomponents builds. Can you try updating to 1.0.5?

**Comment by BorntraegerMarc** [comment]
There is an issue that prevents us using a newer version. Will write back, once it's resolved

**Comment by BorntraegerMarc** [comment]
@azakus I upgraded to v1.0.10 and am still getting the error:
![image](https://user-images.githubusercontent.com/7549295/30250663-c26db5b6-9652-11e7-932f-439f97f21505.png)

and:
![image](https://user-images.githubusercontent.com/7549295/30250664-c7b4058e-9652-11e7-9e1b-65e5915bd622.png)

**Comment by LasaleFamine** [comment]
Getting the same error:

`Unable to get property 'polyfillWrapFlushCallback' of undefined or null reference`

But I'm on **Edge (v40.15063.0.0)** with Polymer 3 and `webcomponents-loader.js` (read '`-lite.js`' for Edge).

**Comment by BorntraegerMarc** [comment]
@azakus did you find out something new?

**Comment by evancaldwell** [comment]
I'm also getting this error in IE11 using Polymer 3 and webcomponents-loader.js.

**Comment by sorvell** [comment]
This is likely happening because Polymer is being loaded before the Web Components polyfills. This is not supported and should be avoided.

We cannot repro this issue in Polymer 2.x, but it is currently expected in Polymer 3.x since there is no coordination between loading Polymer transpiled code and the Web Components polyfills. 

We plan to add a better error message here to explain that what is happening is "Polymer is being loaded without custom elements support."

We also plan to better integrated the web components loader with Polymer 3.x to avoid this issue.

**Comment by azakus** [comment]
This issue is now broken out into https://github.com/webcomponents/webcomponentsjs/issues/853 for the original issue @BorntraegerMarc reported, and https://github.com/webcomponents/webcomponentsjs/issues/882 for the issue from @LasaleFamine
