### ISSUE TITLE
Local html imports not cached in Google Chrome.

### ISSUE THREAD

**Issue by vdegenne** [Polymer/polymer#4763]
Google Chrome is not caching my local html imports.

<img src="https://i.stack.imgur.com/wmXua.png">

✔ Local and remote css's, scripts, ... are well cached.
✔ Remote html imports are well cached.
❌ It seems the issue is only for Local html imports.

Is this Polymer related issue ? Google Chrome issue ?

(Google Chrome Version 59.0.3071.115)

**Comment by TimvdLippe** [comment]
This is probably an issue with your local dev server. Polymer does not set any caching headers.

**Comment by vdegenne** [comment]
@TimvdLippe just realized that. thanks for your answer.

**Comment by TimvdLippe** [comment]
Okay great, good luck debugging!
