### ISSUE TITLE
Cordova

### ISSUE THREAD

**Issue by augmen** [Polymer/polymer#4764]
We are looking to create an android app using polymer. What are the Best Practices for using  Polymer & Cordova﻿

**Comment by TimvdLippe** [comment]
Such questions can be asked on the [Polymer Slack](https://polymer-slack.herokuapp.com/), as it is very broad and subjective. I don't think there is an actionable item in this as a GitHub issue.

**Comment by ronnyroeller** [comment]
I doubt that you will find somewhere a comprehensive list of everything to know about Polymer + Cordova. The combination generally works well but you will encounter interesting corner cases (especially as Cordova doesn't come with the best documentation ever...)
FYI, we tried to share the rough edges that we encountered here: https://medium.com/collaborne-engineering/tagged/cordova

**Comment by spyhole** [comment]
I doubt that you will find somewhere a comprehensive list of everything to know about Polymer + Cordova. The combination generally works well but you will encounter interesting corner cases (especially as Cordova doesn't come with the best documentation ever...)
FYI, we tried to share the rough edges that we encountered here: https://medium.com/collaborne-engineering/tagged/cordova

**Comment by joeblew99** [comment]
I used Cordova with polymer.
It's easy and works.
But you want a hell of a lot more than what Cordova offers to build a proper app.
Now I use xamarin webviews and it's way way better than cordova.

**Comment by augmen** [comment]
Please guide us to the link for marin web view.
Swapnil Bhadade
swapnilrbhadade83@gmail.com
Nagpur
India

**Comment by joeblew99** [comment]
@augmen 

https://github.com/xamarin/xamarin-forms-samples/tree/master/WorkingWithWebview

https://developer.xamarin.com/guides/android/user_interface/controls/web-view/

**Comment by azakus** [comment]
I think this issue can be closed now.
