### ISSUE TITLE
this.splice doesn't update bindings when using legacy element in Polymer 2.0

### ISSUE THREAD

**Issue by admwx7** [Polymer/polymer#4767]
### Description
When using this.splice to modify an array of items in a hybrid element that's running in a Polymer 2 app, the binding doesn't update.  Noticed this when trying to work with firebase-query.

#### Live Demo

coming soon

#### Steps to Reproduce
1. Create an element with a notifying property
2. Use this.splice to modify your array of items

#### Expected Results
Items should update in the parent element

#### Actual Results
Parent element's property bound to the child element isn't updated

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v2.0.2
- webcomponents: v1.0.4

**Comment by azakus** [comment]
@admwx7 I tried making what you described in a jsbin: https://jsbin.com/zakahab/edit?html,console,output

Does this reflect what you mean? The binding _does_ update in the parent element it seems, but an observer won't fire.

**Comment by admwx7** [comment]
I'll check into it more closely later, but I was using firebase-query and
it wasn't updating my binding even, added a call to notify path after each
splice in a branch for the competition I'm currently in, at finals right
now but I'll follow up over the weekend/Monday. Thanks for taking a look so
quickly.

**Comment by admwx7** [comment]
@azakus I think I narrowed down the issue, turns out that data isn't defined as a property on polymerfire/firebase-query, so I'll put out a PR for that.  While I was hunting that down I noticed that using this.splice will trigger updates through the binding system to the parent element whether you include `notify: true` or not, which seems odd.

https://jsbin.com/sasoro/edit?html,console,output
should be updated to use a legacy element within a 2.0 element syntax (my use-case), you'll notice it's updating even without `notify: true`, but if you remove the properties object from the child then you can see the issue in firebase-query.
