### ISSUE TITLE
Why is polymer loaded with only html imports?

### ISSUE THREAD

**Issue by TheInvoker** [Polymer/polymer#4774]
I'm new to polymer and am trying to understand how to load it. I'm reading this

https://www.polymer-project.org/2.0/start/quick-tour

In their first simple example, they load a polyfill

    <script src="https://polygit.org/components/webcomponentsjs/webcomponents-loader.js"></script>

which I understand the reason. But the next part, they load a html file, which appears to load the main polymer app.

They load it with a html import to here

    https://polygit.org/components/polymer/polymer-element.html

Which this appears to load a bunch of html files which all have script tags in it.

Then finally to use polymer, you just make a class that extends `Polymer.Element`.

This seems really strange, to why they chose to import a ton of html files. Why did they not just stuff all that js into 1 javascript polymer library file, like jquery. Or is there a javascript file for polymer like that?

Thanks.

**Comment by web-padawan** [comment]
Polymer 2 respects modular approach (and so does jQuery, BTW) but relies on the Web Components.
HTML imports is now a Chrome-only spec not adopted by evergreen browsers, that's true. But it was a first attempt to standartize loading resources, landed in 2013 - long before ES modules proposal, before Webpack etc.
You could use [webpack loader](https://github.com/webpack-contrib/polymer-webpack-loader) if you don't like HTML imports.

**Comment by TheInvoker** [comment]
It's not that I don't like html imports, but In my own project, I import modules by js script url. And so html imports to load a main library seems weird. Is there no single js file that loads the entire polymer element class?

**Comment by web-padawan** [comment]
I guess this should be clear now and can be closed as well as #4775?

/cc @TimvdLippe

**Comment by azakus** [comment]
You'll be pleased to know that in we'll be using the ES Module loader in Polymer 3.x.
We are still exploring all of the ways to author elements that would feel satisfying for users (build steps to allow separate HTML files, new specs for HTML to be natively loaded by ES modules, etc), but HTML Imports in their current form will not be used by future version of Polymer.

**Comment by TheInvoker** [comment]
What is the ES Module loader?

**Comment by web-padawan** [comment]
@TheInvoker see https://whatwg.github.io/loader

**Comment by arthurevans** [comment]
@TheInvoker @web-padawan the MDN article on import might be more useful:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

Not sure how relevant the stuff in that loader spec is.

**Comment by jasonwr** [comment]
I like how Polymer 3 is headed towards native ES6 modules, but having to stringify my HTML into the JS doesn't feel right. Hopefully in the future we'll have a way to separate HTML, CSS, JS. I really liked Polymer 2, but would like to get onboard more with ES6 modules as they seem like a really solid, long term solution (minus the side affects mentioned).

**Comment by vitawt** [comment]
@web-padawan hello ,  safari didn't support html imports ,but why it can run polymer in normal;sorry for my poor English.

**Comment by web-padawan** [comment]
@vitawt Safari (as well as Firefox, IE and Edge) uses the [webcomponentsjs](https://github.com/webcomponents/webcomponentsjs) polyfill for HTML imports.
