### ISSUE TITLE
How to avoid repeated polymer imports when using multiple polymer elements?

### ISSUE THREAD

**Issue by TheInvoker** [Polymer/polymer#4775]
I am new to polymer 2, and it seems, to load a polymer element, you import a html file that has these 3 html imports:

    1. the polyfill
    2. the main polymer element class
    3. and then potentially extras like iron-input.html or dom-repeat.html

If I then import 5 polymer element html files for 5 different elements, into my main page, I will have 5 times the above 3 imports. How do you avoid all that duplication, and massive import into the DOM?

Am I supposed to remove all the import statements from the 5 files manually? And just keep 1 of each?

https://www.polymer-project.org/2.0/start/quick-tour

Thanks

**Comment by web-padawan** [comment]
One of the core benefits of HTML imports is that browser de-duplicates them itself (and for Firefox, Safari and Edge polyfill handles this). 
You can also use [polymer-bundler](https://github.com/Polymer/polymer-bundler) tool for production to combine imports and decrease number of network requests, but that is optional with http 2.

**Comment by TheInvoker** [comment]
what do you mean de-duplicates?

**Comment by web-padawan** [comment]
I mean this quote from the [spec](http://w3c.github.io/webcomponents/spec/imports/):
>If LOCATION is already in the import map:
Let IMPORT be the imported document for LOCATION and stop.

That sakd, browser won't load file imported from the same location twice.

**Comment by TheInvoker** [comment]
So does that mean if there was two html import statements with the same url, the first one will be loaded and the second one will be skipped?

**Comment by web-padawan** [comment]
Yes, it does. Hovewer, if you try loading same resource from different locations, e. g. from CDN, such imports won't be de-duplicated and this might result in errors.

**Comment by TheInvoker** [comment]
If you have something like this

<link rel="import" href="/imports/heart.html">
<link rel="import" href="/imports/heart.html">

does that mean the first one will download and insert the heart html into the page DOM, but the second one won't download (re-use from cache), but will insert the heart html into the DOM?

**Comment by web-padawan** [comment]
1. Import is not a piece of DOM in the sense that in does not get inserted automatically, you need script to access imported documents (so they are useless when user disables JS in browser).

2. Polymer usually uses HTMl imports to load Custom elements, and that spec has a restriction: attempt to re-declare already defined element leads to error mentioned [here](https://github.com/Polymer/polymer/issues/4134)

For some insight on the future of this spec, I strongly recommend reading the discussion on [HTML modules](https://github.com/w3c/webcomponents/issues/645) proposal.

**Comment by web-padawan** [comment]
@TheInvoker if you still have questions about HTML imports, see [this article](https://www.html5rocks.com/en/tutorials/webcomponents/imports/#basics). I also recommend taking a look at ES modules as a future for Polymer 3.0

**Comment by TimvdLippe** [comment]
Closing this per above comment. Thanks @web-padawan for the explanation, hopefully it is more clear now @TheInvoker 😄
