### ISSUE TITLE
Polymer 2 Shop, PSK or simple projects broken on Safari 8 and Safari mobile 8

### ISSUE THREAD

**Issue by vedtam** [Polymer/polymer#4781]
Hi,

While testing my app on Safari 8 and Safari 8 mobile (real devices: iMac/iPad) I realised that my project was broken due to the following error:

`TypeError: undefined is not a function (evaluating 'Object.setPrototypeOf(f,b.prototype)')`

I immediately updated `polymer-cli` and installed a clean PSK than the Shop demo, both crash on startup while throwing the above error. I have tried to compile to ES5 as well, the error is still happening.

screenshot:

![screen shot 2017-08-08 at 11 50 22](https://user-images.githubusercontent.com/4981592/29063852-ddd9de52-7c2f-11e7-877f-4f5d05240cce.png)

To reproduce the error, just fire up a Xcode iOS simulator version 8.
Thanks!

**Comment by web-padawan** [comment]
Seems that [this row](https://github.com/webcomponents/custom-elements/blob/master/src/Patch/HTMLElement.js#L44) is the reason.

/cc @bicknellr

**Comment by arthurevans** [comment]
Note that Safari 8 is not on the list of officially supported browsers:

https://www.polymer-project.org/2.0/docs/browsers

**Comment by vedtam** [comment]
@arthurevans - yes, my bad. Thanks
