### ISSUE TITLE
The Arrays! are mutating. Unobserved!!!

### ISSUE THREAD

**Issue by retrocausal** [Polymer/polymer#4790]
**unless..**  shallow cloned post mutation
#### Live Demo
https://plnkr.co/edit/dmd4MN?p=info

#### Steps to Reproduce
 - Create two elements
-  two way bind them via an array of objects
- on both elements, have an `observer` defined for the array
- have a dummy logic to mutate the array on one of the elements
- mutate array in the logic, via available polymer mutation methods
- do not shallow clone after
- log changes to the array on the console via the observer
#### Expected Results
on successful mutation, the logs are on the console

#### Actual Results
No logs on mutation

### Browsers Affected

- [x ] Chrome
Untested on other browsers

### Versions
- Polymer: v2.0.2
- webcomponents: v1.0.4

**Note** the binding itself works just fine. However, the observers do not pick up the changes

**Comment by baocang** [comment]
See there: https://plnkr.co/edit/tgqAzrH9tja3dhdcmlJz?p=preview
docs there: https://www.polymer-project.org/2.0/docs/devguide/data-system#optional-mutable-data
and there https://www.polymer-project.org/2.0/docs/devguide/observers#array-observation

**Comment by baocang** [comment]
plnkr now work correct. I'm so sorry i't not saved correct before, I hate The GFW:(!!!.

**Comment by TimvdLippe** [comment]
This is actually working as intended, as documented [here](https://www.polymer-project.org/2.0/docs/devguide/observers#simple-observers)
> Simple observers only fire when the property itself changes. They don't fire on subproperty changes, or array mutation. If you need these changes, use a complex observer with a wildcard path, as described in Observe all changes related to a path.

You can listen to subproperty changes with the complex observer.
