### ISSUE TITLE
Should we consider to use !== rather then != 

### ISSUE THREAD

**Issue by AlphaWong** [Polymer/polymer#4792]
https://github.com/Polymer/polymer/blob/ca1ce19682b0003359090491d7e81a58d26b9a4a/lib/elements/dom-if.html#L160

Should we consider the following condition that 
```js
// true
'abc' != ['abc']

//false
'abc' !== ['abc']
```
when we would like to have a comparison.

Best,
Alpha

**Comment by kevinpschaaf** [comment]
The `if` property is boolean typed, and we accept truthy/falsy values.  So can you explicate why you think `'abc'` (truthy) and `['abc']` (truthy) should be considered a change for the `if` value and thus e.g. fire `dom-changed`?

**Comment by AlphaWong** [comment]
Deat Kevin,

Thanks for your review. I originally idea is using strict comparison to limit developer expectation.
live demo https://jsfiddle.net/dnfwypoa/2/
```js
const showDom = function showDom(flag) {
  if (flag == true) console.log('Dom show.');
  else console.log('Dom not show.');
}

const showDomStrict = function showDomStrict(flag) {
  if (flag === true) console.log('Dom show');
  else console.log('Dom not show.');
}

showDom(1);
// output : Dom show.
showDomStrict(1);
// output : Dom not show
```
However, thx for @web-padawan in https://github.com/Polymer/polymer/pull/4802#issuecomment-323744111 mentions that it may change the <dom-if> behavior.

My standpoint is that some developer may put 0 / 1 to <dom-if> as they think 0 / 1 and true / false are same.

This change can force them to use Boolean rather then 0 / 1.

**Comment by sorvell** [comment]
Yes, we cannot really consider this since it would be a breaking change, but I think the opinion is reasonable and there's a trade off here.
