### ISSUE TITLE
Arrays of multiple equal tabs are not handled separately

### ISSUE THREAD

**Issue by DrNiels** [Polymer/polymer#4793]
### Description
When I use multiple instances of the same object in a polymer project, the different instances seem to share its content.

#### Steps to Reproduce
1. Start with my-app example from here: https://www.polymer-project.org/2.0/start/toolbox/create-a-page
2. Let all tabs link to the same view, i.e. in my-app.html lines 100 - 109,
```
        <iron-pages
            selected="[[page]]"
            attr-for-selected="name"
            fallback-selection="view404"
            role="main">
          <my-view1 name="view1"></my-view1>
          <my-view1 name="view2"></my-view1>
          <my-view1 name="view3"></my-view1>
          <my-view404 name="view404"></my-view404>
        </iron-pages>
```
3. Add an editable array to my-view1:
```
<link rel="import" href="../bower_components/polymer/polymer-element.html">
<link rel="import" href="../bower_components/polymer/polymer.html">
<link rel="import" href="../bower_components/paper-button/paper-button.html">
<link rel="import" href="shared-styles.html">

<dom-module id="my-view1">
  <template>
    <style include="shared-styles">
      :host {
        display: block;

        padding: 10px;
      }
    </style>

    <template is="dom-repeat" id="repeat" items="[[items]]">
      <div>[[item]]</div>
    </template>

    <paper-button on-tap="changeElements">Change elements</paper-button>
  </template>

  <script>
    class MyView1 extends Polymer.Element {
      static get is() { return 'my-view1'; }

      static get properties() {
        return {
          items: {
            type: Array,
            value: ["a", "b", "c"]
          }
        }
      }

      changeElements() {
        this.splice('items', 1, 1);
        console.log(this.items);
      }

    }

    window.customElements.define(MyView1.is, MyView1);
  </script>
</dom-module>
```

#### Expected Results
Even though all tabs are initially equal, each should have its own copy of the array `data`. Thus, if I press _Change elements_ once on each tab, every tab should present the remaining array ["a", "c"]

#### Actual Results
Pressing _Change elements_ on one tab, switching to another tab, and pressing _Change elements_ there as well, leads to the array ["a"] as the changeElements() function is used on the array ["a", "c"], the modified array from the previous tab.

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Edge
- [untested] Safari 9
- [untested] Safari 8
- [untested] IE 11

### Versions

- Polymer: v2.0.2
- webcomponents: v1.0.3

**Comment by jsilvermist** [comment]
> #### Expected Results
> 
> Even though all tabs are initially equal, each should have its own copy of the array data. Thus, if I press Change elements once on each tab, every tab should present the remaining array ["a", "c"]

If you want each element to have it's own copy of the array, you need to define the initial value like:
```js
static get properties() {
  return {
    items: {
      type: Array,
      value: function() {
        return ["a", "b", "c"];
      }
    }
  }
}

```

When you return an array from a function each instance will get it's own array, if you set a static array the same array is used for every instance.

**Comment by arthurevans** [comment]
You can also set the default value in the constructor, like this:

```
constructor() {
  super();
  this.items = ["a", "b", "c"];
}
```

Many people prefer this, as it feels more idiomatic. But other people prefer to put all property-related configuration in the `properties` object.

**Comment by DrNiels** [comment]
It's working. Thanks a lot!
