### ISSUE TITLE
bower.json used to have an explicit "version" element in 1.x, but this is gone in 2.x

### ISSUE THREAD

**Issue by bartolom** [Polymer/polymer#4794]
### Description
bower.json used to have an explicit version in Polymer 1.x, but this is gone in Polymer 2.x

#### Live Demo
n/a

#### Steps to Reproduce
Look at  https://github.com/Polymer/polymer/blob/1.x/bower.json and you can see a ` "version": "1.9.3"`

Look at https://github.com/Polymer/polymer/blob/master/bower.json and no `"version"` element at the top

#### Expected Results
https://github.com/Polymer/polymer/blob/master/bower.json with `"version" : "2.0.2"`

the file https://github.com/Polymer/polymer/blob/master/package.json does have the  `"version" : "2.0.2"` information

#### Actual Results

https://github.com/Polymer/polymer/blob/master/bower.json and no `"version"` element at the top

### Browsers Affected
This does no effect browsers but build tools for instance the Java/JVM centric http://www.webjars.org/ is now prefixing the version with the git tag (?) so there is a `v2.0.2` there instead of a `2.0.2` which is problematic for transitive dependencies in Gradle

### Versions
- Polymer: v2.0.2

### PS
I'm a Java developer so I'm not sure if this is intended and has something to do with bower-webpack or other JavaScript build technology evolution. If it is intended please feel free to close this issue right away. It's just that all PolymerElements seem to only have bower.json files that are referencing their dependencies consistent.

 for instance [paper-input bowser.json](https://github.com/PolymerElements/paper-input/blob/master/bower.json)
`"iron-input": "PolymerElements/iron-input#1 - 2",`
`"polymer": "Polymer/polymer#1.9 - 2",`

**Comment by jorgecasar** [comment]
[Version property in bower.json](https://github.com/bower/spec/blob/master/json.md#version) was deprecated long time ago. Then, I guess this is not an issue.

**Comment by azakus** [comment]
We removed the version field from bower.json because it is a deprecated field, and so we could start using npm-focused tools to handle releases.

I'm not familiar with webjars.org, but bower handles `v2.0.2` and `2.0.2` identically, according to the [Semantic Versioning](http://semver.org) standard.
