### ISSUE TITLE
Firefox 57.0a1 (2017-08-21) & (2017-08-22) Fails to load Polymer sites

### ISSUE THREAD

**Issue by Anaerin** [Polymer/polymer#4804]
### Description

On loading of almost any polymer site (Youtube's New look, https://www.polymer-project.org/2.0/docs/browsers etc.), loading fails with one (or more) instance of the error:
```
TypeError: Polymer.DomModule.import is not a function
[Learn More]
data:(function()%7BPolymer.nar%3D%5B%5D%3Bvar%20d%3DPolymer.Settings.disableUpgradeEnabled%3BPolymer:1:44959
cssBuildTypeForModule
https://www.polymer-project.org/elements/pw-shell.html-2.js:1:44959
_prepStyles
https://www.polymer-project.org/elements/pw-shell.html-2.js:1:54069
_registerFeatures
https://www.polymer-project.org/elements/pw-shell.html-2.js:1:69008
registerCallback
https://www.polymer-project.org/elements/pw-shell.html.js:1:3854
c
https://www.polymer-project.org/elements/pw-shell.html.js:1:1646
window.Polymer
https://www.polymer-project.org/elements/pw-shell.html.js:1:1317
<anonymous>
https://www.polymer-project.org/elements/pw-shell.html-2.js:1:70130
<anonymous>
```

#### Steps to Reproduce

Visit any Polymer 2.0-based site in aforementioned FF versions. Enabling or disabling webcomponents using about:config makes no difference.

#### Expected Results

Site loads, as usual.

#### Actual Results

Background colour of the site is changed, nothing else happens.

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

Whatever versions Youtube and polymer-project.org/2.0/docs/ is using.

Also reported on Bugzilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1367205 and https://bugzilla.mozilla.org/show_bug.cgi?id=1392810

**Comment by azakus** [comment]
Sorry, can't reproduce this with Firefox 57.0a1 on Youtube like you referenced. Based on the [comments to the Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1392810#c8) you posted, it appears you may have a plugin that is breaking the site.
