### ISSUE TITLE
[3.0] Consider renaming polymer.js

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer#4805]
The file `/polymer.html` was named so for backwards compatibility with Polymer 1.0, so that hybrid elements could use the same import. We don't have this constraint with 3.0, and could rename `polymer.js` to `polymer-legacy.js`, which would allow us to create a new `polymer.js` with only modern exports.

**Comment by joeblew99** [comment]
Why break everyone that need to stick with polymer 1 - 2 for a fair while ?
Instead use a new name for polymer 3.0. maybe polymer 3.js

**Comment by arthurevans** [comment]
This change--if we make it--wouldn't affect 1.x or 2.x at all--they import an html file, not a js file. You'll need to change how you import polymer when you go from 2 to 3 whether or not we make this change.

**Comment by joeblew99** [comment]
ah i missed the .html and .js. Makes sense now. thanks @arthurevans

**Comment by justinfagnani** [comment]
If we choose to do this, we can do it one of two ways: Hard-code a filename remapping in polymer-modulizer, or add the ability to make a directive in a file to have modulizer rename it:

ie, in polymer-element.html:
```html
<!-- modulizer-rename: polymer.js -->
```

**Comment by bicknellr** [comment]
(Blocked on https://github.com/Polymer/polymer-modulizer/pull/354.)

**Comment by bicknellr** [comment]
#367 is merged.
