### ISSUE TITLE
Support non-shadow DOM elements in polymer 1.x

### ISSUE THREAD

**Issue by ergo** [Polymer/polymer#4812]
Polymer 2.0 allows us to do something like this, to attach template into light DOM:

> _attachDom(dom) {
  this.appendChild(dom);
}

It would be great if we had an API to allow this behavior in 1.x elements too.

**Comment by azakus** [comment]
You can somewhat do this by overriding `_createLocalRoot` in 1.x, but a lot of internal mechanisms are tied into this, so it really only works when you have enabled native shadow dom

Here's an example: http://jsbin.com/nironekoga/edit?html,output

However, at this point I don't think we'll be adding any _new_ features to the 1.x line.
