### ISSUE TITLE
Neon animations on NPM are not converted to modules

### ISSUE THREAD

**Issue by MarkJamesHoward** [Polymer/polymer#4814]
### Description
When using the paper-menu-button it fails to build in webpack as it relies on neon-animation and tries to pull in the below:

import '../neon-animation/animations/fade-in-animation.js';
import '../neon-animation/animations/fade-out-animation.js';

but they still are .HTML files in npm

### Versions
- Polymer: v3.0

**Comment by arthurevans** [comment]
This issue was moved to Polymer/polymer-modulizer#184
