### ISSUE TITLE
SSL sertificate for blog.polymer-project.org is expired 4 days ago

### ISSUE THREAD

**Issue by limonte** [Polymer/polymer#4816]
https://sslanalyzer.comodoca.com/?url=https%3A%2F%2Fblog.polymer-project.org%2F

![image](https://user-images.githubusercontent.com/6059356/29739618-c44acbda-8a4a-11e7-9b75-dd018f772bbd.png)

**Comment by limonte** [comment]
The SSL certificate for blog was expired the next day after Summit, looks like a :man_facepalming: to me :)

**Comment by TimvdLippe** [comment]
This has been fixed, thanks for the report!
