### ISSUE TITLE
Polymer 1.x with WebComponents 1.x

### ISSUE THREAD

**Issue by IntranetFactory** [Polymer/polymer#4817]
We currently maintain a library of 200+ Polymer components. These components are currently still on Polymer 1.x and we had scheduled a project to migrate to Polymer 2.x in Q4.

We appreciate getting early information about the future directions of Polymer 3. I think I completely understand the goals, priorities and motivation for the future plans. We also see most of Polymer 3 as a big step forward, but, unfortunately for us, just in the wrong direction. 

Polymer 1.x fits to our current needs, but there is one main issue: the lack of native web components and ShadowDom support. So we essentially  would need Polymer 1.x with WebComponents 1.x

We had a short internal discussion and didn’t find an obvious reason why it is not possible to migrate Polymer 1.x to WebComponents 1.x 

So we probably don’t start a migration to Polymer 2.x but consider to extend Polymer 1.x to use WebComponents 1.x

Is it correct to assume that the Polymer team has absolutely no interest supporting that?

I know that a lot of people will see that as a dumb decision. So no need to tell me that.

I just wonder if anybody else might be interested in combining Polymer 1.x with WebComponents 1.x

**Comment by LasaleFamine** [comment]
You can stil use an hybrid solution with Polymer 2, Web Components v1 and legacy Polymer 1.x syntax and methods. Check out the upgrade guide: https://www.polymer-project.org/2.0/docs/upgrade

**Comment by IntranetFactory** [comment]
@LasaleFamine  We schedule a migration project to 2.x - do you assume we planned a migration without reading the documentation?

I assume that if the migration to 2.x is as easy as suggested then at least the Polymer team would have upgraded their own sites. 

But Polymer.version of https://www.polymer-project.org/ is "1.9.3" and https://www.webcomponents.org/ shows also "1.9.3"

**Comment by LasaleFamine** [comment]
But all the Polymer Elements have been upgraded to `2.x` version, did you check also  https://github.com/PolymerElements?

**Comment by web-padawan** [comment]
From my point of view, the only tricky part about migration to 2.0 is differential serving. It's better not to transpile native class syntax for Chrome and Safari to avoid including `custom-elements-es5-adapter.js`, but we have to tranmspile for Safari 9 / IE 11.

Another reason not to migrate to 2.0 is the fact that lots of elements like `paper-input` contain legacy code. In our team, we realize that if we started migration to 2.0 now, we'd finish by the time of 3.0 release, so we are likely to  skip 2.0 at all. I wonder if some of [Google products](https://github.com/abdonrd/PolymerProjects#google-products) consider doing the same BTW.

**Comment by IntranetFactory** [comment]
We now found what causes all the trouble - some browser vendor seems to know better what we need.

> It's not possible to use custom elements without ES6 classes. That was a design decision necessary to
> achieve consensus at the January face-to-face meeting.

https://github.com/w3c/webcomponents/issues/587
