### ISSUE TITLE
Polymer 3 string templates not recognizes dom if

### ISSUE THREAD

**Issue by guzmanpaniagua** [Polymer/polymer#4819]
### Description
I was trying 3.0-preview version in codepen, 
https://codepen.io/guzmanator/pen/rzqPGZ

it works fine with the basic example  described here
https://www.polymer-project.org/blog/2017-08-23-hands-on-30-preview

But when try to use dom-if inside the template like this

~~~ 
  static get template() {
    return `<template is="dom-if" if="[[itsHidden]]">
       this content must be show
     </template>`
~~~ 

the text did not show, i try the same aproach in polymer 2.0 and works ok 

#### Live Demo
polymer 3 version  with bug 
https://codepen.io/guzmanator/pen/prxYrY?editors=1010

polymer 2 versions works ok 
https://codepen.io/guzmanator/pen/YxJgLx

#### Steps to Reproduce
1) create an element 
2) ad a string template as html content
3) add a boolean property with true value
4) add 2 dom-if one with the  propertie  other with the same property but with ! before
5) epect to see only one of the dom if contents
6) did not see any of them

#### Expected Results
the dom-if on condition ok must be show/hidden

#### Actual Results
the content of boh dom if are not visible

### Browsers Affected
- [v ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
Polymer 3 preview

note: i try dom-repeat too but did not get the work too

note2: ES6 modules are only supported in Chrome, from 61 onwards, they also work in older versions, but you’ll have to enable the Experimental Web Platform flag in chrome:flags

**Comment by Westbrook** [comment]
@guzmanpaniagua looks like you'll need to add the following import for that to work:

```
import {DomIf as DomIf} from 'https://cdn.rawgit.com/Polymer/polymer/3.0-preview/lib/elements/dom-if.js';
```

**Comment by guzmanpaniagua** [comment]
It woks, thanks, the isue can be close.

It was hard find working examples 8)

**Comment by TimvdLippe** [comment]
Glad it has been fixed! Polymer 3 is very early preview, so docs included are still in the works. Expect more information rolling out over the coming months :)
