### ISSUE TITLE
 problem with polymer-cli in ubuntu please give me solution 

### ISSUE THREAD

**Issue by ennemli** [Polymer/polymer#4827]
----------------- START -----------------
muhssin@Muhssin:~$ sudo npm install -g polymer-cli
npm **WARN** deprecated babel-preset-babili@0.0.10: babili has been renamed to babel-minify. Please update to babel-preset-minify
npm **WARN** deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
npm **WARN** deprecated @types/assert@0.0.29: See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12826
/usr/bin/polymer -> /usr/lib/node_modules/polymer-cli/bin/polymer.js

> wd@1.4.0 install /usr/lib/node_modules/polymer-cli/node_modules/wd
> node scripts/build-browser-scripts

/usr/lib/node_modules/polymer-cli/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/polymer-cli/node_modules/wd/build'
    at Object.fs.mkdirSync (fs.js:891:18)
    at sync (/usr/lib/node_modules/polymer-cli/node_modules/mkdirp/index.js:71:13)
    at Object.<anonymous> (/usr/lib/node_modules/polymer-cli/node_modules/wd/scripts/build-browser-scripts.js:6:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
npm **ERR!** code ELIFECYCLE
npm **ERR!** errno 1
npm **ERR!** wd@1.4.0 install: `node scripts/build-browser-scripts`
npm **ERR!** Exit status 1
npm **ERR!** 
npm **ERR!** Failed at the wd@1.4.0 install script.
npm **ERR!** This is probably not a problem with npm. There is likely additional logging output above.

npm **ERR!** A complete log of this run can be found in:
npm **ERR!**     /home/muhssin/.npm/_logs/2017-09-07T01_34_20_780Z-debug.log
muhssin@Muhssin:~$ polymer
polymer: command not found
muhssin@Muhssin:~$ polymer init
polymer: command not found
----------------- END -----------------

**Comment by guzmanpaniagua** [comment]
The error seems to be 
Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/polymer-cli/node_modules/wd/build'

in this isue of polymer-cli is explained something similar
https://github.com/Polymer/polymer-cli/issues/832

you colud try to install the cli in nvm as local user and avoid this kind of permisions errors

**Comment by AlphaWong** [comment]
I use https://github.com/tj/n to be my node version manager

**Comment by ennemli** [comment]
this problem does  not solved with me
but i'm using this command for solved  
**muhssin@muhssin:~$ ~/node_modules/polymer-cli/bin/polymer.js**

**Comment by TimvdLippe** [comment]
Glad your issue was resolved! Closing it for now. For those also encountering this issue, please check out https://github.com/Polymer/polymer-cli/issues/832#issuecomment-320238339
