### ISSUE TITLE
template is="dom-repeat" leaves a non hidden <dom-repeat> element in the dom, screwing up css grid layout

### ISSUE THREAD

**Issue by akc42** [Polymer/polymer#4832]
I am trying to build complex table using dom repeat create the table cells.  Unfortunately a `<dom-repeat>` element is left in the dom which creates one more cell in the table.

I can work around the problem by using css
```
dom-repeat {
  display: none;
}
```
But it would be better if I didn't have to

Polymer version 2.0.2

**Comment by TimvdLippe** [comment]
Yes, this should be fixed with #4821 and part of the next release.
