### ISSUE TITLE
Live-templating in Polymer2.0 ?

### ISSUE THREAD

**Issue by vdegenne** [Polymer/polymer#4843]
I'd like to share something I need to do for my application : live-templating.
Here is a fictive code to show you what I try to achieve : 

```html
<script>
/***************
 * X-A ELEMENT
 * After inserted in the dom-tree,
 * will try to live add <x-b> in its shadow-dom.
 * (after one second)
 **********************/
customElements.define(
   'x-a',

   class extends Polymer.Element {

     static get properties() { return {
       testObject: {
         type: Object,
         value: function () { return { foo: 12 } }
       }
     }}

     static get template() { return `
         <div id=container></div>
     `}

     connectedCallback() {
       super.connectedCallback();

       setTimeout(_ => {
         this.$.container.innerHTML =
            '<x-b from-a=[[testObject]]></x-b>'; /* won't work */

         /**
          * WORKAROUND

          const xb = new XB();
          xb.fromA = this.testObject;
          this.$.container.appendChild(xb);

         */
       }, 1000)
     }
   }
)


/***************
 * X-B ELEMENT
 * Added in <x-a> element's container.
 * Expecting templating to be processed on the fly.
 ***************/
class XB extends Polymer.Element {

  static get properties() { return {
    fromA: Object
  }}

  static get template() { return `
      <p>value live shared from &lt;x-a&gt; : [[fromA.foo]]</p>
  `}
}

customElements.define('x-b', XB);
</script>


<x-a></x-a>
```

The problem with the workaround in the code above is that it doesn't take advantage of Polymer bindings, so if I use `set` method on `<x-a>` element, `<x-b>` won't get notified (and the data in the view won't update, unless `notify` is called manually).

I know there are some solution like using `<dom-repeat>` but my application is dealing with large amount of data (back and from the server) and I need to trigger the garbage-collector as much as possible with the data, but `<dom-repeat>` somehow keeps objects internally, then my application after a while is taking too much memory (smartphone users won't like that).

I guess Polymer2.0 is trying to keep light-weight and implementing complex and size cost solutions is maybe out of the team, but the fact is I needed to do that. Or could I be missing something ?
If I am right, are there some chance this mechanism will get implemented in future Polymer releases (3.0) ?

**Comment by TimvdLippe** [comment]
Instead of updating the innerhtml in the timeout, it would be better to wrap it in a dom-if and then in the timeout set the condition. That way the content is inert, but the bindings still parsed by Polymer.

**Comment by TimvdLippe** [comment]
I am closing this issue, as this is not something we are going to actively going to pursue. Primarily based on the performance concerns of these dynamic bindings. However, if you would like to achieve this behavior tailored to your needs, take a look at [`_addTemplatePropertyEffect`](https://www.polymer-project.org/2.0/docs/api/elements/Polymer.Element#method-_addTemplatePropertyEffect).
