### ISSUE TITLE
Polymer 2.x. Firefox/Edge. Adding style element to shadow dom leaks to main document.

### ISSUE THREAD

**Issue by lycandroid** [Polymer/polymer#4844]
Hi, 

Using Polymer 2.x, I have an apparent problem that if I have a custom element which appends an element to the custom element's local dom and the element being appended contains a <style> block, then that style is leaked to the main document when running firefox or edge, but is fine in chrome.

For example:

```
<!DOCTYPE html>
<html>
<head>
  <base href="https://polygit.org/polymer+:master/webcomponents+:master/components/">
  <script src="webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="polymer/polymer.html">
</head>
<body>
  Click Test and this text will go red in firefox/edge<br>
  
  <my-element>
  </my-element>
  
  <dom-module id="my-element">
    <template>
      <button on-click="handleClick">Test</button>
      <div id="wrapper"></div>
    </template>
    <script>
    HTMLImports.whenReady(function() {
      class MyElement extends Polymer.Element {
        static get is() { return 'my-element' }
          
        handleClick() {
          var e = document.createElement('style');
          e.textContent = "* {color: red}";
          this.$.wrapper.appendChild(e);
        }
      }
      
      customElements.define(MyElement.is, MyElement);
    });
    </script>
  </dom-module>
</body>
</html>
```
Live demo: http://jsbin.com/tizazadebe/edit

The ultimate aim of this element is to allow (trusted) html pages to be embedded within the main document which themselves contain <style> blocks.

**Comment by web-padawan** [comment]
Have a look on how this is achieved by [vaadin-themable-mixin](https://github.com/vaadin/vaadin-themable-mixin/blob/master/vaadin-themable-mixin.html#L41) - it looks like style tag should be added into template content (which is document fragment node), not into the element node.

**Comment by lycandroid** [comment]
I'm not sure.  Difficult for me to tell what vaadin-themable-mixin is doing, but I agree it is adding to template content rather than directly to an element node.

However, if I change it to use a dom-if template e..g:

```
  <dom-module id="my-element">
    <template>
      <button on-click="handleClick">Test</button>
      <template id="wrapper" is="dom-if" if="[[go]]">
<style>
*{color:red}
</style>
      </template>
    </template>
...
```

and then set the go property to true
```
        handleClick() {
          this.go = true;
        }
```
which re-stamps the dom-if template then I see the same effect.

I'm fairly new to polymer so I'm quite prepared to be told I'm doing it wrong or am doing something invalid.  However, if I see something that works in chrome but not in firefox, and that what I'm doing is not entirely unreasonable, then I would tend to believe this is a problem in the polyfill implementation.

**Comment by lycandroid** [comment]
FWIW, in my particular case (allow trusted html pages to be embedded within the main document) and in light of current ShadyCSS limitation I intend to impose a standard on how those trusted pages are written such that <style> must use appropriately scoped selectors that target just the page content.

To this end I plan to provide a custom element that purely returns a page unique id and allow for that to be used as the id of the containing element, and therefore for styles to use that id selector e.g. such a page might look like this:

```
<dom-bind>
  <template>
    <my-uuid uuid="{{uuid}}"></my-uuid>

    <style>
    #[[uuid]] > * {color:red}
    </style>

    <div id="[[uuid]]">
      <div>The page content</div>
    </div>

  </template>
</dom-bind>
```

This may all be a waste of time of course if firefox/edge add full support for shadow dom in the meantime.

**Comment by TimvdLippe** [comment]
@lycandroid Please note that bindings in styles and scripts are incorrectly working now and this bug will be fixed a future release.
