### ISSUE TITLE
JSCompiler_renameProperty in boot.js

### ISSUE THREAD

**Issue by fsx950223** [Polymer/polymer#4845]
### Description

What is the effect of this method?
### Versions

- Polymer: 3.0.0

**Comment by TimvdLippe** [comment]
It is used in Closure Compiler to make sure property renames in an object are safe when using advanced mode. For more information you can check out https://github.com/google/closure-compiler/blob/f541d7e7ae06d0e4785ff2436eeac922d3efd31f/src/com/google/javascript/jscomp/RenameProperties.java#L42-L64
