### ISSUE TITLE
Setting Passive Touch Gestures in index.html does not work

### ISSUE THREAD

**Issue by bennypowers** [Polymer/polymer#4847]
### Description
adding the following line to index.html before loading `<my-app>` does not set Polymer.passiveTouchGestures = true. Violation messages appear in console and `Polymer.passiveTouchGestures === false`;
```js
Polymer.setPassiveTouchGestures(true);
``` 

#### Live Demo

http://jsbin.com/mehasat/edit?html,console,output

#### Steps to Reproduce

1. Generate PSK app
2. Add script tag in index.html with `Polymer.setPassiveTouchGestures(true)` to document.head, after or before `webcomponents-loader.js`
3. `console.log(Polymer.passiveTouchGestures)`

#### Expected Results
Polymer.passiveTouchGestures should be true, no scrolling violation messages should appear in chrome console.

#### Actual Results
Polymer.passiveTouchGestures is false, Scrolling violation messages appear in chrome console.

### Browsers Affected

- [x] Chrome

### Versions

- Polymer: v2.1.0
- webcomponents: v1.0.2

**Comment by jsilvermist** [comment]
@bennypowers You're trying to call a `Polymer` method before actually importing the library, it works fine if you just move the `script` down below the `Polymer` import.

http://jsbin.com/yubibedefu/1/edit?html,console,output

**Comment by bennypowers** [comment]
*facepalm*

Ok yeah that works, but i still get several passive scrolling violation messages.

As well, setting `Polymer.passiveTouchGestures = true` in head doesn't work, but I assume that's intentional

**Comment by TimvdLippe** [comment]
@azakus could you take a look at this report?

**Comment by azakus** [comment]
@bennypowers do you have a reproduction that triggers the violation? I couldn't get a violation with @jsilvermist's jsbin.

**Comment by bennypowers** [comment]
@azakus It seems not. If I find i'm getting these warnings again, will re open.
Thank you!
