### ISSUE TITLE
this.$ returns undefined in polymer 2.x

### ISSUE THREAD

**Issue by paladox** [Polymer/polymer#4854]
### Description

Hi, when i am trying to update to polymer 2.x but keep using backwords compat to make the upgrade as easy as possible, this.$ is returning undefined in ready().

See https://gerrit-review.googlesource.com/?polygerrit=0#/c/gerrit/+/128730/6/polygerrit-ui/app/elements/gr-app.js

line 87

this.$.router.start(); is returning undefined.

Reading online shows you have to do super.ready() but you carn't do that if it is not class +
closure compiler fails to build elements that use classes and it fails with super.ready() too.

#### Live Demo

http://jsbin.com/luhaxab/1/edit

#### Steps to Reproduce
Run https://gerrit-review.googlesource.com/?polygerrit=0#/c/gerrit/+/128730/6/

#### Expected Results

It to not throw an undefined.

#### Actual Results

It throws an undefined, thus preventing the app from initialising.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [x] Safari 11
- [x] Safari 10
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v2.1.0
- webcomponents: v1.0.13

**Comment by ernsheong** [comment]
Where is your `.$` refers to an element with ID in the template.

**Comment by paladox** [comment]
Oh, it is located in gr-app.html, inside <template>

<gr-router id="router"></gr-router>

**Comment by paladox** [comment]
It seems that i carn't see the dom-module in the develeper tools on chrome, ie i carn't see anything under <gr-app id="app"></gr-app>

**Comment by ernsheong** [comment]
Here's a few things worth trying:
1) Line 22 in https://gerrit-review.googlesource.com/?polygerrit=0#/c/gerrit/+/128730/6/polygerrit-ui/app/elements/gr-app.js might be messing with `ready()`
2) Lines 19-21 in https://gerrit-review.googlesource.com/?polygerrit=0#/c/gerrit/+/128730/6/polygerrit-ui/app/elements/gr-app.html not sure if that is relevant anymore.

Otherwise, you should be able to figure this out with a second pair of eyes next to ya 👍

**Comment by paladox** [comment]
Ah thanks. I have located the issue. If i switch on shadydom then it breaks the whole thing even though it was the default in polymer 1.x. I have tracked down the problem to polygerrit-ui/app/elements/shared/gr-js-api-interface/gr-public-js-api.js

though i haven't figured out which part in there is breaking it so that the polymer elements break without causing any warnnings in the console (except from js)

**Comment by paladox** [comment]
I found the problem code, it's

Plugin._sharedAPIElement = document.createElement('gr-js-api-interface');

and

  Gerrit._pluginInstalled = function() {
    Gerrit._setPluginsCount(Gerrit._pluginsPending - 1);
  };

**Comment by ernsheong** [comment]
Sounds like it's an internal thing, and not a Polymer issue. Close it?

**Comment by paladox** [comment]
Yep.
