### ISSUE TITLE
tyle\

### ISSUE THREAD

**Issue by adrysn** [Polymer/polymer#4857]
#### Live Demo

http://jsbin.com/luhaxab/1/edit

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: vX.X.X
- webcomponents: vX.X.X

**Comment by vdegenne** [comment]
What exactly is the problem ? Plus you have to insert the `style` element inside the `template`. Please if it is about asking a question about **why won't my code work ? I am a newbie, please help** Consider using *스택 오버플로* good luck.

**Comment by adrysn** [comment]
Oh my god. I was just reading some issues and comments, and I have no idea how I opened this issue here. I didn’t intend to write something. Perhaps I mis-typed some keys.

Really sorry to bother you.

**Comment by jfrazzano** [comment]
In counter to “that", as a newbie in 15, I spent months ashamed to ask a question.  When i asked I got “iq-fat-shamed” for, in retrospect, poor wording.  Thank goodness a senior person took pity on me (Thank you again, Arthur), was patient, and  showed me where code was “janky” and where the best practice/just plain instructions for complex builds could be found.  As a result of this kindness, I learned at an exponential rate, and even with the loss work from 15 and 16 in the move from 1 to 3, I garnered a foundation that allowed me to build my own mini-libraries to finish my work, an then d wait for the chance again rejoin this community,  as Polymer 3 stabilizes. Looks stable. so….

to your please… show me your code.  tell me what you want it to do.  I will give you all the time and effort i have.  Might be off… but 

its the least i can do considering what you all have done for me and the community.


post a code pen, if you have something to show

Sincerely, 

Jason

**Comment by adrysn** [comment]
@jfrazzano I really appreciate your sincere and warm reply for my mistake. Opening this issue was really my mistake. I was reading some usage and examples about style sharing across multiple custom elements as well as certain threads and comments here. I have no idea how I posted this issue, and I just feel sorry for bothering anyone who read my pointless post.

But, it is right that I'm relatively newbie in this field, and I will remember your advice and encouragement when I write real questions. Thanks!
