### ISSUE TITLE
modify the example in to a complate examples

### ISSUE THREAD

**Issue by spyhole** [Polymer/polymer#4858]
with firevbase??

**Comment by TimvdLippe** [comment]
There are multiple options, but if you are looking for some more thorough examples, do check out the codelabs: https://codelabs.developers.google.com/ In the search bar, search for Polymer. One good example codelab is https://codelabs.developers.google.com/codelabs/polymer-firebase-pwa/index.html?index=..%2F..%2Findex#0 which includes Firebase to build a PWA.
