### ISSUE TITLE
Polymer 1.x shared-styles are working in Chrome but not in Firefox

### ISSUE THREAD

**Issue by Boscop** [Polymer/polymer#4862]
I have this in `shared-styles.html`:
```html
<dom-module id="shared-styles">
  <template>
    <style>
    ...
    </style>
  </template>
</dom-module>
```
And then I use it like this:
```html
<dom-module id="foo-view">
  <template>
    <style include="shared-styles">
      ...
    </style>
  </template>
  <script src="view.js"></script>
</dom-module>
```
In Chrome my shared styles work fine but in Firefox they seem to be completely ignored.
Why?

I'd really appreciate any help on this.
(Btw, I already tried googling and asking on Slack but found no answers.)

---
```json
{
  "name": "foobar",
  "private": true,
  "dependencies": {
    "font-roboto": "StartPolymer/font-empty#1.1.0",
    "iron-flex-layout": "PolymerElements/iron-flex-layout#1.2.3",
    "iron-localstorage": "PolymerElements/iron-localstorage#1.0.5",
    "iron-pages": "PolymerElements/iron-pages#1.0.7",
    "iron-selector": "PolymerElements/iron-selector#1.2.2",
    "page": "visionmedia/page.js#1.6.4",
    "paper-drawer-panel": "PolymerElements/paper-drawer-panel#1.0.6",
    "paper-icon-button": "PolymerElements/paper-icon-button#^1.1.6",
    "paper-input": "PolymerElements/paper-input#1.1.6",
    "paper-item": "PolymerElements/paper-item#1.1.3",
    "paper-material": "PolymerElements/paper-material#1.0.6",
    "paper-menu": "PolymerElements/paper-menu#1.2.2",
    "paper-scroll-header-panel": "PolymerElements/paper-scroll-header-panel#1.0.15",
    "paper-styles": "PolymerElements/paper-styles#1.1.3",
    "paper-swatch-picker": "PolymerElements/paper-swatch-picker#master",
    "paper-toast": "PolymerElements/paper-toast#1.1.3",
    "paper-toggle-button": "PolymerElements/paper-toggle-button#1.1.1",
    "paper-toolbar": "PolymerElements/paper-toolbar#1.1.4",
    "platinum-sw": "PolymerElements/platinum-sw#1.2.3",
    "polymer": "Polymer/polymer#1.3.0",
    "start-google-analytics-tracker": "StartPolymer/start-google-analytics-tracker#1.1.0",
    "geo-location": "ebidel/geo-location#^1.0.6",
    "google-map": "GoogleWebComponents/google-map#^1.2.0",
    "paper-input-location": "Koada-os/paper-input-location#^2.0.0",
    "paper-button": "PolymerElements/paper-button#^1.0.15",
    "iron-ajax": "PolymerElements/iron-ajax#^1.4.4",
    "iron-form": "PolymerElements/iron-form#^1.1.4",
    "paper-dropdown-menu": "PolymerElements/paper-dropdown-menu#^1.5.1",
    "iron-dropdown": "PolymerElements/iron-dropdown#^1.5.6",
    "iron-image": "PolymerElements/iron-image#^1.2.6",
    "paper-checkbox": "PolymerElements/paper-checkbox#^2.0.0"
  },
  "devDependencies": {
    "web-component-tester": "4.2.0"
  },
  "ignore": [],
  "resolutions": {
    "polymer": "^1.5.0",
    "iron-selector": "^1.5.2",
    "paper-input": "^1.1.23",
    "paper-styles": "^1.1.4",
    "paper-icon-button": "^1.1.6"
  }
}
```

**Comment by TimvdLippe** [comment]
Could you make sure you are loading the latest version of Polymer (v1.10.1 https://github.com/Polymer/polymer/releases/tag/v1.10.1)? Your bower.json references 1.5.0 instead

**Comment by Boscop** [comment]
How can I safely update one dependency so that it also works for all other dependencies?

**Comment by TimvdLippe** [comment]
You should be able to update Polymer to 1.10.1 without any issues as it is fully backwards-compatible.

**Comment by Boscop** [comment]
I did [`bower update -S`](http://pastebin.centos.org/326236/07111544/) but it didn't update polymer.
[This is the bower.json file afterwards.](http://pastebin.centos.org/326241/71116031/)
It seems to have just added webcomponentsjs..
Does that mean no newer version was compatible with all deps?

**Comment by TimvdLippe** [comment]
Remove Polymer from the resolutions field and try again. That should force it to update

**Comment by Boscop** [comment]
I did that and it asked me to choose a polymer version, [I chose the highest one that resolves to 1.10.1](http://pastebin.centos.org/326271/15071126/) but it only [updated to 1.7.1](http://pastebin.centos.org/326276/07112708/), why?

And why didn't it update any of the other deps?

**Comment by Boscop** [comment]
It's still not working in FF, any idea why?

**Comment by TimvdLippe** [comment]
I have encountered this issue myself, but I have to get a solid reproduction case first. Could you create a JSBin that shows the issue?

**Comment by TimvdLippe** [comment]
Thanks for the issue.  Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  Please fill out as many fields in the issue template as possible, and be sure to include a live reproduction so that the team can debug or understand your issue.  You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions.  Thank you!
