### ISSUE TITLE
pwa polymer templates in visual studio 2017

### ISSUE THREAD

**Issue by touseefbsb** [Polymer/polymer#4868]
A suggestion I wanted to provide to polymer team. I am not sure who exactly will be responsible to create a polymer template for visual studio 2017. So I have requested visual studio team as well for this and now I am requesting the feature here to the polymer team.

Polymer and web components play main role in creating awesome progressive web apps. 
Visual Studio 2017 should integrate with Polymer to give it the templates already present in polymer-cli. 
Also ASP.NET CORE 2.0 already has templates with angular and react, polymer should also have templates with asp.net core 2 with pwa stuff included like service worker e.t.c. 

**Reason to use VS 2017 templates**
1. easy deployment to azure and other services
2. easy integration with multiple types of identity providers including **Azure AD B2C** which supports email sign up, and all social sign ups along with password reset easily.
3. awesome intellisense and brilliant development experience.

**Reason to use polymer**
1. Future of web development is **web components** and polymer is probably best tool to make them.
2. polymer also provides brilliant support for pwas.
3. Those who dont want to use heavy frameworks like angular, vue and react e.t.c, should use polymer because it is simpler and is able to give us a perfect pwa which can run on probably every device possible.

**So if we combine polymer with VS 2017 it will be a perfect environment for future of web development.**

P.S : here is the link of my request on visual studio user voice, please go to this link and vote the idea if you like it.

https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/31776661-pwa-template-for-polymer-2-and-3-with-asp-net-core

Thanks.

**Comment by azakus** [comment]
This is more of a tooling suggestion, kicking to @justinfagnani

**Comment by Inrego** [comment]
I have made a project template for private use. It's just a simple ASP.NET Core 2.0 project with Polymer.
[PolymerTemplate.zip](https://github.com/Polymer/polymer/files/1722423/PolymerTemplate.zip)
