### ISSUE TITLE
Localhost set up Polymer 1.0

### ISSUE THREAD

**Issue by dev-ads** [Polymer/polymer#4869]
I am trying to set up polymer 1.0 on my Apple Mac.

I have been able to install Git, Node JS, Atom and Bower fine but I am not getting anything on any local host.

I have followed instructions on Polymer Project website but when running the polymer serve command in terminal in project directory I get nothing at localhost:8080/components/icon-toggle/demo/

I have attached the response I get from the polymer serve command in terminal. I have also tried to navigate to the link shown in the image but get a page not found error.

Quite new to this so any help is largely appreciated.
![screenshot 2017-10-06 14 43 56](https://user-images.githubusercontent.com/32572953/31280666-024e5c06-aaa5-11e7-969f-8e231decc7bb.png)

**Comment by web-padawan** [comment]
What kind of project do you have? See docs for [element project](https://github.com/Polymer/polymer/issues/4679#issuecomment-333187751) and [application project](https://www.polymer-project.org/2.0/docs/tools/create-app-polymer-cli).

**Comment by dev-ads** [comment]
I would like to set up an elements project I believe. I need to use polymer 1.0

The polymer programming I have done so far has been using HTML files and importing bower components at the start of each document then calling an instance of that component.

**Comment by vaffonso** [comment]
Probably port 8080 is already in use, so polymer serve is using 8081.
Try hitting localhost:8081

**Comment by dev-ads** [comment]
Returns "not found"

**Comment by dev-ads** [comment]
update: If I navigate to 
http://localhost:8081/polymer-first-elements/demo/index.html
I get a white screen with some bower element errors (see attachment)
I'm fairly sure I have installed bower correctly (see attachment)
Again all help appareciated thank you 

<img width="557" alt="screenshot 2017-10-06 17 33 22" src="https://user-images.githubusercontent.com/32572953/31288369-91525940-aabc-11e7-9710-bfa8ec651d89.png">
<img width="625" alt="screenshot 2017-10-06 17 34 43" src="https://user-images.githubusercontent.com/32572953/31288389-a7cfef5c-aabc-11e7-90a4-c5f0ea44eac1.png">

**Comment by vaffonso** [comment]
Looks like port 8081 since you're having errors
If you're following google codelabs then you have a wrong path
localhost:8081/components/icon-toggle/demo/
as per this doc says
https://www.polymer-project.org/1.0/docs/start/reusableelements.html#local-dependencies

**Comment by dev-ads** [comment]
That produces the right page. Looks like Polymer serve is working now thank you all!
What is the best way of setting up a local host to create my own custom elements? Previously I have run a run.bat file with some Go programming code to set up a local host with an index.html file

Can I set something up that will work in a similar way?

Thanks again

**Comment by vaffonso** [comment]
If I get it right, you can follow the same structure, in components folder, to build your own component. Then you can publish or wrap it for your own use.
https://www.webcomponents.org/publish

**Comment by azakus** [comment]
It sounds like you got the help you were looking for so I'm going to close this issue.
