### ISSUE TITLE
IE11 error w/ dom-repeat as slot content

### ISSUE THREAD

**Issue by robrez** [Polymer/polymer#4878]
### Description
Pre-Conditions
- IE11
- Polymer2 project built using the `es5-bundled` preset

An error is raised when the slot content of a custom element is a `dom-repeat` _and_ the dom-repeat's items array is changed. This maybe an caused ultimately by dom-api polyfill...

- A dom mutation error (NoModificationAllowedError) was triggerd in dom-repeat's detachInstances function https://github.com/Polymer/polymer/blob/master/lib/elements/dom-repeat.html#L560
- The error is caught, rethrown here https://github.com/Polymer/polymer/blob/master/lib/utils/async.html#L34

__The error can be avoided__ if the dom-repeat is wrapped in a div and the div is used as the slot content eg:
```
  <!-- error -->
  <x-slot>
    <template is="dom-repeat" items="[[data]]"></template>
  </x-slot>

  <!-- NO error -->
  <x-slot>
    <div>
      <template is="dom-repeat" items="[[data]]"></template>
     </div>
  </x-slot>
```

#### Live Demo
http://jsbin.com/zasusaqode/edit?html,output

#### Steps to Reproduce
1. Create an element that accepts slot content
2. Use a dom-repeat for the slot content
3. Change the dom-repeat's items array
4. Use ie11

#### Expected Results
Items are rendered without error

#### Actual Results
Rendering generates an error

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [X] IE 11
_Only tested chrome and ie_

### Versions

- Polymer: v2.1.1
- webcomponents: v1.0.14
- shadycss: v1.0.6
- polymer-cli: v1.5.4
- os: windows 7 pro x64

**Comment by azakus** [comment]
Probably a ShadyDOM issue
