### ISSUE TITLE
Work around deprecation notice for custom styles in HTML Imports

### ISSUE THREAD

**Issue by dfreedm** [Polymer/polymer#4879]
The deprecation notice for styes in HTML Import documents will print before `<custom-style>` and `<style is="custom-style">` have the opportunity to move styles into the main document (#4679).

### Approaches
- Write an explicit `type` on the style that can be removed when the style moves to the main document
- Add a script to add the `type` to a style in the HTML Import that can be removed when moved to the main document

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

**Comment by baocang** [comment]
Can just move style into template?
<custom-style>
    <template>
        <style></style>
    </template>
</custom-style>
