### ISSUE TITLE
Swipeable Tabs

### ISSUE THREAD

**Issue by jonathanamartin** [Polymer/polymer#4887]
Small poke regarding this question.

https://stackoverflow.com/questions/46773611/swipeable-tabs-with-polymer-js-2

**Comment by TimvdLippe** [comment]
We have no plans to ship such a ready-made component. However, you should be able to combine `<paper-tabs>` and have a custom horizontal scroll listener on your main content to be able to invoke `selectNext()` or `selectPrevious()` to swipe respectively right or left.
