### ISSUE TITLE
Polymer 2 template works with Chrome but not Firefox

### ISSUE THREAD

**Issue by gechols** [Polymer/polymer#4889]
### Description
Custom 'collection-list' component works reliably with Chrome but fails much of the time with Firefox. It seems to work better on a reload of the page in Firefox, but not consistently.

'collection-list' is a subclass of another web component 'table-element' that creates a dynamic table-like display of rows and columns. The table-element supports reordering of columns, sorting, and filtering. The 'collection-list' just populates the 'table-element' with a specific set of data representing a bunch of record collections.

#### Live Demo
https://www.familysearch.org/frontier/search-artifact/collection/list
Sorry I don't have a jsfiddle or something more simple for this.

#### Steps to Reproduce
Load the page in Chrome. Things look just fine - the collection list gets rendered and displayed.
Load the page in Firefox. Often the collection list fails to display its contents, though the row headers get displayed fine. It seems that a race condition exists because if you reload enough times it gets displayed eventually.

#### Expected Results
The collection list should display consistently in Firefox as it does in Chrome.

#### Actual Results
Either the contents of the rows don't get rendered into the DOM, or I have seen times when the content is rendered but is marked as display:none, as if the template polyfill isn't done rendering when something goes wrong and the content doesn't get displayed.

### Browsers Affected

- [ ] Chrome - works fine
- [X] Firefox
- [ ] Edge - untested
- [ ] Safari 9 - works fine
- [ ] Safari 8 - untested
- [ ] IE 11 - untested

### Versions

- Polymer: v2.1.1
- webcomponents: v1.0.14

**Comment by web-padawan** [comment]
@gechols element-specific issues should not be submitted to the core library issue tracker.

Please provide some code used by the `collections-list` element so the community members could look into it and maybe help. I'd recommend asking such questions in the Slack channel BTW.

**Comment by gechols** [comment]
I'll post this in the Slack channel instead.
