### ISSUE TITLE
Publish polymer 1.x on npm

### ISSUE THREAD

**Issue by paladox** [Polymer/polymer#4895]
Hi, please could polymer be published on npm for 1.x too?

the old versions were published but not any newer 1.x releases.

**Comment by TimvdLippe** [comment]
Per #326 we will be moving to the npm ecosystem. However, for maintainability reasons as well as incompatibility with the HTML import system, Polymer 3 will be available on npm. For more information about this new version, please check out https://www.youtube.com/watch?v=JH6jEcLxJEI which contains a lot more information.

As migrating Polymer 1 to npm would be extremely time-consuming in conjunction with various compatibility issues, we will not be publishing a new version of Polymer 1 on npm. You can try out the latest pre-releases of Polymer 3 elements on npm right now under the `@polymer` scope: https://www.npmjs.com/search?q=%40polymer
