### ISSUE TITLE
Object.create in utils/mixin.html may cause a problem?

### ISSUE THREAD

**Issue by YingshanDeng** [Polymer/polymer#4896]
@azakus Hello! When I read the code about `Polymer.dedupingMixin` in `utils/mixin.html`, I found that the `Object.create` may cause a problem.
```
let mixinSet = Object.create(/** @type {!MixinFunction} */(extended).__mixinSet || baseSet || null);
```
[https://github.com/Polymer/polymer/blob/v2.2.0/lib/utils/mixin.html#L65 ](https://github.com/Polymer/polymer/blob/v2.2.0/lib/utils/mixin.html#L65)

when I test the code like this: 
```
class A {
}
function mixinA(superClass) {
    return class extends superClass {
    }
} 

var mixin = Polymer.dedupingMixin(mixinA)

var a = mixin(A)
var b = mixin(A)
var c = mixin(A)
var d = mixin(A)
```
you will found that the  variable `mixinSet` become 
![image](https://user-images.githubusercontent.com/7246595/31878158-b8f7b71c-b79e-11e7-9677-aec8809f8a67.png)

Although it work well, but I think it maybe a problem and should use `Object.assign`:
```
let mixinSet = Object.assign({}, (extended).__mixinSet || baseSet || null)
```
After use `Object.assign` and run the test code above, the variable `mixinSet` become: 
![image](https://user-images.githubusercontent.com/7246595/31878292-3c74551e-b79f-11e7-9714-42cc5a324508.png)

And what do you think, thank u 😋

**Comment by TimvdLippe** [comment]
Hm, this might be true. We have to investigate if this breaks anything, especially as `Object.assign` was introduced later than `Object.create`. This means we have to investigate potential compatibility issues.
