### ISSUE TITLE
dom-repeat items property doesn't update when property are modified

### ISSUE THREAD

**Issue by pintaf** [Polymer/polymer#4901]
### Description
dom-repeat items property doesn't update when property are modified

#### Live Demo

http://jsbin.com/gohiley/1/edit

#### Steps to Reproduce
1. Create an Array property full of objects having properties
2. Do a dom-repeat displaying the Array->object->properties
3. do some code to change the properties
4. the properties displayed in the page are not updated

In the fiddle: Press button "update professor": the data binding is working as expected
                      Press button "update ages": the data binding isn't working in a dom-repeat

#### Expected Results
Data binding. I expect the DOM to reflect the new properties values

#### Actual Results
the properties displayed in the page are not updated

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions
- Polymer: v2.2.0
- webcomponents: latest from master

**Comment by guzmanpaniagua** [comment]
polymer did not did dirty checking on arrays changes, whne you change something insie an array he did not know unless you say him explicitly

if you modify your example like this it will work
```
        changeAge: function(change) {
          this.classroom[0].age = 20;
          this.notifyPath("classroom.0.age", this.classroom[0].age);

        },
```

here is the documentation about it
https://www.polymer-project.org/1.0/docs/devguide/model-data#notifysplices

**Comment by YingshanDeng** [comment]
The simpler way to solve this problem is to use `set`:
```
this.set('classroom.0.age', 20)
```

**Comment by pintaf** [comment]
You guys Rock ! Thanks for the amazingly fast support !
Both solutions are working like a charm.

I'm gonna close this. @guzmanpaniagua : Where you the one sneaking in the fridge ? ;-) .  good example.

@YingshanDeng 👍 
@guzmanpaniagua 👍
