### ISSUE TITLE
PropertyAccessors API doc needs clarification

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#4906]
Doc says:

For basic usage of this mixin, simply declare attributes to observe via the standard static get observedAttributes(), implement _propertiesChanged on the class, and then call MyClass.createPropertiesForAttributes() once on the class to generate property accessors for each observed attribute prior to instancing. Last, call this._flushProperties() once to enable the accessors.

Questions:
1) What does "prior to instancing" mean? Should this be done once, at a class level, before creating an instance of a component? Or once per instance? 
2) _flushProperties--in the constructor? Or does this need to be called after the constructor?
3) API doc for _flushProperties says "Generally, this method should not be called in user code," but the comment at the top of the file tells us to do just that. Maybe, "Generally this method should not be called in user code, _unless you are using the `PropertyAccessor` mixin directly."??

The following code appears to work for me, but I arrived at it by a process of guesswork and experimentation, and it may not be optimal.

```
  class CustomElement extends Polymer.PropertyAccessors(HTMLElement) {
    
    static get observedAttributes() { return ['one', 'two']; }
    
    constructor() {
      super();
      CustomElement.createPropertiesForAttributes();
    }
    
    connectedCallback() {
      this._flushProperties();
    }
    _propertiesChanged() {
      this.textContent = this.one + this.two;
    }
  }

  // Register the new element with the browser
  customElements.define('custom-element', CustomElement);

```

/cc @sorvell @kevinpschaaf

**Comment by kevinpschaaf** [comment]
1. `createPropertiesForAttributes` is a static method that should be called on the _class_ once before any instances of the class are made.  The easiest is to just call it once outside the class, e.g. right before the call to `customElements.define`.  It could also be called lazily within the constructor to defer this work to first instance by using an own-property flag on the class or prototype, but this would be "advanced" usage.

2. Looks like the docs you're referencing are a little outdated.  The [current](https://github.com/Polymer/polymer/blob/master/lib/mixins/property-accessors.html#L78-L83) docs [were fixed](https://github.com/Polymer/polymer/commit/0f695d90bf0d4ecf5302c3ea7380bdd4be2db38d.   ) to read like this, which clarifies that users should call `_enableProperties` to turn on accessors in the `connectedCallback`:  
   > For basic usage of this mixin, simply declare attributes to observe via
   > the standard `static get observedAttributes()`, implement `_propertiesChanged`
   > on the class, and then call `MyClass.createPropertiesForAttributes()` once
   > on the class to generate property accessors for each observed attribute
   > prior to instancing. Last, call `this._enableProperties()` in the element's
   > `connectedCallback` to enable the accessors.

3. With the change to the docs above, I think the existing docs then work ok re: not calling it directly.

So a fixed example of basic PropertyAccessors usage would look like this:

```js
  class CustomElement extends Polymer.PropertyAccessors(HTMLElement) {
    
    static get observedAttributes() { return ['one', 'two']; }
    
    constructor() {
      super();
      // (optional) Set defaults for properties; will be overridden by attributes if set
      this.one = 'one';
      this.two = 'two';
    }
    
    connectedCallback() {
      this._enableProperties();
    }

    _propertiesChanged() {
      this.textContent = this.one + this.two;
    }
  }

  // Install accessors for observed attributes
  CustomElement.createPropertiesForAttributes();

  // Register the new element with the browser
  customElements.define('custom-element', CustomElement);
```

**Comment by arthurevans** [comment]
@kevinpschaaf OK, cool. Will rebuild the API docs. I still think "prior to instancing" is obscure, so I may submit a PR to reword.

So I understand, would the lazy creation you mentioned look something like this:

```
    constructor() {
      super();
      if (!PropertiesElement.hasOwnProperty('__propertiesCreated')) {
        PropertiesElement.createPropertiesForAttributes();
        Object.defineProperty(PropertiesElement, '__propertiesCreated', 
            {configurable: true, enumerable: true, value: true});
      }
    }
```

Or am I overthinking? Would it be better to do this on the prototype?

**Comment by kevinpschaaf** [comment]
@arthurevans Yeah that's basically it.  You shouldn't need the `defineProperty` call, just an assignment should be fine.
