### ISSUE TITLE
Upgrade to Polymer 2, Shadow DOM style docs not accurate

### ISSUE THREAD

**Issue by meinsta** [Polymer/polymer#4907]
https://www.polymer-project.org/2.0/docs/upgrade#shadow-dom-styles

#### Expected Results
In the docs, it's documented to replace ':root' with 'html' in wrapped <custom-style> tag.

#### Actual Results
'html' is not an effective selector. We got ':host' working but this doesn't make sense per specs.

### Versions
- Polymer: v2.0.0
- webcomponents: v6.0.0

**Comment by arthurevans** [comment]
Can you clarify where you're using this selector?

If you're using it at the document level, you should replace it with `html`. That is a valid selector that's useful for, among other things, setting default custom properties:

```
<custom-style>
  <style>
    html {
      --my-default-color: red;
    }
  </style>
</custom-style>
```

If you're using it inside an element, we recommend replacing it with `:html > *`:

```
<dom-module id="my-el">
  <template>
    <style>
       :host { display: block; }
       /* Use :host > * to override custom property values set higher up */
       :host > * { 
         --my-default-color: blue;        
       }
    </style>
```

If you're using it in a style module that gets imported into _both_ document and element contexts, you could use a selector like `html,:host`

**Comment by arthurevans** [comment]
Also: you list the versions as Polymer v2.0.0—hopefully you're using the latest 2.x release, as we've fixed quite a few bugs since the initial 2.0 release.

**Comment by meinsta** [comment]
We're upgrading from 1.9.1 and have been pointing to 2.0.0 to test; I'm confused, you mentioned ':html > *' which is markup that I've never seen before?

**Comment by meinsta** [comment]
':host > *' is an expensive selector and I'm finding that where ':host' should apply it doesn't..

at the document level, I should be able to do something like:
` html { @apply --my-style; }`

but instead I'm forced to do this within the element:
`:host > * { @apply --my-style }`

**Comment by meinsta** [comment]
Also I've found at the element level, in Poly 2.0.0+ (tested this in 2.2.0), `html` works the same as `:host`. 

Another bug we're seeing is background-urls encoded in base64 will occasionally break stylesheets.

**Comment by arthurevans** [comment]
@meinsta The `:html > *` markup is shown in the docs, in the section you cited in your initial report.

The first example you list:

`html { @apply --my-style }`

Applies the mixin `--my-style` to the document itself. What that does depends on the contents of `--my-style`... Settings that inherit, like `font-face ` and `color` should inherit down the tree, including into shadow trees.

The second example:

`:host > * {@apply --my-style}

Applies `--my-style` to every top-level child in the host's shadow tree. (This may be more expensive than `:host`, but it's less expensive than `:host *`.)

`html` shouldn't work at all inside an element's styles.  Do you have a small reproduction case showing the issue you're experiencing?

**Comment by meinsta** [comment]
To clarify, here's the documentation I'm referring to:

<img width="790" alt="screen shot 2017-11-01 at 10 09 58 am" src="https://user-images.githubusercontent.com/9779373/32278784-273db97e-beed-11e7-9b1c-8495dda881fe.png">

I'm working in a private repo so I can't show you the case specifically but here's a gist of the markup. 

Before (Polymer 1.9.1):
```
<dom-module id="foo-css">
 <template>
  <custom-style>
   <style>
     :root {
       background: var(--my-background-color);
     }
    </style>
  </custom-style>
 </template>
</dom-module>
```

After (Polymer 2.x), I should be able to do: 
```
html {
   background: var(--my-background-color);
}
```

But instead, only this is effective: 
```
:host {
   background: var(--my-background-color);
}
```

I have a couple other points of confusion, but here's a good starting point.

**Comment by TimvdLippe** [comment]
I don't think you should include `<custom-style>` in a style module. `<custom-style>` should be used when styling in a main document (e.g. index.html). If you want to share styles, you can remove the usage of `<custom-style>` and up with one of the two:

```html
<dom-module id="foo-css">
 <template>
   <style>
     :host {
       background: var(--my-background-color);
     }
    </style>
 </template>
</dom-module>
```

```html
<custom-style>
  <style>
    html {
      background: var(--my-background-color);
    }
  </style>
</custom-style>
```

**Comment by miafg** [comment]
I don't understand. The second example uses `<custom-style>`.

**Comment by meinsta** [comment]
@TimvdLippe - Those examples don't work for a hybrid environment. I appreciate the clarity for Polymer 2.X though!

We're also seeing in Polymer 2 that base64 background urls are occasionally breaking stylesheets. Not sure if this should be logged as a separate issue.

**Comment by TimvdLippe** [comment]
> Those examples don't work for a hybrid environment

I think I forgot a thing. This should work:

```html
<custom-style>
  <style is="custom-style">
    html {
      background: var(--my-background-color);
    }
  </style>
</custom-style>
```

The `is="custom-style"` makes sure it works in Polymer 1, while the wrapper of `<custom-style>` makes sure it works in Polymer 2. Does this clarify it more? @meinsta

**Comment by meinsta** [comment]
Yes--our repo had `<custom-style>` for all style modules and now we can clean this up with our hybridization efforts. Thank you.

**Comment by TimvdLippe** [comment]
Glad you got it solved! :tada:
