### ISSUE TITLE
Provide a disable-upgrade option for Polymer 2

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#4909]
In Polymer 1.x users could add a `disable-upgrade` attribute to elements to defer upgrade work until the attribute was removed. This feature is not possible in Polymer 2 due to removal of bespoke API (e.g. users implement `connectedCallback` rather than `attached`); however, we should be able to add a mixin that users can opt-in to using.

**Comment by kevinpschaaf** [comment]
Current status: PR #4994 is up which adds an optional mixin for deferring all `connectedCallback` work.  Per IRL review, last step is to add Legacy support for deferring user created callback work (not possible with non-Legacy constructor work).
