### ISSUE TITLE
ShadyDOM + ShadyCSS + dom-repeat + appendChild

### ISSUE THREAD

**Issue by Westbrook** [Polymer/polymer#4910]
### Description
When using `appendChild` inside of an element that is placed using `dom-repeat`, the ShadyDOM scoping on the appended child is incorrectly applied at the parent element's parent rather than the direct parent.

#### Live Demo
http://jsbin.com/copevoxeci/edit?html,console,output

#### Steps to Reproduce
1. Create a parent element that uses `dom-repeat` to place child elements.
2. Have those child elements `.appendChild` elements into themselves either via `this.shadowRoot` or a cached element in the template.
3. See the incorrect scope being applied.

#### Expected Results
```
<my-element-parent class="style-scope my-element-parent">
    <my-element class="style-scope my-element-parent">
        <div class="style-scope my-element"></div>  <!-- see `my-element` class here -->
    </my-element>
    <dom-repeat class="style-scope my-element-parent" style="display: none;"></dom-repeat>
</my-element-parent>
```
#### Actual Results
```
<my-element-parent class="style-scope my-element-parent">
    <my-element class="style-scope my-element-parent">
        <div class="style-scope my-element-parent"></div>  <!-- see `my-element-parent` class here -->
    </my-element>
    <dom-repeat class="style-scope my-element-parent" style="display: none;"></dom-repeat>
</my-element-parent>
```

### Browsers Affected

- [ ] Chrome
- [x] Firefox <-- confirmed
- [x] Edge <-- here and below assumed based on ShadyDOM usage
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions
- Polymer: v2.2.0
- webcomponents: v1.0.17

**Comment by AJStacy** [comment]
I can corroborate this is a problem. Attached is a screenshot of our DOM after this exact same scenario. The classes are applied to the elements, but styles are not registered in the browser for the elements. If I stamp a single element to the DOM outside of the context of a dom-repeat, it renders as expected.

![screen shot 2018-04-16 at 2 24 07 pm](https://user-images.githubusercontent.com/2105141/38831505-9eb94aea-418d-11e8-9201-057c0f3adc4c.png)
