### ISSUE TITLE
Polymer 3, String templates, and IE11

### ISSUE THREAD

**Issue by llamadonica** [Polymer/polymer#4911]
### Description
In Polymer 3, elements with String templates and nested custom elements get empty shadowRoots on IE11, and probably any browser using the <template> polyfill.

#### Live Demo
https://talented-sheet.glitch.me/

#### Steps to Reproduce
See https://glitch.com/edit/#!/talented-sheet?path=views/src/app.js:22:46

my-app element has String template and nested my-element with its own shadow root. 

The result is compiled (Webpack + babel) for IE11. Firefox uses the nomodules version too so I think I can rule out webpack/babel issues.

On IE11, shadowRoot will be empty on String template version, but not HTMLTemplateElement version.

#### Expected Results
In the above example:
"Hello from string template Hello from DOM template"

#### Actual Results
On IE11:
"Hello from DOM template". shadowRoot for <my-app> is present but empty.

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [] Safari 9
- [] Safari 8
- [x] IE 11

### Versions
- Polymer: v3.0.0-pre1
- webcomponents: v1.0.17

**Comment by jogibear9988** [comment]
If I visit with FF or Edge I got

     "Hello from string template Hello from DOM template"

if I visit with IE I got

    "Hello from DOM template"

with chrome it does not work (I think cause of transpilation to ES5?)
