### ISSUE TITLE
polymer中文官网的翻译，可不可以更新的快点，英文不好的，看起来很难受啊

### ISSUE THREAD

**Issue by SamoZ** [Polymer/polymer#4917]

**Comment by merlinnot** [comment]
Hope I'll save you some time by using Google translate for you:
"Translation of the official website, can update faster, English is not good, looks very sad ah"

Guess @SamoZ requests a translation of the website.

**Comment by SamoZ** [comment]
谢谢，但是谷歌翻译有些不太准确，比如 polymer=“聚合物”.....
https://polymer-zh.cn/  这是翻译的版本，但是不是很快，所以希望可以注重下中国的使用者

**Comment by SamoZ** [comment]
@merlinnot 谢谢，但是谷歌翻译有些不太准确，比如 polymer=“聚合物”.....
https://polymer-zh.cn/ 这是翻译的版本，但是不是很快，所以希望可以注重下中国的使用者

**Comment by limhenry** [comment]
I can help! _(But how can I contribute to this?)_

**Comment by TimvdLippe** [comment]
Closing this issue per https://github.com/Polymer/docs/issues/2249#issuecomment-319233181 and #4415. It seems that https://polymer-zh.cn/ is a proper alternative right now for Chinese translated documentation. If you would like to contribute to that documentation, feel free to contact the owners of that website (I couldn't figure it out sadly as I lack knowledge of the Chinese language).
