### ISSUE TITLE
element.setProperties() is great for Redux, how about element.getProperties()?

### ISSUE THREAD

**Issue by rjsteinert** [Polymer/polymer#4918]
`element.setProperties()` is great for reflecting the state of a Redux store to a Polymer element in the DOM but sometimes HTML loaded into the DOM provides initial state for the store and it would be great to have an `element.getProperties()` method to get that state.

**Comment by rjsteinert** [comment]
I'll roll with this for now.

```
HTMLElement.prototype.getProperties = function () {
  let propertyInfo; eval(`propertyInfo = ${this.constructor.name}.properties`)
  let props = {}
  for (let propName in propertyInfo) props[propName] = this[propName] 
  return props
}
```

**Comment by TimvdLippe** [comment]
You can implement this in a one-liner without `eval`: http://jsbin.com/nevaqacuwi/7/edit?html,console,output Given how easy it is to implement, not sure if we want to incorporate or if we expect users to implement it in a Redux base class (since it is of limited usage).

**Comment by rjsteinert** [comment]
@TimvdLippe Nice trick 👍
