### ISSUE TITLE
`:dir` generates incorrect selectors when an element uses CSS Custom Properties

### ISSUE THREAD

**Issue by azakus** [Polymer/polymer#4925]
### Description

When the CSS Custom Property shim activates for an element, the `:dir()` selector will be prefixed with an instance selector that breaks the `:dir()` transform

#### Live Demo

http://jsbin.com/yabomib/edit?html,output

#### Expected Results

`hi` should be orange

#### Actual Results

`hi` is black

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions

- Polymer: v1.11.0

**Comment by TimvdLippe** [comment]
Should be fixed per #4926
