### ISSUE TITLE
How to use visual studio and beautify to handle polymer file?

### ISSUE THREAD

**Issue by yanlee26** [Polymer/polymer#4927]
I want eslint my code and beautify my css , html, and js.But it does not work! Codes like this:
`
:host{
}
<template>

</template>
`

**Comment by TimvdLippe** [comment]
Seems to be duplicate of https://github.com/HookyQR/VSCodeBeautify/issues/185

**Comment by TimvdLippe** [comment]
Closing this per above comment, as this is a request for a specific tool (as linked above).
