### ISSUE TITLE
Can anyone look a these issues / pull requests 

### ISSUE THREAD

**Issue by jogibear9988** [Polymer/polymer#4931]
I'm writing here, because in the other repos no one seems to respond!

Can anyone look at: 

https://github.com/Polymer/polymer-cli/pull/878

https://github.com/webcomponents/shadydom/pull/187

**Comment by jogibear9988** [comment]
ths https://github.com/webcomponents/shadydom/pull/187 is closed

**Comment by TimvdLippe** [comment]
The webcomponents issue has been resolved. I have also pinged the tools team regarding the CLI issue. I hope we can get that PR going as well.

Given the above fact, I am closing this issue for now. Feel free to ping the CLI PR in a week or so if there is still not a response from the team.

**Comment by jogibear9988** [comment]
thx

**Comment by jogibear9988** [comment]
can you also ping the team about https://github.com/Polymer/polymer/issues/4859

**Comment by jogibear9988** [comment]
@TimvdLippe maybe you can also trigger the CLI Team to look at these issues:

https://github.com/Polymer/polymer-cli/issues/886
https://github.com/Polymer/polymer-cli/issues/701
https://github.com/Polymer/polymer-cli/issues/633

I think they are all the same, but not yet solved...

**Comment by TimvdLippe** [comment]
These issues will be addressed when we get to them. Right now the modulizer
is on focus in preparation for Polymer 3.

**Comment by jogibear9988** [comment]
maybe it‘s possible to help you? where‘s help needed?

**Comment by TimvdLippe** [comment]
I dont manage that repository. However, for this repository I will do
another cleanup and then mark issues which you can help out with. Stay
tuned!

**Comment by web-padawan** [comment]
@jogibear9988 I believe that issue is related to how `babel-preset-minify` handles unicode characters. Not sure but it might be [this issue](https://github.com/babel/minify/issues/627).

**Comment by jogibear9988** [comment]
I‘ve also added a issue at babel already https://github.com/babel/minify/issues/706 ;-)

**Comment by jogibear9988** [comment]
I think 2 of the issues are fixed in babel-minify (but not yet in a release) and for the 3rd one I created a fix (https://github.com/babel/minify/pull/733). I look that they'll create a release when the 3rd fix is in, so polymer/cli could be updated!
