### ISSUE TITLE
Adding property of name "watch" type object throw error in Firefox.

### ISSUE THREAD

**Issue by bahrus** [Polymer/polymer#4932]
### Description
Error effects.push is not a function in Firefox

#### Live Demo

http://jsbin.com/luhaxab/1/edit

#### Steps to Reproduce
Define a polymer element with property "watch" of type object, and add an observer:

```javascript
class TempElElement extends Polymer.Element {
      static get is() { return 'temp-el-element'; }
      static get properties() {
        return {
          watch:{
            type: Object,
            observer: 'onWatchChange'
          }
        };
      }
      onWatchChange(){
        debugger;
      }
    }
	window.customElements.define(TempElElement.is, TempElElement);
```

#### Expected Results
No error is thrown

#### Actual Results
effects.push is not a function

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v2.2
- webcomponents: vX.X.X

**Comment by TimvdLippe** [comment]
This is a duplicate of #4572

**Comment by bahrus** [comment]
Good point.  I also read, after filing this, that Firefox will be removing watch in version 58.  So hopefully this issue will go away then.
