### ISSUE TITLE
Selecting a large number of elements in the array-selector takes a very long time

### ISSUE THREAD

**Issue by Yavanosta** [Polymer/polymer#4939]
### Description
There is no way to select pack of items in array-selector. Selecting elements one by one tooks a lot of time because of dispatching `array.splice` events on selected array for each modification.

#### Live Demo

https://jsfiddle.net/brkk045v/1/

#### Steps to Reproduce
1. Open JSFiddle
2. Open performance tab in developer tools
3. Try "Select 1000 items" and "Deselect 1000 items" buttons.
4. Each action takes about 1000ms on my laptop and freezes tab during this action.

#### Expected Results
I need some way to select pack of items without freezing.

#### Suggestion
I've made two methods `selectIndexes` and `deselectIndexes` that works much more faster (about 8-12ms on my laptop) for same data. You can try them with "Fast (de)select 1000 items" buttons.
I can write tests for them and make PR. Is it ok?

### Browsers Affected

- [V] Chrome
- [V] Firefox
- [V] Edge
- [V] Safari 9
- [V] Safari 8
- [V] IE 11

### Versions

- Polymer: v2.1.1

**Comment by TimvdLippe** [comment]
I think the methods make sense, but I am not sure if we should integrate them into `<array-selector>`. Right now, you can implement this functionality yourself with extending `Polymer.ArraySelector` as shown in http://jsbin.com/zigujiyafi/edit?html,console,output

The above approach will not work if you have a dependency that directly uses `<array-selector>`, then you need to method on the original class. Is this the case in your application?

**Comment by Yavanosta** [comment]
Yes, this is my case. I'm using [iron-list](https://www.webcomponents.org/element/PolymerElements/iron-list) for long list and have performance problems with selecting items.
So the plan maximum is to add such methods to array-selector and to iron-list.

Of cause i can do this without changing polymer but i think i'm not only person who faced this a problem.

**Comment by TimvdLippe** [comment]
I see, yes that makes sense. Let's see what the other core developers have to say in regard to the maintainability aspect. Implementation seems to be working just fine :smile:

**Comment by Westbrook** [comment]
Just want to peek my head in on this as I also did some work around the concept in #4705 and #4699. While I understand the API surface issues @TimvdLippe brought up therein, I think @Yavanosta also running into this issue (on top of many others that simply chose not to use Polymer or iron-list for this short coming) it might be worth one more push to get it included. When working with a library that delivers `<array-selector>` functionality of selecting and deselecting, it's pretty early in the usage that someone would want to (de)select in batch, and needing each person or component that needs that functionality to add it themselves seems like a pretty sizable adoption headache.

Thanks for taking this in front of the core team one more time Tim!!

**Comment by TimvdLippe** [comment]
@Westbrook Yes that is totally valid. As this issue points out, multiple users are running into this issue. That's why I think it is worth reconsidering, especially as it appears to be used internally in other elements like `iron-list` which means my earlier suggestions/workaround are not applicable.

**Comment by Yavanosta** [comment]
So may i create PR for it?

**Comment by TimvdLippe** [comment]
Let's wait till @sorvell, @kevinpschaaf or @azakus chimes in for a yay/nay. Then you can create a PR :smile:

**Comment by kevinpschaaf** [comment]
Yeah I think we'd take a PR to add more efficient batched select/deselect API's, so that people aren't using private members to get around the performance issues in the current API. So 👍  with making a PR.
