### ISSUE TITLE
Inconsistent reaction on item replace depending on multi property value.

### ISSUE THREAD

**Issue by Yavanosta** [Polymer/polymer#4947]
### Description
Inconsistent reaction on item replace depending on multi property value.

#### Live Demo

https://jsfiddle.net/9n3k6kwp/

#### Steps to Reproduce

1. Create array-selector element with `multi = false`
2. Select some item
3. Replace this item in items array with another item.

#### Expected Results

Selection will be cleared (as in `multi=true`) state.

#### Actual Results

`selected` and `selectedItem` points to previously selected item.

### Browsers Affected

- [V] Chrome
- [V] Firefox
- [V] Edge
- [V] Safari 9
- [V] Safari 8
- [V] IE 11

### Versions

- Polymer: v2.1.1

**Comment by Yavanosta** [comment]
I've found this issue while refactoring selection logic in https://github.com/Polymer/polymer/issues/4939

So i fixed it in same PR with 4939. If it's not allowed i can split it in two PRs.

**Comment by TimvdLippe** [comment]
Fixing multiple issues is okay, as long as every issue has a clear regression test added in your PR (which you seem to have done :smile: )
