### ISSUE TITLE
Polymer 2 - all styling breaks when using base64 svg+xml image in CSS 

### ISSUE THREAD

**Issue by miafg** [Polymer/polymer#4955]
#### Issue
When using a mixin that styles the background using a url with a svg+xml base-64 image it breaks all the styling on the page. When I remove the url from the css all the styling is fine

#### Live Demo
Here's an example where the mixin changes the background but the image doesn't show up as the background....
http://jsbin.com/madezurute/edit?html,output

#### Steps to Reproduce
1) Create an element of just styles with a mixin setting the background to a url of a base 64 svg+xml image. 
2) In another element apply the mixin

#### Expected Results
No error the rest of the page is styled correctly and the image background shows

#### Actual Results
The page is ill formatted

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Version
- Polymer: v2.0.0
- webcomponents: v1.0.19

**Comment by sorvell** [comment]
The jsbin provided does not seem to demonstrate the problem. Can you explain what's unexpected in the jsbin or update it to show the problem? Thanks.
