### ISSUE TITLE
passiveTouchGestures probably shouldn't apply to touchend

### ISSUE THREAD

**Issue by RByers** [Polymer/polymer#4961]
Touch scrolling is designed to be fast when `touchstart` and `touchmove` listeners are passive, but it's fine for `touchend` to be non-passive (since it doesn't block scrolling).  See [here](https://developers.google.com/web/updates/2017/01/scrolling-intervention#breakage_and_guidance) for some details including:

> Although it's still necessary to do so for mobile Safari, websites should not rely on calling preventDefault() inside of touchstart and touchmove listeners as this is no longer guaranteed to be honored in Chrome. Developers should apply the touch-action CSS property on elements where scrolling and zooming should be disabled to notify the browser before any touch events occur. To suppress the default behavior of a tap (such as the generation of a click event), call preventDefault() inside of a touchend listener.

From [code inspection](https://github.com/Polymer/polymer/blob/21ff47184edf0fd247776dedbf5b764c1a68e8a9/lib/utils/gestures.html#L484) it looks to me like Polymer's `passiveTouchGestures` feature (#3604) sets all touch listeners to passive, including `touchend`.  This will make adoption harder because it disables the ability to suppress `click` events.  See for example b/66423965 inside Google.

Perhaps `passiveTouchGestures` can simply be updated to apply only to `touchstart` and `touchmove` listeners?

/cc @azakus @dtapuska

**Comment by azakus** [comment]
Ah, I missed this guidance somehow!
I'm totally fine making this change as it removes most of the tradeoffs, thanks!
