### ISSUE TITLE
`Polymer is not defined` when using browser ES6 modules in Chrome

### ISSUE THREAD

**Issue by Skwai** [Polymer/polymer#4972]
The following does not work:

```html
// app-main.html
<link rel="import" href="../../bower_components/polymer/polymer-element.html">
<dom-module id="app-main">
    <script type="module"> <!-- this breaks things -->
      import store from './store.js'

      class AppMain extends Polymer.Element {
        static get is () { return 'app-main' [}](url)

        constructor () {
          console.log(store)
        }
      }

      window.customElements.define(AppMain.is, AppMain)
    </script>
</dom-module>

// store.js
export default {
  foo: 'bar'
}
```

Whereas a native Web Component will work (in Chrome)

```html
// x-foo.html
<script type="module">
import foo from './foo.js'

const template = document.createElement('template')
template.innerHTML = `<h1>Foo</h1>`

class XFoo extends HTMLElement {
  static get is () {
    return 'x-foo'    
  }

  constructor () {
    super()
    const shadow = this.attachShadow({ mode: 'open' });
    shadow.appendChild(template.content.cloneNode(true))
    console.log(foo)
  }
}

customElements.define(XFoo.is, XFoo)
</script>

// foo.js
export default 'bar'
```

### Description
Getting `Polymer is not defined` when trying to combine Browser ES6 imports and Polymer Components

#### Expected Results
Should this be working in browsers that support browser ES6 modules and HTML imports? Or is it an issue of something like `document.currentScript.ownerDocument` not being accessible from within a `<script type="module">`?

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v2.2.0
- webcomponents: v1.0.20

**Comment by Skwai** [comment]
After watching this, I now realise that this issue is kind of redundant:
https://www.youtube.com/watch?v=JH6jEcLxJEI

**Comment by arthurevans** [comment]
@Skwai I believe this is a timing issue that had to do with how html imports and modules work together (or don't). I believe it will work if your module code waits for the `WebComponentsReady` event before trying to define an element.

**Comment by TimvdLippe** [comment]
Actually I think it is a different issue: you are putting the `<script>` in the `<template>`. There should not be any script tag in a template. Putting the script outside of the template does work (can't make the `store.js` work in jsbin, but should just work): http://jsbin.com/gozagak/edit?html,console,output

**Comment by Skwai** [comment]
> Actually I think it is a different issue: you are putting the <script> in the <template>

Sorry, that was a typo, have updated example. It still throws the error.

After watching that intro to Polymer 3 I now realise that HTML imports and ES6 Modules are competing solutions to web components and that it doesn't make a lot of sense to use them together. Polymer 3 ditches HTML imports in favour of ES6 Modules. So it's kind of a moot point

**Comment by Skwai** [comment]
@arthurevans 

Assuming this is what you mean, it didn't seem to help:

```
    document.addEventListener('WebComponentsReady', () => {
      window.customElements.define(AppMain.is, AppMain);
    });
```
