### ISSUE TITLE
Polymer website doesn't work with latest Firefox browser

### ISSUE THREAD

**Issue by aartiPl** [Polymer/polymer#4980]
### Description
Polymer website doesn't work with latest Firefox browser. My Firefox is v.57 64 bit.

#### Live Demo
Polymer website

#### Steps to Reproduce
1. Go to https://www.polymer-project.org/
2. Click menu items: Start, Polymer, App Toolbox, Blog, Community
3. Nothing happens after click

#### Expected Results
The content of page should somehow change.

#### Actual Results
Nothing happens.

### Browsers Affected
- [ ] Chrome (62.0.3202.94)
- [x] Firefox (57)
- [ ] Edge (41.16299.15.0)
- [ ] IE 11

### Versions
-

**Comment by TimvdLippe** [comment]
Unable to reproduce on Firefox 57.

**Comment by aartiPl** [comment]
I have restarted the computer and rechecked. Still the same wrong behavior (nothing changes after clicking menu). I have no similar issues with other pages.
Please suggest what to do to investigate the issue further.

**Comment by TimvdLippe** [comment]
Do you have any extensions installed that might break websites?

**Comment by caraya** [comment]
Tested in 57.0 and 57.0.1.  

All the links you pointed in the report work for me. 

Have you tried clearing up your browser's cache?

**Comment by aartiPl** [comment]
Seems that LastPass extension blocks Polymer components. After removal of LastPass, Polymer website is working again. Thanks for help - I guess the problem is on the LastPass company side.

**Comment by usergenic** [comment]
This is my fix https://gist.github.com/usergenic/9baf88a24dcbc77bc808339755a7d436
