### ISSUE TITLE
IE11 - Unable to get property 'length' of undefined or null reference

### ISSUE THREAD

**Issue by limonte** [Polymer/polymer#4987]
### Description

![image](https://user-images.githubusercontent.com/6059356/33884587-f7263910-df48-11e7-8633-a50674cb66e0.png)

#### Live Demo
Reproducible with [px-data-grid](https://github.com/vaadin/px-data-grid) repo.

#### Steps to Reproduce
1. Clone the https://github.com/vaadin/px-data-grid repo
2. Install deps
3. `polymer serve`
4. Open the served document in IE11 

#### Expected Results
No error is throw

#### Actual Results
Exception `Unable to get property 'length' of undefined or null reference` 

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11

### Versions
- Polymer: v2.3.1
- webcomponents: v1.0.20

**Comment by rbjarnason** [comment]
We have the same problem, we are in the progress of upgrading our app to Polymer 2.

**Comment by 99rain** [comment]
me too!!   i tried multi-explorer, only IE11 has this issure.
