### ISSUE TITLE
Polymer 1.x - Test failed on IE11 win 7 and 8

### ISSUE THREAD

**Issue by jarrodek** [Polymer/polymer#4992]
### Description

Recently my tests of different components started failing for IE11 when performing the tests on SauceLabs.

My regular wtc config is as follows:
```
{
  "verbose": false,
  "plugins": {
    "local": {
      "disabled": true,
      "browsers": ["chrome", "firefox"]
    },
    "sauce": {
      "disabled": true,
      "browsers": [{
        "browserName": "microsoftedge",
        "platform": "Windows 10",
        "version": ""
      }, {
        "browserName": "internet explorer",
        "platform": "Windows 8.1",
        "version": "11"
      }, {
        "browserName": "firefox",
        "platform": "Windows 10",
        "version": "latest-2"
      }, {
        "browserName": "chrome",
        "platform": "Windows 10",
        "version": "latest-2"
      }, {
        "browserName": "safari",
        "platform": "OS X 10.11",
        "version": "10"
      }]
    }
  }
}
```

This throws error for IE11:

```
Error: Error thrown outside of test function: the string "console.error: Error stamping [object HTMLUnknownElement] Error: Invalid argument." was thrown, throw an Error :)
```

To test if there's something with IE11, my components or Polymer I've added configuration for IE11 for win 7, win 8, win 8.1 and win 10 to the one of the failing components.
Except win 10 all failed. I was able to reproduce the same behavior for other component that started failing.

I am not sure what is exactly happening and when exactly it started. I am not sure how else I could help here. I can't even test it on this operating systems because I do not have access to it (license keys).

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11

### Versions
- Polymer: v1.11.1
- webcomponents: v0.7.24

**Comment by TimvdLippe** [comment]
Hm this is a tough situation, as we need some more information (preferably a succinct JSBin) that reproduces the issue. Only then are we able to debug and potentially fix the issue. Could you please supply a JSBin that triggers the error?

**Comment by jarrodek** [comment]
The problem is that I do not have access to Windows 7 so I can't test it. The tests are failing on Sauce Labs. I may try if I find win 7 machine somewhere :)

**Comment by TimvdLippe** [comment]
@jarrodek were you able to reproduce this issue?

**Comment by jarrodek** [comment]
Tests stopped to fail so I guess it was either fixed or the problem was not related to Polymer.
