### ISSUE TITLE
Docs for PropertiesChanged mixin are incorrect

### ISSUE THREAD

**Issue by azakus** [Polymer/polymer#5002]
Docs comment for [PropertiesChanged mixin](https://github.com/Polymer/polymer/blob/master/lib/mixins/properties-changed.html#L30) reference API that doesn't exist on this class.
This looks like a copy-paste error from PropertyAccessors mixin.

**Comment by sorvell** [comment]
Fixed by https://github.com/Polymer/polymer/pull/4996
