### ISSUE TITLE
Deprecation of HTML Imports styling the main document

### ISSUE THREAD

**Issue by bastienarm** [Polymer/polymer#5008]
I've updated Polymer and all elements this morning, and I still get the message in console :

[Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.

Warning disapear if I remove from my index.html any paper-* element included with 

`<link rel="import" href="bower_components/paper-*/paper-*">`

What can I do to remove the warning in console ?

Thanks a lot

Here are all current version : 

google-map#2.0.3 bower_components\google-map
├── google-apis#2.0.0
├── iron-resizable-behavior#1.0.6
├── iron-selector#1.5.3
└── polymer#1.11.2

platinum-elements#2.0.0 bower_components\platinum-elements
├── platinum-bluetooth#2.1.2
├── platinum-https-redirect#1.0.2
├── platinum-push-messaging#1.0.5
└── platinum-sw#1.3.0

iron-elements#1.0.10 bower_components\iron-elements
├── iron-a11y-announcer#1.0.6
├── iron-a11y-keys#1.0.9
├── iron-a11y-keys-behavior#1.1.9
├── iron-ajax#1.4.4
├── iron-autogrow-textarea#1.0.15
├── iron-behaviors#1.0.18
├── iron-checked-element-behavior#1.0.6
├── iron-collapse#1.3.0
├── iron-component-page#1.1.9
├── iron-demo-helpers#1.2.6
├── iron-doc-viewer#1.1.0
├── iron-dropdown#1.5.6
├── iron-fit-behavior#1.2.7
├── iron-flex-layout#1.3.7
├── iron-form#1.1.6
├── iron-form-element-behavior#1.0.7
├── iron-icon#1.0.13
├── iron-icons#1.2.1
├── iron-iconset#1.0.6
├── iron-iconset-svg#1.1.2
├── iron-image#1.2.6
├── iron-input#1.0.11
├── iron-jsonp-library#1.0.5
├── iron-label#1.0.2
├── iron-list#1.4.6
├── iron-localstorage#1.0.6
├── iron-location#0.8.11
├── iron-media-query#1.0.8
├── iron-menu-behavior#1.3.1
├── iron-meta#1.1.3
├── iron-overlay-behavior#1.10.4
├── iron-page-url#0.7.0
├── iron-pages#1.0.9
├── iron-range-behavior#1.0.7
├── iron-resizable-behavior#1.0.6
├── iron-scroll-target-behavior#1.1.1
├── iron-scroll-threshold#1.0.3
├── iron-selector#1.5.3
├── iron-signals#1.0.3
├── iron-swipeable-container#1.0.3
├── iron-test-helpers#1.4.1
├── iron-validatable-behavior#1.1.2
└── iron-validator-behavior#1.0.2

google-chart#2.0.0 bower_components\google-chart
├── google-apis#2.0.0
├── iron-ajax#1.4.4
└── polymer#1.11.2

page#1.7.1 bower_components\page

polymer#1.11.2 bower_components\polymer
└── webcomponentsjs#0.7.24

iron-resizable-behavior#1.0.6 bower_components\iron-resizable-behavior
└── polymer#1.11.2

google-apis#2.0.0 bower_components\google-apis
├── iron-jsonp-library#1.0.5
└── polymer#1.11.2

platinum-https-redirect#1.0.2 bower_components\platinum-https-redirect
└── polymer#1.11.2

iron-selector#1.5.3 bower_components\iron-selector
└── polymer#1.11.2

iron-a11y-announcer#1.0.6 bower_components\iron-a11y-announcer
└── polymer#1.11.2

iron-a11y-keys#1.0.9 bower_components\iron-a11y-keys
├── iron-a11y-keys-behavior#1.1.9
└── polymer#1.11.2

platinum-bluetooth#2.1.2 bower_components\platinum-bluetooth
├── polymer#1.11.2
└── promise-polyfill#1.0.1

platinum-sw#1.3.0 bower_components\platinum-sw
├── polymer#1.11.2
└── sw-toolbox#3.6.1

iron-autogrow-textarea#1.0.15 bower_components\iron-autogrow-textarea
├── iron-behaviors#1.0.18
├── iron-flex-layout#1.3.7
├── iron-form-element-behavior#1.0.7
├── iron-validatable-behavior#1.1.2
└── polymer#1.11.2

iron-checked-element-behavior#1.0.6 bower_components\iron-checked-element-behavior
├── iron-form-element-behavior#1.0.7
├── iron-validatable-behavior#1.1.2
└── polymer#1.11.2

iron-ajax#1.4.4 bower_components\iron-ajax
├── polymer#1.11.2
└── promise-polyfill#1.0.1

iron-behaviors#1.0.18 bower_components\iron-behaviors
├── iron-a11y-keys-behavior#1.1.9
└── polymer#1.11.2

iron-collapse#1.3.0 bower_components\iron-collapse
├── iron-resizable-behavior#1.0.6
└── polymer#1.11.2

iron-demo-helpers#1.2.6 bower_components\iron-demo-helpers
├── iron-flex-layout#1.3.7
├── iron-icons#1.2.1
├── iron-location#0.8.11
├── marked-element#1.4.2
├── paper-icon-button#1.1.6
├── paper-styles#1.3.1
├── polymer#1.11.2
└── prism-element#1.2.0

iron-doc-viewer#1.1.0 bower_components\iron-doc-viewer
├── marked-element#1.4.2
├── paper-button#1.0.15
├── paper-styles#1.3.1
├── polymer#1.11.2
└── prism-element#1.2.0

iron-component-page#1.1.9 bower_components\iron-component-page
├── hydrolysis#1.24.1
├── iron-ajax#1.4.4
├── iron-doc-viewer#1.1.0
├── iron-flex-layout#1.3.7
├── iron-icons#1.2.1
├── iron-selector#1.5.3
├── paper-header-panel#1.1.7
├── paper-styles#1.3.1
├── paper-toolbar#1.1.7
└── polymer#1.11.2

iron-dropdown#1.5.6 bower_components\iron-dropdown
├── iron-behaviors#1.0.18
├── iron-overlay-behavior#1.10.4
├── iron-resizable-behavior#1.0.6
├── neon-animation#1.2.5
└── polymer#1.11.2

iron-fit-behavior#1.2.7 bower_components\iron-fit-behavior
└── polymer#1.11.2

iron-flex-layout#1.3.7 bower_components\iron-flex-layout
└── polymer#1.11.2

iron-icon#1.0.13 bower_components\iron-icon
├── iron-flex-layout#1.3.7
├── iron-meta#1.1.3
└── polymer#1.11.2

iron-form#1.1.6 bower_components\iron-form
├── iron-ajax#1.4.4
└── polymer#1.11.2

iron-icons#1.2.1 bower_components\iron-icons
├── iron-icon#1.0.13
├── iron-iconset-svg#1.1.2
└── polymer#1.11.2

iron-iconset#1.0.6 bower_components\iron-iconset
├── iron-meta#1.1.3
└── polymer#1.11.2

iron-form-element-behavior#1.0.7 bower_components\iron-form-element-behavior
└── polymer#1.11.2

iron-input#1.0.11 bower_components\iron-input
├── iron-a11y-announcer#1.0.6
├── iron-validatable-behavior#1.1.2
└── polymer#1.11.2

iron-iconset-svg#1.1.2 bower_components\iron-iconset-svg
├── iron-meta#1.1.3
└── polymer#1.11.2

iron-image#1.2.6 bower_components\iron-image
├── iron-flex-layout#1.3.7
└── polymer#1.11.2

iron-jsonp-library#1.0.5 bower_components\iron-jsonp-library
└── polymer#1.11.2

iron-localstorage#1.0.6 bower_components\iron-localstorage
└── polymer#1.11.2

iron-label#1.0.2 bower_components\iron-label
└── polymer#1.11.2

iron-location#0.8.11 bower_components\iron-location
└── polymer#1.11.2

iron-menu-behavior#1.3.1 bower_components\iron-menu-behavior
├── iron-a11y-keys-behavior#1.1.9
├── iron-selector#1.5.3
└── polymer#1.11.2

iron-list#1.4.6 bower_components\iron-list
├── iron-a11y-keys-behavior#1.1.9
├── iron-resizable-behavior#1.0.6
├── iron-scroll-target-behavior#1.1.1
└── polymer#1.11.2

iron-meta#1.1.3 bower_components\iron-meta
└── polymer#1.11.2

iron-pages#1.0.9 bower_components\iron-pages
├── iron-resizable-behavior#1.0.6
├── iron-selector#1.5.3
└── polymer#1.11.2

iron-overlay-behavior#1.10.4 bower_components\iron-overlay-behavior
├── iron-a11y-keys-behavior#1.1.9
├── iron-fit-behavior#1.2.7
├── iron-resizable-behavior#1.0.6
└── polymer#1.11.2

iron-scroll-threshold#1.0.3 bower_components\iron-scroll-threshold
├── iron-scroll-target-behavior#1.1.1
└── polymer#1.11.2

iron-range-behavior#1.0.7 bower_components\iron-range-behavior
└── polymer#1.11.2

iron-scroll-target-behavior#1.1.1 bower_components\iron-scroll-target-behavior
└── polymer#1.11.2

iron-swipeable-container#1.0.3 bower_components\iron-swipeable-container
└── polymer#1.11.2

iron-test-helpers#1.4.1 bower_components\iron-test-helpers
└── polymer#1.11.2

iron-validatable-behavior#1.1.2 bower_components\iron-validatable-behavior
├── iron-meta#1.1.3
└── polymer#1.11.2

iron-validator-behavior#1.0.2 bower_components\iron-validator-behavior
├── iron-meta#1.1.3
└── polymer#1.11.2

paper-badge#1.1.4 bower_components\paper-badge
├── iron-flex-layout#1.3.7
├── iron-icon#1.0.13
├── iron-resizable-behavior#1.0.6
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-button#1.0.15 bower_components\paper-button
├── iron-flex-layout#1.3.7
├── paper-behaviors#1.0.13
├── paper-material#1.0.7
└── polymer#1.11.2

paper-behaviors#1.0.13 bower_components\paper-behaviors
├── iron-behaviors#1.0.18
├── iron-checked-element-behavior#1.0.6
├── paper-ripple#1.0.10
└── polymer#1.11.2

paper-dialog-scrollable#1.1.5 bower_components\paper-dialog-scrollable
├── iron-flex-layout#1.3.7
├── paper-dialog-behavior#1.2.9
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-dialog-behavior#1.2.9 bower_components\paper-dialog-behavior
├── iron-overlay-behavior#1.10.4
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-checkbox#1.4.2 bower_components\paper-checkbox
├── iron-checked-element-behavior#1.0.6
├── paper-behaviors#1.0.13
├── paper-ripple#1.0.10
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-dialog#1.1.0 bower_components\paper-dialog
├── iron-overlay-behavior#1.10.4
├── neon-animation#1.2.5
├── paper-dialog-behavior#1.2.9
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-dropdown-menu#1.5.1 bower_components\paper-dropdown-menu
├── iron-a11y-keys-behavior#1.1.9
├── iron-form-element-behavior#1.0.7
├── iron-icon#1.0.13
├── iron-iconset-svg#1.1.2
├── iron-validatable-behavior#1.1.2
├── paper-behaviors#1.0.13
├── paper-input#1.1.25
├── paper-menu-button#1.5.2
├── paper-ripple#1.0.10
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-card#1.1.6 bower_components\paper-card
├── iron-flex-layout#1.3.7
├── iron-image#1.2.6
├── paper-material#1.0.7
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-fab#1.2.2 bower_components\paper-fab
├── iron-flex-layout#1.3.7
├── iron-icon#1.0.13
├── paper-behaviors#1.0.13
├── paper-material#1.0.7
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-header-panel#1.1.7 bower_components\paper-header-panel
├── iron-flex-layout#1.3.7
└── polymer#1.11.2

paper-icon-button#1.1.6 bower_components\paper-icon-button
├── iron-icon#1.0.13
├── paper-behaviors#1.0.13
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-item#1.2.2 bower_components\paper-item
├── iron-behaviors#1.0.18
├── iron-flex-layout#1.3.7
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-menu-button#1.5.2 bower_components\paper-menu-button
├── iron-a11y-keys-behavior#1.1.9
├── iron-behaviors#1.0.18
├── iron-dropdown#1.5.6
├── iron-fit-behavior#1.2.7
├── neon-animation#1.2.5
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-listbox#1.1.3 bower_components\paper-listbox
├── iron-behaviors#1.0.18
├── iron-collapse#1.3.0
├── iron-menu-behavior#1.3.1
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-input#1.1.25 bower_components\paper-input
├── iron-a11y-keys-behavior#1.1.9
├── iron-autogrow-textarea#1.0.15
├── iron-behaviors#1.0.18
├── iron-form-element-behavior#1.0.7
├── iron-input#1.0.11
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-menu#1.3.0 bower_components\paper-menu
├── iron-behaviors#1.0.18
├── iron-collapse#1.3.0
├── iron-flex-layout#1.3.7
├── iron-menu-behavior#1.3.1
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-progress#1.0.12 bower_components\paper-progress
├── iron-flex-layout#1.3.7
├── iron-range-behavior#1.0.7
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-material#1.0.7 bower_components\paper-material
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-ripple#1.0.10 bower_components\paper-ripple
├── iron-a11y-keys-behavior#1.1.9
└── polymer#1.11.2

paper-radio-button#1.4.0 bower_components\paper-radio-button
├── iron-checked-element-behavior#1.0.6
├── iron-flex-layout#1.3.7
├── paper-behaviors#1.0.13
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-radio-group#1.2.2 bower_components\paper-radio-group
├── iron-a11y-keys-behavior#1.1.9
├── iron-menu-behavior#1.3.1
├── paper-radio-button#1.4.0
└── polymer#1.11.2

paper-slider#1.0.15 bower_components\paper-slider
├── iron-a11y-keys-behavior#1.1.9
├── iron-behaviors#1.0.18
├── iron-flex-layout#1.3.7
├── iron-form-element-behavior#1.0.7
├── paper-behaviors#1.0.13
├── paper-input#1.1.25
├── paper-progress#1.0.12
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-spinner#1.2.1 bower_components\paper-spinner
├── iron-flex-layout#1.3.7
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-drawer-panel#1.0.11 bower_components\paper-drawer-panel
├── iron-media-query#1.0.8
├── iron-resizable-behavior#1.0.6
├── iron-selector#1.5.3
└── polymer#1.11.2

paper-styles#1.3.1 bower_components\paper-styles
├── font-roboto#1.0.3
├── iron-flex-layout#1.3.7
└── polymer#1.11.2

paper-toast#1.3.1 bower_components\paper-toast
├── iron-a11y-announcer#1.0.6
├── iron-fit-behavior#1.2.7
├── iron-overlay-behavior#1.10.4
└── polymer#1.11.2

paper-scroll-header-panel#1.0.16 bower_components\paper-scroll-header-panel
├── iron-resizable-behavior#1.0.6
└── polymer#1.11.2

shadycss#1.1.0 bower_components\shadycss

paper-toolbar#1.1.7 bower_components\paper-toolbar
├── iron-flex-layout#1.3.7
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-toggle-button#1.3.0 bower_components\paper-toggle-button
├── iron-checked-element-behavior#1.0.6
├── paper-behaviors#1.0.13
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-tooltip#1.1.4 bower_components\paper-tooltip
├── neon-animation#1.2.5
├── paper-styles#1.3.1
└── polymer#1.11.2

paper-tabs#1.8.0 bower_components\paper-tabs
├── iron-behaviors#1.0.18
├── iron-flex-layout#1.3.7
├── iron-icon#1.0.13
├── iron-iconset-svg#1.1.2
├── iron-menu-behavior#1.3.1
├── iron-resizable-behavior#1.0.6
├── paper-behaviors#1.0.13
├── paper-icon-button#1.1.6
├── paper-styles#1.3.1
└── polymer#1.11.2

webcomponentsjs#0.7.24 bower_components\webcomponentsjs

neon-animation#1.2.5 bower_components\neon-animation
├── iron-meta#1.1.3
├── iron-resizable-behavior#1.0.6
├── iron-selector#1.5.3
├── polymer#1.11.2
└── web-animations-js#2.3.1

promise-polyfill#1.0.1 bower_components\promise-polyfill
└── polymer#1.11.2

prism-element#1.2.0 bower_components\prism-element
├── polymer#1.11.2
└── prism#1.9.0

marked-element#1.4.2 bower_components\marked-element
├── marked#0.3.9
└── polymer#1.11.2

font-roboto#1.0.3 bower_components\font-roboto

web-animations-js#2.3.1 bower_components\web-animations-js

hydrolysis#1.24.1 bower_components\hydrolysis

sw-toolbox#3.6.1 bower_components\sw-toolbox

marked#0.3.9 bower_components\marked

prism#1.9.0 bower_components\prism

**Comment by web-padawan** [comment]
Duplicate of #4679. Fixed by #4849

See [this comment](https://github.com/Polymer/polymer/issues/4679#issuecomment-333187751) explaining why this warning appears regardless of the fix.

**Comment by bastienarm** [comment]
Thanks for the information, didn't see this issue
I'm just going to cross my fingers, hoping that everything will be fine.

thanks a lot

**Comment by web-padawan** [comment]
@bastienarm don't worry, the Polymer team has already implemented the fix mentioned above so the upcoming change won't break anything. See also [this blog post](https://www.polymer-project.org/blog/2017-10-18-upcoming-changes.html) for detailed explanation
