### ISSUE TITLE
"Maximum call stack size" in Canary

### ISSUE THREAD

**Issue by karan** [Polymer/polymer#501]
I'm testing [my first component](https://github.com/karan/sc-embed) in different browsers and it seems to work in Chrome stable, Firefox, Safari but not in Canary.

Below are the errors I am receiving these errors

```
Uncaught RangeError: Maximum call stack size exceeded deprecated.js:12
Failed to load resource: the server responded with a status of 404 (Not Found) http://karan.github.io/polymer/polymer.html
Failed to load resource: the server responded with a status of 404 (Not Found) http://karan.github.io/core-ajax/core-ajax.html
Uncaught ReferenceError: Polymer is not defined sc-embed.html:11
```

I have no idea why this is happening. I have all experimental features enabled in `chrome://flags`.

Also, in my `gh-pages` branch, I have all my code except the dependencies. How is the demo able to work in browsers then? How it it able to find the dependencies? This is throwing me off.

**Comment by rohithp37** [comment]
I am running first polymer element on browser but, there is not found text and message in console 
Failed to load resource: the server responded with a status of 404 (Not Found)
