### ISSUE TITLE
mixinBehaviors has incorrect return type

### ISSUE THREAD

**Issue by LarsDenBakker** [Polymer/polymer#5012]
Great to see Polymer 2 typings are now on the master branch.

I noticed that mixinBehaviors has an incorrect return type:
` function mixinBehaviors(behaviors: object|any[]|null, klass: HTMLElement|{new(): HTMLElement}): {new(): HTMLElement};`

 It returns an HTMLElement, ignoring the super class and the behaviors that were passed to it. This is due to how the JSDoc is set up: https://github.com/Polymer/polymer/blob/master/lib/legacy/class.html#L38

Adding the behavior types is a bit more complicated, but at least it could return the type of the class passed as the second argument. I think something like this:

`function mixinBehaviors<T extends HTMLElement>(behaviors: object|any[]|null, klass: T): T;`

**Comment by TimvdLippe** [comment]
I think we can do this with `@template`. @aomarks does gen- support this as well or are changes required?

**Comment by 43081j** [comment]
It may be a bit more complex than `@template` seeing as there's no actual class at the point of it being mixed in (its all dynamic). 

It may well need some sort of logic in the generator instead.
