### ISSUE TITLE
where could I find the new guider of Styling local DOM?

### ISSUE THREAD

**Issue by hzmnet** [Polymer/polymer#5014]
seem the old 1.xxx not same to newest 1.1x
1.  where could I find the new guider of Styling local DOM?
2.  how do you guys to format a file which 70% is HTML template on polymer 3

**Comment by merlinnot** [comment]
1) For version 1: https://www.polymer-project.org/1.0/docs/devguide/styling, for version 2: https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom
2) The answer is [lit-html](https://github.com/PolymerLabs/lit-html). For some overview, see https://www.polymer-project.org/blog/2017-08-22-npm-modules.html

**Comment by hzmnet** [comment]
ok i found the problem when i change to v1.11.2
if  using <style is="custom-style"> all styles are not working.

**Comment by hzmnet** [comment]
but the question #2

i mean is FORMAT the codes. if there 700 lines HTML codes

**Comment by TimvdLippe** [comment]
Closing this issue as the first question is resolved and the second question can better be asked and answered in our Slack (https://polymer-slack.herokuapp.com/)
