### ISSUE TITLE
updateStyles() doesn't work in IE11

### ISSUE THREAD

**Issue by limonte** [Polymer/polymer#5015]
### Description
It's not possible currently to update the CSS custom property using `updateStyles()` in IE11. The same thing in all other browsers works as expected.

#### Live Demo
jsfiddle for IE11 isn't possible, so here's the repo: https://github.com/limonte/ie-polymer2-issue-5015/

#### Steps to Reproduce
1. Clone the repo above
2. Serve and run in IE11

#### Expected Results
The `my-custom-element` has `sandybrown` background. This is the screenshot from Chrome:
![](https://i.imgur.com/VrKI76d.png)

#### Actual Results
The `my-custom-element` has `steelblue` background.
![](https://i.imgur.com/TvJLypZ.png)

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11

### Versions
- Polymer: v2.3.1
- webcomponents: v1.0.22

**Comment by limonte** [comment]
Thanks for discussing this issue!

Here's the glitch.me repro just in case:

- https://glitch.com/edit/#!/odd-plant
- https://odd-plant.glitch.me/

**Comment by Artur-** [comment]
This is not IE11 only, it also manifests in Safari 9. Is this somehow related to ES5 transpilation?

**Comment by Artur-** [comment]
Never mind, the test case is broken as it uses the same `id` on both `dom-module` and `my-custom-element`. 

If you change index.html to 
`<my-custom-element id="the-element"></my-custom-element>` 
and
`const myCustomElement = document.getElementById('the-element');`

then it works fine in all browsers from what I can see

**Comment by Artur-** [comment]
On the other hand, if I change the test to use `myCustomElement.style.setProperty('--my-custom-color', 'sandybrown');`, i.e. `style.setProperty` instead of `updateStyles`, then it is broken on IE11 + Safari 9 and works on Safari 10, Firefox, Chrome

**Comment by Artur-** [comment]
Right, so I was under the impression that some other browsers also were using the polyfill but as it turns out, only IE11 and Safari 9 need filling. Then it kind of makes sense.
