### ISSUE TITLE
Provide a template for reporting IE11 issues 

### ISSUE THREAD

**Issue by limonte** [Polymer/polymer#5016]
Creating jsfiddle/jsbin for IE11 isn't possible, but you still asking for it in ISSUE_TEMPLATE.md

I wonder if there any recommended by the Polymer team way to provide live demos for reporting IE11 issues?

**Comment by merlinnot** [comment]
Hi, just of curiosity: jsfiddle doesnt't work in IE11? Why isn't it possible to create one?

**Comment by limonte** [comment]
Because of ES6 in Polymer, e.g. https://github.com/Polymer/polymer/blob/master/lib/legacy/legacy-element-mixin.html#L43

You can try this simplest possible jsbin in IE11 to insure: https://jsbin.com/kebabi/1/edit?html,js,console,output

**Comment by kevinpschaaf** [comment]
You can use http://glitch.me so that the source is served via `polyserve` and transpiled if necessary: https://glitch.com/edit/#!/polymer-repro.  I'll add this as an option to CONTRIBUTING.md and ISSUE_TEMPLATE.md.

**Comment by limonte** [comment]
> You can use http://glitch.me

http://glitch.com :)
