### ISSUE TITLE
Allow users to avoid deprecation warning re: styles in HTML imports

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#5017]
Per https://github.com/Polymer/polymer/issues/4679 (changes landed in https://github.com/Polymer/polymer/pull/4849 and https://github.com/Polymer/polymer/pull/4850), we updated `<custom-style>` to automatically move itself to the main document to avoid breakage due to the [planned deprecation](https://bugs.chromium.org/p/chromium/issues/detail?id=523952) in Chrome of `<styles>` in HTML Imports applying to the main document.

However, since the Chrome deprecation warning is logged as soon as the HTML parser sees the style in the import, the deprecation warning is misleading since the style will immediately be moved to the main document when the `custom-style` upgrades, avoiding any actual problems.  This has confused users and also leads to muddied statistics about the actual impact of the deprecation.

This issue proposes to allow users to add a [`type="custom"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style#attr-type) attribute to `<style>` tags to prevent them from being parsed as `text/css`, which avoids the deprecation warning.  When `custom-style` then moves the style to the main document, it can remove the `type` attribute, allowing the style to be parsed and apply as normal.

**Comment by retrocausal** [comment]
Just a clarification request.
>we updated <custom-style> to automatically move itself to the main document to avoid breakage due to the planned deprecation in Chrome of <styles> in HTML Imports applying to the main document.

What is referred to here as the main document?

>This issue proposes to allow users to add a type="custom" attribute to <style> tags to prevent them from being parsed as text/css, which avoids the deprecation warning. When custom-style then moves the style to the main document, it can remove the type attribute, allowing the style to be parsed and apply as normal.

What exactly should a user do here?

use `<custom-style>` tags?
use `<style type=custom>` ?
use `<style type=custom>` inside `<custom-style>`?

And, are style modules supported? or, to be deprecated?
