### ISSUE TITLE
Tried to use polymer without loading it first error.

### ISSUE THREAD

**Issue by ryasmi** [Polymer/polymer#502]
Really struggling to figure out why I am receiving this error (see below).

```
You tried to use polymer without loading it first. To load polymer, <link rel="import" href="components/polymer/polymer.html"> 
```

Source code can be found at [badseycc/fantasy-cricket](https://github.com/badseycc/fantasy-cricket).

**Comment by toadkicker** [comment]
Hello guys I'm trying to wrap my head around this as well. To clarify then, for every element (e.g. created by using yo polymer:element), it has to include `<link rel="import" href="../../bower_components/polymer/polymer.html">` and must be repeated for every element using <polymer-element>?

**Comment by robdodson** [comment]
@toadkicker if your element is importing other elements that also import polymer, then you can skip it. Otherwise, yes. It ensures that the dependencies are loaded before your element attempts to register.
