### ISSUE TITLE
Hybrid component in Polymer 2 can't `listen`

### ISSUE THREAD

**Issue by jpodwys** [Polymer/polymer#5022]
### Description

A hybrid polymer element using `this.listen` in Polymer 2 does not catch the provided event.

#### Live Demos

1. [Using Polymer 2 with a class element](http://jsbin.com/sefiduzoru/edit?html,output)
2. [Using Polymer 2 with a hybrid element](http://jsbin.com/jobahereli/edit?html,output)

#### Steps to Reproduce

1. Visit the first link above
2. Open your browser's dev tools to the console
3. Click in the demo (but not on "Hello!")
4. Notice "document:click" appears in the console
5. Click on "Hello!"
6. Notice the alert that says "You got me!" and "my-element:click" appears in the console
7. Visit the second link above
8. Click in the demo (but not on "Hello!")
9. Notice "document:click" appears in the console
10. Click on "Hello!"
11. Notice "document:click" appears in the console and no alert shows up

#### Expected Results

As far as I can tell from Polymer's hybridization docs, `this.listen` is supported in hybrid elements. As such, I expected `this.listen(this, 'click', '_handleClick');` to execute the `_handleClick` function when using a hybridized component with Polymer 2.

#### Actual Results

`this.listen(this, 'click', '_handleClick');` does nothing.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9

I didn't test any others :(

### Versions

Whatever versions are provided in the default JS Bin demos, so I assume

- Polymer: v2.x
- webcomponents: v1.x

**Comment by TimvdLippe** [comment]
The name of your element was wrong in your second JSBin. The second JSBin had `my-inner-element`, which should have been `my-element`. I added a `console.log` in the `ready` to first verify that the call to `this.listen` was actually called (but it wasn't). Then I spotted the actual error. The following JSBin shows the `this.listen` working as intended: http://jsbin.com/vosujunapo/2/edit?html,console,output

**Comment by jpodwys** [comment]
Wow sorry to have wasted your time and thanks for the response.

**Comment by TimvdLippe** [comment]
@jpodwys No worries at all, glad I could help!

**Comment by jpodwys** [comment]
@TimvdLippe Please try [this JS Bin](http://jsbin.com/rilupadazo/1/edit?html,console,output) in firefox. The main difference is that you'll need to right click rather than left click. (This is the actual issue I was experiencing, but I wanted to try distilling it down to the basics.) I'm happy to create a new issue if needed.

**Comment by TimvdLippe** [comment]
@jpodwys You need to wait for the HTML imports to trigger, else `Polymer` is not defined in browsers that do not have HTML imports. This JSBin seems to work in Firefox: http://jsbin.com/fuwakajihe/1/edit?html,console,output

**Comment by jpodwys** [comment]
Dang, you're right again. However, applying this change to my actual app makes no difference. I'll just keep digging.
