### ISSUE TITLE
"is" attribute in anchor

### ISSUE THREAD

**Issue by albertoZurini** [Polymer/polymer#5027]
I have something like this: `<a is="my-element" href="/path"></a>`
The only problem is that my-element is not rendered.
Obviously, `class MyElement extends Polymer.Element`.
Now I'm using a workaround (`window.location.href`), but it results in a page refresh when I click on the link.
How can I use the "is" attribute?

**Comment by TimvdLippe** [comment]
Per https://github.com/Polymer/polymer#v1-custom-elements : 

> Polymer will no longer produce type-extension elements (aka is="..."). Although they are still included in the V1 Custom Elements spec and scheduled for implementation in Chrome, because Apple has stated it will not implement is, we will not be encouraging its use to avoid indefinite reliance on the Custom Elements polyfill.

As suggested, surround a native element with a custom element via composition.
