### ISSUE TITLE
Unexpected token ILLEGAL - multiline problem in polymer.html

### ISSUE THREAD

**Issue by teek** [Polymer/polymer#504]
I've just updated today polymer by bower and got an 'Uncaught SyntaxError: Unexpected token ILLEGAL'. I'm actually using polymer in RoR.

Fixed for me in polymer/polymer.html by changing this lines: 
```
<link rel="import" href="layout.html">

<script src="polymer.js"></script>
<!--<link rel="import" href="../polymer-dev/polymer.html">--> 
```

to this

```
<link rel="import" href="layout.html"> \
<script src="polymer.js"></'+'script>
```

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

**Comment by ankurwase** [comment]
hey am still getting this issue.
Uncaught SyntaxError: Unexpected token ILLEGAL polymer.html

**Comment by tjsavage** [comment]
Hey @ankurwase, what exactly does the file look like that's causing this problem? This doesn't appear like a problem in Polymer. Also - are you using the latest [Polymer 1.2.3](https://github.com/Polymer/polymer/tree/v1.2.3)?
