### ISSUE TITLE
FlattenedNodesObserver Strange Behavior

### ISSUE THREAD

**Issue by hyyan** [Polymer/polymer#5045]
### Description
It hard to describe this issue, as I do not really understand it.  so I will just provide an example with the expected result.

### Element
The element will just observer new nodes and add it to an array 
```js
class TestinbgElement extends Polymer.Element {
      static get is() { return 'testinbg-element'; }
      static get properties() {
        return {
          items: {
            type: Array,
            value: []
          }
        };
      }

      connectedCallback() {
        super.connectedCallback();
        this.__observer = new Polymer.FlattenedNodesObserver(this.$.slot, (info) => {
          this._processNewNodes(info.addedNodes);
        });
      }

      disconnectedCallback() {
        super.disconnectedCallback();
        this.__observer.disconnect();
      }

      _processNewNodes(nodes) {

        nodes.forEach((node) => {
          if(node.nodeType === Node.ELEMENT_NODE) {
            this.push('items',node);
          }
        });

        console.log(this.items);
      }
    }
```
### Usage  

```html
 <testinbg-element>
       <div>I am content 1</div>
        <div>I am content 2</div>
  </testinbg-element>

<testinbg-element>
     <div>I am content 3</div>
      <div>I am content 4</div>
</testinbg-element>
```

## Expected result

Array >> (2) [div, div] // for the first element instance
Array >> (2) [div, div] // for the second element instance

## Actual Result

Array >> (2) [div, div] // for the first element instance
Array >> (4) [div, div , div , div] // for the second element instance

#### Live Repository 
https://github.com/hyyan/strange-behavior-FlattenedNodesObserver

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] IE 11

### Versions
- Polymer: v2.3.1
- webcomponents: v1.0.22

**Comment by TimvdLippe** [comment]
JSBin that shows the issue: http://jsbin.com/jurozobuja/edit?html,console,output

**Comment by hyyan** [comment]
Thanks @TimvdLippe I was just preparing one :)

**Comment by morbidick** [comment]
You need to change line 35 to `value: () => {return []}` so each instance gets its own array.

**Comment by hyyan** [comment]
@morbidick That's great , thanks , this will solve the problem
