### ISSUE TITLE
Buttons break inside dom-repeat

### ISSUE THREAD

**Issue by peardigital** [Polymer/polymer#5052]
### Description
Initially I was investigating a button in a dom-repeat unexpectedly firing on page load. 
It seems any call of a function inside dom-repeat causes this issue.
It doesn't matter if the value used is fixed like 3 or dynamic like text.$key

#### Expected Results
Console log should only appear on button press

#### Actual Results
Console log appears on page load. The button does not function again until page refresh.

### Steps to reproduce
```
<dom-module id="dwt-preset">
<template>
<template is="dom-repeat" items="[[comment]]" as="text">
<tr>
<td>[[text.$key]]</td>
<td><button on-tap="[[deletePreset(text.$key)]]">Remove</button></td>
</tr>
</template>
</template>
</dom-module>
```

```
deletePreset: function(k) {
                console.log('deletePreset: ', k);
            },
```

### Browsers Affected
At least Chrome, Firefox and Safari on Mac

### What are versions?
Tested on:
polymer#1.9 - 2 and polymer 2.3.1
webcomponentsjs#^v1.0.19 and webcomponentsjs#1.0.22

**Comment by web-padawan** [comment]
In order to get it working you should:
1. use `on-tap="deletePreset"` notation
2. change the `deletePreset` to look like this:
```js
deletePreset: function(e) {
  console.log('deletePreset: ', e.model.item);
},
```
See also [docs](https://www.polymer-project.org/2.0/docs/devguide/templates#handling-events) about handling events.

**Comment by TimvdLippe** [comment]
@web-padawan is correct. `on-*` listeners only accept a string and correspond to a method defined on the class with that name.
