### ISSUE TITLE
Properties are not initialised until element is connected?

### ISSUE THREAD

**Issue by 43081j** [Polymer/polymer#5053]
To reproduce this:

* Clone iron-ajax
* `polymer serve` it (or i suppose run `polymer test` or whatever)
* load the test page

The **shadyDOM** tests fail for me in latest chrome because the `completes` property is not yet defined (see [this block of code](https://github.com/PolymerElements/iron-ajax/blob/fd9fd3b7f6f4dca92358085ee0f9b4f783394410/iron-ajax.html#L477)).

This is **not specific to iron-ajax**, though.

Almost all of my tests, after conversion to 2x., fail unless i append the tested component to DOM beforehand.

Why is this? How has nobody else noticed this? Somehow iron-ajax tests pass in CI builds, so is it a recent Chrome change maybe?

It all works fine in native shadow DOM.

Stepping through it, i've noticed:

* when iron-ajax creates an `iron-request`, it is a `HTMLElement` immediately after
* if you append it to DOM while on the breakpoint, it suddenly becomes an `iron-request` with all its properties initialised
* [here](https://github.com/Polymer/polymer/blob/61d8c3e3a31b63dee5839a7a77c996824477ebb9/lib/mixins/properties-mixin.html#L203) we initialise all the properties in `connectedCallback`, so how did we ever expect anything to work before being appended to DOM? how does this even work in native shadow DOM? 

This is all very confusing but means my 2.x project does not work with polyfills enabled.

I don't quite understand how it never got noticed when we seem to explicitly enable properties in a connected callback... but also how it works in CI and not locally...

**Comment by TimvdLippe** [comment]
I am unable to reproduce this problem in Firefox and Chrome: http://jsbin.com/ninukipoye/edit?html,console,output @43081j could you supply a JSBin that shows the issue?

**Comment by 43081j** [comment]
@TimvdLippe i can't seem to reproduce in a jsbin, but i can by running the iron-ajax tests.

have you tried the steps in my original post? i have cloned iron-ajax on 3 systems now, run the tests the exact same way (`polymer serve`, go to `/test/`) and most of the shadydom ones fail.
