### ISSUE TITLE
Upgrade from Polymer @3.0.0-pre.3 to @3.0.0-pre.3 break my project due on comment block issue

### ISSUE THREAD

**Issue by tyohan** [Polymer/polymer#5056]
I have a project that previously ran well with 3.0.0-pre.3 and try to upgrade it to 3.0.0-pre.4. I've upgrade my project by ran `yarn upgrade` and change the template rendering on my elements to return html template literals instead a string. Then I ran my app and found some issues on other Polymer elements like app-header and paper-icon-button like shows below on console
![image](https://user-images.githubusercontent.com/106703/35190259-b4294ef2-fe8f-11e7-9589-7b8444183ab9.png)
Please ignore the Roboto.js not found issue.

The main issue was the comment block break the codes on element. Like show below on app-header element

![image](https://user-images.githubusercontent.com/106703/35190202-c699a33a-fe8e-11e7-88a0-384c7e665894.png)

The issue easily fix by change the block comment on line 121 to inline comment. Because that block actually still part of block comment. Similar thing also happen on paper-icon-button on line 116

![image](https://user-images.githubusercontent.com/106703/35190217-07f8b5b4-fe8f-11e7-9c9c-9750a72358b9.png)

Change the block comment to inline comment also fix the issue.

I'm not sure this issue is part of element or Polymer Modulizer.

**Comment by justinfagnani** [comment]
We have fixed this in modulizer already. It'll be in the next batch of elements.
