### ISSUE TITLE
Does not use passive listeners to improve scrolling performance

### ISSUE THREAD

**Issue by atifwaqar** [Polymer/polymer#5057]
![image](https://user-images.githubusercontent.com/4388707/35196975-9585814c-fed9-11e7-9584-1c5fc1a92bff.png)

### Description
On running an Auding (from Chrome DevTools), I get the above Failed Audit saying.  
Can this be cuz of something I am missing, or is this a known issue from Polymer side?

### Versions
- Polymer: v2.3.1

**Comment by merlinnot** [comment]
https://github.com/Polymer/polymer/pull/4829

**Comment by TimvdLippe** [comment]
This is indeed fixed by #4829. For more information, see https://www.polymer-project.org/2.0/docs/devguide/gesture-events#use-passive-gesture-listeners

**Comment by atifwaqar** [comment]
Thanks for the information @TimvdLippe  :)
