### ISSUE TITLE
Polymer.Templatize.templatize() is preserving forwardHostProp() function

### ISSUE THREAD

**Issue by mkorenko** [Polymer/polymer#5063]
Please see the reproduction here:
https://jsfiddle.net/exxe08ch/

Polymer.Templatize.templatize() is preserving forwardHostProp() function that is set on the first call.

As I can see, templatize() creates propagate effects only once for the first template's instance, then caches templatizeTemplateClass within the template element. (templatize.html:275)
As a result propagate effects are not recreated for new template's instances, forwardHostProp() function reference is preserved, and host property changes are not propagated to them.

Polymer: v2.3.1

**Comment by TimvdLippe** [comment]
Confirmed bug. Maybe #5035 fixes this issue or can be easily incorporated there. Else we have to do a deeper investigation

**Comment by kevinpschaaf** [comment]
Technically, this is working as intended, per the [docs](https://github.com/Polymer/polymer/blob/master/lib/utils/templatize.html#L485-L491):

> The class returned from `templatize()` is generated only once using the `options` from the first call. This means that any `options` provided to subsequent calls will be ignored. Therefore, it is very important not to close over any variables inside the callbacks. Also, arrow functions must be avoided because they bind the outer `this`.  Inside the callbacks, any contextual information can be accessed through `this`, which points to the `owner`.

The class caching ensures that metaprogramming and parsing are only done once for multiple instances. Templatizer was created for advanced use cases like `dom-repeat` so it's API is biased towards performance, not ergonomics.
