### ISSUE TITLE
Polymer 2.4

### ISSUE THREAD

**Issue by LarsDenBakker** [Polymer/polymer#5066]
I want to start using the html tagged template literal in production, it's merged to master but not released yet.

v2.4.0-rc.1 has been out for a month now, when is 2.4 going to be released?

**Comment by TimvdLippe** [comment]
Polymer 2.4.0 has been released yesterday (https://github.com/Polymer/polymer/commit/faad330092e5619b8ee25809dc5d8354b3008577) but the release (https://github.com/Polymer/polymer/releases/tag/v2.4.0) has not been tagged as-is. You should be able to install 2.4.0 with Bower and the docs will probably be updated after the weekend.

**Comment by LarsDenBakker** [comment]
I just noticed this myself as well. Thanks! :)
