### ISSUE TITLE
Observers called multiple times in inheritance chain

### ISSUE THREAD

**Issue by LarsDenBakker** [Polymer/polymer#5067]
### Description
I have two classes, `base-element` defines an observer and `my-element` extends `base-element` with no own properties. Both are placed in the dom with the property set. The observer of just `base-element` is called once. The observer of `my-element` (which was inherited from `base-element`) is called twice.

http://jsbin.com/wimozeravo/1/edit?html,console,output

Adding an empty properties set to `my-element` makes the observer fire only once:

http://jsbin.com/giniqeweco/1/edit?html,console,output

It seems that when a class in an inheritance chain defines a property observer, for each class in the inheritance chain that does not define a properties getter, the property observer is called once extra. 

This can be illustrated with mixins (which are just classes).

Here there are two mixins and a class. The first mixin defines an observer and the others don't define any properties. The observer is fired thrice: 

http://jsbin.com/hilularuce/1/edit?html,console,output

With empty properties it's fired once:

http://jsbin.com/domakayufu/1/edit?html,console,output

**Comment by LarsDenBakker** [comment]
I use this pattern a lot in my codebase, and I was thinking how this could possibly not have caused any issues for me before.

Then I realized that 2.4 just got released yesterday. After downgrading this issue no longer there, so it seems that this is a regression in the new PropertiesMixin. :(

I couldn't get the jsbin pointing to the 2.3.1 working.

**Comment by web-padawan** [comment]
I can confirm the issue, this is affecting us as well, especially by breaking observers used to set and then check some flags. See this [build](https://travis-ci.org/vaadin/vaadin-combo-box/builds/334048915) for `vaadin-combo-box` and the observer code [here](https://github.com/vaadin/vaadin-combo-box/blob/master/src/vaadin-combo-box-mixin.html#L239).

I quickly investigated and was able to reproduce it locally: adding `console.log` inside of the single property observer indicates that it does fire twice for the same old and new values.

**Comment by TimvdLippe** [comment]
Thanks for reporting! Did quite some digging, but I was able to figure it out. Fix up at #5068

**Comment by LarsDenBakker** [comment]
Thanks!

**Comment by TimvdLippe** [comment]
@LarsDenBakker #5068 will be reviewed by @kevinpschaaf and @sorvell and hopefully merged today 🎉

**Comment by LarsDenBakker** [comment]
When can we expect a 2.4.1? Checking so that I can plan accordingly for the release of our app.
