### ISSUE TITLE
Where is the polygit repository?

### ISSUE THREAD

**Issue by limonte** [Polymer/polymer#5072]
The spring cleaning is always nice, but I can't find the polygit repo anymore. It that project still maintained by Polymer team?

polygit.org was down couple of times today, but it seems there's no place to report issues anymore :/

GitHub supports the  repositories archiving: https://github.com/blog/2460-archiving-repositories

Please do not remove such important repositories in future, but archive them. Or at least transfer to https://github.com/googlearchive

**Comment by TimvdLippe** [comment]
Hm, I am actually not sure. I couldn't find it either. Since @sjmiles has the gist README on the homepage, do you maybe know where this code lives?

**Comment by kevinpschaaf** [comment]
I believe https://github.com/Polymer/polygit/tree/timeouts is the currently deployed version, so issues should report to https://github.com/Polymer/polygit/issues.

@justinfagnani Would you or someone on your team want to write up a quick readme on the master branch of the repo?

**Comment by justinfagnani** [comment]
https://github.com/Polymer/polygit is indeed the repo. I'll add a readme
