### ISSUE TITLE
Outdated documentation of dom-repeat

### ISSUE THREAD

**Issue by floribon** [Polymer/polymer#5077]
### Description
The documentation for dom-repeat is using Polymer 1.x syntax. This documentation is present as a JSDoc in the source file and being displayed at webcomponents.org. Happy to create a PR but as this touches public doc the team is probably better placed to review.

#### Live Demo
https://www.webcomponents.org/element/polymer/polymer/v2.4.0/elements/dom-repeat (or any 2.x.x version)

#### Expected Results
Usage of `<dom-repeat>` and Polymer 2 syntax to create a new component with `class EmployeeList extends Polymer.Element`

#### Actual Results
Currently displaying `<template is="dom-repeat">` and Polymer 1 syntax to create a new component using `Polymer({is: 'employee-list'})`

### Versions
- Polymer: v2.x

Note that dom-if would benefit of a similar documentation (missing example)

**Comment by TimvdLippe** [comment]
Hm I am not sure what the policy is for this. @arthurevans @katejeffreys Is the default notation ES6 or Hybrid mode?

**Comment by MajorBreakfast** [comment]
The official docs consistently use the new style.

https://www.polymer-project.org/2.0/docs/devguide/custom-elements
https://www.polymer-project.org/2.0/docs/devguide/dom-template
https://www.polymer-project.org/2.0/docs/devguide/observers

**Comment by TimvdLippe** [comment]
@MajorBreakfast Ah thanks for finding out. @floribon feel free to send a PR to update the documentation :smile:
