### ISSUE TITLE
Polymer 2.4.0 mangles CSS anchor URLs

### ISSUE THREAD

**Issue by justin-elliott** [Polymer/polymer#5080]
### Description
Polymer 2.4.0 mangles CSS anchor URLs, such as `clip-path: url(#cross)`.

#### Live Demo
https://plnkr.co/iHGaV8CUJaG2XWS2r6sz

#### Steps to Reproduce
1. Open the demo on Plnkr.
2. Inspect the frame.
3. Expand the `body`, each of `svg-element-2-3` and `svg-element-2-4`, their respective `#shadow-root`, and finally the `style` elements.
4. Observe the difference between the v2.3.1 and v2.4.0 `clip-path` entries.
  a. `svg-element-2-3`: `clip-path: url('#cross');`
  b. `svg-element-2-4`: `clip-path: url('https://run.plnkr.co/plunks/iHGaV8CUJaG2XWS2r6sz/#cross');`

#### Expected Results
The v2.4.0 Polymer code should produce the same url entry as v2.3.1.

#### Actual Results
The v2.4.0 Polymer code results in missing SVG rendering in many cases (although not in the Plnkr
example).

### Browsers Affected
- [x] Chrome
- [x] Electron 1.7.x
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v2.4.0

**Comment by azakus** [comment]
Hmm, the way your example is formatted won't work because Polymer can't be loaded twice like that.
I've forked the demo to correctly switch between Polymer 2.3.x and Polymer 2.4 here: https://plnkr.co/edit/vGrSfSXB2URcRyftWBqO?p=preview

Can you construct an example where this fails to work?

**Comment by kevinpschaaf** [comment]
This broke due to the change in #5024, which we'll revert for 2.5.0 per explanation in https://github.com/Polymer/polymer/pull/5081.
