### ISSUE TITLE
automatically generate a .gitignore when executed init.

### ISSUE THREAD

**Issue by sottar** [Polymer/polymer#5086]
### Description
I think that it is better to automatically generate a `.gitignore` file when `polymer init` is executed.
It's because in most cases we need to manually create `.gitignore` and write`bower_components` in it.

#### Steps to Reproduce
```
$ polymer init
# chose `polymer-2-application`
```

### Versions
```
$ polymer --version
1.5.7
```

**Comment by TimvdLippe** [comment]
This issue was moved to Polymer/polymer-cli#953
