### ISSUE TITLE
Include TypeScript definition file from Polymer v2.4 into v3

### ISSUE THREAD

**Issue by louis-bompart** [Polymer/polymer#5088]
Since 2.4 there are types files in Polymer which is great 👍 
However, they are not included in Polymer v3.

- Polymer: v3.0.0-pre.7
- webcomponents: v1.1.0

**Comment by ggirard07** [comment]
https://github.com/Polymer/gen-typescript-declarations/issues/18
https://www.polymer-project.org/blog/2018-01-25-polymer-2-4.html

> In the coming months, expect to see additional support for TypeScript, including typings for Polymer 3.0

**Comment by TimvdLippe** [comment]
@ggirard07 is correct, we are going to publish these times in the upcoming months.
