### ISSUE TITLE
Error "Cannot read property 'instanceCount' of undefined" when using importHref to load a page/element that doesn't exist

### ISSUE THREAD

**Issue by fasihrana** [Polymer/polymer#5092]
#### Steps to Reproduce
1. Create a simple Polymer App
2. Make use of importHref in any part of the element/app lifecycle as follows
```
this.importHref('this-page-doe-not-exist.html',
    null,
    function(err){
        console.log('page did not exist');
    },
    true);
```
You can use the Polymer Starter Kit as well.

#### Expected Results
The error callback is called to allow for correct callback handling.

#### Actual Results
The following exception is thrown
```
Uncaught TypeError: Cannot read property 'instanceCount' of undefined
    at HTMLElement.value (app.html:formatted:2145)
    at HTMLElement.c (app.html:formatted:474)
    at HTMLElement.d (app.html:formatted:672)
    at HTMLElement.h (app.html:formatted:825)
    at HTMLElement.r (app.html:formatted:1320)
    at HTMLElement.b (app.html:formatted:1971)
    at HTMLElement.f (app.html:formatted:2086)
    at HTMLElement.b (app.html:formatted:7103)
    at new j (VM21229 custom-elements-es5-adapter.js:4)
```

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v2.5.0
- webcomponents: v1.1.0

**Comment by jsilvermist** [comment]
I think this probably has to do with how you are redirecting the links to `index.html`, so it's importing `index.html` instead of what you intend if the file is missing. To remedy this, add an exception for a specific pattern, or for links using a file extension.

**Comment by fasihrana** [comment]
I figured this out. On my nginx server, instead of sending a =404 when a URL wasn't matched, I was sending back the index.html.

**Comment by fasihrana** [comment]
Closing.

**Comment by sacindia2000** [comment]
I am facing the same issue, can one of you please explain the exact solution. Thanks in advance
