### ISSUE TITLE
Properties outside the properties object

### ISSUE THREAD

**Issue by hadriann** [Polymer/polymer#5093]
### Description
The usage of properties outside of the properties object is not documented. From the docs:

_In most cases, a property that's part of your element's public API should be declared in the properties object._

It is implied that there are use cases when you need not declare a property in the properties object.

One such use case might be a component's private property (like a config), that is set by the component itself (not received via attributes), and passed down to one of its children.

There are a few questions regarding this:

1. Is the above scenario (or any scenario) a valid use case for outside-the-properties properties?
2. Will basic data binding work for such properties?
3. Will computed data binding work?
4. Will such a property be bound at the first render (ready) of the markup?
5. What is the best practice (Polymer-way) to declare or use such private properties?

**Comment by TimvdLippe** [comment]
@hadriann I think the section you are looking for is https://www.polymer-project.org/2.0/docs/devguide/properties#implicitly-declared-properties Does that clarify your questions enough?

**Comment by hadriann** [comment]
@TimvdLippe Thanks, mostly, yes. But the docs miss a short example there and polymer-ide complains about undeclared properties. Also, it's not transparent how implicit properties are treated before they are set, but I guess they should probably be set to a default in the constructor.

**Comment by TimvdLippe** [comment]
This issue was moved to Polymer/docs#2463
