### ISSUE TITLE
Consider adding user-defined attributes to slots

### ISSUE THREAD

**Issue by billmoser** [Polymer/polymer#5101]
I apologize in advance for my lack of proper terminology.  Here's the issue:  I have an element A, whose template has a slot.  I'd like to fill the slot with another element, B, annotated with attributes which can only be computed by A.  For example, A's template looks like this:
```
<slot name='myslot' cool-attr='Super Cool'></slot>
```
I would like to use element A like this:
```
<element-a>
  <element-b slot='myslot'></element-b>
<element-a>
```
with element B picking up the attribute cool-attr.
I don't see how to do this currently in Polymer.  I can achieve the effect I want easily with some code generation, but it would be great to see this as a 'native' Polymer feature

**Comment by TimvdLippe** [comment]
Thanks for the suggestion! Since Polymer relies on the shadow dom standard, such improvements should be discussed in the standard. You can open an issue at https://github.com/w3c/webcomponents/issues to discuss it with the browser vendors.
