### ISSUE TITLE
Migrate away from bower to yarn.

### ISSUE THREAD

**Issue by almereyda** [Polymer/polymer#5109]
### Description

Coming from https://github.com/Polymer/polymer/issues/4772#issuecomment-320433058, which unfortunately did not directly link to a verbose explanation like https://bower.io/blog/2017/how-to-migrate-away-from-bower/, we know that `bower` is deprecating itself and suggesting users to migrate away from it, i.e. to `yarn`. This issue covers the transitioning process and collects implied changes. As there was no current open issue about the subject, it is left here to revive the discussion.

#### Steps to Reproduce

When we scaffold a new Polymer project following [the Toolbox Set Up instructions](https://www.polymer-project.org/2.0/start/toolbox/set-up), we are asked to use Bower for maintaining dependencies.

#### Expected Results

In the future, we may want to be asked to set up Yarn accordingly.

- https://github.com/yarnpkg/yarn/issues/617#issuecomment-311868218
- https://github.com/bower/bower/issues/1520#issuecomment-364310202

#### Actual Results

@TimvdLippe said in https://github.com/Polymer/polymer/issues/4772#issuecomment-322957658

> this is not something we are going to change

### Browsers Affected

- none

### Versions

- all

**Comment by TimvdLippe** [comment]
#4772 discusses the change from our relative imports to absolute imports. In other words the change implies that Polymer bower_components are always in the root directory. This assumption is incorrect, so we can not make all our imports absolute.

Regarding the transition away from bower and adopting the npm ecosystem, that is tracked in https://github.com/Polymer/polymer/issues/326 More specifically, https://github.com/Polymer/polymer-modulizer/blob/master/docs/polymer-3-element-status.md contains the status of all our elements whether they are installable by npm (e.g. not with bower). Once the modulizer effort is finished, we have transitioned away from bower and can use npm.

Please subscribe to #326 to follow all updates.
