### ISSUE TITLE
Proposal: Change how MutableData mixin works

### ISSUE THREAD

**Issue by MajorBreakfast** [Polymer/polymer#5111]
Polymer's MutableData mixin currently applies on a per element basis. If an element implements this mixin, a different strategy is used for comparing objects. This makes it possible to announce changes in a very coarse manner: Instead of announcing that `myProp.a` changed, it suffices to announce that `myProp` changed, because with this mixin Polymer expects that any objects might have been mutated and takes this into account when comparing new and old values.

The current per-element approach has however a problem. Take this example:
https://codepen.io/MajorBreakfast/pen/XZMRJZ
There are 3 nested elements:
  - `outer = <x-outer>`
  - `between = <x-between>` with MutableData
  - `inner = <x-inner>`

Mutating the object `between.prop` by setting `between.prop.a = 'value2'` and calling then `notifyPath('prop')` only updates the value inside `<x-between>` itself. The other two elements are told about the change, but they discard it because they don't implement `MutableData`. They only see that the object is still the same and don't care that it was mutated.

I propose to change how the `MutableData` mixin works: It would be incredibly useful, if the system conveyed to the other elements it propagates the value to that they need to expect mutable data because it originated from an element that implements `MutableData`.

I've already looked at the code an I am confident, that this can be implemented with only minor changes. I could provide a PR if you're interested. What do you think?

### Versions
- Polymer: v2.x

### Related
- https://github.com/Polymer/polymer/pull/4839 This PR by @sorvell already partly implements this
- https://github.com/Polymer/polymer/issues/5094 Problem with `<dom-if>` that would disappear if this was changed

**Comment by MajorBreakfast** [comment]
Here's a more comprehensive demo which considers bindings to subproperties: https://codepen.io/MajorBreakfast/pen/VQpVVb

**Comment by MajorBreakfast** [comment]
I've thought a bit about this:

There are four combinations:
- Parent and child implement `MutableData`: This scenario works
- Parent and child both do not implement `MutableData`: This scenario also works. It's how Polymer works out of the box
- Child implements `MutableData`, parent does not: In this case, the parent won't pick up all changes that the child notifies. E.g the child changes `prop.a` and notifies that `prop` has changed. The parent won't react to the change, because the mutated `prop` object remains the same object. However this scenario is easy to fix: Just implement `MutableData` on the parent as well. 
- Parent has `MutableData`, child not: This case is the inverse of the above situation. The child won't pick up all changes that the parent notifies. E.g the parent changes `prop.a` and notifies that `prop` has changed. The child won't react to the change, because the mutated `prop` object remains the same object. This scenario has no simple fix. Implementing `MutableData` on the child as well isn't a workable solution, because the child element could be 3rd party code. Also, it makes no sense to implement `MutableData` on the child if there is no direct technical reason to do so inside the child element itself. Let's consider the other solution which is to remove `MutableData` from the parent and to announce all changes properly. This is solution isn't workable as well, because a change might not originate from the parent itself. Instead, the change might originate from the grandparent or another child element (which can be 3rd party) that implements `MutableData`.

Conclusion: Changing how elements with the `MutableData` mixin propagate data...
- Makes a lot of sense for parent -> child propagation
- Doesn't really make sense for child -> parent propagation (notify)

**Comment by sorvell** [comment]
Thanks for the thoughtful proposal. We generally agree with the concern and are going to look at ways to make this better. This is a pretty delicate subsystem and we'll need to review changes here very carefully. That probably makes a PR difficult, but we definitely welcome your input.

**Comment by sorvell** [comment]
After consideration, we've determined that there's too much risk of breaking user code if we change the core functionality around how data is passed between elements by altering how the `MutableData` mixin works. 

Instead, we recommend using immutable data patterns to have more control over how data propagates between elements. We plan to provide some helpers around working with immutable data, see: https://github.com/Polymer/polymer/issues/5126.
