### ISSUE TITLE
Cannot set case sensitive attributes with $=

### ISSUE THREAD

**Issue by KeithHenry** [Polymer/polymer#5114]
### Description
Setting an attribute with `$=` strips case information.

#### Steps to Reproduce
1. Create a new Polymer element
1. Add an attribute that relies on case, for instance `<svg viewBox$="[[calculateViewBox()]]">...` 

#### Expected Results
The result template should the attribute with case preserved, e.g. `<svg viewBox="0 0 50 50">...` 

#### Actual Results
Case information is lost, e.g. `<svg viewbox="0 0 50 50">...` 

Note that this specific example (`viewBox`) has already been raised in https://github.com/Polymer/polymer/issues/1831, but nothing has happened on that issue since 2016 - this is a more serious issue and `viewBox` is just an easily reproduced case.

Attributes in HTML are case sensitive, and Polyment needs to support that.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions
- Polymer: ^2.5.0

**Comment by TimvdLippe** [comment]
Polymer actually uses `Element.attributes` (https://developer.mozilla.org/en-US/docs/Web/API/Element/attributes) and that appears to be lowercasing the attribute names: http://jsbin.com/gigefehepo/edit?html,console,output This is working as specified in https://dom.spec.whatwg.org/#namednodemap
> If this NamedNodeMap object’s element is in the HTML namespace and its node document is an HTML document, then for each name in names:
Let lowercaseName be name, in ASCII lowercase.
If lowercaseName is not equal to name, remove name from names.

Given that Polymer does not do any special casing and uses the casing of the browser, I am not sure if we can do something about this.

**Comment by KeithHenry** [comment]
@TimvdLippe This might be a more general issue with `$=` syntax, as `Element.attributes` forces `viewBox$` to `viewbox`, but preserves `viewBox` without the `$` suffix.

Case sensitive attributes are unusual, but `viewBox` isn't the only case.

If this isn't something that can be fixed perhaps we need to update the documentation and provide a workaround (an `observer` that calls `setAttribute`)?

**Comment by TimvdLippe** [comment]
@KeithHenry It appears that it is not an issue with `$=`, but it will only have the correct capitalization if you use the exact literal of the attribute (e.g. `viewBox`): http://jsbin.com/tofiniyela/edit?html,console,output This means we have no control and knowledge whether the attribute is a property or not. We need some way to distinguish attributes from properties, but every textual way to distinguish these values removes the capitalization from the attribute name.

**Comment by kevinpschaaf** [comment]
I think you could override this method (e.g. add this to a mixin) to allow binding to e.g. `viewBox="[[...]]` (without the `$=`) as workaround this in the short term:

```js
static _parseTemplateNodeAttribute(node, templateInfo, nodeInfo, name, value) {
  if (name !== name.toLowerCase()) {
    name = name + '$';
  }
  super._parseTemplateNodeAttribute(node, templateInfo, nodeInfo, name, value);
}
```

**Comment by TimvdLippe** [comment]
@kevinpschaaf Yes that appears to work 🎉 http://jsbin.com/menehizilu/edit?html,console,output I will open a PR tomorrow to implement this solution as an optional mixin
