### ISSUE TITLE
CSS mixins unexpected side effects cause wrong styling 

### ISSUE THREAD

**Issue by freshp86** [Polymer/polymer#5120]
I am currently only able to reproduce this with SVG elements, but perhaps it can be reproduced otherwise too. The code pasted below:

* Defines a custom element that contains an SVG, and exposes a CSS mixin to style the SVG.
* Defines three custom elements `<box-a>`, `<box-b>` and `<box-c>`, and registers them with `customElements.define()` in that order. 
* `<box-a>` and `<box-c>` definitions are identical, but the final outcome is styled differently.

```html
<link rel="import" href="bower_components/shadycss/apply-shim.html">
<link rel="import" href="bower_components/polymer/polymer-element.html">

<dom-module id="child-element">
  <template>
    <style>svg { @apply --my-mixin; }</style>
    <svg width="200" height="100" viewBox="0 0 200 100">
      <rect width="200" height="100"/>
    </svg>
  </template>
</dom-module>

<dom-module id="box-a">
  <template>
    <style>
      :host { display: block; }
      child-element {
        --my-mixin: {
          fill: red;
        }
      }
    </style>
    <child-element></child-element>
  </template>
</dom-module>

<dom-module id="box-b">
  <template>
    <style>
      :host { display: block; }
      child-element {
        --my-mixin: {
          height: 50px;
          width: 100%;
        }
      }
    </style>
    <child-element></child-element>
  </template>
</dom-module>

<dom-module id="box-c">
  <template>
    <style>
      :host { display: block; }
      child-element {
        --my-mixin: {
          fill: red;
        }
      }
    </style>
    <child-element></child-element>
  </template>
</dom-module>

<box-a></box-a>
<box-b></box-b>
<box-c></box-c>

<p>Expected: The two red boxes should be exactly 200x100 exactly each, since
their dom-module templates are identical.</p>
<p>Actual: The 2nd red box size is wrong, because of mixin side-effects caused
by the black box element definition</p>

<script>
  class ChildElement extends Polymer.Element {
    static get is() { return "child-element"; }
  }
  customElements.define(ChildElement.is, ChildElement);

  class BoxA extends Polymer.Element {
    static get is() { return "box-a"; }
  }

  class BoxB extends Polymer.Element {
    static get is() { return "box-b"; }
  }

  class BoxC extends Polymer.Element {
    static get is() { return "box-c"; }
  }

  // This order affects the final outcome. If box-b is defined last, it works as expected.
  customElements.define(BoxA.is, BoxA);
  customElements.define(BoxB.is, BoxB);
  customElements.define(BoxC.is, BoxC);
</script>
```

Actual output (box-a and box-c have different size)
![actual](https://user-images.githubusercontent.com/7547039/36296780-e3784730-12a3-11e8-8ca6-c4a04f9d65a8.png)

Expected output (box-a and box-c are identical), achieved by moving `customElements.define()` call for  `<box-b>` to the end.
![expected](https://user-images.githubusercontent.com/7547039/36296848-3df3f04c-12a4-11e8-88d0-6972f47662be.png)

DevTools reveals the difference in styling between box-a and box-c as follows:
box-a instance
![box-a](https://user-images.githubusercontent.com/7547039/36296909-8a8e0eec-12a4-11e8-8dbd-ae0b4593f88a.png)

box-c instance
![box-c](https://user-images.githubusercontent.com/7547039/36296914-8d1f93ce-12a4-11e8-9356-7fae7314bf25.png)

The additional height/width properties in the mixin of `<box-c>` appear because of `<box-b>`'s usage of the mixin. Is it possible to eliminate such global side-effects?

@azakus: This could maybe be related to the fix that was applied for https://github.com/Polymer/polymer/issues/4486.

**Comment by adi130987** [comment]
I experience a similar/same issue. For example I have an element called `data-table-row` that has a css mixin `--list-row-wrapper` applied  on a `div` inside it's template.  `data-table-row` is used in 2 different and unrelated elements on the same page `element-1` and `element-2`. `element-1` defines the mixin like this:

```CSS
--list-row-wrapper: {
  padding: 0 24px 0 0;
}
```

`element-2` doesn't need it, but if I check it's rendered css I can see this:

```CSS
padding: var(--list-row-wrapper_-_padding, 24px);
```
