### ISSUE TITLE
Example jsbin has style outside template

### ISSUE THREAD

**Issue by LarsDenBakker** [Polymer/polymer#5140]
The issue template links to https://jsbin.com/luhaxab/1/edit?html,css,js,output

Which has:

```
    <style>
      :host {
        display: block;
      }
    </style>
    
    <template>
      <div>[[prop]]</div>
    </template>
```

That should be:

```
    <template>
      <style>
        :host {
          display: block;
        }
      </style>
      <div>[[prop]]</div>
    </template>
```

**Comment by TimvdLippe** [comment]
The first edit did have this issue, but the latest version (http://jsbin.com/luhaxab/edit?html,output) which is also linked in the CONTRIBUTING.md, has the style elements inside the template.

**Comment by LarsDenBakker** [comment]
Its in the issue template. There is a PR for it now!
