### ISSUE TITLE
null template should override inherited template

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#5148]
Currently, if an element extends a parent element that _has_ a template, there's no simple way to override that template and get an element with no template or shadow root.

```js
class ParentElement {
  static get template() { html`Haha! You're stuck with my template!`; }
}

class ChildElement extends ParentElement {
  // I don't want your template! Or anyone's template! Leave me alone!
  static get template() { return null; }
}
```

@kevinpschaaf suggested that an explicit falsey value like `null` should override the parent template. If the child template getter returns `undefined`, it will continue to inherit the parent template.

**Comment by kevinpschaaf** [comment]
I think we decided that this line can just move outside the conditional: https://github.com/Polymer/polymer/blob/master/lib/mixins/element-mixin.html#L314
