### ISSUE TITLE
Allow disabling of platform.js warning that it must be the first script

### ISSUE THREAD

**Issue by tfortes** [Polymer/polymer#515]
It often makes sense to have a first script that starts a timer or similar to allow accurate timing (e.g. Google Analytics).

The platform.js polyfill should probably only care about DOM-manipulating scripts, so perhaps either saying "I know what I'm doing" with some flag, or marking the "safe" scripts somehow.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
