### ISSUE TITLE
when release 3.0?  thanks!

### ISSUE THREAD

**Issue by mylovetop** [Polymer/polymer#5150]
when release 3.0?  thanks!

**Comment by TimvdLippe** [comment]
You can find this information our blog, with for example the latest 3.0 post https://www.polymer-project.org/blog/2018-01-18-polymer-3-new-preview.html

This post links to the public roadmap (https://github.com/Polymer/project/blob/master/Roadmap.md) and element status page (https://github.com/Polymer/polymer-modulizer/blob/master/docs/polymer-3-element-status.md) which show an overview of the progress.

Please follow the blog for updates and our Twitter account (https://twitter.com/polymer) to be notified when updates are published.
