### ISSUE TITLE
mutable-data is not working

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#5151]
### Description
`mutable-data` is not working (documentation: https://www.polymer-project.org/2.0/docs/devguide/templates#update-data)

#### Live Demo
https://jsbin.com/jocoqayoke/edit?html,output

#### Steps to Reproduce
1. Use `dom-repeat` with an array property and `mutable-data`
2. Mutate array
3. Call `notifyPath()` on array property

#### Expected Results
`dom-repeat` re-renders the list

#### Actual Results
Nothing happens

### Browsers Affected
- [x] Chrome
- [x] Firefox

### Versions
- Polymer: v2.5.0

**Comment by kevinpschaaf** [comment]
All elements between the mutated data change and consumption must apply the `MutableData` mixin/behavior.  You've property enabled the optional `mutable-data` setting on `dom-repeat`, but the mutation and `notifyPath` was initiated on `my-element`, which also needs `Polymer.MutableDataBehavior` applied.

https://jsbin.com/vapanuv/1/edit?html,output

**Comment by nazar-pc** [comment]
It doesn't seem to be mentioned in documentation at all. Maybe turn this into documentation issue?
