### ISSUE TITLE
Dom-repeat/dom-if in nested Polymer.html template does not render on IE11

### ISSUE THREAD

**Issue by LarsDenBakker** [Polymer/polymer#5155]
### Description
When using the new Polymer.html tagged template literal syntax, dom-repeat and dom-if don't work when they are used in nested templates.

I've spent some time debugging this, but could not find a clear cause. It is not related to es5 transpilation (such as https://github.com/Polymer/polymer-cli/issues/950). Possibly something to do with the template polyfill since IE11 is the only browser that requires it. 

#### Live Demo
Unfortunately glitch.com does not work on IE11 (They use spread syntax in their bundled code). On chrome it was endlessly on 'fetching projects'. 

I have a jsbin here, since it's a simple repro you could just copy paste the code into a local project:

https://jsbin.com/tecupowilu/edit?html,css,js,output

#### Steps to Reproduce
1. Create `my-element`
2. Create a template using Polymer.html template tag
3. Write a dom-repeat or dom-if inside that template
4. Create another template that is included by the top template
5. Also write a dom-repeat or dom-if inside the nested template

#### Expected Results
Both repeats/ifs are rendered

#### Actual Results
The nested repeat/if does not get rendered.

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11

### Versions
- Polymer: v2.5.0
- webcomponents: v1.1.0

**Comment by masonlouchart** [comment]
Is there a workaround?
