### ISSUE TITLE
connect/disconnect can occur too many times with certain polyfill configurations

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#5157]
If using native Custom Elements and ShadyDOM, a distributed element may connect + disconnect + connect when the host element is created and connected to the document. It's expected that the distributed element just connect once in this case. Consider:

```
<x-host>
  #shadowRoot
    <div><slot></slot></div>
  <x-child></x-child>
```

The `x-child` boots up and is connected, then the `x-host` asynchronously distributes and the `x-child` causing it to disconnect and re-connect. Normally when ShadyDOM and the custom elements polyfill are used together, this is handled.

Handling a host that customizes while connected may not be possible as compared with a host that customizes out of the document. Also, it may be necessary to address this with a mixin that specifically handles this behavior since it may not be possible to polyfill around native custom elements  behavior.

**Comment by TimvdLippe** [comment]
I think this should be solved with https://github.com/webcomponents/custom-elements/pull/62 ?

**Comment by sorvell** [comment]
No, this is when ShadyDOM is used without custom elements polyfill.
