### ISSUE TITLE
contenteditable attribute of a div hanging with document.execCommand and insertunorderedlist

### ISSUE THREAD

**Issue by stucker71** [Polymer/polymer#5158]
### Description
I'm writing a very basic WYSIWYG rich editor using `contenteditable`  attribute of a `div` but experiencing issues with `document.execCommand` and executing the command `insertunorderedlist`. If you select and highlight the text you want to insert an unordered list and click insert button then it either fails to work correctly using Chrome (latest version) or if using Safari (latest version High Sierra), just hangs. If you try this outside of Polymer (plain old html and javascript) it works fine. Here's the code:

```
<link rel="import" href="../../bower_components/polymer/polymer-element.html">

<dom-module id="polymerbasic-app">
  <template>
    <style>
      :host {
        display: block;
      }
    </style>

    <button on-click="_insertunorderedlist" type="button">Insert Unordered List</button>

    <div id="textBox" contenteditable="true">
      Bullet One
      <br> Bullet Two
      <br> Bullet Three
    </div>
  </template>

  <script>
    /**
     * @customElement
     * @polymer
     */
    class PolymerbasicApp extends Polymer.Element {
      static get is() { return 'polymerbasic-app'; }
      static get properties() {
        return {
          prop1: {
            type: String,
            value: 'polymerbasic-app'
          }
        };

      }
      _insertunorderedlist() {
        document.execCommand("insertunorderedlist", false, null); this.$.textBox.focus();
      }

    }

    window.customElements.define(PolymerbasicApp.is, PolymerbasicApp);
  </script>
</dom-module>
```

#### Steps to Reproduce
Select and highlight Bullet One, Bullet Two, and Bullet Three text and click on insert button using Safari or other browser.

#### Expected Results
html Unordered list.

#### Actual Results
Hangs, or does not behave correctly.

### Browsers Affected
- [ x] Chrome
- [ x] Firefox
- [ x] Edge
- [ x] Safari 9
- [ x] Safari 8
- [ x] IE 11

### Versions

- Polymer: v2.6.0
- webcomponents: v1.1.0

**Comment by TimvdLippe** [comment]
It appears that this is actually an issue with the implementation of shadow dom in the browsers, rather than a Polymer issue. Please see this JSBin (http://jsbin.com/muziyafuda/edit?html,console,output) that shows the issue in Chrome, where the non-shadow dom version (top) works, but the shadow dom version (bottom) does not work.

I have filed https://bugs.chromium.org/p/chromium/issues/detail?id=826406 for Chrome and https://bugs.webkit.org/show_bug.cgi?id=184049 for Safari, so the browser vendors can address this issue.
