### ISSUE TITLE
[Suggestion] for-of instead of for-loop

### ISSUE THREAD

**Issue by zaclummys** [Polymer/polymer#5160]
Would it be a good idea if Polymer adopted **for-of** instead of **for-loop** to iterate over arrays? [Babel](https://babeljs.io/docs/plugins/transform-es2015-for-of/#optimization) offers a plugin to convert it harmoniously without using iterators.

**Comment by TimvdLippe** [comment]
I am okay with these changes, although I have two comments:

1. Are there any performance characteristics associated with this change? We do not want to regress in terms of performance
1. Rather than doing this all at once, I propose we change these loops whenever we are changing the file anyways, to avoid cluttering our git history

**Comment by zaclummys** [comment]
**for-of** brings good features:
- iteration over array-like (**HTMLCollection**, **NodeList**, **Arguments**), iterators and generators.
- Faster than **Array#forEach**
- Readability
- [Async iteration](https://github.com/tc39/proposal-async-iteration)
- Can be compiled to **for-loop** and keep all theses features.

**Comment by sorvell** [comment]
Thanks for the suggestion. We love using **for-of** in application code, but within the library itself we generally manually iterate lists. 

We do this for speed and to avoid the extra compiled code. For example, a [simple for-of](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYewdgzgLgBAhjAvDA2gBgDQwIxYExYDMWALALoDcAUAGYgBOMAFADYCmsAljCDfAJQwA3lRgxQkEOwB0LEAHMmnftQC-QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=true&presets=es2015&prettier=false&targets=&version=6.26.0&envVersion=) balloons to 25 lines using babel.

**Comment by zaclummys** [comment]
@sorvell, check [this](https://babeljs.io/docs/plugins/transform-es2015-for-of/#optimization). **Babel** offers two features: compile as iterator or as for-in.

**Comment by zaclummys** [comment]
@sorvell, as mentioned above:

>  Babel offers a plugin to convert it harmoniously without using iterators.

Please, check [here](https://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=true&presets=es2015%2Cstage-0%2Creact&code=for%20(let%20a%20of%20%5B1%2C2%2C3%5D)%20%7B%7D%0A).
