### ISSUE TITLE
Polymer CLI, create clean element, tests fail after importing paper-button

### ISSUE THREAD

**Issue by vroegop** [Polymer/polymer#5162]
### Description
Tests are failing after importing `paper-button`. This also applies to `iron-icons`.

#### Full CLI Logfile
https://gist.github.com/vroegop/3fb30f63f79d39f0cac9248471c3b140

#### HTML file with faililng tests
https://gist.github.com/vroegop/5714db1340f56070cffed0e915774c21

#### Steps to Reproduce

> polymer init

> polymer test

All tests working.

> bower install paper-button

Import paper-button in HTML file.

> polymer test

All tests are working, but on Chrome one test is magically added and failing.

#### Expected Results

```
rvroegop@randy-ubuntu:~/IdeaProjects/polymer-test-remove-this$ polymer test
Installing and starting Selenium server for local browsers
Selenium server running on port 38149
chrome 65                Beginning tests via http://localhost:8081/components/polymer-test-remove-this/generated-index.html?cli_browser_id=0
chrome failed to maximize
chrome 65                Tests passed
[BABEL] Note: The code generator has deoptimised the styling of "unknown" as it exceeds the max of "500KB".
firefox 59               Beginning tests via http://localhost:8081/components/polymer-test-remove-this/generated-index.html?cli_browser_id=1
firefox 59               Tests passed
Test run ended with great success

chrome 65 (2/0/0)                       firefox 59 (2/0/0)
```

#### Actual Results

```
rvroegop@randy-ubuntu:~/IdeaProjects/polymer-test-remove-this$ polymer test
Installing and starting Selenium server for local browsers
Selenium server running on port 41143
chrome 65                Beginning tests via http://localhost:8081/components/polymer-test-remove-this/generated-index.html?cli_browser_id=0
chrome failed to maximize
chrome 65                ✖ Test Suite Initialization

  Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry
    <unknown> at   <unknown> at /bower_components/polymer/lib/elements/dom-module.html:137:0
    <unknown> at   <unknown> at /bower_components/polymer/lib/elements/dom-module.html:142:0

chrome 65                Tests failed: 1 failed tests
[BABEL] Note: The code generator has deoptimised the styling of "unknown" as it exceeds the max of "500KB".
firefox 59               Beginning tests via http://localhost:8081/components/polymer-test-remove-this/generated-index.html?cli_browser_id=1
firefox 59               Tests passed
Test run ended in failure: 1 failed tests

chrome 65 (2/0/1)                       firefox 59 (2/0/0)


Error: 1 failed tests

error:   cli runtime exception: Error: 1 failed tests
error:   Error: 1 failed tests
    at /home/rvroegop/.nvm/versions/node/v6.12.3/lib/node_modules/polymer-cli/node_modules/web-component-tester/runner/steps.js:170:27
    at next (native)
    at fulfilled (/home/rvroegop/.nvm/versions/node/v6.12.3/lib/node_modules/polymer-cli/node_modules/web-component-tester/runner/steps.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v2.6.0
- Web-component-tester: v6.0.0
- Polymer-cli: v1.6.0

**Comment by TimvdLippe** [comment]
> Import paper-button in HTML file.

Could you please attach the full test case, because it is probably an issue with how you import the file.

**Comment by vroegop** [comment]
[Travis builds can be found here](https://travis-ci.org/vroegop/quicktest).

I've tried to import `paper-button` like this:

```
<link rel="import" href="bower_components/paper-button/paper-button.html">
```
The element works, but console errors are shown and failing tests

```
<link rel="import" href="/bower_components/paper-button/paper-button.html">
```
The element works, but console errors are shown and failing tests

```
<link rel="import" href="./bower_components/paper-button/paper-button.html">
```
The element works, but console errors are shown and failing tests

```
<link rel="import" href="../bower_components/paper-button/paper-button.html">
```
The element does not work

```
<link rel="import" href="../../bower_components/paper-button/paper-button.html">
```
The element works, but console errors are shown and failing tests

```
<link rel="import" href="../../../bower_components/paper-button/paper-button.html">
```
The element works, but console errors are shown and failing tests

**Comment by vroegop** [comment]
It seems Firefox is also having issues now, I'm not sure why that didn't happen before. All of the above imports are broken there as well.

**Comment by TimvdLippe** [comment]
> bower install paper-button

This should be `bower install polymerelements/paper-button` instead. If you then add `<link rel="import" href="../../paper-button/paper-button.html">` to your test, it works.

I think what was happening is that Polymer was loaded twice, as the original URL fell back to `index.html`, which then would load your element twice. We will be adding a more descriptive error message in #5095 to make this clearer for users.

CC @kevinpschaaf @sorvell regarding another manifestation of this problem.
