### ISSUE TITLE
Controlled input elements

### ISSUE THREAD

**Issue by askbeka** [Polymer/polymer#5165]
Form inputs and other custom elements being developed using polymer, very often hold an internal state and to retrieve it, event listener or two way binding needs to be assigned.

In order to achieve full control over element one directional binding needs to be used in combination with  weird resetting logic in value change listener.

```html
<x-input id="input" value="[[value]]" on-value-changed="onValueChanged">
</x-input>

<script>
  ....
  static get is() { return 'x-input-parent' }
  ....
  onValueChanged({ detail: { value } } ) {
     if (this.value !== value) {
       this.$.input.value = this.value; 
      // needs a reset since if following logic won't update this.value,
      // input should represent state value not user input.
      this.onValueChange(value);
      // or...
      this.dispatch(new CustomEvent('change', { detail: { value } }))
     }
  }
</script>
```

Controlled elements/components are widely used by React community, which is optional feature. React detects when value is set by parent component, which makes input controlled, if not then internal state is used and warning shown if approach change from controlled to uncontrolled after initial set.

It is very useful feature if application consists of lots of form inputs, that are dependent on each others values.

One suggestion is to make elements that have properties passed in one directional way to be treated as readonly. It seems very logical if one way binding is used to pass the property element should not be able to update it even internally.

If it is implemented. Lots of elements already built have to consider cases when user has set value in one directional manner, and use different ways to notify the parent using events or onChange callback property.

```javascript
  onUserChange(value) {
     this.value = value;
     if (this.value !== value) { // one way binding is used
        if (this.onChangeRequest) {
           this.onChangeRequest(value);
        }
        // or..
        this.dispatch(new CustomEvent('change', { detail: { value } }))
     }
  }
```

It will improve lives of polymer community that uses centralised design to manage their forms.

As you can see it does not change much, it can be solved just by custom input elements authors. But since two way binding is assumed to be used in those elements and even if one way binding is used element won't crash since internal state is not really in sync with properties passed.

**Comment by TimvdLippe** [comment]
Hm, I am not sure if I follow. For example in your code you do `this.$.input = this.value`, but `this.$.input` is a reference to an element (namely the `x-input`) and not the actual value. If you wanted to update the value of the input, you should do `this.$.input.value = this.value`, but that is evident from the callback on `value-changed`.

Moreover, I do not really follow what the suggestion in this issue is. Could you give a full example of an API that should be implemented in Polymer and how that would actually be used?

**Comment by TimvdLippe** [comment]
Closing per above comment. Feel free to reopen if answers are provided to the above questions.
