### ISSUE TITLE
`dom-bind` and template binding erases nested templates content

### ISSUE THREAD

**Issue by tomalec** [Polymer/polymer#5178]
### Description
`<dom-bind>` or any other stamping erases content of all templates inside.

I suspect it does it, as it assumes it processed all `template is="dom-*` already, but the thing is, There are also non-Polymer templates.

```html
<dom-bind>
  <template>
    Template bellow should have `.content` once this text is stamped
    <my-element>
      <template is="mi-ne">
        <p>My content wasn't touched.</p>
      </template>
     </my-element>
  </template>
</dom-bind>
```
#### Live Demo
https://jsbin.com/yehicug/3/edit?html,console,output

#### Steps to Reproduce

1. Define `dom-bind` or `my-element`
2. Put template with some content inside elements template
3. Wait until element from 1. is stamped.
4. Check the `.content` of nested `template`

#### Expected Results
The content provided by author should be there.

#### Actual Results
`.content` is empty `DocumentFragment`

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions

- Polymer: v2.6.0
- webcomponents: v1.1.1

**Comment by TimvdLippe** [comment]
That is correct, as we use the content to compute the metadata required for the data-binding and event-listeners mechanisms. You can read more about this in https://www.polymer-project.org/2.0/docs/devguide/dom-template#preserve-template-contents You can set `preserve-content` to make sure Polymer does not "corrupt" the template.
