### ISSUE TITLE
When should an element expect all of its bound properties resolved?

### ISSUE THREAD

**Issue by mercmobily** [Polymer/polymer#5181]
Hi,

Sorry about the noise. I don't think I could post this anywhere else, and I hope it can help with documentation somehow.
My element is used like this:

            <hot-realtime-field save-url="/stores/users/{{routeData.contactId}}" preload-url="/stores/users/{{routeData.contactId}}">
              <paper-toggle-button id="remoteAccess" name="remoteAccess">Remote access</paper-toggle-button>
            </hot-realtime-field>

It's basically a decorator element which pre-loads data onto the child, *and* listens for changes committing them using the URL provided. If you are curious: https://github.com/mercmobily/hot-realtime-field

So, questions:

(1)
**At which point, in the element's life cycle, can I expect to have all bound properties actually resolved?**
Using `ready()` or `attachedCallback()`, I had huge problems as preloadUrl would be `/stores/users/` WITHOUT `routeData.contactId`.

(2)
At this stage, I am doing:

      ready () {
        super.ready()
        this.loaderRequest = this.$.loader
        this.preloaderRequest = this.$.preloader

        Polymer.RenderStatus.afterNextRender(this, () => {
          this._field = Polymer.FlattenedNodesObserver.getFlattenedNodes(this).find(el => el.nodeType === Node.ELEMENT_NODE)
          if (!this._field) {
            throw new Error('hot-realtime-field could not find the element to be decorated')
          }
          var f = this._field

          this._field.hotAsChecked = !!this._field._hasIronCheckedElementBehavior

          if (this.preloadUrl && !this._preloaded) {
            this.preloaderRequest.method = 'get'
            this.preloaderRequest.url = this.preloadUrl
            this.preloaderRequest.handleAs = 'json'

            // This will give users a chance to change the request if needed
            this.dispatchEvent(new CustomEvent('hot-realtime-field-before-preload', { detail: {}, bubbles: true, composed: true }))
            this.preloaderRequest.generateRequest()
          }
        })

**Is this "the" way?** That is, can I totally trust that `this.preloadUrl` ( which comes from `preload-url="/stores/users/{{routeData.contactId}}"`) is whole and done?

(3) 
**What's a better/best practice way of doing this?**

(4)
The element also listens to change events in the decorated element, and commits changes to the DB. The problem I had is that checkboxes tend to emit `checked-changed` when they are rendered. This causes an immediate (and erroneous) write onto the DB.
At the moment, I am doing this:

    connectedCallback () {
      super.connectedCallback()

      Polymer.RenderStatus.afterNextRender(this, () => {
        this._listenToField()
      })
    }
 
Where `this._listenToField()` will listen for changes
**Is this a good way to go about it?**

**Comment by mercmobily** [comment]
@arthurevans Hopefully some of these points can be cleared up in the docs -- especially the part about "when can I expect bound properties to be totally resolved"

**Comment by TimvdLippe** [comment]
Generally, if you need to "react" to data-changes, you should use an observer. In this case, in `hot-realtime-field`, put an observer on `preloadUrl`.

Properties are [initialized in the constructor](https://github.com/Polymer/polymer/blob/0d8b34e9732348e40e35f366d8611f14e57798af/lib/mixins/properties-changed.html#L166) and the initial bootup of properties is [in the `ready` callback](https://github.com/Polymer/polymer/blob/0d8b34e9732348e40e35f366d8611f14e57798af/lib/mixins/properties-changed.html#L169-L186). If you need to do initial setup work, I advise you to use the `ready` callback. If you need to update your internal state based on the input received from your parent, use an `observer`.

Now regarding the `routeData`, my assumption is that this comes from `app-route`? That element has a different timing, as it has to listen to URL changes. Therefore, if you need to wait on that completely, it is probably better to put the whole `preloadUrl` assignment in a computed binding and ignore all empty values of that property. That way the inner element will do nothing if `preloadUrl` is `undefined` and you explicitly set `undefined` in the parent if the route data is unavailable.

Does this answer/clarify your question?

**Comment by mercmobily** [comment]
Ah, now it's clear -- and obvious. I am proven stupid once again.

Since I have `preload-url="/stores/users/{{routeData.contactId}}"`, it means that the observer will be called once for `/stores/users/`, and then once for `/stores/users/4545` -- hot-realtime-field won't be able to tell which one is "empty" because neither one of them is.

I can require users of hot-realtime-field to write `preload-url="{{_url(routeData.contactId)}}"` but it's cumbersome.

This is what I am doing right now: https://github.com/mercmobily/hot-realtime-field/blob/d04b39bb99c996a73b8328f34e0c7eb8dceb2b02/hot-realtime-field.html#L466-L507

In short:

    ready () {
        super.ready()
        this.loaderRequest = this.$.loader
        this.preloaderRequest = this.$.preloader
        Polymer.RenderStatus.afterNextRender(this, () => {
          this._field = Polymer.FlattenedNodesObserver.getFlattenedNodes(this).find(el => el.nodeType === Node.ELEMENT_NODE)
          if (!this._field) {
            throw new Error('hot-realtime-field could not find the element to be decorated')
          }
   
          this._doPreload()
        })
      }

Is this not guaranteed to work? (that is, has app-route ALWAYS finished by the time I am in `Polymer.RenderStatus.afterNextRender`?

**Comment by TimvdLippe** [comment]
That would depend on the implementation of the element that supplies you the data-binding (in this case `app-route`). I think this should "just" work, but you do not have a guarantee. You could also split up the two values into 2 properties: one for the static part and one for the dynamic part. That way you have more control on what you actually want to listen to.

**Comment by mercmobily** [comment]
THANK YOU Tim, your help clarified everything. I have fixed hot-realtime-field so that it's totally 100% robust.
