### ISSUE TITLE
curly brackets in data binding delimiters not supported

### ISSUE THREAD

**Issue by andrelanger** [Polymer/polymer#5185]
It seems currently not possible to access array content within a data binding expression.
Example:

```
<dom-module id="x-weather">
 <template>
    {{weather.main.temp}}°C, {{weather.weather[0].description}}
    <iron-ajax
     auto
     url="http://api.openweathermap.org/data/2.5/weather" 
     last-response="{{weather}}">
    </iron-ajax>
  </template>

  <!-- ... -->

</dom-module>
```

The example results in the following output:

`20°C weather.weather[0].description`

André

**Comment by andrelanger** [comment]
I am not sure if it is similar and related to https://github.com/Polymer/polymer/issues/3527

**Comment by TimvdLippe** [comment]
You actually have to use `.0` instead of `[0]`. A working example: http://jsbin.com/wogurat/edit?html,output For more info see https://www.polymer-project.org/2.0/docs/devguide/data-binding#array-binding
