### ISSUE TITLE
Polymer LICENSE compatible with GitHub preview

### ISSUE THREAD

**Issue by abdonrd** [Polymer/polymer#5186]
It would be great if all the Polymer projects had a license compatible with the GitHub preview.

![repo-license-indicator](https://help.github.com/assets/images/help/repository/repo-license-indicator.png)

Also in the searchs:

![screen-shot-2018-04-10-at-19 44 36](https://user-images.githubusercontent.com/1007051/38573994-f3b54cc8-3cf7-11e8-95ad-865c893d0bcb.png)

Reference: [GitHub Help: Adding a license to a repository](https://help.github.com/articles/adding-a-license-to-a-repository/)

**Comment by TimvdLippe** [comment]
We have the `LICENSE.txt` in the root, but apparently GitHub wants it to be named `LICENSE` or `LICENSE.md`. I am not sure if we can change the extension without breaking our license thus far (as this url is referenced in our source code). We have to tread carefully here.

**Comment by abdonrd** [comment]
I find a related PR at https://github.com/Polymer/lit-html/pull/84

**Comment by abdonrd** [comment]
Also, thinking about the headers...

Other projects like React have a simpler version like:

```javascript
/**
 * Copyright (c) 2018-present, Google Inc.
 *
 * This source code is licensed under the MIT license found in the LICENSE file
 * in the root directory of this source tree.
 */
```

Instead of longer:

```javascript
/**
 * @license
 * Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
 * This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 * The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 * The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 * Code distributed by Google as part of the polymer project is also
 * subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
 */
```

I don't know if the Polymer projects if the Polymer projects could be simplified in that way.

**Comment by TimvdLippe** [comment]
At this moment in time, we are unable to change the license text/format for non-technical reasons. For future projects, we can hopefully adopt an approved license that is compatible with tools like GitHub.
