### ISSUE TITLE
Invalid argument crash in IE11 & Edge

### ISSUE THREAD

**Issue by rbjarnason** [Polymer/polymer#5191]
### Description
There is an Invalid argument crash in IE11 & Edge that causes a dialog not to appear and on IE11 seems to cause CSS problems.

![image](https://user-images.githubusercontent.com/43699/38778295-568d6eea-40a7-11e8-940a-c73e38725f8e.png)

#### Live Demo
Visit this website with Edge or IE11 https://yrpri.org/ 

#### Steps to Reproduce
Not known, only happens in IE11 or Edge 

#### Expected Results
No crash should happen

#### Actual Results
Invalid argument error

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11

### Versions
- Polymer: v2.6
- webcomponents: v1.2.0

**Comment by TimvdLippe** [comment]
It would be great if you could create a minimal reproducible case. That would significantly ease our debugging process :smile:

**Comment by rbjarnason** [comment]
Sure, but then I would most likely also find the cause of the problem myself ;) I will continue to debugging this but creating minimal reproducible cases are hard from big apps. In the meantime if anybody has any hints then that would be great!

**Comment by rbjarnason** [comment]
I have tracked it down to my new and edit dialogs for example to create and edit communities. They work without an error when I add a new community but get this error when I edit the community with the same dialog so must have something to do with data bindings. Here is an example of a dialog that is broken. https://github.com/CitizensFoundation/your-priorities-app/blob/master/client_app/src/yp-community/yp-community-edit.html

**Comment by rbjarnason** [comment]
Another clue is that if I first fire up the dialog in new mode and then I use it in edit mode then the error does not happen. This is especially strange as yesterday I wrapped all our dialogs in dom-if restamp so they would only be a part of the dom when being used.

**Comment by rbjarnason** [comment]
@TimvdLippe I tracked it down and its fixed! Turns out that this was really an invalid argument in IE11. I was trying to set method to PUT on an native form element. I have my own version of iron-form that uses PUT for my restful APIs and I accidentally had added this parameter also to the native form in the new Polymer 2 iron-form setup. Thanks again for all your help.

**Comment by TimvdLippe** [comment]
Glad to hear it is not an issue with polymer or the polyfill :)
