### ISSUE TITLE
Polymer App crashes on mobile

### ISSUE THREAD

**Issue by ThibzThibz** [Polymer/polymer#5192]
### Description
Polymer App crashes on mobile using Chrome Browser, and cannot see any errors in console when debugging remotely.

We are building an ERP like application using polymer components, so we created and use a lot of custom components and behaviors.
Recently, after adding new behaviors to a component, we noticed that our web-app crashes when loaded with Chrome on mobile devices. But everything works fine on desktops. BTW, we tried to load it on mobile using Firefox : the app didn't crash and render some elements.
What I mean by "the app crashes" is that an "Aw snap!" error page is displayed (and DevTools remote debugging connection is closed), but cannot see any error in console.
We also tried the suggestions (cache cleaning, private tab...) but there was no change.
It doesn't seem to come from a specific behavior we implemented as it works fine on Desktop.
To be a bit more precise, we import a behavior in a component, which itself imports other behavior :
 
MyBehaviorImpl = {
   ///some functions declared here
};
MyBehavior = [ 
    MyBehaviorImpl,
    ///other behaviors declared here
];

We tried to determine if one of the behaviors declared here was causing this issue by removing HTML import tag and declaration in 'MyBehavior' array. But no behavior in particular seems to be the cause.
Actually, when declaring up to 12 behaviors here, our App works fine, but when adding another behavior (and whatever the behavior we add) the crash occurs on mobile devices.

Is there any limitations about behaviors registration ?

I hope I've been clear enough for you to understand this issue ; I'm sorry I can't provide relevant code of the web-app. 
Any help or informations would be very appreciated.

Thx !

### Browsers Affected
- [x] Chrome

### Versions
- Polymer: v2.5.0
- webcomponents: v1.1.0

**Comment by web-padawan** [comment]
Should be the same as vaadin/vaadin-grid#1234 (except that we are using mixibs). See the chromium bug link in that issue.

The bug has been fixed and rolled out to desktop Chrome 65 but tge fix will be only shipped for mobile Chrome 66.

**Comment by ThibzThibz** [comment]
Thank both of you for the reply !
@web-padawan : your comment was very instructive. I just tried the beta version of Chrome 66 for Android and no more errors, the web app is rendered as expected.

We hope that this next version of Chrome for mobile will be release soon. ^^ 

Thank you all !

**Comment by TimvdLippe** [comment]
Thank you @web-padawan for the link. Glad that this issue has been fixed in Chrome and sorry @ThibzThibz that this issue occured in your web application :cry:
