### ISSUE TITLE
Style modules in main document not found under certain ordering scenarios (Chrome only)

### ISSUE THREAD

**Issue by dlockhart** [Polymer/polymer#5196]
### Description
With Polymer 2, when you include a style module into the main document (via `<style include="my-module">`) under certain scenarios (described below), the style module will not be found.

#### Live Demo

https://jsbin.com/cuhisuzosa/edit?html,console,output

Link to the gist that's being imported:
https://gist.github.com/dlockhart/a044505509a9d923a05d255d849469e0

#### Steps to Reproduce

1. Create a style module
2. Create a basic custom element
3. Put both the style module and custom element into a single HTML import file -- similar to what a bundled `polymer build` might produce. **Important**: the style module must be defined **second** in the import.
4. In the main document, import Polymer and your "bundle" containing the custom element and style modules.
5. In the main document, include the style module using `<custom-element><style include="my-module"></style></custom-element>`. This technique is described [in the Polymer documentation](https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom#style-modules), as well as @notwaldorf's [awesome cheat sheet](https://meowni.ca/posts/polymer-2-cheatsheet/#style-modules).
6. In the main document, put an instance of the custom element somewhere.
7. Optional: include something in the main document to indicate whether the style module is getting applied or not.

#### Expected Results
Style module is properly included in the document and there are no console warnings or errors.

#### Actual Results
Style module is not applied and console contains the following warning:
> Could not find style data in module named your-module-name

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 10
- [ ] IE 11 (didn't test as it would require transpiling to ES5)

### Versions
- Polymer: v2.6.0
- webcomponents: v1.2.0 

### Analysis
Any of the following resolves this issue:
- Define the style module _before_ the custom element in the import file
- Do not include an instance of the custom element (or any custom element) in the main document
- Add a single script in the `<head>` after the HTML imports (very strange... the render-blocking script must force Chrome to process something) 

Walking through the code originating from the console warning, it appears as though when the custom element gets defined, it eventually calls into `custom-style`'s [getStyle()](https://github.com/Polymer/polymer/blob/master/lib/elements/custom-style.html#L80) method, which does a `this.querySelector('style')` before passing the results of that to `cssFromModules()`. That querySelector is finding the `<style include="my-module">` from the main document, even though it has nothing to do with the custom element. Since that module hasn't been defined yet, it results in an error.

**Comment by jarrodek** [comment]
I have a similar issue but different condition.

1. Add a web component to the regular web page (not polymer app)
2. Load webcomponents.js + bundle generated with `polymer build` (tested on es6-bundle)
3. After all is loaded add manually custom element to the DOM.

The element that was already in the DOM before bundle was loaded is not styled according to the style definition included in the bundle.
The element inserted to the DOM manually after bundle is loaded renders perfectly.

When calling `updateStyles({})` on the element that is in the DOM before in the beginning updates the styles properly when bundle is loaded.

Maybe I am doing something wrong? But my understanding is that this is how it should work.

This issue occurs in Chrome but not in Firefox and Safari.
