### ISSUE TITLE
this.offsetWidth is always 0 if the element is rendered inside a slot on Firefox.

### ISSUE THREAD

**Issue by LorenzoFerri** [Polymer/polymer#5203]
### Description
If I try to get the actual width in pixel of an element using `this.offsetWidth`, in case the element is rendered inside a slot it return 0.

#### Live Demo
I couldn't setup a live demo, but I created a basic repo that show the problem.

https://github.com/LorenzoFerri/test

#### Steps to Reproduce
1. Create `container-element` and add a `<slot></slot>` in his template;
2. Append `container-element` to the body.
3. Create `inner-element`.
4. On the `connectedCallback()` display the width of the element:
```
connectedCallback() {
                super.connectedCallback();
                console.log(this.offsetWidth);
            }
```
5. Append `inner-element` into `container-element`:
```
    <container-element>
      <inner-element></inner-element>
    </container-element>
```

-->

#### Expected Results
The width in pixel

#### Actual Results
Always 0

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v2.6.0
- webcomponents: v1.2.0

**Comment by TimvdLippe** [comment]
This is an issue with the polyfill. Live reproduction without Polymer: http://jsbin.com/nodokilejo/1/edit?html,console,output You can toggle the script tag to see the difference, even in Chrome.

**Comment by TimvdLippe** [comment]
This issue was moved to webcomponents/shadydom#233

**Comment by jsilvermist** [comment]
I had a similar problem, I fixed it by putting the call for `offsetWidth` inside a `requestAnimationFrame`. Not sure if this is the same problem exactly, but it seems similar as it worked on Chrome without, but needed the RAF for Edge and Firefox.
