### ISSUE TITLE
Problem with re-evaluation of computed property bindings with long data path

### ISSUE THREAD

**Issue by rogerta** [Polymer/polymer#5206]
### Description
Problem with re-evaluation of computed property bindings with long data path.

#### Live Demo
https://run.plnkr.co/plunks/Iu35qIqWhtr8PfT4M8tn/

#### Steps to Reproduce
See live demo:
1. Create an element with a Object type data property.
2. Place the element in a document and use a computed binding to bind the property to an object.
3. Change a sub-property of the bound object.
4. Make sure the computed binding is re-evaluated.

#### Expected Results
The computed binding is re-evaluated.

#### Actual Results
The computed binding is re-evaluated only when the data path to the changed sub-property is short.  When the data path is long, the computed binding is not re-evaluated.  This can be seen in the live demo by clicking the buttons: 

Clicking the button "Change short property" logs a message to the console.

Clicking the button "Change long property" should also log a message to the console, but does not.

I think the problem is in [property-effects.js at line 540](https://github.com/Polymer/polymer/blob/3.0-preview/lib/mixins/property-effects.js#L540).  The comment right above explains what the if condition does: it seems designed to handle bindings of the form `foo="{{obj.sub}}"`.  However, it does not handle computed bindings of the form `foo="{{bar(obj.sub)}}"`, since it does not take into account the prefix `"bar("`.  According to the specs, [computed bindings are allowed](https://www.polymer-project.org/2.0/docs/devguide/data-binding#binding-annotation).

If `path` happens to be shorter than `part.source`, the right thing will happen anyway.

If this is a bug, then it likely [exists in v.2.6.0](https://github.com/Polymer/polymer/blob/v2.6.0/lib/mixins/property-effects.html#L571) too.

### Browsers Affected
- [x] Chrome 66.0.3359.117 (Official Build) (64-bit)
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v3.0.0-pre.12 and v2.6.0
- webcomponents: v1.2.0

**Comment by rogerta** [comment]
@kevinpschaaf you had discussed this issue with Kate in April.  Does this seem like an appropriate fix?

**Comment by ryangreenhill** [comment]
The underlying cause of this is path.translate. 

`translate: function(base, newBase, path) {
      return newBase + path.slice(base.length);
},`

Thus, when you try to bind to attribute (newBase), with a longer path than base, you end up trying to change 'attribute + X characters of path'.

The `&& !part.signature` worked for my issue (2.6), thanks for that.
