### ISSUE TITLE
Add `version` info to 3.x branch

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#5211]
There's currently no replacement for `Polymer.version` in the 3.x branch. 

Perhaps we can put this as a static property on the `PolymerElement` class.

**Comment by TimvdLippe** [comment]
I think we should put this in https://github.com/Polymer/polymer/blob/master/lib/utils/boot.js instead? I would be fine with doing `Polymer.version = '3.0.0'` there

**Comment by web-padawan** [comment]
@sorvell @TimvdLippe is this still planned? Should be a small change. We are preparing stable releases of Vaadin components and would like to have this kind of a flag, so that we could drop weird checks we have now, and identify which version of Polymer is used with our components.
