### ISSUE TITLE
Property changed event not fired if old and new values are both falsy

### ISSUE THREAD

**Issue by shawncplus** [Polymer/polymer#5213]
### Description
I have a `paper-input` bound to some property. That property's value is `0`. The input is _correct_ shown to be value `0`. I focus the field and backspace the `0` and the field is now empty. Because of this line https://github.com/Polymer/polymer/blob/1.x/src/lib/bind/accessors.html#L236 I do not get a `<my-property>-changed` event notification

A possible fix is simply changing the `!=` to a `!==` but I worry that could cause very strange behavior in some people's applications.

#### Live Demo

https://jsbin.com/gucacokuto/1/edit?html

#### Steps to Reproduce

In the demo you can reproduce this: On fresh page load, the input should be 0. Focus the input and backspace, input will be empty but no alert will be shown. Enter in a new value, alert will show new value. Backspace this value, you will get an alert with empty as the value. If you put in 0 in the input again then backspace you will get an alert. This seems strange at first but that's because the value is actually `"0"`, _not_ `0`

#### Expected Results
Expected to get a change notification when a value goes from integer `0` to `""`

#### Actual Results
No change notification is given

### Browsers Affected

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v1.11.0

**Comment by TimvdLippe** [comment]
I dont think we are updating Polymer 1 with these kind of changes. Does
this bug still occur with Polymer 2?

**Comment by shawncplus** [comment]
@TimvdLippe no idea, don't use v2. @kevinpschaaf told me to drop in an issue after I brought it up in Slack

**Comment by shawncplus** [comment]
My workaround, for anyone else that runs into this problem, is to have the input bind to a dummy value, when that value is updated either by a Polymer `-changed` event or a Plain Old DOM Event™️ keyup on the input element I send the value to a debounced function that will actually propagate the value to the real property I want to update. It's a bit of a circumambulation but it gets the job done.

Like so:

```html
<input is="iron-input" bind-value="{{_proxyValue}}" on-keyup="_handleInputChange">

// ...

<script>

// ...

properties: {
  _proxyValue: {
    type: Number,
    observer: '_handleProxyValueChange',
  },
  valueObject: {   // real object I want to update
    type: Object,
    notify: true,
  },
},

// initially set the _proxyValue to the real value
observers: [
  '_valueObjectValueChange(valueObject.value)',
],

_valueObjectValueChange(newValue) {
  this._proxyValue = newValue;
},

// called when we get a real Polymer change event
_handleProxyValueChange(newValue) {
  this._pendingValue = newValue;
  this.debounce('valuechange', this._forwardChangeEvent, 100);
},

// called both when we get a proper polymer change event and a PODE but the debounce will handle the problem of calls stacking up
_handleInputChange(e) {
  const newValue = e.target.value;
  const cleanedValue = newValue === '' ? null : newValue;
  this._pendingValue = cleanedValue;

  this.debounce('valuechange', this._forwardChangeEvent, 100);
},

_forwardChangeEvent() {
  this.set('valueObject.value', this._pendingValue);
},

// ...

</script>
```
