### ISSUE TITLE
Small link typo in Data Bindings section of docs

### ISSUE THREAD

**Issue by GregS2** [Polymer/polymer#5216]
Typo in the link to Compound Bindings in the paragraph "Binding to a target property":
Existing link: https://www.polymer-project.org/2.0/docs/devguide/data-binding#compound-binding
Correct link: https://www.polymer-project.org/2.0/docs/devguide/data-binding#compound-bindings
(the link in the ToC over on the right works)

**Comment by TimvdLippe** [comment]
This issue was moved to Polymer/docs#2568
