### ISSUE TITLE
Missing packages on npm @polymer

### ISSUE THREAD

**Issue by hekod777** [Polymer/polymer#5220]
I was trying move from bower dependencies to npm for a polymer 2.0 spa.

When I tried to run `polymer serve` I was getting a few errors regarding files not found

```
@polymer/prism
@polymer/marked
@polymer/shadycss
@polymer/hydrolysis
```

I checked npm registry that all these 4 packages are not available under `@polymer`

I'd like to know should would be the best approach here.

and...

When will polymer 3 be will out?

**Comment by TimvdLippe** [comment]
We do not own these packages, so they are not under the Polymer scope. For example prism is published under prismjs: https://www.npmjs.com/package/prismjs which should be converted by the modulizer based on this map: https://github.com/Polymer/polymer-modulizer/blob/9d5482bceb4646a940eb15f30b7c01d5a0e9da1f/dependency-map.json#L242-L245 For the other dependencies, please check that map as well (or just use the modulizer to automate this process).

Polymer 3 has been published today 🎉
