### ISSUE TITLE
is not a function in polymer issue

### ISSUE THREAD

**Issue by avix89** [Polymer/polymer#5225]
Hey

I am using polymer framework for my project in which i'm declaring a function callback in properties and trying to call it from another function .But on accessing it i'm getting an error

Uncaught TypeError: this.callback is not a function
Please have a look into this.
```

Polymer({
  is: "parent-dom",
  properties: {
    people: {
      type: String,
      value: "df"
    },
    item: {
      type: String,
      value: "asdf",
      notify: true
    },
    callback: {
      type: Object,
      value: function(index) {
        console.log("Inside  callback function");
      }
    },

  },
  showTargetColorDialog: function(e) {
    this.callback("sadf");
  }
});
```

**Comment by web-padawan** [comment]
As mentioned in the declaring properties [documentation](https://www.polymer-project.org/3.0/docs/devguide/properties#configure-values), setting value to function is used to evaluate the default property value. So if you want it to be a function again, make sure you also return a function as a value, e. g. like this:

```js
callback: {
  type: Function,
  value: function() {
    return function (param) {
      console.log("Inside  callback function");
    };
  }
}
```

You can also pass callbacks inside of the child components using one-way data binding. See the example of this pattern [here](https://github.com/OWOX/brainy-table/blob/master/brainy-table.html#L486).

**Comment by TimvdLippe** [comment]
@web-padawan is correct. You need to wrap it in another function, as explained in the docs.

**Comment by avix89** [comment]
Thanks it helped :+1:
