### ISSUE TITLE
Polymer 3 Doc Issue with styling

### ISSUE THREAD

**Issue by equinusocio** [Polymer/polymer#5229]
### Description
Hi, I noticed a wrong example on the documentation, inside the styling section:
https://www.polymer-project.org/3.0/docs/devguide/style-shadow-dom#style-slotted-content-distributed-children

It show a slotted `h1` inside another `h1` in the element shadow root (the [plunker link](http://plnkr.co/edit/jMjMAY?p=preview) is correct)

I know that is just an example, but it may pass as a "good practice"

#### Live Demo
https://www.polymer-project.org/3.0/docs/devguide/style-shadow-dom#style-slotted-content-distributed-children

![screen shot 2018-05-10 at 15 21 33](https://user-images.githubusercontent.com/10454741/39871763-2545fd84-5466-11e8-9269-4a4e09a37dbd.png)

#### Expected Results
H1 should not putted inside another H1.

**Comment by TimvdLippe** [comment]
This issue was moved to Polymer/docs#2601
