### ISSUE TITLE
Dual llistbox in polymer

### ISSUE THREAD

**Issue by sudipta1411** [Polymer/polymer#5234]
Hi,
I want to know is there any dual list box available in polymer 2.0 as shown in the figure
![slb3e](https://user-images.githubusercontent.com/1386911/40079570-f3958c3e-58a5-11e8-982c-a873c3fe9a75.png).
It seems plausible that this can be built using `paper-listbox`. I just want to know if any such component is already available.
Thank you.

**Comment by TimvdLippe** [comment]
We have no ready-made solution for this and I am not aware of any plans in doing so. Feel free to implement one yourself 😄
