### ISSUE TITLE
CSS mixins seem to leak into other element instances.

### ISSUE THREAD

**Issue by trading-peter** [Polymer/polymer#5236]
### Description
CSS mixins seem to be falsely applied to other element instances. I try my best to explain what I mean by that:

You define a element that has a css mixin applied in it's :host selector. Like in the [demo](https://glitch.com/edit/#!/great-hourglass?path=inner-element.html:9:29):

**inner-element.html**
```css
:host {
  padding-bottom: 20px;      
  @apply --inner-element;
}
```

The inner-element defines a "default" for padding-bottom of 20px.  
Now we define a second element called `parent-element` and use `inner-element` in it's shadow dom.  
The parent-element uses the `--inner-element` mixin to override the padding property (not padding-bottom, but padding) like so:

**parent-element.html**
```html
<template>
    <style> 
      inner-element {
        --inner-element: {
          padding: 0;
        }
      }
    </style>
    <div>
      Parent
    </div>
    <inner-element>Inner element: My parent sets padding to 0</inner-element>
</template>
```
The outcome is as expected: The inner-element no longer renders with a padding at the bottom because parent-element set it to 0.

Now we define a third element called `another-parent-element` that also has a `inner-element` instance in it's shadow dom. It basically the same as with `parent-element` but **without** the use of the `--inner-element` mixin. That means `another-parent-element` lets the default padding-bottom value of `inner-element` as defined.

**another-parent-element.html**
```html
<template>
    <style>
      /* We don't use the --inner-element here */
    </style>
    <div>
      Parent
    </div>
    <inner-element>Inner Element: My parent doesn't mess with my padding. So I should have padding at the bottom.</inner-element>
</template>
```

The expected outcome is that `inner-element` of `another-parent-element` has padding at the bottom.  
The actual outcome is that the padding is gone here as well. It seem that the mixin usage in the styling of `parent-element` is applied inside of `another-parent-element`.

Or maybe I got totally wrong how native css properties / polymers mixin system works...

#### Live Demo
https://glitch.com/edit/#!/great-hourglass?path=index.html:1:5

#### Steps to Reproduce
Just open the glitch project and look at the output. I tried to describe the expected outcome here as well.  
If you remove or comment out the `parent-element` in index.html the `inner-element` of `another-parent-element` get's its padding back. As soon as `parent-element` is present the mixin seems to leak into the styling scope of `another-parent-element` and therefore setting padding-bottom of `inner-element` to 0px.

### Browsers Affected

- [x] Chrome with native css properties
Sorry, didn't test with other browsers or configurations jet.

### Version
- Polymer: v2.3.1

**Comment by freshp86** [comment]
Also other similar bug report about mixins leaking across elements that use them, is at https://github.com/Polymer/polymer/issues/4254.

**Comment by AlbertoFdzM** [comment]
Reproduced in `Polymer v2.6.1` with Chrome 69, Safari 12 and Firefox 62

**Comment by joshcartme** [comment]
I'm seeing a similar issue.  You can check it out here, https://jsfiddle.net/y5j8oe3z/5/

Here's the full code for discussion
```
<base href="https://polygit.org/polymer+polymer+v2.6.1/webcomponentsjs+webcomponents+v1.2.7/components/">

<script src="webcomponentsjs/webcomponents-lite.js"></script>
<!-- Load the Polymer.Element base class -->
<link rel="import" href="polymer/polymer.html">

<my-element></my-element>

<dom-module id="my-element">
  <template>
    <style>
      div.other {
        --special-div-rules: {
          background-color: orange;
        }
      }
    </style>
    <div class="normal">
      <my-inner-element></my-inner-element>
    </div>
    <div class="other">
      <my-inner-element></my-inner-element>
    </div>
  </template>
</dom-module>

<dom-module id="my-inner-element">
  <template>
    <style>
      div {
        background-color: yellow;
      }
      div.special {
        @apply --special-div-rules;
      }
    </style>
    <div class="special">
      I might be special.
    </div>
  </template>
</dom-module>

<script>
class MyElement extends Polymer.Element {
  static get is() {
    return 'my-element';
  }
}
customElements.define(MyElement.is, MyElement);

class MyInnerElement extends Polymer.Element {
  static get is() {
    return 'my-inner-element';
  }
}
customElements.define(MyInnerElement.is, MyInnerElement);

</script>
```
I would expect `my-inner-element` in the `.normal` div to have a yellow background and the one in the `.other` div to have an orange background.  But what happens is the one in the `.normal` div gets no background because it ends up with a style rule like:
```
div.special {
    background-color: var(--special-div-rules_-_background-color);
}
```
`--special-div-rules_-_background-color` has no value for the `.normal` div.  So part of the mixin is spilling out.
