### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'prefix' of object '#<MyElement>'

### ISSUE THREAD

**Issue by benhjt** [Polymer/polymer#5237]
### Description
Error thrown when you have a property named `prefix` and do not use it for data-binding.

#### Live Demo
https://glitch.com/edit/#!/sudden-peak?path=my-element.html:22:24

Note: if you add a data-binding for the `prefix` property in the template, the error disappears

#### Steps to Reproduce
Example:

1. Create element from `polymer-cli`
2. Add property `prefix` to new element with type `String` and default value of empty string.
3. Check console for error

#### Expected Results
No error thrown

#### Actual Results
Error is displaying in console:

    Uncaught TypeError: Cannot assign to read only property 'prefix' of object '#<MyElement>'

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Edge
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11

### Versions
- Polymer: v2.6.0
- webcomponents: v1.2.0

---
I can't find any reference to `prefix` in the Polymer library so I'm not sure if it's something that gets inherited from the HTML element and I can't override that? I couldn't find anything in the docs about property names I couldn't use.

**Comment by TimvdLippe** [comment]
I was unable to see the error in Glitch, but this JSBin shows the issue as well: http://jsbin.com/codaqutiho/1/edit?html,console,output

Now I think this is because this property already exists on an `Element`: https://developer.mozilla.org/en-US/docs/Web/API/Element/prefix You can run the following snippet and see that the setter does not exist:

```js
Object.getOwnPropertyDescriptor(Element.prototype, 'prefix')
```

I do not think this is an issue with Polymer, but simply that no one is able to assign to the `prefix` property on any `Element`.

**Comment by TimvdLippe** [comment]
Oh, I missed your original comment at the end of your post. So yes, we came to the same conclusion. Therefore I am closing this issue, as this is sadly not something we have control over, but is baked into the platform.

**Comment by benhjt** [comment]
That's fine. Is this something that should be raised in the documentation? I couldn't see anything there regarding what property names can't be called.

**Comment by TimvdLippe** [comment]
Yes that would make sense to me. Feel free to update the documentation at https://github.com/polymer/docs in an appropriate location.
