### ISSUE TITLE
Update base href of Polymer JSBin

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/polymer#5239]
The JSBin that we reference in the CONTRIBUTING.md (http://jsbin.com/luhaxab/edit?html,output) currently has an outdated base href. We have to update it to the following to make it work again:

```html
<base href="https://polygit.org/polymer+:2.x/webcomponents+:v1/shadycss+webcomponents+:master/components/">
```

**Comment by kevinpschaaf** [comment]
Done!
