### ISSUE TITLE
Paper-Input: Auto-Validation fires directly for required without any user interaction

### ISSUE THREAD

**Issue by rowe42** [Polymer/polymer#5243]
### Description
Paper-Input: Auto-Validation fires directly for required without any user interaction
Since nothing has been entered so far, the validation fails of course.

#### Live Demo
A working example based on "polymer init" can be found here:
https://github.com/rowe42/PaperInputValidationError

#### Steps to Reproduce
1. Clone Repo
2. bower install
3. polymer serve
4. run in Browser
==> Page only contains one input field, which turns red through validation instantly.

#### Expected Results
No validation until the user has entered something.

#### Actual Results
see above

### Browsers Affected
- [X ] Chrome
- [X ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v2

**Comment by TimvdLippe** [comment]
This issue was moved to PolymerElements/paper-input#655
