### ISSUE TITLE
bower_components is published to npm.

### ISSUE THREAD

**Issue by coreyfarrell** [Polymer/polymer#5244]
### Description
After running `npm install @polymer/polymer` you get everything from polymer 2 into `node_modules/@polymer/polymer/bower_components/`.

#### Steps to Reproduce

1. Execute `npm install @polymer/polymer`

#### Expected Results
`node_modules/@polymer/polymer` should not contain bower_components.

#### Actual Results
`node_modules/@polymer/polymer` is 16MB.  Of that 14MB is bower_components (polymer-2).  In addition a `dist` folder is included which appears to be from polymer 2.

### Versions
- Polymer: v3.0.2

**Comment by TimvdLippe** [comment]
Ah, we missed that one in https://github.com/Polymer/polymer/pull/5215 Feel free to publish a PR that would add such folders to `.npmignore`! (I think you can actually copy-paste all from `.gitignore` into this file)

**Comment by abdonrd** [comment]
@TimvdLippe WDYT about use the `files` option as https://github.com/webcomponents/webcomponentsjs/pull/929?
