### ISSUE TITLE
Access a file uploaded in another page

### ISSUE THREAD

**Issue by hussain21j** [Polymer/polymer#5247]
I am using a simple polymer application with few pages in iron-pages. i am uploading a file in one page and then, i want to access this uploaded file in another page.

I tried several things but nothing seems to work, here is the sample code
1. page on which file is uploaded

`<dom-module id="file-upload-page">
  <template>
          <form method="post" enctype="multipart/form-data"
                action="/someation" disable-native-validation-ui no-validate>
        

            <my-input  file={{file}} id="sampleFileInput" btn-style="primary" max-files="1" accept=".xls, .xlsx" on-drop="fileUploadChangeListener"
                                 label="[[localize('open_invoices_file')]]" help-text="[[localize('open_invoices_file_help')]]" no-auto required>
            </my-input>
  </template>
  <script>
    class FileUploadPge extends Polymer.mixinBehaviors([], Polymer.Element) {
      static get is() {
        return 'file-upload-page';
      }

      static get properties() {
        return {
		}
	}

    customElements.define(FileUploadPge.is, FileUploadPge);
  </script>
</dom-module>`

2. the page on which file is accessed

`<dom-module id="consumer-page">
  <template>
       //some code
  </template>

  <script>
    class ConsumerPage extends Polymer.mixinBehaviors([], Polymer.Element) {

      static get is() {
        return 'consumer-page';
      }

      constructor() {
        super();
      }

      static get properties() {
        return {
         //some properties
        }
      }

      ready() {
      

-   super.ready();
-         var temp2 =this.$.sampleFileInput;   // returns null
-         var temp3 = this.shadowRoot.querySelector("#sampleFileInput"); // returns null
-         var temp4 = this.root.querySelector('#sampleFileInput'); // returns null
-         var temp5 = this.$$('#sampleFileInput'); // returns null
-         this._refreshSelections();

      };

      _proceed() {
-  var test1  = Polymer.dom(this).querySelector("#sampleFileInput"); // returns null
-         var test2 = this.$.sampleFileInput; //returns null
-         var test3 = document.getElementById("sampleFileInput"); //returns null
-         var test4 = this.$$("sampleFileInput"); //returns null
-         var test5 = this.shadowRoot; //returns some object
- 
- 
-         var test6 =this.$$.sampleFileInput; //returns null
-         var test7 = document.querySelector('sampleFileInput'); //returns null
-         var test8 = document.querySelector('file-upload-page::shadow .FileUploadPge'); //returns null
-         var temp4 = this.root.querySelector('#sampleFileInput');//returns null
-         var temp5 = this.$$('#sampleFileInput');//returns null
-         var temp6 = this.shadowRoot.querySelector('#sampleFileInput'); // returns null

      };

    customElements.define(ConusmerPage.is, ConusmerPage);
  </script>
</dom-module>`

The same code works in polymer1.0 with this

`document.getElementById("sampleFileInput")`

can somebody help what wrong am i doing in accessing this file in other page, and how can i handle this scenario in Polymer 2.0?

**Comment by TimvdLippe** [comment]
In Polymer 1 you were probably using shadydom. Polymer 2 uses shadow dom. Queryselectors on the document such as `document.getElementById` will therefore no longer work on elements inside shadow DOM. Instead, do something along the lines of

```js
document.querySelector('file-upload-page').shadowRoot.getElementById('sampleFileInput')
```

**Comment by hussain21j** [comment]
Thanks Tim, It worked
