### ISSUE TITLE
Remove jsbin from issue template

### ISSUE THREAD

**Issue by samuelli** [Polymer/polymer#5249]

**Comment by TimvdLippe** [comment]
The JSBin is working as intended. What would be the reason to remove it?

**Comment by web-padawan** [comment]
I guess the reason is that JSBin still uses Polymer 2?

**Comment by TimvdLippe** [comment]
Okay, I was mistaken. It does use Polymer 2 still. Instead of removing, I would propose to make the distinction clear and add a Polymer 3 compatible JSBin. Such that our Polymer 2 issues can still report issues and we can see whether they are Polymer 2 specific.

**Comment by samuelli** [comment]
The JSBin (https://jsbin.com/luhaxab/edit) uses Polygit and is on Polymer 2. If we like, we could maybe create a Polymer 3 JSBin that maybe works with unpkg? But yeah, good point, we should keep that JSBin around for 2.x issues.

**Comment by TimvdLippe** [comment]
@samuelli Yes we can switch to `unpkg` for both Polymer 2 and 3.

@kevinpschaaf Can you update `luhaxab` JSBin with the following content?

```html
<!doctype html>
<html>
<head>
  <script src="https://unpkg.com/@webcomponents/webcomponentsjs@1.2.2/webcomponents-lite.js"></script>
  <link rel="import" href="https://unpkg.com/@polymer/polymer@2.6.0/polymer.html">
</head>
<body>


  <dom-module id="my-element">
    
    <template>
      <style>
        :host {
          display: block;
        }
      </style>
      <div>[[prop]]</div>
    </template>

    <!-- Uncomment for legacy syntax -->
    <!--
    <script>
    HTMLImports.whenReady(function() {
      Polymer({
        is: 'my-element',
        properties: {
          prop: {
            type: String,
            value: 'my-element'
          }
        }
      });
    });
    </script>
    -->
    
    <!-- Uncomment for class syntax -->
    <script>
    HTMLImports.whenReady(function() {
      class MyElement extends Polymer.Element {
        static get is() { return 'my-element'; }
        static get properties() {
          return {
            prop: {
              type: String
            }
          }
        }
        constructor() {
          super();
          this.prop = 'my-element'
        }
      }
      customElements.define(MyElement.is, MyElement);
    });
      
    </script>
    
  </dom-module>

  <my-element></my-element>
  
</body>
</html>
```

**Comment by kevinpschaaf** [comment]
@TimvdLippe @samuelli Using unpkg for Polymer 2 technically fails because polymer's reference to webcomponentsjs's apply-shim will 404 (it uses a bower-style path that unpkg doesn't handle).  The bin would still works even though apply shim 404's because Polymer is designed to make apply-shim opt-out-able, but doesn't represent the exact configuration of Polymer 2 (e.g. code using @apply wouldn't work).  Also, people often pull in other bower deps (e.g. paper elements) when making repros.

How about just having the PR template point to two different jsBins, one for Polymer 2 (polygit), one for Polymer 3?

**Comment by TimvdLippe** [comment]
Sidenote: I would love to tackle issues like these, but I do not have the permission to edit the jsbin. If I am not mistaken, only @kevinpschaaf has the correct permissions. Would be great if we can find a solution where the full core team would be able to edit the files.

**Comment by ChrisBrownie55** [comment]
If it doesn't need to be JSBin, I would suggest using Glitch for the Polymer 3 issue template

**Comment by scenaristeur** [comment]
Hi , 
I've tried to import paper-checkbox & paper-button as said in README.md and it looks good, but I can't import 'paper-input', any idea ? 

```
<!-- Import a component -->
<script src="https://unpkg.com/@polymer/paper-checkbox@next/paper-checkbox.js?module" type="module" ></script>

<!-- Use it like any other HTML element -->
<paper-checkbox>Web Components!</paper-checkbox>
```
[my jsbin with paper-input](https://jsbin.com/xayotunite/edit?html,console,output)
