### ISSUE TITLE
too slow by "polymer build --preset es6-unbundled"

### ISSUE THREAD

**Issue by MehdiRaash** [Polymer/polymer#5251]
>  We prefer questions that can be answered, not just discussed. stackoverflow
so I think my this issue would turn to a discussion so I asked it here.

I just started a polymer 3 PRPL demo app out by `polymer init`, and then `polymer build --preset es6-unbundled` and finally `polymer serve` alongside a port and hostname.

The problem is, It's too slow, after a simple refresh it tooks about 1200ms, for a paint(it's weird because there's sw working).

So I tried `polymer build --preset es5-bundled` and the result was reasonably fast and nice.

Why the es6-unbundled acts too slow?

**Comment by TimvdLippe** [comment]
Unbundled does not bundle, which means it will issue a server request for
each file. This is probably the bottleneck, especially as they are
blocking. I advise you to run an audit tool like LightHouse which can help
you further.

**Comment by MehdiRaash** [comment]
Thanks.
