### ISSUE TITLE
properties is called twice for each class

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#5252]
_From @blikblum on May 11, 2018 20:18_

This occurs because the check to `constructor.properties` value at https://github.com/Polymer/polymer/blob/master/lib/mixins/properties-mixin.js#L89

_Copied from original issue: Polymer/lit-element#55_

**Comment by sorvell** [comment]
_From @TimvdLippe on May 12, 2018 15:48_

@blikblum Can you provide a JSBin that shows the issue?

**Comment by sorvell** [comment]
_From @blikblum on May 12, 2018 21:14_

Of course: https://lit-element-example-23f7hs.stackblitz.io

**Comment by TimvdLippe** [comment]
@blikblum I do not observe any error in the stackblitz. Could you explain what is going wrong and what is your expected behavior?

**Comment by blikblum** [comment]
There's no error

The expected is to run once as e.g. `observedAttributes`

**Comment by TimvdLippe** [comment]
I am still not following :( Could you add a console or debugger statement
in the function that is called twice? Then I can inspect it using devtools.

**Comment by blikblum** [comment]
In the example i added both a console log and display

Somehow the link of the example was showing an outdated version . Follows the edit link and actual src

https://stackblitz.com/edit/lit-element-example-23f7hs

```javascript
import {LitElement, html} from '@polymer/lit-element';

const propertiesCallCount = 0;

class MyElement extends LitElement {

  static get properties() { 
    propertiesCallCount++;
    console.count('properties method');
    return { mood: String }
  }

  _render({mood}) {
    return html`<style> .mood { color: green; } </style>
      properties Call Count: ${propertiesCallCount}`;
  }
}

customElements.define('my-element', MyElement);

```

**Comment by TimvdLippe** [comment]
@blikblum Awesome thanks for the additional clarification. I was able to debug the issue and fix it. PR up at #5261
