### ISSUE TITLE
Vue team needs help

### ISSUE THREAD

**Issue by xliiv** [Polymer/polymer#5257]
Can anyone help them with [this](https://github.com/vuejs/vuejs.org/issues/1631)?

Here's [the comparasion](https://vuejs.org/v2/guide/comparison.html#Polymer)

**Comment by TimvdLippe** [comment]
I think discussing this is better suited on our Slack http://polymer-slack.herokuapp.com/ Feel free to discuss with the community and submit improvements (like @jsilvermist already did, thanks!)
