### ISSUE TITLE
Mixin is not working with Polymer 3

### ISSUE THREAD

**Issue by masaoliou** [Polymer/polymer#5258]
### Description
While nested `behavior` works fine with Polymer 2, `mixin` is not working with Polymer 3.

#### Steps to Reproduce
file **./src/child-mixin.js**:
```javascript
/*
@polymer
@mixinFunction
@mixinClass
*/
ChildMixin=(BaseClass) => class extends BaseClass{
    static get properties(){
        return {
			p1:"v1"
			,p2:"v2"
		};
    }
    p2p1(){
        return this.p2+this.p1;
    }
}
```
file **./src/my-app.js**:
```javascript
import { PolymerElement } from '../node_modules/@polymer/polymer/polymer-element.js';
import {ChildMixin} from './child-mixin.js';
class MyApp extends ChildMixin(PolymerElement){
    connectedCallback(){
        super.connectedCallback();
        console.log(this.p1,this.p2,this.p2p1());
    }
}
```
file **./index.html**:
```html
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<base href="/">
		<title>Polymer 3 - Mixin</title>
		<script src="./node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js"></script>
		<script src="./src/my-app.js" type="module"></script>
	</head>
	<body>
		<my-app>Mixin</my-app>
	</body>
</html>
```

file **polymer.json**:

```javascript
{
	"entrypoint":"index.html"
	,"shell":"src/my-app.js"
	,"sources":[
		"favicon.ico"
		,"src/**/*"
	]
	,"extraDependencies":[
		"node_modules/@polymer/**/*"
		,"node_modules/@webcomponents/webcomponentsjs/**"
	]
	,"lint":{
		"rules":["polymer-3"]
	}
	,"builds":[
		{
			"preset":"es5-bundled"
			,"addServiceWorker": false
		}
	]
	,"moduleResolution":"node"
	,"npm":true
}
```
#### Expected Results
Prints `v1 v2 v2v1` in console.

#### Actual Results
Chromium and Opera print this error in console:

    Uncaught SyntaxError: The requested module does not provide an export named 'ChildMixin'

Firefox console is empty.

command `polymer build` gives:

    [cli.command.build]    Clearing build/ directory...
    [cli.main]   Promise rejection: Error: 'ChildMixin' is not exported by file:///var/www/test/mixin/src/child-mixin.js
    [cli.main]   Error: 'ChildMixin' is not exported by file:///var/www/test/mixin/src/child-mixin.js
        at error (/usr/lib/node_modules/polymer-cli/node_modules/rollup/dist/rollup.js:199:15)
        at Module.error (/usr/lib/node_modules/polymer-cli/node_modules/rollup/dist/rollup.js:16947:9)
        at handleMissingExport (/usr/lib/node_modules/polymer-cli/node_modules/rollup/dist/rollup.js:17256:21)

### Browsers Affected

- [x] Chrome v.63
- [x] Firefox v.52.5
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11
- [x] Opera v.52

### Versions
- Polymer: v1.7.3
- webcomponents: v2.0.0

**Comment by web-padawan** [comment]
The error message is quite descriptive, actually. Just change the line to look like this:

```js
export const ChildMixin = (BaseClass) => class extends BaseClass {
```

**Comment by masaoliou** [comment]
Thanks a lot!
The error is gone after `export const` is added. (I will investigate why the console logs nothing.)

I get this error from browser

    Uncaught ReferenceError: BaseMixin is not defined at ChildMixin (child-mixin.js:7) at my-app.js:3

with nested mixin:

file **./src/base-mixin.js**:

```javascript
/*
@polymer
@mixinFunction
@mixinClass
*/
export const BaseMixin=(BaseClass) => class extends BaseClass{
    static get properties(){
        return {p1:"v1"};
    }
}
```

file **./src/child-mixin.js**:

```javascript
import "./base-mixin.js";
/*
@polymer
@mixinFunction
@mixinClass
*/
export const ChildMixin=(BaseClass) => class extends BaseMixin(BaseClass){
    static get properties(){
        return {p2:"v2"};
    }
    p2p1(){
        return this.p2+this.p1;
    }
}
```
How to fix it?
Thanks in advance!

**Comment by TimvdLippe** [comment]
@masaoliou You need to explicitly import the exported variables as well:

```js
import {BaseMixin} from "./base-mixin.js";
```

I would advise you to read through some guides on ES modules to understand their inner workings. Some good guides I found: https://hacks.mozilla.org/2018/03/es-modules-a-cartoon-deep-dive/ and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import with https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export
