### ISSUE TITLE
Add 2.x option to treat complex observers as they were in Polymer1

### ISSUE THREAD

**Issue by beckysiegel** [Polymer/polymer#5262]
In order to smooth the upgrade process, add an option at the element level to not call observer/computed functions if any of the arguments is undefined.

Example: 

`properties: {
  foo: String,
  bar: String,
  baz: {
    type: String,
    computed: computedFn(foo, bar),
  },
  usePolymer1StyleObserver: true,
},
computedFn(foo, bar) {
  return foo + bar;
}`

**Comment by jsilvermist** [comment]
Why not just add at the beginning:
```js
if (!foo || !bar) return;
```
Or
```js
if (foo === undefined || bar === undefined) return;
```

**Comment by web-padawan** [comment]
You can also do it like this:
```js
if (Array.from(arguments).some(arg => arg === undefined))
```

**Comment by TimvdLippe** [comment]
I am inclined to agree with @jsilvermist and @web-padawan here. It should be quite straightforward to handle these cases. This also makes the logic more explicit. I would therefore be against adding such an option.

**Comment by beckysiegel** [comment]
Sorry, I didn't illustrate the real problem very well. It's very clear in this case that you can add:
if (foo === undefined || bar === undefined) return;  

However, I've worked on upgrading an app with many elements, and thousands of places where this can happen, many not as obvious as this. A few examples:
- An property that has a default value set, but is also two way bound to its parent. It can be undefined when not expected
- Computed values in templates

This issue is a huge pain point for large apps with many async properties. My goal is to make it easier to incrementally add the undefined checks as you are suggesting.
