### ISSUE TITLE
Android Chrome omnibox and tap position issues with App-Drawer

### ISSUE THREAD

**Issue by RuslanKim** [Polymer/polymer#5265]
DEMO site: https://www.teamatical.com/
If you go to home page and scroll down several screens, then use scrollup button then you should see well working button....
BUT if you use app-drawer (burger button or swipe left from right edge) and scroll down again than swipe a bit on page area to show omnibox of the browser ....BOOM then try to use scrollup button, you should see it does not work as expected and sometimes it needs to tap over...but sometimes it requires to tap under the button to make it works. Try tap under the button, so you can see positioning issue...
What a hell is that? FF works well because it does not hide omnibox (address bar)...
Are there any ideas what is it? How to fix?
Acually it repeats on https://shop.polymer-project.org/ too, you can swipe out the drawer and scroll page up to hide omnibox and links on drawer are missing it tap positioning...
Is it an issue of the Polymer or Browser?

### Browsers Affected
- [ X] Chrome Android
- [X ] Edge Android
- [Works well ] Firefox Android
- [NOT TESTED] Safari 11
- [NOT TESTED] Safari 10
- [NOT TESTED] IE 11

### Versions
- Polymer: v2.6.0
- webcomponents: v1.1.0

**Comment by TimvdLippe** [comment]
This issue was moved to PolymerElements/app-layout#562
