### ISSUE TITLE
Dragging a Polymer 3 web component doesn't work in Safari

### ISSUE THREAD

**Issue by a-xin** [Polymer/polymer#5271]
### Description
When starting the drag operation on a child of a draggable Polymer 3 component, `dragstart` is immediately followed by `dragend` and dragging is cancelled in Safari.

Please enable native HTML5 drag-and-drop for Polymer 3 web components in Safari. This issue has a huge impact on our ability to use Polymer in production as users expect drag and drop functionality.

#### Live Demo
https://codepen.io/a-xin/pen/YvjKXB

#### Steps to Reproduce
Setup:
Safari 11 on macOS 10.13

Steps:
1. Click and hold the left mouse button on a little red square (child of a web component)
2. Move the mouse
3. Observe how `dragend` is logged in the console and the draggable green box doesn't move

#### Expected Results
The component is moved when dragging either the web component (green box) or its child (the red box).

#### Actual Results
- the draggable green box doesn't move
- `dragend` is logged on the console as soon as the mouse is moved

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [X] Safari 11
- [X] Safari 10

### Versions
- Polymer: v3.0.2
- webcomponents: v2.0.2

**Comment by kevinpschaaf** [comment]
Unfortunately this looks like a Safari bug.

I've re-implemented your pen using raw custom elements, removing all Polymer code, and it appears to behave the same.  https://codepen.io/anon/pen/QBvwvM?editors=1000

I'd recommend filing an issue on Webkit/Safari.
