### ISSUE TITLE
Polymer 3 using AMD modules

### ISSUE THREAD

**Issue by nika-begiashvili** [Polymer/polymer#5285]
What is preferred way of loading AMD modules with polymer 3 ?

it would be nice to be able to load AMD modules using ESM import statement but when I run it with polymer serve, it tries to load it as ESM module and browser is failing with no export found error
and since wrapping js files inside html file to deduplicate things is not a thing anymore should I use requirejs for AMD modules ?
I believe most of the libraries on NPM provide AMD modules and not ESM

**Comment by kevinpschaaf** [comment]
The polymer cli is focused on development workflows around forward-facing, standard ES modules.

If you need to build legacy/older code which is has not yet upgraded to ES modules, I'd recommend using something like WebPack which supports compiling multiple module formats.  Polymer 3.x should build just fine using other ecosystem tools that support a wider set of non-standard module formats, which was a big motivating factor behind our decision to move from HTML Imports to ES modules.
