### ISSUE TITLE
Problem during bower install

### ISSUE THREAD

**Issue by MathRobin** [Polymer/polymer#529]
I have try the install of ui elements as indicated in the docs and i get this error :

bower polymer-ui-toggle-button#^0.3.0 ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/Polymer/polymer-ui-toggle-button.git", exit code of #128

Same thing with and without sudo. And with some other packages sometimes.

**Comment by ArthurJahn** [comment]
Issue reappeared with bower 1.5.1  
<code>
bower polymer#^1.0.0           ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/Polymer/polymer.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.129]: errno=Operation timed out
</code>

**Comment by kwijik** [comment]
Hi, I'm trying to install Polymer on my Mac and have some errors:
`joe:app ordi$ npm install -g polymer-cli
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects! Please read our blog for more.
npm WARN deprecated @types/assert@0.0.29: See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12826
npm ERR! git submodule -q update --init --recursive: git: 'submodule' is not a git command. See 'git --help'.
npm ERR! git submodule -q update --init --recursive: 
npm ERR! git clone --template=/Users/ordi/.npm/_git-remotes/_templates --mirror git@github.com:polymerelements/test-fixture.git /Users/ordi/.npm/_git-remotes/git-github-com-polymerelements-test-fixture-git-8142662e: Cloning into bare repository '/Users/ordi/.npm/_git-remotes/git-github-com-polymerelements-test-fixture-git-8142662e'...
npm ERR! git clone --template=/Users/ordi/.npm/_git-remotes/_templates --mirror git@github.com:polymerelements/test-fixture.git /Users/ordi/.npm/_git-remotes/git-github-com-polymerelements-test-fixture-git-8142662e: Permission denied (publickey).
npm ERR! git clone --template=/Users/ordi/.npm/_git-remotes/_templates --mirror git@github.com:polymerelements/test-fixture.git /Users/ordi/.npm/_git-remotes/git-github-com-polymerelements-test-fixture-git-8142662e: fatal: Could not read from remote repository.
npm ERR! git clone --template=/Users/ordi/.npm/_git-remotes/_templates --mirror git@github.com:polymerelements/test-fixture.git /Users/ordi/.npm/_git-remotes/git-github-com-polymerelements-test-fixture-git-8142662e: 
npm ERR! git clone --template=/Users/ordi/.npm/_git-remotes/_templates --mirror git@github.com:polymerelements/test-fixture.git /Users/ordi/.npm/_git-remotes/git-github-com-polymerelements-test-fixture-git-8142662e: Please make sure you have the correct access rights
npm ERR! git clone --template=/Users/ordi/.npm/_git-remotes/_templates --mirror git@github.com:polymerelements/test-fixture.git /Users/ordi/.npm/_git-remotes/git-github-com-polymerelements-test-fixture-git-8142662e: and the repository exists.
npm ERR! code 128
npm ERR! Command failed: git clone --template=/Users/ordi/.npm/_git-remotes/_templates --mirror git@github.com:polymerelements/test-fixture.git /Users/ordi/.npm/_git-remotes/git-github-com-polymerelements-test-fixture-git-8142662e
npm ERR! Cloning into bare repository '/Users/ordi/.npm/_git-remotes/git-github-com-polymerelements-test-fixture-git-8142662e'...
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ordi/.npm/_logs/2017-05-23T12_16_35_946Z-debug.log`
How can I fix it?

**Comment by robdodson** [comment]
I think this is the issue `npm ERR! Permission denied (publickey).`

Are you behind a corporate proxy or anything like that?

**Comment by kwijik** [comment]
No, I'm not sure, because I have exactly the same error from my home wifi.

**Comment by robdodson** [comment]
So you're doing `npm install -g bower` and getting the above error? What commands are you running?

**Comment by kwijik** [comment]
`npm install -g bower ` gives just warning message:
```joe:app ordi$ npm install -g bower
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects! Please read our blog for more.
/usr/local/bin/bower -> /usr/local/lib/node_modules/bower/bin/bower
/usr/local/lib
└── bower@1.8.0 
```

**Comment by robdodson** [comment]
That is all to be expected.

Glad you got it sorted :)
