### ISSUE TITLE
Property change observer sometimes doesn't fire when computing side-effects

### ISSUE THREAD

**Issue by ishermandom** [Polymer/polymer#5299]
### Description
I have a somewhat complex (but AFAICT minified) repro case for a property change observer not firing when it should. There's a live demo; I've also included the code sample below.

#### Live Demo
https://next.plnkr.co/edit/ztqni6EWk1MoomAx

#### Steps to Reproduce
1. Create `my-parent`, with a child `my-child` that binds a `model` object, with two-way binding.
2. Add an observer for changes to `model.*` within `my-parent`.
3. Structure `my-child` to do three things:
    a. Compute a computed property `foo` whenever `model.property` changes.
    b. In the function that computes `foo`, as a side-effect, update a different property `bar` of `my-child`.
    c. Compute a computed property `baz` whenever `bar` changes.
4. Within `my-child`, trigger a change to `model.property`.

#### Expected Results
`my-parent` should observe the change to `model.property`.

#### Actual Results
The observer within `my-parent` doesn't trigger.

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [ ] Edge
- [x] Safari 11
- [ ] Safari 10
- [ ] IE 11

(I only tested Firefox, Chrome, and Safari 11.)

### Versions
- Polymer: v3.0.0-pre.12, also observed in Polymer 2 (not sure exactly which version)
- webcomponents: not sure – whatever Plunkr is using? Also observed with Polymer 2, again not sure exactly which version.

### Code Sample
```js
// Import the Polymer library and the html helper function
import { PolymerElement, html} from 'https://unpkg.com/@polymer/polymer@^3.0.0/polymer-element.js';
// Import template repeater
import 'https://unpkg.com/@polymer/polymer@^3.0.0/lib/elements/dom-repeat.js';

class XSub extends PolymerElement {
  static get properties() {
    return {
      model: {
        notify: true,
      },

      fooComputed_: {
        computed: 'getFoo_(model.property)'
      },

      barSetDuringComputation_: {},

      bazComputedAfterBarSet_: {
        // Comment out the "computed" line below to make the test pass!
        computed: 'getBaz_(barSetDuringComputation_)'
      },
    };
  }

  static get template() { return html`[[model.property]]`; }
  static get observers() { return ['onChange_(model.*)']; }
  onChange_(changeRecord) { console.log(changeRecord); }

  ready() {
    super.ready();
    window.setTimeout(() => this.set('model.property', 'x'), 1)
  }

  getFoo_() {
    // Seemingly must be an array in order to reproduce the bug.
    this.barSetDuringComputation_ = ['x'];
  }

  getBaz_() {}
}

class XCustom extends PolymerElement {
  static get properties() {
    return {
      model: {
        value: () => ({property: 'a'}),
      },

      observedChange_: {
        value: false,
      },
    };
  }
  
  static get template() {
    return html`
     <x-sub model="{{model}}" hidden></x-sub>
     [[getMessage_(observedChange_)]]
    `;
  }

  static get observers() {
    return ['onChange_(model.*)'];
  }
  
  onChange_(changeRecord) {
    console.log(changeRecord);
    if (changeRecord.path === 'model.property') {
      console.log('yay');
      this.observedChange_ = true;
    }
  }
  getMessage_() { return this.observedChange_ ? 'PASS' : 'FAIL'; }
}
customElements.define('x-sub', XSub);
customElements.define('x-custom', XCustom);
```

**Comment by ishermandom** [comment]
An easy work-around, by the way, is to have the child element manually forward change events to the parent, by firing an event whenever it observes the change of interest.

**Comment by M4FFS** [comment]
I have also observed this in Polymer 1.0. It seems to lag a bit, not firing on the first change, but then firing on the next. If I wait a while before doing the first change, it doesn't happen.
