### ISSUE TITLE
Don't override native Element#toggleAttribute()

### ISSUE THREAD

**Issue by freshp86** [Polymer/polymer#5307]
As of Chrome 69, `toggleAttribute()` is now a thing in Chrome, see https://www.chromestatus.com/feature/5676852374929408.

It is currently overriden by the non-native `toggleAttribute()` defiinition at https://github.com/Polymer/polymer/blob/8f6a96254c3a1177c1407ee3591df92217c93b19/lib/legacy/legacy-element-mixin.js#L822.

It would be nice to not override the native method, if it already exists.

**Comment by TimvdLippe** [comment]
@freshp86 Is there a difference in implementation between the two? If there is, we can not make this change as it would be backwards incompatible.

**Comment by freshp86** [comment]
The signature of the native method accepts two parameters only, see https://dom.spec.whatwg.org/#dom-element-toggleattribute.

I did not think about backwards compatibility. Perhaps you could at least have the Polymer method delegate to the native one if available, instead of re-implementing it.

**Comment by TimvdLippe** [comment]
> Perhaps you could at least have the Polymer method delegate to the native one if available, instead of re-implementing it.

That would still mean we have to have the old code around. I do not think that is worthwhile, especially as this on the legacy mixin and thus does not exist on `Polymer.Element`. I am therefore inclined to keep it as-is, since future users will not be using legacy and thus can use the native method as they desire.

**Comment by TimvdLippe** [comment]
After more thought, I am closing this issue. Since we ship the method on the legacy mixin, this should go away over time. Since we can not make backwards incompatible changes, delegation still requires the current implementation to exist. Delegation therefore has no explicit benefit.
