### ISSUE TITLE
Date binding notification events are broken if the bound element has children

### ISSUE THREAD

**Issue by tomalec** [Polymer/polymer#5308]
### Description
Notification events do not work if the bound element has children. They seem to read the value from the descendant node instead of the bound one.
```html
<div onclick="++this.value" value="{{value::click}}">
  works
  <b>fails</b>
</div>
```

#### Live Demo
https://glitch.com/edit/#!/small-duke?path=index.html:13:41
#### Steps to Reproduce

1. Create `div` with property bound with notification event, like `value="{{value::click}}"`
2. Append an element to the `div`
3. Click (or trigger a bubbling event) on `div`

#### Expected Results
The property (`value`) should be changed.

#### Actual Results
The property is set to `undefined` or any value of `descendant.property`.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [?] Safari 11
- [?] Safari 10
- [x] IE 11

### Versions
- Polymer: v2.6.0
- webcomponents: v1.2.3

### Possible fix

Seems that `handleNotification` should check `event.currentTarget` not `event.target` at https://github.com/Polymer/polymer/blob/5807ce0d05e2f179e31bbf44c9b7b5839f34ec99/lib/mixins/property-effects.js#L356

**Comment by TimvdLippe** [comment]
@tomalec Seems like a valid case. Do you mind filing a PR with the fix + test cases? Please submit them to both the 2.x and the 3.x branch. Thanks! 😄

**Comment by jsilvermist** [comment]
onclick isn't a Polymer listener, I think you're looking for on-click . For more information, check out [https://www.polymer-project.org/2.0/docs/devguide/events](https://www.polymer-project.org/2.0/docs/devguide/events).

**Comment by tomalec** [comment]
@TimvdLippe Here you have 2.x https://github.com/Polymer/polymer/pull/5309 :)

**Comment by tomalec** [comment]
@jsilvermist  That's the point I use native `onclick` to trigger event listener given in `{{prop::event}}` syntax

**Comment by TimvdLippe** [comment]
@tomalec Awesome thanks. Once that is merged, please also open a PR on `master` for 3.x

**Comment by tomalec** [comment]
Thanks a lot for the quick feedback :)

**Comment by TimvdLippe** [comment]
Likewise for the detailed issue + solution PR :)

Op do 2 aug. 2018 om 15:31 schreef Tomek Wytrębowicz <
notifications@github.com>:
