### ISSUE TITLE
Erratum in element-mixin.js ? - error lint/constant-condition

### ISSUE THREAD

**Issue by jimmy-collazos** [Polymer/polymer#5315]
Hi everyone!

I'm reading element-mixin.js code and in [line 713](https://github.com/Polymer/polymer/blob/master/lib/mixins/element-mixin.js#L713) have a rare code:
```javascript
export function register(prototype) {
  registrations.push(prototype);
  undefined && _regLog(prototype);
}
```
Any idea why write "undefined" in that condition? because `_regLog()` always is executed.

**Comment by masonlouchart** [comment]
The last change of this file was made 4 months ago. And before it, this function was located to the [line 715](https://github.com/Polymer/polymer/blame/527d2cdd1403db231b71b555c924135a47280e4f/lib/mixins/element-mixin.js#L715) and looked like:

```js
register: function(prototype) {
    this.registrations.push(prototype);
    Polymer.log && this._regLog(prototype);
}
```

I suppose the Polymer.log reference was replaced by "its value" during an automatic migration. IMHO, the existence of the logger has to be brought back in place.

**Comment by jimmy-collazos** [comment]
@masonlouchart 
> ...existence checking of the logger has to be brought back in place

but "Polymer" now is legacy. In current version I don't know where is the best place to put that config.

I think the best option is remove log feature.

**Comment by TimvdLippe** [comment]
This was the output of the modulizer that ran on our code. Since we no longer have a special `Polymer.log`, we can just remove this check.
