### ISSUE TITLE
Cannot find polymer demos on site

### ISSUE THREAD

**Issue by w0298i** [Polymer/polymer#5321]
I am not following the issue template, as this issue does not concern the custom elements or it's API.
When navigating the Polymer page, it is very heard to find the demos i.e the [shop demo](https://shop.polymer-project.org/) without running a Google search for them. I would prefer a "real" Polymer demo page showing how the elements can be used to build a webapp, rather than testing individual web components. This would also show the speed of Polymer, as some people refer to Polymer as "slow".

**Comment by TimvdLippe** [comment]
These case studies are included in our toolbox section on the website: https://www.polymer-project.org/3.0/toolbox/case-study which is advertised on https://www.polymer-project.org/3.0/toolbox/ and included as a link in the footer. If you would like to propose any changes, feel free to open a PR on https://github.com/polymer/docs
