### ISSUE TITLE
Polymer 3: rootPath in utils/settings.js is not exported in typescript declaration.

### ISSUE THREAD

**Issue by hastebrot** [Polymer/polymer#5338]
`lib/utils/settings.js`:
~~~js
export let rootPath = undefined ||
  pathFromUrl(document.baseURI || window.location.href);
~~~

But is missing in auto-generated `lib/utils/settings.d.ts`.

Polymer version 3.0.5.

**Comment by TimvdLippe** [comment]
We probably need to remove the `undefined ||` here. Feel free to open a PR!

**Comment by TimvdLippe** [comment]
This has been fixed in #5455

**Comment by Tronil** [comment]
I just ran into this issue with Polymer 3.3.0, so it doesn't seem to be fixed.

**Comment by abraham** [comment]
Still missing from the types.
