### ISSUE TITLE
The requested module '../../axios/index.js' does not provide an export named 'axios'

### ISSUE THREAD

**Issue by vtolkanov** [Polymer/polymer#5342]
I am manually upgrading polymer 2.0 project to 3.0 one. I replaced 'link' with 'import',  *.html with *.js and bower.json and bower_components with package.json and node_modules.
But when I ran 'polymer serve', I got this problem. What can I do?
![image](https://user-images.githubusercontent.com/40726938/44534360-ee22cd00-a73a-11e8-94f3-f3317c5b0bbf.png)
And in the cmd window, I could see this note. Can you let know how to handle this, too?
![image](https://user-images.githubusercontent.com/40726938/44534409-11e61300-a73b-11e8-8837-39fec2fbb49d.png)
My npm version is 6.2.0
polymer is ^3.0.0-pre.21
axios is ^0.18.0
Please, help me...

In polymer 2.0 script it was coded like this
<script src="../bower_components/axios/dist/axios.js"></script>
And I changed it 
import {axios} from "../node_modules/axios";

**Comment by web-padawan** [comment]
Polymer CLI does not accept CommonJS modules, only ES modules.
Consider using Webpack instead, or use this module as a workaround: 
https://github.com/bundled-es-modules/axios

**Comment by vtolkanov** [comment]
I used axios-es6 instead of axios, but error is the same.
The requested module '../../axios-es6/dist/axios.min.js' does not provide an export named 'axios'
![image](https://user-images.githubusercontent.com/40726938/44536186-3e039300-a73f-11e8-9c00-62e1abbe1089.png)

**Comment by web-padawan** [comment]
@vtolkanov `axios-es6` is not an ES module, as it is compiled with Webpack to UMD bundle.
You will basically get the same error when attempting to load any UMD module with Polymer CLI. 

By the way, Polymer CLI has its own AMD loader which defines `window.define` but not `window.define.amd` thus making impossible using of UMD modules even for `es5-bundled` build.

In case you are interested, here is an example of using Polymer 3 with Webpack: 
https://github.com/web-padawan/polymer3-webpack-starter

**Comment by vtolkanov** [comment]
Thank you for your kindness! I am very new to polymer 3, so I have so many trouble. Plz, help me.

**Comment by web-padawan** [comment]
Hi, honestly no idea. Depends on how you include the script. You should be able to exclude it frim minifying, it could be the reason.

**Comment by vtolkanov** [comment]
I've solve this problem, as you said. And now it works. **REALLY thank you for your advice. ^_^**

**Comment by web-padawan** [comment]
@vtolkanov glad you sorted it out! Also, next time please submit any issues related to the tooling (including `polymer serve`) to https://github.com/Polymer/tools repo, and you can also ask questions in the [Slack](https://polymer-slack.herokuapp.com/) channel.

**Comment by TimvdLippe** [comment]
Closing per https://github.com/Polymer/polymer/issues/5342#issuecomment-415958751 Amazing help @web-padawan :tada:

**Comment by arekucr** [comment]
hey @vtolkanov how did u fix the problem with Axios, did u find an es6 module version? we are using pure polymer cli setup witout webpack and want to keep it in that way but still wanna use axios client

Thanks in advanced

**Comment by web-padawan** [comment]
As mentioned above there is ES module here but not sure if it has been published to npm (as far as I know its maintainers are still on bower): https://github.com/bundled-es-modules/axios

**Comment by arekucr** [comment]
Oh thanks @web-padawan I was confused thinking that that link above was just a rollup.config.js config file.

**Comment by sonuyadav7421** [comment]
Hi, if external js does'nt support es6 module simply you can add the js into script and import the script into index.js
