### ISSUE TITLE
Polymer and a roadmap beyond pre.21

### ISSUE THREAD

**Issue by ztzven** [Polymer/polymer#5344]
Firstly, loving where v3 is at. Performance seems great and development is much more streamlined.

The polymer components on npm have been sitting at pre.21 for quite a while now... Could the community get an update on status of where development is at and heading? Personally I think the API is stable!

... On second thought maybe I should've joined the Slack channel to post this.. anywho, rock on!

**Comment by TimvdLippe** [comment]
@e111077 Could you give some more information on this as replied on Slack as well?

**Comment by e111077** [comment]
Heya, we're putting in the final touches. The `__autogenerated_3.0_preview` branch is actually being manually updated.

We are at the point where we need to do one more prerelease, make sure all of our changes pass tests, repeat until all tests across elements pass, then release to stable.

@bicknellr is currently heading these efforts.
