### ISSUE TITLE
ES6 Module Transforms Exceptionally Slow On Google Cloud N1 Standard Instance 

### ISSUE THREAD

**Issue by dman777** [Polymer/polymer#5351]
### Description
ES6 transforms are exceptionally slow on Google Cloud instance n1-standard-1 (1 vCPU, 3.75 GB memory) with good bandwidth 55Mbps  

#### Steps to Reproduce
1) Deploy Google Cloud n1-standard-1 (1 vCPU, 3.75 GB memory). Ubuntu Xenial. Node v10.5.0.
2) Polymer init -> choose Polymer 3 prpl pattern app
3) Load time ranges from 7 seconds to 10.5 seconds on a 55 Mpbs per second connection 

#### Expected Results
Have ES6 module transforms give same performance as on localhost which would be in the 2 -3 sec range.

#### Actual Results
ES6 transforms have erratic performance and can cause 10 second page loads. With Polymer 1 development on the same server, page loads are only 3.5 seconds. 

### Browsers Affected

- [ x] Chrome v68 64bit Linux
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions
- Polymer cli: v#1.7.7 Polymer 3.0.5 on front

**Note** This for development only, no builds for production use

Please utilize Polymer 3 development for development on cloud. In this day of age where the front end uses facebook auth, google auth, and alexa integration it is necessary to develop the front end with a permanent ip address and https.

**Comment by web-padawan** [comment]
You should be able to do following steps for local configuration:
1. Setup the (arbitrary) local domain, e.g. `https://example.com.local:1234`
2. Generate the self-signed SSL certificate for that domain
3. Configure your local development server, e.g. `nginx` to use it
4. Update the `hosts` file on your computer and map `example.com.loca` to localhost
5. Configure the Google developer console to add `https://example.com.local:1234` as authorised redirect URL

**Comment by dman777** [comment]
Thank you, I considered this set up. However,  it will not work because my local is a laptop that leases ip addressees and can not get static ip addresses. A static ip address is needed  rather I use a domain name on my local or I use the cloud with the domain name to proxy  requests to my local.  

This circles back to the issue where I should be able to develop on a cloud and not have this unusual performance penalty from ES6 modules transforms(I say  ES6 transforms because Polymer 1 development does not have the same reload performance issue on the same server).

**Comment by TimvdLippe** [comment]
This issue was moved to Polymer/tools#693
