### ISSUE TITLE
Run Polymer In Visual Studio

### ISSUE THREAD

**Issue by BilgehanYildiz** [Polymer/polymer#5352]
Hi I want to use polymer with inside visual studio ide.Most of people suggest visual studio code but I want to use polymer with vs2015 or vs2017.When I try to run polymer with vs2015 I get relative path errors.Is there any polymer sample with vs2015 or vs2017 Thanks

**Comment by TimvdLippe** [comment]
Polymer should work in any editor, given that the editor supports web development practices and/or JavaScript. I am not aware of any specific example project for vs2015.

**Comment by BilgehanYildiz** [comment]
I failed to run in vs2015 my be mymistake,for that reason I need specific example for that

**Comment by TimvdLippe** [comment]
I think this question is more suitable to be discussed on our Slack: http://polymer-slack.herokuapp.com/ The Polymer team has no plans currently to create a dedicated example for vs2015.

**Comment by TimvdLippe** [comment]
Closing this per above comment, as this issue does not contain an actionable item for the team.

**Comment by BilgehanYildiz** [comment]
https://stackoverflow.com/questions/51129707/run-polymer-in-visual-studio-2015

I take this error is there any information about that
