### ISSUE TITLE
Help with service worker

### ISSUE THREAD

**Issue by mercmobily** [Polymer/polymer#5363]
Hi,

First of all, I apologise if this is not the right spot for this.
I need to configure the service worker for the first tine, and I am totally lost.
I have a very standard Polymer 2 application with the following `polymer.json` file:

    {
      "entrypoint": "index.html",
      "shell": "src/my-app.html",
      "autoBasePath": true,
      "fragments": [
        "src/my-page-stats.html",
        ...
        "src/my-page-404.html"
      ],
      "sources": [
        "images/**/*",
        "src/**/*",
        "libs/**/*"
      ],
      "extraDependencies": [
        "bower_components/webcomponentsjs/*.js",
        "!bower_components/webcomponentsjs/gulpfile.js",
        "manifest.json",
        "src/lib/Utils.js"
      ],
      "lint": {
        "rules": ["polymer-2"]
      },
      "builds": [
        {
          "preset": "es5-bundled"
        },
        {
          "preset": "es6-bundled"
        },
        {
          "preset": "es6-unbundled"
        }
      ],
      "lint": {
        "rules": ["polymer-2"],
        "ignoreWarnings": ["invalid-polymer-expression"]
      }
    }

The `libs` directory contains a bunch of sym links:

    total 12
    Sortable.js -> ../bower_components/Sortable/Sortable.js
    datalist-polyfill.min.js -> ../../node_modules/datalist-polyfill/datalist-polyfill.min.js
    ejs.js -> ../../node_modules/ejs/ejs.js
    ejs.min.js -> ../../node_modules/ejs/ejs.min.js
    leaflet -> ../../node_modules/leaflet/dist/
    moment-precise-range.js -> ../../node_modules/moment-precise-range-plugin/moment-precise-range.js
    moment-timezone-with-data.js -> ../../node_modules/moment-timezone/builds/moment-timezone-with-data-2012-2022.js
    moment.js -> ../../node_modules/moment/moment.js

Now, I am having several problems with the service worker, and I can't figure out what to do:

* The `libs` folder is not getting cached. If the network is down, the browser will attempt to load all of the files in `libs`. I thought it would since under `sources` in my `polymer.json` I have  `"libs/**/*"` I wonder if them being links is a problem?

* The route `routes/appInfo.js` _must_ get cached, and it doesn't right now. It's a dynamic Javascript file that sets a global variable, used throughout the application. It doesn't get cached because it;s not mentioned anywhere as a "special" file, but... it is.

* The route `/routes/passwordRecover/**` must be ignored by the service worker. The problem right now is that if a user requests a password recovery token, and they have already loaded the site before, the request gets handled by the service worker which redirects them straight to the default index.html. So, the reset never actually happens.

The problem here is that I am not even sure what files to change. I looked at the [officual documentation for service worker in Polymer 2.0](https://www.polymer-project.org/2.0/toolbox/service-worker) but I still have questions.

For example:

* If I specify `--sw-precache-config config-file.json`, I have to write a config file on my own `from scratch`. Is there a way to see the default "starting point" at least, so that I don't make silly mistakes?

* How do I force specific URLs to be cached (see `routes/appInfo.js`), how do I prevent others from being cached (see `/routes/passwordRecover/**`) and how do I check why `libs/**` are not being cached?

Thank you!

Merc.

**Comment by jsilvermist** [comment]
You can check out https://github.com/Polymer/pwa-starter-kit/blob/master/sw-precache-config.js for an example from the `pwa-starter-kit`, or https://github.com/GoogleChromeLabs/sw-precache for more information.

Here's an example from what I'm using right now:

> sw-precache-config.js
```js
module.exports = {
  staticFileGlobs: [
    'images/**/*',
    'src/**/*',
    'manifest.json',
  ],
  runtimeCaching: [
    {
      urlPattern: /\/node_modules\/@webcomponents\/webcomponentsjs\//,
      handler: 'fastest',
    },
    {
      urlPattern: /\/node_modules\/web-animations-js\//,
      handler: 'fastest',
    },
    {
      urlPattern: /^https:\/\/fonts.googleapis.com\//,
      handler: 'fastest',
    },
    {
      urlPattern: /^https:\/\/fonts.gstatic.com\//,
      handler: 'fastest',
    },
    {
      urlPattern: /^https:\/\/unsplash.it\//,
      handler: 'fastest',
    },
  ],
};
```

The `staticFileGlobs` will be downloaded by the service worker on load, while the `runtimeCaching` will cache resources as they are requested.

I'm thinking that since I have a refresh toast on sw updates anyways, it might be a better idea to use `cacheFirst` instead of `fastest` to mitigate mismatched resources, but I haven't tested this yet so I'm not sure of the impact.

**Comment by TimvdLippe** [comment]
Closing this per the awesome explanation of @jsilvermist If you run into any technical issues, please open an issue on https://github.com/polymer/tools For general support, I think the Slack channel is the best place.

**Comment by mercmobily** [comment]
This is for posterity, and for whoever in the future might stumble upon this.
I feel whoever responded didn't quite understand the question.
My problem was that the service worker thought it "should respond" (search for shouldRespond in the template) because all paths where whitelisted to be navigational page.

The solution was to use the `navigateFallbackWhitelist` option in the `sw-precache-config` file. In my case:

    navigateFallbackWhitelist: [ /^((?!(\/routes\/|stores\/|\/f\/)).)*$/ ],

This makes sure that all data calls, and all server calls (see: not pages) are always ignored by the service worker.

Thanks.
