### ISSUE TITLE
Question: Recommended webpack-dev-middleware alternative

### ISSUE THREAD

**Issue by aletorrado** [Polymer/polymer#5368]
Hi, I'm looking for an alternative for embedding the development server functionality, just like `webpack-dev-middleware`, into my existing codebase.

At first I've resolved this using webpack, but because of the lack of ìmport.meta` support, I'm considering some more-officially-recommended way to do this. Also, I would like to access some features like html minification.

Can you give me some hint? Thanks

**Comment by TimvdLippe** [comment]
The tools repository hosts this code. The transformation you are looking for is probably https://github.com/Polymer/tools/blob/f47e31b318de2dbbeaf1b672bb7ecb56b4e23116/packages/build/src/js-transform.ts If you run into any issues, feel free to open an issue on that repo 😄
