### ISSUE TITLE
Add property effects public getter

### ISSUE THREAD

**Issue by madiyetov** [Polymer/polymer#5369]
Hi. I am using Polymer 3.0.

So what do I want in Polymer Elements public API:
The method that returns specific effects of the given property, with the signature like this:
`getPropertyEffects(string prop, PROPERTY_EFFECT_TYPES effectType);`

Now I  have to access, for example, `__computeEffects` directly to retrieve effect.

Use case:
Consider;
```
get properties() {
    return {
          condition: Number, 
          items: Array 
    }
}

first() { return [1, 2, 3]; }
second() { return [4, 5, 6]; }
...
```
I want to change computation function of `items` depending on `condition` dynamically using `createComputedProperty` but it doesn't remove old compute effect. So `getPropertyEffects` method will help to retrieve old one and remove it using public method `removePropertyEffect`.

Thanks in advance

**Comment by stat92** [comment]
Or `createMethodEffect` will return created effect. This way Element will incapsulate other effects.

**Comment by stat92** [comment]
@TimvdLippe Yeah, I think so. How is it going?

**Comment by TimvdLippe** [comment]
Haven't had the time to continue :(
