### ISSUE TITLE
Edit on Github Link returning 404 error

### ISSUE THREAD

**Issue by kiransasi** [Polymer/polymer#540]
In the Tutorial section of Getting started page on Polymer site, the "Edit on Github" link provided is broken.

**Comment by gitact** [comment]
The problem has come again in the brand-new pages of the website www.polymer-project.org (e.g. https://www.polymer-project.org/1.0/start/first-element/intro )
Every "EDIT ON GITHUB" link under the main page title points to an inexistent page "https://github.com/Polymer/docs2/edit/master/app/1.0..."
