### ISSUE TITLE
Using stylesFromTemplate

### ISSUE THREAD

**Issue by halloweenman** [Polymer/polymer#5408]
### Description
I'm a novice using Polymer 3 and need to get styles from an element. Can anyone show me a real world example of how to use stylesFromTemplate? I'm struggling.

`stylesFromTemplate(template: !HTMLTemplateElement, baseURI: string)`

For example, using Polymer Starter Kit (https://github.com/Polymer/polymer-starter-kit), a function in my-app.js that gets the styles from my-view1.js - thanks!

There's generally a lack of help and examples on using Polymer.

### Versions
Polymer 3

**Comment by web-padawan** [comment]
In general, you should not use this API directly (unless you know what you are doing).
See https://www.polymer-project.org/3.0/docs/devguide/style-shadow-dom#share-styles-between-elements

In case you want to use some styles defined in Polymer 3 `dom-module` with LitElement (when mixing both in the same app), you can use this kind of workaround:
https://github.com/web-padawan/lit-components/blob/893453669af1aa72d1b50f3bbae6a93c7be7de6a/packages/style-utils/style-utils.js#L10

**Comment by stucker71** [comment]
Thanks. I managed to get what I wanted working by registering a style module as an element as described above and then using stylesFromModule that gets the styles from the style module

`stylesFromModule('mystylemodule')[0].outerHTML;`

I needed to programatically extract and insert the styles into a html document that is downloaded by the website visitor.
