### ISSUE TITLE
Polymer 3: no support for properties of level 3

### ISSUE THREAD

**Issue by lawlietmester** [Polymer/polymer#5414]
Polymer 3:
Please add support for 3rd level properties, like:

`<p>[[first.second.third]]</p>`

Or write directly in documentation that such properties not supported.

----

In Polymer 1 it was possible

**Comment by TimvdLippe** [comment]
This should be working just fine. Could you create a reproduction case that shows the issue you are seeing? Please see [the contributing guidelines](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) on how to create a reproduction case.

**Comment by lawlietmester** [comment]
Just rechecked and found one interesting detail:

Property [[translations.сhangeTimezone.p1]] not supported.
But if I rename it to [[translations.timezone.p1]] everything works ok.

**Comment by lawlietmester** [comment]
Also checked [[translations.ChangeTimezone.p1]] - it works too. Only [[translations.сhangeTimezone.p1]] does not work
