### ISSUE TITLE
Polymer 3 html literal incompatible with lit html literal.

### ISSUE THREAD

**Issue by KeithHenry** [Polymer/polymer#5417]
### Description
Polymer 3 html literals incompatible with lit html literal.

#### Steps to Reproduce
You cannot mix html literals from Lit in Polymer 3.

In `common-styles.js`, referenced by new `LitElement` components and upgraded `PolymerElement` ones:

```
import { html } from '.../lit-html/lit-html.js';
export const commonStyles = html`<style>...</style>`;
```

Then in `my-component.js`:
```
import { PolymerElement, html } from '../../lib/@polymer/polymer/polymer-element.js';
import commonStyles from './common-styles.js';
const localStyles = html`${commonStyles}<style>...</style>`; 

class MyComponent extends PolymerElement {
    static get template() {
        return html`${styles}...`;
```

#### Expected Results
Lit `TemplateResult` treated like literal string.

Without this `LitElement` and `PolymerElement` cannot share any literal constants, making the messy process of upgrading worse.

#### Actual Results
This throws an error in `html-tag.js` line 56:
https://github.com/Polymer/polymer/blob/1ad496fc7bb78ebe949b149b9b6257b25169c8c6/lib/utils/html-tag.js#L49-L58

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

### Versions
- Polymer: v3.0.2

**Comment by KeithHenry** [comment]
I have a workaround (of sorts for this, but it's nasty:

```
import { html as polyhtml } from '.../@polymer/polymer/polymer-element.js';
import { html as lithtml } from '.../lit-html/lit-html.js';

const commonStyles = `<style>...</style>`;
export const commonStylesPolymer = polyhtml([evoThemeStr]);
export const commonStylesLit = lithtml([evoThemeStr])
```

Then in my-component.js:
```
import { commonStylesPolymer as commonStyles } from './common-styles.js';
```

This works, but is horribly clunky - as I understand it the upgrade path is Polymer 2 to Polymer 3, the write new stuff in LitHtml - in that scenario they really should be compatible.

**Comment by kevinpschaaf** [comment]
Sorry for the confusion.  Polymer 3.x's `html` function is indeed designed to provide an upgrade path from 2.x  (where templates are defined in HTML imports) to 3.x (where templates are inlined in JS), but not also to `lit-html` directly.

While `lit-html` & `LitElement` are the spiritual successors to Polymer, the templates are not compatible, and so you cannot import lit templates into Polymer templates or vice-versa.  While the naming of the tag function used to define templates are the same (and I understand how that can lead to confusion), it is not a design goal to make the template systems interoperate at that level; Polymer's `html` fn returns an actual `HTMLTemplateElement`, whereas `lit-html`'s `html` fn returns a lit `TemplateResult` which must be `render`ed to the DOM using the `lit-html`-specific `render` method -- the values returned are very different.

All that said, there may be a case to address this specific use case (sharing static HTML content such as shared styles between `PolymerElement` & `LitElement`) in `lit-html` by providing a "`templateContent`" directive that stamps the content of an `HTMLTemplateElement` passed as a lit value; this would allow shared styles to be defined using Polymer's `html` tag fn (which just creates an `HTMLTemplateElement` from the string and interpolated into `lit-html` templates.

**Comment by kevinpschaaf** [comment]
Closing the issue here since its most likely any improvement would happen on the lit side; opened https://github.com/Polymer/lit-html/issues/605.
