### ISSUE TITLE
Hot reload support

### ISSUE THREAD

**Issue by aletorrado** [Polymer/polymer#5425]
Hi! With the release of Polymer 3 and it's better integration process with Webpack, it seems to me that the next big feature for development could be Hot Reload, like the React plugin.

In the case of React, it basically creates a Proxy object for each of the components defined, and then targets each access to that object to the latest module loaded.

I think the main challenge here would be to proxy the ES6 classes without side-effects.

What do you think?

**Comment by TimvdLippe** [comment]
Hot reload support is not something we have any immediate plans for and I do not think we will add this feature to our tooling. In general, hot reload should not be necessary in small to medium size applications. If loading performance during development is an issue, I would suggest to adopt [the PRPL pattern](https://developers.google.com/web/fundamentals/performance/prpl-pattern/). This will also help your end users, as well as your developers.

Please do not that there are alternatives that do offer a solution, such as [SkateJS](https://github.com/skatejs/skatejs/issues/663).

**Comment by aletorrado** [comment]
@TimvdLippe that doesn't preserve state at all. Anyways I actually don't agree on how to handle SSR on Polymer (filling unresolved Custom Elements with children and loading the DOM twice doesn't seem reasonable to me).

**Comment by TimvdLippe** [comment]
Polymer does not have an opinionated view on SSR. There are other SSR solutions that work with web components in general. For example https://medium.com/@treshugart/%C3%A5server-side-rendering-web-components-e5df705f3f48 and https://github.com/skatejs/skatejs/tree/master/packages/ssr We have no plans to make a Polymer-specific of these generic tools.
