### ISSUE TITLE
legacy-data-mixin doesn't work with wildcards observers

### ISSUE THREAD

**Issue by vdonich** [Polymer/polymer#5428]
Observer is being called despite undefined property value.
Change record is valid, but all value-related properties such as changeRecord.base and changeRecord.value are undefined:
```
{base: undefined, path: "alwaysUndefinedObject", value: undefined}
```
Here's the jsfiddle with example:
https://jsfiddle.net/gaj0umLs/26/

_Originally posted by @vdonich in https://github.com/Polymer/polymer/pull/5266#issuecomment-435533956_

**Comment by bro314** [comment]
Hey Kevin, can you give an update on this? This is blocking the Gerrit Polymer 2 migration at the moment. Thanks, Ben
