### ISSUE TITLE
#UseThePlatform

### ISSUE THREAD

**Issue by caberger** [Polymer/polymer#5431]
Polymer violates the [#UseThePlatform](https://www.polymer-project.org/about) principles.

Please read the following sentence in the [About the Polymer Project](https://www.polymer-project.org/about) page:
_Over time, the stacks we’ve built on top of the platform have pushed web development further and further from the simplicity of view-source and shift-refresh, to a place where every project begins with an overwhelming sea of choices._

With Polymer 2.0 #UseThePlatform was reached. Now, in Polymer 3.0 Javascript modules were used in the import statements, to that we are forced to use a transpiler, e.g. polymer-cli (polymer serve...), Babbel or Webpack.

Proposed solution: Run the Polymer code through `polymer build` with minify turned off and check the result back in again. This will remove modules and replace them by relative imports + extension.

### Description
Polymer 3.0 cannot be used without transpiling the code. 

#### Steps to Reproduce
1. Use the code of any of your Polymer 3.0 projects
2. Open a Terminal or Command Shell and change the current directory to your project
3. `npm install http-server --save-dev`
4. `npx http-server -p 8080`
5. open http://127.0.0.1:8080 in your browser

#### Expected Results
Your website shows as expected.
#### Actual Results
Nothing is displayed. The console log in the Developer Tools windows shows the following error message:

> Uncaught TypeError: Failed to resolve module specifier "@polymer/polymer/polymer-element". Relative references must start with either "/", "./", or "../".

### Browsers Affected
all
### Versions
- Polymer: v3.1.0.

**Comment by LarsDenBakker** [comment]
How do you propose to handle paths in npm/bower dependencies? Following your logic, the paths within component libraries will need to go exactly to where their dependencies are. But once installed, the paths to their dependencies changed as they are now siblings to their dependencies in a bower_components or node_modules folder.

In Polymer 2, polymer serve did a transform of paths to handle this scenario. Not so #usetheplatform then either.

**Comment by TimvdLippe** [comment]
Back when we made this choice, we wrote a blogpost about our reasoning: https://www.polymer-project.org/blog/2018-02-26-3.0-preview-paths-and-names.html Please see the "Moving the platform forward" section, which should contain the answer to your question.

As extra links, we have a experimental tool that does what you described: https://github.com/Polymerlabs/empathy/tree/initial-implementation
Also, we are actively involved with the standards proposal: https://github.com/domenic/import-maps
