### ISSUE TITLE
class$ broken in v2 with webcomponents polyfill v1.3.0 and shadyDOM

### ISSUE THREAD

**Issue by justincy** [Polymer/polymer#5437]
### Description

It appears that `class$` is broken in Polymer v2 with the webcomponents polyfill v1.3.0. Something is preventing the `style-scope` and associated classes from being added on the first render. Subsequent renders calculate and add those classes properly.

#### Live Demo

https://glitch.com/edit/#!/sleepy-cauliflower

In that demo, the text should render in bold. It doesn't render bold when the page loads but it does after clicking the button and making the computed class reevaluate.

This works properly with v1.2.7 of the webcomponents polyfill.

#### Steps to Reproduce

1. Force ShadyDOM
2. Add a computed binding for class$ on any element

#### Expected Results

style-scope and other classes are setup

#### Actual Results

style-scope isn't added to the class list.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [x] Safari 12
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- Polymer: v2.X.X
- webcomponents: v1.3.0

**Comment by kevinpschaaf** [comment]
This does not repro on the latest version of Polymer (2.7.0) and latest webcomponents (1.3.0): https://glitch.com/edit/#!/false-club?path=bower.json:5:0.

On your glitch, if you `rm -rf bower_components && bower install`, you get the latest version of Polymer (that glitch had an old version installed).
