### ISSUE TITLE
Could you bring GraphQL into polymer?

### ISSUE THREAD

**Issue by spyhole** [Polymer/polymer#5438]
as a backend service

**Comment by TimvdLippe** [comment]
There is no reason for it not to be the case. There are actually open source solutions in this space: https://www.webcomponents.org/element/reach-digital/polymer-apollo-client/elements/graphql-query If you have any general questions, please ask them [on our Slack](http://polymer-slack.herokuapp.com/)

**Comment by spyhole** [comment]
thx very much
