### ISSUE TITLE
HTML Imports

### ISSUE THREAD

**Issue by jay8t6** [Polymer/polymer#5454]
[Deprecation] HTML Imports is deprecated and will be removed in M73, around March 2019. Please use ES modules instead.

HTML imports are still going to work with polyfills right?

**Comment by TimvdLippe** [comment]
If you load the html-imports polyfill (which you probably already do to make your site work on all non-Chrome browsers), you are good to go. No additional changes are necessary.

**Comment by jay8t6** [comment]
Thats what I thought. Thanks!
