### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by vogloblinsky** [Polymer/polymer#5463]
Hi,

I have created a benchmark suite for Web Components librairies. Polymer is implemented, and you can see the raw results here : https://vogloblinsky.github.io/web-components-benchmark

I will release soon a blog post explaining in detail that, but i want a feedback of many librairies authors before, to be sure i am not wrong in my implementations.

Source code here : https://github.com/vogloblinsky/web-components-benchmark

Can you have a look and give me some feedbacks ?

Thanks

**Comment by TimvdLippe** [comment]
I will open some issues with feedback. Thanks for the benchmark!

**Comment by vogloblinsky** [comment]
Results are updated : https://vogloblinsky.github.io/web-components-benchmark/#todo

Polymer move with your PR from that :

![image](https://user-images.githubusercontent.com/2841805/50664578-d5aaa500-0fad-11e9-80ab-de1e2717d2cc.png)

to this for TodoMVC benchmark :

![image](https://user-images.githubusercontent.com/2841805/50664585-dc391c80-0fad-11e9-978e-5c1340e52f22.png)
