### ISSUE TITLE
Invalid Zip File

### ISSUE THREAD

**Issue by OverlyEquipped** [Polymer/polymer#547]
I seem to be experiencing some trouble opening a .zip file for Polymer: "Get Core-Pages".

The Message reads:

"Windows cannot open the folder"
"The Compressed (zipped) Folder 'C:\User\Name\Downloads\corepages.zip' is invalid."

Is there a way to fix this issue?  A friend of mine also seems to be experiencing this same problem.

**Comment by aprishchepov** [comment]
ZIPs are constantly 259 bytes for me when trying to download polymer components - ZIP is corrupted.

**Comment by ebidel** [comment]
Can you let us know what components you were trying to download? I just downloaded these 3 from the catalog. Zip was fine.

<img width="305" alt="screen shot 2015-08-30 at 10 09 38 am" src="https://cloud.githubusercontent.com/assets/238208/9568474/3b42b466-4eff-11e5-8432-d062ea74d01e.png">

**Comment by aprishchepov** [comment]
Thanks for following up, no issues anymore - probably my laptop's problem.
