### ISSUE TITLE
router guide was removed in 3.0

### ISSUE THREAD

**Issue by ljmerza** [Polymer/polymer#5478]
2.0 has router guide[here](https://polymer-library.polymer-project.org/2.0/docs/apps/routing) but 3.0 doesn't contain a router guide anymore?

**Comment by arthurevans** [comment]
That's correct. Here's why: 

1) In our old site architecture, we had both the Polymer library and the Polymer App Toolbox on the same page. When we updated our architecture around the 3.0 timeframe, we tried to separate things more. Polymer App Toolbox was basically replaced by the PWA Starter Kit, which got its own site (https://pwa-starter-kit.polymer-project.org/). 

    Because the App Toolbox pages existed on the 2.0 site and we weren't planning a new App Toolbox site, we left those pages in place so links wouldn't break.

2) app-route proved somewhat inflexible. When the team started on PWA Starter Kit, they decided to create a small basic JS router instead. It's part of the [pwa-helpers](https://github.com/Polymer/pwa-helpers) package.

Note that, as mentioned in our [Roadmap](https://github.com/Polymer/project/blob/master/Roadmap.md) we're not actively developing the PWA starter kit at the moment, pending some ongoing R&D work on SSR that may inform the next version of an app starter kit.

Hope that answers the question!
