### ISSUE TITLE
polymer 3 bug: shared style with url() not working

### ISSUE THREAD

**Issue by jpapro** [Polymer/polymer#5485]
### Description
When migrating from Polymer 2 to 3 I had to remove css imports like 
```
<link rel="import" type="css" href="../../bower_components/ion.rangeSlider/css/ion.rangeSlider.css"/>
``` 

and use shared style instead, like this

```
import {} from '@polymer/polymer/lib/elements/dom-module.js';

const styleElement = document.createElement('dom-module');
styleElement.innerHTML =
  `<template>
    <style>
    
(css here)
    </style>

  </template>`;

styleElement.register('ion-rangeslider-style');
```
However, this doesn't work for url():
```
.irs-slider {
  background-image: url(./sprite_skin.png);
}
```
Indeed polymer serve doesn't serve the file, and polymer build doesn't include it neither.

How should this work?

As a work around, I moved the png to a folder images/ next to the source folder, declared it in the polymer.json build file and used a relative path. This works but feels bad: encapsulation in the component is broken.

Thanks in advance
 
#### Expected Results
The image in the background should be seen

#### Actual Results
Image not shown.

### Browsers Affected
- [X] Chromium
- [X] Firefox

Not tested
- Edge
- Safari 11
- Safari 10
- IE 11

### Versions
- @polymer/polymer@3.1.0
- @webcomponents/webcomponentsjs@2.2.7

**Comment by jpapro** [comment]
Hello

This issue is really a blocker for us... 

I'm now trying to give the asserts path to ion-rangeslider-style's dom-module shown above. I don't manage to get this done... Is there some example of shared style in dom-module with the assetpath defined?

Thanks in advance

**Comment by jpapro** [comment]
I've updated the issue to reflect our last findings on the topic: roughly put the resources in url aren't included by default in the build. 

And putting the resource in the same folder fails when building because the component's code is embedded in the shell component, which is in a different folder. 

So only moving away from the source folder does the trick: the relative path to there is the same whether you're serving directly the source (so from the component) or the build (from the shell component).

Overall this workaround defeats the purpose of components, since now you've resources out of the source folder in some common images folder...

**Comment by jsilvermist** [comment]
You should be able to use `import.meta.url.replace(/[^/]*?$/, '');` in the shared style and then have the images relative to the shared style instead of the end point.

ie.
```js
const importLocation = import.meta.url.replace(/[^/]*?$/, '');
...
styleElement.innerHTML =
`<template>
  <style>
    .irs-slider {
      background-image: url(${importLocation}sprite_skin.png);
    }
  </style>
</template>`;
```

**Comment by jpapro** [comment]
Hi @jsilvermist 

Thanks a lot, that does the trick!

Adding a line in the documentation, around [there](https://polymer-library.polymer-project.org/3.0/docs/devguide/style-shadow-dom#style-modules) most likely, would be a great help I think.

Thanks again
