### ISSUE TITLE
appreciate your feedback for custom element reactions diagram

### ISSUE THREAD

**Issue by AndyOGo** [Polymer/polymer#5492]
I just released an adapted version of the interactive react lifecycle methods diagram for custom element reactions:
https://andyogo.github.io/custom-element-reactions-diagram/

If you have time, I would appreciate your feedback very much.

**Comment by web-padawan** [comment]
For the maintainers: this is a duplicate of w3c/webcomponents#784

Some people watching all these repos (like me) have received this kind of GitHub notifications many times. I would recommend to continue discussion there.

**Comment by AndyOGo** [comment]
@web-padawan Thanks for your hint.
Sorry for spamming 😇

**Comment by TimvdLippe** [comment]
Closing this in favor of https://github.com/w3c/webcomponents/issues/784
