### ISSUE TITLE
Javascript references fail in Cognito

### ISSUE THREAD

**Issue by suared** [Polymer/polymer#5498]
module '../../node_modules/buffer/index.js' does not provide an export named 'Buffer'
However - 1) it does appear 2) when export is moved to the function vs. the alias at the top it is recognized  3) Other libraries follow similar and looser syntax that fixing this one instance leads to finding similar import issues in other instances

#### Steps to Reproduce
Example:  Using polymer startup kit anywhere, add:  import {Buffer} from 'buffer'
*  Note:  One of the following AWS modules likely added the reference when adding to npm:  amazon-cognito-identity-js or amazon-cognito-auth-js

Call it from somewhere on load ( a reducer in my case ):  Buffer.isBuffer({})

During the load it will fail with the message mentioned above.  If you change the style of the import and move it to the function it works.  Though I manually fixed this instance, then I got another export error for a different library.  Is there a way to enable Polymer to enable recognizing this other style on libraries that are imported/ not written by the project?

#### Expected Results
No error is thrown

#### Actual Results
Error thrown in the console while trying to access -->  module '../../node_modules/buffer/index.js' does not provide an export named 'Buffer'

### Browsers Affected

- [ X] Chrome  (only testing here)
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions
:~/localdev/nodespace/ui$ npm polymer -version 
3.5.2

**Comment by suared** [comment]
To clarify, above reproduce is a simpler way to reproduce.  The way I discovered was not trying to use the library directly but using AWS Cognito libraries like this:          new CognitoUserAttribute(dataEmail);
  which in turn refer to the Buffer library that fails

**Comment by jangolano** [comment]
Are you building your application with webpack?  The AWS Javascript Library uses ES6 imports and the Buffer library uses older module exports.
