### ISSUE TITLE
incorrect result of FlattenedNodesObserver

### ISSUE THREAD

**Issue by hzmnet** [Polymer/polymer#5505]
i found some elements could unlimit to list in the addedNodes. like:  `<img><a>`
sample 1
```
<div>
	<slot>
		<slot>
			<img><a><a><a><a></a></a></a></a></img>
		</slot>
	</slot>
</div>
```

result is : `<div><img><a><a><a><a></a></a></a></a></img></div>`

sample 2
```
<div>
	<slot>
		<slot>
			<img><span><a></a></span></img>
		</slot>
	</slot>
</div>
```

result is : `<div><img><span></span></img></div>`

sample 3
```
<div>
	<slot>
		<slot>
			<span><a><a></a></a></span>
		</slot>
	</slot>
</div>
```

result is : `<div><span></span></div>`

**Comment by hzmnet** [comment]
what I want is the list the children of the slot element. is there any other method to get them without the full children tree?

**Comment by TimvdLippe** [comment]
I think you want https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/assignedNodes with `{flatten: true}`

**Comment by hzmnet** [comment]
> I think you want https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/assignedNodes with `{flatten: true}`

it also having above bug
