### ISSUE TITLE
setProperties not work

### ISSUE THREAD

**Issue by zarudYin** [Polymer/polymer#5521]
### Description
When using `setProperties` to change 2 sub-attributes, the sub-element cannot display 2 changes correctly. Only the first sub-property change in the object will be displayed.

#### Code
```js
class PolymerDemoApp extends PolymerElement {
    static get template() {
        return html`
            <button on-click="handleClick">Click</button>
            <info-area info-obj="{{user}}"></info-area>
        `;
    }

    static get properties() {
        return {
            user: {
                type: Object,
                value: {
                    name: 'tom',
                    sex: 'man'
                }
            }
        };
    }

    handleClick() {
        this.setProperties({ 'user.name': 'jack', 'user.sex': 'woman' });
    }
}

window.customElements.define('polymer-demo-app', PolymerDemoApp);

class InfoArea extends PolymerElement {
    static get template() {
        return html`
            <div>name: {{infoObj.name}}, sex: {{infoObj.sex}}</div>
        `;
    }

    static get properties() {
        return {
            infoObj: {
                type: Object,
                value: null
            }
        };
    }
}

window.customElements.define('info-area', InfoArea);
```
![image](https://user-images.githubusercontent.com/19502736/55937622-fa2cb200-5c6b-11e9-8307-f940b33e12bf.png)

**after click button**

![image](https://user-images.githubusercontent.com/19502736/55937663-1cbecb00-5c6c-11e9-9539-09328b4375cd.png)

**the sex is not change**

### Versions
- Polymer: v3.1.0
- webcomponents: v2.0.0

**Comment by kevinpschaaf** [comment]
Batching of _path changes_ via `setProperties` is not supported for this reason.  See the API docs here: https://polymer-library.polymer-project.org/3.0/api/polymer-element#PolymerElement-method-setProperties
