### ISSUE TITLE
Behaviors may not run `registered` if legacy element is subclassed

### ISSUE THREAD

**Issue by dfreedm** [Polymer/polymer#5567]
Root cause of https://github.com/PolymerElements/iron-a11y-keys-behavior/issues/93

In this scenario:
```html
<script type="module">
  import {Polymer} from '@polymer/polymer/polymer-legacy.js';
  const behavior = {
    registered() {
      this.fizz = {};
    }
  };
  Polymer({
    is: 'x-foo',
    behaviors: [behavior]
  });

  class XBar extends customElements.get('x-foo') {}
  customElements.define(XBar.is, XBar);
</script>

<x-bar></x-bar>

<script>
  addEventListener('load', () => {
    const el = document.createElement('x-foo');
    document.body.appendChild(el);
  })
</script>
```

`x-bar` will have `registered` called on it, and `x-foo` will not.
This means that `fizz` will only be set on `x-bar`, and not on `x-foo`'s class, which is causing the error in iron-a11y-keys-behavior.

**Comment by azakus** [comment]
This is caused by moving behavior processing to be more like 1.x, which happened in 3.2.
