### ISSUE TITLE
Demo & Edit on Github links not working on component page

### ISSUE THREAD

**Issue by prtksxna** [Polymer/polymer#557]
On http://www.polymer-project.org/docs/elements/paper-elements.html#paper-dialog-transition links to
- https://github.com/Polymer/docs/edit/master/docs/elements/paper-elements.md
- http://www.polymer-project.org/components/paper-dialog-transition/demo.html

lead to 404s.

**Comment by gitact** [comment]
The problem has come again in the brand-new pages of the website www.polymer-project.org (e.g. https://www.polymer-project.org/1.0/start/first-element/intro )
Every "EDIT ON GITHUB" link under the main page title points to an inexistent page "https://github.com/Polymer/docs2/edit/master/app/1.0..."
