### ISSUE TITLE
Input examples aren't recognized as input fields properly under vimium

### ISSUE THREAD

**Issue by unya** [Polymer/polymer#559]
Input elements in the http://www.polymer-project.org/components/paper-elements/demo.html#paper-input demo have issues if a Chrome extension (like Vimium) is listening to key events and doesn't appear to register properly as "input element" (thus not switching to "input" mode).

While this could be a Vimium bug (as Vimperator on firefox did not have the same issue), it's possible that similar problems could surface with various accessibility-related extensions/plugins, or any other extension that globally listens to key events (just in case, I'm going to report a bug with vimium as well).

Tested with:
Chrome/linux/x86_64 35.0.1916.153 (Official Build 274914)
Vimium 1.44

matching issue in vimium bugtracker: https://github.com/philc/vimium/issues/1083

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
