### ISSUE TITLE
Missing hover states

### ISSUE THREAD

**Issue by escapist** [Polymer/polymer#561]
It seems a lot of clickable/tappable objects in the online Paper Elements library are missing hover/cursor states. Honestly, I wasn't sure if that was deliberate.

Some spots where clickable objects are without hover/cursor states:
* The sidenav tabs used to navigate the (Paper Elements](http://www.polymer-project.org/components/paper-elements/demo.html) area itself
* The labels for [paper-radio-button](http://www.polymer-project.org/components/paper-elements/demo.html#paper-radio-button)
  * (The labels for [paper-checkbox](http://www.polymer-project.org/components/paper-elements/demo.html#paper-checkbox) aren't clickable at all?)
* [paper-slider](http://www.polymer-project.org/components/paper-elements/demo.html#paper-slider)
* [paper-tabs](http://www.polymer-project.org/components/paper-elements/demo.html#paper-tabs)
* The interactive demo at the bottom of [paper-shadow](http://www.polymer-project.org/components/paper-elements/demo.html#paper-shadow)

**Comment by kbwatts** [comment]
+1

**Comment by kbwatts** [comment]
A nice, simple solution example for paper-tabs hover effect exists on the official Android home page: http://www.android.com/

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
