### ISSUE TITLE
404 on ctrl-shift-r refresh of non-home page in starter kit

### ISSUE THREAD

**Issue by eatonphil** [Polymer/polymer#5664]
### Description
Doing a hard-refresh of a non-home page view causes a 404 in the starter kit.

#### Live Demo
None.

#### Steps to Reproduce
1. Create a new polymer-3-start-kit through `polymer init`
1. Build the project with `yarn build`
1. Start a server and navigate to the home page (`cd build/es6-bundled && python3 -m http.server 9091 && open localhost:9091`)
1. Go to view 3 (http://localhost:9091/view3)
1. Hard-refresh with ctrl-shift-r

#### Expected Results
A hard-refresh should load the page correctly. A hard-refresh on the home page (http://localhost:9091) loads successfully.

#### Actual Results
A hard-refresh always causes the non-home page view to 404. Even after a hard-refresh if you soft refresh the non-home page loads correctly.

### Browsers Affected
- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions
The yarn.lock file is attached.
[yarn.lock.txt](https://github.com/Polymer/polymer/files/4741216/yarn.lock.txt)

**Comment by jsilvermist** [comment]
This is expected if using base Python HTTP server.

You need something to redirect requests to index.html. You might want to check out:
https://www.npmjs.com/package/es-dev-server

**Comment by eatonphil** [comment]
That makes sense, thanks. The cached behavior through me off.
