### ISSUE TITLE
Stamp a new release of Polymer + elements with improved trusted type support

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer#5699]
We've landed a number of changes to improve trusted types support in Polymer and our elements, we should stamp a release with these changes. May include externalizing some minor internal changes, like using the html tagged template literal instead of innerHTMLing a constant

**Comment by bicknellr** [comment]
(relaying from the meeting we just had)
The elements seem to already be using Polymer's `` html`...` `` templates, so they might not need any changes for compatibility with trusted types. I'll just work on updating the core library for now and, once that's in, we can see if any of the elements need follow-on changes.

**Comment by freshp86** [comment]
Is there an ETA on when a new version with TrustedTypes support will be pushed to NPM?

**Comment by rictic** [comment]
We're aiming for next week. @bicknellr is out on vacation this week

**Comment by bicknellr** [comment]
[`@polymer/polymer@3.5.0`](https://www.npmjs.com/package/@polymer/polymer/v/3.5.0) is now published.
