### ISSUE TITLE
simple style attribute bindings and styleObject filter not working in IE11 (maybe other versions as well)

### ISSUE THREAD

**Issue by mareksuscak** [Polymer/polymer#589]
see example in IE11 (other IEs not tested yet) here:

http://jsfiddle.net/k4L88/6/ - styleObject
http://jsfiddle.net/k4L88/7/ - simple style binding

Text in span on line 10 should be green but is red in IE. Chrome and Firefox are working just fine.

**Comment by abourget** [comment]
Kabunga !!!
