### ISSUE TITLE
Labels should have text selection disabled by default

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#595]
Currently, we're inconsistent on applying user-select: none to controls that include text labels, like buttons, tabs and checkboxes.

Paper-button includes:

  -webkit-user-select: none;
  user-select: none;

Paper-tabs, paper-checkbox and paper-radio-button don't have these properties.

The demos for all these elements include:

      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;

It seems like user-select: none is the expected behavior for a text label, and we should use the same set of prefixes consistently across the controls.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
