### ISSUE TITLE
paper-slider does not work properly in Safari and FireFox

### ISSUE THREAD

**Issue by aaronmak** [Polymer/polymer#599]
# Safari

![screen shot 2014-07-03 at 6 38 23 pm](https://cloud.githubusercontent.com/assets/3712602/3468462/2cfe5fa8-029e-11e4-9aa2-90ebab60f6ff.png)
# Firefox

![screen shot 2014-07-03 at 6 39 16 pm](https://cloud.githubusercontent.com/assets/3712602/3468480/880068d8-029e-11e4-8781-58d01c09f49e.png)

**Comment by lacrossetech** [comment]
Did this ever get figured out?  I am still having this exact issue.
