### ISSUE TITLE
<polymer-element on-*> style listeners listen on shadowRoot not host

### ISSUE THREAD

**Issue by esprehn** [Polymer/polymer#614]
If you do &lt;polymer-element name="my-element" on-my-event="{{ handle }}">

and then a subclass extends my-element and has a child that dispatches the "my-event" your listener will never be called because it was added to the ShadowRoot of the my-element, not to the subclass.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
