### ISSUE TITLE
Provide a way to support animations associated with data changes which mutate dom

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#620]
Here's a simple example using `template if`:

http://jsbin.com/qilixe/2/edit

Additional discussion: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/polymer-dev/Sp0rJmitpNQ/RIX1xpOKOGAJ

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
