### ISSUE TITLE
on-click doesn't work with bootstrap and jQuery

### ISSUE THREAD

**Issue by kielni** [Polymer/polymer#625]
jQuery v2.0.3
Bootstrap v3.0.3

The on-click seems to be sending a wrapped object that causes problems when jQuery tries to look for other click handlers because it doesn't have a getAttribute method.

I have a custom element like this, on a page that includes Bootstrap and jQuery. 

```
<link rel="import" href="../bower_components/polymer/polymer.html">
<polymer-element name="chart-placeholder">
<template>
    <div class="fa fa-bar-chart-o" style="font-size:200px; cursor:pointer" 
        on-click="{{clickHandler}}"></div>
</template>
<script>
Polymer('chart-placeholder', {
    clickHandler: function(event, detail, sender) {
        this.fire('core-signal', {name: "chartClicked", data: "xy"});
    }
});
</script>
</polymer-element>
```
When I click it in Firefox 29, I get an error every time in Sizzle.attr = function( elem, name ): elem.getAttribute is not a function 

elem is Document { impl=document, treeScope_={...}, documentElement=GeneratedWrapper, more...} 
There is no elem.getAttribute method on Document.  I thought the event handlers weren't supposed to see the wrapped elements?

Here's the stack trace:
```
Sizzle.attr(elem=Document { impl=document, treeScope_={...}, documentElement=GeneratedWrapper, more...}) jquery.js (line 1707)
Sizzle.selectors.filter.ATTR/<(elem=Document { impl=document, treeScope_={...}, documentElement=GeneratedWrapper, more...}, context=Document 1261204759648, xml=false) jquery.js (line 1900)
elementMatcher/<(seed=[Document { impl=document, treeScope_={...}, documentElement=GeneratedWrapper, more...}], context=Document 1261204759648, xml=false, results=[], expandContext=false) jquery.js (line 2395)
matcherFromGroupMatchers/superMatcher() jquery.js (line 2602)
select() jquery.js (line 2769)
Sizzle() jquery.js (line 1154)
jQuery.event.handlers() jquery.js (line 4721)
jQuery.event.dispatch() jquery.js (line 4658)
jQuery.event.add/elemData.handle() jquery.js (line 4360)
invoke() events.js (line 404)
dispatchBubbling() events.js (line 323)
dispatchEvent() events.js (line 287)
dispatchOriginalEvent()
```
I can reproduce it by adding Bootstrap and jQuery to the tutorial's index.html (after polymer.js); the on-click in post-card.html does the same thing.

**Comment by martingust** [comment]
This worked for me with the webcomponents.js (v0.5.1):

(function(document){
    //bootstrap.js - bootstrap.min.js
})(wrap(document));

**Comment by martingust** [comment]
Slight modification of @smasala's fix did it for me with webcomponents.js (v0.5.1).

```javascript
(function(document){
    //bootstrap.js - bootstrap.min.js
})(wrap(document));
```

**Comment by Nevraeka** [comment]
@martingust & @arv - Can we close this issue or do more code fixes need to be applied?

**Comment by martingust** [comment]
@Nevraeka that is all I needed to do to get it to work.

**Comment by robdodson** [comment]
Closing. I've been told that there's no way for Polymer to wrap `document` on your behalf, it must be done by the developer at runtime.

**Comment by HaykoKoryun** [comment]
A tedious workaround I just used to get around this annoying problem was to call `evt.stopPropagation` and `return false;`. It might not work for all cases but for buttons and things that you know won't need to bubble their events upwards it's a good enough solution.
