### ISSUE TITLE
Need a way to schedule a task at or inside the next frame

### ISSUE THREAD

**Issue by esprehn** [Polymer/polymer#627]
If you do requestAnimationFrame from inside a RAF callback it schedules your code to happen in the next frame which can cause you to miss frames if your code is already running inside a raf and doesn't realize it.

For example the track library has your code running inside a raf callback, if you change the data model it'll stamp some new DOM from inside the microtask checkpoint as you exit the track raf callback. If inside the attached() callback for that new DOM you then do async() it won't happen until the next frame, not the current one, which means if you apply a transform in attached() you get to see the element flicker in the old location and then in the new location.

I'm not sure what the right API is for this, but you need a way to ensure that your raf callback always happens before the next paint when used from inside attached/detached/created and track library callbacks.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
