### ISSUE TITLE
`fire` should lowerCase() event names

### ISSUE THREAD

**Issue by zyklus** [Polymer/polymer#634]
Since all event names are automatically lower-cased from HTML, `fire` should do the same:

``` html
<polymer-element on-customEventName='{{ handler }}'>
```

``` js
this.fire( 'customEventName' ); // doesn't work
this.fire( 'customeventname' ); // works
```

**Comment by arthurevans** [comment]
I'm going to open a docs ticket to note this as a possible point of confusion.

I don't know if there's much work happening on a devtools extension at present -- @garlicnation is this something the linter could check for?

**Comment by garlicnation** [comment]
It's totally something that could be added to the linter!

**Comment by TimvdLippe** [comment]
Closing this issue since `fire` is now moved to the legacy element in Polymer 2
