### ISSUE TITLE
Nodes do not appear in this.$ when they become visible after a <template if=""> condition has been met.

### ISSUE THREAD

**Issue by hesamrabeti** [Polymer/polymer#642]
Nodes do not appear in this.$ when they become visible after a ```<template if="">``` condition has been met.

As an example, if the element below is instantiated and at some later time element.setDone() and element.printValue() are executed sequentially, the console.log() command in printValue() fails with a null pointer dereference.

```html
<polymer-element name="x-element">
  <template>
    <template if="{{done}}">
      <paper-input id="input"></paper-input>
    </template>
  </template>

<script>
Polymer('x-element', {
  setDone: function() {
    this.done = true;
  }.

  printValue: function() {
    console.log(this.$.input.value);
  }
});
</script>
</polymer-element>
```

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

**Comment by abhinavmca0909** [comment]
plz give me one example
