### ISSUE TITLE
Safari: createElement in onLoad - Event

### ISSUE THREAD

**Issue by diet3rix** [Polymer/polymer#644]
i habe a following Script in my site (this is a shorted version of a third-party-script):

``` js
window.onload = function() {
  UpdateInputElements();
}

function UpdateInputElements(){
    for(var i = 0; i < document.forms.length; i++){
        var form = document.forms[i];
        var inputElement = document.createElement("INPUT");
        form.appendChild(inputElement);
    }
}
```

It works perfect on chrome, but not on Safari. I get following Exception:
NotFoundError: DOM Exception 8: An attempt was made to reference a Node in a context where it does not exist.

What can i do to fix it? Maybe you know a workaround?

Thank you! :)

**Comment by errows** [comment]
Issue referenced is now here: https://github.com/webcomponents/webcomponentsjs/issues/109
