### ISSUE TITLE
Would like a way to do ?= with non-boolean results

### ISSUE THREAD

**Issue by eseidel** [Polymer/polymer#645]
Would like a way to do ?= with non-boolean results

This seems to be a common pattern for me:
`<a href="{{data | sometimes_link}}">foo</a>`

Due to the quirks of HTML when a has an empty href= its colored blue, when it has no href= its not colored at all.  I'd like the no-href behavior w/o having to resort to attribute selectors to disable link coloring.

Maybe there is a simpler way.

Example:
```
<script src="http://www.polymer-project.org/platform.min.js"></script>
<script src="http://www.polymer-project.org/polymer.min.js"></script>

<polymer-element name="my-element">
  <template>
  <div> using ?=
    <a href?="{{ true | myFilter }}">apple</a>
    <a href?="{{ false | myFilter }}">no link</a>
  </div>
  <div> using just =
    <a href="{{ true | myFilter }}">apple</a>
    <a href="{{ false | myFilter }}">no link</a>
  </div>
  </template>
  <script>
    Polymer('my-element', {
      myFilter: function(value) {
      if (value)
        return "http://apple.com/";
      return "";
      }
    });
  </script>
</polymer-element>
<my-element></my-element>
```

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
