### ISSUE TITLE
Need consistent path behavior

### ISSUE THREAD

**Issue by robdodson** [Polymer/polymer#651]
Original thread: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/polymer-dev/JcBQZCPamcY/OMKhLetXg-4J

If I create an element that looks like this:

``` html
<polymer-element name="x-foo">
  <template>
    <template repeat="{{link in links}}">
      <div><a href="#ok{{link}}">Ok Hash Link {{link}}</a></div>
    </template>
    <div><a href="#bad">Bad Hash Link</a></div>
  </template>
  <script>
    Polymer('x-foo', {
      links : [2,3,4]
    });
  </script>
</polymer-element>
```

and then import it into my project, it will treat the `href`s differently. The `href`'s inside of the repeating template will look like this:

```
<a href="#ok2">
<a href="#ok3">
<a href="#ok4">
```

but the `href` outside of the repeating template will look like this:

```
<a href="x-foo.html#bad">Bad Hash Link</a>
```

**Comment by ssorallen** [comment]
@sorvell, was it intentional to rewrite `href` for anchor elements? It doesn't seem like those should be rewritten at all.

**Comment by sorvell** [comment]
Yes, the idea is that you should always be able to link resources with paths relative to the importing document. If it's an absolute url or a # based one we should bail.

**Comment by azakus** [comment]
The rewriter doesn't check that the node is an anchor, it just rewrites href. The simplest fix is to ignore hash-only hrefs for rewriting.
