### ISSUE TITLE
Select value and options data bound to attributes

### ISSUE THREAD

**Issue by Pierce71588** [Polymer/polymer#664]
I am running into a problem when trying to data bind various elements and they rely on each other. I looked to see if there were similar issues but I didn't know exactly how to describe this problem I am having.

Here is a simplified jsbin that I created.
http://jsbin.com/sudezizu/1/edit?html,console,output

You will notice that I have a repeating template that is data bound to "testData.queries". Then the select box has a template to choose 1 of the "testData.queries". This functionality works properly and when you "add" queries, it adds it to the drop down.

However, you will notice that I am passing "testData" in as an attribute to the element. The queries populate properly, but the specific query you have selected is not selected in the drop down. If you run:

document.getElementById('test').testData.queryNum;

In the console you will see that the value is set correctly. And if you run:

document.getElementById('test').testData.queryNum = 2

you will notice it does update the drop down correctly now. So it is data bound.

My guess is that it is setting the value of the drop down before it is setting the queries variable. So the option doesn't exist when it sets the drop down value. However, my understanding is this is why the updates to the data bindings are asynchronous so you don't run into this problem. 

Any suggestions? I would be willing to tell the system to update all data bindings but it doesn't appear that is possible and I don't know how to fake the system into thinking there is a change when there really isn't. 

Thanks,
Daniel

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
