### ISSUE TITLE
<tr template repeat> throws error in Firefox/Safari

### ISSUE THREAD

**Issue by Sb87** [Polymer/polymer#671]
The attached test page causes the following error in Firefox 31:

Invalid expression syntax: item in items
Error: as and in can only be used within &lt;template bind/repeat&gt;

As &lt;tr template repeat&gt; is the [standard alternative](http://www.polymer-project.org/docs/polymer/databinding-compat.html#elements-that-cant-contain-a-template) to &lt;template&gt; in tables for browsers without template support, the expected outcome is the table properly renders 3 rows. This works fine in Chrome 37 and IE 11.

```html
<!doctype html>
<html>
<head>
  <script src="platform.js"></script>
  <script src="polymer.js"></script>
</head>
<body>
  <polymer-element name="test-foo">
    <template>
      <table>
        <tr template repeat="{{item in items}}">
          <td>{{item}}</td>
        </tr>
      </table>
    </template>
    <script>
      Polymer('test-foo', {
        created: function() {
          this.items = [1, 2, 3];
        }
      });
    </script>
  </polymer-element>
  <test-foo></test-foo>
</body>
</html>
````

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
