### ISSUE TITLE
Incomplete zip files.

### ISSUE THREAD

**Issue by fozziethebeat** [Polymer/polymer#676]
I downloaded the paper components and received the following error on my Macbook Air when trying to unzip the archive.  This looks like a previous error reported where Bower ran out of disk space when generating the zip file.

End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of archive.zip or
        archive.zip.zip, and cannot find archive.zip.ZIP, period.

**Comment by hzacchi** [comment]
This is happening for me too.

**Comment by hzacchi** [comment]
Ah, I get it! 
You first need to select the element that you want, then click 'star' icon. Once you've selected all your elements, click the Star icon at the top left of the page. Than you'll download all the components you've selected at once. 

I was being stupid, but the functionality isn't the most straightforward.
