### ISSUE TITLE
External stylesheet not applied when <script> precedes <template>

### ISSUE THREAD

**Issue by h0ru5** [Polymer/polymer#677]
example is here: http://plnkr.co/edit/agz4ER3qhcgOtM6iN1CG?p=preview

when importing the stylesheet via ``<link rel="stylesheet>`` inside a polymer elment (I figured out is has to be inside the template), it will only be imported when the element is registered declaratively with ``noscript``.

the AJAX-Request goes out also when the element is registered imperatively, but the stylesheet is not inserted into a style element in the shadow DOM.

Bug?

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
