### ISSUE TITLE
Provide sugar for putting static methods on an element constructor

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#684]
It's sometimes valuable to put static methods on an element's constructor. The constructor is available only after registration and the `polymer-ready` method must be used to access and populate the constructor. The timing of this is inconvenient.

It would be better if there were simply something like a `statics` object on the element prototype for sugaring this. Strawman:

http://jsbin.com/qugazu/1/edit

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
