### ISSUE TITLE
i want get data in array (Polymer)

### ISSUE THREAD

**Issue by krol3ong** [Polymer/polymer#693]
![8-8-2557 8-59-54](https://cloud.githubusercontent.com/assets/8099930/3851986/577a64a2-1ea0-11e4-86ef-08b0db4e9e0b.jpg)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
