### ISSUE TITLE
Stoped to render on firefox after .35 update (trying to fix jquery conflict)

### ISSUE THREAD

**Issue by ronydj** [Polymer/polymer#697]
Hi Guys,

I updated yestarday to the 0.35 release trying to fix the problem with getDefaultComputedStyle error with jquery on firefox.

But after this update my test app has stopped to render on Firefox. Its rendering only on IE and Chrome

You can check my test app here:

http://widget.centraltorpedos.com.br/gmaps/

Another problem is that, the getDefaultComputedStyle  error was solved for jquery 1.10.02. But if you use the newest jquery version (1.11.1) implementation, this issue  still happens .

**Comment by nazar-pc** [comment]
@ronydj, there was bug in jQuery and I fixed it, currently it is available in latest stable jQuery version. Is this still an issue or can be closed?

**Comment by ronydj** [comment]
thanks Nazar. It can be closed.

att,

Rony Barbosa Tomaz
-------------------------------------------------------------------------------
Computer Engineer
Universidade Federal de Goiás
+55 62 9135 86 49 (Goiânia- Goiás)

-------------------------------------------------------------------------------
