### ISSUE TITLE
Problems with a tags on Safari and Firefox

### ISSUE THREAD

**Issue by kristenmills** [Polymer/polymer#698]
I'm working on a Polymer/Rails/Angular application and there is a problem with having any links on the page.  
Let's say I have this tag
```html
<a href='http://www.polymer-project.org' target='_blank'> Polymer Project</a>
```
When I click on this link on my page, in a new window it goes to the page http://server:port/[object%20Object] (where server:port is where the rails app is running).

If I look back on the page I was on, instead of the link above, it now says
```html
<a href='[object Object]' target='_blank'> Polymer Project</a>
```

It seems to be an issue specific to the tech stack and it works fine on Chrome.  When I comment out polymer.js, it works fine which is why I assumed it was a polymer bug vs a Rails or Angular bug.

**Comment by ebidel** [comment]
Closing stale issues. Please reopen if you have a reproducible test.
