### ISSUE TITLE
polymer should warn about failing to register a template

### ISSUE THREAD

**Issue by eseidel** [Polymer/polymer#699]
```
<polymer-element name="cq-foo">
  <template></template>
  <script> Polymer('cq-bar', {}); </script>
</polymer-element>
```
Currently just silently fails.  This makes sad panda.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
