### ISSUE TITLE
Making user change events independent of bound value change

### ISSUE THREAD

**Issue by jlebrech** [Polymer/polymer#702]
When you bind a value to an element such as paper-toggle-button you can't bind the value to anything and expect the change callback to be just user interaction, it is also affected by the change to the bound value.

there should be an event that works like the native change event

https://developer.mozilla.org/en-US/docs/Web/Events/change

this would also make sense as as it stands change callback and bindingChanged will both fire.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
