### ISSUE TITLE
Template directives do not function on template in polymer-element

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#703]
Given:

     <polymer-element name="my-element">
       <template if="{{stuff}}">
       </template>
       ...
     </polymer-element>

The `if` direction here is ignored. Likewise other template directives `repeat` and `bind` are ignored.

This has been a source of confusion for users. Polymer should either (1) warn if these directives are used where they will not apply or (2) wrap the template to make this work.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
