### ISSUE TITLE
Blank screen and no error if custom element is not registered

### ISSUE THREAD

**Issue by lavelle** [Polymer/polymer#705]
Creating a new element
```html
<polymer-element name="my-foo"></polymer-element>
```
without declaring it with
```js
Polymer('my-foo', {});
```
causes the entire page to fail to render. No errors are displayed in the console, and while the correct DOM tree is present, nothing is visible. Native elements like `div` and `h1` have the correct dimensions and position, when highlighted with the Chrome inspector, whereas all custom elements have height and width zero, regardless of their styling.

Ideally, other elements on the page should be immune to this, leaving only the undefined element unrendered. At the very least, however, an error should be logged to the console warning that a custom element has been declared in the HTML but not registered in JS.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
