### ISSUE TITLE
Some script imports don't work when vulcanizing

### ISSUE THREAD

**Issue by lavelle** [Polymer/polymer#706]
This is the issue that lead to me discovering #705. When running a Polymer app through vulcanize with both the `--csp` and `--inline` flags, external scripts won't be imported into the component.

So, in a component,

```html
<polymer-element name="my-foo">
    <script>
        Polymer('my-foo', {});
    </script>
</polymer-element>
```
will work, but

```html
<polymer-element name="my-foo">
    <script src="my-foo.js"></script>
</polymer-element>
```
where `my-foo.js` contains

```js
Polymer('my-foo', {});
```
will not work.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
