### ISSUE TITLE
Version Check in DevTools

### ISSUE THREAD

**Issue by nevir** [Polymer/polymer#712]
So, here's the idea:

* Polymer `console.log`s its current version, along with a background image.
* The background image has a URL like `polymer-project.org/versioncheck/X.Y.Z.png` (w/ the version of Polymer that's running).
* Every time we release Polymer, we re-generate images for each version under `/versioncheck`.

Boom; a version check that only runs when you open the inspector!

We'd probably want a scheme for images something like:

* Z version mismatch: white background
* Y version mismatch: yellow background
* X version mismatch: red background

The images will have to have a relatively short cache lifetime, too (week? day?).

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
