### ISSUE TITLE
Polymer elements not loading using Firefox OS 2.0

### ISSUE THREAD

**Issue by ScottDowne** [Polymer/polymer#713]
Looks like examples on this page: http://www.polymer-project.org/components/paper-elements/demo.html

Do not show up using Firefox OS 2.0. You can test this using the 2.0 simulator found here: https://ftp.mozilla.org/pub/mozilla.org/labs/fxos-simulator/

It works on 1.4 but broken on 2.1.

Looks like a change in Firefox OS 2.0 did this, and not something changing in Polymer, but wanted to give you guys a heads up and see if I could get any insight as to what may be wrong.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

**Comment by TitanNano** [comment]
Hello, I still have this issue with firefox os 2.6. Can you fix this problem or does Mozilla need to provide compatibility here?
