### ISSUE TITLE
Polymer elements not rendering in Android 4.1.2 and 4.2.1. Works on 4.4.2

### ISSUE THREAD

**Issue by gngeorgiev** [Polymer/polymer#714]
You can see attached a screenshot of the two emulated devices. I also tried on a real device with 4.2.1 I would really like not to drop polymer as I would love to build a mobile app with it. Can you suggest any workaround? I would like to target at least android 4.x.x. Moreover, it seems that its the CSS that is problematic, there are no errors on the console.

Thank you guys.

![polymer](https://cloud.githubusercontent.com/assets/2229435/3941834/d74f77b2-2544-11e4-9fde-48dc3dcf5502.png)

**Comment by kildem** [comment]
Do you have any plan to get polymer work with android browser 4.0?

**Comment by robdodson** [comment]
@kildem no the old android browser is not supported

**Comment by kildem** [comment]
I can see it isn't supported ... so you don't have any plan to support it on android 4.0 :(

**Comment by kildem** [comment]
@robdodson I can see it isn't supported ... so you don't have any plans to support it on android 4.0 :(

**Comment by robdodson** [comment]
@kildem no sorry. That's a very old version of Android with fairly [small market share](https://developer.android.com/about/dashboards/index.html) and the amount of effort to try to polyfill old android browser would be pretty huge. Our support starts at Android 4.4

**Comment by kildem** [comment]
thanks for answer @robdodson, I have an android 4.0 e-ink e-reader. At the moment there isn't any android 4.4 e-ink device with big screen ... I hope the manufacturers will update these devices to more recent version soon.

**Comment by kildem** [comment]
when I open a polymer website (for example polymer-project.org) in a not supported browser I can see only a blank page. Instead it would be better if the user receive a message, for example: Your browser is out-of-date. Please download one of these up-to-date, free and excellent browsers....

**Comment by robdodson** [comment]
@kildem I don't think this is something Polymer itself would implement, instead we'd leave it up to the developer. You can either try to feature detect which browser the user is on using JS or do UA sniffing server side and send down a different experience for those folks on Android browser
