### ISSUE TITLE
Possibility to change default delimiter from curly braces

### ISSUE THREAD

**Issue by tjsavage** [Polymer/polymer#718]
Add a possibility to change the default delimiter from {{ }} to something else.

Maybe move it out into an external service, something similar to: https://docs.angularjs.org/api/ng/provider/$interpolateProvider

Helps a lot in integrating Polymer with other Frameworks like Meteor for example

**Comment by nmabhinandan** [comment]
Any news?

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

**Comment by ktiedt** [comment]
Since this came up again in Slack I am commenting here to get bring some eyes back to it.

**Comment by jargnar** [comment]
+1, this will be nice to have

**Comment by abdonrd** [comment]
:+1:

**Comment by ktiedt** [comment]
There are a couple challenges I see with this feature though:

1) Is this a per element option or an all or nothing option?
2) If all or nothing, you would have to not use any other pre-made components or, manually search/replace every one you did use to match your config...

(Things I have not seen mentioned in the thread above)

**Comment by JeremybellEU** [comment]
I think the only feasible option is to choose 1. If you would choose option 2, your element is not reusable anymore. It will break elements in the project it is used in.

Therefore when implementing option 1, the chosen binding should be known during the `Polymer({})` call. It would need a new field in `this`.

The [current regex](https://github.com/Polymer/polymer/blob/master/src/lib/annotations/annotations.html#L92) is compiled beforehand. Therefore I propose the following changes in the code to achieve this:

1. Extract the compiled regex to a method
 * Add two arguments for an object with a start and end tag
 * Call this function by default with bindings `{ start: '{', end: '}' }` and `{ start: '[', end: ']' }` for respectively two-way and one-way binding
 * Compose `OPEN_BRACKET` and `CLOSE_BRACKET` of the provided arguments and compile the regex
* Add a check before parsing of any annotations to check if the added field (for example `bindings`) exists
 * If `this.bindings` exists, overwrite the default bindings
* When [checking for the type of binding](https://github.com/Polymer/polymer/blob/master/src/lib/annotations/annotations.html#L137), use the corresponding bindings (either the default or the overwritten)
* (Probably) If `this.bindings` exists, reset the bindings to the default bindings

I am not sure, but I think the bindings have to be reset after all parsing has happened, to not leak and fail other elements.

**Comment by TimvdLippe** [comment]
@tjsavage shall I develop a PR for this issue?

**Comment by tjsavage** [comment]
Thanks @TimvdLippe! I think this is a good statement of a potential solution.

Overall the risks here are the usual ones for feature additions to the core Polymer library - adding complexity and hurting performance. In the interests of keeping Polymer lean and light, it would be difficult to justify any performance hit in order to implement this feature. As you point out, currently the core library isn't architected in a way that easily supports this kind of change - so there are a bunch of unknowns around if this would be possible or worthwhile.

So I think it would be up to your judgment whether it would be worth pursuing a PR - it'd probably have to be concretely provable that a solution doesn't add significant complexity and that it doesn't impact current performance.

**Comment by TimvdLippe** [comment]
So I have been thinking about this issue for quite some time now, but I think that after recent efforts of a more robust regex binding matching, there is no use case for changing the delimiters. Therefore I would advise to close this issue @tjsavage

**Comment by tjsavage** [comment]
Agreed - I don't yet see a compelling reason to do this at the library level during runtime, when it should be achievable with something at build-time at least.

Closing for now, but very open to compelling examples of where this would be needed - please all feel free to continue adding to this thread.

**Comment by ktiedt** [comment]
I find the lack of compelling reason, compelling in itself... all you have to do to see a compelling reason is look at the hoops needed to jump through to get Angular and Polymer to play nicely together. Or any SS templating system that uses curly braces too... Although I think Library level would break more things than it would help, it would need to be at a component level so that a project would not have to rewrite all the existing compounded elements that already use the native brackets.

**Comment by JoostvanPinxten** [comment]
Bibtex is another one. This is used in e.g. Jekyll Scholar., Escaping in bibtex clashes with the liquid tags. Therefore we suggested disabling this by default, but that disables many interesting things, like highlighting and parsing parts. 

Having a way to replace the curly braces with another set of braces or other delimiters would be useful in Jekyll Scholar.
