### ISSUE TITLE
Really slow polyfills when building nontrivial site

### ISSUE THREAD

**Issue by psvensson** [Polymer/polymer#720]
OK, I know it's a developer preview, but currently the site I'm building for my customer takes 20-25 seconds to load in either latest FF or chrome < 36. In Chrome 36 -> super-snappy.

So my question is; what is the timeline in speeding up polyfills? Or at least make the run in chunks, asynchronously or something. 

Or are they as tuned as can be and we just have to wait until the world catches up?

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
