### ISSUE TITLE
Polymer with alternative architectural patterns

### ISSUE THREAD

**Issue by mehdi-cit** [Polymer/polymer#732]
Hello everyone!
I have been looking into Polymer and find many of its facets very interesting. I however wonder whether it's possible to "use" polymer in a different way. Different than how I see it being used in examples and tutorials.
Is it possible to use one way binding from the model to the view only (and not from the view to the model)?. How about no binding at all?
One could obviously create extra variables in the model and update the "real parts of the model" in a more controlled manner. But maybe there are some sort of backed-in one way binding alternatives?
The other thing that makes me hesitate with jumping on the Polymer train is the way integration is done between polymer components. Are there alternatives to using the declarative integration/composition. Can one compose different polymer components in a more controlled manner (i.e. programmatically).
I'm pretty sure the above is possible. But can it be done in an elegant way? Has anyone tried such approach?
For instance, knockout offers some beforechange event to allow for more controls on updating the observables. But this ugly "work around" makes the whole process cumbersome.
Thanks in advance for any help!

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
