### ISSUE TITLE
polymer-element attributes semi-restrictions/

### ISSUE THREAD

**Issue by benzen** [Polymer/polymer#735]
When using polymer-element atttributes attribute, i was tempeted to use variable with '-'.
But this give me wrong result when rendering the view.

The variable is rendered as "x - y", like x minus y.

I think that a little warning will help in the sections about polymer element.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
