### ISSUE TITLE
Problem with Polymer when using vulcanize

### ISSUE THREAD

**Issue by schmidek** [Polymer/polymer#741]
Polymer Version 0.4.0 

After using vulcanize to concatenate source into one file, I'm seeing an error 'Template must be cleared before a new bindingDelegate can be assigned' when loading the page.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
