### ISSUE TITLE
Unexpected Rendering Artifacts with Webview on Android L Preview

### ISSUE THREAD

**Issue by steve-the-edwards** [Polymer/polymer#743]
Using a basic set of polymer elements, paper and core:

core-collapse
paper-fab
paper-input
core-icons

On Chrome for Android 36.0.1985.135 through CordovaWebView running on Android L Preview.

I have noticed a number of rendering flashes/glitches and unexpected artifacts for these elements that were not visible on 4.4.2 w/ same chrome version.  Is this a known issue?

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
