### ISSUE TITLE
core-ajax does not handle ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by har79** [Polymer/polymer#744]
In core-ajax, if my backend server is dead when .go() is called, on-core-response is called with invalid data. The expected behaviour is that on-core-error is called. The console contains the following logs:

GET http://localhost:8080/data net::ERR_CONNECTION_REFUSED core-xhr.html:68
core-ajax caught an exception trying to parse response as JSON: core-ajax.html:241
url: /data core-ajax.html:242
SyntaxError {stack: (...), message: "Unexpected end of input"} core-ajax.html:243

![polymer core-ajax](https://cloud.githubusercontent.com/assets/8668280/4164957/05cb1a20-34fd-11e4-9d00-6cac3fd84e12.png)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
