### ISSUE TITLE
[Error] core-input / paper-input validation of empty field

### ISSUE THREAD

**Issue by jagi** [Polymer/polymer#755]
Hello,
there is a bug in `input` element. When I want to check `element.invalid` attribute of not touched element (I mean without setting and later removing any value) I always get `false` value even if there are `pattern` and `required` attributes. I've described this bug in details here: http://stackoverflow.com/questions/25867582/form-validation-in-polymer

**Comment by ebidel** [comment]
Closing stale issues. Please reopen on the 1.0 element's repo if you have a reproducible test.
