### ISSUE TITLE
Iphone 5 - Uncaught TypeError: Cannot read property 'addEventListener' of null 

### ISSUE THREAD

**Issue by gngeorgiev** [Polymer/polymer#756]
This is the exception i get on Iphone 5 - Uncaught TypeError: Cannot read property 'addEventListener' of null - polymer.js:11 (minified)

After that, the following: You tried to use polymer without loading it first. To load polymer, <link rel="import" href="components/polymer/polymer.html">

As a side note, how can we support Iphone's webview? For android we have crosswalk, as far as I could understand it is not available for iphone.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
