### ISSUE TITLE
can't inspect external style sheets

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/polymer#757]
If an element has its style included using a <link> tag from another file, the style sheet is not visible in the chrome inspector. It seems that it is read in programmatically and inserted as inline <style>. This means that the files don't appear in the 'source' tab of the 'sources' tool, and so the developer can't make use of the tools available there, eg editor, beautifier, etc, etc.

Please consider making the files available in the sources, as they are in the actual sources.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
