### ISSUE TITLE
Polymer and Vulcanize, cannot use Polymer.import for elements that have polymer as dependency.

### ISSUE THREAD

**Issue by TimWillis** [Polymer/polymer#759]
I have recently upgraded from 0.3.x to 0.4.0 and noticed that after I vulcanize I cannot dynamically import  an element either with polymer.import, or directly inserting the <link rel='import' ..> tag. The polymer.import function throws errors anytime I want to include an element that uses core or paper elements because almost all of the core and paper elements have a variation of <link rel="import" href="../polymer/polymer.html"> - this then causes an error when trying to load platform twice. I did a find and replace on all core and paper elements to comment out the polymer import. That fixed most of the problem, but if I have a element in my vulcanized file and I have the same element required on my dynamically imported file I will get the error "A type with that name is already registered"

**Comment by bzeffren** [comment]
We're trying to get a logical workflow setup for dealing with nested components and have hit this problem as well. Any update or new advice for working with this issue?

**Comment by flowlo** [comment]
Hey! Ran into this as well. Any news here?

**Comment by ebidel** [comment]
Check out https://github.com/PolymerLabs/web-component-shards. It's a new tool we're working on that can create multiple vulcanized bundles.

If you don't want to give that a try, you can use vulcanize's `--exclude` flag. You can use that to preserve the imports for polymer.html. That flag will prevent polymer.html from being inlined and url de-duping will kick in.
 
You could also use `--strip-exclude` to remove all references to polymer.html and instead, load it in your main page.

**Comment by jmcgdz** [comment]
@ebidel great news, this will help me as well

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
