### ISSUE TITLE
hero transition blocking inputs right after transition for 10 seconds

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#760]
http://sea-is-snow.appspot.com/

1) click first  image
2) click the beanie image that appears in the middle
**page blocks inputs for 10 seconds and can not select a other beanie**
3) after 10 seconds you can push on the beanie tiles again.

source: https://github.com/gertcuykens/sea-is-snow

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
