### ISSUE TITLE
Polymer does not work in Chrome Extensions

### ISSUE THREAD

**Issue by viridium** [Polymer/polymer#762]
Polymer does not work in Chrome Extensions without modifications. The reason is restrictions by the Chrome Extensions infrastructure preventing inline scripts from running.

To allow Polymer to function in Chrome Extensions without using tools that will slow development (tools like Vulcanize), and to help with its adoption, please consider having the Polymer components use external scripts only. I believe that some components already do this.

**Comment by baazoo** [comment]
Hey guys,

Is [PolymerLabs/Crisper](https://github.com/PolymerLabs/crisper) the (best) solution for this problem?

**Comment by davidmaxwaterman** [comment]
@baazoo : I don't think it is.

Crisper seems to do something weird...it actually builds a standard html file structure, ie it makes a, html element, with a head and body within it.

On the following html :

```
<link rel="import" href="../bower_components/some-element.html">

<polymer-element name="my-element">
<template>
  <style>
  </style>
  <some-element id="someElement"></some-element>
  <script>
    Polymer('my-element', {
      ready: function () {
        this.$.someElement.doSomething();
      }
    });
  </script>
</template>
</polymer-element>
```

it produces this :

```
<html><head><link rel="import" href="../bower_components/some-element.html">

</head><body><polymer-element name="my-element">
<template>
  <style>
  </style>
  <some-element id="someElement"></some-element>
  </template>
</polymer-element>
<script src="my-element.csp.js"></script></body></html>
```

It's not the right thing at all. It almost seems like it is simply the -csp part of vulcanize separated into a different command.

If it we to simply do what it says and extract script from html, then it would be possible to wrap it in some script to run on a whole directory tree, but it really doesn't do the right thing, imo.

**Comment by baazoo** [comment]
@davidmaxwaterman 
I am new to Polymer and haven't dug deep into Vulcanize. As far as I understood, it doesn't have CSPize feature by itself, however, Crisper by definition does split the inline script (not styles though) to make them CSP proof.
Could you please elaborate a bit on what exactly should be done to use Polymer for Chrome Extension development? Is it the problem with Custom Elements?
I am building a Chrome App / Extension duo and I don't want to create them in a totally separate line.

**Comment by davidmaxwaterman** [comment]
@baazoo vulcanize used to have a --csp option, and looking up a reference, I see that, indeed, it was simply moved to 'crisper':

<https://github.com/polymer/vulcanize#what-happened-to-feature-from-0x>

Actually, I've found following this thread a bit confusing, but let me try to answer your question....er, in answering your question, I began to wonder if the additional <html>, <head>, and <body> tags make any difference - it makes the file look very odd, but it might not make any difference. Indeed, a quick test on one of my 0.5 projects suggest that the extra stuff does *not* make any difference. I didn't realise that was the case. A bit annoying, but anyway.

Perhaps this means it'll work just fine, as a build step anyway.

I was thinking that cripser (and vulcanize --csp) where designed to only work on the main index.html file; but that seems wrong. It'd be nice if it were able to process a whole tree of files, but a script can do that, I think.

**Comment by baazoo** [comment]
## Crisper solved the issue
I tested with crisper on Polymer 1.0 and it worked like  a charm.
After installing crisper, I modified the Vulcanize task as below:

```js
var vulcanize = require('gulp-vulcanize'); // added for use in chrome extensions
var crisper = require('gulp-crisper'); // added for use in chrome extensions

// Vulcanize imports
gulp.task('vulcanize', function () {
  var DEST_DIR = 'dist/elements';

  return gulp.src('dist/elements/elements.vulcanized.html')
    .pipe($.vulcanize({
      stripComments: true,
      inlineCss: false, // changed from 'true' for use in chrome extensions
      inlineScripts: false // changed from 'true' for use in chrome extensions
    }))
    .pipe(crisper()) // added for use in chrome extensions
    .pipe(gulp.dest(DEST_DIR))
    .pipe($.size({title: 'vulcanize'}));
});
```
### PS:
1. This should work for Chrome Extensions popup (and future sidebar) pages but not for Content Scripts without WebComponents polyfil since [Chrome does not allow `registerElement` in content scripts](https://code.google.com/p/chromium/issues/detail?id=390807)
2. Crisper only separates scripts from HTML not the styles. I am not sure if Inline styles are allowed in Content Scripts.
3. I am sure there is a workaround for using Polymer in Content Scripts but I have no interest in that.

**Comment by davidmaxwaterman** [comment]
@baazoo yes, it will work because it doesn't much matter about the extra <html>, <head>, and <body> tags...iinm. they're kind of added anyway as part of the import code (if you look at what is 'inside' an import using dev tools, it's basically another html document).
So, as part of a build step, or if you're 'converting' 3rd party code, like in bower_components, then it would work fine. You can probably make it work in a hierarchy too, with an appropriate wrapper.
It isn't so good at converting our own code, but perhaps that is not such a big deal since we can do that ourselves fairly easily (or just always do it using a build step).
Yeah, I think I agree that it's pretty much good enough and so this issue could be close....just my personal opinion.
That is...if only it had a grunt plugin (I guess 'brocolli' users might also have an issue).

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. You can even design UI mockups for mobile as for standard display (html, js, css always generating without any coding required from you). Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi

**Comment by viridium** [comment]
baazoo: I don't understand how that can be used. Who runs that script at what point?

The best solution for me has been to:
1. install the Chrome Dev Editor from [1],
2. Open the directory containing my bower_components,
3. Right-click and say "Refactor for CSP" in the context menu.

I have to do this each time I install a new component, but it is a no-op for previously CSPized components, and it leaves my own components alone if they already use external scripts. Fairly low footprint.

[1] https://chrome.google.com/webstore/detail/chrome-dev-editor-develop/pnoffddplpippgcfjdhbmhkofpnaalpg

**Comment by baazoo** [comment]
@viridium 

You should change the gulpfile.js as I explained above and then run gulp. Don't remember the specific task, maybe the default will do the job.

**Comment by davidmaxwaterman** [comment]
I can't help but think there's a more direct equivalent to the CDE 'refactor for CSP' function. Perhaps something like this (remove 'echo' to make it do something):

```
$ for file in $(find bower_components -name \*.html); do js=${file/\.html/.js}; echo crisper --source "$file" --html "$file" --js "$js"; done
```

**Comment by gutenye** [comment]
The best tool is [polybuild](https://github.com/PolymerLabs/polybuild), it combines vulcanize, crisper and also handles bower_components

```
$ polybuild popup.html
> popup.build.html and popup.build.js
```

**Comment by davidmaxwaterman** [comment]
Yeah, that looks quite nice - they've come up with quite a few new tools since this issue was opened (probably *because* this issue was opened). I haven't tried polybuild yet, but it looks hopeful :)

I'm curious if there is any hope regarding fixing the browser so this isn't an issue to start with, as @sjmiles and @ebidel mentioned.

**Comment by zboralski** [comment]
Are there still issues? and is polybuild the easiest path?

**Comment by viridium** [comment]
As of a couple months ago, there were still issues. To me, the easiest path right now is to extract the inline resources using the Chrome Dev Editor. It's easiest, but not easy. I have to run the CSP-ize function available in that app each time a new non-CSP-ized component enters my source tree.

It would be best if components worked out of the box, without the dev having to run any builds.

**Comment by azakus** [comment]
The right tool for this is [polybuild](https://www.npmjs.com/package/polybuild), which will make your elements follow CSP guidelines.

@justinfagnani, good candidate for CLI tooling.

**Comment by justinfagnani** [comment]
Thanks @azakus, got it.

**Comment by ernsheong** [comment]
Managed to figure out how to split files to adhere to default extension CSP settings using [polymer-build](https://github.com/Polymer/polymer-build):

```
const gulp = require('gulp');
const PolymerBuild = require('polymer-build');

const HtmlSplitter = PolymerBuild.HtmlSplitter;
const PolymerProject = PolymerBuild.PolymerProject;

gulp.task('build', function() {
  const project = new PolymerProject(require('./polymer.json'));
  const sourcesHtmlSplitter = new HtmlSplitter();

  return project.sources()
    .pipe(sourcesHtmlSplitter.split())
    .pipe(gulp.dest('./build/'));
});
```

Be sure to configure `sources` in your `polymer.json` file.
See https://www.polymer-project.org/2.0/docs/tools/polymer-json#sources
