### ISSUE TITLE
Support Tizen

### ISSUE THREAD

**Issue by jagi** [Polymer/polymer#770]
I've tried to run Polymer on Tizen device but I got error. After investigation I've noticed that Tizen has `window.performance` object but it doesn't have `now` function. So I've made little fix and error doesn't appear any more. However it seems not to work at all. I tried simple layout with drawer, but without success. Are you gonna support Tizen OS?

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
