### ISSUE TITLE
Polymer + Cordova + PhoneGap + iOS = Very Laggy / Slow?

### ISSUE THREAD

**Issue by wes** [Polymer/polymer#773]
I'm sorry this isn't necessarily a specific bug, but it is something I am noticing as developing an app in Polymer to be deployed as an app via PhoneGap.  I have seen it take nearly 30 seconds to render a list of a 100 items.  On a browser, its nearly instant.

When using certain things like:

```
<core-list id="list" data="{{data}}">
        <template>
            <div>stuff</div>
        </template>
</core-list>
```

**Comment by pareshgami** [comment]
Thanks nice tutorial.
I created project successfully but when i run project for android graphics and navigation goes down.
Please see this http://prntscr.com/5rgaj8
