### ISSUE TITLE
External CSS in Polymer Elements is ignored in Chrome Extensions

### ISSUE THREAD

**Issue by viridium** [Polymer/polymer#779]
I'm using Polymer JS version 0.4.0. My custom element has some styling rules, but these rules don't apply if I place them in an external CSS file and link to it using a `<link rel="import" href="..."/>`. They do work when I replace the `<link>` with a `<style>` and move the rules inside it.

**Comment by AnasAl-tamemy** [comment]
I have the same issue, when i moved the CSS after template it works.
Thanks
