### ISSUE TITLE
Font components don't work in Chrome extensions

### ISSUE THREAD

**Issue by viridium** [Polymer/polymer#780]
Font components link to online fonts using a URL, but the URL does not include a scheme, under the assumption that the scheme of the containing page may be used. The intent is to allow https: pages to use an https: resource, and, similarly, for http: pages to use the resource from http:.

Chrome extensions run as chrome-extension:, so the fonts end up not getting imported.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
