### ISSUE TITLE
created and ready called twice

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/polymer#781]
Hi,

I fully expect the response to this issue to be "yeah, don't do that" or some such, but I figured I'd see what people say anyway. FWIW, I have changed the way things are done now, so it's not an actual problem for our development, but it did cause some quite odd behaviour and had us scratching our heads for a while.

I have a content script that essentially replaces the entire contents of the page it's executed on. The method I used to do this was to empty the document, and build up head and body elements.

The replacement page is contained in an index.html file - so that *that* portion of the app can be developed without using an extension, using a server to debug (accelerates the development cycle).

To get the new page inside the newly emptied page, the content script injects an 'import' link tag for index.html, then extracts the head and body from there, and adds them to the new head and body.

That seemed to work ok. I realised that 'import' link tags aren't like #include in cpp, in that they don't simply replace themselves with the content, which is why I copied out the html contents. However, I also realised that the javascript that is imported by the tag is executed immediately.

It is the behaviour of executing the javascript immediately that I think causes the problems we found.

The index.html page is fairly simple, with just one polymer element - ie it has an import link tag for the element in the head, and the polymer element itself in the body.

There's no actual javascript in index.html, so I had thought it might not actually execute anything. Furthermore, I understand that importing an element twice was of no consequence since Polymer knows the elements have been registered already and doesn't do anything.

However, we were finding that the created and ready functions were being called twice, and were likely the cause of all sorts of problem that we had trouble understanding.

The problem that made us suspect what was happening, and investigate a fix, was that element properties seemed to be changing back to their initialised values. We encountered the problem when we endeavoured to fix an error where we were using 'self' as a 'shared variable'. We have the Polymer() constructor inside an anonymous function in which we define private functions that don't belong in the prototype; but mistakenly put 'self' in that scope too, and initialised it in created. This worked for elements that only have a single instance, but when we used that same practice for elements that have multiple instances, we ran into trouble. We decided to stop doing that for all elements, even those with single instances. Ironically, that was actually making those elements work, and when we used self locally to each function that had call-back functions, everything became wildly unpredictable, and a day-long search for the issue ensued.

Well, that's the story. As I intimated, it's quite a 'corner-case', but I'd thought I'd get people's thoughts on the real reasons behind what was happening - as I say, it was mostly instinct that lead me to realise where the problem lay, and I've not really understood *exactly* what was happening with the import tag.

So, if you import an html file, does it actually perform imports that are inside that html file? As I mentioned, our index.html file has no javascript in it at all, and no script tags either.

I think I have my (mis)understanding from the following page, particularly the bit about considering the import content 'inert' - from that I assumed that the sub-import wouldn't take immediate effect, though, thinking about it more, it surely must :

<http://www.html5rocks.com/en/tutorials/webcomponents/imports/>
(I wish that page had links on the titles :/)

> Think of content as inert until you call upon its services. Take a normal,
> dynamically created stylesheet:
> 
> var link = document.createElement('link');
> link.rel = 'stylesheet';
> link.href = 'styles.css';
> The browser won't request styles.css until link is added to the DOM:
> 
> document.head.appendChild(link); // browser requests styles.css
> Another example is dynamically created markup:
> 
> var h2 = document.createElement('h2');
> h2.textContent = 'Booyah!';
> The h2 is relatively meaningless until you add it to the DOM.
> 
> The same concept holds true for the import document. Unless you append
> it's content to the DOM, it's a no-op. In fact, the only thing that
> "executes" in the import document directly is <script>. See scripting
> in imports.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
