### ISSUE TITLE
Should ShadowCSS always prefix polyfill-next-selector rules with the element name?

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#783]
I thought the ShadowDOM CSS shimmer always added the host prefix to `polyfill-next-selector` rules. However, given `my-element` contains:

    polyfill-next-selector { content: '> *' }
    ::content > * { ... }

the polyfill does not transform the rule into this:

    my-element > * { ... }

@sorvell wdyt?

**Comment by silvenon** [comment]
Why is `polyfill-next-selector` even needed in this case? Why doesn't the shimmer convert all selectors which start with `::content ...` to `my-element ...` like it prepends `my-element` to all selectors which don't start with `:host`?

**Comment by silvenon** [comment]
My bad, this is happening actually.

**Comment by arthurevans** [comment]
For that, wouldn't you have to do:

```
polyfill-next-selector { content: ':host > *' }
::content > * { ... }
```

It seems like this is one area where the shimmer can't reasonably insert my-element, because if your DOM looks like:

```
<my-element>
   <shadow-root>
     <div class="container">
       <content></content>
    </div>
  </shadow-root>
</my-element>
```

Then `my-element > *` is not the correct substitution (which is why shimming ::content is so tricky, seems to me).

**Comment by silvenon** [comment]
You're right, but it does polyfill when there is no `>`.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
