### ISSUE TITLE
Core-item > vertical positioning of content using IE 11

### ISSUE THREAD

**Issue by Joshhughes34** [Polymer/polymer#785]
the vertical positioning of the content withing a core item is not centered when display in IE 11.
Below are two images from https://www.polymer-project.org/components/core-item/demo.html
(note: ive highlighted the core-item using each browser's dev-tools)

From Chrome 37:

![core-item snapshot chrome ](https://cloud.githubusercontent.com/assets/5749275/4541489/d23e4840-4e14-11e4-9317-71548f49fa7c.png)

From IE 11:

![core-item snapshot ie](https://cloud.githubusercontent.com/assets/5749275/4541499/f7c72c08-4e14-11e4-9f1c-0faa88b837e8.PNG)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
