### ISSUE TITLE
Core-dropdown-menu > nested core-item doesnt display using IE11

### ISSUE THREAD

**Issue by Joshhughes34** [Polymer/polymer#786]
Using IE 11, the core-item which contains the div with id: "label" doesnt display. Image is from: 

https://www.polymer-project.org/components/core-dropdown-menu/demo.html

![borken](https://cloud.githubusercontent.com/assets/5749275/4541377/22ff517c-4e13-11e4-81c7-65a3e749f54d.PNG)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
