### ISSUE TITLE
Not-actually-JSON parsing is problematic with strings that contain single quotes

### ISSUE THREAD

**Issue by davidt** [Polymer/polymer#788]
I'm trying to pass a complex object in to my polymer element, which can include some strings that include single quotes. In src/lib/deserialize.js, the code first replaces all single quotes with double quotes, before trying to parse as JSON:

```javascript
try {
  // If the string is an object, we can parse is with the JSON library.
  // include convenience replace for single-quotes. If the author omits
  // quotes altogether, parse will fail.
  return JSON.parse(value.replace(/'/g, '"'));
} catch(e) {
  // The object isn't valid JSON, return the raw value
  return value;
}
```

Using single quotes to wrap attribute names or strings isn't actually JSON, and in this case makes it impossible to pass in the object. I understand that there might be some existing applications relying on this behavior, but perhaps this can be changed to first try parsing `value` as JSON without replacing quotes, and only if that fails, fall back on the replacement?

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
