### ISSUE TITLE
"Incorrect binding types" warning can be misleading

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#795]
http://jsbin.com/haxaha/1/edit is an example that produces the warning:

> Attributes on my-element were data bound prior to Polymer upgrading the element. This may result in incorrect binding types. 

my-element is correctly defined before it is used. Is the warning because of `.innerHTML`?

**Comment by warpech** [comment]
Any ideas for a workaround?

**Comment by ebidel** [comment]
Loading your dependencies in the correct order can help. For example, if elementA depends on elementB, make sure B's import is loaded first. I'd have to see your setup to know for sure.

**Comment by RenaudF** [comment]
What's the recommended way to deal with asynchronous element registering? (as in [this fiddle](http://jsfiddle.net/RFontana/6cbj7qam/) for example)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
