### ISSUE TITLE
For educational purposes, why a Object Literal is passed in to create new Polymer elements? 

### ISSUE THREAD

**Issue by lozandier** [Polymer/polymer#796]
For educational purposes to better understand Polymer works, why is it a Object Literal?

Since Polymer authors no longer have to specify the same name of a new Polymer web component they've defined as an attribute for `polymer-element`, and also considering the ratification of ES6 (hopefully soon)--has a syntax been considered for Polymer that more closely matches the process of creating native web components using the new `class` shorthand of creating constructor function?

An example would be the code snippet below that demonstrates what I mean:

```js
class MyWebComponent extends Polymer {
  created {
    // For private variables not defined as public variables via
    // polymer-element 
    this.bar = 'defaultValue';
  }
  fooChanged(oldvalue, newValue){
    this.foo = newValue
    doSomething()
  }
  doSomething(){
    console.log("Something of significance happened");
  }
}
```
Today we do the following:
```js
Polymer({
  bar:  'defaultValue',

  created: function() {
    // For private variables not defined as public variables via
    // polymer-element?
    this.bar = 'defaultValue';
  },

  fooChanged: function(oldvalue, newValue){
    this.foo = newValue
    doSomething()
  },

  doSomething: function(){
    console.log("I did something");
  }
});
```

**Comment by ebidel** [comment]
Closing stale issues. I think the question was addressed.

**Comment by lozandier** [comment]
Yup; thanks for checking back nonetheless that it was addressed.

On Wednesday, October 21, 2015, Eric Bidelman <notifications@github.com>
wrote:

> Closing stale issues. I think the question was addressed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Polymer/polymer/issues/796#issuecomment-150003513>.
>


-- 
Kevin Lozandier
lozandier@gmail.com <lozandier@gmail.com>
