### ISSUE TITLE
console log will not catch errors when use "auto-binding" template in <body>

### ISSUE THREAD

**Issue by jwu** [Polymer/polymer#798]
I found polymer will not issue error when we write something wrong inside `<template id="my-template" is="auto-binding">` in a `<body>` element. And the worse thing is, the whole web page get blank after that, so there is no error no things show up to trace what happen there.

Here is my code:

```html
<html>

<head>
<title>Polymer Test</title>
<script src="/bower_components/platform/platform.js"></script>
<link rel="import" href="/bower_components/polymer/polymer.html">

<polymer-element name="test-label" >
    <template>
        <style>
            .text {
                font-size: 30px;
                color: red;
            }
        </style>
        <div class="text">{{text}}</div>
    </template>
    <script>
        Polymer({
            publish: {
                text: "",
            },

            ready: function () {
                this.foobar.runtime_error = "hello"; //<==== I put an error here.
            },
        });
    </script>
</polymer-element>

<body>
    <template id="my-template" is="auto-binding">
        <test-label text="{{foobar.text}}"></test-label>
    </template>
</body>

<script>
    var tmpl = document.querySelector('#my-template');
    tmpl.foobar = {
        text: "Foo Bar",
    }
</script>

</html>
```

In the code I put an error code in ready: function ==> `this.foobar.runtime_error = "hello";`. But when you run this html file in your browser, you will not receive errors in the console, and your page will be blank.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
