### ISSUE TITLE
Lack in documentation

### ISSUE THREAD

**Issue by TimWillis** [Polymer/polymer#799]
Hi, this isn't really a bug, but there isn't a place that I seen to make suggestions. 

It would really be helpful to have the correct way to create a callback when the animation is completed documented. It took me forever to find this: http://stackoverflow.com/questions/25860395/way-to-detect-if-a-polymer-web-animation-is-complete - I kept following the thought that it had something to do with effectcallback, which the link of the official documentation is provided, but the documentation is hard to understand without reading all of it. If there is a place for suggestions please let me know and I will use that next time. Keep up the great work with Polymer!

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

Now with 1.0, the best place to make suggestions for the library itself is on the Polymer/project repo
