### ISSUE TITLE
Add support for iterables in dom-repeat

### ISSUE THREAD

**Issue by RB14** [Polymer/polymer#800]
It might be still early, but I'm really excited about iterators\iterables landing in Chrome 38, that I'd really like to make use of them in my templates. Chrome 39 will come with Generators support which should really allow iterables to be more memory friendly when creating a large generator, and when chaining them inside a filter.

I think it should be implemented in Polymer (or should I say MDV?), but maybe , in the lack of an appropriate polyfill for Symbol.iterator (which should be easily implemented in platform.js if necessary), or for Generators (which may be harder), it should come with a warning for an experimental technology or the likes. This will allow developers who target the Chrome\Firefox platforms, to make use of them right away.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

**Comment by justinfagnani** [comment]
Re-opening and cleaning up for 1.0

**Comment by justinfagnani** [comment]
`Symbol.iterator` is supported Chrome, FF, IE Edge 12 and Safari 9. It's possible to polyfill, though polyfilling the places where it's used is a little trickier. IE 11 and Safari Maps aren't iterable for example.

Presumably someone using this feature has their own browser support requirements and can live with that or load the needed polyfills themselves. Then dom-repeat could just check if `items[Symbol.iterator]` exists and use that.

**Comment by jogibear9988** [comment]
In 2.0 still only array is supported! 
As now a compile to ES5 is needed because polymer also uses ES6 can't we just use a "for of" loop if its not an array?
