### ISSUE TITLE
How to deal with the `this` argument changing in a function defined in a polymer prototype

### ISSUE THREAD

**Issue by akashkrishnan** [Polymer/polymer#803]
For example, if I bind an ```on-click``` event to a function defined in ```Polymer({...})```, the ```this``` keyword no longer refers the the ```{...}``` prototype. There should be an elegant way to bind an ```on-click``` event to a ```toggle``` function that does something like this: ```this.$.dialog.toggle();```.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
