### ISSUE TITLE
Drop down menu does not keep currently selected item on top

### ISSUE THREAD

**Issue by ericberdinis** [Polymer/polymer#805]
According to Google's Material Design guidelines:

"Menus are positioned over their emitting elements such that the currently selected menu item appears on top of the emitting element."

In all of the examples, the currently selected menu item bubbles to the top of the list. It does not exhibit this behavior in this link:
https://www.polymer-project.org/components/paper-elements/demo.html#paper-dropdown-menu

Source:
https://www.google.com/design/spec/components/menus.html#menus-menu-behavior

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
