### ISSUE TITLE
ShadowDOM CSS shim: background-size incorrectly serializes

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#811]
`background-size: 30px 30px;` is converted into `background-size: 30px;` under the style shimmer.

http://jsbin.com/carinesone/edit?html,output

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
