### ISSUE TITLE
Element binding when conditional templates always chooses first id

### ISSUE THREAD

**Issue by clyfe** [Polymer/polymer#813]
See the following gist:
https://gist.github.com/clyfe/ca6d95cb5d1ab43c9935

There are two conditional templates (mutually exclusive), each with an element with the same id.
Shouldn't the binding attach to the element in the successful template ?

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
