### ISSUE TITLE
console.warn is not a function error in firefox

### ISSUE THREAD

**Issue by TimWillis** [Polymer/polymer#818]
somewhere in polymer.js (eInstance&&this.templateInstance.model&&console.warn("Attributes on "+this.local...) I get the error console.warn is not a function. I believe it is trying to warn me about ("Attributes on is-content-menu were data bound prior to Polymer upgrading the element. This may result in incorrect binding types.") But in firefox the console.warn throws an error and kills my js.
thanks
Tim

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
