### ISSUE TITLE
No puedo guardar en el polymer designer

### ISSUE THREAD

**Issue by goalkeeper112** [Polymer/polymer#820]
Hola amigos desarrolladores del proyecto polymer, he tenido problemas ultimamente a la hora de usar su tools designer con la opción de guardar, yo genero mi token github y a la hora de introducirlo y guardar mi proyecto no ocurre nada, no puedo ver el preview, nada de nada, me podrian ayudar con este bug

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
