### ISSUE TITLE
please provide csp versions of polymer and all elements

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/polymer#821]
It is quite painful to convert the polymer library and all its elements to conform to csp in order to use them inside chrome apps and extensions.

Vulcanise works as a tool to produce a distribution/optimised version of the app, but it has serious disadvantages for use during development, the most serious being that it introduces a build step - most of us enjoy and greatly value being able to develop apps and extensions without a build step. Recently, this fact was the sole reason I didn't use polymer in my extension - since I am part of a team, and I knew they would baulk at having to use a build step.

Now, for our own polymer elements, it is easy to just write them with external scripts - that's no big deal at all. The problem is the polymer library and the core and paper elements that are written with the scripts inline. This has lead some people to attempt to write tools to split them all apart, but this again introduces a build step. Actually, it's not too bad since we already have to do 'bower install' and it's just another command after that, and once they're done, the development cycle can proceed without any build steps.

However, I just feel like it must be easy enough to do this in the repository, so we can 'import' the csp version, right after 'bower install'. In fact, once it's done, it should be pretty easy to run that command on all the elements and it would have no impact on anyone else (apart from additional download load, I suppose).

```
<link rel='import' href='bower_components/core-ajax/core-ajax-csp.html'>
```

or perhaps have different repositories (auto-generated, of course) so we can specify them in bower.json :

```
<link rel='import' href='bower_components/core-ajax-csp/core-ajax.html'>
```

So :

1. Is there some reason this isn't already done?
1. Please consider doing something to alleviate the problem.
1. Why doesn't polymer.html work in a background.html page anyway (even cde's 'refactor for csp' doesn't seem to help)?[1]

[1] <https://github.com/davidmaxwaterman/polymer-in-event-page>

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
