### ISSUE TITLE
Notifications for missing elements

### ISSUE THREAD

**Issue by giltig** [Polymer/polymer#822]
Hi,

I was using some elements in my application and noticed that there is no notification when I haven't imported a specific element (thus the entire look of the page looked different from what I expected).
Now I understand that the browser simply ignores the tags that it doesn't recognize but isn't there anyway to notify the user about missing imports?

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
