### ISSUE TITLE
core elements 

### ISSUE THREAD

**Issue by giltig** [Polymer/polymer#823]
Hi,
I think Polymer and web components is an actual revolution and you can build with this library practically any app (without any other framework).
However there are two fundamental elements which are missing from the core-elements:
core-socket - a web socket element for real time communication
core-router - a router element for single page applications.
Hopefully those will be released with the next version of Polymer.
Regards.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
