### ISSUE TITLE
No callback after template instantiation

### ISSUE THREAD

**Issue by RenaudF** [Polymer/polymer#825]
For convenience I like to use a mix of declarative and imperative data binding (doing a lot of data viz). I have a repeat template bound to some data array that generates the skeleton of my template. Next thing I want to finish all the bindings using another library but there are no callbacks to notify when the Polymer template nodes have been instantiated and added to the DOM. When simply using the `attributeChanged` callback, the DOM hasn't been updated yet.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
