### ISSUE TITLE
UIWebView/WKWebView polymer-gestures double click event bug

### ISSUE THREAD

**Issue by m4b** [Polymer/polymer#831]
Problem:
****
It appears that in iOS web views, when Polymer/polymer-gestures#master is imported, polymer is sending two click/tap events for a _single_ click/tap.  Simply including the gesture library is enough, without actually calling any of its functions, so some kind of variable/function bleeding might be occurring.

This is most noticeable in the `<paper-dropdown-menu>` element because the second click causes the menu drop-down to cancel, or in paper buttons, where two ink ripple events will occur.  

This is particularly vexing for menus because the only way to select an item is "long press", usually about 1 second, which allows the menu to drop down without being auto-cancelled by a spurious second tap/click event.

I've only noticed this when testing on iOS devices with either UIWebView (and the newer WKWebView) loading the polymer app --- on both physical (iPad) as well as emulated devices.

NOTE: this will not show in firefox, chrome, _or_ safari.  It is only (visibly) present in UIWebView and WKWebView on iOS (I have not tested on android, but if you want I will report back with results).

Steps to Reproduce:
****

1. Create a basic polymer app (`<paper-button>` elements display the effect the best, because of the two ink ripples, or drop-down menu's because of the cancellation) ---  I recommend using Chrome Dev Editor's js web app with paper elements as a simple app, since it includes paper tabs with ink ripples.

2. Include the polymer gestures library; i.e., if your bower.json has `"polymer-gestures" : "Polymer/polymer-gestures#master"`, update your bower, then you can include something like this in the app: `<link rel="import" href="bower_components/polymer-gestures/polymer-gestures.html">`

3. Create any simple iOS app with a UIWebView or WKWebView and point the webview's loadRequest: method at your polymer app.  I can supply a demo iOS app if you like.

4. Run the iOS app on an emulator or device which can access the polymer app, and view the double ink ripple, double click on menu bugs, etc.

Attached are some screenshots of the double click events (the double ink ripples) in an iOS app web view loading a polymer web app.

![double_vision](https://cloud.githubusercontent.com/assets/1920204/4853804/9589dbb2-6089-11e4-9ff4-b9a2b3ecae17.png)
![double_vision_2](https://cloud.githubusercontent.com/assets/1920204/4853803/95888898-6089-11e4-91b4-6af5879bd0ff.png)

**Comment by m4b** [comment]
No response, and I don't care about 0.5 anymore; but probably should check if something like this bug still occurs in 1.0

**Comment by azakus** [comment]
This probably won't happen in 1.0 due to disabling mouse for mobile: https://github.com/Polymer/polymer/blob/master/src/standard/gestures.html#L239-L241
