### ISSUE TITLE
Bindings are not complete when PathObserver path changes

### ISSUE THREAD

**Issue by wprater** [Polymer/polymer#832]
Should we expect all the two-way bindings to be complete in the callback of the `observe` path callback?

```
observe: {
  'myObj': function(oldData, newData) {
    // Would expect all the two-way bindings to be complete
    //  textfields were not bound
  }
}
```

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
