### ISSUE TITLE
webcomponentsjs/ShadowCSS/ incorrectly webcomponentsjs/ShadowCss in filesystem

### ISSUE THREAD

**Issue by mberends** [Polymer/polymer#833]
Case insensitive file systems (OSX, Windows) would ignore this case discrepancy but on Linux the web server throws a 404 not found error.  Caught when adding &lt;paper-icon-button&gt; to a plain &lt;core-header-panel&gt; example.  Successful workaround is `ln -s ShadowCss ShadowCSS` in the webcomponentsjs directory.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
