### ISSUE TITLE
Can't use document.createElement('polymer-element')

### ISSUE THREAD

**Issue by Legioth** [Polymer/polymer#835]
You can't imperatively create a polymer-element, populate its content and then attach it to the DOM because initialization happens in `createdCallback` when attributes and child nodes are not yet present.

Would it be possible to set a flag in `createdCallback` if there's no name attribute, and then retry the initialization in `attachedCallback` if the flag was set?

My workaround right now is to build an HTML string containing the `<polymer-element>` and set is as `innerHTML`, but this approach requires additional hacking to make script tags evaluate.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
