### ISSUE TITLE
paper-input

### ISSUE THREAD

**Issue by thanush** [Polymer/polymer#836]
paper-input validation is not working on my local and https://www.polymer-project.org/tools/designer/
also please help me

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

**Comment by ADELG** [comment]
adel






Sent from Windows Mail





From: Eugene Horan
Sent: ‎Saturday‎, ‎24‎ ‎October‎ ‎2015 ‎8‎:‎38‎ ‎AM
To: Polymer/polymer





Closing this issue due to age and the release of version 1 of Polymer - please feel free to re-open if this is incorrect.
