### ISSUE TITLE
The "label" property is deprecated.

### ISSUE THREAD

**Issue by ocorso** [Polymer/polymer#837]
\<core-item\> uses the "label" attribute to fill out the text. Perhaps we should probably use another attribute that doesn't throw a warning? like "text" or "name?"

![screenshot 2014-11-01 17 15 59](https://cloud.githubusercontent.com/assets/207023/4873784/7a717824-6225-11e4-8e7a-ee45eecb8eed.png)

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
