### ISSUE TITLE
Inconsistent `extends` behavior between imperative and declarative modes

### ISSUE THREAD

**Issue by RenaudF** [Polymer/polymer#879]
Extending an element this way:  

    Polymer('extended-item', {extends: 'div'})

will let me use the `<extended-item>` tag directly.  
Extending an element this way:  

    <polymer-element name="extended-item" extends="div">

Will only allow the use of `<div is="extended-item">`.

This also seems to have implication with CSS selectors (see this [SO](http://stackoverflow.com/questions/26738435/how-to-select-extended-custom-elements))

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
