### ISSUE TITLE
Polymer dies if imports have mismatched protocols (http + https)

### ISSUE THREAD

**Issue by dlazin** [Polymer/polymer#882]
If you import multiple components but accidentally use different protocols (one HTTP, one HTTPS), Polymer's JS dies with console errors. (And the error messages don't make it look like the issue is a protocol mismatch, so it takes a while to figure this out.) Verified by Jeff Posnick.

Chrome console says:
Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': Nodes of type 'HTML' may not be inserted inside nodes of type '#document'. polymer.concat.js:6313
Uncaught TypeError: object is not a function core-meta.html:68
... + many more TypeErrors

Minimal repro:

    <script src="http://www.polymer-project.org/platform.js"></script>
    <link rel="import" href="http://www.polymer-project.org/components/paper-button/paper-button.html">
    <link rel="import" href="https://www.polymer-project.org/components/paper-icon-button/paper-icon-button.html">
    <paper-button>Hello</paper-button>

Live demos:
Works (both imports use HTTPS): http://jsbin.com/woquzipopi/1/edit?html,console,output
Fails (one import HTTP, one HTTPS): http://jsbin.com/noyozu/2/edit?html,console,output

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
