### ISSUE TITLE
core-icons... settings-input-composite has same image as settings-input-component

### ISSUE THREAD

**Issue by cminter** [Polymer/polymer#883]
In core-icons demo page
    https://www.polymer-project.org/components/core-icons/demo.html
look at 'settings-input-composite'...
   ` <core-icon icon=​"{{ iconset.id }​}​:​{{ icon }​}​" aria-label=​"settings-input-composite" role=​"img">​…​</core-icon>​`

Notice 'settings-input-composite' has same image as 'settings-input-component'.  Composite should look different than that since it is one "RCA connector".

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
