### ISSUE TITLE
Polymer.flush() not being corrected to Platform.flush()

### ISSUE THREAD

**Issue by aleccool213** [Polymer/polymer#893]
Was having issues getting my web app to show up on safari. I got an undefined method error in Polymer.js where is calls Polymer.flush(). I had the most updated version of Polymer installed and apparently the new method call is Platform.flush(). I had to go into Polymer.js and manually fix this.

I found the fix here: http://stackoverflow.com/questions/26122043/paper-dropdown-menu-error-in-observe-js

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
