### ISSUE TITLE
core-collapse with layout attribute issues

### ISSUE THREAD

**Issue by lingz** [Polymer/polymer#895]
When core-collapse is used with layout, it defaults to being open instead of closed. The first attempt to trigger .toggle() on the element then makes the collapse instantly closed, and then open again. It seems like the initial hiding is bugged.

```
<core-collapse layout vertical>
  I am showing by default instead of hidden
</core-collapse>
```

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
