### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by Zevran** [Polymer/polymer#896]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with polymer. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable polymer on @Sourcegraph by going to https://sourcegraph.com/github.com/Polymer/polymer and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
