### ISSUE TITLE
paper-input invalid attribute cannot find function or filter

### ISSUE THREAD

**Issue by trepidacious** [Polymer/polymer#897]
When setting the invalid attribute of a paper-input to a filter using a function of the element, the function is  called only once, and then modifying the input's value causes an error "Cannot find function or filter: functionName".

I've made a simple fiddle to demonstrate this:
http://jsfiddle.net/tudbzmbt/5/

As expected, on loading the page inputA is invalid and inputB is valid, since the associated filters return true and false. However when editing the inputs, the javascript console shows errors.

If the filter functions are changed to the commented code (which marks the inputs as invalid unless they match) I would expect both inputs to be valid when the input values match, and invalid otherwise, but this does not happen since the filter functions are only evaluated once.

The use case for this is a password entry form that marks the input fields as invalid until they match.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
