### ISSUE TITLE
Calling this.super() from outside extended methods scope.

### ISSUE THREAD

**Issue by domderen** [Polymer/polymer#898]
Hi,

I am working on an extension of <core-ajax> element. I am extending the "go" method of the core element, to return a promise that will be resolved on a response from server.

I got it to work, but while implementing it, I had an issue to call 'this.super()' form inside the promise, even though the "this" argument was the representation of my own element (which extends the code-ajax).

By digging though some Polymer code, I assume this is because, I called 'this.super()', from a method, which was a promise callback, and not exactly the extended method. Because of that Polymer was not able to get the name of the method to be called in the super class.

I was able to work around it, as presented here:
https://github.com/domderen/cachable-ajax/blob/master/cachable-ajax.html#L109

But the line:
`that.__proto__.__proto__.go.call(that);`

Seems to be a dirty hack, and I wonder if there is some more standard way of calling the super method of the extended class? Or if not, maybe Polymer should handle it somehow internally?

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
