### ISSUE TITLE
Externs file for use with Closure Compiler

### ISSUE THREAD

**Issue by stevenle** [Polymer/polymer#90]
We're exploring the use of toolkit in our Closure-compiled application. It'd be great if the project maintained externs that would work with Closure compiler.

https://developers.google.com/closure/compiler/docs/api-tutorial3#externs

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
