### ISSUE TITLE
Polyfill for CSS breaks prefix attribute selector

### ISSUE THREAD

**Issue by gweax** [Polymer/polymer#902]
If I have a CSS selector like
```
:host [my-type^="f"]
```
the polyfill converts this to
```
my-element span[my-type="f"]
```

which obviously is wrong. Other attribute selector like the suffix attribute selector however work fine.

See this demo: http://plnkr.co/edit/9QdOAvJHRTJopyrYqiiG?p=preview

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
