### ISSUE TITLE
plans to make the element called Bottom Sheet available in Polymer ?

### ISSUE THREAD

**Issue by teolemon** [Polymer/polymer#903]
Are there plans to make the element called Bottom Sheet available in Polymer ?
It's present in the Angular.js Material Design Implementation, and would be swell for Polymer.
https://material.angularjs.org/#/demo/material.components.bottomSheet

**Comment by Leandro-Andrade** [comment]
No one?
I'm also interested on that.

**Comment by send2cloud** [comment]
+1 !

**Comment by Leandro-Andrade** [comment]
Any updates?

**Comment by DiJi1001** [comment]
+1

**Comment by birkir** [comment]
It's fairly easy to modify the `paper-drawer-panel` to work on the x-axis. Just Do It :+1:

**Comment by ebidel** [comment]
You don't even need drawer panel. This can be doe with a dialog and neon-animations: https://github.com/PolymerElements/neon-animation/issues/77

@tjsavage shall we close if there' no roadmap for this el?

**Comment by ebidel** [comment]
I put together a demo that shows how you can implement a bottom-sheet design: https://googlewebcomponents.github.io/places-app/. Code is here: https://github.com/GoogleWebComponents/places-app

**Comment by tjsavage** [comment]
This issue was moved to PolymerElements/paper-elements#42
