### ISSUE TITLE
Nested templates content gets turned into empty string

### ISSUE THREAD

**Issue by jakemac53** [Polymer/polymer#910]
Example: http://jsbin.com/kuxiho/1/edit?html,output

I noticed this when trying to add some runtime warnings to core-list-dart based on the contents of the template supplied, but I can't actually access the content at all.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
