### ISSUE TITLE
font-roboto does not work with a number of languages written in Latin/Greek/Cyrillic

### ISSUE THREAD

**Issue by jungshik** [Polymer/polymer#912]
roboto.html pulls inthe following: 

//fonts.googleapis.com/css?family=RobotoDraft:regular,bold,italic,thin,light,bolditalic,black,medium&lang=en'

Passing 'lang=en' means that a subsetted version of Roboto with glyphs necessary for English only is returned by Google Web Font. 

As a result, a number of Latin letters with diacritical marks will be missing and even pages in West European languages will have ransom note effects (ASCII latin coming from Roboto while Latin letters with diacritical mark coming from another font on the system). Languages written in Cyrillic and Greek (covered by Roboto) will have the same problem. 

Either 'lang' has to be parameterized so that 'lang' corresponding to the current document language is passed instead of hardcoded 'lang=en' [1] or the full set of Roboto has to be retrieved (yes, it's larger than English-only subset). 

[1] This is not bullet-proof for pages where the contents can change dynamically (with user input such as comments).

**Comment by tjsavage** [comment]
This issue was moved to PolymerElements/font-roboto#9
