### ISSUE TITLE
Data-binding with core-style

### ISSUE THREAD

**Issue by caiowilson** [Polymer/polymer#917]
Edit: Chrome 38
i've just ran into a problem: even inside a core-style, i get some weird results, like so:

background: url({{cursoURL}}'/card01/imgs/envelope.png');

produces :

background: url('..correctPath/asStored/inMyVar/plusExtraString/{{cursoURL}}/card01/imgs/envelope.png');

and

background: url([[myVar]]'/card01/imgs/envelope.png');

produces:

url('..correctPath/asStored/inMyVar/plusExtraString/[[Object object]]/card01/imgs/envelope.png');

template engine or core-style fault? :(

**Comment by tjsavage** [comment]
https://github.com/Polymer/polymer/issues/912
