### ISSUE TITLE
Testing the unbind example, received "Uncaught TypeError: undefined is not a function"

### ISSUE THREAD

**Issue by neilhan** [Polymer/polymer#921]
when testing the example on https://www.polymer-project.org/docs/polymer/template.html
The unbind('bind) gives "undefined is not a function"

...

  var t = document.querySelector('#greeting');
  var model = {
    salutations: { what: 'GoodBye', who: 'Imperative' }
  };
  t.model = model;
    
  function removeGo() {
    t.unbind('bind');
    //t.bind('if',false); // this gives another error.---
  }

**Comment by polpo** [comment]
It looks like `Node.unbind()` was removed in commit Polymer/NodeBind@230d5b218639cd41327e417a71184568c908c330 so either the docs are out of date or `Node.unbind()` should be added back. I certainly would find it useful.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
