### ISSUE TITLE
Error with vulcanized core and paper elements js file

### ISSUE THREAD

**Issue by Joshhughes34** [Polymer/polymer#925]
In relation to this Stackoverflow question:

http://stackoverflow.com/questions/26629641/polymer-vulcanize-core-elements-and-paper-elements-to-one-file

With the latest Polymer (0.5.1) the vulcanized files do not work anymore using the same command.

I get a "Uncaught Element name could not be inferred." error from the generated js file after vulcanizing

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
