### ISSUE TITLE
core-animated Card Chip link making error

### ISSUE THREAD

**Issue by rtexplore** [Polymer/polymer#931]
created some chip and when on tap it opens a card inside that card i have created a link but it not works on mobile it works only on pc laptop even on chrome emulation mode it works but on phone when we tap over the link the card dissolve to chip and no link is opened i have tried on tap onclick window.loaction window.open _blank and slef, window.loaction.herf and many more options and adjustment but non of the worked woks like a charm on pc but nothing happens on mobile

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
