### ISSUE TITLE
Polymer validator

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#932]
_From @gertcuykens on October 22, 2014 23:51_

Would be nice if there was a validator designed for polymer, I know there is a chrome developer plugin in the making, but a validator site would also be nice for troubleshooting, optimization and validating your code.

What should it detect
- Duplicate imports
- Unused imports
- Unknown elements (when you forget a import)
- Unknown attributes  (when you forget to export a attribute)
- Unused attributes (when you forget to assign a binding)
- Unused bindings (when you have a typo in a binding name)
- W3C validation (see errors below)
- ...

example http://validator.w3.org/check?uri=http%3A%2F%2Fsea-is-snow.appspot.com%2F&charset=%28detect+automatically%29&doctype=Inline&group=0

Suggesting new Polymer / validator repository?

(PS Extra tasks for the plugin that a validator site can not do could be things like a console for easy access to custom element bindings and variables like the designer tool does.)

_Copied from original issue: Polymer/docs#718_

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
