### ISSUE TITLE
the `computed` property and `extends`

### ISSUE THREAD

**Issue by mysticatea** [Polymer/polymer#933]
Code: http://jsbin.com/nivoka/1/edit?html,output

When with using `extends`, the `publish` property is merged from the derived element's value and its base element's value.
But the `computed` property is not like so.

I hope, the `computed` property to have a behavior as same as the `publish` property.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
