### ISSUE TITLE
Constrained height drop down menus can't be scrolled by using the scrollbar.

### ISSUE THREAD

**Issue by marekroman** [Polymer/polymer#938]
As soon as you depress LMB while using the scrollbar, the dropdown menu closes. I.e. the only way to scroll the list is to use the scroll wheel. Check it out in the [demo](https://www.polymer-project.org/components/core-dropdown-menu/demo.html) (second to last example).

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
