### ISSUE TITLE
Refused to evaluate a string as JavaScript because 'unsafe-eval' for Chrome Packaged App

### ISSUE THREAD

**Issue by jnicolau** [Polymer/polymer#939]
Hi,

I've been getting an error that was described in this ticket that was closed:
https://github.com/Polymer/polymer/issues/252

It should have been fixed since Jul 7.

I'm running polymer 4.2 on Chrome 38.0.2125.122 (MacOS) with vulcanize.
vulcanize --csp --strip index.html

Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' chrome-extension-resource:".
 polymer.concat.js:4170

Looks like the error begins here:
     var f = new Function('', 'return true;');

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
