### ISSUE TITLE
Paper-item inside core-menu freezes ripple effect item change

### ISSUE THREAD

**Issue by danazkari** [Polymer/polymer#946]
Hello,

I was trying to use `core-menu` and `paper-item` together like this:

```html
<template is="auto-binding">
        <div>In a core-menu ({{route}})</div>
        <paper-shadow>
            <core-menu selected="{{route}}" valueattr="hash">
                <template repeat="{{ item in items }}">
                    <paper-item hash="{{item.hash}}">{{item.description}}</paper-item>
                </template>
            </core-menu>
        </paper-shadow>
        <script>
            var template = document.querySelector('template[is="auto-binding"]');
            template.items = [
                {
                    hash: 'firstPage',
                    description: 'First Page'
                },
                {
                    hash: 'secondPage',
                    description: 'Second Page'
                }
            ];
        </script>
    </template>
```

But the the ripples get stuck when changing from item to item, if I then click the item once more, the ripple effect starts to work correctly.

![image](https://dl.dropboxusercontent.com/u/4662767/core-menu_with_paper-item_ripple_freeze.gif)

Am I using this wrongly?

Here's an [example of it happening](https://gist.github.com/danazkari/a7b8a4165e6636a91adc) inside the very demo.html inside `components/paper-item/`

Please let me know what's going on.

Thanks!

# Update!
If the `core-selector` is populated statically instead of using `<template repeat="{{item in items}}">` then ripple and valueattr work perfectly, the iteration of items is somehow messing with `upAction`. This could be another workaround for other people.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
