### ISSUE TITLE
Need info how to test polymer elements using Selenium.

### ISSUE THREAD

**Issue by karanahuja007** [Polymer/polymer#948]
Hi All,

I have used polymer elements in my project, but when I was automating it using Selenium I feel I was not able to access Shadow Dom objects.
Is there any other alternative to access Shadow DOM objects?

**Comment by nmondal** [comment]
I might be late, very late.
But apparently - polymer stuffs are not changing anything - so as much - Selenium is able to run through it. In [nJexl](https://github.com/nmondal/njexl)  the code is this :  

       	/*
	 Tests the polymer sample :
	 http://1.daily-stock-forecast.appspot.com
	*/
	import 'java.lang.System.out' as out 
	import 'java.lang.Thread' as Thread

	selenium.open("/") ;  ## Open the URL 

	@@selenium.click("search-dialog-button")

	@@selenium.type("symbol_search" , "MSFT\n")

	Thread.sleep(6000)


I can see that the UI is properly automated!

**Comment by letsenzoy** [comment]
Any updates on this?

**Comment by huanleapp** [comment]
Hi 
For clarifying selenium. 
I can run Selenium (firefoxDriver) to get element and control a element i want
But, i can use ChromeDriver for that. 
what is it deference between Firefox and chrome ? are there more way to automation test by Selenium on website's polimer (ex: https://shop.polymer-project.org/)
thanks
