### ISSUE TITLE
paper-input element not working in Chrome on iOS8.1

### ISSUE THREAD

**Issue by lihan** [Polymer/polymer#953]
Open [paper-input demo page](https://www.polymer-project.org/components/paper-input/demo.html) in Chrome on iOS8.1, you will see none of the input control works. This control however works in mobile Safari from iOS 8.1.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
