### ISSUE TITLE
[unresolved] does not work as expected on elements inside auto-binding template

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#963]
Test: http://jsbin.com/yijusuqahe/1/edit?html,output

Both elements should fade in, but only the one outside of the auto-binding does. Presumably this is because `polymer-ready` happens before the template is stamped.

:santa:

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
