### ISSUE TITLE
Template Binding outside polymer-element does not work with 0.8-preview

### ISSUE THREAD

**Issue by tomalec** [Polymer/polymer#966]
I am not sure if it is a bug, I cannot enable some features, or Template Binding feature for templates outside polymer-element's ShadowDOM will be removed in 0.8.

My test case is here http://jsfiddle.net/tomalec/31tLeL37/
```html
<template id="myTempl" bind>
 Hello {{who}}!
</template>
```

Importing additional [features](https://github.com/Polymer/polymer/tree/0.8-preview/src/features) did not help, I have also tried adding them to particular `<template>` node, with no luck.

I hope "The heavyweight binding system will now be opt-in" does not mean it will not be able to support non-polymer templates at all, as many of my apps, and individual Custom Elements (some almost-production) uses it extensively.

**Comment by bigdave** [comment]
@sorvell The example above is using platform/polymer 0.4.2 - should this have the 0.8 label?

**Comment by arthurevans** [comment]
I think this is an 0.8 question. The current answer is that Polymer 0.8 doesn't use the TemplateBinding library or its relatives at all (NodeBind, Object.observe). The TemplateBinding library sets up bindings based on the template, and the nodes themselves interpret the bindings.

0.8 data binding is managed by the host element (custom element). There aren't as many moving parts and the performance is both faster and more predictable. 

Theoretically you could add TemplateBinding-style data binding as a feature on 0.8, but to the best of my knowledge, no one's done so.

That said, the example above doesn't use any Polymer code at all -- uses TemplateBinding and NodeBind, which are available as separate libraries.

**Comment by bigdave** [comment]
Cool - that makes sense.  I was just confused given the example.

**Comment by tomalec** [comment]
We really hope to get TemplateBinding work with Polymer 0.8, so we created small fan-site [TemplateBinding.org](http://templatebinding.org/) to keep TemplateBinging-style hope alive.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
