### ISSUE TITLE
Core-header-panel  Uncaught SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by fredpedro** [Polymer/polymer#969]
When i tried to insert into the scrip tag,

scrollHandler: function(event) {
  var scroller = event.detail.target;
  console.log(scroller.scrollTop);
}

It create an error that says "Uncaught SyntaxError: Unexpected token ("

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
