### ISSUE TITLE
Responsive image doesn't render on page load in Chrome, loads on browser resize or opening of dev tools

### ISSUE THREAD

**Issue by atomikolex** [Polymer/polymer#971]
An img with srcset and sizes attributes inside a polymer template won't render on page load, but only after dev tools are opened.
This bug is limited to Chrome and didn't occur prior to version 39.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
