### ISSUE TITLE
Make it easy to spot missing-import errors

### ISSUE THREAD

**Issue by tommie** [Polymer/polymer#972]
One type of error is fairly common with Polymer; forgetting to import a component definition. In most programming languages, this results in an "undefined" error, but since Custom components allows registering after the fact, there is no clue. And the element is simply rendered as nothing.

It would be nice to have a debug/linting mode where unresolved elements are printed to the console, or highlighted in the DOM somehow. It could be triggered by a timer set at page load to account somewhat for delayed registrations. Or in "polymer-ready". The output would be just a list of unresolved elements (and possibly their source location, if possible.)

BTW, this is somewhat similar to the problem of printing error messages for unhandled exception in Twisted Python's Deferreds... They do it in the destructor, so if nothing has handled the exception, it will likely get shown at some point.

**Comment by samccone** [comment]
@addyosmani @ebidel Does polylint cover this case?

**Comment by tjsavage** [comment]
Yep! github.com/polymerlabs/polylint covers this
