### ISSUE TITLE
Paper Elements Accessibility 

### ISSUE THREAD

**Issue by rodrigoprestesmachado** [Polymer/polymer#974]
Hello,

I was trying to use Polymer in a project but I realize that some Paper Elements does not implement appropriated WAI-ARIA specification. Do you have plans to add this feature in core and paper elements?

Best regards,
Rodrigo

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
