### ISSUE TITLE
Issue with polymer on iOS 8

### ISSUE THREAD

**Issue by MeloJR** [Polymer/polymer#975]
Both Safari and Chrome fail to display a web app written in polymer in an iPhone with iOS 8.

The same web app fails as well when you try to display it using the native browser Apache Cordova launches in its applications.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
