### ISSUE TITLE
Topeka example takes > 30 seconds to load on smartphones

### ISSUE THREAD

**Issue by richieb** [Polymer/polymer#978]
I just tested the latest version of Topeka (on master), and it takes more than 30 seconds to load on both iOS 8 (Safari mobile on iPad) and Android (Note 4, both Chrome and Samsung's browser).

I am about to use Polymer for my next project, but I want to make sure it will load faster than it loading now on smartphones.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
