### ISSUE TITLE
A way to manually recompute computed properties

### ISSUE THREAD

**Issue by thedeeno** [Polymer/polymer#979]
I'm not sure this if this is undocumented or unsupported. 

Given this custom element

```
Polymer({
  name: 'dane',

  computed: {
    message: 'greet(name)'
  },

  greet: function(name) {
    return 'hello ' + name + Date.now();
  }
})
```

When I change `name` polymer automatically recomputes `message`. Awesome. But is there a way to manually recompute `message` without changing `name`?

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
