### ISSUE TITLE
Polymer text input fields are not registered by "Vimium" as a text input field

### ISSUE THREAD

**Issue by kmelkon** [Polymer/polymer#982]
I'm using Chrome Version 38.0.2125.122 on Ubuntu GNOME 14.10 (64bit), and I have an extension called Vimium for emulating some of Vim functionality in Chrome.

when I'm writing in a text input field the extension stops listening for the specified hotkeys, unless it's a field in the shadow DOM.

Any solution other than disabling the extension on pages using Polymer/web-components?

**Comment by maoswald** [comment]
+1

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
