### ISSUE TITLE
auto assign {{-attribute}} instead of writing  attribute="{{attribute}}"

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#983]
Example 
```<tiedot-service id="service" jwt="{{jwt}}" url="{{url}}" json="{{json}}"></tiedot-service>```

Equals 
```<tiedot-service id="service" {{-jwt}} {{-url}} {{-json}}></tiedot-service>```

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
