### ISSUE TITLE
On android chrome: need to tap paper-input twice to open on-screen-kb

### ISSUE THREAD

**Issue by snickell** [Polymer/polymer#989]
Expected: tapping on a paper-input will bring up the android on screen keyboard
Actual: first tap focuses the paper-input (cursor blinks), but you have to tap a second time to bring up the keyboard

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
