### ISSUE TITLE
cloneNode doesn't clone changed attribute

### ISSUE THREAD

**Issue by shycherry** [Polymer/polymer#990]
Hello Polymer team !
Please take a look at this codepen :
http://codepen.io/anon/pen/LEpBeE

Change the input value, see in the console that element's command attribute is changed.
Click clone : the cloned element's command attribute stay as if it was unchanged.

Why such behavior ?
Thank you !

**Comment by silentHoo** [comment]
+1

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
