### ISSUE TITLE
layout test is broken in FF 34

### ISSUE THREAD

**Issue by jakemac53** [Polymer/polymer#995]
https://github.com/Polymer/polymer/blob/master/test/html/layout.html fails in FF 34, gives `AssertionError: unsized container: vertical flex items have no intrinsic height: expected '19px' to equal '0px'`

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
