### ISSUE TITLE
Computed properties issue

### ISSUE THREAD

**Issue by malekpour** [Polymer/polymer#998]
Computed properties and change detection does not work correctly for nested properties. In the following plunker by commenting line 53 polymer stops updating expression:

http://plnkr.co/edit/PqVWRYSKk3Jcp87wlfZH?p=preview

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
