### ISSUE TITLE
Testing polymer in Intellij IDE Request ID=946019532871517420

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#999]
I tried getting a free Intellij IDE for testing Polymer stuff but only you guys get one :-p This is just to let you know you can have a free license for polymer if interested.

```text
Polymer project qualifies for a free OS license of WebStorm, however we can only issue a license to the project's core team (https://github.com/orgs/Polymer/people). Please feel free to forward this message to them.

Kind regards,
Julia Kuznetsova
Community Support Coordinator
```

I already found some things that can be improved I am sure you can add a ton more things they can improve.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
